Flash shell migrate commands to new shell
zephyrproject-rtos/zephyr pull request #10019
Opened 2018-09-17 11:54 UTC by jarz-nordic

As the new shell is still a PR, this one contains commits from it #9362 so please only review changes in last commit.

Fixes #8883

2018-09-20 06:45 UTC, nordic-krch requested changes

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_SHELL(shell, "flash_erase: %d\r\n", ret);
ret != 0 indicates error. this should be PR_ERROR. Message should be something like "flash_erase failed (err:%d)."

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_ERROR(shell, "flash_write_protection_set: %d (can't"
here message is misleading, better would be "Failed to disable flash protection (err: %d)."

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_ERROR(shell, "flash_write_protection_set: %d (can't"
"Failed to enable flash protection (err: %d)."

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_ERROR(shell, "flash_write_protection_set: %d (can't"
here, also messages could be improved.

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_SHELL(shell, "flash_write: %d\r\n", ret);
PR_ERROR

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +	printk("\tPage %u: start 0x%08x, length 0x%lx (%lu, %lu KB)\r\n",
you can extend struct page_layout_data to have shell handler and use PR_SHELL() here. Even though it is called callback, it is executed in the context of shell command so no worries about using shell_fprintf.

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +#define PR_SHELL(shell, fmt, ...)				\
maybe that could be simple PR()

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_SHELL(shell, "flash_page_info_by_idx: %d\r\n", ret);
PR_ERROR and improve message.

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +			PR_SHELL(shell, "flash_get_page_info_by_idx:"
PR_ERROR and improve message

2018-09-20 06:45 UTC, nordic-krch commented on samples/drivers/flash_shell/src/main.c
> +		PR_SHELL(shell, "flash_get_page_info_by_idx: %d\r\n", ret);
PR_ERROR

2018-09-20 06:48 UTC, nordic-krch commented
Apart from review i have one suggestion. Why not move those commands out from sample to /drivers/flash folder and add kconfig option to enable shell commands for flash driver. Sample would just enable those.

2018-10-04 10:09 UTC, jarz-nordic commented
@nordic-krch : done

2018-10-09 08:27 UTC, nordic-krch approved these changes

2018-10-09 08:36 UTC, carlescufi approved these changes

2018-10-09 11:22 UTC, merged