Olimex stm32 p405
zephyrproject-rtos/zephyr pull request #1007
Opened 2017-08-04 15:38 UTC by lowlander

A new board package for a Olimex P405 board.

2017-08-04 16:01 UTC, lowlander commented
@dbkinder I have a small error (some wrong pin names) in the docs,  I'll wait with pushing until your review, so I can push possible change requests in one go.

2017-08-04 20:14 UTC, dbkinder commented on boards/arm/olimex_stm32_p405/doc/olimex_stm32_p405.rst
> +More information about the board can be found at the
Following the template, let's add the hardware section title before this paragraph:

    Hardware
    ********

    Information about the board can be found at the

2017-08-04 20:16 UTC, dbkinder commented on boards/arm/olimex_stm32_p405/doc/olimex_stm32_p405.rst
> +=========================
following the template, change the underline here to ***** (for an h2 heading)

2017-08-04 20:18 UTC, dbkinder commented on boards/arm/olimex_stm32_p405/doc/olimex_stm32_p405.rst
> +-------------------------------------------
... and use ====== here for an h3 heading

2017-08-04 20:19 UTC, dbkinder commented on boards/arm/olimex_stm32_p405/doc/olimex_stm32_p405.rst
> +You should see the following message:
After you get minicom running, do you need to reset the board?

2017-08-04 20:24 UTC, dbkinder commented on boards/arm/olimex_stm32_p405/doc/olimex_stm32_p405.rst
> ++=======+================================================+
need to have the `+` column indicator on the heading/row line, align with the previous `|`

2017-08-04 20:27 UTC, dbkinder requested changes
a few formatting fixes on the doc

2017-08-05 09:28 UTC, lowlander commented
@dbkinder I applied the same docu fixes to the Olimex_stm32_e407 board, I hope you don't mind. I didn't want to open another PR for just the small doc update. And E407 is almost the same as P405.

2017-08-05 13:00 UTC, dbkinder submitted a review, later dismissed
+1 for docs (thanks for helping keep our documentation up to date!)

2017-08-09 14:05 UTC, lowlander commented
@galak  ping

2017-08-09 19:24 UTC, galak approved these changes

2017-08-09 19:24 UTC, merged