tests: sched: Use SCHED_MULTIQ for native posix platform
zephyrproject-rtos/zephyr pull request #10131
Opened 2018-09-20 13:26 UTC by ajaykish

To improve the code coverage on native posix, adding CONFIG_SCHED_MULTIQ
for scheduler api tests.

Extracting a separate prj_native_posix.conf file for the scheduler test,
which validates the "multi queue" scheduler on native posix.

Signed-off-by: Ajay Kishore <ajay.kishore@intel.com>

2018-09-20 15:32 UTC, nashif requested changes

2018-09-20 15:32 UTC, nashif commented on tests/kernel/sched/schedule_api/testcase.yaml
> +    min_ram: 20
I am sure you do not need that min_ram here.

2018-09-21 06:40 UTC, ajaykish commented
@nashif Removed the min_ram from testcase.yaml

2018-09-21 12:50 UTC, nashif approved these changes

2018-09-21 12:50 UTC, merged