sensors:am2320: add support for AM2320
zephyrproject-rtos/zephyr pull request #1016
Opened 2017-08-07 09:13 UTC by tidyjiang8

Add initinal support for AM2320 Temperature and Humidity sensor.
Tested with frdm_k64f.

Signed-off-by: Tidy Jiang <tidyjiang@163.com>

2017-08-09 10:29 UTC, bogdan-davidoaia requested changes

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +#define AM2320_I2C_ADDR     0xB8
Keep this define name for the 7bit address and use a different define for 7+1bit. This way you don't need a shift for each i2c_write.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	 * Send START + ADDRESS(0xA8) signal to wake up AM2320.
The value of the define is 0xB8, why is it 0xA8 here?

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	buf[0] = 0x03;
Use defines for these values.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +					drv_data->temp, drv_data->humidity);
Fixa alignment.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	crc = buf[7] * 256 + buf[6];
Use << 8 rather then * 256.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +				CONFIG_AM2320_I2C_MASTER_DEV_NAME);
Fix alignment.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +		NULL, POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY);
Fix alignment.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	i2c_write(drv_data->i2c, buf, 1, AM2320_I2C_ADDR >> 1);
Are you sure this is needed? The start + address signal mentioned in the datasheet are included when doing an i2c_write.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +		val->val2 = drv_data->temp % 10;
val2 should be in micro, so val2 = temp % 10 * 100000

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +		val->val1 = drv_data->humidity / 10;
Humidity should be in milli percent, so val1 = humidity * 100 and val2 = 0.

2017-08-09 10:29 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	/* Step 0: clean stored old data. */
No other driver clears the previous sample if a fetch error occurs, so you don't need to do this.

2017-08-09 13:24 UTC, tidyjiang8 commented on drivers/sensor/am2320/am2320.c
> +	i2c_write(drv_data->i2c, buf, 1, AM2320_I2C_ADDR >> 1);
Yes, you are right, it is included in i2c_write. But I still can't find a way to wake up AM2320.
I tested with sampes/sensor/hts221 just now, if I uncomment this, application can only successfully fetch data once, and then failed the next time. Do you have any good idea?

2017-08-11 07:15 UTC, bogdan-davidoaia commented on drivers/sensor/am2320/am2320.c
> +	i2c_write(drv_data->i2c, buf, 1, AM2320_I2C_ADDR >> 1);
You are right, the datasheet does state that you need to explicitly wake up the chip fist. Initially I though that it was done by the implicit address sent by the i2c_write.

So you can leave the way you had in the first version. Sorry for the confusion.

2017-08-11 07:17 UTC, bogdan-davidoaia approved these changes

2017-08-11 14:43 UTC, MaureenHelm requested changes
Please add a build test for this driver in another commit. Probably can add to `tests/drivers/build_all/sensors_a_m.conf`

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +	__ASSERT_NO_MSG(chan == SENSOR_CHAN_TEMP || SENSOR_CHAN_HUMIDITY);
This should be
```c
__ASSERT_NO_MSG((chan == SENSOR_CHAN_TEMP) || (chan == SENSOR_CHAN_HUMIDITY));
```

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +		val->val1 = drv_data->temp / 10;
Please add a comment that describes what units you are converting from and to. Same for humidity

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +DEVICE_INIT(am2320, CONFIG_AM2320_NAME, am2320_init, &am2320_driver,
use `DEVICE_AND_API_INIT` instead and remove line 143

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +int am2320_init(struct device *dev)
this should be static

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +struct am2320_data am2320_driver;
this should be static

2017-08-11 14:43 UTC, MaureenHelm commented on drivers/sensor/am2320/am2320.c
> +static u16_t am2320_crc16(u8_t *ptr, unsigned int len)
Can you use `include/crc16.h` instead?

2018-05-28 21:00 UTC, nashif commented
outdated, closing. Reopen with updates/rebase if needed.

2018-05-28 21:00 UTC, closed without merging