scripts: update to latest west
zephyrproject-rtos/zephyr pull request #10167
Opened 2018-09-23 14:22 UTC by mbolivar

Now that the multi-repo West functionality is ready for wider testing, we need to tweak the launcher scripts so that they can detect whether the zephyr tree is part of a multi-repo installation, and run the west code in its own repository if that is the case.

Do the needful, preserving compatibility with monorepo installations.

2018-09-24 07:55 UTC, carlescufi approved these changes
Tested locally

2018-09-24 08:14 UTC, carlescufi commented
recheck

2018-09-24 15:00 UTC, carlescufi requested changes
NACKing until we sort a recently discovered issue

2018-09-24 15:17 UTC, mbolivar commented on scripts/west-launcher.py
> +        topdir = find_west_topdir(os.getcwd())
This os.getcwd() should be __file__. I'm also working on emitting a message when this script is being run from a "monorepo" Zephyr (i.e. a zephyr tree outside of a multi-repo west installation) with the west bootstrapper installed on the system.

2018-09-24 22:18 UTC, mbolivar commented
> NACKing until we sort a recently discovered issue

Ready for retesting

2018-09-24 22:43 UTC, mbolivar commented
> Ready for retesting

@carlescufi --- but as discussed, we can't merge unless https://github.com/zephyrproject-rtos/west/pull/50 is OK as-is, since that's where this west came from. If west 50 needs changes, this will too.

2018-09-24 23:39 UTC, mbolivar commented
(I see the docs now fail to build; looking into it)

2018-09-25 08:53 UTC, carlescufi approved these changes
Retested locally

2018-09-25 09:01 UTC, carlescufi commented
@mbolivar there's a doc issue:
```
WARNING: autodoc: failed to import module 'west.runners.core' the following exception was raised:
No module named 'runners'
```

2018-09-25 15:51 UTC, merged