samples: net: sockets: Update docs with TLS information
zephyrproject-rtos/zephyr pull request #10211
Opened 2018-09-25 12:33 UTC by rlubos

Update documentation of socket samples that support TLS with information
on how to enable it.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2018-09-25 23:05 UTC, dbkinder requested changes

2018-09-25 23:05 UTC, dbkinder commented on samples/net/sockets/http_get/README.rst
> +   :zephyr-app: samples/net/
Probably:

    :zephyr-app: samples/net/sockets/http_get

2018-09-25 23:05 UTC, dbkinder commented on samples/net/sockets/http_get/README.rst
> +Certificate used by the sample can be found in the ``src`` directory. The
Change to:

    The certificate used by the sample can be found in the sample's ``src`` directory.

2018-09-25 23:05 UTC, dbkinder commented on samples/net/sockets/http_get/README.rst
> +the sample (https://google.com). In order to access different webpage over TLS
Change to:

    To access a different web page over TLS, provide an appropriate certificate to
    authenticate to that web server.

2018-09-26 12:27 UTC, rlubos commented
@dbkinder Thank you for the feedback, I've addressed your comments.

I had a doubt about one comment, please check if slightly modified proposal is fine.

2018-09-26 12:59 UTC, dbkinder approved these changes
doc changes look good, thanks.

2018-09-26 13:33 UTC, rlubos commented
recheck

2018-09-26 15:13 UTC, merged