subsys: console: Split serial tty handling to a separate module
zephyrproject-rtos/zephyr pull request #10247
Opened 2018-09-26 18:12 UTC by pfalcon

Before going further for API refactoring in console subsys, makes
sense to split "tty" implementation from "console" implementation,
to make it clearer that "console" is just a "tty" instantiated on
a particular UART device.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

2018-09-26 18:16 UTC, pfalcon commented
> Before going further for API refactoring in console subsys

For reference, this API refactoring would be switching to POSIX read()/write() methods, as was discussed previously with @andrewboie .

Another task would be switching to @nordic-krch's byte ring_buf https://github.com/zephyrproject-rtos/zephyr/pull/9853

2018-10-02 10:09 UTC, pfalcon commented
@nordic-krch : Could you have a look here please? Should be easy review, just code moved around (well, a couple of typecast fixes too).

2018-10-02 10:56 UTC, nordic-krch requested changes

2018-10-02 10:56 UTC, nordic-krch commented on include/console.h
> +int tty_putchar(struct tty_serial *tty, u8_t c);
what value it returns?

2018-10-02 10:56 UTC, nordic-krch commented on subsys/console/tty.c
> +	if (rx_next >= tty->rx_ringbuf_sz) {
new line after variable declaration.

2018-10-02 10:56 UTC, nordic-krch commented on subsys/console/tty.c
> +	k_sem_take(&tty->rx_sem, K_FOREVER);
i guess we can assume thatit is never called from isr?

2018-10-02 11:40 UTC, nordic-krch approved these changes

2018-10-03 14:40 UTC, carlescufi approved these changes

2018-10-03 14:40 UTC, merged