arch: arm: fix K_MEM_PARTITION_IS_WRITABLE definition
zephyrproject-rtos/zephyr pull request #10282
Opened 2018-09-28 10:03 UTC by ioannisg

In ARMv8-M MPU it is not possible to have the following access
permissions: Privileged RW / Unprivileged RO. So we define
K_MEM_PARTITION_IS_WRITABLE macro separately for v8M and v7M MPU
architectures (in the separate include files).

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2018-09-28 11:49 UTC, pizi-nordic approved these changes

2018-09-28 12:02 UTC, ioannisg commented
FYI, @pizi-nordic and @agross-linaro 
>In ARMv8-M MPU it is not possible to have the following access
permissions: Privileged RW / Unprivileged RO.

Please check this in the ARMv8-M Architecture Reference Manual, page D-1063:
"D1.2.150 MPU_RBAR, MPU Region Base Address Register"

2018-10-01 08:13 UTC, ioannisg commented
@agross-linaro could you take a quick look?

2018-10-02 18:00 UTC, galak requested changes
Do we need to fixup samples/mpu/mem_domain_apis_test/src/main.c & tests/kernel/mem_protect/mem_protect/src/mem_domain.c for armv8m?

2018-10-02 18:06 UTC, ioannisg commented
>Do we need to fixup samples/mpu/mem_domain_apis_test/src/main.c & tests/kernel/mem_protect/mem_protect/src/mem_domain.c for armv8m?

Yes, I think so.

2018-10-02 18:08 UTC, ioannisg commented
@galak those samples won't compile for ARMv8m as is. However, we still have no v8m board available in the tree.

2018-10-03 13:59 UTC, galak commented
> @galak those samples won't compile for ARMv8m as is. However, we still have no v8m board available in the tree.

Will they break when we have an in tree board and enable the support?  Can we at least put some handling for ARMv8m in those tests/samples?

2018-10-03 14:34 UTC, ioannisg commented
> 
> 
> > @galak those samples won't compile for ARMv8m as is. However, we still have no v8m board available in the tree.
> 
> Will they break when we have an in tree board and enable the support? Can we at least put some handling for ARMv8m in those tests/samples?

Yes, @galak , I can do that. I will push the patches in this PR and ping you back.

2018-10-03 21:48 UTC, agross-oss approved these changes
this looks good to me

2018-10-08 19:15 UTC, ioannisg commented
@galak , I pushed a second commit to select special access permissions for v8m MPU (as we already have for x86, actually) 
Please, re-review.

2018-10-09 23:33 UTC, galak approved these changes

2018-10-09 23:33 UTC, merged