doc: addition of a code of conduct
zephyrproject-rtos/zephyr pull request #10364
Opened 2018-10-04 00:59 UTC by Thea-Aldrich

This change adds a Code of Conduct based on
https://www.contributor-covenant.org/. Additional reporting and
enforcement guidelines will be added at a later date.

Signed-off-by: Thea Aldrich <aldrich.thea@gmail.com>

2018-10-04 16:32 UTC, dbkinder submitted a review, later dismissed

2018-10-04 16:32 UTC, dbkinder commented on CODE_OF_CONDUCT.rst
> +report the incident please contact us at info@zephyrproject.org.
The project "sanitycheck" has some rules about file changes that enforce good habits. One was caught here: trailing white space is not allowed, there are a couple of spaces at the end of this line you should delete, reported by https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/23650/5/tests

2018-10-08 20:15 UTC, nashif commented
> This change adds a Code of Conduct based on contributor-covenant.org. Additional reporting and enforcement guidelines will be added at a later date.

I would add that as is, the issue with enforcement was related to the original proposal wrt to the 3 strike enforcement. This one here is acceptable I guess.

2018-10-16 14:58 UTC, nashif commented
@Thea-Aldrich ping

2018-10-17 02:49 UTC, nashif commented
> Additional reporting and
> enforcement guidelines will be added at a later date.

@Thea-Aldrich can you please add https://www.contributor-covenant.org/version/1/4/code-of-conduct.md as is, I think we should adopt it without changes.

2018-11-23 16:33 UTC, nashif approved these changes

2018-12-06 22:29 UTC, nashif requested changes

2018-12-06 22:29 UTC, nashif commented on CODE_OF_CONDUCT.rst
> +reported by contacting the project team at [INSERT EMAIL ADDRESS]. All
Can you add 2 names here, mine and Kate's as agreed on in the F2F meeting

2019-01-18 17:06 UTC, nashif commented
Can this be updated please?

2019-01-19 19:15 UTC, nashif approved these changes

2019-01-24 19:12 UTC, merged