fs: fat_fs: Implement fs_rename API
zephyrproject-rtos/zephyr pull request #10555
Opened 2018-10-12 16:02 UTC by psidhu

fat_fs was missing this API call so I've implemented it.  The call clobbers the destination path as per the fs.h API definition.

2018-10-16 14:40 UTC, nashif requested changes
We need a test, add one into 

tests/subsys/fs/fat_fs_api

2018-10-16 20:20 UTC, psidhu commented
@nashif Done. I'm not sure what CI is failing on, however.

2018-11-02 16:14 UTC, psidhu commented
@nashif ping

2018-11-02 16:15 UTC, nashif approved these changes

2018-11-02 16:21 UTC, merged