Bluetooth: controller: Add packet transmit time restrictions
zephyrproject-rtos/zephyr pull request #1058
Opened 2017-08-09 13:47 UTC by cvinayak

Add implementation to support PHY update procedure with
packet transmit time restrictions.

This fixes:
TP/CON/SLA/BV-49-C [Initiating PHY Update Procedure Packet
Time Restrictions]
TP/CON/SLA/BV-50-C [Responding to PHY Update Procedure
Packet Time Restrictions]
TP/CON/SLA/BV-52-C [Initiating PHY Update Procedure Packet
Time Restrictions, No Change]
TP/CON/SLA/BV-53-C [Responding to PHY Update Procedure
Packet Time Restrictions, No Change]
TP/CON/MAS/BV-49-C [Initiating PHY Update Procedure Packet
Time Restrictions]
TP/CON/MAS/BV-50-C [Responding to PHY Update Procedure
Packet Time Restrictions]
conformance tests in LL.TS.5.0.0.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2017-08-09 14:30 UTC, carlescufi requested changes

2017-08-09 14:30 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +	if (phys & BIT(2)) {
would it be worth using a look-up table here instead of the succession of if() statements?

2017-08-09 14:30 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		default:
add fall-through comment, will be required in GCC 7

2017-08-09 14:30 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +			max_tx_octets = conn->max_tx_time >> 3;
maybe a comment about the magic of converting time to octets depending on PHY?

2017-08-09 14:30 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +	pdu_ctrl_tx->payload.llctrl.ctrldata.length_rsp.max_rx_time =
same, comment on the magic to convert from octets to time for each phy

2017-08-10 07:42 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +	pdu_ctrl_tx->payload.llctrl.ctrldata.length_rsp.max_rx_time =
@carlescufi fix using a macro to calculate octets to time

2017-08-10 07:47 UTC, carlescufi approved these changes

2017-08-10 07:54 UTC, jhedberg approved these changes

2017-08-10 07:54 UTC, merged