build: do not rename elf file, copy it
zephyrproject-rtos/zephyr pull request #10643
Opened 2018-10-16 14:56 UTC by nashif

We break dependency if we rename the zephyr.elf file, we should keep it
as it is an essential dependency in the build system. Instead, copy the
file.

Fixes #10639

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2018-10-16 15:13 UTC, SebastianBoe approved these changes

2018-10-16 15:20 UTC, SebastianBoe commented
We still need a dependency from the "run" target to the ".exe" file ...

2018-10-16 15:33 UTC, SebastianBoe commented
@nashif : To continue to have logical_target_for_zephyr_elf mean "the final executable", we can change the suffix of the elf file instead of copying/renaming it.

This approach can be seen here: https://github.com/SebastianBoe/zephyr/commit/0c72c82fdad67bef68cc6ecaa0d9c9a170ffcae0

2018-10-16 15:34 UTC, SebastianBoe requested changes
We still need a dependency from the "run" target to the ".exe" file.

2018-10-19 07:50 UTC, SebastianBoe commented
> We still need a dependency from the "run" target to the ".exe" file.

This is wrong. It is safe to depend on a target, when you actually depend on a targets post_build output.

2018-10-19 07:51 UTC, SebastianBoe approved these changes

2018-10-19 09:16 UTC, pfalcon approved these changes
Ok, confirming that this fixes issue I had too.

2018-10-19 11:56 UTC, merged