Convert Atmel SAM0 SPI & UART driver to use dts for sercom pad
zephyrproject-rtos/zephyr pull request #10989
Opened 2018-11-01 10:18 UTC by galak

2018-11-01 11:52 UTC, galak commented
@mnkp @fallrisk do you guys mind doing a review.

2018-11-05 11:37 UTC, mnkp requested changes
This looks good. I have only a minor request regarding comments.

On a side note, the way Atmel designed signal routing / pin assignment in SAM0 family is really confusing. Good example of software unfriendly hardware design. But it looks like they were aware of it as the approach taken in SAM family is much, much better.

2018-11-05 11:37 UTC, mnkp commented on dts/bindings/spi/atmel,sam0-spi.yaml
> +      description: Receive Data Pinout
The datasheet refers to this configuration setting as "Data In Pinout".

2018-11-05 11:37 UTC, mnkp commented on dts/bindings/spi/atmel,sam0-spi.yaml
> +      description: Transmit Data Pinout
Should be "Data Out Pinout".

2018-11-05 12:51 UTC, galak commented on dts/bindings/spi/atmel,sam0-spi.yaml
> +      description: Transmit Data Pinout
Yep, copy paste error, good catch.

2018-11-05 12:52 UTC, galak commented
@mnkp if you can re-review, made fixes to the spi binding file.

2018-11-05 13:26 UTC, mnkp approved these changes

2018-11-05 15:05 UTC, merged

2018-11-19 06:32 UTC, sknsean commented
Breaks UART on atsamd20_xpro :-(

2018-11-19 09:20 UTC, sknsean commented on boards/arm/atsamd20_xpro/board.h
> -	(SERCOM_USART_CTRLA_RXPO_PAD3 | SERCOM_USART_CTRLA_TXPO_PAD2)
SERCOM_USART_CTRLA_TXPO_PAD2  = 1

2018-11-19 09:21 UTC, sknsean commented on boards/arm/atsamd20_xpro/atsamd20_xpro.dts
> +	txpo = <2>;
txpo = <1>;