Add DTS support for NXP Kinetis TRNG/RNGA
zephyrproject-rtos/zephyr pull request #11062
Opened 2018-11-03 12:06 UTC by galak

2018-11-03 23:22 UTC, aurel32 approved these changes
I used this as a basis to implement DTS support in SAM E70 driver. It all looks good to me.

2018-11-06 01:03 UTC, MaureenHelm requested changes

2018-11-06 02:54 UTC, galak commented on drivers/entropy/Kconfig
> +config HAS_DTS_ENTROPY
No reason, forgot about dts/Kconfig :)

2018-11-06 13:46 UTC, galak commented
@MaureenHelm moved the Kconfig option, take another look.

2018-11-06 14:49 UTC, MaureenHelm approved these changes

2018-11-06 14:49 UTC, merged