Add initial support for Silicon Labs EFM32PG-STK3402A board
zephyrproject-rtos/zephyr pull request #11065
Opened 2018-11-03 14:21 UTC by chrta

The following examples are tested:

- hello_world
- basic/blinky
- basic/button
- subsys/shell/shell_module

This continues #7043, which can be closed now.

2018-11-03 14:32 UTC, galak commented on boards/arm/efm32pg_stk3402a/board.h
> +#include <soc.h>
can we remove <soc.h>

2018-11-03 14:32 UTC, galak commented on boards/arm/efm32pg_stk3402a/board.c
> +#include <board.h>
"board.h"

2018-11-03 15:56 UTC, chrta commented on boards/arm/efm32pg_stk3402a/board.h
> +#include <soc.h>
done

2018-11-03 15:56 UTC, chrta commented on boards/arm/efm32pg_stk3402a/board.c
> +#include <board.h>
done

2018-11-08 18:27 UTC, dbkinder approved these changes
+1 for doc addition, thanks.

2018-11-11 11:30 UTC, chrta commented
Added flash support and rebased on current master.

2018-11-15 13:57 UTC, galak requested changes
Need to rework dts_fixup.h for recent CONFIG_ -> DT_ change

2018-11-15 13:58 UTC, galak commented on boards/arm/efm32pg_stk3402a/Kconfig.defconfig
> +	def_bool y
replace def_bool y with 'default y'

2018-11-15 20:11 UTC, chrta commented on boards/arm/efm32pg_stk3402a/Kconfig.defconfig
> +	def_bool y
done

2018-11-21 11:24 UTC, galak approved these changes

2018-11-21 12:21 UTC, galak commented
Can you fixup the missing copyright/license on:

dts/arm/silabs/efm32pg12b.dtsi missing license.
dts/arm/silabs/efm32pg12b.dtsi missing copyright.

I'll chat with @nashif about the zlib license checks.

2018-11-21 12:38 UTC, chrta commented
@galak Ok, i will add this license and copyright info to this file.

2018-11-21 19:12 UTC, chrta commented
@galak @nashif The same licenses are also used in the newest gecko sdk in #11453

2018-11-21 19:20 UTC, galak approved these changes

2018-11-21 19:42 UTC, merged