doc: Add Bluetooth host changes to 1.9 release note
zephyrproject-rtos/zephyr pull request #1108
Opened 2017-08-14 12:47 UTC by Vudentz

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

2017-08-14 12:54 UTC, dbkinder commented on doc/release-notes-1.9.rst
> +* IPSP net-app support
Might expand on this more, something like:

     * IPSP net-app support: a simplified networking API reducing duplication of common
       tasks an application writer has to go through to connect to the network

2017-08-14 12:55 UTC, dbkinder requested changes
a bit more detail would be better for the release notes

2017-08-15 09:09 UTC, Vudentz commented
I incorporate the changes suggested.

2017-08-15 11:31 UTC, jhedberg approved these changes

2017-08-15 11:51 UTC, carlescufi commented
@dbkinder I've added the controller-side release notes. I haven't added more detail in purpose, to align them with the other release notes from other subsystems

2017-08-15 13:35 UTC, nashif approved these changes

2017-08-15 13:35 UTC, merged