drivers: flash: w25q: Make spi_flash_wb_write/read support multiple pages
zephyrproject-rtos/zephyr pull request #11113
Opened 2018-11-05 15:49 UTC by Olivier-ProGlove

Until now `spi_flash_wb_write/read` functions were only supporting buffers that fit into a W25Q page (even if they were not checking the offset was page aligned).

This change allows these functions to read/write across multiple W25Q page.
This change is required as the caller of these functions are not aware of flash page size.

Signed-off-by: Olivier Martin olivier.martin@proglove.de
Signed-off-by: Johannes Hutter johannes@proglove.de
Signed-off-by: Michael Wendland michael@proglove.de

2018-11-08 11:41 UTC, Olivier-ProGlove commented
@nashif Without this PR W25Q cannot be used with NVS and FCB as data are not correctly written. So it is quite high priority fix.

2019-01-02 13:12 UTC, Olivier-ProGlove commented
PR rebased to solve merging conflict.

2019-01-02 14:18 UTC, nvlsianpu requested changes

2019-01-04 15:06 UTC, baw-serafin commented on drivers/flash/spi_flash_w25qxxdv.c
> +	if (lock) {
Would it no be a lot easier to replace the k_sem with a K_mutext which is re-entrant than we don't have to worry if we lock twice we just have to unlock the same amount

2019-01-04 15:43 UTC, nvlsianpu approved these changes

2019-01-06 17:02 UTC, aurel32 approved these changes
I have no way to test this patch, but I have reviewed the code. It looks fine to me.

2019-01-07 21:09 UTC, merged