Bluetooth: Add function to unregister SMP service
zephyrproject-rtos/zephyr pull request #11128
Opened 2018-11-06 07:54 UTC by MariuszSkamra

This adds a possibility to unregister SMP service. Using this function,
device can disable Firmware Update functionality, if not needed.

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

2018-11-06 09:20 UTC, jhedberg commented
Ok, this is confusing. SMP here doesn't mean Security Manager Protocol? Especially when using the other meaning (whatever it is) in combination with Bluetooth, please spell it out instead of using the acronym - otherwise this is just confusing.

2018-11-06 09:20 UTC, jhedberg requested changes
see my earlier comment

2018-11-06 09:33 UTC, MariuszSkamra commented
OK. This might be confusing. I mean Bluetooth service of Simple Management Protocol ^^ I'll change the commit message to avoid confusion.

2018-11-06 20:56 UTC, sjanc commented
yeap, that SMP name is unfortunate.

Lets just name commit "mgmt: Add function to unregister GATT service".
It should be clear enough.

2018-11-07 08:06 UTC, MariuszSkamra commented
@sjanc @jhedberg done

2018-11-07 08:09 UTC, jhedberg approved these changes

2018-11-07 09:24 UTC, carlescufi approved these changes

2018-11-07 11:51 UTC, MariuszSkamra commented
recheck

2018-11-07 12:35 UTC, merged