boards: Update STM32 disco boards default configuration
zephyrproject-rtos/zephyr pull request #11139
Opened 2018-11-06 12:48 UTC by erwango

First batch of patches to address #9247.

Impacted boards:
-stm32l496g_disco
-disco_l475_iot1
-stm32l476g_disco
-stm32f769i_disco
-stm32f723e_disco
-stm32f469i_disco
-stm32f429i_disco

2018-11-06 17:01 UTC, ydamigos requested changes
Looks good. Some minor comments.

2018-11-07 07:53 UTC, erwango commented on boards/arm/stm32f469i_disco/doc/stm32f469i_disco.rst
> +- SPI1 NSS/SCK/MISO/MOSI : PA4/PA5/PA6/PA7 (Arduino SPI)
Fixed

2018-11-07 07:53 UTC, erwango commented on boards/arm/stm32f769i_disco/doc/stm32f769i_disco.rst
> +- SPI1 SCK/MISO/MOSI : PA12/PB14/PB15 (Arduino SPI)
Fixed

2018-11-07 07:53 UTC, erwango commented
@ydamigos , comments fixed. Thanks for the review

2018-11-07 19:00 UTC, dbkinder approved these changes
doc changes look OK.

2018-11-08 19:23 UTC, ydamigos approved these changes

2018-11-08 22:16 UTC, nashif approved these changes

2018-11-08 22:16 UTC, merged