arch: arc: Add mpu support
zephyrproject-rtos/zephyr pull request #1122
Opened 2017-08-15 04:40 UTC by vonhust

* add arc mpu driver
* modify the corresponding kconfig and kbuild
* currently only em_starterkit 2.2's em7d configuration
  has mpu feature (mpu version 2)
* as the minimum region size of arc mpu version 2 is 2048 bytes and
  region size should be power of 2, the stack size of threads
  (including main thread and idle thread) should be at least
  2048 bytes and power of 2
* for mpu stack guard feature, a stack guard region of 2048 bytes
  is generated. This brings more memory footprint
* For arc mpu version 3, the minimum region size is 32 bytes.
* the codes are tested by the mpu_stack_guard_test and stackprot

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

2017-08-15 09:11 UTC, chunlinhan commented on arch/arc/core/mpu/arc_mpu.c
> +		return  AUX_MPU_RDP_REGION_SIZE(
should be
return AUX_MPU_RDP_REGION_SIZE(ARC_FEATURE_MPU_ALIGNMENT_BITS);
or
return AUX_MPU_RDP_REGION_SIZE(_vmpu_region_bits(1 << ARC_FEATURE_MPU_ALIGNMENT_BITS));
?

2017-08-15 09:15 UTC, vonhust commented on arch/arc/core/mpu/arc_mpu.c
> +		return  AUX_MPU_RDP_REGION_SIZE(
Thanks @chunlinhan . It's an error, should be AUX_MPU_RDP_REGION_SIZE(ARC_FEATURE_MPU_ALIGNMENT_BITS);.

I will modify it in the coming commits

2017-08-15 12:24 UTC, ruuddw commented on arch/arc/core/mpu/arc_mpu.c
> +	r_index = num_regions - mpu_config.num_regions;
Please add some explanation here: on use of regions: first 'special type' regions, then static ones from mpu_config struct.

2017-08-15 12:26 UTC, ruuddw commented on arch/arc/core/mpu/arc_mpu.c
> +	for (r_index = 0; i < num_regions; i++) {
add a note that loop over i continues with remaining static items.

2017-08-15 12:27 UTC, ruuddw commented on arch/arc/core/mpu/arc_mpu.c
> +	/* Enable MPU */
I think the default region should be updated here as well (disabled, so addresses not explicitly defined in MPU no longer have the 'everything permitted' reset setting.

2017-08-15 12:35 UTC, ruuddw commented on arch/arc/core/mpu/arc_mpu.c
> +	if (region_index == 0) {
Don't think this check will work, only catches case where total number of regions equals mpu_config regions + 'type' region. Please change into a better check (type < _get_nu,_regions() - mpu_config.num_regions, or something like that)

2017-08-15 12:40 UTC, ruuddw requested changes
Initial MPU support for ARC. Looks mostly ok, see detailed remarks for few improvement suggestions.

2017-08-15 15:24 UTC, andrewboie commented on arch/arc/core/mpu/Kconfig
> +	  Enable Thread Stack Guards via MPU
There are *much* better ways of doing stack checking on ARC, see CONFIG_ARC_STACK_CHECKING.

We need to clearly document that CONFIG_MPU_STACK_GUARD is very, very, sub-optimal configuration and should only be used on those platforms that don't support CONFIG_ARC_STACK_CHECKING.

2017-08-15 15:24 UTC, andrewboie commented on include/arch/arc/arch.h
> + * @brief Declare a toplevel thread stack memory region
these APIS are already documented in kernel.h, please don't copy-paste the documentation here

2017-08-16 03:23 UTC, vonhust commented
The configure of default mpu region is done in arc_core_mpu_enable().
No permissions are given to default mpu region.

From: ruuddw [mailto:notifications@github.com]
Sent: 2017年8月15日 20:28
To: zephyrproject-rtos/zephyr <zephyr@noreply.github.com>
Cc: Wayne Ren <Wei.Ren@synopsys.com>; Author <author@noreply.github.com>
Subject: Re: [zephyrproject-rtos/zephyr] arch: arc: Add mpu support (#1122)


@ruuddw commented on this pull request.

________________________________

In arch/arc/core/mpu/arc_mpu.c<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zephyrproject-2Drtos_zephyr_pull_1122-23discussion-5Fr133177288&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=uIRv5OnfaYG5_34mbrNlSdByDrbpAfi15TvQ5YKDOG8&m=Cj05v7UtZG5E0UNqczlc4gW2wX4Cn05NOtPhfjgvsW8&s=AIhVgvNRNuhTNBFjbGALN3-ly0lu5ptnF5BtxFj4jA8&e=>:

> +    arc_core_mpu_disable();

+

+      for (i = 0; i < r_index; i++) {

+             _region_init(i, 0, 0);

+      }

+

+      /* Configure regions */

+      for (r_index = 0; i < num_regions; i++) {

+             _region_init(i,

+                     mpu_config.mpu_regions[r_index].base

+                     | AUX_MPU_RDB_VALID_MASK,

+                     mpu_config.mpu_regions[r_index].attr);

+             r_index++;

+      }

+

+      /* Enable MPU */

I think the default region should be updated here as well (disabled, so addresses not explicitly defined in MPU no longer have the 'everything permitted' reset setting.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zephyrproject-2Drtos_zephyr_pull_1122-23pullrequestreview-2D56326892&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=uIRv5OnfaYG5_34mbrNlSdByDrbpAfi15TvQ5YKDOG8&m=Cj05v7UtZG5E0UNqczlc4gW2wX4Cn05NOtPhfjgvsW8&s=5fgrLYGqPJCuAikeXKFhpzxHrpNxm8JictLZvHmfAk8&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFB9OzKM8Bmtt-2DGiDTmF97rTn5kZSvVuks5sYY7RgaJpZM4O3LoI&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=uIRv5OnfaYG5_34mbrNlSdByDrbpAfi15TvQ5YKDOG8&m=Cj05v7UtZG5E0UNqczlc4gW2wX4Cn05NOtPhfjgvsW8&s=nzFIE-BeAHRdljdolanzDZvNvRn2pj4D-wUN6GKNLlY&e=>.

2017-08-16 04:04 UTC, vonhust commented on arch/arc/core/mpu/Kconfig
> +	  Enable Thread Stack Guards via MPU
For stack guard,  ARC has more effective way,  i.e., STACK_CHECKING.  But CONFIG_MPU_STACK_GUARD is added here to test the MPU feature.  After I search the zephyr's codes,  it seems MPU_STACK_GUARD is the only place to show MPU's protection.  In the future, it's better to use STACK_CHECKING to do stack protection.

2017-08-16 04:04 UTC, vonhust commented on arch/arc/core/mpu/arc_mpu.c
> +	/* Enable MPU */
The default regions is configured in arc_core_mpu_enable

2017-08-16 09:38 UTC, ruuddw approved these changes

2017-08-16 20:09 UTC, merged