doc: Document some Kconfig best practices and tips
zephyrproject-rtos/zephyr pull request #11282
Opened 2018-11-10 14:34 UTC by ulfalizer

Add a new 'Kconfig tips and best practices' page that covers some
Kconfig best practices, tips, and arcana, like the following:

 - What should be turned into a Kconfig symbol?

 - Best practices and pitfalls for 'select'

 - Factoring out common dependencies

 - Kconfig shorthands

 - Redundant defaults

 - Explanations of various more obscure Kconfig features, like 'imply',
   optional prompts, optional choices, and 'visible if'

Link the new page in the sidebar (under Developer Guides), the
application development primer, and the architecture and board porting
guides.

Perhaps other, more Zephyr-specific information could be added later on
as well, but this is a good start.

Include some other Kconfig-related documentation improvements as well:

 - In the application development primer, give 'CONFIG_FOO=n' as the way
   to set a bool symbol to 'n', instead of '# CONFIG_FOO is not set'.
   That seems to be what people usually do in practice in Zephyr.

   Explain why '# CONFIG_FOO is not set' works as well. There's a
   technical reason for it, related to Make.

 - Mention that the recommended syntax for referencing environment
   variables is now $(FOO) (which uses the Kconfig preprocessor)

 - Mention that the kconfiglib.py docstring has more in-depth
   information about how symbol values are calculated.

2018-11-10 14:34 UTC, ulfalizer commented
CC @dbkinder @carlescufi

2018-11-10 20:03 UTC, dbkinder requested changes
Nice addition, thanks!

2018-11-10 20:03 UTC, dbkinder commented on doc/application/kconfig-tips.rst
> +~~~~~~~~~~~~~~~~~
Use =====‘s for this second level heading.

2018-11-10 20:03 UTC, dbkinder commented on doc/application/kconfig-tips.rst
> +~~~~~~~~~~~~~~~~~~~~~~~
Use =====‘s for this second level heading.

2018-11-10 20:03 UTC, dbkinder commented on doc/application/kconfig-tips.rst
> +~~~~~~~~~~~~~~~~
Use =====‘s for this second level heading.

2018-11-10 20:03 UTC, dbkinder commented on doc/application/kconfig-tips.rst
> +~~~~~~~~~~~~~~~~
Use =====‘s for this second level heading.

2018-11-10 20:03 UTC, dbkinder commented on doc/application/kconfig-tips.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
Use =====‘s for this second level heading.

2018-11-10 20:16 UTC, ulfalizer commented
@dbkinder 
Fixed

2018-11-10 21:52 UTC, dbkinder approved these changes
LGTM, thanks!

2018-11-11 08:49 UTC, aescolar approved these changes
Nice :). At least I, very much welcome this extra kconfig documentation

2018-11-11 08:58 UTC, aescolar commented on doc/application/kconfig-tips.rst
> +   CONFIG_USB_CONSOLE=n
Shouldn't this say CONFIG_CONSOLE=n?

2018-11-11 09:06 UTC, aescolar commented on doc/application/kconfig-tips.rst
> +the same definition is redundant, since is gives the type twice.
since *is* gives =>  it

2018-11-11 09:13 UTC, aescolar commented on doc/application/kconfig-tips.rst
> +      	default 1
should it say `default 0xFF`?

2018-11-11 12:48 UTC, ulfalizer commented on doc/application/kconfig-tips.rst
> +   CONFIG_USB_CONSOLE=n
Oops... fixed

2018-11-11 12:48 UTC, ulfalizer commented on doc/application/kconfig-tips.rst
> +the same definition is redundant, since is gives the type twice.
Fixed

2018-11-11 12:48 UTC, ulfalizer commented on doc/application/kconfig-tips.rst
> +      	default 1
Yup, fixed

2018-11-11 14:01 UTC, merged

2018-11-12 09:39 UTC, carlescufi reviewed
Nice job Ulf. this was merged before I could review, but it looks like a great resource for users.