Build: Build offsets lib as OBJECT instead of STATIC. Use cmake to ge…
zephyrproject-rtos/zephyr pull request #11309
Opened 2018-11-12 16:36 UTC by kapedev

Build offsets lib as OBJECT instead of STATIC. Use cmake to get generated path of lib instead of predefined absolute path

Signed-off-by: Klaus Petersen <klauspetersen@gmail.com>

2018-11-12 16:56 UTC, SebastianBoe requested changes

2018-11-12 16:56 UTC, SebastianBoe commented on CMakeLists.txt
> +  $<TARGET_OBJECTS:offsets>                                                 #                zephyr/CMakeFiles/offsets.dir/arch/xmcu/core/offsets/offsets.c.obj
It's good to see that we can get rid of

 ${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/offsets.dir/arch/${ARCH}/core/offsets/offsets.c.obj

I can approve this if you remove this comment and move some of the PR description text into the commit message text.

2018-11-15 11:56 UTC, SebastianBoe approved these changes

2018-11-16 13:34 UTC, nashif approved these changes

2018-11-16 13:34 UTC, merged