Fixes for stm32l496g_disco
zephyrproject-rtos/zephyr pull request #11316
Opened 2018-11-12 22:43 UTC by gon1332

This PR addresses the following issues:

- LPUART 1 mapping was not correct
- The sublists on the docs did not appear as expected

2018-11-12 23:16 UTC, dbkinder requested changes
Thanks for fixing all those extra indents... one more tweak

2018-11-12 23:16 UTC, dbkinder commented on boards/arm/stm32l496g_disco/doc/stm32l496g_disco.rst
> +  - `STM32L496AG on www.st.com`_
Better would be:
```
More information about STM32L496AG can be found in:

- `STM32L496AG on www.st.com`_
- `STM32L496 reference manual`_

```

2018-11-12 23:31 UTC, dbkinder approved these changes
Nice, thanks.

2018-11-13 10:31 UTC, erwango approved these changes

2018-11-13 12:49 UTC, erwango commented
recheck

2018-11-13 14:03 UTC, gon1332 commented
@erwango It seems that kernel timer api fails one check. It's strange, since my change seems trivial.

2018-11-14 12:34 UTC, erwango commented
recheck

2018-11-14 12:35 UTC, erwango commented
@gon1332 

>@erwango It seems that kernel timer api fails one check. It's strange, since my change seems trivial.

Yeah, I don't know exactly why you'd be the only one impacted.
Can you rebase your change and push again?

2018-11-14 17:07 UTC, merged