boards: arm: Updated Cypress PSoC6 cy8ckit_062_wifi_bt_m0 doc
zephyrproject-rtos/zephyr pull request #11364
Opened 2018-11-14 10:39 UTC by OlegKapshii

Added description how to build, programm and see console output of
hello_world example on cy8ckit_062_wifi_bt_m0 board.

Signed-off-by: Oleg Kapshii <oleg.kapshii@cypress.com>

2018-11-14 11:35 UTC, OlegKapshii commented
There is some error in Shippable, but I do not understand what is wrong here and what should I do: "77144675eacbe65478536e0adc3bf03d737090f2: author email (Signed-off-by: Oleg Kapshii <oleg.kapshii@cypress.com>) needs to match one of the signed-off-by entries"

2018-11-17 07:39 UTC, OlegKapshii commented
@galak Do we need this PR after you have submitted PR with PSoC6 OpenOCD support?

2018-11-19 21:49 UTC, dbkinder requested changes

2018-11-19 21:49 UTC, dbkinder commented on boards/arm/cy8ckit_062_wifi_bt_m0/doc/cy8ckit_062_wifi_bt.rst
> +   $<openocd_path>\bin\openocd -c "source [find interface/cmsis-dap.cfg]" -c "transport select swd" -c "source [find target/psoc6.cfg]" -c "if [catch {program {<zephyr_path>\samples\hello_world\build
Can this be written as this (so the block reads better):

```
$ <openocd_path>\bin\openocd -c "source [find interface/cmsis-dap.cfg]" \
   -c "transport select swd" -c "source [find target/psoc6.cfg]" \
   -c "if [catch {program {<zephyr_path>\samples\hello_world\build\zephyr\zephyr.elf}} ] \
        { echo {** Program operation failed **} } \
        else { echo {** Program operation completed successfully **} }" \
   -c "reset_config srst_only;reset run;psoc6.dap dpreg 0x04 0x00;shutdown"
```

2018-11-19 22:37 UTC, galak commented
> @galak Do we need this PR after you have submitted PR with PSoC6 OpenOCD support?

Yeah, if you are going lets close this PR.

2018-11-20 18:40 UTC, carlescufi commented
@OlegKapshii @pfalcon note that by default the official way of flashing in Zephyr is `ninja flash`, since that is cross-platform, unlike `make`.

2018-11-20 20:11 UTC, galak commented
> Well, I can assure you that it doesn't. For it to work, it should be implemented first. I.e., we want to provided an abstracted and consistent flashing interface for flashing any board. For that, we have "make flash", and you'll see that it now redirects to "west flash". But in the west tool, support for each board needs to be implemented first (hopefully not from scratch, just add needed config I hope - I didn't look into it myself).

I implemented support here:

https://github.com/zephyrproject-rtos/zephyr/pull/11452

2018-11-20 20:35 UTC, pfalcon commented
Oh, cool! Can't keep up with all the stuff happening ;-).

2018-11-21 22:28 UTC, dbkinder approved these changes
+1 for doc changes, thanks.

2018-11-22 01:03 UTC, nashif approved these changes

2018-11-22 01:03 UTC, merged