net: Remove check for k_delayed_work_cancel
zephyrproject-rtos/zephyr pull request #1141
Opened 2017-08-16 10:46 UTC by Vudentz

k_delayed_work_cancel now only fail if it hasn't been submitted which
means it is not in use anyway so it safe to reset its data regardless
of its return.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

2017-08-16 11:29 UTC, pfalcon commented on subsys/net/ip/ipv6.c
> +	k_delayed_work_cancel(&data->send_ns);
I may imagine Coverity won't be happy with this change ;-).

2017-08-16 12:07 UTC, pfalcon commented
Will also conflict with https://github.com/zephyrproject-rtos/zephyr/pull/1130/commits/71f7a0f23fc19dcc43507be598f1acf1c771b502 .

Otherwise, this seems ok in the light of the recent change, but I have the same concern as with this comment: https://github.com/zephyrproject-rtos/zephyr/pull/1130#discussion_r133385619 . It's not related to this change per se, as the same issue existed before. I'm just not sure if this may increase race condition exposure window. For example, commit message says "k_delayed_work_cancel now only fail if it hasn't been submitted". What happens if delayed work started to execute, got preempted, and then k_delayed_work_cancel() got called? Is this not possible?

2017-08-16 12:36 UTC, Vudentz commented
The handler is called only after the K_WORK_STATE_PENDING is cleared:
		
                /* Reset pending state so it can be resubmitted by handler */
		if (atomic_test_and_clear_bit(work->flags,
					      K_WORK_STATE_PENDING)) {
			handler(work);
		}

So nothing will happen if k_delayed_work_cancel is called after this.

2017-08-16 13:44 UTC, Vudentz commented on subsys/net/ip/ipv6.c
> +	k_delayed_work_cancel(&data->send_ns);
Most user of k_delayed_work_cancel don't check the return, it is only really useful to tell the difference if the work has run or not but if we all we care is that it don't get executed that is now guaranteed regardless of the return.

2017-08-17 06:53 UTC, jukkar requested changes
Thanks Luiz, this looks good indeed. As you submitted this one, would you mind fixing the other two delayed work checks in this PR too. Those are found in net_context.c and tcp.c too, namely ack_timer_cancelled and fin_timer_cancelled?

2017-08-22 11:59 UTC, Vudentz commented
@jukkar Ive updated the patch fixing the other instances that you mentioned.

2017-08-23 12:18 UTC, jukkar approved these changes

2017-08-24 16:37 UTC, tyrantlizard77 approved these changes

2017-08-25 19:34 UTC, nashif approved these changes

2017-08-25 19:34 UTC, merged