dts: x86: quark_se_c1000_devboard: Add device tree support
zephyrproject-rtos/zephyr pull request #1142
Opened 2017-08-16 11:56 UTC by SavinayDharmappa

patch add device tree support for develoement board of
quark_se_c1000. Previously pushed patch was flashing binary
at wrong address because of which UART was not working

Jira ZEP:2459

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

2017-08-16 13:54 UTC, nashif requested changes

2017-08-16 13:54 UTC, nashif commented on dts/x86/Makefile
> +dtb-$(CONFIG_BOARD_QUARK_SE_C1000_DEVBOARD)	=	quark_se_c1000_devboard.dts_compiled
what is the reason for having all use CONFIG_BOARD excluding arduino 101 which uses CONFIG_SOC?

2017-08-16 13:54 UTC, nashif commented on dts/x86/quark_se_c1000_devboard.fixup
> +#define CONFIG_UART_QMSI_0_NAME		INTEL_QMSI_UART_B0002000_LABEL
what is this cryptic define using B0002000? where is INTEL_QMSI_UART_B0002000_LABEL defined?

2017-08-16 13:54 UTC, nashif commented on dts/x86/quark_se_c1000_devboard.dts
> +		zephyr,bt-mon-uart = &uart1;
what about serial over USB? did you test that with the board, how can I configure the serial console to go over CDC ACM? See related sample for serial usb in samples/subsys/usb

2017-08-16 13:54 UTC, jukkar reviewed
Note that the Jira comment is in wrong format.
It should be
Jira: ZEP-2459

2017-08-16 15:46 UTC, galak commented on dts/x86/Makefile
> +dtb-$(CONFIG_BOARD_QUARK_SE_C1000_DEVBOARD)	=	quark_se_c1000_devboard.dts_compiled
Agreed, we should be using BOARD not SOC here.

2017-08-16 15:48 UTC, galak commented on dts/x86/quark_se_c1000_devboard.fixup
> +#define CONFIG_UART_QMSI_0_NAME		INTEL_QMSI_UART_B0002000_LABEL
It is generated, the fixup file is meant to map from the generated defines to more "generic" ones that drivers can use.  Eventually the fixup files should go away when we can generate the code/structs directly.

2017-08-18 12:14 UTC, SavinayDharmappa commented on dts/x86/mem.h
> +#elif defined(CONFIG_SOC_QUARK_SE_C1000)
it is bad implementation i will correct it.

2017-08-18 12:15 UTC, SavinayDharmappa commented on dts/x86/quark_se_c1000_devboard.dts
> +		zephyr,bt-mon-uart = &uart1;
I tested it. It is not working. I will correct it and push the changes

2017-08-21 10:31 UTC, SavinayDharmappa commented
@galak  please review this patch

2017-08-23 14:00 UTC, nashif approved these changes

2017-08-23 14:00 UTC, merged