Add dts for STM32L433
zephyrproject-rtos/zephyr pull request #11479
Opened 2018-11-19 10:08 UTC by markusr

The STM32L433 has the same layout than the STM32L433, additionally it
has GPIOD, GPIOE and I2C2.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/10909

2018-11-19 13:00 UTC, erwango reviewed
You need to add your signed-off in the commit message.
Cf: https://docs.zephyrproject.org/latest/contribute/contribute_guidelines.html#dco-sign-off-methods

Then, regarding the change itself, you need to add Kconfig symbols for the new SoC.
You can check following PR as example: https://github.com/zephyrproject-rtos/zephyr/pull/9418

2018-11-19 15:05 UTC, markusr commented
@erwango 
Sorry this is my first pull request. 

As I understand it, there already Kconfig symbols for the L433.

https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/st_stm32/stm32l4/Kconfig.defconfig.stm32l433xx

2018-11-20 09:31 UTC, erwango requested changes
Looking at it in detail, it seems that stm32l433 is a superset of stm32l432 (+I2C2, SPI2, USATRT3, LCD, ..) which is already ported.
Can you get stm32l433 including stm32l432?
Thanks

2018-11-20 11:33 UTC, markusr commented
@erwango 
I don't know if I understood correctly what you mean. 
I updated the stm32l433.dtsi to include the stm32l432.dtsi

2018-11-20 15:43 UTC, erwango commented
@markusr can you squash your changes and push a single commit ?

2018-11-20 16:57 UTC, closed without merging