net: l2: bt: Make 6lowpan/BLE be compatible with Linux by default
zephyrproject-rtos/zephyr pull request #1151
Opened 2017-08-16 20:21 UTC by pfalcon

As https://jira.zephyrproject.org/browse/ZEP-1656 mentions, "RFC 7668
(https://tools.ietf.org/html/rfc7668) is actually quite recent and
there is basically only Zephyr and Linux implementions so far".

And Zephyr manages to have default configuration not compatible
with Linux, which doesn't make sense. Also, the description of
CONFIG_NET_L2_BT_ZEP1656 says that it's required for Linux below
4.10, but without it, kernel 4.10.0 still doesn't work. So, enable
the option by default for the time being.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

2017-08-16 20:26 UTC, pfalcon commented
In addition to what's said in the commit message, I'd like to emphasize again that it's literally impossible for a mere human to setup correct Zephyr config from scratch. Like, you have an existing sample with gazillion of options, it works. You try to enable the same feature in another sample, and short of copying those gazillion unrelated options, you just can't make it work, without going thru the ordeal of enabling opts one by one and reverse-engineering what each of them does (can easily take hours). The same happens everywhere, with any subsystem.

We should have default config which works. Then subsystem geeks should keep an eye on and fix issues without putting burden of mere users.

2017-08-16 20:41 UTC, Vudentz commented
And then 4.12 onwards it doesn't work either since Linux has been fixed. Btw, the IPSP on Linux is not even enabled by default, you have to use debugfs which is not a stable API.

So chances are we will remove ZEP1656 as soon as Linux IPSP is done, or if you prefer I can remove it right away so link-local IPs are always properly setup, though perhaps there is a better alternative that is to enable both old and new link-local IP which may make it work either way.

2017-08-17 06:41 UTC, jukkar reviewed
IMHO this should be left "n" by default. It is only needed when working with "legacy" i.e., pre-4.10 kernel.

2017-08-17 06:46 UTC, jukkar commented
> Also, the description of
> CONFIG_NET_L2_BT_ZEP1656 says that it's required for Linux below
> 4.10, but without it, kernel 4.10.0 still doesn't work.

Do you mean that specifically 4.10.0 does not work but for example 4.10.1 kernel works ok? Note that there has been fixes in later linux kernel versions that will make the IPSP work better. At least I have been able to run IPSP when using kernel version 4.11.

2017-08-17 06:56 UTC, pfalcon commented
> Do you mean that specifically 4.10.0 does not work but for example 4.10.1 kernel works ok?

I'm on 4.10.0-30-generic, and without CONFIG_NET_L2_BT_ZEP1656=y, 6lowpan/BLE doesn't work (no response to ping6). https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/l2/Kconfig#L65 says that that option is required "up to 4.10", which I interpret as "all below 4.10", but as practice shows, 4.10 still has that issue.

As far as I can tell, all relevant samples have CONFIG_NET_L2_BT_ZEP1656=y, so the purpose of this patch is to just set it as a default, so all new samples works without detective work, and that when good times come, it can be changed/removed at one place.

2017-08-17 07:08 UTC, pfalcon commented
> And then 4.12 onwards it doesn't work either since Linux has been fixed.

So, the Kconfig help for the option says it'll b 4.10, now it's 4.12, and maybe in 4.14 it really works as expected.

But I'm on the latest LTS release of a well-known Linux distro (Ubuntu 16.04), and I had to upgrade from Ubuntu 14.04 which ran very happily to me exactly to be able to use IPSP. That upgrade brought bunch of issues to my system, so I acquired BLE IPSP, but lost stability. And with all that, the default kernel for Ubuntu 16.04 is still 4.4. I had to upgrade to testing kernel, that's how I ended up with 4.10.

Summing up: it will be *years* before mere users will end up with 4.12, which (supposedly) fixed 6lowpan+BLE/IPSP. 

> Btw, the IPSP on Linux is not even enabled by default, you have to use debugfs which is not a stable API.

And where that leads us? To long discussions ending with statements like "Linux sucks" or "Bluetooth sucks"? Ain't it better to reward the users who go thru the ordeals (like described above) to setup 6lowpan/BLE support on Linux available to them, by setting the options that work?

> So chances are we will remove ZEP1656 as soon as Linux IPSP is done

Cool, except please treat "done" as "it gets into hands of users".

> or if you prefer I can remove it right away 

Kinda this patch suggests that I'd prefer that it was enabled by default, not removed, to let people actually use it, not run away in awe.

> so link-local IPs are always properly setup, though perhaps there is a better alternative that is to enable both old and new link-local IP which may make it work either way.

If there's a way to support working 6lowpan/BLE automagically on both old and new kernels, please kindly implement it, and enable by default. When time comes, this workaround can be removed altogether, but we'll get *years* of happy usage and Zephyr adoption before that.

However, I may imagine that coding such option may take time, so for 1.9.0 release, I still would suggest to apply this patch. Thanks for consideration.

2017-08-17 07:16 UTC, pfalcon commented
> IMHO this should be left "n" by default. It is only needed when working with "legacy" i.e., pre-4.10 kernel.

What do you mean by "legacy"? Example given above is that the latest non-flicky-support release (aka LTS release) of well-known OS distro is on 4.4. It will be such (the latest) for a year more, and supported (== most people will keep use it) for 4 years more. 4.4 is the *current* kernel, anything above is "bleeding edge", not accessible by (== not supported for) mere users.

Do we build Zephyr for real tasks and real people, or is it an abstract academic project not caring about adoption? We already have low adoption/penetration, shown by low Github star count, anyone brave enough to try Zephyr nonetheless, will be damned to go thru all these issues (so will drop out and tweet "it sucks").

2017-08-17 07:32 UTC, tbursztyka commented
@pfalcon: IPSP on linux does not seem like a broadly adopted feature, yet. As vudentz said "the IPSP on Linux is not even enabled by default, you have to use debugfs which is not a stable API.". :)

Well documented I don't see why it would be a problem to make as jukka commented. On this page https://www.zephyrproject.org/doc/subsystems/bluetooth/bluetooth.html you could have a specific note for Linux compatibility with IPSP. What do you think?

2017-08-17 07:35 UTC, pfalcon commented
> IPSP on Linux is not even enabled by default, you have to use debugfs which is not a stable API.

A bit more of timeline: according to https://devzone.nordicsemi.com/blogs/663/6lowpan-for-bluetooth-low-energy-on-openwrt/, bluetooth_6lowpan appeared in 3.17, which is according to https://kernelnewbies.org/LinuxVersions , was released  5 October, 2014. So, BLE 6lowpan "not enabled by default" and "uses debugfs" for close to 3 years. That should give an idea of timescale which will be required to actually adopt it to wide user base, once it finally ready (people are very slow and conservative).

2017-08-17 07:39 UTC, pfalcon commented
>  IPSP on linux does not seem like a broadly adopted feature, yet.

In my previous comment, it's timed that this "yet" has been happening for 3 years now. The outcome would be that without driving adoption, it may "never" happen (happen too late due to momentum lost, and by the lack of momentum being permanently broken).

> On this page https://www.zephyrproject.org/doc/subsystems/bluetooth/bluetooth.html you could have a specific note for Linux compatibility with IPSP. What do you think?

Why not make it work by default with the real-world Linux, given that the Linux is about the only choice with which Zephyr can talk it (6lowpan/ble), and real-world people run real-world Linux, which is 3.high and 4.low-low?

2017-08-17 07:55 UTC, tbursztyka commented
I did not want to go into that adoption path, I see your point but that's another debate: as devs we all work on techs that are sometimes more than a decade old, and yet to be adopted anywhere.

That said, people using ble/ipsp are most likely going to be devs. Hard to tell if they use latest kernel or distro's stable release.

Either way, documenting this Linux/IPSP compat thingy would be good, a bold dot "Beware" about it, whether your new option is no or yes by default.

2017-08-17 10:25 UTC, pfalcon commented
> Either way, documenting this Linux/IPSP compat thingy would be good, a bold dot "Beware" about it, whether your new option is no or yes by default.

I'm all for adding more documentation, including mentioning known issues if they're multiyear-persistent. I'm not sure however that adding it to https://www.zephyrproject.org/doc/subsystems/bluetooth/bluetooth.html would look good - that seems like a clean generic page with features list. It might be better to add it to the specific page of https://www.zephyrproject.org/doc/samples/bluetooth/ipsp/README.html . I'm still not sure about formulation of the warning (e.g. if we accept this patch, then even a warning is optional), but I'm actually extending that page with a detailed walkthru on setting up and diagnosing 6lowpan/ble connection, so we can discuss that in the review to be submitted.

2017-08-17 14:24 UTC, Vudentz commented
Ive been trying to make both only an new Linux with a unified configuration, unfortunately, it doesn't seems possible as the link-address announced over neighbor discover are broken, has ff:fe embedded, we cannot disable the pointopoint flag but if we don't then Linux 4.12 and later cannot use it either. IMO without neighbor discover we can't really use it on production.

2017-08-17 14:26 UTC, Vudentz requested changes
If you want to default this on some board or .conf I won't oppose.

2017-09-19 06:16 UTC, pfalcon commented
Kinda truly superseded by https://github.com/zephyrproject-rtos/zephyr/pull/1537

2017-09-19 06:16 UTC, closed without merging