Spi api fix
zephyrproject-rtos/zephyr pull request #11628
Opened 2018-11-23 18:01 UTC by rgundi

drivers: flash: spi_nor: Correct the return values for R/W

Fixed the return values for read and write APIs for spin_nor.c which were not inline with what the corresponding interfaces were meant to return.

Signed-off-by: Rajavardhan Gundi <rajavardhan.gundi@intel.com>

2018-11-23 21:42 UTC, sathishkuttan requested changes

2018-11-23 21:42 UTC, sathishkuttan commented on drivers/flash/spi_nor.c
>  err:
Why not return the error code returned by `spi_nor_cmd_addr_read` and adding a `SYNC_UNLOCK()`?

2018-11-23 21:42 UTC, sathishkuttan commented on drivers/flash/spi_nor.c
> +	if (((u8_t *)dest - p_dest) == size_req) {
no need for the `if-else` when a return is added upon error returned by `spi_nor_cmd_addr_read`

2018-11-23 21:42 UTC, sathishkuttan commented on drivers/flash/spi_nor.c
> +	if (((u8_t *)src - p_src) == size_req) {
Same comments as above for `spi_nor_read`

2018-11-24 04:55 UTC, rgundi commented
@sathishkuttan Addressed your comments.

2018-11-24 05:15 UTC, sathishkuttan approved these changes
LGTM

2018-11-24 10:27 UTC, vanwinkeljan approved these changes

2018-11-24 12:57 UTC, nashif approved these changes

2018-11-24 12:58 UTC, merged