drivers: adc: deprecate adc_enable/adc_disable functions
zephyrproject-rtos/zephyr pull request #1167
Opened 2017-08-17 12:27 UTC by mnkp

adc_enable/adc_disable functions are no more required. Power management
should be done via Zephyr Power Management Subsystem API.

This commit marks the two functions as deprecated and removes them
from the test suite.

Jira: ZEP-2550
Signed-off-by: Piotr Mienkowski <piotr.mienkowski@gmail.com>

2017-08-17 12:31 UTC, tbursztyka approved these changes

2017-08-17 13:26 UTC, galak requested changes
I think we should leave the testsuite alone until users of adc_enable/adc_disable are converted over.  Looks like adc_dw, adc_qmsi, and adc_qmsi_ss need changes.

2017-08-17 13:36 UTC, tbursztyka commented
isn't is sot hat deprecated api, if used in a test, will make this built failing? (used to be that way when we were on gerrit if I remember correctly)

2017-08-17 15:07 UTC, nashif commented
> I think we should leave the testsuite alone until users of adc_enable/adc_disable are converted over. Looks like adc_dw, adc_qmsi, and adc_qmsi_ss need changes.

I do not see this being used in any of the drivers.

2017-08-17 16:50 UTC, mnkp commented
>> I think we should leave the testsuite alone until users of adc_enable/adc_disable are converted over. Looks like adc_dw, adc_qmsi, and adc_qmsi_ss need changes.

> I do not see this being used in any of the drivers.

@galak is right, adc_dw, adc_qmsi, adc_qmsi_ss drivers need to be reworked. It is well possible that after this PR is applied the adc testcases for these drivers will fail.

I still removed adc_enable/adc_disable functions from testcases because:
- I assumed we shouldn't test deprecated functionality
- if left, we force any new drivers to implement these deprecated functions (we plan to send a PR with Atmel SAM ADC driver in the next few days).
- by having a testcase fail we would know which adc drivers need to be reworked. In CI tests we only build testcases so it doesn't influence the outcome anyway.

But maybe my assumptions were wrong.

Apart from testsuite adc_enable function is called by the following drivers:
- drivers/grove/light_sensor.c
- drivers/grove/temperature_sensor.c

I didn't remove these calls as it could break the functionality for those who rely on adc_dw, adc_qmsi, adc_qmsi_ss drivers.

2017-08-22 14:45 UTC, mnkp commented
So, what should we do about this PR?

2017-08-22 15:12 UTC, nashif commented
> So, what should we do about this PR?

we need to move the existing drivers to the new API and remove usage of enable/disable.

2017-08-22 20:29 UTC, mnkp commented
> we need to move the existing drivers to the new API and remove usage of enable/disable.

Does it mean that we should deprecate enable/disable functions only after the existing drivers are reworked? If that's the case should I close this PR, should we keep it in the backlog for the time being? This PR is marked with 1.9 milestone. This is probably not valid anymore.

Is there someone willing to do the job and update the drivers? Unfortunately I don't have any Intel or ARC boards so I can't do it myself.

2017-08-23 14:39 UTC, nashif commented
yes, lets do that after 1.9

2018-02-20 17:17 UTC, nashif commented
this should be obsoleted by #6176

2018-04-21 13:14 UTC, nashif commented
obsoleted by #6176

2018-04-21 13:14 UTC, closed without merging