x86: MMU: Miscellaneous macros related to MMU.
zephyrproject-rtos/zephyr pull request #1182
Opened 2017-08-18 06:57 UTC by AdithyaBaglody

Helper macros to ease the usage of the MMU page table structures.
Added Macros to get Page table address and Page Table Entry
values.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

2017-08-22 15:02 UTC, nashif commented
Would be great if you also submit the code that would use those macros in the same PR

2017-08-22 20:02 UTC, tyrantlizard77 requested changes
Yeah, I'd like to see a patch in this series which convertes the existing x86_mmu.c code to use these new macros.

2017-08-23 04:52 UTC, AdithyaBaglody commented
I was modifying the sample test for the mem_domain_api. In that I had used these macros to ensure the flags are correctly set.
But sure I can change the x86_mmu code to use these new macros.

2017-08-24 16:45 UTC, tyrantlizard77 approved these changes

2017-09-08 00:13 UTC, merged