boards: add new board Electronut-labs Blip
zephyrproject-rtos/zephyr pull request #11877
Opened 2018-12-05 12:04 UTC by ntavish

Added config for https://github.com/electronut/ElectronutLabs-blip/.
Depends on https://github.com/zephyrproject-rtos/zephyr/pull/11837 being merged for the debugger.

2018-12-05 16:01 UTC, carlescufi requested changes

2018-12-05 16:01 UTC, carlescufi commented on boards/arm/nrf52840_blip/doc/nrf52840_blip.rst
> +Follow the instructions in the :ref:`nordic_segger` page to install
I don't think this is correct, since your board doesn't use J-Link.

2018-12-05 16:12 UTC, carlescufi approved these changes
Thanks!

2018-12-06 01:26 UTC, dbkinder requested changes

2018-12-06 06:17 UTC, ntavish commented
@dbkinder pushed requested changes.

2018-12-06 14:58 UTC, dbkinder approved these changes
+1 for doc changes

2018-12-06 19:47 UTC, ntavish commented
Don't think checkpatch test will pass. The shippable failure is due to `blackmagicprobe.board.cmake` file being not found, since that PR is on hold, because west runners are to be add in the west repo for the time being.

2019-01-11 13:22 UTC, ntavish commented
recheck

2019-01-12 14:15 UTC, merged