sample:ipsp: remove undefined symbol an clarify how to build
zephyrproject-rtos/zephyr pull request #11931
Opened 2018-12-07 10:00 UTC by jfischer-phytec-iot

Remove undefined symbol NET_DEBUG_L2_BT
Clarify how to build for Linux kernels released before 4.12.

2018-12-10 19:53 UTC, dbkinder requested changes

2018-12-10 19:53 UTC, dbkinder commented on samples/bluetooth/ipsp/README.rst
> +   For hosts using kernels released before 4.12 CONFIG_NET_L2_BT_ZEP1656
```suggestion
   For hosts using kernels released before 4.12,
   option :option:`CONFIG_NET_L2_BT_ZEP1656`
```

2018-12-10 19:53 UTC, dbkinder commented on samples/bluetooth/ipsp/README.rst
> +   shall be selected: https://github.com/zephyrproject-rtos/zephyr/issues/3111
```suggestion
   must be selected.  For more information, see `Zephyr issue #3111
   <https://github.com/zephyrproject-rtos/zephyr/issues/3111>`_
```

2018-12-11 13:41 UTC, jfischer-phytec-iot commented on samples/bluetooth/ipsp/README.rst
> +   shall be selected: https://github.com/zephyrproject-rtos/zephyr/issues/3111
done

2018-12-21 00:50 UTC, dbkinder approved these changes
doc changes LGTM, thanks!

2019-01-17 02:42 UTC, nashif approved these changes

2019-01-17 02:42 UTC, merged