scripts: extract_dts_includes: Generate defines for chosen props
zephyrproject-rtos/zephyr pull request #11952
Opened 2018-12-07 18:36 UTC by galak

Generate a set of defines that convey if a given chosen property is used
or not.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2018-12-07 20:56 UTC, carlescufi commented
This is in addition to what's being generated today right? i.e. `*_ON_DEV_NAME` and company?

2018-12-10 12:13 UTC, erwango commented
Technically, change seem fine but as @carlescufi , I'm not sure how this should be used.
What will be the relationship with `CONFIG_UART_CONSOLE_ON_DEV_NAME` and `DT_UART_CONSOLE_ON_DEV_NAME` ?

Then, it brings me that, along with the addition of device bus info define, we need some way to document these kind of artifacts, as they are not documented through dt bindings..

2018-12-10 12:33 UTC, carlescufi commented
@erwango they are now described here:
https://docs.zephyrproject.org/latest/devices/dts/device_tree.html#aliases-and-chosen-nodes

2018-12-10 12:45 UTC, erwango commented
@carlescufi , ok, thanks. Though, my question was more related to the following symbols:
#DT_UART_CONSOLE_ON_DEV_NAME 1
(and the likes #DT_SENSOR_BUS_(SPI/I2C) 1

2018-12-13 17:12 UTC, galak commented
> To address my point, I propose the following in the doc chapter provided by @carlescufi (`doc/devices/dts/device_tree.rst:311`):
> `CONFIG_*_ON_DEV_NAME` symbols could be used under `#ifdef DT_*_ON_DEV_NAME`.
> 
> Or maybe this is too much restrictive compare to current situation.

I think a general statement like:

As chosen properties tend to be related to software configuration, it can be useful for the build system to know if a chosen property was defined.  We generate a define for each chosen property, ie: 

`zephyr,flash` will generate: `#define DT_CHOSEN_ZEPHYR_FLASH 1`

2018-12-14 16:49 UTC, dbkinder requested changes

2018-12-14 16:49 UTC, dbkinder commented on doc/devices/dts/device_tree.rst
> +seful for the build system to know if a chosen property was defined. We
```suggestion
useful for the build system to know if a chosen property was defined. We
```

2018-12-14 16:49 UTC, dbkinder commented on doc/devices/dts/device_tree.rst
> +generate a define for each chosen property.
```suggestion
generate a define for each chosen property, for example:
```

2018-12-14 16:49 UTC, dbkinder commented on doc/devices/dts/device_tree.rst
> +``zephyr,flash`` will generate: `#define DT_CHOSEN_ZEPHYR_FLASH 1`
```suggestion
``zephyr,flash`` will generate: ``#define DT_CHOSEN_ZEPHYR_FLASH 1``
```

2018-12-14 16:55 UTC, galak commented
@dbkinder merged your changes in, take a look again.  Thanks.

2018-12-14 17:38 UTC, dbkinder approved these changes
LGTM, thanks!

2018-12-14 20:20 UTC, carlescufi approved these changes

2018-12-17 08:08 UTC, erwango approved these changes

2018-12-17 10:26 UTC, merged