Always release driver context in Nordic SPI driver
zephyrproject-rtos/zephyr pull request #11968
Opened 2018-12-08 15:06 UTC by NZSmartie

Do not return immediately in transfer_next_chunk on successful transfer

Fixes #11967

2018-12-08 15:15 UTC, NZSmartie commented
Uh, I need to re-gen my PGP keys in order to re-commit with my current email address instead of my legacy. If this can not be over-looked then I'm happy for someone else to submit my commit under their name. 

Also, I'm not sure how to reword the commit title to fit appropiately

2018-12-10 08:10 UTC, tbursztyka approved these changes

2018-12-10 10:18 UTC, anangl requested changes
Blocking this PR because these changes will cause the drivers to not handle the transfers correctly.
See https://github.com/zephyrproject-rtos/zephyr/issues/11967#issuecomment-445761378.

2019-01-08 10:14 UTC, NZSmartie commented
Closing as this PR was made without fully understanding what was cause of the problem was.

2019-01-08 10:14 UTC, closed without merging