driver: sensors: convert lsm9ds0_gyro to use information coming from dts
zephyrproject-rtos/zephyr pull request #12183
Opened 2018-12-19 15:21 UTC by avisconti

Convert lsm9ds0_gyro driver to get the device name as well as
i2c slave informationnd gpio info for triggers from device tree.
Updates the build_all test accordingly.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

2018-12-19 16:05 UTC, MaureenHelm requested changes
Code changes look good, but please fix the typo in the commit message. `informationnd` should be `information and`

2018-12-19 16:13 UTC, avisconti commented
> Code changes look good, but please fix the typo in the commit message. informationnd 
> should be information and

Ooops... thx!

2018-12-19 16:33 UTC, MaureenHelm approved these changes

2018-12-20 11:35 UTC, carlescufi approved these changes

2018-12-20 11:35 UTC, merged