samples: net: zoap_server: Unify Makefile and add prj_arduino_101.con…
zephyrproject-rtos/zephyr pull request #123
Opened 2017-05-09 03:55 UTC by jiequanx

…f file

Modify the Makefile to unify with other sample apps and add the arduino 101
configuration file.

Signed-off-by: Wu Jiequan <jiequanx.wu@intel.com>

2017-05-11 11:32 UTC, pfalcon approved these changes
+1, but don't know why tests failed.

2017-05-12 00:58 UTC, jiequanx commented
Yes, I do not modify the source code.

2017-05-15 09:26 UTC, jukkar requested changes
The actual patch looks ok. You need to remove the merge commit from this PR. Please rebase (not merge) your own branch against master, and then re-submit this PR.

2017-05-16 09:52 UTC, jukkar approved these changes

2017-05-17 06:37 UTC, merged