doc: updated doc for Zephyr release 1.9.
zephyrproject-rtos/zephyr pull request #1230
Opened 2017-08-23 11:33 UTC by SavinayDharmappa

Updated doc for rel 1.9 for :-

1. Added device tree support for Intel Quark based microcontroller boards.

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

2017-08-23 16:09 UTC, punitvara commented
Keep commit message upto 72 characters per line @SavinayDharmappa

2017-08-23 21:50 UTC, dbkinder commented on doc/release-notes-1.9.rst
> +  such as Arduino_101,tinytile and Quark_d2000_crb.
change to:

     such as Arduino_101, tinytile, and Quark_d2000_crb.

2017-08-23 21:50 UTC, dbkinder requested changes
fix typos

2017-08-25 13:08 UTC, nashif approved these changes

2017-08-25 13:08 UTC, merged