Bluetooth: controller: Implement missing commands required by EBQ
zephyrproject-rtos/zephyr pull request #1233
Opened 2017-08-23 14:21 UTC by carlescufi

2017-08-23 14:30 UTC, holtmann commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +u32_t ll_rssi_get(u16_t handle, u8_t *rssi)
Why is this u32 and not u8 if this returns the status.

2017-08-23 14:30 UTC, holtmann commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		return 1;
I would use HCI status errors if it is used for that.

2017-08-23 14:30 UTC, holtmann commented on subsys/bluetooth/controller/hci/hci.c
> +	rp->rssi = -rp->rssi;
This seems pointless if ll_rssi_get could just return it in the right format. Or at least add a comment here.

2017-08-23 14:44 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		return 1;
This is part of the LE Controller style fixes Jira issue, will be done as one later on

2017-08-23 14:45 UTC, carlescufi commented on subsys/bluetooth/controller/hci/hci.c
> +	rp->rssi = -rp->rssi;
I'll add a comment, because there are other places where we have this issue. Will be fixed alongside the rest of "style issues"

2017-08-23 14:46 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +u32_t ll_rssi_get(u16_t handle, u8_t *rssi)
All LL return values are currently u32_t except for privacy. This will be overhauled when we address the LL "style issues" Jira.

2017-08-23 14:47 UTC, carlescufi commented
@holtmann comments addressed

2017-08-23 14:48 UTC, holtmann approved these changes

2017-08-25 08:43 UTC, cvinayak requested changes

2017-08-25 08:43 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +	rp->rssi = -rp->rssi;
is garbage value ok, on failure?

2017-08-25 08:43 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +
You are not using the "type" in the cmd, please add a TODO for now that we return 0 dB for both current and max tx power.

2017-08-25 08:56 UTC, carlescufi commented
@cvinayak comments addressed

2017-08-25 08:59 UTC, cvinayak approved these changes

2017-08-25 09:27 UTC, merged