net: 6lo: fix unused variable warning
zephyrproject-rtos/zephyr pull request #1237
Opened 2017-08-23 18:47 UTC by rsalveti

subsys/net/ip/6lo.c: In function 'compress_IPHC_header':
subsys/net/ip/6lo.c:759:22: warning: unused variable 'hdr' [-Wunused-variable]
   struct net_udp_hdr hdr, *udp;
                      ^~~

Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

2017-08-23 20:22 UTC, jukkar requested changes

2017-08-23 20:22 UTC, jukkar commented on subsys/net/ip/6lo.c
> +		struct net_udp_hdr hdr __unused, *udp;
This works but I suggest to fix this other way.
Please edit `include/net/udp.h` and change `net_udp_get_hdr()` macro to
`static inline struct net_udp_hdr *net_udp_get_hdr(struct net_pkt *pkt, struct net_udp_hdr *hdr) { return NULL; }`
and similar change to net_udp_set_hdr(). This way we do not need to add these __unused strings around.

2017-08-23 20:44 UTC, rsalveti commented on subsys/net/ip/6lo.c
> +		struct net_udp_hdr hdr __unused, *udp;
You mean changing both the function definition and macro? The macro itself is only used when CONFIG_NET_UDP is not defined.

2017-08-23 20:51 UTC, rsalveti commented on subsys/net/ip/6lo.c
> +		struct net_udp_hdr hdr __unused, *udp;
You are right, was confused by IS_ENABLED but checking my own config, NET_UDP was not even used. Will change as suggested.

2017-08-24 18:48 UTC, jukkar approved these changes

2017-08-25 19:35 UTC, merged