handle RST packets under the status of tcp established
zephyrproject-rtos/zephyr pull request #124
Opened 2017-05-09 11:35 UTC by Likailiu

when tcp connection was established, if one RST packet
received from peer next, the current connection should
be free.

2017-05-09 15:43 UTC, lpereira requested changes
In order to be compliant with RFC 793 (see page 32), this check must be performed in all of the synchronized states (ESTABLISHED, FIN-WAIT-1, FIN-WAIT-2, CLOSE-WAIT, CLOSING, LAST-ACK, TIME-WAIT).  The sequence number must also be validated (see page 37, "Reset processing") before taking any decision.

In addition, the connection shouldn't be aborted cold-turkey like this; the receive callback must be called with an error as well. Maybe `-ECONNRESET` would be the best error code. Without warning the user, they have no way to know that the connection has been reset and the context handle they have is not only invalid, but also allocated resources won't be deallocated.

2017-05-10 07:23 UTC, jukkar commented
I noticed the same issue and send a bug fix before I noticed this patch. I will remove my patch as it came later.

2017-05-10 07:35 UTC, jukkar requested changes
As mentioned in separate comment, I found out the same issue and sent a patch few minutes ago. My patch about this issue can be found at https://github.com/jukkar/zephyr/commit/ca798642a4f4eab52bc69ae7b679f546356e4033

As @lpereira mentioned, the seq numbers should be checked and my patch is also missing those checks and state checks in other states. Anyway it has better commit message and also informs user application about the situation. So the original commiter can use my patch as a base for fixes.

2017-05-10 09:02 UTC, pfalcon commented
@jukkar : With all due respect to @Likailiu's work, I would prefer your patch (also @tbursztyka, @lpereira, @andyross 's) to a patch of someone who just starts with the Zephyr IP stack (this includes me). While investigating few last issues, I already got an impression that contributors oftentimes literally patching the IP stack on spot, instead of trying to find a better underlying solution to a problem. My "draft" and "WIP" patches definitely show that tendency, and my real hope is that by posting them, I would prompt the core maintainers to look into a proper fix instead.

Given that we're single weeks away from the 1.8 freeze, it really amounts to whether 1.8 will have "more working" or "more broken" TCP support, so @jukkar, I would encourage you to continue with your patch instead, and I hope @Likailiu would agree.

Thanks!

2017-05-10 09:35 UTC, Likailiu commented
OK, I agree with pfalcon and will  remove this patch.@jukkar @pfalcon @simple2017

2017-05-10 09:35 UTC, closed without merging