smp: shell: Add support for SMP in new shell.
zephyrproject-rtos/zephyr pull request #12434
Opened 2019-01-11 13:00 UTC by Mierunski

Added smp support for new shell.

Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>

2019-01-11 13:18 UTC, jakub-uC requested changes
Thank you for this PR.

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/mgmt/Kconfig
> +	select SHELL
I would add here:
`select CONFIG_SHELL_BACKEND_SERIAL`

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
> +#define CONSOLE_MCUMGR_STATE_NONE       1
Console is not used. Maybe:
`SHELL_MCUMGR_STATE_NONE` and so on...

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
> +static int read_mcumgr_byte(struct smp_shell_data *data, uint8_t byte)
`u8_t`

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/shell/shell_uart.c
> +#endif          /* CONFIG_UART_CONSOLE_MCUMGR */
you can move `#endif` one line up and remove `ring_buf_put_finish` function call in line 63

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/shell/shell_uart.c
> +			/* Divert this byte from normal console handling if it
What console?

2019-01-11 13:18 UTC, jarz-nordic commented on subsys/shell/shell_uart.c
> +	.update = update,
Initialization is not in the order of structure definition. This will cause a warning for C++ compiler.

2019-01-11 14:37 UTC, jakub-uC requested changes
Please remove console references.

2019-01-11 14:37 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
> +};
please name this enum

2019-01-11 14:37 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
>  struct device;
It is not yours... but what is that? :)

2019-01-11 14:37 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
> +		/* Not an mcumgr command; let the normal console handling
console?

2019-01-11 14:37 UTC, jarz-nordic commented on subsys/mgmt/smp_shell.c
> +	 * and return true to indicate that normal console handling should
console...

2019-01-11 14:37 UTC, jarz-nordic commented on subsys/shell/shell_uart.c
> +#ifdef CONFIG_UART_CONSOLE_MCUMGR
`CONSOLE`...

2019-01-14 10:30 UTC, jarz-nordic commented on include/mgmt/smp_shell.h
> + *		is a plain console command.
shell

2019-01-14 13:42 UTC, jakub-uC approved these changes

2019-01-14 16:10 UTC, carlescufi approved these changes
LGTM

2019-01-14 16:10 UTC, carlescufi commented
This concludes the required changes in order to deprecated the previous shell implementation

2019-01-14 20:17 UTC, dbkinder reviewed
I don't see any doc (.rst file) changes for me to review.  Should there be?

2019-01-15 08:41 UTC, Mierunski commented
@carlescufi Yes
@dbkinder There was no change in behaviour or functionality, so no doc changes except in header files.

2019-01-15 14:31 UTC, Mierunski commented
@nashif Could you merge this?

2019-01-15 22:19 UTC, merged