net: tcp: do not drop successfully received packets
zephyrproject-rtos/zephyr pull request #12502
Opened 2019-01-15 22:05 UTC by aurel32

Each time a successfully TCP connection is done, the number of dropped
TCP packets increases by 2. This is happens because when receiving an
initial SYN packet, or an ACK packet following a SYN+ACK packet,
NET_DROP is returned even if there is no error.

Fix that by replacing the two corresponding "return NET_DROP" by
"net_pkt_unref(pkt)" followed by "return 0".

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

2019-01-15 23:01 UTC, aurel32 commented
recheck

2019-01-16 07:57 UTC, jukkar requested changes
Looks good, minor nitpick.

2019-01-16 07:57 UTC, jukkar commented on subsys/net/ip/tcp.c
> +		return 0;
Better to return NET_OK here, the code is more readable that way.

2019-01-16 09:18 UTC, jukkar commented
recheck

2019-01-16 11:11 UTC, jukkar approved these changes

2019-01-16 11:11 UTC, merged