SAM GMAC ethernet driver fixes
zephyrproject-rtos/zephyr pull request #12591
Opened 2019-01-18 20:36 UTC by aurel32

This set of 3 patches aims to fix issue #11255. It has been tested with ICMPv4 and ICMPv6 ping with a 0.00001 interval during 2 hours, both as standalone and with PR#11888 + PR#12555. For me it fixes the reported issue, although I am almost sure there are more bugs lying down in the driver, especially as these patches only touch the TX path.

Fixes: #11255

2019-01-21 07:34 UTC, jukkar reviewed
Thanks @aurel32, the commit messages in this PR are excellent :+1: 
I will try this with gptp which had some weird issues with sam-e70 earlier. I will post results after some testing.

2019-01-21 07:41 UTC, tbursztyka approved these changes

2019-01-21 10:36 UTC, jukkar approved these changes
Done some testing with gptp, sam-e70 works now as well as frdm-k64f

2019-01-21 10:58 UTC, jukkar commented
Now I started to see this in sam-e70
```
[00:00:04.546,287] <wrn> net_gptp: Not AS capable: 4294967295 ns > 100000 ns
```
This is most probably not related to this PR but anyway this is something I do not see in frdm-k64f. This needs more investigation in gptp code.

2019-01-21 11:05 UTC, pfalcon requested changes

2019-01-21 11:05 UTC, pfalcon commented on drivers/ethernet/eth_sam_gmac_priv.h
> +#define MAIN_QUEUE_TX_DESC_COUNT (max(CONFIG_NET_BUF_RX_COUNT, \
Please add comment why this formula.

2019-01-21 11:07 UTC, pfalcon commented on drivers/ethernet/eth_sam_gmac_priv.h
> +#define MAIN_QUEUE_TX_DESC_COUNT (max(CONFIG_NET_BUF_RX_COUNT, \
While doing that, also please update the title from "drivers: eth: gmac: correctly compute the number of descriptors" to "drivers: eth: gmac: *conservatively* compute the number of descriptors". Per, https://github.com/zephyrproject-rtos/zephyr/pull/12591#issuecomment-456035299 , this is unlikely "correct".

2019-01-21 11:07 UTC, pfalcon commented on drivers/ethernet/eth_sam_gmac_priv.h
> +#define MAIN_QUEUE_TX_DESC_COUNT (max(CONFIG_NET_BUF_RX_COUNT, \
Also:

> This wrong assume that 

Should be "wrongly assume".

2019-01-21 11:50 UTC, pfalcon commented
> The ICMPv6 implementation already copies the RX buffer into the TX buffers.

Well, good to know (I didn't).

> Should I try to do the same for ICMPv4 instead of this patch?

"Instead", unlikely, at least I wouldn't burden anyone with such a request. But if you could pursue that after this patch, I would both appreciate and +1 (well, +10) it. I generally mention such issues to "raise awareness" and build a consensus on how to resolve them.

2019-01-21 13:33 UTC, aurel32 commented
> > Should I try to do the same for ICMPv4 instead of this patch?
> 
> "Instead", unlikely, at least I wouldn't burden anyone with such a request. But if you could pursue that after this patch, I would both appreciate and +1 (well, +10) it. I generally mention such issues to "raise awareness" and build a consensus on how to resolve them.

Ok, I'll keep that on my TODO list, as it would also allow to have a simple TX timeout mechanism in the GMAC driver.

2019-01-21 22:55 UTC, aurel32 commented
@pfalcon I have just pushed a new version with the fixes you suggested.

2019-01-22 11:36 UTC, pfalcon approved these changes
Thanks for updates!

2019-01-22 13:40 UTC, merged

2019-01-27 23:11 UTC, mnkp reviewed
@aurel32 I didn't have time to review this PR in a timely manner. Just want to say thanks for working on and fixing the issues!