soc/arm: stm32: Add common to zephyr include directories
zephyrproject-rtos/zephyr pull request #12695
Opened 2019-01-24 16:13 UTC by erwango

st_stm32/common/ is not added to Cmake include pathes.
Fix this with zephyr_include_directories.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

2019-01-24 16:14 UTC, erwango commented
@GeorgeCGV

2019-01-24 17:11 UTC, ydamigos approved these changes

2019-01-24 17:17 UTC, galak commented
any idea why we haven't seen this until now?

2019-01-24 18:32 UTC, GeorgeCGV commented
@galak seems like nothing really uses the header file in the commons at runtime.
Discovered accidentally upon messing with vscode and eclipse development environments.
There is another issue  [#12696](https://github.com/zephyrproject-rtos/zephyr/issues/12696) discovered as a part of this.

2019-01-25 08:20 UTC, SebastianBoe commented
If it's a private header file, why do we want to add it to the global includes?

2019-01-25 08:22 UTC, erwango commented
@SebastianBoe , this is breaking Eclipse project according to @GeorgeCGV

2019-01-25 08:36 UTC, erwango commented
@SebastianBoe , some context from slack:
> Geo: I also noticed that there are some broken include paths for STM32 in generated `compile_commands.json`
`-IE:...soc/arm/st_stm32/include`and `-IE:.../soc/arm/st_stm32/stm32l4/include` but missing the right one - `-IE:.../soc/arm/st_stm32/common`. Is this known?

2019-01-25 08:42 UTC, SebastianBoe commented
The broken paths are covered by the other issue mentioned.

Why soc/arm/st_stm32/common is the "right" include I can't understand (is probably wrong).

2019-01-25 08:51 UTC, GeorgeCGV commented
It doesn't have to be added, it builds completely fine without it; as it is more of a private include there.
Maybe I write it a bit incorrectly initially,

> but missing the right one - -IE:.../soc/arm/st_stm32/common

by the "right one" was the meaning that such a path does exist. 
But as forementioned

> It looks more of like a private header than a system-wide one.

if this assumption is true then it shall not be included globally.

2019-01-25 08:54 UTC, SebastianBoe requested changes
Don't add the private include directory to the global includes.

2019-01-25 10:00 UTC, erwango commented
@GeorgeCGV , so no issue in Eclipse if change is not done? You mentioned:
> I guess this might lead to an inability to compile projects where stm32 soc is used, and probably that is a moderate or even a critical issue.

Is that ok now?

2019-01-25 11:37 UTC, GeorgeCGV commented
@erwango by the time of writing I didn't investigate much what headers the folder contained and assumed
> I guess this might lead to an inability to compile projects where stm32 soc is used, and probably that is a moderate or even a critical issue.
but seems like this location only contains some private headers

2019-01-25 12:44 UTC, erwango commented
@GeorgeCGV , np! ok to close this PR then?

2019-01-25 14:13 UTC, GeorgeCGV commented
@erwango sure

2019-01-25 14:21 UTC, closed without merging