dfu: Fix build issue with gcc8
zephyrproject-rtos/zephyr pull request #12897
Opened 2019-01-30 22:28 UTC by galak

We get the following warning when buiding with gcc8:

	error: 'packed' attribute ignored for type 'u32_t *'
	{aka 'unsigned int *'} [-Werror=attributes]

Removing __pack from the cast fixes the issue.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2019-01-30 22:30 UTC, carlescufi requested changes
The problem I see with this is that on platforms not supporting unaligned access this might trigger a fault now

2019-01-30 22:35 UTC, galak commented
> The problem I see with this is that on platforms not supporting unaligned access this might trigger a fault now

Hmm, I wondering if gcc 6.2.0 actually does anything w/regards to the alignment and packed.

2019-01-30 22:43 UTC, galak commented
> The problem I see with this is that on platforms not supporting unaligned access this might trigger a fault now

Changed to using UNALIGNED_GET().

2019-01-30 22:45 UTC, carlescufi approved these changes

2019-01-31 08:54 UTC, nvlsianpu approved these changes

2019-01-31 09:13 UTC, merged