net: openthread: move the flash area to the storage partition
zephyrproject-rtos/zephyr pull request #12944
Opened 2019-01-31 21:28 UTC by aurel32

OpenThread currently uses the 4 last pages of the flash memory to store
its data. This does not work correctly when a bootloader is used (either
MCUboot or nRF5 bootloader) as this area is used for other purpose.

This patch therefore move the OpenThread flash area to the storage area.
In the long term it should be better to use the settings subsystem
instead of the OpenThread flash platform system, but that is a more
complicated change.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

2019-02-01 08:39 UTC, rlubos approved these changes
Looks good 👍 

I agree that eventlually we should build OT settings module on top of Zephyr's settings subsys. Hopefully, in a near feature we'll be able to put more effort into actually improving OT port for  Zephyr, not only maintaining it.

2019-02-01 13:18 UTC, aurel32 commented
recheck

2019-02-01 17:11 UTC, aurel32 commented
Recheck

2019-02-01 17:34 UTC, aurel32 commented
recheck

2019-02-01 18:06 UTC, mike-scott approved these changes

2019-02-01 18:15 UTC, mike-scott requested changes
Hrm.. at first glance this is a good change.  I have to wonder though if we can actually use 4 pages of flash for all of the OT enabled HW in Zephyr.. let me take a look.

2019-02-01 18:32 UTC, mike-scott commented
Adding @MaureenHelm and @dleach02 for discussion as they own 2 of the 802.15.4 capable boards here w/o storage partitions.

2019-02-01 19:06 UTC, aurel32 commented
@mike-scott You got a good idea to check all boards, I only checked the nrf ones. I believe that we can switch back to the previous solution of using the last pages of the flash when the storage area is not defined.

2019-02-01 20:17 UTC, rlubos commented
A fallback to old solution sounds reasonable for boards that don't have such partition. Still, I believe other boards would benefit from having storage partition defined - all in all it's board maintainer who should know better where persistent data is allowed to be stored, not the OpenThread library.

And keep in mind we're not bound to 4 pages here - it's a default value, still it's configurable. AFAIR 2 pages is the minimal valid configuration for OpenThread's settings module.

2019-02-02 20:54 UTC, jfischer-phytec-iot commented
>However, the below boards are (in theory) able to compile OpenThread and do not have a storage partition configured:
quark_se_c1000_devboard
frdm_kw41z
usb_kw24d512

USB-KW24D512 does not have enough RAM (low and high ram on 0x20000000 boundary issue) and K64F + MCR20A has a write-block-size issue, see #5943

2019-02-02 22:34 UTC, aurel32 commented
> K64F + MCR20A has a write-block-size issue, see #5943

That's actually a good reason to better integrate OT and store the configuration using the settings subsystem.

2019-02-03 22:15 UTC, dleach02 commented
on the frdm-kw41z, I just used the built-in OpenThread support. But for the BLE enablement, some modes of BLE require the storage partition so my PR has this optionally enabled. The biggest problem though is what size should this partition be? A "one size fits all" strategy doesn't seem appropriate but I'm not sure how to parameterize it to adjust to the needs of the application.

2020-01-17 09:40 UTC, rlubos commented
This PR is no longer applicable with #21796, can be closed.

2020-07-01 12:30 UTC, rlubos commented
I'll take the liberty to close this PR, since it's no longer applicable.

2020-07-01 12:30 UTC, closed without merging