net: lib: mqtt: Enable blocking PUBLISH payload readout
zephyrproject-rtos/zephyr pull request #13058
Opened 2019-02-05 12:34 UTC by rlubos

A follow up of a discussion in #10500 regarding PUBLISH payload reading.

It is convenient to have a blocking version of `mqtt_read_publish_payload` function, for cases when it is called from the event handler. Therefore, extend the 'mqtt_read_publish_payload' argument list with information whether the call should block or not.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2019-02-05 14:31 UTC, agross-linaro commented
If you are going to go this route, i'd rather see it implemented with a timeout value.  0 for non block and any other amount would indicate waiting some period of time.  Return bytes read or -EAGAIN or whatever other error code you get.

2019-02-05 14:41 UTC, rlubos commented
I wanted to mimic socket `recv` behavior in this case, there's no timeout value there.  All in all, `mqtt_read_publish_payload` is just a wrapper for `recv` call with some extra checks. But if we conclude we should implement a timeout feature here, then it could be achieved with `recv`/`poll` combination I guess.

2019-02-05 19:07 UTC, pfalcon requested changes
I'm -1 on this change, because it breaks the requirement that "read" function had the same syntactic signature (with `int fd` replaced with `void *obj`). This requirement is in turn based on the principle of composability of read (also write) interfaces of different modules. This principle call to follow the same interface fore read/write, and pass "ancillary data" by other means.

Let's discuss possible alternatives:

1. Add another call, *_set_blocking(true/false).
2. Add convenience function *_read_blocking().
3. Both of the above, i.e. implement convenience func in the terms of existing mqtt_read_publish_payload() and *_set_blocking() from p.1.

2019-02-05 19:11 UTC, agross-linaro commented
@pfalcon I don't follow you.  Why would we add 2 more APIs when we can just use 1 with an additional parameter.  This isn't about recv() or whatever, this is about a mqtt wrapper function that does something with the underlying network layer.

2019-02-05 19:14 UTC, pfalcon commented
> I wanted to mimic socket `recv` behavior in this case, there's no timeout value there.

Well, fairly speaking, MSG_DONTWAIT is a hack too. It doesn't exist for read(), and that's what we "mimic" (rather, faithfully follow).

> But if we conclude we should implement a timeout feature here, then it could be achieved with `recv`/`poll` combination I guess.

Mind that we have https://github.com/zephyrproject-rtos/zephyr/issues/11820. And a natural reaction would be that we don't want to "emulate" timeout in each and every protocol imp, if it can be handled on socket level.

But the problem we solve here is all different:

* It's convenient for library to work with non-blocking sockets (to ensure extra efficiency)
* It's convenient for lib user to work in blocking mode (to simplify code).

We need a way to shift perspective between library and user. Specific options indeed would rather be implemented on socket level.

2019-02-05 19:21 UTC, pfalcon commented
@agross-linaro 

> @pfalcon I don't follow you. Why would we add 2 more APIs when we can just use 1 with an additional parameter. This isn't about recv() or whatever, this is about a mqtt wrapper function that does something with the underlying network layer.

Because it breaks the paradigm of networking APIs (plural), for spur-of-the-moment benefit in one of them (which of course will be mirrored in inconsistent way to other APIs, leading to cute mess overall). Paradigms mean more than adhoc perceived benefits, and thus should be preserved. Any conveniences can be added *on top* of generic, flexible, consistent API.

2019-02-05 19:57 UTC, pfalcon commented
@d3zd3z:

> So, stepping back a little, can someone explain to me how it makes sense for this call to be non-blocking? ... What exactly would it do if the read call would block, it can't return?

May I suggest that these 2 question have contradictory, emm, connotations? In first you seem to be critical regarding call being non-blocking (apparently, suggesting that it would make more sense to be blocking), yet in 2nd you express reservation how a blocking call would work. That's however a typical situation: it's impossible to satisfy different (oftentimes contradictory) requirements with one solution. That would be a good reason not to try, but cluster requirements, and offer different solutions. Hopefully, clustering happens to cover exactly the (two) opposite requirements - offer as flexible choices as possible in minimal bytes of code as possible, vs dumb-can't-fail solution.

Now trying to answer specific questions:

> So, stepping back a little, can someone explain to me how it makes sense for this call to be non-blocking?

Apparently, the best explanation why it is so now is due to underlying socket state leak from API into client. That's not to say that non-blocking operation is not useful. But by all accounts, that would be rare.

> Isn't it an error to return from that callback before all of the payload is read?

Yes, so it's up to a user to ensure they did it. A whole spectrum of solutions is available - from the most obvious - poll(), to creative ones like busy-polling on that read call. (Flexibility is a requirement! ;-) )

> What exactly would it do if the read call would block, it can't return?

Obviously, it's impossible to *receive* anything new on MQTT connection until the old data is read out. However, MQTT is full-duplex protocol, so user may want to send something while they still reading out something. E.g., if a user reads out 100MB payload (which will take a while), and wants to ping server in the meantime to show it's still alive, who are we to preclude that? Hence, flexibility of non-blocking reads.

2019-02-06 11:59 UTC, rlubos commented
Moved blocking `mqtt_read_publish_payload` into a separate API function.

2019-02-06 12:01 UTC, pfalcon commented
> Moved blocking `mqtt_read_publish_payload` into a separate API function.

But what about discussing the situation and finding the best solution (by a number of criteria, that is)?

2019-02-06 12:37 UTC, rlubos commented
So I don't understand why do we need to follow some unspecifed requirements regarding MQTT API, but I don't have strong issue with that, hence I changed the implementation, as requested.

As parametrizing `mqtt_read_publish_payload` was rejected, providing a convenience function beside `mqtt_read_publish_payload` simpy sounds like more user friendly approach.
I'm afraid that introducing an extra API function that will silently modify `mqtt_read_publish_payload` behavior will bring even more confusion for users than introduction of `mqtt_read_publish_payload` did.

2019-02-06 13:10 UTC, pfalcon commented
> So I don't understand why do we need to follow some unspecifed requirements 

Ok, if they are unspecified, we'll specify them.

> regarding MQTT API, but I don't have strong issue with that, hence I changed the implementation, as requested.

Thanks, but it's not just about MQTT API, it's about protocols API in general - what patterns do we use to design and implement them. It's just MQTT is the first (of SOCK_STREAM APIs), and is a precedent to consider.

> I'm afraid that introducing an extra API function that will silently modify `mqtt_read_publish_payload` behavior 

What do you mean "silently"? It would be explicitly documented as such. But you git the idea right - after all the consideration above, I also lean towards have a set_blocking() call straight on mqtt_client object, then   mqtt_read_publish_payload() will just always work in blocking or non-blocking manner, per user's choice. (With obvious default.) 

> will bring even more confusion for users than introduction of `mqtt_read_publish_payload` did.

How, how will it bring more confusion? What can be simpler to both explain and understand, than saying "mqtt_read_publish_payload() works in exactly the same way as POSIX read() does" and "blocking/noblocking behavior of mqtt_read_publish_payload() is set up using function *_set_blocking(), in a absolutely similar way to how fcntl(F_SETFL, O_NONBLOCK) sets blocking/non-blocking behavior of a socket" ?

2019-02-06 13:11 UTC, pfalcon commented
> "mqtt_read_publish_payload() works in exactly the same way as POSIX read() does" and "blocking/noblocking behavior of mqtt_read_publish_payload() is set up using function *_set_blocking(), in a absolutely similar way to how fcntl(F_SETFL, O_NONBLOCK) sets blocking/non-blocking behavior of a socket" ?

And again, the whole point - that would be the same for any other protocol implementation.

2019-02-09 16:38 UTC, pfalcon commented
>> So I don't understand why do we need to follow some unspecifed requirements

> Ok, if they are unspecified, we'll specify them.

So, as promised (also briefly touched at the last networking forum): https://github.com/zephyrproject-rtos/zephyr/issues/13212 . Nothing there should come as surprise, as these things were discussed during original MQTT review. What's left is effectively formalizing those principles down to specific function signatures. (As of this time, it's still WIP, though majority of wording is there.)

2019-02-13 08:32 UTC, pfalcon commented
@rlubos: Can you rebase this, and can we continue the best-way-to-do-it API discussion?

2019-02-13 10:21 UTC, rlubos commented
It would be really good to hear from other what do they think. Especially from people that actually used this library. For me personally it's not a big difference whether I have to make a single API call to read payload or three API calls, I can even live with current `poll` approach. But I see people gets confused even with `mqtt_read_publish_payload` (and I'm not talking about comments we received here, upstream), hence my concerns.

But beside that, given we decide to have `fnctl-like` function, there are still some unknowns and assumptions that need to be considered:

1. Should blocking mode affect only `mqtt_read_publish_payload` or `mqtt_input` as well? It could make sense to have blocking `mqtt_input` in simple use cases, but it will have consequences.
2. If blocking `mqtt_input` would be allowed, we should reconsider whether having `mqtt_live` function for keep-alive management makes sense. Probably we should handle connection upkeep internally in the library with delayed works. 
3. And this call should not affect TX path as the library is not prepared for non-blocking TX.

2019-02-25 20:10 UTC, agross-linaro commented
@rlubos In response to your points:
1) If we don't implement a blocking call, I'd expect we would need a helper function which would do this based on a FD/socket.

2) I really don't like the automatic mqtt_live.  I'd rather people have to manually deal with that because of the serialized nature of mqtt data/traffic.

3) agreed

2019-04-18 07:31 UTC, jukkar commented
@rlubos what is the plan with this PR, at least it needs rebasing against latest master?

2019-04-18 07:33 UTC, rlubos commented
Let's close this until we come up with a "better" solution.

2019-04-18 08:14 UTC, pfalcon commented
@rlubos: In my list, this was in backlog while working on 1.14, and at the same time allowing us to think more about it/collect feedback. My plan was to call to discuss any concerns with "follow POSIX spirit" approach re: blocking vs non-blocking handling, and if no grave issues raised, to suggest to go forward with it. So, I'd suggest to reopen this.

2019-04-24 08:03 UTC, pfalcon commented
As discussed on Slack, this PR implements valuable feature, and contains useful discussion, so let's reopen it, and ideally continue.

2019-04-24 10:23 UTC, rlubos commented
@jukkar As the PR got revived, I've rebased the PR branch.

@pfalcon The PR was stall for quite some time and I've decided to close it as it's unclear to me what the expectations are here. Given the previous discussion, we had 3 proposals on how to proceed with the PR:

>Let's discuss possible alternatives:
>1. Add another call, *_set_blocking(true/false).
>2. Add convenience function *_read_blocking().
>3. Both of the above, i.e. implement convenience func in the terms of existing mqtt_read_publish_payload() and *_set_blocking() from p.1.

`2.` was implemented (which was a minimalistic approach), but apparently it was considered not good enough. Did anything change since then? I understand the alternative is to provide a `fctnl` wrapper to reconfigure the underlying socket, but here we need some clarifications: https://github.com/zephyrproject-rtos/zephyr/pull/13058#issuecomment-463143222

2019-05-07 13:55 UTC, pfalcon commented
>  @rlubos commented 13 days ago

Sorry, this time, there was a series of holidays on my side. Let's get back to this though.

> 2. was implemented (which was a minimalistic approach), but apparently it was considered not good enough. Did anything change since then?

Well, I have to admit that my favorite still remains to be:

> 1. Add another call, *_set_blocking(true/false).

But:

> I understand the alternative is to provide a fctnl wrapper to reconfigure the underlying socket, but here we need some clarifications: #13058 (comment).

Ok, let's look thru these:

> 1. Should blocking mode affect only mqtt_read_publish_payload or mqtt_input as well?

I have to admit that I followed approach "solve an issue at hand, but do that in as generic way as makes sense". I.e., I always had in mind that it would affect only mqtt_read_publish_payload(). But that indeed leads to "interesting" questions like above. My answer would be still "oh no, it would affect only  mqtt_read_publish_payload()", but I may imagine that may raise eyebrows re: whether "as generic way as possible" approach is really well thought out on my side.

> 2. If blocking mqtt_input would be allowed, we should reconsider whether ...

No-no, that brings us to far from the current issue at hand - let users read out payload in a blocking manner.

> 3. And this call should not affect TX path as the library is not prepared for non-blocking TX.

Would work for me, and actually what I have in mind re: answer to p.1 above.



So, well, I have to admit that `*_set_blocking(true/false)` call is based on a bit of wishful thinking and on some thin-air considerations. While I still think that's the ultimately best (the most generic) way to do it, this leaves many questions unanswered between that vision and the current situation we have, and that can't be right for usability.

So, I have to agree that the introduction of mqtt_read_publish_payload_blocking() function, as this patch does, is a practical and focused way to solve the issue we have at hand, so let me approve this PR.

2019-05-07 13:57 UTC, pfalcon approved these changes
Withdrawing my ideas/concerns as not very well thought out, and opening too many new questions instead of just resolving the issue at hand. +1 for going this practical approach.

(More comments at https://github.com/zephyrproject-rtos/zephyr/pull/13058#issuecomment-490090146)

2019-05-07 20:35 UTC, jukkar approved these changes
The current proposal looks good, +1 from me.

2019-05-08 02:08 UTC, merged