shell: net: Switch to synchronous getaddrinfo call
zephyrproject-rtos/zephyr pull request #13191
Opened 2019-02-08 18:32 UTC by agross-linaro

This patch fixes an issue with the 'net dns query' shell command.  The
asynchronous nature of the dns_get_addr_info call makes this unsuitable
for the use inside the shell.  Instead, let's use the synchronous
getaddrinfo to acquire DNS records.

Signed-off-by: Andy Gross <andy.gross@linaro.org>

2019-02-08 19:03 UTC, pfalcon commented
> This patch fixes an issue with the 'net dns query' shell command.

What issue?

> The
asynchronous nature of the dns_get_addr_info call makes this unsuitable
for the use inside the shell.

Why it's unsuitable?

2019-02-08 19:05 UTC, agross-linaro commented
@pfalcon It crashes when issuing a 'net dns query'.

The asynchronous nature of the call makes it difficult to get it working in the current shell implementation.  By difficult, I mean that I've wasted countless hours dealing with it and I am not going to spend another minute when I can use a synchronous call that works 100% of the time without failure.

2019-02-08 19:17 UTC, pfalcon commented
> It crashes when issuing a 'net dns query'.

So, what exactly crashes? Is it dns_get_addr_info() issue, or regression in the new shell implementation, which perhaps needs to be fixed by the shell folks? We had that command implemented long ago, much earlier than getaddrinfo(), and nobody reported and issues about it.

My concern is that getaddrinfo() is implemented for applications wanting POSIX API. It incurs additional code size overhead, and will incur only more going forward, when more and more POSIX options will be implemented. The shell has quite different requirements - offer as much functionality as possible with as little code size as possible, and itself it's quite large, so that all contradicts usage of getaddrinfo(), if dns_get_addr_info() served us well.

2019-02-08 19:22 UTC, pfalcon requested changes

2019-02-08 19:22 UTC, pfalcon commented on subsys/net/ip/Kconfig
> +	select NET_SOCKETS_POSIX_NAMES if DNS_RESOLVER
Regardless of other matters, NET_SOCKETS_POSIX_NAMES should not be used by any internal code in Zephyr itself. It's strictly a compatibility option for external applications of a particular type. It's not compatible with POSIX subsystem (soon there will conflicting anti-depend on it).

Internal Zephyr code should always use native Zephyr API, which is zsock_getaddrinfo().

2019-02-08 19:22 UTC, pfalcon commented on subsys/net/ip/Kconfig
> +	select NEWLIB_LIBC if DNS_RESOLVER
Why do we bring newlib here?

2019-02-08 19:35 UTC, closed without merging

2019-02-08 19:35 UTC, jukkar commented
I am wondering the same thing as @pfalcon. I think we need to fix the resolver if it causing crashes in shell. One good thing about the async DNS call is that the shell is fully usable while the resolving is done, although the timeout when using the sync version is probably not very long.
Anyway, using async DNS code in shell is one of the few users of the resolver code so it is good to leave it here for testing purposes. Beside the getaddrinfo() is basically calling the async version of the resolver so I am suspecting that the reason for crashes is not in DNS code but in shell integration of it. I can look into this next week, the fix is probably quite simple one.

As a summary, I am not big fan of this change but if people really want to have this done this way we can certainly change it.

2019-02-08 19:37 UTC, agross-linaro commented
@jukkar Paul is being assigned the work.

2019-02-08 19:37 UTC, agross-linaro commented
Closed this ticket.  We'll look forward to other presented solutions.

2019-02-11 08:44 UTC, jarz-nordic commented
@agross-linaro : Shell is not able to print asynchronous messages. Is it still an issue?

2019-02-11 20:12 UTC, pfalcon commented
> We'll look forward to other presented solutions.

For references, it's traced in https://github.com/zephyrproject-rtos/zephyr/pull/13260 .

> Shell **is** now able to print asynchronous messages. Is it still an issue?

It seems to work ok in my testing of https://github.com/zephyrproject-rtos/zephyr/pull/13260 . Thanks for confirming it's intended usage, @jarz-nordic (I know we discussed all this stuff, but shell kept changing all this time either. With 1.14 going into RC, and shell apparently "complete", it's really good time to finally make a mind snapshot of its properties).