cmake: more deterministic git describe --abbrev=12 --dirty
zephyrproject-rtos/zephyr pull request #13608
Opened 2019-02-21 01:11 UTC by marc-hb

Hardcode --abbrev=12 not to depend on personal git config preference.
12 is deemed large enough for the Linux kernel which should leave some
room:
https://public-inbox.org/git/xmqq37knwcf4.fsf@gitster.mtv.corp.google.com/

Add --dirty because it should be the default: who likes to be duped into
thinking they're debugging an exact version when they're not?

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2019-02-22 09:31 UTC, SebastianBoe requested changes
+1 to --abbrev=12, the build should be system-independent.

-1 to --dirty

I often test patches that I expect will not have an affect on the hex file by doing:

build --build-dir=b_0
git stash
build --build-dir=b_1
kdiff b_0 b_1

without --dirty I can verify that my stashed patch did not corrupt the build, but with --dirty I can not.

Presumably, the BUILD_VERSION exists for non-developers to be able to identify their build, any developer worth his salt will not distribute a build with a dirty working directory, so the --dirty flag is not needed in production, and harmful for developers that test like me.

2019-02-22 18:33 UTC, marc-hb commented
Thanks everyone for the review.

> build --build-dir=b_0
> git stash
> build --build-dir=b_1
> kdiff b_0 b_1
> 
> without --dirty I can verify that my stashed patch did not corrupt the build, but with --dirty I can not.

Interesting, I didn't think of that use case. Making a whitespace change after the git stash would be a simple workaround but I get your point.

To solve the same problem I typically do something "git add builddir/" and revert the source changes "manually" instead of using git stash. Then I can keep using all the same and usual set of git diff options than for source code. For non-trivial commits I tend to want finer-grained "revert" abilities anyway, git stash is too coarse and wouldn't work.

> any developer worth his salt will not distribute a build with a dirty working directory, 

Depending on what you mean by "distribute" this is actually quite frequent, for instance when several people debug the same hardware and change the code (debug statements, others) frequently. Or even just one person interrupted by meetings or other context switches.

Anyway --dirty is unrelated to the this topic so I'll remove it. Maybe I'll try to make it optional in another PR.

2019-02-22 21:11 UTC, marc-hb commented
The last force push doesn't show any difference because github can apparently not compare commit messages. Doh.

2019-02-25 07:54 UTC, mped-oticon approved these changes

2019-02-25 09:17 UTC, SebastianBoe approved these changes

2019-02-26 15:38 UTC, SebastianBoe commented
@carlescufi : This is ready to be merged.

2019-02-27 09:27 UTC, merged