[DNM] Added support to set max I2C message size for data transfers in SSD1306 driver
zephyrproject-rtos/zephyr pull request #13645
Opened 2019-02-21 22:16 UTC by vanwinkeljan

Added support to set maximum I2C message size that can be used in the SSD1306 driver for data transfers. The maximum supported value is retrieved from a KConfig variable as the current I2C API does not provide this info.

Marked PR with DNM as I have now hardware available to test this changes.
@KwonTae-young could you please test this fix?

fixes: #13550

2019-02-21 22:46 UTC, jfischer-no requested changes
no way. This should be fixed in the stm32 driver and not here.

2019-02-21 23:39 UTC, vanwinkeljan commented
> no way. This should be fixed in the stm32 driver and not here.

@jfischer-phytec-iot I had the same thought first but then the I2C API specifies  a lot of warnings (notes) which actually gives me the feeling it is up to the caller of the I2C API to solve the issues.

Added @ldts and @ydamigos as they are the code owners of the stm32 I2C driver

2019-02-22 02:48 UTC, KwonTae-young commented
To test, a branch [stm32f4-disco_ssd1306_with_ssd1306_max_i2c_transfer_size](https://github.com/KwonTae-young/zephyr/tree/stm32f4-disco_ssd1306_with_ssd1306_max_i2c_transfer_size) was created.
I tried it and still get an error.

```
uart:~$
uart:~$ cfb init

Framebuffer initialized: SSD1306
Framebuffer finalize error=-22
uart:~$
uart:~$ cfb print 0 0 1234
Failed to finalize the Framebuffer error=-22
Failed printing to Framebuffer error=-22
uart:~$
```

So I added a debug log.
The size being written is greater than `CONFIG_SSD1306_MAX_I2C_TRANSFER_SIZE`.
```
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_init() 437Line  CONFIG_SSD1306_MAX_I2C_TRANSFER_SIZE=255


uart:~$ cfb init
Framebuffer initialized: SSD1306
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 188Line length=512
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=257
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/i2c/i2c_ll_stm32.c i2c_stm32_transfer() 84Line 257
Framebuffer finalize error=-22
uart:~$
uart:~$ cfb print 0 0 123456
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 188Line length=512
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=257
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/i2c/i2c_ll_stm32.c i2c_stm32_transfer() 84Line 257
Failed to finalize the Framebuffer error=-22
Failed printing to Framebuffer error=-22
uart:~$
```

I have made the following modifications.
``` diff
diff --git a/drivers/display/ssd1306.c b/drivers/display/ssd1306.c
index 1f825979eb..d817eea17a 100644
--- a/drivers/display/ssd1306.c
+++ b/drivers/display/ssd1306.c
@@ -199,7 +199,7 @@ static int ssd1306_i2c_data_write(const struct device *dev, const u8_t *data,
                printk("%s %s() %dLine length=%d\n", __FILE__, __func__, __LINE__, length);
                err = i2c_burst_write(driver->i2c,
                                      DT_SOLOMON_SSD1306FB_0_BASE_ADDRESS,
-                                     cmd, data, length);
+                                     cmd, data, cur_length);
 
        } while ((err == 0) && (length > 0));
 

```

An error does not occur, but something is wrong.
1. stm32f4_disco power on
```
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_init() 437Line  CONFIG_SSD1306_MAX_I2C_TRANSFER_SIZE=255


uart:~$ 
```
![image](https://user-images.githubusercontent.com/10510127/53216303-7ad12800-3697-11e9-912b-36b2e5d4d9d2.png)


2. cfb init
```
uart:~$
uart:~$ cfb init
Framebuffer initialized: SSD1306
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 188Line length=512
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=257
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=2
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=0
Display Cleared
uart:~$
```
![image](https://user-images.githubusercontent.com/10510127/53216349-989e8d00-3697-11e9-8f91-42e2ed7ec917.png)


3. cfb print 0 0 123456
```
uart:~$
uart:~$ cfb print 0 0 123456
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 188Line length=512
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=257
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=2
/work/zephyrproject_stm32_i2c_bug/zephyr/drivers/display/ssd1306.c ssd1306_i2c_data_write() 199Line length=0
uart:~$
```
![image](https://user-images.githubusercontent.com/10510127/53216374-ab18c680-3697-11e9-8a33-7767e8db3a62.png)

2019-02-23 16:26 UTC, ydamigos commented
Hi @vanwinkeljan and @KwonTae-young,

I addressed the issue here: https://github.com/ydamigos/zephyr/commit/b9289fdbc18a2dae80216120d136a9808dd30390

I tested it on my 96b_Carbon + SSD1306 and it works.

@vanwinkeljan Could you merge it to your PR? Github didn't give me the option to create a pull request to your branch.

Because I am moving to a new apartment, I don't have enough time to check the patch properly. @erwango and @avisconti could you please check that the patch doesn't break anything.

2019-02-24 22:08 UTC, vanwinkeljan commented
@ydamigos looks like your commit should replace my PR as it fixesses the issue at the STM32 I2C driver level, as such would it not be better to create a new PR with only your commit on top of master?

2019-02-25 05:40 UTC, ydamigos commented
@vanwinkeljan and @KwonTae-young, I opened PR  #13726.

2019-02-25 09:46 UTC, vanwinkeljan commented
Closed PR as a PR (#13726) is available that fixes the issue at I2C driver level

2019-02-25 09:46 UTC, closed without merging