Documentation for net-shell
zephyrproject-rtos/zephyr pull request #13679
Opened 2019-02-22 14:14 UTC by jukkar

Note that this PR has been built on top of #13616 (so the first commit is from that PR).

2019-02-22 16:47 UTC, nashif approved these changes

2019-02-22 16:53 UTC, dbkinder requested changes
The commit message should also indicate this PR reorganizes the network API documentation (in addition to filling out more net-shell documentation).

2019-02-22 16:53 UTC, dbkinder commented on doc/reference/networking/net_shell.rst
> +Network shell provides helpers for figuring out network statuses,
```suggestion
Network shell provides helpers for figuring out network status,
```

2019-02-22 16:53 UTC, dbkinder commented on doc/reference/networking/net_shell.rst
> +enabling/disabling features and issuing commands like ping or DNS resolving.
```suggestion
enabling/disabling features, and issuing commands like ping or DNS resolving.
```

2019-02-22 16:53 UTC, dbkinder commented on doc/reference/networking/net_shell.rst
> +Following commands are implemented:
```suggestion
The following net-shell commands are implemented:
```

2019-02-22 16:53 UTC, dbkinder commented on doc/reference/networking/net_shell.rst
> +   "net dns", "Show how DNS is configured. The command can also used to
```suggestion
   "net dns", "Show how DNS is configured. The command can also be used to
```

2019-02-24 09:41 UTC, jukkar commented
Updated according to comments.

2019-02-25 18:29 UTC, dbkinder approved these changes

2019-02-26 01:24 UTC, merged