doc: net: Change connectivity API doc to use BSD sockets
zephyrproject-rtos/zephyr pull request #13713
Opened 2019-02-24 12:01 UTC by jukkar

The connectivity API will now point to BSD socket API instead
of legacy connectivity API (net_context.h) when creating
a network application.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2019-02-24 12:36 UTC, nashif approved these changes

2019-02-25 13:16 UTC, pfalcon approved these changes

2019-02-25 18:59 UTC, dbkinder requested changes

2019-02-25 18:59 UTC, dbkinder commented on doc/guides/networking/networking-api-usage.rst
> +used by the applications any more.
```suggestion
used by applications.
```

2019-02-26 07:18 UTC, jukkar commented
Updated according to comments.

2019-02-26 23:47 UTC, dbkinder approved these changes

2019-02-27 01:27 UTC, merged