drivers: can: stm32: Cleanup Kconfig enablement
zephyrproject-rtos/zephyr pull request #13715
Opened 2019-02-24 14:30 UTC by galak

Follow the pattern we have for other peripherals in that if the driver
class (CAN) is enabled than enable the driver for that class
(CAN_STM32).  Also have the STM32 CAN driver depend on being on a STM32
SoC.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2019-02-24 14:35 UTC, galak commented
Here's some output from the build log:

```
[ 22%] Built target subsys__testsuite__ztest
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:46:8: error: variable 'test_std_msg' has initializer but incomplete type
 struct can_msg test_std_msg = {
        ^~~~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:47:3: error: 'struct can_msg' has no member named 'id_type'
  .id_type = CAN_STANDARD_IDENTIFIER,
   ^~~~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:47:13: error: excess elements in struct initializer [-Werror]
  .id_type = CAN_STANDARD_IDENTIFIER,
             ^~~~~~~~~~~~~~~~~~~~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:47:13: note: (near initialization for 'test_std_msg')
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:48:3: error: 'struct can_msg' has no member named 'rtr'
  .rtr     = CAN_DATAFRAME,
   ^~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:48:13: error: excess elements in struct initializer [-Werror]
  .rtr     = CAN_DATAFRAME,
             ^~~~~~~~~~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:48:13: note: (near initialization for 'test_std_msg')
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:49:3: error: 'struct can_msg' has no member named 'std_id'
  .std_id  = TEST_CAN_STD_ID,
   ^~~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:34:30: error: excess elements in struct initializer [-Werror]
 #define TEST_CAN_STD_ID      0x555
                              ^~~~~
/home/galak/git/zephyr/tests/drivers/can/api/src/main.c:49:13: note: in expansion of macro 'TEST_CAN_STD_ID'
  .std_id  = TEST_CAN_STD_ID,
             ^~~~~~~~~~~~~~~
```

2019-02-24 17:17 UTC, nashif approved these changes

2019-02-25 07:51 UTC, jukkar approved these changes

2019-02-25 08:22 UTC, erwango requested changes
Change is fine with me but please complete with existing CONFIG_CAN_STM32 symbol clean up in samples/ and tests/

2019-02-25 14:00 UTC, galak commented
> Change is fine with me but please complete with existing CONFIG_CAN_STM32 symbol clean up in samples/ and tests/

Huh?

2019-02-25 14:37 UTC, erwango approved these changes

2019-02-25 16:05 UTC, merged