lib: json: Fix crashes on xtensa/nios2
zephyrproject-rtos/zephyr pull request #1372
Opened 2017-09-05 23:39 UTC by lpereira

This fixes two issues: alignment not being considered when calculating struct size, and an off-by-one error when serializing an object.

Tested on Linux with both address and behavior sanitizers, and on Zephyr running on qemu_nios2 and qemu_xtensa.

Should fix #1347.

2017-09-05 23:52 UTC, nashif requested changes
remove build_only: true in testcase.yaml, this would verify the fix.

2017-09-06 14:17 UTC, lpereira commented
@mbolivar Do you have any idea how the alignment issue could be fixed? I'm not really happy with this way here; it's quite wasteful.

2017-09-06 14:57 UTC, tyrantlizard77 submitted a review, later dismissed
I'm curious about the warnings due to use of anonymous types, since sanitycheck builds with -Werror in what situations do the warnings appear?

2017-09-06 16:11 UTC, andyross commented
Seems sane.  One question.

2017-09-06 19:45 UTC, lpereira commented
@andyross What's the question?

@andrewboie I built this with `-Wextra` while debugging on Linux, so that's where the warning came from.

2017-09-06 23:23 UTC, andyross submitted a review, later dismissed
(Sorry, left my inline comment in a "review" and then posted a new "comment" leaving this stranded)

2017-09-06 23:32 UTC, lpereira commented on lib/json/json.c
> +				total += s;
Indeed. Pushed a new version that does `ROUND_UP(s, descr->alignment)` unconditionally.

2017-09-06 23:41 UTC, andyross approved these changes

2017-09-07 10:49 UTC, merged