stm32wb: Add BLE support through IPM HCI driver
zephyrproject-rtos/zephyr pull request #13898
Opened 2019-02-27 14:11 UTC by erwango

Add BLE support on nucleo_wb55rg thanks to indroduction of HCI driver.

This pull request is an early work to get feedback on HCI driver implementation.

Based on #13742

2019-03-02 12:02 UTC, jhedberg requested changes
Some initial feedback on the HCI driver

2019-03-02 12:02 UTC, jhedberg commented on drivers/bluetooth/hci/ipm_stm32wb.c
> +void stm32wb_start_ble(void)
Seems like this should be static?

2019-03-04 09:53 UTC, erwango commented on drivers/bluetooth/hci/ipm_stm32wb.c
> +	err = bt_hci_cmd_send_sync(ACI_WRITE_SET_TX_POWER_LEVEL, NULL, &rsp);
Right, fixed, txs

2019-03-04 09:54 UTC, erwango commented
@jhedberg , txs for initial review, comments fixed.

2019-03-08 10:10 UTC, closed without merging