x86: mitigate Lazy FP vulnerability
zephyrproject-rtos/zephyr pull request #14013
Opened 2019-03-02 23:09 UTC by andrewboie

Also organized the set of Kconfigs relative to speculative CPU vulnerabilities a bit.

See:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-3665
https://en.wikipedia.org/wiki/Lazy_FP_state_restore

2019-03-03 15:11 UTC, ulfalizer requested changes

2019-03-03 20:06 UTC, andrewboie commented on arch/x86/Kconfig
> +
> What does it mean if you turn off FP_SHARING in arch/Kconfig and then enable e.g. LAZY_FP_SHARING?

LAZY_FP_SHARING should depend on FP_SHARING always.
EAGER_FP_SHARING doesn't, it's also needed for systems where just one thread is using the FPU (FLOAT + !FP_SHARING)

It's a little complicated with what gets enabled where.

If USERSPACE is disabled, or the CPU is immune to this vulnerability:
FLOAT should be enabled if one thread uses the FPU.
FLOAT + FP_SHARING should be enabled if multiple threads are using the FPU, and using LAZY_FP_SHARING is the default since it is much faster.

If USERSPACE is enabled on a CPU which is vulnerable, and FLOAT is enabled, then EAGER_FP_SHARING is the default since it is secure, regardless if one thread or multiple are using the FPU (FP_SHARING)

2019-03-03 21:28 UTC, ulfalizer commented on arch/x86/Kconfig
> +
> LAZY_FP_SHARING should depend on FP_SHARING always.

Currently it doesn't. The user can still turn on `LAZY_FP_SHARING` when `FP_SHARING` is off (can try it out in the `menuconfig`).

For symbols with prompts, `default` just determines the default value. It doesn't influence what values the user can set. Maybe `LAZY_FP_SHARING` is ignored anyway if `FP_SHARING` is unset, but it looks confusing. Might want to add a `depends on FP_SHARING` to `LAZY_FP_SHARING`.

It's also possible for both `EAGER_FP_SHARING` and `LAZY_FP_SHARING` to be disabled. Should make sure that makes sense.

2019-03-03 21:31 UTC, ulfalizer commented on arch/x86/Kconfig
> +
In general, I know many people never use the `menuconfig`, but it's a good idea to check that the stuff the user can do in it makes sense still. It's a good sanity check for dependencies too. :)

2019-03-03 21:40 UTC, ulfalizer commented on arch/x86/Kconfig
> +
Maybe a `choice` could be handy here.

2019-03-03 22:03 UTC, ulfalizer commented on arch/x86/Kconfig
> +
Thinking something like this (with no `EAGER_FP_SHARING`):

```
config LAZY_FP_SHARING
	bool "Floating point register sharing (lazy state switching)"
	default y if !USERSPACE
	depends on FP_SHARING
	help
	  If enabled, lazy FP sharing is used. If disabled, eager FP sharing is
	  used. ...
```

`default y if !USERSPACE` could be condensed down to `default !USERSPACE` btw, but to keep it consistent with other stuff.

2019-03-04 20:35 UTC, andyross approved these changes
F{N,X}{SAVE,RSTOR} usage looks correct.  Keeping my head down about the kconfig stuff.

2019-03-04 22:32 UTC, dcpleung approved these changes

2019-03-08 22:33 UTC, andrewboie commented on arch/x86/Kconfig
> +
thanks for the feedback. new revision to be posted soon.

2019-03-11 17:10 UTC, andrewboie commented on arch/x86/Kconfig
> +
OK I've updated this.

LAZY_FP_SHARING now explicitly depends on FP_SHARING.
Both LAZY and EAGER_FP_SHARING are now hidden options, as it doesn't make sense if CONFIG_FP_SHARING is enabled and neither are enabled; a choice doesn't work so well as the two options don't have the same set of dependencies.

2019-03-11 21:50 UTC, andrewboie commented
@ulfalizer please let me know how this latest iteration looks to you.

2019-03-11 22:06 UTC, ulfalizer approved these changes
Still wondering if a single symbol might be enough here, since these seem to be mutually exclusive.

These definitions are equivalent to this btw, just as an added sanity check:

```
config EAGER_FP_SHARING
	...
	default y if !X86_NO_LAZY_FP && FLOAT && USERSPACE
        ...

config LAZY_FP_SHARING
	...
	default y if (X86_NO_LAZY_FP || !USERSPACE) && FLOAT && !EAGER_FP_SHARING && FP_SHARING
	...
```

(Though the `depends on` would come in if they're ever `select`ed.)

2019-03-11 22:08 UTC, andrewboie commented
> Still wondering if a single symbol might be enough here, since these seem to be mutually exclusive.

The thing that gets in the way is that for affected systems, we need EAGER_FP_SHARING turned on even if just CONFIG_FLOAT is enabled. On an unaffected system, where CONFIG_FLOAT=y and only one thread is using the FPU, no sharing logic is required at all.

2019-03-12 03:36 UTC, merged