kernel: enhance ducumentation of z_arch_buffer_validate
zephyrproject-rtos/zephyr pull request #14441
Opened 2019-03-12 23:34 UTC by ioannisg

This commit enhances the documentation of z_arch_buffer_validate
describing the cases where the validation is performed
successfully, as well as the cases where the result is
undefined.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2019-03-12 23:35 UTC, ioannisg commented
I 'm not so familiar, @andrewboie , with writing kernel API documentation, so I appreciate your feedback here.

2019-03-12 23:40 UTC, tyrantlizard77 approved these changes

2019-03-12 23:41 UTC, andrewboie commented
This looks fine.
It may be worthwhile to also leave a note under doc/..../syscalls.rst

2019-03-12 23:44 UTC, andrewboie commented
Btw there is a typo in the patch subject line 'ducumentation'

2019-03-12 23:47 UTC, ioannisg commented
> 
> 
> This looks fine.
> It may be worthwhile to also leave a note under doc/..../syscalls.rst

Sure, i am going to do that.

2019-03-12 23:52 UTC, dbkinder requested changes
so close...

2019-03-12 23:52 UTC, dbkinder commented on kernel/include/kernel_internal.h
> + * In some architectures the validation is will always return failure,
```suggestion
 * In some architectures the validation will always return failure
```

2019-03-13 07:32 UTC, ioannisg commented on kernel/include/kernel_internal.h
> + * In some architectures the validation is will always return failure,
Fixed now.

2019-03-13 08:37 UTC, ioannisg reviewed
Fixed the minor style issue and added one more commit, to correctly
document the arguments in Z_SYSCALL_MEMORY macros.
@dbkinder please, re-review.

2019-03-13 21:58 UTC, dbkinder approved these changes

2019-03-13 22:36 UTC, merged