Bluetooth: Mesh: Increase advertising thread stack size
zephyrproject-rtos/zephyr pull request #14680
Opened 2019-03-19 15:19 UTC by erwango

With BT_HOST_CRYPTO, advertising stack size could be overflowed,
increase size to 1024 when BT_HOST_CRYPTO is enabled.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

2019-03-19 15:21 UTC, jhedberg requested changes

2019-03-19 15:21 UTC, jhedberg commented on subsys/bluetooth/host/mesh/adv.c
> +#ifdef CONFIG_BT_HOST_CRYPTO
minor thing: we've tried to be consistent with `#if defined(CONFIG_...)` in the Bluetooth code, could you please do that? (benefit is that you can combine multiple `defined(...)` conditions for a single `#if` but not with `#ifdef`)

2019-03-19 15:24 UTC, jhedberg approved these changes

2019-03-20 07:26 UTC, jhedberg commented
@sjanc @Vudentz @carlescufi could we get a second review on this? A month ago or so it was discovered that the stack requirement for advertising had grown, see commit 1cfa12276c3723f0b84401454e65ba2e5956828b, however turns out we still need the conditionally higher size for BT_HOST_CRYPTO.

2019-03-20 10:02 UTC, carlescufi approved these changes
No objections

2019-03-26 02:51 UTC, merged