USB: Fix warning in DFU class
zephyrproject-rtos/zephyr pull request #14699
Opened 2019-03-20 09:47 UTC by Qbicz

Move unused variable to scope where it is used.

Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>

2019-03-20 09:49 UTC, Qbicz commented
When using USB DFU in a composite device, variable `ret` is unused.

2019-03-20 09:52 UTC, finikorg requested changes
I think we do not use this methods, however you might want to use 
```
if (IS_ENABLED()) {
}
```

2019-03-20 09:55 UTC, Qbicz commented
@finikorg what do you mean? Do you say to keep variable declaration at the top of function block, but enclose it in `IS_ENABLED(CONFIG_USB_COMPOSITE_DEVICE)`?

2019-03-20 09:56 UTC, finikorg commented
> @finikorg what do you mean? Do you say to keep variable declaration at the top of function block, but enclose it in `IS_ENABLED(CONFIG_USB_COMPOSITE_DEVICE)`?

Yes, exactly

2019-03-20 10:09 UTC, Qbicz commented
@finikorg why not? There are already numerous examples of declaring variables in the middle of the block in Zephyr kernel, but not to look far there is https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/class/hid/core.c#L150 in USB. It's good to keep the variables as local as possible, and Zephyr will not compile with C89 anyway.

But if you prefer to keep it, I can do as you suggest.

2019-03-20 10:35 UTC, finikorg commented
I think this is a bad example, some people do not like it 
https://github.com/zephyrproject-rtos/zephyr/pull/9691#discussion_r256412908

2019-03-20 10:55 UTC, Qbicz commented
@finikorg I made changes according to your suggestion.

2019-03-20 10:58 UTC, finikorg approved these changes

2019-03-20 10:59 UTC, masz-nordic approved these changes

2019-03-20 12:17 UTC, jfischer-phytec-iot commented
>I think this is a bad example, some people do not like it
#9691 (comment)

I suggest to look at it more differentiated. The first commit was much easier, more readable and and has changed less code, I am for the first suggestion. And, maintainer preferences may vary from subsystem to subsystem ;-).

2019-03-20 12:17 UTC, jfischer-no approved these changes

2019-03-21 09:59 UTC, pawelzadrozniak approved these changes

2019-03-26 10:21 UTC, carlescufi approved these changes

2019-03-26 10:21 UTC, merged