Make errno protocol compatible with Newlib
zephyrproject-rtos/zephyr pull request #147
Opened 2017-05-10 21:02 UTC by pfalcon

This patch makes it possible to use errno in apps built with CONFIG_NEWLIB_LIBC=y.

Issue found when coding BSD Sockets API.

2017-05-10 21:09 UTC, nashif requested changes
Duplication not required, you can build the original test with a different configuration, just a new entry into the testcase.ini and make it use a different configuration enabling newlib.

2017-05-10 21:29 UTC, pfalcon commented
@nashif : Reworked per the suggestion.

2017-05-10 21:41 UTC, tyrantlizard77 approved these changes

2017-05-11 00:54 UTC, nashif approved these changes

2017-05-11 00:54 UTC, merged