Improve test harness ability to track test runs in  samples/drivers/soc_flash_nrf/ and  samples/subsys/power/device_pm
zephyrproject-rtos/zephyr pull request #14701
Opened 2019-03-20 10:21 UTC by cinlyooi-intel

Changing from default test harness to  `harness: console` to allow test harness to track progress of the test run.

2019-03-20 11:18 UTC, pizi-nordic approved these changes

2019-03-20 13:14 UTC, nvlsianpu approved these changes

2019-03-29 13:27 UTC, nashif requested changes

2019-03-29 13:27 UTC, nashif commented on samples/drivers/soc_flash_nrf/sample.yaml
>    test:
This need to be moved to become a test. The matching below does not work with sanitycheck and is error-prone.

2019-03-29 13:27 UTC, nashif commented on samples/subsys/power/device_pm/sample.yaml
> +        - "transfer()"
duplicate lines do not work with sanitycheck matching, so this will fill due to the duplicate transfer() lines.

2019-04-02 10:23 UTC, cinlyooi-intel commented
@nashif : Thank you for the comments. I will withdraw this PR for a rethink and resubmit

2019-04-02 10:23 UTC, closed without merging