Xtensa fixes
zephyrproject-rtos/zephyr pull request #148
Opened 2017-05-10 21:02 UTC by andrewboie

Miscellaneous fixes for Xtensa architecture.

2017-05-10 21:22 UTC, lpereira submitted a review, later dismissed
Can't comment on XCC-related changes, but the change inside kernel_arch_thread.h seem correct.

2017-05-10 22:01 UTC, nashif submitted a review, later dismissed

2017-05-11 10:03 UTC, mazen-neifer requested changes

2017-05-11 10:03 UTC, mazen-neifer commented on include/toolchain.h
> +#if defined(XCC_COMPILER)
I would avoid adding a new compiler flag.
I would use __XCC__ builtin instead

2017-05-11 10:03 UTC, mazen-neifer commented on scripts/Makefile.toolchain.xcc
> +		   -D'XCC_COMPILER=1'
I'd remove this and use __XCC__ builtin in above change

2017-05-11 10:05 UTC, mazen-neifer approved these changes

2017-05-11 16:47 UTC, nashif approved these changes

2017-05-11 16:47 UTC, merged