usb: cdc_acm: SerialState notification full support
zephyrproject-rtos/zephyr pull request #14933
Opened 2019-03-27 11:27 UTC by masz-nordic

Added bBreak, bRingSignal, bFraming, bParity and bOverRun
handling in cdc_acm_line_ctrl_set.
Reference: Chapter 6.5.4 of Universal Serial Bus Communications Class
Subclass Specification for PSTN Devices rev 1.2

Signed-off-by: Marcin Szymczyk <Marcin.Szymczyk@nordicsemi.no>

2019-04-17 09:16 UTC, jfischer-no requested changes

2019-04-17 09:16 UTC, jfischer-phytec-iot commented on include/usb/class/usb_cdc.h
> +#define USB_CDC_LINE_CTRL_BREAK		(1 << 5)
You can use BIT macro from util.h.

2019-04-18 13:32 UTC, jfischer-no approved these changes

2019-04-19 10:29 UTC, finikorg approved these changes

2019-04-19 18:36 UTC, merged