net: Enable logging in more modules if CONFIG_NET_LOG_GLOBAL defined
zephyrproject-rtos/zephyr pull request #1523
Opened 2017-09-15 20:34 UTC by pfalcon

This is useful to enable error/warning logging across the net
codebase (less useful for debug level logging, but that's true
for CONFIG_NET_LOG_GLOBAL already).

Implementation-wise, instead of keeping adding to long list of
"select"'s in CONFIG_NET_LOG_GLOBAL and thus introduce component
inter-dependencies, add "default y if NET_LOG_GLOBAL" to
individual components' logging options.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

2017-09-15 20:35 UTC, pfalcon commented
This is rework of https://github.com/zephyrproject-rtos/zephyr/pull/1507 using @tbursztyka's suggestion.

2017-09-17 18:16 UTC, nashif approved these changes

2017-09-18 06:54 UTC, tbursztyka requested changes
For better consistency, I think you will need to do the same change for all the options currently listed in config NET_LOG_GLOBAL, and remove the select of those there.

2017-09-18 10:46 UTC, pfalcon commented
> For better consistency, I think you will need to do the same change for all the options currently listed in config NET_LOG_GLOBAL, and remove the select of those there.

How about doing it step by step, minimizing the amount on big changes on each?

2017-09-18 11:42 UTC, tbursztyka commented
Sure, either way. You can add another commit on this PR

2017-09-18 12:10 UTC, tbursztyka approved these changes

2017-09-18 12:19 UTC, merged