Bluetooth: controller: Fix control procedure sequencing
zephyrproject-rtos/zephyr pull request #15320
Opened 2019-04-10 07:52 UTC by cvinayak

Fix the controller implementation to make start encryption
queue-able if there is any control procedure in progress.

The context related to encryption procedure is not shared so
that it will be used as the ongoing procedure completes.

The fix here maintains the old functionality of serializing
the queued data and LL Encryption Request PDU, so that data
queued before start encryption is acknowledged.

Fixes #15012.

Fix implementation to correctly cache the control procedures
initiatable by local and peer. And, fix feature exchange and
version information procedures from being disallowed by
having then as cached requests to the controller.

Relates to #15256.

2019-06-07 13:54 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		if (conn->llcp_feature.ack != conn->llcp_feature.req) {
yes. and I have added it.

2019-06-11 11:18 UTC, aescolar commented
@joerchan : Could you take a look and approve if it is ok?

2019-06-11 11:18 UTC, aescolar commented
@thoh-ot Could you also please take a look?

2019-06-12 13:16 UTC, joerchan requested changes
It would be helpful to rebase this PR to get the queueing of Encryption procedure in.

I think currently conn_param_update and channel_map_update can receive disallowed while encryption procedure is active (or other, ping etc).

I think it would be cleaner to use llcp_<phy/length/conn_param_req/feature>.ack/req to set the procedures pending, and use llcp_ack/req to for when a procedure is active, and set llcp_type to the active procedure.
Currently encryption works like this. but version ind/feature exchange does not. There seems to be a mix between alle the procedures.
That makes it really hard to check if a procedure is currently in progress or not. leading to some complex statements to check for procedure collision.
I suggest we simplify the design, it makes it much easier to validate that it is bug-free.

2019-07-09 08:14 UTC, joerchan commented
Checked that type 3 of #15256 will be fixed by this PR as well.

2019-08-25 13:48 UTC, maz3max commented
@joerchan My application currently works with the branch of this PR. In this config, the central requests encryption right at the start, while the peripheral doesn't. This does **not** work with upstream currently.
When I apply the changes of this PR to upstream, it also doesn't work, meaning it seems to be **incompatible** with upstream.

2019-08-26 04:54 UTC, cvinayak commented
@maz3max could please give more details, does your application behave as expected with controller built using this PR branch? and it does not on upstream/master (which by default is new controller (which does not have the changes in this PR ported yet)?

2019-08-27 23:45 UTC, maz3max commented
> @maz3max could please give more details, does your application behave as expected with controller built using this PR branch? and it does not on upstream/master (which by default is new controller (which does not have the changes in this PR ported yet)?

Yes, my application works as expected with the controller built using this PR branch. (There is a feature missing which was added in upstream and was commented out.)
The **key feature** that I want to use is to enable encryption right after connecting. This is what currently not possible with upstream or the unpatched old controller.

2019-08-28 14:31 UTC, cvinayak commented
@maz3max  Thanks. I will keep you posted if I have updates on the porting to upstream/master.

2019-09-03 11:37 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +#if defined(CONFIG_BT_CTLR_CONN_PARAM_REQ) || \
Agreed. Will remove the cond. compile.

2019-09-03 11:37 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		conn->llcp_feature.req = 0U;
Not all of the big struct needs zero-initialization.

2019-09-03 11:37 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		} else if (conn->llcp_version.ack != conn->llcp_version.req) {
Added checks in is_enc_req_pause_tx. Regarding the isr_rx_conn_pkt_ctrl, check there is not required as feature and/or version procedure is only cached and it is not a procedure collision.

2019-09-04 14:21 UTC, joerchan requested changes
This seems to fix the Procedure collision between the feature exchange and the encryption procedure.

However it seems to be unstable, running connection and encrypt in a loop it ends up with an failure after a while. This seems related the SMP pairing instability issue reported elsewhere.
After a while the slave disconnects with an "LLCP timeout (0x22)"
From the sniffer log in this connection there was a single LL_FEATURE_REQ sent from master to slave.
No other traffic observed.

2019-09-05 08:55 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +	conn->llcp_version.req++;
The check is handled in event_vex_prep. If already exchanged, then local host gets the info without on-air PDU transmission. It had to go through event_vex_prep in order to be able to generate (HCI) event back to host.

2019-09-05 10:49 UTC, joerchan commented on subsys/bluetooth/controller/ll_sw/ctrl.c
> +		    ((conn->llcp_req == conn->llcp_ack) &&
The following statements mean that "no procedure is active, but procedures are pending" In which we would actually start the procedure?

2019-09-05 11:14 UTC, joerchan approved these changes

2019-09-05 13:42 UTC, carlescufi approved these changes

2019-09-06 10:32 UTC, jhedberg approved these changes

2019-09-07 15:10 UTC, merged