usb: class: dfu: fix dfu mode with composite device enabled
zephyrproject-rtos/zephyr pull request #15360
Opened 2019-04-11 13:49 UTC by pawelzadrozniak

When the device enters DFU mode, the descriptor set is switched
to DFU-specific. Device descriptor must match the previous one,
otherwise dfu-util will report an error. DFU descriptor was
missing a variant for composite device mode (currently composite
device mode has a special implementation in ifdefs - to be
refactored in future) causing a mismatch - composite before
DFU_DETACH and non-composite after.

Fixes #14882

Signed-off-by: Paweł Zadrożniak <pawel.zadrozniak@nordicsemi.no>

2019-04-11 13:53 UTC, Qbicz commented
Thanks @pawelzadrozniak, I'm testing it right now

2019-04-11 14:17 UTC, jfischer-no requested changes
No, I do not think so. After DFU_DETACH the device is not composite one.

2019-04-12 09:48 UTC, Qbicz approved these changes
For me this fixes losing the device after USB reset as described in #14882
```
dfu-util: Lost device after RESET?.
```
I was able to perform upload and download with usb/dfu sample with CONFIG_USB_COMPOSITE_DEVICE=y

2019-04-12 09:50 UTC, Qbicz commented
@jfischer-phytec-iot I wonder why you couldn't reproduce the #14882 on nrf52840_pca10056 on master. We could reproduce it on different computers, on Windows and Linux, on different boards. Any ideas what could be the difference? And if device is not composite after DFU_DETACH how to fix this problem?

2019-04-12 11:42 UTC, Qbicz commented
@pawelzadrozniak @jfischer-phytec-iot with this fix I was able to do the DFU download in a composite device also with other classes enabled: e.g. in usb/hid-mouse sample with mcuboot + HID class + DFU class + composite.

However, now I see that this is not background DFU, at least when we go from runtime mode into DFU mode other classes cannot communicate with host (e.g. sending HID events). Is is possible to use other USB classes during the DFU or is it this way by design?

2019-04-12 12:38 UTC, jfischer-phytec-iot commented
@Qbicz Can you please tell me version of dfu-util, OS and OS version you testing on?

2019-04-12 12:47 UTC, Qbicz commented
@jfischer-phytec-iot I have tested on:
- Windows 7 Professional SP1 with WinUSB v6.1.7600 and dfu-util 0.9.
- Ubuntu 16.04 with dfu-util 0.8 and dfu-util 0.9. I can later check version of driver on Ubuntu.

Also @pawelzadrozniak reproduced this issue on his computer.

2019-04-12 14:17 UTC, jfischer-phytec-iot commented
>Is is possible to use other USB classes  during the DFU or is it this way by design?

Hmmm, I had not in mind one would wish it. The next step after download would be to reset the device and mcuboot would try to swap the images. Updating is not regular state of the device, I also see it unusual to have dfu present in application mode and suggest to use it together with bootloader.

2019-04-12 14:18 UTC, jfischer-phytec-iot commented
@Qbicz 
>Ubuntu 16.04 with dfu-util 0.8 and dfu-util 0.9. I can later check version of driver on Ubuntu.

as gast or native?

2019-04-15 06:16 UTC, Qbicz commented
> as gast or native?

As guest. Driver on Ubuntu is libusb-1.0-0/xenial,now 2:1.0.20-1 amd64 [installed,automatic]

> Updating is not regular state of the device, I also see it unusual to have dfu present in application mode and suggest to use it together with bootloader.

Of course USB DFU can be used in bootloader, we also support such scenario (USB recovery). However, in some use cases when we already have USB stack in application, we don't want to have another copy of USB stack in bootloader (memory space reasons). Application can just download the image and switch to bootloader, which knows nothing about USB.

2019-04-15 06:25 UTC, Qbicz commented
@jfischer-phytec-iot Anyway, right now let's don't worry about background operation; USB update is quick, much much quicker than update over BLE. For now, what matters is the composite device proper operation during DFU.

2019-05-08 10:41 UTC, masz-nordic commented
@Qbicz @jfischer-phytec-iot 
Is this PR still valid or should it be closed?

2019-05-08 10:51 UTC, Qbicz commented
@masz-nordic, For me this was the only way to fix #14882. The problem with DFU in composite configuration was reproduced by @barsok but was not reproduced by @jfischer-phytec-iot.

Recently I was not working on USB class DFU, so I can check on latest master if this is still needed to make DFU in composite device detected after reset. Otherwise, I will reopen #14882.

2019-05-22 09:24 UTC, carlescufi commented
Closing since this is not applicable after merging https://github.com/zephyrproject-rtos/zephyr/pull/15818

2019-05-22 09:24 UTC, closed without merging