net: lwm2m: fix automatic notification frequency
zephyrproject-rtos/zephyr pull request #15441
Opened 2019-04-13 11:36 UTC by pieterjanc

This fixes the issue where observations are automatically reported using
the minimum period instead of the maximum. This causes notifications to
be sent more frequently than configured when the resource does not change.

Signed-off-by: Pieterjan Camerlynck <pieterjan.camerlynck@gmail.com>

2019-04-13 14:22 UTC, mike-scott requested changes
We cannot use maximum here.  Due to network latency the notifications would always arrive late.

Let me look at specification to determine recommendation.

2019-04-14 15:37 UTC, therealprof commented
@mike-scott The code now matches what the comment above says.

2019-04-14 18:34 UTC, pieterjanc commented
> Notes: The Maximum Period Attribute indicates the maximum time in seconds the LwM2M Client MAY wait between two notifications. When this “Maximum Period” expires after the last notification, a new notification MUST be sent. In the absence of this parameter, the “Maximum Period” is defined by the Default Maximum Period when set in the LwM2M Server Account or considered as 0 otherwise. The maximum period parameter MUST be not smaller than the minimum period parameter otherwise it will be ignored for the Resource to which such inconsistent Timing Conditions applied.
(http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf)

It does not say anything about checking the timing on server side. The timing should not really be impacted by (constant) latency, but packets could indeed arrive late. Do you know of server implementations checking the notification timing?

2019-06-28 22:01 UTC, mike-scott approved these changes
After re-reading this change, I think it *is* correct.  Otherwise we would never hit the maximum wait time for an observe.

2019-06-28 22:02 UTC, mike-scott commented
@pieterjanc also, I should apologize for the length delay in review.  My work has been very busy and I've also just returned from vacation.  This shouldn't happen again, and I appreciate your patience.

2019-07-01 07:36 UTC, jukkar approved these changes

2019-07-01 07:36 UTC, merged