ssd1306: added support for 128*32 oled
zephyrproject-rtos/zephyr pull request #15783
Opened 2019-05-01 08:44 UTC by tbultel

Adds support for 128*32 oled displays.
The MUX parameter depends on the height of
the display, and the pads config must ber sequential.

Signed-off-by: Thierry Bultel <thierry.bultel@iot.bzh>

2019-05-04 09:36 UTC, vanwinkeljan requested changes

2019-05-04 09:36 UTC, vanwinkeljan commented on drivers/display/ssd1306.c
> +	if (DT_SOLOMON_SSD1306FB_0_HEIGHT == 32)
The COM Pins Hardware Configuration is panel depended and is not depended on the panel height.
Please  add multiple display panel support to this driver (see SSD1673 driver).

2019-05-21 12:45 UTC, jfischer-no requested changes

2019-05-21 12:45 UTC, jfischer-phytec-iot commented on drivers/display/ssd1306.c
> +	u8_t comPins;
coding style, see https://docs.zephyrproject.org/latest/contribute/index.html#coding-style

2019-05-22 22:35 UTC, microbuilder commented
I can test this PR since I have the displays on hand, but first need to look into https://github.com/zephyrproject-rtos/zephyr/issues/15116 which prevents these display from working with I2C on the nRF52 SoC family.

2019-09-19 08:06 UTC, jfischer-phytec-iot commented
already fixed by #19073

2019-09-19 08:06 UTC, closed without merging