disk: fixing the sending of commands with r1 response
zephyrproject-rtos/zephyr pull request #15790
Opened 2019-05-01 17:02 UTC by lucaspeixotot

The sdhc_cmd_r1_raw() function doesn't take into account the existence
of commands with data response. Because of this, some datas were being
lost.

The commands that return a r1 response and a data are: SDHC_SEND_CSD,
SDHC_SEND_CID, SDHC_READ_SINGLE_BLOCK, SDHC_READ_MULTIPLE_BLOCK,
SDHC_WRITE_BLOCK, SDHC_WRITE_MULTIPLE_BLOCK.

In order to solve this, was juts necessary skip the byte discard when
the command is one of these.

This problem was affecting, for example, the sdhc initialization. The
token returned from SDHC_SEND_CSD was being lost and the initialization
was broken.

Fixes #15444.

Signed-off-by: Lucas Peixoto <lucaspeixotoac@gmail.com>

2019-05-07 17:38 UTC, nashif commented
do we have a PR against master? Can you please open an issue for 1.14.

2019-06-04 17:39 UTC, lucaspeixotot commented
> do we have a PR against master? Can you please open an issue for 1.14.

Do I need to create another PR, this time against master, beyond this?

2019-06-18 17:47 UTC, ioannisg commented
Needs a rebase onto master

2019-07-18 20:59 UTC, pabigot requested changes
Needs to be rebased (the file was renamed, as was the function), but this works and needs to go in.

2019-07-18 21:00 UTC, pabigot commented
> Needs to be rebased (the file was renamed, as was the function), but this works and needs to go in to fix #17657.

I can push the rebase if necessary.

2019-07-22 01:43 UTC, lucaspeixotot commented
> > Needs to be rebased (the file was renamed, as was the function), but this works and needs to go in to fix #17657.
> 
> I can push the rebase if necessary.

Please, push the rebase. Thanks in advance.

2019-07-22 11:13 UTC, pabigot commented
@lucaspeixotot Sorry, turns out I can't push to this PR.  So I added a new PR to replace this, and will handle the backport as well.  Thanks for providing the fix.

2019-07-22 11:13 UTC, closed without merging