Bluetooth: controller: Increase advertising random delay resolution
zephyrproject-rtos/zephyr pull request #15803
Opened 2019-05-02 06:13 UTC by cvinayak

Increase the resolution of advertising random delay from
1 ms unit to 1 ticker unit.

Relates to #10289, #10391, and #10398.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2019-05-02 11:34 UTC, carlescufi approved these changes

2019-05-02 11:59 UTC, aescolar reviewed
Just a very minor nit (Which you dont even need to fix for this commits, but may want to account for in future PRs): when porting a fix to the split link layer you may want to say in the commit description that it applies to it (otherwise it may start getting confusing when there is several commits which claim to fix the same thing)

2019-05-02 14:23 UTC, mtpr-ot commented on subsys/bluetooth/controller/ll_sw/ull_adv.c
> +		random_delay %= HAL_TICKER_US_TO_TICKS(10000);
I don't think u16_t will work for sub-microsecond tick configurations. I suggest changing the type to u32_t, in which case it will work for us.

2019-05-02 14:24 UTC, mtpr-ot requested changes
Please change type for randomized integer.

2019-05-02 15:38 UTC, cvinayak commented
@mtpr-ot changed to u32_t.

2019-05-03 05:38 UTC, mtpr-ot approved these changes
OK

2019-05-03 12:33 UTC, merged