api: dma: add circular buffer support
zephyrproject-rtos/zephyr pull request #15885
Opened 2019-05-03 17:33 UTC by jli157

Add one more bitfield to support buf configuration, thus
to support using circular buffer config.

And implement circular buffer support for STM32 SoCs.

Signed-off-by: Jun Li <jun.r.li@intel.com>

2019-05-03 18:18 UTC, jli157 commented
@erwango Please help to review. Thanks!

2019-05-06 12:53 UTC, erwango commented
@cybertale can you review?

2019-05-06 16:26 UTC, cybertale commented
Hi, in reference maunals of STM32, circular mode is explained as 'reloading address pointer'. As an example from RM0090, it is explained as:

> When the circular mode is activated, the number of data items to be transferred is
> automatically reloaded with the initial value programmed during the stream configuration
> phase, and the DMA requests continue to be served.

And there are two configuration options in 'struct dma_block_config', which is 'source_reload_en' and 'dest_reload_en', I think these two options can just do the job, right? For STM32 series SOCs, these two options have to be enabled and disabled togather since circular mode in STM32 reload both dest and src address pointers.

2019-05-06 19:03 UTC, jli157 commented
> Hi, in reference maunals of STM32, circular mode is explained as 'reloading address pointer'. As an example from RM0090, it is explained as:
> 
> > When the circular mode is activated, the number of data items to be transferred is
> > automatically reloaded with the initial value programmed during the stream configuration
> > phase, and the DMA requests continue to be served.
> 
> And there are two configuration options in 'struct dma_block_config', which is 'source_reload_en' and 'dest_reload_en', I think these two options can just do the job, right? For STM32 series SOCs, these two options have to be enabled and disabled together since circular mode in STM32 reload both dest and src address pointers.

Hmm, it seems a good idea to use the fields `source_reload_en` and `dest_reload_en` for enabling the circular mode. However, STM32 seems not to differentiate them: either enabling both or disabling both. it just restarts the transfer once the register `DMA_SxNDTR` hits zero.

2019-05-07 08:47 UTC, avisconti commented
> > Hi, in reference maunals of STM32, circular mode is explained as 'reloading address pointer'. As an example from RM0090, it is explained as:
> > > When the circular mode is activated, the number of data items to be transferred is
> > > automatically reloaded with the initial value programmed during the stream configuration
> > > phase, and the DMA requests continue to be served.
> > 
> > 
> > And there are two configuration options in 'struct dma_block_config', which is 'source_reload_en' and 'dest_reload_en', I think these two options can just do the job, right? For STM32 series SOCs, these two options have to be enabled and disabled together since circular mode in STM32 reload both dest and src address pointers.
> 
> Hmm, it seems a good idea to use the fields `source_reload_en` and `dest_reload_en` for enabling the circular mode. However, STM32 seems not to differentiate them: either enabling both or disabling both. it just restarts the transfer once the register `DMA_SxNDTR` hits zero.

To be honest I think the purpose of `source_reload_en` and `dest_reload_en` was a little different, but maybe we can use them for this purpose. Nevertheless, it seems to me more clear to have a separate flag like this commit does (DMA_BUF_CFG_CIRCULAR).

2019-05-07 09:02 UTC, cybertale commented
@avisconti I agree with aa standalone option for this mode, but I'm worried that if this feature is generic enough for ADC's api. I'm thinking it may be better to have a 'void *args' parameter pointing to a DMA controller related structure to convey these special options in dma_config().

2019-05-09 22:59 UTC, jli157 commented
> @avisconti I agree with aa standalone option for this mode, but I'm worried that if this feature is generic enough for ADC's api. I'm thinking it may be better to have a 'void *args' parameter pointing to a DMA controller related structure to convey these special options in dma_config().

So, the client can access any DMA registers through that pointer? Sounds good to developers but the behaviors could be hard to control.

2019-05-10 02:34 UTC, cybertale commented
@jli157 What I'm thinking is that they pass driver specific structure like what the clock control subsystem of stm32 do. 
There should be a
```
typedef struct{
    bool circular_mode;
    ...
} stm32_dma_properties;
```
in dma_stm32.h or something like that. And when users use dma clients, they pass a pointer pointing to a instance of this structure.
This would be nice for us to add more options that only stm32 has, like double buffer mode.

2019-05-10 02:36 UTC, cybertale commented
So the answer is no, client would not be able to access registers directly or through the pointer, they just pass options.

2019-05-10 03:03 UTC, jli157 commented
> @jli157 What I'm thinking is that they pass driver specific structure like what the clock control subsystem of stm32 do.
> There should be a
> 
> ```
> typedef struct{
>     bool circular_mode;
>     ...
> } stm32_dma_properties;
> ```
> 
> in dma_stm32.h or something like that. And when users use dma clients, they pass a pointer pointing to a instance of this structure.
> This would be nice for us to add more options that only stm32 has, like double buffer mode.

The problem from this way is that a client needs to include a header file inside the driver directory which is kind of internal use. Also, some applications expect driver behaviors agnostic to specific hardware; thus its requirement can't be met by this way.

2019-05-10 03:41 UTC, cybertale commented
From my experience, main usage of dma in stm32 is for stm32's internal IP blocks, ADC, DMA, etc. Other devices or apps using stm32's DMA wouldn't need this parameter so they would need to include that header file. For example, i2s driver of stm32 should include this header, while if some app needs only memory copy, they can pass NULL to this. 
How clock control system works is very similar to this, like polymorphism in object-oriented programming, which could pass an base class object with a sub class object.

2020-07-08 15:22 UTC, erwango commented
@jli157 Is this PR still valid?

2020-07-08 15:23 UTC, erwango requested changes
Requires heavy rebase

2020-07-08 15:24 UTC, jli157 commented
It has been addressed and solved in the current code base. So, I can close this PR.

2020-07-08 15:24 UTC, closed without merging