Add CC13xx / CC26xx I2C support
zephyrproject-rtos/zephyr pull request #15895
Opened 2019-05-03 22:27 UTC by bwitherspoon

Depends on #15302.

Add support for I2C on CC13xx / CC26xx SoCs and boards. This driver is functional, but is still a work in progress until I receive new hardware for testing. It does not yet fully comply with the I2C API.

2019-05-08 20:09 UTC, vanti requested changes

2019-05-10 04:00 UTC, bwitherspoon commented
If you have a BOOSTXL-SENSORS expansion some basic testing can be done with https://github.com/bwitherspoon/zephyr/tree/boostxl_sensors and `west build -b cc1352r1_launchxl zephyr/samples/sensor/bme280/ -- -DSHIELD=boostxl_sensors`.

2019-05-10 20:03 UTC, bwitherspoon commented on drivers/i2c/i2c_cc13xx_cc26xx.c
> +
Added a comment and a note for someone wanting to implement multiple master support.

2019-05-10 20:03 UTC, bwitherspoon commented on drivers/i2c/i2c_cc13xx_cc26xx.c
> +		goto send_error_stop;
I see. That makes sense. Fixed.

2019-05-10 20:03 UTC, bwitherspoon commented on drivers/i2c/i2c_cc13xx_cc26xx.c
> +
Done. Same in other drivers.

2019-05-11 13:42 UTC, bwitherspoon commented
I updated the boards' YAML and documentation to indicate support for I2C.

2019-05-19 15:32 UTC, dbkinder approved these changes
doc changes LGTM, thanks.

2019-05-20 17:26 UTC, vanti approved these changes

2019-05-21 19:37 UTC, nashif approved these changes

2019-05-21 19:37 UTC, merged