drivers: serial: Clarify usage of TX/RX IRQ predicates.
zephyrproject-rtos/zephyr pull request #159
Opened 2017-05-11 15:50 UTC by pfalcon

uart_irq_tx_empty() function proved to be problematic: its semantics
was not documented properly, and many hardware uses terminology like
"TX register empty" to signify condition of TX register being ready
to accept another character (what in Zephyr is tested with
uart_irq_tx_ready()). To avoid confusion, uart_irq_tx_empty() was
renamed to uart_irq_tx_complete(), propagating to drivers/serial
device methods.

The semantics and usage model of all of uart_irq_rx_ready(),
uart_irq_tx_ready(), uart_irq_tx_complete() is now described in
detail.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

2017-05-11 15:53 UTC, pfalcon commented
This implements RFC https://lists.zephyrproject.org/pipermail/zephyr-devel/2017-May/007642.html . Note that this is mechanical replacement of irq_tx_empty to irq_tx_complete. Some drivers clearly (still) don't have correct semantics for tx_ready vs tx_complete, that's the subject of follow-up patches. This patch just clarifies the API.

@daniel-thompson, @erwango : Please review.

2017-05-11 15:54 UTC, nashif requested changes

2017-05-11 15:54 UTC, nashif commented on include/uart.h
>  }
when renaming APIs, please deprecate the old function and keep it in place.

2017-05-11 16:44 UTC, pfalcon commented on include/uart.h
>  }
Done.

2017-05-12 02:05 UTC, nashif commented on include/uart.h
>  }
you need to add attribute __deprecated, doxygen @deprecated is not enough :)
Look at include/dma.h for example.

2017-05-12 11:11 UTC, pfalcon commented on include/uart.h
>  }
Missed that, sorry. Now fixed. Used pwm.h/dma.h as a reference re: placement of `__deprecated`, just in case.

2017-05-13 14:57 UTC, nashif approved these changes

2017-05-13 14:57 UTC, merged