west.yml: add ci-tools project / repository
zephyrproject-rtos/zephyr pull request #15992
Opened 2019-05-07 22:28 UTC by marc-hb

Should make check_compliance.py more popular by removing the steps to
find and clone it and save round-trips to Continous Integration.

Since commit 14e34431dccb each check prints which repo it is checking
which makes this ready to be thrown into a multi-repo world.

revision=master because it's completely optional and cannot break
local builds even if CI is utterly broken.

While check_compliance.py runs only on Linux for now, in the
context of (unrelated) PR #54 I managed to run the Codeowners check
on Windows with a small number of hacks so Windows portability
doesn't seem far away.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2019-05-07 23:21 UTC, nashif requested changes
i thought @ulfalizer  was pulling that back into the zephyr tree. Lets not not confuse people with a repo with a ci specific name.

2019-05-07 23:40 UTC, marc-hb commented
> i thought @ulfalizer was pulling that back into the zephyr tree

I know but I think it's better to preserve and separate git histories, think "divide and conquer" (the... `west`). So I wanted to test and float this alternative which was proposed by some other people some time back.

Another option would be to move back only the check_compliance.py script + any other bit every developer should use but not the CI-specific stuff only admins can use?

> Lets not not confuse people with a repo with a ci specific name.

The name can be anything.

A separate CI repo seems easier to ignore than CI-specific commits in the main git log.

2019-05-08 07:18 UTC, aescolar submitted a review, later dismissed
Just because we can (we have west), it does not mean we should start splitting and pulling zephyr in/from a myriad of tiny repositories.
The drive for multirepo was to split out the `ext/` components mainly due to license and origin issues.
If a script is needed by everybody we should make it available in the main repo (and document it)

2019-05-08 07:22 UTC, aescolar commented
> A separate CI repo seems easier to ignore than CI-specific commits in the main git log.

The "noise" in the commit log would seem to me like a trivially small problem compared to other problems. And not worthwhile trying to fix it creating the extra complexity of adding extra repos for normal users to know about.

2019-05-08 09:35 UTC, mbolivar commented on west.yml
> +      revision: master
This is the default revision, so you can leave it out. Just FYI.

2019-05-08 21:04 UTC, marc-hb commented
> Just because we can (we have west), it does not mean we should start splitting and pulling zephyr in/from a myriad of tiny repositories.

Agreed. This PR would increase the number from 2 to 3.


> The "noise" in the commit log would seem to me like a trivially small problem compared to other problems. And not worthwhile trying to fix it creating the extra complexity of adding extra repos for normal users to know about.

The manifest for the ChromeOS project has about 200 git repos. I worked in that project for a few years and I still have no idea what most of these git repos are. That's one of the main advantages of multi-repo approaches like west: they let you ignore the stuff you don't care about, it never gets in your way. So I can't see what these "other problems" and "extra complexity" are.

> > Another option would be to move back only the check_compliance.py script + any other bit every developer should use but not the CI-specific stuff only admins can use?

> If a script is needed by everybody we should make it available in the main repo (and document it)

"Must/should/may use" nuances aside: agreed.
After a closer look I think I overestimated the amount of CI-specific/admin-only code in the ci-tools repo, my bad. BTW this is great news for reproducing issues reported by CI, the less the better. So a separate repo seems overkill now, not sure why it was created. Maybe there were other CI plans that didn't materialize.

2019-05-09 19:35 UTC, dbkinder reviewed
Not sure what I can add to the review.  Is there a documentation impact?

2019-05-10 17:36 UTC, ulfalizer commented
@marc-hb 
FWIW, I was planning to preserve the history. Found some nice how-tos on how to do it.

2019-05-13 20:16 UTC, carlescufi commented
> After a closer look I think I overestimated the amount of CI-specific/admin-only code in the ci-tools repo, my bad. BTW this is great news for reproducing issues reported by CI, the less the better. So a separate repo seems overkill now, not sure why it was created. Maybe there were other CI plans that didn't materialize.

@marc-hb it  was split  out because we use it downstream on both  our zephyr fork  and also our separate repo with our Nordic-specific applications and libraries, and  we wanted  to be able to freeze it to a particular revision without having to depend on whatever came from the latest zephyr upmerge

2019-05-13 21:30 UTC, marc-hb commented
@carlescufi that sounds like the perfect `west` use case. Now you don't want that anymore?

2019-05-13 23:03 UTC, carlescufi commented
> @carlescufi that sounds like the perfect `west` use case. Now you don't want that anymore?

I do, what makes you think I don't? The only thing is whether we include this in the default upstream manifest, but certainly using west to pull down ci-tools sounds like the right path for me.

2019-05-14 07:13 UTC, aescolar commented
I remove my negative review:
My concern is about what I commented above (The degenerated case in which we would have a pile of repos to pull 1 or 2 files from each). But if there is a good reason for this case in particular I'm not going to oppose.
If the aim of this, is just to have that repo as an optional one, for those working on ci-tools to be able to fetch it easier, but users are not really meant to use those scripts, then it would not really make  much of a difference for anybody else. But, if users and Zephyr's scripts are meant to use this repo files during normal development, and this repo just contains a couple of files then it gets into the daily work annoyance territory.

2019-06-14 03:53 UTC, marc-hb commented
Just spotted PR #16802 by chance

2019-06-20 14:31 UTC, nashif commented
lets close this then.

2019-06-20 14:31 UTC, closed without merging

2019-10-24 16:25 UTC, marc-hb commented
> i thought @ulfalizer was pulling that back into the zephyr tree.

[wip] scripts: ci: Merge back the ci-tools repository into scripts/ci #20039