samples: add ADXL362 sensor sample application
zephyrproject-rtos/zephyr pull request #16073
Opened 2019-05-10 17:31 UTC by bwitherspoon

Add a sample application that demonstrates how to use the ADXL362 with
data ready and threshold triggers.

This depends on #15913 to work.

2019-05-10 17:38 UTC, bwitherspoon commented
Tested on cc1352r1_launchxl board with SPI support from #15741 and a TI BOOSTXL-ULPSENSE shield not upstream yet.

2019-05-10 21:39 UTC, dbkinder approved these changes
doc looks OK, thanks!

2019-05-13 14:56 UTC, MaureenHelm requested changes

2019-05-13 14:56 UTC, MaureenHelm commented on samples/sensor/adxl362/CMakeLists.txt
> +# SPDX-License-Identifier: Apache-2.0
Please add a license/copyright header

2019-05-13 15:24 UTC, bwitherspoon commented on samples/sensor/adxl362/CMakeLists.txt
> +# SPDX-License-Identifier: Apache-2.0
Added

2019-05-14 18:09 UTC, MaureenHelm approved these changes

2019-05-15 10:32 UTC, galak commented
rebased on master to re-kick CI.

2019-05-15 18:38 UTC, merged