flash_map: move flash areas redirect labels to one header
zephyrproject-rtos/zephyr pull request #16137
Opened 2019-05-14 10:35 UTC by nvlsianpu

Labels for assign proper flash area id which depends on TrustZone enabled or not 
were distributed among the source code.
This patch move them into one header file.

Signed-off-by: Andrzej Puzdrowski andrzej.puzdrowski@nordicsemi.no

2019-05-14 10:43 UTC, hakonfam approved these changes

2019-05-14 11:33 UTC, SebastianBoe approved these changes

2019-05-14 13:18 UTC, sigvartmh approved these changes

2019-05-14 13:19 UTC, carlescufi approved these changes

2019-05-15 07:35 UTC, Laczen commented
All these defines are related to mcuboot, they should be moved to a folder related to mcuboot and not in the main zephyr include. Also the name of the include file should be related to mcuboot.
Ideally the defines for mcuboot should not be generated by the DTS file but by a mcuboot config file.

2019-05-15 07:49 UTC, nvlsianpu commented
Storage label can land here as well in near feature. It didn't so fare because it is identical for Secure and NonSecure build right now. My point is that partitioning is not only related to mcuboot, it imposes on storage as well.

2019-05-15 09:11 UTC, Laczen commented
@nvlsianpu, where the storage label should land is something else which should also be decided. It has nothing to do with the fact that all these labels are mcuboot related.

Suppose you would integrate the nrf bootloader next to mcuboot, you would need to have other labels defined for this (i.e. for the MBR region). The definitions for the nrf bootloader should then be configured using Kconfig.

Once this approach is followed you would need to decide on storage: is this defined by the bootloader (or is the bootloader putting constraints on storage) than the storage setting needs to be (re)defined by
the bootloader settings. Since storage is a zephyr related setting a default could be defined in the dts so
that compilation without any bootloader would also provide defines for storage.

2019-05-15 10:23 UTC, galak requested changes
We're trying to reduce headers in include/ or at least the pollution of it.  While I see the duplication going on here, I'm not sure this belongs in include/, not sure where to put it.

2019-05-15 11:17 UTC, nvlsianpu commented on samples/drivers/soc_flash_nrf/src/main.c
> -#define FLASH_TEST_OFFSET DT_FLASH_AREA_IMAGE_1_NONSECURE_OFFSET
this is offset, ot id so is not included in the heder added, fix it

2019-05-16 08:35 UTC, nvlsianpu commented
^^
@sigvartmh @hakonfam What do you think about the header location?

2019-05-16 09:24 UTC, Laczen commented
@andrewboie, @vanwinkeljan, would this not be the ideal moment to start moving the mcuboot defines into a seperate mcuboot config setting instead of using dts ? The present proposal would distribute the mcuboot settings even more throughout the zephyr source.  I remember this being discussed in #15831.

2019-05-16 09:37 UTC, nvlsianpu commented
@Laczen This will be probably something we need to do after multi-mage build PR will be adapted to zephyr. Now I would hesitate against touching that,

2019-05-16 09:38 UTC, nvlsianpu commented
I will move file to mcuboot related place.

2019-05-16 10:06 UTC, Laczen commented
> @Laczen This will be probably something we need to do after multi-mage build PR will be adapted to zephyr. Now I would hesitate against touching that,

Maybe, if the multi-image build is a zephyr related PR it should not use any mcuboot related defines. As far as I understand it there should be 2 (or more) text offset defines, these should not depend on mcuboot generated defines. When mcuboot is selected these text offsets could be redefined to match correct image definitions and locations allowing for a header to be added.

2019-05-16 10:15 UTC, nvlsianpu commented
@galak pleas revisit

2019-05-24 12:57 UTC, nvlsianpu commented
@galak ping

2020-02-06 01:46 UTC, nashif commented
stale, closing. Reopen when there are updates...

2020-02-06 01:46 UTC, closed without merging