disco_l475_iot: Enable peripheral sample
zephyrproject-rtos/zephyr pull request #16146
Opened 2019-05-14 15:10 UTC by erwango

This PR enables peripheral sample on disco_l475_iot1.
Also for convenience, it proposes a default configuration when using btmon

2019-05-15 10:03 UTC, galak approved these changes

2019-05-15 10:27 UTC, jhedberg approved these changes

2019-05-15 10:30 UTC, jhedberg commented
@erwango I already approved, but it'd be good if you could also add the answer to the question "why?" to the ATT flow enforcement patch commit message. Thanks.

2019-05-16 05:19 UTC, frantony commented on boards/arm/disco_l475_iot1/Kconfig.defconfig
> +endif # UART_CONSOLE
UART_CONSOLE -> BT_DEBUG_MONITOR?

2019-05-16 05:54 UTC, jhedberg commented
@erwango seems like this is missing a Fixes #15714 in the description?

2019-05-16 05:57 UTC, jhedberg requested changes
Marking as "Request changes" until we get some better reasoning on the ATT flow control disabling (more details in my comment in #15714).

2019-06-11 15:30 UTC, erwango commented
Closing as issue has been properly fixed by #16748.
Will push a new PR for the monitor thing.

2019-06-11 15:43 UTC, closed without merging