Bluetooth: gatt: Reuse existing handles from a previously added service
zephyrproject-rtos/zephyr pull request #16178
Opened 2019-05-15 13:04 UTC by arthur-proglove

When removing a service using bt_gatt_service_unregister, its attributes
handles will keep their value which can cause a problem when adding the
service again to the GATT database.
When re-adding, the gatt_register routine is taking the last handle of the GATT
database to compare it with the handles of the service to be added.
If a service has handles with a lower value than the last handle of the database
an error will occur. If we add/remove/add the last service, no error will
occur as its handles are always greater than the last one of the database.

Instead of resetting the handles when unregistering a service and
reassign new ones we make sure that the handles of the services are
not in use in the GATT database in order to place the service back
where it used to be.

Thank you to @Vudentz on PR [#16173](https://github.com/zephyrproject-rtos/zephyr/pull/16173)

Signed-off-by: Arthur Crepin-Leblond <arthur.crepin@proglove.de>

2019-05-16 09:01 UTC, Vudentz approved these changes
LGTM

2019-05-16 09:03 UTC, Vudentz commented
@arthur-proglove Just a note before we close it, not sure why you created a new PR since you could have just updated the existing one.

2019-05-16 09:09 UTC, arthur-proglove commented
Oh yes, I was hesitating here between force pushing and creating a new PR and I opted for the latter thinking starting fresh was the best since your fix was different than mine.
It's my first PR on Zephyr, I want everything to be perfect hehe! :blush:

2019-05-16 10:34 UTC, joerchan requested changes
Sorry for ruining your first PR on Zephyr :worried:

Temporarily blocking this until possible specification violation issue has been resolved

Note: Attributes can be added or removed while an ATT bearer is active,
however, an attribute that has been removed cannot be replaced by another
attribute with the same handle while an ATT bearer is active

Are we not breaking this point with this PR?

2019-05-16 11:58 UTC, joerchan approved these changes
Looks good, Discussion resolved on slack

2019-05-30 21:17 UTC, merged

2019-08-12 08:06 UTC, joerchan commented
Added to backporting in #18122, needed to fix #17971