drivers: adxl362: fix acceleration sample conversion
zephyrproject-rtos/zephyr pull request #16248
Opened 2019-05-19 02:48 UTC by bwitherspoon

This driver uses magic numbers which are incorrect. A correct conversion
is done using the LSB/g scale factors given by Table 1 in the
specifications section of the ADXL362 (Rev. F) datasheet. The entire
conversion has also been consolidated into a signal function.

The sensitivity and offset of the accelerometer values actually vary
with the supply voltage and temperature. Using datasheet provided values
for 25 C and 2.0 V is the best we can do. Users will need to apply
sensitivity and offset corrections for their application.

2019-05-20 12:49 UTC, MaureenHelm requested changes

2019-05-20 12:49 UTC, MaureenHelm commented on drivers/sensor/adxl362/adxl362.c
> +	val->val2 = (milli_c % 1000) / 1000;
This always evaluates to zero

2019-05-20 19:06 UTC, bwitherspoon commented on drivers/sensor/adxl362/adxl362.c
> +	val->val2 = (milli_c % 1000) / 1000;
Sorry about that. Fixed.

2019-05-21 19:26 UTC, MaureenHelm approved these changes

2019-05-21 19:26 UTC, merged