kernel: make the main thread a pthread if CONFIG_PTHREAD_IPC
zephyrproject-rtos/zephyr pull request #16328
Opened 2019-05-22 13:38 UTC by tgorochowik

If pthreads are enabled, it is possible to call `pthread_getspecific` and
`pthread_setspecific` in the main thread.

Doing this, makes Zephyr crash with a bus fault.

This patch changes the structure used for the main thread to a pthread.
It works with this simple change, as by-design, `struct kthread` is the
very first element of `struct posix_thread`.

To be honest it seems that this patch is only touching something that is part of a larger issue. It does fix my use-case, but there are probably other very similar issues (related to other pthread callbacks).

Please let me know what should be the approach here. Should we initialize the rest of the fields properly? Should all of this be handled differently (or in a different place)?

2019-05-22 13:54 UTC, tgorochowik commented
Another option I can think of would be simply disallowing doing this somehow (either with a runtime or a compile time check).

2019-06-03 17:24 UTC, pfalcon requested changes
> It works with this simple change, as by-design, struct kthread is the
very first element of struct posix_thread.

Well, can you please make this explicit and type-safe instead of relying on this implicit fact?

2019-06-03 17:31 UTC, pfalcon commented
More generally, this shows a problem of integration of POSIX and native Zephyr kernel. If we want a no-nonsense POSIX subsystem in Zephyr, then it should well and deep into Zephyr itself (at some points), not be just a layer on top.

If we all agree with that, this is nice clean patch (after fixes suggested above), . if we don't, this is layering violation.

> Another option I can think of would be simply disallowing doing this somehow (either with a runtime or a compile time check).

You said you have a usecase for it, and yet you propose to just disallow it? Btw, it's always helpful to be explicit about usecases.

Another approach also may be to spawn a proper "main" pthread in case of POSIX_API application, but that's only more bloat...

2019-06-03 17:46 UTC, pfalcon commented on kernel/init.c
> +#include <posix/pthread.h>
And it's helpful to get a code comments of what happens here.

2019-06-03 18:51 UTC, tyrantlizard77 reviewed
I don't think this is a great idea.

Can't the main thread just spawn a pthread as a child thread and then exit itself?

2019-06-03 18:53 UTC, andrewboie commented
> If pthreads are enabled, it is possible to call pthread_getspecific and
pthread_setspecific in the main thread. Doing this, makes Zephyr crash with a bus fault.

Seems like a garbage-in-garbage-out situation to me.

2019-06-03 18:55 UTC, pfalcon commented
> Can't the main thread just spawn a pthread as a child thread and then exit itself?

And - what happens? Does this release main thread's stack, etc? No.

2020-02-06 01:47 UTC, nashif commented
stale, closing. Reopen when there are updates...

2020-02-06 01:47 UTC, closed without merging