boards: twr_ke18f: exclude board from tests with userspace enabled
zephyrproject-rtos/zephyr pull request #16399
Opened 2019-05-26 13:31 UTC by henrikbrixandersen

Exclude the NXP TWR-KE18F development board from all tests which have
userspace enabled.

The NXP KE1xF SoC has 8 MPU regions of which five are statically
defined, one is used for thread stack protection, and two are used for
stack guard. This leaves zero MPU regions for use by the userspace
privilege separation.

Fixes #16229, #16225.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

2019-05-27 07:03 UTC, ioannisg approved these changes
that's ok for me
Alternatively, we could "block" the user-mode feature completely at the platform level.

We do not have a generic solution to assess which platforms can support the user mode feature; currently, if MPU is present and enabled, ARCH_HAS_USERSPACE is set. but this says nothing about the user-mode "capabilities"...

2019-05-30 14:25 UTC, MaureenHelm commented
> Alternatively, we could "block" the user-mode feature completely at the platform level.

I like this idea better, as it will hopefully avoid confusion when out-of-tree applications try to enable user mode.

2019-05-30 18:03 UTC, henrikbrixandersen commented
> > Alternatively, we could "block" the user-mode feature completely at the platform level.
> 
> I like this idea better, as it will hopefully avoid confusion when out-of-tree applications try to enable user mode.

@ioannisg, @MaureenHelm Appreciate your feedback. Any hints on how to disable usermode support at the platform level?

2019-05-30 18:40 UTC, henrikbrixandersen commented
Would this be the correct approach? What about `CONFIG_TEST_USERSPACE`?

```
diff --git a/arch/arm/core/Kconfig b/arch/arm/core/Kconfig
index 527552ec5d..964ca79c4a 100644
--- a/arch/arm/core/Kconfig
+++ b/arch/arm/core/Kconfig
@@ -21,7 +21,7 @@ config CPU_CORTEX_M
        select HAS_FLASH_LOAD_OFFSET
        select ARCH_HAS_TRUSTED_EXECUTION if ARM_TRUSTZONE_M
        select ARCH_HAS_STACK_PROTECTION if ARM_MPU || CPU_CORTEX_M_HAS_SPLIM
-       select ARCH_HAS_USERSPACE if ARM_MPU
+       select ARCH_HAS_USERSPACE if ARM_MPU && !SOC_SERIES_KINETIS_KE1XF
        select ARCH_HAS_NOCACHE_MEMORY_SUPPORT if ARM_MPU && CPU_HAS_ARM_MPU && CPU_CORTEX_M7
        select ARCH_HAS_RAMFUNC_SUPPORT
        select SWAP_NONATOMIC
```

2019-07-10 08:33 UTC, ioannisg commented
> 
> 
> Would this be the correct approach? What about `CONFIG_TEST_USERSPACE`?
> 
> ```
> diff --git a/arch/arm/core/Kconfig b/arch/arm/core/Kconfig
> index 527552ec5d..964ca79c4a 100644
> --- a/arch/arm/core/Kconfig
> +++ b/arch/arm/core/Kconfig
> @@ -21,7 +21,7 @@ config CPU_CORTEX_M
>         select HAS_FLASH_LOAD_OFFSET
>         select ARCH_HAS_TRUSTED_EXECUTION if ARM_TRUSTZONE_M
>         select ARCH_HAS_STACK_PROTECTION if ARM_MPU || CPU_CORTEX_M_HAS_SPLIM
> -       select ARCH_HAS_USERSPACE if ARM_MPU
> +       select ARCH_HAS_USERSPACE if ARM_MPU && !SOC_SERIES_KINETIS_KE1XF
>         select ARCH_HAS_NOCACHE_MEMORY_SUPPORT if ARM_MPU && CPU_HAS_ARM_MPU && CPU_CORTEX_M7
>         select ARCH_HAS_RAMFUNC_SUPPORT
>         select SWAP_NONATOMIC
> ```

@henrikbrixandersen this is one way to do that, of course, but, IMHO, that is not easy to maintain.
Being able to support user mode or not depends on
- the architecture of the MPU hardware
- the number of available MPU regions (SOC-dependent; can be expressed in DTS, see #12173)
- the number of minimum features we need to support as part of user mode (e.g. a user thread stack, possibly a stack-overflow guard, a thread's app memory, etc.)

All of these need to be know in compile time and Kconfig must make a decision. DTS runs before Kconfig so it can supply the number of available regions already.

@andrewboie , how does this sound? Can we do this for next release?

2019-07-10 20:51 UTC, tyrantlizard77 requested changes
I would rather investigate freeing up some MPU regions so that the tests work.

- Disable hw stack protection if userspace is enabled, which frees one region
- Review the boot-time MPU regions...we are using FIVE. Why so many????

2019-07-10 21:20 UTC, ioannisg commented
> 
> 
> I would rather investigate freeing up some MPU regions so that the tests work.
> 
>     * Disable hw stack protection if userspace is enabled, which frees one region
> 
>     * Review the boot-time MPU regions...we are using FIVE. Why so many????

Actually for Kinetis, the disabling of guards frees up 2 regions, @andrewboie

2019-08-26 10:59 UTC, ioannisg commented
obsoleteby #18647  (hopefully)

2019-09-02 19:37 UTC, closed without merging