Bluetooth: controller: ULL user init function
zephyrproject-rtos/zephyr pull request #16404
Opened 2019-05-27 08:57 UTC by asmk-ot

Implements hooks to implement user protocols in ull.c
A user defined init function can now be called, this code is gated by
the CONFIG_BT_CTLR_USER_EXT define.
A user defined PDU length can now also be defined using the Kconfig
CONFIG_BT_RX_USER_PDU_LEN

Signed-off-by: Asger Munk Nielsen <asmk@oticon.com>

2019-05-27 14:37 UTC, cvinayak requested changes
Changes look good, but please add an additional new commit to this PR with BT_MAYFLY_YIELD_AFTER_CALL and CONFIG_BT_CTLR_USER_* options moved under controller advanced features. Lets not makes proprietary options visible in the top level Bluetooth menu for general Zephyr users.

2019-05-28 07:51 UTC, asmk-ot commented
@cvinayak I pushed changes to Kconfig file as you suggested

2019-05-28 08:11 UTC, aescolar reviewed
2 comments:
* The move of the already existing options should have been done in a separate commit from the addition of the new functionality.
* We really should be adding a test for these kind of hooks so they do not bit-rot in master. At least a build test.

2019-05-28 08:17 UTC, aescolar submitted a review, later dismissed
The move of the already existing options should have been done in a separate commit from the addition of the new functionality.

2019-05-28 08:35 UTC, asmk-ot commented
@aescolar did you mean to say separate PR?

2019-05-28 08:42 UTC, aescolar commented
@asmk-ot Just a separate commit, as @cvinayak had suggested.

2019-05-28 10:05 UTC, cvinayak approved these changes

2019-05-28 12:05 UTC, thoh-ot approved these changes

2019-05-28 12:47 UTC, aescolar commented
@carlescufi review pending

2019-05-28 13:23 UTC, carlescufi requested changes

2019-05-28 13:23 UTC, carlescufi commented on subsys/bluetooth/controller/Kconfig
> +	default 2
Either you add a `depends on BT_CTLR_USER_EXT` in here or you do:

```
#if BT_CTLR_USER_EXT
config BT_CTLR_USER_EVT_RANGE
...
config BT_RX_USER_PDU_LEN
...
#endif

2019-05-28 14:23 UTC, carlescufi approved these changes

2019-05-30 21:14 UTC, merged