drivers: nrf: Add power management to nrf TWIM peripheral.
zephyrproject-rtos/zephyr pull request #16628
Opened 2019-06-05 08:26 UTC by Mierunski

Add power management to nrf TWIM peripheral.

Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>

2019-06-06 09:56 UTC, anangl approved these changes

2019-06-06 09:59 UTC, anangl commented
@Mierunski Could you provide similar PRs for TWI and SPI peripherals?

2019-06-07 11:41 UTC, anangl approved these changes

2019-06-17 09:41 UTC, ioannisg commented on drivers/i2c/i2c_nrfx_twim.c
> +		      POST_KERNEL,					       \
Just wondering @Mierunski why is this in a POST_KERNEL initialization?

2019-06-17 10:44 UTC, pizi-nordic requested changes

2019-06-17 10:44 UTC, pizi-nordic commented on drivers/i2c/i2c_nrfx_twi.c
> +			if (new_state == DEVICE_PM_ACTIVE_STATE) {
Could we have switch/case here? Please note that "if" requires priority encoding which is not needed for switch case so the resulting code is smaller and faster.

2019-06-17 10:44 UTC, pizi-nordic commented on drivers/i2c/i2c_nrfx_twim.c
> +				assert(new_state == DEVICE_PM_LOW_POWER_STATE ||
Could we have switch/case here? Please note that "if" requires priority encoding which is not needed for switch case so the resulting code is smaller and faster.

2019-06-17 10:44 UTC, pizi-nordic commented on drivers/i2c/i2c_nrfx_twim.c
> +				assert(new_state == DEVICE_PM_LOW_POWER_STATE ||
It looks that we only support FORCE_SUSPEND state. Is this what we want?

2019-06-17 10:44 UTC, pizi-nordic commented on drivers/i2c/i2c_nrfx_twim.c
> +static int twim_nrfx_pm_control(struct device *dev, u32_t ctrl_command,
It looks that runtime configuration (i2c_api_configure_t) is not preserved when power mode is changed.

2019-06-25 08:39 UTC, Mierunski commented
@carlescufi @pizi-nordic ping

2019-06-25 08:53 UTC, pizi-nordic approved these changes

2019-06-25 12:23 UTC, ioannisg commented on drivers/i2c/i2c_nrfx_twim.c
> +		      POST_KERNEL,					       \
Ping @Mierunski

2019-06-25 12:55 UTC, carlescufi approved these changes

2019-06-25 12:55 UTC, merged