Fix and improve 'west sign'
zephyrproject-rtos/zephyr pull request #16783
Opened 2019-06-12 18:02 UTC by mbolivar

West sign was broken when build.dir-fmt was added.

Fix that and add some improvements while we are here.

This change breaks backwards compatibility; the default output
locations are now in the build directory.

2019-06-12 19:40 UTC, carlescufi approved these changes
LGTM, but have not tested it

2019-06-13 15:12 UTC, mbolivar commented
Rebased and updated documentation also.

2019-06-13 19:12 UTC, dbkinder requested changes
one nit fix, otherwise LGTM

2019-06-13 19:12 UTC, dbkinder commented on doc/guides/west/sign.rst
> +The availability of a hex file, and whether west flash uses it to flash,
```suggestion
The availability of a hex file, and whether ``west flash`` uses it to flash,
```

2019-06-13 19:27 UTC, mbolivar commented on doc/guides/west/sign.rst
> +The availability of a hex file, and whether west flash uses it to flash,
Done!

2019-06-13 23:21 UTC, dbkinder approved these changes
doc changes LGTM, thanks!

2019-06-14 19:46 UTC, mnkp approved these changes
@mbolivar Sorry for the late review. I've tested the PR on `efr32_slwstk6061a` board with `jlink` runner. The signed images are generated as expected. I could successfully run the hello_world sample app after flashing the `zephyr.signed.bin` image. Application flashed via the `zephyr.signed.hex` image doesn't run but it was also the case before. I didn't have time to debug the issue yet but `west sign` is unlikely the cause. Another user complained about similar issue in "[Zephyr-devel] MCUBoot can't find bootable image (nRF52)". He was running `imgtool` "by hand".

2019-06-14 20:21 UTC, mbolivar commented
@mnkp great, thanks so much for your review and testing. Sorry to hear about the hex issues you're facing, though. I wonder what's going on -- have you asked the mcuboot developers?

2019-06-14 20:31 UTC, mnkp commented
No, I didn't have time to look into the .hex issue, neither contact MCUBoot developers. I'll try to do it.

Have you try to flash .hex file yourself? If it generally doesn't work that's a bit of an issue, since few Zephyr runners correctly flash .bin images.

2019-06-14 20:37 UTC, mbolivar commented
Yeah, I always flash hex files, since it's more convenient because they have embedded addresses.

2019-06-16 14:16 UTC, merged