boards: stm32f469i_disco: add more leds to board
zephyrproject-rtos/zephyr pull request #16796
Opened 2019-06-13 09:10 UTC by FRASTM

Fixes "basic disco sample fails" #16687

Signed-off-by: francois ramu <francois.ramu@st.com>

2019-06-13 12:58 UTC, erwango requested changes
Looks good but please update board doc accordingly.

2019-06-13 13:12 UTC, FRASTM commented
https://docs.zephyrproject.org/latest/boards/arm/stm32f469i_disco/doc/index.html




le doc fait déjà référence à 4 LED:

  *   LD1 : PG6
  *   LD2 : PD4
  *   LD3 : PD5
  *   LD4 : PK3


________________________________
De : Erwan Gouriou <notifications@github.com>
Envoyé : jeudi 13 juin 2019 14:59
À : zephyrproject-rtos/zephyr
Cc : Francois RAMU; Author
Objet : Re: [zephyrproject-rtos/zephyr] boards: stm32f469i_disco: add more leds to board (#16796)


@erwango requested changes on this pull request.

Looks good but please update board doc accordingly.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/zephyrproject-rtos/zephyr/pull/16796?email_source=notifications&email_token=AMIJCMH43RLRCRNMITA6IPLP2JACBA5CNFSM4HXXPQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB3OHEBA#pullrequestreview-249328132>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AMIJCMAH5OZPC63U53VNGJ3P2JACBANCNFSM4HXXPQAQ>.

2019-06-13 14:04 UTC, erwango approved these changes

2019-06-17 21:13 UTC, nashif approved these changes

2019-06-17 21:13 UTC, merged