tests: kernel: add simple ramfunc test
zephyrproject-rtos/zephyr pull request #17091
Opened 2019-06-26 09:14 UTC by ioannisg

This commit contributes a simple test for
the ARM RAMFUNC feature.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2019-06-26 19:59 UTC, agansari requested changes
Looks good, needs a minor change.

2019-06-26 19:59 UTC, agansari commented on tests/kernel/arm_ramfunc/prj.conf
> +CONFIG_USERSPACE=y
Please add empty line at eof.

2019-06-27 06:18 UTC, ioannisg commented on tests/kernel/arm_ramfunc/prj.conf
> +CONFIG_USERSPACE=y
Will fix, thanks.

2019-06-27 06:34 UTC, ioannisg commented
> 
> 
> Looks good, needs a minor change.

Fixed that, @agansari , thanks.

2019-06-27 12:13 UTC, wentongwu approved these changes

2019-06-27 14:01 UTC, agansari approved these changes

2019-06-27 19:44 UTC, merged