Revert "net: sockets: Make NET_SOCKETS_POSIX_NAMES depend on !POSIX_API"
zephyrproject-rtos/zephyr pull request #17362
Opened 2019-07-05 07:14 UTC by jukkar

This reverts commit 0fb8a917e6cfd2d93711cd1e06074315800e6c95.
Our system is not yet ready for this change and it is causing
issues if one wishes to use both generic Posix APIs and
BSD networking APIs.

Fixes #17353

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2019-07-05 09:02 UTC, tbursztyka approved these changes

2019-07-05 09:34 UTC, tgorochowik requested changes
This does not really fix #17353. #17346 contains the proper fix for it.

Reverting 0fb8a917e6cfd2d93711cd1e06074315800e6c95 would require also reverting at least 5cfbcdf1cee5669a5d0a20c8b908e0babdd54b07 (could be more that I don't recall).

Otherwise the problem would be moved from a configuration problem to a compilation problem (redefinition). #17353 would still not be fixed.

Some related issues: #16009 #16141

I really think #17346 is the way to go, even if it has to wait for a dev-review to be decided whether it should go to `include` or `include/posix`.

2019-07-05 10:59 UTC, SteveOss commented
Backing out this change may not be the optimal fix for the original issue. But this had broken all my
existing builds on a LTS branch, which is hardly ideal.

2019-07-05 11:23 UTC, pfalcon requested changes
Our system will never be ready for the right changes, unless we make steps in that direction.

The change this PR tries to revert passed CI, hence it's not incorrect. Otherwise, the state of POSIX subsys in Zephyr is poor, and needs fixing. To that extent, a number of PRs were submitted, to be improving it (in gradual and incremental fashion). Instead of reversing that trend of improvement, and going back to broken state with revert PRs like this, the pending improvement PRs should be merged.

2019-07-10 07:53 UTC, jukkar commented
Lets drop this and fix the posix stuff instead.

2019-07-11 15:43 UTC, jukkar commented
As #17346 is not going forward, I will re-open and rework this a bit (adding revert of commit 5cfbcdf)

2019-07-11 19:31 UTC, pfalcon commented
> As #17346 is not going forward,

While #17346 isn't going forward, I don't see reasons why this should go forward either. We're just in that deadlock situation, where we can't make progress due to actual or perceived shortcomings of the proposed solutions. But that doesn't meet that the regress is the solution, so I'm happy to remain at -1 with this.

Let's try to address the actual concerns raised during the dev meeting (my summary of them are here: https://github.com/zephyrproject-rtos/zephyr/pull/17346#issuecomment-510621911).

2019-07-23 09:56 UTC, pfalcon commented
The RFC for POSIX subsys was posted: https://github.com/zephyrproject-rtos/zephyr/issues/17706 . Hopefully, we can restart with https://github.com/zephyrproject-rtos/zephyr/pull/17346.

Regarding this patch, it would make sense to apply it to 1.14 branch, but actually the original commit was not backported to 1.14, so there's nothing to revert there, and we're good from that PoV too (and I remove "backport" label from this patch).

2019-07-25 22:09 UTC, jukkar commented
This is not needed so closing.

2019-07-25 22:09 UTC, closed without merging