Add support for ODROID-GO Game Kit
zephyrproject-rtos/zephyr pull request #17540
Opened 2019-07-15 17:36 UTC by ydamigos

Add support for ODROID-GO Game Kit

Tested samples:
```
samples/hello_world
samples/basic/blinky
```

2019-07-15 18:27 UTC, dbkinder requested changes

2019-07-15 18:27 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +The toolchain is available for Linux, Windows, and Mac hosts and instructions to
Let's expose these links better (and fix a typo) with:
```
The toolchain is available for Linux, Windows, and macOS hosts and instructions to
obtain and set them up are available in the `ESP-IDF repository
<https://github.com/espressif/esp-idf>`_, as explained in the
`ESP-IDF Programming Guide <SDK>`_.
```

2019-07-15 18:27 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +.. code-block:: console
Can we use the ``.. zephyr-app-commands`` directive here (see samples/hello_world/README.rst for an example use).

2019-07-15 18:27 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +
If you want the toolchain and SDK links (and not just the footnote) to show up here too, add the directive (followed by a blank line):
```
.. target-notes::

```

2019-07-15 18:27 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +  --esp-tool ESP_TOOL   if given, complete path to espidf. default is to
probably don't need the phrase ``if given,  ``

2019-07-15 18:27 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +All flashing options are now handled by the :ref:`west` tool, including flashing
```suggestion
All flashing options are handled by the :ref:`west` tool, including flashing
```

2019-07-15 19:10 UTC, dbkinder requested changes

2019-07-15 19:10 UTC, dbkinder commented on boards/xtensa/odroid_go/doc/index.rst
> +
Can you also add what happens when you run the hello_world sample?  I doubt it displays the usual "hello world" message on the screen, so do you need instructions that hook up a serial console to see that?  (Or are you relying on the link to application_run to cover that?)

2019-07-16 18:31 UTC, ydamigos commented
@dbkinder Thanks for reviewing. All comments addressed.

2019-07-16 19:16 UTC, dbkinder approved these changes
docs LGTM, thanks

2019-07-16 21:28 UTC, dcpleung approved these changes

2019-08-02 05:24 UTC, ydamigos commented
Rebased to master and remove `version` from `espressif,esp32-gpio.yaml`.

2019-08-24 11:47 UTC, ydamigos commented
Rebased to master.

2019-09-08 10:43 UTC, carlescufi commented
@galak could you take a look please?

2019-09-11 17:59 UTC, ydamigos commented
Rebased to master and updated board's device tree for the new UART driver.

2019-09-16 16:38 UTC, ydamigos commented
Rebased to master.

2019-09-25 15:39 UTC, carlescufi approved these changes
LGTM

2019-09-25 15:39 UTC, merged