ext: simplelink: Revert to static memory model in WiFi host driver
zephyrproject-rtos/zephyr pull request #17551
Opened 2019-07-15 23:39 UTC by vanti

During the update to TI SimpleLink SDK 2.40 in commit
8476c451c4b47202c3832a7c46578a6d9bfe59ab, a change to the memory model
in the driver was introduced. This commit reverts back to the original
static memory model. This is necessary because malloc() used by the
dynamic memory model is not thread-safe.

Fixes #17550

Signed-off-by: Vincent Wan <vincent.wan@linaro.org>

2019-07-16 00:44 UTC, tyrantlizard77 requested changes
I think we should look into having malloc() be thread-safe, that seems like the real problem

2019-07-16 22:31 UTC, vanti commented
Thanks @andrewboie. Yes, something similar to PR https://github.com/zephyrproject-rtos/zephyr/pull/17552 that makes malloc() thread-safe would do the trick, in which case this change can be discarded. Once that PR is merged we can close this one.

2019-08-12 19:04 UTC, vanti commented
Suggest we only apply this PR if #17552 does not make it in time for the 2.0 release.

2019-08-22 17:33 UTC, vanti commented
Can be closed now that #17552 has been merged.

2019-08-22 17:33 UTC, closed without merging