drivers: flash: stm32: Fix insufficient wait time
zephyrproject-rtos/zephyr pull request #17598
Opened 2019-07-17 08:13 UTC by gon1332

flash_erase cannot erase a page from the STM32xx SOC flash. It seems
that the erase wait time is not enough and against to what the SOC's
datasheet states. As a result this patch doubles the wait time.

Signed-off-by: Ioannis Konstantelias <ikonstadel@gmail.com>

2019-07-22 12:26 UTC, erwango requested changes

2019-07-22 12:26 UTC, erwango commented on drivers/flash/flash_stm32.c
> +#define CFG_HW_FLASH_SEMID	2
Please remove this line

2019-07-23 06:52 UTC, gon1332 commented on drivers/flash/flash_stm32.c
> +#define CFG_HW_FLASH_SEMID	2
Done.

2019-07-23 07:48 UTC, erwango approved these changes

2019-08-14 21:30 UTC, nashif approved these changes

2019-08-14 21:30 UTC, merged