boards/arm/v2m_musca_b1: Add missing label to timer node
zephyrproject-rtos/zephyr pull request #17674
Opened 2019-07-19 14:58 UTC by galak

The binding for arm,cmsdk-timer requires a label so add it into the dts
since its missing on v2m_musca_b1.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2019-07-19 15:00 UTC, ulfalizer requested changes
There's more of these too, so might want to put those in the same commit.

See the commits `Add missing TIMER_0/1` labels and `Add missing DTIMER_0` label commits that I added yesterday in https://github.com/zephyrproject-rtos/zephyr/pull/17660.

2019-07-19 15:26 UTC, galak commented
> There's more of these too, so might want to put those in the same commit.
> 
> See the commits `Add missing TIMER_0/1` labels and `Add missing DTIMER_0` label commits that I added yesterday in #17660.

worked up #17676

2019-07-19 15:29 UTC, microbuilder approved these changes

2019-07-19 15:31 UTC, microbuilder approved these changes

2019-07-19 15:34 UTC, ulfalizer approved these changes

2019-07-19 16:39 UTC, ioannisg approved these changes

2019-07-20 01:26 UTC, karl-zh approved these changes

2019-07-20 12:27 UTC, merged