drivers : timer : Add MEC1501 32KHz kernel timer driver
zephyrproject-rtos/zephyr pull request #17776
Opened 2019-07-25 12:58 UTC by scottwcpg

Add a kernel timer driver for the MEC1501 32KHz RTOS timer.
This timer is a count down 32-bit counter clocked at a fixed
32768 Hz. It features one-shot, auto-reload, and halt count down
while the Cortex-M is halted by JTAG/SWD. This driver is based
on the new Intel local APIC driver. The driver was tuned for
accuracy at small sleep values. Added a work-around for RTOS
timer restart issue. RTOS timer driver requires board ticks per
second to be 32768 if tickless operation is configured. Because a
32KHz timer cannot provide the 1us resolution for the kernel's
busy wait API we use a 32-bit high speed peripheral timer for
this purpose in the SoC layer.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

2019-07-25 14:48 UTC, tbursztyka approved these changes

2019-07-25 15:01 UTC, tbursztyka commented
@galak  could you eview/merge that one? it's is quite necessary on my side (I can still work on a fork of that pr though)

2019-07-26 11:29 UTC, tbursztyka requested changes
Looks like I was a bit in a hurry. Just tested it, and it does not work. Unfortunately, as I don't have any console on uart2 (whatever I do, nothing goes through) I cannot provide any insights. But my local sample that make the led 3 blinking does not work: led3 goes on, and stays on. I guess it either crashes or stops at the first k_sleep right after writing 1 to the gpio pin.

2019-07-31 19:13 UTC, albertofloyd commented on soc/arm/microchip_mec/mec1501/soc.c
> +		(u64_t)usec_to_wait << 4
@scottwcpg  shouldn't this match consider the pre-scaler value used in initialization.
Changing this to 2, I get more precised delay for values between 20-50us

2019-08-01 19:39 UTC, albertofloyd commented on drivers/timer/mchp_xec_rtos_timer.c
>  	IRQ_CONNECT(RTMR_IRQn, 1, xec_rtos_timer_isr, 0, 0);
We need to have higher priority in this driver, same or higher than UART.

2020-09-19 09:56 UTC, closed without merging