i2c_ll_stm32: Use macros to add I2C instances
zephyrproject-rtos/zephyr pull request #17818
Opened 2019-07-27 14:40 UTC by ydamigos

Use macros to add I2C instances

Signed-off-by: Yannis Damigos <giannis.damigos@gmail.com>

2019-07-29 07:55 UTC, erwango requested changes
Nitpicks to enhance readability

2019-07-29 07:55 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
> +
To enhance readability, what about adding a comment here, to clearly separate macro declaration and instances declaration part?

2019-07-29 07:55 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
>  #endif
/* CONFIG_I2C_STM32_COMBINED_INTERRUPT */

2019-07-29 07:55 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
>  #endif
/* CONFIG_I2C_STM32_INTERRUPT */

2019-07-29 07:55 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
> +#else
Break a line here

2019-07-29 07:55 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
> +#define STM32_I2C_IRQ_HANDLER(name)
Break a line here

2019-07-29 16:16 UTC, ydamigos commented
@erwango Thanks for the review. Comments addressed.

2019-07-30 07:33 UTC, erwango approved these changes

2019-07-31 09:35 UTC, merged