dts: Remove all 'device_type = ...' properties
zephyrproject-rtos/zephyr pull request #17860
Opened 2019-07-30 10:00 UTC by ulfalizer

Unused in Zephyr. There's some documentation for device_type at
https://elinux.org/Device_Tree_Linux, which says that it's deprecated.

Trying to get rid of properties that appear on device tree nodes but
aren't declared in bindings.

Removal was done with

    git ls-files '*.dts' '*.dtsi' | xargs sed -i '/device_type/d'

2019-07-30 10:15 UTC, pabigot approved these changes

2019-07-30 11:30 UTC, erwango approved these changes

2019-07-30 12:32 UTC, ioannisg approved these changes
i am fine with that.

2019-07-30 15:13 UTC, galak requested changes
`device_type` should still be on cpu and memory nodes.

2019-07-30 15:15 UTC, ulfalizer commented
@galak 
Could you explain why? Would be nice to have for reference.

2019-07-30 16:02 UTC, galak commented
> Could you explain why? Would be nice to have for reference.

https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.3-rc2

Look at section `2.3.11 device_type`:

`property is deprecated, and it should be included only on cpu and memory nodes for compatibility with IEEE 1275–derived devicetrees.`

2019-07-30 17:32 UTC, ulfalizer commented
@galak 
I think they mean that it's okay to put it on CPU and memory nodes if you need to be IEEE 1275-compatible, not that it should be included.

Removing it should help make the `.dts` files less confusing either way.

2019-08-01 16:28 UTC, galak commented
> @galak
> I think they mean that it's okay to put it on CPU and memory nodes if you need to be IEEE 1275-compatible, not that it should be included.
> 
> Removing it should help make the `.dts` files less confusing either way.

Its required for both, you can see that here:

https://github.com/devicetree-org/dt-schema/blob/master/schemas/cpus.yaml#L123
https://github.com/devicetree-org/dt-schema/blob/master/schemas/memory.yaml#L26

Now for nodes with compat 'mmio-sram' we can remove device_type.

2019-08-01 17:35 UTC, ulfalizer commented
@galak 
Only read up on that anyOf thing quickly (see [anyOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof) here), but I think this means that CPU nodes are required to have either `device_type`, `reg`, or  `compatible` (i.e., they must have at least one of them).

```
anyOf:
  - required:
      - device_type
  - required:
      - reg
  - required:
      - compatible
```

Looks like it's required for memory nodes by that schema, but IMO it would be better for us to ignore it there, since we don't use it or need it.

2019-08-01 18:33 UTC, ulfalizer commented
Did a `git grep cpu@` in Linux and found lots of nodes that just have a `compatible = ...`. We should be able to scrap it for CPU nodes at least without worrying about not being "compliant".

2020-05-04 12:35 UTC, erwango commented
@ulfalizer should we close this PR ?

2020-07-08 19:15 UTC, closed without merging