dts: edtlib: Support giving missing properties a default value
zephyrproject-rtos/zephyr pull request #17928
Opened 2019-08-01 01:40 UTC by ulfalizer

First commit implements `default:`, the rest first change some stuff to be able to sanity check bindings in a robust way, and then adds sanity checking for `default:`.

```
dts: edtlib: Support giving missing properties a default value

For optional properties, it can be handy to generate a default value
instead of no value if the property is missing, to cut down on #ifdefs.

Allow a default value to be specified in the binding, via a new
'default: <default value>' key on properties in 'properties:'.

Suggested by Peter A. Bigot in
https://github.com/zephyrproject-rtos/zephyr/issues/17829.

The documentation changes in binding-template.yaml explain the syntax.

Fixes: #17829
```

```
dts: edtlib: Check the final merged binding instead of each file

It's currently impossible to check that 'type:' is consistent with
'default:' in a robust way, as they might come from different !included
files and be overridden.

Instead of checking each !included file, have _check_binding() check the
final merged binding. This should also make it possible to move some
other checks there.
```

```
dts: edtlib: Improve naming in _check_binding()
    
'keys' is really a dictionary of settings (like {"type": "int", ...})
for a property. Calling it 'settings' makes it clearer.
```

```
dts: edtlib: Check that 'default:' values are okay

'default:' values for properties in bindings need to match the 'type:'
setting.

The check is done in a new _check_prop_type_and_default() helper
function that's called from _check_binding(). The 'type:' value check is
moved there as well.

This relies on that we now only check the final merged binding. It
wouldn't be robust otherwise, since types and defaults might get added
in different files that then get merged.
```

```
dts: edtlib: Make _init_props() naming consistent with _check_binding()
    
_check_binding() calls the per-property settings dict 'settings'. Call
it that in _init_props() too, instead of 'options'.
```

2019-08-01 14:52 UTC, galak requested changes
If we want to go down this path, we should discuss the concept with the dt-schema guys.  However, I think we should just have the .dts files have the default value in the soc .dtsi files if such defaults are desired.

I know there might be some cases for board level devices that the soc .dtsi doesn't work, but than we can handle the default can than just be in the board dts files.

2019-08-01 14:59 UTC, ulfalizer commented
@galak 
It's best to think of this as just an output control setting.

If you have properties like `foo-pin = <123>` or `buf-size = <123>` that only apply in some cases, and the code happens to use e.g. `-1` as a flag value for `foo-pin` in cases where it does not apply, then it's nicer to have `default: -1` than to force nodes to set `foo-pin = <(-1)>`.

It avoids exposing code internals in the device tree. The `default:` is just between the binding and the code.

2019-08-01 15:05 UTC, pabigot commented
Another way to think of it: in "real" device tree descriptions that are processed at runtime you can detect presence/absence of a property and do the right thing with respect to default behavior.

Because Zephyr needs to do some of that presence reaction at compile time this flexibility is lost, so we need a way to restore it that doesn't involve horrific preprocessor macro manipulation (or more horrific than we already have).

The real killer application of this is devices with multiple instances, of which there aren't a lot now, but I have one that needs this.  I'll try to get it into a proof-of-concept stage so people can see where it's needed.

2019-08-01 23:30 UTC, dbkinder approved these changes
OK, I think.

2019-08-09 20:31 UTC, ulfalizer commented
@galak 
Discovered that dt-schema actually seems to support this by the way. See this in `example-schema.yaml`:

```
  clock-frequency:
    # The type is set in the core schema. Per device schema only need to set
    # constraints on the possible values.
    minimum: 100
    maximum: 400000
    # The value that should be used if the property is not present
    default: 200
```

2019-08-09 23:55 UTC, pabigot approved these changes
So I find:
* [json-schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.2) specifically allows a `default` property to provide a default value;
* From [dt-schema](https://github.com/devicetree-org/dt-schema): "Devicetree Schema files are normal YAML files using the jsonschema vocabulary."

So this is not only *not* something that should be dismissed as unnecessary, its absence is arguably a bug in the Zephyr implementation.  To the degree we're trying to be compatible with dt-schema, at least.

2019-08-10 00:09 UTC, ulfalizer commented
Nice that it's there to get things moving, but more generally I think we should ignore what the "other guys" are doing except as inspiration, and judge things on their own. Maybe dt-schema is horrible. Maybe it's more complex than what we need, or adapted for different needs.

I don't think "dt-schema does this or that" should ever be a deciding factor on its own ("dt-schema does this, and I like it" is better).

There are lots of little improvements that could be made to the existing format, and it'll be really frustrating for me if they're blocked because "it's either dt-schema or no change". :/

2019-08-10 00:25 UTC, pabigot commented
I'm on the exact opposite side.  If there's a standard that seems to have traction, frameworks should have a *very* strong reason for deciding to dismiss it and create a similar but incompatible solution.  Especially if, as I understand it, a driving reason for Zephyr's use of YAML devicetree schemas is compatibility with other systems.

As I understand it `dt-schema` comes from the same people who define the devicetree standard.  As such we should use it, or we should stop claiming that we're using devicetree.

We also could re-use the existing tooling already provided by [dt-schema](https://github.com/devicetree-org/dt-schema) to handle the parsing and validation, and instead focus effort on expressing the bindings in ways that make sense in Zephyr.  The evolution of the last year has come closer to a consistent and usable capability, but I still find it pretty limited and frustrating to use.

2019-08-10 00:44 UTC, ulfalizer commented
@pabigot 
I said that we shouldn't refrain from improving on what we have unless it's an instant switch to dt-schema, not that we should never switch to dt-schema.

We must also be able to point at something and says "this sucks, and we won't be doing it", even if it's "the standard". Standards are only worth so much.

(FWIW, I suspect dt-schema is pretty nice, but it's the mindset that matters.)

2019-08-29 22:47 UTC, ulfalizer commented
Replaced with https://github.com/zephyrproject-rtos/zephyr/pull/18788.

2019-08-29 22:47 UTC, closed without merging