dts: Remove all 'device_type = "cpu"' properties
zephyrproject-rtos/zephyr pull request #17985
Opened 2019-08-02 17:49 UTC by ulfalizer

These are unused in Zephyr. The devicetree spec. does not require
'device_type' anywhere.

Maybe they were put in to copy Linux, under the assumption that it's
required there, but there are lots of CPU nodes in Linux that don't have
'device_type = "cpu"'. See these files for example (randomly picked from
'git grep cpu@'):

 - arch/openrisc/boot/dts/simple_smp.dts
 - arch/xtensa/boot/dts/xtfpga.dtsi
 - arch/xtensa/boot/dts/csp.dts

The cpus.yaml schema from the dt-schema project just says that CPU nodes
should have at least 'compatible', 'reg', or 'device_tree' (i.e., one or
more of them).

2019-08-02 17:51 UTC, galak requested changes
Marking this as 'request changes' as we get clarity on the DTS spec on what is actually required for a cpu node:

https://github.com/devicetree-org/devicetree-specification/issues/29

2019-08-02 17:52 UTC, galak commented
> The cpus.yaml schema from the dt-schema project just says that CPU nodes
> should have at least 'compatible', 'reg', or 'device_tree' (i.e., one or
> more of them).

I think you mean `device_type` not `device_tree`.

2019-08-02 18:03 UTC, ulfalizer commented
> I think you mean `device_type` not `device_tree`.

Derp... fixed.

2019-08-02 19:02 UTC, ulfalizer commented
To summarize devicetree-org/devicetree-specification#29 (scream if you think I'm biased):

 - `device_type` is required on CPUs by the [ARM cpus schema](https://github.com/torvalds/linux/blob/97b00aff2c45069bb8ea88acac664a17d63f77f9/Documentation/devicetree/bindings/arm/cpus.yaml) in the Linux kernel, but not the newer [RISCV cpus schema](https://github.com/torvalds/linux/blob/97b00aff2c45069bb8ea88acac664a17d63f77f9/Documentation/devicetree/bindings/riscv/cpus.yaml).

 - It would be nice to get rid of it on ARM, but in practice, there's too much legacy stuff.

   >You mean the Arm cpu schema (kernel:Documentation/devicetree/bindings/arm/cpus.yaml)?
   >
   > That's correct. While we'd like to drop device_type, we can't. 

 - In Linux, it seems to be a per-arch decision in practice whether you require `device_type` or not (I suspect it might not be that formal though).

    > Probably the spec can be optional, but then it is up to the arch. Whether the arch is optional and it's up to individual platforms is the question.

I think we should decide to not use it, like we already don't. Then it'll never have a chance to become legacy for us either.

2020-01-30 10:57 UTC, galak commented
Closing this PR for now, feel free to re-open and update.

2020-01-30 10:57 UTC, closed without merging