arm: tfm: samples: psa level 1 certified sample
zephyrproject-rtos/zephyr pull request #18185
Opened 2019-08-12 11:22 UTC by microbuilder

**WORK IN PROGRESS, SHOULD NOT BE MERGED!**

This PR adds some boilerplate code for a PSA Certified Level 1
sample application that can be used during the PSA certification
process.

It implements the following features:

- A config struct is defined (`cfg_data`) that contains app and user
  configuration data that will be persisted to secure storage via the
  appropriate PSA FF API calls.
- A `psa` shell command is added that can be extended with required
  features, such as the ability to delete the above config record and
  reset the device to factory defaults.
- Basic logging support to handle common TF-M error codes (`applog.c`),
  based on the Zephyr logging subsystem.
- Basic encryption/decryption support showing how the TF-M crypto
  service can be used to encrypt and decrypt data transfers.

This sample depends on #16450.

Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>

2019-08-14 16:41 UTC, dbkinder requested changes

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +implements the RTOS vendor requirements for a PSA Certified Level 1 product.
add the link you defined below:
```
implements the RTOS vendor requirements for a `PSA Certified Level 1`_ product.
```

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +All TF-M dependencies will be automatically cloned in the /ext folder, and
change to:
```
in the ``/ext`` folder
```

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +At present, this sample is only compatible with Linux and OS X based systems,
Change to:
```
This sample will only build on a Linux or macOS development system (not Windows),
```

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +- OS X 10.14.5 natively with gcc-arm-none-eabi-7-2018-q2-update
change ``OS X`` to ``macOS Mojave``

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +1. Build Zephyr with a non-secure configuration (``-DBOARD=mps2_an521_nonsecure``). This will also build TF-M in the ``ext/tfm`` folder if necessary.
Keep line length < 80 when possible

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +Using ``west``
All these lines (46-61) should be indented an additional three spaces to be part of step 1.

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +.. code-block:: bash
same here.  Indent the code block and contents (line 65-67) by an additional three spaces.

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +4. Open ``<MPS2 device name>/MB/HBI0263C/AN521/images.txt``.
Let's merge some of these steps and fix some formatting issues:
```
4. Edit (e.g., with vim) the ``<MPS2 device name>/MB/HBI0263C/AN521/images.txt``
   file, and update it as shown below:

   .. code-block:: bash

      TITLE: Versatile Express Images Configuration File

      [IMAGES]
      TOTALIMAGES: 2 ;Number of Images (Max: 32)

      IMAGE0ADDRESS: 0x10000000
      IMAGE0FILE: \SOFTWARE\mcuboot.bin  ; BL2 bootloader

      IMAGE1ADDRESS: 0x10080000
      IMAGE1FILE: \SOFTWARE\tfm_sign.bin ; TF-M with application binary blob

5. Save the file, exit the editor, and reset the MPS2+ board.
```

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +By default, tfm/bl2/ext/mcuboot/root-rsa-3072.pem is used to sign images.
It renders better if you enclose filenames with double back-ticks:
```
By default, ``tfm/bl2/ext/mcuboot/root-rsa-3072.pem`` is used to sign images.
The ``merge.sh`` script signs the TF-M + Zephyr binary using the ``.pem`` private key,
by calling ``imgtool.py`` to perform the actual signing operation.
```

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +In order to satisfy PSA Level 1 certification requirements, **You MUST replace
Change ``In order to`` to simply ``To``

2019-08-14 16:41 UTC, dbkinder commented on samples/tfm_integration/psa_level_1/README.rst
> +.. _TF-M build instruction:
You've defined these two external links, but don't use them anywhere in the document so they won't show up in our generated HTML.  Note what I did on line 9 above to add a link in the documentation to the document you identified.  We need to create similar references in the text to these two documents.

2019-08-15 13:31 UTC, karl-zh reviewed
The Crypto test cases are leveraging the same non secure test cases from TFM. These test cases are designed for TFM crypto service. @microbuilder Is it fine to take advantage these integration test cases here?

2019-08-15 13:31 UTC, karl-zh commented on boards/arm/mps2_an521/mps2_an521_nonsecure.dts
> +	flash0: flash@100400 {
This commit is from #16450 at [here](https://github.com/zephyrproject-rtos/zephyr/pull/16450/commits/f9d10e31e2436c2dc604f2a3fe43d8dd2b67e961) to resolve secure fault while jump into Zephyr.

2019-10-22 15:59 UTC, microbuilder commented
Superseded by #19985, which takes into account the changes and feedback made in this PR.

This PR is being closed in favour of the newer version which integrates a shared TF-M build system, and will simplify the overall TF-M sample app review process.

2019-10-22 15:59 UTC, closed without merging