ext: hal: make TI HAL a zephyr module
zephyrproject-rtos/zephyr pull request #18526
Opened 2019-08-20 13:46 UTC by nashif

Move TI HAL to a module repository:
https://github.com/zephyrproject-rtos/hal_ti

managed by west.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2019-08-20 13:59 UTC, galak approved these changes

2019-08-20 18:41 UTC, vanti requested changes
I tried to rebuild the http_get sample for cc3220sf_launchxl and it failed:

```
[40/168] Building C object zephyr/CMak...fi/simplelink/simplelink_support.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/drivers/wifi/simplelink/simplelink_support.c.obj 
ccache /home/a0792201local/bin/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBUILD_VERSION=v2.0.0-rc1-143-g441ac4195e3e -DKERNEL -DSL_PLATFORM_MULTI_THREADED -DSL_SUPPORT_IPV6 -DUSE_CC3220_ROM_DRV_API -D_FORTIFY_SOURCE=2 -D__LINUX_ERRNO_EXTENSIONS__ -D__ZEPHYR__=1 -I../../../../../kernel/include -I../../../../../arch/arm/include -I../../../../../include -I../../../../../include/drivers -Izephyr/include/generated -I../../../../../soc/arm/ti_simplelink/cc32xx -I../../../../../ext/hal/cmsis/Include -I../../../../../subsys/net/lib/sockets/. -I../../../../../subsys/net/lib/tls_credentials/. -I../../../../../drivers/wifi/simplelink/. -I../../../../../ext/hal/ti/simplelink/kernel/zephyr/dpl -I../../../../../ext/hal/ti/simplelink/source -I../../../../../ext/hal/ti/simplelink/source/ti/drivers/net/wifi/porting -I../../../../../subsys/net/lib/tls_credentials -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/source/ti/devices/cc32xx/. -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/source/ti/devices/cc32xx/inc -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/source/ti/devices/cc32xx/driverlib -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/. -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/source -I/home/a0792201local/zephyrproject-work/modules/hal/ti/simplelink/kernel/zephyr/dpl -isystem /home/a0792201local/bin/zephyr-sdk-0.10.3/arm-zephyr-eabi/arm-zephyr-eabi/include -Og -imacros/home/a0792201local/zephyrproject-work/zephyr/samples/net/sockets/http_get/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mthumb -mcpu=cortex-m4 -imacros/home/a0792201local/zephyrproject-work/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/a0792201local/zephyrproject-work/zephyr/samples/net/sockets/http_get=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/a0792201local/zephyrproject-work/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -mabi=aapcs -march=armv7e-m -std=c99 -MD -MT zephyr/CMakeFiles/zephyr.dir/drivers/wifi/simplelink/simplelink_support.c.obj -MF zephyr/CMakeFiles/zephyr.dir/drivers/wifi/simplelink/simplelink_support.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/drivers/wifi/simplelink/simplelink_support.c.obj   -c /home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink_support.c
/home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink_support.c:18:10: fatal error: CC3220SF_LAUNCHXL.h: No such file or directory
 #include <CC3220SF_LAUNCHXL.h>
          ^~~~~~~~~~~~~~~~~~~~~
```

There are some references in drivers/wifi/simplelink/CMakeLists.txt to the old location that need to be updated. Looks like Shippable caught it too.

2019-08-20 18:45 UTC, nashif commented
> There are some references in drivers/wifi/simplelink/CMakeLists.txt to the old location that need to be updated. Looks like Shippable caught it too.

yep, have a fix for that, testing that now.

2019-08-21 17:39 UTC, vanti approved these changes
I have verified the latest changes resolved the build issue and I am able to run http_get on cc3220sf_launchxl. I am also successful in building and running the blinky sample on cc1352r1_launchxl. 

LGTM

2019-08-21 17:46 UTC, merged