arch: arm: be able to infer Z_ARCH_EXCEPT() for baseline SOCs
zephyrproject-rtos/zephyr pull request #18713
Opened 2019-08-27 15:37 UTC by ioannisg

This commit makes it possible to infer Z_ARCH_EXCEPT()
calls in SVCs that escalate to HardFault due to being
invoked from priority level equal or higher to the
interrupt priority level of the SVC Handler.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2019-08-27 15:38 UTC, ioannisg commented
This should be fixing #18590 
@galak could you, please, test?

2019-08-28 14:15 UTC, galak requested changes
Logic seems good, had a few comments on the code style.

2019-08-28 14:41 UTC, ioannisg commented on arch/arm/core/cortex_m/fault.c
> +		u16_t *svc_addr = (u16_t *)(((u8_t *)ret_addr) - 2);
Sure, I can do that.

2019-08-28 14:52 UTC, pizi-nordic approved these changes
I would like to see @galak suggestion: https://github.com/zephyrproject-rtos/zephyr/pull/18713#discussion_r318606023 implemented here.

Everything else LGTM.

2019-08-28 16:31 UTC, galak approved these changes

2019-08-28 16:32 UTC, ioannisg reviewed
@galak updated code style based on your suggestion.
Could you please, confirm that this fixes the failing test on your platform?

It fixes the test on atsamr21_xpro.

2019-08-28 16:33 UTC, ioannisg commented on arch/arm/core/cortex_m/fault.c
> +#undef _SVC_OPCODE
Not really - just thought it's ok to remove the definition, after it is not any more needed.

2019-08-29 01:39 UTC, wentongwu approved these changes

2019-08-29 09:29 UTC, merged