kernel: deprecate and replace k_uptime_get_32()
zephyrproject-rtos/zephyr pull request #18742
Opened 2019-08-28 12:33 UTC by pabigot

This function does not return the low 32 bits of k_uptime_get() as
suggested by it's documentation; it returns the number of milliseconds
represented by the low 32-bits of the underlying system clock.  The
truncation before translation results in discontinuities at every point
where the system clock increments bit 33.

Refine the documentation to describe what it actually does, mark it
deprecated, and replace all in-tree uses with an expression that is
slower but does the right thing.

Closes #18739.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

2019-08-28 12:49 UTC, pfalcon requested changes
> This function does not return the low 32 bits of k_uptime_get() as
suggested by it's documentation

Ok, so that's where the bug lies, and what needs fixing, instead of making a statue of the incorrect implementation in stone and telling not to use it.

2019-08-28 13:00 UTC, pizi-nordic approved these changes

2019-08-28 13:27 UTC, carlescufi commented
> > This function does not return the low 32 bits of k_uptime_get() as
> > suggested by it's documentation
> 
> Ok, so that's where the bug lies, and what needs fixing, instead of making a statue of the incorrect implementation in stone and telling not to use it.

Not sure I get what you mean here @pfalcon. The current implementation is being marked as [deprecated in this PR](https://github.com/zephyrproject-rtos/zephyr/pull/18742/commits/7a75ed2b635bbc6d9cdb9f6b5734379b5fd86ffd#diff-3fbe299f0805e317d53562fee256c989R1752) because what it does now does not reflect what a user might infer from the function name. Do you suggest that we should keep the function and cast to uint32 inside the new implementation or that we keep the current implementation but rename it?

2019-08-28 13:40 UTC, pizi-nordic commented
> Ok, so that's where the bug lies, and what needs fixing, instead of making a statue of the incorrect implementation in stone and telling not to use it.

This way we will have k_uptime_get_32() and k_uptime_get() with no difference on performance, which so far justified existence of  k_uptime_get_32().

2019-08-28 13:46 UTC, alexanderwachter commented
@pizi-nordic since `TICKLESS_KERNEL` is the default, ` k_uptime_get_32()` does not even have better performance.

2019-08-28 14:11 UTC, pizi-nordic commented
@alexanderwachter: So there is no doubts that this PR should go in...

2019-08-28 14:14 UTC, pfalcon commented
> Not sure I get what you mean here @pfalcon.

Let me explain by example. In https://github.com/zephyrproject-rtos/zephyr/pull/18708, it was found that pthread_cond_timedwait(), pthread_mutex_timedlock() functions don't do what's described in the documentation. However, I don't deprecate them with a desire to make users find workarounds or introduce new names for the same functions. I just fix incorrect implementation.

> This way we would have k_uptime_get_32() and k_uptime_get() with no difference on performance, which so far justified existence of k_uptime_get_32().

Really? I thought it exists just because it's convenient API to use. And don't let me start on possible implications on register pressure when returning 64bit, instead of 32bits, on all architectures and compilers, past, present, and future, with LTO and not, with a case when ticks and millisecond perfectly align and not, for the case of no userspace separation and with it (reading comments on https://github.com/zephyrproject-rtos/zephyr/pull/18064 was insightful, even though it talks about 64-bit *arguments*, not returns).

Let me just point that fixing k_uptime_get_32() has a very obvious benefit of making unnecessary patches rampaging thru 47 files of the codebase (2 days before the planned release date, just by pure coincidence, surely nobody thinks about merging it into this release).

2019-09-03 17:49 UTC, pabigot commented
Withdrawn, prefer #18744

2019-09-03 17:49 UTC, closed without merging