West 0.6.1 docs
zephyrproject-rtos/zephyr pull request #18761
Opened 2019-08-28 20:12 UTC by mbolivar

I am guessing we will need yet another container update to install 0.6.1 for this to pass shippable.

2019-08-28 20:31 UTC, dbkinder requested changes

2019-08-28 21:41 UTC, dbkinder approved these changes
LGTM, thanks!

2019-08-28 22:33 UTC, mbolivar commented
> I am guessing we will need yet another container update to install 0.6.1 for this to pass shippable.

Hurray, CI passed somehow :)

2019-08-29 08:29 UTC, carlescufi approved these changes

2019-08-29 08:37 UTC, merged