net: socket: Return error in recvfrom() if buffer size is 0
zephyrproject-rtos/zephyr pull request #18931
Opened 2019-09-05 12:05 UTC by jukkar

If there is no buffer available where to read data, then return
error and set errno to ENOBUFS

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2019-09-05 12:42 UTC, pfalcon requested changes
ENOBUFS means "no buffers on the OS side", can't use it here. Did you check what POSIX suggests to in such a case? Did you check what Linux does?

2019-09-05 12:57 UTC, jukkar commented
I agree, ENOBUFS is probably wrong here. EINVAL is more appropriate value.

2019-09-05 13:02 UTC, pfalcon commented
> I agree, ENOBUFS is probably wrong here. EINVAL is more appropriate value.

More likely, it should just return 0. User asked for 0 bytes, user gets what they commanded. I'd suggest to check what Linux does and do the same. And I'd suggest that we should run tests for our socket subsys on both Zephyr and Linux, to check for consistent result. Otherwise, we'll create such an "original design", that it will be horror to port/debug apps for.

2019-09-05 13:24 UTC, jukkar commented
Returning 0 is correct behaviour here, new version sent.

2019-09-05 13:24 UTC, pfalcon approved these changes

2019-09-06 07:28 UTC, rveerama1 approved these changes

2019-09-08 21:13 UTC, merged