[WIP] Prototype / hack of integration of DTS into sanitycheck
zephyrproject-rtos/zephyr pull request #19127
Opened 2019-09-12 23:37 UTC by galak

This is a wip in progress, first cut/example of using DTS in sanitycheck.  Looking for feedback if this direction seems desirable.  etc.

2019-09-12 23:47 UTC, ulfalizer reviewed
Haven't looked much at these scripts, but getting rid of `generated_dts_board.conf` seems nice.

2019-10-01 20:46 UTC, pabigot approved these changes
Seems like a clean solution, especially if this means we can put application-specific board conf/overlay files in the test and they get picked up automatically (no mods to `testcase.yaml` or `sample.yaml`).

2019-10-01 20:46 UTC, pabigot commented on scripts/sanity_chk/expr_parser.py
> +sys.path.insert(0, os.path.join(ZEPHYR_BASE, "scripts/dts"))
IIRC for portability this should be `os.path.join(ZEPHYR_BASE, "scripts", "dts")`  but there's probably already a lot of code that won't work for `os.path.sep` not equal to `'/'`.  Certainly there's material in `sanitycheck` that should be using `os.path.split` if that's a concern.

2019-10-07 18:23 UTC, dbkinder requested changes

2019-10-07 18:23 UTC, dbkinder commented on doc/guides/test/sanitycheck.rst
> +the following new options::
they won't be "new" for long, so just say "the following options"

2019-10-07 18:23 UTC, dbkinder commented on doc/guides/test/sanitycheck.rst
> +To build and execute tests on multiple devices connected to the host PC a
Better would be:
```
To build and execute tests on multiple devices connected to the host PC,
you'll need to create a hardware map with all connected devices and their
details, such as the serial device and their IDs, if available. Create a
hardware map by running this command::
```

2019-10-07 18:23 UTC, dbkinder commented on doc/guides/test/sanitycheck.rst
> +Any options marked as 'unknown' need to be changed and set with the correct
Better would be:
```
You must manually change any options marked as ``unknown``.
In the above example, replace the ``platform`` and ``runner``
names with values appropriate for the connected
hardware. In this example we are using a ``reel_board`` and an
``nrf52840_pca10056`` board, and ``pyocd`` and ``nrfjprog``
runners, respectively::
```

2019-10-07 18:23 UTC, dbkinder commented on doc/guides/test/sanitycheck.rst
> +  Currently only boards with support for both pyocd and nrfjprog are supported
Do the boards need to support **both pyocd and nrfjprog** ? I'm guessing it's either, and if so, change this to:
```
Currently only boards with support for either pyocd or nrfjprog are supported ...
```

2019-10-29 06:18 UTC, galak commented
Will open a new PR with the code now that its cleaned up.

2019-10-29 06:18 UTC, closed without merging