debug: tracing: Common Trace Format Simplification
zephyrproject-rtos/zephyr pull request #19283
Opened 2019-09-19 13:17 UTC by msenOticon

Various C and Assembly modules in the debug subsystem
make function calls to z_sys_trace_*. These merely call
corresponding functions sys_trace_*. This commit
is to simplify these by making direct function calls
to the sys_trace_* functions from these modules.
Subsequently, the z_sys_trace_* functions are removed.

Signed-off-by: Mrinal Sen <msen@oticon.com>

2019-09-19 13:21 UTC, nashif submitted a review, later dismissed
this commit has too many unrelated changes in 1 commit, including changes to ctf which was submitted earlier in some other PR, please keep this PR just for the z_sys -> sys...

2019-09-19 13:37 UTC, msenOticon commented
@nashif : Hi Anas, This part of the implementation builds on top of the previous one (PR19210). We wondered if this will be confusing for the reviewers to see the changes submitted in the previous PR is undone in this PR. For example, one file that was deleted in the previous PR would have reappeared in this one. If you would prefer, I can wait till the previous PR is merged before re-submitting this one. I believe the previous PR is ready to be merged subject to your final review. Many thanks!

2019-09-19 13:54 UTC, aescolar submitted a review, later dismissed
By far most changes in this commit are indentations changes in unrelated places.
Please do not do that.
Also as @nashif mentioned, please do not mix the CTF refactoring into this commit.
If the only intended change is what the commit message described, the commit
title should also reflect that (which is not a "CTF simplification")

2019-09-19 14:17 UTC, msenOticon commented
@aescolar : Hi Alberto, the indentations are added by the uncrustify and only on the modules I have touched! It is best, that I revert this commit and resubmit when the first PR is merged. Thanks!

2019-09-20 00:57 UTC, nashif commented
@msenOticon if you use uncrustify in some code, keep those changes separate from any functional changes, ie. put them in a different commit. Also, if you depend on some other PR, keep the original commits from the other PR intact, do not squash them in one some single commit. Thanks.

2019-09-21 20:04 UTC, dbkinder approved these changes
doc changes LGTM.

2019-09-23 10:33 UTC, mped-oticon reviewed
@msenOticon You may now either rebase+separate out the whitespace changes, or perhaps easier - redo the renaming + uncrustify whitespace again (as two separate PRs IMHO).

2019-09-24 07:27 UTC, msenOticon commented
I have re-based in line with your comments with an appropriate commit message. Many thanks!

2019-09-24 09:53 UTC, ioannisg approved these changes
Looks fine to me

2019-09-24 11:49 UTC, nashif requested changes
with this patch to enable tracing:

```
diff --git a/samples/synchronization/prj.conf b/samples/synchronization/prj.conf
index fb9f4cdb23..7a1792ae40 100644
--- a/samples/synchronization/prj.conf
+++ b/samples/synchronization/prj.conf
@@ -1,3 +1,5 @@
 CONFIG_STDOUT_CONSOLE=y
 # enable to use thread names
-#CONFIG_THREAD_NAME=y
+CONFIG_THREAD_NAME=y
+CONFIG_SEGGER_SYSTEMVIEW=y
+CONFIG_USE_SEGGER_RTT=y
```
I am getting:

```
        IDT_LIST:          56 B         2 KB      2.73zephyr/arch/arch/arm/core/libarch__arm__core.a(swap_helper.S.obj): In function `__pendsv':
/Users/anashif/zephyr/zephyrproject/zephyr/arch/arm/core/swap_helper.S:49: undefined reference to `sys_trace_thread_switched_out'
/Users/anashif/zephyr/zephyrproject/zephyr/arch/arm/core/swap_helper.S:322: undefined reference to `sys_trace_thread_switched_in'
zephyr/arch/arch/arm/core/libarch__arm__core.a(cpu_idle.S.obj): In function `k_cpu_idle':
/Users/anashif/zephyr/zephyrproject/zephyr/arch/arm/core/cpu_idle.S:77: undefined reference to `sys_trace_idle'
zephyr/arch/arch/arm/core/libarch__arm__core.a(isr_wrapper.S.obj): In function `_isr_wrapper':
/Users/anashif/zephyr/zephyrproject/zephyr/arch/arm/core/isr_wrapper.S:68: undefined reference to `sys_trace_isr_enter'
/Users/anashif/zephyr/zephyrproject/zephyr/arch/arm/core/isr_wrapper.S:155: undefined reference to `sys_trace_isr_exit'
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.
```

2019-09-24 16:59 UTC, msenOticon commented
@nashif : Hi Anas, could you please give me the build command for this (board and samples options). I tried a few options but couldn't produce the same errors. Many thanks.

2019-09-24 19:10 UTC, nashif commented
> @nashif : Hi Anas, could you please give me the build command for this (board and samples options). I tried a few options but couldn't produce the same errors. Many thanks.

`west  build -b nrf52840_pca10056 samples/synchronization/`

with the above change to `prj.conf`

2019-09-25 06:57 UTC, msenOticon commented
@nashif : Hi Anas, Thank you. I have tried this but get different results! 
In my branch (msen/ctf_rm_z_sys_traces), I get the error "../soc/arm/nordic_nrf/nrf52/soc.h:17:10: fatal error: nrf.h: No such file or directory". 
In master (with git pull, west update, etc.), I get "../soc/arm/nordic_nrf/nrf52/soc.h:16:10: fatal error: nrfx.h: No such file or directory".
I am using the command: west build -b nrf52840_pca10056 samples/synchronization --pristine
The .prj file as you suggested: samples/synchronization/prj.conf
CONFIG_STDOUT_CONSOLE=y
# enable to use thread names
CONFIG_THREAD_NAME=y
CONFIG_SEGGER_SYSTEMVIEW=y
CONFIG_USE_SEGGER_RTT=y

2019-09-25 07:33 UTC, msenOticon commented
@nashif : Hi Anas, I have fixed my build issue, now I can see the errors you have mentioned. Will investigate and fix the problem!

2019-09-25 16:31 UTC, msenOticon commented
"west build -b nrf52840_pca10056 samples/synchronization" is now working with the last update.

2019-09-25 16:34 UTC, nashif commented
> "west build -b nrf52840_pca10056 samples/synchronization" is now working with the last update.

does it work with ```
diff --git a/samples/synchronization/prj.conf b/samples/synchronization/prj.conf
index fb9f4cdb23..7a1792ae40 100644
--- a/samples/synchronization/prj.conf
+++ b/samples/synchronization/prj.conf
@@ -1,3 +1,5 @@
 CONFIG_STDOUT_CONSOLE=y
 # enable to use thread names
-#CONFIG_THREAD_NAME=y
+CONFIG_THREAD_NAME=y
+CONFIG_SEGGER_SYSTEMVIEW=y
+CONFIG_USE_SEGGER_RTT=y```

2019-09-26 06:12 UTC, msenOticon commented
@nashif : I can build this as well as for native_posix, hello_world without any errors:
diff --git a/samples/synchronization/prj.conf b/samples/synchronization/prj.conf
index fb9f4cdb23..7a1792ae40 100644
--- a/samples/synchronization/prj.conf
+++ b/samples/synchronization/prj.conf
@@ -1,3 +1,5 @@
 CONFIG_STDOUT_CONSOLE=y
 # enable to use thread names
-#CONFIG_THREAD_NAME=y
+CONFIG_THREAD_NAME=y
+CONFIG_SEGGER_SYSTEMVIEW=y
+CONFIG_USE_SEGGER_RTT=y
C7.5.1804 kbnuxaes02 [/scratch/zephyrproject/zephyr]
$ west build -b nrf52840_pca10056 samples/synchronization
-- west build: build configuration:
       source directory: /scratch/zephyrproject/zephyr/samples/synchronization
       build directory: /scratch/zephyrproject/zephyr/build
       BOARD: nrf52840_pca10056 (origin: CMakeCache.txt)
-- west build: building application
[0/1] Re-running CMake...
Zephyr version: 2.0.99
-- Selected BOARD nrf52840_pca10056
-- Found west: /home/msen/.local/bin/west (found suitable version "0.6.2", minimum required is "0.6.0")
-- Loading /scratch/zephyrproject/zephyr/boards/arm/nrf52840_pca10056/nrf52840_pca10056.dts as base
-- Overlaying /scratch/zephyrproject/zephyr/dts/common/common.dts
Device tree configuration written to /scratch/zephyrproject/zephyr/build/zephyr/include/generated/generated_dts_board.conf
warning: please put 'required: false' instead of 'category: optional' in 'properties: center-aligned: ...' in /scratch/zephyrproject/zephyr/dts/bindings/pwm/nordic,nrf-pwm.yaml - 'category' will be removed
Parsing Kconfig tree in /scratch/zephyrproject/zephyr/Kconfig
Loaded configuration '/scratch/zephyrproject/zephyr/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig'
Merged configuration '/scratch/zephyrproject/zephyr/samples/synchronization/prj.conf'
No change to '/scratch/zephyrproject/zephyr/build/zephyr/.config'
warning: please put 'required: false' instead of 'category: optional' in 'properties: center-aligned: ...' in /scratch/zephyrproject/zephyr/dts/bindings/pwm/nordic,nrf-pwm.yaml - 'category' will be removed
-- Cache files will be written to: /home/msen/.cache/zephyr
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/zephyrproject/zephyr/build
[97/101] Linking C executable zephyr/zephyr_prebuilt.elf

2019-09-26 08:46 UTC, msenOticon commented
@nashif : Hi Anas, I just created a new branch from the master and applied this commit on top. I can build for nrf52840_pca10056 using the prj.conf as above. Best regards, Mrinal

2019-09-26 10:26 UTC, nashif approved these changes

2019-09-26 10:26 UTC, merged