shields: add WAVESHARE e-Paper shield
zephyrproject-rtos/zephyr pull request #19293
Opened 2019-09-19 21:59 UTC by jfischer-phytec-iot

Add WAVESHARE e-Paper shield and support for
GDEH0213B1, GDEH0213B72 and GDEH029A1 displays.

2019-09-20 04:43 UTC, vanwinkeljan approved these changes

2019-09-21 20:50 UTC, dbkinder requested changes
Thanks for the docs.  A few suggested changes.

2019-09-21 20:50 UTC, dbkinder commented on boards/shields/waveshare_epaper/doc/index.rst
> +This shield comes also with a 23LC1024 SPI RAM
Change to:
```
This shield includes a 23LC1024 1Mb SPI Serial SRAM that is
not currently supported by the Zephyr RTOS.
```

2019-09-21 20:50 UTC, dbkinder commented on boards/shields/waveshare_epaper/doc/index.rst
> +This shield can only be used with a board which provides a configuration
change "which" to "that"

2019-09-21 22:16 UTC, dbkinder approved these changes
+1 for docs, thanks!

2019-09-25 09:59 UTC, galak reviewed
Do we have any sample or something that builds with this shield?

2019-09-25 12:56 UTC, jfischer-phytec-iot commented
>Do we have any sample or something that builds with this shield?

@galak I have to add something like 183a95c132aa9d9d9f1ac9b0befbbb43640c25f3. I am just not sure how. There are (currently) three variants of this shield, should we test all variants or just one?

2019-09-25 14:23 UTC, galak commented
> @galak I have to add something like [183a95c](https://github.com/zephyrproject-rtos/zephyr/commit/183a95c132aa9d9d9f1ac9b0befbbb43640c25f3). I am just not sure how. There are (currently) three variants of this shield, should we test all variants or just one?

Would be good to test all 3, just so we at least have one build test for each shield.

2019-10-04 12:27 UTC, erwango approved these changes

2019-10-05 01:49 UTC, merged