avoid shippable build errors on limited platforms
zephyrproject-rtos/zephyr pull request #19330
Opened 2019-09-23 15:27 UTC by pabigot

Several platforms fail to build several tests because they run out of memory.  Exclude them so we don't get false negatives from shippable on PRs that happen to trigger these tests.

Found with `sanitycheck --all`.

2019-09-23 17:22 UTC, tyrantlizard77 requested changes
This isn't the right way to do this.
The right way to do this is to set the platform's RAM/flash size in the board level YAML file, and then set min_ram/min_flash in the testcase.yaml.

2019-09-23 17:32 UTC, pabigot commented
> The right way to do this is to set the platform's RAM/flash size in the board level YAML file, and then set min_ram/min_flash in the testcase.yaml.

Fair enough.  In that case I'll have to increase the amount of flash required for some tests, because these boards are failing even though they meet the minimum specified.

I'll rework for that.

2019-09-23 18:04 UTC, tyrantlizard77 approved these changes
looks better thanks.
I'm uneasy that basic kernel validation tests like thread_apis and poll use so much flash, but that can get addressed in another PR.

2019-09-24 00:49 UTC, tyrantlizard77 approved these changes

2019-09-24 00:49 UTC, merged