arm: soc: nordic nRF52: Add MPU support
zephyrproject-rtos/zephyr pull request #194
Opened 2017-05-15 18:04 UTC by mike-scott

We now have generic ARM M4 MPU support added to Zephyr.
Let's enable it for use with Nordic nRF52 chips.

Memory Layout was generated from Section 8.3 "Memory
Map" of nRF52 Product Specifications (for both nRF52832
and nRF52840):
0x00000000: Flash
0x10000000: Factory Information Config Registers
0x10001000: User Information Config Registers
0x20000000: SRAM
0x40000000: APB Peripherals
0x50000000: AHB Peripherals
0xE0000000: ARM M4 Private Peripheral Registers

NOT Configured:
0x60000000: External RAM
0x80000000: External RAM
0xA0000000: External Device
0xC0000000: External Device

NOTE: More work will be needed for future Nordic MWU (Memory
Watching Unit) support.

Change-Id: I6d2629bb70abc8c85dc81fdf7e03e7be01478ff6
Signed-off-by: Michael Scott <michael.scott@linaro.org>

2017-05-15 18:06 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/arm_mpu_regions.c
> +#define APB_PERIPH_BASE	0x40000000
This looks like there's no tab here.. but in the code there is.  Odd.  (Same below)

2017-05-15 18:26 UTC, cvinayak requested changes

2017-05-15 18:26 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/arm_mpu_regions.c
> +#define XICR_BASE	0x10000000
Use spaces instead of tabs

2017-05-15 18:26 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +	  Enable MPU
Enable MPU support on Nordic Semiconductor nRF52x series ICs.

2017-05-15 18:26 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/Makefile
> +obj-$(CONFIG_NRF52_ARM_MPU_ENABLE) += arm_mpu_regions.o
since the file is under arch/arm path, just mpu_regions.c as filename?

2017-05-15 18:26 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/arm_mpu_mem_cfg.h
> +#ifndef _ARM_MPU_MEM_CFG_H_
Same here just mpu_mem_cfg.h ?

2017-05-15 18:26 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
ARM_MPU_NRF52X

2017-05-15 18:43 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +	  Enable MPU
Nice catch.  Fixing w/ your text.

2017-05-15 18:43 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
The STM32 implementation uses STM32_ARM_MPU_ENABLE, so I also used that pattern in this patch.  However, the ARM Beetler uses "ARM_MPU_ENABLE" (w/o SoC at all) so there is no standard, I'm open to using your format.

2017-05-15 18:44 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/Makefile
> +obj-$(CONFIG_NRF52_ARM_MPU_ENABLE) += arm_mpu_regions.o
Both the ARM Beetle and STM32 implementation used this naming structure.  You have a good point however.

2017-05-15 18:45 UTC, galak commented on arch/arm/soc/nordic_nrf5/nrf52/arm_mpu_regions.c
> +#define XICR_BASE	0x10000000
where? tabs are normal default

2017-05-15 18:46 UTC, galak requested changes
can you send to arm branch

2017-05-15 18:49 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
Clarification: Did you mean ARM_MPU_NRF52X_ENABLE?

2017-05-15 18:50 UTC, mike-scott commented
@galak Woops.. arm branch right.  Would it be ok to finish the initial review here so we can keep these comments and then re-post once @cvinayak and @carlescufi are ok w/ the patch?

2017-05-15 20:21 UTC, galak commented
Sure no issues w/waiting til comments are agreed or when you repost a version

2017-05-15 22:36 UTC, mike-scott commented
CHANGES:
- Updated the memory regions slightly to add the ARM M4 Private Peripheral area (which is also included in the STM32 and ARM Beetle configs).
- merged the 2 peripheral areas into 1 so we don't use too many areas
- Fixed compile warning by adding "SOC_FAMILY_NRF5" to the "depends on SOC_FAMILY_ARM || SOC_FAMILY_STM32 || SOC_FAMILY_NRF5" line in the ARM_MPU config.. NOTE: Currently, only nRF52x is supported but I emulated the other checks here for STM32 and ARM where not all of their devices are supported... but probably will be in the future.

2017-05-15 22:37 UTC, mike-scott commented
Also removed Change-Id.

2017-05-16 03:36 UTC, cvinayak commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
_ENABLE is unnecessary, and makes the define long. The feature is enabled if it is defined to 'y'; 

CONFIG_ARM_MPU_NRF52X=y

This is sufficient to convery, ARM arch MPU in NRF52X is enabled (=y).

2017-05-16 07:07 UTC, carlescufi commented on arch/arm/soc/nordic_nrf5/nrf52/Makefile
> +obj-$(CONFIG_NRF52_ARM_MPU_ENABLE) += arm_mpu_regions.o
This might be because it refers to ARM's standard MPU, as opposed to a custom MPU implemented by the IC vendor

2017-05-16 07:09 UTC, carlescufi commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
Agreed with @cvinayak, CONFIG_ARM_MPU_NRF52X sounds best to me as well

2017-05-16 07:11 UTC, carlescufi commented on arch/arm/soc/nordic_nrf5/nrf52/arm_mpu_regions.c
> +#define XICR_BASE	0x10000000
@galak he means between XICR_BASE and 0x10000000, that's what we do in the bluetooth subsystem

2017-05-16 12:44 UTC, fvincenzo commented on arch/arm/soc/nordic_nrf5/nrf52/Makefile
> +obj-$(CONFIG_NRF52_ARM_MPU_ENABLE) += arm_mpu_regions.o
mpu_regions is the configuration file for a specific mpu, to easily identify the vendor, the format of the configuration file name currently is <vendor>_mpu_regions and the driver filename is <vendor>_mpu.

2017-05-16 12:56 UTC, fvincenzo commented on arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc
> +config NRF52_ARM_MPU_ENABLE
In my opinion this parameter should be considered vendor specific and can be called in any way as far as it makes sense :smile: and respects the dependencies. Said that my preference would be NRF52X_ARM_MPU to maintain the same order used for STM32 and Beetle.

2017-05-19 00:27 UTC, mike-scott commented
Rebased on arm branch and addressed @carlescufi  / @cvinayak comments

2017-05-19 00:28 UTC, mike-scott commented on arch/arm/soc/nordic_nrf5/nrf52/mpu_mem_cfg.h
> +#ifndef _ARM_MPU_MEM_CFG_H_
Woops.. need to fix the header guard.

2017-05-19 13:14 UTC, galak commented
Would like to see @carlescufi / @cvinayak approve this from a review point of view

2017-05-19 13:19 UTC, carlescufi approved these changes
Looks fine to me, nothing to add.

2017-05-19 19:49 UTC, mike-scott commented
Changes:
- Rebased on latest ARM branch
- Fixed up the mpu_mem_cfg.h header guard: 
#ifndef _NRF52X_MPU_MEM_CFG_H_

2017-05-22 18:36 UTC, galak approved these changes

2017-05-22 19:15 UTC, merged