scripts: dts: Accept 'status = "ok"'
zephyrproject-rtos/zephyr pull request #19408
Opened 2019-09-26 14:31 UTC by ulfalizer

Erroring out for 'status = "ok"' broke backwards compatibility for a
downstream project. Accept it instead.

Maybe the error could be selectively re-enabled later.

The rest of the code only checks for 'status = "disabled"' (like the old
scripts), so no other updates are needed.

(It's a bit weird that we duplicate the property check in base.yaml.
Thinking of including base.yaml implicitly. Could clean things up then.)

2019-09-26 14:31 UTC, ulfalizer commented
CC @rallare

Alternative to https://github.com/zephyrproject-rtos/zephyr/pull/19396. Pick your favorite.

2019-09-26 14:34 UTC, carlescufi approved these changes

2019-09-26 14:44 UTC, SebastianBoe approved these changes

2019-09-26 14:48 UTC, galak requested changes
NAK.  The spec clearly states 'okay'.  Why should we support anything else?

2019-09-26 14:51 UTC, ulfalizer commented
I wrote a tip re. running

```
$ git ls-files | xargs sed -i 's/status\s*=\s*"ok"/status = "okay"/'
```

to fix it in a single command, on the Nordic mail. That removes the need to hand-edit a ton of files at least.

2019-09-26 15:03 UTC, carlescufi commented
> NAK. The spec clearly states 'okay'. Why should we support anything else?

My argument would be because Linux still uses `ok` all over the place and many DTS files out there use `ok`.

2019-10-30 07:21 UTC, galak commented
I'm closing this as we should treat 'ok' as an error.  Feel free to re-open if needed.

2019-10-30 15:01 UTC, galak commented
> Re-opening because we should not treat 'ok' as an error.

As stated, this is not part of the spec and I don't see any reason to support this in upstream.  Feel free to raise to the TSC.

2019-10-31 09:40 UTC, SebastianBoe commented
>  I don't see any reason to support this in upstream. 

Here are two reasons;

Backwards-compatibility.
Linux-compatibility.

2019-11-07 12:20 UTC, pabigot commented
Looks like Linux has this [as a deviation](https://elinux.org/Device_Tree_Linux#status_property) from the original ePAPR 1.1 spec (which did *not* allow "ok").

2019-11-07 16:40 UTC, galak approved these changes

2019-11-07 22:20 UTC, ulfalizer commented
> Looks like Linux has this [as a deviation](https://elinux.org/Device_Tree_Linux#status_property) from the original ePAPR 1.1 spec (which did _not_ allow "ok").

Think it's more being tolerated than accepted though. It's very rare:

```
$ git grep 'status = "okay"' | wc -l
13704
$ git grep 'status = "ok"' | wc -l
349
```

I think it'd make us look sloppy if we allowed it to spread.

2019-11-07 23:43 UTC, ulfalizer commented
Some related clean-up commits from Linux found with `git log -S'status\*s=\s*"ok"'`, just to show what the sentiment is:

```
84024468cf16 devicetree: Adjust status "ok" -> "okay" under drivers/of/
5c285dd76c7f powerpc/dts: Standardize DTS status assignments from "ok" to "okay"
1dd5e986a9b9 media: dt-bindings: media: rcar_vin: Use status "okay"
231b362aec8c arm64: dts: NS2: convert "ok" to "okay"
d8fc23051a9b ARM: dts: porter: Always use status "okay" to enable devices
```

2019-12-03 14:47 UTC, SebastianBoe commented
It has been decided that we should acceept  'status = "ok"'

2019-12-03 15:06 UTC, pabigot commented
> It has been decided that we should accept 'status = "ok"'

I have no objections, but could we have some documentation on who was involved in this decision, where it was discussed, and the reasoning behind it?

2019-12-03 15:43 UTC, SebastianBoe commented
IIRC it was a TSC meeting, perhaps @galak can confirm. I assume the TSC meetings have meeting minutes that could be read.

2019-12-03 15:48 UTC, pabigot commented
I don't remember this being discussed in TSC and searching for "status" and "ok" show no relevant matches in the minutes going back to June.

2019-12-09 17:49 UTC, merged