doc: relnotes: 1.14.1 release notes
zephyrproject-rtos/zephyr pull request #19411
Opened 2019-09-26 15:37 UTC by carlescufi

Remove unused sections, bugfix list will come later. Also mention the
Bluetooth qualification listings with the Controller still TBD.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2019-09-26 16:58 UTC, jhedberg approved these changes

2019-09-26 20:30 UTC, dleach02 approved these changes

2019-09-26 23:09 UTC, dbkinder requested changes

2019-09-26 23:09 UTC, dbkinder commented on doc/releases/release-notes-1.14.rst
> +  * 1.14.x Controller subsystem qualified on Nordic nRF52 with QDID <TBD>
Need a QDID number for the ``<TBD>`` here, right?  Or are we releasing 1.14.1 before we know the QDID number?   Also should these three lines say 1.14.1 (and not 1.14.x) ?

2019-09-27 09:17 UTC, carlescufi commented on doc/releases/release-notes-1.14.rst
> +  * 1.14.x Controller subsystem qualified on Nordic nRF52 with QDID <TBD>
I will get the QDID number today and update the PR. No, the lines should say 1.14.x because that is what we are qualifying: the 1.14 series.

2019-09-30 02:21 UTC, nashif approved these changes

2019-09-30 02:21 UTC, merged