soc : mec1501 : Deep and light sleep example
zephyrproject-rtos/zephyr pull request #19423
Opened 2019-09-27 00:24 UTC by scottwcpg

Created MEC1501 deep and light sleep example for MCHP MEC1501.
Modifications were made to SoC, board, timer, and hello world
sample program. Power management split into SoC power
implementing the interface and device power for device specific
logic.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

2019-09-27 23:33 UTC, albertofloyd commented on soc/arm/microchip_mec/mec1501/device_power.c
> +{
I see PLL never shutting off when triggering deep sleep  from BIOS command line.
Better to have this disabled by default until root cause is known

2019-09-30 22:42 UTC, andrewboie commented
@scottwcpg please rebase, CI failure seems unrelated

2019-10-01 17:28 UTC, scottwcpg commented
Rebased per request.

2019-10-03 00:08 UTC, albertofloyd commented on soc/arm/microchip_mec/mec1501/power.c
> +	soc_deep_sleep_non_wake_en();
@scottwcpg  add macro to have this functionality disable by default

2019-10-15 06:24 UTC, albertofloyd commented
@wentongwu  could you review this?

2019-10-15 14:05 UTC, wentongwu requested changes

2019-10-15 14:05 UTC, wentongwu commented on soc/arm/microchip_mec/mec1501/power.c
> +		__enable_irq();
please use zephyr's interface to change irq state.

2019-10-22 20:31 UTC, scottwcpg commented on soc/arm/microchip_mec/mec1501/power.c
> +	__set_BASEPRI(0);
The Cortex-M4 will not wake on a pending interrupt if that interrupts priority is less than the mask value. If I use z_arch_irq_lock then the system will not wake due to the normal wake sources.  The point of setting PRIMASK=1 and BASEPRI=0 is to allow the peripheral interrupts to wake the system but NOT enter the ISR until all wake clean-up code which restores peripheral state. I looked but only found z_irq_lock/unlock which do not do what I need.

2019-11-07 18:33 UTC, albertofloyd commented
@wentongwu could you review scott comments?

2019-11-21 05:31 UTC, wentongwu approved these changes

2019-12-04 21:55 UTC, albertofloyd approved these changes

2019-12-05 00:16 UTC, dcpleung approved these changes

2019-12-05 18:15 UTC, tyrantlizard77 approved these changes

2019-12-09 16:57 UTC, merged

2020-01-08 14:57 UTC, wentongwu commented on soc/arm/microchip_mec/mec1501/power.c
> + * Cons:
so for deep sleep and light sleep, the difference is that the PLL(48Mhz) for CPU clock is on or off? If yes, can I understand that CPU just have different clock for deep/light sleep? @scottwcpg

2020-01-08 15:02 UTC, wentongwu commented on soc/arm/microchip_mec/mec1501/device_power.c
> + * the EC. Once the peripheral has serviced the external master the PLL
from this comment, it seems there is another PLL for peripherals?