coccinelle: final pass standardizing integer timeout parameters
zephyrproject-rtos/zephyr pull request #19650
Opened 2019-10-07 12:57 UTC by pabigot

(At least I think this is final, but I've thought that before.)

This PR like the others is best reviewed at the commit level, as there are a lot of rote changes.  Only the changes to the `.cocci` script are by hand.

Three features in this:
* Fixed a few errors in the existing regular expression intended to detect API calls that passed a timeout in the last parameter.  No errors resulted in incorrect conversion in previous PRs, and only one missed function resulted in a new conversion.
* Convert `k_sleep` to take timeouts.  There's been some discussion of whether this should remain milliseconds, but the consensus was that being able to use explicit duration macros like `K_MSEC` and `K_SECONDS` was highly desired.  The scale tipped to "timeout" for me when I discovered that `k_sleep()` specifically relies on the thread timeout infrastructure (it's a no-op if threads are disabled).  If the consensus switches again, those commits can be dropped.

    I have a proposal in draft that would preserve use those API macros for time-defined timeouts even when #17155 revisions are done so unifying it now seems to make sense.  If that proposal doesn't fly we'd still want to replace these.
* Convert static and runtime thread start delays to timeouts.  Most static definitions did this already, but it took me a while to figure out how to make Coccinelle convert the missing ones.

2019-10-08 09:22 UTC, nvlsianpu approved these changes
looks good in my areas

2019-10-08 12:12 UTC, joerchan approved these changes

2019-10-08 21:18 UTC, nashif requested changes

2019-10-08 21:18 UTC, nashif commented on .shippable.yml
>      global:
please remove this change, we will need to override CI in this case..

2019-10-08 21:22 UTC, nashif requested changes

2019-10-08 21:22 UTC, nashif commented on tests/kernel/mbox/mbox_api/src/test_mbox_api.c
>  			     NULL);
Please put this with other code change and separate it from the coccinelle script change.

2019-10-08 21:35 UTC, pabigot commented
@nashif shippable patch removed, API change separated, rebased on current master (no new changes were required).

2019-10-09 07:39 UTC, vanwinkeljan approved these changes
display related changes LGTM

2019-10-09 08:17 UTC, jfischer-no approved these changes

2019-10-09 12:18 UTC, aescolar approved these changes
No complaints for the few files I own.

2019-10-09 12:37 UTC, nashif approved these changes

2019-10-09 12:38 UTC, merged