Bluetooth: Mesh: Persistent storage of Virtual Addresses
zephyrproject-rtos/zephyr pull request #19799
Opened 2019-10-14 11:13 UTC by LingoMeng

The 16-bit format group addresses will be stored,
but we don't store (or restore) the virtual label UUIDs,
i.e. after a power cycle the 16-bit group addresses
would be meaningless.

Fixes #19342

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

2019-10-14 11:14 UTC, jhedberg commented
How does this related to #19499? Why did you open a new PR instead of continuing with the existing one?

2019-10-14 11:45 UTC, LingoMeng commented
This PR should be more concise than before.

2019-10-16 08:36 UTC, trond-snekvik requested changes
All my comments from the previous PR have been resolved 👍 

I think the `get_label()` function in cfg_srv.c is a code smell, and it'd be better to take the index as a parameter to that function. That way, we'd encapsulate the array and its boundary. We'd still be manipulating another module's data though, but this is kind of the nature of the settings module. 

@jhedberg: Perhaps the settings module should be restructured to only be a multiplexer for the "bt/mesh" settings directory, and the handlers should go into their respective modules? In a separate task, of course.

2019-10-16 08:49 UTC, jhedberg commented
> @jhedberg: Perhaps the settings module should be restructured to only be a multiplexer for the "bt/mesh" settings directory, and the handlers should go into their respective modules? In a separate task, of course.

@trond-snekvik yes, sounds like a good idea

2019-10-16 11:18 UTC, trond-snekvik requested changes

2019-10-16 11:18 UTC, trond-snekvik commented on subsys/bluetooth/mesh/cfg_srv.c
> +	return labels[index];
Should be `return &labels[index]`

2019-10-16 11:18 UTC, trond-snekvik commented on subsys/bluetooth/mesh/settings.c
> +	       lab[index].addr, lab[index].ref);
should not use the index anymore, as we're getting the pointer directly to the label. All of the `lab[index].` in this function should be `lab->`

2019-10-16 11:18 UTC, trond-snekvik commented on subsys/bluetooth/mesh/settings.c
> +					IS_VA_DEL(lab[i])?"Deleted":"Stored",
Same here with the index (should be `*lab` and `lab->`)

2019-10-16 12:29 UTC, trond-snekvik approved these changes

2019-10-16 12:55 UTC, jhedberg approved these changes

2019-10-16 12:57 UTC, jhedberg requested changes
Could you please squash these 5 patches into a single one (using e.g. `git rebase -i` and then `git push --force` to update this PR? Otherwise the result looks good and mergeable to me.

2019-10-17 05:40 UTC, trond-snekvik approved these changes

2019-10-17 06:22 UTC, jhedberg requested changes
Thanks for doing the squashing. I have a few more coding-style related comments, sorry about missing those issues earlier!

2019-10-17 06:22 UTC, jhedberg commented on subsys/bluetooth/mesh/settings.c
> +					BT_MESH_VA_CHANGED)) {
Make this:
```
if (!atomic_test_and_clear_bit(...)) {
        continue;
}

...
```

That way you reduce one level of indentation from most of the stuff in the for-loop and avoid having to do line splits so easily.

2019-10-17 06:22 UTC, jhedberg commented on subsys/bluetooth/mesh/foundation.h
> +enum label_flag {
I don't think you necessarily need a name for this enum, at least I don't think I saw you use the name anywhere

2019-10-17 06:22 UTC, jhedberg commented on subsys/bluetooth/mesh/foundation.h
> +	atomic_t flag[1];
Call this `flags` to be consistent with the naming used elsewhere

2019-10-17 06:22 UTC, jhedberg commented on subsys/bluetooth/mesh/settings.c
> +					IS_VA_DEL(lab)?"delete":"store",
Minor coding style: there should be spaces before & after `?` and `:`

2019-10-17 06:22 UTC, jhedberg commented on subsys/bluetooth/mesh/settings.c
> +					IS_VA_DEL(lab)?"Deleted":"Stored",
Same here

2019-10-17 07:21 UTC, jhedberg approved these changes

2019-10-17 07:28 UTC, jhedberg commented
@LingoMeng please stop pushing to this PR, I've fixed up some coding style issues and pushed them to it, and I've approved the PR, so let's just wait for CI to finish so we can merge it.

2019-10-17 09:24 UTC, merged