arch: arm: error: fix ARMv6-M assembly for Z_ARCH_EXCEPT
zephyrproject-rtos/zephyr pull request #19825
Opened 2019-10-15 11:48 UTC by ioannisg

As we are allowed to pass any integer value as as software
fatal exception reason, we need to fix the inline assembly
for ARMv6-M, to accept large immediate offsets. We do this
by changing MOV to LDR. We add a test case in kernel/fatal
to cover this scenario.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2019-10-15 11:52 UTC, ioannisg commented
ARMv6-M won't build for error reasons above 0xff.

2019-10-15 13:46 UTC, agansari requested changes

2019-10-15 13:46 UTC, agansari commented on include/arch/arm/error.h
> +		"ldr r0, =%[reason]\n\t" \
move to a separate commit

2019-10-15 17:13 UTC, andrewboie commented on tests/kernel/fatal/src/main.c
> +	zassert_not_equal(rv, TC_FAIL, "thread was not aborted");
this test is run on all arches, so yes, otherwise CI would fail for this PR

2019-10-15 17:13 UTC, tyrantlizard77 approved these changes

2019-10-15 17:18 UTC, ioannisg commented
@andrewboie @agansari I will split the test-addition in a separate commit, and I will rework the Z_ARCH_EXCEPT for ARMv6, so it works in all cases. Stay tuned. This is the last prerequisite for USer Mode on ARMv6.m

2019-10-15 17:55 UTC, ioannisg commented on include/arch/arm/error.h
> +		"ldr r0, =%[reason]\n\t" \
Moved

2019-10-15 17:56 UTC, ioannisg commented on tests/kernel/fatal/src/main.c
> +	zassert_not_equal(rv, TC_FAIL, "thread was not aborted");
@andrewboie , I added a test case for arbitrary error reasons in SW-generated exceptions. There's a similar test for user mode (where only OOPS and ST FAIL may be reported)

2019-10-16 06:21 UTC, agansari approved these changes

2019-10-16 09:22 UTC, carlescufi approved these changes

2019-10-16 09:22 UTC, merged