boards: PineTime board skeleton
zephyrproject-rtos/zephyr pull request #19973
Opened 2019-10-21 00:25 UTC by rafacouto

Pinout reference: http://files.pine64.org/doc/datasheet/pinetime/PineTime%20Port%20Assignment%20rev0.2.pdf

Signed-off-by: Rafa Couto <caligari@treboada.net>

2019-10-22 20:42 UTC, dbkinder requested changes
Docs are not quite ready for review, but here's a fix for the doc build failure.

2019-10-25 19:26 UTC, DWagenk commented
received one of the devkits today and will collaborate on getting zephyr running on it as soon as I've got some free time (sometime in november)

2019-10-27 23:44 UTC, rafacouto commented
> Docs are not quite ready for review, but here's a fix for the doc build failure.

Thank you for the tips :+1:

2019-10-28 19:03 UTC, dbkinder requested changes

2019-10-28 19:03 UTC, dbkinder commented on boards/arm/pinetime_devkit0/doc/index.rst
> +
Normally, links to other docs like this won't be displayed in the generated HTML. If you do want them to show up, add a directive before the first link:

```
.. target-notes::

.. _Pine64 wiki: https://wiki.pine64.org/index.php/PineTime
```

2019-11-01 23:22 UTC, dbkinder reviewed
OK.  Doc build errors are resolved.  Will there be more documentation coming?  I wandered around looking for some sample code for this platform and found some stuff written in Go on GitHub (https://github.com/aykevl/go-smartwatch/blob/master/smartwatch_pinetime-devkit0.go).  
What's the plan for this devkit and Zephyr?

2019-11-11 13:25 UTC, rafacouto commented
> OK. Doc build errors are resolved. Will there be more documentation coming? I wandered around looking for some sample code for this platform and found some stuff written in Go on GitHub (https://github.com/aykevl/go-smartwatch/blob/master/smartwatch_pinetime-devkit0.go).

I will commit some basic sample in a few days (_samples/boards/pinetime_devkit0/blink_, right?).

> What's the plan for this devkit and Zephyr?

This is the board skeleton in order to developers are able to start their firmware apps with Zephyr.

2020-04-17 09:00 UTC, galak commented
Any plans to update this PR?

2020-04-28 20:09 UTC, DWagenk commented
@galak Thanks for cleaning up here. I guess closing this one and opening a new one once there's momentum again would be best. I'm still interested and did some testing based on this PR with the device, but can't forsee when I'll have time to pick it up again.

2020-07-06 15:11 UTC, sdorre commented
May I help on this topic, I really would love to see the PineTime officially supported by Zephyr

2020-07-08 15:26 UTC, galak commented
Closing this PR and lets focus on #26698

2020-07-08 15:26 UTC, closed without merging