power: stm32wb: support of the Low Power Mode
zephyrproject-rtos/zephyr pull request #20155
Opened 2019-10-25 13:52 UTC by FRASTM

This patch enables the low power Mode for the stm32wb soc. 
It uses the LPTIM timer as tickless timer. 
This PR requires Implementation on L4 series (#18582) and Extend to other LP series (WB: #19818 
The SLEEP (0,1,2) modes are supported on this device.
Only the HSE clock is restored after sleep Mode.
This PR requires an update of the hal_stm32  https://github.com/zephyrproject-rtos/hal_stm32/pull/24

Signed-off-by: Francois Ramu francois.ramu@st.com

2020-03-30 13:19 UTC, FRASTM commented
rebase and adapt on top of  https://github.com/zephyrproject-rtos/zephyr/pull/19026

2020-03-30 13:44 UTC, FRASTM commented
remove blank line

2020-06-09 06:13 UTC, erwango requested changes
Please fix commit message ("# Conflicts: ....")

2020-06-11 08:33 UTC, FRASTM commented
stm32wb low power modes depends on the CONFIG_SYS_POWER_MANAGEMENT

2020-06-12 12:38 UTC, FRASTM commented
move the

config STM32_LPTIM_TIMER
	bool
	default y
	depends on SYS_POWER_MANAGEMENT

from soc/arm/st_stm32/common/Kconfig.defconfig.series to soc/arm/st_stm32/stm32wb/Kconfig.defconfig.series

2020-06-15 08:00 UTC, erwango requested changes
One last comment.

2020-06-16 07:53 UTC, FRASTM commented on subsys/power/device.c
> +#define MAX_PM_DEVICES	2
setting 2 PM_DEVICES for WB and L4 soc, except if MAX_PM_DEVICES means something else

2020-06-16 11:54 UTC, erwango requested changes

2020-06-16 11:54 UTC, erwango commented on subsys/power/device.c
> +#define MAX_PM_DEVICES	2
I don't actually understand why this is increased when adding WB support.
If this is 1 for L4, it should be 1 for WB, right ?

2020-06-16 19:44 UTC, erwango approved these changes

2020-06-23 12:40 UTC, ABOSTM reviewed
File power.c for WB looks very similar to L4 file. Is there no way to have a common file ?

2020-06-23 13:39 UTC, FRASTM commented on subsys/power/device.c
> +#define MAX_PM_DEVICES	2
changing 1 for L4 or WB

2020-06-23 16:02 UTC, ABOSTM approved these changes

2020-06-24 06:59 UTC, erwango commented
Sanitychek failure: ' Sanitycheck / qemu_arc_hs:tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1 / tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1'

2020-06-30 13:43 UTC, FRASTM commented
rebase

2020-07-02 12:45 UTC, merged