tests: eliminate the compile warning for arc
zephyrproject-rtos/zephyr pull request #20179
Opened 2019-10-28 09:26 UTC by vonhust

the compile warning will fail the CI

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

2019-10-28 14:30 UTC, abrodkin submitted a review, later dismissed
Could you please refer to CI breakage you're referring to and preferably include CI message about problem in commit message? Otherwise it makes not much sense. Also it would be really good to explain what was the reason for CI complaint really.

2019-10-29 02:21 UTC, vonhust commented
> Could you please refer to CI breakage you're referring to and preferably include CI message about problem in commit message? Otherwise it makes not much sense. Also it would be really good to explain what was the reason for CI complaint really.

Here is the  CI msg from the PR #20082 :

FAILED: ccache /opt/sdk/zephyr-sdk-0.10.3/arc-zephyr-elf/bin/arc-zephyr-elf-gcc -DBUILD_VERSION=zephyr-v2.0.0-1505-g2fbb24ee3385 -DKERNEL -DPI_NUM_ITERATIONS=500 -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/kernel/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/arc/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/drivers -Izephyr/include/generated -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/soc/arc/snps_nsim -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/testsuite/include -isystem /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/lib/libc/minimal/include -isystem /opt/sdk/zephyr-sdk-0.10.3/arc-zephyr-elf/bin/../lib/gcc/arc-zephyr-elf/8.3.0/include -isystem /opt/sdk/zephyr-sdk-0.10.3/arc-zephyr-elf/bin/../lib/gcc/arc-zephyr-elf/8.3.0/include-fixed -Os -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/nsim_hs/tests/kernel/fp_sharing/generic/kernel.fp_sharing.arc/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mcpu=hs -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -Werror -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -g3 -gdwarf-2 -fno-delete-null-pointer-checks -munaligned-access -mno-sdata -mmpy-option=plus_qmacw -mfpu=fpud_all -std=c99 -nostdinc -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj   -c /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/main.c
In file included from /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/main.c:68:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/float_regs_arc_gcc.h: In function '_load_all_float_registers':
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/float_regs_arc_gcc.h:41:8: error: unused variable 'temp' [-Werror=unused-variable]
  u32_t temp = 0;
        ^~~~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/float_regs_arc_gcc.h: In function '_store_all_float_registers':
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/fp_sharing/generic/src/float_regs_arc_gcc.h:75:8: error: unused variable 'temp' [-Werror=unused-variable]
  u32_t temp = 0;
        ^~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

2019-10-29 05:05 UTC, galak requested changes
Please update the commit message to be something like:

```
commit bc181596766ffb9685e712455e33f2c0a0c0271e
Author: Kumar Gala <kumar.gala@linaro.org>
Date:   Thu Oct 3 18:32:35 2019 -0500

    kernel: Fix gcc-9.2 warning with _StackCheckHandler
    
    Remove FUNC_NORETURN attribute from _StackCheckHandler to address the
    following warning from gcc-9.2:
    
    kernel/compiler_stack_protect.c:62:32: error: '__stack_chk_fail'
    specifies less restrictive attribute than its target
    '_StackCheckHandler': 'noreturn' [-Werror=missing-attributes]
    
    Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
```

2019-10-29 05:58 UTC, vonhust commented
@galak  already done

2019-10-30 08:28 UTC, galak approved these changes

2019-10-30 08:28 UTC, merged