sensor: lis3mdl-magn: Convert GPIO INT to device tree
zephyrproject-rtos/zephyr pull request #20343
Opened 2019-11-05 13:26 UTC by galak

Update lis3mdl-magn dts binding to include GPIO interrupt pin and change
driver code to get the GPIO pin and controller info from DT instead of
Kconfig.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2019-11-05 14:58 UTC, erwango requested changes

2019-11-05 15:18 UTC, erwango approved these changes

2019-11-06 14:44 UTC, avisconti commented
@erwango 
have you tested it on the shield x_nucleo_iks01a1?

2019-11-06 15:21 UTC, erwango commented
> have you tested it on the shield x_nucleo_iks01a1?

@avisconti, yes, and it is failing for now.
Since this not a regression per se, and not the intent of the change, I plan to fill an issue once the PR is merged (as currently busy with other stuff).

2019-11-06 16:10 UTC, merged