Collect TCP statistics
zephyrproject-rtos/zephyr pull request #204
Opened 2017-05-16 13:59 UTC by jukkar

2017-05-16 14:41 UTC, tbursztyka requested changes

2017-05-16 14:41 UTC, tbursztyka commented on subsys/net/ip/connection.c
>  	}
Hum, why not wrapping this if/else if (as well as the update recv above) in an inline function such as: 
net_stats_update_per_proto_recv(proto);
and:
net_stats_update_per_proto_drop(proto);

2017-05-16 17:01 UTC, lpereira commented on subsys/net/ip/connection.c
>  	}
+1 for this

2017-05-17 06:33 UTC, jukkar commented on subsys/net/ip/connection.c
>  	}
Sure, why not. I will cook a new version.

2017-05-17 08:05 UTC, jukkar commented
New version sent. Added also new patch that adds possibility to update UDP checksum error count.

2017-05-17 08:27 UTC, jukkar commented
Added two more statistics related fixes that I noticed while testing the statistics printing.

2017-05-17 09:56 UTC, pfalcon approved these changes
I'd also find enabling stats by default strange. As a further step on https://jira.zephyrproject.org/browse/ZEP-2105, I wanted to propose to enable NET_ERR logging by default (so the case of no netif's was visibly reported to a user). Assuming we can only have one enabled by default - stats or err logging, I'd prefer logging.

2017-05-17 09:56 UTC, pfalcon commented on include/net/net_stats.h
> +	/** Number of received TCP bad RST (reset) segments. */
Minor nitpick: "TCP bad RST" sounds strange, maybe "bad TCP RST"?

2017-05-17 10:25 UTC, jukkar commented
> I'd also find enabling stats by default strange.

Please note that we enable only statistics for given subsystem like RPL if both CONFIG_NET_STATISTICS and CONFIG_NET_RPL is defined. IMHO this is quite logical now so that user does not have to separately enable RPL statistics in this case.

2017-05-17 10:26 UTC, jukkar commented on include/net/net_stats.h
> +	/** Number of received TCP bad RST (reset) segments. */
sure, I will fix that

2017-05-17 10:54 UTC, tbursztyka approved these changes

2017-05-17 10:54 UTC, tbursztyka approved these changes

2017-05-17 10:54 UTC, tbursztyka approved these changes

2017-05-17 10:55 UTC, tbursztyka approved these changes

2017-05-17 10:55 UTC, merged