subsys/usb: correct dfu upload implementation
zephyrproject-rtos/zephyr pull request #20745
Opened 2019-11-16 12:23 UTC by pabigot

The routine to read the image from the device and upload it to the
host stored data in a buffer unrelated to the one transferred to the
host, resulting in a corrupt image.

This fixes `samples/usb/dfu` so the upload command does what the sample says it will.

2019-11-16 23:15 UTC, jfischer-no requested changes
Thanks, please change `subsys/usb:` to `usb: dfu` in commit title.

2019-11-16 23:15 UTC, jfischer-phytec-iot commented on subsys/usb/class/usb_dfu.c
> +						      *data, len);
Please also remove [buffer](https://github.com/zephyrproject-rtos/zephyr/pull/20745/commits/6e3c6a2e2151c620bc3c4e33bdda08d7ce42e475#diff-98a1f9ecb2c01757bdb4413acdfcab02R293) from struct dfu_data_t

2019-11-17 19:31 UTC, jfischer-no approved these changes

2019-11-18 12:50 UTC, carlescufi approved these changes

2019-11-18 12:50 UTC, merged