dts: Rename generated_dts_board* to devicetree*, with backwards compatibility
zephyrproject-rtos/zephyr pull request #20757
Opened 2019-11-18 05:13 UTC by ulfalizer

Three commits:

```
dts: Rename generated_dts_board*.{h,conf} to devicetree*.{h,conf}

generated_dts_board* is pretty redundant and confusing as a name.

dts.h would be another option, but DTS stands for "devicetree source"
and is the source code format, so it's a bit confusing too.

The replacement was done by grepping for 'generated_dts_board' and
'GENERATED_DTS_BOARD'.
```

```
dts: Add include/generated_dts_board.h for backwards compatibility

Includes include/devicetree.h and generates a warning.
```

```
doc: release-notes-2.1: Mention generated_dts_board* renaming

generated_dts_board*.{h,conf} have been renamed to devicetree*.{h,conf}.
```

2019-11-18 05:17 UTC, cvinayak approved these changes
QUICK ACK.

2019-11-18 08:09 UTC, ulfalizer commented
Needs https://github.com/zephyrproject-rtos/ci-tools/pull/111 and https://github.com/zephyrproject-rtos/hal_ti/pull/3. Multi-repo makes changes like these awkward.

2019-11-18 09:10 UTC, aescolar commented
@erwango, @rlubos, @dcpleung, @nategraff-sifive and @wentongwu : Sorry, the list of reviewers was over the maximum allowed and trying to edit it caused it to be truncated

2019-11-18 10:23 UTC, George-Stefan commented
@alexandru-porosanu-nxp ^^

2019-11-18 18:00 UTC, galak submitted a review, later dismissed
@SebastianBoe had some desire that we use toolchain_cc_imacros() to get devicetree.h included the same way we include `${AUTOCONF_H}` so we don't need to do the `#include`.

So lets close on that before we rename everything vs removing those lines.

2019-11-20 11:15 UTC, ulfalizer commented
> @SebastianBoe had some desire that we use toolchain_cc_imacros() to get devicetree.h included the same way we include `${AUTOCONF_H}` so we don't need to do the `#include`.
> 
> So lets close on that before we rename everything vs removing those lines.

Renaming is still worthwhile to reduce developer confusion I think, but no panic at least.

2019-11-20 12:01 UTC, galak commented
> Renaming is still worthwhile to reduce developer confusion I think, but no panic at least.

Yeah, I'm not opposed to the file renaming.  Just figure if we're going to touch all the files that include things likes decide how we want to really do it, and make that part of the change once.  see issue #7214

2019-11-20 19:12 UTC, dbkinder approved these changes
doc changes LGTM (and isn't' it nice to be able to grep and edit SVG images :)

2019-12-10 01:57 UTC, galak commented
Can you rebase.

2019-12-10 09:53 UTC, SebastianBoe commented on include/devicetree.h
> +#include <devicetree_unfixed.h.deprecated>
This is no longer present is it?

2019-12-10 17:29 UTC, ulfalizer commented on include/devicetree.h
> +#include <devicetree_unfixed.h.deprecated>
Nope. Fixed.

2019-12-10 17:29 UTC, ulfalizer commented
> Can you rebase.

Rebased now.

2019-12-14 01:22 UTC, ulfalizer commented
@galak 
ping

2019-12-18 21:05 UTC, carlescufi commented
> @SebastianBoe had some desire that we use toolchain_cc_imacros() to get devicetree.h included the same way we include `${AUTOCONF_H}` so we don't need to do the `#include`.
> 
> So lets close on that before we rename everything vs removing those lines.

Is this still the case @SebastianBoe?

2019-12-18 23:40 UTC, ulfalizer commented
The way to merge this is to first merge https://github.com/zephyrproject-rtos/ci-tools/pull/111. I'll then update this PR to also add the ci-tools change.

`GENERATED_DTS_BOARD` needs to be renamed to `DEVICETREE_CONF` simultaneously in both repos.

2019-12-19 13:26 UTC, SebastianBoe commented
> @SebastianBoe had some desire that we use toolchain_cc_imacros() to get devicetree.h included the same way we include ${AUTOCONF_H} so we don't need to do the #include.

This was based on a model where the user could consider DT and Kconfig symbols to be originating from two different sources based on the prefix, but otherwise be two equal configuration systems that are merged together and available in a consistent way.

But we have now moved DT out of CMake, so these symbols are not available simultaneously and it is not a reasonable assumption that they are available through the same mechanisms.

Including devicetree.h through the preprocessor is reasonable since using "-include" is not without issues (it causes trouble for static analyzers, IDE's, programmers looking for where a symbol comes frlom, and other tooling).

2019-12-21 04:41 UTC, ulfalizer commented
Rebased again. Some headers got moved around.

@carlescufi 
See https://github.com/zephyrproject-rtos/zephyr/pull/20757#issuecomment-567261796 for how to merge.

2020-01-08 15:45 UTC, carlescufi approved these changes
I am OK with this change as it is now after @SebastianBoe 's explanation.

@nashif are you ok with the procedure described [here](https://github.com/zephyrproject-rtos/zephyr/pull/20757#issuecomment-567261796)?

EDIT; @ulfalizer you will need an update to `west.yml` to reflect the changes in hal_ti

2020-01-08 17:28 UTC, tbursztyka commented
sounds like a relevant change to me as well. +1

2020-01-09 05:01 UTC, ulfalizer commented
@carlescufi 
> EDIT; @ulfalizer you will need an update to `west.yml` to reflect the changes in hal_ti

Can't update `west.yml` until the commits are in. See https://github.com/zephyrproject-rtos/zephyr/pull/20757#issuecomment-567261796 for instructions.

2020-01-13 11:57 UTC, ulfalizer commented
Updated instructions (ci-tools change got in):

1. Merge https://github.com/zephyrproject-rtos/hal_ti/pull/3
2. Merge https://github.com/zephyrproject-rtos/mcuboot/pull/2
3. I'll update west.yml here
4. Merge this

2020-01-16 10:47 UTC, nvlsianpu requested changes

2020-01-16 10:47 UTC, nvlsianpu commented on west.yml
> +      revision: pull/2/head
I synchronized zephyr-fork mcuboot, use SHA : e96b6873bd8a64185796ac47b941f56dd29b6e3f

2020-01-16 10:53 UTC, carlescufi requested changes

2020-01-16 10:53 UTC, carlescufi commented on west.yml
> +      revision: pull/2/head
Please replace with e96b6873bd8a64185796ac47b941f56dd29b6e3f, now that the required fix is merged

2020-01-16 13:45 UTC, carlescufi approved these changes

2020-01-16 13:47 UTC, ulfalizer commented
Rebased now. Had a bunch of clashes in docs and elsewhere.

Also updated the diagrams with https://draw.io. For whatever reason, some of the SVG files are included directly in the documentation (`doc/guides/build/build-config-phase.svg`), while others have been converted to PNG files that are included instead (the ones in `doc/guides/dts/`).

A messy thing about `doc/guides/dts/zephyr_dt_inputs_outputs.png` is that it's not synced to `doc/guides/dts/zephyr_dt_inputs_outputs.svg`. That's why the text is a bit different in the updated version.

These diagrams have some errors and confusing stuff in them. I'll clean them separately later. I mostly just renamed `generated_dts*` to `devicetree*` here.

`doc/guides/build/build-config-phase.svg` before/after:

![config-before](https://user-images.githubusercontent.com/154768/72530046-d20f5680-386e-11ea-9eca-23fa6b84fc73.png)

![config-after](https://user-images.githubusercontent.com/154768/72530074-ddfb1880-386e-11ea-8b08-d323085f1ad3.png)

`doc/guides/dts/zephyr_dt_inputs_outputs.svg` before/after:

![devicetree-before](https://user-images.githubusercontent.com/154768/72530061-d8053780-386e-11ea-8229-1adf55770630.png)

![devicetree-after](https://user-images.githubusercontent.com/154768/72530084-e3f0f980-386e-11ea-89de-2c02678b138f.png)

2020-01-16 14:08 UTC, nvlsianpu approved these changes

2020-01-16 17:55 UTC, mbolivar commented
Very nice work!

2020-01-17 13:40 UTC, ulfalizer commented
Needs https://github.com/zephyrproject-rtos/ci-tools/pull/117 too.

2020-01-17 14:26 UTC, ulfalizer commented
> Needs [zephyrproject-rtos/ci-tools#117](https://github.com/zephyrproject-rtos/ci-tools/pull/117) too.

In now.

2020-01-17 16:58 UTC, merged