doc: Update NXP board docs for pyOCD and Segger J-Link
zephyrproject-rtos/zephyr pull request #209
Opened 2017-05-16 21:52 UTC by MaureenHelm

Now that NXP boards support 'make flash' and 'make debug' via pyOCD and
Segger J-Link, update all the NXP board docs accordingly. Adds a new
generalized OpenSDA document so certain details don't have to be
repeated for every OpenSDA board.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

2017-05-16 23:43 UTC, dbkinder commented on boards/arm/frdm_k64f/doc/frdm_k64f.rst
> +   $ . zephyr-env.sh
alas, $ZEPHYR_BASE isn't set until after you source zephyr-env.sh so you can't cd to it

2017-05-16 23:52 UTC, dbkinder commented on boards/arm/frdm_k64f/doc/opensda.rst
> +Segger offers a firmware running on the OpenSDA platform which makes OpenSDA
"a firmware" might should be just "firmware"

2017-05-16 23:53 UTC, dbkinder commented on boards/arm/frdm_k64f/doc/opensda.rst
> +microcontroller with an integrated USB controller. On the software side, it
replace "consists of a circuit featuring" with just "features"

2017-05-16 23:57 UTC, dbkinder requested changes
a few suggestions...

2017-05-17 18:45 UTC, MaureenHelm commented on boards/arm/frdm_k64f/doc/frdm_k64f.rst
> +   $ . zephyr-env.sh
Good point. How do you recommend I fix this? I think I could either 1) change line 233 to ``cd zephyr`` or 2) remove lines 233 and 234 altogether.

2017-05-17 20:24 UTC, dbkinder commented on boards/arm/frdm_k64f/doc/frdm_k64f.rst
> +   $ . zephyr-env.sh
Well, a popular way is to say:  $ cd <zephyr_root_path>

2017-05-17 23:00 UTC, dbkinder approved these changes
+1 for docs

2017-05-17 23:14 UTC, merged