doc: add recent documentation writing features
zephyrproject-rtos/zephyr pull request #20922
Opened 2019-11-22 00:16 UTC by dbkinder

We've added some new capabilities for documentation writers such as the
tabbed interface and numbered instruction steps, as used in the updated
Getting Started Guide.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

2019-11-22 16:57 UTC, MaureenHelm requested changes

2019-11-22 16:57 UTC, MaureenHelm commented on doc/guides/documentation/index.rst
> +The ``:widths:`` parameter let's you define relative column widths.  The
lets

2019-11-22 16:57 UTC, MaureenHelm commented on doc/guides/documentation/index.rst
> +easy to create tutorial guides with clearly identified steps. Simply add
Remove "Simply"

2019-11-22 16:59 UTC, dbkinder commented on doc/guides/documentation/index.rst
> +The ``:widths:`` parameter let's you define relative column widths.  The
doh!

2019-11-22 17:03 UTC, MaureenHelm approved these changes

2019-11-22 17:30 UTC, dleach02 requested changes
Show the result of the numbered-steps directive.

2019-11-22 17:39 UTC, dbkinder commented on doc/guides/documentation/index.rst
> +
Done.  Yes, along with auto-numbering the steps (as shown in the getting started guide).

2019-11-22 19:52 UTC, dleach02 approved these changes

2019-11-22 21:06 UTC, nashif approved these changes

2019-11-24 12:20 UTC, ioannisg approved these changes

2019-11-24 12:32 UTC, merged