doc: net: Enhance 802.1Qav documentation
zephyrproject-rtos/zephyr pull request #21076
Opened 2019-11-29 09:01 UTC by jukkar

There was no examples how to set the Qav parameters from application.

Fixes #21074

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2019-12-02 22:49 UTC, dbkinder requested changes
one typo, otherwise LGTM

2019-12-02 22:49 UTC, dbkinder commented on doc/reference/networking/8021Qav.rst
> +In order enable 802.1Qav shaper, the Ethernet device driver must declare
Change ``In order enable`` to ``To enable``

2019-12-03 10:40 UTC, jukkar commented
Updated according to comments.

2019-12-03 19:36 UTC, dbkinder approved these changes
+1 for doc change, thanks

2019-12-03 20:07 UTC, merged