BLE: Enable/Disable Automatic Sending of Connection Parameter update
zephyrproject-rtos/zephyr pull request #21174
Opened 2019-12-04 09:50 UTC by kipm-ot

request on GAP recommended timeout of 5 seconds.

Added a new Kconfig flag to enable/disable this feature.

Signed-off-by: Kiran Paramaswaran <kipm@oticon.com>

2019-12-04 11:24 UTC, joerchan requested changes
Looks good.

Need to update the commit message. Should be "Bluetooth: Host: Enab..."

2019-12-04 11:24 UTC, joerchan commented on subsys/bluetooth/host/conn.c
>  	atomic_set_bit(conn->flags, BT_CONN_SLAVE_PARAM_UPDATE);
Please add empty line between `}` and next code line

2019-12-04 11:34 UTC, kipm-ot commented
> Looks good.
> 
> Need to update the commit message. Should be "Bluetooth: Host: Enab..."

Sure, Done :)

2019-12-04 11:35 UTC, joerchan approved these changes

2019-12-09 15:04 UTC, jhedberg approved these changes

2019-12-09 15:04 UTC, merged

2020-04-03 14:00 UTC, dnsglk commented
Hi @kipm-ot 

shouldn't `conn.le->latency` and `conn->le.timeout` in the lines 355-356 be `conn->le.pending_latency` and `conn->le.pending_timeout` (like for the 338-339) ? The new values for latency and timeout from the app-level  are set in bt_conn_le_param_update() as `conn->le.pending_latency`, `conn->le.pending_timeout`.

https://github.com/zephyrproject-rtos/zephyr/pull/21174/files#diff-ada91fdd1e1bb24ad6bd262d126ea7afR355-R356

Thanks,
Denys