drivers: rework usb_dc_mcux_ehci
zephyrproject-rtos/zephyr pull request #21175
Opened 2019-12-04 09:59 UTC by jfischer-phytec-iot

This is bug fix, rework, and style fix of usb_dc_mcux_ehci

2019-12-04 13:27 UTC, jfischer-phytec-iot commented
Tested on IMXRT1050-EVKB, passes USB 2 CV Chapter 9 and all testusb tests now.

2019-12-05 10:39 UTC, ioannisg commented
We should perhaps hold this back, merge it after 2.1 release, we are in -rc3 already.

2019-12-05 13:14 UTC, eobalski requested changes

2019-12-09 23:57 UTC, MaureenHelm commented
@MarkWangChinese please review

2020-01-29 10:54 UTC, jfischer-phytec-iot commented on drivers/usb/device/usb_dc_mcux_ehci.c
> +	dev_data.attached = 0;
fixed

2020-01-29 10:54 UTC, jfischer-phytec-iot commented on drivers/usb/device/usb_dc_mcux_ehci.c
> +		return -EINVAL;
thanks for the point, forgot to fix it here.

2020-01-29 10:59 UTC, jfischer-phytec-iot commented on drivers/usb/device/usb_dc_mcux_ehci.c
> -		s_Device.interface->deviceControl(s_Device.controllerHandle, kUSB_DeviceControlEndpointDeinit, (void *)(&cfg->ep_addr));
sorry, what do you mean?

2020-01-29 11:21 UTC, jfischer-phytec-iot commented
Rebased. 

@MaureenHelm The header file modules/hal/nxp/mcux/middleware/usb/device/port/zephyr/usb_dc_mcux.h is a part of the driver. It hides a lot of things, has unnecessary complexity, and does not help to maintain the driver. This file should be moved to drivers/usb/device/usb_dc_mcux_hal.h and reworked/simplified. I would like to do that, this would also help to fix high speed support what I really would like to improve and test with imxrt1050.

2020-01-29 11:23 UTC, jfischer-phytec-iot commented on drivers/usb/device/usb_dc_mcux_ehci.c
> +		LOG_WRN("Device not attached");
That does not really matter, it is the current state of the device

2020-01-29 12:31 UTC, emob-nordic commented on drivers/usb/device/usb_dc_mcux_ehci.c
> -		s_Device.interface->deviceControl(s_Device.controllerHandle, kUSB_DeviceControlEndpointDeinit, (void *)(&cfg->ep_addr));
At first sight I was confused why You have removed
```
s_Device.interface->deviceControl(s_Device.controllerHandle, kUSB_DeviceControlEndpointDeinit ... );
```
But now I assume it has no sense to do that as later there is 
```
status = dev_data.interface->deviceControl(dev_data.controllerHandle,
			kUSB_DeviceControlEndpointInit, &ep_init);
```

I understand that You made some cleanup here.

2020-01-29 12:32 UTC, eobalski approved these changes

2020-02-04 15:39 UTC, jhedberg commented
@MaureenHelm did you still want someone else to review this? I see you mentioned @MarkWangChinese back in December.

2020-02-13 10:58 UTC, jhedberg commented
@jfischer-phytec-iot there seems to be a conflict with `drivers/usb/device/usb_dc_mcux_ehci.c` so you'll need to rebase. @MaureenHelm is someone else still expected to review this?

2020-02-17 05:38 UTC, hakehuang commented
test pass in this PR @MaureenHelm , @dlech 
```
_descriptor_start 0x20002b5c
D: __usb_descriptor_end 0x20002bcd
D: Configuration descriptor 0x20002b6e
D: Interface descriptor 0x20002b77
D: Endpoint descriptor 0x20002b80
D: Fixing EP address 81 -> 81
D: endpoint 0x81
D: Now the wTotalLength is 25
D: idx_max 11, ascii_idx_max 5, buf 0x20002b8d
D: char R : 52, idx 5 -> 11
D: char Y : 59, idx 4 -> 9
D: char H : 48, idx 3 -> 7
D: char P : 50, idx 2 -> 5
D: char E : 45, idx 1 -> 3
D: char Z : 5a, idx 0 -> 1
D: idx_max 13, ascii_idx_max 6, buf 0x20002b9b
D: char V : 56, idx 6 -> 13
D: char E : 45, idx 5 -> 11
D: char D : 44, idx 4 -> 9
D: char - : 2d, idx 3 -> 7
D: char B : 42, idx 2 -> 5
D: char S : 53, idx 1 -> 3
D: char U : 55, idx 0 -> 1
D: Serial Number
D: d7 49 4c 5a 46 00 00 50 |.ILZF..P
D: idx_max 31, ascii_idx_max 15, buf 0x20002bab
D: char 7 : 37, idx 15 -> 31
D: char D : 44, idx 14 -> 29
D: char 9 : 39, idx 13 -> 27
D: char 4 : 34, idx 12 -> 25
D: char C : 43, idx 11 -> 23
D: char 4 : 34, idx 10 -> 21
D: char A : 41, idx 9 -> 19
D: char 5 : 35, idx 8 -> 17
D: char 6 : 36, idx 7 -> 15
D: char 4 : 34, idx 6 -> 13
D: char 0 : 30, idx 5 -> 11
D: char 0 : 30, idx 4 -> 9
D: char 0 : 30, idx 3 -> 7
D: char 0 : 30, idx 2 -> 5
D: char 0 : 30, idx 1 -> 3
D: char 5 : 35, idx 0 -> 1
*** Booting Zephyr OS version 2.2.0-rc1  ***
D: lock usb_enable_lock mutex
D: Attached
D: set cb, ep: 0x81
D: unlock usb_enable_lock mutex
Running test suite test_device
===================================================================
starting test - test_usb_dc_api_invalid
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
E: Wrong endpoint index/address
PASS - test_usb_dc_api_invalid
===================================================================
starting test - test_usb_dc_api
PASS - test_usb_dc_api
===================================================================
starting test - test_usb_dc_api_read_write
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
PASS - test_usb_dc_api_read_write
===================================================================
starting test - test_usb_dc_api_invalid
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
E: Wrong endpoint index/address
PASS - test_usb_dc_api_invalid
===================================================================
starting test - test_usb_deconfig
PASS - test_usb_deconfig
===================================================================
starting test - test_usb_disable
W: Device not attached
PASS - test_usb_disable
===================================================================
Test suite test_device succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

2020-02-19 10:30 UTC, carlescufi commented
@MaureenHelm this fixes a bug, has been opened for a while and is scheduled for this release. Could you review it so we can include it in the release?
cc @jhedberg

2020-02-19 10:31 UTC, jhedberg approved these changes

2020-03-10 15:04 UTC, carlescufi approved these changes

2020-03-10 15:04 UTC, merged