board: efm32pg_stk3402a: Add option to compile for EFM32JG12B
zephyrproject-rtos/zephyr pull request #21183
Opened 2019-12-04 14:35 UTC by chrta

This PR adds the Soc files for the SiLabs EFM32 Jade Gecko (EFM32JG12B). There is no distinct development boards that is populated with this SoC.
Since firmware compiled for the EFM32JG12B runs on the equivalent EFM32PG12B SoC, the board efm32pg_stk3402a is extended, to be able to compile a "Jade Gecko"-firmware for this board. This can be done by specifying the board `efm32pg_stk3402a_jg` instead of `efm32pg_stk3402a`, see contained documentation.

This PR depends on https://github.com/zephyrproject-rtos/hal_silabs/pull/3 being merged. Once this is done, i update the west.yml here.

See also https://lists.zephyrproject.org/g/devel/topic/60553822#6533

2019-12-05 22:14 UTC, dbkinder requested changes
one doc tweak, otherwise doc LGTM

2019-12-05 22:14 UTC, dbkinder commented on boards/arm/efm32pg_stk3402a/doc/index.rst
> +the EFM32 Jade Gecko SoC (EFM32JG12B). The only difference between the Pearl
Change these last two sentences to:
```
The Pearl Gecko contains contains an ARM® Cortex®-M4F core, and the Jade Gecko
an ARM® Cortex®-M3 core.  Other features such as memory and peripherals are the same.
```

2019-12-06 08:56 UTC, chrta commented on boards/arm/efm32pg_stk3402a/doc/index.rst
> +the EFM32 Jade Gecko SoC (EFM32JG12B). The only difference between the Pearl
done

2019-12-18 20:28 UTC, dbkinder approved these changes
+1 for doc changes, thanks.

2020-01-10 13:53 UTC, chrta commented
@MaureenHelm, @galak or @ioannisg
Can someone have a look at zephyrproject-rtos/hal_silabs#3? After merging it i can update this pr so it builds.

2020-01-10 14:25 UTC, MaureenHelm commented
> @MaureenHelm, @galak or @ioannisg
> Can someone have a look at [zephyrproject-rtos/hal_silabs#3](https://github.com/zephyrproject-rtos/hal_silabs/pull/3)? After merging it i can update this pr so it builds.

You can get it to build before merging the hal pr like this: 
```diff
diff --git a/west.yml b/west.yml
index 06ed9a56ca..c9cd6d6143 100644
--- a/west.yml
+++ b/west.yml
@@ -53,7 +53,7 @@ manifest:
       revision: 85302959c0c659311cf90ac51d133e5ce19c9288
       path: modules/hal/microchip
     - name: hal_silabs
-      revision: 9151e614c23997074acd1096a3e8a9e5c255d5b9
+      revision: pull/3/head
       path: modules/hal/silabs
     - name: hal_st
       revision: fa481784b3c49780f18d50bafe00390ccb62b2ec
```
See also: https://docs.zephyrproject.org/latest/guides/modules.html#changes-to-existing-modules

2020-01-10 15:19 UTC, chrta commented
@MaureenHelm Thank you, i was not aware of this.

2020-01-27 15:21 UTC, chrta commented
Rebased and added myself to CODEOWNERS.

2020-01-28 19:38 UTC, galak commented
@chrta looks like you still need a CODEOWNERS update.

2020-01-29 16:51 UTC, chrta commented
@galak Added myself to CODEOWNERS.

2020-01-29 17:13 UTC, galak approved these changes

2020-01-29 17:13 UTC, galak commented
LGTM.  Marking DNM until we close on the HAL side update.

2020-01-30 10:07 UTC, galak commented
Please update west.yml now that HAL changes are merged.

2020-01-30 13:03 UTC, chrta commented
> Please update west.yml now that HAL changes are merged.

Done. Everything should be ready now.

2020-01-30 13:06 UTC, merged