cmake: require python 3.6 or later
zephyrproject-rtos/zephyr pull request #21212
Opened 2019-12-05 19:15 UTC by mbolivar

Zephyr currently requires Python 3.4 or later. Python 3.4 has been EOL
since March, so there's no reason to continue to support it if it's
causing a burden, which it is. In particular, Python 3.6 has new
features which make writing Zephyr scripts that deal with paths a lot
easier, and which it would be good to be able to rely upon.

Note Python 3.5 won't hit EOL until September 2020, but dropping
support for it will only affect very old versions of Linux, so the
tradeoff is worthwhile:

- Windows and macOS users get recent versions of Python from choco and
  Homebrew, respectively
- Ubuntu 18.04 and later include Python 3.6 or later
- Ubuntu 16.04 does ship Python 3.5, so its system python won't
  work out of the box anymore after this commit

Rationale for moving to 3.6:

Python 3.6 introduced os.PathLike, which is an abstract base class for
objects which represent file system paths, and updated many standard
library functions, such as those found in os.path, to accept any
os.PathLike instead of just strings.

PathLike objects are very convenient for doing cross-platform Python
development using file system paths, which obviously applies to
Zephyr's scripts (and west). In particular, pathlib.Path and
pathlib.PurePath objects are instances of os.PathLike, and have many
useful features.

Moving to 3.6 means these objects can largely be used interchangeably
with 'raw' path strings, easing interoperability between code that
needs to use these objects and existing code using the os.path API.

These objects have a variety of advantages over 'raw' paths when
writing portable Python scripts that deal with file system paths,
such as:

- On Windows, Path and PurePath objects can be compared with == in
  a case-insensitive way that works regardless of whether slashes or
  backslashes are used as separator characters, along with other
  normalization/canonicalization:

```
  >>> PurePath(r'C:\Users') == PurePath('C:/users/')
  True
```

- On Linux, comparison is case sensitive, but otherwise normalized:

```
  >>> PurePath('/home/mbolivar') == PurePath('/home/MBOLIVAR')
  False
  >>> PurePath('/home/mbolivar') == PurePath('/home/mbolivar/')
  True
  >>> PurePath('/home/mbolivar') == PurePath('/home////mbolivar/')
  True
```

- Similar comments apply to macOS

- On Unix, Path.samefile() allows comparing real files to one
 another in a way that dereferences symlinks and hardlinks:

```
  >>> Path('foo').samefile(Path('symlink-to-foo'))
  True
  >>> Path('foo').samefile(Path('hardlink-to-foo'))
  True
```

- On all platforms, joining paths from their components is portable
  and readable.

  Windows:

```
  >>> Path.home() / 'zephyrproject' / 'zephyr'
  WindowsPath('C:/Users/marti/zephyrproject/zephyr')
```

  Linux (macOS is similar):

```
  >>> Path.home() / 'zephyrproject' / 'zephyr'
  PosixPath('/home/mbolivar/zephyrproject/zephyr')
```

Moving to 3.6 makes it possible to write Python code for Zephyr which
intermixes PathLike objects with the older-style os.path API:

- Windows:

```
  >>> os.path.basename(PurePath(r'C:\Users'))
  'Users'
  >>> print(Path.home() / 'zephyrproject' / 'zephyr')
  C:\Users\marti\zephyrproject\zephyr
```

- Unix:

```
  >>> os.path.dirname(PurePath('/home/mbolivar'))
  '/home'
```

- Linux (macOS is similar):

```
  >>> os.path.dirname(Path.home() / 'zephyrproject' / 'zephyr')
  '/home/mbolivar/zephyrproject'
```

Without the move to 3.6, scripters have to remember to convert between
strings and pathlib objects at appropriate times. Experience has
shown that this is cumbersome and error-prone.

Since 3.6 is widely available in Zephyr's supported host platforms, there's
no reason to continue to deal with this maintenance burden.

2019-12-05 19:36 UTC, galak commented
You need to update the docker image for CI as we have python 3.5 installed there.

2019-12-05 19:40 UTC, carlescufi approved these changes
Agreed, no reason to support anything below 3.6 anymore.

2019-12-05 19:42 UTC, nashif commented
> You need to update the docker image for CI as we have python 3.5 installed there.

that is going to be fun, I think it is time to update the docker image OS as well, it has been a while and it is running an ancient ubuntu.

2019-12-05 19:43 UTC, nashif commented
Why the TSC label? Is there any controversy around this already?

2019-12-05 19:50 UTC, nashif approved these changes

2019-12-05 19:51 UTC, mbolivar commented
> Why the TSC label? Is there any controversy around this already?

Just being cautious here. I wanted to make sure project members have a heads-up by discussing it briefly (1-2 min) at the next TSC meeting. I can drop this label if people don't think that's necessary.

2019-12-05 19:56 UTC, mbolivar commented
> You need to update the docker image for CI as we have python 3.5 installed there.

https://github.com/zephyrproject-rtos/ci-dockerfiles/pull/63

2019-12-05 20:12 UTC, nashif commented
> that is going to be fun, I think it is time to update the docker image OS as well, it has been a while and it is running an ancient ubuntu.

ah, @galak already updated that a while back, cool.

2019-12-05 20:59 UTC, ulfalizer commented
Don't care all that much about the path stuff myself (`pathlib` is available since 3.4, and mixing with `os` isn't super painful). f-strings are nice though: Can write `f"foo = {foo.bar}, bar = {baz}"` instead of `"foo ={}, bar = {}".format(foo.bar, baz)"`.

I might've waited a bit longer (Python 3.5 EOLs 2020-09-13), but up to you.

2019-12-06 07:14 UTC, aescolar commented
Thanks @mbolivar. Giving reasonable warning is always nice.
One comment: note that corporate environments tend to use oldish distros, with RedHat being common. I just quickly checked and RedHat 7, which is probably the most common RedHat today, seems to provide 3.6 thru an extra RedHat repo.

2019-12-06 09:57 UTC, SebastianBoe commented
The 18.04 ubuntu release is quite recent (3 months old), but the python release is quite old, so this seems reasonable to me.

This will most likely not affect Windows users (due to 3.6 being released so long ago).

Ubuntu release schedule: https://wiki.ubuntu.com/Releases
Python releases: https://en.wikibooks.org/wiki/Python_Programming/Version_history

2019-12-06 12:29 UTC, aescolar reviewed
No complaints from me, as it is not too overly new.

2019-12-06 17:02 UTC, mbolivar commented
> The 18.04 ubuntu release is quite recent (3 months old), but the python release is quite old, so this seems reasonable to me.
> [...]
> https://wiki.ubuntu.com/Releases

Thanks for the review!

Just a quick note that Ubuntu's release numbers are calendar-based, so 18.04 was released in 2018 (in April, month 4). So this latest LTS has actually been out for over a year now. You might be looking at 18.04.3, the latest point release, instead of the first 18.04 line in that link.

2019-12-09 11:19 UTC, SebastianBoe commented
Aha, that's much better, thanks :)

2019-12-09 14:39 UTC, galak commented
Going to put out an -rc of the docker image for testing.  We use this for both zephyr CI and SDK builds so want to make sure things work for both before we update.

2019-12-09 15:36 UTC, galak commented
updated #20625 for testing with 0.10.0-rc1 of the ci image.

2019-12-11 16:20 UTC, tyrantlizard77 approved these changes

2019-12-11 22:49 UTC, mbolivar commented
- Rebased on 2.1
- Updated Linux documentation
- Updated PR description to more fully describe impact and upgrade mechanisms

2019-12-12 15:47 UTC, mgti commented
Looks good - +1

2019-12-17 01:46 UTC, dbkinder approved these changes
Thanks for updating the GSG...

2019-12-17 23:15 UTC, mbolivar commented
@galak That seems like a long enough comment period without any controversy; I think this is ready to go in.

2019-12-17 23:55 UTC, mbolivar commented
> @galak That seems like a long enough comment period without any controversy; I think this is ready to go in.

I think he's on vacation -- can anybody else merge this?

2019-12-18 00:08 UTC, stephanosio requested changes

2019-12-18 00:15 UTC, mbolivar commented on .shippable.yml
> +        image_tag: v0.10.0-rc1
I rebased on top of that PR instead. Thanks.

2019-12-18 00:16 UTC, stephanosio approved these changes

2019-12-18 00:42 UTC, andrewboie commented
> I think he's on vacation -- can anybody else merge this?

Sure, once CI is passing I'll push it.

2019-12-18 09:15 UTC, merged