docs: mec15xxevb assy6853 updated set up manual
zephyrproject-rtos/zephyr pull request #21361
Opened 2019-12-13 08:14 UTC by maksimmasalski

Set up manual was modified, added more detailed description how to
program board and how to set up it. Added more photos.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

2019-12-16 03:08 UTC, maksimmasalski commented
@MaureenHelm @dbkinder Hello, I can't understand why it gives error with images. For example error is for image that was already was in that tree before I made that commit. Is it should be a jpg?

2019-12-16 18:53 UTC, albertofloyd approved these changes

2019-12-18 01:04 UTC, dbkinder requested changes

2019-12-18 01:28 UTC, maksimmasalski commented on boards/arm/mec15xxevb_assy6853/doc/index.rst
> +   ..list-table:: Microchip board wiring
What does the |p| means? It gives an error when I use a restview.

2019-12-18 01:30 UTC, maksimmasalski commented on boards/arm/mec15xxevb_assy6853/doc/index.rst
> +   ..list-table:: Microchip board wiring
If necessary to insert blank line symbol `|` works well

2019-12-18 20:18 UTC, dbkinder commented on boards/arm/mec15xxevb_assy6853/doc/index.rst
> +   ..list-table:: Microchip board wiring
We've got a ``substitutions.txt`` file defined in the sphinx build to set up a collection of shorthand for character replacements and stuff like that.  Using a ``|`` is OK too.

2019-12-18 20:22 UTC, dbkinder approved these changes
I think your doc changes look OK, but the CI system hasn't rerun the doc build so the previous error is cleared.  You may need to force push your change to give it a kick.

2019-12-19 02:25 UTC, maksimmasalski commented
> I think your doc changes look OK, but the CI system hasn't rerun the doc build so the previous error is cleared. You may need to force push your change to give it a kick.

I ran it, it gives the same errors.

2019-12-20 01:50 UTC, dbkinder requested changes
I've verified locally that these three tweaks will remove the doc build errors

2019-12-20 01:50 UTC, dbkinder commented on boards/arm/mec15xxevb_assy6853/doc/index.rst
> +      * - .. image:: spidongle_assy6791.png
OK, I've verified that this works (the ``.. image`` directive can only have white-space before it to work right):
```
      * -
          .. image:: spidongle_assy6791.png
             :width: 300px
             :align: center
             :alt: SPI DONGLE ASSY 6791

        -
          .. image:: spidongle_assy6791_view2.png
             :width: 300px
             :align: center
             :alt: SPI DONGLE ASSY 6791 view 2
```

BTW, PR #21509 will fix the doc processing you've encountered :)

2019-12-20 15:05 UTC, dbkinder approved these changes
+1 for doc changes, thanks.

2019-12-20 18:03 UTC, merged