dts: gen_defines.py: Support generating static initializers for nodes
zephyrproject-rtos/zephyr pull request #21393
Opened 2019-12-14 00:35 UTC by ulfalizer

Documentation (from the updated `dts/binding-template.yaml`):

```
If 'generate-child-initializer: true' appears in the binding for a node, then
static initializers will be generated for the child nodes of the node, along
with a static initializer for an array with the child nodes.

As an example, take the following devicetree. Assume that the binding for
'foos' contains 'generate-child-initializer: true', and that it gives the
foo_0 and foo_1 nodes a binding via 'child-binding:' (see below).

    / {
            foos@0 {
                    compatible = "foos";
                    foo_0 {
                            int = <0>;
                            string = "foo";
                    };
                    foo_1 {
                            int = <1>;
                            array = <2 3>;
                    };
            };
    };

These additional static initializers will then be generated, along with
aliases. The order of the properties in the initializer matches the order in
the devicetree.

    /* Initializer for foo_0 */
    #define DT_FOOS_0_FOO_0_INIT   {DT_FOOS_0_FOO_0_INT, DT_FOOS_0_FOO_0_STRING}
    /* Initializer for foo_1 */
    #define DT_FOOS_0_FOO_1_INIT   {DT_FOOS_0_FOO_1_INT, DT_FOOS_0_FOO_1_ARRAY}
    /* Initializer for the children of foos@0 */
    #define DT_FOOS_0_INIT         {DT_FOOS_0_FOO_0_INIT, DT_FOOS_0_FOO_1_INIT}

The referenced macros initialize each property (note that these are always
generated):

    #define DT_FOOS_0_FOO_0_INT    0
    #define DT_FOOS_0_FOO_0_STRING "foo"
    #define DT_FOOS_0_FOO_1_INT    1
    #define DT_FOOS_0_FOO_1_ARRAY  {2, 3}
```

Main commit:

```
dts: gen_defines.py: Support generating static initializers for nodes

Add a new 'generate-child-initializer' flag to bindings. When 'true',
static initializers will be generated for all child nodes of the node,
along with an initializer for an array that includes all the child
nodes.

This can be used to statically initialize structures and arrays derived
from devicetree data, e.g. for a list of LEDs.

See the updated documentation in doc/binding-template.yaml for more
information.

Fixes: #21239
```

Misc. refactoring:

```
dts: gen_defines.py: Add should_write() helper for properties

should_write() returns False for properties that are skipped in
write_properties().

Helps shorten write_properties() a bit. Want to keep it manageable when
adding some new stuff.
```

```
dts: gen_defines.py: Add helper for outputting {} initializers

The

    "{" + ", ".join(...) + "}"

pattern is in a bunch of places now. Add an out_dev_init() helper for
it, with the same parameters as out_dev().
```

2019-12-14 00:37 UTC, ulfalizer commented
@KAGA164 
Try it out when you have the time and tell me what you think.

2019-12-14 07:01 UTC, pabigot requested changes
Block until we come to agreement in #21369 about how devicetree paths are to be mapped to symbols that won't conflict.

Also the implicit dependency on the order that properties are listed in the binding is not maintainable.

2019-12-16 09:24 UTC, KAGA164 commented
@ulfalizer Thanks for this feature. This is exactly what I need.

2020-04-17 09:24 UTC, galak commented
Closing this as we are moving to the new generator / dt macro's

2020-04-17 09:24 UTC, closed without merging