samples: sensors: isl29035: add sample
zephyrproject-rtos/zephyr pull request #21434
Opened 2019-12-16 20:18 UTC by pabigot

Add a sample to demonstrate and test the Renesas/Intersil ISL29035 light sensor driver.

2019-12-17 21:03 UTC, dbkinder requested changes
A couple of doc tweaks, then LGTM.

2019-12-18 12:46 UTC, pabigot commented on samples/sensor/isl29035/README.rst
> +window, then continues as before.
It's actually the intensity range window, not the time window.  Updated, along with the delete requested above.  Please re-check; thanks.

2019-12-18 19:59 UTC, dbkinder approved these changes
+1 for doc changes, thanks!

2019-12-18 21:06 UTC, MaureenHelm approved these changes

2019-12-18 21:07 UTC, merged