arm: board: 96b_stm32_sensor_mez: enable USART3
zephyrproject-rtos/zephyr pull request #21457
Opened 2019-12-17 18:57 UTC by ric96

This patchset enables USART3 on the 96Boards STM32 Mezzanine.
It is broken out to J10 Grove Connector.

Changes:

- Enabled USART3 in board dts.
- Updated board index.rst with uart pinouts.
- soc dtsi: enabled usart3.

Test: Tested USART3 as console at 115200 baud

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2019-12-17 20:55 UTC, dbkinder approved these changes
doc changes LGTM, thanks.

2019-12-18 04:00 UTC, Mani-Sadhasivam requested changes

2019-12-18 04:00 UTC, Mani-Sadhasivam commented on dts/arm/st/f4/stm32f446.dtsi
> +
No need of new line here.

2019-12-22 10:33 UTC, ric96 commented on dts/arm/st/f4/stm32f446.dtsi
> +
Fixed

2019-12-26 09:52 UTC, Mani-Sadhasivam approved these changes

2020-01-03 15:37 UTC, MaureenHelm approved these changes

2020-01-03 15:37 UTC, merged