sanitycheck: hardware map correct detected platform name
zephyrproject-rtos/zephyr pull request #21472
Opened 2019-12-18 06:29 UTC by maksimmasalski

During hardware map generation it was unable to detect platform
name correctly. Result for each platform was unknown.
Now it will give manufacturer's name when serial device connected.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

2019-12-18 07:17 UTC, chen-png commented
this platform means the board name you want to test, and for each arc, there have many different board have the same arc.
even you set, when you run the sanitycheck, you still have to modify the platform name manually in map file.

2019-12-18 07:18 UTC, maksimmasalski commented
> this platform means the board name you want to test, and for each arc, there have many different board have the same arc.
> even you set, when you run the sanitycheck, you still have to modify the platform name manually in map file.

I thought it is serial device name manufacturer

2019-12-18 18:02 UTC, nashif requested changes
This is wrong, the platform name here needs to be entered manually and match a board name that is supported in zephyr.

2019-12-19 17:39 UTC, nashif commented
lets close this, reopen if you have other changes...

2019-12-19 17:39 UTC, closed without merging