samples: wpan_serial: Add rf2xx transceiver overlay
zephyrproject-rtos/zephyr pull request #21563
Opened 2019-12-22 01:24 UTC by nandojve

Add Atmel rf2xx transceiver and update documentation to add details how build and flash the application. The intention is differentiate between SoC and transceivers to help user understand what they need to do to build and flash successfully.

2019-12-22 16:54 UTC, jukkar approved these changes
LGTM

2019-12-23 21:08 UTC, dbkinder requested changes

2019-12-23 21:08 UTC, dbkinder commented on samples/net/wpan_serial/README.rst
> +overlays or using a SoC with build in radio like kw41z/nrf5/samr21.
Let's change this last sentence to:
```
You can pick, for example, a transceiver such as a CC2520 or RF2xx using
overlays, or by using an SoC with a built-in radio,  such as a kw41z, nrf5,
or samr21.
```

2019-12-23 21:08 UTC, dbkinder commented on samples/net/wpan_serial/README.rst
> +   This is an example how build for the Atmel SAM R21 Xplained Pro
Change to:
```
   Here's how to build the sample for the Atmel SAM R21 Xplained Pro
   Development Kit. Note that for this SoC, you don't need to include
   ``overlay-rf2xx.conf``.
```

2019-12-26 11:07 UTC, pfalcon approved these changes

2019-12-29 14:07 UTC, dbkinder approved these changes
+1 for docs, thanks!

2020-01-16 08:44 UTC, jukkar commented on samples/net/wpan_serial/README.rst
> +     :zephyr-app:
Documentation error seems to be related to this section, you probably need to fill these couple of empty values

2020-01-18 10:28 UTC, jukkar approved these changes

2020-01-18 10:28 UTC, merged