Bluetooth: Mesh: Add Minimum Period Constraint of Publish
zephyrproject-rtos/zephyr pull request #21612
Opened 2019-12-28 06:26 UTC by LingoMeng

According Mesh Model Specification Section 4.1.3 Sensor Cadence

The Status Min Interval field is a 1-octet value that shall
control the minimum interval between publishing two consecutive
Sensor Status messages.

This change will not have any impact on the current implementation.

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

2020-01-03 09:22 UTC, jhedberg requested changes
Isn't this exactly the same as HealthFastPeriodDivisor but just for a different model. I.e. can't you just use the existing `period_div` and `fast_period` members of the `bt_mesh_model_pub` struct instead of adding a new variable there?

2020-01-03 09:24 UTC, jhedberg commented
Correction to my previous comment: I was looking at "Fast Cadence Period Divisor" state from the sensor model, whereas you're trying to deal with the "Status Min Interval" state. Let me have another look. @trond-snekvik have you looked at solving this in some other way for your model spec work?

2020-01-03 09:29 UTC, jhedberg commented
The reason I'm reluctant here is that you're making changes to the access layer for something that's actually a layer above, i.e. in the model layer. I made exceptions for the health model with the fast period divisor since it's at least part of the mesh model spec, but here we're talking about a model that's not a foundation model.

2020-01-03 11:30 UTC, trond-snekvik commented
It is possible to solve this in the model layer, depending on the way the spec is interpreted. This minimum interval thing is defined on a per sensor-basis (a single sensor server will hold multiple sensors), which means that there needs to be some application logic going into this anyway. This application logic can include the minimum-check before setting the interval. 

The same can be said about the health server period divisor though... I don't think this is a blocker for a functioning sensor server, but it makes it easier to implement the model, just like the existing period divisor helps the health server implementation.

2020-01-09 12:46 UTC, carlescufi commented
@moringe can you please reply to the review comments to move this PR forward?

2020-02-13 11:28 UTC, trond-snekvik commented
Closing this, as it breaks the boundary between access and application to solve a problem that can be solved in the application.

See for instance this solution:
https://github.com/trond-snekvik/fw-nrfconnect-nrf/blob/386d68139ea2da0890d54183921ef1a46ef9a3c4/subsys/bluetooth/mesh/sensor_srv.c#L853-L858

It utilizes the fact that the publish update call now supports error returns, skipping publication of the sensor value until the min interval for each sensor instance has passed. Similar application layer restrictions should be implementable for other approaches as well, as the publication division has to be adjusted every publication interval already.

Feel free to reopen if this still is a blocker somehow.

2020-02-13 11:28 UTC, closed without merging