ble: define adv channel access address as macro in pdu.h
zephyrproject-rtos/zephyr pull request #21653
Opened 2020-01-03 01:07 UTC by cfriedt

The new macro is PDU_AC_ACCESS_ADDR

Signed-off-by: Christopher Friedt <chrisfriedt@gmail.com>

2020-01-03 10:23 UTC, wopu-ot requested changes
Looks good, except that the commit title should follow conventions.

2020-01-04 15:10 UTC, cfriedt commented
> Looks good, except that the commit title should follow conventions.

Done

2020-01-06 00:54 UTC, cvinayak approved these changes

2020-01-06 07:21 UTC, wopu-ot approved these changes

2020-01-06 08:58 UTC, aescolar approved these changes

2020-01-06 08:58 UTC, merged