drivers: hmc5883l: update to new GPIO API
zephyrproject-rtos/zephyr pull request #21718
Opened 2020-01-06 14:25 UTC by microbuilder

This commit updates the HMC5883L driver to use the new GPIO API.

Tested on frdm_k64f.

Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>

2020-01-06 14:33 UTC, pabigot requested changes
Please update the binding file to describe the active level of the signal so people don't have to guess whether the sensor/driver is providing/expecting active low.  See for example https://github.com/pabigot/zephyr/blob/286518ef1f79688524f7cc88d9073a1c95936de2/dts/bindings/sensor/st%2Chts221.yaml#L20

2020-01-06 14:45 UTC, microbuilder commented
> Please update the binding file to describe the active level of the signal so people don't have to guess whether the sensor/driver is providing/expecting active low. See for example https://github.com/pabigot/zephyr/blob/286518ef1f79688524f7cc88d9073a1c95936de2/dts/bindings/sensor/st%2Chts221.yaml#L20

https://github.com/zephyrproject-rtos/zephyr/pull/21718/commits/ffd644816c06cb059d8063d653e180c7c3fd2bf4

2020-01-06 14:53 UTC, pabigot approved these changes
Generally we've been putting all changes related to the new API into a single commit, rather than breaking out the binding description from the driver support.

2020-01-06 17:38 UTC, microbuilder commented
> Generally we've been putting all changes related to the new API into a single commit, rather than breaking out the binding description from the driver support.

I can merge these both into a single commit, just wanted to see if the description was sufficient or not.

2020-01-17 14:06 UTC, galak commented
> I can merge these both into a single commit, just wanted to see if the description was sufficient or not.

I merged them into one commit in the rebase.

2020-01-17 14:13 UTC, MaureenHelm approved these changes

2020-01-17 18:58 UTC, merged