Modify the max thread number according to CONFIG_MAX_THREAD_BYTES in gen_kobject_list.py.
zephyrproject-rtos/zephyr pull request #21732
Opened 2020-01-07 06:43 UTC by chen-png

if the created threads' number just equal to the number
set by the CONFIG_MAX_THREAD_BYTES, then each thread will
map a bit in _thread_idx_map array, the generated
_thread_idx_map will all be zero, it will be alocated to
bss section as a zero initialized object in zephyr.elf,
not the kobject_data section in zephyr_prebuilt.elf,
this will cause the address shift between
zephyr_prebuilt.elf and zephyr.elf, so we can't find the
correct thread using z_object_find function.

for example, if the CONFIG_MAX_THREAD_BYTES=4, and we creates 32 threads dynamically totally,
then in scripts/gen_kobject_list.py,  for each thread, it will map a bit index in thread_idx_map, then the generated array _thread_idx_map is [0x0, 0x0, 0x, 0x0].
so in the finally generate file kobject_hash.c , the thread_idx_map array is [0x0, 0x0, 0x0, 0x0],  it's allocated to bss section because it's a zero initialized object.

Signed-off-by: peng1 chen <peng1.chen@intel.com>

2020-01-08 03:09 UTC, LeiW000 reviewed
The commit log has to updated to explain why the change can prevent the issue.

2020-01-08 03:16 UTC, chen-png commented
> The commit log has to updated to explain why the change can prevent the issue.

done.

2020-01-08 03:19 UTC, LeiW000 approved these changes

2020-01-09 01:44 UTC, tyrantlizard77 requested changes
This looks like it will work but I think it's better to just force _thread_idx_map to be in the right part of memory regardless of its contents. Please see https://github.com/zephyrproject-rtos/zephyr/pull/21782

Thanks for isolating this problem, subtle issue!

2020-01-09 03:44 UTC, chen-png commented
see #21782

2020-01-09 03:44 UTC, closed without merging