cmake: remove include/drivers from include lists
zephyrproject-rtos/zephyr pull request #21776
Opened 2020-01-08 23:18 UTC by pabigot

Files that need something from this directory should be using the
prefix, e.g. <drivers/sensor.h> instead of just <sensor.h>.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

2020-01-09 00:55 UTC, nashif approved these changes

2020-01-16 13:30 UTC, pabigot commented
Blocked by #21974.

2020-01-16 16:16 UTC, carlescufi approved these changes

2020-01-17 19:01 UTC, pabigot commented
This got ugly.  I think this now fixes all the references that break when `drivers` is not an include root, but we'll see what CI says.  zephyrproject-rtos/mcumgr#10 must be merged and west updated before the mcumgr sample will build.

2020-01-17 19:03 UTC, pabigot commented
Also note that because this has tree-wide changes the cleanup may have to be done again several times as things are merged in.  The script below automates the changes.
```
(cd include/drivers ;
 find . -name '*.h' \
   | sed -e 's@^\./@@' \
   | sed -e '\@console/console.h@d' \
   | sort
) | while read f ; do
git grep -l "<${f}>" | xargs sed -i -r -e "s@<${f}>@<drivers/${f}>@g"
git grep -l '"'${f}'"' | xargs sed -i -r -e 's@"'${f}'"@<drivers/'${f}'>@g'
(cat <<EOText
treewide: use full path to ${f} header

The build infrastructure should not be adding the drivers subdirectory
to the include path.  Fix the legacy uses that depended on that
addition.
EOText
) > /tmp/x
git commit -a -F/tmp/x -s || true
done
```

2020-01-17 19:22 UTC, jhedberg approved these changes

2020-01-17 20:51 UTC, joerchan approved these changes

2020-01-17 23:59 UTC, vanwinkeljan approved these changes

2020-01-19 08:13 UTC, ydamigos approved these changes

2020-01-19 08:46 UTC, henrikbrixandersen approved these changes

2020-01-20 08:00 UTC, jukkar approved these changes

2020-01-20 08:04 UTC, masz-nordic approved these changes

2020-01-20 08:06 UTC, finikorg approved these changes

2020-01-20 11:02 UTC, SebastianBoe approved these changes

2020-01-20 12:25 UTC, jfischer-no approved these changes

2020-01-20 12:53 UTC, alexanderwachter approved these changes

2020-01-21 16:47 UTC, dleach02 approved these changes

2020-01-21 19:13 UTC, pfalcon approved these changes

2020-01-21 20:37 UTC, pabigot commented
DNM until zephyrproject-rtos/mcumgr#10 is merged and the west commit in this PR updated.

2020-01-23 11:30 UTC, pabigot commented
Blocked by #22128.

2020-01-24 19:01 UTC, pabigot commented
Subsequent merges require a re-run of the conversion, and mcuboot also needs an update.  I'll do that this weekend, hopefully it'll be quiet enough to get a CI pass and merge quickly before more conflicts arise.

2020-01-25 15:12 UTC, nvlsianpu requested changes

2020-01-25 15:12 UTC, nvlsianpu commented on west.yml
> +      revision: pull/4/head
54c1e3fb6ba4dcf7b315943bcfcda1e10a4042f5

2020-01-25 15:25 UTC, pabigot commented on west.yml
> +      revision: pull/4/head
done

2020-01-25 15:52 UTC, nvlsianpu approved these changes

2020-01-25 21:36 UTC, carlescufi commented
@pabigot why is this marked as DNM?

2020-01-25 22:29 UTC, pabigot commented
> @pabigot why is this marked as DNM?

Because it had not yet completed a successful CI after the final update of the mcuboot west module this morning; I wanted to make sure it was right.

It still hasn't, but the failure is due to fragile CI: the last test related to kernel.futex seems to never finish nor be cancelled.  So I've removed the label.

2020-01-26 16:52 UTC, merged