driver/sensor: lis3mdl: update to use new GPIO API
zephyrproject-rtos/zephyr pull request #21972
Opened 2020-01-16 12:31 UTC by avisconti

update to the new GPIO API

The LIS3MDL sensor is quite old and the driver requires to be restructured. This commit is only addressing the new GPIO API in order to compile properly.

2020-01-16 13:22 UTC, MaureenHelm requested changes
Need to add gpio flags to the the board and shield dts files that instantiate this sensor.

2020-01-16 13:50 UTC, avisconti commented
> Need to add gpio flags to the the board and shield dts files that instantiate this sensor.

ok, done!
There is actually only one place declaring the interrupt as well; x_nucleo_iks01a1 shield

2020-01-16 13:58 UTC, MaureenHelm approved these changes

2020-01-17 13:34 UTC, galak approved these changes

2020-01-17 13:34 UTC, merged