[TOPIC-BLE-LLCP] Bluetooth: controller: Add Tx Queue
zephyrproject-rtos/zephyr pull request #22227
Opened 2020-01-27 08:43 UTC by thoh-ot

Tx Queue implementation and accompanying unit test.

2020-01-28 10:52 UTC, cvinayak requested changes

2020-01-28 10:52 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_tx_queue.h
> +struct node_tx *ull_tx_q_dequeue(struct ull_tx_q *queue);
Please clarify that `ull_tx_q_dequeue` is ULL-only callable and memq construct will continue to be used between ULL and LLL?

2020-01-30 09:04 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_tx_queue.h
> +struct node_tx *ull_tx_q_dequeue(struct ull_tx_q *queue);
Agreed by @thot-ot.

2020-01-30 09:09 UTC, cvinayak approved these changes

2020-01-30 09:52 UTC, thoh-ot commented
Just pushed a minor update adding the ull_tx_queue.c to the CMakeLists.txt

2020-01-30 10:57 UTC, cvinayak approved these changes

2020-01-30 13:16 UTC, thoh-ot commented
Reopen to re-run ci

2020-01-31 10:15 UTC, kruithofa approved these changes

2020-01-31 13:21 UTC, merged