drivers: modem: Add support for different line endings
zephyrproject-rtos/zephyr pull request #22256
Opened 2020-01-28 08:59 UTC by tsvehagen

2020-01-28 17:37 UTC, jukkar requested changes

2020-01-28 17:37 UTC, jukkar commented on drivers/modem/modem_cmd_handler.h
> +	char *eol;
This seems to be always a const string, so perhaps adding `const char *eol`? here.

2020-01-28 17:37 UTC, jukkar commented on drivers/modem/modem_cmd_handler.c
> +		iface->write(iface, data->eol, strlen(data->eol));
What about calculating the length only once and storing the length in `modem_cmd_handler_data` struct. The send function is called all the time and it feels useless to calculate the length every time even if it is not changing.

2020-02-04 15:44 UTC, jukkar approved these changes
LGTM

2020-02-04 18:29 UTC, mike-scott commented
LGTM.  Let's get this in and I'll rebase https://github.com/zephyrproject-rtos/zephyr/pull/22149 on top.

2020-02-04 18:29 UTC, mike-scott approved these changes

2020-02-05 21:31 UTC, merged