bluetooth: controller: Force central cleanup on MIC error
zephyrproject-rtos/zephyr pull request #22351
Opened 2020-01-30 13:56 UTC by mtpr-ot

Since a peer MIC failure closes the event, it does not allow a terminate
acknowledge. For that reason a peer MIC fail for central role must force
a conn_cleanup.

Signed-off-by: Morten Priess <mtpr@oticon.com>

2020-01-30 13:56 UTC, mtpr-ot commented
@wopu-ot: FYI

2020-01-30 15:49 UTC, cvinayak approved these changes

2020-01-30 15:51 UTC, cvinayak requested changes
Add "split" to commit title, "Bluetooth: controller: split: Force central cleanup on MIC error"

Otherwise, changes look good

2020-01-31 07:25 UTC, cvinayak approved these changes

2020-01-31 07:29 UTC, thoh-ot approved these changes

2020-01-31 09:15 UTC, aescolar approved these changes

2020-01-31 09:15 UTC, merged