boards: pca10056: remove conflicting spi2 node
zephyrproject-rtos/zephyr pull request #22377
Opened 2020-01-31 15:15 UTC by jfischer-phytec-iot

Commit 5b4f4253c196
("drivers: flash: add Nordic JEDEC QSPI NOR flash driver")'
added SPI2 pin properties wich are in conflict with CS pin
of the SPI3, pin D9, and pin D8 routed to Arduino connector
of the pca10056 board. This change has broken any shield
support on this board. Remove conflicting SPI2 node.

2020-02-05 20:49 UTC, pabigot requested changes
The change to spi2 in that commit is absolutely wrong, but the correct fix would be the one below, which retains the configuration necessary to use spi2 for the flash, while leaving the peripheral disabled and the flash device under QSPI control.

```
 &spi2 {
        compatible = "nordic,nrf-spi";
-       status = "okay";
-       sck-pin = <42>;
-       mosi-pin = <43>;
-       miso-pin = <44>;
+       status = "disabled";
+       sck-pin = <19>;
+       mosi-pin = <20>;
+       miso-pin = <21>;
 };
```

2020-02-05 20:57 UTC, jfischer-phytec-iot commented
> The change to spi2 in that commit is absolutely wrong, but the correct fix would be the one below, which retains the configuration necessary to use spi2 for the flash, while leaving the peripheral disabled and under QSPI control.
> 
> ```
>  &spi2 {
>         compatible = "nordic,nrf-spi";
> -       status = "okay";
> -       sck-pin = <42>;
> -       mosi-pin = <43>;
> -       miso-pin = <44>;
> +       status = "disabled";
> +       sck-pin = <19>;
> +       mosi-pin = <20>;
> +       miso-pin = <21>;
>  };
> ```

But the pins are used for qspi node, I do no really understand the reason to have spi2 node.

```
&qspi {
	status = "okay";
	sck-pin = <19>;
	io-pins = <20>, <21>, <22>, <23>;
	csn-pins = <17>;
	mx25r64: mx25r6435f@0 {
```

2020-02-05 21:03 UTC, pabigot commented
> But the pins are used for qspi node, I do no really understand the reason to have spi2 node.

Sorry, I wasn't clear in my original comment.

The pins are hard-wired to the MX25R64 device, which can be controlled by either QSPI or SPI drivers.  The addition of the QSPI driver did change the default interface to the flash to be QSPI, but there are cases (such as driver performance comparison) where being able to access it by SPI is useful.  (I had done this during early analysis of the QSPI infrastructure, and now have alternative conf/devicetree overlays that do enable the SPI-based implementation.)

Deleting the spi2 instance entirely makes it much harder to switch between the interfaces, and adds no real value over providing the interface and leaving it disabled so that the QSPI driver can use them by default, and SPI2 can use them when selected by overlay.

2020-02-05 21:07 UTC, jfischer-phytec-iot commented
> Deleting the spi2 instance entirely makes it much harder to switch between the interfaces, and adds no real value over providing the interface and leaving it disabled so that the QSPI driver can use them by default, and SPI2 can use them when selected by overlay.

okay, thanks @pabigot . Should I let `config SPI_2` enabled?

2020-02-05 21:12 UTC, pabigot commented
> okay, thanks @pabigot . Should I let `config SPI_2` enabled?

No, I think it's OK to remove it from default enabled since the devicetree node is not enabled.  Anybody who overrides that can also override the Kconfig.

Thanks.

2020-02-06 15:34 UTC, kamlaz commented
It was my silly mistake - I have checked if the rest of peripehrial has been using those pins, but I missed arduino shield. **Sorry!**
According to your changes - disabling `SPI2` without any additional steps will indicate compilation errors of `spi_flash` sample.
What I propose is to disable `SPI2` exactly how you did and additionally add `CONFIG_SPI=n` in `samples/drivers/spi_flash/boards/nrf52840_pca10056.conf`.
This change is obligatory if you set `SPI2` as `okay`, since :
1. `spi_flash` sample uses `CONFIG_SPI` by default
2. When SPI2 was disabled it was ok, since it was ignored.
3. When SPI2 was enabled, during compilation of an example it tried to use exactly `SPI2` instead of `QSPI` becouse `SPI` instance was enabled.

2020-02-06 16:00 UTC, pabigot approved these changes

2020-02-06 16:07 UTC, jfischer-phytec-iot commented
> It was my silly mistake - I have checked if the rest of peripehrial has been using those pins, but I missed arduino shield. **Sorry!**
> According to your changes - disabling `SPI2` without any additional steps will indicate compilation errors of `spi_flash` sample.
> What I propose is to disable `SPI2` exactly how you did and additionally add `CONFIG_SPI=n` in `samples/drivers/spi_flash/boards/nrf52840_pca10056.conf`.
> This change is obligatory if you set `SPI2` as `okay`, since :
> 
>     1. `spi_flash` sample uses `CONFIG_SPI` by default
> 
>     2. When SPI2 was disabled it was ok, since it was ignored.
> 
>     3. When SPI2 was enabled, during compilation of an example it tried to use exactly `SPI2` instead of `QSPI` becouse `SPI` instance was enabled.

`samples/drivers/spi_flash` compiles and works fine with this PR:
 ```
*** Booting Zephyr OS build zephyr-v2.1.0-2064-g2f96be44230c  ***

JEDEC QSPI-NOR SPI flash testing
==========================

Test 1: Flash erase
Flash erase succeeded!

Test 2: Flash write
Attempting to write 4 bytes
Data read matches data written. Good!!

```

2020-02-06 16:09 UTC, pabigot commented
@kamlaz Yes, since `spi2` is disabled in devicetree this should be fine as-is.

2020-02-08 08:11 UTC, jhedberg commented
@lemrey @ioannisg @carlescufi could we get at least one more review on this one?

2020-02-08 16:27 UTC, carlescufi commented
@kamlaz @anangl could you please review?

@jhedberg this is a bugfix so no rush.

2020-02-08 17:17 UTC, carlescufi approved these changes
LGTM but I'd rather @anangl approves

2020-02-10 07:17 UTC, kamlaz approved these changes

2020-02-10 08:30 UTC, anangl approved these changes

2020-02-11 07:56 UTC, kl-cruz approved these changes

2020-02-11 15:42 UTC, merged