drivers: clock_control: Add subsys argument to the callback
zephyrproject-rtos/zephyr pull request #22425
Opened 2020-02-03 14:13 UTC by nordic-krch

Added subsys argument to the callback, updated one driver which
used it and test cases.

Fixes #22424.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2020-02-03 17:45 UTC, carlescufi requested changes
Missing changes to the release notes as described in:
https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#introducing-incompatible-changes

2020-02-04 17:36 UTC, galak approved these changes

2020-02-04 17:58 UTC, pabigot approved these changes

2020-02-04 17:58 UTC, pabigot commented on include/drivers/clock_control.h
> + * @param subsys	Opaque data representing the clock.
"...representing the clock subsystem".  Otherwise we're getting confused between the clock and the specific subsystem that's being started.

2020-02-05 16:06 UTC, carlescufi approved these changes

2020-02-05 16:07 UTC, merged