drivers: display: Add ili9163
zephyrproject-rtos/zephyr pull request #22454
Opened 2020-02-04 08:27 UTC by pavlohamov

Implement driver for Ilitek ili9163

2020-02-04 14:03 UTC, jfischer-no requested changes
Please follow [Coding Style](https://docs.zephyrproject.org/latest/contribute/index.html#coding-style). Please take a look at new [GPIO API](https://github.com/zephyrproject-rtos/zephyr/tree/topic-gpio). This driver needs at least a generic shield like [st7789v_generic](https://github.com/zephyrproject-rtos/zephyr/tree/topic-gpio/boards/shields/st7789v_generic).

2020-02-04 14:23 UTC, jfischer-no requested changes
Why do we need a driver for ILI9163 controller and can not enhance/use ILI9340?

Before that, ILI9340 driver needs some rework to obtain all the panel parameters from DT, like it was done for ST7789V.

2020-02-04 14:44 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +#define ILI9163_CMD_DATA_PIN_COMMAND 0
Make sense. removed

2020-02-04 14:44 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +#ifdef CONFIG_LVGL
Done

2020-02-04 14:44 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +static int ili9163_blanking_off(const struct device *dev);
Oups, i didn't event think about moving. thank you for suggestion. Done

2020-02-04 14:44 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +static int ili9163_init(struct device *dev)
Done

2020-02-04 14:45 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +	LOG_ERR("Set contrast not supported");
My bad. Thanks, fixed

2020-02-04 14:45 UTC, pavlohamov commented on drivers/display/display_ili9163.h
> +#define ILI9163_CMD_SOFTWARE_RESET 0x01
Done

2020-02-04 14:45 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +#ifdef CONFIG_ILI9163_RGB565
Done

2020-02-04 14:45 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +#ifdef CONFIG_ILI9163_RGB565
Done

2020-02-04 14:46 UTC, pavlohamov commented on drivers/display/display_ili9163.c
> +#ifdef CONFIG_ILI9163_RGB565
> 
> 
> Why do we need a driver for ILI9163 controller and can not enhance/use ILI9340?
> 
> Before that, ILI9340 driver needs some rework to obtain all the panel parameters from DT, like it was done for ST7789V.

Good idea. As for now i've fixed your comments. I will see what i can do to combine them

2020-02-04 14:47 UTC, pavlohamov commented
> 
> 
> Why do we need a driver for ILI9163 controller and can not enhance/use ILI9340?
> 
> Before that, ILI9340 driver needs some rework to obtain all the panel parameters from DT, like it was done for ST7789V.

Good idea. As for now i've fixed your comments. I will see what i can do to combine them

2020-02-10 07:06 UTC, pavlohamov commented
@jfischer-phytec-iot Could you be so kind to take a look on https://github.com/zephyrproject-rtos/zephyr/pull/22674 ?

2020-07-22 07:57 UTC, closed without merging