Final merge of topic-gpio branch
zephyrproject-rtos/zephyr pull request #22481
Opened 2020-02-04 23:37 UTC by pabigot

Push `HEAD^` when it passes so the shippable override is not included.

2020-02-04 23:42 UTC, mbolivar approved these changes

2020-02-04 23:46 UTC, mike-scott approved these changes

2020-02-04 23:53 UTC, jfischer-no approved these changes

2020-02-05 01:37 UTC, mnkp requested changes

2020-02-05 01:37 UTC, mnkp commented on drivers/gpio/gpio_sam.c
> +	if (flags & GPIO_PULL_DOWN) {
```
        } else if (flags & GPIO_PULL_DOWN) {
```

2020-02-05 01:37 UTC, mnkp commented on drivers/gpio/gpio_sam.c
Let's remove this empty line. The code will read better. Originally it wasn't there.

2020-02-05 05:20 UTC, ydamigos approved these changes

2020-02-05 07:18 UTC, jhedberg approved these changes

2020-02-05 07:33 UTC, henrikbrixandersen approved these changes

2020-02-05 07:56 UTC, vanwinkeljan approved these changes

2020-02-05 10:12 UTC, mnkp approved these changes
Tested on efr32_slwstk6061a, nrf52840_pca10056, frdm_k64f, sam_e70_xplained, nucleo_wb55rg board with `tests/drivers/gpio/gpio_api_1pin/` test.

2020-02-05 10:34 UTC, carlescufi approved these changes

2020-02-05 10:35 UTC, carlescufi commented
Tagging as DNM since it has the minions tweak commit

2020-02-05 11:00 UTC, merged