kernel: err: Add ERR_PTR, IS_ERR, and ERR_GET for error pointers
zephyrproject-rtos/zephyr pull request #22684
Opened 2020-02-10 12:09 UTC by joerchan

Add error pointers as a way to include the error reason in APIs that
would otherwise return a valid pointer or NULL. This provides a way
to return both types.

Fixes: #4973

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

2020-02-10 12:17 UTC, carlescufi commented
It could be argued that this should be don per-architecture. I personally think this is not necessary because Linux doesn't do this per-arch, and it supports pretty much all of Zephyr's architectures:
https://elixir.bootlin.com/linux/latest/source/include/linux/err.h#L22

That said, I would not be against making the macros "weak" so that they can be overridden by the different archs if necessary.

2020-02-10 12:29 UTC, carlocaione commented on include/sys/err.h
> +	return (int)ptr;
Can we use `intptr_t` instead?

2020-02-10 12:57 UTC, joerchan commented on include/sys/err.h
> +	return (int)ptr;
In the cast or the return type?

2020-02-10 12:57 UTC, carlocaione commented on include/sys/err.h
> +	return (int)ptr;
both

2020-02-10 13:13 UTC, carlocaione commented on include/sys/err.h
> +	return ERR_GET(ptr) < ERR_PTR_LIMIT || ERR_GET(ptr) < -ERR_PTR_LIMIT;
Isn't `ERR_GET(ptr) < -ERR_PTR_LIMIT` a subset of `ERR_GET(ptr) < ERR_PTR_LIMIT `? So that always evaluates to `ERR_GET(ptr) < ERR_PTR_LIMIT` ?

2020-02-10 15:17 UTC, pabigot requested changes
No.

Existing practice supporting this sort of thing includes [linux/err.h](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/err.h) and [openssl/err.h](https://linux.die.net/man/3/err_get_lib).

This is close to the API for Linux, but doesn't use the same technical solution.  For example, `IS_ERR(NULL)` defined here returns true.  Is that intended?  What error does it indicate?  In Linux it's not an error, and in APIs a null pointer may be a legitimate non-error result (depending on what "error" means).

What precise problem is this solving?  New APIs that return a pointer and need to provide an error indicator should return NULL and fill in an output argument.  Changing existing APIs to encode special non-null error values seems like to cause confusion and breakage.

If we're going to do this, I would prefer the technical solution used by Linux: error values are encoded as `(uintptr_t)-errno` and we hope that they don't produce a valid address.  I'd also be inclined to prefix all the API with `SYS_` to suggest that it's playing dirty tricks.  And include `PTR_ERR_OR_ZERO()` which is probably the most useful of the support functions defined in Linux.

But my preference is to not try to pack two concepts with different value domains into a single scalar value.  Especially if it could become visible to the user.

2020-02-10 15:47 UTC, carlescufi commented
> What precise problem is this solving? New APIs that return a pointer and need to provide an error indicator should return NULL and fill in an output argument

The problem it is solving is the ability to introduce new APIs that return a pointer and need to return an error code in case of failure, one beyond `NULL`. Why is an output argument a better solution than the one proposed here? I admit that forgetting to use the functions implemeneted here and instead checking for `NULL` has the potential to cause confusion among application developers, but this reduces the argument count by one and is overall elegant, so it's a tradeoff.

2020-02-10 15:57 UTC, joerchan commented
> For example, IS_ERR(NULL) defined here returns true. Is that intended? What error does it indicate? In Linux it's not an error, and in APIs a null pointer may be a legitimate non-error result (depending on what "error" means).

We can change that to have IS_ERR and IS_ERR_OR_NULL. So that IS_ERR(NULL) returns false and IS_ERR_OR_NULL(NULL) returns true.

> No

For the entire thing? Or do you want changes?

2020-02-10 17:03 UTC, pabigot commented
> > What precise problem is this solving? New APIs that return a pointer and need to provide an error indicator should return NULL and fill in an output argument
> 
> The problem it is solving is the ability to introduce new APIs that return a pointer and need to return an error code in case of failure, one beyond `NULL`. Why is an output argument a better solution than the one proposed here? I admit that forgetting to use the functions implemented here and instead checking for `NULL` directly has the potential to cause confusion among application developers, but this reduces the argument count by one and is overall elegant, so it's a tradeoff.

One person's "elegant" is another's "grotesque hack".  You don't *need* this to be able to return a pointer-or-error value, it's just an optimization with no clear evidence that it's got significant benefit to useability or performance.

The strongest technical objection: There is simply no way to guarantee that any specific encoding of error values into a pointer will not conflict with some valid pointer on some platform for some API and error value.  Zephyr's scope of targets is quite wide: I could easily see somebody trying to use a processor where there's a 16-byte block at 0xFFFFFFF0 that maps to valid data.  Just as a 16 byte block at 0x00000010 might be valid.  So positive value or negative value casts of, say, `EINVAL` could produce dereferenceable pointers. How are you going to ensure nobody uses this trick for API where those pointers are valid return values?

Developers expect a pointer to be a pointer.  About the only thing they might be used to doing is checking it against NULL.  A non-null invalid pointer as a legitimate return value increases the likelihood of code that breaks in error conditions--which are the ones least likely to be robustly tested.

Less compelling to some is that casting between pointers and integers is inherently fragile.  MISRA 11.4 explicitly outlaws this technique, though it's an advisory rule, so Zephyr could choose to state an exception.

There are at least three ways to have API that returns a pointer or an error value, in increasing order of personal preference:
* `type* func();` check `PTR_ERR_OR_ZERO(rv) == 0` before dereferencing, else examine `PTR_ERR(rv)` to react to the failure;
* `type* func(int *errp);` check `rv != NULL` before dereferencing; else examine `*errp` to react to the failure;
* `int func(type* ptr);` check `rv == 0` before dereferencing `ptr`, else examine `rv` to react to the failure.  You can even extend this and have a non-negative `rv` convey metadata about the object returned in `*ptr`, like its size, which is really useful.

The third follows the same pattern as pretty much all system API: consistency for the win.  It also prevents people from doing stupid things like `func()->value` because they think a failure can't occur in their special situation, which is a weakness of both the first and second approaches.

> We can change that to have IS_ERR and IS_ERR_OR_NULL. So that IS_ERR(NULL) returns false and IS_ERR_OR_NULL(NULL) returns true.

That would be a start, yes.  I do think if you do this you should follow Linux in both technical solution and complete API (names and behavior).  What would be the benefit of deviating from that existing solution?

> > No
> 
> For the entire thing? Or do you want changes?

If it were up to me, no to the whole thing.  This isn't elegant.  It's complex, fragile, and confusing.  I get that Linux uses it internally for some situations, but exposing it to application developers seems like a really bad idea.

However, you need input from a lot more stakeholders.  If I'm the only one against it when the dust settles I'll withdraw my NACK.

2020-02-11 09:49 UTC, joerchan commented
> That would be a start, yes. I do think if you do this you should follow Linux in both technical solution and complete API (names and behavior). What would be the benefit of deviating from that existing solution?

One difference from linux is that there are cases for positive error codes here as well coming from pthreads/Posix.
```
 *  @return Zero on success or error code otherwise, positive in case
 *  of protocol error or negative (POSIX) in case of stack internal error
```
This means that we have more error codes, which when casted will end up with 2 different memory regions, one at the very top of the address space, and one at the very bottom. Since the very bottom of the address space is most likely code memory (at least for ARM) that means we cannot return pointer to read-only memory at the moment. So if we wanted to support that use-case as well we would have to do further tricks to handle positive error codes.

I agree with your list of personal preference, but your 3rd solution should be `int func(type **ptr);`. This is the solution I'd like to use as well.

> The third follows the same pattern as pretty much all system API: consistency for the win. It also prevents people from doing stupid things like func()->value because they think a failure can't occur in their special situation, which is a weakness of both the first and second approaches.

I think that is another good argument but I haven't seen the double pointer used that much in the API. but there are atleast a few examples: `int k_mem_slab_alloc(struct k_mem_slab *slab, void **mem, s32_t timeout)`. @carlescufi @jhedberg Following this pattern seems like the best solution to me.

2020-02-11 10:51 UTC, jhedberg commented
> I think that is another good argument but I haven't seen the double pointer used that much in the API. but there are atleast a few examples: int k_mem_slab_alloc(struct k_mem_slab *slab, void **mem, s32_t timeout)

`k_mem_pool_alloc` as well

> @carlescufi @jhedberg Following this pattern seems like the best solution to me.

Agreed.

2020-02-11 11:27 UTC, carlescufi commented
> > > What precise problem is this solving? New APIs that return a pointer and need to provide an error indicator should return NULL and fill in an output argument
> > 
> > 
> > The problem it is solving is the ability to introduce new APIs that return a pointer and need to return an error code in case of failure, one beyond `NULL`. Why is an output argument a better solution than the one proposed here? I admit that forgetting to use the functions implemented here and instead checking for `NULL` directly has the potential to cause confusion among application developers, but this reduces the argument count by one and is overall elegant, so it's a tradeoff.
> 
> One person's "elegant" is another's "grotesque hack". You don't _need_ this to be able to return a pointer-or-error value, it's just an optimization with no clear evidence that it's got significant benefit to useability or performance.

The opposite can be argued as well though. Passing in a pointer to an integer to get the error back is far from intuitive. That said, I will not insist since this is more a matter of perception and taste than anything else.


> The strongest technical objection: There is simply no way to guarantee that any specific encoding of error values into a pointer will not conflict with some valid pointer on some platform for some API and error value. Zephyr's scope of targets is quite wide: I could easily see somebody trying to use a processor where there's a 16-byte block at 0xFFFFFFF0 that maps to valid data. Just as a 16 byte block at 0x00000010 might be valid. So positive value or negative value casts of, say, `EINVAL` could produce dereferenceable pointers. How are you going to ensure nobody uses this trick for API where those pointers are valid return values?

This is a valid point. My argument was based on decades of Linux using the same approach on myriads of different hardware platforms, but your argument is indeed solid, we never know what we'll find in other people's memory maps.

> There are at least three ways to have API that returns a pointer or an error value, in increasing order of personal preference:
> 
> * `type* func();` check `PTR_ERR_OR_ZERO(rv) == 0` before dereferencing, else examine `PTR_ERR(rv)` to react to the failure;
> * `type* func(int *errp);` check `rv != NULL` before dereferencing; else examine `*errp` to react to the failure;
> * `int func(type* ptr);` check `rv == 0` before dereferencing `ptr`, else examine `rv` to react to the failure.  You can even extend this and have a non-negative `rv` convey metadata about the object returned in `*ptr`, like its size, which is really useful.

You are omitting the case that brought us here in the first place, which is a function that returns both an error code and a pointer to an object that it has allocated itself. But I have addressed this in a later comment so I won't repeat it here.


> > > No
> > 
> > 
> > For the entire thing? Or do you want changes?
> 
> If it were up to me, no to the whole thing. This isn't elegant. It's complex, fragile, and confusing. I get that Linux uses it internally for some situations, but exposing it to application developers seems like a really bad idea.

This is in my opinion the best argument in favor of closing this PR: while this is a "clever" and probably optimal solution to the problem, it is safer to hide it from users. It is one thing to expose it to kernel developers, another one altogether to have application developers have to deal with it.

As agreed with @joerchan and @jhedberg, we will go with the `**conn` approach to get the pointer back and then the API function can just return `int`.

2020-02-11 11:41 UTC, joerchan commented
Thank you all for valuable feedback. Since we have come to an agreement we can close this now.

2020-02-11 11:41 UTC, closed without merging