dts: fix up type comments in binding-template.yaml
zephyrproject-rtos/zephyr pull request #22763
Opened 2020-02-12 17:26 UTC by mbolivar

@galak I'm targeting master since this is a documentation fix, as this file is included in the [devicetree docs page](https://docs.zephyrproject.org/latest/guides/dts/index.html#devicetree-bindings)

List the details for each type in the order they appear in the summary
of all types. Add the missing 'path' value to the summary.

2020-02-12 19:25 UTC, galak approved these changes

2020-02-13 03:07 UTC, ulfalizer approved these changes

2020-02-13 03:08 UTC, ulfalizer requested changes

2020-02-13 03:08 UTC, ulfalizer commented on dts/binding-template.yaml
>  #         frequency = <100>;
This line belongs to `type: int`.

2020-02-13 03:25 UTC, galak commented on dts/binding-template.yaml
>  #         frequency = <100>;
Fixed

2020-02-13 03:35 UTC, ulfalizer approved these changes

2020-02-13 06:57 UTC, mbolivar commented on dts/binding-template.yaml
>  #         frequency = <100>;
> Fixed

thanks @galak

2020-02-13 08:14 UTC, merged