Convert stellaris drivers to DT_INST
zephyrproject-rtos/zephyr pull request #22839
Opened 2020-02-14 17:43 UTC by galak

2020-02-25 01:45 UTC, vanti requested changes
LGTM apart from the enumeration that is no longer needed

2020-03-11 14:07 UTC, galak commented on drivers/gpio/gpio_stellaris.c
> -	.port_map = GPIO_PORT_D_MAP,
removed.

2020-03-11 16:50 UTC, vanti approved these changes

2020-03-12 09:18 UTC, carlescufi approved these changes

2020-03-12 10:54 UTC, merged