Add Feather STM32F405 Express
zephyrproject-rtos/zephyr pull request #23029
Opened 2020-02-21 23:24 UTC by hierophect

This PR adds support to the Feather F405 board from Adafruit.

2020-02-23 22:22 UTC, hierophect commented
I'm not familiar with Shippable. Is there something I still need to change? I cannot reproduce the problem it is having locally, and it doesn't provide very useful error information.

2020-02-24 19:23 UTC, hierophect commented
The specific error provided by Shippable is:
`error: ARM (defined at arch/Kconfig:26) is assigned in a configuration file, but is not directly
user-configurable (has no prompt). It gets its value indirectly from other symbols. See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_ARM.html and/or look up ARM in the
menuconfig/guiconfig interface. The Application Development Primer, Setting Configuration Values,
and Kconfig - Tips and Best Practices sections of the manual might be helpful too.`

This implies CONFIG_ARM is not user settable. However, it is set in every other ST board file listed in the device tree - I'm not sure what is different about my PR, so I'd appreciate anyone's help in spotting the error!

2020-02-25 13:10 UTC, erwango requested changes
Thanks for this addition!
A few hints and nitpicks otherwise LGTM.

2020-02-25 13:10 UTC, erwango commented on boards/arm/adafruit_feather_stm32f405/adafruit_feather_stm32f405_defconfig
> +CONFIG_BOARD_ADAFRUIT_FEATHER_STM32F405=y
Both these lines should be removed (recent evolution as well).

2020-02-25 13:10 UTC, erwango commented on boards/arm/adafruit_feather_stm32f405/adafruit_feather_stm32f405_defconfig
> +CONFIG_PWM=y
Aside from minimum required for basic operations (GPIO, clock, UART), no peripheral should be enabled in default board configuration.

2020-02-25 13:10 UTC, erwango commented on boards/arm/adafruit_feather_stm32f405/doc/index.rst
> +instructions on the Learn website.
Maybe you can use the link here as well.

2020-02-25 13:10 UTC, erwango commented on boards/arm/adafruit_feather_stm32f405/pinmux.c
> +#endif	/* CONFIG_USB_DC_STM32 */
Please fix comment alignment

2020-02-25 13:10 UTC, erwango commented on boards/arm/adafruit_feather_stm32f405/pinmux.c
> +		CONFIG_PINMUX_STM32_DEVICE_INITIALIZATION_PRIORITY);
Please fix indentation

2020-02-25 18:08 UTC, hierophect commented
Botched my git here by accidentally force pushing without committing, which forces future commits to be merges. Do I need to nuke this PR and start over? What's your best practice here?

2020-02-25 18:12 UTC, hierophect commented
Something's gone pretty wrong, Github won't even show my latest changes any more. Nuking and starting over.

2020-02-25 18:17 UTC, closed without merging

2020-02-25 18:29 UTC, hierophect commented
@erwango please see #23080

2020-02-26 08:07 UTC, erwango commented
@hierophect ok, will do. But please keep "close PR"/"create new PR" exceptional. This is much harder to track changes happening between reviews.

2020-02-26 16:58 UTC, hierophect commented
@erwango sorry, I'm not used to the single-commit approach and got myself into a corner I wasn't sure how to git-fu myself out of. I'll do some research and see how I can fix it properly next time.