usb_dc_stm32: ameliorate PMA leak on reset.
zephyrproject-rtos/zephyr pull request #23179
Opened 2020-02-29 12:54 UTC by jmgao

Previously, endpoint configuration would reserve memory in the packet
memory area which would never be reclaimed. After this patch, the leak
still exists on SET_CONFIGURATION/SET_INTERFACE, but we will at least
reclaim the memory upon reset, so disconnect/reconnect gets us back
into a working state.

Bug: https://github.com/zephyrproject-rtos/zephyr/issues/23178
Signed-off-by: Josh Gao <josh@jmgao.dev>

2020-03-02 09:50 UTC, jfischer-phytec-iot commented
I suggest to add a check if an endpoint is already configured or not to [usb_dc_ep_configure()](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/usb/device/usb_dc_stm32.c#L551) and fix the bug.

2020-03-04 10:13 UTC, carlescufi commented
@loicpoulain @ydamigos could you take a look at this PR?

2020-03-05 20:58 UTC, ydamigos requested changes

2020-03-05 20:58 UTC, ydamigos commented on drivers/usb/device/usb_dc_stm32.c
> +	if (ep_cfg->ep_mps > ep_state->ep_pma_buf_len) {
Why do we need `ep_state->ep_pma_buf_len`? Isn't enough to check `if (ep_cfg->ep_mps > ep_state->ep_mps)`?

2020-03-05 21:17 UTC, ydamigos commented on drivers/usb/device/usb_dc_stm32.c
> +	if (ep_cfg->ep_mps > ep_state->ep_pma_buf_len) {
Ignore my comment. We need it because `ep_cfg->ep_mps` may be less than `ep_state->ep_mps`.

2020-03-05 21:19 UTC, ydamigos commented
I am approving the patch as it improves the situation we have right now.

2020-03-05 21:19 UTC, ydamigos approved these changes

2020-03-10 16:32 UTC, merged