boards: pinmux: Don't throw compiler warnings on using custom sercom use
zephyrproject-rtos/zephyr pull request #23252
Opened 2020-03-04 11:25 UTC by KubaFYI

In order to use it's serial peripheral SERCOMs SAMD socs require their
pins to be configured with pinmux. Currently pins are muxed only for the
boards' default serial interfaces. The pinmux code is written to throw
a compiler error if a user tries to use any sercom in a way it wasn't
pre-defined to be used.

This commit changes compiler errors to warnings so that user can provide
custom pinmuxing code in their app.

Fixes #23133

Signed-off-by: Kuba Sanak <contact@kuba.fyi>

2020-03-04 14:44 UTC, stephanosio requested changes
>  The pinmux code is written to throw a compiler error if a user tries to use any sercom in a way it wasn't pre-defined to be used.

I think that is quite self-explanatory of why this should be an error (i.e. you are trying to use the pin mappings that are not supported/should not be used on the board).

If you encounter these errors, you are probably using a different board with the same SoC or doing something not originally intended with the board- in which case, you should probably create a new board definition.

If the board can (and should) actually support such pin mappings yet `pinmux.c` disallows it, then the proper pin configurations using `pinmux_pin_set` for such mappings should be added instead.

2020-03-05 12:12 UTC, KubaFYI commented
> I think that is quite self-explanatory of why this should be an error (i.e. you are trying to use the pin mappings that are not supported/should not be used on the board).
> 
> If you encounter these errors, you are probably using a different board with the same SoC or doing something not originally intended with the board- in which case, you should probably create a new board definition.

Except that this might not necessarily be the case. Some of those boards (e.g. the Adafruit Feather and Trinket) are prototyping boards and have misc pins brought out to be used freely, instead of having their purpose set in stone. The way pinmux throws a fuss prevents any of those supposedly general use pins available on the boards to be used with the HW serial capability of the SOCs - which goes against what prototyping boards are intended for.

I suppose that if you really wanted to do make sure that no incorrect muxing happens that would need to be done in the pinmux driver itself. Currently as it stands the user can still set pins to something silly in their app. Trying to prevent incorrect pin configuration by stopping users from having custom SERCOMs is like trying to prevent unlicensed drivers from driving by banning cars.

2020-03-06 02:49 UTC, stephanosio commented
> I suppose that if you really wanted to do make sure that no incorrect muxing happens that would need to be done in the pinmux driver itself. Currently as it stands the user can still set pins to something silly in their app. Trying to prevent incorrect pin configuration by stopping users from having custom SERCOMs is like trying to prevent unlicensed drivers from driving by banning cars.

I am not suggesting that we block users from using/customising the board in the way they want.

What I am saying is that, if they want to do that, they should do it properly- i.e. in `pinmux.c`.

> This commit changes compiler errors to warnings so that user can provide custom pinmuxing code in their app.

This is not something that should be encouraged, as it can create unnecessary clutters and introduce potential bugs.

2020-03-06 10:57 UTC, KubaFYI commented
> What I am saying is that, if they want to do that, they should do it properly- i.e. in `pinmux.c`.

I assumed that the design philosophy for zephyr is that users should be just able to do everything their board supports from the app, without modifying zephyr code. If that's not the case then I yield. If it is the case - I guess my argument is that prototyping boards like Adafruit Feather, with their pins brought out to be used for whatever, should support the use of one of the extra SERCOMs with them. 

> This is not something that should be encouraged, as it can create unnecessary clutters and introduce potential bugs. 

I understand the clutter argument (though it would be only a single warning message per custom SERCOM used, so not exactly tons of warnings), but how is that likely to introduce bugs?

2020-03-11 19:30 UTC, henrikbrixandersen approved these changes
I think it is okay to reduce this to a warning.

2020-03-11 23:51 UTC, stephanosio approved these changes
I suppose this is okay given that the CI treats all warnings as errors and we won't ever see any bad practices being merged in the future.

2020-04-07 14:02 UTC, KubaFYI commented
@galak & @MaureenHelm is there anything else I need to do with this?

2020-04-07 16:45 UTC, nandojve commented
I'm usually use a board referenced on Zephyr with <board>.conf and <board>.overlay. This way I can enable/disable DT nodes and extend to my own app and implement necessary pinmux complement.

There are some of this on using SAM series: https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/sockets/echo_client/boards using.

I was wondering if it works in general cases like presented here if is pinmux.c defined WEAK?

2020-04-07 18:24 UTC, KubaFYI commented
Hey @nandojve could you please elaborate what you mean. Do you mean you reimplement the `pinmux.c` file present in the board's directory?

> There are some of this on using SAM series: https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/sockets/echo_client/boards using.

Those files don't really seem to mention pinmux at all.

2020-04-07 18:50 UTC, nandojve commented
> Hey @nandojve could you please elaborate what you mean. Do you mean you reimplement the `pinmux.c` file present in the board's directory?
> 
> > There are some of this on using SAM series: https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/sockets/echo_client/boards using.
> 
> Those files don't really seem to mention pinmux at all.

I mean, we update original file with **weak** attribute

master/boards/arm/atsamr21_xpro/pinmux.c
static int board_pinmux_init(struct device *dev) __attribute__((weak))

than when appropriated use \<board\>,config and \<board\>.overlay to get you project configured. 
With that, you simple add **int board_pinmux_init(struct device *dev)** in your project. This new method with same signature will replace the original one at link time.

It is just another idea.

2020-04-07 20:26 UTC, KubaFYI commented
Ok thanks for the explanation. This makes sense though we'd also need to remove the `#error`s from the original pinmux anyway as they would be resolved and stop the build before gcc scraps the weakly defined function.

As a meagre occasional contributor though I don't think I should make a decision on how exactly to handle this. @henrikbrixandersen @stephanosio Do you have any thoughts on this?

2020-04-17 09:52 UTC, merged