boards: arm: lpcxpresso55s69_cpu0: Add LEDs to dts.
zephyrproject-rtos/zephyr pull request #23361
Opened 2020-03-10 04:53 UTC by mayanez

Hi,
I just got a new lpcxpresso kit and was getting it up and running. Being new to zephyr, I was trying to run the samples and found that the `blinky` wasn't supported. This PR adds support for this.

2020-03-10 22:42 UTC, galak requested changes
This doesn't seem right, the LEDS are defined in boards/arm/lpcxpresso55s69/lpcxpresso55s69.dtsi already.

2020-03-10 23:42 UTC, mayanez commented
Hmm, not sure then. I tried to build the blinky example and it was throwing an error due to the missing aliases. What is there a difference between a `dts` and `dtsi` file?

2020-03-11 09:53 UTC, agansari requested changes
No point in this pull request, leds are defined and blinky sample builds and runs.

dtsi are used as dts _includes_ , e.g. `#include "lpcxpresso55s69.dtsi"`

2020-03-11 16:14 UTC, mayanez commented
Ok. I will retry again on my end then. Not sure why it did not work previously before the change. Thanks!

2020-03-11 16:14 UTC, closed without merging