stm32: dma: enable dma with peripheral
zephyrproject-rtos/zephyr pull request #23396
Opened 2020-03-11 13:45 UTC by FRASTM

Test application and example configuring the spi  peripheral as a client of the dma.
In case the stm32 soc has a dma multiplexer, the peripheral request is defined by the client and any dmamux channel is used for transfer. 
In case the stm32 has no multiplexer, the dma channels and the requests are fixed by the client.
The DT is filled with parameters to set the peripheral request on the dmamux or the dma (if no mux)
The dma or dmamux channels used for the client transfer (rx, tx) are assigned by the DT among the total nb of channels.
Tested on nucleo_wb55rg board
Also tested on nucleo_l476rg board, where the dma requests are fixed (no multiplexer)
Also tested on nucleo_f411re board, where the dma V1 requests are fixed (no multiplexer)

Requires https://github.com/zephyrproject-rtos/zephyr/pull/23157
Requires #22021
Requires https://github.com/zephyrproject-rtos/zephyr/pull/23155/

Fix https://github.com/zephyrproject-rtos/zephyr/issues/20825

Signed-off-by: Francois Ramu francois.ramu@st.com

2020-03-11 14:07 UTC, FRASTM commented
rebase

2020-03-24 15:41 UTC, FRASTM commented
changed the DTS for dma client of the SPI for nucleo_l476
removed `compatible = "st,stm32-spi"; `  in the .overlay for this test

2020-03-25 15:48 UTC, FRASTM commented
changed the dts_fixup.h for l4 on DT_FLASH_DEV_NAME

2020-03-27 09:17 UTC, FRASTM commented
rebase

2020-04-27 15:06 UTC, erwango requested changes

2020-04-27 15:06 UTC, erwango commented on soc/arm/st_stm32/stm32l4/dts_fixup.h
> +#endif /* CONFIG_SPI_STM32_DMA */
This should not be needed anymore

2020-04-27 15:06 UTC, erwango commented on soc/arm/st_stm32/stm32f4/dts_fixup.h
> +
Not needed anymore

2020-04-27 15:12 UTC, erwango requested changes

2020-04-27 15:12 UTC, erwango commented on drivers/spi/spi_ll_stm32.c
> +	/* callback_arg directly holds the client data */
Can this be squashed to previous commit ?

2020-04-27 15:12 UTC, erwango commented on dts/bindings/dma/dma.yaml
> +# Common fields for DMA users
This binding is not needed anymore.
Properties moved to base.yaml

2020-04-27 15:12 UTC, erwango commented on tests/drivers/dma/chan_blen_loop_transfer/boards/nucleo_f411re.conf
> +CONFIG_DMA=y
Can we move this commit to a dedicated PR ?

2020-04-28 13:56 UTC, FRASTM commented
spi/spi_loopback  example for nucleo_l476 and nucleo_f411 boards

2020-04-29 10:27 UTC, FRASTM commented
decision to close this PR and to report all tests and configurations in the PR https://github.com/zephyrproject-rtos/zephyr/pull/23157

2020-04-29 10:27 UTC, closed without merging