driver: pinmux: stm32f7 configure speed for SPI clock pin
zephyrproject-rtos/zephyr pull request #23493
Opened 2020-03-16 15:13 UTC by FRASTM

This patch is setting the pin to very high speed for the
SPI2 clock output on PA12, for the stm32f7 soc series.

Fix https://github.com/zephyrproject-rtos/zephyr/issues/21899

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2020-03-16 15:26 UTC, erwango requested changes
Please extend to all `_SCK` entries in this file

2020-03-16 17:26 UTC, FRASTM commented
extended to all _SCK entries

2020-03-17 19:46 UTC, erwango approved these changes

2020-03-17 21:01 UTC, MaureenHelm approved these changes

2020-03-17 21:01 UTC, merged