arch: arm: Set lpc55s69 image type in cortex-m vector table
zephyrproject-rtos/zephyr pull request #23972
Opened 2020-03-31 20:44 UTC by MaureenHelm

The secure boot rom in the lpc55s69 soc uses a reserved entry in the
cm33 vector table to determine the application image type and
enable/disable a preset tz-m configuration. Zero out this entry in the
vector table to set the image type as a plain image (not signed or CRC)
and disable the preset tz-m configuration. Otherwise, the address of
z_arm_reserved can potentially cause an invalid image type that can't
boot.

Eventually we will want to support other image types and write non-zero
values to this entry in the vector table, however we don't yet have
zephyr infrastructure in place to generate these types of images.
Therefore we don't introduce any Kconfig options to configure the value.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

2020-04-01 01:39 UTC, galak approved these changes

2020-04-01 07:22 UTC, ioannisg reviewed
Although this should be OK and safe to do, it does not look ideal that SOC-specific conditionals are present in this core ARM assembly file.

If the secure boot (i.e. another image) needs to read a special value in this address, this should be taken care of by the image building process. For example, after Zephyr is built, some script locates the address of the vector table in the generated .hex and overwrites this particular reserved entry with 0x0, or with whatever value it is needed.

Such an approach would be the right thing to do, because the presence of a special value in this address is not a requirement at all for _this_ Zephyr image to run properly, but a requirement for a "parent" image.

2020-04-01 13:36 UTC, galak commented
> Although this should be OK and safe to do, it does not look ideal that SOC-specific conditionals are present in this core ARM assembly file.
> 
> If the secure boot (i.e. another image) needs to read a special value in this address, this should be taken care of by the image building process. For example, after Zephyr is built, some script locates the address of the vector table in the generated .hex and overwrites this particular reserved entry with 0x0, or with whatever value it is needed.
> 
> Such an approach would be the right thing to do, because the presence of a special value in this address is not a requirement at all for _this_ Zephyr image to run properly, but a requirement for a "parent" image.

I think that is overkill, we already have cases of SoC specific ifdef's in the arch code.  I don't see why it being asm vs c would make any difference.  We have things like CONFIG_CPU_HAS_NRF_IDAU and CONFIG_CPU_HAS_NXP_MPU.

2020-04-01 13:51 UTC, ioannisg commented
>I think that is overkill, we already have cases of SoC specific ifdef's in the arch code. I don't see why it being asm vs c would make any difference. We have things like CONFIG_CPU_HAS_NRF_IDAU and CONFIG_CPU_HAS_NXP_MPU already in arch/arm/core/aarch32/cortex_m

No, we should in fact do better with cleaning up the ARCH code and ideally remove everything that is not generic to ARM. That is:
- remove the _single_ occurrence of CPU_HAS_NXP_MPU from fault.c and place the fault handling function somewhere in soc/arm/nxp
- remove the _single_ occurence of CPU_HAS_NRF_IDAU from the arm linker script and include this as a linker snippet from somewhere in soc/arm/nrf

Also: your comparison is not fair because those Kconfigs are needed for the build itself to work, not for some other image that happens to co-exist with Zephyr. Zephyr core ARCH code cannot be aware of all the requirements of other co-existing images. 

I could agree with adding 0 unconditionally, in the reserved ARM exception entries, if this solves the current problem. This would be a clean solution at least.

2020-04-01 14:31 UTC, galak commented
@MaureenHelm do you have a reference in the LPC55S69 manual for this feature?

2020-04-01 20:49 UTC, MaureenHelm commented
> Although this should be OK and safe to do, it does not look ideal that SOC-specific conditionals are present in this core ARM assembly file.
> 
> If the secure boot (i.e. another image) needs to read a special value in this address, this should be taken care of by the image building process. For example, after Zephyr is built, some script locates the address of the vector table in the generated .hex and overwrites this particular reserved entry with 0x0, or with whatever value it is needed.
> 
> Such an approach would be the right thing to do, because the presence of a special value in this address is not a requirement at all for _this_ Zephyr image to run properly, but a requirement for a "parent" image.

This "other image" (secure boot rom) is in hardware and taped out as part of the chip. The special value is required to run "this" image (i.e., the zephyr image). I agree it's not ideal to put an soc-specific conditional in this part of the code, and at some point we will need to integrate a script into the build process that inserts nonzero values into special reserved entries in the vector table. This will be needed to support signed images, but it is nontrivial work and for now I'd at least like to reliably support plain images with this change. Without it, some applications will mysteriously fail, as I have discovered while debugging #23119.

> do you have a reference in the LPC55S69 manual for this feature?

See chapter 7 and tables 183-184 (page 151) in the [LPC55S69 Reference Manual](https://www.nxp.com/webapp/Download?colCode=UM11126)

2020-04-02 07:56 UTC, ioannisg commented
>  The special value is required to run "this" image (i.e., the zephyr image).

Maureen, what I meant here is that Zephyr does not need any special value written here, to run properly, in the sense that: this .text address is neither read, written, nor instruction-fetched, by the Zephyr image, itself.

2020-04-02 07:58 UTC, ioannisg requested changes
Let's try to put 0 on all vector table entries which are reserved-for-future-use by the ARM architecture. This will not require any SoC-specific defines.

2020-04-02 10:59 UTC, ioannisg commented
opened #24012 for rfc

2020-04-07 14:58 UTC, galak commented
Closing this since we merged #24012

2020-04-07 14:58 UTC, closed without merging