DTS: i.mx Convert driver to new DT_INST macros
zephyrproject-rtos/zephyr pull request #24025
Opened 2020-04-02 16:03 UTC by galak

2020-04-02 21:47 UTC, MaureenHelm requested changes

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/colibri_imx7d_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
this should be i2c1

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/colibri_imx7d_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c2

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/colibri_imx7d_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c3

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/colibri_imx7d_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c4

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/pico_pi_m4/pinmux.c
> + #if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c1

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/pico_pi_m4/pinmux.c
> + #if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c2

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/pico_pi_m4/pinmux.c
> + #if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c3

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/pico_pi_m4/pinmux.c
> + #if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c4

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c1

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c2

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c3

2020-04-02 21:47 UTC, MaureenHelm commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
i2c4

2020-04-02 21:52 UTC, galak commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
fixed

2020-04-02 21:52 UTC, galak commented on boards/arm/warp7_m4/pinmux.c
> +#if DT_HAS_NODE(DT_NODELABEL(i2c))
fixed

2020-04-03 15:59 UTC, MaureenHelm approved these changes

2020-04-04 14:34 UTC, merged