[Backport v2.0-branch] lib: updatehub: Minor bug fixes
zephyrproject-rtos/zephyr pull request #24064
Opened 2020-04-03 12:11 UTC by otavio

This backport the fixes made in #23885.

2020-04-15 21:49 UTC, d3zd3z requested changes

2020-04-15 21:49 UTC, d3zd3z commented on lib/updatehub/updatehub.c
> +	char buffer[3], sha256_image_dowloaded[TC_SHA256_BLOCK_SIZE + 1];
We really need to fix this block size thing. This define has nothing to do with the length of the hex representation of the digest. This should be `TC_SHA256_DIGEST_SIZE*2 + 1`.

2020-04-17 17:15 UTC, d3zd3z requested changes
@otavio can you update this with the latest version that merged into master from #24154.

2020-04-17 18:04 UTC, otavio commented
Sure. @nandojve can you handle it please?

2020-04-17 18:32 UTC, nandojve commented
Added #24154

2020-04-28 17:05 UTC, carlescufi commented
@ceolin @d3zd3z @jukkar this needs review in order to be transitioned to the ready column in the backports project

2020-05-08 18:57 UTC, d3zd3z approved these changes

2020-05-26 16:09 UTC, ceolin approved these changes
lgtm

2020-05-26 17:14 UTC, carlescufi commented
@d3zd3z let's defer this one until we can identify the origin of all commits in this PR

2020-06-02 17:33 UTC, carlescufi commented
@d3zd3z @ceolin please rebase to the latest 2.0-branch and build documentation locally to make sure it doesn't break it and report back please.

2020-06-02 23:08 UTC, d3zd3z commented
One question is why there are 9 commits here, when it says it is a backport of another PR that only has 6 commits.

2020-06-03 02:14 UTC, nandojve commented
>> One question is why there are 9 commits here, when it says it is a backport of another PR that only has 6 commits.

> d3zd3z requested changes on Apr 17
> d3zd3z left a comment
> @otavio can you update this with the latest version that merged into master from #24154.

The other 3 commits are from #24154.

2020-06-04 16:50 UTC, d3zd3z commented
There are 9 commits. 6 are from #23885, and the other three are from #24154. Both have been merged.

2020-06-04 17:39 UTC, d3zd3z commented
> @d3zd3z @ceolin please rebase to the latest 2.0-branch and build documentation locally to make sure it doesn't break it and report back please.

It is unclear to me what to do here @carlescufi. This is already based on the v2.0-branch, but I get documentation build failures when on v2.0-branch directly, even without these changes.

2020-06-11 22:18 UTC, dleach02 approved these changes

2020-08-11 02:44 UTC, nandojve commented
We would like to have this changes on the v2.0 branch.
Could someone remove stale?

2020-08-11 12:23 UTC, jukkar approved these changes

2020-10-13 20:39 UTC, d3zd3z commented
At this point 2.0 is beyond the support window, so this does not need to be merged, but can still be referenced externally.

2020-11-17 22:47 UTC, closed without merging