net: sntp: use socket functions with zsock_ prefix
zephyrproject-rtos/zephyr pull request #24129
Opened 2020-04-06 16:01 UTC by jdascenzio

Use socket functions with zsock_ prefix to avoid necessarily
enabling NET_SOCKETS_POSIX_NAMES

2020-04-06 16:33 UTC, pfalcon requested changes
I believe we discussed this pattern with @jukkar and he made an argument which made us conclude that we shouldn't perform such a conversion. Sadly, I don't remember the argument exactly now :-(. But if I were to provide counter-argument now, it would be: this is userspace library, userspace libraries should work with both POSIX and non-POSIX Zephyr configuration, and IIRC, `zsock_` aren't supported in POSIX config.

Maybe, you should start from the other side and explain, why it's beneficial "to avoid necessarily
enabling NET_SOCKETS_POSIX_NAMES".

Otherwise, perhaps we should make NET_SOCKETS_POSIX_NAMES default to `y` for non-POSIX config.

2020-04-06 17:10 UTC, jdascenzio commented
>  But if I were to provide counter-argument now, it would be: this is userspace library, userspace libraries should work with both POSIX and non-POSIX Zephyr configuration, and IIRC, `zsock_` aren't supported in POSIX config.



> I believe we discussed this pattern with @jukkar and he made an argument which made us conclude that we shouldn't perform such a conversion. Sadly, I don't remember the argument exactly now :-(. But if I were to provide counter-argument now, it would be: this is userspace library, userspace libraries should work with both POSIX and non-POSIX Zephyr configuration, and IIRC, `zsock_` aren't supported in POSIX config.
> 
> Maybe, you should start from the other side and explain, why it's beneficial "to avoid necessarily
> enabling NET_SOCKETS_POSIX_NAMES".
> 
> Otherwise, perhaps we should make NET_SOCKETS_POSIX_NAMES default to `y` for non-POSIX config.

Ok, I understand your argument.  To avoid compilation error (implicit declaration of function 'close' in sntp_close) NET_SOCKETS_POSIX_NAMES could be force to yes in Kconfig:
```
menuconfig SNTP                                                                                                                                                                                                                             
        bool "SNTP"                                                                                                                                                                                                                         
        select NET_SOCKETS                                                                                                                                                                                                                  
        select NET_SOCKETS_POSIX_NAMES if (!ARCH_POSIX && !POSIX_API)                                                                                                                                                                       
        help                                                                                                                                                                                                                                
          Enable SNTP client library 
```

2020-04-06 19:54 UTC, closed without merging

2020-04-07 12:48 UTC, pfalcon commented
@jdascenzio: I'd say closure of this was premature, I'd suggest to reopen it and wait for comments from @jukkar.

> menuconfig SNTP                                                                                                                                                                                                                             
        bool "SNTP"                                                                                                                                                                                                                         
        select NET_SOCKETS                                                                                                                                                                                                                  
        select NET_SOCKETS_POSIX_NAMES if (!ARCH_POSIX && !POSIX_API)        

I'd consider such a solution too adhoc. This issue definitely affects (or may affect) more than just SNTP lib. That's why I suggest to discuss various ways to solve it. And as I hinted in my original comment, I'd consider enabling NET_SOCKETS_POSIX_NAMES by default (unless POSIX_API is enabled). (Whereas using too much of `select` is considered an anti-pattern, as it complicates config dependencies too much.)

2020-04-07 14:01 UTC, jukkar commented
For the network stack internal APIs, I think we could use the zsock_xxx() APIs directly if using BSD socket API is causing too much problems. But for the sample applications, we should use the BSD socket API as that is what applications are suppose to use anyway.