Bluetooth: Mesh: Fixes dumplicated close callback
zephyrproject-rtos/zephyr pull request #24177
Opened 2020-04-08 07:42 UTC by LingaoMeng

When PB-GATT Procedure timeout, func `bt_mesh_pb_gatt_close`
will also dumplicated with `link_closes()`

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

2020-04-08 07:47 UTC, LingaoMeng commented
CC @trond-snekvik @jhedberg 
I'm think to move `provision timer` move to `prov.c` in another pr.  This make sense?

2020-04-08 09:46 UTC, jhedberg commented
Could you fix the obvious typo in the subject and commit message: dumplicate -> duplicate? Thanks :)

2020-04-08 14:37 UTC, trond-snekvik approved these changes

2020-04-08 14:57 UTC, jhedberg requested changes
Looks fine, but the commit message still contains "dumplicated". It also contains a reference to a non-existent function called `link_closes()`, perhaps you meant `link_closed()`?

2020-04-09 11:19 UTC, jhedberg approved these changes

2020-04-09 11:19 UTC, merged