NXP: Configure NXP Kinetis FlexTimer DTS nodes for PWM on board level
zephyrproject-rtos/zephyr pull request #24498
Opened 2020-04-19 20:46 UTC by henrikbrixandersen

Don't assume in the soc level device trees that FlexTimer nodes will always be configured as PWM. Instead, configure FlexTimer nodes for PWM at the board level for NXP Kinetis boards.

The NXP Kinetis FlexTimer IP can be configured as PWM controller, counter,
quadrature decoder, pulse-width measurements and more. Zephyr currently only has support for PWM. This PR is preparation for introduction of Zephyr support for other FlexTimer functionality.

2020-04-29 18:54 UTC, galak requested changes
LGTM.  Can we remove the pwm-N aliases?  Not sure we need them anywhere.

2020-04-29 19:01 UTC, henrikbrixandersen commented
> LGTM. Can we remove the pwm-N aliases? Not sure we need them anywhere.

@galak Thanks. I have removed the unused aliases.

2020-04-29 19:04 UTC, galak approved these changes

2020-04-30 13:28 UTC, MaureenHelm approved these changes

2020-04-30 13:28 UTC, merged