board/arm/stm32h747i_disco: add support of flash with openocd
zephyrproject-rtos/zephyr pull request #24682
Opened 2020-04-24 14:19 UTC by ABOSTM

Allow to flash either Cortex M4 or M7 with OpenOCD
(depending on which Board/Core has been compiled)
Command: west flash

Warning: Dependency with recent OpenOCD patch:
Windows: https://gnutoolchains.com/arm-eabi/openocd/
                 version 20200408
Linux : http://openocd.zylin.com/
           SHA1: 0a804222da63c5f849efa23b019a59e2dea76842

Do not merge yet due to OpenOCD dependency.

2020-04-29 18:45 UTC, erwango requested changes
Please update doc regarding openocd compatibility, potential issues that could be faced and how to overcome.
Otherwise LGTM

2020-04-30 12:03 UTC, ABOSTM commented
Done

2020-04-30 12:35 UTC, erwango approved these changes

2020-04-30 12:36 UTC, erwango requested changes

2020-04-30 12:36 UTC, erwango commented on boards/arm/stm32h747i_disco/doc/index.rst
> +(with `STM32CubeProgrammer` for example) to make it work again.
Remove `` around STM32CubeProgrammer as it makes doc generation failing

2020-04-30 14:55 UTC, erwango approved these changes

2020-05-04 12:18 UTC, erwango commented
Failing tests: qemu_x86_64:tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls / tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls

2020-05-05 12:48 UTC, erwango commented
Trying to get CI passed

2020-05-06 15:57 UTC, merged