[backport v2.2] Bluetooth: controller: Update Bluetooth version to 5.2
zephyrproject-rtos/zephyr pull request #25121
Opened 2020-05-08 05:21 UTC by cvinayak

backport of #25072 

This will allow for Bluetooth Controller qualified design listing with v5.2.

2020-05-08 07:59 UTC, joerchan approved these changes

2020-05-08 08:50 UTC, jhedberg requested changes
We cannot merge backports unless they have a corresponding bug report. If the original PR doesn't have a matching issue you'll need to open one for this backport PR, something along the lines of "Controller reports incorrect Bluetooth version".

2020-05-08 10:16 UTC, cvinayak commented
I just followed in lines of https://github.com/zephyrproject-rtos/zephyr/pull/24925,  does adding the label "bug" to upstream PR suffice?

2020-05-08 11:13 UTC, jhedberg commented
@cvinayak no, you need a real issue. The PR you referenced is special in that it does have an issue but it’s in the restricted Jira (since our security folks considered it a security vulnerability)

2020-05-08 11:26 UTC, cvinayak commented
@jhedberg updated PR description with GH issue #25130

2020-05-08 15:53 UTC, joerchan commented
Putting a DNM until @thoh-ot has a chance to look at this as requested by @wopu-ot

2020-05-11 10:24 UTC, cvinayak commented
@thoh-ot @wopu-ot any updates?

2020-05-11 10:27 UTC, thoh-ot requested changes
The host qualification evidence that we already collected for v2.2 is based on Core Specification 5.1 and that is also the version we are targeting in the qualification of the controller; therefor we would argue against updating the version in the v2.2 branch.

2020-05-11 13:53 UTC, jhedberg commented
I guess this PR should be closed then without merging?

2020-05-11 14:21 UTC, joerchan commented
> I guess this PR should be closed then without merging?

[12:38] Cufi, Carles
    Let’s do 5.1 and stay on the safe side.

From an offline discussion there seems to an agreement to stay with 5.1, so this should be closed without merging.

2020-05-11 14:25 UTC, cvinayak commented
Closing, its decided v2.2-branch code base will use LL_VERSION of BT version 5.1.

2020-05-11 14:25 UTC, closed without merging