tests: timing_info: cleanup timing calculation code
zephyrproject-rtos/zephyr pull request #25503
Opened 2020-05-20 21:26 UTC by dcpleung

() This is simply to clean up the code for cycles and timing
   calculations as there are quite a bit of unnecessary AND
   operations.
() This also moves the cycle calculation closer to the print
   statement as a few calculations were done between grabbing
   counter values.
() PRINT_STATS() now takes only two parameters as the third
   one was always calling CYCLES_TO_NS(2nd) anyway.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

2020-06-13 22:35 UTC, nashif approved these changes

2020-07-08 19:49 UTC, sjg20 approved these changes

2020-07-08 19:49 UTC, sjg20 commented on tests/benchmarks/timing_info/src/msg_passing_bench.c
> +	msg_q_put_w_cxt_end_time = ((uint32_t)arch_timing_value_swap_common);
Can you drop the outer brackets?

2020-07-08 19:49 UTC, sjg20 commented on tests/benchmarks/timing_info/src/msg_passing_bench.c
> +	msg_q_put_w_cxt_start_time = (uint32_t) TIMING_INFO_OS_GET_TIME();
No space after cast, right?

2020-07-08 19:50 UTC, nashif requested changes
please address comments from @sjg20

2020-07-08 19:53 UTC, dcpleung commented
Removed the brackets and space.

2020-07-08 20:04 UTC, nashif approved these changes

2020-07-08 20:50 UTC, merged