Bluetooth: controller: split: Update feature exchange to BTCore V5.0
zephyrproject-rtos/zephyr pull request #25550
Opened 2020-05-22 13:30 UTC by kruithofa

The existing feature exchange procedure does not give the proper response as specified
in the BT core spec 5.0.
The old behaviour is that the feature-response returns the logical and of the features
for both peers.
The behaviour implemented here is that the feature-response returns the featureset of
the peer, except for octet 0 which is the logical and of the supported features.
Tested by using the bt shell, and having different featuresets on the 2 peers.

This fixes #25483 

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2020-05-25 01:25 UTC, cvinayak requested changes

2020-05-25 07:25 UTC, kruithofa commented on subsys/bluetooth/controller/ll_sw/ull_adv.c
>  		conn->llcp_feature.features = LL_FEAT;
This is the featureset on the connection; so I think a better name will then be 'features_conn'

2020-05-25 13:32 UTC, thoh-ot requested changes

2020-05-25 13:32 UTC, thoh-ot commented on subsys/bluetooth/controller/ll_sw/ull_conn.c
> +		feat_land_octet0(feat_get(&req->features[0]), LL_FEAT);
Something is wrong with the dual assignment to llcp_feature.features_conn

2020-05-25 15:04 UTC, cvinayak approved these changes

2020-05-26 08:57 UTC, thoh-ot approved these changes

2020-05-26 12:34 UTC, carlescufi approved these changes

2020-05-26 12:34 UTC, merged