manifest: update west.yml for find_package(Zephyr) in mcuboot
zephyrproject-rtos/zephyr pull request #25696
Opened 2020-05-28 11:09 UTC by tejlmand

This commit updates the manifest to use mcuboot revision containing the
find_package(Zephyr) feature.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

-----
People can now build Zephyr without ZEPHYR_BASE in environment, then there is a high risk that someone building mcuboot will suddenly experience build failures.

2020-06-01 10:47 UTC, nvlsianpu requested changes

2020-06-01 10:47 UTC, nvlsianpu commented on west.yml
> +      revision: pull/22/head
SHA: 4bb0f9547f80e1d14cb6591db12030e2dbf891f4

2020-06-02 05:09 UTC, tejlmand commented on west.yml
> +      revision: pull/22/head
Done.

2020-06-02 05:09 UTC, tejlmand commented
west.yml updated to use SHA.

2020-06-02 17:38 UTC, nvlsianpu approved these changes

2020-06-03 09:07 UTC, nvlsianpu commented
@carlescufi Can be merged.

2020-06-03 12:20 UTC, henrikbrixandersen commented
Beware that there are still references to the `ZEPHYR_BASE` environment variable in `mcuboot` (e.g. `scripts/assemble.py` and `samples/zephyr/Makefile`, so people are still likely to be confused if building without `ZEPHYR_BASE` set in the environment.

2020-06-03 18:33 UTC, tejlmand commented
> Beware that there are still references to the `ZEPHYR_BASE` environment variable in `mcuboot` (e.g. `scripts/assemble.py` and `samples/zephyr/Makefile`), so people are still likely to be confused if building without `ZEPHYR_BASE` set in the environment.

@henrikbrixandersen Thanks for the warning.
I have made a followup PR here: https://github.com/zephyrproject-rtos/mcuboot/pull/23

I did a search, and the followup PR should now include all remaining places in mcuboot.
Of course, users using the Makefile must still specify `ZEPHYR_BASE`, either on `make` or in the environment, but ZEPHYR_BASE is now passed on to `assemble.py` as argument.

2020-06-15 16:31 UTC, mbolivar-nordic approved these changes

2020-06-15 19:33 UTC, tejlmand commented
superseeded by: https://github.com/zephyrproject-rtos/zephyr/pull/26042

2020-06-15 19:33 UTC, closed without merging