drivers: usb: handle a null output arg on SAM0
zephyrproject-rtos/zephyr pull request #25879
Opened 2020-06-01 16:20 UTC by nzmichaelh

The CDC driver doesn't care about the written bytes and sets ret_bytes to NULL.

Signed-off-by: Michael Hope <mlhx@google.com>

2020-06-02 07:29 UTC, jfischer-no requested changes
It is not specific to the CDC (ACM?), the driver has to check it, please fix commit message.

2020-06-02 19:14 UTC, nzmichaelh commented
Done, PTAL.

2020-06-02 19:57 UTC, jfischer-no approved these changes

2020-06-05 19:17 UTC, nzmichaelh commented
@jfischer-phytec-iot Johann, I found another bug in the driver and updated this pull request.  PTAL.

2020-06-06 09:59 UTC, jfischer-phytec-iot commented
@nzmichaelh Please move last commit to own PR, this one was already approved and last commit needs more discussion, thanks.

2020-06-06 10:18 UTC, nzmichaelh commented
@jfischer-phytec-iot done

2020-06-12 18:10 UTC, sslupsky commented
@nzmichaelh I've also run across an issue in this function where BK1RDY is not set indicating the transfer is not complete.  I use a modified driver that checks the status of this hardware flag as follows:

```
	s64_t reftime = k_uptime_get();

	while (endpoint->EPSTATUS.bit.BK1RDY) {
		/* previous transfer is still not complete */
		if ((k_uptime_get() - reftime) >= 1) {
			return -EAGAIN;
		}
	}
```

2020-06-15 14:55 UTC, carlescufi approved these changes

2020-06-15 14:55 UTC, merged