eth: fix: Check if passed iface pointer is not NULL
zephyrproject-rtos/zephyr pull request #25897
Opened 2020-06-02 09:32 UTC by lmajewski

The eth_stats_update_errors_rx() implicitly assumes that passed pointer
to struct net_if is not NULL.

This is not true for MCUX's eth_rx() (in eth_mcux.c), where we can
execute eth_stats_update_errors_rx() after net_recv_data() returning
-EINVAL because of passed NULL iface pointer.

This change fixes this problem with adding extra check on iface not
being NULL before it is dereferenced.

Signed-off-by: Lukasz Majewski <lukma@denx.de>

2020-06-02 11:50 UTC, jukkar requested changes
Looks good, one minor issue.

2020-06-02 11:50 UTC, jukkar commented on subsys/net/l2/ethernet/eth_stats.h
> +	if (!iface)
You need to add {} even for one liners.

2020-06-02 11:50 UTC, jukkar commented on subsys/net/l2/ethernet/eth_stats.h
> +	if (!iface)
Also please set the commit subject to `net: eth: Check if ....`

2020-06-03 10:29 UTC, jukkar approved these changes

2020-06-09 07:20 UTC, tbursztyka approved these changes

2020-06-09 07:54 UTC, merged