[TOPIC-BLE-LLCP]: Bluetooth: controller: llcp: update cmake files
zephyrproject-rtos/zephyr pull request #26043
Opened 2020-06-08 10:25 UTC by kruithofa

Updated the CMake files so that they use 'find_package'
Added prefix bt_ to tags in testcase.yaml

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2020-06-08 12:30 UTC, thoh-ot requested changes
Great idea to unify the cmake files

2020-06-09 10:25 UTC, kruithofa commented on tests/bluetooth/controller/ctrl_version/testcase.yaml
> +    tags: test_framework bluetooth bt_version bt_ull_llcp
That is more consistant, yes

2020-06-18 08:03 UTC, thoh-ot approved these changes

2020-06-18 09:15 UTC, kruithofa commented
Rebased for fixing merge conflicts

2020-06-18 09:38 UTC, merged