drivers: wifi: esp: Retry command for getting IP settings
zephyrproject-rtos/zephyr pull request #26436
Opened 2020-06-25 08:21 UTC by tsvehagen

If AT_CIPSTA? command fails it is retried again after 5 seconds.

Fixes #25741

Signed-off-by: Tobias Svehagen <tobias.svehagen@gmail.com>

2020-06-25 08:34 UTC, jukkar commented on drivers/wifi/esp/esp.c
> +					       K_SECONDS(5));
This 5 second hardcoded value seems quite arbitrary. Should we provide a Kconfig option for that so that the value can be tweaked if needed?

2020-06-25 08:35 UTC, mniestroj requested changes

2020-06-25 08:35 UTC, mniestroj commented on drivers/wifi/esp/esp.c
> +		k_delayed_work_submit_to_queue(&dev->workq, &dev->ip_addr_work,
Would be nice to have some `LOG_WRN()` or `LOG_ERR()` here.

2020-06-25 08:46 UTC, mniestroj commented on drivers/wifi/esp/esp.c
> +		k_delayed_work_submit_to_queue(&dev->workq, &dev->ip_addr_work,
Main reason to have this log is to find out how frequently does AT+CIPSTA? fail. Then we can better tweek or export 5s timeout as Kconfig, as @jukkar proposed.

2020-06-30 15:38 UTC, mniestroj approved these changes

2020-07-20 07:03 UTC, jukkar approved these changes

2020-07-22 10:16 UTC, pfalcon reviewed
@tsvehagen: Can you look what's up with build failures here?

2020-07-23 19:08 UTC, mniestroj commented
@pfalcon Those failures are all qemu_arc related. qemu_arc has been disabled since in CI tests in master (7d10b68baaaa8fcf32610f1c65156685dc87cc6d).

@tsvehagen One more rebase will most probably solve build issues and make CI green :)

2020-07-24 09:22 UTC, tsvehagen commented
@pfalcon @mniestroj Rebased

2020-07-24 10:01 UTC, merged