Bluetooth: controller: Remove redundant BT_LL_SW_SPLIT conditional
zephyrproject-rtos/zephyr pull request #26559
Opened 2020-07-01 06:06 UTC by cvinayak

Remove redundant use of BT_LL_SW_SPLIT conditional.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2020-07-01 07:43 UTC, dagbja approved these changes

2020-07-02 11:08 UTC, kruithofa commented
Please look at other places where the BT_LL_SW_SPLIT still is used, and whether that is correct or not

2020-07-02 11:11 UTC, kruithofa requested changes
Please look at other places where the BT_LL_SW_SPLIT is used and see if this needs to be removed there as well

2020-07-16 07:33 UTC, joerchan approved these changes

2020-07-17 12:04 UTC, kruithofa approved these changes
LGTM

2020-07-20 10:46 UTC, merged