STM32H7: manage Dual core boot whatever option bytes configuration
zephyrproject-rtos/zephyr pull request #26765
Opened 2020-07-09 11:23 UTC by ABOSTM

STM32H7: manage Dual core boot whatever option bytes configuration

Manage Dual core boot automatically whatever Option Bytes configuration.
No more need of KConfig STM32H7_DUAL_CORE_BOOT to match Option Bytes.

Signed-off-by: Alexandre Bourdiol <alexandre.bourdiol@st.com>

2020-07-13 12:02 UTC, erwango requested changes
Nit pick, otherwise LTGM

2020-07-13 12:02 UTC, erwango commented on soc/arm/st_stm32/stm32h7/soc_m7.c
> +		/* CM4 is started at boot in parallele of CM7
```suggestion
		/* CM4 is started at boot in parallel of CM7
```

2020-07-15 08:37 UTC, ABOSTM commented on soc/arm/st_stm32/stm32h7/soc_m7.c
> +		/* CM4 is started at boot in parallele of CM7
Done

2020-07-15 11:18 UTC, erwango approved these changes

2020-07-22 15:15 UTC, erwango commented
@ABOSTM can you rebase  ?

2020-07-22 15:16 UTC, erwango commented
@Nukersson , @lochej can you have a look ?

2020-07-22 15:28 UTC, ABOSTM commented
> @ABOSTM can you rebase ?

Done

2020-07-22 16:13 UTC, lochej commented
> 
> 
> @Nukersson , @lochej can you have a look ?

LGTM, I'm not able to test this one as I don't have any STM32H745/757. But that implementation complies with the RM0399 when it comes to CM4 booting.

2020-07-22 16:22 UTC, erwango commented
> > @Nukersson , @lochej can you have a look ?
> 
> LGTM, I'm not able to test this one as I don't have any STM32H745/757. But that implementation complies with the RM0399 when it comes to CM4 booting.

@lochej are you able to approve then ? We need 2 approvals to get a release engineer to merge it.

2020-07-22 16:29 UTC, Nukersson commented
> @Nukersson , @lochej can you have a look ?

Tested the branch of  this PR on my NUCLEO-H745ZI-Q as follows:

1. Cortex-M7: running [Hello World](https://docs.zephyrproject.org/latest/samples/hello_world/README.html) over `USART3`
2. Cortex-M4: running [Blinky](https://docs.zephyrproject.org/latest/samples/basic/blinky/README.html#overview)

After the compilation both cores booting properly, `minicom` console shows `hello_world` and `LD2` blinks.

Moreover, setting two breakpoints in `soc_m7.c` on lines `47` and `54` respectively leads to break on line `47`, which means  following:

```
/* CM4 is started at boot in parallel of CM7
* but CM4 should set itself into stop mode,
* waiting for CM7 clock initialization.
*/
```

But I have only one problem (maybe incorrect understanding) with the implementation:

- What if developer does not need M4 booting anyway? As I understand the `else` of `if (READ_BIT(SYSCFG->UR1, SYSCFG_UR1_BCM4)) {` (line 54 of `soc_m7.c`) will force Cortex-M4 booting.

2020-07-22 16:36 UTC, ABOSTM commented
> * What if developer does not need M4 booting anyway? As I understand the `else` of `if (READ_BIT(SYSCFG->UR1, SYSCFG_UR1_BCM4)) {` (line 54 of `soc_m7.c`) will force Cortex-M4 booting.

In such case developer should disable CONFIG_STM32H7_DUAL_CORE, and M4 wakeup will not happen any more:
```
#if defined(CONFIG_STM32H7_DUAL_CORE)
/* Unlock M4 once system configuration has been done */
SYS_INIT(stm32h7_m4_wakeup, POST_KERNEL, CONFIG_APPLICATION_INIT_PRIORITY);
#endif /* CONFIG_STM32H7_DUAL_CORE */
```

2020-07-22 16:38 UTC, lochej approved these changes

2020-07-22 16:38 UTC, Nukersson commented
> > * What if developer does not need M4 booting anyway? As I understand the `else` of `if (READ_BIT(SYSCFG->UR1, SYSCFG_UR1_BCM4)) {` (line 54 of `soc_m7.c`) will force Cortex-M4 booting.
> 
> In such case developer should disable CONFIG_STM32H7_DUAL_CORE, and M4 wakeup will not happen any more:
> 
> ```
> #if defined(CONFIG_STM32H7_DUAL_CORE)
> /* Unlock M4 once system configuration has been done */
> SYS_INIT(stm32h7_m4_wakeup, POST_KERNEL, CONFIG_APPLICATION_INIT_PRIORITY);
> #endif /* CONFIG_STM32H7_DUAL_CORE */
> ```

Perfect form Alexander Kozhinov ( still learning Zephyr's KConfig 😄 )

2020-07-22 16:51 UTC, KozhinovAlexander approved these changes
LGTM

2020-07-22 16:54 UTC, lochej commented
> > > @Nukersson , @lochej can you have a look ?
> > 
> > 
> > LGTM, I'm not able to test this one as I don't have any STM32H745/757. But that implementation complies with the RM0399 when it comes to CM4 booting.
> 
> @lochej are you able to approve then ? We need 2 approvals to get a release engineer to merge it.

I approve these changes but I don't have write access, so my approval doesn't count 😅

2020-07-23 07:19 UTC, erwango commented
> I approve these changes but I don't have write access, so my approval doesn't count sweat_smile

@lochej Only a limited set of people (said "release engineers") have write access and are able to merge PRs once approved.
Though, anyone with interest in a change can review and provide feedback (approve, comment or request modification). Among those, some will be able to block a PR because they are codeowner, have an recognized expertise or generally known to provide valuable comments. Minimum of 2 approvals is required so a release engineer can merge a PR. So, the more the merrier...

2020-07-31 16:09 UTC, MaureenHelm approved these changes

2020-07-31 16:09 UTC, merged