[TOPIC-BLE-LLCP] Bluetooth: controller: allow multiple version requests
zephyrproject-rtos/zephyr pull request #26878
Opened 2020-07-15 13:42 UTC by kruithofa

At the linked layer level we are only allowed to send one VERSION_IND
per connection, but the host may request version information
multiple times.
We need to ensure that we fill out data correctly in case of
multiple requests, even when we only send one VERSION_IND
over the air. We need to set the response_opcode correctly
since that is used for selecting how to decode/fill in correct data
for the host

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2020-07-16 08:38 UTC, kruithofa commented
Add unit test for sending 2 VERSION_IND

2020-08-12 09:16 UTC, thoh-ot requested changes
The unit test that you mention in the comments is missing.

2020-08-12 12:56 UTC, kruithofa commented
> The unit test that you mention in the comments is missing.

Indeed; I wonder where it went. In any case I'll put it back in

2020-08-13 13:09 UTC, kruithofa commented
> The unit test that you mention in the comments is missing.

I found out; I added the test on the branch for implementing HCI interface. The test is now added here.

2020-08-17 07:58 UTC, thoh-ot approved these changes

2020-08-27 08:17 UTC, merged