sensor: Add Silabs SI7055 support
zephyrproject-rtos/zephyr pull request #26904
Opened 2020-07-16 18:08 UTC by greg-leach

Add support for the Silabs SI7055 temperature sensor

Signed-off-by: Greg Leach <greg.leach@lairdconnect.com>

2020-07-22 19:24 UTC, rerickson1 approved these changes

2020-07-23 13:12 UTC, avisconti submitted a review, later dismissed
Seems overall simple and good, but check identation when you break lines

2020-07-23 13:12 UTC, avisconti commented on drivers/sensor/si7055/si7055.c
> +		SI7055_MEAS_TEMP_MASTER_MODE, temp, sizeof(temp));
check identation

2020-07-23 13:12 UTC, avisconti commented on drivers/sensor/si7055/si7055.c
> +				temp[SI7055_DATA_SIZE]){
identation

2020-07-23 13:12 UTC, avisconti commented on drivers/sensor/si7055/si7055.c
> +					temp[SI7055_TEMPERATURE_DATA_BYTE_1];
identation (I would put the <<8 together with first line)

2020-07-23 13:12 UTC, avisconti commented on drivers/sensor/si7055/si7055.c
> +				SI7055_MULTIPLIER;
identation also here

2020-07-30 21:32 UTC, MaureenHelm requested changes
Please add this sensor to `tests/drivers/build_all/sensors_i_z.conf` to ensure it gets build in CI.

I don't quite understand your comment about squashed commits in the commit message. You seem to refer to a commit that isn't in the history?

2020-07-30 21:32 UTC, MaureenHelm commented on drivers/sensor/si7055/Kconfig
> +	default n
Bools are implicitly default n, so you can remove this line

2020-08-05 19:49 UTC, MaureenHelm approved these changes

2020-08-05 19:50 UTC, merged