drivers: defined charger driver api's.
zephyrproject-rtos/zephyr pull request #26968
Opened 2020-07-20 11:10 UTC by rkotabag

Defined API's header file for new charger driver.

Signed-off-by: Ramesh Kotabagi <ramesh.kotabagi@intel.com>

2020-07-20 14:43 UTC, pabigot requested changes
Same as #26974: It would be OK to add this as a specific driver for a specific charger management capability, but a generic API needs to be developed taking into account #2542.

There may also be some precedent for treating this functionality as a sensor, e.g. ti,bq274xx.

2020-07-20 15:01 UTC, nashif requested changes

2020-07-20 15:01 UTC, nashif commented on dts/bindings/charger/renesas,isl92xx.yaml
> +# Copyright (c) 2020 Intel Corporation
this should come with the driver it supports, should be separate from the API introduction/discussion.

2020-07-20 15:01 UTC, nashif commented on drivers/charger/Kconfig
> +
Kconfigs needs to be used and should come with the driver/subsystem they support.

2020-07-20 20:19 UTC, pabigot commented
See https://github.com/zephyrproject-rtos/zephyr/pull/26974#issuecomment-661311525 for further information on this approach.

2020-07-23 11:42 UTC, carlescufi commented on CODEOWNERS
> +/drivers/charger/                         @rgundi
Is that correct? your current handle seems to be @rkotabag

2020-07-28 16:41 UTC, carlescufi commented
@rkotabag are you planning to add an implementation of this driver? This is a requirement for any new API:

>The API introduction should be accompanied by at least one implementation of said API (in the case of peripheral APIs, this corresponds to one driver)

https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#experimental

2020-07-28 17:35 UTC, rkotabag commented
> @rkotabag are you planning to add an implementation of this driver? This is a requirement for any new API:
> 
> > The API introduction should be accompanied by at least one implementation of said API (in the case of peripheral APIs, this corresponds to one driver)
> 
> https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#experimental

Up streaming the driver implementation for defined charger API's is currently dropped after discussing with our internal team, due to the following reasons,
1. Defined API and driver implementation are specific to particular chip and we are not sure w.r.t NDA and IP regarding same to open source the implementation.
2. Defined API's does not  meet 100% expectations of #2542 
So its decided internally that we will modify the current API for charger and battery driver to meet the requirement #2542  

So this pull request will be closed and will be working on to meet the requirement of #2542 .

2020-07-28 17:47 UTC, rkotabag commented
Up streaming the driver implementation for defined charger API's is currently dropped after discussing with our internal team, due to the following reasons,
1. Defined API and driver implementation are specific to particular chip and we are not sure w.r.t NDA and IP regarding same to open source the implementation.
2.Defined API's does not meet 100% expectations of #2542

So its decided that we will be working on to meet the requirement of #2542  and close this pull request.

I am closing the this pull request as commented above. 
I thank everyone for there valuable inputs and exposure to #2542 requirement.

2020-07-28 17:47 UTC, closed without merging