drivers: counter: Add native_posix rtc counter
zephyrproject-rtos/zephyr pull request #26976
Opened 2020-07-20 13:23 UTC by FilipZajdel

Adds native_posix and native_posix_64 counter driver which uses rtc.
Driver is needed to develop tests executed using native_posix board.
Module was built around native_rtc with use of a thread which periodically
reads rtc value and thus it's not reliable enough to run in -no-rt mode.
Module was tested using tests/drivers/counter/counter_basic_api and
samples/drivers/counter/alarm.

Signed-off-by: FilipZajdel <filip.zajdel@nordicsemi.no>

2020-07-20 13:37 UTC, aescolar requested changes
Sorry but this is fundamentally not OK.
There is no way this can be merged.

What problem are you trying to solve?

2020-07-20 14:07 UTC, FilipZajdel commented
The problem I'm trying to solve is to built Zigbee stack using native_posix board. 
The stack uses counter driver, which hasn't yet been implemented.
What exactly do you mean by "fundamentally not OK"? 
Does the approach should be changed 
(to get rid of thread within driver and implement this functionality within native_posix board code)?

2020-07-20 14:26 UTC, aescolar commented
> Zigbee stack using native_posix board

(off-topic) Do you have some Zigbee HW attached to a Linux machine?

>What exactly do you mean by "fundamentally not OK"?

You are spawning an asynchronous pthread to do something which should be already taken care of.
The concept of time in native_posix is overall handled by the "time_machine" (hw_models_top.c) and the HW timer models.
The current native_posix timer HW models takes care for you of linking real time and simulated time. You should not need to worry about this in other places. (and if you do, you will probably break things badly).

For example:
* If you want to have a HW model of a device which allows you to queue alarms, where that HW device awakes every now and then to trigger an interrupt, you can do that easily: By adding a new HW model with a new "event timer" (see https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/posix/native_posix/hw_models_top.c#L38 , https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/posix/native_posix/hw_models_top.c#L48  & https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/posix/native_posix/hw_models_top.c#L150 . This uses exactly the same patters as the nrf52_bsim HW models. So you can get some inspiration on how those are built if you want, see for example https://github.com/BabbleSim/ext_NRF52_hw_models/blob/master/src/HW_models/NRF_RNG.c )

* If you want to handle it just with driver code, without any HW models, you can just rely on the Zephyr OS API (k_sleep() etc.)

2020-07-20 15:10 UTC, FilipZajdel commented
> If you want to handle it just with driver code, without any HW models, you can just rely on the Zephyr OS API (k_sleep() etc.)

I considered that option, but finally rejected that due to the fact that k_sleep() etc. functions are constrained by system tick resolution which is not enough for my needs. 

> If you want to have a HW model of a device which allows you to queue alarms, where that HW device awakes every now and then to trigger an interrupt

Would it be okay to extend native_posix board by providing functions to register interrupt routines called by the machine at some point in simulated time? Using this extension, counter driver could be built without breaking the concept of simulated time.

> (off-topic) Do you have some Zigbee HW attached to a Linux machine?

HW is going to be replaced by simulation of 802.15.4. I consider extending BabbleSim with 802.15.4 support. How hard do you find that? Do you know if anyone tried it before?

2020-07-20 18:40 UTC, aescolar commented
>  functions are constrained by system tick resolution which is not enough for my needs.

You can configure the system tick to be as high as you want in native_posix: up to 1MHz with `CONFIG_SYS_CLOCK_TICKS_PER_SEC`

> Would it be okay to extend native_posix board by providing[...]

If all you really want is a counter/timer driver: What you would need could be easily implemented. But I would do it keeping a proper separation of "HW models" and driver. (I would not call it an "interrupt routine" if I would be going around the Zephyr interrupt mechanism, and the native_posix interrupt controller)

>> (off-topic) Do you have some Zigbee HW attached to a Linux machine?
>
> HW is going to be replaced by simulation of 802.15.4. I consider extending BabbleSim with 802.15.4 support. How hard do you find that? Do you know if anyone tried it before?

NRF52840 like? in the 2.4GHz band?

Anyhow, in this case I would not go the native_posix way, as what you would be building would not end up achieving what you really need.
If it were me, I would fork the BabbleSim 2.4GHz Phy and 2G4_libPhyComv1, prototype there the 802.15.4 support, and also prototype the support in a fork of the nrf52 HW models (a 52840 variant, or maybe a variant for the 5340)
This seems like a longer path, and will take some investment, but if done well it would pay off. Once you have the HW models supporting what is used, all SW (including drivers) is just the real Nordic SW. So you end up running your whole SW stack as in reality.
Note that I am biased here because I have built BabbleSim (including another non open source Phy), so to me the way forward would be a very clear, already trotted, path.
But in any case I would start by prototyping the whole thing and getting it running before getting lost in individual PRs, focusing on the radio, as that is were the real work would be.

2020-07-21 14:17 UTC, FilipZajdel commented
Thank you for the great feedback. I'm closing this PR.

2020-07-21 14:17 UTC, closed without merging