[DNM] drivers: serial: Add error code to uart_rx_buf_rsp (unstable API change)
zephyrproject-rtos/zephyr pull request #27234
Opened 2020-07-29 11:33 UTC by nordic-krch

API did not cover a case when uart_rx_buf_rsp is called when receiver
is already disabled. It may happen if uart_rx_buf_rsp is called too
late and active transfer is already finished. In that case -EAGAIN is
returned.

Added implementation for nrf_uarte.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2020-07-29 11:34 UTC, nordic-krch commented
DNM until other implementations are updated.

2020-07-29 11:59 UTC, carlescufi approved these changes
This looks reasonable to me.

2020-07-29 12:02 UTC, anangl reviewed
Looks good, except for the error code used. I think we should find some more suitable.

2020-07-30 07:05 UTC, de-nordic commented on include/drivers/uart.h
> + * @retval -EAGAIN  Receiver is already disabled (function called too late?).
What is returned from other devices in such case?

2020-07-30 07:37 UTC, de-nordic commented on include/drivers/uart.h
> + * @retval -EAGAIN  Receiver is already disabled (function called too late?).
If we do not distinguish between disabled and non-existent devices, `NODEV` could be used.or use some of operational errors `ENOTCONN` or `ESHUTDOWN`, which is ` Cannot send after transport endpoint shutdown.` according to linux man page for errno, and quite fits `Receiver is already disabled (function called too late?).`

2020-07-31 13:04 UTC, nordic-krch commented on include/drivers/uart.h
> + * @retval -EAGAIN  Receiver is already disabled (function called too late?).
`ESHUTDOWN` sounds ok to me, @anangl what do you think?

2020-07-31 13:25 UTC, nordic-krch commented on include/drivers/uart.h
> + * @retval -EAGAIN  Receiver is already disabled (function called too late?).
turns out that 2/3 implementations already were handling that case and returned `-EACCES`, decided to keep it that way as some may already use it.

2020-07-31 13:26 UTC, nordic-krch commented
Removed DNM. Also added a commit for nrf_uart where i added protection against race condition between disabling RX and calling `uart_rx_buf_rsp`.

2020-08-03 06:23 UTC, anangl requested changes

2020-08-03 06:58 UTC, anangl approved these changes

2020-08-03 07:00 UTC, de-nordic approved these changes

2020-08-03 11:49 UTC, merged