board: arm: nucleo_f207zg: add DAC support
zephyrproject-rtos/zephyr pull request #27349
Opened 2020-08-03 13:11 UTC by ABOSTM

board: arm: nucleo_f207zg: add DAC support
    
* Add DAC support to nucleo_f207zg
* Add fixture `dac_adc_loopback` to test it :  tests\drivers\dac\dac_loopback

2020-08-04 17:03 UTC, galak approved these changes

2020-08-04 17:06 UTC, martinjaeger requested changes

2020-08-04 17:06 UTC, martinjaeger commented on drivers/pinmux/stm32/pinmux_stm32f2.h
> +	STM32_MODER_ANALOG_MODE
Please add also:
```
#define STM32F2_PINMUX_FUNC_PA5_DAC_OUT2 \
	STM32_MODER_ANALOG_MODE
```

2020-08-05 07:14 UTC, ABOSTM commented on drivers/pinmux/stm32/pinmux_stm32f2.h
> +	STM32_MODER_ANALOG_MODE
Done

2020-08-05 07:16 UTC, martinjaeger approved these changes

2020-08-10 12:31 UTC, erwango approved these changes

2020-08-10 12:48 UTC, erwango commented
dac_loopback test is failed on arduino_zero which declares support for both dac and adc but which is not supported in `tests/drivers/dac/dac_loopback/src/test_dac.c`, which seems a valid case.
Adding `depends on: dac adc` is not sufficient to solve this case, but unless adding a dac_loopback as a possible `supported` value, I don't see how this could be solved.

2020-08-27 11:13 UTC, ABOSTM commented
Rebased.
@carlescufi @nashif @galak 
Could PR be merged for next release ?

2020-08-27 14:06 UTC, merged

2020-08-27 14:06 UTC, carlescufi commented
> Rebased.
> @carlescufi @nashif @galak
> Could PR be merged for next release ?

Done