shell: fix possible deadlock in shell_fprintf
zephyrproject-rtos/zephyr pull request #27342
Opened 2020-08-03 10:59 UTC by jakub-uC

Disable shell print functions if the shell is not initialized.

Fixes #27161

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordisemi.no>

2020-08-06 07:27 UTC, nordic-krch approved these changes
looks good

2020-08-18 08:33 UTC, jakub-uC commented
@Mierunski : ping

2020-08-18 09:53 UTC, Mierunski requested changes

2020-08-18 09:53 UTC, Mierunski commented on subsys/shell/shell_ops.h
> +	return shell->ctx->internal.flags.print_noinit == 1 ? true : false;
Comparison should be enough

2020-08-18 09:53 UTC, Mierunski commented on include/shell/shell_dummy.h
> + * @param shell		Shell pointer
Too many spaces

2020-08-18 10:12 UTC, jakub-uC commented on subsys/shell/shell_ops.h
> +	return shell->ctx->internal.flags.print_noinit == 1 ? true : false;
will fix it

2020-08-18 10:31 UTC, jakub-uC commented on include/shell/shell_dummy.h
> + * @param shell		Shell pointer
done

2020-08-18 10:35 UTC, Mierunski approved these changes

2020-08-18 14:44 UTC, merged