Bluetooth: Mesh: Add Option config unprov beacon interval
zephyrproject-rtos/zephyr pull request #27451
Opened 2020-08-10 02:59 UTC by LingaoM

1 Add Option to specifies the second interval when device
send Unprovisioned Beacon.

2 Move BT_MESH_LPN_SUB_ALL_NODES_ADDR to LPN subgroup.

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

2020-08-10 07:15 UTC, trond-snekvik requested changes
Just a couple of minor comments :)

2020-08-10 07:15 UTC, trond-snekvik commented on subsys/bluetooth/mesh/Kconfig
> +	int "The second interval to send the unallocated beacon"
```suggestion
	int "The second interval to send the unprovisioned beacon"
```

2020-08-10 07:15 UTC, trond-snekvik commented on subsys/bluetooth/mesh/Kconfig
> +	  This option specifies the second interval at which the
```suggestion
	  This option specifies the interval (in seconds) at which the
```

2020-08-10 07:15 UTC, trond-snekvik commented on subsys/bluetooth/mesh/Kconfig
> +config BT_MESH_UNPROV_BEACON_INVL
Interval is generally shortened to `INT`, or the full `INTERVAL` is used.

2020-08-10 07:43 UTC, trond-snekvik approved these changes

2020-08-10 09:00 UTC, joerchan commented
@LingaoM I think it would be best to have "2 Move BT_MESH_LPN_SUB_ALL_NODES_ADDR to LPN subgroup." as it's own commit.

2020-08-10 09:19 UTC, LingaoM commented
> @LingaoM It would be best to have "2 Move BT_MESH_LPN_SUB_ALL_NODES_ADDR to LPN subgroup." as it's own commit.
> 
> Can you please split it?

Done

2020-08-10 09:21 UTC, joerchan approved these changes

2020-08-10 13:35 UTC, trond-snekvik requested changes
Please fix the compilation error before merging. When kconfig dependencies are missing, the integer config entries aren't defined at all, so you'll need to replace the `IS_ENABLED(CONFIG_BT_MESH_PROV)` with an `#if`

2020-08-18 07:06 UTC, joerchan commented
@LingaoM Please check buildkite, there are compilation issues.

2020-08-18 08:43 UTC, LingaoM commented
> @LingaoM Please check buildkite, there are compilation issues.

Done

2020-08-25 13:06 UTC, jhedberg requested changes
See my inline comments.

Also, your first commit message still contains stuff about BT_MESH_LPN_SUB_ALL_ADDRS even though you moved that to the second commit.

2020-08-25 13:06 UTC, jhedberg commented on subsys/bluetooth/mesh/beacon.c
> +#if defined(CONFIG_BT_MESH_PROV)
Why is the dependency changed from BT_MESH_PB_ADV to BT_MESH_PROV?

2020-09-01 08:36 UTC, trond-snekvik approved these changes

2020-09-01 12:22 UTC, jhedberg commented
@LingaoM I pushed a third patch on top of your two patches, which eliminates a bunch of unnecessary #ifdefs from the code (in favour of using IS_ENABLED). Could you take a look and confirm that it's fine with you?

2020-09-01 15:17 UTC, LingaoM commented
> @LingaoM I pushed a third patch on top of your two patches, which eliminates a bunch of unnecessary #ifdefs from the code (in favour of using IS_ENABLED). Could you take a look and confirm that it's fine with you?

LGTM

2020-09-01 18:59 UTC, jhedberg approved these changes

2020-09-01 19:00 UTC, merged