kernel: start: relocate vector table
zephyrproject-rtos/zephyr pull request #276
Opened 2017-05-22 08:45 UTC by Likailiu

Without this vector table initiated, an system exception
will be raised under arm arch M0.

Signed-off-by: likai liu <likai.liu@linaro.org>

2017-05-22 13:46 UTC, galak requested changes
Can you explain thus further.  What exact issue are you running into?  What platform?  We have M0 running on a number of systems with any issues so curious what you are seeing.

2017-05-23 09:11 UTC, Likailiu commented
@galak An abnormal crash was encountered in our chips with zephyr OS, and the reason for this crash is that, on the arm architecture ARMV6_M, the ARMV6_M system requires an exception vector table at the 0 address. Because the relocate_vector_table function is not implemented, the exception vector table does not move to the 0 address, so the system generates an exception. 
Now the function is implemented and the exception vector table moves the 0 address with this fix.

2017-05-24 08:24 UTC, carlescufi commented
Just checked with @cvinayak and we don't think this makes sense. You cannot write to address 0, which is typically flash, with a memcpy. There must be something else here that we're missing. Can you give us additional details about the config you are running? are you executing in-place?

2017-05-24 08:26 UTC, cvinayak commented
@Likailiu Agree that vector table should  be at address 0, but thats always done by the linker in Zephyr OS for CM0. Besides, your patch with memcpy to address 0 (in flash) will not work.

2017-05-24 14:44 UTC, tyrantlizard77 reviewed
This really doesn't look right.
The vector table should be pinned at address 0 by the linker script. I don't understand why it's elsewhere in your configuration.

2017-05-25 01:03 UTC, simple2017 commented
@carlescufi @cvinayak @andrewboie Hi all,  if the address plan about flash is just as you said, there will be some problems. There is another situation, the 0 address is mapped by bootlink (SRAM) and can be written. Our implementation is the solution to this situation, and the address plan we are using can be found in the linker.cmd file. Thanks.

2017-05-25 01:19 UTC, Likailiu commented
@carlescufi @cvinayak @andrewboie Hi, all, if the address plan about flash is just as you said, there will be some problems. There is another situation, that is,  the 0 address is mapped by bootlink (SRAM) and can be written. Our implementation is the solution to this situation, and th address plan we are using can be found in the attached linker.cmd.txt. Thanks.
[linker.cmd.txt](https://github.com/zephyrproject-rtos/zephyr/files/1027689/linker.cmd.txt)

2017-06-20 06:35 UTC, closed without merging