[doc]: fix typos in variable names
zephyrproject-rtos/zephyr pull request #27751
Opened 2020-08-24 16:25 UTC by pinkit-cwa

There are no fl_sector nor fl_data_off fields in fe_entry.
Changed to fe_* instead of fl_*.

Signed-off-by: Marjan Erzen <github-cwa@pinkit.de>

2020-08-27 07:15 UTC, de-nordic commented
@pinkit-cwa  Ok, before you do anything more: Please stop opening and closing these pull requests every time you fix something. Open pull request once, for a given issue or fix,  and update branch attached to them by pushing changes to it, with force if needed.
When you close pull request and open new one just to apply changes it leaves a discussion in closed pull request and it is hard to track issues found in you solution and comments on them; you completely discard them this way.

2020-08-27 07:18 UTC, de-nordic commented
Now, if you have read my previous comment, please update commit message which should not have `[]` around `[doc]` and force push the changes to your `pinkit-cwa:patch-2` branch to update it within this PR (pull request)..

2020-09-09 08:08 UTC, pinkit-cwa commented
removed brackets in both commot message as well as pull request name

2020-09-09 09:52 UTC, de-nordic commented
@pinkit-cwa Please squash your commits to single commit. This PR is quite trivial and should consist of only one commit with proper message and changes to the file.

2020-09-09 11:28 UTC, nashif approved these changes

2020-09-09 11:29 UTC, nashif commented
> @pinkit-cwa

squash commits please.

2020-09-09 11:41 UTC, pabigot requested changes
Content is fine, commits need to be squashed.

2020-09-09 12:20 UTC, nvlsianpu reviewed
as @pabigot said.

2020-09-11 12:05 UTC, nvlsianpu commented
CI failure not related.

2020-09-11 12:06 UTC, nvlsianpu approved these changes

2020-09-11 12:13 UTC, pabigot approved these changes

2020-09-11 12:37 UTC, de-nordic approved these changes

2020-09-11 13:02 UTC, merged