sanitycheck: Allow to pass command with argument to ser_pty
zephyrproject-rtos/zephyr pull request #27968
Opened 2020-09-02 11:00 UTC by finikorg

By default, subprocess.Popen commands are supplied as a list of strings.
Using split() allows to use command with arguments, for example it is
possible to use following:

sanitycheck ... \
--device-serial-pty="set_ambient read_terminal.py" \
...

2020-09-03 08:27 UTC, finikorg commented
@nashif I see that for flash command we use split with ',', shall I use the same here? Or maybe both with re.split()

2020-09-03 22:29 UTC, nashif requested changes
This is now becoming a multipurpose, custom variable and this is not really documented... This will be confusing. Not really a fan of this.

2020-09-04 08:18 UTC, finikorg commented
> This is now becoming a multipurpose, custom variable and this is not really documented... This will be confusing. Not really a fan of this.

@nashif , this would be still script but with extra arguments. The same way as `--west-flash` is used:
https://github.com/zephyrproject-rtos/zephyr/blob/4eba946e2bb1fe97b2a9ac65c4c85400f87e226a/scripts/sanitycheck#L627-L634

I can also add "Supports comma-separated argument list."

2020-09-04 11:16 UTC, nashif commented
>  The same way as `--west-flash` is used:

this does not look like --west-flash at all.

--west-flash uses west, so you do not need to specify the script, then it take arguments that can be passed to west-flash..

In you case:

`--device-serial-pty="set_ambient read_terminal.py"`

you put the argument before the script, it is not really clear what is the script and what are the argument, in which order they appear. does read_rerminal.py support set_ambient as an argument, i.e. `read_terminal.py --set_ambient`?

2020-09-04 11:23 UTC, finikorg commented
> > The same way as `--west-flash` is used:
> 
> this does not look like --west-flash at all.
> 
> --west-flash uses west, so you do not need to specify the script, then it take arguments that can be passed to west-flash..
> 
> In you case:
> 
> `--device-serial-pty="set_ambient read_terminal.py"`
> 
> you put the argument before the script, it is not really clear what is the script and what are the argument, in which order they appear. does read_rerminal.py support set_ambient as an argument, i.e. `read_terminal.py --set_ambient`?

In this case read_terminal is an argument for set_ambient, set_ambient is just app for reading /dev/mem as a user.
More info about set_ambient here: https://github.com/zephyrproject-rtos/zephyr/pull/22724#issuecomment-627308907

2020-09-08 11:35 UTC, finikorg commented
Closing as it is already merged as a part of another PR.

2020-09-08 11:35 UTC, closed without merging