Bluetooth: Mesh: Virtual address memory leak
zephyrproject-rtos/zephyr pull request #28279
Opened 2020-09-10 13:40 UTC by trond-snekvik

Fixes a memory leak when a virtual address subscription is added for a
model that either has this VA already, or the model has no more space
for subscription addresses.

Split off from to go into 2.4 #28062.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

2020-09-10 14:17 UTC, LingaoM commented
Looks indeed is bug, but I think the same operation should be done in these places.

1 `mod_pub_va_set`
2 `mod_sub_va_overwrite`

More, if model publish first set with label uuid, and again with mod_pub_set, memory leak also will be appear. So, should check whether each place in mod->group[] is a vritual address.

2020-09-10 14:19 UTC, LingaoM requested changes
See comments in above.

2020-09-11 08:22 UTC, LingaoM approved these changes
LGTM

2020-09-12 19:48 UTC, jhedberg approved these changes

2020-09-12 19:48 UTC, merged