test: power: run test case on more platforms
zephyrproject-rtos/zephyr pull request #28293
Opened 2020-09-11 01:01 UTC by mengxianglinx

remove "platform_allow" to enable test case run on more platforms,
only qemu_extensa is excluded.

Signed-off-by: Meng xianglin <xianglinx.meng@intel.com>

2020-09-15 07:56 UTC, LeiW000 approved these changes

2020-09-16 07:57 UTC, enjiamai approved these changes

2020-09-18 13:42 UTC, nashif requested changes

2020-09-18 13:42 UTC, nashif commented on tests/subsys/power/power_mgmt/testcase.yaml
> +    platform_exclude: rv32m1_vega_ri5cy rv32m1_vega_zero_riscy litex_vexriscv
please use integration_platforms filter here with at least two qemu platforms of different arches:

```
integration_platforms:
  - qemu_x86
  - mps2_an385

```

2020-10-12 17:39 UTC, ceolin approved these changes

2020-10-13 01:55 UTC, LeiW000 commented
I guess that it can be merged now. Does anyone help on it?

2020-10-14 03:26 UTC, LeiW000 commented
@nashif , could you take look at it again? If no other comment, please merge it.

2020-10-14 17:51 UTC, dcpleung approved these changes

2020-10-27 12:41 UTC, nashif approved these changes

2020-10-27 12:41 UTC, merged