drivers: sensor: lis2mdl: Add device power management
zephyrproject-rtos/zephyr pull request #28391
Opened 2020-09-15 08:56 UTC by eHammarstrom

The power draw of this magnetometer is significant,
device power management is needed for our use-cases.

Signed-off-by: Emil Hammarstrom <emil.hammarstrom@assaabloy.com>
Change-Id: I71158e629e93b491c6d673aa81001b7a7099f654

2020-09-23 13:44 UTC, mniestroj requested changes

2020-09-23 13:44 UTC, mniestroj commented on drivers/sensor/lis2mdl/lis2mdl.c
> +		u32_t new_state)
It should be `uint32_t`, as `u32_t` is deprecated now.

2020-09-23 13:44 UTC, mniestroj commented on drivers/sensor/lis2mdl/lis2mdl.h
> +	u32_t power_state;
It should be `uint32_t`, as `u32_t` is deprecated now.

2020-09-23 13:44 UTC, mniestroj commented on drivers/sensor/lis2mdl/lis2mdl.c
> +	u32_t current_state = lis2mdl->power_state;
It should be `uint32_t`, as `u32_t` is deprecated now.

2020-09-23 13:44 UTC, mniestroj commented on drivers/sensor/lis2mdl/lis2mdl.c
> +	u32_t new_state;
It should be `uint32_t`, as `u32_t` is deprecated now.

2020-09-23 14:14 UTC, mniestroj approved these changes
LGTM

2020-10-02 07:13 UTC, pabigot approved these changes
Looks like a straightforward application of the existing idiom.

2020-10-02 09:33 UTC, merged