doc: releases: add notes on core dump for v2.4 release
zephyrproject-rtos/zephyr pull request #28447
Opened 2020-09-16 20:17 UTC by dcpleung

This adds a few lines regarding core dump in the v2.4 release
notes.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

2020-09-16 20:31 UTC, MaureenHelm requested changes

2020-09-16 20:31 UTC, MaureenHelm commented on doc/releases/release-notes-2.4.rst
> +      This allow dumping the CPU registers and memory content for offline
```suggestion
      This allows dumping the CPU registers and memory content for offline
```

2020-09-16 21:00 UTC, MaureenHelm approved these changes

2020-09-17 19:31 UTC, mbolivar-nordic approved these changes

2020-09-17 19:44 UTC, merged