drivers: net: slip: Allow slip to co-exist with other interfaces
zephyrproject-rtos/zephyr pull request #28463
Opened 2020-09-17 12:01 UTC by a8961713

This commit fixes the following issue:
When using slip without TAP, i.e. CONFIG_SLIP_TAP=n (default), while
another ethernet interface is enabled and sets CONFIG_NET_L2_ETHERNET=y.

This causes ethernet_init() to be wrongly called with struct dummy_api
instead of struct ethernet_api.
ethernet_init() expects struct ethernet_api (by cast), so we end up
with the get_capabilities field pointing to garbage!
Actually, as we are using the dummy api, we don't need to call
ethernet_init() at all.

Sole dependency on CONFIG_NET_L2_ETHERNET is wrong because it
can be enabled by another interface.

Signed-off-by: David Developer <a8961713@gmail.com>

2020-09-17 14:47 UTC, jukkar approved these changes

2020-09-17 14:57 UTC, rlubos approved these changes

2020-09-18 05:46 UTC, tbursztyka approved these changes

2020-09-18 15:02 UTC, MaureenHelm requested changes
Thank you for the fix. Will you please update your Signed-off-by to use your name instead of a pseudonym?

2020-09-21 03:54 UTC, closed without merging

2020-09-21 03:56 UTC, a8961713 commented
I am reissuing this pr because it does not let me change the signed-off name as requested