soc: nordic: Turn hardware stack protection on by default
zephyrproject-rtos/zephyr pull request #28470
Opened 2020-09-17 13:45 UTC by carlescufi

In all Nordic ICs that support hardware stack protection, turn it on by
default so that we detect stack overflows easier.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2020-09-17 13:47 UTC, joerchan approved these changes
Makes sense to me.

2020-09-17 13:55 UTC, carlescufi commented
The cost in ROM is around ~200 bytes.

2020-09-17 13:55 UTC, carlescufi commented
Proof that this would be very useful: https://github.com/zephyrproject-rtos/zephyr/issues/27768

2020-09-17 14:03 UTC, anangl approved these changes

2020-09-17 14:09 UTC, pabigot approved these changes

2020-09-17 14:12 UTC, ioannisg requested changes
Not opposing this, I think it solves many problems.

I think this should not be enabled in the SoC level because this is a "user" option (i.e. for application developers to enable certain features). Let's do this at the Board level, a common file for nRF boards.

You might need to fix some tests in the tree that expect HW_STACK_PROTECTION TO be OFF by default. Let's see how CI will run.

2020-09-17 14:16 UTC, carlescufi commented
> Not opposing this, I think it solves many problems.
> 
> I think this should not be enabled in the SoC level because this is a "user" option (i.e. for application developers to enable certain features). Let's do this at the Board level, a common file for nRF boards.

I disagree. There's no common file to all of our boards, and I don't think there should be. Whatever this common file contains it will be there because the board has a Nordic SoC on it so what is the point on having that file?

Note that `west build sample -- -DCONFIG_HW_STACK_PROTECTION=n` works just fine with this PR.

> You might need to fix some tests in the tree that expect HW_STACK_PROTECTION TO be OFF by default. Let's see how CI will run.

Those tests will probably set `CONFIG_HW_STACK_PROTECTION=n` so there will be nothing to fix hopefully.

2020-09-17 14:30 UTC, ioannisg commented
> I disagree. There's no common file to all of our boards, and I don't think there should be. Whatever this common file contains it will be there because the board has a Nordic SoC on it so what is the point on having that file?

The SoC .defconfig files serve the purpose to have default configuration for SoC related matters (capabilities, peripherals, HW configuration, etc.). HW_STACK_PROTECTION is, in fact, a "Kernel" option (allows the application developer to configure the kernel to detect supervisor thread stack overflows). It has nothing to do with SoC default configuration. Conceptually, it needs to be enabled at the Board level which is accepted as an entry point for application developer configuration.

Besides being counter-intuitive, having the option added at SoC level by default requires you to explicitly set it to `=n` at the board or project level, if you want to build without stack protection (and save ROM and RAM footprint). This is a problem. Ideally Board defconfig files should only have =y , i.e. enabling options, not disabling.

The other problem I see is that we actually enable it only for nRF platforms: This is not easily justified. This is a kernel feature - why it should be ON for nRF but OFF for all other Cortex-M vendors or for x86 and ARC? This breaks uniformity.

I guess **the best way** to address this is to enable the option at each nRF DK board, exactly as we do for ARM_MPU. And I'd say it should be enabled for the official Nordic-maintained boards only. Like this we indicate that this is a desirable feature for development on Nordic official DKs, but nothing to be done by-default for anything else.

2020-09-17 14:34 UTC, pabigot requested changes
Agree with https://github.com/zephyrproject-rtos/zephyr/pull/28470#issuecomment-694275764

2020-09-17 15:12 UTC, carlescufi commented
> The SoC .defconfig files serve the purpose to have default configuration for SoC related matters (capabilities, peripherals, HW configuration, etc.). HW_STACK_PROTECTION is, in fact, a "Kernel" option (allows the application developer to configure the kernel to detect supervisor thread stack overflows). It has nothing to do with SoC default configuration. Conceptually, it needs to be enabled at the Board level which is accepted as an entry point for application developer configuration.

Yes, I agree with this particular statement, although I have to say that we could be far more lenient with what is enabled by default in the SoC. Some other vendors are.

> Besides being counter-intuitive, having the option added at SoC level by default requires you to explicitly set it to `=n` at the board or project level, if you want to build without stack protection (and save ROM and RAM footprint). This is a problem. Ideally Board defconfig files should only have =y , i.e. enabling options, not disabling.

Well, that is exactly the point? We want to enable hardware stack protection by default unless your board or project disables it. That way we can help users not shoot themselves in the foot.
If we put this in the board configuration instead users will have to set `=n` in their `.conf` files.

> The other problem I see is that we actually enable it only for nRF platforms: This is not easily justified. This is a kernel feature - why it should be ON for nRF but OFF for all other Cortex-M vendors or for x86 and ARC? This breaks uniformity.

Well, everybody is entitled to set kernel options on or off in their SoCs honestly. But fair enough.

> I guess **the best way** to address this is to enable the option at each nRF DK board, exactly as we do for ARM_MPU. And I'd say it should be enabled for the official Nordic-maintained boards only. Like this we indicate that this is a desirable feature for development on Nordic official DKs, but nothing to be done by-default for anything else.

OK, I yield and will change this, but I still think the SoC defconfig file is a better place for this :)

2020-09-17 23:14 UTC, pabigot approved these changes
I think this is the best we can do right now, absent a clear policy and commitment to enable this feature uniformly Zephyr-wide.

2020-09-18 07:49 UTC, ioannisg commented on soc/arm/nordic_nrf/Kconfig.defconfig
> +	default ARCH_HAS_STACK_PROTECTION
Needs to be removed.

2020-09-18 09:05 UTC, ioannisg approved these changes
LGTM now.

2020-09-18 09:09 UTC, carlescufi commented
> LGTM now.

Thanks!

2020-09-18 09:09 UTC, ioannisg commented
> If we put this in the board configuration instead users will have to set =n in their .conf files.

This is correct, however, as I mentioned, the Board defconfig is accepted as a place to add generic application-related configuration:
https://docs.zephyrproject.org/latest/guides/porting/board_porting.html

> > "For consistency and to make it easier for users to build generic applications that are not board specific for your board, please follow these guidelines while porting."

2020-09-18 09:39 UTC, joerchan approved these changes

2020-09-18 09:52 UTC, anangl commented
And what about `thingy52_nrf52832`?

2020-09-18 09:55 UTC, ioannisg commented
> And what about `thingy52_nrf52832`?

Agreed, that should be an official Nordic platform, which we could also force to use HW STACK PROTECTION

2020-09-18 10:47 UTC, carlescufi commented
> And what about `thingy52_nrf52832`?

I thought about it and for some reason decided not to include it. Probably because we don't support it officially. But I will add it now.

2020-09-18 10:48 UTC, joerchan commented
@carlescufi With this approach I guess we will have to update all defconfig files in downstream as well.

2020-09-18 11:26 UTC, ioannisg commented
> @carlescufi With this approach I guess we will have to update all defconfig in our non-zephyr tree boards.

in nRF-connect-sdk?

2020-09-18 11:30 UTC, joerchan commented
> in nRF-connect-sdk?

Yes, that is what I meant.

2020-09-18 11:33 UTC, carlescufi commented
> @carlescufi With this approach I guess we will have to update all defconfig in our non-zephyr tree boards.

Yes, I will send a PR there too, thanks for reminding me!

2020-09-18 11:33 UTC, ioannisg commented
> > in nRF-connect-sdk?
> 
> Yes, that is what I meant.

Yeap, we probably need a ticket for the downstream boards, so they behave in the same way.

2020-09-18 11:44 UTC, anangl approved these changes

2020-09-18 11:48 UTC, merged

2020-09-18 14:58 UTC, erwango commented
> I think we should consider enabling it for all platforms, not just nRF. cc: @andrewboie @erwango

Sure. One question though:
Once it will be set in all boards _defconfig files, will it be `default y` at the end?

2020-09-18 14:59 UTC, ioannisg commented
It will, if the ARCH supports it.

2020-09-18 15:04 UTC, erwango commented
> It will, if the ARCH supports it.

Ok, I will work on that next week.

2020-10-02 10:30 UTC, XavierChapron commented
Can anyone describe the main differences between CONFIG_HW_STACK_PROTECTION and CONFIG_STACK_SENTINEL at least regarding NRF MCU.
Does both of them catch every stack overflow?
Is there any reason not to use the hardware version? Maybe in term of footprint, mcu usage, mcu consumption?

2020-10-02 11:38 UTC, erwango commented
> Can anyone describe the main differences between CONFIG_HW_STACK_PROTECTION and CONFIG_STACK_SENTINEL at least regarding NRF MCU.
> Does both of them catch every stack overflow?
> Is there any reason not to use the hardware version? Maybe in term of footprint, mcu usage, mcu consumption?
> Thanks!

@XavierChapron might be better to raise this question in https://github.com/zephyrproject-rtos/zephyr/pull/28710#event-3833191475

2020-10-02 11:41 UTC, erwango commented
> Can anyone describe the main differences between CONFIG_HW_STACK_PROTECTION and CONFIG_STACK_SENTINEL at least regarding NRF MCU.
> Does both of them catch every stack overflow?
> Is there any reason not to use the hardware version? Maybe in term of footprint, mcu usage, mcu consumption?
> Thanks!

@XavierChapron might be better to raise this question in https://github.com/zephyrproject-rtos/zephyr/discussions

2020-10-02 11:53 UTC, XavierChapron commented
@erwango Done https://github.com/zephyrproject-rtos/zephyr/discussions/28866