Bluetooth: L2CAP: Document behavior of alloc_buf
zephyrproject-rtos/zephyr pull request #28488
Opened 2020-09-17 20:46 UTC by Vudentz

Channel that requires segmentation must set alloc_buf in order for the
stack to be able to reassemble segments of an SDU.

If this happens at runtime warn the user and truncate the MTU to
force segmentation to be disabled.

Fixed #28384

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

2020-09-18 06:46 UTC, joerchan commented on subsys/bluetooth/host/l2cap.c
> +	/* Assert if channel have disabled segmentation but still have set an
The comment does not match the code, needs to be updated.

2020-09-21 09:07 UTC, joerchan approved these changes

2020-09-21 09:18 UTC, jhedberg requested changes
The changes look fine, but the commit message summary is rather misleading: when I read it I assume that there are only documentation changes involved, however when I look at the actual changes I see you're changing code as well. Could you change the commit message to something more accurate?

2020-09-21 09:19 UTC, jhedberg commented
..or alternatively split this into two commits: one that updates alloc_buf documentation and another which does the code change

2020-09-21 23:07 UTC, Vudentz commented
> ..or alternatively split this into two commits: one that updates alloc_buf documentation and another which does the code change

Done.

2020-09-22 07:56 UTC, jhedberg approved these changes

2020-09-22 07:56 UTC, merged