doc: release notes: Update security notes for 2.4
zephyrproject-rtos/zephyr pull request #28524
Opened 2020-09-18 22:16 UTC by ceolin

Add information about security issues addressed in the v2.4.0
release.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

2020-09-18 22:57 UTC, d3zd3z requested changes

2020-09-18 22:57 UTC, d3zd3z commented on doc/security/vulnerabilities.rst
> +  CVE-2020-13599
Extra space in front of this one.

2020-09-18 22:57 UTC, d3zd3z commented on doc/security/vulnerabilities.rst
> +______________
These should be a line of hyphens instead of underscores. All of the entries at a given level need to have the same marker, and the existing CVEs are marked with hyphens.

2020-09-21 21:10 UTC, ceolin commented on doc/security/vulnerabilities.rst
> +______________
done, would you mind review it again ?

2020-09-21 21:40 UTC, dleach02 approved these changes
lgtm

2020-09-22 16:59 UTC, d3zd3z approved these changes

2020-09-22 18:39 UTC, MaureenHelm approved these changes

2020-09-22 18:39 UTC, merged