toolchain: mwdt: add some compile options to reduce warning
zephyrproject-rtos/zephyr pull request #28531
Opened 2020-09-19 04:59 UTC by IRISZZW

When compile zephyr project with arcmwdt toolchain, there are some harmless but noisy compiling warnings,
add some compile options:
`-Wno-typedef-redefinition` 
`-Wno-duplicate-decl-specifier`
 `-Wno-incompatible-pointer-types` 
to reduce warning.

```
warning: duplicate 'inline' declaration specifier [-Wduplicate-decl-specifier]
warning: redefinition of typedef 'k_tid_t' is a C11 feature [-Wtypedef-redefinition]
......
```

2020-09-21 16:19 UTC, evgeniy-paltsev commented
Hmm, any clue about why do we need '-Wno-incompatible-pointer-types'?

2020-09-21 16:20 UTC, evgeniy-paltsev commented
BTW, your commit doesn't touch '-Wno-incompatible-pointer-types' at all.

2020-09-22 02:58 UTC, IRISZZW commented
> Hmm, any clue about why do we need '-Wno-incompatible-pointer-types'?

It might be fixed by some code changes in latest commits, I can't reproduce it, so I remove it.

2020-09-23 11:31 UTC, abrodkin requested changes
Now when there's only 1 warning being muted we may explicitly mention in in the commit title.
Also it would be really useful to have an explanation of why that redefinition happens and maybe even insert an extract from real code which requires that treatment.

2020-09-24 05:20 UTC, IRISZZW commented
> Now when there's only 1 warning being muted we may explicitly mention in in the commit title.
> Also it would be really useful to have an explanation of why that redefinition happens and maybe even insert an extract from real code which requires that treatment.

The redefinition is caused by this PR : [userspace: memory domain cleanups & arch-specific data support](https://github.com/zephyrproject-rtos/zephyr/pull/27687):

```
1 warning generated.
[106/114] Building C object zephyr/kernel/CMakeFiles/kernel.dir/idle.c.obj
In file included from zephyr/kernel/idle.c:7:
../include\kernel.h:648:26: warning: redefinition of typedef 'k_tid_t' is a C11 feature [-Wtypedef-redefinition]
typedef struct k_thread *k_tid_t;
                         ^
../include\app_memory/mem_domain.h:18:26: note: previous definition is here
typedef struct k_thread *k_tid_t;
```
https://github.com/zephyrproject-rtos/zephyr/blob/04fe7c6eeb7880d2a41d1d9d8e17a3d7d427c9ed/include/kernel.h#L648
https://github.com/zephyrproject-rtos/zephyr/blob/04fe7c6eeb7880d2a41d1d9d8e17a3d7d427c9ed/include/app_memory/mem_domain.h#L18

kernel.h include kernel_includes.h:
https://github.com/zephyrproject-rtos/zephyr/blob/04fe7c6eeb7880d2a41d1d9d8e17a3d7d427c9ed/include/kernel.h#L17
kernel_includes.h include mem_domain.h:
https://github.com/zephyrproject-rtos/zephyr/blob/04fe7c6eeb7880d2a41d1d9d8e17a3d7d427c9ed/include/kernel_includes.h#L45

Maybe we need to do some changes in codes, but it's interesting why only mwdt toolchain will treat this as redefinition warning.

2020-09-24 11:35 UTC, tejlmand commented
@andrewboie could you comment here ^^^

2020-09-24 17:45 UTC, evgeniy-paltsev commented
Is it possible that it is the same issue?
https://patchwork.kernel.org/patch/10920427/

2020-09-24 20:11 UTC, andrewboie commented
> @andrewboie could you comment here ^^^

I needed k_tid_t for that header, without pulling in the entire kernel.h to avoid circular deps. GCC was fine with this (probably because the definition is unchanged), but it seems MWDT is not.

Probably the best solution is to create a thread.h header with all the thread definitions and have both kernel.h and mem_domain.h include it

2020-09-24 23:29 UTC, evgeniy-paltsev commented
@andrewboie, thanks for explanation. It's most likely not MWDT thing but CLANG thing (MWDT is CLANG based) given that link about '-Wno-typedef-redefinition' adding in Linux kernel for CLANG.

@IRISZZW could you please update the commit message? Otherwise ACK.

2020-09-24 23:39 UTC, andrewboie approved these changes

2020-09-25 21:50 UTC, evgeniy-paltsev approved these changes

2020-10-07 13:23 UTC, tejlmand approved these changes
LGTM, but I think it would be nice to create a followup task on this:
> Probably the best solution is to create a thread.h header with all the thread definitions and have both kernel.h and mem_domain.h include it. May itself require some untangling.

so that we can re-enable this warning.
What do you think @andrewboie  ?

2020-10-19 15:16 UTC, carlescufi commented
@abrodkin could you review this again?

2020-10-19 15:39 UTC, abrodkin approved these changes

2020-10-19 19:06 UTC, merged

2020-10-20 13:17 UTC, nashif commented
attempt to fix this proper was submitted here: https://github.com/zephyrproject-rtos/zephyr/pull/29359