Bluetooth: Fix Null deref during adv data update
zephyrproject-rtos/zephyr pull request #28831
Opened 2020-10-01 06:42 UTC by J-Montgomery

Added a check for adv->lll.aux before starting extended advertising to fix observed derefs in [#28544](https://github.com/zephyrproject-rtos/zephyr/issues/28544).

Signed-off-by: Jordan Montgomery <montytyper@msn.com>

2020-10-01 07:05 UTC, cvinayak requested changes

2020-10-01 07:05 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_adv_aux.c
> +	if(adv->lll.aux && adv->is_enabled) {
```suggestion
	if (adv->is_enabled && adv->lll.aux) {
```

2020-10-01 07:05 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_adv_aux.c
> +		if (adv->is_enabled && !aux->is_started) {
```suggestion
		struct ll_adv_aux_set *aux;
		
		 aux = (void *)HDR_LLL2EVT(adv->lll.aux);
		if (!aux->is_started) {
```

2020-10-01 07:25 UTC, cvinayak commented
Also, please address the checkpatch errors too.

```
$ ./scripts/checkpatch.pl -g HEAD
```

2020-10-02 14:02 UTC, kruithofa approved these changes
LGTM

2020-10-04 12:05 UTC, pabigot approved these changes

2020-10-05 05:53 UTC, cvinayak approved these changes

2020-10-05 09:47 UTC, carlescufi approved these changes

2020-10-05 09:47 UTC, merged