boards: share the leftover mcuboot scratch flash between image 0 and image 1 for nRF devices
zephyrproject-rtos/zephyr pull request #29122
Opened 2020-10-12 11:19 UTC by nvlsianpu

Newest mcuboot uses move swap instead of scratch
for nRF devices

Share the leftover scratch flash between image 0 and image 1.
For trustzone enabled devices, give the non secure
partitions the extra space.

Adjusted test overlays to above changes.

This PR supersedes #22228 as due the push to its branch during it was closed, GH GUI disallow to reopen it.

2020-10-13 06:00 UTC, hakonfam approved these changes
Should we add comments where not all of flash is used explaining why its like that? (primary and secondary have to be the same size)

2020-10-19 16:34 UTC, carlescufi commented on boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
> +			reg = <0x0000C000 0x000076000>;
@nvlsianpu please address the comments.

2020-10-19 19:16 UTC, ioannisg requested changes
This will not really work for TrustZone-capable nRF SoCs, where the flash partitions need to align with SPU boundaries.

2020-10-20 13:34 UTC, nvlsianpu commented
>  This will not really work for TrustZone-capable nRF SoCs, where the flash partitions need to align with SPU boundaries.

Align as follow?
``` 
	default 0x8000 if SOC_NRF9160
	default 0x8000 if SOC_NRF5340_CPUAPP && NRF5340_CPUAPP_ERRATUM19
	default 0x4000 if SOC_NRF5340_CPUAPP
```

2020-11-09 12:09 UTC, nvlsianpu commented on boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
> +			reg = <0x0000C000 0x000076000>;
@mniestroj fixed

2020-11-09 12:13 UTC, nvlsianpu commented
@ioannisg I align changes to SPU boundaries. For nrf5340dk_nrf5340 applied the same alignment as for nrf5340pdk_nrf5340.

2020-11-09 12:14 UTC, mniestroj commented on boards/arm/nrf52840_blip/nrf52840_blip.dts
> +			reg = <0x0000C000 0x000076000>;
Leading 0 to be removed.

2020-11-09 12:14 UTC, mniestroj commented on boards/arm/nrf52840_mdk/nrf52840_mdk.dts
> +			reg = <0x0000C000 0x000076000>;
Leading 0 to be removed.

2020-11-09 12:14 UTC, mniestroj commented on boards/arm/nrf52840_papyr/nrf52840_papyr.dts
> +			reg = <0x0000C000 0x000076000>;
Leading 0 to be removed.

2020-11-09 12:26 UTC, nvlsianpu commented
@mniestroj fixed

2020-11-11 13:31 UTC, mniestroj approved these changes

2021-04-06 00:30 UTC, closed without merging