drivers: pwm: stm32: control update event when updating values
zephyrproject-rtos/zephyr pull request #29470
Opened 2020-10-23 09:08 UTC by gmarull

With this commit the update event is disabled prior to the update of
ARR/CCR registers so that written values are kept in the shadow
registers. Once both are updated, the update event is enabled again and
forced so that transfer of the new values occurs.

Fixes #29446

Tested using the following sample code (thanks @simonguinot):
```c
while (1) {
        pwm_pin_set_cycles(pwm, ch, 100, 0);
        k_sleep(K_MSEC(1000));
        pwm_pin_set_cycles(pwm, ch, 100, 100);                 
        k_sleep(K_MSEC(1000));
	pwm_pin_set_usec(pwm, ch, 1000000, 500000, 0);
	k_sleep(K_MSEC(5000));
	pwm_pin_set_usec(pwm, ch, 100000, 50000, 0);
	k_sleep(K_MSEC(5000));
}
```

Waveforms before fix:
![image](https://user-images.githubusercontent.com/25011557/96981115-d5cbba00-151f-11eb-9947-916fb70344be.png)

Waveforms after fix:
![image](https://user-images.githubusercontent.com/25011557/96981254-de23f500-151f-11eb-9dd3-c6eee17a8098.png)

Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>

2020-10-23 09:17 UTC, erwango commented
^^@bpbradley

2020-10-23 09:50 UTC, simonguinot approved these changes
Hi @gmarull. Many thanks for this patch. I confirm I can't reproduce the #29446 bug with it.

2020-10-23 13:27 UTC, bpbradley commented
> ^^@bpbradley

Awesome! I will check to see if this solves my issue as well next week.

2020-10-28 16:59 UTC, ABOSTM requested changes
@gmarull,
With this PR, update of period and pulse is asynchronous, meaning it is taken into account in the middle of ongoing pulse. And clearly, setting preload` LL_TIM_OC_EnablePreload(cfg->timer, channel); `doesn't make sense anymore. 
This cause an undetermined transition pulse (truncated pulse), as we can se on your plot, which is generally not want (whatever motor control, servo or even led).
This is why, generally it is advised to enable preload, so that new settings of period and pulse are taken into account at the end of the ongoing period.
So, specially for a generic framework like zephyr I would advice to enable preload, because we don't know how pwm will be used.
That said, the original error comes from the fact that ARR preload was disabled, this new ARR value was effective immediately, but potentially lower than the actual CNT value, and then counter counts till its max value 0xFFFF FFFF (depending on 16/32 bits) . This explain the long delay.
So I propose a new fix: https://github.com/zephyrproject-rtos/zephyr/pull/29619

2020-10-28 17:41 UTC, gmarull commented
Closing for #29619

2020-10-28 17:41 UTC, closed without merging