STM32: Convert I2S to devicetree pinctrl configuration
zephyrproject-rtos/zephyr pull request #29484
Opened 2020-10-23 13:12 UTC by erwango

Last STM32 driver to be converted to  device tree based pinctrl configuration

2020-10-23 13:13 UTC, erwango commented
@avisconti Mostly relying on you to test this :-)

2020-10-23 13:45 UTC, galak approved these changes

2020-10-23 13:45 UTC, galak requested changes
binding looks like its missing or got cut-off.

2020-10-23 13:45 UTC, galak commented on dts/bindings/i2s/st,stm32-i2s.yaml
> +        For example the I2S1 would be
I think you forgot something here.

2020-10-23 13:47 UTC, galak reviewed
Can you add a comment in `boards: stm32: Convert I2S users to dt based pinctrl config` as to what was going on with nucleoo_f411re (since the block removed has SPI signal names)

2020-10-23 13:52 UTC, galak approved these changes

2020-10-23 15:54 UTC, gmarull approved these changes

2020-10-27 12:32 UTC, ABOSTM approved these changes
LGTM

2020-10-28 14:29 UTC, merged