kernel: limit thread local storage to Zephyr SDK
zephyrproject-rtos/zephyr pull request #29591
Opened 2020-10-27 17:53 UTC by dcpleung

Toolchains other than Zephyr SDK may not support generating
code with thread local storage. So limit TLS to Zephyr SDK
for now, and only enable TLS on other toolchains as needed.

Fixes #29541

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

2020-10-27 17:54 UTC, galak approved these changes

2020-10-27 17:57 UTC, galak requested changes
Let's introduce this as:

```
config TOOLCHAIN_SUPPORTS_THREAD_LOCAL_STORAGE
   depends on "$(ZEPHYR_TOOLCHAIN_VARIANT)" = "zephyr"

config THREAD_LOCAL_STORAGE
   ...
   depends no ARCH_HAS_THREAD_LOCAL_STORAGE && TOOLCHAIN_SUPPORTS_THREAD_LOCAL_STORAGE

```

and

2020-10-27 18:22 UTC, dcpleung commented
Updated to add a hidden option.

2020-10-27 19:02 UTC, galak approved these changes

2020-10-27 20:58 UTC, nashif approved these changes

2020-10-28 16:18 UTC, pfalcon approved these changes

2020-10-30 14:27 UTC, tejlmand approved these changes
LLVM does seem to support this.
https://releases.llvm.org/10.0.0/docs/LangRef.html#thread-local-storage-models

but safest to limit to Zephyr SDK, until we have tested further.

2020-10-30 14:59 UTC, merged