Bluetooth: Mesh: Fix rpl clear in rx_reset
zephyrproject-rtos/zephyr pull request #29625
Opened 2020-10-29 05:43 UTC by LingaoM

RPL only be call when local node reset.

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

2020-10-29 11:36 UTC, trond-snekvik approved these changes

2020-10-29 12:05 UTC, jhedberg requested changes
The change looks good, but please provide a more complete commit message that explains what exactly was wrong and how the new place of calling the function fixes it.

2020-10-29 16:22 UTC, jhedberg approved these changes

2020-10-29 16:30 UTC, jhedberg commented
@LingaoM thanks! Since this is critical enough that we'll want to backport it to earlier releases (you might have seen the added labels) it will need to have a matching issue and a "Fixes: ..." entry for it. This would be the simplest way so we don't need to create issues for the back port PRs but just this one.

2020-10-30 10:51 UTC, LingaoM commented
@trond-snekvik Is the same problem solved in this pr #28062

2020-10-30 14:21 UTC, trond-snekvik commented
> @trond-snekvik Is the same problem solved in this pr #28062

Looks like it, yes! It wasn't really on purpose, I didn't realize until you pointed it out now, sorry. 
Unless you feel strongly about doing this in main.c instead of transport, I think we can close this. I'll create backport PRs in that case.

2020-10-30 14:31 UTC, closed without merging