doc/releases: update release note by latest MCUBoot changes
zephyrproject-rtos/zephyr pull request #29787
Opened 2020-11-04 12:31 UTC by nvlsianpu

Notes on MCUBoot changes and flash_area API extension.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2020-11-12 12:23 UTC, carlescufi requested changes

2020-11-12 12:23 UTC, carlescufi commented on doc/releases/release-notes-2.5.rst
> +  * flash_map: Added API for get the value of an erased byte in the flash_area,
```suggestion
  * flash_map: Added API to get the value of an erased byte in the flash_area,
```

2020-11-12 12:23 UTC, carlescufi commented on doc/releases/release-notes-2.5.rst
> +    application during its early ini.
```suggestion
    application during its early initialization.
```

2020-11-12 12:23 UTC, carlescufi commented on doc/releases/release-notes-2.5.rst
> +  * Clean ARM core configuration only when selected by user,
```suggestion
  * Initialize the ARM core configuration only when selected by the user,
```

2020-11-12 12:23 UTC, carlescufi commented on doc/releases/release-notes-2.5.rst
> +  * Allowed nonaligned last image data chunk in the serial-recovery protocol.
```suggestion
  * Allow the final data chunk in the image to be unaligned in the serial-recovery protocol.
```

2020-11-13 14:37 UTC, carlescufi approved these changes

2020-11-16 19:27 UTC, nashif approved these changes

2020-11-17 16:10 UTC, MaureenHelm approved these changes

2020-11-17 16:10 UTC, merged