Test: Kernel: Timing: add some description for clock and timer
zephyrproject-rtos/zephyr pull request #29912
Opened 2020-11-10 01:33 UTC by KangJianX

Add more detail description for test case to describe the test
purpose, condition, procedure etc... make test cases more clear
to understand.

Signed-off-by: Jian Kang <jianx.kang@intel.com>

2020-11-16 06:31 UTC, LeiW000 requested changes

2020-11-16 06:31 UTC, LeiW000 commented on tests/kernel/common/src/clock.c
> + *
The test procedure has to be written to describe the details. For example:
1. Start a timer with 100ms.
2. Busy wait 80ms.
3, Check if the timer has expired.

2020-11-16 06:31 UTC, LeiW000 commented on tests/kernel/timer/timer_api/src/timer_convert.c
> + * - Success if the result of convert time in the range.
"is" is missing here.
Success if the result of convert is in the range. Otherwise, it is failure.

2021-01-14 02:13 UTC, enjiamai reviewed
@KangJianX I recommend we temporary close this PR until doxygen format ensured, thanks!

2021-02-15 17:16 UTC, nashif commented
closing

2021-02-15 17:16 UTC, closed without merging