Bluetooth: Mesh: Fixes missing recv net_idx copy to context
zephyrproject-rtos/zephyr pull request #30019
Opened 2020-11-14 04:26 UTC by LingaoM

Missing copy net_idx to ctx, this cause tx subnet not found
or different with rx subnet, when rx subnet net_idx not zero.

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

2020-11-14 09:09 UTC, trond-snekvik approved these changes

2020-11-19 11:23 UTC, jhedberg requested changes

2020-11-19 11:23 UTC, jhedberg commented on subsys/bluetooth/mesh/subnet.c
> +		}
You'll need to add `__fallthrough;` after this so that it doesn't get flagged by static analysers (it's also a requirement of the coding guidelines)

2020-11-25 09:11 UTC, trond-snekvik commented
@lingaoM please see Johan's comment

2020-11-26 10:21 UTC, jhedberg approved these changes

2020-11-26 10:21 UTC, merged