usb/class/usb_dfu: give wait_for_usb_dfu an argument.
zephyrproject-rtos/zephyr pull request #30015
Opened 2020-11-14 02:59 UTC by jmgao

Allow callers to wait for an arbitrary amount of time, instead of always
waiting for a compile-time fixed period.

Signed-off-by: Josh Gao <josh@jmgao.dev>

2020-11-14 03:00 UTC, jmgao commented
This is a minor change that's a dependency of https://github.com/mcu-tools/mcuboot/pull/882.
Should this leave the existing API alone and add another _with_timeout version? The call in mcuboot is probably the only existing call to this function.

2020-11-14 12:11 UTC, carlescufi requested changes

2020-11-14 12:11 UTC, carlescufi commented on subsys/usb/class/usb_dfu.c
> +		time < (delay_ms/INTERMITTENT_CHECK_DELAY);
If you introduce a runtime parameter then you should remove the Kconfig option

2020-11-16 10:10 UTC, jfischer-no requested changes
It is a change to the public API, can you please add a note about in the _API Changes_ chapter of _doc/releases/release-notes-2.5.rst_?

Also please change the commit title to "usb: dfu: give wait_for_usb_dfu an argument"

2020-11-17 19:02 UTC, carlescufi approved these changes
LGTM, thank you.

2020-11-18 11:47 UTC, jfischer-no approved these changes

2020-11-18 16:06 UTC, de-nordic commented
I have DNMed it because this should go in pair with mcuboot and west.yaml update, otherwise we will have non-buildable mcuboot.

2021-03-12 09:16 UTC, jmgao commented
Rebased onto tip of tree.

2021-03-22 08:25 UTC, nvlsianpu reviewed
Please align usage of changed API: 
zephyrproject/zephyr/subsys/usb/class/dfu/usb_dfu.c

2021-03-22 08:25 UTC, nvlsianpu requested changes
^^

2021-03-22 09:18 UTC, jmgao commented
> Please align usage of changed API:
> zephyrproject/zephyr/subsys/usb/class/dfu/usb_dfu.c

Sorry, what do you mean by that?

2021-03-22 10:16 UTC, nvlsianpu commented
@jmgao ^^ I missed the path (form greped files).

2021-03-22 10:25 UTC, nvlsianpu approved these changes

2021-03-22 10:30 UTC, nvlsianpu commented
Need to update zephyr-rtos/mcuboot. I can the open PR which tip you will can referee.

2021-03-22 10:55 UTC, nvlsianpu commented
@jmgao  https://github.com/zephyrproject-rtos/mcuboot/pull/47 please reference `pull/47/head` for mcuboot/.

2021-03-22 11:01 UTC, de-nordic approved these changes

2021-03-22 11:55 UTC, merged