samples+tests: add CBPRINTF_FP_SUPPORT to samples/tests/features that require FP formatting
zephyrproject-rtos/zephyr pull request #30058
Opened 2020-11-16 15:14 UTC by pabigot

Multiple tests include *printf formatting specifications for floating point output.  To make sure they work with minimal libc add support for formatting floating point to the corresponding `prj.conf` files.

Also the shell sensor module selects this functionality.

    git grep -E '%[-0-9# ]*(\.[0-9]*)?[fgeFGE]'

2020-11-16 15:14 UTC, jhedberg approved these changes

2020-11-16 15:26 UTC, aescolar submitted a review, later dismissed
A false positive there

2020-11-16 15:26 UTC, aescolar commented on tests/boards/native_posix/rtc/prj.conf
> +CONFIG_CBPRINTF_FP_SUPPORT=y
False positive (`posix_print_trace()` uses the host libC `printf`)

2020-11-16 16:11 UTC, avisconti commented
@pabigot 
Sorry, I was commenting on my commit.
Here seems that following configuration files are missing, because the name is shub.conf, and not prj.conf. Is there any requirement on the name?

  samples/shields/x_nucleo_iks01a3/sensorhub/shub.conf
  samples/shields/x_nucleo_iks02a1/sensorhub/shub.conf

2020-11-16 16:14 UTC, avisconti requested changes
Two cases are missing:

samples/shields/x_nucleo_iks01a3/sensorhub/shub.conf
samples/shields/x_nucleo_iks02a1/sensorhub/shub.conf

2020-11-16 16:32 UTC, pabigot commented
> @pabigot
> Sorry, I was commenting on my commit.
> Here seems that following configuration files are missing, because the name is shub.conf, and not prj.conf. Is there any requirement on the name?

Well, anybody maintaining samples is going to assume `prj.conf` is the one to use.  Overlay configurations are normally used to augment, rather than replace, that core configuration file.   I recommend changing that if possible.

I'll update this to do it in the `shub.conf` files after I see how CI goes.

2020-11-16 17:01 UTC, avisconti commented
> I recommend changing that if possible.

I'll do that in the next days

2020-11-16 17:19 UTC, pabigot commented
@aescolar @avisconti updated per your requests.  Previous run passed all tests.

2020-11-17 08:15 UTC, aescolar commented
> @aescolar @avisconti updated per your requests. Previous run passed all tests.

@pabigot Thanks. I leave it as a +0 to allow the respective codeowners to take a look

2020-11-17 08:44 UTC, jukkar approved these changes
+1 to net changes

2020-11-17 09:25 UTC, avisconti approved these changes
LGTM now

2020-11-17 14:53 UTC, MaureenHelm approved these changes

2020-11-17 20:45 UTC, merged