Bluetooth: controller: Fix ull_conn LSTO for must_expire and random force on lost anchor configurable
zephyrproject-rtos/zephyr pull request #30132
Opened 2020-11-19 09:52 UTC by mtpr-ot

When CONFIG_BT_CTLR_CONN_META is enabled and the ticker "must_expire"
feature is used, collisions may cause incorrect decrement of the
supervision_expire counter, resulting in a too early link supervision
timeout.

Legacy functionality in ull_conn will force scheduling of a connection
which has missed an anchor point due to lost RX. This kicks in either
for previously skipped events (latenzy_event != 0) or at random
depending on the randomness of the AA bit pattern.
    
This behavior is good at ensuring that a connection with errors or
aborted RX get up-prioitized, but it breaks the predictability of the
round-robin ticker scheduling.
    
With "must_expire" enabled, this feature also kicks in for collisions,
which may not be desirable.
    
This commit adds a configuration flag, BT_CTLR_CONN_RANDOM_FORCE, which
is default enabled (legacy behavior).

2020-11-20 11:55 UTC, mtpr-ot commented
Can't seem to get CI passing - looks unrelated.

2020-11-21 01:33 UTC, cvinayak requested changes
Separate into two different PRs, so that I can approve the Random Forced scheduling Kconfig.

Regarding is_must_expire, please add a simple upstream test to cover it, so that any future upstream regressions get caught of the features that not enabled by default in upstream samples.

2020-11-21 01:33 UTC, cvinayak commented on subsys/bluetooth/controller/Kconfig
> +	bool "Enable random forced sceduling for peripheral on missed anchor point"
```suggestion
	bool "Random forced scheduling for peripheral on missed anchor point"
```

2020-11-21 01:33 UTC, cvinayak commented on subsys/bluetooth/controller/Kconfig
> +	  scheduling for peripheral.
```suggestion
	  When enabled, controller will have legacy behavior and randomly force
	  priority at next ticker scheduling for peripheral role, if anchor point is
	  missed.
	  Two are more connections with similar interval on a device connected
	  to a peer device having two or more connections at its end with same
	  interval could lock to a round robin pattern where in neither of the central
	  nor peripheral event would be in sync at either end. Randomness allows
	  to break this locked round robin pattern permitting an anchor point sync.
```

2020-11-22 21:48 UTC, mtpr-ot commented on subsys/bluetooth/controller/Kconfig
> +	  scheduling for peripheral.
Split into two PRs

2020-11-23 09:55 UTC, cvinayak approved these changes

2020-11-23 14:28 UTC, kruithofa approved these changes

2020-11-23 21:07 UTC, mtpr-ot commented
> Separate into two different PRs, so that I can approve the Random Forced scheduling Kconfig.
> 
> Regarding is_must_expire, please add a simple upstream test to cover it, so that any future upstream regressions get caught of the features that not enabled by default in upstream samples.

Can this be a part of a later PR? I need to figure out how to create a test running on upstream code, without support for the "must_expire" feature in Nordic ULL. Ant ideas?

2020-12-07 12:36 UTC, merged