sanitycheck: fix FileNotFoundError
zephyrproject-rtos/zephyr pull request #30277
Opened 2020-11-27 08:36 UTC by wangnuannuan

When platform is nsim_hs_smp, if testcase timeout, the sanitycheck may not be able to find mdb.pid

https://github.com/zephyrproject-rtos/zephyr/issues/30276

Signed-off-by: Jingru Wang <jingru@synopsys.com>

2020-11-27 12:03 UTC, nashif commented on scripts/sanity_chk/sanitylib.py
> +            if os.path.exists(self.pid_fn):
put both in one single if statement.

2020-11-28 12:22 UTC, nashif approved these changes

2020-11-30 07:29 UTC, abrodkin requested changes
First of all it looks like it might be at attempt to fix the same problem as here https://github.com/zephyrproject-rtos/zephyr/pull/30301. And from @evgeniy-paltsev explanation I'd say it's quite a reverse situation: not test time-outs and then we cannot find a PID of some process, but we execute a test that fast that child process' PID is no longer available.

Anyways that kind of justification makes IMHO no sense:
> if testcase timeout, the sanitycheck may not be able to find mdb.pid

What we want to see is analysis of what was wrong in the first place and only then suggest a fix for the real root cause. Otherwise we're trying to cure a symptom which most probably will hide the real problem deeper and it will inevitably hit us later but at a larger scale.

2021-02-02 13:39 UTC, nashif commented
stale

2021-02-02 13:39 UTC, closed without merging