arch: arm: aarch32:cortex_m: timing.c: cortex M7 may need DWT unlock
zephyrproject-rtos/zephyr pull request #30327
Opened 2020-11-30 15:40 UTC by ABOSTM

arch: arm: aarch32:cortex_m: timing.c: cortex M7 may need DWT unlock

On Cortex M7, we need to check the optional presence of
Lock Access Register (LAR) which is indicated in
Lock Status Register (LSR).
When present, a special access token must be written to unlock DWT
registers.

Fixes #30322

2020-12-01 09:42 UTC, erwango requested changes

2020-12-01 09:42 UTC, erwango commented on arch/arm/core/aarch32/cortex_m/timing.c
> +/* Define DWT LSR masks which are currentuly not defined by the CMSIS V5.1.2.
```suggestion
/* Define DWT LSR masks which are currently not defined by the CMSIS V5.1.2.
```

2020-12-01 09:42 UTC, erwango commented on arch/arm/core/aarch32/cortex_m/timing.c
> +#else /* __CORTEX_M */
```suggestion
#else /* CONFIG_CPU_CORTEX_M7 */
```

2020-12-01 09:42 UTC, erwango commented on arch/arm/core/aarch32/cortex_m/timing.c
> +#endif /* __CORTEX_M */
```suggestion
#endif /* CONFIG_CPU_CORTEX_M7 */
```

2020-12-01 09:42 UTC, erwango commented on arch/arm/core/aarch32/cortex_m/timing.c
> +	UNUSED(ena);
```suggestion
	ARG_UNUSED(ena);
```

2020-12-01 10:03 UTC, ABOSTM commented on arch/arm/core/aarch32/cortex_m/timing.c
> +/* Define DWT LSR masks which are currentuly not defined by the CMSIS V5.1.2.
Done

2020-12-01 10:03 UTC, ABOSTM commented on arch/arm/core/aarch32/cortex_m/timing.c
> +#else /* __CORTEX_M */
Done

2020-12-01 10:03 UTC, ABOSTM commented on arch/arm/core/aarch32/cortex_m/timing.c
> +#endif /* __CORTEX_M */
Done

2020-12-01 10:04 UTC, ABOSTM commented on arch/arm/core/aarch32/cortex_m/timing.c
> +	UNUSED(ena);
Done

2020-12-01 10:06 UTC, ABOSTM commented
This patch is inspired from Arduino code (Copyright STMicroelectronics) with BSD-3-Clause license, compatible with Apache License.
https://github.com/stm32duino/Arduino_Core_STM32/blob/5f95b95cd5c8f7673886ca0d243684421f4595b8/libraries/SrcWrapper/src/stm32/dwt.c#L54

2020-12-01 13:23 UTC, erwango approved these changes

2020-12-01 23:01 UTC, nashif approved these changes

2020-12-02 08:57 UTC, ioannisg approved these changes
Looks ok to me, thanks @ABOSTM 

Interesting that LSR seems to only be implemented, optionally, in CM7, while LSR register is available in all other core variant implementations.

2020-12-02 08:58 UTC, merged