doc: add interrupt implementation details
zephyrproject-rtos/zephyr pull request #304
Opened 2017-05-24 21:30 UTC by andrewboie

Issue: ZEP-634
Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

2017-05-26 23:17 UTC, nashif approved these changes

2017-05-27 14:00 UTC, nashif requested changes

2017-05-27 14:00 UTC, nashif commented on doc/kernel/other/interrupts.rst
> +arches do not support the notion of interrupt priority, in which case the
architectures

2017-05-27 14:00 UTC, nashif commented on doc/kernel/other/interrupts.rst
> +Whether to generate this depends on whether CONFIG_GEN_IRQ_VECTOR_TABLE is
Whether to generate the vector table ...

2017-05-27 14:00 UTC, nashif commented on doc/kernel/other/interrupts.rst
> +x86 has a special type of vector table called the Interrupt Descriptor Table
The X86 architecture has a special ....

2017-05-28 16:40 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +be covered in its own section.
how about:
```
    which are covered in the `x86 Details`_ section below.
```

2017-05-28 16:43 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +This is then used by the gen_isr_tables.py script to
Say what "this" is.  Are you referring to zephyr_prebuild.elf?

2017-05-28 16:46 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +generate a vector table and/or a software ISR table. This is produced as a C
generate a C file defining a vector table and software ISR table that are then compiled and linked into the final application.

2017-05-29 16:03 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +Whether to generate this depends on whether CONFIG_GEN_IRQ_VECTOR_TABLE is
How about:
```
A vector table is generated when CONFIG_GEN_IRQ_VECTOR_TABLE is enabled.
```

2017-05-29 16:09 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +enabled. This is simply an array of function pointers, where each element
A vector table is simply an array of function pointers, where each element **n** corresponds to the IRQ handler for IRQ line **n**, and the function pointers are:

2017-05-29 16:10 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +Some architectures (like Nios II internal interrupt controller) have a common
s/like/such as/

2017-05-29 16:14 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +this option should be disabled.
the CONFIG_GEN_IRQ_VECTOR_TABLE option should be disabled.

2017-05-29 16:17 UTC, dbkinder requested changes
some clarification changes

2017-06-06 21:03 UTC, nashif submitted a review, later dismissed

2017-06-06 22:30 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +details laid out here apply to all architectures except x86, which which are
delete the extra "which"

2017-06-06 22:36 UTC, dbkinder commented on doc/kernel/other/interrupts.rst
> +   spurious IRQ handler, which causes a system fatal error if encountered.
after "which causes a system fatal error if encoungered" add ", will be placed here."

2017-06-06 22:37 UTC, dbkinder requested changes
a few (final) suggestions

2017-06-07 00:50 UTC, andrewboie commented
updated

2017-06-07 02:23 UTC, merged