Bluetooth: Mesh: Fix friendship counter increasing order
zephyrproject-rtos/zephyr pull request #30622
Opened 2020-12-11 06:18 UTC by LingaoM

For Bluetooth Mesh, counter shall be increasing by one when
every try to establishing friendship.

Counter to be used when create friendship security material.
So this value shall be consist between friend and lpn.

Due to zephyr bluetooth mesh send previous counter, after that
it will automatically increase one, which will result in the
incorrect generation of friend key when key rephase.

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

2020-12-11 16:47 UTC, trond-snekvik commented
Is this related to #30240?

2020-12-12 09:54 UTC, LingaoM commented
> Is this related to #30240?

Yes, looks like missing this.

2020-12-15 19:02 UTC, michal-narajowski approved these changes

2021-01-04 12:02 UTC, trond-snekvik requested changes

2021-01-04 12:02 UTC, trond-snekvik commented on subsys/bluetooth/mesh/friend.c
> -
Perhaps add a comment here explaining why we're not following spec and increasing the friend counter? In the added location, git blame can explain it, but here, it'll look like a bug.

2021-01-05 02:27 UTC, LingaoM commented on subsys/bluetooth/mesh/lpn.c
> +
First, `lpn->lpn_counter++` is operated before sending `friend_request`, so LPN and friend should be the same value, so there is no problem.

In addition, When we don't set up friendship, LPN does not call `clear_friendship`.  if we only put `lpn->lpn_counter++` here, can we send `friend_request` every time use the same `lpn->lpn_counter` ?  it's obviously against the rules.

2021-01-05 02:39 UTC, LingaoM commented on subsys/bluetooth/mesh/lpn.c
> +
The reason for doing this in friend is that friend calls `clear_friendship `when it does not establish `friendship`.

2021-01-05 13:56 UTC, trond-snekvik commented on subsys/bluetooth/mesh/lpn.c
> +
> `lpn->lpn_counter++` is operated before sending `friend_request`, so LPN and friend should be the same value, so there is no problem.

This is not according to spec though, and it's a different solution than friend for the same problem.

> When we don't set up friendship, LPN does not call `clear_friendship`. if we only put `lpn->lpn_counter++` here, can we send `friend_request` every time use the same `lpn->lpn_counter`? it's obviously against the rules.

There's also a counter++ here that should take care of this: https://github.com/zephyrproject-rtos/zephyr/blob/5c7151b02c5567d3897ef28145a27f1dac3612b5/subsys/bluetooth/mesh/lpn.c#L792-L801

2021-01-11 08:38 UTC, trond-snekvik commented on subsys/bluetooth/mesh/lpn.c
> +
@LingaoM any comment?

2021-01-11 09:17 UTC, LingaoM commented on subsys/bluetooth/mesh/lpn.c
> +
Deleted.

2021-01-11 12:10 UTC, trond-snekvik approved these changes
This appears to work as expected, but we're essentially swapping the approaches for the two roles. Why not use the same approach in both? I.e. either performing the increment when the friendship ends in both or performing it before sending the first message for both.

2021-01-15 16:36 UTC, merged