tests: ringbuffer: code coverage develops
zephyrproject-rtos/zephyr pull request #30975
Opened 2020-12-23 02:58 UTC by Zhaoningx

Add some testcase to develop the source code
coverage, and add a ASSERT handler function
to handle the error expected, make it passed.

Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

2020-12-23 05:48 UTC, LeiW000 requested changes
By the way, for title of the PR, it better to change it like "tests: ringbuffer: code coverage improvements"

2020-12-23 05:48 UTC, LeiW000 commented on tests/lib/ringbuffer/ringbuffer_error_case/src/main.c
> + * Copyright (c) 2016 Intel Corporation
It should be "2020", rather than "2016".

2020-12-23 05:48 UTC, LeiW000 commented on tests/lib/ringbuffer/ringbuffer_error_case/src/main.c
> +	printk("Caught assert failed\n");
I think we can remove this line.

2020-12-23 05:48 UTC, LeiW000 commented on tests/lib/ringbuffer/ringbuffer_error_case/src/main.c
> + * normally, and meanwhile, develop our source code's
It better to replace "develop" with "improve".

2020-12-24 01:56 UTC, Zhaoningx commented
Hi @LeiW000 , I have updated. Could you take a look at this again, thanks.

2020-12-24 02:01 UTC, enjiamai commented on tests/lib/ringbuffer/ringbuffer_error_case/Kconfig
> +# Copyright (c) 2020 Nordic Semiconductor ASA
It should be "Intel Corporation", not "Nordic Semiconductor ASA".

2020-12-24 02:10 UTC, enjiamai commented on tests/lib/ringbuffer/ringbuffer_error_case/prj.conf
> +CONFIG_IRQ_OFFLOAD=y
I don't think we need this.

2020-12-24 02:29 UTC, enjiamai requested changes
Please see the comment, thanks.

2020-12-24 08:52 UTC, Zhaoningx commented
Hi @enjiamai , I have improved the PR, thanks for your comments.:)

2020-12-25 01:23 UTC, enjiamai approved these changes

2020-12-27 11:17 UTC, LeiW000 commented
I still see below in the commit log. Please change it with "code coverage improvements".

tests: ringbuffer: code coverage develops

2020-12-28 02:25 UTC, Zhaoningx commented
> I still see below in the commit log. Please change it with "code coverage improvements".
> 
> tests: ringbuffer: code coverage develops

Hi @LeiW000 , I'm sorry, I forgot this point, and I have updated this.

2020-12-28 09:01 UTC, LeiW000 approved these changes

2021-01-07 02:39 UTC, LeiW000 commented
@andrewboie , could you help to merge it? It already got 2 approvals. The code change is straight-forward.

2021-01-14 02:21 UTC, enjiamai requested changes
1. The common fatal and assert handler has been merged, could you please leverage them instead?
2. And let's remove error test case which trigger assertion which passing NULL directly, but keep others which will trigger Z_OOPS() from userspace.  
please refer to https://github.com/zephyrproject-rtos/zephyr/pull/30150
Thanks!

2021-01-14 07:40 UTC, Zhaoningx commented
Hi @enjiamai @LeiW000 , we needn't to cover ASSERT and __week function, so I deleted my code and just add double macros to filter the __week function, and now coverage is line:100% function:100% branches:100%

2021-01-14 13:55 UTC, enjiamai approved these changes

2021-01-15 04:08 UTC, LeiW000 commented
@nashif , I think the PR is OK for merging.

2021-01-18 03:06 UTC, Zhaoningx commented
Hi @nashif @andrewboie , the PR has got two approvals, so could you take a look at this, thanks.

2021-01-19 04:12 UTC, nashif approved these changes

2021-01-19 04:12 UTC, merged