Bluetooth: Mesh: Add a send callback mechanism for proxy
zephyrproject-rtos/zephyr pull request #31038
Opened 2020-12-29 07:50 UTC by LingaoM

Zephyr Bluetooth Mesh did not check whether the proxy message
was actually sent out, so that the response message could
not be received during reset. Although @trond tried to fix
this problem in PR(#26668), it did not solve the status
callback of the proxy sending message, so a new problem was
introduced after PR(#28457) merged.

`bt_mesh_prov_send(&buf, public_key_sent))`

This PR will try to solve the above problem, and will fix
the problem due to thread competition, and PR(26668) will
not be necessary.

Fixes: #31019

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

2021-01-04 14:13 UTC, trond-snekvik requested changes
Conceptually, this makes sense to me, but it is very close to the `bt_mesh_adv` structure in adv.h, which is also pooled. I think this should replace the pool from the adv.c file, so that we can reuse it without duplicating the memory. This would also allow us to set a flag for each bearer, so we don't call the callback until all bearers have sent the message, even for group addresses. The pool size might have to increase for this?

2021-01-04 14:47 UTC, LingaoM commented
> Conceptually, this makes sense to me, but it is very close to the `bt_mesh_adv` structure in adv.h, which is also pooled. I think this should replace the pool from the adv.c file, so that we can reuse it without duplicating the memory. This would also allow us to set a flag for each bearer, so we don't call the callback until all bearers have sent the message, even for group addresses. The pool size might have to increase for this?
> 
> 
> 
> 

In fact, I also used this method initially, considering that provisioning over gatt does not occupy the buffer of adv?

2021-01-04 15:02 UTC, trond-snekvik commented
Yes, but you'll have the advertiser with its buffer anyway, so it wouldn't cause any additional resource usage, right?

2021-01-04 15:14 UTC, LingaoM commented
Yes, the resource is always there. During the provisioning over gatt procedures, a resource is allocated from the adv buffer, but it is only used for callback, to me, it's kind of weird😅.

2021-02-26 02:36 UTC, LingaoM commented
Close this, please move to https://github.com/zephyrproject-rtos/zephyr/pull/32666.

2021-02-26 02:36 UTC, closed without merging