Added support to return data via ztest mock
zephyrproject-rtos/zephyr pull request #31057
Opened 2020-12-30 16:35 UTC by vanwinkeljan

Added support to the ztest mock framework to return for pointer parameters of functions.

2021-01-30 13:16 UTC, nashif commented
need a test for this.

2021-02-02 13:05 UTC, LeiW000 requested changes

2021-02-02 13:05 UTC, LeiW000 commented on subsys/testsuite/ztest/include/ztest_mock.h
> + * @brief Copy the data set by ztest_return_data to the data pointed by
It better to change it like below.

"the memory pointed by......"

2021-02-08 02:38 UTC, LeiW000 approved these changes

2021-03-09 12:09 UTC, nashif approved these changes

2021-03-09 12:09 UTC, merged