Kernel: poll: code coverage improvements
zephyrproject-rtos/zephyr pull request #31209
Opened 2021-01-11 05:24 UTC by Zhaoningx

Add some testcases to test some unnormal branches,
for covering branches that not covered.

Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

2021-01-14 02:18 UTC, enjiamai requested changes
1. The common fatal and assert handler has been merged, could you please leverage them instead?
2. And let's remove error test case which trigger assertion which passing NULL directly, but keep others which will trigger Z_OOPS() from userspace.  
please refer to https://github.com/zephyrproject-rtos/zephyr/pull/30150
Thanks!

2021-01-14 08:22 UTC, LeiW000 requested changes
Please address Enjia's comments.

2021-01-15 05:38 UTC, Zhaoningx commented
Hi @LeiW000 , I have finished changing my code, and could you take a look at this PR, thanks.

2021-01-15 07:17 UTC, LeiW000 approved these changes

2021-01-15 07:30 UTC, enjiamai approved these changes

2021-02-28 21:16 UTC, andyross approved these changes

2021-03-01 21:45 UTC, merged