boards: arm: Add support for Actinius Icarus Bee and SoM (nRF9160)
zephyrproject-rtos/zephyr pull request #31275
Opened 2021-01-13 00:51 UTC by alextsam

This PR adds support for 2 new boards based on the nRF9160.

These two board definitions are largely similar and they are derived from the boards/arm/actinius_icarus board

Signed-off-by: Alex Tsamakos <alex@actinius.com>

2021-02-08 14:26 UTC, alextsam commented
@MaureenHelm @galak @nordic-krch @jakub-uC @nashif Could you please let me know if there is something I could do to get this merged soon? Thanks a lot in advance!

2021-02-08 21:30 UTC, MaureenHelm commented
> @MaureenHelm @galak @nordic-krch @jakub-uC @nashif Could you please let me know if there is something I could do to get this merged soon? Thanks a lot in advance!

@alextsam, the merge window is currently closed to new features until the v2.5.0 release is complete, which is scheduled for 12 Feb. We'll have some more bandwidth to review this after that.

2021-02-08 23:39 UTC, alextsam commented
> > @MaureenHelm @galak @nordic-krch @jakub-uC @nashif Could you please let me know if there is something I could do to get this merged soon? Thanks a lot in advance!
> 
> @alextsam, the merge window is currently closed to new features until the v2.5.0 release is complete, which is scheduled for 12 Feb. We'll have some more bandwidth to review this after that.

@MaureenHelm Ah I was not aware of the feature window, thank you so much for the information!

2021-02-09 15:57 UTC, MaureenHelm commented
> @MaureenHelm Ah I was not aware of the feature window, thank you so much for the information!

This gets announced on the [mailing lists](https://lists.zephyrproject.org/g/main/subgroups). I recommend subscribing to devel or announcements to receive future updates.

2021-02-17 22:26 UTC, MaureenHelm approved these changes

2021-04-19 12:02 UTC, alextsam commented
Could you please remove the stale label? Thank you!

2021-04-30 08:11 UTC, ioannisg commented
will take a look

2021-05-04 13:23 UTC, ioannisg approved these changes
Fine with me. @alextsam you might want to align this with the latest version of nrf1960dk_nrf9160 board definition, but that's not mandatory.

2021-05-04 13:23 UTC, ioannisg commented
I would also like @anangl to take a quick look.

2021-05-04 13:53 UTC, alextsam commented
> Fine with me. @alextsam you might want to align this with the latest version of nrf1960dk_nrf9160 board definition, but that's not mandatory.

Please DNM just yet, I will align with the latest changes of the nrf9160dk_nrf9160 today 
Thank you @ioannisg

2021-05-05 14:48 UTC, anangl commented on boards/arm/actinius_icarus_bee/actinius_icarus_bee_common.dts
> +};
Why enable these HW instances without assigning any pins to them? The PWM driver will consume (when enabled in Kconfig) some RAM and flash for data structures related to those (not much but still), but they will not be very useful (`pwm_pin_set_*` functions will fail for them, regardless of the supplied `pwm` parameter).

2021-05-05 15:20 UTC, ioannisg requested changes
nacking temporarily, until the changes are applied

2021-05-05 18:50 UTC, galak commented
@alextsam any updates here.  Code freeze for getting this in is on Friday May 7th.

2021-05-06 08:09 UTC, anangl approved these changes

2021-05-06 08:14 UTC, alextsam commented
Thank you for your patience, should be good to go now!

2021-05-06 13:00 UTC, ioannisg approved these changes

2021-05-06 13:03 UTC, merged