NUCLEO-F303RE add USART1
zephyrproject-rtos/zephyr pull request #31381
Opened 2021-01-17 20:46 UTC by Nukersson

Add USART1 to the board.

2021-01-18 08:22 UTC, erwango approved these changes

2021-01-20 08:51 UTC, erwango requested changes
This is the CAN commit, we need the USART commit here

2021-01-20 20:11 UTC, Nukersson commented
> This is the CAN commit, we need the USART commit here

Sorry. It's done now.

2021-01-21 10:33 UTC, erwango approved these changes

2021-01-21 20:27 UTC, MaureenHelm approved these changes

2021-01-21 20:27 UTC, merged