doc: ARC: add info page with Zephyr support status on ARC
zephyrproject-rtos/zephyr pull request #31492
Opened 2021-01-21 17:50 UTC by evgeniy-paltsev

As of today, Zephyr misses any kind of info page with overall support status of ARC processors, their HW features and SW tools.

Fix that.

2021-01-21 19:12 UTC, abrodkin approved these changes

2021-01-21 19:34 UTC, nashif approved these changes

2021-01-22 07:04 UTC, IRISZZW approved these changes

2021-01-22 08:35 UTC, ruuddw requested changes
Please update the DSP part, for the rest it looks fine and matches current status afaik.

2021-01-22 08:35 UTC, ruuddw commented on doc/guides/arch/arc-support-status.rst
> +| DSP extension                                                       | N [#f3]_   | N [#f3]_    | TBD    | TBD      |
Can you split this into 1) DSP ISA, and 2) DSP AGU/XY?
E.g. EM5D/7D are fully supported (accumulator save/restore), the 'N' in the table is confusing as it only applies to the AGU/XY single task restriction (maybe some lazy context switching like for FPU could be an option).

2021-01-27 16:38 UTC, ruuddw approved these changes
thanks for the update for DSP, looks good now.

2021-01-27 16:45 UTC, merged