RFC: dts: bindings: pwm-controller: add channel child binding
zephyrproject-rtos/zephyr pull request #31698
Opened 2021-01-27 10:21 UTC by alexanderwachter

This commit adds channel child-bindings to the pwm controller binding.
With those bindings, a user can add channels to a pwm node that generate
the channel-number and flags. The pwm device can be obtained from
the parent node.

2021-01-27 10:26 UTC, alexanderwachter commented
Example Usage:
```
&timers2 {
	status = "okay";
	pwm {
		status = "okay";
		pinctrl-0 = <&tim2_ch1_pa0>;
		#address-cells = <1>;
		#size-cells = <0>;
		pwm_out: ch@1 {
			reg = <1>;
			flags = <PWM_POLARITY_NORMAL>;
		};
	};
};
```

```C
#define DT_PWMS_CHILD_CHANNEL(node_id) DT_PROP(node_id, reg)
#define DT_PWMS_CHANNEL_FLAGS(node_id) DT_PROP(node_id, flags)
#define DT_PWMS_CHANNEL_CONTROLLER_LABEL(node_id) DT_LABEL(DT_PARENT(node_id))

#define SYNCH_PWM_CHANNEL DT_PWMS_CHILD_CHANNEL(DT_NODELABEL(pwm_out))
#define SYNCH_PWM_LABEL   DT_PWMS_CHANNEL_CONTROLLER_LABEL(DT_NODELABEL(pwm_out))
#define SYNCH_PWM_FLAGS   DT_PWMS_CHANNEL_FLAGS(DT_NODELABEL(pwm_out))

static void en_pwm(void)
{
	const struct device *pwm_dev = device_get_binding(SYNCH_PWM_LABEL);
	if (pwm_dev) {
		int ret = pwm_pin_set_usec(pwm_dev, SYNCH_PWM_CHANNEL, 1000000U, 1000000U / 10U, SYNCH_PWM_FLAGS);
		LOG_ERR("Failed to set pulse [%d]", ret);
	}
}
```

2021-01-27 10:27 UTC, alexanderwachter commented
ping @martinjaeger @henrikbrixandersen @pabigot

2021-01-27 12:26 UTC, henrikbrixandersen requested changes
As we already discussed on Slack, I do not believe this is the right approach. All other clients/users in DTS (GPIO, I/O channels, ...) use the phandle-array approach like PWM does. 

A PWM channel is not just a PWM channel (similar as to a GPIO not just being a GPIO). It has a hardware function (e.g. a LED, a charge pump, ...) which should be described in DTS.

What you are suggesting can already be accomplished on an application level using a `zephyr,user` node with a `pwms` property. 

NACK from me.

2021-01-27 12:41 UTC, alexanderwachter commented
I don't want to replace the phandle. It is an addition that is not in conflict with the existing.
Let the user decide whats best for his application. For me it is really a pain to add a custom binding, because we separate things into components. Only components have bindings. I don't want to add the whole boilerplate code just to enable a PWM.

2021-01-27 12:58 UTC, galak commented
NACK as well.  This isn't in the spirit of our devicetree architecture decision.

We have an application specific way to have nodes w/o bindings `/zephyr,user`

2021-01-27 12:58 UTC, galak requested changes
NACK: Agree w/@henrikbrixandersen here.

2021-01-27 13:12 UTC, martinjaeger commented
> A PWM channel is not just a PWM channel (similar as to a GPIO not just being a GPIO). It has a hardware function (e.g. a LED, a charge pump, ...) which should be described in DTS.

The nodelabel would describe the function of the PWM channel with this approach.

I don't have a strong opinion about which approach is better. But we should probably only use one way in Zephyr upstream and not provide several different options (which might confuse people).

2021-01-30 10:05 UTC, alexanderwachter commented
Too many NACKs :-(

2021-01-30 10:05 UTC, closed without merging