drivers/flash/soc_flash_nrf: FTPAN-242 workaround
zephyrproject-rtos/zephyr pull request #31759
Opened 2021-01-28 18:00 UTC by nvlsianpu

- Introduce support for situation when synchronization back-end aborts operation before it is done. synchronization API will transfer operation return code to the driver shim back.

- Disable POFWARN by writing POFCON before a write or erase operation. Do not attempt to write or erase if EVENTS_POFWARN is already asserted.

2021-01-28 18:02 UTC, nvlsianpu commented
cc @eugmes

2021-01-29 13:44 UTC, ioannisg commented
I would like reviews from @anangl and @de-nordic here

2021-02-01 08:39 UTC, anangl requested changes

2021-02-01 08:39 UTC, anangl commented on drivers/flash/soc_flash_nrf.c
> +		nrf_power_pofcon_set(NRF_POWER, false, NRF_POWER_POFTHR_V27);
Do you need to change the threshold here? Wouldn't it be sufficient to just disable the warning? I mean:
```
		nrf_power_pofcon_set(NRF_POWER, false, pof_thr);
```
You could eliminate `pofcon_pof_thr` then (and use `nrf_power_pofcon_get()` in `restore_pofwarn()`).

2021-02-01 08:39 UTC, anangl commented on drivers/flash/soc_flash_nrf.c
> +						  NRF_POWER_EVENT_POFWARN)) {
Why is the event actually cleared here? Maybe you could use `nrf_power_event_check()` instead?

2021-02-01 08:39 UTC, anangl commented on drivers/flash/soc_flash_nrf.c
> +#ifdef CONFIG_NRF52_ANOMALY_242_WORKAROUND
```suggestion
#if NRF52_ERRATA_242_PRESENT
```

2021-02-01 08:39 UTC, anangl commented on drivers/flash/soc_flash_nrf.c
> +	}
`pofcon_enabled = false;` is missing here.

2021-02-01 08:39 UTC, anangl commented on drivers/flash/soc_flash_nrf.c
> +#define RESUME_CONFLICTING_SYSTEMS()  restore_pofwarn()
Is it worth naming "conflicting systems"? Maybe just `*_POFWARN()` could work?

2021-02-05 15:59 UTC, nvlsianpu commented
@anangl Reworked.

2021-02-09 09:11 UTC, anangl approved these changes

2021-02-09 09:57 UTC, de-nordic approved these changes
Looks OK

2021-02-12 12:48 UTC, ioannisg approved these changes

2021-02-14 23:23 UTC, merged