Bluetooth: controller: Use Host defined Periodic Advertising Kconfig
zephyrproject-rtos/zephyr pull request #32017
Opened 2021-02-05 04:57 UTC by cvinayak

Use the Host defined BT_PER_ADV_SYNC_MAX Kconfig in the
controller implementation of Periodic Advertising Sync Sets.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2021-02-05 08:04 UTC, thoh-ot commented
Isn't it more of "Use subsystem defined" as the configuration resides in subsys/bluetooth/Kconfig?

2021-02-05 09:25 UTC, Thalley requested changes
I agree with @thoh-ot - Let's update the PR name and commit message

2021-02-09 13:06 UTC, Thalley approved these changes
LGTM

2021-02-09 13:09 UTC, thoh-ot approved these changes

2021-02-15 13:01 UTC, merged