drivers: sensor: dps310 fix out of bounds write
zephyrproject-rtos/zephyr pull request #32088
Opened 2021-02-08 17:37 UTC by creiter32

Fixes a copy paster error which results in an out of bounds write on the stack.

This should probably be marked for backporting to all supported releases with this driver.

2021-02-08 19:39 UTC, MaureenHelm requested changes
It would help to prevent future copy-paste errors if this is instead changed to `sizeof(tmp_coef_srce)`.

2021-02-08 21:38 UTC, gmarull requested changes
Agree with @MaureenHelm, using `sizeof` is a better choice

2021-02-09 08:39 UTC, gmarull approved these changes

2021-02-09 08:40 UTC, creiter32 commented
> 
> 
> It would help to prevent future copy-paste errors if this is instead changed to `sizeof(tmp_coef_srce)`.

Done.

2021-02-09 13:50 UTC, avisconti approved these changes
using sizeof() looks good

2021-02-09 15:40 UTC, MaureenHelm approved these changes

2021-02-09 15:44 UTC, merged