net: openthread: added heap related otPlat methods implementation
zephyrproject-rtos/zephyr pull request #32395
Opened 2021-02-17 12:37 UTC by kkasperczyk-no

Added implementations of otPlatCAlloc and otPlatFree methods
necessary for the OpenThread in case of using EXTERNAL_HEAP.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2021-02-17 12:37 UTC, kkasperczyk-no commented
Associated openthread upmerge PR: https://github.com/zephyrproject-rtos/openthread/pull/37

2021-02-17 12:47 UTC, rlubos reviewed
LGTM, final approve after SHA is updated.

2021-02-17 13:00 UTC, edmont requested changes
Please update `subsys/net/l2/openthread/Kconfig.features` with `CONFIG_OPENTHREAD_DNSSD_SERVER`.

See https://github.com/zephyrproject-rtos/zephyr/pull/32025/commits/c7a1d7ddaaa7f76f23cdacf62b1031f7e8dd9bed

2021-02-17 13:03 UTC, edmont commented
Also please revert https://github.com/nrfconnect/sdk-zephyr/pull/464

2021-02-17 13:38 UTC, kkasperczyk-no commented
CONFIG_OPENTHREAD_DNSSD_SERVER option added, nrfconnect/sdk-zephyr revert is not appropriate until sdk-zephyr version is updated in the sdk-nrf.

2021-02-17 13:41 UTC, edmont approved these changes

2021-02-18 08:20 UTC, rlubos commented on west.yml
> +      revision: pull/37/head
Please update SHA: `d44ee763b7e8fea29b54dd064342c771161afcab`

2021-02-18 08:49 UTC, kkasperczyk-no commented on west.yml
> +      revision: pull/37/head
Done

2021-02-18 09:07 UTC, rlubos approved these changes

2021-02-18 16:22 UTC, jukkar approved these changes

2021-02-18 16:23 UTC, merged