cmake: modules: Remove duplicates only from existing ZEPHYR_MODULE_NAMES
zephyrproject-rtos/zephyr pull request #32482
Opened 2021-02-19 12:12 UTC by wopu-ot

Remove duplicates from ZEPHYR_MODULE_NAMES only if that list
exists. That avoids cmake error "list sub-command REMOVE_DUPLICATES
requires list to be present" if ZEPHYR_MODULE_NAMES is empty.

Signed-off-by: Wolfgang Puffitsch <wopu@demant.com>

2021-02-23 08:19 UTC, tejlmand requested changes
Please check with `if(DEFINED ..)` instead.

2021-02-23 08:19 UTC, tejlmand commented on cmake/zephyr_module.cmake
> +if(ZEPHYR_MODULE_NAMES)
```suggestion
if(DEFINED ZEPHYR_MODULE_NAMES) 
```

2021-02-23 09:49 UTC, wopu-ot commented on cmake/zephyr_module.cmake
> +if(ZEPHYR_MODULE_NAMES)
Done.

2021-02-23 10:41 UTC, tejlmand approved these changes

2021-03-04 09:37 UTC, wopu-ot commented
@nashif Can you maybe have a look at this?

2021-03-05 12:27 UTC, wopu-ot commented
@tejlmand @nashif This rather trivial change is now already sitting there for two weeks. What can I do to get it merged?

2021-03-09 12:04 UTC, nashif approved these changes

2021-03-09 12:04 UTC, merged