net: shell: UDP commands
zephyrproject-rtos/zephyr pull request #32722
Opened 2021-02-28 09:26 UTC by hubertmis

This patch adds to network shell set of basic commands for UDP protocol
to receive and send datagrams. It is compatible only with IPv6. It
can be extended later with IPv4 support as well.

Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>

2021-02-28 18:02 UTC, jukkar requested changes

2021-02-28 19:26 UTC, hubertmis commented on subsys/net/ip/net_shell.c
> +	port = strtol(argv[2], &endptr, 0);
I'm testing it with OpenThread, I don't have any IPv4 capable applications to verify IPv4 variant. I would prefer to limit scope of this PR to IPv6 and if someone would like to use it with IPv4, it should be straightforward to extend.

2021-02-28 19:30 UTC, hubertmis commented on subsys/net/ip/net_shell.c
> +	struct net_if *iface = net_if_get_default();
I got inspiration from TCP functions. It seems the limitation you described here is still present in `tcp_connect()`. Or am I missing something?

2021-03-01 08:18 UTC, jukkar commented on subsys/net/ip/net_shell.c
> +	struct net_if *iface = net_if_get_default();
Yes, the same limitation is in TCP too and should be fixed at some point.

2021-03-01 08:19 UTC, jukkar commented on subsys/net/ip/net_shell.c
> +	port = strtol(argv[2], &endptr, 0);
> I'm testing it with OpenThread,

Ok, that is good. But this is trivial to test using Qemu which by default provides dual IPv6 and IPv4 support.

2021-03-01 10:31 UTC, rlubos reviewed
Looks good, but I agree with Jukka that it should be pretty straightforward to test IPv4 with QEMU so it shouldn't be a big deal to add/test IPv4 as well for completeness.

I also wonder, while current solution is consistent with the TCP shell module implementation, we should likely be moving towards socket API usage in modules like this? There's an open issue to convert TCP shell to socket API. But I don't think it should be a blocker, perhaps both TCP and UDP could be reimplemented together at some point in the future.

2021-03-01 11:18 UTC, hubertmis commented
> that it should be pretty straightforward to test IPv4 with QEMU so it shouldn't be a big deal to add/test IPv4 as well for completeness

I created this patch while I was testing my OpenThread project. I'm happy to share my work with community and add UDP commands for IPv6. I don't think I'll have enough free time soon to setup QEMU and add IPv4 support. But if you think missing IPv4 is a blocker, we can close this PR for now.

I'm also OK if someone modified this PR and add IPv4 support before it is merged.

2021-03-01 15:29 UTC, jukkar commented
See #32750 I added IPv4 support. For some reason I could not push to this PR so created a new one.

2021-03-01 15:33 UTC, jukkar commented
> perhaps both TCP and UDP could be reimplemented together at some point in the future.

Ack to this, we should convert both the TCP and UDP using sockets but probably not in this PR

2021-03-01 18:32 UTC, hubertmis commented
> For some reason I could not push to this PR so created a new one.

Interesting. I verified, the box allowing edits by maintainers is checked. Anyway, I reviewed #32750. It looks nearly ready to be merged.

2021-03-02 12:22 UTC, hubertmis commented
Suppressed by #32750

2021-03-02 12:22 UTC, closed without merging