Add USB 2.0 peripheralfor STM32L053 in device tree
zephyrproject-rtos/zephyr pull request #32732
Opened 2021-03-01 01:26 UTC by GunZi200

I noticed STM32L053 didn't have any USB FS peripheral set similar to STM32L073. It seems to be a copy-paste from STM32L073 since they are both STM32L0x3.

This pull request also:

* Removes redundant `ram-size` parameter set for STM32F469, it is already set for STM32F405 which is included into STM32F469 `.dtsi` file.
* Add `maximum-speed` parameter for USB peripheral for STM32L072 & STM32L073 and all STM32L4x2, STM32L4x3. I set it to `"full-speed"`. Saw this parameter when looking through STM32F4 `.dtsi` files.

This is my first pull request here, hope this helps. 😄 

![image](https://user-images.githubusercontent.com/8218499/109440793-4bdeb100-7a2b-11eb-9697-c81fc9f11b9a.png)

2021-03-01 08:41 UTC, erwango requested changes
Thanks for this contribution.

The only change requested is to re-compose your pull request. 
-squash all the commits
-split in 2 or 3 commits: 1 commit to introduce the new node, other commit(s) for the L4/F4 fixes.
For each commit, please provide a commit message in accordance with contributing guidelines (you can also check other commit messages)

2021-03-01 08:41 UTC, erwango commented on dts/arm/st/l0/stm32l072.dtsi
> +			maximum-speed = "full-speed";
This is not strictly required as this property is optional. 
When not available, USB controller set speed to the controller maximum available speed.
This is what is done in STM32 USB driver.
Anyway, this doesn't harm.

2021-03-01 09:30 UTC, GunZi200 commented
> Thanks for this contribution.
> 
> The only change requested is to re-compose your pull request.
> -squash all the commits
> -split in 2 or 3 commits: 1 commit to introduce the new node, other commit(s) for the L4/F4 fixes.
> For each commit, please provide a commit message in accordance with contributing guidelines (you can also check other commit messages)

Do I understand it correctly that this would require a new branch / fork to change the previous commit messages?

2021-03-01 13:00 UTC, erwango commented
> > Thanks for this contribution.
> > The only change requested is to re-compose your pull request.
> > -squash all the commits
> > -split in 2 or 3 commits: 1 commit to introduce the new node, other commit(s) for the L4/F4 fixes.
> > For each commit, please provide a commit message in accordance with contributing guidelines (you can also check other commit messages)
> 
> Do I understand it correctly that this would require a new branch / fork to change the previous commit messages?

You don't need a new branch, nor fork to do this. In few steps:
-1)squash all your commits into one
-2)amend the commit, spit the content, rework the commit message, commit
-3)Iterate 2) for the next commits
-4)Force push your branch (git push -f <your_fork> <your_branch_name>)

2021-03-02 14:56 UTC, erwango approved these changes

2021-03-17 08:42 UTC, FRASTM reviewed
LGTM including @erwango 's comments

2021-03-17 08:43 UTC, FRASTM approved these changes

2021-03-17 10:29 UTC, merged