net: mqtt: add missing log_strdup() calls
zephyrproject-rtos/zephyr pull request #32846
Opened 2021-03-03 21:16 UTC by plskeggs

Strings must be passed to log_strdup() so logging
with CONFIG_LOG_IMMEDIATE=n doesn't assert.

Signed-off-by: Pete Skeggs <peter.skeggs@nordicsemi.no>

2021-03-03 23:04 UTC, mniestroj requested changes
`struct mqtt_utf8` doesn't have to (or even should not?) be NULL-terminated, so log_strdup() can't be used. Unfortunately current MQTT_TRC logs already rely on NULL termination... Please consider using `LOG_HEXDUMP_*` (and maybe ading `MQTT_HEXDUMP_TRC`) APIs for dumping `struct mqtt_utf8`.

2021-03-03 23:40 UTC, plskeggs commented
I think seeing the text is more helpful than a hexdump.  What do you think about, instead of this, adding a new `log_strndup()` function which also accepts a length parameter, and properly handles unterminated strings, then using that new facility here?

2021-03-04 00:03 UTC, mniestroj commented
`log_strndup()` sounds good!

2021-03-04 09:02 UTC, rlubos commented
Yeah, that seems like a bad overlook from the original implementation... 

We could go for `log_strndup()`, but I see one issue with interpreting the `struct mqtt_utf8` value as an ASCII string. As the name suggests, MQTT expects a UTF-8 encoded string, and while for basic ASCII character set there's no difference, the application could still encode a string with a broader character set, and in this case the logger will simply print some rubbish if we interpret it as a plain string. So perhaps sticking to hexdup would be a more generic approach.

2021-03-04 09:33 UTC, mniestroj commented
I had the same concern as @rlubos, but was hoping that UTF-8 characters would silently be interpreted properly (as UTF-8) by most terminals, where output from logging goes.

2021-03-04 10:54 UTC, jukkar commented
> was hoping that UTF-8 characters would silently be interpreted properly (as UTF-8) by most terminals, where output from logging goes.

Perhaps we should assume that those **debug** prints get printed properly, and tackle this problem only when really needed.

2021-03-04 11:31 UTC, mniestroj commented
Agreed with @jukkar. Besides, non-ASCII characters in logging backend is not as bad as lack of NULL-termination, which results in undefined behavior and possible crashes.

2021-03-04 17:39 UTC, plskeggs commented
Unfortunately it is more difficult to create a log_strndup() than I realized, due to the need to support CONFIG_LOG_IMMEDIATE=y.  In that situation, the log_strdup buffer pool is not allocated or initialized, so there is nothing to use as a buffer in which to store and null terminate the string, nor would it be freed when logged.

We could restrict enabling these traces unless CONFIG_LOG_IMMEDIATE=n, though that's not very desirable.

Perhaps hexdump is better after all, despite my readability objection, since it is supported in all modes and has a length parameter.

2021-03-05 07:36 UTC, jukkar approved these changes
LGTM

2021-03-05 09:24 UTC, mniestroj approved these changes

2021-03-05 09:33 UTC, rlubos approved these changes

2021-03-05 10:49 UTC, merged