boards: nsim: add mdb unaligned memory access option
zephyrproject-rtos/zephyr pull request #32856
Opened 2021-03-04 06:43 UTC by IRISZZW

When CONFIG_ARC_USE_UNALIGNED_MEM_ACCESS=y, we also
need to add -Xunaligned option for mdb to enable unaligned
memory access feature for nsim.

2021-03-04 10:42 UTC, evgeniy-paltsev approved these changes
Nice catch!

2021-03-04 10:47 UTC, abrodkin requested changes
Please provide some details how did you get to that conclusion, or in another words which problem you were solving and why.

2021-03-04 13:45 UTC, ruuddw approved these changes

2021-03-15 07:54 UTC, abrodkin approved these changes

2021-03-15 09:23 UTC, merged