stm32: window watchdog: Fix interrupt priority for CM0 series and prescaler setup for new series.
zephyrproject-rtos/zephyr pull request #33003
Opened 2021-03-05 20:48 UTC by str4t0m

- Corrects invalid interrupt priority for F0, L0, and G0.
- removes depenency on macros in hal: IS_WWDG_TIMEOUT, and WWDG_IS_PRESCALER
- Fixes prescaler bit mask for STM32G0, STM32G4, STM32H7, STM32L5, STM32WB, and STM32WL
- removes hardcoded prescaler range of 1 to 8.

Fixes: #33000 #33001

2021-03-30 12:37 UTC, FRASTM approved these changes

2021-04-02 09:02 UTC, erwango requested changes
Thanks for his contribution.

Looks fine aside 2 comments.

2021-04-02 09:02 UTC, erwango commented on drivers/watchdog/wdt_wwdg_stm32.c
> +	      WWDG_TIMEOUT_IS_VALID(timeout, calculated_timeout))) {
I would prefer we keep existing HAL marco.
I don't see really good reason to remove them, specially if this is to provide alternative implementation using a different name.

2021-04-08 14:37 UTC, erwango approved these changes
Nit: Commit message for "drivers/watchdog: wwdg stm32: fix prescaler setup for newer series." could deserve a slight rework.

2021-04-08 14:41 UTC, str4t0m commented on samples/drivers/watchdog/boards/nucleo_g431rb.overlay
> +&wwdg {
Per default the board uses a APB1 prescaler of 1 resulting in a ABP1 frequency of 170MHz.
WWDG has the fixed prescaler of 4096 and a variable prescaler of 1 to 128.
Therefore the valid range w/o a modified prescaler is:
t_WWDG_min = 1 / (170MHz / (4096 * 1)) = 24.1us.
t_WWDG_max = (0x3F + 1) / (170MHz / (4096 * 128)) = 197.4ms.

As the sample uses a max window of 100ms, this should be fine? What do I miss?
I don't have a nucleo_g431rb but I have tested it on a nucleo_g474re.

2021-04-08 15:06 UTC, str4t0m commented
I have reworked the commit message regarding the "IS_WWDG_PRESCALER".

2021-04-08 15:15 UTC, str4t0m commented
The complience check seems unrelated. I have rebased on the latest master, but that didn*t resolve the issue:

Found references to undefined Kconfig symbols.
...
CONFIG_DMA_0_NAME tests/drivers/dma/chan_link_transfer/src/test_dma.c:24

2021-04-09 06:23 UTC, erwango commented on samples/drivers/watchdog/boards/nucleo_g431rb.overlay
> +&wwdg {
That's fine indeed, txs.

2021-04-09 11:23 UTC, merged