Update LTS documentation
zephyrproject-rtos/zephyr pull request #33438
Opened 2021-03-17 15:51 UTC by nashif

- doc: LTS release docs
- doc: master -> main branch
- doc: more LTS details

2021-03-17 16:11 UTC, galak commented on doc/development_process/release_process.rst
> +- **Long Term**: Maintained for an extended period of time (at least 2.5 years)
do we add a bullet here about overlapping LTS release support?

2021-03-17 16:20 UTC, galak commented on doc/development_process/release_process.rst
> +    - Kconfig
add deprecation removal in LTS-2

2021-03-17 16:40 UTC, galak commented on doc/development_process/release_process.rst
> +- Requirements Traceability Matrix (RTM)
Anything about license/SPDX manifest?

2021-04-14 17:23 UTC, jhedberg approved these changes

2021-04-20 21:32 UTC, nashif commented
@MaureenHelm  @ioannisg  @carlescufi  can you please review?

2021-04-21 21:34 UTC, ioannisg requested changes

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +docmented and tracked. The footprint and scope of mature and stable APIs expands
documented

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +as we move from one LTS to the next given users access to bleading edge features
giving

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +by 3 weeks with the feature freeze happening 6-7 weeks before the anticipated
happening -> occurring

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +++++++++++++
extra +

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +products. To guarantee stability of the APIs and the implemementation of such
implementation

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +APIs, it is required that any release software that makes the core of the OS
remove comma

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +This guarantees that we release many of the highlighted and core feature with
features

Also the syntax in the last sentence is not clear to me; what is "implementation supports by stable APIs"?

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +  - All stable APIs need to be frozen 2 release before an LTS. APIs can extended
releases

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +  - All stable APIs need to be frozen 2 release before an LTS. APIs can extended
be extended

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +  - New APIs for experiental features can be added at any time as long as they
experimental

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +The Zephyr project follows industry standards and processes with goal of
the goal of

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +providing a quality oritented releases. This is achieved by providing the
oriented

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +  open-source tools and documentation of deviations and false postives.
positives

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +- Requirement Catalog
Requirements

2021-04-21 21:34 UTC, ioannisg commented on doc/development_process/release_process.rst
> +independently from the mainline tree for at least 2.5 years after it was
main tree, sounds better, and will correspond also to the main branch

2021-04-22 07:36 UTC, ioannisg approved these changes

2021-04-22 09:35 UTC, carlescufi approved these changes
LGTM

2021-04-22 11:22 UTC, merged