Enabling SPI for STM32F2
zephyrproject-rtos/zephyr pull request #33636
Opened 2021-03-23 16:27 UTC by ikmdani

These commits enable SPI on STM32F2. test_spi_loopback was used for testing on SPI-1 and the results is tests passed.

2021-03-24 08:23 UTC, erwango requested changes
Thanks!
One minor addition required, aside this: LGTM.

2021-03-24 08:23 UTC, erwango commented on boards/arm/nucleo_f207zg/doc/index.rst
> +- SPI1 NSS/SCK/MISO/MOSI : PA4/PA5/PA6/PA7 (Arduino SPI)
Please also update `boards/arm/nucleo_f207zg/arduino_r3_connector.dtsi` to configure arduino_spi in dts:
`arduino_spi: &spi1 {};`
When doing so please also update `supported` section in boards yaml to document it supports `arduino_spi`.

2021-03-24 10:58 UTC, erwango approved these changes

2021-03-25 09:35 UTC, ikmdani commented
@ABOSTM , i request you to kindly review this GP request.

2021-03-25 12:48 UTC, FRASTM approved these changes

2021-03-25 12:48 UTC, FRASTM commented on tests/drivers/spi/spi_loopback/boards/nucleo_f207zg.overlay
> + * Copyright (c) 2020 STMicroelectronics
Copyright (c) 202**1** ?

2021-03-25 13:59 UTC, erwango requested changes
@ikmdani please fix comments in original commits instead of using additional commits to fix comments.

2021-03-25 14:14 UTC, ikmdani commented on tests/drivers/spi/spi_loopback/boards/nucleo_f207zg.overlay
> + * Copyright (c) 2020 STMicroelectronics
@FRASTM , corrected the year. Thanks.

2021-03-25 14:54 UTC, erwango approved these changes

2021-03-26 12:26 UTC, merged