nucleo-g0b1re fixes
zephyrproject-rtos/zephyr pull request #33642
Opened 2021-03-23 18:08 UTC by raul-klg

Hello. I'd like to help with some little changes/fixes to the recently added support to stm32g0b1 and nucleo-g0b1re, specifically to the related dts files.

2021-03-23 19:46 UTC, erwango requested changes
Thanks for these fixes!
Aside from the compliance checks, looks good.
Please fix the reported long lines in commit messages (which otherwise are well documented, thanks for that also).

2021-03-23 19:50 UTC, str4t0m requested changes
One nit.

2021-03-23 19:50 UTC, str4t0m commented on boards/arm/nucleo_g0b1re/arduino_r3_connector.dtsi
> +			   <7 0 &gpioc 4 0>,	/* D1 */
The nucleo_g071rb, uses the same board, could you eventually fix it there as well?

2021-03-23 20:33 UTC, jenmwms commented
> Please fix the reported long lines in commit messages

To answer your question from dev mail list, there are a few ways to satisfy these compliance checks. Here, IMO you can just cut the long line onto another line to satisfy the limit. Line break between the warnings can help readability then. Or, you can file a quick bug and link the number in your commit with a Fixes #xxxxx.  In some cases, when not simple to shorten, it may be permissible based on feedback from approvers.

2021-03-25 07:53 UTC, erwango approved these changes

2021-03-25 14:03 UTC, FRASTM approved these changes

2021-03-26 12:35 UTC, merged