drivers: sensor: bmi160: Fix device definition on bus I2C
zephyrproject-rtos/zephyr pull request #33685
Opened 2021-03-24 18:10 UTC by vinceWii4

When the bmi160 device is located on bus i2c: the anymotion trigger can't be mapped to int-pin and interrupt status register 

Signed-off-by: Vincent De Carvalho <vincent.decarvalho@wiifor.com>

2021-03-24 18:50 UTC, sjg20 approved these changes
Not keen on the #if stuff but I don't have a better idea

2021-03-25 06:28 UTC, vinceWii4 commented
1. I updated _**drivers: sensor: bmi160: Fix device definition on bus I2C**_ commit message body
2. I added a commit to fix an issue in bmi160_trigger.c

2021-03-30 16:09 UTC, MaureenHelm requested changes

2021-03-30 16:09 UTC, MaureenHelm commented on drivers/sensor/bmi160/bmi160_trigger.c
> +#define DT_DRV_COMPAT bosch_bmi160
Please squash this change into the previous commit

2021-04-13 17:53 UTC, galak commented
@vinceWii4 Any updates.

2021-04-13 17:54 UTC, galak commented
This also needs to be submitted to master branch first before we backport.

2021-06-28 00:28 UTC, closed without merging