module: add option to add syscalls include dirs
zephyrproject-rtos/zephyr pull request #33756
Opened 2021-03-28 17:37 UTC by shlomow

The system calls in zephyr are generated automatically
using python script. The cmake looks for the syscalls
in files that are present in `SYSCALL_INCLUDE_DIRS`
variable. This commit adds an option to add more syscalls
paths in the module yaml file.

2021-04-01 13:03 UTC, shlomow commented
@nashif @tejlmand ping

2021-07-16 07:38 UTC, tejlmand commented
@shlomow sorry for late response. for some reason I never noticed this PR before.

Could you raise an issue first, describing precisely the issue you have with the current solution.
Your Zephyr module should be able to do the following already in today's solution:
```
# <zephyr-module>/CMakeLists.txt
if(<some-condition>)
  list(APPEND SYSCALL_INCLUDE_DIRS ${ZEPHYR_CURRENT_MODULE_DIR}/<some>/<path>/<system-includes>)
endif()
```
and through that be able to achieve what you want.

But there could be reasons to think that having this as part of module.yml would be nice, but i'm not convinced at the moment.
That's why a dedicated issue would be nice, for further discussion.

2021-07-16 08:54 UTC, shlomow commented
@tejlmand  From what I remember (this was 2 months ago) changing the cmake file as you say worked only for the application cmake and not the cmake of the module. Maybe I am wrong

2021-07-16 10:46 UTC, tejlmand commented
> @tejlmand From what I remember (this was 2 months ago) changing the cmake file as you say worked only for the application cmake and not the cmake of the module. Maybe I am wrong

Zephyr modules are processed here:
https://github.com/zephyrproject-rtos/zephyr/blob/0106d8f2a391fffcefabd053e17c683ea2e53d8a/CMakeLists.txt#L463

and the `SYSCALL_INCLUDE_DIRS` afterwards here:
https://github.com/zephyrproject-rtos/zephyr/blob/0106d8f2a391fffcefabd053e17c683ea2e53d8a/CMakeLists.txt#L565-L569

What you probably need is to ensure is that the updated list goes back to the higher level CMakeLists.txt file, like this:
```
set(SYSCALL_INCLUDE_DIRS ${SYSCALL_INCLUDE_DIRS} PARENT_SCOPE)
```
after the `list(APPEND SYSCALL_INCLUDE_DIRS ...)`.

2021-07-16 10:48 UTC, tejlmand requested changes
blocking, not because of requested changes, but to allow for further discussion on whether this is needed or not.

2021-08-07 15:43 UTC, shlomow commented
@tejlmand Thank you so much! the `PARENT_SCOPE` solved the issue. Any how I think that this feature is nice and it works the same way for other params like `dts_root`. At least documentation should be added. What do you think?

2021-08-10 10:00 UTC, tejlmand commented
> @tejlmand Thank you so much! the PARENT_SCOPE solved the issue. 

Great to hear.

> Any how I think that this feature is nice and it works the same way for other params like dts_root.

The difference here is that the additional roots are for the build system, so that it allows board, dts, etc. out of tree.
All the roots contains files that integrates closely to the build system itself, like Kconfig or CMake files.

The syscall is a include folder, which is of course important for the source files being compiled, but not an integrated part of the build infrastructure as such.

So it would not really be a `root` per se.

CMake already offers functionality for include folders, so we should be careful not to re-invent our own mechanism here.
Note: the root description above is not covered as a CMake feature, and thus makes sense as part of module description.

> At least documentation should be added. What do you think?

I think that sounds like a good thing.
This could possibly be done in a generic way, so that it covers specifying Zephyr CMake variable from a Zephyr module in general.

And then we keep the CMake part inside the CMake code where it really belongs.

2021-08-12 23:56 UTC, str4t0m commented
Thanks very much!
I had the same problem, luckily I saw these suggestions from @tejlmand.
` set(SYSCALL_INCLUDE_DIRS ${SYSCALL_INCLUDE_DIRS} PARENT_SCOPE) ` also solved the issue for me.

2021-08-24 19:56 UTC, tejlmand commented
> @tejlmand Thank you so much! the `PARENT_SCOPE` solved the issue. Any how I think that this feature is nice and it works the same way for other params like `dts_root`. At least documentation should be added. What do you think?

See https://github.com/zephyrproject-rtos/zephyr/pull/37909

2021-08-27 08:21 UTC, closed without merging