Various coding guideline fixes
zephyrproject-rtos/zephyr pull request #33852
Opened 2021-03-29 21:26 UTC by nashif

﻿- kernel: Make both operands of operators of same essential type category
- kernel/arch: cleanup function definitions
- userspace: rename _is_user_context -> k_is_user_context
- x86: make tests of a value against zero should be made explicit
- kernel: make tests of a value against zero should be made explicit

2021-03-29 21:43 UTC, dcpleung commented on arch/x86/core/x86_mmu.c
>  			   MASK_ALL, 0);
This one is actually better with `phys` and `virt`. Could you change the declaration instead?

2021-03-29 21:43 UTC, dcpleung commented on include/sys/mem_manage.h
> +			  uintptr_t phys_addr, size_t size, size_t align);
`addr` and `aligned_addr` are better as it will align any addresses.

2021-03-30 07:57 UTC, jhedberg commented on kernel/device.c
>  		return NULL;
Wouldn’t '\0' be the most appropriate here since it’s a character and not an integer?

2021-03-30 07:59 UTC, jhedberg commented on kernel/device.c
>  		return NULL;
It would also be more consistent with the place you’re changing in fatal.c

2021-03-30 14:09 UTC, MaureenHelm approved these changes

2021-03-30 14:49 UTC, enjiamai approved these changes

2021-03-30 16:08 UTC, dcpleung approved these changes

2021-03-30 21:59 UTC, ceolin approved these changes

2021-03-31 10:44 UTC, jhedberg requested changes

2021-03-31 10:44 UTC, jhedberg commented on kernel/device.c
>  		return NULL;
Seems like you missed this comment? I think the signedness of `char` is also architecture dependent, which is why `\0` would also be better.

2021-04-01 08:59 UTC, jhedberg approved these changes

2021-04-01 09:34 UTC, merged