soc: atmel_sam0: Add GCLK Reset
zephyrproject-rtos/zephyr pull request #33855
Opened 2021-03-29 23:08 UTC by legoabram

Fixes an issue with mcuboot where the SoC will freeze when the dpll is
disabled since `atmel_samd_init` was already run in the bootloader.

Signed-off-by: Abram Early <abram.early@gmail.com>

2021-04-01 12:39 UTC, carlescufi commented
@nvlsianpu and @ioannisg could you please review this, as it is part of the MCUboot hardware cleanup that you worked on?

2021-04-27 22:58 UTC, nandojve requested changes
I think you should follow same structure used by, if possible https://github.com/zephyrproject-rtos/zephyr/blob/e3a79046fbd45eaf0bd4f58241c168471deded0e/soc/arm/atmel_sam0/common/soc_samd2x.c#L183-L190

My feeling is, the reset will do difference for below, which configure the generic clocks:
https://github.com/zephyrproject-rtos/zephyr/blob/e3a79046fbd45eaf0bd4f58241c168471deded0e/soc/arm/atmel_sam0/common/soc_samd5x.c#L133-L137

If I'm right, you can create a `gclks_init` and refact gclk_connect methods.
Dividers care attention. I think the more secure way is configure it with a well know low freq oscillator as main source.

2021-05-02 14:19 UTC, nandojve commented
> @nandojve
> 
> > If I'm right, you can create a `gclks_init` and refact gclk_connect methods.
> 
> Not really. The problem occurs when the dpll is initialized, since the core is running on that clock when it hits that function if the bootloader ran. The first thing dpll_init does is disable the clock which then bricks the core. And the reset can't be put in the same place as the gclk connect since the dpll has to be initialized before connecting it.

Ok, understood!

> 
> > Dividers care attention. I think the more secure way is configure it with a well know low freq oscillator as main source.
> 
> I don't really agree since this reset is practically the same as a power on reset, which necessitates a well known oscillator. I wouldn't be totally averse to explicitly connecting the core to a different oscillator before entering dpll_init, but I personally see the reset as a better solution because it puts the entire GCLK peripheral into a known state before configuration. (Which probably means that this should be included on the samd21 as well.)

I understand what you are saying but it is not clear to me what is Main clock between glkc reset and new first gclk_connect. If when you reset gclk system switch to another clock source, what is that clock source, frequency?

2021-05-03 18:39 UTC, legoabram commented
> I understand what you are saying but it is not clear to me what is Main clock between glkc reset and new first gclk_connect. If when you reset gclk system switch to another clock source, what is that clock source, frequency?

On any reset, generic clock 0 (which provides the core clock) is reset to be sourced from the DFLL48M which is factory calibrated for 48MHz from an RC oscillator.

I do need to add a minor correction: If any of the peripheral clocks are write locked, their respective generic clock source will not be reset on a software reset. Generic clock 0 is exempt from this rule, and will be reset anyway even if peripheral clocks using this as a source are write locked.

2021-05-03 19:37 UTC, nandojve approved these changes
Thank you @legoabram 
LGTM

2021-05-04 10:42 UTC, ioannisg approved these changes

2021-05-04 10:43 UTC, ioannisg commented
@stephanosio not sure if you'd like to take a look here.

2021-05-04 12:01 UTC, stephanosio approved these changes
It certainly would not hurt to bring the GCLK to a known state prior to initialising them.

2021-05-04 12:08 UTC, merged