Fix STM32F103XE not able to enter master mode
zephyrproject-rtos/zephyr pull request #33900
Opened 2021-03-31 02:08 UTC by ycsin

This pr fixes the [I2C issue](https://github.com/zephyrproject-rtos/zephyr/issues/33196#issuecomment-795204302) mentioned in #33196

2021-03-31 02:23 UTC, ycsin commented
ping @erwango

2021-03-31 07:02 UTC, erwango approved these changes

2021-03-31 07:04 UTC, erwango requested changes

2021-03-31 07:04 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
> +#if defined(CONFIG_SOC_STM32F103X8) || defined(CONFIG_SOC_STM32F103XB) || defined(CONFIG_SOC_STM32F103XE)
Please reduce line length :
```suggestion
#if defined(CONFIG_SOC_STM32F103X8) || \
     defined(CONFIG_SOC_STM32F103XB) || \
     defined(CONFIG_SOC_STM32F103XE)
```

2021-03-31 13:13 UTC, tagunil commented
Shouldn't this fix be extended to handle all STM32F1 devices by using CONFIG_SOC_SERIES_STM32F1X?

2021-03-31 14:33 UTC, erwango commented
> Shouldn't this fix be extended to handle all STM32F1 devices by using CONFIG_SOC_SERIES_STM32F1X?

@tagunil This is correct, I've just checked and this behavior is present in all STM32F1 series. Thanks

@ycsin Can you use CONFIG_SOC_SERIES_STM32F1X instead of the initial #ifdef combination ?

2021-04-01 08:35 UTC, ycsin commented
> > Shouldn't this fix be extended to handle all STM32F1 devices by using CONFIG_SOC_SERIES_STM32F1X?
> 
> @tagunil This is correct, I've just checked and this behavior is present in all STM32F1 series. Thanks
> 
> @ycsin Can you use CONFIG_SOC_SERIES_STM32F1X instead of the initial #ifdef combination ?

[Done](https://github.com/zephyrproject-rtos/zephyr/pull/33900/commits/b2915e0756a8cbde7ff59810afc254316987e1c9)

2021-04-01 08:47 UTC, erwango approved these changes

2021-04-01 08:50 UTC, erwango requested changes
The change itself is correct, but please squash your commits into one.
Also please pay attention to the signed-off-by (as reported by compliance checks)

2021-04-07 12:43 UTC, FRASTM approved these changes

2021-04-07 14:35 UTC, ycsin commented
closed: #34088

2021-04-07 14:35 UTC, closed without merging