Bluetooth: controller: Guard against race in connection establishment
zephyrproject-rtos/zephyr pull request #34123
Opened 2021-04-08 07:28 UTC by mtpr-ot

In the time between a NODE_RX_TYPE_CONNECTION node is sent from LLL and
demuxed in ULL, an ADV/SCAN role disable may be executed.
This makes the LLL data referenced in the node NULL/invald, and
ull_conn_setup would operate on invalid data.
This commit introduces a NULL-pointer/sanity check of the LLL data in
the node footer field.

Signed-off-by: Morten Priess <mtpr@oticon.com>

2021-04-08 07:47 UTC, mtpr-ot commented on subsys/bluetooth/controller/ll_sw/ull_conn.c
> +		if ((lll == &conn->lll) && (lll->handle == 0xffff)) {
This is a bit "over the top" and not necessary for this particualr race, but always nice to be safe...

2021-04-08 08:01 UTC, cvinayak requested changes
Connection *established* shall be prioritized over advertisement disable, the fix has to be in the `disable()` to detect the generated `NODE_RX_TYPE_CONNECTION` and fail with the HCI command response as cmd disallowed.

2021-04-08 08:07 UTC, mtpr-ot commented
> Connection _established_ shall be prioritized over advertisement disable, the fix has to be in the `disable()` to detect the generated `NODE_RX_TYPE_CONNECTION` and fail with the HCI command response as cmd disallowed.

OK, good point. Will try to rework.

2021-04-08 10:10 UTC, mtpr-ot commented
@cvinayak, I'm now using the `slave.initiated` flag in `lll_adv->conn` to detect connection initiation in `disable` - like in `prepare_cb`. Do you agree that would be safe?

2021-04-08 11:13 UTC, cvinayak commented
> 
> 
> @cvinayak, I'm now using the `slave.initiated` flag in `lll_adv->conn` to detect connection initiation in `disable` - like in `prepare_cb`. Do you agree that would be safe?

I feel like talking over the race conditions of ISR/LLL that sets up the expected reception of the CONNECT_IND in LLL that could happen before the `is_enabled` flags is checked, that could happen after the `is_enabled` check.  Do you think a handshake is not necessary, like being done when central is cancelling connection?

2021-04-10 02:29 UTC, cvinayak approved these changes
I have forced push my suggestions, please pull my changes, review and verify at your end.

2021-04-10 02:31 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv.c
> +		(lll->conn->slave.initiated || lll->conn->slave.cancelled))) {
Have updated myself and force push to this PR.

2021-04-12 08:25 UTC, mtpr-ot commented
Additions look good, and local tests are passing.

2021-04-12 13:19 UTC, kruithofa approved these changes
LGTM

2021-04-13 06:26 UTC, mtpr-ot commented
@cvinayak maybe we should trigger a CI rerun. Seems to have been fixed.

2021-04-13 17:02 UTC, merged