linker: aarch32: simplify memory region generation
zephyrproject-rtos/zephyr pull request #34185
Opened 2021-04-10 06:35 UTC by JordanYates

Generating linker memory regions from devicetree nodes is a common pattern in the linker script. This PR adds a macro which automatically generates a region given a devicetree node. The macro is then used in the linker script to cleanup definitions.

Dedicated devicetree nodes are created for SRAM1 and SRAM2  for the STM32WB family to facilitate macro usage.
The TI_CCFG registers are redefined as a partition on `flash0` to enable more cleanup.

2021-04-10 06:36 UTC, JordanYates commented
@galak This contains the standalone linker cleanup from #33656

2021-04-12 08:40 UTC, erwango requested changes
Minor changes requested but otherwise welcomed addition, thanks!

2021-04-12 08:40 UTC, erwango commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    DT_REGION_FROM_NODE_STATUS_OKAY(DTCM, rw, DT_CHOSEN(zephyr_dtcm))
ccm is indeed STM32 specific but itcm and dtcm are arm generic.

2021-04-12 08:40 UTC, erwango commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    /* STM3232WB IPC RAM */
```suggestion
    /* STM32WB IPC RAM */
```

2021-04-12 09:37 UTC, erwango approved these changes

2021-04-14 06:54 UTC, tejlmand approved these changes
Nice cleanup, thanks. :+1:

2021-04-14 19:30 UTC, MaureenHelm approved these changes

2021-04-15 10:25 UTC, carlescufi approved these changes

2021-04-15 10:25 UTC, merged

2021-04-15 13:48 UTC, ioannisg commented
Nice work here - sorry I had no chance to review this.

2021-04-16 03:34 UTC, MaureenHelm commented
Turns out this broke code relocation to these regions, as the relocation script expects `<region name>_ADDR` to be defined (i.e., `ITCM_ADDR`). This affects #33701, which relocates flash driver code to ITCM.

cc: @pdgendt @mmahadevan108

2021-04-16 08:16 UTC, JordanYates commented
@MaureenHelm is there a sample which produces the error, or can be modified to produce it?
I'm not sure which relocation script is the problem, nor can I find where `<region name>_ADDR` is expected.

2021-04-16 08:26 UTC, pdgendt commented
@JordanYates the [relocate script](https://github.com/zephyrproject-rtos/zephyr/blob/d8bbd2ad5c57de7ad85b920477447791518725c2/scripts/gen_relocate_app.py#L63) creates the `<region name>_ADDR`

2021-04-16 08:33 UTC, JordanYates commented
@pdgendt thanks for that link, can you provide a board & sample which fails to build?

2021-04-16 08:42 UTC, pdgendt commented
@JordanYates you can build `samples/drivers/flash_shell/` for `mimxrt1064_evk` but you have to enable the following in `prj.conf`:
```
CONFIG_FLASH_MCUX_FLEXSPI_NOR=y
CONFIG_FLASH_MCUX_FLEXSPI_XIP=y
```

2021-04-16 10:43 UTC, JordanYates commented
@pdgendt  #34331 should fix the issue.