arm: stm32f411e_disco: add dt node for leds and sensors
zephyrproject-rtos/zephyr pull request #34181
Opened 2021-04-09 20:30 UTC by ric96

Add dts nodes for onboard devices that have drivers in zerphyr src
- Add PWM for all leds
- Add LSM303AGR sensor node

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2021-04-12 06:19 UTC, erwango requested changes
Thanks for this addition.
Though, the sensors' references you're adding are adding are valid only for board rev-D.
There is no problem making this choice as it doesn't appears that other element of BSP were
specific to a revision. But doing so, you set the board default revision as rev D.
Please document this, so users using rev B could be informed and take appropriate actions.

2021-04-12 06:48 UTC, FRASTM approved these changes

2021-04-12 22:09 UTC, ric96 commented
> Thanks for this addition.
> Though, the sensors' references you're adding are adding are valid only for board rev-D.
> There is no problem making this choice as it doesn't appears that other element of BSP were
> specific to a revision. But doing so, you set the board default revision as rev D.
> Please document this, so users using rev B could be informed and take appropriate actions.

ack, I can make two overlays. the difference is the same as stm32f3_disco E-vs-B. I'll make sure to add it to the docs as well.

2021-04-13 06:00 UTC, erwango requested changes
You're missing a `revision.cmake` file.
Also, please update board description to reflect the sensor variation in between revision (`Overview`).
This might require to split the commits to have pwm related change in one and the board revision stuff in a second commit.

2021-04-13 15:24 UTC, ric96 commented
> You're missing a `revision.cmake` file.
> Also, please update board description to reflect the sensor variation in between revision (`Overview`).
> This might require to split the commits to have pwm related change in one and the board revision stuff in a second commit.

done. please let me know if splitting is still required, i've changed the commit topic to include both pwm and board rev changes

2021-04-26 13:26 UTC, erwango approved these changes

2021-04-26 18:16 UTC, merged