modules: trusted-firmware-m: fix dependencies for isolation level
zephyrproject-rtos/zephyr pull request #34243
Opened 2021-04-13 10:11 UTC by ioannisg

Do not allow the TFM_ISOLATION_LEVEL to be non-hidden option,
if the IPC (PSA_API) option is not set, since, in that case,
only Isolation Level 1 is supported.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

2021-04-13 10:14 UTC, ioannisg commented
This will probably fail, now, since stm32 l552ze_2 forces TFM isolation level to 2, while it still allows the psa_level1 sample to build and run.

2021-04-13 10:51 UTC, oyvindronningstad commented on modules/trusted-firmware-m/Kconfig
> +	  PSA_API (IPC) support.
```suggestion
	  Isolation levels 2 and 3 require PSA_API (IPC) support.
```

2021-04-13 12:36 UTC, erwango requested changes

2021-04-13 12:36 UTC, erwango commented on modules/trusted-firmware-m/Kconfig
> +	  PSA_API (IPC) support.
```suggestion
	  As isolation levels 2 and 3 require PSA_API (IPC) support, force level 1 when not enabled.
```

2021-04-13 13:36 UTC, ioannisg commented
@erwango @oyvindronningstad thanks for the review - text updated.

2021-04-13 13:40 UTC, oyvindronningstad approved these changes

2021-04-15 08:56 UTC, ioannisg commented
I added a commit that removes the forcing of TF-M isolation level to 2 for STM32 boards that support TFM - there does not seem to be any need for this, and the proof is the fact that psa_level1 sample could run successfully for the STM32L562 board (there was a Kconfig overlay that was explicitly setting the isolation level to 1)

2021-04-15 09:31 UTC, erwango approved these changes

2021-04-15 09:32 UTC, ioannisg commented
Will test psa_level1 on nucleo_l552ze_q before merging it.

2021-04-15 14:39 UTC, ioannisg commented
Need an overlay for the nucleo board. Wil add a re-run CI.

2021-04-16 07:16 UTC, ioannisg commented
Tested the integration samples  on nucleo_l552ze_q_ns

2021-04-16 11:33 UTC, merged