driver: sensor: m41t62 Added support
zephyrproject-rtos/zephyr pull request #34306
Opened 2021-04-15 07:26 UTC by ivonalo

Added driver support for the M41T62 RTC
Signed-off-by: Ivona Loncar <ivona.loncar@greyp.com>

2021-04-26 14:10 UTC, MaureenHelm requested changes
Thank you for the contribution!

Why did you implement this as a sensor driver? I think it's better suited as a counter driver instead.

2021-05-04 06:47 UTC, ivonalo commented
> Thank you for the contribution!
> 
> Why did you implement this as a sensor driver? I think it's better suited as a counter driver instead.

Thank you for your answer! I have refactored this pull request into a counter driver, so please take a look

2021-05-06 19:06 UTC, gmarull requested changes
I did an initial pass, requested a few changes. I see a sensor driver and then a counter... Can this be clarified?

2021-05-06 19:06 UTC, gmarull commented on drivers/sensor/m41t62/m41t62.c
> +	for (int i = 0; i < ARRAY_SIZE(alarm_buf); ++i) {
`size_t i`

2021-05-06 19:06 UTC, gmarull commented on drivers/sensor/m41t62/m41t62.h
> +	M41T62_OnceperYear      = (uint8_t)0
naming should be uppercase, `uint8_t` is also redundant here

2021-05-06 19:06 UTC, gmarull commented on include/drivers/sensor.h
> +	SENSOR_CHAN_RESET_OSCILLATOR,
Channels should be documented, since they don't look "standard" I'm not sure if they should be "private", @MaureenHelm ?

2021-05-07 06:33 UTC, ivonalo commented
> I did an initial pass, requested a few changes. I see a sensor driver and then a counter... Can this be clarified?

@gmarull the sensor driver was a commit left from the previous version. Now I have removed that commit and there is only the counter driver left as discussed with @MaureenHelm. Please take a look

2021-05-07 06:34 UTC, ivonalo commented
> > Thank you for the contribution!
> > Why did you implement this as a sensor driver? I think it's better suited as a counter driver instead.
> 
> @MaureenHelm  thank you for your answer! I have refactored this pull request into a counter driver, so please take a look

2021-07-28 00:28 UTC, closed without merging