dts/arm: STM32: Move i2s1 to right dtsi files for stm32f4 series.
zephyrproject-rtos/zephyr pull request #34394
Opened 2021-04-19 15:09 UTC by ikmdani

i2s1 is not present in all stm32f4 series. So moving the i2s1 node
from the top level stm32f4 dtsi file to the stm32fxx specific dtsi
files. Also in stm32f429zi, the sequence starts from i2s2, this commit
helps in having the right channel number.

Signed-off-by: Krishna Mohan Dani <krishnamohan.d@hcl.com>

2021-04-19 15:42 UTC, ikmdani commented
@erwango , as discussed.
kindly add reviewers for this commit.

2021-04-22 08:52 UTC, FRASTM approved these changes

2021-04-23 19:27 UTC, ikmdani commented
@erwango @ABOSTM kindly review this PR. Thanks.

2021-04-26 08:50 UTC, erwango requested changes

2021-04-26 08:50 UTC, erwango commented on dts/arm/st/f4/stm32f412.dtsi
> +		i2s1: i2s@40013000 {
This file includes `st/f4/stm32f411.dtsi`, by adding this node you're duplicating i2s1 definition.

2021-04-26 08:50 UTC, erwango commented on dts/arm/st/f4/stm32f413.dtsi
> +		};
same here:
This file includes stm32f412.dtsi

2021-04-26 12:36 UTC, ikmdani commented
@erwango , yes you are right, I made appropriate changes in my PR.

2021-04-26 12:43 UTC, erwango approved these changes

2021-04-26 18:17 UTC, merged