board: nxp_ls1046ardb: add 2 cores smp for running in Jailhouse
zephyrproject-rtos/zephyr pull request #34406
Opened 2021-04-20 06:34 UTC by JiafeiPan

1. add a seperate 2 cores SMP board configuration to run in Jailhouse
   inmate Cell, root Cell Linux will use Core0 and Core1, Zephyr will
   run on Core2 and Core3.
2. Refine the code of dts, move common dts nodes into dtsi files.

Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>

2021-04-20 12:01 UTC, galak requested changes
We should have the SoC dtsi file live in dts/arm/nxp.  And use `/delete-node/` to remove the cpu cores or make them as `status = "disabled"`

2021-04-21 03:16 UTC, JiafeiPan commented
> We should have the SoC dtsi file live in dts/arm/nxp. And use `/delete-node/` to remove the cpu cores or make them as `status = "disabled"`

Done, thanks.

2021-04-21 13:46 UTC, galak approved these changes

2021-04-21 14:32 UTC, npitre approved these changes

2021-04-22 09:29 UTC, merged