logging: Enable SWO pin in log_backend_swo.c
zephyrproject-rtos/zephyr pull request #34436
Opened 2021-04-20 20:13 UTC by andresmanelli

Signed-off-by: Andrés Manelli <am@toroid.io>

2021-04-22 19:53 UTC, mnkp requested changes
The code is STM32 specific. It should be placed somewhere in `soc/arm/st_stm32/`. It's typical that the platform needs some special, platform specific steps, to enable SWO. E.g. in case of Atmel SAM they are placed in `soc/arm/atmel_sam/same70/soc_config.c`.

2021-04-26 16:37 UTC, andresmanelli commented
> The code is STM32 specific. It should be placed somewhere in `soc/arm/st_stm32/`. It's typical that the platform needs some special, platform specific steps, to enable SWO. E.g. in case of Atmel SAM they are placed in `soc/arm/atmel_sam/same70/soc_config.c`.

Thanks for the review. I will place this in the `soc` directory.

2021-04-27 00:07 UTC, mnkp approved these changes
LGTM for the SWO part. I'm approving the PR to remove my previous NACK. However, it needs to be verified by the STM32 maintainers.

2021-04-30 08:01 UTC, erwango requested changes

2021-04-30 08:01 UTC, erwango commented on soc/arm/st_stm32/common/soc_config.c
> + * SPDX-License-Identifier: Apache-2.0
Please add a copyright.

2021-05-01 08:44 UTC, andresmanelli commented on soc/arm/st_stm32/common/soc_config.c
> + * SPDX-License-Identifier: Apache-2.0
Done.

2021-05-11 14:27 UTC, erwango approved these changes

2021-05-11 18:02 UTC, merged