Adds support for the BT6x0, a multi sensor platform.
zephyrproject-rtos/zephyr pull request #34519
Opened 2021-04-23 10:16 UTC by greg-leach

Signed-off-by: Greg Leach <greg.leach@lairdconnect.com>

2021-04-23 12:50 UTC, nashif requested changes

2021-04-23 12:50 UTC, nashif commented on boards/arm/bt6x0/bt6x0.dts.bak
> + * Copyright (c) 2021 Laird Connectivity
dts.bak? is this just some backup file?

2021-04-23 13:09 UTC, greg-leach commented on boards/arm/bt6x0/bt6x0.dts.bak
> + * Copyright (c) 2021 Laird Connectivity
It is indeed, removed.

2021-04-26 14:54 UTC, MaureenHelm approved these changes

2021-05-06 15:27 UTC, nashif approved these changes

2021-05-06 16:34 UTC, merged