Added qspi driver for ATSAME and ATSAMD parts
zephyrproject-rtos/zephyr pull request #34522
Opened 2021-04-23 14:01 UTC by flaminggoat

I attached the logic scope of running the spi_flash sample program.

```
JEDEC SPI-NOR SPI flash testing
==========================

Test 1: Flash erase
Flash erase succeeded!

Test 2: Flash write
Attempting to write 4 bytes
Data read matches data written. Good!!
```

[pulseview.zip](https://github.com/zephyrproject-rtos/zephyr/files/6365785/pulseview.zip)

Signed-off-by: Theo Hussey <theo@open-cosmos.com>

2021-07-02 09:23 UTC, tbursztyka requested changes
Seems fine to me.

One change however: s/CONFIG_QSPI_SAM0/CONFIG_SPI_SAM0_QSPI 
(it's still a SPI driver in the end)

Change the commit titles adding prefix "drivers: spi: "

2021-11-25 23:50 UTC, nandojve commented
Hi @flaminggoat ,

Just to inform, it is not allowed merge branches in Zephyr. I recommend you rebase your code on top of main. You can read [How to Contribute](https://docs.zephyrproject.org/latest/contribute/index.html) to get a better view.

2021-11-26 07:17 UTC, tbursztyka commented
Instead of merging which creates unecessary commits, rebase your branch against the main branch. And don't make commit with changes on top of original commit, rebase your branch and fixup your first commit.

2021-12-20 16:52 UTC, nandojve requested changes
Hi @flaminggoat ,

I don't have any board to run local tests. I pointed some notes and I think you should squash all in only one commit. My concern is that no boards enabling this driver and we would not check at CI. Suggestion is add another commit that enable ATSAME54-XPRO QSPI.

2021-12-20 16:52 UTC, nandojve commented on dts/bindings/spi/atmel,sam0-spi-quadspi.yaml
> +
Drop lines

2022-04-02 14:36 UTC, nandojve commented
Hi @flaminggoat ,

Please, rebase your code and move to pinctrl API. See #43731 as reference.

2022-08-11 06:12 UTC, nandojve commented
Hi @flaminggoat ,

Are you interested on this PR? I removed STALE so you can continue if you want.
Let me know if you still interested or not.

2022-10-25 00:43 UTC, closed without merging