tests: net: Refactor tests when running in real hw
zephyrproject-rtos/zephyr pull request #34655
Opened 2021-04-28 11:08 UTC by jukkar

The network tests were expecting that network interfaces
are in certain order. As we cannot guarantee that, refactor
the tests like this:

* if test is using DUMMY L2 driver, then disable Ethernet L2
  and fetch only DUMMY L2 instead of default interface
* if test is using Ethernet L2 driver, then make sure that the
  test is using the Ethernet interface specified in the test
  instead of the one provided by the DUT

Fixes #34505

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2021-04-28 11:11 UTC, jukkar commented
Tested this with `sam_e70_xplained` board, all the tests in `tests/net` pass now. Other boards with Ethernet controller should work too.

2021-04-29 03:13 UTC, hakehuang requested changes
tests/net/tcp2 also need add below config.
CONFIG_NET_L2_ETHERNET=n

2021-04-29 05:28 UTC, jukkar commented
> tests/net/tcp2 also need add below config.
> CONFIG_NET_L2_ETHERNET=n

Sure, that can be done. I sent updated version.

2021-04-29 09:51 UTC, rlubos approved these changes

2021-04-29 13:17 UTC, pfalcon approved these changes

2021-04-30 03:00 UTC, hakehuang approved these changes

2021-04-30 08:59 UTC, merged