interrupt_controller: ioapic: support more device power states
zephyrproject-rtos/zephyr pull request #34723
Opened 2021-04-30 08:24 UTC by kwd-doodling

do nothing when enter or resume from DEVICE_PM_LOW_POWER_STATE

Signed-off-by: Dong Wang <dong.d.wang@intel.com>

2021-04-30 18:00 UTC, ceolin approved these changes

2021-05-03 05:31 UTC, ceolin commented on drivers/interrupt_controller/intc_ioapic.c
> +			ret = ioapic_suspend(device);
s/device/dev/

2021-05-03 05:32 UTC, ceolin requested changes
The variable name is incorrect and there are tests failing. Other than that this pr is +1

2021-05-04 16:41 UTC, jenmwms commented on drivers/interrupt_controller/intc_ioapic.c
> +		uint32_t new_state = *((const uint32_t *)context);
I see this was not a `const` before, was this change intentional?

2021-05-06 17:34 UTC, ceolin approved these changes

2021-05-07 09:10 UTC, jhedberg approved these changes

2021-05-07 11:11 UTC, merged