west.yml: Update Mbed TLS to 2.26.0
zephyrproject-rtos/zephyr pull request #34877
Opened 2021-05-05 19:15 UTC by d3zd3z

Move to the latest release of Mbed TLS.

Signed-off-by: David Brown <david.brown@linaro.org>

2021-05-05 20:20 UTC, nashif requested changes

2021-05-05 20:20 UTC, nashif commented on west.yml
> +      remote: d3zd3z
you should be pointing to the PR in the mbedtls module , not some private remote:

`revision: pull/23/head`

2021-05-06 07:20 UTC, frkv commented
Adding mbed TLS v2.26.0 is not compatible with TF-M 1.3 (latest release) or TF-M master

The latest current release used in the TF-M project is mbed TLS v2.25

2021-05-06 07:30 UTC, microbuilder commented
> Adding mbed TLS v2.26.0 is not compatible with TF-M 1.3 (latest release) or TF-M master
> 
> The latest current release used in the TF-M project is mbed TLS v2.25.0

TF-M builds for the secure environment should continue to pull in it's own copy of mbedtls, which will reference 2.25 as of TF-M 1.3.0: https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/master/trusted-firmware-m/config/config_default.cmake#L164

At present, this module is for use with the NS environment, enabling use of the PSA APIs as a backend in mbedtls. Initial testing seems to indicate that 2.26.0 on the NS side is still compatible with TF-M 1.3.0, but if you have seen any specific issues please bring them up so that we can investigate.

There is a goal to bring the entire mbedtls history into Zephyr's mbedtls module repo, which will allow us to reference past tags/releases as well, but that's still a WIP, and 2.26.0 was selected since it is currently the latest release.

2021-05-06 13:54 UTC, ioannisg commented
I guess it is possible to force TF-M builds in Zephyr to use the mbedtls 2.26 as well. It is a configuration, really, so out-of-tree projects can re-modify this to use the "DOWNLOAD" option.

2021-05-06 17:32 UTC, ceolin commented
> Adding mbed TLS v2.26.0 is not compatible with TF-M 1.3 (latest release) or TF-M master
> 
> The current release used in the TF-M project is mbed TLS v2.25.0

Yep, TF-M is not the only reason. The other thing that motivated moving to the latest release is that end of life for the current LTS is this year  and this does not work for next Zephyr LTS. Moving to something newer right now allow us find possible failures before next  Zephyr LTS release.

2021-05-06 19:35 UTC, microbuilder approved these changes
Unable to approve the PR on the mbedtls repo, but tested and seems OK here (so far).

2021-05-07 07:22 UTC, ioannisg commented
> Unable to approve the PR on the mbedtls repo, but tested and seems OK here (so far).

The crypto.mbedtls test seems to be failing, though

2021-05-07 07:23 UTC, ioannisg approved these changes

2021-05-07 10:25 UTC, microbuilder commented
@frkv Just as a FYI, I did a test pointing TF-M on the S side to mbedtls 2.26.0 and it still builds and runs as expected.

2021-05-07 18:43 UTC, ceolin approved these changes

2021-05-09 14:59 UTC, closed without merging