shell: Add shell_exec
zephyrproject-rtos/zephyr pull request #351
Opened 2017-05-31 08:04 UTC by Vudentz

This adds shell_exec which can be used to execute commands directly
without the use of a console which is useful for both testing as well
as interfacing with applications/upper layer which would like to have
access to shell commands directly.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

2017-05-31 10:11 UTC, jukkar reviewed
@pfalcon Would it make sense in micropython to use this instead of calling the net-shell C-functions directly?

2017-05-31 10:16 UTC, jukkar submitted a review, later dismissed
I like this approach so +1 from me.

2017-05-31 10:39 UTC, jhedberg commented
A couple of comments:

Make it super clear in the documentation that the shell commands are not a formal API or something that can be considered stable. I.e. anyone writing code that uses the command strings should be prepared for that code to stop working at some point.

Secondly, make it clear in the documentation that C string literals cannot be passed to this function because it modifies the input (by inserting nul characters to terminate each command line argument). Instead, the caller will need to do something like "char cmd[] = "my command"; shell_exec(cmd);"

2017-05-31 12:52 UTC, nashif requested changes
Please provide a testcase for this new usage and document this in the shell subsystem documentation.

2017-06-02 08:29 UTC, jukkar submitted a review, later dismissed
LGTM

2017-06-02 12:00 UTC, Vudentz commented
@nashif Tests are now included.

2017-06-03 13:13 UTC, nashif requested changes
Please move to test to:

tests/subsys/shell

2017-06-03 13:13 UTC, nashif commented on tests/shell/testcase.ini
> +build_only = true
remove, this should be run in qemu during sanitycheck

2017-06-03 13:13 UTC, nashif commented on tests/shell/src/main.c
> +
put this below the license header

2017-06-03 13:13 UTC, nashif commented on tests/shell/src/main.c
> +	TC_PRINT("\nhelp tests:\n");
this duplicates what the testsuite already prints, too verbose. I would remove all those prints, thats how it looks now:

`tc_start() - test_select

select tests:`

2017-06-03 13:13 UTC, nashif commented on tests/shell/src/main.c
> +	TC_PRINT("\nselect tests:\n");
same, remove this, this is already printed by ztest, other tests below as well.

2017-06-04 12:19 UTC, pfalcon approved these changes
>@pfalcon Would it make sense in micropython to use this instead of calling the net-shell C-functions directly?

As discussed in the previous patch by @Vudentz, using IP stack diagnostic functions is a more direct way. We don't have such functions well defined, but un-static-izing functions used by net shell was a first step in that direction.

These changes are definitely good improvements to the shell system, and yep, if direct access to net subsystem functions will be closed, can serve as a (somewhat hackish) fallback for that too.

2017-06-09 11:24 UTC, Vudentz commented on tests/shell/testcase.ini
> +build_only = true
Done

2017-06-09 11:24 UTC, Vudentz commented on tests/shell/src/main.c
> +
Done

2017-06-09 11:24 UTC, Vudentz commented on tests/shell/src/main.c
> +	TC_PRINT("\nhelp tests:\n");
Done

2017-06-09 11:24 UTC, Vudentz commented on tests/shell/src/main.c
> +	TC_PRINT("\nselect tests:\n");
Done

2017-06-09 11:31 UTC, Vudentz commented
> As discussed in the previous patch by @Vudentz, using IP stack diagnostic functions is a more direct way. We don't have such functions well defined, but un-static-izing functions used by net shell was a first step in that direction.

> These changes are definitely good improvements to the shell system, and yep, if direct access to net subsystem functions will be closed, can serve as a (somewhat hackish) fallback for that too.

Im not directly targeting any changes to net_shell.h right now, though this offer an alternative to having the callback handler exposed in headers like that I guess we need a proper discussion on what are the benefit vs shell_exec.

2017-06-09 22:54 UTC, nashif approved these changes

2017-06-09 22:54 UTC, merged