Bluetooth: controller: Set buffer size default for BT_HCI_RAW
zephyrproject-rtos/zephyr pull request #35168
Opened 2021-05-11 15:49 UTC by cvinayak

Set default Rx, Tx and Data Length exchange PDU sizes to
251 bytes when building BT_HCI_RAW.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2021-05-12 01:10 UTC, cvinayak commented
> I believe BT_CTLR_DATA_LENGTH_MAX has corresponding entries in the IXIT;

Yes. The design listing where done with 251 bytes in the IXIT for nRF52dk_nrf52832 hci_uart, hence the default hci_uart should be build to a conformant binary. So far, the binary where build after manually updating the prj conf file, which is subject to errors or needs porting like in this case, `BT_CTLR_TX_BUFFER_SIZE` is removed.

And for the LE Read Buffer Size command to return 251 bytes, `BT_BUF_ACL_TX_SIZE` too need a default that should build a conformant binary. (Refer to, https://github.com/zephyrproject-rtos/zephyr/blob/ed59ceba62cba8cf2ad0829784926fa6326ddca8/subsys/bluetooth/controller/hci/hci.c#L1169)

2021-05-12 06:35 UTC, joerchan commented
@cvinayak If we now build an HCI uart (or any of the others) application and a host application with a a matching HCI driver then their default configuration would be incompatible. Because the controller does not support the host setting a lower RX buffer size (see host buffer size command). Having incompatible defaults in split builds is not a good default.

If higher buffer sizes is needed for qualification we could add a kconfig fragment for qualification in HCI-uart sample.

2021-05-12 06:36 UTC, joerchan requested changes
Creates incompatible host and controller split builds in their default configuration.
Controller does not support the host setting a lower host buffer size than the controller in the Host Buffer Size command.

2021-05-12 07:03 UTC, cvinayak commented
> @cvinayak If we now build an HCI uart (or any of the others) application and a host application with a a matching HCI driver then their default configuration would be incompatible. Because the controller does not support the host setting a lower RX buffer size (see host buffer size command). Having incompatible defaults in split builds is not a good default.
> 
> If higher buffer sizes is needed for qualification we could add a kconfig fragment for qualification in HCI-uart sample.


> Creates incompatible host and controller split builds in their default configuration.

This is incorrect argument, upstream samples have been incompatible. Currently the upstream peripheral samples uses  `CONFIG_BT_BUF_ACL_RX_SIZE=69` (when `CONFIG_BT_CTLR=n`) and this is against the `CONFIG_BT_BUF_ACL_RX_SIZE=255` that is set in the upstream hci_uart.

Host should set the buffer size equal to or greater than the amount controller-to-host will be sent and not expect the controller to send lower buffer size unless using the controller to host flow control(in this case, as zephyr controller does not support hci fragmentation/assembly in the controller-to-host path, the buffer size need to be equal or else the HCI_Set_Host_Controller_To_Host_Flow_Control command will fail with Zephyr controller).

2021-05-12 07:23 UTC, joerchan commented
> This is incorrect argument, upstream samples have been incompatible. Currently the upstream peripheral samples uses CONFIG_BT_BUF_ACL_RX_SIZE=69 (when CONFIG_BT_CTLR=n) and this is against the CONFIG_BT_BUF_ACL_RX_SIZE=255 that is set in the upstream hci_uart.
> 
> The incompatibility was introduced here: bda438a

It's not incompatible, because the controller uses `CONFIG_BT_CTLR_DATA_LENGTH_MAX` as it's maximum RX buffer size.
But you are right,  `CONFIG_BT_BUF_ACL_RX_SIZE=255` could be removed from the HCI uart sample. We only need the CMD and EVT sizes to be larger to support extended advertising.

2021-05-12 07:45 UTC, cvinayak commented
@wopu-ot do you suggestion that default hci_uart supporting data length update procedure use the max length of 27 bytes? Spec is not against it, but it is just odd to set the minimum value.

2021-05-12 11:58 UTC, wopu-ot commented
> @wopu-ot do you suggestion that default hci_uart supporting data length update procedure use the max length of 27 bytes? Spec is not against it, but it is just odd to set the minimum value.

If the data length update procedure is enabled, a default data length > 27 bytes make senses. But that does not depend on HCI_RAW, that applies also to other builds.

2021-05-13 01:34 UTC, cvinayak commented
Closing this PR, will continue to use modified buffer size in prj conf file in a private branch to meet the conformance IXIT value of 251 bytes.

2021-05-13 01:34 UTC, closed without merging