soc: stm32f7 remove cache memory with dma transfer
zephyrproject-rtos/zephyr pull request #35165
Opened 2021-05-11 14:37 UTC by FRASTM

When using the DMA on stm32f7, the cache memory is disabled using the CONFIG_NOCACHE_MEMORY
This must be the case when running dma memory-to-memory transfers test cases
    `tests/driver/dma/chan_blen_transfer` and  `tests/driver/dma/loop_transfer`

on nucleo_f746zg (dma2 is already enabled in the dts of the board)

Signed-off-by: Francois Ramu <francois.ramu@st.com>

Fixes #35220

2021-05-11 15:18 UTC, erwango requested changes
If commit "drivers: dma: stm32 dmamux has request 0 for mem-to-mem" is fixing a bug, this should be clearly identified.

2021-05-11 15:18 UTC, erwango commented on tests/drivers/dma/loop_transfer/boards/nucleo_f746zg.conf
> +#CONFIG_NOCACHE_MEMORY=y
Remove the line rather than commenting it.

2021-05-11 15:18 UTC, erwango commented on tests/drivers/dma/chan_blen_transfer/boards/nucleo_f767zi.overlay
> +};
Is dma1 required in this case ?

2021-05-11 15:18 UTC, erwango commented on tests/drivers/dma/chan_blen_transfer/boards/nucleo_f767zi.overlay
> + * Copyright (c) 2020 Erwin Rol <erwin@erwinrol.com>
Use your copyright

2021-05-11 16:06 UTC, FRASTM commented on tests/drivers/dma/chan_blen_transfer/boards/nucleo_f767zi.overlay
> + * Copyright (c) 2020 Erwin Rol <erwin@erwinrol.com>
done

2021-05-12 11:08 UTC, FRASTM commented
single commit for this fix so that it is not mix with other PRs

2021-05-12 17:15 UTC, galak requested changes
I wonder if we need this fix for:

soc/arm/nxp_imx/rt/soc.c
soc/arm/atmel_sam/same70/soc.c
soc/arm/atmel_sam/samv71/soc.c

And if we should refactor that code into something come for M7's to do this in one place.

2021-05-12 17:15 UTC, galak commented
@mnkp - wonder if this same fix would address #35107

2021-05-12 18:01 UTC, mnkp requested changes
The implementation is incorrect. From the description of `NOCACHE_MEMORY` Kconfig option

>   Add a "nocache" read-write memory section that is configured to
  not be cached. This memory section can be used to perform DMA
  transfers when cache coherence issues are not optimal or can not
  be solved using cache maintenance operations.

The option adds support for a new, dedicated linker section. Only data placed in this specific section via `__nocache` pragma/macro are not cached. This PR disables completely instruction and data cache if `CONFIG_NOCACHE_MEMORY=y`.

2021-05-13 11:35 UTC, aurel32 commented
> The implementation is incorrect. From the description of `NOCACHE_MEMORY` Kconfig option
> 
> > Add a "nocache" read-write memory section that is configured to
> > not be cached. This memory section can be used to perform DMA
> > transfers when cache coherence issues are not optimal or can not
> > be solved using cache maintenance operations.
> 
> The option adds support for a new, dedicated linker section. Only data placed in this specific, limited RAM section via `__nocache` pragma/macro are not cached. This PR disables completely instruction and data cache if `CONFIG_NOCACHE_MEMORY=y`.

I fully agree with that. Now if that PR fixes the issue, it means that there is a cache issue somewhere, which can actually be fixed by using no cache memory *for that particular region*. Alternatively it should be possible to use cache invalidate / clean, but Zephyr still lacks a proper infrastructure to do that.

Both DMA and cache are supposed to improve performance. They should not be exclusive.

2021-05-13 12:02 UTC, aurel32 commented
I have been able to reproduce the issue on a stm32f723e_disco board. This happens every other boot and is definitely the same issue than #35107 and #35089. Reverting commit b160cb7cfea0cf128fca436b263de14f7ef31849 fixes the issue.

2021-05-13 12:22 UTC, galak commented
> I have been able to reproduce the issue on a stm32f723e_disco board. This happens every other boot and is definitely the same issue than #35107 and #35089. Reverting commit [d6b5023](https://github.com/zephyrproject-rtos/zephyr/commit/d6b50233acc7e27030bfbf1bd069d0f6969a4f68) fixes the issue.

Do we think there is a an ordering issue here between MPU init and cache init and that commit changed the order and thus broke M7?

2021-05-13 12:27 UTC, aurel32 commented
> > I have been able to reproduce the issue on a stm32f723e_disco board. This happens every other boot and is definitely the same issue than #35107 and #35089. Reverting commit [d6b5023](https://github.com/zephyrproject-rtos/zephyr/commit/d6b50233acc7e27030bfbf1bd069d0f6969a4f68) fixes the issue.
> 
> Do we think there is a an ordering issue here between MPU init and cache init and that commit changed the order and thus broke M7?

I have the impression that it worked by chance before and that the cache clean and invalidation is not done the proper way. For instance enabling `CONFIG_INIT_ARCH_HW_AT_BOOT` moves that cache clean and invalidation even earlier in the boot process, and also fails.

2021-05-13 13:10 UTC, aurel32 commented
I think the problem is with the clean part of the operation. By reorganizing the code, the call to `SCB_CleanInvalidateDCache()` happens before the D-cache is enabled. When the cache is not enabled, it might contain plenty of outdated cache lines from before the reset, and trying to clean them means pushing random data to random addresses, triggering a bus fault.

We should change that part to something like:
```
        if (SCB->CCR & SCB_CCR_DC_Msk) {
                SCB_CleanInvalidateDCache();
        } else {
                SCB_InvalidateDCache();
        }   
```

Now if we are sure that the D-cache is not enabled at this point, we can just call `SCB_InvalidateDCache()` instead.

For the `CONFIG_INIT_ARCH_HW_AT_BOOT` case, we should just drop `SCB_CleanInvalidateDCache()`, as `SCB_DisableDCache()` already takes care of cleaning and invaliding the cache.

2021-05-20 13:42 UTC, FRASTM commented
This patch is no more relevant since the https://github.com/zephyrproject-rtos/zephyr/pull/35258, isn't it

2021-05-20 14:44 UTC, closed without merging