tests: pm: Remove a platform from power_mgmt test
zephyrproject-rtos/zephyr pull request #35184
Opened 2021-05-11 21:53 UTC by ceolin

frdm_k64f does not implement power management, so just exclude it from
this test.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

2021-05-11 22:14 UTC, galak requested changes
This doesn't seem correct, if we excluded every platform that didn't implement powermgmt we'd have probably 80% of the boards listed.

Also, this feels weird since we have mps2_an385 listed as an integration platform and there isn't any power mgmt support there beyond what might exist in the core.

2021-05-12 13:37 UTC, galak commented
> Well the test is requires power management. If the platform does not implement any power state there is no way the application receive notification about state transition. Let me review the targets that this test should run. But again, this test is for targets that implement pm.

Is there some filter based on a Kconfig we should than add?  We need to fix the `integration_platforms` as well.  Don't know if qemu_x86 supports power mgmt or not.  Guessing the mps2 does not.

2021-05-12 15:20 UTC, ceolin commented
> > Well the test is requires power management. If the platform does not implement any power state there is no way the application receive notification about state transition. Let me review the targets that this test should run. But again, this test is for targets that implement pm.
> 
> Is there some filter based on a Kconfig we should than add? We need to fix the `integration_platforms` as well. Don't know if qemu_x86 supports power mgmt or not. Guessing the mps2 does not.

qemu does not define any idle state as well. Let me be clear, any target can build with power management enabled, if they don't implement any idle state the idle thread will just run k_cpu_idle(). The problem is that this test is expecting notifications about idle states transitions that obviously never happen since the target does not have any state other than ACTIVE. We have to run this sample only with targets that implement at least one idle state.

2021-05-12 23:42 UTC, mengxianglinx approved these changes

2021-05-13 05:58 UTC, ceolin commented
> > Well the test is requires power management. If the platform does not implement any power state there is no way the application receive notification about state transition. Let me review the targets that this test should run. But again, this test is for targets that implement pm.
> 
> Is there some filter based on a Kconfig we should than add? We need to fix the `integration_platforms` as well. Don't know if qemu_x86 supports power mgmt or not. Guessing the mps2 does not.

@galak it turns out that the test is implementing power management in the application. There is another test testing pm on different SoCs (https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/subsys/pm/power_mgmt_soc)

2021-05-13 12:19 UTC, galak commented
> > 
> 
> qemu does not define any idle state as well. Let me be clear, any target can build with power management enabled, if they don't implement any idle state the idle thread will just run k_cpu_idle(). The problem is that this test is expecting notifications about idle states transitions that obviously never happen since the target does not have any state other than ACTIVE. We have to run this sample only with targets that implement at least one idle state.

How do targets define the states?  Changing this to `platform_allow` seems limiting and remove a fair number of hardware platforms that actually could run this test.

2021-05-13 16:53 UTC, ceolin commented
> > > 
> > 
> > 
> > qemu does not define any idle state as well. Let me be clear, any target can build with power management enabled, if they don't implement any idle state the idle thread will just run k_cpu_idle(). The problem is that this test is expecting notifications about idle states transitions that obviously never happen since the target does not have any state other than ACTIVE. We have to run this sample only with targets that implement at least one idle state.
> 
> How do targets define the states? Changing this to `platform_allow` seems limiting and remove a fair number of hardware platforms that actually could run this test.

The test will exercise more code when soc does implement pm, but looking it better what was causing the issue is that a device was returning ENOSYS when pm was not implemented and the system was checking for ENOTSUP. This was fixed in https://github.com/zephyrproject-rtos/zephyr/pull/35233

2021-05-13 16:53 UTC, closed without merging