coding guidelines 4.1: fix literal zero as the null-ptr-constant
zephyrproject-rtos/zephyr pull request #35205
Opened 2021-05-12 07:21 UTC by maksimmasalski

File has next violations:
MISRA 4-1-H Avoid overflow when writing to a buffer

Function stats_reset() had wrong usage of the memset() to reset and zero
values of the structure members.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

2021-05-14 06:12 UTC, maksimmasalski commented
@nvlsianpu Hi, Github assigned you. Seems like you are a code owner of that part. Do you know why that can happen?

2021-05-14 08:39 UTC, maksimmasalski commented
I don't think function `void stats_reset` works correctly. You can try to add my debug print out. Then you can see structure data before and after call `memset` didn't change. I expect after call function `stats_reset` data recorded in the structure variables have to be zeroed. I tried on qemu_x86 and native_posix.
<b>Expected result (with my patch #35205 run on native_posix):</b>
```
STATS BEFORE RESET

address of struct hdr points to = 0x8055840
(uint8_t *)hdr = 0x8055840
sizeof(*hdr) = 24 byte
(uint8_t *)hdr + sizeof(*hdr) 0x8055858
hdr->s_size and hdr->s_cnt 4 6
hdr->s_size * hdr->s_cnt 24
hdr is (name (null), size 4, count 6, padding 0)
```
After call function `void stats_reset` it has to be:
```
STATS AFTER RESET

address of struct hdr points to = 0x8055840
(uint8_t *)hdr = 0x8055840
sizeof(*hdr) = 24 byte
(uint8_t *)hdr + sizeof(*hdr) 0x8055858
hdr->s_size and hdr->s_cnt 0 0
hdr->s_size * hdr->s_cnt 0
hdr is (name (null), size 0, count 0, padding 0)
```
<b>Current situation:</b>
With the existing codebase it doesn't happen. With the existing code data recorded in hdr->s_size and hdr->s_cnt before and after call `void stats_reset` is still existing. I submitted patch which I think correct, but it passes only for the native_posix, and works as I showed in the Expected result section. Unfortunately, it fails on the qemu_x86.

<b>You can add my printout into the default `void stats_reset` function to see it:</b>
```
void stats_reset(struct stats_hdr *hdr)
{
	printf("\n\nSTATS BEFORE RESET\n\n");
	printf("address of struct hdr points to = %p\n", hdr);
    printf("(uint8_t *)hdr = %p\n", (uint8_t *)hdr);
    printf("sizeof(*hdr) = %d byte\n", sizeof(*hdr));
    printf("(uint8_t *)hdr + sizeof(*hdr) %p\n", (uint8_t *)hdr + sizeof(*hdr));
    printf("hdr->s_size and hdr->s_cnt %d %d\n", hdr->s_size, hdr->s_cnt);
    printf("hdr->s_size * hdr->s_cnt %d\n", hdr->s_size * hdr->s_cnt);
	printf("hdr is (name %s, size %d, count %d, padding %d)\n\n", hdr->s_name, hdr->s_size, hdr->s_cnt, hdr->s_pad1);

(void)memset((uint8_t *)hdr + sizeof(*hdr), 0, hdr->s_size * hdr->s_cnt);

	printf("\n\nSTATS AFTER RESET\n\n");
	printf("address of struct hdr points to = %p\n", hdr);
    printf("(uint8_t *)hdr = %p\n", (uint8_t *)hdr);
    printf("sizeof(*hdr) = %d byte\n", sizeof(*hdr));
    printf("(uint8_t *)hdr + sizeof(*hdr) %p\n", (uint8_t *)hdr + sizeof(*hdr));
    printf("hdr->s_size and hdr->s_cnt %d %d\n", hdr->s_size, hdr->s_cnt);
    printf("hdr->s_size * hdr->s_cnt %d\n", hdr->s_size * hdr->s_cnt);
	printf("hdr is (name %s, size %d, count %d, padding %d)\n\n", hdr->s_name, hdr->s_size, hdr->s_cnt, hdr->s_pad1);
}
```

2021-05-17 07:16 UTC, maksimmasalski commented
@nashif @andyross Do you have fresh angle on that issue?

2021-05-19 16:56 UTC, jenmwms approved these changes

2021-06-02 00:53 UTC, andyross approved these changes

2021-06-07 13:59 UTC, galak commented
@maksimmasalski  can you fix the commit message issue.

2021-06-07 14:19 UTC, nvlsianpu requested changes
give me a while for looking into.
cc @de-nordic

2021-06-07 15:13 UTC, nvlsianpu requested changes
`struct stats_hdr *hdr` is the header of the statistics structure, contains things like statistic section name, size of statistics entries, number of statistics, etc. It ought to be keep during statistic reset.

The header is following by statistic data: s_count entries of s_size size.

2021-06-07 15:32 UTC, de-nordic requested changes
Agree with @nvlsianpu 

Look at the definition of the `STATS_SECT_START`: you will notice that it starts structure that contains `hdr` as first field and requires to be followed by `STATS_SECT_END`; between these two there is place for actual stat.
The contents of the  `hdr`, the one that you are unfortunately clearing here, are only initialized once, indirectly, usually by the invocation of `STATS_INIT_AND_REG`.
Example of usage is in `drivers/flash/flash_simulator.c`.

2021-06-08 02:37 UTC, maksimmasalski commented
> `struct stats_hdr *hdr` is the header of the statistics structure, contains things like statistic section name, size of statistics entries, number of statistics, etc. It ought to be keep during statistic reset.
> 
> The header is following by statistic data: s_count entries of s_size size.

Thank you for the detailed explanation.

2021-06-08 02:46 UTC, maksimmasalski commented
> STATS_SECT_START

I understand full content. hdr can not be cleaned.
`(void)memset((uint8_t *)hdr + sizeof(*hdr), 0, hdr->s_size * hdr->s_cnt);` cleans only the number of elements in the statistics structure multiple the size of the individual statistics element. Seems valid.
Probably close that PR.

2021-06-08 02:46 UTC, maksimmasalski commented
> Agree with @nvlsianpu
> 
> Look at the definition of the `STATS_SECT_START`: you will notice that it starts structure that contains `hdr` as first field and requires to be followed by `STATS_SECT_END`; between these two there is place for actual stat.
> The contents of the `hdr`, the one that you are unfortunately clearing here, are only initialized once, indirectly, usually by the invocation of `STATS_INIT_AND_REG`.
> Example of usage is in `drivers/flash/flash_simulator.c`.
> 
> The definition of the `stats_init` function explains purpose of the hdr fields.

You are always doing great explanations.

2021-06-08 06:12 UTC, nvlsianpu commented
> The header is following by statistic data: s_count entries of s_size size.

I mean that only statistic data has to be cleared, the header itself must be kept.

2021-06-08 06:54 UTC, de-nordic commented
> 
> 
> > STATS_SECT_START
> 
> I understand full content. hdr can not be cleaned.
> `(void)memset((uint8_t *)hdr + sizeof(*hdr), 0, hdr->s_size * hdr->s_cnt);` cleans only the number of elements in the statistics structure multiple the size of the individual statistics element. Seems valid.

Yes, exactly, although it is not done in the best way possible; we should probably rewrite the definitions so that additional field would be added, an unspecified size array, at the end of structure, and find the size to be cleared by the difference between the header and that field. But this is topic for some rework PR rather than MISRA fix.

2021-06-10 07:59 UTC, maksimmasalski commented
I will close it.

2021-06-10 07:59 UTC, closed without merging