kernel/sched: Remove "cooperative scheduling only" special cases
zephyrproject-rtos/zephyr pull request #35276
Opened 2021-05-13 22:53 UTC by andyross

The scheduler has historically had an API where an application can
inform the kernel that it will never create a thread that can be
preempted, and the kernel and architecture layer would use that as an
optimization hint to eliminate some code paths.

Those optimizations have dwindled to almost nothing at this point, and
they're now objectively a smaller impact than the special casing that
was required to handle the idle thread (which, obviously, must always
be preemptible).

Fix this by eliminating the idea of "cooperative only" and ensuring
that there will always be at least one preemptible priority with value
>=0.  CONFIG_NUM_PREEMPT_PRIORITIES now specifies the number of
user-accessible priorities other than the idle thread.

The only remaining workaround is that some older architectures (and
also SPARC) use the CONFIG_PREEMPT_ENABLED=n state as a hint to skip
thread switching on interrupt exit.  So detect exactly those platforms
and implement a minimal workaround in the idle loop (basically "just
call swap()") instead, with a big explanation.

Note that this also fixes a bug in one of the philosophers samples,
where it would ask for 6 cooperative priorities but then use values -7
through -2.  It was assuming the kernel would magically create a
cooperative priority for its idle thread, which wasn't correct even
before.

Fixes #34584

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

2021-05-13 23:06 UTC, dcpleung approved these changes

2021-05-14 12:43 UTC, nashif requested changes
with both CONFIG_NUM_PREEMPT_PRIORITIES=0  and CONFIG_NUM_COOP_PRIORITIES=0 we used to #error , now we are failing with build asserts in random locations, the #error is preferred.

2021-05-14 17:54 UTC, andyross commented
Fair enough, fixed.

2021-05-17 15:41 UTC, ceolin approved these changes

2021-05-18 21:29 UTC, mnkp commented
> The only remaining workaround is that some older architectures (and
also SPARC) use the CONFIG_PREEMPT_ENABLED=n state as a hint to skip
thread switching on interrupt exit.

If we want to remove "cooperative only scheduling" then we can't skip thread switching on the interrupt exit, isn't it? I would expect that it shouldn't be possible to compile with `CONFIG_NUM_PREEMPT_PRIORITIES=0` any more.

2021-05-18 22:00 UTC, nashif approved these changes

2021-05-25 03:38 UTC, merged