boards: arm: lpcxpresso55s69: Force TF-M when using NS boards
zephyrproject-rtos/zephyr pull request #35406
Opened 2021-05-18 16:41 UTC by microbuilder

This commit forces the `CONFIG_BUILD_WITH_TFM=y` option when using the `_ns` build targets for the LPC55sXX.

Using these targets in samples or in CI without an accompanying secure environment image (ex. TF-M) leads to execution failures, since the NS images are offset a predetermined amount.

Fixes #35100

## Test Output

```bash
$ ./scripts/twister -v --device-testing --build-only -p lpcxpresso55s69_ns -T tests/lib/sprintf
$ JLinkExe -device lpc55s69 -if swd -speed 2000 -autoconnect 1
```

Then in the JLink shell:

```
J-Linke>r
J-Link>erase
J-Link>loadfile twister-out/lpcxpresso55s69_ns/tests/lib/sprintf/libraries.libc.sprintf/tfm_merged.hex 
```

Serial output (post reset):

```
*** Booting Zephyr OS build zephyr-v2.5.0-3928-gfa836cc00d4f  ***
Running test suite test_sprintf
===================================================================
START - test_sprintf_misc
 PASS - test_sprintf_misc in 0.1 seconds
===================================================================
START - test_sprintf_double
 PASS - test_sprintf_double in 0.3 seconds
===================================================================
START - test_sprintf_integer
 PASS - test_sprintf_integer in 0.1 seconds
===================================================================
START - test_vsprintf
 PASS - test_vsprintf in 0.1 seconds
===================================================================
START - test_vsnprintf
 PASS - test_vsnprintf in 0.1 seconds
===================================================================
START - test_sprintf_string
 PASS - test_sprintf_string in 0.1 seconds
===================================================================
START - test_snprintf
 PASS - test_snprintf in 0.1 seconds
===================================================================
START - test_print
3
 PASS - test_print in 0.1 seconds
===================================================================
START - test_fprintf
3
 PASS - test_fprintf in 0.1 seconds
===================================================================
START - test_vfprintf
This 3
        3
/%/a/
11
 PASS - test_vfprintf in 0.3 seconds
===================================================================
START - test_vprintf
This 3
```

2021-05-18 16:44 UTC, galak requested changes
So only the LPC55S69 seems to have TFM support, so this doesn't make sense.

I still don't quite understand why we have `_ns` variants for 55s28 and 55s16 in zephyr.

2021-05-18 16:54 UTC, microbuilder commented
@henrikbrixandersen I'm a bit confused about the LPC55S16 and LPC55S28 having `_ns` targets here since neither of those boards are supported upstream in TF-M. What was the goal adding those, and do you have an out of tree solution for these targets? Just realized after creating this PR that only the LPC55S69 can really pull in TF-M today.

2021-05-18 17:08 UTC, microbuilder commented
> So only the LPC55S69 seems to have TFM support, so this doesn't make sense.
> 
> I still don't quite understand why we have `_ns` variants for 55s28 and 55s16 in zephyr.

Correct ... updated this to only force TF-M for the 55s69.

2021-05-18 19:49 UTC, henrikbrixandersen commented
@microbuilder I have submitted a PR for renaming the lpcxpresso55s16_ns to drop the _ns part: #35416

2021-05-18 20:30 UTC, galak approved these changes

2021-05-18 20:31 UTC, henrikbrixandersen approved these changes

2021-05-18 20:37 UTC, ioannisg requested changes
Does this need any documentation change? E.g. For nordic we write it down that tfm is build by default.

2021-05-19 10:08 UTC, microbuilder commented
> Does this need any documentation change? E.g. For nordic we write it down that tfm is build by default.

Good point ... fixed.

2021-05-19 13:11 UTC, galak commented
@ioannisg can you take another look

2021-05-19 13:44 UTC, ioannisg approved these changes

2021-05-19 15:47 UTC, mmahadevan108 commented on boards/arm/lpcxpresso55s69/doc/index.rst
>  To enable it, run one of the following samples in ``subsys\ipc``:
The documentation states we should flash tfm_merged.bin. I see only a .hex file, should this be updated to tfm_merged.hex

2021-05-19 18:05 UTC, mmahadevan108 approved these changes

2021-05-19 19:02 UTC, merged