Bluetooth: controller: Improve ticker_by_next_slot_get
zephyrproject-rtos/zephyr pull request #35535
Opened 2021-05-21 12:11 UTC by mtpr-ot

Fixes ticker_by_next_slot_get for JIT scheduler by allowing iterating
through ticker nodes without ticks_slot information, and improves
performance for legacy ticker scheduling use.

To reduce the processing and context switching overhead, a new feature
is introduced via BT_TICKER_NEXT_SLOT_GET_MATCH, by which an operation
callback may be added via the ticker_next_slot_get_ext interface, and
the match function is then called when the ticker_job is processing the
request.
By returning true in this callback, iteration stops and normal operation
callback is invoked. If the match function returns true, node iteration
continues. This reduces the number of ticker_job executions for node
iteration.

Signed-off-by: Morten Priess <mtpr@oticon.com>

2021-05-26 13:39 UTC, kruithofa approved these changes

2021-05-27 14:47 UTC, wopu-ot approved these changes

2021-06-07 10:07 UTC, carlescufi commented
@cvinayak please review

2021-06-08 05:49 UTC, cvinayak requested changes

2021-06-08 05:49 UTC, cvinayak commented on subsys/bluetooth/controller/ticker/ticker.c
> +				    uint16_t *lazy)
~Any reason to not conditional compile the parameters?~
Ok, I find that the constant `NULL` is passed in the calls to `ticker_by_next_slot_get` and compile should optimize out the code associated with these parameters.

2021-06-08 05:49 UTC, cvinayak commented on subsys/bluetooth/controller/ticker/ticker.c
> +		if (fp_match_op_func) {
Changes in this PR here, adds this additional branching instructions when `CONFIG_BT_TICKER_SLOT_AGNOSTIC`  and `CONFIG_BT_TICKER_NEXT_SLOT_GET_MATCH` are disabled. Add conditional compile here, as compiler/linker would not optimize this branching (based on static constant parameters if any like `fp_match_op_func`). Observed by building upstream/main peripheral_hr sample with and without this PR (149812 B with this PR vs 149796 B without this PR).

2021-06-08 13:26 UTC, cvinayak approved these changes

2021-06-11 14:18 UTC, merged