boards: stm32f429i_disc1 remove usart2 node
zephyrproject-rtos/zephyr pull request #35563
Opened 2021-05-23 15:51 UTC by fabiobaltieri

Hi, hit this while troubleshooting some suspiciously high power consumption readings on the board, turns out the current default config is causing the MCU to sink about 60mA into PA2, which is driven low by another chip (the line sits at about 1V). Looked into replace this with any of the other other 6 UARTs on this chip, but it looks like none of them have a usable TX/RX pair available, between the display and the SDRAM all the pins gets used, so I ended up just removing the node.

![f429-disc1-pa2](https://user-images.githubusercontent.com/891546/119267521-f0b1fa00-bbe6-11eb-9439-b0f7a0960562.png)

2021-05-25 07:45 UTC, ABOSTM requested changes
I am fine to remove uasrt2 due to conflict on the board on PA2.
Can you please update doc/index.rst to reflect this removal ?

2021-05-25 09:51 UTC, avisconti commented
> I am fine to remove uasrt2 due to conflict on the board on PA2.
> Can you please update doc/index.rst to reflect this removal ?

Yes, I agree!

2021-05-25 11:38 UTC, fabiobaltieri commented
> I am fine to remove uasrt2 due to conflict on the board on PA2.
> Can you please update doc/index.rst to reflect this removal ?

Oh yeah, done.

2021-05-25 11:38 UTC, fabiobaltieri commented
Sorry wrong button. :-)

2021-05-25 11:47 UTC, ABOSTM approved these changes
LGTM

2021-05-26 11:44 UTC, avisconti approved these changes

2021-06-04 21:15 UTC, merged