lib: check for null before dereferencing
zephyrproject-rtos/zephyr pull request #35654
Opened 2021-05-26 07:05 UTC by maksimmasalski

In a primitive SYS_SLIST_FOR_EACH_NODE check for null was
after dereferencing. Place check for null of the "thread_spec_data"
before its dereferencing.
As a result no need check if "key_obj->destructor" is not NULL.
Because if "thread_spec_data" is not NULL,
after "key_obj = thread_spec_data->key" won't be NULL too.

Found as a coding guideline violation (MISRA R4.1) by static
coding scanning tool.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

2021-05-26 16:52 UTC, dcpleung requested changes
`key_obj->destructor` can still be `NULL`, as it is expanded to `thread_spec_data->key->destructor`.

2021-05-26 17:39 UTC, pfalcon commented
Commit subject `lib: check for null before dereferencing` is not specific enough. It should be something like `posix: pthread_exit: check for null before dereferencing`.

2021-05-27 11:14 UTC, pfalcon approved these changes

2021-05-27 14:03 UTC, dcpleung approved these changes

2021-05-27 14:07 UTC, merged