docs: pm: System power management diagram
zephyrproject-rtos/zephyr pull request #35744
Opened 2021-05-27 20:48 UTC by ceolin

Add a diagram for system power management.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

2021-05-27 21:17 UTC, nashif commented
please fix the typo

2021-05-27 23:30 UTC, nashif approved these changes

2021-05-28 07:46 UTC, gmarull requested changes

2021-05-28 07:46 UTC, gmarull commented on doc/reference/power_management/index.rst
> +The following diagram described system power management:
```suggestion
The following diagram describes system power management:
```

2021-05-28 07:46 UTC, gmarull commented on doc/reference/power_management/system-pm.svg
> +<?xml version="1.0" encoding="UTF-8"?>
There are some style issues in tge diagram:

![image](https://user-images.githubusercontent.com/25011557/119948910-9d9ac700-bf99-11eb-869a-5f573eb071d7.png)

2021-06-01 17:11 UTC, gmarull approved these changes

2021-06-03 19:12 UTC, merged