drivers: timer: fix device PM usage
zephyrproject-rtos/zephyr pull request #35761
Opened 2021-05-28 10:08 UTC by gmarull

If a device does not implement device PM it needs to provide a NULL
pointer when defining the device. The `sys_clock` driver provided a weak
function returning `-ENOSYS`, so it did not follow the requirements.
This change requires drivers implementing device PM to select the
`TIMER_USE_PM_DEVICE` option. This will enable the
`sys_clock_device_ctrl` weak function, so that the driver can provide an
implementation.

2021-05-28 12:12 UTC, erwango approved these changes
Renaming `sys_clock_device_ctrl` to something more "PM aware" would be nice, but I guess this is not the good timing.
Approved

2021-05-28 12:38 UTC, gmarull commented
> Renaming `sys_clock_device_ctrl` to something more "PM aware" would be nice, but I guess this is not the good timing.
> Approved

Agreed, we can address it afterwards (this PR just fixes the issue)

2021-05-28 20:08 UTC, ceolin submitted a review, later dismissed

2021-05-28 20:17 UTC, ceolin commented
How this is a bug ? Isn't the system handling -ENOSYS properly ? I rather having the code handling it properly than adding a new build option.

2021-05-28 20:39 UTC, gmarull commented
Devices not implementing PM need to provide a NULL, not a function returning -ENOSYS. This will actually allow some further error handling simplifications.

2021-06-01 03:36 UTC, ceolin commented
> Devices not implementing PM need to provide a NULL, not a function returning -ENOSYS. This will actually allow some further error handling simplifications.

got it, but between have this an extra Kconfig symbol and keep this weak function returning ENOSYS I rather the last one. Thas is not a regular case, not discussion. But again, the code is already handling ENOSYS and unless we have a concrete reason and not "further error handling simplifications" I prefer not to have a Kconfig option.

2021-06-01 07:01 UTC, gmarull commented
> > Devices not implementing PM need to provide a NULL, not a function returning -ENOSYS. This will actually allow some further error handling simplifications.
> 
> 
> 
> got it, but between have this an extra Kconfig symbol and keep this weak function returning ENOSYS I rather the last one. Thas is not a regular case, not discussion. But again, the code is already handling ENOSYS and unless we have a concrete reason and not "further error handling simplifications" I prefer not to have a Kconfig option.

The problem here is that a device not implementing PM needs to provide NULL, not a function. This driver is not following the requirements, and so it has to be fixed. If you can think of a way that avoids a Kconfig option let's discuss it.

2021-06-03 07:49 UTC, ceolin commented
> > > Devices not implementing PM need to provide a NULL, not a function returning -ENOSYS. This will actually allow some further error handling simplifications.
> 
> 
> 
> got it, but between have this an extra Kconfig symbol and keep this weak function returning ENOSYS I rather the last one. Thas is not a regular case, not discussion. But again, the code is already handling ENOSYS and unless we have a concrete reason and not "further error handling simplifications" I prefer not to have a Kconfig option.

The problem here is that a device not implementing PM needs to provide NULL, not a function. This driver is not following the requirements, and so it has to be fixed. If you can think of a way that avoids a Kconfig option let's discuss it. 

@gmarull is this a hard requirement ? That is the whole point for me, I am not seeing this requirement anywhere, As far as I understood, devices that don't implement power management *can* set  (not obligated) it to NULL.
The other point is that this device *may* implement PM defining a strong symbol. It is not like the device  does not implement PM at all.

2021-06-03 08:02 UTC, gmarull commented
> @gmarull is this a hard requirement ? That is the whole point for me, I am not seeing this requirement anywhere, As far as I understood, devices that don't implement power management _can_ set (not obligated) it to NULL.
> The other point is that this device _may_ implement PM defining a strong symbol. It is not like the device does not implement PM at all.

It's true that docs mention _can_, but I think we should change that, it's probably the result of the previous method (a "noop" dummy function was used). In fact, "can be NULL" does not clarify what happens if it is not. This driver is the only one in-tree with such behavior, probably because of its design particularity (weak functions). I think it's better to be consistent, that is, use `NULL` if no PM is in place.

2021-06-04 17:28 UTC, ceolin reviewed
If it is not NULL is expected the function be used, there is nothing especial here. It is a very common pattern.
I don't think we have control over all device drivers. A device may support just one state (suspend) and return -ENOSYS for others (LOW_POWER for example). This patch is bringing more complexity that we need imho. I don't wat make a big deal with this though, if others agree with this patch I'm fine. But my opnion is that it does not worth adding this complexity.

2021-07-01 18:19 UTC, nashif requested changes
not a fan of adding those workaround kconfigs to handle such special cases, lets try and look at this driver class and see how we can improve it instead.

2021-08-04 12:51 UTC, gmarull commented
Closing, see #37435

2021-08-04 12:51 UTC, closed without merging