Bluetooth: tester: Add provisioning procedure, Config Client and Health Client tests support
zephyrproject-rtos/zephyr pull request #35774
Opened 2021-05-28 12:16 UTC by agata-ponitka

2021-06-04 09:40 UTC, trond-snekvik requested changes

2021-06-04 09:40 UTC, trond-snekvik commented on subsys/bluetooth/mesh/cfg_cli.c
> +		BT_WARN("Net Key Status key index does not match");
I believe this practice of warning about non-matching has stopped, as it just creates noise

2021-06-04 09:40 UTC, trond-snekvik commented on subsys/bluetooth/mesh/cfg_cli.c
> +		*param->phase = phase;
Check `param->phase == NULL` as well.
Same in the other two-parameter handlers

2021-06-04 09:40 UTC, trond-snekvik commented on subsys/bluetooth/mesh/cfg_cli.c
> +	BT_MESH_MODEL_BUF_DEFINE(msg, OP_NODE_IDENTITY_GET, 3);
Could be 2

2021-06-28 09:28 UTC, LingaoM commented
@agata-ponitka Can you choose time to continue to promote this PR?

2021-07-06 12:10 UTC, LingaoM approved these changes

2021-07-12 08:13 UTC, trond-snekvik requested changes
A couple of minor comments and one unresolved comment from the previous round :)

2021-07-12 08:13 UTC, trond-snekvik commented on include/bluetooth/mesh/cfg_cli.h
> +			       struct bt_mesh_cfg_mod_pub *pub, uint8_t *status);
Needs a vendor model variant as well

2021-07-15 13:54 UTC, trond-snekvik requested changes
You'll need to rebase on `main` to resolve the config client conflict. There's also an unresolved NULL pointer access above. 

Otherwise good :+1:

2021-07-15 13:54 UTC, trond-snekvik commented on subsys/bluetooth/mesh/cfg_cli.c
> +		*param->phase = phase;
Still could have `NULL` pointer access here

2021-07-21 15:49 UTC, trond-snekvik approved these changes

2021-07-22 10:32 UTC, cfriedt commented
@trond-snekvik - are all outstanding issues resolved? Ready to be merged?

2021-07-22 10:37 UTC, LingaoM approved these changes

2021-07-22 14:41 UTC, trond-snekvik commented
> @trond-snekvik - are all outstanding issues resolved? Ready to be merged?

Yep, good to go!

2021-07-22 19:41 UTC, jhedberg approved these changes

2021-07-22 19:41 UTC, merged