dfu: flash_img: Removing conditional compilation from header
zephyrproject-rtos/zephyr pull request #35798
Opened 2021-05-28 18:51 UTC by de-nordic

Applying Coding Guideline rule A.1: Conditional Compilation.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2021-05-28 18:51 UTC, nashif approved these changes

2021-05-31 13:23 UTC, ioannisg approved these changes

2021-05-31 18:16 UTC, nvlsianpu requested changes
what are consequences of that patch?

2021-05-31 19:21 UTC, nandojve commented
I think if you are removing this conditional, you should remove the CONFIG_IMG_ENABLE_IMAGE_CHECK KConfig symbol too.
The code will increase for those that don't use this feature.

2021-06-01 12:43 UTC, nvlsianpu commented
@nandojve @de-nordic That what concerns me. Zephyr is targeted for resource limited devices, we are using optional implementations everywhere for being able to reduce memory requirements.

nack for this patch

2021-06-10 00:41 UTC, nandojve commented
I prefer keep Kconfig symbol. Is still valid the use of IS_ENABLED(CONFIG_foo)? Is that a problem for MISRA rules etc?

2021-06-10 07:14 UTC, nvlsianpu commented
@de-nordic Regard documentation generation: you can add CONFIG_IMG_ENABLE_IMAGE_CHECK to [the PREDEFINED C macros list](https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/zephyr.doxyfile.in#L1968).

2021-06-10 07:58 UTC, de-nordic commented
> 
> 
> I prefer keep Kconfig symbol. Is still valid the use of IS_ENABLED(CONFIG_foo)? Is that a problem for MISRA rules etc?

This is not misra, this is https://docs.zephyrproject.org/latest/guides/coding_guidelines/index.html?highlight=coding%20guideline#rule-a-1-conditional-compilation, and I do not want to remove symbol,
I just "flatten" the header file while definitions in C compilation unit remain conditionally compiled.

There is no need to make declarations conditional, because unless the functions are used they will not be linked, and when they are used but not enabled via Kconfig you will get linker error anyway.

The change applies rule https://docs.zephyrproject.org/latest/guides/coding_guidelines/index.html?highlight=coding%20guideline#rule-a-1-conditional-compilation

2021-06-10 09:54 UTC, nvlsianpu commented
^^ @de-nordic I missed that. OK, although I'm not agree with rationale behind paragraph your mentioned.
So fare we were using PREDEFINED list, it is working just fine. 
User will encounter only linking error instead of missing prototype + linking error. I hope that no-operation API stumps won't be requested.

So can you add note to each function description that need to enable CONFIG_IMG_ENABLE_IMAGE_CHECK if it is used?

2021-06-18 06:44 UTC, de-nordic commented
> 
> 
> ^^ @de-nordic I missed that. OK, although I'm not agree with rationale behind paragraph your mentioned.
> So fare we were using PREDEFINED list, it is working just fine.
> User will encounter only linking error instead of missing prototype + linking error. I hope that no-operation API stumps won't be requested.
> 
> So can you add note to each function description that need to enable CONFIG_IMG_ENABLE_IMAGE_CHECK if it is used?

Wait with re-review, I will be doing the additions.

2021-06-29 09:47 UTC, nvlsianpu approved these changes

2021-06-29 12:13 UTC, nandojve commented
Hi @de-nordic ,

Are there any reason to keep IMG_ENABLE_IMAGE_CHECK symbol at Kconfig ?

2021-06-29 12:19 UTC, de-nordic commented
> Kconfig

@nandojve  The function, within C source file is still, conditionally, compiled. So you may choose to have it or not.
You have introduced the Kconfig option with the supporting functions, question is whether you want to keep it? If you abandon it, the source that support the option will always be compiled, even if not used.

2021-06-29 12:38 UTC, merged