cmake: Support coverage flags on all archs
zephyrproject-rtos/zephyr pull request #35925
Opened 2021-06-03 20:38 UTC by jeremybettis

Most arch's CMakeLists.txt contain rules to add compiler and linker
flags for coverage if CONFIG_COVERAGE is enabled, but 4 of them were
missing this.

Signed-off-by: Jeremy Bettis <jbettis@chromium.org>

2021-06-03 20:51 UTC, dcpleung approved these changes

2021-06-03 22:03 UTC, keith-zephyr approved these changes

2021-06-04 01:09 UTC, galak requested changes
If we are supporting this on all arch's seems like we can put this in a common place rather than duplicating it everywhere.

2021-06-04 09:28 UTC, carlescufi commented
> If we are supporting this on all arch's seems like we can put this in a common place rather than duplicating it everywhere.

@tejlmand could you please weigh in here?

2021-06-04 16:18 UTC, jeremybettis commented
> If we are supporting this on all arch's seems like we can put this in a common place rather than duplicating it everywhere.

Alright, I moved this to arch/common/CMakeLists.txt and removed the redundant copies.

2021-06-04 16:22 UTC, carlocaione approved these changes

2021-06-04 16:47 UTC, nashif approved these changes

2021-06-04 17:18 UTC, keith-zephyr approved these changes

2021-06-07 07:56 UTC, ruuddw approved these changes

2021-06-07 16:03 UTC, jeremybettis commented
@galak I don't know how to clear the requested changes you asked for, and merging is blocked because of that.

2021-06-08 08:51 UTC, tejlmand requested changes
> > If we are supporting this on all arch's seems like we can put this in a common place rather than duplicating it everywhere.
> 
> Alright, I moved this to arch/common/CMakeLists.txt and removed the redundant copies.

Thanks, having this in a single place makes things much cleaner.

But could you please update the commit message to reflect the new changes, which is that you actually place this in a common place, so that all archs are covered.

The commit message currently says:
> Most arch's CMakeLists.txt contain rules to add compiler and linker
flags for coverage if CONFIG_COVERAGE is enabled, but 4 of them were
missing this.

2021-06-08 08:57 UTC, ioannisg requested changes
As @tejlmand suggests, this needs a minor update to the commit message, indicating that the coverage flags are moved to the common ARCH place.

2021-06-09 17:03 UTC, galak approved these changes

2021-06-09 19:05 UTC, aescolar approved these changes

2021-06-10 13:28 UTC, closed without merging