twister: try to clean ninja zombie
zephyrproject-rtos/zephyr pull request #36257
Opened 2021-06-15 09:18 UTC by wangnuannuan

When run a testcase on QEMU, but qemu isn't launched, the `QEMU_PIPE` will not be created, then the twister will block at https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L951 until testcase [timeout](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L1119), then the ninja process will be kill, but the parent process can't deal ninja process's signal, because the parent process block at https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L1150, then the twister will block at https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L3377. 
```
$ ps -aux | grep relauto
...
relauto  11557  0.0  0.0 135828  1300 ?        Ss   May29   0:00 tcsh -c source /global/etc/modules.csh && module load git git_lfs && cd "/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03" && /u/relauto/.RELAUTO_JAVA/java -Xmx1G -jar remoting.jar -workDir ./ -jar-cache .//remoting/jarCache
relauto  11608  0.8  0.6 7971288 396832 ?      Sl   May29 154:14 /u/relauto/.RELAUTO_JAVA/java -Xmx1G -jar remoting.jar -workDir ./ -jar-cache .//remoting/jarCache
relauto  13217  0.0  0.0      0     0 ?        Z    02:47   0:00 [ninja] <defunct>
relauto  13416  0.0  0.0      0     0 ?        Z    02:47   0:00 [ninja] <defunct>
relauto  13899  0.0  0.0 113180   636 ?        S    02:07   0:00 sh -c ({ while [ -d '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587' -a \! -f '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt' ]; do touch '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-log.txt'; sleep 3; done } & jsc=durable-1ea490dce05e997dfdcc2605441adb32; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/script.sh' > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-log.txt' 2>&1; echo $? > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt.tmp'; mv '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt.tmp' '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt'; wait) >&- 2>&- &
relauto  13900  0.0  0.0 113308   904 ?        S    02:07   0:01 sh -c ({ while [ -d '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587' -a \! -f '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt' ]; do touch '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-log.txt'; sleep 3; done } & jsc=durable-1ea490dce05e997dfdcc2605441adb32; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/script.sh' > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-log.txt' 2>&1; echo $? > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt.tmp'; mv '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt.tmp' '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/jenkins-result.txt'; wait) >&- 2>&- &
relauto  13901  0.0  0.0 113188  1220 ?        S    02:07   0:00 sh -xe /slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-2-tmp/durable-230cb587/script.sh
relauto  13904  0.0  0.0 113456  1900 ?        S    02:07   0:00 /bin/bash -eux ./jenkins-jobs/zephyr-sanity-check/sanity-check.sh main
relauto  13960  0.0  0.0 113180   636 ?        S    02:07   0:00 sh -c ({ while [ -d '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff' -a \! -f '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt' ]; do touch '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-log.txt'; sleep 3; done } & jsc=durable-40ee1a504ff8bb3260009eb2a2e9e228; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/script.sh' > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-log.txt' 2>&1; echo $? > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt.tmp'; mv '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt.tmp' '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt'; wait) >&- 2>&- &
relauto  13961  0.0  0.0 113308   900 ?        S    02:07   0:01 sh -c ({ while [ -d '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff' -a \! -f '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt' ]; do touch '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-log.txt'; sleep 3; done } & jsc=durable-40ee1a504ff8bb3260009eb2a2e9e228; JENKINS_SERVER_COOKIE=$jsc 'sh' -xe  '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/script.sh' > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-log.txt' 2>&1; echo $? > '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.txt.tmp'; mv '/slowfs/ru20arcjenkins/de02-arcjenkins2/slaves/ru20-gp-srv-linux03/workspace/arcoss_verification/zephyr_verification/sanity_check-3-tmp/durable-77b892ff/jenkins-result.tx [...]

2021-06-17 10:00 UTC, hakehuang approved these changes

2021-06-17 10:00 UTC, hakehuang commented on scripts/pylib/twister/twisterlib.py
> +                time.sleep(0.5)
why add a sleep here?

2021-06-21 01:51 UTC, wangnuannuan commented on scripts/pylib/twister/twisterlib.py
> +                time.sleep(0.5)
I referenced https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L463

2021-06-22 09:21 UTC, ruuddw approved these changes

2021-06-22 14:13 UTC, PerMac requested changes
Maybe you could refactor the twisterlib.py a bit?  As you pointed out, you are copying the code from https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib.py#L450 IMO it would be the cleanest if you'd extract the `terminate(self, proc)` method from BinaryHandler class, and call this method instead of copying the code. The `self` is only used there to set `self.terminated = True`. Maybe this line can be added wherever `BinaryHandler.teminate(self, proc)` is used originally? Or even after extracting this method you can overwrite it in the BinaryHandler, by calling the extracted method and adding  `self.terminated = True`. Then no need of changes would be needed in the rest of the code.
Then the `terminate` method wouldn't be bonded to BinaryHandler and could be used to terminate any subprocess? 
I am giving +/- now, just to raise this idea. Feel free to dismiss my review if you consider such work pointless. IMO this could be a tiny step towards making twister more maintainable. 
In fact, I can do this myself, will link PR in a sec

2021-06-23 03:37 UTC, wangnuannuan commented
@PerMac I set `terminate` as the `Handle`r's method, then `Handler`'s children class can call it. What do you think this?

2021-06-23 07:14 UTC, PerMac approved these changes

2021-06-23 10:10 UTC, nashif approved these changes

2021-06-23 10:10 UTC, merged