ARM: misc enhancements & fixes for LTS
zephyrproject-rtos/zephyr pull request #36333
Opened 2021-06-16 15:27 UTC by ioannisg

Collection of fixes and improvements for the ARM architecture port

2021-07-28 08:57 UTC, julien-massot approved these changes

2021-07-28 13:47 UTC, bbolen requested changes

2021-07-28 15:30 UTC, ioannisg commented on arch/arm/core/aarch32/cortex_m/vector_table.S
> -    .word 0
thanks, fixed.

2021-07-28 15:30 UTC, ioannisg commented on arch/arm/core/aarch32/Kconfig
> -	  The platform specific initialization code (z_platform_init) is executed
thanks, fixed

2021-07-28 15:30 UTC, ioannisg commented on arch/arm/core/aarch32/cortex_a_r/reset.S
> -GTEXT(z_platform_init)
done

2021-07-28 22:57 UTC, cfriedt commented on soc/arm/nxp_lpc/lpc54xxx/gcc/startup_LPC54114_cm4.S
> +/*
@ioannisg - this one and the one above do not seem exactly miscellaneous. Should they be included here or possibly in a separate PR?

2021-07-29 00:14 UTC, bbolen approved these changes

2021-07-29 01:08 UTC, merged