soc: atmel: sam4l: Enable RC32K osc
zephyrproject-rtos/zephyr pull request #36406
Opened 2021-06-19 01:56 UTC by nandojve

Enable sam4l internal factory calibrated RC32K clock source.  The RC32K was used as source for Generic Clock 5 using 32 as divider.  The output is a 1024 Hz clock that can be used by GLOC and TC0 peripherals.

This PR is necessary to enable a slow clock that can be used by TC driver at #36195.
Currently, there is no dependencies to this change.

Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>

2021-06-21 22:05 UTC, mnkp requested changes
This feels like too much of a shortcut. We shouldn't make decisions on behalf of the application but rather provide tools for it to use.

Rather than configuring Generic Clock 5 to an arbitrary value we should provide a 'driver' for a Generic Clock module. Probably the best way to go about it is to model the module as `clock-controller` DTS node. Something similar to how it's done for samd5x Generic Clock module:
- dts/bindings/clock/atmel,samd5x-gclk.yaml
- dts/arm/atmel/samd5x.dtsi

But that's going to be quite some work.

2021-06-21 22:15 UTC, nandojve commented
> This feels like too much of a shortcut. We shouldn't make decisions on behalf of the application but rather provide tools for it to use.
> 
> Rather than configuring Generic Clock 5 to an arbitrary value we should provide a 'driver' for a Generic Clock module. Probably the best way to go about it is to model the module as `clock-controller` DTS node. Something similar to how it's done for samd5x Generic Clock module:
> 
> * dts/bindings/clock/atmel,samd5x-gclk.yaml
> * dts/arm/atmel/samd5x.dtsi
> 
> But that's going to be quite some work.

Hi @mnkp ,

I agreed this is not optimal and I have plans to work with `clock-controller` in future. This is the short cut that I can submit right now to have a slow clock on SAM4L. GCLK-5 is connected only for TC0 and GLOC peripherals. GLOC doesn't have a driver yet too. If it is enabled there will be no damage, only an minimal increase in power. At least users can see TC working.

If that is a problem I'm OK to close this PR for now.

2021-06-21 22:46 UTC, mnkp commented
I would rather wait for the proper implementation. But if others feel differently I'm not going to oppose.

2021-07-21 21:24 UTC, cfriedt commented
@nandojve - should this one be closed for now?

2021-07-21 21:27 UTC, nandojve commented
Hi @cfriedt ,

Yes, let's do it!

thks!

2021-07-21 21:27 UTC, closed without merging