gpio: additional `struct gpio_dt_spec` helper functions
zephyrproject-rtos/zephyr pull request #36477
Opened 2021-06-23 11:01 UTC by JordanYates

Add helpers to allow providing a `struct gpio_spec_dt` directly to `gpio_pin_get`, `gpio_pin_set` and `gpio_pin_toggle` functions. The intention of this PR is to simplify GPIO usage in the same vein as `gpio_pin_configure_dt` and gpio_pin_configure_interrupt_dt`.

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

2021-06-23 11:50 UTC, stephanosio requested changes
`gpio_pin_set_dt` seems to have been affected by copypasta.

2021-06-23 11:50 UTC, stephanosio commented on include/drivers/gpio.h
> +}
This doesn't seem right.

2021-06-23 12:29 UTC, JordanYates commented on include/drivers/gpio.h
> +}
The dreaded copypasta :( fixed

2021-06-23 12:48 UTC, mnkp approved these changes

2021-06-23 12:59 UTC, stephanosio approved these changes

2021-06-23 15:30 UTC, mbolivar-nordic approved these changes

2021-06-24 11:39 UTC, henrikbrixandersen approved these changes

2021-06-24 11:40 UTC, merged