tests: net: ethernet_mgmt: skip tests if no HW support
zephyrproject-rtos/zephyr pull request #36563
Opened 2021-06-25 21:00 UTC by dleach02

Some of the test cases will call net_mgmt() functions that return
-ENOTSUP. If that is the error then skip that test.

This occurs because a number of the net_mgmt() queries will
use api->get_config() call which is only supported on a few
Ethernet drivers.

Signed-off-by: David Leach <david.leach@nxp.com>

2021-06-27 15:05 UTC, hakehuang approved these changes
this fix works

2021-06-28 07:06 UTC, rlubos approved these changes

2021-06-28 07:44 UTC, jukkar requested changes
The test will certainly pass now when running on frdm_k64f, but I think this should be fixed so that that the Ethernet driver is skipped for board specific Ethernet interface. The test should use the simulated Ethernet interface that is provided by the test itself. Now the test is using the Ethernet interface provided by frdm_k64f which is not the intended way and this test does not test the configuration setting functionality when running on frdm_k64f.
Similar kind of issues have been fixed earlier but this seems to have been missed.

2021-06-28 08:17 UTC, jukkar commented
This should be fixed at run time by not calling `net_if_get_default()` directly but like this:
```
diff --git a/tests/net/ethernet_mgmt/src/main.c b/tests/net/ethernet_mgmt/src/main.c
index c4b59ea5fd..85fe6fb9d2 100644
--- a/tests/net/ethernet_mgmt/src/main.c
+++ b/tests/net/ethernet_mgmt/src/main.c
@@ -898,7 +898,7 @@ static void test_change_qav_params(void)
 
 static void test_change_qbv_params(void)
 {
-       struct net_if *iface = net_if_get_default();
+       struct net_if *iface = default_iface;
        const struct device *dev = net_if_get_device(iface);
        struct eth_fake_context *ctx = dev->data;
        struct ethernet_req_params params;
@@ -1075,7 +1075,7 @@ static void test_change_qbv_params(void)
 
 static void test_change_qbu_params(void)
 {
-       struct net_if *iface = net_if_get_default();
+       struct net_if *iface = default_iface;
        const struct device *dev = net_if_get_device(iface);
        struct eth_fake_context *ctx = dev->data;
        struct ethernet_req_params params;
@@ -1276,7 +1276,7 @@ static void test_change_qbu_params(void)
 
 static void test_change_txtime_params(void)
 {
-       struct net_if *iface = net_if_get_default();
+       struct net_if *iface = default_iface;
        const struct device *dev = net_if_get_device(iface);
        struct eth_fake_context *ctx = dev->data;
        struct ethernet_req_params params;
```
Sorry for causing this issue in the first place, I missed the fact that you guys are running the test in such a hw that has onboard Ethernet controller. I should have not called `net_if_get_default()` in my patch that introduced these couple of new tests.

2021-06-29 19:52 UTC, dleach02 commented
@jukkar do we need to make a pass across all the ethernet tests to avoid this? I'm pretty sure this is the second ethernet test we had issues with where the other needed us to retrieve the DUMMY interface instead of the real interface.

2021-06-30 06:46 UTC, jukkar commented
@dleach02 Probably not, if you do not see any issues in other tests, then they are ok.

The tests in `tests/net/ethernet_mgmt` were fixed by commit 6e1df0d603a52e507105217757738d557e0600c9 when running in a board that has an Ethernet controller. Then I introduced new tests in PR #35593 but I missed the fact that I should not have called the `net_if_get_default()` but used the `default_iface` variable that I introduced by that earlier commit. The diff I added above should fix the issue you are seeing when running in frdm_k64f

2021-07-16 16:22 UTC, dleach02 commented
The correct way to fix this was submitted under a different PR

2021-07-16 16:22 UTC, closed without merging