npcx: fit the booter's behavior in different NPCX series
zephyrproject-rtos/zephyr pull request #37330
Opened 2021-07-30 10:13 UTC by ChiHuaL

The booter (bootloader) behavior may be different in different NPCX chip series. One example is that the booter sets the host interface type in NPCX7 series but leaves the firmware to set it in NPCX9 series.  
This PR do the following:
1. adds a new DT node to record variants in its properties.
2. add an API function to select the host interface type.
3. set the host interface type in eSPI driver explicitly if it is not set by the booter.

2021-07-30 18:28 UTC, keith-zephyr requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330)* status: all files reviewed, 2 unresolved discussions (waiting on @albertofloyd, @ChiHuaL, @galak, @jackrosenthal, @mbolivar-nordic, @MulinChao, @scottwcpg, @sjg20, @ssekar15, @VenkatKotakonda, and @WealianLiao)

___
*[drivers/espi/espi_npcx.c, line 861 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330#-MfseU2oE5-YktTyiNF4:-MfseU2oE5-YktTyiNF5:b-imo3z) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fd7980b38934acd9d732da12f1ba4d3ad850da59/drivers/espi/espi_npcx.c#L861)):*
> ```C
> 	/* If booter doesn't set the host interface type */
> 	if (!NPCX_BOOTER_IS_HIF_TYPE_SET()) {
> 		npcx_host_interface_sel(NPCX_HIF_TYPE_ESPI_SHI);
> ```

Is there a pending chromium change to also call npcx_host_interface_sel() when SHI is used?
___
*[dts/bindings/misc/nuvoton,npcx-booter-variant.yaml, line 15 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330#-MfsdsVwAh1GvMcSBa2v:-MfsdsVwAh1GvMcSBa2w:b-rjwwe8) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fd7980b38934acd9d732da12f1ba4d3ad850da59/dts/bindings/misc/nuvoton,npcx-booter-variant.yaml#L15)):*
> ```
>             The host interface type (LPC/eSPI/SHI) is configured by booter
>             if true;
>             otherwise, it should be configured by the firmware.
> ```
Please fix the line wrapping.


<!-- Sent from Reviewable.io -->

2021-07-30 21:30 UTC, mbolivar-nordic commented on soc/arm/nuvoton_npcx/common/soc_dt.h
> +	DT_PROP(DT_INST(0, nuvoton_npcx_booter_variant), hif_type_auto)
Interesting use of DT.

I think `DT_PROP(DT_PATH(soc, booter_variant), hif_type_auto)` would be a bit more robust if you're always going to have this node at `/soc/booter-variant`. Sometimes people get confused and try to add nodes of different compatibles. If that happens here, you wouldn't be sure which node you're reading from if you use instance numbers.

Just something to consider; feel free to disregard.

2021-08-02 05:38 UTC, ChiHuaL reviewed
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @albertofloyd, @ChiHuaL, @galak, @jackrosenthal, @keith-zephyr, @MulinChao, @scottwcpg, @sjg20, @ssekar15, @VenkatKotakonda, and @WealianLiao)

___
*[drivers/espi/espi_npcx.c, line 861 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330#-MfseU2oE5-YktTyiNF4:-Mg4LxfS-3zefReiyAsg:b-ry44oo) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fd7980b38934acd9d732da12f1ba4d3ad850da59/drivers/espi/espi_npcx.c#L861)):*
<details><summary><i>Previously, keith-zephyr (Keith Short) wrote…</i></summary><blockquote>

Is there a pending chromium change to also call npcx_host_interface_sel() when SHI is used?
</blockquote></details>

For SHI driver, it also needs to call npcx_host_interface_sel() here:
https://chromium.googlesource.com/chromiumos/platform/ec/+/refs/heads/main/zephyr/drivers/cros_shi/cros_shi_npcx.c#817
We will prepare a CL to do that.
___
*[dts/bindings/misc/nuvoton,npcx-booter-variant.yaml, line 15 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330#-MfsdsVwAh1GvMcSBa2v:-Mg4MP56C9QEKCN_SVAh:b-896fix) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fd7980b38934acd9d732da12f1ba4d3ad850da59/dts/bindings/misc/nuvoton,npcx-booter-variant.yaml#L15)):*
<details><summary><i>Previously, keith-zephyr (Keith Short) wrote…</i></summary><blockquote>

> ```
>             The host interface type (LPC/eSPI/SHI) is configured by booter
>             if true;
>             otherwise, it should be configured by the firmware.
> ```
Please fix the line wrapping.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 05:38 UTC, ChiHuaL reviewed
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @albertofloyd, @galak, @jackrosenthal, @keith-zephyr, @mbolivar-nordic, @MulinChao, @scottwcpg, @sjg20, @ssekar15, @VenkatKotakonda, and @WealianLiao)

___
*[soc/arm/nuvoton_npcx/common/soc_dt.h, line 718 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330#-MfsZfbMDN3jIFaRVuUR-r1-718:-Mg4Miij1_rHOAPezcT7:b-896fix) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fd7980b38934acd9d732da12f1ba4d3ad850da59/soc/arm/nuvoton_npcx/common/soc_dt.h#L718)):*
<details><summary><i>Previously, mbolivar-nordic (Marti Bolivar) wrote…</i></summary><blockquote>

Interesting use of DT.

I think `DT_PROP(DT_PATH(soc, booter_variant), hif_type_auto)` would be a bit more robust if you're always going to have this node at `/soc/booter-variant`. Sometimes people get confused and try to add nodes of different compatibles. If that happens here, you wouldn't be sure which node you're reading from if you use instance numbers.

Just something to consider; feel free to disregard.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 14:32 UTC, keith-zephyr approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37330)* status: all files reviewed, 1 unresolved discussion (waiting on @albertofloyd, @galak, @jackrosenthal, @mbolivar-nordic, @MulinChao, @scottwcpg, @sjg20, @ssekar15, @VenkatKotakonda, and @WealianLiao)



<!-- Sent from Reviewable.io -->

2021-08-02 19:03 UTC, mbolivar-nordic approved these changes

2021-08-02 20:35 UTC, jackrosenthal approved these changes

2021-08-03 11:59 UTC, merged