Telink b91 I2C Driver Support
zephyrproject-rtos/zephyr pull request #37334
Opened 2021-07-30 13:56 UTC by yurvyn

2021-08-10 12:16 UTC, yurvyn commented
Please approve the PR if you are OK with the changes.

2021-08-12 08:08 UTC, yurvyn commented
Two approvals required.
Could anyone please approve the PR?

2021-08-17 08:11 UTC, yurvyn commented
@kgugala, @pgielda
Since you are owners of most of the files in this PR, could you please approve it?
Thanks.

2021-08-25 08:36 UTC, yurvyn commented
@galak, @kgugala, @nashif, @pgielda

There no any activity in this PR for 26 days already.
Could you please assign someone for this PR?

2021-08-27 15:50 UTC, mbolivar-nordic requested changes
I noticed a few minor things, otherwise looks fine to me.

2021-08-30 09:59 UTC, yurvyn commented on drivers/i2c/i2c_b91.c
> +#define I2C_CFG(dev)                    ((struct i2c_b91_cfg *) ((dev)->config))
Done.

2021-08-30 09:59 UTC, yurvyn commented on drivers/i2c/i2c_b91.c
> +#define I2C_DATA(dev)                   ((struct i2c_b91_data *) ((dev)->data))
Done.

2021-08-30 10:00 UTC, yurvyn commented on drivers/i2c/i2c_b91.c
> +
Done.

2021-08-30 10:00 UTC, yurvyn commented on drivers/i2c/i2c_b91.c
> +
Done.

2021-08-30 10:00 UTC, yurvyn commented on drivers/i2c/i2c_b91.c
> +	DEVICE_DT_INST_DEFINE(0, i2c_b91_init,			  \
Done.

2021-08-30 18:33 UTC, mbolivar-nordic approved these changes

2021-08-31 07:27 UTC, yurvyn commented
@carlescufi, @tbursztyka 

One more approval is left.
Could you please approver the PR?

2021-09-01 08:07 UTC, yurvyn commented
Hello @cfriedt 

This PR is not assigned for more than 30 days, but already has 1 approval.
Could you please approve and merge it?

2021-09-01 10:36 UTC, cfriedt approved these changes

2021-09-01 10:36 UTC, merged