runners: jlink: Add support for specifying a serial number
zephyrproject-rtos/zephyr pull request #37337
Opened 2021-07-30 14:57 UTC by carlescufi

Handle serial numbers provided from the command-line instead of forcing
the user to provide 'tool-opt' manually.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2021-07-30 14:58 UTC, carlescufi commented
Note: I suggest we get this in first, then consider unifying the `--snr` option for all runners.

2021-07-30 21:52 UTC, mbolivar-nordic requested changes
Thanks for the patch. I think `--snr` is too nrfjprog-centric though, as discussed on slack. Putting a -1 on for now as a result.

It seemed like there was some agreement on `--id`; will that work?

2021-07-31 12:14 UTC, carlescufi commented
> Thanks for the patch. I think `--snr` is too nrfjprog-centric though, as discussed on slack. Putting a -1 on for now as a result.
> 
> It seemed like there was some agreement on `--id`; will that work?

The reason I chose `--snr` is that J-Link itself uses "Serial Number", and so it seemed like the best choice for a J-Link centric option.

2021-08-02 10:35 UTC, carlescufi commented
CC @tsrinivasanece

2021-08-02 10:51 UTC, tsrinivasanece approved these changes
Verified  the changes in our platform. When multiple debugger connected, able to fetch the right debugger using --snr command.

2021-08-03 14:23 UTC, mbolivar-nordic approved these changes

2021-08-03 14:36 UTC, carlescufi commented
This now uses `--id` for J-Link, and will generalize this in a subsequent PR.

2021-08-03 14:50 UTC, MaureenHelm approved these changes

2021-08-03 15:39 UTC, merged