host: l2cap: assign mtu and mps when chan is found
zephyrproject-rtos/zephyr pull request #37566
Opened 2021-08-10 09:11 UTC by KKopyscinski

In while loop there is a series of checks for valid request, starting
with finding matchin CID. If chan was not found assignment still took
place, leading to crash with MPU FAULT. Now new mtu and mps values
will be assigned only for valid channels.

Signed-off-by: Krzysztof Kopyściński <krzysztof.kopyscinski@codecoup.pl>

2021-08-10 09:14 UTC, KKopyscinski commented
FYI @sjanc

2021-08-23 11:02 UTC, Thalley requested changes

2021-08-23 11:02 UTC, Thalley commented on subsys/bluetooth/host/l2cap.c
>  	}
Why not use a for loop to make it more readable? 
```suggestion
	for (int i = 0; i < chan_count; i++) {
		BT_L2CAP_LE_CHAN(chans[i])->tx.mtu = mtu;
		BT_L2CAP_LE_CHAN(chans[i])->tx.mps = mps;
	}
```

Then the value of `chan_count` also remain valid.

2021-08-25 12:37 UTC, michal-narajowski commented
Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/37778.

2021-08-25 12:37 UTC, closed without merging