mpu6050: add i2c aux bypass
zephyrproject-rtos/zephyr pull request #37801
Opened 2021-08-19 17:47 UTC by ric96

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2021-08-20 20:15 UTC, MaureenHelm approved these changes

2021-08-23 12:14 UTC, avisconti requested changes
Please correct typos in the commit message

2021-08-23 12:14 UTC, avisconti commented on drivers/sensor/mpu6050/Kconfig
> +	bool "Bypasss auxiliary i2c bus to main i2c bus."
default is true, correct? Is that what you want?

2021-08-23 15:11 UTC, avisconti commented on drivers/sensor/mpu6050/Kconfig
> +	bool "Bypasss auxiliary i2c bus to main i2c bus."
Sorry is "n", so I guess this is ok

2021-09-15 08:18 UTC, avisconti commented
@ric96 Can you change the commit message? I'm saying this again just to avoid confusion about my review.

2021-11-30 00:29 UTC, closed without merging