subsys: modbus: Add file record support to server
zephyrproject-rtos/zephyr pull request #37829
Opened 2021-08-20 08:30 UTC by christiansandberg

This commit adds support for function codes 20 (Read File Record)
and 21 (Write File Record) to the server. Write File Record allows the
application to modify the record data in the response. This is typically
the case when responding with the same data adds unnecessary overhead.
Tested with Pymodbus.

Signed-off-by: Christian Sandberg <christian.sandberg@xylem.com>

2021-08-31 22:06 UTC, jfischer-no requested changes
We need client implementation for FC20 and FC21 and tests (see tests/subsys/modbus)

2021-09-03 14:48 UTC, christiansandberg commented
I'll do the client implementation and tests as soon as I have time. Thanks for reviewing!

2022-01-06 12:04 UTC, jfischer-no commented
We still need the client implementation to be able to test it.

2022-01-06 15:34 UTC, christiansandberg commented
Sorry, I started to implement the client code but had problems running the unit tests. I'll push my WIP progress so far and try to continue the implementation soon.

2022-03-22 00:29 UTC, closed without merging