dts: stm32f103Xd: added missing dts file
zephyrproject-rtos/zephyr pull request #37825
Opened 2021-08-20 07:50 UTC by Aukstkalnis

1. Added stm32f103xd series dts file that was missing.
2. Changed stm32f103xe file's import dts <st/f1/stm32f103Xc.dtsi> to
   <st/f1/stm32f103Xd.dtsi>. This change will show only the difference
   between stm32f103xd and stm32f103xd series.

2021-08-20 13:12 UTC, FRASTM approved these changes
The stm32f103XD  devices have 384K flash and 64K Ram

2021-08-25 15:00 UTC, erwango commented
@Aukstkalnis please fix the compliance check reported [here](https://github.com/zephyrproject-rtos/zephyr/pull/37825/checks?check_run_id=3398614848)

2021-09-08 08:01 UTC, ABOSTM requested changes
Need to fix compliance check (commit message line too long)
otehrwise LGTM

2021-09-16 06:33 UTC, ABOSTM approved these changes

2021-09-28 23:48 UTC, cfriedt commented
@erwango - would you like to ack?

2021-09-28 23:51 UTC, merged