Bluetooth: ISO: Add ISO limits as #defines and use them
zephyrproject-rtos/zephyr pull request #37923
Opened 2021-08-25 10:14 UTC by Thalley

Add #define's for ISO HCI limits and use them to validate
input parameters.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

2021-08-26 17:10 UTC, cvinayak requested changes

2021-08-27 03:31 UTC, cvinayak approved these changes

2021-08-27 10:57 UTC, Casper-Bonde-Bose requested changes

2021-08-27 11:20 UTC, Casper-Bonde-Bose approved these changes
LGTM

2021-08-27 11:21 UTC, asbjornsabo approved these changes
My comments have been resolved - glad to have the defines in place!

2021-08-27 13:34 UTC, merged