usb: cdc_acm: trigger TX IRQ when CDC ACM class is ready
zephyrproject-rtos/zephyr pull request #37924
Opened 2021-08-25 10:29 UTC by GrixaYrev

Before commit 4f2682bd79c0b13ca5271af44d6ea93fba717520
("usb: cdc_acm: avoid spurious interrupt on configured or resume events")
spurious rx-interrupt provided start to read shell tx ring buffer by
CDC ACM UART. Now shell log backend not transmit data, until CDC ACM UART
received data from host.

This PR added invoking interrupt callback if tx interrupt is enable,
when CDC ACM class go to configured state, and flag tx_ready go to true.

Signed-off-by: Grixa Yrev <GrixaYrev@yandex.ru>

2021-08-25 11:36 UTC, jfischer-no approved these changes

2021-08-25 12:35 UTC, GrixaYrev commented
Fixed lines length in commit message.

2021-08-26 01:33 UTC, stephanosio requested changes

2021-08-26 08:36 UTC, stephanosio approved these changes

2021-08-26 13:13 UTC, merged