manifest: Regular upmerge to bring the openthread CSL fixes
zephyrproject-rtos/zephyr pull request #38024
Opened 2021-08-26 07:41 UTC by canisLupus1313

Periodic upmerge of OpenThread.

Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>

2021-08-26 09:01 UTC, pdgendt requested changes
Shouldn't the `Kconfig` options for `CONFIG_OPENTHREAD_CSL_AUTO_SYNC` and `CONFIG_OPENTHREAD_HISTORY_TRACKER` be added in this PR?

2021-08-26 09:51 UTC, pdgendt requested changes

2021-08-26 10:12 UTC, pdgendt approved these changes

2021-08-26 12:46 UTC, edmont approved these changes

2021-08-30 08:01 UTC, edmont commented on west.yml
> +      revision: pull/47/head
Please update to `5d706547ebcb0a85e11412bcd88e80e2af98c74d`.

2021-08-30 11:32 UTC, carlescufi approved these changes

2021-08-30 11:32 UTC, merged