cmake: emu: nsim: fix nsim props and args name
zephyrproject-rtos/zephyr pull request #38020
Opened 2021-08-26 06:52 UTC by wangnuannuan

use this change to fix https://github.com/zephyrproject-rtos/zephyr/issues/38019

nsim_sem_mpu_stack_guard board use nism_sem board's config file

Signed-off-by: Jingru Wang <jingru@synopsys.com>

2021-08-30 12:19 UTC, ruuddw commented
Isn't it simpler to create 'nsim_sem_mpu_stack_guard.[args|props] files instead of the extra cmake code for handling this?

2021-08-31 10:38 UTC, evgeniy-paltsev requested changes
I'd also propose to just create required `args\props` files instead of increasing complexity of board.cmake and introducing the implicit cross-dependency.

2021-09-01 09:00 UTC, ruuddw approved these changes

2021-09-01 11:48 UTC, evgeniy-paltsev commented
Hmm, is the commit message still actual?

> Before nsim_sem_mpu_stack_guard board uses nism_sem board's config files, so we had to use the extra cmake code for handling it.

We don't do workarounds in cmake code now (the only change in cmake is just a cleanup as I can see)

2021-09-06 22:45 UTC, evgeniy-paltsev approved these changes

2021-09-07 02:20 UTC, merged