net: sockets: add shutdown() support in vtable and implement it for native and tls sockets
zephyrproject-rtos/zephyr pull request #38034
Opened 2021-08-26 12:22 UTC by mniestroj

So far shutdown() implementation was a noop and just resulted in warning
logs. Add shutdown() method into socket vtable. Call it if provided and
fallback into returning -ENOTSUP if not.

Add basic shutdown() implementation for net_context sockets, which
handles only SHUT_RD as 'how' parameter and returns -ENOTSUP for SHUT_WR
and SHUT_RDWR. The main use case to cover is to allow race-free wakeup
of threads calling recv() on the same socket.

Add basic shutdown() implementation of TLS sockets, which basically
calls shutdown() on underlying wrapped sockets.

Fix internal http_client timeout implementation by using shutdown(..., SHUT_RD)
instead of close().

Fixes: #37730

2021-08-28 10:44 UTC, ycsin commented
@mniestroj buildkite complaining that `SHUT_RD`, etc aren't declared

2021-09-08 13:00 UTC, rlubos reviewed
Looks pretty good, but it seems that `socket.h` changes are missing.

2021-09-09 13:32 UTC, mniestroj commented on subsys/net/lib/sockets/sockets.c
> +	if (how == ZSOCK_SHUT_RD) {
They were there already:
https://github.com/zephyrproject-rtos/zephyr/blob/2e3c9ce3fb06634094aa661ee8871a4dbae07199/include/net/socket.h#L67-L76

Or do you mean something different?

2021-09-09 14:00 UTC, rlubos approved these changes

2021-09-10 09:32 UTC, rlubos commented on subsys/net/lib/http/http_client.c
> +	(void)shutdown(data->sock, SHUT_RD);
This should rather use `zsock_shutdown()` now due to recent changes in the lib.

2021-09-10 09:33 UTC, rlubos requested changes

2021-09-10 09:33 UTC, rlubos commented on subsys/net/lib/http/http_client.c
> +	(void)shutdown(data->sock, SHUT_RD);
This should rather use `zsock_shutdown()` now due to recent changes in the lib.

2021-09-13 11:21 UTC, rlubos approved these changes

2021-09-14 19:59 UTC, pfalcon commented
@mniestroj: I'm all for implementing missing socket features, and thanks for going for that. But it's also fair to say that you implement a peculiar, adhoc feature, and that particular feature kept me perplexed for a while when reviewing this patch. The matter, I'm not familiar with usage of shutdown(SHUT_RD), in my list "the only useful" (from us/remote-peer communication perspective) was shutdown(SHUT_WR), which allows to signal to peer EOF, while still keeping receive data from it.

So, that would be first comment. Something like:

> The main use case to cover is to allow race-free wakeup of threads calling recv() on the same socket.

doesn't provide enough information about the usecase. Please consider elaborating the description. It could be something along the lines of (please extend further):

> The main usecase is to allow side-effect free wakeup of threads blocked in recv(), by calling shutdown(SHUT_RD) in another thread (e.g. a callback). Previously, close() was used for that, but that has side effect of also closing file descriptor. This led to cases when a file descriptor was closed in some circumstances, but not other, which was confusing to users. Moreover closed file descriptor could be reused in the meantime, leading to hard to debug races.

But now about the actual behavior of shutdown(SHUT_RD). I played with it on Linux (using Python) and indeed, it can be used in a way you use it. But faithfulness of your implementation is questionable. Here's a transcript:

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s=socket.socket()
>>> s.connect(("localhost", 8082))
>>> s.recv(1)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> socket.SHUT_RD
0
>>> s.shutdown(0)
>>> s.recv(1)
b''
>>> s.send(b"GET / HTTP/1.0\r\n\r\n")
18
>>> s.recv(1)
b'H'
>>> s.recv(1)
b'T'
>>> s.recv(1)
b'T'
>>> s.recv(1)
b'P'
>>> s.recv(1)
b'/'
>>> s.recv(20)
b'1.0 200 NA\r\nContent-'
>>> s.shutdown(0)
>>> s.recv(20)
b'Type: text/html\r\n\r\n<'
>>> s.shutdown(0)
>>> 
```

As you can see, it "shuts down for read" only so much. After you called s.shutdown(SHUT_RD), you can still call send(), and the socket will be automagically un-shutdown for read. More important, the above shows that read shutdown doesn't affect any pending data on socket, it should be still readable. While in your implementation, as far as I can tell, you just flush it.

And then final point: We now have much better way to handle socket timeouts - by using setsockopt(SOCK_RCVTIMEO), instead of fiddling with all those multi-threading races of accessing a single I/O object (which should be avoided in the first place).

So, that's what we have: this doesn't really implement shutdown(), just one option of it, and of that option, a very partial, peculiar behavior piece. Bottom line: great work! ;-) Tests are there, etc. But as suggested above, please elaborate the description of this very peculiar behavior and usecase behind it. Thanks.

2021-09-22 13:11 UTC, cfriedt approved these changes
Thanks for adding this!

2021-09-22 13:13 UTC, cfriedt commented
It looks like at least some of the failing tests are due to a simple compilation error, so ensure that the correct header is included for `SHUT_RD`.

```
/workdir/zephyr/subsys/net/lib/sockets/sockets.c:410:13: error: 'SHUT_RD' undeclared (first use in this function)
```

2021-09-23 17:20 UTC, cfriedt requested changes
Please fix compilation error due to `SHUT_RD` being undefined.

2021-09-29 09:18 UTC, carlescufi commented
@mniestroj ping

2021-11-29 12:57 UTC, ycsin commented
Another ping @mniestroj

2022-02-13 00:29 UTC, closed without merging