[TOPIC-BLE-LLCP] Bluetooth: llcp: Fix CI build errors
zephyrproject-rtos/zephyr pull request #38067
Opened 2021-08-27 12:00 UTC by kruithofa

The first commit fixes missing includes for the direction finding samples:
when including ull_internal.h we must also include lll_conn.h for
getting the type definition of the node_tx struct.
Without this change the samples direction_finding_connectionless_rx and direction_finding_connectionless_tx will fail
This change is required in topic branch only, not in main

The second commit fixes missing conditional compiles, which caused build errors for babblesim

CI is still failing on:
- EDTT tests, to be fixed in a separate PR
- qemu tests, but that also seems to happen in main branch and is not specific for the topic-ble-llcp branch

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2021-08-27 12:04 UTC, ppryga-nordic approved these changes

2021-08-27 12:13 UTC, ppryga-nordic requested changes

2021-08-27 13:19 UTC, ppryga-nordic approved these changes

2021-08-30 13:31 UTC, kruithofa commented
There still is a CI failure I want to investigate before merging this

2021-09-16 06:22 UTC, erbr-ot approved these changes

2021-10-20 12:04 UTC, closed without merging