tests: threads: fix issue#219656
zephyrproject-rtos/zephyr pull request #38096
Opened 2021-08-30 09:06 UTC by naiyuantian

In the file variable val is not initialized,
causing the variable stack_ptr, pos, points to uninitialized data.
Initialize the variable val according to the code and commits.

Fix #219656

Signed-off-by: Naiyuan Tian <naiyuan.tian@intel.com>

2021-08-30 13:52 UTC, maksimmasalski commented
@naiyuantian You need to add into message body, not into title "Fixes #Github_Issue_Number". Use a Github issue number, not a Coverity issue number.

2021-09-01 03:49 UTC, maksimmasalski commented
@naiyuantian I think Coverity wants you to initialize `val` in its declaration like `uint8_t val=0;`

2021-09-02 02:29 UTC, maksimmasalski commented on tests/kernel/threads/thread_stack/src/main.c
> +	val = *stack_start;
As I said in the comment, Coverity wants you to initialize `val` in its declaration like `uint8_t val=0;`

2021-09-02 02:30 UTC, maksimmasalski requested changes

2021-09-02 02:30 UTC, maksimmasalski commented on tests/kernel/threads/thread_stack/src/main.c
> +	val = *stack_start;
As I said in the comment, Coverity wants you to initialize val in its declaration like uint8_t val=0;

2021-09-03 06:04 UTC, maksimmasalski approved these changes

2021-09-18 02:30 UTC, cfriedt approved these changes

2021-09-18 02:30 UTC, merged