Bluetooth: ISO: Update BIS index to start from 0x01
zephyrproject-rtos/zephyr pull request #38164
Opened 2021-08-31 07:53 UTC by Thalley

The HCI spec defines the BIS index range as starting from
index 0x01. We had previously implemented it such that it
starts from 0x00, and then simply adding 1 to the index
when sending over HCI. However, this may cause issue with
other HCI, or other SIG defined specification, commands
and events, and thus it is probably simpler if we just
use the HCI defined range.

This commit disallows BIT(0) (representing the BIS
index 0x00) to be set, and removes the addition
of 1 when sending over HCI.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

2021-08-31 13:45 UTC, kruithofa requested changes

2021-08-31 13:45 UTC, kruithofa commented on samples/bluetooth/iso_broadcast_benchmark/src/receiver.c
> +	for (int i = i; i <= big_sync_param.num_bis; i++) {
You mean: int i = 1?
```suggestion
	for (int i = 1; i <= big_sync_param.num_bis; i++) {
```

2021-08-31 13:45 UTC, kruithofa commented on subsys/bluetooth/host/iso.c
> +	for (int i = 1; i < BT_ISO_MAX_GROUP_ISO_COUNT; i++) {
shouldn't this be changed to 
```suggestion
	for (int i = 1; i <= BT_ISO_MAX_GROUP_ISO_COUNT; i++) {
```

2021-08-31 13:58 UTC, Thalley commented on samples/bluetooth/iso_broadcast_benchmark/src/receiver.c
> +	for (int i = i; i <= big_sync_param.num_bis; i++) {
Yes, wow... Thanks!

2021-09-01 00:52 UTC, cvinayak requested changes

2021-09-01 00:52 UTC, cvinayak commented on subsys/bluetooth/host/iso.c
> +	CHECKIF(!param->bis_bitfield || ((param->bis_bitfield & BIT(0)) != 0)) {
```suggestion
	CHECKIF(param->bis_bitfield <= BIT(0)) {
```

2021-09-01 00:52 UTC, cvinayak commented on samples/bluetooth/iso_receive/src/main.c
> +	.bis_bitfield = (BIT(BIS_ISO_CHAN_COUNT)),
```suggestion
	.bis_bitfield = (BIT_MASK(BIS_ISO_CHAN_COUNT) << 1),
```

2021-09-01 11:25 UTC, Thalley commented on samples/bluetooth/iso_receive/src/main.c
> +	.bis_bitfield = (BIT(BIS_ISO_CHAN_COUNT)),
Great idea!

2021-09-01 12:32 UTC, cvinayak approved these changes

2021-09-01 14:03 UTC, kruithofa approved these changes

2021-09-01 14:57 UTC, merged