device: add DEVICE_DT_GET_OR utility macro
zephyrproject-rtos/zephyr pull request #38345
Opened 2021-09-06 13:48 UTC by gmarull

Opening as draft for discussion.

2021-09-06 13:53 UTC, erwango approved these changes
+1 on my side if you think that `DEVICE_DT_GET_OR` might be useful for others.

2021-09-07 17:43 UTC, dcpleung approved these changes

2021-09-08 04:56 UTC, ceolin requested changes
Please add a test for this macro in `tests/lib/devicetree/devices/`

2021-09-08 08:46 UTC, gmarull commented
> Please add a test for this macro in `tests/lib/devicetree/devices/`

done

2021-09-08 22:03 UTC, ceolin approved these changes

2021-09-09 14:16 UTC, mbolivar-nordic approved these changes

2021-09-29 00:00 UTC, merged