Bluetooth: shell: gatt-write-without-response with repeat
zephyrproject-rtos/zephyr pull request #384
Opened 2017-06-02 09:54 UTC by cvinayak

Add a repeat param to gatt-write-without-response so that
it covers what gatt-write-without-response-repeated was
doing. gatt-write-without-response was removed in the
commit 26eae70da.

gatt-write-signed too will have repeat param with this
change.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2017-06-02 10:40 UTC, jhedberg requested changes

2017-06-02 10:40 UTC, jhedberg commented on subsys/bluetooth/shell/gatt.c
> +		repeat = 1;
Wouldn't it be simpler just to initialize repeat to 1 instead of 0 to start with?

2017-06-02 10:40 UTC, jhedberg commented on subsys/bluetooth/shell/gatt.c
> +		repeat = 1;
Well, this wouldn't cover the case when somebody passes '0' on the command line, but that's just user stupidity :)

2017-06-02 10:51 UTC, cvinayak commented on subsys/bluetooth/shell/gatt.c
> +		repeat = 1;
the strtoul could return 0, hence this if-clause covers that.

2017-06-02 10:57 UTC, cvinayak commented on subsys/bluetooth/shell/gatt.c
> +		repeat = 1;
without this check, putting 0 in console will lead to the printk displaying junk for err.

2017-06-02 12:03 UTC, Vudentz approved these changes

2017-06-04 06:33 UTC, jhedberg approved these changes

2017-06-04 06:34 UTC, merged