libc/minimal: Add islower() to ctype.h
zephyrproject-rtos/zephyr pull request #38404
Opened 2021-09-09 09:33 UTC by xhpohanka

ctype.h in minimal libc was lacking implementation of
islower(int a).

Signed-off-by: Jan Pohanka <xhpohanka@gmail.com>

2021-09-09 09:52 UTC, xhpohanka commented
I have no problem to fix the reported checkpatch compliance issues but I'd like to keep consistency with already existing code in the file...

2021-09-09 10:46 UTC, carlescufi approved these changes

2021-09-10 15:30 UTC, stephanosio requested changes
Although the code is severely malformed, so are the rest of the functions in this file -- we can fix those later in a separate PR.

For now, please update the following related doc:
https://github.com/zephyrproject-rtos/zephyr/blame/ab7f07dc4a33d1b2b732f071c3334bf833fb58df/doc/guides/portability/posix.rst#L258

2021-09-16 14:23 UTC, stephanosio approved these changes

2021-11-30 00:29 UTC, closed without merging