tests: driver: build-test: exclude twr_ke18f
zephyrproject-rtos/zephyr pull request #38443
Opened 2021-09-10 05:43 UTC by hakehuang

below two build test can not fit in SRAM size

drivers.modem.build
drivers.modem.quectel_bg9x.build

build error report:

region `SRAM' overflowed by 20688 bytes
collect2: error: ld returned 1 exit status

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

2021-09-11 17:49 UTC, stephanosio reviewed
> region `SRAM' overflowed by 20688 bytes

Twister should skip these and not treat SRAM overflows as errors, no?

2021-09-13 03:01 UTC, hakehuang commented
> Twister should skip these and not treat SRAM overflows as errors, no?

yes, twister will skip this as errors. so we need find a solution

2021-09-15 08:21 UTC, henrikbrixandersen commented
> > Twister should skip these and not treat SRAM overflows as errors, no?
> 
> yes, twister will skip this as errors. so we need find a solution

As far as I can tell, they are already skipped?

2021-09-15 08:22 UTC, henrikbrixandersen commented
@hakehuang Are you running twister with `--overflow-as-errors`?

2021-09-16 09:13 UTC, hakehuang commented
> As far as I can tell, they are already skipped?

this will report a error not failure if you run with twister.

2021-09-16 09:16 UTC, henrikbrixandersen commented
> this will report a error not failure if you run with twister.

It shouldn't. It does not report an error here. How are you invoking twister? With which arguments?

2021-09-16 15:19 UTC, hakehuang commented
> It shouldn't. It does not report an error here. How are you invoking twister? With which arguments?

@henrikbrixandersen sorry, my mistaken, is is marked as 'skip due to build error'.

2021-09-17 10:31 UTC, henrikbrixandersen commented
> @henrikbrixandersen sorry, my mistaken, is marked as 'skip due to build error'.

So there is no reason for an explicit exclude?

2021-09-17 15:15 UTC, hakehuang commented
> So there is no reason for an explicit exclude?

with this, we do not need try build it first every time.

2021-09-18 01:02 UTC, stephanosio requested changes, later dismissed
> with this, we do not need try build it first every time.

While that is true, if we added `platform_exclude` for every skipped platform with FLASH or SRAM overflow, we will likely end up with hundreds of them.

If this test cannot run on the platforms with low SRAM, please set `min_ram` instead.

2021-09-19 10:18 UTC, hakehuang commented
> If this test cannot run on the platforms with low SRAM, please set `min_ram` instead.

ok, update to use 
```
min_ram: 36
```

2021-09-21 07:11 UTC, henrikbrixandersen requested changes
The commit log needs to be updated to match the commit contents.
How did you come up with 36?

2021-09-22 03:50 UTC, hakehuang commented
> The commit log needs to be updated to match the commit contents.
> How did you come up with 36?

the error log reply as
region `SRAM' overflowed by 20688 bytes
and twr_ke18f is 32M SRAM by default.

2021-10-28 07:07 UTC, henrikbrixandersen approved these changes

2022-01-18 18:55 UTC, nashif approved these changes

2022-01-21 17:29 UTC, merged