drivers: adc: stm32h7: Oversampling Ratio set incorrectly
zephyrproject-rtos/zephyr pull request #38627
Opened 2021-09-17 10:39 UTC by FRASTM

Configure the with Oversamplig ratio for the stm32H7 soc devices, with the LL_ADC_ConfigOverSamplingRatioShift
The LL API function dffers from other stm32 soc : 
ratio is directly the value to set from 1..1024
Depending on the ADC instance ratio is directly the value to set from 1..1024   --> ADC of the stm32H74x for example
or is directly a 3-bit   --> **ADC3** of the stm32H723 for example

requires https://github.com/zephyrproject-rtos/hal_stm32/pull/117

fixes https://github.com/zephyrproject-rtos/zephyr/issues/38606

Signed-off-by: Francois Ramu francois.ramu@st.com

2021-09-17 12:04 UTC, heinwessels commented
@FRASTM as mentioned in [#38606](https://github.com/zephyrproject-rtos/zephyr/issues/38606) this code will not handle `ADC3` correctly for H7. Even if the [HAL Bug](https://github.com/STMicroelectronics/STM32CubeH7/issues/177) is solved, ADC3 still requires a 3-bit value, and your code will send a `10bit` value. It will also not handle the `2^N` input number correctly that Zephyr specifies in it's documentation.

2021-09-28 09:54 UTC, FRASTM commented
include the commit for the hal_stm32 : west.yml: update modules/hal/stm32/hal_stm32 for stm32h7

2021-09-28 09:58 UTC, erwango commented
@heinwessels Would you mind having a new look ?

2021-09-28 11:44 UTC, heinwessels commented
> @heinwessels Would you mind having a new look ?

I'm AFK for the next two weeks so I cannot test the code. I did find a possible issue in HAL PR #117 that this PR depends on, although this PR looks good.

2021-09-29 09:29 UTC, FRASTM commented
Keeping the` LL_ADC_ConfigOverSamplingRatioShift(adc, sequence->oversampling`   for the stm32H7
It means that the 'Ratio' in the LL function is a 'n' value from 1 to 8 (ADC3) or from 1 to 10 (other ADC)  and no more the corresponding to a oversampling of 2^n. 
That makes the adc_stm32_start_conversion() unchanged for the oversampling configuration (excepting a possible extension to case 9 and case 10) but the change is reported to the stm32cube LL function.

2021-09-30 13:03 UTC, ABOSTM requested changes

2021-09-30 13:03 UTC, ABOSTM commented on drivers/adc/adc_stm32.c
> +	LL_ADC_SetChannelPreSelection(adc, index);
Isn't it `channel `instead of `index `?

2021-10-01 07:17 UTC, ABOSTM approved these changes
LGTM

2021-10-01 12:25 UTC, heinwessels approved these changes
LGTM, atthough I cannot test the code at the moment. 

Also, I tend to agree with ABOSTM's [comment](https://github.com/zephyrproject-rtos/hal_stm32/pull/117#discussion_r720037396) on the HAL Driver change, which would mean this driver will need to be updated.

2021-10-04 06:44 UTC, FRASTM commented
rebase

2021-10-04 09:25 UTC, heinwessels commented on drivers/adc/adc_stm32.c
>  	 * NOTE: There is no LL API to control this register yet.
This comment is outdated.

2021-10-05 10:10 UTC, FRASTM commented
New version that take the new LL_ADC_ConfigOverSamplingRatioShift stm32Cube function
where the Ratio is a value from 1..1024 (or a 2^n value from 1..256 for ADC3)
This means that the parameter to give to the LL_ADC_ConfigOverSamplingRatioShift is 2^oversampling (and no more the 'oversampling').

2021-10-06 15:32 UTC, ABOSTM approved these changes
LGTM

2021-10-08 11:41 UTC, erwango requested changes

2021-10-12 14:21 UTC, erwango requested changes
One minor comment, otherwise LGTM

2021-10-12 14:46 UTC, erwango approved these changes

2021-10-25 23:15 UTC, merged