Drivers: hwinfo: add reset cause shell
zephyrproject-rtos/zephyr pull request #38754
Opened 2021-09-22 16:56 UTC by alexanderwachter

This PR adds a shell command to obtain, clear and show available reset causes

2021-09-23 07:29 UTC, pdgendt approved these changes
Small nits, otherwise LGTM

2021-09-23 07:29 UTC, pdgendt commented on drivers/hwinfo/hwinfo_shell.c
> +	SHELL_CMD_ARG(clear, NULL, "Clear all persisten reset causes",
```suggestion
	SHELL_CMD_ARG(clear, NULL, "Clear all persistent reset causes",
```

2021-09-23 07:29 UTC, pdgendt commented on drivers/hwinfo/hwinfo_shell.c
> +}
Why not just:
```suggestion
static void print_all_reset_causes(const struct shell *shell, uint32_t cause)
{
	for (uint32_t cause_mask = 1; cause_mask; cause_mask <<= 1) {
		if (cause & cause_mask) {
			shell_print(shell, "- %s", cause_to_string(cause & cause_mask));
		}
	}
}
```

2021-09-23 16:42 UTC, alexanderwachter commented on drivers/hwinfo/hwinfo_shell.c
> +}
Whoops 😅
Much easier, yes!

2021-10-08 09:05 UTC, henrikbrixandersen requested changes

2021-10-10 21:31 UTC, henrikbrixandersen requested changes

2021-11-07 10:01 UTC, alexanderwachter commented on drivers/hwinfo/hwinfo_shell.c
> +	for (uint32_t cause_mask = 1; cause_mask; cause_mask <<= 1) {
A minimal scope is always preferable.

2021-11-07 19:49 UTC, henrikbrixandersen approved these changes

2021-11-07 19:54 UTC, alexanderwachter commented
@cfriedt ready to merge :-)

2021-11-07 19:55 UTC, cfriedt commented
Cc @arvinf

2021-11-07 19:55 UTC, merged