flash : stm32l4x don'y write 0xff
zephyrproject-rtos/zephyr pull request #389
Opened 2017-06-02 15:30 UTC by jamike

for mcuboot on l4, avoiding writting 0xff solves trailer write access during swap

2017-06-02 15:36 UTC, galak requested changes
Any reason not to include this in PR #388?

Also similar comment about subject of commit message provide additional details about the issue & fix.

2017-06-02 17:30 UTC, lpereira commented
You might want to rebase this, so it only includes the last patch. You can force-push to your repository, this PR will be updated.

2017-06-06 09:17 UTC, jamike commented
This commit is required is required only for MCU boot loader. That 's why I pushed it separetly.

2017-06-07 15:18 UTC, erwango commented on drivers/flash/flash_stm32l4x.c
> +					, p);
can you move coma at end of second line?

2017-06-07 15:19 UTC, erwango requested changes
minor comment, otherwise LGTM

2017-06-15 16:20 UTC, galak commented
now that the other flash changes are merged, can you rebase/update this.

2017-06-15 18:36 UTC, jamike commented
Following some changes in mcu bootloader . this patch seems not needed . I continue testing without. 
And if confirmed , i will close it.

2017-06-20 14:50 UTC, galak commented
any updates if still needed?

2017-06-20 15:10 UTC, jamike commented
no

2017-06-20 15:10 UTC, closed without merging

2017-06-20 15:11 UTC, jamike commented
After the changes in mcuboot , the PR is not needed any more.