soc: riscv: esp32c3: added wifi support for esp32c3 soc
zephyrproject-rtos/zephyr pull request #38955
Opened 2021-09-29 01:19 UTC by uLipe

This PR enables the esp32 wlan driver do support the esp32c3 SoC, enabling its wifi support.

2021-09-29 12:07 UTC, henrikbrixandersen requested changes
I am a bit confused here. The PR description and commit logs talk about WiFi support, but the changes add RNG support?

2021-09-29 15:00 UTC, uLipe commented
Reworked the commit messages to make more sense in the context of wifi.

2021-09-29 15:15 UTC, henrikbrixandersen approved these changes

2021-09-30 10:38 UTC, cfriedt commented on west.yml
> +      revision: 2f438dfde14900d35bf703ddc4c0f71efc0d065f
@sylvioalves - is this fine here?

2021-09-30 10:39 UTC, cfriedt approved these changes

2021-09-30 10:39 UTC, merged