Backport 38834 to v2.7 branch
zephyrproject-rtos/zephyr pull request #39054
Opened 2021-10-01 18:00 UTC by mbolivar-nordic

2021-10-01 18:15 UTC, nashif commented
fun following the links to know what this PR is supposed to do without any description...

2021-10-02 00:35 UTC, cfriedt approved these changes

2021-10-02 00:36 UTC, cfriedt requested changes
may need some additional work

2021-10-04 16:36 UTC, mbolivar-nordic commented
I botched the rebase last time; it's passing now

2021-10-04 19:08 UTC, cfriedt approved these changes

2021-10-04 19:08 UTC, merged