MAINTAINERS: add myself as hawkbit collaborator
zephyrproject-rtos/zephyr pull request #39069
Opened 2021-10-02 08:00 UTC by ycsin

Add myself as collaborator for hawkbit subsystem.

2021-10-02 11:46 UTC, nashif requested changes

2021-10-02 11:46 UTC, nashif commented on MAINTAINERS.yml
> +        - "area: hawkbit"
"area: hawkBit"

2021-10-02 12:02 UTC, nashif approved these changes

2021-10-07 15:50 UTC, carlescufi approved these changes

2021-10-07 15:50 UTC, merged