drivers: sensor: fxos8700: Initialize device in standby mode
zephyrproject-rtos/zephyr pull request #39073
Opened 2021-10-02 23:10 UTC by hollerdawg

Put device in standby power mode when initializing.

Resolves #39024

Serial output of samples/sensor/fxos8700 `west build -b frdm_k22f -p -- -DCONFIG_FXOS8700_DRDY_INT1=y`:
```
[00:00:00.001,000] <dbg> FXOS8700.fxos8700_init: Device ID 0xc7
[00:00:00.001,000] <dbg> FXOS8700.fxos8700_set_odr: Set ODR to 0x28
[00:00:00.007,000] <dbg> FXOS8700.fxos8700_init: Init complete
[00:00:00.012,000] <dbg> FXOS8700.fxos8700_set_odr: Set ODR to 0x28
AX=  0.047884 AY= -0.450110 AZ=  9.605537 MX=  0.326000 MY= -0.101000 MZ=  0.647000 T= 22.080000
[continued]
```

2021-10-04 14:45 UTC, MaureenHelm requested changes
Thanks for the patch. I think a better fix would be to rework `fxos8700_set_odr` so it doesn't clobber the current power mode.

2021-10-05 01:32 UTC, hollerdawg commented
> Thanks for the patch. I think a better fix would be to rework `fxos8700_set_odr` so it doesn't clobber the current power mode.

Ah, that makes sense; I didn't realize that was the default value after reset.

2021-10-05 20:12 UTC, MaureenHelm approved these changes

2021-10-28 14:59 UTC, teburd approved these changes

2021-10-28 15:10 UTC, merged