ITE: dts: cpu/yaml: fix the name of compatible
zephyrproject-rtos/zephyr pull request #39080
Opened 2021-10-04 07:34 UTC by GTLin08

This name should be the same as cpus node in dtsi. After the power
policy is added, the cpu-power-states in the CPU properties can
be used.

Signed-off-by: Tim Lin <tim2.lin@ite.corp-partner.google.com>

2021-10-04 15:11 UTC, brockus-zephyr approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39080)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @galak, @jackrosenthal, @keith-zephyr, and @mbolivar-nordic)



<!-- Sent from Reviewable.io -->

2021-10-04 15:19 UTC, galak requested changes
Rename the file to match the compatible.

2021-10-05 05:14 UTC, GTLin08 commented
> Rename the file to match the compatible.

Done.

2021-10-07 11:09 UTC, galak approved these changes

2021-10-07 11:09 UTC, merged