twister: Allow baud rates other than 115200
zephyrproject-rtos/zephyr pull request #39207
Opened 2021-10-06 17:54 UTC by DRuffer

Fixes #38046
Document the changes in twister.rst
Add baud rate to debug message in twister
Add baud parameter to twister's add_device function
Set the twister baud rate from input parameters
Use 115200 as the default baud rate if not specified
Add baud to the hwmap-schema.yaml file
Add --device-serial-baud to twister arguments
Fix compliance issues

Signed-off-by: Dennis Ruffer <daruffer@gmail.com>

2021-10-07 11:07 UTC, nashif approved these changes

2021-10-07 11:42 UTC, PerMac requested changes
I find the scope and handling of `DEFAULT_BAUD` and `baud` a bit confusing. My major concern is that you define `DEFAULT_BAUD = 115200` twice, in twisterlib.py and twister scripts. Since this variable is nowhere changed in twister script, why not getting rid of it completely there? You are only passing the default value to `hwm.add_device()`.
I tried to refactor your commit a bit, getting rid of multiple definitions of default baud and IMO making the logic of baud passing/handling a bit simpler. In my proposition, the default value for baud is only given once, when DUT object is created and is replaced whenever non-default is given.
 I will run some smoke tests on it now add share it with you.

2021-10-13 21:45 UTC, DRuffer commented
Rebase and squash have passed all checks

2021-10-14 00:08 UTC, enjiamai approved these changes

2021-10-14 04:13 UTC, chen-png approved these changes

2021-10-14 05:03 UTC, henrikbrixandersen approved these changes

2021-10-14 07:01 UTC, PerMac approved these changes

2021-10-14 20:35 UTC, merged