drivers: serial: NXP: Set initialization priority
zephyrproject-rtos/zephyr pull request #39308
Opened 2021-10-10 22:05 UTC by dleach02

The NXP MCUX serial drivers have a dependency on the clock controller
driver being initialized. Created a UART_INIT_PRIORITY Kconfig to
provide a configuration for serial driver initialization priority
setting. The initial value is set to the origin priority level and
then added the Kconfig value overrides in the SOC defconfig files.

Set the override value for NXP SOCs to 55 to ensure the serial drivers
initialize after the clock control driver which uses
KERNEL_INIT_PRIORITY_DEVICE which is 50.

Merged the NXP serial driver Kconfig files into a single Kconfig.mcux

Fixes #38631

Signed-off-by: David Leach <david.leach@nxp.com>

2021-10-11 20:49 UTC, MaureenHelm requested changes

2021-10-12 21:00 UTC, mmahadevan108 commented
@dleach02 Why not move `UART_MCUX_INIT_PRIORITY `to `drivers/serial/Kconfig` and call it `UART_INIT_PRIORITY` as was suggested by @MaureenHelm. This config might be useful to other platforms at a later time. This is similar to what is done for I2C in `drivers/i2c/Kconfig` where it provides `I2C_INIT_PRIORITY`

2021-10-13 03:04 UTC, dleach02 commented
@mmahadevan108 I thought about doing that but then considered that as far as I could tell, this was only a NXP problem. I can do it though but not really inclined to change all the other drivers over to using that priority setting though.

2021-10-14 07:45 UTC, mbittan approved these changes

2021-10-14 14:15 UTC, mmahadevan108 approved these changes

2021-10-15 15:26 UTC, closed without merging