drivers: spi: mark old spi_cs_control fields deprecated
zephyrproject-rtos/zephyr pull request #39338
Opened 2021-10-11 19:31 UTC by bbilas

Since gpio_dt_spec is finally available within spi_cs_control struct, mark the old fields deprecated in order to use gpio_dt_spec struct.

Depends on https://github.com/zephyrproject-rtos/zephyr/pull/37498 and https://github.com/zephyrproject-rtos/zephyr/pull/39341

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>
Co-authored-by: Jordan Yates <jordan.yates@data61.csiro.au>
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
Co-authored-by: Bartosz Bilas <bartosz.bilas@hotmail.com>

2021-11-02 14:40 UTC, henrikbrixandersen commented
This is a stable API change.

2021-11-02 15:13 UTC, carlescufi commented
> This is a stable API change.

I am not sure I get this. We are deprecating structures, how is that a stable API change? By definition we call a Stable API change one that does not follow the standard deprecation process.

2021-11-02 18:43 UTC, henrikbrixandersen commented
> I am not sure I get this. We are deprecating structures, how is that a stable API change? By definition we call a Stable API change one that does not follow the standard deprecation process.

Exactly my point. This change needs to follow the process for changing a stable API as described here: https://docs.zephyrproject.org/latest/reference/api/api_lifecycle.html#introducing-incompatible-changes

2021-11-02 18:44 UTC, henrikbrixandersen requested changes
Blocking pending the process for changing a stable API has been met.

2021-11-03 11:44 UTC, carlescufi commented
> > I am not sure I get this. We are deprecating structures, how is that a stable API change? By definition we call a Stable API change one that does not follow the standard deprecation process.
> 
> Exactly my point. This change needs to follow the process for changing a stable API as described here: https://docs.zephyrproject.org/latest/reference/api/api_lifecycle.html#introducing-incompatible-changes

2021-11-03 11:44 UTC, carlescufi commented
Apologies for closing this, I clicked on it by mistake.

2021-11-03 12:55 UTC, henrikbrixandersen commented
> @henrikbrixandersen maybe there is some confusion here :) [The section you linked to](https://docs.zephyrproject.org/latest/reference/api/api_lifecycle.html#introducing-incompatible-changes) was introduced for the cases where one does **not** want to use deprecation. If you use deprecation then there's no need to follow that guide, which was designed for the cases that require skipping deprecation due to complexity.

Sorry, meant to link to https://docs.zephyrproject.org/latest/reference/api/api_lifecycle.html#deprecated.

2021-11-06 09:21 UTC, bbilas commented
FYI: that's not a ready MR since there is a couple of places where the old spi_cs_control members are being used but I'm periodically rebasing it and checking the buildkite results. I think DNM label should be set here...

2022-04-19 19:13 UTC, bbilas commented
cc @carlescufi @henrikbrixandersen issue https://github.com/zephyrproject-rtos/zephyr/issues/44956 created

2022-04-19 20:09 UTC, henrikbrixandersen submitted a review, later dismissed

2022-04-20 07:08 UTC, bbilas commented
In the meantime, someone has committed a new code where the deprecated members are being used... I will try to fix that soon.

2022-04-20 17:10 UTC, bbilas commented
@carlescufi @henrikbrixandersen hotfix #44968 ;)

2022-04-21 11:13 UTC, henrikbrixandersen approved these changes

2022-04-21 13:15 UTC, MaureenHelm approved these changes

2022-04-22 07:45 UTC, merged