Bluetooth: ISO: Split ISO broadcaster and sync receiver
zephyrproject-rtos/zephyr pull request #39467
Opened 2021-10-15 08:57 UTC by Thalley

Splits the Kconfiguration option to be able to enable just one of the roles, which significantly improves memory size if just a single role is supported.

2021-10-15 12:24 UTC, asbjornsabo requested changes
1) I need a clarification on ISO broadcast roles
2) The BT_ISO_BROADCAST consistently seem to be missing "CONFIG_" in front
3) Some files seems to have disappered during the review - Github says 7/10 files reviewed, but has no more files to show me ... ?

2021-10-15 13:27 UTC, asbjornsabo approved these changes
My comments have been addressed.

2021-10-18 02:59 UTC, rick1082 approved these changes

2021-10-18 07:06 UTC, alexsven approved these changes

2021-10-18 10:43 UTC, merged