Add devicetree files for STM32L010xB series microcontrollers
zephyrproject-rtos/zephyr pull request #39466
Opened 2021-10-15 08:45 UTC by wcappelle

Add the devicetree files for the STM32L010xB. this has been tested on a nucleo L010RB development board with STM32L010RB mcu.

Signed-off-by: Wouter Cappelle <wouter.cappelle@crodeon.com>

2021-10-15 09:40 UTC, erwango requested changes
Thanks for this change.

Some changes required:
- dts: see comment
- Along with dts, you'll need to add Kconfig SoC symbol in `soc/arm/st_stm32/stm32l0`
- Some changes required on the commit message, otherwise you won't pass the CI checks (See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details)
  - 1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys)
  - 1: UC6 Body has no content, should at least have 1 line.`

2021-10-15 12:11 UTC, wcappelle commented
Thanks for the review, i've updated the commit messages, and done the requested changes.
I've left some rely on the dts changes, so if you don't agree, let's discuss further.

2021-10-18 08:00 UTC, erwango requested changes

2021-10-18 09:47 UTC, erwango approved these changes
Thanks for the clean up

2021-11-02 15:50 UTC, FRASTM approved these changes

2021-11-03 02:21 UTC, merged