bluetooth: ots: Enable testing with assert
zephyrproject-rtos/zephyr pull request #39488
Opened 2021-10-17 14:45 UTC by ekohandel

Fix compilation and logic issues to allow testing OTS functionality with
    assert enabled.

    The compilation fixes are simple and do not require an explanation.

    The assertion in bt_ots_dir_list_init was logically reversed. Its
    purpose is to ensure the directory list is not already initialized
    and as such should assert that the dir_list is not set (i.e. is NULL).

    Signed-off-by: Abe Kohandel <abe.kohandel@gmail.com>

2021-10-18 08:29 UTC, Thalley approved these changes

2021-10-18 11:35 UTC, asbjornsabo requested changes
One of the changes reverses the outcome of an assert.
I suspect this is unintended, and an error.
If it is intended, please explain so, and why, in the commit message.

(The other changes look OK.)

2021-10-18 12:25 UTC, asbjornsabo approved these changes
I believe these changes are correct.
A bit more detail in the commit message would be good, though.

2021-10-21 15:20 UTC, jhedberg approved these changes

2021-10-21 15:21 UTC, merged