tests: build_all: Add device pm configuration for sensor drivers
zephyrproject-rtos/zephyr pull request #39706
Opened 2021-10-25 19:33 UTC by MaureenHelm

Adds another test configuration to ensure we build sensor drivers with
device power management enabled, in addition to the existing test that
builds sensor drivers with device power management disabled.

Signed-off-by: Maureen Helm <maureen.helm@intel.com>

Fixes #39721

@ceolin @gmarull I think we need to start doing this for other driver classes (SPI, I2C, etc) too.

2021-10-25 19:52 UTC, gmarull requested changes
LGTM, the fix for bq274xx should be different though

2021-10-25 20:27 UTC, galak approved these changes

2021-10-26 13:29 UTC, teburd approved these changes
Makes sense, and is clearly already catching build issues

2021-10-26 16:41 UTC, ceolin approved these changes

2021-10-26 18:35 UTC, gmarull approved these changes

2021-10-27 00:51 UTC, merged