test: drivers: pwm: extends pwm_loopback test
zephyrproject-rtos/zephyr pull request #39816
Opened 2021-10-28 12:30 UTC by TilmannUnte

Adds a new zassert to check whether PWM capture has previously been
enabled and correctly returns -EBUSY on a second call.
While working on #39694 this was found to be a missing test case.
The new test case has been verified against the suggested changes of
that PR.

Signed-off-by: Tilmann Unte <unte@es-augsburg.de>

2021-10-28 14:43 UTC, gmarull approved these changes

2021-10-29 11:48 UTC, henrikbrixandersen requested changes
Thanks, looks good. I am blocking this until #39914 is merged in order not to break testing.

2021-11-02 12:36 UTC, henrikbrixandersen approved these changes
Thanks!

2021-11-02 12:37 UTC, henrikbrixandersen commented
@TilmannUnte Please rebase on `main` to fix the compliance issue.

2021-11-04 11:20 UTC, merged