drivers/flash/nrfx_qspi_nor: Change anomaly_122_init ret type
zephyrproject-rtos/zephyr pull request #40017
Opened 2021-11-02 18:24 UTC by de-nordic

The commit changes a ret type of the anomaly_122_init from int
to nrfx_err_t; this makes return type coherent with ret type
of other nrfx functions.
The commit modifies code that calls the function to add return
code translation where needed.

Fixes #39923.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2021-11-02 18:25 UTC, de-nordic commented
@Driesdenijs please take a look.

2021-11-03 09:13 UTC, nvlsianpu reviewed
This patch does much more than mentioned in the only commit message.

I think that fixing issue of testing the return value of ANOMALY_122_init in place where
it was incorrect would be enough, but give me a few minutes to analyze by myself.

2021-11-04 13:22 UTC, anangl requested changes

2021-11-04 13:22 UTC, anangl commented on drivers/flash/nrf_qspi_nor.c
> +static nrfx_err_t anomaly_122_init(const struct device *dev)
I see no benefit in changing the type of `anomaly_122_init` return value. This function is not a part of nrfx, so there is no need for it to return an `nrfx_err_t` value. 
Fixing of #39923, as mentioned in its description, requires only correction in this line: https://github.com/zephyrproject-rtos/zephyr/blob/54516743732a081deda5b32339f850bf89e69846/drivers/flash/nrf_qspi_nor.c#L772 so I don't see the point in making that many modifications as this PR does.

2021-11-05 08:11 UTC, anangl commented on drivers/flash/nrf_qspi_nor.c
> +	int res = NRFX_SUCCESS;
```suggestion
	nrfx_err_t res = NRFX_SUCCESS;
```

2021-11-05 09:24 UTC, anangl approved these changes

2021-11-05 09:25 UTC, anangl commented on drivers/flash/nrf_qspi_nor.c
> +		LOG_DBG("ANOMALY_122_INIT: %x", ret);
```suggestion
		LOG_DBG("ANOMALY_122_INIT: %d", ret);
```

2021-11-05 09:30 UTC, de-nordic commented on drivers/flash/nrf_qspi_nor.c
> +		LOG_DBG("ANOMALY_122_INIT: %x", ret);
Fixed.

2021-11-17 10:50 UTC, de-nordic commented
@nvlsianpu @carlescufi  please review.

2021-11-30 10:46 UTC, carlescufi approved these changes

2021-11-30 10:46 UTC, merged