Enable I2C on RT11xx Evaluation Kits
zephyrproject-rtos/zephyr pull request #40136
Opened 2021-11-05 17:08 UTC by danieldegrasse

Enables I2C on RT1160 and RT1170 evaluation boards. Both boards contain an FXOS8700 accelerometer, which was has been enabled as well, and was used to test I2C functionality.

2021-11-12 03:53 UTC, mbolivar-nordic approved these changes

2021-11-12 14:44 UTC, teburd approved these changes

2021-11-12 16:21 UTC, MaureenHelm requested changes

2021-11-12 16:21 UTC, MaureenHelm commented on boards/arm/mimxrt1160_evk/mimxrt1160_evk_cm4.dts
> +		int2-gpios = <&gpio11 15 GPIO_ACTIVE_LOW>;
Move this to the shared `boards/arm/mimxrt1160_evk/mimxrt1160_evk.dtsi` so you don't have to duplicate for each core. Ditto for rt1170

2021-11-18 15:24 UTC, dleach02 approved these changes

2021-11-18 22:38 UTC, MaureenHelm approved these changes

2021-11-18 22:39 UTC, merged