sensors: add SI1153 driver
zephyrproject-rtos/zephyr pull request #402
Opened 2017-06-05 15:16 UTC by MaxAgneni

Signed-off-by: Massimiliano Agneni <massimiliano.agneni@iptronix.com>

2017-07-05 16:15 UTC, bogdan-davidoaia requested changes

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/Kconfig
> +	 Enable driver for SI1153 Proximity/Ambient Light Sensor IC with I2C Interface.
Alignment should be:
\<tab>\<space>\<space>help text

This applies to the rest of the configs as well.

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +	while (count < 5) {
Maybe define a constant instead of using the number 5. This applies to multiple places in this file.

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +	while ((retval & RSP0_COUNTER_MASK) == response_stored) {
Why not wait for 5 loops here like in the rest of the file?

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +} gesture_t;
Move this to sensors.h

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +		k_busy_wait(50);
More magic numbers around here.

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +	case SENSOR_CHAN_PROX:
I'd rather not expose the prox channel as the API doesn't really support multiple values for this channel type.

2017-07-05 16:15 UTC, bogdan-davidoaia commented on drivers/sensor/si1153/si1153.c
> +#define ADCCONFIG   (ADCCFG_DR_4096 | ADCCFG_AM_LARGE_IR)
Move these to .h file

2017-07-05 16:15 UTC, bogdan-davidoaia commented on include/sensor.h
> +	SENSOR_CHAN_GESTURE,
Add an enum for these values.

2017-07-05 22:13 UTC, MaureenHelm requested changes

2017-07-05 22:13 UTC, MaureenHelm commented on drivers/sensor/si1153/si1153.c
> +		k_busy_wait(500);
This will block, which you don't want to do

2017-07-05 22:13 UTC, MaureenHelm commented on drivers/sensor/si1153/si1153.c
> +	data->i2c_slave_addr = CONFIG_SI1153_I2C_DEV_ADDRESS;
Do you need this in the data structure? You can probably put in the config structure instead and save a little ram.

2017-10-08 23:51 UTC, nashif commented
recheck

2017-10-08 23:52 UTC, nashif commented
recheck

2017-10-08 23:57 UTC, nashif commented
recheck

2017-10-08 23:59 UTC, nashif commented
recheck

2017-10-09 00:00 UTC, nashif commented
recheck

2017-10-09 00:03 UTC, nashif commented
recheck

2017-10-09 00:03 UTC, nashif commented
rtest

2017-10-09 00:09 UTC, nashif commented
recheck

2018-03-23 12:33 UTC, nashif commented
stale PR

2018-03-23 12:33 UTC, closed without merging

2023-11-07 10:38 UTC, PritamSSahoo01 commented
Hii @nashif 
Can you please provide me the si1153 kernel driver source code link..