[WIP] Add mTLS https example
zephyrproject-rtos/zephyr pull request #40224
Opened 2021-11-09 17:24 UTC by theotherjimmy

This include a test-server written in Rust, for your convenience.

For the time being, this is very much WIP.

2021-11-09 17:39 UTC, d3zd3z requested changes
I think we're close to this being ready, just a few things beyond what I mentioned in code comments. Namely, the commit text should better explain what is happening, and what we're trying to do here. Also, make sure there is a Signed-off-by in the commit text.

2021-11-09 17:39 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/README.rst
> +:zephyr_file:`samples/net/sockets/http_get`.
This should be fixed for the directory we're in now. Maybe reference where it came from?

2021-11-09 17:39 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/prj.conf
> +CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=7168
This isn't likely to work very well with a generic web server. If we are able to configure the buffer size in our client, though, it should be fine.

2021-11-09 17:39 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/server/client.key
> +-----BEGIN RSA PRIVATE KEY-----
I wonder if we should include these, or if we should just leave them out, and instruct people to run the generate script. We tend to get annoying vulnerability reports from people that scan github repos for keys. Realistically, though, I don't have a problem with these keys being in tree.

2021-11-09 17:39 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/server/src/main.rs
> +    let config = rustls::ServerConfig::builder()
At some point, we should try to figure out if the TLS maximum record size can be configured in rustls. We will have problems right now if any request ends up larger than the 7k configured for the maximum record size on the client.

2021-11-09 17:39 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/src/ca_certificate.h
> +/* By default only certificates in DER format are supported. If you want to use
This comment seems in conflict with the PEM format certificates these files point to.

2021-11-09 17:40 UTC, d3zd3z commented
Also check, there is a stray space at the end of a line in the README.rst file.

2021-11-09 17:42 UTC, theotherjimmy commented
The text may be copy-paste from another example, and may not have been edited for this example

2021-11-10 11:09 UTC, jukkar commented
The `samples/net/sockets/http_get` supports both http and https protocols. Is there some reason we would need a new app that would do the same stuff?

2021-11-10 11:19 UTC, microbuilder commented
> The `samples/net/sockets/http_get` supports both http and https protocols. Is there some reason we would need a new app that would do the same stuff?

The purpose of this sample if to demonstrate **mutual** TLS, where a certificate is also present on the client side which is validated by the server. The supplied Rust project demonstrates what a server that supports this might look like to be able to test both sides of the TLS handshake.

2021-11-10 14:01 UTC, microbuilder commented on samples/net/sockets/mtls_http_get/README.rst
> +   :zephyr-app: samples/net/sockets/http_get
```suggestion
   :zephyr-app: samples/net/sockets/mtls_http_get
```

2021-11-10 14:02 UTC, microbuilder commented on samples/net/sockets/mtls_http_get/README.rst
> +   :zephyr-app: samples/net/sockets/http_get
```suggestion
   :zephyr-app: samples/net/sockets/mtls_http_get
```

2021-11-18 22:11 UTC, d3zd3z commented on samples/net/sockets/mtls_http_get/README.rst
> +to do mTLS with Zephyr.
There is a space at the end of this line.

2022-02-27 00:29 UTC, closed without merging