linker: add DWARF-5 debug sections
zephyrproject-rtos/zephyr pull request #40258
Opened 2021-11-10 15:38 UTC by semihalf-barnas-michal

DWARF-5 standard replaced the location list (.debug_loc) and range
list (.debug_ranges) sections with new sections (.debug_loclists
and .debug_rnglists).
They weren't handled which resulted in many orphan sections
reported as warnings by linker.

Signed-off-by: Michał Barnaś <mb@semihalf.com>

2021-11-10 16:24 UTC, dcpleung approved these changes

2021-11-10 19:49 UTC, brockus-zephyr requested changes
I had to add an additional line to remove my ITE warnings. Can you add .debug_line_str?

> 	/* DWARF 5 */
> 	SECTION_PROLOGUE(.debug_line_str, 0,)  { *(.debug_line_str) }
> 	SECTION_PROLOGUE(.debug_loclists, 0,)  { *(.debug_loclists) }
> 	SECTION_PROLOGUE(.debug_rnglists, 0,)  { *(.debug_rnglists) }

2021-11-12 10:48 UTC, semihalf-barnas-michal commented
> I had to add an additional line to remove my ITE warnings. Can you add .debug_line_str?
> 
> > /* DWARF 5 */
> > SECTION_PROLOGUE(.debug_line_str, 0,)  { *(.debug_line_str) }
> > SECTION_PROLOGUE(.debug_loclists, 0,)  { *(.debug_loclists) }
> > SECTION_PROLOGUE(.debug_rnglists, 0,)  { *(.debug_rnglists) }

Sure, done and checked with hayato

2021-11-15 15:59 UTC, brockus-zephyr approved these changes

2021-11-15 19:52 UTC, merged