tests: edtt: re-enable HCI tests
zephyrproject-rtos/zephyr pull request #40632
Opened 2021-11-24 14:07 UTC by kruithofa

HCI tests HCI/DSU/BV-05-C and HCI/GEV/BV-01-C fail when
compiling with debug optimisations turned on.
Therefor revert to not compiling with debug optimisations.

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2021-11-24 14:10 UTC, jhedberg approved these changes

2021-11-24 14:11 UTC, thoh-ot requested changes

2021-11-24 14:11 UTC, thoh-ot commented on tests/bluetooth/bsim_bt/compile.source
> -    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"}"
Please leave in the CMAKE_EXPORT_COMPILE_COMMANDS, it's a useful feature when using clang based tools to analyze the source.

2021-11-24 16:15 UTC, thoh-ot commented
The real issue here is not about debug optimization, it due to the fact that the DUT app is sent an HCI command packet from the EDTT test script that is 255 bytes long (Adv Ext), but the DUT app is configured without support for Adv Ext, so it only has buffer space for the default 65 bytes long commands, the EDTT test expects the DUT to respond with a Unknown Command Response, but the target crashes due to an Segmentation Fault.

The DUT app mindlessly copies the 255 bytes into the 65 bytes net buffer and it overwrites memory following the data buffer.

The memory layout shift a bit depending on CONFIG_DEBUG_OPTIMIZATIONS and that's why it seems like it works, but the error is still there:

With CONFIG_DEBUG_OPTIMIZATIONS=y memory is layout like this:
```
[net_buf_data_hci_cmd_pool]
[_net_buf_hci_cmd_pool]
```

So data overflows writes into the command net buffer book-keeping.

With CONFIG_DEBUG_OPTIMIZATIONS=n memory is layout like this:
```
[net_buf_data_hci_cmd_pool]
[_net_buf_hci_acl_pool]
```

So data overflows writes into the acl net buffer book-keeping.

2021-11-25 11:11 UTC, thoh-ot approved these changes

2021-11-25 14:56 UTC, kruithofa commented
The buffer overflow error is submitted as issue #40672

2021-11-25 15:44 UTC, merged