drivers: mcux_flexspi: Default logging to disabled when XIP is used
zephyrproject-rtos/zephyr pull request #40794
Opened 2021-11-30 20:31 UTC by danieldegrasse

Program flow will behave incorrectly (memory and instruction fetches
return invalid data) if Flexspi is accessed by the Flexspi driver while
being used as XIP memory by the Cortex M7.

Set logging to disabled by when XIP mode is used in the memc and
flexspi drivers, and warn the user if they attempt to enable it.

Fixes #40133

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

2021-12-03 16:08 UTC, dleach02 approved these changes

2021-12-03 16:14 UTC, mmahadevan108 approved these changes

2021-12-03 16:18 UTC, dleach02 commented
Note: Please merge backport #40792 first to ensure clean bisectability

2021-12-03 16:19 UTC, dleach02 requested changes
backport merge #40792 first for bisect support.

The original PR was in response to the previous change that was merged and marked for backport.

2021-12-06 17:07 UTC, dleach02 approved these changes
rt6xx backport has been merged so releasing my block in this PR

2021-12-06 19:11 UTC, bbilas approved these changes

2021-12-08 13:57 UTC, merged