enable edma on mimxrt11xx series board
zephyrproject-rtos/zephyr pull request #40828
Opened 2021-12-02 04:53 UTC by hakehuang

enable edma on mimxrt11xx series board

tested on mimxrt1160_evk_cm7, and build pass for mximxrt1160_evk_cm4

```
*** Booting Zephyr OS build v2.7.99-2040-g1aa4c3f4c2d6  ***
Running test suite dma_m2m_link_test
===================================================================
START - test_dma_m2m_chan0_1_major_link
Preparing DMA Controller: Chan_ID=1, BURST_LEN=1
Starting the transfer
DMA transfer done ch 0
It is harder to be kind than to be wise........
It is harder to
 PASS - test_dma_m2m_chan0_1_major_link in 2.15 seconds
===================================================================
START - test_dma_m2m_chan0_1_minor_link
Preparing DMA Controller: Chan_ID=1, BURST_LEN=1
Starting the transfer
DMA transfer done ch 0
It is harder to be kind than to be wise........
It is harder to be kind than to
 PASS - test_dma_m2m_chan0_1_minor_link in 2.14 seconds
===================================================================
START - test_dma_m2m_chan0_1_minor_major_link
Preparing DMA Controller: Chan_ID=1, BURST_LEN=1
Starting the transfer
DMA transfer done ch 0
DMA transfer done ch 1
It is harder to be kind than to be wise........
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan0_1_minor_major_link in 2.15 seconds
===================================================================
Test suite dma_m2m_link_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

2021-12-02 13:32 UTC, dleach02 approved these changes

2021-12-02 13:42 UTC, dleach02 requested changes
How are these changes related to #40183?

2021-12-02 15:22 UTC, danieldegrasse reviewed
@hakehuang #40183 Should already handle DMA for the RT1170/1160. However, the Cortex M4 core will not work in either PR, because we lack the infrastructure in Zephyr to mark a custom region of memory on the M4 as noncacheable. Without the memory being marked as noncachable, DMA tests will fail.

Either of these PRs should work to add support for the RT1170. I noticed your PR adds the LPSR clock to the clock control module, which I didn't catch in my PR. If we end up going with mine, I'll add that to the PR

2021-12-03 02:48 UTC, hakehuang commented
> How are these changes related to #40183?

let's use daniel's PR, and close this one

2021-12-03 02:48 UTC, closed without merging