pwm: stm32: Modify digital filter for timer capture driver
zephyrproject-rtos/zephyr pull request #40966
Opened 2021-12-07 15:43 UTC by lmajewski

With the current code there is no digital filtering applied to the
stm32 PWM/capture driver (in init_capture_channel() function).

It turns out that for stm32h743 (nucleo_h743zi) board the filter
needs to be enabled to allow correct operation - this change
follows recommendation from point 39.3.5 "Input Capture Mode"
 -   point 3 (from Reference Manual "RM0433 Rev 7").

This problem has been discovered when the PWM loopback test was
run (./zephyr/tests/drivers/pwm/pwm_loopback/).

Signed-off-by: Lukasz Majewski <lukma@denx.de>

2021-12-08 10:03 UTC, ABOSTM commented
Hi @lmajewski ,
I am not in line with this PR:
This is right that Reference Manual talk about setting Input Filter, but it should be done according to the input signal. especially when signal is not stable.
But It should not be the case with the loopback test, wire between output timer and input timer should be present before test, and no there should be no transient pulse on the line.
Adding input filter will impact the behavior: 
* for example with a continuous measurement, computation will be done only 1 out of 8 pulse instead of at each pulse.
* let's imagine application need to measure the length of a single pulse, it will be skipped due to the filter.

So I think there is something wrong with the test on this board. And filter is not the appropriate solution.

2021-12-08 13:17 UTC, lmajewski commented
> Hi @lmajewski , I am not in line with this PR: This is right that Reference Manual talk about setting Input Filter, but it should be done according to the input signal. especially when signal is not stable. But It should not be the case with the loopback test, wire between output timer and input timer should be present before test, and no there should be no transient pulse on the line. Adding input filter will impact the behavior:
> 
>     * for example with a continuous measurement, computation will be done only 1 out of 8 pulse instead of at each pulse.
> 
>     * let's imagine application need to measure the length of a single pulse, it will be skipped due to the filter.
> 
> 
> So I think there is something wrong with the test on this board. And filter is not the appropriate solution.

On the Nucleo board (stm32h743) I do use general purpose timers - TIM2 and TIM5 with the `pwm_stm32.c` driver.
There is either some other bug in the driver, or I misunderstood how the driver and timer IP blocks work.

Without adding this filter - the captured time is correct sometimes. It fails in 50% of cases. Maybe using TIM2 and TIM5 is
wrong, and I shall use TIM2 and for example TIM14/15 ? However, I couldn't find any rationale for doing this.

I would be very happy if somebody with "disco" (`disco_l475_iot1.overlay`) stm32 board check if this test still works without modification of the filter.

2021-12-09 12:28 UTC, henrikbrixandersen commented
Could this be a timing issue? The PWM output is applied after the current PWM cycle is complete (synchronously), but PWM capture may be out of sync and capture the previous cycle? I remember discussing this with someone a long time ago, but I don't think we ever reached a conclusion.

2021-12-09 13:40 UTC, lmajewski commented
> Could this be a timing issue? The PWM output is applied after the current PWM cycle is complete (synchronously), but PWM capture may be out of sync and capture the previous cycle? I remember discussing this with someone a long time ago, but I don't think we ever reached a conclusion.

This would be _very_ strange. According to the documentation of the stm32h7xx SoC, timer blocks (TIM2 and TIM5 in my case) are independent ones. 
The only common nominator is the `F_CK_INT` provided to those two blocks.

The [errata ](file:///tmp/mozilla_lukma0/es0392-stm32h742xig-and-stm32h743xig-device-limitations-stmicroelectronics-1.pdf) doesn't mention this problem.

Even more strange - the test (pwm_loopback) generates the PWM signal in a continuous way - i.e. we **do not** capture single pulse signal duration, but waveform, which is generated for hundreds of ms.

Maybe somebody from ST could provide some input to this discussion?
Without setting this filter (as recommended in the Reference Manual) the PWM and capture HW is not working correctly.
I _really_ would like to know why.

2021-12-09 13:46 UTC, ABOSTM commented
@lmajewski,
I am looking at this issue,
unfortunately, as soon as I modify code, even for a simple printf, I got a Zephyr crash () which drastically slowdown my analysis.
I will keep you informed.

2021-12-09 17:24 UTC, lmajewski commented
> @lmajewski, I am looking at this issue, unfortunately, as soon as I modify code, even for a simple printf, I got a Zephyr crash
> 
> ```
> E: 0x800e3a8 is not a valid generic
> E: address is not a known kernel object
> E: syscall z_vrfy_device_usable_check failed check: access denied
> E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
> E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
> E:  xpsr:  0x00000000
> E: Faulting instruction address (r15/pc): 0x75bc51b9
> E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
> E: Current thread: 0x24000100 (test_pulse_capture)
> E: Halting system
> ```
> 
> which drastically slowdown my analysis. I will keep you informed.

I'm testing this stuff with `Nucleo STM32H742ZI2` and by using oscilloscope.

To compile/debug - I do use the `west debug` command. It also helps to use reduced printk - i.e. `CONFIG_LOG_MODE_MINIMAL=y`

2021-12-10 16:38 UTC, ABOSTM commented
@lmajewski,
I finally found the issue:
Output pin PA1 (TIM2_CH2) is connected to Ethernet on Nucleo_H743ZI2. And this disrupt timer output signal.
I changed it to PA3 (TIM2_CH3) on Arduino connector A0.
and test is passed.
PR #41076
Can you confirm that #41076 (without  current PR #40966) is working for you too 

So I confirm the current PR #40966 is not needed.

2021-12-10 17:09 UTC, ABOSTM commented
BTW, I tested disco_l475_iot1, and tested is passed without the Digital filter

2021-12-10 17:10 UTC, ABOSTM requested changes
PR not required. #41076 fixes the issue on Nucleo_H743ZI2

2021-12-13 12:30 UTC, lmajewski commented
@ABOSTM 
I've tested your suggestion - and it works as expected :-) Thanks!

I've prepared the PR with fix: https://github.com/zephyrproject-rtos/zephyr/pull/41109

And this PR can be safely closed.

2021-12-13 12:30 UTC, closed without merging