drivers: dma_stm32: init DMA struct in dma_stm32_configure
zephyrproject-rtos/zephyr pull request #41161
Opened 2021-12-14 17:12 UTC by nfaurant

The init struct for DMA peripheral is allocated in stack
and must be initialized (e.g. with LL_DMA_StructInit here)
to avoid loading undefined values in the DMA peripheral
registers.

2021-12-15 09:29 UTC, erwango approved these changes
Good catch, thanks!

2021-12-15 09:36 UTC, erwango requested changes
Struct was already 0 initialized, but I agree this is probably better to use the dedicated function (given the structure could have variable definitions depending on series and on new series we don't know a priori the correct init value).
This being said, please update `DMA_InitStruct` initial definition, as it doesn't need to be zero initialized anymore.

2021-12-17 11:02 UTC, nfaurant commented
> This being said, please update `DMA_InitStruct` initial definition

Done

2021-12-17 12:33 UTC, erwango approved these changes

2021-12-17 12:47 UTC, FRASTM approved these changes

2021-12-17 17:51 UTC, MaureenHelm approved these changes

2021-12-17 17:52 UTC, merged