samples: restore cpp_synchronization test
zephyrproject-rtos/zephyr pull request #413
Opened 2017-06-06 20:53 UTC by andrewboie

Issue: ZEP-2172
Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

2017-06-06 22:02 UTC, lpereira requested changes
LGTM, but please s/fiber|task/thread/

2017-06-06 22:12 UTC, andrewboie commented
should be fixed now

2017-06-06 23:04 UTC, nashif requested changes

2017-06-06 23:04 UTC, nashif commented on samples/cpp_synchronization/README.txt
> +The background task and a fiber take turns printing a greeting message to the
task and fiber?

2017-06-06 23:12 UTC, andrewboie commented
README updated

2017-06-07 00:37 UTC, nashif approved these changes

2017-06-07 00:37 UTC, merged