soc: arm: st_stm32: add STM32H725XX family support
zephyrproject-rtos/zephyr pull request #41361
Opened 2021-12-21 10:40 UTC by aunsbjerg

Add support for the stm32h725 family.

The only difference between the stm32h723 and stm32h725 families are that the h725 family has an built-in SMPS module which is available for use in code only when the `STM32H725XX` define is set, which this PR provides.

Changes have been tested on a custom board using an STM32H725VG mcu.

2021-12-21 13:29 UTC, manoj153 commented
Quickly ruining through the changes, I don't see anywhere you're enabling SMPS.

2021-12-21 13:49 UTC, erwango commented
> Quickly ruining through the changes, I don't see anywhere you're enabling SMPS.

@manoj153 SMPS support is declared in CMSIS file: `stm32cube/stm32h7xx/soc/stm32h725xx.h`.

2021-12-21 13:50 UTC, erwango commented on dts/arm/st/h7/stm32h725.dtsi
> +#include <st/h7/stm32h723.dtsi>
It would be worth adding a comment stating: STM32H725 is STM32H723 + SMPS

2021-12-21 13:52 UTC, erwango requested changes
LGTM aside a comment that would be worth adding in device tree.

2021-12-21 14:41 UTC, manoj153 commented
> > Quickly ruining through the changes, I don't see anywhere you're enabling SMPS.
> 
> @manoj153 SMPS support is declared in CMSIS file: `stm32cube/stm32h7xx/soc/stm32h725xx.h`.

If I understood right, @aunsbjerg want to use SMPS, so I suppose `CONFIG_POWER_SUPPLY_DIRECT_SMPS` should be set, which seems to be missing now.

2021-12-21 14:54 UTC, aunsbjerg commented
> > > Quickly ruining through the changes, I don't see anywhere you're enabling SMPS.
> > 
> > 
> > @manoj153 SMPS support is declared in CMSIS file: `stm32cube/stm32h7xx/soc/stm32h725xx.h`.
> 
> If I understood right, @aunsbjerg want to use SMPS, so I suppose `CONFIG_POWER_SUPPLY_DIRECT_SMPS` should be set, which seems to be missing now.

You are right, I do want to use SMPS and I do use `CONFIG_POWER_SUPPLY_DIRECT_SMPS=y` in my board definition. I do not know enough about the SoC to judge if SMPS should be enabled by default, but if that is the case, then I will of course add it to the appropriate kconfig file.

2021-12-21 15:26 UTC, manoj153 commented
> > > > Quickly ruining through the changes, I don't see anywhere you're enabling SMPS.
> > > 
> > > 
> > > @manoj153 SMPS support is declared in CMSIS file: `stm32cube/stm32h7xx/soc/stm32h725xx.h`.
> > 
> > 
> > If I understood right, @aunsbjerg want to use SMPS, so I suppose `CONFIG_POWER_SUPPLY_DIRECT_SMPS` should be set, which seems to be missing now.
> 
> You are right, I do want to use SMPS, and I do use `CONFIG_POWER_SUPPLY_DIRECT_SMPS=y` in my board definition. I do not know enough about the SoC to judge if SMPS should be enabled by default, but if that is the case, then I will of course, add it to the appropriate kconfig file.

Sorry, you're doing it correctly. I just realised this PR is related to SoC.

2021-12-21 15:31 UTC, aunsbjerg commented
> Sorry, you're doing it correctly. I just realised this PR is related to SoC.

No worries :)

@erwango I pushed an updated dts commit with a comment on the reason for inheriting the h723 devicetree, as you suggested.

2021-12-21 16:04 UTC, erwango approved these changes, later dismissed

2022-01-06 21:08 UTC, MaureenHelm requested changes
small nitpick

2022-01-06 21:08 UTC, MaureenHelm commented on dts/arm/st/h7/stm32h725Xg.dtsi
> +				reg = <0x08000000 DT_SIZE_K(1024)>;
You can use `DT_SIZE_M(1)` instead

2022-01-10 08:22 UTC, erwango commented
@MaureenHelm Can you have a new look ?

2022-01-10 08:27 UTC, FRASTM approved these changes

2022-02-28 14:00 UTC, aunsbjerg commented
@erwango @MaureenHelm anything I can do to get this PR merged?

2022-02-28 14:36 UTC, erwango approved these changes

2022-02-28 15:15 UTC, MaureenHelm approved these changes

2022-02-28 15:15 UTC, merged