Wip sanitycheck
zephyrproject-rtos/zephyr pull request #414
Opened 2017-06-07 05:17 UTC by agross-linaro

This patch creates a new sanitycheck target.  this target collates the kconfig options with the DTS generated ones.  Sanitycheck will now filter properly for DTS enabled targets for DTS generated config options.

2017-06-07 14:11 UTC, galak requested changes
Can we rename the 'sanitycheck' target and file name to something like 'config-sanitycheck' & '.config-sanitycheck'.

2017-06-07 15:24 UTC, agross-linaro commented
yeah that'd be easy.  Let me do that and repush

2017-06-07 15:48 UTC, galak requested changes
nit picking, but you didn't update commit message for new make targets ;)

2017-06-07 15:56 UTC, agross-linaro commented
oooops. fixed

2017-06-07 16:51 UTC, galak requested changes
Sorry for being annoying, but can we have the first commit message be something like:

Makefile: Add config-sanitycheck target

This patch adds a separate target for config-sanitycheck that will generate a .config-sanitycheck file ....

[ when I see unqualified sanitycheck i think a target to run sanitycheck or do something like that]

2017-06-15 20:56 UTC, galak commented
Updated commit message and sent new PR #514

2017-06-15 20:56 UTC, closed without merging