drivers: ieee802154_nrf5: fix condition for mac keys and frame counter
zephyrproject-rtos/zephyr pull request #41680
Opened 2022-01-10 08:41 UTC by lmaciejonczyk

For multicore devices like nRF54, shim layer part of setting mac keys and frame counters is called on application core where
CONFIG_NRF_802154_ENCRYPTION is disabled (the define concerns radio driver for net core).
This commit replaces CONFIG_NRF_802154_ENCRYPTION with CONFIG_IEEE802154_2015.

2022-01-10 09:45 UTC, rlubos approved these changes

2022-01-10 10:09 UTC, edmont approved these changes

2022-01-11 09:56 UTC, hubertmis reviewed
Is there any dependency between `IEEE802154_2015` and `NRF_802154_ENCRYPTION` configuration flags? I understand this patch fixes the issue for dual-core devices running ieee802154_nrf5.c on other core than the radio driver itself. But I would like to make sure it does not create a problem for single core devices.

2022-01-11 09:58 UTC, lmaciejonczyk commented
> Is there any dependency between `IEEE802154_2015` and `NRF_802154_ENCRYPTION` configuration flags? I understand this patch fixes the issue for dual-core devices running ieee802154_nrf5.c on other core than the radio driver itself. But I would like to make sure it does not create a problem for single core devices.

Currently we do no have such dependency.

2022-01-11 10:06 UTC, hubertmis commented
> Currently we do no have such dependency

Does it mean it's possible to misconfigure single-core device so that ieee802154_nrf5.c expects the radio driver to encrypt the frame (`IEEE802154_2015=y`) while the driver itself does not support encryption (`NRF_802154_ENCRYPTION=n`)?

2022-01-11 10:12 UTC, lmaciejonczyk commented
> > Currently we do no have such dependency
> 
> Does it mean it's possible to misconfigure single-core device so that ieee802154_nrf5.c expects the radio driver to encrypt the frame (`IEEE802154_2015=y`) while the driver itself does not support encryption (`NRF_802154_ENCRYPTION=n`)?

It seems so.

2022-01-11 10:16 UTC, hubertmis requested changes
>> Does it mean it's possible to misconfigure single-core device so that ieee802154_nrf5.c expects the radio driver to encrypt the frame (IEEE802154_2015=y) while the driver itself does not support encryption (NRF_802154_ENCRYPTION=n)?
> 
> It seems so.

By fixing one issue you should not introduce bugs in other configurations. This patch should be modified to work correctly on both single- and dual-core configurations.

2022-01-11 10:25 UTC, lmaciejonczyk commented
> > > Does it mean it's possible to misconfigure single-core device so that ieee802154_nrf5.c expects the radio driver to encrypt the frame (IEEE802154_2015=y) while the driver itself does not support encryption (NRF_802154_ENCRYPTION=n)?
> > 
> > 
> > It seems so.
> 
> By fixing one issue you should not introduce bugs in other configurations. This patch should be modified to work correctly on both single- and dual-core configurations.

This is what it does it. With this patch in current form both configuration are correct.
Little context: currently all required options are enabled by one overlay. The plan for near future is to have one primary option which selects other required. We do not want to have here options with strict dependencies which are difficult for handling where the radio is on the different core.

2022-01-11 12:29 UTC, hubertmis commented
> currently all required options are enabled by one overlay.

I understand this patch works correctly for selected applications or samples providing configuration overlays like the one you described.  But someone might be using this driver in an out-of-tree application without such overlay. This patch could break such application.

2022-01-11 12:33 UTC, hubertmis commented
> We do not want to have here options with strict dependencies

 I don't  think we need to create a dependency. But we need to make sure that configuration options are aligned between 802.15.4 driver build and ieee802154_nrf.c build. Dependency would be one way to solve it, but there are other available.

2022-01-11 14:23 UTC, lmaciejonczyk commented
> I understand this patch works correctly for selected applications or samples providing configuration overlays like the one you described. But someone might be using this driver in an out-of-tree application without such overlay. This patch could break such application.

This is very doubtful assumption that someone is using this quite new feature which were provided for Thread and it's not using Thread but some other protocol. But let say you are right in this, what do you suggest? Frankly speaking any other solution which comes to my mind seems much worse than we have right now.

2022-01-11 15:28 UTC, hubertmis commented
> But let say you are right in this, what do you suggest?

My point is that with this patch it's very easy to misconfigure an application (existing or a new one). I understand we should not babysit developers, but we should make project configuration user friendly.

My understanding of the configuration options we are discussing is like this:

- IEEE802154_2015 is a system wide configuration option stating that 2015 version frames are supported
- NRF_802154_ENCRYPTION_ENABLED is an option related to nRF 802.15.4 radio driver enabling frame encryption in this driver.

In single-core applications the code responsible for managing radio diriver cryptography shall be enabled only when radio driver has encryption enabled (NRF_802154_ENCRYPTION_ENABLED).
The question is how to enable this code in dual- core projects where the radio driver is replaced with a serialization library.
The simplest solution that comes to me is to use NRF_802154_ENCRYPTION_ENABLED with serialization library to enable serializing crypto-related operations. Another option would be stating that NRF_802154_ENCRYPTION_ENABLED should be enabled by default when version 2015 is supported and guard crypto-related code with IEEE802154_2015. Another option is to forcefully select NRF_802154_ENCRYPTION_ENABLED when nRK 802.15.4 driver is present and version 2015 is supported. Probably other solutions are available.

But guarding implementation of a function with one configuration option while usage of this function is guarded by an unrelated option is not a user-friendly configuration design.

2022-01-12 09:44 UTC, lmaciejonczyk commented
> My point is that with this patch it's very easy to misconfigure an application (existing or a new one). I understand we should not babysit developers, but we should make project configuration user friendly.
> 
> My understanding of the configuration options we are discussing is like this:
> 
>     * IEEE802154_2015 is a system wide configuration option stating that 2015 version frames are supported
> 
>     * NRF_802154_ENCRYPTION_ENABLED is an option related to nRF 802.15.4 radio driver enabling frame encryption in this driver.
> 
> 
> In single-core applications the code responsible for managing radio diriver cryptography shall be enabled only when radio driver has encryption enabled (NRF_802154_ENCRYPTION_ENABLED). The question is how to enable this code in dual- core projects where the radio driver is replaced with a serialization library. The simplest solution that comes to me is to use NRF_802154_ENCRYPTION_ENABLED with serialization library to enable serializing crypto-related operations. Another option would be stating that NRF_802154_ENCRYPTION_ENABLED should be enabled by default when version 2015 is supported and guard crypto-related code with IEEE802154_2015. Another option is to forcefully select NRF_802154_ENCRYPTION_ENABLED when nRK 802.15.4 driver is present and version 2015 is supported. Probably other solutions are available.
> 
> But guarding implementation of a function with one configuration option while usage of this function is guarded by an unrelated option is not a user-friendly configuration design.

I think you too oversimplify the problem. For dual-core application the image on radio core is build separately which imply that we don't know if the configuration is right until run time. The only option to verify on the early stage if will work is to call get_capabilities from radio and check expected result. But this PR is not for fixing existing problems (we already can misconfigure application even single-core application) or future one (how to make sure that dual-core application is configured properly). This PR is to fix the wrong conditions for dual-core application without breaking sinle-core application. And the PR does it. Take notice that to work properly an single-core application already needs to enabled both flags: CONFIG_NRF_802154_ENCRYPTION and CONFIG_IEEE802154_2015 so nothing will change.

2022-01-12 13:46 UTC, hubertmis commented
I disagree. Currently it is fine to enable `CONFIG_NRF_802154_ENCRYPTION` with `CONFIG_IEEE802154_2015` disabled and use the encryption feature for 802.15.4-2006 frames. With your patch is not possible anymore.

> This PR is to fix the wrong conditions for dual-core application without breaking sinle-core application. 

This PR is working around the problem in dual-core application by providing incorrect configuration guards in ieee802154_nrf5.c. I'm not OK with working around problems taking shortcuts leading to other problems. If we cannot create a workaround for dual-core which does not cause problems for single-core, maybe proper fix should be implemented instead?

2022-01-19 09:06 UTC, tbursztyka approved these changes

2022-01-19 19:16 UTC, merged