JSON array fixes
zephyrproject-rtos/zephyr pull request #418
Opened 2017-06-07 18:42 UTC by mbolivar

Fixes and regression tests for the JSON library's array handling.

2017-06-07 19:01 UTC, mbolivar commented
@lpereira got time for another JSON review?

2017-06-07 21:42 UTC, lpereira requested changes
The patches look good, thanks! Just a few minor nits.

2017-06-07 21:42 UTC, lpereira commented on lib/json/json.c
> +		 * but that would add a size_t to every descriptor.
Thanks for adding these comments.

2017-06-07 21:42 UTC, lpereira commented on lib/json/json.c
> -		}
Might be nice if we had a test for the case you're fixing with this commit.

2017-06-07 21:42 UTC, lpereira commented on lib/json/json.h
> + *           JSON_OBJ_DESCR_OBJ_ARRAY(struct people_heights, heights, 10,
Where is the field name in this example code?

2017-06-07 21:42 UTC, lpereira commented on lib/json/json.h
> + * Here's an example of use:
Can we mark the example of use with some markup that'll get it syntax-highlighted in the documentation?

2017-06-07 22:41 UTC, mbolivar commented on lib/json/json.c
> -		}
We do -- the last patch adds a test which fills an array completely.

2017-06-07 22:43 UTC, mbolivar commented on lib/json/json.h
> + * Here's an example of use:
None of the existing macros' documentation has such markup -- can that be done as a separate cleanup patch, outside of this series?

2017-06-07 22:44 UTC, lpereira commented on lib/json/json.h
> + * Here's an example of use:
Of course.

2017-06-07 22:45 UTC, mbolivar commented on lib/json/json.h
> + *           JSON_OBJ_DESCR_OBJ_ARRAY(struct people_heights, heights, 10,
The field name is "heights", which is argument 2.

The docstring for JSON_OBJ_DESCR_OBJ_ARRAY() below shows a field name "people-heights" and a struct field name "heights".

2017-06-07 22:46 UTC, mbolivar commented on lib/json/json.h
> + * Here's an example of use:
Thanks!

2017-06-08 15:23 UTC, mbolivar commented
@lpereira, any other feedback?

2017-06-08 16:12 UTC, lpereira approved these changes
LGTM

2017-06-08 19:11 UTC, merged