Bluetooth: controller: LLCP: Rejection logic for handling non-supported features
zephyrproject-rtos/zephyr pull request #41886
Opened 2022-01-17 16:31 UTC by thoh-ot

Implement rejection logic for handling non-supported features and unit tests for:

- Invalid opcodes based on controller role
- No LE Encryption support
- No Connection Parameters Request procedure support
- No Peripheral-initiated Features Exchange support
- No LE 2M PHY/LE Coded PHY support

2022-01-18 10:58 UTC, erbr-ot reviewed
Looks real good to me. Look forward to trying it and perhaps to get a walk through on Thursday?

2022-01-20 09:09 UTC, kruithofa commented on subsys/bluetooth/controller/ll_sw/ull_llcp_remote.c
> +		struct proc_ctx *ctx = llcp_rr_peek(conn);
This is a merge error and needs to be fixed

2022-01-20 09:26 UTC, kruithofa commented on tests/bluetooth/controller/ctrl_unsupported/src/main.c
> +{
add test for undefined opcode

2022-01-20 09:27 UTC, kruithofa commented on tests/bluetooth/controller/ctrl_unsupported/src/main.c
> +{
in particular opcode 255 may be an issue

2022-01-21 13:32 UTC, kruithofa approved these changes, later dismissed

2022-01-21 14:01 UTC, erbr-ot approved these changes, later dismissed
LGTM

2022-02-16 12:41 UTC, tejlmand requested changes, later dismissed
CMake version is now 3.20

2022-02-16 12:41 UTC, tejlmand commented on tests/bluetooth/controller/ctrl_unsupported/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13.1)
```suggestion
cmake_minimum_required(VERSION 3.20)
```

2022-02-16 12:41 UTC, tejlmand commented on tests/bluetooth/controller/ctrl_unsupported/testcase.yaml
> +     extra_args: NO_ENC=y KCONFIG_OVERRIDE_FILE="kconfig_override.h"
seems like I was not invited to this party #40073

The way `KCONFIG_OVERRIDE_FILE` and `tests/bluetooth/controller/common/defaults_cmake.txt` appears to be short cutting everything else we do in the build system.

But guess that is outside the scope of this PR.

2022-03-03 10:34 UTC, ppryga approved these changes
I did quick pass-through and I didn't find anything blocking the PR so approve it.

2022-03-04 12:10 UTC, kruithofa approved these changes

2022-03-07 15:15 UTC, merged