stm32g4: adc: Add DTS for ADC345
zephyrproject-rtos/zephyr pull request #41934
Opened 2022-01-18 23:13 UTC by pdietl

Add DTS information for ADCs 3, 4, and 5 for stm32g4

Signed-off-by: Pete Dietl <petedietl@gmail.com>

2022-01-19 08:59 UTC, erwango requested changes

2022-01-19 08:59 UTC, erwango commented on dts/arm/st/g4/stm32g4.dtsi
> +		};
To be moved to g473, g474, g483, g484, g491, g4a1

2022-01-19 08:59 UTC, erwango commented on dts/arm/st/g4/stm32g4.dtsi
> +		};
To be moved to g473, g474, g483, g484

2022-01-19 16:58 UTC, FRASTM commented
The ADC 3 4 5 share a common bank of 1KB at  0x50000400. In the Table 166. ADC global register map from 0x50000400
Offset 0x000 - 0x0FC  stores the Master ADC3 registers
Offset 0x100 - 0x1FC stores the Slave ADC4  registers 
Offset 0x200 - 0x2FC is Reserved/single ADC5 registers
Offset 0x300 - 0x30C stores Master and slave ADCs common registers
So that ADC 3  and 4  have some of their common registers at address 0x50000400 + 0x300,
Should  ADC 3 and 4 access that area ?

2022-01-20 02:01 UTC, pdietl commented
@FRASTM It looks like 3, 4, & 5 have common registers at + 0x300. The same goes for ADC 1 & 2, and we don't indicate the offset of that shared memory region either. Is it possible to specify multiple `reg`s?

Also, we don't need to know that offset, because it is taken care of by the LL library: `LL_ADC_GetCommonPathInternalCh(__LL_ADC_COMMON_INSTANCE(adc));`

2022-01-20 07:52 UTC, erwango approved these changes

2022-01-20 08:51 UTC, FRASTM approved these changes

2022-01-21 19:38 UTC, merged