dts: stm32: added SPI 2&3 for stm32f105
zephyrproject-rtos/zephyr pull request #42079
Opened 2022-01-24 11:00 UTC by mkolchurin

Added device tree definition for SPI2 and SPI3 in STM32F105

2022-02-15 11:25 UTC, FRASTM requested changes

2022-02-15 11:25 UTC, FRASTM commented on dts/arm/st/f1/stm32f105.dtsi
> +			clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>;
SPI2 is on RCC_APB1ENR   bit 14   (according to the RefMan RM0008)

2022-02-15 11:28 UTC, FRASTM commented on dts/arm/st/f1/stm32f105.dtsi
> +		spi3: spi@4003C000 {
better is lower case '4003c000' for node and reg address

2022-03-02 07:41 UTC, erwango commented
@mkolchurin Do you plan to fix update this PR?

2022-03-02 15:36 UTC, erwango approved these changes, later dismissed

2022-03-03 07:42 UTC, FRASTM submitted a review, later dismissed

2022-03-29 21:30 UTC, MaureenHelm approved these changes

2022-03-30 00:05 UTC, mbolivar-nordic commented
Could someone from ST please re-ack?

2022-03-30 07:00 UTC, erwango approved these changes

2022-03-30 09:40 UTC, merged