drivers: uart stm32 F4X, F1X, F2X have a sw sequence to clear error flags
zephyrproject-rtos/zephyr pull request #42217
Opened 2022-01-27 09:23 UTC by FRASTM

This is just a PR to add comments to the uart_stm32.c

Gives more explanation on uart_stm32_err_check function.
On stm32 F4X, F1X, and F2X, when clearing the usart Error Flag (PE, ORE, FE, NE), the  LL Clear function applies a software sequence which reads the usart SR then the usart DR.
Consequently the RXNE flag is affected (cleared) by the uart_stm32_err_check function call.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/41818

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-01-28 15:34 UTC, erwango requested changes

2022-01-28 15:45 UTC, FRASTM commented
change text as suggested

2022-01-28 15:55 UTC, FRASTM commented
resolving conflict

2022-01-28 15:57 UTC, erwango approved these changes

2022-02-01 18:39 UTC, dcpleung approved these changes

2022-02-01 21:21 UTC, merged