drivers/flash: Remove the flash write protection API
zephyrproject-rtos/zephyr pull request #42257
Opened 2022-01-28 10:52 UTC by nvlsianpu

This API was designed to be removed in Zephyr 2.8

As prepartraion:
The ite_i8xx3 driver was reworked to serve protection by itself.
In its case the `write_protection` handler was introduced despite that the API had been
already deprecated at the addition time.

2022-01-28 20:11 UTC, MaureenHelm requested changes, later dismissed
Please add to the 3.0 release notes

2022-01-31 10:26 UTC, nvlsianpu commented
@MaureenHelm The note was added.
@de-nordic Can you review?

2022-01-31 11:06 UTC, de-nordic approved these changes
Looks OK.

2022-01-31 16:21 UTC, carlescufi approved these changes

2022-01-31 19:46 UTC, MaureenHelm approved these changes

2022-02-01 09:46 UTC, merged