esp32: Added rodata injection to esp32 build
zephyrproject-rtos/zephyr pull request #42263
Opened 2022-01-28 14:17 UTC by melka

When building for ESP32, the linker scripts were not loaded by zephyr_linker_sources.
This PR fixes that and allows custom linker scripts to be added to the build.

Shoutout to Sylvio on Zephyr discord for the solution.

Signed-off-by: Kamel Makhloufi melka@blaste.net

2022-01-28 20:08 UTC, sylvioalves approved these changes

2022-01-28 20:09 UTC, sylvioalves requested changes
@melka, sorry. Code is correct but you have to fix the commits. Please, squash them all in a single one. The middle one is correct: https://github.com/zephyrproject-rtos/zephyr/pull/42263/commits/893cb203bf3c08cf8be1f808a58313a5fe84e649

2022-01-28 20:30 UTC, uLipe reviewed
Aside the comments, LGTM

2022-01-30 13:21 UTC, melka commented
Hey @sylvioalves, I tried to do the requested changes but I am bad at git commits and PR requests, so let me know if I should redo it again. Sorry for the inconvenience, not used to working on big projects like this one.

2022-01-30 16:58 UTC, sylvioalves commented
> Hey @sylvioalves, I tried to do the requested changes but I am bad at git commits and PR requests, so let me know if I should redo it again. Sorry for the inconvenience, not used to working on big projects like this one.

You can check current errors in here: https://github.com/zephyrproject-rtos/zephyr/runs/4997252486?check_suite_focus=true  

1) Both description lines are too big. Break them. (max 75 chars in a single line).
2) As from guidelines, sign-off is required in every commit message. Use `git commit -s` to added it. In your case, I guess your Signed-off-by is missing `<` and `>` surrounding the email.

2022-03-16 12:16 UTC, sylvioalves commented
Merged #43725

2022-03-16 12:16 UTC, closed without merging