WIP log_backend_memory
zephyrproject-rtos/zephyr pull request #42284
Opened 2022-01-29 03:12 UTC by laurenmurphyx64

A really rough WIP of a memory logging backend. I'm still in the process of making changes to match with feedback I got recently, so the code is more up as a skeleton of what I'm doing than a prototype. For those wondering what the memory backend would do, here's the rundown:

> The memory backend writes logs to a buffer in memory, either in RAM or flash (or disk, in the future?). It can cache characters passed through `char_out` into a block buffer and write blocks at a time into the memory buffer to avoid flash wear. Using RAM allows for a host system to read logs live or post-crash if it has access to RAM. Using flash allows logs to be read post-mortem.

You can see the Kconfig options in `Kconfig.backends` for more information.

This backend would also have general uses, but I'm introducing it specifically to support flushing logs to memory on crash:

> If the LOG_FLUSH_ON_CRASH option is selected, the log_memory_backend will be selected but remain deactivated until kernel panic. When it receives the logging panic notification, it will activate and begin processing log messages.

Feedback would still be appreciated on the Kconfig options and (the many, possibly unnecessary) BUILD_ASSERTS. I also have some other questions:

- How can I let users plug in a flash partition to store the memory buffer - Kconfig, Devicetree, linker script fragment...?
- The winstream API isn't designed to work with flash, so unless I re-implement or modify it, users who want to use flash can't enable the PRESERVE_NEWEST option if the memory buffer overflows
- Should I implement the memory backend as separate backends (flash, memory/RAM, disk...) instead of one?

2022-02-03 22:47 UTC, nashif requested changes
first pass

2022-02-03 22:47 UTC, nashif commented on samples/hello_world/prj.conf
> -# nothing here
do not use hello_world for testing

2022-02-03 22:47 UTC, nashif commented on subsys/logging/log_backend_memory.c
> +	.put = IS_ENABLED(CONFIG_LOG1_DEFERRED) ? put : NULL,
please make this work for v2 only, no need to support v1 which is deprecated.

2022-02-03 22:47 UTC, nashif commented on subsys/logging/Kconfig.backends
> +config LOG_BACKEND_MEMORY
it is time to start having single Kconfig files for each backend I guess...

2022-02-08 18:06 UTC, teburd reviewed
This is mostly ok, I'd work towards creating a test case for this rather than using hello world for testing

2022-02-08 18:06 UTC, teburd commented on subsys/logging/Kconfig.backends
> +	# TODO: Are these reasonable defaults? First is a sentence, second is paragraph
This is fine, err on the side of larger is better here, when people run out of memory they will start tweaking the knobs. If you can capture a typical crash dump its fine.

2022-04-25 00:29 UTC, closed without merging