doc: devicetree: fix broken link in api.rst
zephyrproject-rtos/zephyr pull request #42291
Opened 2022-01-29 14:55 UTC by helo9

The devicetree binding link for fixed-partitions is broken. I assumed the file is now called _fixed_partitions.yaml_. See https://docs.zephyrproject.org/latest/reference/devicetree/api.html#fixed-flash-partitions.

2022-02-01 13:11 UTC, nashif approved these changes

2022-02-01 13:39 UTC, gmarull requested changes

2022-02-01 13:39 UTC, gmarull commented on doc/reference/devicetree/api.rst
>  compatible's binding.
I think this should actually be:

```suggestion
device tree. See :dtcompatible:`fixed-partition` for more details.
```

2022-02-01 22:58 UTC, helo9 commented on doc/reference/devicetree/api.rst
>  compatible's binding.
adapted

2022-02-01 23:19 UTC, gmarull approved these changes

2022-02-03 16:11 UTC, mbolivar-nordic approved these changes

2022-02-03 20:01 UTC, merged