boards like nrf52840dongle: use CDC ACM UART as serial backend
zephyrproject-rtos/zephyr pull request #42371
Opened 2022-02-01 17:20 UTC by jfischer-no

This patch adds new board specific Kconfig options
NRF52840DONGLE_SERIAL_BACKEND_CDCACM / BL654_USB_SERIAL_BACKEND_CDCACM,
which can be used when CDC ACM UART should serve as backend for console or shell.
Application like hci_usb do not need this option.

For console or shell support via USB CDC ACM UART, in-tree samples
for this boards is to be built as follows:

west build -b nrf52840dongle_nrf52840
  samples/basic/threads
  -- -DCONFIG_NRF52840DONGLE_SERIAL_BACKEND_CDCACM=y

or

west build -b bl654_usb samples/bluetooth/hci_uart
  -- -DCONFIG_BL654_USB_SERIAL_BACKEND_CDCACM=y

_This is a workaround until we have agreed on a generic solution like #40645._

Fixes: #39904

2022-02-02 11:08 UTC, carlescufi requested changes

2022-02-02 11:08 UTC, carlescufi commented on subsys/usb/usb_device.c
> +		if (ret) {
why do you need this `if` statement?

2022-02-02 11:48 UTC, jfischer-no commented on subsys/usb/usb_device.c
> +		if (ret) {
(⊙.☉)7, probably c&p

2022-02-02 12:08 UTC, lairdjm commented
This doesn't solve the issue if users still need to supply a random Kconfig when building projects. https://github.com/zephyrproject-rtos/zephyr/pull/39987 fixes this without needing user intervention and providing an easy user experience

2022-02-02 13:24 UTC, jfischer-no commented
> This doesn't solve the issue if users still need to supply a random Kconfig when building projects. #39987 fixes this without needing user intervention and providing an easy user experience

According to my understanding it is not possible and I have tried to explain it to you several times. Probably I am missing something, can you explain to me in what miraculous way it happens that option CONFIG_BOARD_ENABLE_USB_AUTOMATICALLY in #39987 is activated?

2022-02-02 13:27 UTC, lairdjm commented
> > This doesn't solve the issue if users still need to supply a random Kconfig when building projects. #39987 fixes this without needing user intervention and providing an easy user experience
> 
> According to my understanding it is not possible and I have tried to explain it to you several times. Probably I am missing something, can you explain to me in what miraculous way it happens that option CONFIG_BOARD_ENABLE_USB_AUTOMATICALLY in #39987 is activated?

I built an application and it worked, so going off that which I also explained to you several times, yes, it is possible and works.
```
config USB_UART_CONSOLE
	default y if !USB_DEVICE_BLUETOOTH

config BOARD_ENABLE_USB_AUTOMATICALLY
	bool "Enable USB automatically"
	default y if USB_UART_CONSOLE
```

If USB_DEVICE_BLUETOOTH is not set, then USB_UART_CONSOLE is set, if this is set then BOARD_ENABLE_USB_AUTOMATICALLY is set which then enables USB automatically at startup with Kconfig specified in the build options via command line

2022-02-03 10:35 UTC, jfischer-no commented
> ```
> config USB_UART_CONSOLE
> 	default y if !USB_DEVICE_BLUETOOTH
> 
> config BOARD_ENABLE_USB_AUTOMATICALLY
> 	bool "Enable USB automatically"
> 	default y if USB_UART_CONSOLE
> ```
> 
> If USB_DEVICE_BLUETOOTH is not set, then USB_UART_CONSOLE is set, if this is set then BOARD_ENABLE_USB_AUTOMATICALLY is set which then enables USB automatically at startup without any Kconfigs being specified in the build options via command line

There is no USB_UART_CONSOLE, but assuming it describes exact behavior desired by you, it is the same as:
 ```
 config BOARD_ENABLE_USB_AUTOMATICALLY
 	bool "Enable USB automatically"
 	default y if !USB_DEVICE_BLUETOOTH
 ```


or with 951633eeefbae31b06fa97484640b4c8c6cb3a34, 
```
config BL654_USB_SERIAL_BACKEND_CDCACM
	bool "Use CDC ACM UART as backend for BL654 USB adapter"
	default y if !USB_DEVICE_BLUETOOTH
	help
	  Use CDC ACM UART as backend for console or shell.

if BL654_USB_SERIAL_BACKEND_CDCACM

config USB_DEVICE_INITIALIZE_AT_BOOT
	default y

...

endif #BL654_USB_SERIAL_BACKEND_CDCACM
```

Is it correct so far? If yes please approve and accept the resulting disadvantages.

2022-02-07 08:30 UTC, lairdjm approved these changes

2022-02-07 10:34 UTC, carlescufi approved these changes

2022-02-07 12:06 UTC, merged