Bluetooth: Controller: Fix Periodic Sync Terminate race condition
zephyrproject-rtos/zephyr pull request #42402
Opened 2022-02-02 13:18 UTC by cvinayak

Fix Periodic Sync Terminate implementation for race
conditions with ULL scheduling by using a flag to stop any
new ULL scheduling to receive chain PDUs.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2022-02-02 14:47 UTC, Thalley requested changes

2022-02-03 01:21 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_scan_aux.c
> +				LL_ASSERT(ref < 2);
Added comment in code.

2022-02-03 01:21 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_sync.c
> +		/* TODO: detect race */
Added the implementation to confirm the race scenario being handled.

2022-02-03 09:25 UTC, Thalley approved these changes

2022-02-04 14:03 UTC, carlescufi approved these changes

2022-02-04 14:03 UTC, merged