drivers: flash: stm32 qspi driver reads or writes non-null size
zephyrproject-rtos/zephyr pull request #42413
Opened 2022-02-02 15:20 UTC by FRASTM

In case the length of data to read/write/erase is null, the qspi drivers immediately returns without sending any command to the QSPI controller.
This is the same approach as for the stm32 flash driver flash_stm32.c.

The tests/drivers/flash can successfully run on the stm32l4r5 disco kit.

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-02-02 15:20 UTC, FRASTM commented
$ west build -p auto -b disco_l475_iot1 tests/drivers/flash
```
I: MX25R6435F: SFDP v 1.6 AP ff with 3 PH
I: PH0: ff00 rev 1.6: 16 DW @ 30
I: MX25R6435F: 8 MiBy flash
I: PH1: ffc2 rev 1.0: 4 DW @ 110
I: Device MX25R6435F initialized
*** Booting Zephyr OS build v3.0.0-rc1-93-g5dc63b016c08  ***
Running test suite flash_driver_test
===================================================================
START - test_setup
 PASS - test_setup in 0.75 seconds
===================================================================
START - test_read_unaligned_address
 PASS - test_read_unaligned_address in 0.33 seconds
===================================================================
Test suite flash_driver_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

2022-02-02 15:44 UTC, erwango requested changes
Please also delete `tests/drivers/flash/boards/stm32f746g_disco.overlay`

2022-02-02 15:53 UTC, FRASTM commented
idem for stm32f746g_disco : run the tests/drivers/flash/ on the QSPI nor-flash

2022-02-02 15:54 UTC, erwango approved these changes

2022-02-03 12:40 UTC, gmarull commented on drivers/flash/flash_stm32_qspi.c
> +	if (!size) {
nit: better use essentially boolean expressions:

```suggestion
	if (size == 0U) {
```

2022-02-03 12:40 UTC, gmarull commented on drivers/flash/flash_stm32_qspi.c
> +	if (!size) {
```suggestion
	if (size == 0U) {
```

2022-02-03 12:40 UTC, gmarull commented on drivers/flash/flash_stm32_qspi.c
> +	if (!size) {
```suggestion
	if (size == 0U) {
```

2022-02-04 09:04 UTC, FRASTM commented on drivers/flash/flash_stm32_qspi.c
> +	if (!size) {
changed

2022-02-04 09:06 UTC, gmarull approved these changes

2022-02-04 09:17 UTC, FRASTM commented
changed to compare size with 0 explicitely.
Note that flash_stm32.c has the `if (!len) {`

2022-02-08 12:03 UTC, merged