fs: littlefs: Use flash map macro in automount
zephyrproject-rtos/zephyr pull request #42452
Opened 2022-02-03 14:53 UTC by chrta

To identify the flash partition id, the macro FLASH_AREA_ID() was
basically copied from include/storage/flash_map.h.
Now the macro FLASH_AREA_ID() is used.

Now this also supports the usecase when a different flash map
implementation is used that redefines the macros in
include/storage/flash_map.h, e.g. the nordic partition manager.

Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>

2022-02-04 12:19 UTC, de-nordic requested changes
Generally look OK, but change the commit message.
I do not think that the macro has been copied it has probably just been independently written, so I would rather not add this comment to commit log.
Just write that you are replacing the code with FLASH_AREA_ID and add the part about benefits that the change provides (second paragraph).

2022-02-04 13:40 UTC, nvlsianpu reviewed
looks good

2022-03-01 09:27 UTC, de-nordic approved these changes
Looks OK

2022-03-24 12:28 UTC, nashif commented
@nvlsianpu ping

2022-03-24 13:18 UTC, nvlsianpu approved these changes

2022-03-26 11:15 UTC, merged