Add Ateml SAM0 pinctrl for SPI, I2C & TCC
zephyrproject-rtos/zephyr pull request #42512
Opened 2022-02-06 19:10 UTC by attie-argentum

This PR adds pinctrl support for the SAM0 SPI, I2C and TCC (wip) drivers, as a continuation of #35423, and in support of #41308.

2022-02-06 21:58 UTC, nandojve commented
Hi @attie-argentum , you got the spirit !

2022-02-07 00:25 UTC, attie-argentum commented
I'm unsure how we should handle `samr2x-pinctrl.dtsi`... there are a number of functions that the SAMD2x parts have available that are not available on the SAML2x parts - for example:
- On SAML2x, it looks like perhaps PA02 & PA03 aren't bonded out
- On SAML2x, PA04 has `TCC0/WO[0]` on mode `E`, but _does not_ have `TCC3/WO[2]` on mode `F` like the SAMD2x.

For pads that aren't bonded, I'm fairly happy to leave the pinctrl items in place (it's "_harmless_"?), but for modes that aren't available (e.g: `PA04.F`), I'd be tempted to use a `/delete-node/` in `samr2x-pinctrl.dtsi`... I suspect there could be many... any thoughts?

2022-02-07 02:37 UTC, attie-argentum commented
I believe this is now ready for review.

I've tested this on SAML21 XPro and SAMR34 XPro boards (via #41308), as well as our custom board.

2022-02-07 08:59 UTC, gmarull requested changes
This PR is not really implementing a pinctrl driver but just moving `pinmux.c` to DT. Please check https://docs.zephyrproject.org/latest/guides/pinctrl/index.html and other existing implementations listed in https://github.com/zephyrproject-rtos/zephyr/issues/39740

2022-02-07 11:52 UTC, attie-argentum commented
Hi @gmarull,

I'm not sure what you mean - this PR follows directly in the footsteps of https://github.com/zephyrproject-rtos/zephyr/pull/35423/commits/7c91f46f0584f21bb14eac62610594bc1ff2eadc (#35423, which is listed in #39740).

Please could you clarify?

2022-02-07 14:44 UTC, gmarull commented
> Hi @gmarull,
> 
> I'm not sure what you mean - this PR follows directly in the footsteps of [7c91f46](https://github.com/zephyrproject-rtos/zephyr/commit/7c91f46f0584f21bb14eac62610594bc1ff2eadc) (from #35423, which is listed in #39740).
> 
> Please could you clarify?

I can't see any `drivers/pinctrl` driver here, nor any of the pinctrl APIs being used. Please check the references I've provided, this is using a custom API.

2022-02-11 12:27 UTC, attie-argentum commented
Hi @gmarull, understood... If you're pushing for a "proper" pinctrl driver right now, then I'll have to put this PR on hold for the moment. Hopefully I'll get back to it, but it may be a couple of weeks.

2022-02-12 23:42 UTC, attie commented
After discussion, this PR is on hold, and I'm going to try and spend some time on a proper pinctrl driver in the next month or so...

2022-02-12 23:59 UTC, attie-argentum commented
After discussion, this PR is on hold, and I'm going to try and spend some time on a proper pinctrl driver in the next month or so...

2022-02-20 16:19 UTC, Cooler1989 commented on dts/bindings/spi/atmel,sam0-spi.yaml
> +        be of the form p<port><pin><periph>_<inst>_<signal>.
p<port><pin>[missing '_']<periph>_<inst>_<signal>.

2022-03-13 18:01 UTC, nandojve commented
I'm closing this in favor of #43731. New devices should have their pins defined as https://github.com/zephyrproject-rtos/hal_atmel/pull/19 pinconfigs/README and will be accept after #43731.

2022-03-13 18:01 UTC, closed without merging

2022-03-13 18:13 UTC, attie-argentum commented
Thanks @nandojve !