Bluetooth: Samples: Increase main stack size for iso_receive
zephyrproject-rtos/zephyr pull request #42635
Opened 2022-02-09 11:58 UTC by Thalley

Starting the sample on an nRF53 caused a stackoverflow
on boot.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

2022-02-09 15:25 UTC, cvinayak requested changes
Use "samples: Bluetooth: ..." in commit title to differentiate between subsys/bluetooth changes vs samples/bluetooth changes.

2022-02-09 15:25 UTC, cvinayak commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
This should be architecture/board specific and repository wide change if the increase is likely for all samples/feature used on nRF53 Series

2022-02-09 16:22 UTC, Thalley commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
Removed reference to nRF53; I don't see this as being specific to that board nor the nRF family.

2022-02-09 16:34 UTC, cvinayak commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
is the iso_receive crashing on nrf52dk_nrf52832 and nrf52840dk_nrf52840, we do not want to use RAM foot print for architectures that do not use more program stack. Have you run with CONFIG_THREAD_RUNTIME_STATS=y? What are the values for stack usage?

2022-02-09 16:58 UTC, Thalley commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
I can try to run some statistics tomorrow :) The `struct thread_analyzer_info` doesn't seem to have a `max stack size used`, so will need to figure out where it maxes out.

2022-02-10 13:44 UTC, asbjornsabo approved these changes

2022-02-10 18:02 UTC, Thalley commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
It'll take a few more days to test this :)

2022-02-11 13:09 UTC, Thalley commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
For debugging purposes I had `CONFIG_LOG_FUNC_NAME_PREFIX_ERR` enabled, which is what caused the stack overflow.

2022-02-11 13:11 UTC, Thalley commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
@cvinayak The projects builds and runs with both nRF52480 and nRF5340. Should we close the PR, or does it make sense to still investigate the stack usage? It's seeming quite near the limits it seems.

2022-02-11 15:03 UTC, cvinayak commented on samples/bluetooth/iso_receive/prj.conf
> +CONFIG_MAIN_STACK_SIZE=2096
You can close the PR.

2022-02-11 16:56 UTC, Thalley commented
Closed as the prj.conf works, even though it's near capacity

2022-02-11 16:56 UTC, closed without merging