Bluetooth: df: Fix sample application build issues
zephyrproject-rtos/zephyr pull request #42692
Opened 2022-02-10 13:59 UTC by ppryga

Fix problem with building sample applications where Host is
split from Controller into separate binaries. In that situation
samples does not have access to controllers Kconfig options.
To allow memory optimization on Host site disable unwanted
features (angle of arrival or angle of departure).

CONFIG_BT_CTLR_DF_CTE_RX is enabled by default if CONFIG_BT_CLTR_DF
is enabled and there is support for DF in given SOC.
If CONFIG_BT_CTLR_DF_SCAN_CTE_RX is disabled then the CONFIG_BT_CTLR-
_PER_SCAN_CTE_NUM_MAX is not available.
It causes build errors if that particular configuration is used by
an application. It was a case for e.g. split builds of direction
finding connectionless TX sample application were periodic advertising
was enabled.

2022-02-10 14:09 UTC, Thalley approved these changes, later dismissed

2022-02-10 14:16 UTC, carlescufi approved these changes, later dismissed

2022-02-10 15:24 UTC, cvinayak requested changes
Please fix commit title's misspelled `sampels`

2022-02-10 17:57 UTC, jhedberg submitted a review, later dismissed

2022-02-11 06:42 UTC, ppryga commented
@cvinayak done

2022-02-11 08:54 UTC, cvinayak approved these changes, later dismissed

2022-02-11 12:53 UTC, ppryga commented
Added one commit to fix build issue for nRF53820.

2022-02-15 09:44 UTC, ppryga commented
@carlescufi @Thalley can you re-review it? I've added a commit to fix another thing 4 days ago (before approval rules were changed) and every approve was discarded.

2022-02-15 11:31 UTC, Thalley approved these changes

2022-02-15 11:33 UTC, cvinayak approved these changes

2022-02-15 17:17 UTC, carlescufi commented
Please add a 52820 board to the integration platforms

2022-02-15 17:18 UTC, nashif requested changes, later dismissed
you need to update the sample.yaml file to make it build in CI.

2022-02-16 07:37 UTC, ppryga commented
> Please add a 52820 board to the integration platforms

Added nRF52820 and nRF5340 to sample.yml `integration_platforms`.

2022-02-16 08:56 UTC, carlescufi approved these changes

2022-02-16 11:44 UTC, jhedberg approved these changes

2022-02-17 12:07 UTC, merged