Remove warning about path with spaces on Windows
zephyrproject-rtos/zephyr pull request #42742
Opened 2022-02-11 16:43 UTC by timonsku

Works just fine if I point it to the default install path from the Arm GCC installer which contains several spaces.
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\x.x.x\"

2022-02-14 14:02 UTC, tejlmand commented
@mbolivar-nordic you originally added this commit https://github.com/zephyrproject-rtos/zephyr/commit/0d811b9aee6a6410f73fdfb4d4072d4d16b05a52 with this sentence:
>   Like the Zephyr repository, do not install the toolchain in a directory with spaces anywhere in the path.

while it is correct you should not install Zephyr at a location containing spaces (one reason being the fact we treat space as value separator for `CONF_FILE` and similar), then I'm unsure of the reason why the toolchain cannot be installed in path containing spaces.

Do you remember why this was added ?

2022-02-14 15:06 UTC, mbolivar-nordic commented
> Do you remember why this was added ?

I don't remember anymore, sorry. If it's wrong, let's just remove it.

2022-02-14 15:32 UTC, tejlmand approved these changes, later dismissed
lgtm.

Please read the contribution guidelines:
https://docs.zephyrproject.org/latest/contribute/#commit-guidelines

2022-02-14 17:51 UTC, timonsku commented
Ah sorry, missed the guidelines. Will remember for next time.

2022-02-16 20:29 UTC, mbolivar-nordic commented
> Will remember for next time.

This needs to be fixed or the PR is not mergeable

2022-02-16 21:20 UTC, mbolivar-nordic commented
You need to:

1. Fix your signed-off-by line to use a legal name and a real email (https://docs.zephyrproject.org/latest/contribute/index.html#dco-sign-off-methods)
2. please use `doc:` instead of `Docs:`

2022-02-18 23:59 UTC, mbolivar-nordic approved these changes

2022-02-19 00:00 UTC, mbolivar-nordic requested changes
My mistake, meant to -1 not +1

2022-02-22 09:02 UTC, tejlmand approved these changes, later dismissed
lgtm

2022-03-21 17:33 UTC, carlescufi commented
@timonsku could you please fix your commit message as per @mbolivar-nordic's instrucitons?

2022-03-22 13:21 UTC, timonsku commented
Sorry for the delay! Had some busy weeks.
Thank for bearing with me. I squashed and amended the commits as instructed.
I hope that now follows the guidelines correctly.

2022-03-22 21:24 UTC, mbolivar-nordic commented
@timonsku no worries! You are almost there. Just please change this:

```
Signed-off-by: Timon Skerutsch timon@diodes-delight.com
```

To this:

```
Signed-off-by: Timon Skerutsch <timon@diodes-delight.com>
```

and all will be well.

2022-03-23 00:17 UTC, timonsku commented
ah yes, fixed!

2022-03-25 23:06 UTC, mbolivar-nordic approved these changes, later dismissed

2022-03-26 03:50 UTC, stephanosio requested changes
```
1: T6 Title has leading whitespace: " doc: Add a notice that you are free to choose compiler path"
3: UC4 Line exceeds max length (115>75): "Works just fine if I point it to the default install path from the Arm GCC installer which contains several spaces."
6: UC4 Line exceeds max length (1[27](https://github.com/zephyrproject-rtos/zephyr/runs/5699365541?check_suite_focus=true#step:9:27)>75): "The previous notice about not using spaces made sense to have this very specific path but this might confuse people who install"
7: UC4 Line exceeds max length (127>75): "ARM GCC with the provided installer which puts it into a path under C:\Program FIles, to avoid people moving their installation"
8: UC4 Line exceeds max length (117>75): "and possibly breaking a different setup I thinks its good to make that clear that this is not a hard coded assumption"
```

2022-03-27 11:25 UTC, timonsku commented
fixed

2022-03-29 20:08 UTC, mbolivar-nordic approved these changes, later dismissed

2022-03-29 23:48 UTC, stephanosio commented on doc/getting_started/toolchain_3rd_party_x_compilers.rst
> +      path used by the ARM GCC installer, you will need to adjust the path
```suggestion
      path used by the ARM GCC installer, in which case you will need to adjust the path
```

2022-03-30 00:56 UTC, timonsku commented on doc/getting_started/toolchain_3rd_party_x_compilers.rst
> +      path used by the ARM GCC installer, you will need to adjust the path
sure, lgtm

2022-03-30 01:44 UTC, mbolivar-nordic approved these changes, later dismissed

2022-03-30 04:22 UTC, stephanosio approved these changes, later dismissed

2022-03-30 04:26 UTC, stephanosio reviewed
It looks like you have added a new commit while addressing the review comment.

Please squash that commit into the first one; also, there is no need to add `Co-authored-by: Stephanos ...` for minor review comments like this :)

2022-05-02 12:25 UTC, timonsku commented
oh sorry I thought I had already fixed this. Commit is squashed.

2022-05-02 12:44 UTC, stephanosio commented
> oh sorry I thought I had already fixed this. Commit is squashed.

@timonsku Thanks. It looks like there is a merge conflict with the latest main. Could you rebase/resolve conflicts and push again?

2022-05-02 13:23 UTC, timonsku commented
Rebased to latest upstream main.
I just noticed it auto added the co-authored to the commit message, I hope thats ok?

2022-05-02 13:25 UTC, stephanosio approved these changes

2022-05-02 13:26 UTC, stephanosio commented
> I just noticed it auto added the co-authored to the commit message, I hope thats ok?

yea, no worries :)

2022-05-13 17:48 UTC, mbolivar-nordic approved these changes

2022-05-13 17:48 UTC, merged