allow for memset/memcpy alternatives during early boot
zephyrproject-rtos/zephyr pull request #42751
Opened 2022-02-11 21:49 UTC by npitre

Zeroing the BSS and copying data to RAM with regular memset/memcpy may
cause problems when those functions are assuming a fully initialized
system for their optimizations to work e.g. some instructions require
an active MMU, but turning the MMU on needs the .bss section to be
cleared first, etc.

This is a more scalable and future-proof solution to the issue described
in #31321.

2022-02-11 22:05 UTC, dcpleung approved these changes

2022-02-11 22:06 UTC, dcpleung commented
Out of curiosity... does the issue occur with the minimal libc's memset? That code doesn't seem to require BSS.

2022-02-11 22:39 UTC, npitre commented
> Out of curiosity... does the issue occur with the minimal libc's memset? That code doesn't seem to require BSS.

It's the newlib one. It uses the FP unit to go faster, but that
needs an addressing mode that isn't available without the MMU enabled.

The commit log for commit c5b898743a20 is worth reading.

2022-02-11 23:00 UTC, andyross approved these changes
Seems sane.  Note for purposes of comparison, there's a similar trick that needs to be played in lib/os/winstream.c.  That code needs to zero a buffer, but as deployed it's happening at a moment where the main Zephyr image (including almost-but-not-quite-all symbols) hasn't yet been copied into place by the bootstrap code.

That isn't well-captured by the __boot_func abstraction exploited here, so I don't know if there's an obvious way to unify them if you want to link these as symbols.   But it's worth keeping in mind I guess.

Another option would be to make these two into ALWAYS_INLINE functions in headers, given how simple they are.  That could absolutely be used in both places.

2022-02-12 08:44 UTC, carlocaione approved these changes

2022-02-14 12:58 UTC, carlocaione requested changes
Hey @npitre I think you also want to modify the `scripts/gen_relocate_app.py` content.

2022-02-14 14:29 UTC, carlocaione approved these changes

2022-02-14 14:42 UTC, stephanosio approved these changes

2022-02-14 15:14 UTC, peter-mitsis approved these changes

2022-02-14 15:20 UTC, npitre commented
> Hey @npitre I think you also want to modify the `scripts/gen_relocate_app.py` content.

Good catch, done.

2022-02-14 16:31 UTC, MaureenHelm approved these changes

2022-02-14 22:04 UTC, tejlmand approved these changes

2022-02-15 01:57 UTC, povergoing approved these changes

2022-02-22 02:00 UTC, merged