subsys/ztest: Make 1cpu tests run on CPU 0 specifically
zephyrproject-rtos/zephyr pull request #42803
Opened 2022-02-14 20:13 UTC by andyross

Some hardware has "interesting" configuration like asymmetric default
interrupt masking (the intel_adsp devices in particular, but x86's
IO-APIC driver has tripped over this in the past too) that needs
special treatment if you want to run something on "core 1"
specifically, and 1cpu test cases pretty much by definition are going
to have been written without SMP details in mind.  Switch the logic
around a tiny bit such that these test cases always run on CPU ID zero
explicitly.

Actually in practice this was ALMOST guaranteed to be true already,
because test setup and happens serially, having been started on the
main thread, which starts on CPU 0 by definition.  Then the test
teardown aborts all the spawned threads that might have been running
on CPUs 1+, so those reach idle, and the next test case starts
syncronously on the same thread (and thus CPU) where it started.  But
nonetheless that wasn't actually enforced, and we've found at least
one simulation environment where timing conspires to break things.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

2022-02-14 20:14 UTC, andyross commented
Adding a reasonably obvious feature to ztest to help chase a great hypothesis from @enjiamai

2022-02-15 00:48 UTC, enjiamai commented
Hi @andyross , Sorry for a wrong hypothesis and misleading you. I will do more analysis on this.

2022-02-15 17:30 UTC, dcpleung approved these changes
Wonder if we should just enable CPU mask on ztest with SMP.

2022-02-15 18:07 UTC, andyross commented
> Wonder if we should just enable CPU mask on ztest with SMP.

That would indeed be easier, but then you can't get coverage of !CPU_MASK though, thus making it an essentially mandatory feature.

Really this isn't that complicated.  Or... it's not any more complicated than the original hack anyway.

2022-02-17 01:26 UTC, ceolin approved these changes

2022-02-18 06:27 UTC, ceolin commented on subsys/testsuite/ztest/src/ztest.c
> +#if defined(SMP) && (CONFIG_MP_NUM_CPUS > 1)
s/SMP/CONFIG_SMP/

2022-02-18 06:27 UTC, ceolin commented on subsys/testsuite/ztest/src/ztest.c
> +#if defined(SMP) && (CONFIG_MP_NUM_CPUS > 1)
s/SMP/CONFIG_SMP/

2022-02-18 06:28 UTC, ceolin commented on subsys/testsuite/ztest/src/ztest.c
> +#if defined(SMP) && (CONFIG_MP_NUM_CPUS > 1)
s/SMP/CONFIG_SMP/

2022-02-18 06:29 UTC, ceolin requested changes
The build condition is wrong and the code is never executed, so cpus are not hold.

I've tested with the change and it works great !

2022-02-18 15:17 UTC, andyross commented
Whoops, yeah.  That snuck in at the end, I changed the #if logic so the threads wouldn't be defined if not needed and clearly that snuck in.

2022-02-18 18:43 UTC, ceolin approved these changes

2022-02-21 13:24 UTC, enjiamai requested changes
Excuse me, @andyross , I would like to block this first, I made a full testing on it, the result is better but not address all the problem.  Let me provide you more details. Thanks!

2022-03-07 19:38 UTC, ceolin commented
Is there any reason to not merget it ?

2022-03-08 00:41 UTC, enjiamai commented
Hi @ceolin @andyross , I think we don't need this because the original one works well now and it is a real SMP scenario. But this might be possibly needed in the future if we meet the scenario that "main core" cannot use for spinning around. How do you think adding a CONFIG_MAIN_CPU_NO_SPIN to enable/disable this feature is a good idea for this?

2022-03-08 05:20 UTC, andyross commented
This no longer fixes anything.  It's somewhat reasonable protection against future systems with the kind of CPU asymmetry we were worried about, and matches the broad intent of the API (to emulate a "one cpu" system as closely as possible for the benefit of tests that aren't MP-aware).  I'm happy if this goes in or gets dropped, no preference.  Though it looks like it does need a rebase.

2022-03-08 06:47 UTC, ceolin commented
> This no longer fixes anything.  It's somewhat reasonable protection against future systems with the kind of CPU asymmetry we were worried about, and matches the broad intent of the API (to emulate a "one cpu" system as closely as possible for the benefit of tests that aren't MP-aware).  I'm happy if this goes in or gets dropped, no preference.  Though it looks like it does need a rebase. 

Exactly ... +1 to merge it.

2022-03-08 08:03 UTC, enjiamai approved these changes

2022-03-08 15:38 UTC, andyross commented
Huh... so I pushed a new tree to https://github.com/andyross/zephyr/commits/1cpu0 to fix the rebase collision, but it's not being picked up here.  Is this a github glitch or is there something I have to do to kick it?

2022-03-08 15:59 UTC, nashif commented
needs rebase

2022-03-08 16:53 UTC, andyross commented
Still stuck, despite source branch being updated.  Try closing/reopening...

2022-03-08 16:53 UTC, closed without merging

2022-03-08 16:54 UTC, andyross commented
And... now it won't let me reopen because "The 1cpu0 branch was force-pushed or recreated".  Well, yeah.  Why is that a problem?

Did we break something with the github settings?

2022-03-08 17:01 UTC, andyross commented
Yeah, this is borked.  Opened a new PR at #43547