Bluetooth: controller: llcp: update CMake version for unittesting
zephyrproject-rtos/zephyr pull request #42930
Opened 2022-02-17 13:28 UTC by kruithofa

The minimum CMake version required is 2.20.0, but the unittests
for the LLCP controller still referred to 3.13.1 as the minimum

Signed-off-by: Andries Kruithof <Andries.Kruithof@nordicsemi.no>

2022-02-17 13:41 UTC, ppryga approved these changes, later dismissed

2022-02-17 15:16 UTC, Thalley requested changes
While it is easy to figure out what you mean, please fix the version number typo in the commit message and PR description :) (3.20 instead of 2.20)

2022-02-18 11:10 UTC, Thalley approved these changes

2022-02-21 07:14 UTC, thoh-ot approved these changes

2022-02-21 11:35 UTC, tejlmand approved these changes

2022-02-22 18:09 UTC, merged