cmake: Add xcc-clang toolchain
zephyrproject-rtos/zephyr pull request #42971
Opened 2022-02-18 21:12 UTC by edersondisouza

Instead of setting XCC_USE_CLANG=1, this patch adds xcc-clang toolchain
that is basically xcc using the clang compiler.

Initially, the new toolchain simply includes files from current xcc
toolchain and (re)sets some variables. This should be a more scalable
approach to diverge the toolchains in the future than placing
"if($ENV{XCC_USE_CLANG})" at several places.

It should also help to filter tests that run (or not) exclusively with
the clang variant of XCC on twister.

The XCC_USE_CLANG flag is documented as deprecated, and a message is
emitted during build if still in use. Its new behaviour is to instruct
Zephyr to use `xcc-clang` toolchain.

2022-02-21 11:00 UTC, tejlmand requested changes
I think it makes a lot of sense to be able to identify the `xcc-clang` as a dedicated toolchain, caused that is what it is basically.

But we shouldn't have two ways of identifying the same toolchain, so when introducing:
```
export ZEPHYR_TOOLCHAIN_VARIANT=xcc-clang
```

then please deprecate the use of:
```
export XCC_USE_CLANG=1
```

we can keep `XCC_USE_CLANG` around for two releases before removing.

And when introducing `xcc-clang`, then a corresponding compiler should be defined to allow cleaning this up: https://github.com/zephyrproject-rtos/zephyr/blob/d353e551607926612ff258dadbc13d028d58b54e/cmake/compiler/xcc/compiler_flags.cmake#L3

as there will no longer be a need for this code.

Of course all common code can still be placed so both `xcc` and `xcc-clang` can use it.
(`xcc-clang` version re-using `xcc` gcc version).
Ideally COMPILER should be just `clang` as that's the name of the compiler, but as that is already in use by vanilla clang and `xcc-clang` seems to require some extra tweaks, then I believe using `xcc-clang` is fine (and better than `xcc` cause `xcc` seems to be the gcc based compiler).

2022-02-23 00:22 UTC, edersondisouza commented
v2: Instead of being a simple shortcut, add `xcc-clang` as a proper toolchain - albeit still reusing most of the files from xcc one.
Also, document new flag and that old behaviour is deprecated.

2022-02-23 18:55 UTC, dcpleung approved these changes

2022-02-25 16:10 UTC, tejlmand approved these changes
Very nice :+1: 

Thanks a lot for cleaning up this.

2022-02-25 16:17 UTC, merged