cmake: zephyr-package: add message mode
zephyrproject-rtos/zephyr pull request #43009
Opened 2022-02-21 07:26 UTC by JordanYates

Add a <mode> value to the message printed when including
`boilerplate.cmake`. Without this mode it defaults to `NOTICE`, which
outputs to `stderr` and is not needed in this instance. `STATUS` is
sufficient.

https://cmake.org/cmake/help/latest/command/message.html

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

2022-02-21 10:20 UTC, tejlmand requested changes
please see discussion here, and why this specific message is of higher importance.
https://github.com/zephyrproject-rtos/zephyr/pull/31365#issuecomment-769674895

2022-02-21 10:35 UTC, JordanYates commented
> please see discussion here, and why this specific message is of higher importance. [#31365 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/31365#issuecomment-769674895)

Thanks for the reasoning, given this has appeared twice independently, I have swapped this PR to be explicit with the type and why it is that way.

2022-02-21 15:34 UTC, tejlmand submitted a review, later dismissed
LGTM.

But I agree, would be nice if CMake allowed users to output `NOTICE` to stdout instead of stderr.

2022-03-03 11:00 UTC, de-nordic approved these changes, later dismissed
Looks OK.

2022-03-07 09:48 UTC, carlescufi submitted a review, later dismissed

2022-03-07 09:49 UTC, carlescufi commented
@JordanYates please rebase

2022-03-07 10:55 UTC, tejlmand approved these changes
lgtm

2022-03-23 12:24 UTC, carlescufi approved these changes

2022-03-23 12:24 UTC, merged