tests: Fix codec specific capabilities
zephyrproject-rtos/zephyr pull request #43074
Opened 2022-02-22 15:48 UTC by MariuszSkamra

This fixes exposing capabilities instead of configuration in PACS characteristic.

2022-02-22 16:39 UTC, Thalley requested changes
Any plans on updating the remaining uses of the preset macros used in e.g. the shell? 

Does broadcast also need this change?

2022-02-22 16:39 UTC, Thalley commented on samples/bluetooth/unicast_audio_server/src/main.c
The commit message is off here, as this is a sample and not a test :)

2022-02-23 08:06 UTC, MariuszSkamra commented
> Any plans on updating the remaining uses of the preset macros used in e.g. the shell?
> 
> Does broadcast also need this change?

Looks like the shell implementation is correct

2022-02-23 08:16 UTC, asbjornsabo reviewed
I find the commit messages unclear:
"This fixes exposing capabilities instead of configuration in PACS characteristic."

Does this mean that the code used to expose capabilities, not configuration, and these commits change that?  
Or does it mean the opposite, the code used to expose configuration, but has been changed to expose capabilities?

2022-02-23 12:19 UTC, Thalley approved these changes

2022-02-23 12:19 UTC, Thalley commented on samples/bluetooth/unicast_audio_server/src/main.c
> +#define CHANNEL_COUNT_1 BIT(0)
Ideally we'll provide helper functions to help format things like this, but this is fine for now

2022-02-23 13:21 UTC, asbjornsabo approved these changes

2022-02-25 13:50 UTC, jhedberg approved these changes

2022-02-25 18:05 UTC, merged