Issue #43131 - LPCXPresso55S69-evk dtsi file incorrect
zephyrproject-rtos/zephyr pull request #43134
Opened 2022-02-24 02:18 UTC by jasonNXP

Updated the active state for the LPCXpresso55S69 board LEDs to reflect their proper active state.

2022-02-24 21:07 UTC, dleach02 commented
@jasonNXP, the commits need to be signed as part of the DCO

https://docs.zephyrproject.org/latest/contribute/index.html

2022-02-25 20:01 UTC, mmahadevan108 approved these changes, later dismissed

2022-03-01 15:11 UTC, danieldegrasse approved these changes, later dismissed

2022-03-01 21:00 UTC, MaureenHelm requested changes
The commit message doesn't quite follow the [Commit Guidelines](https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines). Specifically, "The subject line must include a prefix that identifies the subsystem being changed, followed by a colon, and a short title". We don't typically put the GitHub Issue number in the subject.

Can you update it to something like: `boards: arm: Fix led active state on the lpcxpresso55s69`

Nice to see you're sending patches upstream. :)

2022-03-01 22:18 UTC, dleach02 submitted a review, later dismissed

2022-03-01 22:19 UTC, danieldegrasse approved these changes, later dismissed

2022-03-02 03:34 UTC, dleach02 approved these changes

2022-03-02 15:19 UTC, MaureenHelm approved these changes

2022-03-02 15:20 UTC, merged