stm32: clock_control: Add test suite for stm32
zephyrproject-rtos/zephyr pull request #43157
Opened 2022-02-24 14:16 UTC by FRASTM

Similarly to what was done for U5 in https://github.com/zephyrproject-rtos/zephyr/pull/40731
and H7 in https://github.com/zephyrproject-rtos/zephyr/pull/41391
add some tests dedicated to other stm32 clock_control driver configuration

- stm32g0 target board : nucleo_stm32g071rb : config PLL 64MHz from HSI 16 MHz, PLL 64 MHz from HSE 8MHz, 

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-02-25 10:44 UTC, FRASTM commented
$ west build -p auto -b nucleo_g071rb -- -DDTC_OVERLAY_FILE="boards/clear_clocks_f0_g0.overlay" -DDTC_OVERLAY_FILE="boards/pll_64_hsi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/

2022-02-25 14:29 UTC, FRASTM commented
adding stm32g474re target
Keeping the the ahb-prescaler, apb1-prescaler, apb2-prescaler as they are set by each board DTS (not cleared by the clear_clocks.overlay as hey are not required for the test case).

2022-02-28 16:14 UTC, FRASTM commented
adding stm32l073rz and nucleo_l152re targets
HSE is bypassed, the max PLL freq is 32MHz, the MSI range is possible from 1 to 6

2022-03-01 11:12 UTC, FRASTM commented
adding target nucleo_wl55jc with:
`$ west build -p auto -b nucleo_wl55jc -- -DDTC_OVERLAY_FILE="boards/wl_clear_clocks.overlay;boards/pll_48_hsi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/`

2022-03-01 13:16 UTC, erwango commented on tests/drivers/clock_control/stm32_clock_configuration/stm32_common/testcase.yaml
> +    platform_exclude: nucleo_h723zg b_u585i_iot02a
This should be updated/removed

2022-03-01 13:17 UTC, erwango commented on tests/drivers/clock_control/stm32_clock_configuration/stm32_common/src/test_stm32_clock_configuration.c
> +LOG_MODULE_REGISTER(test);
Please put this out of the #include section

2022-03-01 13:20 UTC, erwango commented on tests/drivers/clock_control/stm32_clock_configuration/stm32_common/boards/msi_range11.overlay
> + * Copyright (c) 2022 STMIcroelectronics
```suggestion
 * Copyright (c) 2022 STMicroelectronics
```
Apply everywhere

2022-03-01 14:29 UTC, FRASTM commented
adding target nucleo_wb55rg with:
$ west build -p auto -b nucleo_wb55rg -- -DDTC_OVERLAY_FILE="boards/wb_clear_clocks.overlay;boards/pll_48_hsi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/

2022-03-02 11:04 UTC, FRASTM commented
adding target nucleo_l4xxx with:
$ west build -p auto -b nucleo_l476rg -- -DDTC_OVERLAY_FILE="boards/clear_clocks.overlay;boards/clear_clocks_msi.overlay;boards/pll_64_hsi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/

2022-03-02 12:14 UTC, FRASTM commented
rebase on d2a56c5047f9e7f10b1b0df53d57917d3980bf72

2022-03-02 16:20 UTC, FRASTM commented
adding stm32f0/f1/f2/f3/f4/f7 targets:

`$ west build -p auto -b nucleo_f207zg -- -DDTC_OVERLAY_FILE="boards/clear_f2_f4_f7_clocks.overlay;boards/f2_f4_f7_pll_64_hse_8.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/`

`$ west build -p auto -b nucleo_f334r8 -- -DDTC_OVERLAY_FILE="boards/clear_f0_f1_f3_clocks.overlay;boards/f0__f3_pll_32_hse_8.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/`

`$ west build -p auto -b nucleo_f429zi -- -DDTC_OVERLAY_FILE="boards/clear_f2_f4_f7_clocks.overlay;boards/f2_f4_f7_pll_64_hse_8.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/`

`$ west build -p auto -b nucleo_f767zi -- -DDTC_OVERLAY_FILE="boards/clear_f2_f4_f7_clocks.overlay;boards/f2_f4_f7_pll_64_hsi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/`

2022-03-03 09:23 UTC, FRASTM commented
split hse 8 configuration in 2:  with and without by-pass to run on the nucleo_wb55rg

2022-03-16 14:35 UTC, erwango approved these changes

2022-03-22 13:14 UTC, erwango requested changes

2022-03-22 13:14 UTC, erwango commented on tests/drivers/clock_control/stm32_clock_configuration/stm32_common/testcase.yaml
> +    extra_args: DTC_OVERLAY_FILE="boards/clear_clocks.overlay;;boards/clear_clocks_msi.overlay;boards/pll_64_hsi_16.overlay"
```suggestion
    extra_args: DTC_OVERLAY_FILE="boards/clear_clocks.overlay;boards/clear_clocks_msi.overlay;boards/pll_64_hsi_16.overlay"
```

2022-03-22 15:00 UTC, erwango commented
@FRASTM The following test is failed on my side, can you have a check ?

`nucleo_wb55rg/tests/drivers/clock_control/stm32_clock_configuration/stm32_common/drivers.stm32_clock_configuration.common.sysclksrc_wb_48_msi`

2022-03-23 07:32 UTC, erwango approved these changes, later dismissed

2022-03-23 07:33 UTC, erwango commented on drivers/clock_control/clock_stm32_ll_common.c
> -/* Calculate MSI freq for the given range(at RUN range, not after standby) */
This commit was already merged in a different version. Let's remove it

2022-03-23 10:23 UTC, ABOSTM approved these changes

2022-03-23 12:18 UTC, erwango approved these changes

2022-03-23 14:25 UTC, MaureenHelm approved these changes

2022-03-23 14:25 UTC, merged