[RFC][WIP] Add RF PHY API
zephyrproject-rtos/zephyr pull request #43201
Opened 2022-02-25 10:04 UTC by leonardp

## Introduction

This is a proposal for a generic API for the pysical layer of RF frontends.

It is a rough sketch of the idea and I am not sure if this approach is even feasible.

### Problem description

Currently Zephyr does not have a device driver abstraction for interacting with an RF modems' pyhsical layer.

One examples of an [IEEE 802.15.4](https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/ieee802154) driver where this leads to problems is
the CC1200 which supports frequencies and modulation techniques for applications not covered by the IEEE 802.15.4 standard.

### Proposed change

Introduce an API for device drivers targeting the pyhsical layer of RF frontends.

This could provide a straight-forward path for e.g.

* [IEEE 802.15.4 PHYs](https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/ieee802154)
* [LoRa PHYs](https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/lora)
* [NFC/RFID](https://github.com/zephyrproject-rtos/zephyr/issues/5703)
* RF protocols outside of IEEE 802.15.4 and LoRa-MAC (wM-Bus, NB-Fi, propietary, ...)
* Real-time locating systems (RTLS)
* Custom analog RF frontends

without tying the driver into any protocol/subsystem layers.

## Detailed (draft) RFC

```C
/**
 * NOTE: different way to handle packets? e.g. network buffers?
 */
union rf_packet {
	uint8_t buffer[CONFIG_RF_MAX_PACKET_SIZE];
	struct {
		uint8_t length;
		uint8_t payload[CONFIG_RF_MAX_PACKET_SIZE - 1];
	} __packed;
};

typedef uint64_t rf_freq_t;

typedef uint16_t rf_chan_t;

typedef uint32_t rf_baud_t;

typedef int16_t rf_power_t;

enum rf_mod_format {
	RF_MODULATION_OOK = 0,
	RF_MODULATION_ASK,
	RF_MODULATION_2FSK,
	RF_MODULATION_4FSK,
	RF_MODULATION_GFSK,
	RF_MODULATION_AFSK,
	RF_MODULATION_2PSK,
	RF_MODULATION_MSK,
	RF_MODULATION_GMSK,
	RF_MODULATION_DSSS,
};

enum rf_op_mode {
	RF_MODE_CALIBRATE = 0,
	RF_MODE_POWER_OFF,
	RF_MODE_SLEEP,
	RF_MODE_IDLE,
	RF_MODE_RX_WAKE_ON_EVENT,
	RF_MODE_RX_WAKE_PERIODIC,
	RF_MODE_RX,
	RF_MODE_TX,
};

/**
 * -> see: rf_event_cb_t
 * -> using k_event object might be more sensible
 * -> define event bits
 */
enum rf_event {
	RF_EVENT_STUCK = 0,
	RF_EVENT_RECV_READY,
	RF_EVENT_SEND_READY,
	RF_EVENT_RECV_DONE,
	RF_EVENT_SEND_DONE,
	RF_EVENT_CHANNEL_CLEAR,
	RF_EVENT_WAKEUP,
};

enum rf_hw_filter {
	RF_HW_FILTER_NONE = 0,
	RF_HW_FILTER_CRC8,
	RF_HW_FILTER_CRC16,
	RF_HW_FILTER_ADDR,
	RF_HW_FILTER_LENGTH,
};

/**
 * making every entry in this enum a seperate API  function
 * will avoid the use of void pointers
 */
enum rf_device_arg {
	RF_DEVICE_FREQUENCY = 0,
	RF_DEVICE_CHANNEL,
	RF_DEVICE_MODULATION_FORMAT,
	RF_DEVICE_BAUDRATE,
	RF_DEVICE_OUTPUT_POWER,
	RF_DEVICE_OPERATING_MODE,
	RF_DEVICE_SET_EVENT_CB,
	RF_DEVICE_HW_FILTER,
	RF_DEVICE_SETTINGS,
	RF_DEVICE_CALIBRATION_SETTINGS,
	RF_DEVICE_POWER_TABLE,
};

/**
 * -> this will block the phy driver
 * -> using k_event object might be more sensible
 */
typedef void (*rf_event_cb_t)(const struct device *dev,
				enum rf_event event,
				void *event_params);

/**
 * see `enum rf_device_arg`
 */
typedef int (*rf_device_set_t)(const struct device *dev,
				    enum rf_device_arg cfg,
				    void *val);

typedef int (*rf_device_get_t)(const struct device *dev,
				    enum rf_device_arg cfg,
				    void *val);

typedef int (*rf_device_send_t)(const struct device *dev,
				     union rf_packet *pkt);

typedef int (*rf_device_recv_t)(const struct device *dev,
				     union rf_packet *pkt);

__subsystem struct rf_driver_api {
	rf_device_set_t device_set;
	rf_device_get_t device_get;
	rf_device_send_t send;
	rf_device_recv_t recv;
};
```

### Dependencies

Some already existing IEEE 802.15.4 and LoRa-MAC drivers MAY be adapted to use this API.

### Concerns and Unresolved Questions

There are a lot of open questions. To list a few:

* Instead of having `rf_device_set/rf_device_get` that accepts `enum rf_device_arg` and a void
pointer. Make a function for everything listed in the enum.

* Support for multiple channels (e.g. MIMO)?

* Use `net_buf` instead of `struct rf_packet`?!

* Usage of `k_event` instead of callbacks. This way one would end up with two rx threads
(one for the rf device and one in the upper layers) a dependency on `CONFIG_EVENTS`.

* Is there another/clean way to get the rf device from other drivers (see: )?

* There are devices in this category have a "direct" mode (might be a usecase for RTIO API proposed in https://github.com/zephyrproject-rtos/zephyr/pull/17434).

## Alternatives

The alternative is to deal with some code duplication for the PHY layer of multi-protocol rf frontends.

`CONFIG_IEEE802154_RAW_MODE`/`CONFIG_NET_RAW_MODE` are available and it might be sufficient to resort to these?

2022-03-01 18:04 UTC, rettichschnidi commented
If this gets any positive feedback from the Zephyr community I intend to contribute a implementation for the SiLabs Si4467. Using it already for a non-802.15.4 protocol and a RF PHY API the missing part to make upstreaming this driver beneficial from my POV.

2022-03-09 07:47 UTC, hubertmis commented
It seems to me the proposed API is not limited to physical layer of RF front ends, but it defines some link layer (or MAC) features:
* CRC
* periodic receiver
* frame filtering

I understand some radios support these features in HW, but other support more features like ACK receiving or sending, retransmissions, crypto, etc. I think we should follow one of two possible approaches:

1. Define generic PHY RF API, without any link layer features (remove CRC, periodic receiver, filtering), but with more complete list of PHY features like preamble length, preamble content, PHY header configuration, detecting energy level, detecting carrier
2. Continue already existing APIs and implement drivers for radios for specific MAC layer protocols like:
* https://github.com/zephyrproject-rtos/zephyr/blob/main/include/net/ieee802154.h
* https://github.com/zephyrproject-rtos/zephyr/blob/main/include/net/wifi.h
* https://github.com/zephyrproject-rtos/zephyr/tree/main/subsys/bluetooth/controller/ll_sw

2022-03-15 17:38 UTC, leonardp commented
@rettichschnidi, @hubertmis 

Thanks for your feedback!
This API does indeed support features that go above/beyond the physical layer. "RF frontend API" would probably
be a more accurate title.

> 2. Continue already existing APIs and implement drivers for radios for specific MAC layer protocols like:

I can see these APIs making perfect sense for hardware that only supports those protocols but the main driver for me
was multi-protocol RF devices.
I understand that having an API for *all* RF capable devices is probably impossible/impractical. On the other hand
having a separate driver for every protocol a multi-protocol device supports is also something that should be avoided IMHO.

> 1. Define generic PHY RF API, without any link layer features (remove CRC, periodic receiver, filtering), but with more complete list of PHY features like preamble length, preamble content, PHY header configuration, detecting energy level, detecting carrier

I like this approach better than `2.` but how/where would you handle the the link-layer/device-specific hardware features?
The choices I can think of are Kconfig, devicetree and public APIs.

2022-03-15 17:47 UTC, hubertmis commented
> On the other hand having a separate driver for every protocol a multi-protocol device supports is also something that should be avoided IMHO.

We are doing it with success for Nordic devices. I don't see any issues with this approach. If you would like to reuse some common library for both protocols you could place it in your vendor-specific hal repository.

> how/where would you handle the the link-layer/device-specific hardware features?

I would recommend to specify only generic PHY features in the standard device driver API, and create device-specific API extensions for device-specific hardware features.

2022-06-02 08:22 UTC, tbursztyka requested changes
Would a good addition. But this means also aligning with other radio tech in order to get a true general RF API.

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +typedef int16_t rf_power_t;
this will need better description. is it in dBm or?

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +	/* Idle state of the rf device with shortest possible transistion time to RX/TX */
I am wondering if these 2 modes above should integrate with device PM directly.

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +enum rf_device_arg {
s/rb_device_arg/rf_config

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +	rf_device_set_t device_set;
on all API function: 
s/rf_device_/rf_

This is just pretty obvious that if you access a struct dev through such API, I it will mean an RF device.

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +//__syscall int rf_device_set(const struct device *rf,
why is this commented out atm?

2022-06-02 08:22 UTC, tbursztyka commented on include/drivers/rf.h
> +	rf_device_send_t send;
Since it's dealing with radio, I'd prefer tx instead of send and rx instead of recv.

2022-06-02 08:22 UTC, tbursztyka commented on drivers/rf/cc1101/cc1101.h
> +		uint8_t FIFO_BYTES_AVAILABLE: 4;
Use small letters for attribute names. 

Capital letters mostly go only to macros and enums.

Apply that everywhere.

2022-06-02 08:22 UTC, tbursztyka commented on drivers/rf/cc1101/cc1101.c
> +}
Looks like you could reduce the code size above by having one generic function for accessing SPI and having helpers for just reg access on top. See cc1200 or cc2520 driver code for instance

2022-06-02 08:22 UTC, tbursztyka commented on drivers/rf/cc1101/cc1101.c
> +	} else {
superfluous else (compiler would probably notify about it)

2022-06-02 08:22 UTC, tbursztyka commented on drivers/rf/cc1101/cc1101.c
> +	if (ret) {
seems like a useless if block at the moment

2022-06-02 08:22 UTC, tbursztyka commented on drivers/ieee802154/ieee802154_cc1101.c
> +	int ret;
ret seems superfluous here, just return directly from the RF API call

same in various places below

2022-06-09 08:54 UTC, leonardp commented
@tbursztyka thank you for the reviewing this! I am a bit tied up at the moment but I will incorporate your suggested 
changes as soon as I get back to this.

@rettichschnidi
> Is the conclusion that this should not be an API, but rather an external HAL module?
>
> If so, would this also be the recommended way to go for HALs (i.e. for the SiLabs Si4467) written by 3rd-parties (i.e. Gardena) specifically for Zephyr?

I took a quick look at the driver for the SI4467. In that case, if I understand correctly, the options as of *right now* that could be upstreamed into Zephyr are:

1. a device driver using already existing APIs (e.g. ieee802.15.4)
2. a driver *and* a protocol (e.g. W-MBus) for the device/protocol you want
3. a HAL for the EZRadio®/EZRadioPRO® family

I still think it is fine to have an API for the PHY layer only. It will have some similarity to the [modem](https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/modem) driver API while having the required functions for RF devices.

2022-06-12 16:26 UTC, hubertmis commented
> I still think it is fine to have an API for the PHY layer only. It will have some similarity to the [modem](https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/modem) driver API while having the required functions for RF devices.

I cannot find a device driver API header file in Zephyr for modem (similar to [API header for 802.15.4](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/net/ieee802154_radio.h) ). Is there one defined or all modem drivers have different APIs?

2022-06-14 19:47 UTC, leonardp commented
> I cannot find a device driver API header file in Zephyr for modem (similar to [API header for 802.15.4](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/net/ieee802154_radio.h) ). Is there one defined or all modem drivers have different APIs?

You are right, all modem drivers do have different APIs. Thanks for rectifying, I am totally out of the loop at the moment.

The API will have the features as you described earlier:

> Define generic PHY RF API, without any link layer features (remove CRC, periodic receiver, filtering), but with more complete list of PHY features like preamble length, preamble content, PHY header configuration, detecting energy level, detecting carrier

2022-08-28 00:32 UTC, closed without merging