Bluetooth: controller: Fix Controller to Host flow control leak
zephyrproject-rtos/zephyr pull request #4329
Opened 2017-10-14 12:03 UTC by carlescufi

When a connection is disconnected with outstanding unacked packets, the
Host has no way to signal or acknowledge their processing to the
Controller, since it is illegal to send a Host Number of Completed
Packets command when the connection is not up. Instead, consider the
outstanding packets as acked in order not to affect the correct flow
control.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2017-10-14 18:55 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +	memset(hci_hbuf_pend, 0x00, sizeof(hci_hbuf_pend));
I think our general style convention is to use just 0 (instead of 0x00) when setting memory to zero.

2017-10-15 04:08 UTC, cvinayak requested changes

2017-10-15 04:08 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +		if((h >= ARRAY_SIZE(hci_hbuf_pend)) ||
Missing blank line after declaration.

2017-10-15 04:08 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +			hci_hbuf_pend[handle]++;
Please have a TODO or NOTE, to mention that connection handles could be random from controller (not in the current ll_sw controller implementation though), and a lookup table implementation is needed.

2017-10-17 09:18 UTC, carlescufi commented
@cvinayak @jhedberg please re-review

2017-10-17 10:50 UTC, jhedberg approved these changes

2017-10-17 10:56 UTC, cvinayak approved these changes

2017-10-17 11:10 UTC, merged