boards: Add Proteus-II board file
zephyrproject-rtos/zephyr pull request #43320
Opened 2022-03-01 12:40 UTC by mah-eiSmart

Add a new board file of the Proteus-II radio module

Signed-off-by: Matthias Hauser <Matthias.Hauser@we-online.de>

2022-03-07 08:46 UTC, mah-eiSmart commented
Hey @anangl,

I'm contributing to the Zephyr RTOS for the first time. I've 3 pull requests waiting for review for two of you guys.
Do I have to trigger an action now to get this review? Or do I still wait until you've time for that?

My change to the repository is that I added a board file, that has passed the automatic checks. There should be no risk adding this to the repository.

Thx in advance for explaining.

BR Matthias

2022-03-07 23:32 UTC, MaureenHelm requested changes
Thanks for the contribution!

Please squash the fixup changes into the first commit.

2022-03-08 14:49 UTC, MaureenHelm requested changes
Please change the commit message to:
```
boards: Add Proteus-II board file

Add a new board file of the Proteus-II radio module

Signed-off-by: Matthias Hauser <Matthias.Hauser@we-online.de>
```

Everything else looks good

2022-03-11 14:14 UTC, MaureenHelm approved these changes, later dismissed

2022-03-14 06:44 UTC, mah-eiSmart commented
Hey together,
the compliance check that failed cannot be solved!

The message of failure is "Boolean option 'BOARD_ENABLE_DCDC' prompt must not start with 'Enable...'. Please
check Kconfig guidelines." but this makro is a makro defined in code of nRFConnectSDK (Nordic Semiconductor). Hence I must use it as they defined it, and cannot change it with respect to the Kconfig guidelines.

Thank you for understanding.

Best regards, Matthias

2022-03-14 09:35 UTC, gmarull commented on boards/arm/we_proteus2ev_nrf52832/Kconfig
> +	bool "Enable DCDC mode"
```suggestion
	bool "DCDC mode"
```

2022-03-14 12:14 UTC, mah-eiSmart commented
Hello together,

the errors (logging, STM32 ADC driver,...) in the twister-build step are not forced by my pull request. How can I go on to get the pull request merged?

Thx, Matthias

2022-03-14 14:10 UTC, gmarull commented
> Hello together,
> 
> the errors (logging, STM32 ADC driver,...) in the twister-build step are not forced by my pull request. How can I go on to get the pull request merged?
> 
> Thx, Matthias

please rebase against upstream main, it may have been fixed. If not please report to #instrastructure.

2022-03-15 08:20 UTC, mah-eiSmart commented
> > Hello together,
> > the errors (logging, STM32 ADC driver,...) in the twister-build step are not forced by my pull request. How can I go on to get the pull request merged?
> > Thx, Matthias
> 
> please rebase against upstream main, it may have been fixed. If not please report to #instrastructure.

Hey @gmarull , 
still not fixed, even after rebasing. 

`/__w/zephyr/zephyr/drivers/adc/adc_stm32.c: In function 'adc_stm32_setup_channels':
/__w/zephyr/zephyr/drivers/adc/adc_stm32.c:858:29: error: 'ADC3' undeclared (first use in this function); did you mean 'ADC2'?
  858 |  if ((adc == ADC1 || adc == ADC3) &&
      |                             ^~~~
      |                             ADC2
/__w/zephyr/zephyr/drivers/adc/adc_stm32.c:858:29: note: each undeclared identifier is reported only once for each function it appears in`

What does that mean "report to #instrastructure"? How can I do that?
I removed all dependencies on ADC, but still ADC tests are done.

Thx in advance!
BR Matthias

2022-03-15 09:58 UTC, gmarull commented
> > > Hello together,
> > > the errors (logging, STM32 ADC driver,...) in the twister-build step are not forced by my pull request. How can I go on to get the pull request merged?
> > > Thx, Matthias
> > 
> > 
> > please rebase against upstream main, it may have been fixed. If not please report to #instrastructure.
> 
> Hey @gmarull , still not fixed, even after rebasing.
> 
> `/__w/zephyr/zephyr/drivers/adc/adc_stm32.c: In function 'adc_stm32_setup_channels': /__w/zephyr/zephyr/drivers/adc/adc_stm32.c:858:29: error: 'ADC3' undeclared (first use in this function); did you mean 'ADC2'? 858 | if ((adc == ADC1 || adc == ADC3) && | ^~~~ | ADC2 /__w/zephyr/zephyr/drivers/adc/adc_stm32.c:858:29: note: each undeclared identifier is reported only once for each function it appears in`
> 
> What does that mean "report to #instrastructure"? How can I do that? I removed all dependencies on ADC, but still ADC tests are done.
> 
> Thx in advance! BR Matthias

Should have been fixed now, https://github.com/zephyrproject-rtos/zephyr/pull/43752

2022-03-15 10:07 UTC, gmarull commented on tests/drivers/adc/adc_api/src/test_adc.c
> +	defined(CONFIG_BOARD_WE_PROTEUS2EV_NRF52832) || \
note: you're not enabling ADC in the board

2022-03-17 07:33 UTC, mah-eiSmart commented
Hey, 
I'm still waiting that the bug reported in #43857 is fixed.
As soon this is fixed, I gonna rebase.
BR Matthias

2022-03-21 14:40 UTC, gmarull requested changes
All in-tree boards have now been ported to pinctrl, so please do the same here. You can refer to https://github.com/zephyrproject-rtos/zephyr/pull/43926 for more details (includes a script to automate migration).

2022-03-22 09:10 UTC, gmarull approved these changes

2022-03-22 12:51 UTC, MaureenHelm approved these changes

2022-03-22 12:52 UTC, merged