WIP: Add zephyr logging to ztest
zephyrproject-rtos/zephyr pull request #43347
Opened 2022-03-02 03:37 UTC by tristan-google

This is a demo PR for the TSC based on a conversation on the #testing
channel in the Discord.

  * Define a set of ztest logging macros (ZTEST_ERR, ZTEST_WRN, etc)
    that get used globally.
  * Add a Kconfig for choosing between Zephyr logging framework and
    built-in printk() logging (only supported in new ztest API)
  * Transistion ztest log outputs to these new macros at the appropriate
    levels.

 ### TODO
  * There's a lot of test output happening in tc_util.h, which isn't
    part of ztest and has its own printk macro wrapper. Need to find
    a nice way to override that.
  * Various other TODOs and thoughts added in comments.
  * Strip newlines from log messages since logging subsystem adds its
    own.

Zephyr logging has been enabled in the `tests/ztest/base/` tests, which
you can run with `/workdir/zephyr/scripts/twister -T
/workdir/zephyr/tests/ztest/base -vvv` for dev purposes.

2022-03-02 04:08 UTC, nashif commented
You want to talk to this in the TSC tomorrow?

2022-03-02 16:44 UTC, dleach02 commented
@hakehuang ping

2022-03-03 18:16 UTC, yperess requested changes

2022-03-03 18:16 UTC, yperess commented on subsys/testsuite/ztest/include/ztest_assert.h
> +		ZTEST_ERR("%s\n", formatted_msg);
Can you use `Z_LOG_VA`?

Alternatively (if not), I think your best bet is to actually turn `z_zassert` into a macro, then you can just pass `msg` and `__VA_ARGS__` to `ZTEST_ERR`

2022-05-24 00:30 UTC, closed without merging