drivers: modem: gsm_ppp: Enable hooking the setup process
zephyrproject-rtos/zephyr pull request #43373
Opened 2022-03-02 14:28 UTC by tautologyclub

This enables quirky modems, non-standard radio techs etc to work under
Zephyr without forcing developers to maintain huge patches. Previously,
there was no interface for:

- configuring NB-IoT or LTE CAT-M1,
- specifying the bandmask,
- disabling 3G

or a whole slew of other things that one might have to do to accomodate
modems that require slightly non-standard setup steps. This commit
should solve this problem, at least for most modems.

Signed-off-by: Benjamin Lindqvist <benjamin.lindqvist@endian.se>

2022-03-02 14:30 UTC, tautologyclub commented
This requires more work, but first I'd like general input.

This at least enables us to run LTE CAT M-1 and NB-IoT on U-Blox SARA R4, and configure some roaming settings on a SIMCOM7600E, without having to maintain out-of-tree patches. This would not have been possible without this patch.

2022-03-18 13:29 UTC, HrMitrev commented
Is there any updates on the subject? To me it looks quite interesting at least as an idea. I would even prefer if all AT commands are out in the user code and there's no CONFIG_MODEM_GSM_GENERIC / CONFIG_MODEM_GSM_QUECTEL. This way I can support multiple add-on modems based on mdm_model string without the need of different firmware. @ycsin

2022-03-20 13:56 UTC, ycsin requested changes
I think you need to add two more states in the `gsm_finalize_connection` for the added hooks

2022-03-20 13:56 UTC, ycsin commented on drivers/modem/Kconfig.gsm
> +	  If this is enabled, the application can hook into the setup procedure at
fix formatting

2022-03-20 13:56 UTC, ycsin commented on drivers/modem/gsm_ppp.c
> +			LOG_DBG("%s returned %d", "setup_hook", ret);
Would `LOG_ERR` be a better choice?

2022-03-20 13:56 UTC, ycsin commented on drivers/modem/gsm_ppp.c
> +			(void)gsm_work_reschedule(&gsm->gsm_configure_work,
The driver could potentially stuck here forever

2022-03-20 13:56 UTC, ycsin commented on drivers/modem/gsm_ppp.c
> +		LOG_DBG("Couldn't create PDP context (error %d), %s", ret,
error?

2022-03-20 13:56 UTC, ycsin commented on drivers/modem/gsm_ppp.c
> +			LOG_DBG("%s returned %d", "setup_hook", ret);
error?

2022-03-21 08:46 UTC, jukkar commented
> Are there any updates on the subject? To me it looks quite interesting at least as an idea. I would even prefer if all AT commands are out in the user code and there's no CONFIG_MODEM_GSM_GENERIC / CONFIG_MODEM_GSM_QUECTEL. This way I can support multiple add-on modems based on mdm_model string without the need of different firmware.

I also like the idea that vendor specific configuration would be out of generic driver, although I am not sure that all AT commands would be in user code.  If user has a generic GSM modem without any vendor stuff, there should be no need to do anything special in application part. If the application defines any callbacks, it can override configurations but if it does not define any callbacks, then the default would be used.

2022-03-22 07:01 UTC, endian-benjamin commented
@jukkar @ycsin @HrMitrev I am still looking for general comments on this approach (let's hold off on bickering about indentation etc), what looks iffy and what more will be required? For example, this still requires the hooks to do stuff like:

```
#include "../drivers/modem/modem_cmd_handler.h"
```

Should we perhaps make these internal headers a bit less internal somehow?

Also, the hook prototypes are pretty weird, but I believe those args are required. An alternative would be to expose the `gsm` struct. But that feels like killing mosquitos with a sledgehammer.

2022-03-22 07:33 UTC, ycsin commented
> I am still looking for general comments on this approach

I'd probably have a function to register callback when the state of the gsm driver changes, I think this *might* be easier after the merge of the FSM implementation, that way I think user can have better control over the gsm driver.

```c
int gsm_ppp_change_state(struct gsm_modem *gsm, enum gsm_state target_state, void *user_data) {
	int ret = 0;

	gsm->state = target_state;
	if (gsm->state_change_cb) {
		ret = gsm->state_change_cb(gsm, target_state, user_data);
	}

	return ret;
}
```

We probably can have a cb for things like the registration state / rssi as well (application might be able to use these data), but I dont have any real use case for these.

2022-03-22 09:46 UTC, endian-benjamin commented
> > I am still looking for general comments on this approach
> 
> I'd probably have a function to register callback when the state of the gsm driver changes, I think this _might_ be easier after the merge of the FSM implementation, that way I think user can have better control over the gsm driver.
> 
> ```c
> int gsm_ppp_change_state(struct gsm_modem *gsm, enum gsm_state target_state, void *user_data) {
> 	int ret = 0;
> 
> 	gsm->state = target_state;
> 	if (gsm->state_change_cb) {
> 		ret = gsm->state_change_cb(gsm, target_state, user_data);
> 	}
> 
> 	return ret;
> }
> ```
> 
> We probably can have a cb for things like the registration state / rssi as well (application might be able to use these data), but I dont have any real use case for these.

So the gsm setup state is an external API now?

2022-03-22 10:44 UTC, ycsin commented
> So the gsm setup state is an external API now?

It could be public when necessary

2022-03-22 11:00 UTC, endian-benjamin commented
> > So the gsm setup state is an external API now?
> 
> It could be made public when necessary

Well... I think internal state should be kept hidden as much as possible. This was discussed in another issue already I believe. External APIs need to be stable. The gsm FSM doesn't seem like a stable API to me.

2022-06-05 00:31 UTC, closed without merging