boards: add support for stm32f401_mini
zephyrproject-rtos/zephyr pull request #43384
Opened 2022-03-02 16:42 UTC by bpbradley

Adds support for [the STM32 Mini F401 board](https://stm32-base.org/boards/STM32F401CCU6-STM32-Mini-F401).

It is the lowest cost / most barebones board that I could find which is domestically available (can buy it on Amazon for ~5 dollars in the US).

2022-03-03 08:28 UTC, FRASTM submitted a review, later dismissed

2022-03-10 16:21 UTC, erwango approved these changes, later dismissed

2022-03-10 16:21 UTC, erwango commented on boards/arm/stm32f401_mini/doc/index.rst
> +The STM32 Mini S401 is an extremely low cost and bare-bones
s/S401/F401

2022-03-10 16:46 UTC, erwango approved these changes, later dismissed

2022-03-14 11:12 UTC, ABOSTM requested changes

2022-03-14 11:12 UTC, ABOSTM commented on boards/arm/stm32f401_mini/stm32f401_mini_defconfig
> +CONFIG_SOC_STM32F401XE=y
CONFIG_SOC_STM32F401XC=y

2022-03-14 13:45 UTC, bpbradley commented on boards/arm/stm32f401_mini/doc/index.rst
> +to achieve a stable USB clock (42MHz).
Fixed. This was an artifact from the docs of a board I made in the past. I simply removed it as it isn't that useful of a note anyway. Thanks for catching.

2022-03-14 13:45 UTC, bpbradley commented on boards/arm/stm32f401_mini/stm32f401_mini_defconfig
> +CONFIG_SOC_STM32F401XE=y
Fixed

2022-03-14 14:20 UTC, ABOSTM requested changes

2022-03-14 16:19 UTC, FRASTM submitted a review, later dismissed

2022-03-14 18:32 UTC, bpbradley commented on boards/arm/stm32f401_mini/stm32f401_mini.dts
> +#include <st/f4/stm32f401Xe.dtsi>
Of course... I probably should have built a sample after making the last change. I will have it fixed in a few minutes.

Thanks!

2022-03-14 19:31 UTC, bpbradley commented
It seems tests are failing because of an issue with the nucleo_l4r5zi? I don't think this is related to my PR.

2022-03-15 07:52 UTC, erwango submitted a review, later dismissed

2022-03-15 08:27 UTC, ABOSTM submitted a review, later dismissed

2022-03-15 09:52 UTC, benediktibk commented
@bpbradley #43750 is fixed, ready for rebase

2022-03-15 17:02 UTC, bpbradley commented
Looks like I am waiting on the hotfix in #43805 before this will pass

2022-03-16 14:25 UTC, MaureenHelm approved these changes, later dismissed

2022-03-16 15:05 UTC, ABOSTM submitted a review, later dismissed

2022-03-16 16:21 UTC, erwango submitted a review, later dismissed

2022-03-16 17:54 UTC, bpbradley commented
> 

@erwango did I mess something up? I am still having the same issue. I rebased to main and force pushed. My commit is on top of ae71444426a07a918ff82132e046e90d05093725 which I believe was supposed to resolve this issue.

2022-03-16 18:20 UTC, erwango commented
It seems we can't rely on CI to detect issues on unrelated PRs but not much on the one we need.
Last step is https://github.com/zephyrproject-rtos/zephyr/pull/43857 (hopefully)

2022-03-16 18:22 UTC, bpbradley commented
> 

Sounds good, I will wait for that to be merged before requesting re-reviews. Thanks!

2022-03-22 13:25 UTC, erwango approved these changes

2022-03-22 13:40 UTC, bpbradley commented
Thanks @erwango  -- Looks like the fix for the CI issue was merged and tests are now passing. Re-requesting reviews now.

2022-03-29 16:30 UTC, MaureenHelm approved these changes

2022-03-29 16:35 UTC, merged