dtlib: Allow overlay files to have version
zephyrproject-rtos/zephyr pull request #43455
Opened 2022-03-04 21:18 UTC by jeremybettis

According to the dts spec, all dts and dtsi files can have a /dts-v1/;
directive at the start of the file. However since zephyr uses the C
preprocessor to concatinate the files together, the version directive
can happen anywhere. Change dtlib to allow extra version directives
to appear anywhere in the file.

Change-Id: I3e227d09769f2f03f128ce6b18e7a51485b1a577

2022-03-07 10:39 UTC, carlescufi commented
@jeremybettis thanks for the patch. Note that on GitHub you don't need a `Change-Id` like with Gerrit, not sure if this was cherry-picked from a patch that was earlier submitted to a Gerrit instance.

2022-03-07 10:40 UTC, carlescufi submitted a review, later dismissed

2022-03-08 09:41 UTC, henrikbrixandersen requested changes
Please remove the `Change-Id` line from the commit message. Otherwise looks good.

2022-03-08 16:17 UTC, jeremybettis commented
> Please remove the `Change-Id` line from the commit message. Otherwise looks good.

done

2022-03-08 16:21 UTC, jeremybettis commented
> @jeremybettis thanks for the patch. Note that on GitHub you don't need a `Change-Id` like with Gerrit, not sure if this was cherry-picked from a patch that was earlier submitted to a Gerrit instance.

I have a local repo where it has both ChromiumOS and Zephyr Github as remotes to move changes back and forth easier, and somehow I ended up with a pre-commit hook that adds that Change-Id. I now see I need to use git commit --no-verify when making changes on this setup.

2022-03-08 20:08 UTC, henrikbrixandersen approved these changes

2022-03-09 16:24 UTC, keith-zephyr approved these changes

2022-03-11 10:01 UTC, carlescufi approved these changes

2022-03-11 19:25 UTC, mbolivar-nordic requested changes
Overlay files should not be starting with `/dts-v1/;` as far as I can see. The build system concatenates overlay source files to a pre-existing devicetree source, so overlays should expect the `/dts-v1/;` marker to already be present, and they should not include it. Therefore I do not think that the existing justification is convincing enough to merge this, and I would argue that such cases are a user error. Please help me understand  if I'm missing something.

2022-03-15 15:38 UTC, mbolivar-nordic commented
> It's not overlay files, but dtsi files that would start with /dts-v1/;.

OK, this comment in the patch is throwing me off, then:

```
                 # Overlay files may start with /dts-v1/; also, so allow it
```

I went and checked `dtc`'s behavior and it doesn't accept multiple `/dts-v1/;` appearing in random places like this:

>  Looking to the dts documentation in linux, it seems correct that dtsi files should start with the version marker

I went and checked what `dtc` does:

```
$ cat foo.dts
/dts-v1/;

/ {
        buttons {
        };
};

/dts-v1/;
$ dtc -O dts foo.dts
Error: foo.dts:8.1-9 syntax error
FATAL ERROR: Unable to parse input tree
```

So the upstream Linux tooling doesn't seem to accept this, either. What "dts documentation in linux" are you referring to?

2022-03-16 16:13 UTC, jeremybettis commented
I just want this to work:

a.dtsi
```
/dts-v1/;

/ {
        widgets {
        };
};
```

b.dtsi
```
/dts-v1/;

/ {
        wobbles {
        };
};
```

foo.dts
```
#include "a.dtsi"
#include "b.dtsi"

/ {
        baubles {
        };
};

```

That would work with the dts tool (except that it doesn't support #include, so you would need to use the correct import syntax.  But it doesn't work in Zephyr right now.

What do I need to change in this PR to make you happy?

2022-03-23 18:49 UTC, jeremybettis commented
> 
> > What "dts documentation in linux" are you referring to?
> 
> You have not responded to this. You have not responded to my point that Linux doesn't seem to accept this either.

https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.4-rc1 is the documentation I read. It seems to indicate that all files should have /dts-v1/;

The alternative to this PR is one that removes /dts-v1/; from all dtsi files. Would you prefer that?

2022-03-25 17:49 UTC, mbolivar-nordic commented
I double checked again and I think you are mistaken. I will try to explain in detail below. If you want me to consider this PR, I really need you to provide a detailed counterexample with steps to reproduce. I want to help you and I'm not trying to be the bad guy here. I just see no need for this change, and since I maintain dtlib, I need you to convince me that I'm wrong, **with details**, not just vague references to elsewhere.

First: it's true that you can have as many `/dts-v1/;` values at the **start** of a file as you want, and Zephyr's tooling (dtlib) does support that, as does dtc (which is the tool mentioned in the devicetree spec you have linked -- and for clarity, that is not Linux documentation; it is maintained by a separate organization).

So for example, this devicetree is legal, and is accepted by dtc:

```
/dts-v1/;

/dts-v1/;

/ {};
```

And a similar devicetree works fine in zephyr. For example, on today's main branch, if I do this:

```patch
diff --git a/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts b/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
index 3306fb6bce..0aac3d9636 100644
--- a/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
+++ b/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
@@ -4,6 +4,9 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+/dts-v1/;
+/dts-v1/;
+/dts-v1/;
 /dts-v1/;
 #include <nordic/nrf52840_qiaa.dtsi>
 #include "nrf52840dk_nrf52840-pinctrl.dtsi"
diff --git a/dts/arm/nordic/nrf52840_qiaa.dtsi b/dts/arm/nordic/nrf52840_qiaa.dtsi
index d460f0582c..e2266d58ab 100644
--- a/dts/arm/nordic/nrf52840_qiaa.dtsi
+++ b/dts/arm/nordic/nrf52840_qiaa.dtsi
@@ -4,6 +4,9 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+/dts-v1/;
+/dts-v1/;
+
 #include <mem.h>
 #include <nordic/nrf52840.dtsi>
 
```

Then I can run this with no issues:

```
$ west build -p -b nrf52840dk_nrf52840 samples/hello_world/
```

But this devicetree is illegal, and is not accepted by dtc, regardless of whether the final `/dts-v1/;` comes from an `/include/` (which by the way, Zephyr's devicetree tooling **does** support) or is written inline:

```
/dts-v1/;

/ {};

/dts-v1/;
```

And dtlib similarly rejects this diff with the same `west build` command as I pasted before:

```patch
diff --git a/dts/arm/nordic/nrf52840_qiaa.dtsi b/dts/arm/nordic/nrf52840_qiaa.dtsi
index d460f0582c..0b80174890 100644
--- a/dts/arm/nordic/nrf52840_qiaa.dtsi
+++ b/dts/arm/nordic/nrf52840_qiaa.dtsi
@@ -20,3 +20,6 @@
                compatible = "nordic,nRF52840-QIAA", "nordic,nRF52840", "nordic,nRF52", "simple-bus";
        };
 };
+
+
+/dts-v1/;
```

So zephyr's dtlib accepts the same things that devicetree.org's dtc accepts, and rejects the same thing dtc rejects, as far as I can tell. I see no inconsistencies between the two sets of tools here.

If I'm missing something, please point it out.

2022-03-28 18:53 UTC, closed without merging