board: gd32e103v_eval: add prescaler to timer.
zephyrproject-rtos/zephyr pull request #43461
Opened 2022-03-05 10:37 UTC by feilongfl

I find I had a mistake in #36833 that default timer clock source is too fast,
so add prescaler to timer, samples can work without patch feilongfl@4093c50 .

tested with `samples/basic/fade_led`

2022-03-05 11:47 UTC, nandojve requested changes

2022-03-05 11:47 UTC, nandojve commented on boards/arm/gd32e103v_eval/gd32e103v_eval.dts
> +	prescaler = <128>;
Hi @feilongfl ,

LGTM! I only think you can rework commit message. You need a prescaler to have long time period, right?

2022-03-06 15:12 UTC, nandojve approved these changes

2022-03-07 09:53 UTC, gmarull approved these changes

2022-03-07 09:57 UTC, merged