Bluetooth: iso: Fix Data Channel Path configuration
zephyrproject-rtos/zephyr pull request #43533
Opened 2022-03-08 12:45 UTC by MariuszSkamra

This fixes the data path configuration parameters.

2022-03-08 15:11 UTC, Thalley requested changes
The switch between `in_path` and `out_path` can be considered irrelevant. It depends on the viewpoint, where `out` used to refer to Ctrl to Host (to be comparable with the core spec terms: 
![image](https://user-images.githubusercontent.com/2520413/157265983-a86de2f2-4cad-40ed-9e6f-67aaa7d80557.png)
). Ditto for `in`, so I wouldn't mind that if that could reverted back again. 

Otherwise this change seem sound. If you haven't already please run one of the ISO samples as well to ensure that they still work (unfortunately we don't have CI for ISO yet). 

This change also relates to https://github.com/zephyrproject-rtos/zephyr/pull/42029/files. 

Lastly, please add `fixes` to https://github.com/zephyrproject-rtos/zephyr/issues/43190

2022-03-09 12:12 UTC, MariuszSkamra commented
> 

Ah, I had to mix up something. I removed the patch from the PR.

2022-03-09 12:32 UTC, Thalley approved these changes
Looks good. I honestly don't remember why or how the `BT_ISO_DATA_PATH_DISABLED` ever worked :D

2022-03-09 13:30 UTC, jhedberg approved these changes

2022-03-10 19:33 UTC, merged