drivers: clock_control: lpc: syscon: Add BUSCLK support
zephyrproject-rtos/zephyr pull request #43554
Opened 2022-03-08 18:27 UTC by Navin-Sankar

Add support for the LPC BUS clock to the LPC SYSCON clock controller
driver.

Signed-off-by: Navin Sankar Velliangiri <navin@linumiz.com>

2022-03-09 16:12 UTC, mmahadevan108 requested changes

2022-03-09 16:12 UTC, mmahadevan108 commented on drivers/clock_control/clock_control_mcux_syscon.c
> +		break;
Please replace 1 with kCLOCK_BusClk

2022-03-13 10:16 UTC, Navin-Sankar commented on drivers/clock_control/clock_control_mcux_syscon.c
> +		break;
replaced. Thanks!

2022-03-14 14:18 UTC, danieldegrasse approved these changes

2022-03-14 14:34 UTC, MaureenHelm approved these changes

2022-03-23 04:26 UTC, dleach02 approved these changes

2022-03-23 20:24 UTC, mmahadevan108 approved these changes

2022-03-24 09:44 UTC, merged