Bluetooth: Controller: Fix Extended Legacy Direct Advertising report
zephyrproject-rtos/zephyr pull request #43633
Opened 2022-03-10 01:18 UTC by cvinayak

Fix Extended Legacy Direct Advertising report to have the
correct Target Address.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2022-03-16 12:14 UTC, Thalley requested changes

2022-03-16 12:14 UTC, Thalley commented on subsys/bluetooth/controller/hci/hci.c
> +	       sizeof(bt_addr_t));
```suggestion
	bt_addr_copy(&adv_info->direct_addr.a, &adv->direct_ind.tgt_addr);
```

2022-03-17 06:40 UTC, ppryga approved these changes, later dismissed

2022-03-17 07:29 UTC, ppryga-nordic approved these changes

2022-03-17 09:34 UTC, Thalley approved these changes

2022-03-17 10:38 UTC, carlescufi approved these changes

2022-03-17 10:38 UTC, merged