MAINTAINAERS: introduce formatted output and fix path matching for BT
zephyrproject-rtos/zephyr pull request #43677
Opened 2022-03-10 18:54 UTC by nashif

Introduce formatted ouptut area and fix BT controller paths for tests.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2022-03-10 19:17 UTC, jhedberg requested changes
Typo in the commit message: MAINTAINAERS

Also, having “and” in the subject is usually a hint to consider splitting the commit up in two. Even though it’s the same file the changes aren’t really related. But I’ll leave that up to you to decide.

2022-03-10 19:30 UTC, jhedberg approved these changes

2022-03-15 13:33 UTC, nashif commented
@nordic-krch  ping

2022-03-15 13:40 UTC, nordic-krch approved these changes

2022-03-15 13:43 UTC, merged