[backport v2.7-branch] soc: arm: stm32 mcus should execute stm32_power_init in PRE_KERNEL_1
zephyrproject-rtos/zephyr pull request #43771
Opened 2022-03-14 14:35 UTC by FRASTM

Change the stm32_power_init to be executed PRE_KERNEL_1
for all the devices with the low power mode (power.c)
when GPIO and UART are not yet up and running.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/42915

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-03-14 14:44 UTC, ycsin approved these changes

2022-03-14 15:12 UTC, ycsin commented
Associated issue is https://github.com/zephyrproject-rtos/zephyr/issues/41442

2022-03-16 00:26 UTC, cfriedt commented
@erwango - can you ack this one?

2022-03-16 07:55 UTC, erwango requested changes
This PR is fixing https://github.com/zephyrproject-rtos/zephyr/issues/41442 which was raised following a code review.
Typically, even if the risk is low, I think this is the kind of PR we can avoid to merge in 2.7 if we're aiming at keeping the branch stable.

2022-03-16 15:41 UTC, cfriedt commented
Closing due to nak

2022-03-16 15:41 UTC, closed without merging