drivers: pwm: microchip: Add MEC172x PWM support
zephyrproject-rtos/zephyr pull request #43780
Opened 2022-03-14 21:39 UTC by jvasanth1

Add support for MEC172x PWM and pin control changes.

2022-03-15 14:40 UTC, gmarull requested changes

2022-03-15 14:40 UTC, gmarull commented on boards/arm/mec172xevb_assy6906/mec172xevb_assy6906.dts
> +	pinctrl-0 = < &pwm0_gpio053 >;
```suggestion
	pinctrl-0 = <&pwm0_gpio053>;
```

2022-03-15 14:40 UTC, gmarull commented on boards/arm/mec172xevb_assy6906/mec172xevb_assy6906_defconfig
> +CONFIG_PWM_XEC=y
PWM is not a minimal peripheral, so it should not be in the board defconfig per porting guidelines (actually same applies for some other entries in that file).

2022-03-15 14:40 UTC, gmarull commented on dts/bindings/pwm/microchip,xec-pwm.yaml
> +      required: false
```suggestion
```

this is redundant

2022-03-17 16:16 UTC, jvasanth1 commented on boards/arm/mec172xevb_assy6906/mec172xevb_assy6906.dts
> +	pinctrl-0 = < &pwm0_gpio053 >;
Fixed

2022-03-17 19:10 UTC, gmarull approved these changes
pinctrl part LGTM

2022-03-21 18:57 UTC, albertofloyd approved these changes

2022-03-21 23:17 UTC, mbolivar-nordic reviewed
ACK on the devicetree portions

2022-03-22 01:49 UTC, merged