drivers: console: adds hardware CDC as option for console and shel for esp32c3
zephyrproject-rtos/zephyr pull request #43881
Opened 2022-03-16 16:20 UTC by uLipe

This PR adds the hardware CDC of esp32c3 as an option for console and shell backend.

2022-03-17 07:48 UTC, bbilas commented on drivers/console/Kconfig
> +	default n
bool symbols implicitly default to n.

2022-03-17 12:43 UTC, sylvioalves commented on subsys/shell/backends/Kconfig.backends
> +		Enables shell backend over ESP32 hardware CDC.
2-space indentation.

2022-03-17 12:45 UTC, sylvioalves approved these changes

2022-04-20 21:34 UTC, glaubermaroto approved these changes

2022-04-22 07:35 UTC, jfischer-no requested changes

2022-04-22 07:35 UTC, jfischer-no commented on subsys/shell/backends/shell_esp32_hw_cdc.c
> +SHELL_DEFINE(shell_esp32_hw_cdc, CONFIG_SHELL_PROMPT_ESP32_HW_CDC, &shell_transport_esp32_hw_cdc,
Since you have to wrap the line, can you please make it nicer?

2022-04-22 07:35 UTC, jfischer-no commented on drivers/console/esp32_hw_cdc_console.c
> +	esp_rom_usb_uart_tx_one_char(character);
I do not like to see `_usb_` in identifiers that are not related to USB subsystem in Zephyr.

2022-04-22 07:35 UTC, jfischer-no commented on subsys/shell/backends/shell_esp32_hw_cdc.c
> +	uint8_t *ptr = (uint8_t *)data;
Please not like this. Define variable at the top of a block, change to:

```c
static int write(const struct shell_transport *transport,
		 const void *data, size_t length, size_t *cnt)
{
	const uint8_t *ptr = (const uint8_t *)data;

	*cnt = length;

```

2022-04-22 07:35 UTC, jfischer-no commented on subsys/shell/backends/shell_esp32_hw_cdc.c
> +const struct shell_transport_api shell_transport_esp32_hw_cdc_api = {
nit, there is no need to make a poem out of every identifier.

2022-06-22 04:26 UTC, closed without merging