everywhere: fix typos
zephyrproject-rtos/zephyr pull request #43890
Opened 2022-03-16 21:21 UTC by nazar01

Fix a lot of typos

Signed-off-by: Nazar Kazakov <nazar.kazakov.work@gmail.com>

2022-03-16 21:21 UTC, nazar01 commented
Gotta admit it's quite funny :D

2022-03-16 21:38 UTC, nazar01 commented
Fixing some CI warnings...

2022-03-16 21:46 UTC, nazar01 commented
Ok, looks like the rest of CI warnings aren't meaningful

2022-03-17 02:36 UTC, stephanosio requested changes
Looks ok overall. Just need to fix some.

2022-03-17 02:36 UTC, stephanosio commented on samples/boards/nrf/mesh/onoff_level_lighting_vnd_app/src/mesh/device_composition.c
> +/* Generic Level (lightness) Server message handlers */
to be consistent with `/* Generic Level (TEMPERATURE) Server message handlers */` below:

```suggestion
/* Generic Level (LIGHTNESS) Server message handlers */
```

2022-03-17 07:02 UTC, ppryga approved these changes, later dismissed
Reviewed changes for BLE direction finding.
BTW. Thank for the corrections!

2022-03-17 07:56 UTC, Laczen approved these changes, later dismissed
Changes to nvs are OK, thanks.

2022-03-17 08:05 UTC, de-nordic submitted a review, later dismissed
VFS and mcumgr look ok.

2022-03-17 08:38 UTC, ruuddw approved these changes, later dismissed
All ARC fixes look fine, thanks! Guess who will be top contributor for this release...

2022-03-17 09:12 UTC, avisconti approved these changes, later dismissed
It's a tough job, but someone had to do it!

2022-03-17 09:36 UTC, Thalley commented
Not sure why GH decided that I removed review request from all those people when I just removed it from myself :s

2022-03-17 10:15 UTC, nazar01 commented on cmake/linker/ld/ld_script.cmake
> +#?
Fixed, thanks!

2022-03-17 10:16 UTC, nazar01 commented
Hmm, GH "dismissed stale reviews" for me, I didn't do it

2022-03-17 10:19 UTC, Thalley commented
> Hmm, GH "dismissed stale reviews" for me, I didn't do it

That's due to a recent change in our GH settings. If you rebase your PR it will typically dismiss all current approvals.

2022-03-17 10:40 UTC, nazar01 commented
Rebased on main

2022-03-17 11:20 UTC, ruuddw approved these changes

2022-03-17 11:35 UTC, nandojve approved these changes

2022-03-17 11:39 UTC, stephanosio approved these changes

2022-03-17 11:45 UTC, gmarull commented
@nazar01 did you use any tool to automate those changes? Would probably be good to add it to CI.

2022-03-17 12:36 UTC, cfriedt approved these changes

2022-03-17 13:05 UTC, nazar01 commented
> @nazar01 did you use any tool to automate those changes? Would probably be good to add it to CI.

It was mostly manual, I went through all spellcheck warnings in my IDE (CLion)

2022-03-17 14:05 UTC, microbuilder approved these changes

2022-03-18 13:42 UTC, nazar01 commented
Merge?

2022-03-18 14:18 UTC, nazar01 commented
To whoever wants to merge it: feel free to delete my merge commit and rebase this PR on main instead.

2022-03-18 17:04 UTC, gmarull commented
> To whoever wants to merge it: feel free to delete my merge commit and rebase this PR on main instead.

You should rebase and force-push. It looks like CI has some failures (maybe the changes triggered some unknown issues), if they are not related to your changes, please report them.

2022-03-18 17:24 UTC, merged