tests: sockets: Add TCP test cases
zephyrproject-rtos/zephyr pull request #4390
Opened 2017-10-18 03:15 UTC by askawu

- Following test cases are added.
   - Test ipv4/ipv6 send() and recv().
   - Test ipv4/ipv6 sendto() and recvfrom().
   - Test ipv4/ipv6 sendto() and recvfrom() with bad dest address. 
   - Test ipv4/ipv6 sendto() and recvfrom() with NULL dest address.
- Before running test cases, make sure the net-tool is up-to-date and echo-server is running. 
- Run test cases by "make run" under tests/net/socket/tcp/src.

2017-10-18 10:45 UTC, pfalcon requested changes
> Before running test cases, make sure the net-tool is up-to-date and echo-server is running.

Running on the host? And the apparently loop-socat.sh/loop-slip-tap.sh too? Please add this information to the commit message (along the lines of "to run these tests, host should run the usual QEMU networking support tools, and additionally echo-server from Zephyr net-tools").

The matter, all tests in tests/ are (AFAIK) intended to be unit tests, i.e. run without any special environment setup. Your tests are however integration tests. We mostly can't write unit tests for networking, but need to somehow break thru such situation, and your tests are very welcome, but please document clearly how they need to be run.

2017-10-18 12:52 UTC, jukkar commented
> The matter, all tests in tests/ are (AFAIK) intended to be unit tests, i.e. run without any special environment setup. Your tests are however integration tests. We mostly can't write unit tests for networking, but need to somehow break thru such situation, and your tests are very welcome, but please document clearly how they need to be run.

Paul is correct here, so far we have tried to keep all the tests in tests/net self contained. If the test requires external components like host connectivity, then those tests should be placed under samples/net/

2017-10-18 13:02 UTC, nashif commented
> If the test requires external components like host connectivity, then those tests should be placed under samples/net/

No, please don't. TESTS are always under tests, do not push tests under samples. Anything under samples that is a test needs to be moved away. You can have some structure to support this under tests if you need that..

2017-10-20 07:02 UTC, askawu commented
Update:
- Make test cases self-contained without the help of net-tools echo server.
- Each test case will submit a delayed work to play the role of the client, wait for the connection by accept(), and verify the received data.
- Increasing CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE from 1024 to 2048 is necessary because the client will use socket API and be run by system work queue.
- Increasing CONFIG_NET_PKT_TX_COUNT is necessary. The tx net pkt with the same source and destination address will not be free after send() because it will be processed as the incoming pkt.

2017-10-20 07:45 UTC, jukkar approved these changes
LGTM

2017-10-20 07:54 UTC, pfalcon commented
> Make test cases self-contained without the help of net-tools echo server.

That's great!

> Each test case will submit a delayed work to play the role of the client, wait for the connection by accept(), and verify the received data.

Previously, that didn't work, see https://github.com/zephyrproject-rtos/zephyr/issues/3442 . But I didn't try to use delayed work, just used connect() followed by accept(). In a normal IP stack/sockets implementation that should work. Why did you decided to use delayed work? Did you try it without delayed work?

2017-10-20 09:48 UTC, askawu commented
@pfalcon, I don't know connect() followed by accept() can work in normal IP stack/socket. I just think another context should be used because accept() will block the test execution. After receiving your comment, I give a try to use "conenct() followed by accepted()", It didn't work. Does test cases based on delayed work make sense to you?

2017-10-20 10:26 UTC, pfalcon commented
@askawu :

> After receiving your comment, I give a try to use "conenct() followed by accepted()", It didn't work.

It didn't work in which way?

> Does test cases based on delayed work make sense to you?

Your tests are unbelievably great (I by now ran them) - you did something which I couldn't do. Now I'm trying to understand: a) why you did it the way you did (more complex than could be)? b) why your stuff works? c) why my stuff didn't?

If you'd like to have this merged ASAP, let me now and I just approve it, and any further questions will be left "for later". But I encourage you to spend more time on it, and try to understand better what work and what doesn't, and improve the tests (cover more usecases) if possible.

2017-10-20 10:29 UTC, pfalcon commented
I'm trying following patch:

~~~
diff --git a/tests/net/socket/tcp/prj.conf b/tests/net/socket/tcp/prj.conf
index 79e49503f..62e1033db 100644
--- a/tests/net/socket/tcp/prj.conf
+++ b/tests/net/socket/tcp/prj.conf
@@ -19,7 +19,9 @@ CONFIG_NET_APP_NEED_IPV6=y
 CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.1"
 CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::1"
 
-CONFIG_MAIN_STACK_SIZE=2048
+CONFIG_MAIN_STACK_SIZE=3192
+CONFIG_NET_RX_STACK_SIZE=3192
+CONFIG_NET_TX_STACK_SIZE=3192
 
 # Required:
 # The delayed work is running by system workqueue
diff --git a/tests/net/socket/tcp/src/main.c b/tests/net/socket/tcp/src/main.c
index 2f1e4f9c8..da1ac6545 100644
--- a/tests/net/socket/tcp/src/main.c
+++ b/tests/net/socket/tcp/src/main.c
@@ -57,19 +57,15 @@ static void prepare_sock_v6(int *sock, struct sockaddr_in6 *addr)
 	zassert_equal(rv, 1, "inet_pton failed");
 }
 
-static void client_conn_send(struct k_work *work)
+static void client_conn_send_(struct client_ctx *ctx)
 {
-	struct client_ctx *ctx;
 	int rv;
 	ssize_t sent;
 
-	zassert_not_null(work, "null work");
-
-	ctx = CONTAINER_OF(work, struct client_ctx, work);
-	zassert_not_null(ctx, "null ctx");
-
+printk("connecting\n");
 	rv = connect(ctx->sock, &ctx->addr, sizeof(ctx->addr));
 	zassert_equal(rv, 0, "connect failed");
+printk("connected\n");
 
 	sent = send(ctx->sock, TEST_STR_SMALL, strlen(TEST_STR_SMALL), 0);
 	zassert_equal(sent, strlen(TEST_STR_SMALL), "send failed");
@@ -78,6 +74,20 @@ static void client_conn_send(struct k_work *work)
 	zassert_equal(rv, 0, "close failed");
 }
 
+static void client_conn_send(struct k_work *work)
+{
+	struct client_ctx *ctx;
+	int rv;
+	ssize_t sent;
+
+	zassert_not_null(work, "null work");
+
+	ctx = CONTAINER_OF(work, struct client_ctx, work);
+	zassert_not_null(ctx, "null ctx");
+
+	client_conn_send_(ctx);
+}
+
 static void client_conn_sendto(struct k_work *work)
 {
 	struct client_ctx *ctx;
@@ -158,8 +168,9 @@ void test_v4_send_recv(void)
 	/* start client in another context */
 	prepare_sock_v4(&client.sock, (struct sockaddr_in *)&client.addr);
 	client.addrlen = sizeof(client.addr);
-	k_delayed_work_init(&client.work, client_conn_send);
-	k_delayed_work_submit(&client.work, CLIENT_WORK_DELAY);
+//	k_delayed_work_init(&client.work, client_conn_send);
+//	k_delayed_work_submit(&client.work, CLIENT_WORK_DELAY);
+	client_conn_send_(&client);
 
 	socklen = sizeof(addr);
 	accepted_sock = accept(sock, (struct sockaddr *)&addr, &socklen);

~~~

This crashes with:

~~~
[QEMU] CPU: qemu32
qemu-system-i386: warning: Unknown firmware file in legacy mode: genroms/multiboot.bin

shell> Running test suite socket_tcp
===================================================================
starting test - test_v4_send_recv
connecting
***** Stack Check Fail! *****
Current thread ID = 0x00420760
Faulting segment:address = 0x0008:0x0000835f
eax: 0x00000014, ebx: 0x0040707c, ecx: 0x00000000, edx: 0x004042cc
esi: 0x004042cc, edi: 0x004042cc, ebp: 0x00407000, esp: 0x00407000
eflags: 0x206
Fatal fault in thread 0x00420760! Aborting.
~~~

So, I'm trying to understand which stack it complains about (as can be seen, I already tried to bump some of them).

2017-10-20 10:34 UTC, pfalcon commented on tests/net/socket/tcp/src/main.c
> +#define CLIENT_WORK_DELAY MSEC_PER_SEC
How this delay time was chosen?

2017-10-20 10:50 UTC, askawu commented
Try CONFIG_ZTEST_STACKSIZE=4096

2017-10-20 11:06 UTC, pfalcon commented
> Try CONFIG_ZTEST_STACKSIZE=4096

Pure magic. So, the following patch works. However, if I bypass worker for test_v6_send_recv() too, *following* tests start to fail with:

~~~
starting test - test_v4_sendto_recvfrom

    Assertion failed at /mnt/hdd/projects-3rdparty/Embedded/Zephyr/zephyr/tests/net/socket/tcp/src/main.c:230: test_v4_sendto_recvfrom: listen failed (rv not equal to 0)
FAIL - test_v4_sendto_recvfrom.
~~~

I guess, TIME_WAIT is involved or something. @askawu, please work on converting as many testcases as possible to the linear execution flow, and on minimizing needed delay between the testcases - we should target this to be run in sanitycheck (using https://github.com/zephyrproject-rtos/zephyr/pull/4457 and other magic), where it will be run many times for different boards, so 1s delay between tests makes it very slow and affects sanitycheck performance.

~~~
diff --git a/tests/net/socket/tcp/prj.conf b/tests/net/socket/tcp/prj.conf
index 79e49503f..a5289b6d0 100644
--- a/tests/net/socket/tcp/prj.conf
+++ b/tests/net/socket/tcp/prj.conf
@@ -20,6 +20,7 @@ CONFIG_NET_APP_MY_IPV4_ADDR="192.0.2.1"
 CONFIG_NET_APP_MY_IPV6_ADDR="2001:db8::1"
 
 CONFIG_MAIN_STACK_SIZE=2048
+CONFIG_ZTEST_STACKSIZE=4096
 
 # Required:
 # The delayed work is running by system workqueue
diff --git a/tests/net/socket/tcp/src/main.c b/tests/net/socket/tcp/src/main.c
index 2f1e4f9c8..2cfa25e17 100644
--- a/tests/net/socket/tcp/src/main.c
+++ b/tests/net/socket/tcp/src/main.c
@@ -57,19 +57,15 @@ static void prepare_sock_v6(int *sock, struct sockaddr_in6 *addr)
 	zassert_equal(rv, 1, "inet_pton failed");
 }
 
-static void client_conn_send(struct k_work *work)
+static void client_conn_send_(struct client_ctx *ctx)
 {
-	struct client_ctx *ctx;
 	int rv;
 	ssize_t sent;
 
-	zassert_not_null(work, "null work");
-
-	ctx = CONTAINER_OF(work, struct client_ctx, work);
-	zassert_not_null(ctx, "null ctx");
-
+printk("connecting\n");
 	rv = connect(ctx->sock, &ctx->addr, sizeof(ctx->addr));
 	zassert_equal(rv, 0, "connect failed");
+printk("connected\n");
 
 	sent = send(ctx->sock, TEST_STR_SMALL, strlen(TEST_STR_SMALL), 0);
 	zassert_equal(sent, strlen(TEST_STR_SMALL), "send failed");
@@ -78,6 +74,18 @@ static void client_conn_send(struct k_work *work)
 	zassert_equal(rv, 0, "close failed");
 }
 
+static void client_conn_send(struct k_work *work)
+{
+	struct client_ctx *ctx;
+
+	zassert_not_null(work, "null work");
+
+	ctx = CONTAINER_OF(work, struct client_ctx, work);
+	zassert_not_null(ctx, "null ctx");
+
+	client_conn_send_(ctx);
+}
+
 static void client_conn_sendto(struct k_work *work)
 {
 	struct client_ctx *ctx;
@@ -158,8 +166,9 @@ void test_v4_send_recv(void)
 	/* start client in another context */
 	prepare_sock_v4(&client.sock, (struct sockaddr_in *)&client.addr);
 	client.addrlen = sizeof(client.addr);
-	k_delayed_work_init(&client.work, client_conn_send);
-	k_delayed_work_submit(&client.work, CLIENT_WORK_DELAY);
+//	k_delayed_work_init(&client.work, client_conn_send);
+//	k_delayed_work_submit(&client.work, CLIENT_WORK_DELAY);
+	client_conn_send_(&client);
 
 	socklen = sizeof(addr);
 	accepted_sock = accept(sock, (struct sockaddr *)&addr, &socklen);
@@ -192,6 +201,7 @@ void test_v6_send_recv(void)
 	client.addrlen = sizeof(client.addr);
 	k_delayed_work_init(&client.work, client_conn_send);
 	k_delayed_work_submit(&client.work, CLIENT_WORK_DELAY);
+//	client_conn_send_(&client);
 
 	socklen = sizeof(addr);
 	accepted_sock = accept(sock, (struct sockaddr *)&addr, &socklen);
~~~

2017-10-23 10:01 UTC, askawu commented
@pfalcon, I will try to refactor these test cases without using delayed work. Before that, I will check the timing issue first.

2017-10-23 10:16 UTC, pfalcon commented
@askawu , Thanks!

2017-10-27 07:25 UTC, askawu commented
The timing issue is caused by find_available_port() is used but the port number of sockaddr is unpredictable. Check #4599 for the detail.

2017-10-30 14:22 UTC, pfalcon commented
@askawu: Thanks for the investigation work so far. With https://github.com/zephyrproject-rtos/zephyr/pull/4599 merged, please let me know when this is ready for new review/testing.

2017-11-01 06:10 UTC, askawu commented
Update:
- Refactor test cases.
- At the end of each test cases, a delay is used to ensure the TCP connection is closed, so the server port can be bound successfully in the following test case. For now, the delay is 1 second which is the same as FIN_TIMEOUT in net_context.c

During testing, I found that, if net_context_put() is called to release a listening net context, FIN message isn't sent successfully because the destination address is unspecified. And it turns out the context is released by the net_context.c::handle_fin_timeout() every time. Is this what we expect? I thought FIN message would be sent to every connected peer before timeout.

2017-11-01 08:07 UTC, jukkar commented
> During testing, I found that, if net_context_put() is called to release a listening net context, FIN message isn't sent successfully because the destination address is unspecified. And it turns out the context is released by the net_context.c::handle_fin_timeout() every time. Is this what we expect? I thought FIN message would be sent to every connected peer before timeout.

The FIN timer is set when in TCP active close (==zephyr initiated termination) so that if we do not receive FIN back, we still close the connection after a timeout. But if we do not even send the FIN, then the connection is closed too early. Did you managed to figure out why the destination address is unspecified?

2017-11-01 11:05 UTC, askawu commented
> But if we do not even send the FIN, then the connection is closed too early. Did you managed to figure out why the destination address is unspecified?

As a TCP server waiting for connections, the remote address of the net context isn't assigned during bind(), listen() and accept(). When a new connection is established, a new net context will be allocated and the remote address of the new net context will be assigned based on the SYN.

When net_context_put() is called for the first net context, FIN isn't sent by net_tcp_send_pkt() in queue_fin() because the remote address is zero.

2017-11-01 11:26 UTC, pfalcon commented
@askawu : I'd suggest to open a separate ticket for this last matter, so we can consider it separately and it wasn't lost.

2017-11-01 12:23 UTC, pfalcon approved these changes
Looks great, also tested with https://github.com/zephyrproject-rtos/zephyr/pull/4457 .

2017-11-01 13:08 UTC, merged