it8xxx2: re-factor idle routine
zephyrproject-rtos/zephyr pull request #44169
Opened 2022-03-24 10:09 UTC by Dino-Li

Don't leave idle state if soc isn't waked-up by an interrupt.
(We change to check interrupt controller register)

Signed-off-by: Dino Li <Dino.Li@ite.com.tw>

2022-03-24 15:04 UTC, brockus-zephyr submitted a review, later dismissed

2022-03-25 15:21 UTC, keith-zephyr requested changes

2022-03-25 15:21 UTC, keith-zephyr commented on soc/riscv/riscv-ite/it8xxx2/soc.c
> +		__asm__ volatile ("wfi");
Interrupts are disabled at this point.  How does the CPU core wake up?

The IT81202 datasheet indicates that interrupts should be enabled before executing the standby instruction (section 5.6).

2022-03-29 22:07 UTC, keith-zephyr approved these changes, later dismissed

2022-03-29 22:07 UTC, keith-zephyr commented on soc/riscv/riscv-ite/it8xxx2/soc.c
> +		__asm__ volatile ("wfi");
Thank you for the explanation.

2022-03-30 06:50 UTC, fkokosinski approved these changes
LGTM

2022-03-30 07:55 UTC, Dino-Li commented
Rebase only. @keith-zephyr @brockus-zephyr please approve again

2022-03-30 17:17 UTC, brockus-zephyr approved these changes

2022-03-31 19:35 UTC, keith-zephyr approved these changes

2022-04-01 11:31 UTC, carlescufi commented
@GTLin08 please review

2022-04-01 11:43 UTC, GTLin08 approved these changes

2022-04-01 17:49 UTC, merged