subsys/cfb: support for HPACKED fonts
zephyrproject-rtos/zephyr pull request #44184
Opened 2022-03-24 17:04 UTC by mzagrabski

The HPACKED fonts are already declared in header.
Extend drawing routine to allow HPACKED fonts
along with VPACKED fonts.

Signed-off-by: Karol Duda <karol.duda@grinn-global.com>
Signed-off-by: Maciej Zagrabski <maciej.zagrabski@grinn-global.com>

2022-03-25 10:19 UTC, jfischer-no requested changes
Thanks, just few minor comments, please also remove _subsys/_ from the commit title:
`cfb: support for HPACKED fonts`.

2022-03-25 10:19 UTC, jfischer-no commented on subsys/fb/cfb.c
> +	       (fptr->width * fptr->height / 8U);
You forgot to remove `return NULL;` below.

2022-03-25 10:19 UTC, jfischer-no commented on subsys/fb/cfb.c
> +	} else {
Maybe it makes sense to add `LOG_WRN("Unknown font type");` here.

2022-04-01 07:04 UTC, jfischer-no approved these changes, later dismissed

2022-04-05 15:08 UTC, mniestroj commented on subsys/fb/cfb.c
> +			byte = get_glypt_byte(glyph_ptr, fptr, g_x, g_y);
```suggestion
			byte = get_glyph_byte(glyph_ptr, fptr, g_x, g_y);
```

2022-04-05 15:51 UTC, mniestroj approved these changes

2022-04-06 13:49 UTC, jfischer-no approved these changes

2022-04-06 14:49 UTC, merged