drivers: sensor: add driver for Invensense ICM42670 motion sensor
zephyrproject-rtos/zephyr pull request #44396
Opened 2022-03-31 07:56 UTC by aunsbjerg

Adds support for the Invensense ICM42670 6-axis motion sensor with support for accelerometer, gyroscope and on-die temperature readings.

Driver work is based on the ICM42605 (#29682) which is quite similar but still different enough in register layout and register access methods that it warrants a separate driver. The ICM42670 driver does not include support for the 2K sample FIFO on the IC, instead only "normal" data ready interrupts are supported.

Currently implemented features are:

* trigger support for data ready interrupts
* accelerometer and gyroscope sample frequency and range attribute setting

Future work includes alarm trigger support, alarm threshold attribute setting, power management and low power mode support, and support for advanced features like pedometer, freefall detection, tilt detection etc.

2022-04-04 20:43 UTC, mbolivar-nordic requested changes
Uses of `default` in devicetree bindings must be justified in the descriptions for each property with a default value.

Please read https://docs.zephyrproject.org/latest/guides/dts/bindings.html#default-values-for-properties and fix the bindings accordingly.

2022-04-05 06:47 UTC, aunsbjerg commented
> Uses of `default` in devicetree bindings must be justified in the descriptions for each property with a default value.
> 
> Please read https://docs.zephyrproject.org/latest/guides/dts/bindings.html#default-values-for-properties and fix the bindings accordingly.

Removed default values and converted to required properties instead.

2022-04-05 14:07 UTC, MaureenHelm approved these changes, later dismissed
Looks great, thanks

2022-04-06 06:38 UTC, aunsbjerg commented on drivers/sensor/icm42670/Kconfig
> +	depends on SPI
Neat, hadn't seen that before. Added as suggested, but keeping the explicit `CONFIG_ICM42670=y` in the build_all prj.conf to keep with the existing pattern.

2022-04-06 13:37 UTC, teburd approved these changes

2022-04-06 14:42 UTC, MaureenHelm approved these changes

2022-04-08 18:31 UTC, mbolivar-nordic approved these changes

2022-04-08 22:49 UTC, merged