mgmt/mcumgr/lib: Add OS group command for obtaining mcumgr parameters
zephyrproject-rtos/zephyr pull request #44643
Opened 2022-04-07 13:28 UTC by de-nordic

The PR adds two commits that:
 1) add documentation for new OS management command that allows to obtain MCUMGR parameters;
 2) add implementation for that commit together with Kconfig options.

Due to lack of better suggestions to https://github.com/zephyrproject-rtos/zephyr/issues/42325 this is the best thing we can have now.

2022-04-08 08:01 UTC, philips77 commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +        (str)"buff_size"    : (uint)
Why buff, not buf?

2022-04-08 08:12 UTC, lairdjm requested changes

2022-04-08 08:12 UTC, lairdjm commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset request
Don't think this title is correct

2022-04-08 08:12 UTC, lairdjm commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset response header fields
Nor these

2022-04-08 11:34 UTC, de-nordic commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset request
Will fix.

2022-04-08 11:34 UTC, de-nordic commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset response header fields
Will fix.

2022-04-08 12:37 UTC, de-nordic commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset response header fields
Done

2022-04-08 12:37 UTC, de-nordic commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +System reset request
Done

2022-04-08 12:37 UTC, de-nordic commented on doc/services/device_mgmt/smp_groups/smp_group_0.rst
> +        (str)"buff_size"    : (uint)
Done

2022-04-08 12:37 UTC, de-nordic commented
Fixed, moved to zcbor, tested.

2022-04-08 13:42 UTC, lairdjm approved these changes

2022-04-11 10:10 UTC, carlescufi approved these changes

2022-04-11 10:10 UTC, merged