ztest API Migration: lib/c_lib
zephyrproject-rtos/zephyr pull request #44851
Opened 2022-04-13 20:16 UTC by tristan-google

Migrate the unit tests at `lib/c_lib` to use the new ztest API.

Signed-off-by: Tristan Honscheid <honscheid@google.com>

2022-04-14 04:44 UTC, yperess requested changes

2022-04-14 04:44 UTC, yperess commented on tests/lib/c_lib/src/test_qsort.c
> +ZTEST_SUITE(test_c_lib_qsort, NULL, NULL, NULL, NULL, NULL);
Not needed, tests all go into a single section in the linker so you can actually link the tests here into the same test suite so this PR leaves this 1:1 with the old code, just use `ZTEST(test_c_lib, my_test_name)`

2022-04-14 04:44 UTC, yperess commented on tests/lib/c_lib/src/test_qsort.c
> +ZTEST(test_c_lib_qsort, test_qsort)
s/test_c_lib_qsort/test_c_lib/g

2022-04-21 04:45 UTC, yperess approved these changes

2022-04-22 04:14 UTC, yperess approved these changes

2022-04-26 12:30 UTC, stephanosio approved these changes

2022-04-26 12:38 UTC, nashif approved these changes

2022-04-26 12:38 UTC, merged