dts: arm: st: g4: device tree factorization
zephyrproject-rtos/zephyr pull request #44877
Opened 2022-04-14 15:00 UTC by TDhaouST

dts: arm: st: g4: device tree factorization

dts files in G4 series could use some factorization

2022-04-19 08:58 UTC, erwango requested changes
LGTM, but please fix commit title. It should be:
dts/arm/st: g4: device tree factorization

2022-04-19 09:42 UTC, erwango submitted a review, later dismissed

2022-04-19 13:25 UTC, erwango approved these changes

2022-04-20 11:36 UTC, ABOSTM approved these changes

2022-04-20 15:34 UTC, merged