boards: fix type of BOARD_DEPRECATED
zephyrproject-rtos/zephyr pull request #4496
Opened 2017-10-23 18:17 UTC by mbolivar

Proposed fix for the following message I'm seeing:

```
scripts/kconfig/conf --silentoldconfig Kconfig
/home/mbolivar/src/zephyr/boards/arm/stm32_mini_a15/Kconfig.board:11:warning: 'BOARD_DEPRECATED' has wrong type. 'select' only accept arguments of boolean and tristate type
```

2017-10-23 22:16 UTC, nashif approved these changes

2017-10-24 05:32 UTC, galak requested changes
This is wrong, I shouldn't have done a select on BOARD_DEPRECATED, its meant to be a string with the version info printed.  Will fix that.

2017-10-24 05:34 UTC, galak commented
See #4504, we should be able to close this out

2017-10-24 11:47 UTC, galak commented
WIth #4504 merged, will close this out.

2017-10-24 11:47 UTC, closed without merging

2017-10-24 13:50 UTC, mbolivar commented
Ok, makes sense