Bluetooth: Controller: Kconfig: Cleanup direction finding configs
zephyrproject-rtos/zephyr pull request #45022
Opened 2022-04-21 12:40 UTC by rugeGerritsen

- Makes it possible to support transmitting or receiving constant tone extensions only
- Removes dependencies to BT_LL_SW_SPLIT for common configurations
- Marks some configurations to be specific to BT_LL_SW_SPLIT
- Makes it possible to make BT_CTLR_DF non-experimental for out of tree controllers

2022-04-25 16:30 UTC, cvinayak submitted a review, later dismissed

2022-04-28 05:48 UTC, ppryga requested changes
One minor comment, otherwise LGTM

2022-04-28 05:48 UTC, ppryga commented on subsys/bluetooth/controller/Kconfig.df
> +	depends on !BT_CTLR_TIFS_HW
`BT_CTLR_DF_SUPPORT` is used as a supported features set for Zephyr LL only. It is just a convenience wrapper. I suggest to move select part: https://github.com/zephyrproject-rtos/zephyr/pull/45022/files#diff-e9984b2a061624f67ff5705bc3295a77b97df2b1c5b4452dc706a3177bd710c1R11-R15 here and remove first definition.

2022-04-28 07:25 UTC, ppryga submitted a review, later dismissed

2022-04-28 07:29 UTC, cvinayak approved these changes, later dismissed

2022-04-28 09:08 UTC, cvinayak submitted a review, later dismissed

2022-04-29 09:12 UTC, ppryga requested changes
I prefer to have `!BT_CTLR_TIFS_HW` dependency in the `BT_CTRL_DF_SUPPORT` config. Currently it is true for all Nordic platforms that support Direction Finding, hence in my humble opinion it is better to have it inside the option.

2022-04-29 09:12 UTC, ppryga commented on subsys/bluetooth/controller/Kconfig.df
> -	depends on !BT_CTLR_TIFS_HW
Instead of remove the line please use this: `depends on BT_LL_SW_SPLIT && !BT_CTLR_TIFS_HW`

2022-04-29 09:12 UTC, ppryga commented on subsys/bluetooth/controller/Kconfig.ll_sw_split
> +	select BT_CTLR_DF_SUPPORT if HAS_HW_NRF_RADIO_DFE && !BT_CTLR_TIFS_HW
```suggestion
	select BT_CTLR_DF_SUPPORT if HAS_HW_NRF_RADIO_DFE
```

2022-05-05 11:10 UTC, ppryga approved these changes

2022-05-05 11:15 UTC, cvinayak approved these changes

2022-05-05 19:39 UTC, merged