drivers: dma buffers memory location specified in devicetree
zephyrproject-rtos/zephyr pull request #45128
Opened 2022-04-26 08:05 UTC by awojasinski-nordicsemi

This PR introduces new binding for all Nordic peripherals that use EasyDMA. `dma-buffers-memory-region` is a property that allows a developer to specify the memory section where buffers passed to EasyDMA will be placed. This property requires reference to the node with compatible `zephyr,memory-region`. If `dma-buffers-memory-region` is not specified, buffers are placed in the default location.

It is the developer's responsibility to check whether the specified in the node, memory region is accessible by EasyDMA.

As an example, SPIM and UARTE shims were aligned to utilize the new feature.

2022-04-26 08:18 UTC, anangl commented
cc @nika-nordic @masz-nordic

2022-04-26 09:03 UTC, carlocaione requested changes

2022-04-26 12:18 UTC, carlocaione commented on dts/bindings/audio/nordic,nrf-pdm.yaml
> +        Phandle have to refer to node with zephyr,memory-region compatible.
On a second thought I think the best way is to add a more general `memory-region` property to `base.yaml` and use that instead (the property name is taken from Linux). @awojasinski-nordicsemi to be done in a separate PR though.

2022-04-28 07:35 UTC, JordanYates commented
What is the purpose here, given that all RAM is accessible by EasyDMA?

2022-04-28 07:53 UTC, awojasinski-nordicsemi commented
> What is the purpose here, given that all RAM is accessible by EasyDMA?

@JordanYates You may want to have a special partition or shared memory region where you want to place buffers passed to EasyDMA. This mechanism gives the programmer control over the location of buffers

2022-04-28 12:09 UTC, JordanYates commented
> > What is the purpose here, given that all RAM is accessible by EasyDMA?
> 
> @JordanYates You may want to have a special partition or shared memory region where you want to place buffers passed to EasyDMA. This mechanism gives the programmer control over the location of buffers

I understand that's what this does, but why is that useful?
Especially given this has no impact on where the data transmitted with the UART async API or 99% of SPI data comes from.

2022-04-28 13:15 UTC, awojasinski-nordicsemi commented
> > > What is the purpose here, given that all RAM is accessible by EasyDMA?
> > 
> > 
> > @JordanYates You may want to have a special partition or shared memory region where you want to place buffers passed to EasyDMA. This mechanism gives the programmer control over the location of buffers
> 
> I understand that's what this does, but why is that useful? Especially given this has no impact on where the data transmitted with the UART async API or 99% of SPI data comes from.

There were some cases in the past where EasyDMA didn't have access to some memory regions so it is worth having some easy-to-use mechanism that can apply a workaround. The following errata occurred in I2S but I wanted to begin with the uarte and spim shims.

https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF52840_EngA%2FERR%2FnRF52840%2FEngineeringA%2Flatest%2Fanomaly_840_96.html&cp=4_0_1_6_1_14

2022-06-03 14:17 UTC, awojasinski-nordicsemi commented
Closing this PR. https://github.com/zephyrproject-rtos/zephyr/pull/45142 contains all needed changes.

2022-06-03 14:17 UTC, closed without merging