boards: arm: rpi_pico: add openocd runner configuration
zephyrproject-rtos/zephyr pull request #45137
Opened 2022-04-26 10:51 UTC by soburi

Add openocd configuration.

This configuration allows selecting what debug adapter debugging rpi_pico
by a command-line argument.
It is mainly intended to support both the 'picoprobe' and 'raspberrypi-swd'
adapter described in "Getting started with Raspberry Pi Pico".
And any other SWD debug adapter might also be usable with this configuration.

2022-07-05 13:19 UTC, yonsch reviewed
Looking good overall, I have just one question:
Does this work with the openocd found in zephyr-sdk, or does it use a custom version of openocd? I couldn't find `target/rp2040.cfg` (though I did find `rp2040-core0.cfg`), and neither `interface/picoprobe`/`interface/raspberrypi-swd`.

2022-07-05 13:54 UTC, soburi commented
Hi! @yonsch 
Thanks for reviewing.

> Looking good overall, I have just one question: Does this work with the openocd found in zephyr-sdk, or does it use a custom version of openocd? I couldn't find `target/rp2040.cfg` (though I did find `rp2040-core0.cfg`), and neither `interface/picoprobe`/`interface/raspberrypi-swd`.

It requires a custom version openocd.

I missed writing information about the distribution source of the custom version.
(https://github.com/raspberrypi/openocd)
I will add some information about that version.

There is an easy way to use this version of openocd is running the setup.sh script for setting up the pico development environment. I wrote it in the document.

2022-07-06 17:22 UTC, burumaj commented
I tested this yesterday evening with the picoprobe. There are couple remarks I have regarding the documentation of this:

1) when using the picoprobe adding a `udev` rule might be necessary so a regular user can use it with openocd (or at least a user that is in de plugdev group in this case).
```
# Raspberry Pi Picoprobe
ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0004", MODE="660", GROUP="plugdev", TAG+="uaccess"
```
2) When using an openocd not included with the zephyr sdk there is not rtos support for zephyr. The consequence of this is that it's possible to use openocd to debug an application, but only without thread awareness.

3) You mention the use of `picosetup.sh`, this script and is only supported on piOS, and probably works fine on debian based systems like ubuntu.

2022-07-08 00:19 UTC, soburi commented
Hi, @burumaj 

> I tested this yesterday evening with the picoprobe. There are couple remarks I have regarding the documentation of this:

Thanks for testing it and comments.
I updated the document with apply your mentions.

2022-07-08 13:05 UTC, yonsch requested changes
Thanks, a few comments about the documentation.

2022-07-08 15:11 UTC, soburi commented on boards/arm/rpi_pico/doc/index.rst
> +
Fix it

2022-07-08 15:11 UTC, soburi commented on boards/arm/rpi_pico/doc/index.rst
>  This fork can be found here: https://github.com/raspberrypi/openocd
I removed this line.

2022-07-08 15:14 UTC, soburi commented on boards/arm/rpi_pico/doc/index.rst
> +install openocd as described for flashing the board.
I wrote on "Flashing" section previous push, but "Debugging" section is more suitable.
Move it to here.

2022-07-13 06:39 UTC, MeisterBob commented
I would suggest adding jlink support to board.cmake as well

```
board_runner_args(jlink "--device=RP2040_M0_0")
include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
```

2022-07-15 02:08 UTC, soburi commented
Hi, @MeisterBob 

Thanks for comment.

> I would suggest adding jlink support to board.cmake as well
> 
> ```
> board_runner_args(jlink "--device=RP2040_M0_0")
> include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
> ```

It seems good.
And this code is your contribution.
So, I think it is better to create your PR.
(In another view, it keeps simple PR.)

Please consider it.

2022-07-22 22:33 UTC, soburi commented
@MeisterBob ,
I split the topic about J-Link support to new issue.
https://github.com/zephyrproject-rtos/zephyr/issues/48194

(Simply reason, I can't verify the code within this PR becasuse I don't have J-Link debugger...)

2022-08-02 05:46 UTC, yonsch approved these changes

2022-08-18 10:22 UTC, carlescufi approved these changes

2022-08-18 10:22 UTC, merged