Add missing SPI_DT_SPEC_INST_GET for reset gpio, if existing in devic…
zephyrproject-rtos/zephyr pull request #45144
Opened 2022-04-26 13:01 UTC by gadrou

…e tree.

It seems to me that the lora functions cannot be executed correctly without initializing the reset pin for the SX1272 and SX1276.
Tested on a dedicated board integrating a SX1272.

Signed-off-by: Adrien Rouault <adrien.rouault@nemeus.fr>

2022-04-27 10:02 UTC, JordanYates requested changes
Please have a look at the format of other commit messages and follow their formatting.
The current commit message also does not match what is actually done in the commit.

2022-04-27 10:02 UTC, JordanYates commented on drivers/lora/sx127x.c
> +#if DT_INST_NODE_HAS_PROP(0, reset_gpios)
Same here, the property needs to exist so the `#if` guard is not necessary

2022-04-27 11:53 UTC, JordanYates commented
Please have a read through https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines
Each commit should contain one logical change, and not fix up problems from other commits in the PR.
In general, when addressing feedback you should be modifying existing commits, not creating new ones.

Specifically for this PR, you should squash all 3 commits down to 1, update the commit message, and force push to your branch.

2022-04-27 23:04 UTC, JordanYates commented
Almost there, you just need to rebase your branch on top of the latest `main` to get rid of the out-of-date warning

2022-04-29 10:03 UTC, JordanYates approved these changes

2022-04-29 10:14 UTC, erwango approved these changes

2022-04-29 10:33 UTC, carlescufi commented
@Mani-Sadhasivam could you please take a look?

2022-04-29 11:16 UTC, Mani-Sadhasivam approved these changes

2022-04-29 11:16 UTC, Mani-Sadhasivam commented
@carlescufi you can merge now!

2022-04-29 13:30 UTC, merged

2022-04-29 13:30 UTC, carlescufi commented
> @carlescufi you can merge now!

Thanks!