soc/xtensa/intel_adsp/tools: Make cavstwist.sh accept ssh port
zephyrproject-rtos/zephyr pull request #45154
Opened 2022-04-26 23:32 UTC by edersondisouza

Sometimes the remote ssh server is not on default port. This patch makes
cavstwist.sh accept an ssh port in the host address: host[:port].

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

2022-04-27 12:40 UTC, MaureenHelm submitted a review, later dismissed

2022-04-27 14:14 UTC, andyross submitted a review, later dismissed

2022-04-27 19:21 UTC, marc-hb requested changes

2022-04-27 19:21 UTC, marc-hb commented on soc/xtensa/intel_adsp/tools/cavstwist.sh
> +CAVS_PORT=${CAVS_HOST##[A-Za-z0-9@.]*:}
This is a bit too restrictive and not IPv6-proof (fails with `[1:2::3:4]:678`). While there are Unix restrictions on hostnames, DNS actually supports unicode and what not and who knows what people could use in their username before @.

Strip the optional port number _first_ with `CAVS_HOST=${CAVS_HOST_PORT%:[0-9]*}`. If `CAVS_HOST != CAVS_HOST_PORT` then there is a port number, extract it with `CAVS_PORT=${CAVS_HOST_PORT#${CAVS_HOST}:}`

This still does not support IPv6 + port but it gets _much_ closer and it does not make any hostname assumption. 

PS: https://bugzilla.mindrot.org/show_bug.cgi?id=1602 - 13 years old ssh bug.

2022-04-27 20:01 UTC, edersondisouza commented
v2: Match shortest substring when spliting hostname and port.

2022-04-27 20:33 UTC, marc-hb submitted a review, later dismissed
Thanks!

2022-04-28 16:04 UTC, edersondisouza commented on soc/xtensa/intel_adsp/tools/cavstwist.sh
> +    exec ssh $CAVS_PORT_SSH $CAVS_HOST "sudo ./$(basename $CAVSTOOL) $(basename $IMAGE2)"
Oh, that's neat! Will update, thanks!

2022-04-28 17:48 UTC, marc-hb approved these changes

2022-04-28 17:49 UTC, marc-hb commented on soc/xtensa/intel_adsp/tools/cavstwist.sh
> +    ssh ssh://$CAVS_HOST "sudo pkill -9 -f cavstool" ||:
I find this slightly more readable but it's off-topic
```suggestion
    ssh ssh://$CAVS_HOST "sudo pkill -9 -f cavstool" || true
```

2022-05-05 20:40 UTC, ceolin approved these changes

2022-05-05 21:00 UTC, merged