Bluetooth: lc3: Improve BT_CODEC_LC3_CHAN_COUNT_SUPPORT macro
zephyrproject-rtos/zephyr pull request #45373
Opened 2022-05-05 09:28 UTC by MariuszSkamra

This improves the macro so that it can take variable number of arguments, e.g. BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 2, 8).

2022-05-05 09:34 UTC, Thalley commented
What is the advantage of doing `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 3, 7)` compared to 
`BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(3) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(7)`?

Shorter lines of code?

2022-05-05 09:46 UTC, MariuszSkamra commented
> What is the advantage of doing `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 3, 7)` compared to `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(3) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(7)`?
> 
> Shorter lines of code?

Yes :D

2022-05-05 10:30 UTC, Thalley commented
> > What is the advantage of doing `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 3, 7)` compared to `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(3) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(7)`?
> > Shorter lines of code?
> 
> Yes :D

What do you think about the proposal in https://github.com/zephyrproject-rtos/zephyr/pull/45373#issuecomment-1118360118? 

While the variable-argument approach using the fixed size macros probably works, it's not particularly readable and easy to understand from a user's perspective if they investigate the macro.

2022-05-05 11:30 UTC, MariuszSkamra commented
> > > What is the advantage of doing `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 3, 7)` compared to `BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(3) | BT_CODEC_LC3_CHAN_COUNT_SUPPORT(7)`?
> > > Shorter lines of code?
> > 
> > 
> > Yes :D
> 
> What do you think about the proposal in [#45373 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/45373#issuecomment-1118360118)?
> 
> While the variable-argument approach using the fixed size macros probably works, it's not particularly readable and easy to understand from a user's perspective if they investigate the macro.

You have right, it was not a bit ugly solution. Please check the latest PR

2022-05-05 12:08 UTC, Thalley requested changes
New solution is much cleaner, thanks! 

Added a few requests

2022-05-05 12:08 UTC, Thalley commented on include/zephyr/bluetooth/audio/lc3.h
> + *  @ref BT_CODEC_LC3_CHAN_COUNT_MIN to @ref BT_CODEC_LC3_CHAN_COUNT_MAX.
```suggestion
 *  @ref BT_CODEC_LC3_CHAN_COUNT_MIN to @ref BT_CODEC_LC3_CHAN_COUNT_MAX inclusive.
```

2022-05-05 12:08 UTC, Thalley commented on include/zephyr/bluetooth/audio/lc3.h
> +#define BT_CODEC_LC3_CHAN_COUNT_SUPPORT(...) ((uint8_t)((FOR_EACH(BIT, (|), __VA_ARGS__)) >> 1))
Can you also provide an example here, like it had before? 
e.g.

```c
 * Example to support 1 and 3 channels:
 *  BT_CODEC_LC3_CHAN_COUNT_SUPPORT(1, 3)
```

2022-05-05 12:53 UTC, Thalley submitted a review, later dismissed

2022-06-07 09:57 UTC, Thalley approved these changes

2022-06-07 10:12 UTC, sjanc approved these changes

2022-06-08 10:45 UTC, merged