Issue/45390 enable mingw build
zephyrproject-rtos/zephyr pull request #45392
Opened 2022-05-05 15:43 UTC by lescopc

Fix issue#45390

2022-05-05 15:59 UTC, stephanosio requested changes
Please review the [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html).

2022-05-05 15:59 UTC, stephanosio commented on cmake/toolchain/gnuarmemb/generic.cmake
> +set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
see https://github.com/zephyrproject-rtos/zephyr/pull/45386#discussion_r866025396

2022-05-05 15:59 UTC, stephanosio commented on cmake/compiler/gcc/target.cmake
> +  string(REGEX REPLACE "^(.):(.)" "\\2\\1\\2" _OUTPUT "${_OUTPUT}")
should define a general function to handle this, since there is likely going to be more places that require this (now and in the future as well).

2024-03-02 23:47 UTC, Kreijstal commented
@lescopc you still working on this?

2024-03-04 03:26 UTC, stephanosio commented
This PR is almost two years old at this point. Closing.

2024-03-04 03:26 UTC, closed without merging

2024-03-05 08:57 UTC, lescopc commented
Yes, it is working now.
Just a little patch but I dont think it is necessary

Le dim. 3 mars 2024, 00:47, Kreijstal ***@***.***> a écrit :

> @lescopc <https://github.com/lescopc> you still working on this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zephyrproject-rtos/zephyr/pull/45392#issuecomment-1974944446>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUXMRDI5D44RCEG6YP5WPB3YWJQKBAVCNFSM5VFPRD32U5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOJXGQ4TINBUGQ3A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-05 09:11 UTC, Kreijstal commented
for msys path correction you can use MSYS2_ARG_CONV_EXCL, also maybe you can submit your patch to msys2/mingw_packages

2024-03-06 13:33 UTC, lescopc commented
Just for people who may come across this PR:
You need to have a clean MSYS2 environment and do **not** mix MSYS2/**MSYS** MSYS2/**MinGW** applications.
- **MSYS** applications are cygwin' ones -> Unix PATH (impacted by MSYS2_ARG_CONV_EXCL -> PATH conversion)
- **MinGW** applications are Windows' ones -> Windows PATH

I used Git-bash environment which is based on MSYS2/**MinGW** and all applications built for it (like GCC coming from ARM website [arm-gnu-toolchain-13.2.rel1-mingw-w64-i686-arm-none-eabi.exe](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads)). Also, make sure to use Python and ninja (or mingw-make if you prefer) built for MinGW.

Once your environment is clean, everything work out-of-the-box except for 
#> ninja menuconfig
The 'cbreak()' in ncurses will fail in MinGW so you have 2 workarounds:
1. either use 'ninja guiconfig'. (this one is not based on ncurses and works fine)
2. or call ninja in cmd.exe environment