kernel: include: Change the included header file in sw_isr_table.h.
zephyrproject-rtos/zephyr pull request #4542
Opened 2017-10-25 08:20 UTC by AdithyaBaglody

Changing the included header from arch/cpu.h to kernel.h.
Currently the build will take up the arch specific header file.
So for example consider the include sequence, first arch/cpu.h
then arch.h and so on until all the required files are included. But in
the course of this sequence there may be a chance that the kernel.h gets
included. But the kernel.h needs arch/cpu.h. This arch/cpu.h file
will not get included due to the header file guard macros.
Thus a compilation with the kernel.h will result in a build failure.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

2017-10-25 10:04 UTC, ramakrishnapallala approved these changes

2017-10-25 12:21 UTC, galak commented
Do you have a case that things fail, confused what it is that we need kernel.h instead of arch/cpu.h

2017-10-25 16:25 UTC, AdithyaBaglody commented
In file included from /home/adithya/zephyr/zephyr2/include/sys_io.h:16:0,
                 from /home/adithya/zephyr/zephyr2/include/arch/arm/cortex_m/sys_io.h:16,
                 from /home/adithya/zephyr/zephyr2/include/arch/arm/arch.h:42,
                 from /home/adithya/zephyr/zephyr2/include/arch/cpu.h:15,
                 from /home/adithya/zephyr/zephyr2/include/sw_isr_table.h:17,
                 from /home/adithya/zephyr/zephyr2/arch/common/isr_tables.c:9:
/home/adithya/zephyr/zephyr2/include/kernel.h:4233:2: error: unknown type name ‘k_mem_partition_attr_t’
  k_mem_partition_attr_t attr;

This is a new typedef that will be created in arch.h for arm. From the PR #4482 .
In this the includes will start from the cpu.h and then go till sys_io.h at which point the it will include the kernel.h.. Inside the kernel.h we need to include arch/cpu.h and because of the guard macros it will not allow the expansion of the cpu.h file again inside kernel.h.
So to overcome this issue I just included kernel.h at the beginning of this include sequence.

2017-10-25 17:39 UTC, tyrantlizard77 approved these changes

2017-10-25 22:07 UTC, tyrantlizard77 requested changes
Actually, this header doesn't seem to depend on arch/cpu.h for anything in it unless I'm missing something.

Have you tried just deleting this #include instance? Maybe there was a time when this header needed something from arch/cpu.h, but I'm not seeing it now.

If there is C code pulling in this header which relies on these other headers being included implicitly, just fix the C code.

2017-10-26 05:03 UTC, AdithyaBaglody commented
Andrew this is a weird problem which occurs in the build for arch/common/isr_table.c.
I tried deleting the header file inclusion but the file still needs some of the arch specific code. Such as  "_irq_spurious" ; all these would be included from the cpu.h file. So I realized that the best option is to include a superset header which is kernel.h

2017-10-26 16:57 UTC, tyrantlizard77 requested changes
> Andrew this is a weird problem which occurs in the build for arch/common/isr_table.c.
I tried deleting the header file inclusion but the file still needs some of the arch specific code. Such as "_irq_spurious" ; all these would be included from the cpu.h file. So I realized that the best option is to include a superset header which is kernel.h

NACK

The best option is to have isr_table.c include the actual headers that it needs.

2017-10-27 06:28 UTC, AdithyaBaglody commented
I don't understand Andrew. isr_table.c requires arch/cpu.h that is **required**. But such an inclusion causes build failures so I suggested kernel.h to overcome this.
How should I overcome this weird situation?? because I am not able to see it.

2017-10-27 18:28 UTC, andrewboie commented
> I don't understand Andrew. isr_table.c requires arch/cpu.h that is required. But such an inclusion causes build failures so I suggested kernel.h to overcome this.
How should I overcome this weird situation?? because I am not able to see it.

I wasn't talking about isr_table.c. Remove the #include from sw_isr_table.h. isr_table.c pulls in arch/cpu.h on its own.

Like this: #4613 

In general, header files must only include those headers that header needs itself.

2017-10-30 05:01 UTC, AdithyaBaglody commented
Andrew, the crux of the issue here is that the include sequence is wrong. Be it in the isr_table.c or in sw_isr_table.h.
The include sequence I mentioned above will occur even if we remove arch/cpu.h from sw_isr_table.h.

2017-10-31 10:42 UTC, AdithyaBaglody commented
Delta: 
1. added the libc-hooks.c into this PR. Facing the same issue in that .
2. rebased

2017-10-31 16:18 UTC, andrewboie commented
Can you please merge this PR with the memory domain one so we can demonstrate 1) what the problem is and 2) that the patch passes CI with this patch?

If we have a real problem here I don't see this is being the best fix.

2017-11-01 18:01 UTC, andrewboie commented
This patch isn't a root-cause fix, any C file that includes <arch/cpu.h> is going to have this problem.
Please look at #4676  and #4675

2017-11-02 06:03 UTC, AdithyaBaglody commented
Actually Andrew the root cause fix might touch a lot of files. I wasn't sure of the impact it might cause. 
The issues keep coming one after another if I try to remove unnecessary headers. Hence I decided that this is the least risky option available.

2017-11-03 06:44 UTC, AdithyaBaglody commented
Closing because of #4675 . Fixes the header file issues.

2017-11-03 06:44 UTC, closed without merging