Fix typos
zephyrproject-rtos/zephyr pull request #45467
Opened 2022-05-07 23:08 UTC by rettichschnidi

Comments only, no functional changes.

2022-05-09 20:27 UTC, henrikbrixandersen requested changes
Changes looks fine, but you need to get rid of the merge commit (use rebase instead).

2022-05-10 14:14 UTC, MaureenHelm approved these changes

2022-05-13 17:33 UTC, mbolivar-nordic approved these changes

2022-05-18 04:43 UTC, henrikbrixandersen approved these changes

2022-05-18 08:55 UTC, merged