samples: drivers: spi_flash rename definitions
zephyrproject-rtos/zephyr pull request #45487
Opened 2022-05-09 12:56 UTC by FRASTM

This commits prefixes all the definitions
with SPI_  to be used by the sample application _samples/drivers/spi_flash_ 

In that spi_flash sample, the #define are identified with SPI_FLASH_xxx and this will avoid conflicts with other `FLASH_SECTOR_SIZE` used by any driver or hal elsewhere.
Typically stm32h7b3xx define FLASH_SECTOR_SIZE for itself.

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-06-20 08:29 UTC, FRASTM commented
rebase, fix merge conflct

2022-06-20 12:23 UTC, erwango approved these changes, later dismissed

2022-06-28 15:41 UTC, ABOSTM requested changes

2022-06-28 15:53 UTC, FRASTM commented on samples/drivers/spi_flash/src/main.c
> +	rc = flash_erase(flash_dev, SPI_FLASH_TEST_REGION_OFFSET,
done

2022-06-28 15:53 UTC, FRASTM commented
rebase
update comment

2022-06-28 15:55 UTC, ABOSTM approved these changes
LGTM

2022-06-29 07:25 UTC, erwango approved these changes

2022-06-29 08:25 UTC, merged