Bluetooth: Mesh: Fix segmentation when sending proxy message
zephyrproject-rtos/zephyr pull request #45551
Opened 2022-05-11 10:56 UTC by PavelVPV

Previous check in the if-statement would never allow to send last
segment if msg->len + 2 == MTU * x.

Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>

2022-05-11 10:57 UTC, PavelVPV commented
This fixes https://github.com/zephyrproject-rtos/zephyr/issues/45394.

2022-05-11 13:23 UTC, Andrewpini approved these changes, later dismissed
I've read the bug ticket, and the explination makes sence. I guess as long as the header is one byte in size this will work, since `if (mtu > msg->len)` guarantees that there is atleast one free byte in the buffer.

2022-05-11 14:04 UTC, jhedberg requested changes

2022-05-11 15:23 UTC, Balaklaka submitted a review, later dismissed

2022-05-12 10:15 UTC, jhedberg approved these changes

2022-05-12 10:17 UTC, LingaoM approved these changes

2022-05-12 13:45 UTC, alxelax approved these changes

2022-05-13 12:45 UTC, merged