HCI reset synchronization
zephyrproject-rtos/zephyr pull request #45585
Opened 2022-05-12 11:08 UTC by mtpr-ot

Bluetooth: controller: Prevent HCI reset race with RX thread
----------
When an HCI reset is issued, the HCI RX thread may be in the middle of
processing RX nodes. Normally this is not a problems as the RX/TX
cooperative threads are exclusive. However, if the RX thread yields via
a kernel functions like waiting for a semaphore or netbuffer, the RX
thread may have unfinished business when the reset is executed.
This means that when reset is done, the processing continues, and may
operate on invalidated data.

To prevent this, a new "processing" semaphore is introduced in the RX
thread. Before starting node processing, the semaphore is taken, and
given when processing is done.
The HCI reset function also takes this semahore, thereby preventing
reset starting in the middle of node processing. Whenever the RX thread
takes the semaphore, it checks for reset signal to see if a reset
happened while waiting. In this case the node is discarded.

Bluetooth: controller: Signal HCI reset to recv thread
----------
Synchronize HCI reset with receive thread to prevent processing of
dangling RX nodes.

2022-06-07 09:42 UTC, cvinayak requested changes
With changes in this PR, HCI Reset issued by EBQ did not return command response (IUT is hung, not able to remote debug hence have no further information as to why it is hung)

2022-06-21 08:15 UTC, mtpr-ot commented
Re-triggering CI.

2022-06-23 08:45 UTC, cvinayak commented
> I got an action to run a simulation test to see the problem reported by @cvinayak. However, what kind of test would that be, which is not already run in CI?

I believe none of the Babblesim CI tests that involve host have the `CONFIG_BT_HCI_RAW` and do not use `BT_HCI_RESET_SIGNAL` set and hence not exercising the changes in this PR, correct me...

My change requested in this PR is only based on testing a build with the two commits added to upstream hci_uart sample and running through the conformance tester which hangs on the first HCI Reset Command being sent to IUT. I have not investigated or debugged as the setup is remote with no possibility to attach a debugger to the running target to get a back trace.

2022-06-23 10:37 UTC, mtpr-ot commented
> I believe none of the Babblesim CI tests that involve host have the `CONFIG_BT_HCI_RAW`

Right, forgot about that difference. One thing though; did you solve conflicts when taking in the commits? I noticed that the first commits I pushed were difficult to merge, and left in a merge error in my first attempt. Any chance you could try with the rebased version in the PR now?

2022-08-16 10:52 UTC, mtpr-ot commented
Closing this PR as another somewhat similar solution was merged. Will monitor if that solution solves our problem.

2022-08-16 10:52 UTC, closed without merging