net: buf: keep memory alignment provided by k_heap_alloc and k_malloc
zephyrproject-rtos/zephyr pull request #45689
Opened 2022-05-16 13:17 UTC by jfischer-no

Allocation callback in net_buf_heap_cb and net_buf_var_cb
used for net_bufs with variable size payloads, defined by
NET_BUF_POOL_HEAP_DEFINE or NET_BUF_POOL_VAR_DEFINE,
allocate one more octet for internal variable ref_count,
used in function generic_data_ref(), which in turn is needed
for net_buf_clone()).
The user gets a buffer which is shifted by one octet in memory
block. This breaks alignment provided k_heap_alloc and k_malloc.

2022-05-16 19:49 UTC, jhedberg commented
I’m not really opposed to this, curious to hear where you benefit from it considering that in almost all cases the buffer payload is some protocol data that’s not assumed to be properly aligned, ie we access it using packed structs or using the various net buf data getter functions that don’t assume any specific alignment for the payload.

2022-05-17 08:11 UTC, jfischer-no commented
> I’m not really opposed to this, curious to hear where you benefit from it considering that in almost all cases the buffer payload is some protocol data that’s not assumed to be properly aligned

I use it in USB device controller API, some controllers allow to use data for transfers directly from RAM without storing it in specific area or FIFO, but data block must be aligned. IMHO it is a kind of bug because it does not keep the alignment provided by k_heap what one could assume. As I see fixed size pools can not provide aligned buffers as well. I could possibly solve it differently by definition of own callbacks and NET_BUF_POOL_UDC_DEFINE macro.

2022-05-18 12:28 UTC, carlescufi requested changes
Please update the documentation for `k_heap_alloc` stating that it aligns the memory to `void *`.

2022-11-22 10:09 UTC, carlescufi approved these changes

2022-11-23 10:46 UTC, carlescufi commented
@rlubos @jhedberg @tbursztyka could you please review?

2022-11-23 10:53 UTC, jhedberg approved these changes

2022-11-23 10:58 UTC, rlubos approved these changes

2022-11-23 11:18 UTC, desowin approved these changes

2022-11-24 08:35 UTC, merged

2023-05-26 05:18 UTC, M1cha commented
Am I right in that this messes up `generic_data_ref`? That one still uses `1` insead of `sizeof(void*)`:
```c
ref_count = data - 1;
```

If true, ref and unref would use different memory locations. I'm not sure how that would not be caught by unit and manual tests though since it would cause memory leaks all over the place.

2023-05-28 15:01 UTC, jhedberg commented
@jfischer-no could you respond to the comment from @M1cha above? Is there some place in the code that you forgot to update?

2023-05-31 12:16 UTC, jfischer-no commented
> Am I right in that this messes up `generic_data_ref`? That one still uses `1` insead of `sizeof(void*)`:
> 
> ```c
> ref_count = data - 1;
> ```
> 
> If true, ref and unref would use different memory locations. I'm not sure how that would not be caught by unit and manual tests though since it would cause issues all over the place.

It looks like I screwed up on this one, cloned net_buf data would point to a data block that has already been freed:

https://github.com/zephyrproject-rtos/zephyr/blob/fa5b706871f01bb3bba3b2d9f774d27615855e7e/subsys/net/buf.c#L96-L103

There are net_buf reference count (member ref of struct net_buf) and data reference count at the top of allocated data. This PR is about data reference count.
Probably no one caught it because it is only used for NET_BUF_POOL_VAR_DEFINE() and  NET_BUF_POOL_HEAP_DEFINE() to increase the data reference count in `net_buf_clone()`. NET_BUF_POOL_HEAP_DEFINE is not used in the tree. 

test_net_buf_clone() would not catch it, @jhedberg any ideas other than the one-line fix below?

```diff
diff --git a/subsys/net/buf.c b/subsys/net/buf.c
index dc6f5dc8e0d..462a21198e2 100644
--- a/subsys/net/buf.c
+++ b/subsys/net/buf.c
@@ -93,7 +93,7 @@ static uint8_t *generic_data_ref(struct net_buf *buf, uint8_t *data)
 {
        uint8_t *ref_count;
 
-       ref_count = data - 1;
+       ref_count = data - sizeof(void *);
        (*ref_count)++;
 
        return data;
```