shell: suppress newlines on boot when promt is an empty string
zephyrproject-rtos/zephyr pull request #45766
Opened 2022-05-18 13:02 UTC by MeisterBob

If the user sets the default_prompt to an empty string no newlines will be printed during boot.

2022-05-18 15:39 UTC, stephanosio requested changes, later dismissed

2022-05-18 16:00 UTC, jakub-uC requested changes
Please use `z_shell_strlen` instead of `strlen` because the latter does not check `NULL`.

In addition please update the documentation with this information:
doc/services/shell/index.rst

2022-05-19 07:21 UTC, MeisterBob commented
added braces and using `z_shell_strlen` instead of `strlen`

2022-05-19 07:34 UTC, jakub-uC commented
@MeisterBob 
I think it will be enough to write a sentence in the help here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/backends/Kconfig.backends#L36
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/backends/Kconfig.backends#L132
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/backends/Kconfig.backends#L295
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/backends/Kconfig.backends#L389

That if the prompt is not set then the shell will not send two newline characters during initialization.

Apart from that `LGTM`.

2022-05-19 07:51 UTC, MeisterBob commented
and added a few words to the documentation.

2022-05-19 07:53 UTC, jakub-uC approved these changes

2022-05-19 07:56 UTC, nordic-krch approved these changes

2022-06-05 12:42 UTC, merged