net: lwm2m: replace coap_next_block() w/ coap_update_from_block()
zephyrproject-rtos/zephyr pull request #4577
Opened 2017-10-27 03:27 UTC by rbtchc

We should call coap_update_from_block() which will determine the minimum
size of the BLOCK1 SIZE between server/client and update the current
offset and total size(if available) accordingly.

This PR shouldn't be conflict w/ #4557

2017-10-27 05:25 UTC, mike-scott commented
@rbtchc This looks good, but I had to do quite a bit of work to my backend changes forhttps://github.com/zephyrproject-rtos/zephyr/pull/4557.  Can we hold this till after that's merged.  I touched some of this code.

2017-10-27 05:31 UTC, rbtchc commented
@mike-scott no problem. let's wait.

2017-10-27 06:16 UTC, mike-scott requested changes
Holding for now.

2017-11-01 06:19 UTC, rbtchc commented
Rebase on top of the master branch which has  #4557 merged now.
@mike-scott plz let me know if you have any problem w/ it.

2017-11-02 04:55 UTC, mike-scott commented
LGTM.  Have you run tests to confirm that block size negotiation is working correctly?

2017-11-02 04:56 UTC, mike-scott approved these changes

2017-11-02 06:01 UTC, rbtchc commented
@mike-scott Yes, I did. It will now use the minimum block_size between server/client. Originally, it will use whatever we set to "CONFIG_LWM2M_COAP_BLOCK_SIZE"

2017-11-02 08:02 UTC, merged