Bluetooth: controller: Controller to Host flow control
zephyrproject-rtos/zephyr pull request #46
Opened 2017-05-02 10:03 UTC by carlescufi

The Bluetooth Specification allows for optional Controller to Host flow
control based on the same credit-based mechanism as the Host to
Controller one. This is particularly useful in 2-chip solutions where
the Host and the Controller are connected via a physical link (UART, SPI
or similar) where the Host is sometimes required to ask the Controller
to throttle its data traffic while still making sure that relevant
events get through the line.

This implementation is based on a simple queue of pending events and
data that is populated whenever the Controller detects that the Host is
out of buffers and then emptied whenever the Host notifies the
Controller that is ready to receive data again. Events relevant to the
connections are also queued to preserve the order of arrival.

At this point the Controller ignores the connection handle sent by the
Host and treats all connections equally, and it also queues events even
for connections that have no data pending in the queue. Both this items
can be improved if necessity arises.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2017-05-02 10:09 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +
Redundant empty line here

2017-05-02 10:09 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +printk("reset signal\n");
This doesn't seem to be correctly indented - also shouldn't you be using BT_DBG?

2017-05-02 10:10 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +	switch(cmd->flow_enable) {
Missing space after 'switch'

2017-05-02 10:11 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +printk("host num signal\n");
Incorrect indentation, and I suppose this should bt BT_DBG

2017-05-02 10:14 UTC, jhedberg commented on subsys/bluetooth/controller/Kconfig
> +	default y
Don't we also want 'default n if BLUETOOTH_HCI_HOST'? Since AFAIK combined builds don't have any advantage of this?

2017-05-02 10:15 UTC, carlescufi commented on subsys/bluetooth/controller/Kconfig
> +	default y
This should actually be default n, I will fix

2017-05-02 10:17 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +	case BT_HCI_CTL_TO_HOST_FLOW_ENABLE:
How come you don't treat enable and disable differently?

2017-05-02 10:30 UTC, carlescufi commented on subsys/bluetooth/controller/hci/hci.c
> +	case BT_HCI_CTL_TO_HOST_FLOW_ENABLE:
I just apply a negative so that the signed integer switches sign

2017-05-02 11:32 UTC, jhedberg commented
Looks quite good now

2017-05-02 11:32 UTC, jhedberg submitted a review, later dismissed

2017-05-02 12:57 UTC, cvinayak requested changes

2017-05-02 12:57 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +		hci_hbuf_total = -hci_hbuf_total;
What if enable is called twice?

2017-05-02 13:03 UTC, cvinayak requested changes

2017-05-02 13:03 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +			LL_ASSERT((hci_hbuf_sent - hci_hbuf_acked) <=
shouldn't this be just "<"

2017-05-02 13:04 UTC, carlescufi commented on subsys/bluetooth/controller/hci/hci.c
> +		hci_hbuf_total = -hci_hbuf_total;
There's tons of missing checks like those all over HCI, I have a Jira task to add parameter checking, which would include things like this

2017-05-02 13:27 UTC, cvinayak requested changes

2017-05-02 13:27 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +		hci_hbuf_total = -hci_hbuf_total;
That is ok. @jhedberg and myself has expressed concern on the toggle here. I still feel, the enable and disable should be explicit.

2017-05-03 18:20 UTC, cvinayak approved these changes

2017-05-03 19:23 UTC, jhedberg approved these changes

2017-05-03 19:23 UTC, merged