doc/releases: 3.1 release notes for kernel/xtensa/x86
zephyrproject-rtos/zephyr pull request #46146
Opened 2022-05-31 16:38 UTC by andyross

Not a huge release, but a handful of noteworthy new features (and one
important bug)

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

2022-05-31 17:59 UTC, ceolin approved these changes, later dismissed

2022-05-31 20:41 UTC, MaureenHelm requested changes
Thanks @andyross . Content looks good, but will you please trim the long lines?

2022-05-31 21:14 UTC, andyross commented
Reflow lines.  I swear I remember some previous rule with docs that wanted bullet points on a single line, some tooling issue or something? ...

2022-05-31 22:36 UTC, MaureenHelm approved these changes

2022-06-01 00:33 UTC, ceolin approved these changes

2022-06-01 14:34 UTC, merged