Bluetooth: controller: llcp: pause data during PHY update procedure
zephyrproject-rtos/zephyr pull request #46394
Opened 2022-06-09 06:32 UTC by kruithofa

This PR fixes the PHY update procedures for conformance tests when
being a Central by pausing data transmission during the PHY update 
procedure
    
To be more precise, following tests are fixed:
    LL/CON/CEN/BV-49-C
    LL/CON/CEN/BV-50-C
    LL/CON/CEN/BV-53-C
    LL/CON/CEN/BV-54-C
    
Signed-off-by: Andries Kruithof <andries.kruithof@nordicsemi.no>

2022-06-09 06:36 UTC, cvinayak submitted a review, later dismissed

2022-06-21 12:08 UTC, erbr-ot commented on subsys/bluetooth/controller/ll_sw/ull_llcp_phy.c
> +	    !ull_is_lll_tx_queue_empty(conn)) {
why this? Means phy update will not add tx unless tx queue is empty? That seems wrong?

2022-06-22 09:11 UTC, erbr-ot commented on subsys/bluetooth/controller/ll_sw/ull_llcp_phy.c
> +	    !ull_is_lll_tx_queue_empty(conn)) {
Gottit

2022-06-22 09:21 UTC, erbr-ot approved these changes, later dismissed
LGTM

2022-06-24 13:56 UTC, thoh-ot submitted a review, later dismissed

2022-06-28 10:00 UTC, ppryga requested changes
One nit-pick and one other request: Can you update commit messages to give some information what was wrong and what is fixed, except IDs of conformance tests?

2022-06-28 11:34 UTC, ppryga-nordic approved these changes

2022-06-28 11:46 UTC, sjanc approved these changes

2022-06-29 08:25 UTC, merged