soc: arm: xilinx_zynq7000: add MMU PTEs for all AXI GPIO instances
zephyrproject-rtos/zephyr pull request #46463
Opened 2022-06-13 07:18 UTC by ibirnbaum

Add the MMU page table entries for all instances of the Xilinx AXI GPIO controller IP core. Other than any Zynq-7000 peripheral supported so far, the existance of 1..n instances of the IP core within the FPGA part of the SoC is optional. Therefore, other than addressing instances of supported peripherals using their DT nodelabel as has always been the case so far, the data for the MMU page table is added using the DT_FOREACH_STATUS_OKAY macro.

Signed-off-by: Immo Birnbaum <Immo.Birnbaum@weidmueller.com>

2022-06-14 12:56 UTC, henrikbrixandersen requested changes

2022-06-14 12:58 UTC, henrikbrixandersen commented
See https://github.com/zephyrproject-rtos/zephyr/issues/46477 for further discussions related to this.

2022-06-14 13:02 UTC, carlocaione requested changes, later dismissed
Yeah, as @henrikbrixandersen said this should be really fixed at driver level by adding support for the MMIO APIs. The discussion in #46477 is really for ARM64 but the point is the same here.

2022-06-14 13:16 UTC, ibirnbaum commented
One point already mentioned in the discussion in #46477 is that the driver for which the [0..n] MMU entries are being added here is for a peripheral which exists both in the Zynq-7000, where the memory has to be mapped via the MMU, and in the UltraScale, which has the MPU. At the time being, *all* of the UltraScale's peripherals and the On-Chip Memory are covered by a single 128 MB R/W/nocache MPU region if the MPU is active, so there's nothing to do with regards to the UltraScale. If the driver was to be modified to use MMIO, that would be SoC family-specific.

This issue basically affects all supported Xilinx peripherals: the AXI GPIO, the PS GPIO, the UART, the GEM, the CAN controller for which a driver has been submitted for review, and some others still in my pipeline (I2C, SPI, etc.).

2022-06-14 13:31 UTC, carlocaione commented
> If the driver was to be modified to use MMIO rather than having the MMU set up based on code outside of the driver, that would be SoC family-specific.

Why? The MMIO API is MMU mapping the addresses only when an MMU is present, see https://github.com/zephyrproject-rtos/zephyr/blob/1578dc699be8d334ec36123996922fef375bde81/include/zephyr/sys/device_mmio.h#L36-L38

In case of MPU, the API is simply falling back to access the usual address without mapping anything: https://github.com/zephyrproject-rtos/zephyr/blob/1578dc699be8d334ec36123996922fef375bde81/include/zephyr/sys/device_mmio.h#L261-L269

> This issue basically affects all supported Xilinx peripherals: the AXI GPIO, the PS GPIO, the UART, the GEM, the CAN controller for which a driver has been submitted for review, and some others still in my pipeline (I2C, SPI, etc.).

Yeah this sucks. I'm trying to push for all the new drivers to support MMIO API as soon as they are introduced but I cannot push people to fix all the existing drivers, especially when there are a lot of them. So, I can approve this as workaround for an existing driver but if you are going to introduce new drivers these must support the MMIO API out-of-the-box.

2022-06-15 09:46 UTC, ibirnbaum commented
> > This issue basically affects all supported Xilinx peripherals: the AXI GPIO, the PS GPIO, the UART, the GEM, the CAN controller for which a driver has been submitted for review, and some others still in my pipeline (I2C, SPI, etc.).
> 
> Yeah this sucks. I'm trying to push for all the new drivers to support MMIO API as soon as they are introduced but I cannot push people to fix all the existing drivers, especially when there are a lot of them. So, I can approve this as workaround for an existing driver but if you are going to introduce new drivers these must support the MMIO API out-of-the-box.

I don't mind converting all the existing Xilinx drivers, that's something that shouldn't take too long, most of them should be fairly simple to switch over, and if memory areas like the SLCR and the MPCore registers can still be mapped via the mmu_regions table in future releases and DMA can still be set up as it currently is being set up in the GEM driver in future releases, there shouldn't be any major conflicts. What I was trying to point out was that if the memory mapping API wasn't compatible with non-MMU systems, some sort of SoC-specific adaptation would have been required for all the Xilinx drivers as the Zynq and the UltraScale support all those peripherals equally. As the physical address is returned by the API in the non-MMU scenario, that assumed issue doesn't exist. So I guess I'll get to it.

2022-08-07 20:06 UTC, ibirnbaum commented
@henrikbrixandersen @carlocaione I've had a go at refactoring the Xilinx AXI GPIO and PS GPIO drivers to use the MMIO API instead, but at the time being, it's just not possible to let GPIO drivers use the MMIO API due to conflicting demands - I opened #48243 to address the issue, as I don't think that having a hand full of particular device drivers or one class of device drivers use a workaround all the other drivers don't need is a good idea. Therefore, could we for now go ahead as suggested herein for now, until a clean solution is found? I'd really like to add support for the Zedboard, where unfortunately, most of the useful GPIOs (slider switches, buttons, LEDs) can only be connected to instances of the AXI GPIO IP core.

2022-08-08 14:29 UTC, carlocaione commented
@ibirnbaum I'm fine to put aside the MMIO story but please fix the CI to be all green so I can take again another look.

2022-08-08 14:54 UTC, ibirnbaum commented
@carlocaione I'll force-push in order to run the CI again. During the last run, the completely unrelated test case net.socket.tcp failed on the unrelated target mps2_an385. Looks to me like a glitch of the CI itself?

2022-08-08 21:20 UTC, ibirnbaum commented
@carlocaione CI passed this time as intended.

2022-08-09 14:30 UTC, carlocaione approved these changes

2022-08-15 07:56 UTC, henrikbrixandersen approved these changes
I am okay with this work-around for now, but we really need to get this working for all kinds of peripherals (in-tree as well as out-of-tree).

If we re-organise the devicetree to closer match that of the Linux kernel (where all memory-mapped peripherals of the Zynq7000 are below an `amba` node, we should be able to iterate all these child devices and add corresponding MMU regions.

2022-08-15 08:11 UTC, merged