drivers: sensor: ams_iAQcore: Update driver to use DEVICE_DT_GET
zephyrproject-rtos/zephyr pull request #46489
Opened 2022-06-13 16:15 UTC by galak

Move driver to use DEVICE_DT_GET for handling access to bus parent
device struct.

Signed-off-by: Kumar Gala <galak@kernel.org>

2022-06-13 23:15 UTC, galak commented
Was commented on discord about use of `i2c_dt_spec`.  Not sure if it makes sense here or not, since the I2C address is hard coded.  Thoughts?

2022-06-14 07:43 UTC, gmarull commented
> Was commented on discord about use of `i2c_dt_spec`. Not sure if it makes sense here or not, since the I2C address is hard coded. Thoughts?

I think we should (I2C address should come from DT), and use driver's config instead of data as well.

2022-06-14 10:52 UTC, galak commented
> > Was commented on discord about use of `i2c_dt_spec`. Not sure if it makes sense here or not, since the I2C address is hard coded. Thoughts?
> 
> I think we should (I2C address should come from DT), and use driver's config instead of data as well.

Will like to see @MaureenHelm chime in and will update accordingly.

2022-06-14 14:24 UTC, MaureenHelm commented
> > > Was commented on discord about use of `i2c_dt_spec`. Not sure if it makes sense here or not, since the I2C address is hard coded. Thoughts?
> > 
> > 
> > I think we should (I2C address should come from DT), and use driver's config instead of data as well.
> 
> Will like to see @MaureenHelm chime in and will update accordingly.

Yes, I think it makes sense here.

2022-06-14 16:54 UTC, alexanderwachter submitted a review, later dismissed
👌

2022-06-14 20:30 UTC, alexanderwachter approved these changes, later dismissed

2022-06-15 08:47 UTC, gmarull requested changes

2022-06-15 08:47 UTC, gmarull commented on drivers/sensor/ams_iAQcore/iAQcore.c
> +static struct iaq_core_config iaq_core_config = {
```suggestion
static const struct iaq_core_config iaq_core_config = {
```

2022-06-15 08:47 UTC, gmarull commented on drivers/sensor/ams_iAQcore/iAQcore.h
> +	const struct i2c_dt_spec i2c;
```suggestion
	struct i2c_dt_spec i2c;
```

2022-06-16 12:58 UTC, gmarull submitted a review, later dismissed

2022-06-17 13:19 UTC, MaureenHelm requested changes

2022-06-17 13:19 UTC, MaureenHelm commented on drivers/sensor/ams_iAQcore/iAQcore.c
>  		return -EINVAL;
Return value should be changed to `-ENODEV`

2022-06-20 09:02 UTC, gmarull approved these changes

2022-06-20 13:25 UTC, MaureenHelm approved these changes

2022-06-20 13:25 UTC, merged