drivers: can: st: improve clock control
zephyrproject-rtos/zephyr pull request #46480
Opened 2022-06-13 14:04 UTC by gmarull

This PR improves the STM32 CAN driver by using the clock control instead of HAL. We should avoid using hard-coded values in HALs, as they bypass Devicetree as a source of hardware description. Also, this practice tends to make code less portable.

Note that there's still one hardcoded register access, `FDCAN_CONFIG`, it can be fixed later.

Found this _issue_ while working on <soc.h> cleanups.

2022-06-13 15:40 UTC, martinjaeger approved these changes, later dismissed

2022-06-13 15:40 UTC, martinjaeger commented on drivers/can/can_stm32fd.c
> +		LOG_ERR("Could not turn CAN clock (%d)", ret);
Nits
```suggestion
		LOG_ERR("Could not turn on CAN clock (%d)", ret);
```

2022-06-14 08:19 UTC, gmarull commented on drivers/can/can_stm32fd.c
> +		LOG_ERR("Could not turn CAN clock (%d)", ret);
fixed thanks

2022-06-14 09:40 UTC, martinjaeger submitted a review, later dismissed

2022-06-14 11:30 UTC, henrikbrixandersen submitted a review, later dismissed
Thanks!

2022-06-14 16:58 UTC, alexanderwachter approved these changes, later dismissed

2022-06-15 07:11 UTC, carlescufi commented
@erwango ping

2022-06-15 08:28 UTC, erwango requested changes
Please set clocks prop as `required: true` in `st,stm32-fdcan.yaml`.
Also, there's one more fdcan node that would require a clocks prop in `dts/arm/st/g4/stm32g473.dtsi`.
Otherwise thanks for doing this change!

2022-06-15 08:38 UTC, gmarull commented
> Please set clocks prop as `required: true` in `st,stm32-fdcan.yaml`. Also, there's one more fdcan node that would require a clocks prop in `dts/arm/st/g4/stm32g473.dtsi`. Otherwise thanks for doing this change!

done

2022-06-15 08:50 UTC, martinjaeger approved these changes

2022-06-15 08:53 UTC, henrikbrixandersen approved these changes

2022-06-15 09:09 UTC, erwango approved these changes

2022-06-16 09:26 UTC, merged