drivers: sensor: amg88xx: Update driver to use new driver mechanisms
zephyrproject-rtos/zephyr pull request #46486
Opened 2022-06-13 16:14 UTC by galak

Move driver to use gpio_dt_spec and DEVICE_DT_GET for handling access
to bus parent device struct.

Signed-off-by: Kumar Gala <galak@kernel.org>

2022-06-13 20:19 UTC, MaureenHelm requested changes
The I2C and GPIO changes should be in separate commits.

Also, why did you rename i2c to i2c_bus_dev? The change adds some unnecessary noise to the diff

2022-06-14 07:34 UTC, gmarull requested changes

2022-06-14 07:34 UTC, gmarull commented on drivers/sensor/amg88xx/amg88xx_trigger.c
> +	}
Driver uses `GPIO_DT_SPEC_INST_GET`, not `GPIO_DT_SPEC_INST_GET_OR`, meaning `int_gpio.port` can't be NULL. We should also return `-ENODEV`.

2022-06-14 10:44 UTC, galak commented on drivers/sensor/amg88xx/amg88xx.h
> +	const struct amg88xx_config *cfg;
removed.  getting `config` from `dev` pointer now.

2022-06-14 10:45 UTC, gmarull commented on samples/sensor/amg88xx/src/main.c
> +	const struct device *dev = DEVICE_DT_GET(DT_INST(0, panasonic_amg88xx));
```suggestion
	const struct device *dev = DEVICE_DT_GET_ONE(panasonic_amg88xx);
```

2022-06-14 10:51 UTC, gmarull approved these changes

2022-06-14 14:20 UTC, MaureenHelm approved these changes

2022-06-14 14:21 UTC, merged