drivers: serial: atmel_sam: Added hw flow control
zephyrproject-rtos/zephyr pull request #46501
Opened 2022-06-14 06:39 UTC by wojciechslenska

Patch added hw flow control to usart driver

Signed-off-by: Wojciech Slenska <wsl@trackunit.com>

2022-06-19 16:27 UTC, nandojve requested changes

2022-06-19 16:27 UTC, nandojve commented on drivers/serial/usart_sam.c
> +		| US_MR_CHMODE_NORMAL;
```c
	us_mr = US_MR_NBSTOP_1_BIT
	      | US_MR_PAR_NO
	      | US_MR_CHRL_8_BIT
	      | US_MR_USCLKS_MCK
	      | US_MR_CHMODE_NORMAL;
```

2022-06-20 20:11 UTC, nandojve approved these changes
Thank you @wojciechslenska

2022-06-21 16:21 UTC, dcpleung approved these changes

2022-06-22 10:24 UTC, merged