tests: condition variables: move to new ztest API
zephyrproject-rtos/zephyr pull request #46662
Opened 2022-06-17 19:58 UTC by nashif

Move test to new ztest API.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2022-06-17 20:19 UTC, yperess requested changes

2022-06-17 20:19 UTC, yperess commented on tests/kernel/condvar/condvar_api/src/main.c
> +ZTEST(condvar_tests, test_condvar_wait_forever_wake)
Should be `ZTEST_USER()`

2022-06-17 21:04 UTC, dcpleung approved these changes

2022-06-17 21:16 UTC, andyross approved these changes

2022-06-17 21:30 UTC, yperess approved these changes

2022-06-18 11:45 UTC, stephanosio approved these changes

2022-06-18 12:10 UTC, merged