Bluetooth: Host: Add CONFIG_BT_PRIVACY_RANDOMIZE_IR
zephyrproject-rtos/zephyr pull request #46767
Opened 2022-06-22 08:14 UTC by alwa-nordic

This new option prevents the Host from using Controller-provided identity roots. This potentially increases privacy.

2022-06-22 08:19 UTC, jori-nordic commented on subsys/bluetooth/host/Kconfig
> +	  This may come with a performance penalty.
can we say `at boot` ?

2022-06-22 08:30 UTC, jori-nordic requested changes

2022-06-22 08:30 UTC, jori-nordic commented on subsys/bluetooth/host/Kconfig
> +	  the Host will fallback to automatically setup the default identity
setting up

2022-06-22 08:30 UTC, jori-nordic commented on subsys/bluetooth/host/Kconfig
> +	  If the controller has a public address (HCI_Read_BD_ADDR) that becomes
), that becomes

2022-06-22 08:30 UTC, jori-nordic commented on subsys/bluetooth/host/Kconfig
> +	  identity.
Could we change `this config determines` to `setting this config to false will make the Host try to use ...` This way it's clearer what value does what. same comment for the next paragraph.

2022-07-11 06:52 UTC, jori-nordic submitted a review, later dismissed

2022-07-15 04:34 UTC, jori-nordic approved these changes

2022-08-18 10:54 UTC, jhedberg approved these changes

2022-08-18 11:04 UTC, merged