doc: net: Add HTTP client library page
zephyrproject-rtos/zephyr pull request #46791
Opened 2022-06-22 15:00 UTC by rlubos

Add brief documentation for the HTTP client library and reference its
API.

Fixes #46267

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2022-06-23 05:35 UTC, jukkar submitted a review, later dismissed

2022-06-23 09:07 UTC, carlescufi requested changes

2022-06-23 09:07 UTC, carlescufi commented on doc/connectivity/networking/api/http.rst
> +over TLS socket (HTTPS).
```suggestion
Zephyr provides an HTTP client library which allows to send HTTP requests and
parse HTTP responses. The library communicates over the sockets API, it does not
however create sockets on its own. The application is responsible for creating
a socket and passing it to the library. Therefore, depending on the application's
needs, the library can communicate either over a plain TCP socket (HTTP) or
over a TLS socket (HTTPS).
```

2022-06-23 09:07 UTC, carlescufi commented on doc/connectivity/networking/api/http.rst
> +to receive or not. A very simple response handling function is presented below:
```suggestion
If the server responds to the request, the response will be provided to the
application through the response callback registered in the request structure.
The response may be provided in chunks, therefore the application shall be
prepared for that. The callback function, along with the structure
containing the response data, provides information about whether more data is expected
to be received. A very simple response handling function is presented below:
```

2022-06-24 13:34 UTC, FrancescoSer requested changes
Just a few suggestions

2022-06-24 13:34 UTC, FrancescoSer commented on doc/connectivity/networking/api/http.rst
> +####
```suggestion
HTTP client
###########
```

2022-06-24 13:34 UTC, FrancescoSer commented on doc/connectivity/networking/api/http.rst
> +over a TLS socket (HTTPS).
```suggestion
The HTTP client library allows you to send HTTP requests and
parse HTTP responses. The library communicates over the sockets
API but it does not create sockets on its own.

The application must be responsible for creating a socket and passing it to the library.
Therefore, depending on the application's needs, the library can communicate over
either a plain TCP socket (HTTP) or a TLS socket (HTTPS).
```

2022-06-24 13:34 UTC, FrancescoSer commented on doc/connectivity/networking/api/http.rst
> +function. It's important to setup the request structure correctly, for example:
```suggestion
The API of the HTTP client library has a single function.

The following is an example of a request structure created correctly:
```

2022-06-24 13:34 UTC, FrancescoSer commented on doc/connectivity/networking/api/http.rst
> +to be received. A very simple response handling function is presented below:
```suggestion
If the server responds to the request, the library provides the response to the
application through the response callback registered in the request structure.
As the library can provide the response in chunks, the application must be able
to process these.

Together with the structure containing the response data, the callback function
also provides information about whether the library expects to receive more data.

The following is an example of a very simple response handling function:
```

2022-06-24 13:38 UTC, rlubos commented
@FrancescoSer Thanks, I've applied your suggestions.

2022-06-24 14:02 UTC, FrancescoSer approved these changes

2022-06-26 09:54 UTC, jukkar approved these changes

2022-06-27 14:29 UTC, carlescufi approved these changes

2022-06-27 14:29 UTC, merged