drivers: sensor: lsm6ds0: Update driver to use i2c_dt_spec
zephyrproject-rtos/zephyr pull request #46855
Opened 2022-06-23 15:56 UTC by benjaminbjornsson

Simplify driver by using i2c_dt_spec for bus access.

Signed-off-by: Benjamin Björnsson <benjamin.bjornsson@gmail.com>

2022-06-23 21:14 UTC, MaureenHelm requested changes

2022-06-24 11:40 UTC, benjaminbjornsson commented on drivers/sensor/lsm6ds0/lsm6ds0.c
> +	    0) {
Fixed!

2022-06-24 13:51 UTC, galak approved these changes

2022-06-27 09:20 UTC, gmarull approved these changes

2022-06-27 14:42 UTC, MaureenHelm approved these changes

2022-06-27 14:42 UTC, merged