modules: fix advice on deprecating a module
zephyrproject-rtos/zephyr pull request #46863
Opened 2022-06-23 22:07 UTC by mbolivar-nordic

Commit d169171a6644fc3d9f0f67f1bb9ac72272d69d87
("cmake: Use CMake DEPRECATION level instead of WARNING")
altered the way we handle deprecation warnings in CMake.

The deprecation_warnings.cmake file has some commented-out example
code which should be updated to match the pattern introduced in that
commit, for consistency.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

2022-06-24 02:21 UTC, nashif approved these changes

2022-07-04 13:20 UTC, carlescufi commented
I know @tejlmand has ideas regarding warnings and CMake so need a +1 from him.

2022-07-11 12:34 UTC, gmarull approved these changes

2022-07-15 10:17 UTC, tejlmand requested changes
I prefer to move this feature into Kconfig itself.

This is aligned with how we do experimental.

2022-07-19 20:11 UTC, closed without merging