Add lib_code module type.
zephyrproject-rtos/zephyr pull request #46879
Opened 2022-06-24 11:10 UTC by jxstelter

External libraries can contain processing module code or common library code.
Library manager need to distinguish between both type of modules for proper loading.

Signed-off-by: Jaroslaw Stelter <jaroslaw.stelter@intel.com>

2022-06-24 12:55 UTC, marcinszkudlinski submitted a review, later dismissed

2022-06-24 19:59 UTC, dcpleung requested changes
Please change the commit summary to prefix with `soc: intel_adsp:` or something similar. `manifest` is used for changing the West manifest.

2022-06-28 08:18 UTC, kv2019i submitted a review, later dismissed

2022-06-28 12:35 UTC, andyross approved these changes, later dismissed

2022-06-28 16:55 UTC, dcpleung approved these changes, later dismissed

2022-06-28 17:40 UTC, nashif requested changes
commit message, author email does not match sign-off-by, you need to fix your git settings and have First Last names correctly.

2022-06-29 10:30 UTC, nashif approved these changes

2022-06-29 14:29 UTC, dcpleung approved these changes

2022-06-29 14:42 UTC, merged