drivers: sensor: sht3xd: Update driver to use DEVICE_DT_GET
zephyrproject-rtos/zephyr pull request #46909
Opened 2022-06-26 10:51 UTC by benjaminbjornsson

2022-06-26 15:26 UTC, galak requested changes
Rename `gpio_spec_dt` variable

2022-06-26 16:38 UTC, benjaminbjornsson commented
> Rename `gpio_spec_dt` variable

Fixed!

2022-06-27 08:15 UTC, gmarull approved these changes

2022-06-27 14:13 UTC, galak approved these changes

2022-06-27 15:43 UTC, MaureenHelm approved these changes

2022-06-27 15:43 UTC, merged