kernel: timeout: next timeout is closer to elapsed time
zephyrproject-rtos/zephyr pull request #47016
Opened 2022-06-29 07:25 UTC by FRASTM

Directly get the elapsed time instead of writing a variable
So is the calculated next timeout value as close to the
elapsed time as possible.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/46641

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-06-29 07:45 UTC, FRASTM commented
test case **tests/kernel/context** PASSED on the nucleo_f091rc 
```
*** Booting Zephyr OS build zephyr-v3.1.0-914-gad71390e548d  ***
Running TESTSUITE context
===================================================================
START - test_kernel_interrupts
SKIP - test_kernel_interrupts in 0.1 seconds
===================================================================
START - test_kernel_ctx_thread
Testing k_current_get() from an ISR and thread
Testing k_is_in_isr() from an ISR
Testing k_is_in_isr() from a preemptible thread
PASS - test_kernel_ctx_thread in 0.12 seconds
===================================================================
START - test_busy_wait
Thread busy waiting for 20000 usecs
Thread busy waiting completed
Thread busy waiting for 20000 usecs (irqs locked)
Thread busy waiting completed (irqs locked)
PASS - test_busy_wait in 0.54 seconds
===================================================================
START - test_k_sleep
thread sleeping for 50 milliseconds
thread back from sleep
Testing k_thread_create() without cancellation
thread (q order: 2, t/o: 500) is running
got thread (q order: 2, t/o: 500) as expected
thread (q order: 3, t/o: 750) is running
got thread (q order: 3, t/o: 750) as expected
thread (q order: 0, t/o: 1000) is running
got thread (q order: 0, t/o: 1000) as expected
thread (q order: 6, t/o: 1250) is running
got thread (q order: 6, t/o: 1250) as expected
thread (q order: 1, t/o: 1500) is running
got thread (q order: 1, t/o: 1500) as expected
thread (q order: 4, t/o: 1750) is running
got thread (q order: 4, t/o: 1750) as expected
thread (q order: 5, t/o: 2000) is running
got thread (q order: 5, t/o: 2000) as expected
Testing k_thread_create() with cancellations
cancelling [q order: 0, t/o: 1000, t/o order: 0]
thread (q order: 3, t/o: 750) is running
got (q order: 3, t/o: 750, t/o order 1) as expected
thread (q order: 0, t/o: 1000) is running
got (q order: 0, t/o: 1000, t/o order 2) as expected
cancelling [q order: 3, t/o: 750, t/o order: 3]
cancelling [q order: 4, t/o: 1750, t/o order: 4]
thread (q order: 4, t/o: 1750) is running
got (q order: 4, t/o: 1750, t/o order 5) as expected
cancelling [q order: 6, t/o: 1250, t/o order: 6]
PASS - test_k_sleep in 5.336 seconds
===================================================================
START - test_kernel_cpu_idle_atomic
SKIP - test_kernel_cpu_idle_atomic in 0.1 seconds
===================================================================
START - test_kernel_cpu_idle
PASS - test_kernel_cpu_idle in 0.8 seconds
===================================================================
START - test_k_yield
PASS - test_k_yield in 0.1 seconds
===================================================================
START - test_kernel_thread
PASS - test_kernel_thread in 0.1 seconds
===================================================================
START - test_kernel_timer_interrupts
SKIP - test_kernel_timer_interrupts in 0.1 seconds
===================================================================
TESTSUITE context succeeded
===================================================================
RunID: 0e4722e3073f6b99bce70cd258a7f372
PROJECT EXECUTION SUCCESSFUL
```

2022-06-29 12:30 UTC, andyross requested changes
This seems poorly justified, and more like you're chasing a timing glitch in the test that adjusting a few cycles in the kernel just happens to fix.  This is only going to move timing by a tiny bit, and the kernel should be making correct decisions even if the clock slips by a tick (because it will all the time: you can't lock or synchronize against real time).

Can you walk me through exactly what the situation is that's failing here and why this fixes it?

2022-06-30 07:09 UTC, FRASTM commented
> This seems poorly justified, and more like you're chasing a timing glitch in the test that adjusting a few cycles in the kernel just happens to fix. This is only going to move timing by a tiny bit, and the kernel should be making correct decisions even if the clock slips by a tick (because it will all the time: you can't lock or synchronize against real time).
> 
> Can you walk me through exactly what the situation is that's failing here and why this fixes it?

What I can say is reported in the issue https://github.com/zephyrproject-rtos/zephyr/issues/46641 : the testcase  tests/kernel/context/test_kernel_cpu_idle failed  on the nucleo_f091rc START - 
because of                     
```
 Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/context/src/main.c:355: _test_kernel_cpu_idle: (tms2 < )
Bad ms value computed,got 5481 which is less than 5482   
``` 
and that changing the elapsed fixes the pb without impacting others (as far as I can check)

2022-06-30 13:48 UTC, andyross commented
Yeah, that just looks like a racy test.  It's relying on a 1ms idle coming out exactly as expected, on a system with a 10 kHz tickrate and with a driver (systick) that is known to be a little sloppy on boundaries (it isn't free running and doesn't self-reset, so the ISR inevitably loses time and has to guess at a calibration/correction).  My guess is that other systick devices would probably fail similarly.

(Also it's invoking k_cpu_idle() incorrectly -- interrupts need to be masked on entry there too, not just for k_cpu_atomic_idle(), but that's benign unless this test has a mystery interrupt source other than the timer)

And AFAIK we don't actually promise high precision through k_cpu_idle() anyway.  This platform doesn't have a deep idle state, but some do (e.g. if you guys ever move to the "kHz-scale clock for idle, mHz for runtime" architecture, you're going to get there too), and almost by definition timeout precision is going to be impacted by idle in a way this test doesn't understand.

My suggestion would be to go back to the test, pick a more reasonable threshold (+/- 10ms in idle wakeup can be done almost everywhere I'm sure), do the math in ticks and not ms (not a big deal here where the rates are integer multiples, but the nordic and microchip folks will thank you), and see if that works for you.

2022-06-30 14:21 UTC, andyross commented
Never mind, I gave it a quick shot in https://github.com/zephyrproject-rtos/zephyr/pull/47112 .  Works for the emulation platforms, can you see if it addresses the failure on your board?

2022-07-01 09:18 UTC, FRASTM commented
> Never mind, I gave it a quick shot in #47112 . Works for the emulation platforms, can you see if it addresses the failure on your board?

definitely, thanks

2022-07-01 09:20 UTC, FRASTM commented
> Never mind, I gave it a quick shot in #47112 . Works for the emulation platforms, can you see if it addresses the failure on your board?

definitely, thanks

2022-07-01 09:21 UTC, FRASTM commented
> Never mind, I gave it a quick shot in #47112 . Works for the emulation platforms, can you see if it addresses the failure on your board?

 definitely. Thanks !

2022-07-01 09:21 UTC, FRASTM commented
refer to https://github.com/zephyrproject-rtos/zephyr/pull/47112

2022-07-01 09:21 UTC, closed without merging