drivers: interrupt: stm32 several exti can share one irq
zephyrproject-rtos/zephyr pull request #47108
Opened 2022-06-30 13:55 UTC by FRASTM

With this CONFIG_EXTI_STM32_ONE_IRQ,
the stm32 several pins can share one interrupt
(instead of one irq per pin).
Then one callback function is common to all sources.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/45234

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-06-30 14:17 UTC, gmarull requested changes

2022-06-30 14:38 UTC, gmarull commented on drivers/interrupt_controller/Kconfig.stm32
> +	  multiple EXTI lines trigger one single IRQ
note: `default n` is not needed

2022-06-30 15:34 UTC, FRASTM commented on drivers/interrupt_controller/Kconfig.stm32
> +	  multiple EXTI lines trigger one single IRQ
ok

2022-07-07 07:00 UTC, FRASTM commented
DNM until the related issue is confirmed

2022-07-27 13:49 UTC, erwango commented
Closing as https://github.com/zephyrproject-rtos/zephyr/issues/45234 is now closed

2022-07-27 13:49 UTC, closed without merging