RFC: Voltage divider sensor
zephyrproject-rtos/zephyr pull request #47176
Opened 2022-07-01 21:01 UTC by aurel32

There is already a `voltage-divider` binding defined, which is only used by the `boards/nrf/battery` sample. Looking at the recently added `stm32_vbat` sensor driver, I realized it might be a good idea to implement a more generic sensor using the existing binding, that can replace the `stm32_vbat` sensor and big part of the battery sample. As a bonus it allows to easily measure other voltages with only 2 resistors. It is actually more versatile than existing sample and drivers as it allows to tune all ADC parameters (resolution, oversampling, gain, ...) at the expense of more entries in the device tree.

For now this is just a RFC to demonstrate the idea. I have fully tested the driver itself. I have converted the `sensor/stm32_vbat_sensor` sample to show the changes are minimal, but only tested compiled it, as I don't have the corresponding boards. If this driver sounds like a good idea, I can also convert the `boards/nrf/battery` sample.

2022-07-05 15:23 UTC, carlescufi commented
API meeting: 

- @MaureenHelm @gmarull @erwango

2022-08-05 15:52 UTC, aurel32 commented
I have just pushed an updated version of this PR, following the recent changes in Zephyr. I have been able to test the `stm32_vbat_sensor` on a Nucleo L432KC board, which have the VBAT pin internally connected to VCC, and the value was correct.

2022-09-06 21:32 UTC, aurel32 commented
Any news about that? It might be worth looking at the idea before the 3.2 is released with `stm32_vbat`, as this alternative sensor can just replace it and do much more.

2022-09-07 09:01 UTC, erwango approved these changes
I think this addition is valuable and I'm fine if this could replace `stm32_vbat` driver.
Regarding the sample itself, it could be made generic of course but I'd prefer we can keep it identified as `vbat_sensor`, rather than a generic `voltage_divider` sensor, otherwise we'd need some doc addition to inform and redirect people that are looking for a solution to measure vbat.

Edit: Tested ok on supported boards.

2022-09-07 09:14 UTC, gmarull requested changes

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/Kconfig
> +	depends on ADC
```suggestion
	select ADC
```

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/Kconfig
> +	  Enable driver for Voltage Divider and then also ADC
help should be improved, maybe:

```suggestion
	  Enable driver for voltage divider. This driver allows measuring analog voltages scaled with a voltage divider circuit.
```

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +#endif
```suggestion
```

this is mostly redundant with the `DT_HAS_` helpers

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +#include <zephyr/device.h>
```suggestion
#define DT_DRV_COMPAT voltage_divider

#include <zephyr/device.h>
```

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +}
I think we should be using the regulator framework here, and `-supply` properties instead.

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +	if (rc) {
```suggestion
	if (rc < 0) {
```
nit: use expressions evaluating to boolean, same for others

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +	adc_raw_to_millivolts_dt(&data->adc_channel, &mv);
this needs error checking (`-ENOTSUP`), not all drivers support this operation.

2022-09-07 09:14 UTC, gmarull commented on drivers/sensor/voltage_divider/voltage_divider.c
> +DT_INST_FOREACH_STATUS_OKAY(DEFINE_VOLTAGE_DIVIDER)
please align `\`, or try with `clang-format`.

2022-09-07 09:14 UTC, gmarull commented on samples/sensor/stm32_vbat_sensor/README.rst
>  This sample reads the Vbat from the STM32 Internal
we need to rename the sample to not be stm32 specific, this is now a generic sample that can work on any board, and can measure any voltage, not just battery.

2022-09-07 13:19 UTC, erwango commented
@MaureenHelm Should CODEOWNERS/MAINTAINERS be updated ?

2022-09-07 14:50 UTC, FRASTM commented on samples/sensor/stm32_vbat_sensor/README.rst
> +        compatible = "voltage_divider";
compatible = "voltage**-**divider";

2022-09-07 15:01 UTC, FRASTM commented on drivers/sensor/voltage_divider/voltage_divider.c
> +{
what is the difference when enable is true/false -> should 'enable' or disable but there is no check on 'enable' boolean

2022-09-19 13:08 UTC, erwango reviewed
Discard comment

2022-09-21 12:01 UTC, erwango commented on samples/sensor/stm32_vbat_sensor/boards/nucleo_wb55rg.overlay
> +	channel@12 {
```suggestion
	channel@18 {
```
?

2022-09-21 15:01 UTC, MaureenHelm reviewed
I like the idea and agree with most of the feedback from @gmarull 

> @MaureenHelm Should CODEOWNERS/MAINTAINERS be updated ?

@erwango how?

2022-09-21 15:12 UTC, erwango commented
> @erwango how?

From recent examples, I think that CODEOWNER is still in use. So if confirmed, this file should be updated.

2022-10-17 18:41 UTC, talih0 commented
@aurel32, are you still working on this PR? I can take over if you are too busy (I have some interest in getting this merged upstream)

2023-01-01 00:30 UTC, closed without merging