* lib: mem_blocks: add a usage test for a block
zephyrproject-rtos/zephyr pull request #47194
Opened 2022-07-02 11:28 UTC by marcinszkudlinski

add a sys_mem_blocks_is_region_free procedure to test
if the block in question is free or taken

Required for storage of memory banks in save to disk like operations

2022-07-05 15:03 UTC, dcpleung requested changes

2022-07-05 15:03 UTC, dcpleung commented on include/zephyr/sys/mem_blocks.h
> + * @param[in]  mem_block  Pointer to memory block object.
Need a `@param` for `mem_block`.

2022-07-05 15:03 UTC, dcpleung commented on include/zephyr/sys/mem_blocks.h
> + * @retval false at least one of the memory blocks is taken
These need to match the data type of the return.

2022-07-12 15:29 UTC, dcpleung approved these changes

2022-07-14 08:44 UTC, carlescufi approved these changes

2022-07-14 08:44 UTC, merged