drivers: sensor: bma280: Add multi-instance support
zephyrproject-rtos/zephyr pull request #47207
Opened 2022-07-03 15:50 UTC by benjaminbjornsson

Move driver to use DT_INST_FOREACH_STATUS_OKAY to add
multi-instance support.

Signed-off-by: Benjamin Björnsson <benjamin.bjornsson@gmail.com>

2022-07-04 07:45 UTC, gmarull requested changes

2022-07-04 07:45 UTC, gmarull commented on drivers/sensor/bma280/bma280.c
> +					())))							\
`GPIO_DT_SPEC_INST_GET_OR()`

2022-07-04 08:56 UTC, benjaminbjornsson commented on drivers/sensor/bma280/bma280.c
> +					())))							\
Fixed!

2022-07-04 08:57 UTC, gmarull approved these changes

2022-07-05 13:48 UTC, MaureenHelm approved these changes

2022-07-05 13:49 UTC, merged