drivers: sensor: amg88xx: Add multi-instance support
zephyrproject-rtos/zephyr pull request #47202
Opened 2022-07-03 09:27 UTC by benjaminbjornsson

Move driver to use DT_INST_FOREACH_STATUS_OKAY to add
multi-instance support.

Signed-off-by: Benjamin Björnsson <benjamin.bjornsson@gmail.com>

2022-07-03 14:34 UTC, galak submitted a review, later dismissed

2022-07-04 07:47 UTC, gmarull requested changes

2022-07-04 07:47 UTC, gmarull commented on drivers/sensor/amg88xx/amg88xx.c
> +		      CONFIG_SENSOR_INIT_PRIORITY, &amg88xx_driver_api);	     \
nit: indent here

2022-07-04 07:47 UTC, gmarull commented on drivers/sensor/amg88xx/amg88xx.c
> +			       ())))						     \
`GPIO_DT_SPEC_INST_GET_OR`

2022-07-04 08:52 UTC, benjaminbjornsson commented on drivers/sensor/amg88xx/amg88xx.c
> +		      CONFIG_SENSOR_INIT_PRIORITY, &amg88xx_driver_api);	     \
Fixed!

2022-07-04 08:55 UTC, gmarull approved these changes, later dismissed

2022-07-05 13:47 UTC, MaureenHelm requested changes

2022-07-05 13:47 UTC, MaureenHelm commented on drivers/sensor/amg88xx/amg88xx.c
> +	struct amg88xx_data amg88xx_data_##inst;						\
```suggestion
	static struct amg88xx_data amg88xx_data_##inst;						\
```

2022-07-05 15:05 UTC, gmarull approved these changes

2022-07-07 13:39 UTC, galak approved these changes

2022-07-07 14:21 UTC, MaureenHelm approved these changes

2022-07-07 14:21 UTC, merged