tests: subsys/cpp: move to new ztest API
zephyrproject-rtos/zephyr pull request #47233
Opened 2022-07-04 05:48 UTC by shuai1x

Move test subsys/cpp to use new ztest API.

Signed-off-by: Zhao Shuai shuai1x.zhao@intel.com

2022-07-04 05:57 UTC, stephanosio requested changes
There is no need to create a new pull request when you amend commits.

See https://github.com/zephyrproject-rtos/zephyr/pull/47223#pullrequestreview-1027019061

2022-07-04 07:31 UTC, shuai1x commented
Ok. I'm sorry. I accidentally turned the last pull request off because I deleted the branch.

2022-07-05 02:25 UTC, chen-png approved these changes, later dismissed

2022-07-06 04:40 UTC, shuai1x commented
> There is no need to create a new pull request when you amend commits.
> 
> See [#47223 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/47223#pullrequestreview-1027019061)

I'm sorry to say that I was not familiar with pull request before. I accidentally turned the last pull request off because I deleted the branch. And the last one can not reopen, so I have to use this one. And I will pay attention to this problem. Could you help me to get through? Thank you.

2022-07-07 03:30 UTC, chen-png approved these changes

2022-07-07 03:48 UTC, stephanosio approved these changes

2022-07-07 06:09 UTC, merged