itests: lib: move heap to new ztest API
zephyrproject-rtos/zephyr pull request #47310
Opened 2022-07-05 09:19 UTC by 1xlibiao

Move test lib/heap to use new ztest API.

Signed-off-by: li biao <biao1x.li@intel.com>

2022-07-06 04:01 UTC, stephanosio submitted a review, later dismissed
Please fix the typo in the commit title:
```
itests: lib: move heap to new ztest API 
```

2022-07-06 04:09 UTC, 1xlibiao commented
> Please fix the typo in the commit title:
> 
> ```
> itests: lib: move heap to new ztest API 
> ```

OK,thanks for helping me correct,I will modify it as soon.

2022-07-07 04:57 UTC, nashif requested changes

2022-07-07 04:57 UTC, nashif commented on tests/lib/heap/src/main.c
> +ZTEST(lib_heap_test, test_big_heap)
no need for _test in the suite name.

2022-07-07 05:01 UTC, 1xlibiao commented on tests/lib/heap/src/main.c
> +ZTEST(lib_heap_test, test_big_heap)
ok,I will revise it as soon

2022-07-08 08:41 UTC, chen-png approved these changes

2022-07-13 10:06 UTC, enjiamai approved these changes

2022-07-13 16:29 UTC, yerabolu approved these changes

2022-07-15 02:11 UTC, nashif approved these changes

2022-07-15 10:58 UTC, merged