drivers: sensor: tmp007: Add multi-instance support
zephyrproject-rtos/zephyr pull request #47319
Opened 2022-07-05 10:16 UTC by benjaminbjornsson

Move driver to use DT_INST_FOREACH_STATUS_OKAY to add
multi-instance support.

Signed-off-by: Benjamin Björnsson <benjamin.bjornsson@gmail.com>

2022-07-05 10:24 UTC, gmarull submitted a review, later dismissed

2022-07-05 14:13 UTC, MaureenHelm requested changes

2022-07-05 14:13 UTC, MaureenHelm commented on drivers/sensor/tmp007/tmp007.c
> +	struct tmp007_data tmp007_data_##inst;							\
```suggestion
	static struct tmp007_data tmp007_data_##inst;							\
```

2022-07-05 14:55 UTC, benjaminbjornsson commented on drivers/sensor/tmp007/tmp007.c
> +	struct tmp007_data tmp007_data_##inst;							\
Fixed!

2022-07-06 10:16 UTC, gmarull approved these changes

2022-07-06 14:07 UTC, MaureenHelm approved these changes

2022-07-06 14:07 UTC, merged