Generate symbols file for test plan
zephyrproject-rtos/zephyr pull request #47353
Opened 2022-07-05 17:46 UTC by nashif

- build: generate symbols file
- ztest: generate symbols for tests
- cmake: binutils: find binutils nm for host compiler

2022-07-06 03:47 UTC, stephanosio commented on Kconfig.zephyr
> +	default n
`default n` is implied and redundant. It should be removed.

2022-07-06 03:55 UTC, stephanosio commented
@nashif I assume, with this, we will no longer need an abomination like the following, is that correct?

https://github.com/zephyrproject-rtos/zephyr/blob/735ddeb4a8e26c6ce07d6aa5a0b77fffc559b2a8/tests/lib/newlib/thread_safety/testcase.yaml#L7-L14

2022-07-06 09:56 UTC, nashif commented
> @nashif I assume, with this, we will no longer need an abomination like the following, is that correct?

yes

2022-07-06 13:10 UTC, stephanosio submitted a review, later dismissed

2022-07-07 08:36 UTC, tejlmand requested changes
Please add this new bintools command property to this template file:
https://github.com/zephyrproject-rtos/zephyr/blob/55df2bf08ff0bb9abbc46b11d252d6b310a604c9/cmake/bintools/bintools_template.cmake#L7-L13

so that users using other toolchains won't get an error when enabling this.

Also, could we find a more generic name, that are then mapped by toolchain implementations.
For example: `symbol_command` or `symbol_list_command` ?

2022-07-07 08:36 UTC, tejlmand commented on cmake/bintools/gnu/target_bintools.cmake
> +set_property(TARGET bintools PROPERTY nm_command ${CMAKE_NM})
could you come up with a more generic name here ?
Like is done for `disassembly`, `strip`, `elfconvert`

`nm` is very GNU centric, and other toolchains may provide other commands and arguments for achieving similar functionality.
So would be nice with more generic name on what you want to achieve.

2022-07-08 03:22 UTC, yperess reviewed
LGTM, one small nit on a mispelled word

2022-07-08 03:22 UTC, yperess commented on cmake/bintools/bintools_template.cmake
> +#             For GNU binajry utilities this is nm
nit `s/binajry/binary`

2022-07-11 08:42 UTC, stephanosio approved these changes

2022-07-11 09:01 UTC, tejlmand approved these changes
lgtm.

A minor alignment issuse noticed, but nothing blocking.

2022-07-11 09:56 UTC, merged