doc: fix typos and broken DCO link
zephyrproject-rtos/zephyr pull request #4735
Opened 2017-11-04 16:43 UTC by xasc

Corrected a few typos and a broken reference to the DCO in the contribution guidelines.

2017-11-04 18:08 UTC, dbkinder requested changes
update looks ok, except for “locks” change

2017-11-04 18:08 UTC, dbkinder commented on doc/kernel/synchronization/mutexes.rst
> +have been released. It is recommended that a thread locks only a single mutex
“lock” is correct here.

2017-11-05 11:58 UTC, xasc commented
The spelling change has been reverted.

2017-11-05 13:20 UTC, nashif approved these changes

2017-11-05 13:20 UTC, merged