drivers: counter: stm32u5 family compatibility
zephyrproject-rtos/zephyr pull request #47486
Opened 2022-07-07 10:00 UTC by wojciechslenska

In STM32U5X family there is no EXTI line for RTC.

Signed-off-by: Wojciech Slenska <wsl@trackunit.com>

2022-08-09 07:35 UTC, erwango requested changes

2022-08-09 07:35 UTC, erwango commented on dts/arm/st/u5/stm32u5.dtsi
> +			label = "RTC";
Remove property 'label'

2022-08-09 09:15 UTC, erwango approved these changes

2022-08-11 06:10 UTC, FRASTM approved these changes

2022-08-11 06:24 UTC, merged