drivers: sensor: bq274xx: fix lazy loading
zephyrproject-rtos/zephyr pull request #47498
Opened 2022-07-07 13:13 UTC by pdgendt

This change allows per-instance configuration of lazy loading and fixes build issue.

Fixes #47458

2022-07-07 13:44 UTC, galak requested changes
rename dts property.

2022-07-11 16:40 UTC, MaureenHelm submitted a review, later dismissed

2022-07-12 08:51 UTC, thedjnK requested changes

2022-07-12 08:51 UTC, thedjnK commented on dts/bindings/sensor/ti,bq274xx.yaml
> +        till the first sample request and keep the boot time as short as possible.
*until

2022-07-12 14:18 UTC, MaureenHelm approved these changes

2022-07-13 15:14 UTC, pdgendt commented
@thedjnK do you approve with the change? (I can't seem to click the re-request review button)

2022-07-14 13:14 UTC, thedjnK approved these changes

2022-07-19 06:37 UTC, pdgendt commented
> @galak please revisit

:pray:

2022-07-20 13:39 UTC, galak approved these changes

2022-07-20 13:39 UTC, merged