soc: arm: new stm32f412Rx device
zephyrproject-rtos/zephyr pull request #47495
Opened 2022-07-07 12:21 UTC by FRASTM

This adds a new stm32f412Rx in the list of stm32F4 devices.
The module stm32cube/stm32f4/soc/stm32f412rx.h exists

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/47232

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-07-07 12:31 UTC, erwango requested changes

2022-07-07 13:01 UTC, FRASTM commented on soc/arm/st_stm32/stm32f4/Kconfig.soc
> +
done

2022-07-07 14:31 UTC, erwango approved these changes

2022-07-08 08:49 UTC, carlescufi approved these changes

2022-07-08 08:49 UTC, merged