Nffs example
zephyrproject-rtos/zephyr pull request #4751
Opened 2017-11-06 17:45 UTC by koffes

I have created a NFFS file system example for NRF52 devices. This example creates a file system in flash if it does not already exist and writes a file to it. For each target power cycle the file will be read and a counter in the file incremented. Hopefully, this example will make using NFFS much easier.

2017-11-07 08:59 UTC, rbtchc commented
I believe that you'll have to fix your coding style first before this can be merged.
ref: http://docs.zephyrproject.org/contribute/contribute_guidelines.html#coding-style

2017-11-07 09:34 UTC, carlescufi commented
@koffes First things first, you need checkpatch to pass. Try running it locally or check the errors generated by Shippable.

2017-11-07 09:35 UTC, carlescufi commented
@koffes Also, the commit message must be preceded by a prefix. For example:

samples: fs: Add an NFFS sample

2017-11-07 19:11 UTC, dbkinder requested changes

2017-11-07 19:11 UTC, dbkinder commented on samples/ext/nffs/README.rst
> +
Add information about installing the nRF5x Command Line Tools (in particular, ``nrfjprog``) as a requirement. It looks like they're included when installing the SEGGER software, but you should clarify that here.  I found [this Nordic material](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.tools%2Fdita%2Ftools%2Fnrf5x_command_line_tools%2Fnrf5x_installation.html) that might be worth linking to as well.

2017-11-13 10:07 UTC, koffes commented
Thank you for the feedback. I am held up by a few other tasks now, but will address these issues as soon as possible.

2017-11-20 15:04 UTC, nvlsianpu commented
@koffes this PR need to use `cmake` instead of `make` now.

2018-02-15 07:48 UTC, nvlsianpu commented on samples/ext/nffs/prj.conf
> +CONFIG_SOC_FLASH_NRF5_DEV_NAME="NRF5_FLASH"
remove `CONFIG_SOC_FLASH_NRF5_DEV_NAME` - it was replaced by device tree property - so now you should use macro auto-generated FLASH_DEV_NAME for calls to nRF5 flash driver.

2018-02-15 07:48 UTC, nvlsianpu commented on samples/ext/nffs/prj.conf
> +CONFIG_FS_NFFS_FLASH_DEV_NAME="NRF5_FLASH"
=NRF5_FLASH_DRV_NAME instead

2018-02-15 07:48 UTC, nvlsianpu commented on samples/ext/nffs/src/main.c
> + * Copyright (c) 2016 Nordic Semiconductor ASA
I belief this file is whole new - you can add your or your company as copyright owner.

2018-02-15 08:30 UTC, nvlsianpu requested changes

2018-02-15 08:30 UTC, nvlsianpu commented on samples/ext/nffs/Makefile
> +CONF_FILE = prj.conf
zephyr migrated form make to cmake.

Cmake should looks like this:
```
# Standard Zephyr application boilerplate.
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
project(NONE)

target_sources(app PRIVATE
    src/main.c
)

zephyr_link_libraries(
    NFFS
)
```

2018-02-15 08:32 UTC, nvlsianpu commented
Please rebase you work on top of the master - looks like you start from quite old master.

2018-02-16 07:56 UTC, koffes commented
Thank you for your comments. Yes, this work was done some time ago and consequently, a lot of alterations has to be done. Unfortunately, my efforts has been directed elsewhere. Perhaps someone else can continue on this PR?

2018-02-20 08:25 UTC, nvlsianpu commented
@koffes - unfortunately we all have lot of works, so I don't expect that someone else will take over the PR. But thank for communicate this early.

2018-05-28 20:59 UTC, nashif commented
outdated, closing. Reopen with updates/rebase if needed.

2018-05-28 20:59 UTC, closed without merging