Bluetooth: Controller: Fix jitter in offsets for Extended and Periodic Advertising
zephyrproject-rtos/zephyr pull request #47619
Opened 2022-07-11 12:08 UTC by cvinayak

Updated ticker implementation to return remainder value for
a ticker when enumerating active tickers with time
reservations.

This is required to find offsets and to use the remainder
value to correctly calculate auxiliary offsets to the
microsecond resolution.

Use macro to adjust ticks for jitter stored in remainder
value.

Use remainder value in scheduling the periodic auxiliary
PDUs and use the ticker next slot get interface with
remainder value to fill the auxiliary offsets with
microsecond precision in the primary channel PDUs.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2022-07-26 13:39 UTC, ppryga requested changes

2022-07-26 13:39 UTC, ppryga commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ticker.h
> +#define HAL_TICKER_REMOVE_JITTER(t, r) \
Why macro? Wouldn't a function be better option? It does a type checking.

2022-07-26 13:39 UTC, ppryga commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ticker.h
> +			r += 30517578UL; \
Please change a magic number into named constant. The same value is repeated in multiple places hence it is a great candidate to be named constant.

2022-07-26 13:39 UTC, ppryga commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ticker.h
> +/* Macro returning remainder in picoseconds */
Was it an error in former description of the macro?

2022-07-26 13:39 UTC, ppryga commented on subsys/bluetooth/controller/ll_sw/lll_adv.h
> +	uint32_t us_offset;
These members names does not say anything about reference point for these offsets. Hence one is forced to get to struct and luckily read the comment above. I suggest to change these names.
```suggestion
	uint32_t prim_adv_ticks_offset;
	uint32_t prim_adv_us_offset;
```

2022-08-02 06:03 UTC, cvinayak commented on subsys/bluetooth/controller/Kconfig.ll_sw_split
> +	depends on BT_BROADCASTER && BT_CTLR_ADV_EXT
just being consistent with the hierarchy of features

2022-08-02 08:55 UTC, kruithofa approved these changes

2022-08-02 10:35 UTC, ppryga approved these changes

2022-08-02 10:54 UTC, merged