build: Overlay build vars expand ${ZEPHYR_<module>_MODULE_DIR}
zephyrproject-rtos/zephyr pull request #47638
Opened 2022-07-11 14:25 UTC by gregshue

Support referencing module directories by name in CONF_FILE,
OVERLAY_CONFIG, and DTC_OVERLAY_FILE so that projects can reference
overlay files in arbitrary modules.

Fixes #41830

Signed-off-by: Gregory Shue <gregory.shue@legrand.us>

2022-07-22 11:37 UTC, de-nordic submitted a review, later dismissed

2022-08-02 10:15 UTC, tejlmand requested changes
Please push the correct and approved version.

Current version is older with unaddressed comments.

2022-08-02 10:15 UTC, tejlmand commented on doc/develop/application/index.rst
> +   set(CONF_FILE "\${ZEPHYR_MODULENAME_MODULE_DIR}/<module-relative-pathname>")
Could you please push the correct version ?

This is old version where changes was requested here:
https://github.com/zephyrproject-rtos/zephyr/pull/42057#discussion_r807340997

**note** you most likely need to manually expand collapsed comments in githug for the link to take you to the right comment.
Old comment copy:
> Looking at the rendered output, I feel this particular feature fills to much, compared to the description of the other parts:
![image](https://user-images.githubusercontent.com/9802583/154154022-eb50bd05-19f4-4282-83be-81c4b4ca8b09.png)
>
> How about just a short mentioning of this possibility, for example:
```suggestion
``DTC_OVERLAY_FILE``. A file in a Zephyr module can be referred by escaping the Zephyr module dir variable like this ``\${ZEPHYR_<module>_MODULE_DIR}/<path-to>/<file>`` when setting any of said variables.
```

2022-08-02 15:12 UTC, gregshue commented
@tejlmand Thank you for pointing out my mistake.  I have corrected the changes that I could map to the current files.  Some of the relevant documentation has been restructured.  I will need some guidance on further documentation updates.

2022-09-08 13:28 UTC, tejlmand submitted a review, later dismissed
lgtm

2022-09-13 22:49 UTC, mbolivar-nordic submitted a review, later dismissed

2022-09-14 07:43 UTC, de-nordic submitted a review, later dismissed

2022-10-12 22:47 UTC, gregshue commented
Rebased, updated test source to new ZTest API.

2022-10-13 07:03 UTC, tejlmand approved these changes

2022-10-13 10:04 UTC, mbolivar-nordic approved these changes

2022-10-13 10:04 UTC, merged