ztest: Remove uses of ztest mock
zephyrproject-rtos/zephyr pull request #47651
Opened 2022-07-11 17:54 UTC by yperess

This PR (split into multiple commits) removes references to ztest mock in favor of FFF.

2022-07-13 00:34 UTC, aaronemassey requested changes

2022-07-13 05:19 UTC, yperess commented on tests/subsys/openthread/radio_test.c
> +	set_expected_match_values(IEEE802154_CONFIG_AUTO_ACK_FPB, NULL, false, false);
Done

2022-07-13 05:19 UTC, yperess commented on tests/subsys/openthread/radio_test.c
> +	enum ieee802154_hw_caps return_values[] = {
It was just more concise this way, there's no real reason.

2022-07-13 05:34 UTC, yperess commented on tests/bluetooth/ctrl_isoal/src/main.c
> -	ztest_expect_value(sink_sdu_alloc_test, sink_ctx, &isoal_global.sink_state[sink_hdl]);
All the asserts are there, it's just hard to visually map them. Some asserts are in the custom_sink_sdu_alloc_test function, while most of the asserts just moved below the function call

2022-07-13 16:51 UTC, aaronemassey submitted a review, later dismissed

2022-07-21 07:50 UTC, thoh-ot approved these changes

2022-07-21 14:17 UTC, aaronemassey approved these changes

2022-07-22 08:32 UTC, merged