boards: Add TDK RoboKit1 for testing Sensors
zephyrproject-rtos/zephyr pull request #47863
Opened 2022-07-15 15:48 UTC by teburd

Has a lot of great sensors on it including a very fast 6 axis IMU,
atmospheric, and time of flight sensors.

This is a fantastic board to test sensors and algorithms on.

Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

2022-07-18 15:46 UTC, MaureenHelm approved these changes, later dismissed

2022-07-18 16:09 UTC, teburd commented
Removed the ADC from the board support yaml for now to remove (hopefully) the remaining CI error.

2022-07-18 17:27 UTC, MaureenHelm approved these changes, later dismissed

2022-07-24 09:13 UTC, nandojve requested changes

2022-07-24 09:13 UTC, nandojve commented on boards/arm/tdk_robokit1/doc/index.rst
> ++-----------+------------+-------------------------------------+
Let's move to new table entry format. You can use below as reference: https://github.com/zephyrproject-rtos/zephyr/blob/6ede1da43494da3840b2f270de955f6bf11cbbf0/boards/arm/gd32f450z_eval/doc/index.rst#L54-L86

2022-08-01 19:41 UTC, nandojve requested changes

2022-08-01 19:41 UTC, nandojve commented on boards/arm/tdk_robokit1/tdk_robokit1_defconfig
> +CONFIG_GPIO=y
```diff
-CONFIG_UART_SAM=y
-CONFIG_GPIO=y
```

Those are enabled by devicetree right now. I think you can  drop it.

2022-08-01 20:15 UTC, nandojve approved these changes

2022-08-01 20:45 UTC, MaureenHelm approved these changes

2022-08-01 20:45 UTC, merged