test: Update the new ZTEST APIs tests/net/socket/poll
zephyrproject-rtos/zephyr pull request #48207
Opened 2022-07-23 03:19 UTC by hunterhu3000

TEST=twister -T tests/net/socket/poll

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

2022-07-25 08:54 UTC, rlubos submitted a review, later dismissed

2022-07-25 14:44 UTC, enjiamai approved these changes, later dismissed

2022-07-25 15:14 UTC, nashif requested changes

2022-07-25 15:14 UTC, nashif commented on tests/net/socket/poll/src/main.c
> +ZTEST(socket_poll_test_suite, test_poll)
no need for _test_suite here.

2022-07-28 11:28 UTC, hunterhu3000 commented on tests/net/socket/poll/src/main.c
> +ZTEST(socket_poll_test_suite, test_poll)
Updated. Thanks to review.

2022-07-28 14:38 UTC, nashif approved these changes

2022-07-28 14:46 UTC, rlubos approved these changes

2022-07-28 14:50 UTC, merged

2022-07-29 09:19 UTC, hunterhu3000 commented
This test case cannot be run with CONFIG_ZTEST_SHUFFLE =y, as some of the test case cannot be run twice.