test: Update the new ZTEST APIs tests/net/socket/af_packet_ipproto_raw
zephyrproject-rtos/zephyr pull request #48200
Opened 2022-07-23 02:39 UTC by hunterhu3000

TEST=twister -T tests/net/socket/af_packet_ipproto_raw

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

2022-07-25 08:40 UTC, rlubos approved these changes, later dismissed

2022-07-25 14:33 UTC, enjiamai submitted a review, later dismissed

2022-07-25 15:15 UTC, nashif requested changes

2022-07-25 15:15 UTC, nashif commented on tests/net/socket/af_packet_ipproto_raw/src/main.c
> +ZTEST(sckt_packet_raw_ip_test_suite, test_sckt_raw_packet_raw_ip)
no need for _test_suite here.

2022-07-28 09:41 UTC, hunterhu3000 commented on tests/net/socket/af_packet_ipproto_raw/src/main.c
> +ZTEST(sckt_packet_raw_ip_test_suite, test_sckt_raw_packet_raw_ip)
> no need for _test_suite here.

Updated, thanks to review

2022-07-28 14:41 UTC, nashif approved these changes

2022-07-28 14:48 UTC, rlubos approved these changes

2022-07-28 14:49 UTC, merged

2022-07-29 09:15 UTC, hunterhu3000 commented
This test case cannot be run with CONFIG_ZTEST_SHUFFLE =y, as some of the test case cannot be run twice.