test: Update the new ZTEST APIs tests/net/socket/websocket
zephyrproject-rtos/zephyr pull request #48224
Opened 2022-07-24 03:18 UTC by hunterhu3000

TEST=twister -T tests/net/socket/websocket

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

2022-07-25 11:08 UTC, rlubos approved these changes, later dismissed

2022-07-25 14:53 UTC, enjiamai approved these changes, later dismissed

2022-07-25 15:11 UTC, nashif requested changes

2022-07-30 13:04 UTC, hunterhu3000 commented on tests/net/socket/websocket/src/main.c
> +ZTEST(websocket_test_suite, test_recv_1_byte)
Updated. Thanks to review.

2022-07-30 13:05 UTC, hunterhu3000 commented
CONFIG_ZTEST_SHUFFLE=y can be turned on

2022-08-01 09:29 UTC, rlubos approved these changes, later dismissed

2022-08-14 01:43 UTC, enjiamai approved these changes, later dismissed

2022-08-23 05:28 UTC, enjiamai approved these changes

2022-08-29 14:45 UTC, rlubos approved these changes

2022-09-06 15:15 UTC, hunterhu3000 commented
@nashif Thanks to review and +1, so that the PR can be merged into the mainline.

2022-09-06 15:25 UTC, hunterhu3000 commented
@enjiamai  the numbers in the function name is not added by me, it was there before.
@nashif Thank to review and +1, so that the patch can be merged to mainline.

2022-09-13 15:33 UTC, stephanosio approved these changes

2022-10-19 01:28 UTC, hunterhu3000 commented
@nashif can we merge this PR?

2023-01-03 00:31 UTC, closed without merging