samples: basic: blink_led: add support PWM for the stm32f4_disco
zephyrproject-rtos/zephyr pull request #4824
Opened 2017-11-09 05:37 UTC by spring-z

Fix #4760
Signed-off-by: Zhang WenChao <zhangwenchao001@gmail.com>

2017-11-09 05:39 UTC, spring-z commented
@galak @erwango 
Sorry.thank you for your help

2017-11-09 13:23 UTC, spring-z commented
[![YouTube Video](https://img.youtube.com/vi/nCQjuAUB0wU/0.jpg)](https://www.youtube.com/watch?v=nCQjuAUB0wU)

2017-11-09 13:53 UTC, erwango requested changes
Fix is ok.

Miss some doc:
-Update samples/basic/blink_led/README.rst

Then split the change into 2 commits:
*board: Add PWM2 on stm32f4_disco
*sample: blink_led: Add support for stm32f4_disco

Then ok for merge

2017-11-09 15:38 UTC, spring-z commented
successful check @erwango

2017-11-09 15:49 UTC, dbkinder requested changes
A little fix to the heading and otherwise looks good.

2017-11-09 15:49 UTC, dbkinder commented on samples/basic/blink_led/README.rst
> +Nucleo_F401RE and Nucleo_L476RG and STM32F4_DISCOVERY
change to:

    Nucleo_F401RE, Nucleo_L476RG, and STM32F4_DISCOVERY

2017-11-09 16:00 UTC, spring-z commented
Already modified, thanks. @dbkinder

2017-11-09 16:26 UTC, dbkinder approved these changes

2017-11-12 07:00 UTC, spring-z commented
@erwango

2017-11-13 15:35 UTC, galak approved these changes

2017-11-13 15:56 UTC, erwango approved these changes

2017-11-14 12:04 UTC, merged