subsys: lorawan: upgrade to LoRaMAC-node v4.6.0
zephyrproject-rtos/zephyr pull request #48418
Opened 2022-07-28 12:33 UTC by martinjaeger

This release contains some bug fixes and improvements in the upstream repo.

See below link for details:
https://github.com/Lora-net/LoRaMac-node/releases/tag/v4.6.0

As discussed in Discord, @JordanYates and I propose to name the branches in our tracking repo based on the upstream LoRaMAC-node release instead of the Zephyr release. I've already created a branch [v4.6.0-zephyr](https://github.com/zephyrproject-rtos/loramac-node/tree/v4.6.0-zephyr) with the necessary 2 commits for Zephyr integration cherry-picked from the previous branch. If you disagree with the approach, just let me know a different way for the update to happen.

2022-07-28 12:49 UTC, martinjaeger commented on subsys/lorawan/lorawan.c
> +			       mcps_indication->IsUplinkTxPending == 1,
I blindly changed the name based on the following upstream change:
https://github.com/Lora-net/LoRaMac-node/commit/edff6ce161773e888687a9cd352ce2e2234e6b0d

However, I just got quite confused by the name. In my understanding, the `FramePending` indicated that there is another downlink message pending on the server and that we should send another uplink message to open a receive window for that pending message.

Here is the original discussion for that change:
https://github.com/Lora-net/LoRaMac-node/discussions/1142

I'll probably at least add a comment that it's actually a downlink rx message that is pending... or did I get something wrong?

2022-08-01 05:53 UTC, Mani-Sadhasivam commented
> As discussed in Discord, @JordanYates and I propose to name the branches in our tracking repo based on the upstream LoRaMAC-node release instead of the Zephyr release. I've already created a branch [v4.6.0-zephyr](https://github.com/zephyrproject-rtos/loramac-node/tree/v4.6.0-zephyr) with the necessary 2 commits for Zephyr integration cherry-picked from the previous branch. If you disagree with the approach, just let me know a different way for the update to happen.

The reason for naming the branch against the Zephyr release was to indicate to which Zephyr release the branch corresponds. But having the upstream release info is not a bad idea also. How about using both?

2022-08-01 06:00 UTC, martinjaeger commented
> How about using both?

I think that may get confusing because we don't want to create a dedicated LoRaMAC-node branch for every Zephyr release even if nothing was changed, so people may wonder why e.g. Zephyr v3.5 is still using a loramac branch named zephyr-v3.1.

2022-08-01 14:15 UTC, Mani-Sadhasivam commented
> > How about using both?
> 
> I think that may get confusing because we don't want to create a dedicated LoRaMAC-node branch for every Zephyr release even if nothing was changed, so people may wonder why e.g. Zephyr v3.5 is still using a loramac branch named zephyr-v3.1.

Fair enough!

2022-08-01 14:16 UTC, Mani-Sadhasivam approved these changes, later dismissed

2022-08-02 08:02 UTC, JordanYates requested changes
Functionality looks fine, commit title needs to remove the `subsys:`

2022-08-02 08:19 UTC, martinjaeger commented
Yeah, seen the CI error with the commit title already, but I wanted to wait for your comments regarding the variable name before pushing the fix.

@Mani-Sadhasivam and @JordanYates do you also find the `IsUplinkTxPending` name confusing / wrong, or is it just me?

2022-08-02 10:12 UTC, JordanYates commented
I agree the name is bad, but it’s constrained to the lorawan driver, and it comes from the upstream code, so I’m not sure we need to do anything. If you want to add a comment where it’s used that would be good I guess

2022-08-02 11:06 UTC, martinjaeger commented on subsys/lorawan/lorawan.c
> +			       mcps_indication->IsUplinkTxPending == 1,
Added a comment to clarify the confusing name.

2022-08-02 15:02 UTC, Mani-Sadhasivam commented
> Yeah, seen the CI error with the commit title already, but I wanted to wait for your comments regarding the variable name before pushing the fix.
> 
> @Mani-Sadhasivam and @JordanYates do you also find the `IsUplinkTxPending` name confusing / wrong, or is it just me?

It is confusing indeed... But we should just cope with it as we don't want to carry a commit for changing the name.

2022-08-02 15:07 UTC, martinjaeger commented
Yep, I'll think about submitting a PR upstream. But for now let's keep it as is. Could you please re-approve @Mani-Sadhasivam?

2022-08-02 22:49 UTC, JordanYates approved these changes

2022-08-03 01:09 UTC, Mani-Sadhasivam approved these changes

2022-08-03 04:02 UTC, merged