ztest: Fix logic for SUITE_SKIP
zephyrproject-rtos/zephyr pull request #48542
Opened 2022-08-01 21:07 UTC by asemjonovs

When ZTEST setup fails z_assume, we should mark all tests within
suite as skipped.

Signed-off-by: Al Semjonovs <asemjonovs@google.com>

2022-08-02 15:44 UTC, yperess approved these changes

2022-08-02 15:49 UTC, henrikbrixandersen requested changes
I don't believe a failed assumption in setup or before stages should be marked as the whole suite being skipped. It should mark the entire suite as having failed (or even use a new result type for distinguishing the two).

A test suite needs to be able to test prerequisites common to all its test cases and error out in setup if they are not met (think e.g. `device_is_ready()` or other DUT test initialization that may fail).

2022-08-03 17:42 UTC, yperess commented
> I don't believe a failed assumption in setup or before stages should be marked as the whole suite being skipped. It should mark the entire suite as having failed (or even use a new result type for distinguishing the two).
> 
> A test suite needs to be able to test prerequisites common to all its test cases and error out in setup if they are not met (think e.g. `device_is_ready()` or other DUT test initialization that may fail).

The idea of an assumption is that the test is invalid if the assumption failed. It should not fail the test. If you want the test to fail, you should use an assert. The point of assumptions is to reduce noise and avoid having a lot of failed tests when 1 failure occurs, if developers don't want to use it, they're free to use asserts (you can simply move your assert to `before` which will just fail every test in the suite).

2022-08-03 20:55 UTC, aaronemassey approved these changes

2022-08-04 08:28 UTC, str4t0m approved these changes

2022-08-04 15:47 UTC, henrikbrixandersen approved these changes
I think we need to come up with a standard pattern for testing ztest suite prerequisites.

2022-08-05 15:54 UTC, merged