Atmel Saml2x dts fix
zephyrproject-rtos/zephyr pull request #48668
Opened 2022-08-04 00:57 UTC by jmalbers

Update device tree entries for Atmel SAML2x socs.

2022-08-04 18:15 UTC, stephanosio requested changes
Please review the [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines) and re-format the commit message.

2022-08-04 23:21 UTC, jmalbers commented
Thanks for the help. First timer here :)

2022-08-07 10:50 UTC, nandojve commented
Hi @jmalbers ,

Thank you for look on this. I noted that there are peripherals that you are moving which has same register address. The devicetree should keep shared address at only one file and describe the difference in the more specific file. Try follow [samv71q21b.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/atmel/samv71q21b.dtsi) as referece.
You need structure the change using same principle.

2022-08-07 20:24 UTC, jmalbers commented
> Hi @jmalbers ,
> 
> Thank you for look on this. I noted that there are peripherals that you are moving which has same register address. The devicetree should keep shared address at only one file and describe the difference in the more specific file. Try follow [samv71q21b.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/atmel/samv71q21b.dtsi) as referece. You need structure the change using same principle.

Missed a few I see! Thanks for pointing this out :)

2022-08-15 16:38 UTC, nandojve requested changes

2022-08-15 16:38 UTC, nandojve commented on dts/arm/atmel/saml2x.dtsi
> +
This line is not necessary

2022-08-15 16:38 UTC, nandojve commented on dts/arm/atmel/saml21.dtsi
> +		nvmctrl: nvmctrl@41004000  {
nvmctrl@41004000 is the same for L21/22. There is a big error at Figure 8-1. SAM L22 Product Mapping datasheet on the AHB-APB Bridge B part. The prefix of AHB-APB Bridge B is 0x41xx-xxxx and there are entries with 0x40xx-xxxx which is complete wrong.

2022-08-15 16:38 UTC, nandojve commented on dts/arm/atmel/saml21.dtsi
> +				reg = <0 0x40000>;
flash@0 reg property should be defined on a file named saml21x18.dtsi
idem with sram0: memory@20000000, the reg property should be at saml21x18.dtsi file too.

Same principle of https://github.com/zephyrproject-rtos/zephyr/blob/32f4b6e09a85c4886767df93d8a6c4297b79b009/dts/arm/atmel/samd5xx20.dtsi#L7-L22

2022-08-28 10:33 UTC, nandojve commented
Hi @jmalbers ,

I was wondering if you had time to look comments. I would like to have it for next release but a few work still needed. Please, let us know if you still have interest and time to finish work.

2022-08-29 06:44 UTC, jmalbers commented
Sorry, let this sit for a while. I'll have a look at it again this week.

2022-09-18 15:42 UTC, nandojve commented
Hi @jmalbers ,

You need rebase and keep your commits on top of main without merge commits.
May you update?

2022-10-05 15:43 UTC, nandojve commented
Hi @jmalbers ,

Merge windows is open again and we can continue work here.

2022-12-19 00:30 UTC, closed without merging