Format correct thread
zephyrproject-rtos/zephyr pull request #48767
Opened 2022-08-08 05:33 UTC by Zhaoningx

Move thread testcases of the tests/kernel/thread to new ZTEST api.

2022-08-08 15:49 UTC, andyross submitted a review, later dismissed

2022-08-08 18:18 UTC, dcpleung requested changes

2022-08-08 18:18 UTC, dcpleung commented on arch/x86/core/fatal.c
> +	printk("arch_system_halt in X86\n");
Please remove in this commit.

2022-08-09 03:21 UTC, Zhaoningx commented
Hi @andyross @dcpleung, I have addressed the comment and done some changes for thread init test cases, could you help to review this PR again? Thanks.

By the way, I don't know what should I do for the CI building failure, have you seen this failure log? Thanks.

2022-08-09 16:55 UTC, dcpleung commented
Errr.. the error said to increase `CONFIG_MAX_THREAD_BYTES`.

2022-08-10 02:33 UTC, enjiamai commented
I saw another failure like this, anyone knows how to solve it? 

```
INFO    -  74/406 degu_evk                  tests/kernel/threads/thread_apis/kernel.threads.apis FAILED Build failure (build)
INFO    - /__w/zephyr/zephyr/twister-out/degu_evk/tests/kernel/threads/thread_apis/kernel.threads.apis/build.log

.....

-- Found assembler: /opt/toolchains/zephyr-sdk-0.14.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
CMake Warning at ../../../../subsys/usb/device/CMakeLists.txt:22 (message):
  CONFIG_USB_DEVICE_VID has default value 0x2FE3.

  This value is only for testing and MUST be configured for USB products.


CMake Warning at ../../../../subsys/usb/device/CMakeLists.txt:28 (message):
  CONFIG_USB_DEVICE_PID has default value 0x100.

  This value is only for testing and MUST be configured for USB products.
```

2022-08-10 03:11 UTC, Zhaoningx commented
> Errr.. the error said to increase `CONFIG_MAX_THREAD_BYTES`.

Hi @dcpleung, thanks for your help, I have updated the PR.

2022-08-10 03:25 UTC, enjiamai approved these changes

2022-08-10 03:27 UTC, Zhaoningx commented
> I saw another failure like this, anyone knows how to solve it?
> 
> ```
> INFO    -  74/406 degu_evk                  tests/kernel/threads/thread_apis/kernel.threads.apis FAILED Build failure (build)
> INFO    - /__w/zephyr/zephyr/twister-out/degu_evk/tests/kernel/threads/thread_apis/kernel.threads.apis/build.log
> 
> .....
> 
> -- Found assembler: /opt/toolchains/zephyr-sdk-0.14.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
> CMake Warning at ../../../../subsys/usb/device/CMakeLists.txt:22 (message):
>   CONFIG_USB_DEVICE_VID has default value 0x2FE3.
> 
>   This value is only for testing and MUST be configured for USB products.
> 
> 
> CMake Warning at ../../../../subsys/usb/device/CMakeLists.txt:28 (message):
>   CONFIG_USB_DEVICE_PID has default value 0x100.
> 
>   This value is only for testing and MUST be configured for USB products.
> ```

Hi @enjiamai, it seems the CI failure has been addressed. Thanks.

2022-08-10 17:57 UTC, dcpleung approved these changes

2022-08-12 15:39 UTC, merged