device.h: Allow DEVICE_DT_GET to accept DTS node or DTS node label
zephyrproject-rtos/zephyr pull request #48872
Opened 2022-08-10 14:02 UTC by de-nordic

Usage of DEVICE_DT_GET requires node identifier and is often
invoked with DT_NODELABEL(...) to get such identifier, from the
node label.
The change allows to use DEVICE_DT_GET with either node identifier
or node label directly.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2022-08-10 14:07 UTC, galak requested changes
I'm not sure this makes sense.  This is effectively allowing 2 different types to `DEVICE_DT_GET()`.

What is the purpose/reason for this?

I could see adding a DEVICE_DT_NODELABEL_GET() but not sure how much value that is compared to `DEVICE_DT_GET(DT_NODELABEL(node))`

2022-08-10 15:20 UTC, de-nordic commented
> I'm not sure this makes sense. This is effectively allowing 2 different types to `DEVICE_DT_GET()`.

You mean two versions of invocations, right? Then yes it does.
> 
> What is the purpose/reason for this?
> 
> I could see adding a DEVICE_DT_NODELABEL_GET() but not sure how much value that is compared to `DEVICE_DT_GET(DT_NODELABEL(node))`

The value is that you do not have to do the `DT_NODELABEL` (or `DEVICE_DT_NODELABEL_GET`).
Using `DEVICE_DT_GET` with `DT_NODELABEL` is quite often, in out-of-tree code it is probably even more often because people would rather use node labels than IDs (using it with DT_CHOSEN would be another case).

Why not just allow `DEVICE_DT_GET` to directly accept either node or node label.

2022-08-10 15:28 UTC, galak commented
> > ``
> 
> The value is that you do not have to do the `DT_NODELABEL` (or `DEVICE_DT_NODELABEL_GET`). Using `DEVICE_DT_GET` with `DT_NODELABEL` is quite often, in out-of-tree code it is probably even more often because people would rather use node labels than IDs (using it with DT_CHOSEN would be another case).
> 
> Why not just allow `DEVICE_DT_GET` to directly accept either node or node label.

Would like @mbolivar-nordic take, but this feels off to me to mix a "node" specifier and nodelabel.

2022-08-19 00:11 UTC, mbolivar-nordic commented
Yeah, I don't like this kind of thing. I would be OK with DEVICE_DT_GET_BY_NODE_LABEL, or DEVICE_DT_GET_BY_NL even for short, but let's not overload this macro, please.

2022-08-22 13:49 UTC, closed without merging