doc: restore doc build filtering of warnings
zephyrproject-rtos/zephyr pull request #4890
Opened 2017-11-11 01:02 UTC by dbkinder

PR #4875 caused previously filtered warning messages to display
even though they're "known" messages that were intended to be
filtered out of the doc build output.  We only want to display
"unknown" messages from the doc building step.

Problem that PR #4875 attempted to fix (I think) was when the
sphinx-build step fails with an error, make does not continue
with the next step in the list of make commands (and that step
would have displayed the error message sphinx-build encountered).

By prefixing the sphinx-build step with a "-", we tell make to
continue in the presence of errors, and the filter-doc-log.sh
script on the next line can write out any "unknown" messages.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

2017-11-11 01:08 UTC, nashif requested changes
I lost 1 day of debugging because of how we hide all output of the build process. We should not really care showing warnings that are known, the problem that remains here is that documentation can't fail because missing dependencies or wrong python packages without any output to the console, this is really bad and makes users wonder what the hell is going on like what happened to a few of us in the last 2 days.

2017-11-11 01:14 UTC, dbkinder commented
This PR fixes that, and lets the step following sphinx-build do it's job.  Make stopped it early.  Without this PR, successful doc builds write a bunch of messages that confuse folks (and why the whole message filtering process was put in place.)  I tested this PR out by forcing sphinx-build to get an error (I removed the doc theme it was looking for) and that error was displayed.

2017-11-11 15:11 UTC, nashif commented
not showing warnings/errors was probably a mistake, we are just hiding the problem and also make it look like all is great when it is not. Also, some other issues might not be caught when redirecting all the output to files, I prefer to have warning on the screen and show developers what their change introduced on top, see #4892 which has this implemented.

2017-11-13 21:22 UTC, dbkinder commented
Sigh. OK.

2017-11-14 11:48 UTC, nashif commented
not needed anymore

2017-11-14 11:48 UTC, closed without merging