devicetree: Add base property "model"
zephyrproject-rtos/zephyr pull request #49259
Opened 2022-08-19 03:54 UTC by galak

Add "model" property to base.yaml as its a standard property defined
by the devicetree spec.  Being a simple standard property, add it to
the list of properties that are automatically handled.

Signed-off-by: Kumar Gala <galak@kernel.org>

2022-08-19 04:01 UTC, mbolivar-nordic reviewed
Do you really mean to add this to every binding? I thought model was just a root node property or something like that.

Also, what is it needed for in zephyr?

2022-08-19 04:14 UTC, galak commented
> Do you really mean to add this to every binding? I thought model was just a root node property or something like that.
> 

I did, was basing that on what is defined in 2.3 Standard Properties of the DTS spec. (v0.4-rc1)

> Also, what is it needed for in zephyr?

1. completeness since we define model in our dtsi, we should probably have it specified in a binding.
2. provide model if the sensor subystem work ends up using it
3. allow model to be used to default CONFIG_BOARD value.

2022-08-19 04:15 UTC, galak commented
#49260 shows a use of 'model' property.

2022-08-19 05:01 UTC, mbolivar-nordic commented
> I did, was basing that on what is defined in 2.3 Standard Properties of the DTS spec. (v0.4-rc1)

Yeah, I read that too, but then I grepped around for it in linux and it seems like it's only used to define the model for an entire platform as a root node property, from what I could tell. Do you have any counterexamples?

> #49260 shows a use of 'model' property.

That's an example where we really want it only for the root node :). Do you have any use case for other nodes?

2022-08-19 19:20 UTC, galak commented
@mbolivar-nordic here's a PR from @MaureenHelm that introduces model usage outside of top level.

2022-08-19 20:05 UTC, MaureenHelm approved these changes
That's convenient. I didn't know `model` was a standard property defined in the devicetree spec.

2022-08-25 21:11 UTC, mbolivar-nordic commented
> @mbolivar-nordic here's a PR from @MaureenHelm that introduces model usage outside of top level.

But that's just in Zephyr, right? I'm asking about Linux :)

2022-08-25 21:13 UTC, mbolivar-nordic requested changes
I would really like to see explicit references to usage of `model` outside of specifying the model name for the entire device that a particular devicetree is ... modeling (ugh, sorry), before we merge this. My concern is whether we are using model in a way that it wasn't intended for by adding it to all nodes, and that the DT spec is just being its usual unclear self about where this property is allowed / expected to go.

2022-09-12 20:18 UTC, mbolivar-nordic commented
> @mbolivar-nordic there are some uses of `model` in linux outside of top level:

I don't think this is convincing. I sent an email to the spec mailing list and cc'ed you with more details.

2022-09-12 20:25 UTC, mbolivar-nordic commented
(TL;DR your examples are mostly in a single subsystem, which might be doing it wrong, and I would have expected `model` in dt-schema/meta-schemas/core.yaml if you were right.)

2022-09-13 16:57 UTC, galak commented
@mbolivar-nordic how would we handle getting `model` prop generation for the root node?  I don't think it makes sense to have a binding for every board.  (if we want access to the model string that describes the board).

I get the sense of having this be like how we are dealing with `label` that its done on a per binding basis and not in `base.yaml`.

2022-09-13 18:23 UTC, mbolivar-nordic commented
> @mbolivar-nordic how would we handle getting `model` prop generation for the root node?

I think we probably shouldn't do that; Rob explicitly discouraged that.

> I don't think it makes sense to have a binding for every board. (if we want access to the model string that describes the board).

Perhaps a magic zephyr,board property in the root node that we special case in edtlib, like the /zephyr,user node? Something like that.

> I get the sense of having this be like how we are dealing with label that its done on a per binding basis and not in base.yaml.

Yep, something like that for where it's explicitly needed and we have a good use case like linux audio.

2022-11-27 00:30 UTC, closed without merging