tests:ipc_service: Add ipc_service test of deregistered endpoint
zephyrproject-rtos/zephyr pull request #49273
Opened 2022-08-19 09:17 UTC by jacksonc-xlnx

This adds an additional test to the ipc_service test suite whereby the
test attempts to deregister the endpoint from the ipc_service instance
and then send a message to that endpoint - this should fail with
-ENOENT.

Signed-off-by: Jackson Cooper-Driver <jackson.cooper---driver@amd.com>

2022-10-07 07:11 UTC, carlocaione commented
@jacksonc-xlnx can you rebase?

2022-10-07 08:19 UTC, carlocaione submitted a review, later dismissed

2022-10-11 08:17 UTC, stephanosio requested changes

2022-10-11 08:17 UTC, stephanosio commented on tests/subsys/ipc/ipc_service/src/backend.c
> +	data->cfg = 0;
```suggestion
	data->cfg = NULL;
```

2022-10-11 09:00 UTC, carlocaione approved these changes

2022-10-11 09:26 UTC, stephanosio approved these changes

2022-10-11 11:03 UTC, carlescufi approved these changes

2022-10-11 11:03 UTC, merged