boards: Add support for Khadas Edge-V board
zephyrproject-rtos/zephyr pull request #49349
Opened 2022-08-22 13:23 UTC by hx-bora

This is an AArch64 board. We also add RK3399 SoC support.

See https://www.khadas.com/edge-v for more info about the board.

2022-08-22 13:35 UTC, carlocaione requested changes

2022-08-22 13:35 UTC, carlocaione commented on dts/arm64/rockchip/rockchip_rk3399.dtsi
> +		label = "arch_timer";
no need to have the `label` property anywhere anymore.

2022-08-22 13:35 UTC, carlocaione commented on soc/arm64/rockchip/rk3399/soc.c
> +	/* Nothing yet */
if nothing is done here can we remove this?

2022-08-22 13:35 UTC, carlocaione commented on boards/arm64/khadas_edgev/doc/index.rst
> +	tftpboot ${pxefile_addr_r} zephyr.img; bootm start ${pxefile_addr_r}; bootm loados; bootm go
is this correct? No cache flushing?

2022-08-22 13:35 UTC, carlocaione commented on drivers/serial/Kconfig.snps8250dw
> +	help
move to `depends on DT_HAS_*_ENABLED`

2022-08-22 13:35 UTC, carlocaione commented on drivers/serial/uart_snps8250dw.c
> +#define DT_DRV_COMPAT snps8250dw
the compatible should be `snps,8250dw`

2022-08-22 13:35 UTC, carlocaione commented on drivers/serial/uart_snps8250dw.c
> +}
no need to have this (and you can use `ARG_UNUSED`)

2022-08-22 13:35 UTC, carlocaione commented on soc/arm64/rockchip/rk3399/mmu_regions.c
> +			      MT_DEVICE_nGnRnE | MT_P_RW_U_NA | MT_DEFAULT_SECURE_STATE),
do not map this. Just modify the UART driver to support the device MMIO API (see `include/zephyr/sys/device_mmio.h`).

2022-08-22 17:00 UTC, galak commented on drivers/serial/Kconfig.snps_8250dw
> +config UART_SNPS_8250DW
does the 16550 driver not work for this?

2022-08-22 17:04 UTC, galak commented on dts/arm64/rockchip/rockchip_rk3399.dtsi
> +		compatible = "rockchip,rk3399-uart", "snps,8250dw";
Why isn't this using `snps,dw-apb-uart` as the linux rk3399.dtsi uses?

2022-08-22 17:06 UTC, galak requested changes, later dismissed
question about 8250 uart and if we can use 16550 driver, and use the 'snps,dw-apb-uart' compatible that linux rk3399.dtsi uses.

2022-08-23 02:00 UTC, povergoing commented on dts/arm64/rockchip/rockchip_rk3399.dtsi
> +		cpu@4 {
Just out of curiosity, generally, a53 and a72 belong to different cluster and thus have different `mpdir` aff formats, for example, a72's `mpdir` are something different like 0x100 0x200 or other formats? But here seems not the case (a72 and a53 are in the same cluster)?

2022-08-23 02:28 UTC, galak commented
Also, rename `dts/arm64/rockchip/rockchip_rk3399.dtsi` to `dts/arm64/rockchip/rk3399.dtsi`

2022-08-24 12:27 UTC, carlocaione commented
Please, split the serial changes in a different commit.

2022-09-05 14:32 UTC, carlocaione submitted a review, later dismissed

2022-10-03 15:26 UTC, carlocaione approved these changes

2022-10-07 07:11 UTC, carlocaione commented
@povergoing can you take a look?

2022-10-08 02:19 UTC, povergoing approved these changes
LGTM

2022-10-08 16:32 UTC, merged