Bluetooth: Audio: Update ASE EP state checks
zephyrproject-rtos/zephyr pull request #49421
Opened 2022-08-23 14:52 UTC by Thalley

Update the existing ASE EP state checks to be more correct
and aligned with the ASCS specification.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

2022-09-01 15:39 UTC, cvinayak requested changes
Minor changes requested, otherwise LGTM

2022-09-01 15:39 UTC, cvinayak commented on subsys/bluetooth/audio/unicast_client.c
> +			/* fall through */
```suggestion
			} /* else fall through for sink */

			/* fall through */
```

2022-09-01 15:39 UTC, cvinayak commented on subsys/bluetooth/audio/ascs.c
> +				return;
```suggestion
				default:
					BT_WARN("Invalid state transition: %s -> %s",
						bt_audio_ep_state_str(old_state),
						bt_audio_ep_state_str(ep->status.state));
					return;
```

2022-09-01 23:56 UTC, cvinayak submitted a review, later dismissed

2022-09-07 07:53 UTC, rick1082 submitted a review, later dismissed

2022-09-22 12:44 UTC, MariuszSkamra reviewed
Looks good to me, however I would highly recommend to `__ASSERT` instead of BT_WARN.
The state machine is driven by us, thus any invalid state transitions are ASCS internal fault.

2022-09-26 16:04 UTC, rick1082 approved these changes

2022-09-28 08:01 UTC, MariuszSkamra approved these changes
LGTM

2022-10-04 06:46 UTC, sjanc approved these changes
I guess you can also remove this :) 
/* TODO: Verify state changes */

2022-10-04 07:54 UTC, Thalley commented
> I guess you can also remove this :) /* TODO: Verify state changes */

Quite possibly, yes. That being said, we are doing 

```c
	old_state = ep->status.state;
	ep->status.state = state;

	/* Notify clients*/
	ase_status_changed(ep, old_state, state);
```

without verifying the state change, so I think the TODO is still valid. The change in this PR seems to only affect the callbacks later.

2022-10-04 08:33 UTC, merged