mgmt/mcumgr: Drop zst from zephyr_smp_transport_out_fn
zephyrproject-rtos/zephyr pull request #49527
Opened 2022-08-25 13:38 UTC by de-nordic

Never used and not needed.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2022-08-25 13:46 UTC, nordicjm approved these changes, later dismissed

2022-09-06 10:55 UTC, de-nordic commented
Release notes added.

2022-09-06 10:55 UTC, nordicjm commented
@de-nordic merge conflict

2022-09-06 11:05 UTC, nordicjm submitted a review, later dismissed

2022-09-06 14:24 UTC, nordicjm commented
@de-nordic needs rebase

2022-09-09 08:28 UTC, carlescufi approved these changes, later dismissed

2022-09-09 09:56 UTC, fabiobaltieri commented
@de-nordic can you rebase?

2022-09-09 10:15 UTC, nordicjm requested changes
smp_dummy.c needs changes also

2022-09-09 10:56 UTC, nordicjm submitted a review, later dismissed

2022-09-09 10:57 UTC, nvlsianpu approved these changes, later dismissed

2022-09-09 11:00 UTC, fabiobaltieri approved these changes, later dismissed

2022-09-09 11:34 UTC, fabiobaltieri commented
> Running `./zephyr/scripts/twister -T zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_echo/` gives a lot of failures, but build.log contains no reason nor any error messages.
> 
> ```
> INFO    - Total complete:   29/  43  67%  skipped:   28, failed:    0
> ERROR   - see: /repos/doer/zephyrproject-dirty/twister-out/qemu_riscv32_smp/tests/subsys/mgmt/mcumgr/os_mgmt_echo/os.mgmt.echo/build.log
> ```

```
$ git show --oneline
3f452d6642 (HEAD) doc/release: Add note on change to zephyr_smp_transport_out_fn
$ ./scripts/twister -T tests/subsys/mgmt/mcumgr/os_mgmt_echo
...
INFO    - Total complete:   43/  43  100%  skipped:   28, failed:    0
INFO    - 15 of 43 test configurations passed (100.00%), 0 failed, 28 skipped with 0 warnings in 37.59 seconds
...
$ ./scripts/twister -p qemu_riscv32_smp -v -T tests/subsys/mgmt/mcumgr/os_mgmt_echo
...
INFO    - 1/1 qemu_riscv32_smp          tests/subsys/mgmt/mcumgr/os_mgmt_echo/os.mgmt.echo PASSED (qemu 2.026s)
...
```

Looks fine here...

2022-09-09 16:42 UTC, fabiobaltieri commented
Also needs a rebase now...

2022-09-09 17:48 UTC, nordicjm approved these changes

2022-09-09 18:25 UTC, fabiobaltieri approved these changes

2022-09-09 18:25 UTC, merged