mgmt/mcumgr: Drop zephyr_ prefix from functions
zephyrproject-rtos/zephyr pull request #49528
Opened 2022-08-25 13:38 UTC by de-nordic

The MCUMgr library is now part of Zephyr, so there is no point
to prefix SMP functions with Zephyr.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2022-08-25 14:13 UTC, galak requested changes, later dismissed
This is technically a breaking API change, so should go through the API change process: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html

2022-08-25 14:38 UTC, de-nordic commented
> This is technically a breaking API change, so should go through the API change process: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html

OK, can follow that path, although nothing I have changed is available in public documentation, nor here https://docs.zephyrproject.org/latest/develop/api/overview.html.

2022-08-30 15:48 UTC, galak commented
Please update release notes for deprecation.

2022-08-31 02:53 UTC, stephanosio commented
Please rebase to fix CI failure

2022-08-31 15:17 UTC, nordicjm commented on subsys/mgmt/mcumgr/smp.c
This code can go once the other PRs are merged

2022-08-31 15:18 UTC, nordicjm approved these changes, later dismissed

2022-09-06 09:06 UTC, nordicjm commented on include/zephyr/mgmt/mcumgr/smp.h
>  					struct net_buf *nb);
nit. alignment

2022-09-06 09:06 UTC, nordicjm commented on subsys/mgmt/mcumgr/smp_uart.c
>  				  smp_uart_get_mtu, NULL, NULL);
nit. alignment

2022-09-06 09:37 UTC, carlescufi commented
We agreed with @de-nordic to follow the [stable API change procedure](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes)

2022-09-06 10:37 UTC, nordicjm commented
Needs rebase

2022-09-06 14:14 UTC, nordicjm commented on doc/releases/release-notes-3.2.rst
> +  is now replaced with c:struct:`smp_transport`, and the later one is used,
```suggestion
  is now replaced with :c:struct:`smp_transport`, and the later one is used,
```

2022-09-06 14:14 UTC, nordicjm commented on doc/releases/release-notes-3.2.rst
> +     | :C:func:`zephyr_smp_transport_init` | :c:func:`smp_transport_init`          |
Not sure if C vs c makes a difference here but rest are lowercase

2022-09-06 14:14 UTC, nordicjm commented on doc/releases/release-notes-3.2.rst
> +     | :C:func:`zephyr_smp_transport_out_fn`       | :c:func:`smp_transport_out_fn`        |
As above

2022-09-06 14:14 UTC, nordicjm commented on doc/releases/release-notes-3.2.rst
> +     | :C:func:`zephyr_smp_transport_ud_copy_fn`   | :c:func:`smp_transport_ud_copy_fn`    |
As above

2022-09-06 14:24 UTC, nordicjm commented
@de-nordic needs rebase

2022-09-07 07:58 UTC, nordicjm submitted a review, later dismissed

2022-09-07 07:58 UTC, nordicjm commented on subsys/mgmt/mcumgr/smp.c
>  			  struct net_buf *nb)
nit. alignment, can all go on one line

2022-09-08 10:53 UTC, de-nordic commented
> @de-nordic please fix the compliance issue

@carlescufi checkpatch wants me to do this
```
-                              zephyr_smp_transport_ud_free_fn *ud_free_func);
+                              zephyr_smp_transport_ud_free_fn * ud_free_func)
```
to correct "problem". Seems weird.

2022-09-08 10:58 UTC, gmarull commented
> > @de-nordic please fix the compliance issue
> 
> @carlescufi checkpatch wants me to do this
> 
> ```
> -                              zephyr_smp_transport_ud_free_fn *ud_free_func);
> +                              zephyr_smp_transport_ud_free_fn * ud_free_func)
> ```
> 
> to correct "problem". Seems weird.

check `scripts/checkpatch/typedefsfile`, btw why isn't that typedef already a pointer?

2022-09-08 11:15 UTC, nordicjm approved these changes, later dismissed

2022-09-08 11:15 UTC, nordicjm commented on include/zephyr/mgmt/mcumgr/smp.h
> +			       smp_transport_ud_free_fn *ud_free_func);
nit. alignment

2022-09-08 11:15 UTC, nordicjm commented on subsys/mgmt/mcumgr/smp.c
> +			  smp_transport_ud_free_fn *ud_free_func)
nit. alignment

2022-09-08 11:26 UTC, nordicjm approved these changes, later dismissed

2022-09-08 12:20 UTC, de-nordic commented
> check `scripts/checkpatch/typedefsfile`, btw why isn't that typedef already a pointer?

OK so I have no good reason not to fix the new definitions (the `smp_transport_`), but I do not want to touch the old `zephyr_smp_transport_` definitions which I am deprecating anyway.
@gmarull  Can the compliance issue be waved in this instance, as this has been triggered only because I have extended original declaration of `zephyr_smp_transport_init` to inline it, and actually just call `smp_transport_init`, and have it deprecated.

2022-09-08 12:27 UTC, nordicjm submitted a review, later dismissed

2022-09-09 10:13 UTC, nordicjm commented
@de-nordic needs rebase

2022-09-09 10:19 UTC, nordicjm requested changes
smp_dummy.c needs updates too

2022-09-09 11:22 UTC, nordicjm submitted a review, later dismissed

2022-09-09 17:49 UTC, nordicjm approved these changes, later dismissed

2022-09-09 19:42 UTC, nordicjm approved these changes, later dismissed

2022-09-09 20:15 UTC, nordicjm submitted a review, later dismissed

2022-09-14 10:14 UTC, nordicjm approved these changes, later dismissed

2022-09-14 10:35 UTC, nvlsianpu submitted a review, later dismissed

2022-09-14 12:04 UTC, fabiobaltieri commented
@de-nordic we are in stabilization phase, should this be considered a bugfix or part of some deprecation we need to do for v3.2? Otherwise, can we wait for v3.3 or you want this to be discussed with the TSC for merging during stabilization?

2022-09-14 12:08 UTC, de-nordic commented
> @de-nordic we are in stabilization phase, should this be considered a bugfix or part of some deprecation we need to do for v3.2? Otherwise, can we wait for v3.3 or you want this to be discussed with the TSC for merging during stabilization?

@fabiobaltieri  Lets postpone it and have it merged just after the 3.2 gets released; I think it will be more wise to introduce API change at the beginning of development cycle rather than just prior to release.

2022-10-04 10:23 UTC, nvlsianpu approved these changes, later dismissed

2022-10-06 06:53 UTC, nordicjm submitted a review, later dismissed

2022-10-06 09:02 UTC, fabiobaltieri submitted a review, later dismissed

2022-10-06 14:37 UTC, carlescufi submitted a review, later dismissed

2022-10-06 14:38 UTC, nordicjm commented
@de-nordic please rebase

2022-10-06 17:56 UTC, nvlsianpu approved these changes

2022-10-07 16:42 UTC, fabiobaltieri approved these changes

2022-10-10 06:52 UTC, nordicjm approved these changes

2022-10-18 10:05 UTC, merged