include: Add a missed semicolon
zephyrproject-rtos/zephyr pull request #49673
Opened 2022-08-30 09:35 UTC by ahmedmoheb-nordic

Missing a semicolon at the end causes some compilation issues.

Signed-off-by: Ahmed Moheb <ahmed.moheb@nordicsemi.no>

2022-08-30 16:14 UTC, dcpleung approved these changes, later dismissed

2022-08-31 02:01 UTC, stephanosio commented
Rebased to fix CI failure

2022-08-31 02:01 UTC, stephanosio approved these changes

2022-08-31 14:50 UTC, galak commented
When do you get a compile error?

2022-08-31 15:31 UTC, ahmedmoheb-nordic commented
> When do you get a compile error?

While trying to compile `subsys/bluetooth/host/id.c` for unit testing.
When that semicolon isn't there, a lot of errors are generated to due missing the statement termination.

2022-08-31 15:34 UTC, galak commented
> > 
> 
> While trying to compile `subsys/bluetooth/host/id.c` for unit testing. When that semicolon isn't there, a lot of errors are generated to due missing the statement termination.

can you say how to reproduce building `subsys/bluetooth/host/id.c` for unit testing?

2022-08-31 16:00 UTC, ahmedmoheb-nordic commented
> > > 
> > 
> > 
> > While trying to compile `subsys/bluetooth/host/id.c` for unit testing. When that semicolon isn't there, a lot of errors are generated to due missing the statement termination.
> 
> can you say how to reproduce building `subsys/bluetooth/host/id.c` for unit testing?

I created a dummy PR with the UT project, please check this one [Compilation Issue](https://github.com/ahmedmoheb-nordic/zephyr/pull/4)

Please navigate to `tests/bluetooth/host/id/bt_id_init/` then invoke the build command `west build -p always -b unit_testing .`

2022-08-31 16:14 UTC, galak requested changes
Need to find a proper fix for unit test builds

2022-08-31 16:16 UTC, galak commented
> I created a dummy PR with the UT project, please check this one [Compilation Issue](https://github.com/ahmedmoheb-nordic/zephyr/pull/4)
> 
> Please navigate to `tests/bluetooth/host/id/bt_id_init/` then invoke the build command `west build -p always -b unit_testing .`

So I was able to recreate this and this has more to do with unit tests than the macro missing a `;`.  Adding a `;` here is just paper taping over properly getting the unit test mocked up.

2022-08-31 17:05 UTC, ahmedmoheb-nordic commented
> > I created a dummy PR with the UT project, please check this one [Compilation Issue](https://github.com/ahmedmoheb-nordic/zephyr/pull/4)
> > Please navigate to `tests/bluetooth/host/id/bt_id_init/` then invoke the build command `west build -p always -b unit_testing .`
> 
> So I was able to recreate this and this has more to do with unit tests than the macro missing a `;`. Adding a `;` here is just paper taping over properly getting the unit test mocked up.

Do you have any suggestions how to fix it?

2022-09-01 14:50 UTC, galak commented
> > 
> 
> Do you have any suggestions how to fix it?

I don't.  I'm not that familiar with the unit test framework.  I guess the question is how are you mocking up devices, and devicetree as part of the unit test.

2022-09-01 21:35 UTC, mbolivar-nordic requested changes
I agree; there is "no way" this is missing a semicolon at the end, because Z_MAYBE_DEVICE_DECLARE_INTERNAL has a semicolon at the end.

2022-09-02 01:36 UTC, stephanosio commented
> because Z_MAYBE_DEVICE_DECLARE_INTERNAL has a semicolon at the end.

But should it?

2022-09-13 23:57 UTC, mbolivar-nordic commented
> But should it?

Yes

> (in general, you do not include semicolon at the end of a macro definition).

We do in devicetree all the time

2022-09-14 00:19 UTC, mbolivar-nordic commented
I'm just going to close this because it won't be merged. Please open another PR which fixes the real root cause of your issue after you have identified it.

2022-09-14 00:19 UTC, closed without merging