Bluetooth: controller: Fix memq_dequeue function
zephyrproject-rtos/zephyr pull request #4969
Opened 2017-11-14 19:28 UTC by cvinayak

When testing memq implementation used by controller, a
missing check on NULL pointer return could lead to NULL
pointer deferencing.

Current implementation of controller and mayfly do not
by design lead to NULL pointer dereferencing, this fix
is only for correct-ness and complete-ness.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2017-11-14 19:36 UTC, carlescufi approved these changes

2017-11-14 20:34 UTC, jhedberg requested changes

2017-11-14 20:34 UTC, jhedberg commented on subsys/bluetooth/controller/util/memq.c
> +		return 0;
We prefer NULL over 0 for pointers, so that it's clear what the type of the value is (pointer vs integer).

2017-11-16 08:06 UTC, jhedberg commented
@cvinayak besides the minor issue I commented on, this patch looks otherwise good - will you be sending an updated version soon so that we could get it merged?

2017-11-20 08:28 UTC, jhedberg approved these changes

2017-11-20 08:42 UTC, merged