test: nested_irq: Remove all printk in the nested irq handler
zephyrproject-rtos/zephyr pull request #49806
Opened 2022-09-01 09:50 UTC by povergoing

Fix https://github.com/zephyrproject-rtos/zephyr/issues/49491#issuecomment-1233436589

Accessing Advanced SIMD registers in the nested irq has a side effect with FPU sharing enabled #35410. We fix it by simply simulating the sequence of STR instructions. 
But for GCC12, things are more complicated which is GCC 12 will use `ldp q0, q1, [sp|xn #xx]` and `stp q0, q1, [sp #xx]` pairs to copy content when handling the `va_start()` things (printk). It is not worth emulating more of those instructions considering the combination of gcc v12 + va_arg usage within IRQ handlers + recursive IRQs shouldn't happen much in practice
with real applications.

Fix this issue #49491 by removing all printk that will cause the nested irq test failures.

2022-09-01 10:50 UTC, stephanosio requested changes
This is a very wrong approach to fixing this problem; in fact, this "solution" just hides away the problem without actually fixing it.

There may be applications that use `printk` (or anything that uses va_arg for that matter) in ISR and also require nested IRQs to be serviced. Those applications will not work (furthermore, even without any error messages).

We need to fix the problem instead of sweeping it under the rug.

2022-09-01 14:39 UTC, npitre approved these changes

2022-09-01 15:02 UTC, stephanosio commented
> There might be many things in life that are perfectly valid hypothesis but
> not worth the cost of supporting without actual confirmation they really
> exist.

`sprintf`? That sounds very practical to me.

2022-09-01 15:36 UTC, npitre commented
> `sprintf`? That sounds very practical to me.

From an IRQ handler which also must be interrupted by another IRQ at the
same time as part of normal operation? Let me entertain some doubts.

> If you decide to go down the path of not implementing support for this, 
> there should at least be an ASSERT/error message displayed when someone 
> decides to use va_arg inside ISR.

`va_arg` is perfectly usable inside ISRs. Restrictions are as follows:

- you compiled with gcc version >= 12, and

- you are inside an ISR (recursive or not), and

- you make use of va_arg

then IRQs are blocked for the remainder of that ISR preventing further 
recursive IRQs.

Can this be "fixed"? Sure. Is it worth the cost? Likely not until proven
otherwise.

2022-09-01 15:51 UTC, stephanosio commented
> > So I guess logging from ISR is going to be a thing of the past ...
> 
> I'm not going to discuss further with you if you so blatently ignore what I wrote above. I know you're not that dumb.

Right. This only affects nested IRQs, a very important feature in a "real-time" operating system.

2022-09-01 15:59 UTC, npitre commented
> Right. This only affects nested IRQs, a very important feature in a
> "real-time" operating system.

You expect your app to still be "real-time" with logging from ISRs?

2022-09-01 16:01 UTC, stephanosio commented
> You expect your app to still be "real-time" with logging from ISRs?

Yes, a lower priority ISR, that may be interrupted by a higher priority IRQ. may "log" to a memory buffer.

2022-09-01 16:21 UTC, andyross approved these changes
Seems like blood pressures are high.

Middle path: yeah, this isn't a root cause fix.  The root issue seems indeed to be that SIMD state management on arm64 isn't working in nested ISRs.  We should absolutely track that somewhere, with arguments about priority, etc...

But this isn't a test of SIMD state management, nor is it a test of printk() usage in ISRs.  It's just a test of nested interrupts.  I don't see why we should lose coverage of that feature (which is important to have even if there are funny platform bugs with optional CPU state!) while we wait for a complicated bug to be fixed.

Seems like we should merge this now (really, those printk()'s aren't doing any good anyway, this patch is worth it even as pure cleanup) and open a different issue for the arm64 thing?

2022-09-01 16:27 UTC, stephanosio commented
> really, those printk()'s aren't doing any good anyway

Really? Those printk's have been very helpful in analysing this issue (and other nested interrupt-related issues in the past).

I would, at least, prefer to see those left in, but made optional (custom printk macro, ifdef-ed out for ARM64).

2022-09-01 16:29 UTC, stephanosio commented
Also to re-iterate what I said above,

> if you are not going to fix it, make it ASSERT at minimum.

If va_arg is used (the unsupported instructions are executed), there should be at least a warning saying that nested interrupts are not going to work afterwards; otherwise, users will be wasting a lot of time trying to analyse this issue, as we have.

2022-09-01 16:31 UTC, andyross commented
I guess that's a taste thing.  I'm absolutely a debug-via-print person, but I guess my general sense is that needless logging in tests is something to be avoided.   It's extra space in the binary (we still have some small platforms) and extra bytes over the wire (the DSP work is currently struggling with its no-flow-control winstream buffer that can't handle more than 8k of output -- we have some tests that do 8k+ of output synchronously!).

2022-09-02 07:45 UTC, povergoing commented
I totally understand both sides. I actually think we should tell the compiler not to use SIMD for printk or anything like that containing `va_list` `va_start()` and `va_end()` in the kernel or at least in exception handlers. Do we really need printk with SIMD in the kernel? Can we disable SIMD/FPU registers for kernel and enable it only for apps?

Anyway, I don't think there is a quick way to really fix it. Based on this, what about following @stephanosio's this suggestion,
> If you decide to go down the path of not implementing support for this, there should at least be an ASSERT/error message displayed when someone decides to use va_arg inside ISR.

I try to find out a simple way to add a warning or something when handling FPU trap, finding that, oh there is nested usage of FPU registers :) @npitre @andyross.

2022-09-02 07:48 UTC, stephanosio commented
> I actually think we should tell the compiler not to use SIMD for printk or anything like that containing `va_list` `va_start()` and `va_end()`

Let me check if this can be done.

2022-09-02 07:52 UTC, povergoing commented
> > I actually think we should tell the compiler not to use SIMD for printk or anything like that containing `va_list` `va_start()` and `va_end()`
> 
> Let me check if this can be done.

There is a `-mgeneral-regs-only` and a `__attribute__ ((target("general-regs-only")))` for one single function, but not for sure how much effort this will take

2022-09-02 08:37 UTC, stephanosio commented
> > I actually think we should tell the compiler not to use SIMD for printk or anything like that containing `va_list` `va_start()` and `va_end()`
> 
> Let me check if this can be done.

So there is no way to prevent the NEON register `ldp` and `stp` instructions from being emitted without patching GCC -- GCC emits `ldp/stp qn` for 256-bit copy operations even with `-O0`.

What we CAN do is to make the `ldp/stp qn` for 256-bit copy operations be emitted sequentially by disabling the `schedule-insns2` optimisation (`-fno-schedule-insns2`), for example:
```
        str     q0, [sp, 80]
        str     q1, [sp, 96]
        str     q2, [sp, 112]
        str     q3, [sp, 128]
        str     q4, [sp, 144]
        str     q5, [sp, 160]
        str     q6, [sp, 176]
        str     q7, [sp, 192]
        stp     x1, x2, [sp, 216]
        stp     x3, x4, [sp, 232]
        stp     x5, x6, [sp, 248]
        str     x7, [sp, 264]
        .loc 1 207 2 view .LVU68
        add     x1, sp, 272
        stp     x1, x1, [sp, 48]
        add     x1, sp, 208
        str     x1, [sp, 64]
        mov     w1, -56
        str     w1, [sp, 72]
        mov     w1, -128
        str     w1, [sp, 76]
        .loc 1 209 2 is_stmt 1 view .LVU69
        ldp     q0, q1, [sp, 48]
        stp     q0, q1, [sp, 16]
        add     x1, sp, 16
        bl      vprintk
```

2022-09-02 09:00 UTC, povergoing commented
> So there is no way to prevent the NEON register `ldp` and `stp` instructions from being emitted without patching GCC -- GCC emits `ldp/stp qn` for 256-bit copy operations even with `-O0`.

can't we use `-mgeneral-regs-only` to disable it?

> What we CAN do is to make the `ldp/stp qn` for 256-bit copy operations be emitted sequentially by disabling the `schedule-insns2` optimisation (`-fno-schedule-insns2`), for example:

But IMHO, if this `-fno-schedule-insns2` gonna work, why do not use `-mgeneral-regs-only` directly so that we don't enable FPU, don't trap, and thus don't need to simulate it?

BTW, where do we enable this `-fno-schedule-insns2`? Only the files with `va_xx`usage or globally?

2022-09-02 09:05 UTC, stephanosio commented
> can't we use `-mgeneral-regs-only` to disable it?

We cannot use floats then.

**Also another very important observation I made is that this pattern ("GCC emits `ldp/stp qn` for 256-bit copy operations") is not just limited to the `va_list` usage. In fact, GCC can emit `ldp/stp qn` for any 256-bit copy operations:**

```
        (void)memset(&h, 0x00, sizeof(h));
    40005264:   d2801e02        mov     x2, #0xf0                       // #240
    40005268:   52800001        mov     w1, #0x0                        // #0
        const uint8_t expected[32] = {
    4000526c:   ad400400        ldp     q0, q1, [x0]
        (void)memset(&h, 0x00, sizeof(h));
    40005270:   9105c3e0        add     x0, sp, #0x170
        const uint8_t expected[32] = {
    40005274:   ad0187e0        stp     q0, q1, [sp, #48]
        (void)memset(&h, 0x00, sizeof(h));
    40005278:   94002356        bl      4000dfd0 <memset>
```

So, this is no longer just `printk` or `va_list` problem.

2022-09-02 09:14 UTC, stephanosio commented
To elaborate on https://github.com/zephyrproject-rtos/zephyr/pull/49806#issuecomment-1235256667:

Compiling the following code with `-O0`:

```c
#include <stdint.h>
#include <string.h>

void test(void)
{
        volatile uint8_t src[32];
        volatile uint8_t dst[32];

        memcpy(dst, src, 32);
}
```

We get:

```
        .arch armv8-a
        .file   "test7.c"
        .text
        .align  2
        .global test
        .type   test, %function
test:
        sub     sp, sp, #64
        mov     x0, sp
        add     x1, sp, 32
        ldp     q0, q1, [x1]
        stp     q0, q1, [x0]
        nop
        add     sp, sp, 64
        ret
        .size   test, .-test
        .ident  "GCC: (Zephyr SDK 0.15.0) 12.1.0"
```

2022-09-02 09:20 UTC, povergoing commented
> > can't we use `-mgeneral-regs-only` to disable it?
> 
> We cannot use floats then.

I meant disable file by file?

> So, this is no longer just printk or va_list problem.

Really, emm, so you prefer simulating insn + `-fno-schedule-insns2`? But with `-fno-schedule-insns2` means we lost many optimizations which may be an issue when someone needs that re-ordering optimization?

2022-09-02 09:23 UTC, stephanosio commented
> Really, emm, so you prefer simulating insn + `-fno-schedule-insns2`? But with `-fno-schedule-insns2` means we lost many optimizations which may be an issue when someone needs that re-ordering optimization?

well, at this point, I think we need to reconsider the approach taken in #35410.

2022-09-02 17:16 UTC, npitre commented
> at this point, I think we need to reconsider the approach taken in #35410.

The approach in #35410 is fine. Every `va_start()` must store q0-q7 on 
the stack to form the `va_arg` object whether or not float arguments 
were used. This is so because va_start() simply can't tell if there were 
actual float arguments being passed along, and the Aarch64 PCS says those, 
if any, must be provided in Q0-Q7.

Given the FP/SIMD register content on ARM64 is huge, we want it to be 
saved/restored lazily and only when necessary. Otherwise, doing that on 
every context switch adds a significant overhead to thread scheduling
(and a real-time OS wants to minimize context switch overhead).

So, what #35410 does is to simulate the string of `STR Qn, [SP, #imm]`
that comes with every `va_start()` in order to avoid saving/restoring
the FP/SIMD context needlessly when no FP arguments are being used (if
FP args were used, the FP context would have been restored already and
the FP trap wouldn't trigger on `va_start()`).

This being said, the new behavior in gcc v12 as illustrated by 
https://github.com/zephyrproject-rtos/zephyr/pull/49806#issuecomment-1235264899 
is a completely different thing. The fact that gcc may decide to use Q0-Q1
on a whim to optimize 32-byte copies without the ability to disable it
(and only it as we still might want to use floats some times) that
is the real issue.

> So there is no way to prevent the NEON register `ldp` and `stp` 
> instructions from being emitted without patching GCC -- GCC emits 
> `ldp/stp qn` for 256-bit copy operations even with `-O0`.

That is what has to be fixed. We can decide explicitly when we are using 
floats or not in the code, obviously. But gcc shouldn't start using those
regs as it sees fit without at least the ability to tell it not to do so.

Simulating those `LDP` / `STP` is not the way to go either as performance
will be way worse than the code gcc emitted before gcc v12 in that case.

And forcing a FP/SIMD context save/restore just for those cases (as
it is done right now) completely dwarfs the possible performance gain 
from those instructions, and runs into the same documented restrictions 
about FP usage from ISRs on ARM64 when those insns execute in ISR code 
(it is allowed, but recursive IRQs are no longer possible for the remainder of the ISR).

Therefore I think the best course of action here is to patch gcc in the 
Zephyr SDK, possibly adding a command line argument to prevent code 
optimizations using SIMD (but still allowing float usage), and submit
it in a gcc bug report.

2022-09-02 17:35 UTC, andyross commented
> The fact that gcc may decide to use Q0-Q1 on a whim to optimize 32-byte copies without the ability to disable it
(and only it as we still might want to use floats some times) that is the real issue.

To be fair: gcc is using the registers we told it were available for use.   The architecture doesn't have a published category for "register state that should only be used by optimized code".

The subject came up in the early days of x86_64 too (gcc will use SSE registers in surprising spots) and the solution there was just to save the SIMD state unconditionally on interupt entry and eat the cost (@dcpleung might remember this better than I do).  Maybe that's less of an option for arm64, though.

2022-09-02 18:04 UTC, stephanosio commented
I will try to track down the GCC commit(s) that introduced this behaviour and see if there is an undocumented option we can use to control this behaviour. If not, we should probably look into adding an option to control that and include the patch in the Zephyr SDK (and possibly to the upstream GCC).

2022-09-23 06:08 UTC, stephanosio commented
> I will try to track down the GCC commit(s) that could have introduced this behaviour:

It turns out https://github.com/gcc-mirror/gcc/commit/9f5361c8cac181dbc79b7302d7241a61e0ce2386 is the culprit, and it thankfully provides an "undocumented" option to turn it off.

I will send a patch for this.

2022-09-23 06:08 UTC, closed without merging

2022-09-23 06:48 UTC, stephanosio commented
Superseded by https://github.com/zephyrproject-rtos/zephyr/pull/50573