Bluetooth: controller: Fix ISO TX pool corruption and missing release
zephyrproject-rtos/zephyr pull request #49855
Opened 2022-09-02 07:33 UTC by mtpr-ot

- Remove unused union in struct node_tx_iso
- Fix ISO TX data pool corruption due to multiple calls to tx_cmplt_get,
  without removing the nodes
- Added missing release of TX node link in case of ISOAL error

Signed-off-by: Morten Priess <mtpr@oticon.com>

2022-09-02 08:08 UTC, mtpr-ot commented
CI failure does not seem to be caused by this PR.

2022-09-02 14:50 UTC, mtpr-ot commented
How can this continue to fail with "ARRAY_SIZE" CI error, after multiple rebases?

2022-09-02 15:47 UTC, cvinayak requested changes
Refer to request change here: https://github.com/zephyrproject-rtos/zephyr/pull/45989#discussion_r881644639

This PR is hiding the hack in macros instead of the requested redesign in #45989. If we have decided to keep the hack based on this PR. Then, #45989 be merged first and this PR be reworked to use macros.

2022-09-07 00:05 UTC, cvinayak commented
@mtpr-ot you can rebase this PR to upstream main, and when push with no changes in the branch, the PR will be closed by github as being merged.

2022-09-15 12:09 UTC, closed without merging