I2c: shell: Remove forward declaration
zephyrproject-rtos/zephyr pull request #49941
Opened 2022-09-05 16:21 UTC by finikorg

remove forward declaration.

2022-09-06 07:41 UTC, henrikbrixandersen requested changes

2022-09-06 07:52 UTC, finikorg commented on drivers/i2c/i2c_shell.c
> +	const struct device *dev = shell_device_lookup(idx, "i2c");
BTW, can I filter devices some other way? Now it is really messy, I see all kind of devices which are obviously not I2C.

2022-09-07 14:30 UTC, finikorg commented on drivers/i2c/i2c_shell.c
> +	const struct device *dev = shell_device_lookup(idx, "i2c");
OK, removed that patch

2022-09-07 14:37 UTC, teburd submitted a review, later dismissed

2022-09-07 15:16 UTC, teburd approved these changes

2022-09-07 19:43 UTC, henrikbrixandersen approved these changes

2022-09-07 20:04 UTC, nashif approved these changes

2022-09-07 20:04 UTC, merged