tests: limit drivers/can tests to capable platforms
zephyrproject-rtos/zephyr pull request #49948
Opened 2022-09-06 02:51 UTC by smrtos

The drivers/can tests should only run on platforms with can bus
support. This can avoid false failures on other platforms.

Signed-off-by: Ming Shao <ming.shao@intel.com>

2022-09-06 03:39 UTC, enjiamai approved these changes

2022-09-06 05:02 UTC, henrikbrixandersen requested changes
But these tests do not depend on CAN. Which failures are you seeing?

2022-09-06 06:00 UTC, smrtos commented
> But these tests do not depend on CAN. Which failures are you seeing?

I see some failures on Intel CAVS platforms. Since there's no CAN at all I want to exclude such tests. And I don't want to use "platform_exclude" tags because it's kind of to specific.

2022-09-06 06:19 UTC, henrikbrixandersen commented
> I see some failures on Intel CAVS platforms. 

Please be more specific. The board name and the output of the failed tests would be a good place to start.

2022-09-06 06:27 UTC, smrtos commented
> > I see some failures on Intel CAVS platforms.
> 
> Please be more specific. The board name and the output of the failed tests would be a good place to start.

I am using below command with failures:

```
twister --hardware-map ~/cavs25.map --device-testing -vv -x=CONFIG_BOOT_DELAY=500 -T tests/drivers/can/shell/
```

The CAVS25 platform uses a special mechanism to collect log and this test output log fast enough that the log collection cannot catch up. So twister consider it a failure due to incomplete log. Since the test is meant for CAN, though technically it can run on any platforms via the mocks, do you think it's ok to test only on platform with CAN support.

2022-09-06 06:36 UTC, henrikbrixandersen commented
> The CAVS25 platform uses a special mechanism to collect log and this test output log fast enough that the log collection cannot catch up.

So this is a limitation in the CAVS25 platform - not an issue in the CAN tests. We cannot go and exclude a ton of other platforms from a test just because one platform cannot process console output fast enough. This could affect any test, it is not limited to the two tests you change here.

2022-09-06 06:45 UTC, smrtos commented
> > The CAVS25 platform uses a special mechanism to collect log and this test output log fast enough that the log collection cannot catch up.
> 
> So this is a limitation in the CAVS25 platform - not an issue in the CAN tests. We cannot go and exclude a ton of other platforms from a test just because one platform cannot process console output fast enough. This could affect any test, it is not limited to the two tests you change here.

I am not excluding the tests just for a specific platform.  I am just describing the test in a more detailed way. Then it can be automatically picked or skipped.

Of course unless you consider it appropriate to run such tests on platform **with no CAN support**.

2022-09-06 07:27 UTC, henrikbrixandersen commented
> Of course unless the community consider it appropriate/necessary to run such tests on a platform **with no CAN support**.

I find it relevant no to put artificial limits on which tests are run on which platforms. These tests have no dependency on the platform having a CAN controller and thus should not be limited to running on platforms with a CAN controller.

So far the `tests/drivers/can/shell` test, which was introduced less than a 2 weeks ago, have two generic, non-CAN related issues: A problem with dummy shell initialisation on SMP systems (work-around in e9e7ad388da7122a6193845be4eff48c19bbe618) and the issue with with CAVS25 platform, you bring up here.

2022-09-06 13:26 UTC, PerMac commented
This `depends_on` filter is a real pain in the ass. I guess we would want to deprecate its usage and start using other, more robust ways of filtering platforms. I know we have to still live with it, but I would recommend not to use it unless there is no other means to filter (the pain is caused by platform_allow). Sorry, this is out of my domain, hence my comments might not be applicable. 
If this test can run on platforms without CAN support, then I'm against adding new filter for it, just like Hendrik argumented. Is it the issue of too short timeout? If so, you can either add a PR increasing the timeout value of this test, or if it is due to platform speed of processing the output, you can raise a PR modifying your board's yaml, adding e.g `timeout_modifier=1.5` and then default timeout for your platform will be always increased 1.5x and might unlock other tests failing due to timeouts (like here https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arc/nsim/nsim_hs_smp.yaml#L10).

2022-09-06 13:27 UTC, nashif commented
agree with @henrikbrixandersen, should not depend on hardware availability. The filtering needs to happens somewhere else.
Although this should work on hardware devices regardless of CAN hw availability, this is the type of test we should consider as sufficiant to run on emulation platforms and not run on devices by default with the goal of covering as much as possible  using emulation and native posix and leaving hw dependent tests to run on devices in default scope with the option of being able to run on a device if needed (or as part of a different test plan).

2022-09-06 13:34 UTC, henrikbrixandersen commented
> Although this should work on hardware devices regardless of CAN hw availability, this is the type of test we should consider as sufficiant to run on emulation platforms and not run on devices by default with the goal of covering as much as possible using emulation and native posix and leaving hw dependent tests to run on devices in default scope with the option of being able to run on a device if needed (or as part of a different test plan).

@nashif That's why I have set `integration_platforms` to `native_posix` and `native_posix_64`. What do you suggest?

2022-09-06 13:53 UTC, nashif commented
> @nashif That's why I have set `integration_platforms` to `native_posix` and `native_posix_64`. What do you suggest?

that is correct, but we have other gaps in how tests are selected or filtered and how tests are classified and categorised. integration platforms was introduced only to deal with CI load and not to support scalable test plans and optimizing coverage with the ultimate goal of Testing the OS rather than focusing on devices.

Either using tags or some new dedicated keyword, mark a test as required to be run on hardware, or we have no other way to verify but run on hardware (if emulation is not possible) and if something is covered by qemu/native_posix, mark it accordingly as well, WITHOUT hardcoding an exclude (so you still can run it on hardware).

2022-09-06 13:54 UTC, nashif commented
To illustrate that, here is how this could look like in terms of where we run tests and get coverage:

![image](https://user-images.githubusercontent.com/180017/188653415-59fd38ff-5e07-4ea9-a097-98360df13a15.png)

2022-09-16 08:02 UTC, henrikbrixandersen commented
Can this be closed in favour of #50071?

2022-09-16 12:52 UTC, smrtos commented
Should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/50071

2022-09-16 12:52 UTC, closed without merging