doc: fix some doxygen grouping
zephyrproject-rtos/zephyr pull request #49979
Opened 2022-09-06 18:04 UTC by nashif

- doc: group demand paging APIs in doxygne
- doc: doxygen: restructure device model APIs
- doc: doxygen: add memory management group
- doc: doxygen: move lifo tests to test group
- doc: doxygen: group smp tests
- doc: doxygen: move all IPC APIs under one group
- doc: doxygen: add disk to io_interfaces

2022-09-06 18:36 UTC, dcpleung requested changes

2022-09-06 18:36 UTC, dcpleung commented on include/zephyr/sys/mem_manage.h
> + * @ingroup memory_management
This should be in the next commit.

2022-09-06 18:59 UTC, dcpleung approved these changes

2022-09-07 07:22 UTC, carlocaione approved these changes

2022-09-07 08:32 UTC, carlescufi approved these changes

2022-09-07 08:35 UTC, jxstelter approved these changes

2022-09-07 08:36 UTC, merged