Bluetooth: Shell: Add connect-name command
zephyrproject-rtos/zephyr pull request #49973
Opened 2022-09-06 14:21 UTC by Thalley

Add a new command, connect-name, which takes a string
as the single input and uses that to setup a scan filter
and connect to the first device that matches the name.

This command is thus basically shorthand for
bt scan-filter-set <name>
bt scan on
bt scan off
bt connect
bt scan-filter-clear-name

The idea of this command is to not only make it easier
find and connect to devices in a crowded environment,
but also to more easily connect to devices that has
privacy enabled (and thus changes their advertised
address).

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

2022-09-06 14:23 UTC, Thalley commented
The main motive behind this PR is to make UPF testing easier :)

2022-09-07 15:25 UTC, cvinayak requested changes

2022-09-08 08:23 UTC, Thalley commented on subsys/bluetooth/shell/bt.c
> +#endif /* CONFIG_BT_CENTRAL */
Good suggestion, thanks

2022-09-08 12:31 UTC, cvinayak submitted a review, later dismissed

2022-09-08 12:38 UTC, sjanc approved these changes, later dismissed
LGTM but I'd prefer to not suggest in commit message that privacy and fixed adv data (name here) is something that should be used :-)

2022-09-08 13:07 UTC, Thalley commented
> LGTM but I'd prefer to not suggest in commit message that privacy and fixed adv data (name here) is something that should be used :-)

Removed the privacy reference :)

2022-09-09 06:14 UTC, sjanc approved these changes

2022-09-09 07:29 UTC, MariuszSkamra approved these changes

2022-09-09 08:10 UTC, carlescufi approved these changes

2022-09-09 08:10 UTC, merged