arch/xtensa: Properly namespace special register API
zephyrproject-rtos/zephyr pull request #49980
Opened 2022-09-06 18:08 UTC by andyross

The Xtensa arch has historically had state/user register accessor
macros with bare three-byte symbol names.  I think this might have
been in the original Cadence-contributed arch integration, but I'm not
sure.  In any case they also exist in the same names in vendor
HAL/toolchain code and are causing collisions.  We never should have
had these symbols exposed in our header.

Put them under an ARCH_ prefix to decollide.

Signed-off-by: Andy Ross <andyross@google.com>

2022-09-06 18:10 UTC, andyross commented
This is my somewhat higher-risk alternative to Kai's patch in #49930

I'm not wedded to doing this here, now, or to this particular naming scheme.  But IMHO if we have conflicts on these APIs we should address it now.   The risk here is that out-of-tree apps that happened to have treated these symbols as a "Zephyr API" (IMHO I'd call them more a "mistake" -- we never documented them, certainly) will be broken by this change.

I ran it on the platforms I can build with the SDK, but needs validation vs. esp32 where I don't have a toolchain installed.

2022-09-06 18:39 UTC, dcpleung commented
Maybe use `XTENSA_` as prefix? since these are all Xtensa specific instructions.

2022-09-06 19:33 UTC, kv2019i approved these changes, later dismissed
I'm perfectly happy with this (or with XTENSA_). I think it's safer to use different names to ensure the definitions in Zephyr tree are actually used.

2022-09-06 19:37 UTC, nashif requested changes
use XTENSA_ instead of ARCH_

2022-09-07 15:00 UTC, andyross commented
Update naming.  FWIW: I picked ARCH_ originally because it was two bytes shorter and because the specific conflict was with Cadence tooling, and "XTENSA_" is ambiguous in that context.  AFAIK they don't use that as a prefix but they might.  But long term we want their headers out of our builds anyway.

2022-09-07 17:30 UTC, dcpleung approved these changes

2022-09-07 17:35 UTC, nashif approved these changes

2022-09-07 17:45 UTC, sylvioalves approved these changes

2022-09-08 00:28 UTC, merged