devicetree: edtlib: gen_defines: Add model name macros based on compatibles
zephyrproject-rtos/zephyr pull request #50015
Opened 2022-09-07 22:40 UTC by MaureenHelm

Follow up to #49489 adding support in edtlib, gen_defines, and devicetree.h to get model name strings from a node's compatibles.

cc: @huhebo

2022-09-09 05:30 UTC, yperess submitted a review, later dismissed

2022-09-10 04:28 UTC, teburd submitted a review, later dismissed

2022-09-13 22:14 UTC, mbolivar-nordic requested changes

2022-09-13 22:14 UTC, mbolivar-nordic commented on scripts/dts/python-devicetree/src/devicetree/edtlib.py
> +                        self.compat2vendor[compat] = (self._vendor_prefixes[vendor], model)
Please rename the variable or create a separate look up table.

2022-09-13 22:14 UTC, mbolivar-nordic commented on include/zephyr/devicetree.h
> +	DT_CAT(node_id, _COMPAT_MODEL_IDX_##idx)
Use DT_CAT3 (see 47ef58e8ac4aecc186054cf703a0a62a0106957f).

2022-09-15 20:32 UTC, galak commented
Hmm, curious about if we think a compatible w/o vendor means, no model.

For example:

`compatible = "ns16550";`

seems like model being `ns16550` would be reasonable.

@mbolivar-nordic @MaureenHelm thoughts?

2022-09-16 21:05 UTC, mbolivar-nordic commented
@galak do you really mean to say "no model"? I'm confused because your example seems to be saying the opposite: compatible without vendor means the compatible is the model, not compatible with no vendor means no model.

Are you asking for a change?

2022-09-20 15:59 UTC, galak commented
> @galak do you really mean to say "no model"? I'm confused because your example seems to be saying the opposite: compatible without vendor means the compatible is the model, not compatible with no vendor means no model.
> 
> Are you asking for a change?

I'm asking for us to decide how to handle the case of a `compatible` that is NOT of the form `vendor,model`.  For `compatible = "ns16550"`, is the `model` None or is it `ns16550`?

2022-09-21 18:09 UTC, MaureenHelm commented
> > @galak do you really mean to say "no model"? I'm confused because your example seems to be saying the opposite: compatible without vendor means the compatible is the model, not compatible with no vendor means no model.
> > Are you asking for a change?
> 
> I'm asking for us to decide how to handle the case of a `compatible` that is NOT of the form `vendor,model`. For `compatible = "ns16550"`, is the `model` None or is it `ns16550`?

I took the simplest route and chose not to define a model macro when the compatible doesn't have the form `vendor,model`. The logic is consistent with the vendor macro, which also doesn't exist for non-compliant compatibles. I'm open to other ideas though.

2022-09-21 19:49 UTC, galak commented
> > > @galak do you really mean to say "no model"? I'm confused because your example seems to be saying the opposite: compatible without vendor means the compatible is the model, not compatible with no vendor means no model.
> > > Are you asking for a change?
> > 
> > 
> > I'm asking for us to decide how to handle the case of a `compatible` that is NOT of the form `vendor,model`. For `compatible = "ns16550"`, is the `model` None or is it `ns16550`?
> 
> I took the simplest route and chose not to define a model macro when the compatible doesn't have the form `vendor,model`. The logic is consistent with the vendor macro, which also doesn't exist for non-compliant compatibles. I'm open to other ideas though.

For vendor it makes sense, since if there is a `,` than we clearly have no vendor.  My question is that it seems like model still might make sense for the cases that there is NOT `,`.

2022-09-29 21:39 UTC, mbolivar-nordic commented
In my opinion we shouldn't define a model in cases like that. Things like `gpio-leds` are not a model of any hardware in the sense I usually understand the term. The absence of a vendor means "generic or vendor-independent" almost all the time, which is why the [bindings index](https://docs.zephyrproject.org/latest/build/dts/api/bindings.html#dt-no-vendor) uses that as the section name when there is no vendor.

2022-09-29 22:34 UTC, galak approved these changes

2022-10-04 15:35 UTC, MaureenHelm commented
@mbolivar-nordic are you ok with this now?

2022-10-07 18:47 UTC, mbolivar-nordic approved these changes

2022-10-07 18:48 UTC, merged