tests: shell: do not poll for dummy shell to become ready
zephyrproject-rtos/zephyr pull request #50058
Opened 2022-09-08 19:39 UTC by henrikbrixandersen

Do not use WAIT_FOR() for polling for the dummy shell backend to become ready as WAIT_FOR() does not work for such long timeouts (here 20msec) on platforms with relatively low number of hardware timer ticks per second (e.g. with a system timer clock frequency of 32768 Hz).
    
Fixes: #50032

2022-09-08 19:57 UTC, fabiobaltieri commented
Could we instead change `WAIT_FOR` to do `cycle_count = MAX(<...>, 1)`, so that it sleeps at lest one cycle?

2022-09-08 20:00 UTC, stephanosio reviewed
I wonder if we should fix the root cause instead of replacing `WAIT_FOR` with just `k_sleep`.

https://github.com/zephyrproject-rtos/zephyr/blob/de4b56475460dc286e45af8ebe7840587d559d30/include/zephyr/sys/util.h#L478

The fix could be as simple doing `sys_clock_hw_cycles_per_sec() * timeout / USEC_PER_SEC` if `sys_clock_hw_cycles_per_sec < USEC_PER_SEC`.

2022-09-08 20:05 UTC, andyross requested changes
Agreed, this looks like a bug in WAIT_FOR() to me.  FWIW there's a whole library of overflow-resistant and optimized time conversion utilities in `<zephyr/sys/time_units.h>`.  Looks like this should have just been a `k_us_to_cyc_ceil64()`.

2022-09-09 08:40 UTC, stephanosio submitted a review, later dismissed

2022-09-09 08:40 UTC, henrikbrixandersen commented
> Agreed, this looks like a bug in WAIT_FOR() to me. FWIW there's a whole library of overflow-resistant and optimized time conversion utilities in `<zephyr/sys/time_units.h>`. Looks like this should have just been a `k_us_to_cyc_ceil64()`.

Thank you for the hint, I was not aware of those utility functions. I have changed `WAIT_FOR()` to use that and verified on my usual set of development boards (which includes a `mimxrt1024_evk` on which I could reproduce the initially reported issue).

Please re-review.

2022-09-09 08:43 UTC, fabiobaltieri approved these changes, later dismissed

2022-09-09 08:59 UTC, henrikbrixandersen commented
Rebased to switch to 32-bit utility function variant.

2022-09-09 09:04 UTC, stephanosio approved these changes

2022-09-09 09:05 UTC, fabiobaltieri approved these changes

2022-09-09 12:58 UTC, nordic-krch approved these changes

2022-09-09 15:09 UTC, andyross approved these changes
Looks great

2022-09-09 15:28 UTC, merged