reel_board: remove the hw_reset which blocks flashing
zephyrproject-rtos/zephyr pull request #50128
Opened 2022-09-10 08:44 UTC by smrtos

The hw reset type is blocking the flash of reel_board.
It seems removing it can fix the issue.

Signed-off-by: Ming Shao <ming.shao@intel.com>

The error I saw is:

> Traceback (most recent call last):
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/__main__.py", line 161, in run
>     status = cmd.invoke()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/subcommands/load_cmd.py", line 125, in invoke
>     programmer.program(filename,
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/file_programmer.py", line 170, in program
>     self._loader.commit()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/loader.py", line 289, in commit
>     perf = builder.program(chip_erase=chipErase,
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 490, in program
>     sector_erase_count, page_program_time = self._compute_sector_erase_pages_and_weight(fast_verify)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 666, in _compute_sector_erase_pages_and_weight
>     self._analyze_pages_with_crc32(fast_verify)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 645, in _analyze_pages_with_crc32
>     self._enable_read_access()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 259, in _enable_read_access
>     self.flash.init(self.flash.Operation.VERIFY)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 252, in init
>     result = self._call_function_and_wait(self.flash_algo['pc_init'],
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 653, in _call_function_and_wait
>     self._call_function(pc, r0, r1, r2, r3, init)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 555, in _call_function
>     self.target.write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/core/soc_target.py", line 235, in write_core_registers_raw
>     self.selected_core_or_raise.write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/coresight/cortex_m.py", line 1175, in write_core_registers_raw
>     self._base_write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/coresight/cortex_m.py", line 1189, in _base_write_core_registers_raw
>     raise exceptions.CoreRegisterAccessError(
> pyocd.core.exceptions.CoreRegisterAccessError: cannot write registers pc, r0, r1, r2, r9, sp, lr because core #0 is not halted
> FATAL ERROR: command exited with status 1: pyocd flash --config /home/ming/sources/zephyrproject/zephyr/boards/arm/reel_board/support/pyocd.yaml -e sector -t nrf52840 -f 4000000 /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/zephyr.hex
> FAILED: zephyr/cmake/flash/CMakeFiles/flash /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/cmake/flash/CMakeFiles/flash

(I am not sure if this fix is appropriate. But it can work when I try to flash reel board)

2022-09-14 13:48 UTC, jfischer-no requested changes
I cannot confirm any issues flashing reel board, tested on latest main and Python 3.10.6.

2022-09-17 15:29 UTC, smrtos commented
> I cannot confirm any issues flashing reel board, tested on latest main and Python 3.10.6.

Could you try below steps:

I have two reel boards plugged on my host (but I think the number doesn't matter).

I got hardware map like below:

> - connected: true
>   id: OSHW000032254e45000d8003ab98002484d1000097969900
>   platform: reel_board
>   product: DAPLink CMSIS-DAP
>   runner: pyocd
>   serial: /dev/ttyACM0
> - connected: true
>   id: OSHW000041114e45002e3006bcf000330571000097969900
>   platform: reel_board
>   product: DAPLink CMSIS-DAP
>   runner: pyocd
>   serial: /dev/ttyACM1
> 

Then I did this:

cmake -B bld_reel -GNinja -DBOARD=reel_board -S samples/hello_world/
cd bld_reel/
ninja flash

Then pyocd prompts me with this:

```
[0/1] Flashing reel_board
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner pyocd
-- runners.pyocd: Flashing file: /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/zephyr.hex
  #   Probe/Board             Unique ID                                          Target
-----------------------------------------------------------------------------------------
  0   ARM DAPLink CMSIS-DAP   OSHW000032254e45000d8003ab98002484d1000097969900   n/a

  1   ARM DAPLink CMSIS-DAP   OSHW000041114e45002e3006bcf000330571000097969900   n/a

Enter the number of the debug probe or 'q' to quit>

```

Then I select `0` or `1`.

Then I got the error:

> 0059759 W Board ID OSHW is not recognized [mbed_board]
> 0059996 I Loading /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/zephyr.hex [load_cmd]
> 0060789 C cannot write registers pc, r0, r1, r2, r9, sp, lr because core #0 is not halted [__main__]
> Traceback (most recent call last):
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/__main__.py", line 161, in run
>     status = cmd.invoke()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/subcommands/load_cmd.py", line 125, in invoke
>     programmer.program(filename,
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/file_programmer.py", line 170, in program
>     self._loader.commit()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/loader.py", line 289, in commit
>     perf = builder.program(chip_erase=chipErase,
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 490, in program
>     sector_erase_count, page_program_time = self._compute_sector_erase_pages_and_weight(fast_verify)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 666, in _compute_sector_erase_pages_and_weight
>     self._analyze_pages_with_crc32(fast_verify)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 645, in _analyze_pages_with_crc32
>     self._enable_read_access()
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/builder.py", line 259, in _enable_read_access
>     self.flash.init(self.flash.Operation.VERIFY)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 252, in init
>     result = self._call_function_and_wait(self.flash_algo['pc_init'],
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 653, in _call_function_and_wait
>     self._call_function(pc, r0, r1, r2, r3, init)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/flash/flash.py", line 555, in _call_function
>     self.target.write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/core/soc_target.py", line 235, in write_core_registers_raw
>     self.selected_core_or_raise.write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/coresight/cortex_m.py", line 1175, in write_core_registers_raw
>     self._base_write_core_registers_raw(reg_list, data_list)
>   File "/home/ming/.local/lib/python3.10/site-packages/pyocd/coresight/cortex_m.py", line 1189, in _base_write_core_registers_raw
>     raise exceptions.CoreRegisterAccessError(
> pyocd.core.exceptions.CoreRegisterAccessError: cannot write registers pc, r0, r1, r2, r9, sp, lr because core #0 is not halted
> FATAL ERROR: command exited with status 1: pyocd flash --config /home/ming/sources/zephyrproject/zephyr/boards/arm/reel_board/support/pyocd.yaml -e sector -t nrf52840 -f 4000000 /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/zephyr.hex
> FAILED: zephyr/cmake/flash/CMakeFiles/flash /home/ming/sources/zephyrproject/zephyr/bld_reel/zephyr/cmake/flash/CMakeFiles/flash
> cd /home/ming/sources/zephyrproject/zephyr/bld_reel && /usr/bin/cmake -DTARGET=flash -DDEPENDENCIES="" -P /home/ming/sources/zephyrproject/zephyr/cmake/flash/check_runner_dependencies.cmake && /usr/bin/cmake -E env /usr/bin/python3.10 -m west flash
> ninja: build stopped: subcommand failed.

2022-09-20 07:52 UTC, jfischer-no commented
> Then I did this:
> 
> cmake -B bld_reel -GNinja -DBOARD=reel_board -S samples/hello_world/ cd bld_reel/ ninja flash

```
[0/1] Flashing reel_board
-- west flash: rebuilding
[2/171] Generating include/generated/version.h
-- Zephyr version: 3.2.0-rc2 (/home/john/zephyr-project/zephyr), build: v3.2.0-rc2-68-g7c231e3e271a
[161/171] Linking C executable zephyr/zephyr_pre0.elf

[165/171] Linking C executable zephyr/zephyr_pre1.elf

[171/171] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       22508 B         1 MB      2.15%
            SRAM:        4264 B       256 KB      1.63%
        IDT_LIST:          0 GB         2 KB      0.00%
-- west flash: using runner pyocd
-- runners.pyocd: Flashing file: /home/john/zephyr-project/zephyr/build/zephyr/zephyr.hex
  #   Probe                   Unique ID                                         
--------------------------------------------------------------------------------
  0   ARM DAPLink CMSIS-DAP   OSHW000032254e4500138003ab98002184d1000097969900  
  1   ARM DAPLink CMSIS-DAP   OSHW000047784e45001d9002d996002b9081000097969900  

Enter the number of the debug probe or 'q' to quit> 0
0003791 I Loading /home/john/zephyr-project/zephyr/build/zephyr/zephyr.hex [load_cmd]
[==================================================] 100%
0006252 I Erased 24576 bytes (6 sectors), programmed 24576 bytes (6 pages), skipped 0 bytes (0 pages) at 9.82 kB/s [loader]
```

Works fine for me. What is your `pyocd --version`?

2022-09-20 13:13 UTC, smrtos commented
> Works fine for me. What is your pyocd --version?

pyocd 0.34.1

@jfischer-no

2022-09-21 10:53 UTC, jfischer-no commented
> > Works fine for me. What is your pyocd --version?
> 
> pyocd 0.34.1
> 
> @jfischer-no

I cannot reproduce it using pyocd-0.33.1 but pyocd 0.34.1

2022-09-21 11:00 UTC, jfischer-no requested changes

2022-09-22 06:29 UTC, smrtos commented on boards/arm/reel_board/support/pyocd.yaml
> +#reset_type: 'hw'
OK, just removed it.

2022-09-22 07:15 UTC, jfischer-no approved these changes

2022-09-22 14:35 UTC, MaureenHelm approved these changes

2022-09-22 15:02 UTC, fabiobaltieri approved these changes
Thanks, I also noticed the issue, pyocd 0.34.0 and 0.34.1. The hardware reset line is correctly been toggled but flashing fails as described, works fine with this.

2022-09-22 15:02 UTC, merged