pcie: devicetree: Add helper macros
zephyrproject-rtos/zephyr pull request #50151
Opened 2022-09-12 10:10 UTC by finikorg

At the moment PCIE BDF is hacked into REG_ADDR and PCIE ID is hacked into REG_SIZE. Add those macros so that the code looks readable.

2022-09-13 13:16 UTC, jhedberg commented
Shouldn't you also add an include statement to the bottom of `include/zephyr/devicetree.h`?

2022-09-13 15:19 UTC, jhedberg approved these changes

2022-09-13 16:47 UTC, galak requested changes
NAK: we shouldn't be propagating the incorrect PCI/PCIe addressing in devicetree by adding APIs around it.

2022-09-13 19:02 UTC, mbolivar-nordic requested changes
Can you explain the problem in more detail? My understanding from @superna9999 was that we were doing this correctly.

If these are needed, then

- all devicetree macros need test cases in tests/lib/devicetree/api
- we sometimes add regular macros without INST macros, but we don't add INST macros without regular macros

2022-09-14 06:16 UTC, finikorg commented
Hi @galak @mbolivar-nordic , the current way of using PCIE in devicetree is hacking into REG_ADDR and REG_SIZE like shown below:

https://github.com/zephyrproject-rtos/zephyr/blob/878edeb6ff190a713910a0e5cb9022704c5934a3/dts/x86/intel/elkhart_lake.dtsi#L57-L68

and then the code using this register and size looks really ugly like:

https://github.com/zephyrproject-rtos/zephyr/blob/878edeb6ff190a713910a0e5cb9022704c5934a3/drivers/serial/uart_ns16550.c#L1068-L1077

This macro programming stuff is already unreadable and hiding PCI_ID into REG_SIZE, etc  making it even harder to understand.

2022-09-14 08:22 UTC, henrikbrixandersen commented
> NAK: we shouldn't be propagating the incorrect PCI/PCIe addressing in devicetree by adding APIs around it.

Agreed.

2022-09-14 09:07 UTC, jhedberg commented
I think it would be more productive to continue the discussion in #26109

2022-09-16 21:23 UTC, mbolivar-nordic commented
> I think it would be more productive to continue the discussion in #26109

I read this thread, and I'm going to leave my -1 on this PR because the requested changes apply regardless of the outcome of that discussion.

2022-11-11 13:21 UTC, finikorg commented
Closing it, PR #52107 fixes the issue.

2022-11-11 13:23 UTC, closed without merging