intel_adsp: cleanup interrupt controller and headers
zephyrproject-rtos/zephyr pull request #50279
Opened 2022-09-15 17:13 UTC by nashif

- drivers: intc: ace: use DW structure already defined in the driver
- drivers: intc: rename macros and use single prefix
- intel_adsp: put interrupt defines in own headers/cleanup namespace

2022-09-15 17:53 UTC, andyross approved these changes, later dismissed

2022-09-15 18:27 UTC, dcpleung approved these changes, later dismissed

2022-10-03 21:27 UTC, dcpleung submitted a review, later dismissed

2022-10-04 09:17 UTC, kv2019i reviewed
Looks good to me. @mwasko @aborisovich @marcinszkudlinski  please have a look!

2022-10-05 19:07 UTC, edersondisouza requested changes
Minor comments, but it seems there's a missing file rename.

2022-10-11 15:49 UTC, dcpleung approved these changes

2022-10-11 16:43 UTC, edersondisouza approved these changes
Minor nitpicks only

2022-10-11 16:43 UTC, edersondisouza commented on soc/xtensa/intel_adsp/ace/multiprocessing.c
> +#define ACE_INTC_IRQ DT_IRQN(DT_NODELABEL(ace_intc))
Isn't this already defined at `ace_v1x-regs.h/adsp_interrupt.h`?

2022-10-11 16:43 UTC, edersondisouza commented on soc/xtensa/intel_adsp/cavs/include/intel_tgl_adsp/adsp_shim.h
> +	uint32_t _unused7[2];
Why not merge this two "unused"?

2022-10-11 16:50 UTC, merged