boards: posix: native_posix: Handle SDL events in zephyr thread
zephyrproject-rtos/zephyr pull request #50411
Opened 2022-09-20 08:55 UTC by pdgendt

This commit introduces a zephyr thread for SDL events. This allows to use zephyr mutex locking with SDL callbacks.

Relates to #50080; as this calls `gpio_emul_input_set` which locks a mutex, and asserts if called from an idle thread (which apparently is the case for the posix main thread).

2022-09-20 09:10 UTC, aescolar requested changes

2022-09-20 09:10 UTC, aescolar commented on boards/posix/native_posix/Kconfig
> +	  Sleep interval time of SDL thread to handle events in microseconds.
Beware that k_sleep only has the resolution of the system tick. Meaning not less than 10 milliseconds by default.
=> this definition seems a bit off

2022-09-20 09:10 UTC, aescolar commented on boards/posix/native_posix/Kconfig
> +	default 2048
There is no need to define a stack size for this. You can just use ARCH_POSIX_RECOMMENDED_STACK_SIZE See https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/posix/Kconfig#L12

2022-09-20 09:11 UTC, aescolar commented
>(which apparently is the case for the posix main thread).

Just for info: The native_posix main thread is a separate thread than the Zephyr SW threads. If you happen to call Zephyr APIs from it, you confuse the Zephyr kernel :)

2022-09-20 09:15 UTC, pdgendt commented
> If you call Zephyr APIs from it, you confuse the Zephyr kernel :)

That is exactly the problem :)

2022-09-20 09:32 UTC, aescolar reviewed
You can still define a kconfig option for the delay :), just not a too tiny amount

2022-09-20 09:44 UTC, aescolar approved these changes

2022-09-20 10:03 UTC, pdgendt commented
@aescolar FYI when enabling `CONFIG_STACK_SENTINEL` the `ARCH_POSIX_RECOMMENDED_STACK_SIZE` should be set to 44 instead of 40 in case of 64 bit, to prevent a stack overflow. Not sure for 32 bit though.

2022-09-20 10:25 UTC, pdgendt commented
> Would you so kind as to send a PR to fix it?

Done #50416

2022-10-05 11:11 UTC, carlescufi approved these changes

2022-10-05 11:11 UTC, merged