doc: release-notes: 3.2: bits for eSPI
zephyrproject-rtos/zephyr pull request #50509
Opened 2022-09-21 22:56 UTC by albertofloyd

This adds a few bits about the eSPI driver updates flash over eSPI support and platform-specific virtual wires support.

Signed-off-by: Jose Alberto Meza <jose.a.meza.arellano@intel.com>

2022-09-22 19:03 UTC, dcpleung approved these changes, later dismissed

2022-09-22 19:13 UTC, fabiobaltieri approved these changes

2022-09-22 19:14 UTC, fabiobaltieri commented on doc/releases/release-notes-3.2.rst
> +  * eSPI emulator initialization improvements.
Actually I think you need to leave an empty line here.

2022-09-22 19:15 UTC, fabiobaltieri requested changes

2022-09-22 19:15 UTC, fabiobaltieri commented on doc/releases/release-notes-3.2.rst
> +  * eSPI emulator initialization improvements.
Yeah it needs an empty line to render correctly.

2022-09-27 14:53 UTC, mmahadevan108 commented
@albertofloyd can you help address the comment.

2022-09-28 08:08 UTC, fabiobaltieri commented
(added a whiteline)

2022-09-28 08:08 UTC, fabiobaltieri approved these changes

2022-09-28 14:23 UTC, henrikbrixandersen approved these changes

2022-09-28 14:25 UTC, merged