Bluetooth: Controller: Warn LLCP Legacy implementation as DEPRECATED
zephyrproject-rtos/zephyr pull request #50585
Opened 2022-09-23 11:04 UTC by cvinayak

Add in Kconfig, select DEPRECATED, to warn at build time that the LLCP legacy implementation is deprecated and the refactored LLCP enabled by BT_LL_SW_LLCP Kconfig option be used instead (which is the default now).

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2022-09-23 11:12 UTC, carlescufi requested changes
Please add a note to the release notes

2022-09-23 11:26 UTC, carlescufi commented
@cvinayak please rebase

2022-09-23 12:48 UTC, carlescufi approved these changes

2022-09-26 09:06 UTC, tejlmand approved these changes
lgtm

2022-09-26 09:07 UTC, merged