drivers: serial: Runtime Configure for SAM UART and USART
zephyrproject-rtos/zephyr pull request #50629
Opened 2022-09-25 17:21 UTC by nick-kraus

Implements dynamic configuration for the atmel,sam-uart and atmel,sam-usart drivers and enables the new API calls if CONFIG_UART_USE_RUNTIME_CONFIGURE is set.

Test samples [are available here](https://github.com/nick-kraus/zephyr/tree/add_sam_uart_configure-test/samples) (sam_{uart/usart}_configure_test), which checks that the expected configurations can be set and data can still be sent and received after dynamically changing the UART configuration.

Signed-off-by: Nick Kraus <nick@nckraus.com>

2022-09-25 18:25 UTC, nick-kraus commented
It appears that the register header for the USART peripheral for the sam4l line of chips only has a different `#define` macro name than for all the other chip lines [(see here)](https://github.com/zephyrproject-rtos/hal_atmel/blob/master/asf/sam/include/sam4l/component/usart.h#L1004). For all other chips the symbol name is `US_MR_CHRL_{n}_BIT`, but for the 4l chip series it is `US_MR_CHRL_{n}`.

It is probably best to change the hal_atmel code to match, instead of using a #if here, so I'll work on a pull request for that as well, and this can be marked as draft or DNM until that is ready. It should however be ready to review, as the change in hal_atmel shouldn't require any changes here.

2022-09-26 17:16 UTC, dcpleung submitted a review, later dismissed

2022-09-27 03:59 UTC, nick-kraus commented
This pull request is now dependent on [a pull request on hal_atmel](https://github.com/zephyrproject-rtos/hal_atmel/pull/28), which defines some needed register masks and resolves the build failures for the sam4l line of chips, but the core of the PR wasn't changed in the last commit.

2022-10-03 16:47 UTC, nandojve commented
Hi @nick-kraus ,

Please, update:
  * rebase on top of current main
  * update hash with latest from hal_atmel
  * reorder commits to add west changes first

Thank you!

2022-10-04 03:43 UTC, nick-kraus commented
@nandojve I've performed the suggested changes, AFAIK this should be ready on my end to merge, just needs the re-reviews after the new push.

2022-10-04 15:51 UTC, nandojve requested changes
Hi @nick-kraus ,

Overall LGTM ! Please, fix that small alignments.

2022-10-04 15:51 UTC, nandojve commented on drivers/serial/usart_sam.c
> +		       | US_CR_RXDIS | US_CR_TXDIS | US_CR_RSTSTA;
```
	usart->US_CR = US_CR_RSTRX | US_CR_RSTTX
		     | US_CR_RXDIS | US_CR_TXDIS
		     | US_CR_RSTSTA;
```

2022-10-04 15:51 UTC, nandojve commented on drivers/serial/usart_sam.c
> +		| usart_sam_cfg2sam_flow_ctrl(cfg->flow_ctrl);
```
	usart->US_MR = US_MR_CHMODE_NORMAL
		     | US_MR_USCLKS_MCK
		     | usart_sam_cfg2sam_parity(cfg->parity)
		     | usart_sam_cfg2sam_stop_bits(cfg->stop_bits)
		     | usart_sam_cfg2sam_data_bits(cfg->data_bits)
		     | usart_sam_cfg2sam_flow_ctrl(cfg->flow_ctrl);
```

2022-10-04 15:51 UTC, nandojve commented on drivers/serial/uart_sam.c
> +			| UART_CR_RXDIS | UART_CR_TXDIS | UART_CR_RSTSTA;
```
	uart->UART_CR = UART_CR_RSTRX | UART_CR_RSTTX
		      | UART_CR_RXDIS | UART_CR_TXDIS
		      | UART_CR_RSTSTA;
```

2022-10-04 15:51 UTC, nandojve commented on drivers/serial/uart_sam.c
> +			| uart_sam_cfg2sam_parity(cfg->parity);
```
	uart->UART_MR = UART_MR_CHMODE_NORMAL
		      | uart_sam_cfg2sam_parity(cfg->parity);
```

2022-10-05 17:26 UTC, nick-kraus commented
> Hi @nick-kraus ,
> 
> I noted that your last update not aligned `=` with `|` yet. Use TABs most you can and then complete with spaces.

Apologies, just noticed that the zephyr repo has a tab width of 8, whereas my editor was set to 4. The last commit was to resolve that comment, but that obviously didn't work out. I'll make an update tonight with the proper width.

2022-10-06 20:47 UTC, nandojve approved these changes

2022-10-06 21:09 UTC, dcpleung approved these changes

2022-10-06 22:37 UTC, merged