doc/release-note-3.2: storage changelog
zephyrproject-rtos/zephyr pull request #50743
Opened 2022-09-28 09:47 UTC by nvlsianpu

Summary on storage updates for 3.2 release.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2022-09-28 11:12 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +* :c:macro:`FLASH_AREA_LABEL_EXISTS`, :c:macro:`FLASH_AREA_ID`,
@de-nordic @carlescufi Can you confirm that it is true.

2022-09-28 16:08 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +  device with `status = "okay"` but with no driver compiled in.
I can tell you that there is no issue registered for that.

2022-09-28 16:27 UTC, fabiobaltieri commented on doc/releases/release-notes-3.2.rst
> +  device with `status = "okay"` but with no driver compiled in.
Ok can you file one? Then this can be dropped, I'll add the bug with the other open ones before wrapping the notes.

2022-09-28 16:39 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +  device with `status = "okay"` but with no driver compiled in.
registered the known issue https://github.com/zephyrproject-rtos/zephyr/issues/50768

2022-09-28 17:05 UTC, fabiobaltieri commented on doc/releases/release-notes-3.2.rst
> +  device with `status = "okay"` but with no driver compiled in.
Thanks, can you drop this one then?

2022-09-29 07:25 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +  device with `status = "okay"` but with no driver compiled in.
OK

2022-09-29 07:43 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +* :c:macro:`FLASH_AREA_LABEL_EXISTS`, :c:macro:`FLASH_AREA_ID`,
ref.: https://github.com/zephyrproject-rtos/zephyr/pull/48174

2022-09-29 08:48 UTC, fabiobaltieri approved these changes, later dismissed

2022-09-29 13:07 UTC, nvlsianpu commented on doc/releases/release-notes-3.2.rst
> +* :c:macro:`FLASH_AREA_LABEL_EXISTS`, :c:macro:`FLASH_AREA_ID`,
actually this PR should have been merged: https://github.com/zephyrproject-rtos/zephyr/pull/49974

2022-09-29 13:40 UTC, mmahadevan108 requested changes
This cannot be merged till the PR that deprecates the macros is merged.

2022-09-29 13:47 UTC, fabiobaltieri commented on doc/releases/release-notes-3.2.rst
> +  * :c:func:`flash_area_open` returns error if area's flash device is unrichable.
s/unrichable/unreachable/

2022-09-29 15:15 UTC, nvlsianpu commented
@mmahadevan108 I removed the deprecation report - it has own PR along with deprecation of these macros.

2022-09-29 15:41 UTC, mmahadevan108 approved these changes

2022-09-29 15:47 UTC, mmahadevan108 commented on doc/releases/release-notes-3.2.rst
> +  * `flash_area` components were reworked so build-time reference to the flash
Missing an extra opening and closing '

2022-09-29 15:49 UTC, mmahadevan108 submitted a review, later dismissed
Minor formatting issue

2022-09-30 08:52 UTC, fabiobaltieri approved these changes, later dismissed

2022-09-30 12:42 UTC, stephanosio requested changes

2022-09-30 13:07 UTC, mmahadevan108 commented
@nvlsianpu can you please help address the comment.

2022-09-30 14:08 UTC, fabiobaltieri commented
Hey, pushed it for you @nvlsianpu, just address Stephanos typo, hope you don't mind, trying to wrap on the release docs. :-)

2022-09-30 14:08 UTC, fabiobaltieri approved these changes

2022-09-30 14:10 UTC, stephanosio approved these changes

2022-09-30 14:46 UTC, merged