Bluetooth: host: Log SC LTK in pairing procedure without bonding
zephyrproject-rtos/zephyr pull request #50758
Opened 2022-09-28 13:56 UTC by joerchan

Log the LE Secure Connection (SC) LTK in a pairing procedure without bonding when CONFIG_BT_LOG_SNIFFER_INFO is enabled.

Fixes: #50691

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

2022-09-28 14:01 UTC, Thalley requested changes
Works, but giving a compile error

2022-09-28 14:01 UTC, Thalley commented on subsys/bluetooth/host/smp.c
> +				bt_hex(ltk, keys->enc_size));
```suggestion
			sys_memcpy_swap(ltk, smp->tk, conn->le.keys->enc_size);
			BT_INFO("SC LTK: 0x%s (No bonding)",
				bt_hex(ltk, conn->le.keys->enc_size));
```

2022-09-28 19:27 UTC, Thalley approved these changes

2022-09-29 06:49 UTC, jori-nordic approved these changes

2022-09-29 10:15 UTC, merged