test: lib: cmsis_dsp Malloc big memory first and then the small one
zephyrproject-rtos/zephyr pull request #50804
Opened 2022-09-29 08:20 UTC by Kunli123

The calloc function requires large memory,Allocating after is easy to fail.

Fixes #50452

Signed-off-by: Kun Li <kun1x.li@intel.com>

2022-09-29 14:57 UTC, stephanosio requested changes
> The calloc function requires large memory,Allocating after is easy to fail.

Why? The rationale given here does not make much sense to me.

Sure, this "works" because of how the newlib malloc algorithm is implemented and it just happens to request a smaller chunk later through `sbrk` if `calloc(length, ...` is called first in this particular case, but there is nothing that guarantees this behaviour and is subject to change with a different version/configuration of newlib and/or with a different libc.

The fact that this test may fail depending on the order of calloc/malloc call implies that there is very little room left on this device with 64KB RAM running this test, and this test may very well fail again on this platform with a slight change in the RAM usage in the future due to other changes.

For that reason, I do not think this is the right way to go about resolving this issue. My suggestion would be:

a) look into a way to actually reduce RAM usage, OR
b) increase `min_ram: 64` to a larger value (e.g. `min_ram: 72`) so that this test is filtered out for `mec172xevb_assy6906` and other platforms with 64KB RAM, which has been demonstrated to be not so sufficient for this test.

Obviously, "a" would require more extensive changes to the internals of this test, so I would highly recommend implementing "b" as I initially suggested in https://github.com/zephyrproject-rtos/zephyr/issues/50452#issuecomment-1259748729.

2022-10-20 05:03 UTC, hunterhu3000 submitted a review, later dismissed

2022-10-20 07:02 UTC, stephanosio submitted a review, later dismissed

2022-11-04 10:52 UTC, stephanosio commented
Closing this since https://github.com/zephyrproject-rtos/zephyr/pull/51883 has already addressed this issue.

2022-11-04 10:52 UTC, closed without merging