cmake: ld: add 'defines' snippet
zephyrproject-rtos/zephyr pull request #50857
Opened 2022-09-30 13:23 UTC by hakonfam

This can be used for adding a linker snippet at the top of the linker script where the defines are.

This is useful for out of tree users that need to modify RAM/ROM start/size.

Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

2022-09-30 17:52 UTC, dcpleung approved these changes

2022-09-30 22:19 UTC, evgeniy-paltsev reviewed
I guess we should we add some docs/example about how this new functionality is planed to be used.

2022-10-03 08:10 UTC, carlocaione approved these changes

2022-10-03 09:13 UTC, tejlmand requested changes
The PR description says:
> This can be used for adding a linker snippet at the top of the linker script where the defines are.

`autoconf.h` is included when generating linker scripts, meaining all defines from Kconfig are present and ready to use.
So a downstream only define can be specified in downstream Kconfig and thereby available for example to be used by other snippets later.
So the possibility of having specific defines available is already covered.

> This is useful for out of tree users that need to modify RAM/ROM start/size.

This specific use-case is already covered through devicetree / Kconfig.
For example the use of FLASH_OFFSET, which is obtained from devicetree through Kconfig:
https://github.com/zephyrproject-rtos/zephyr/blob/39af51372dd2020e6a2397d0b2c04797102f3775/Kconfig.zephyr#L99-L103
https://github.com/zephyrproject-rtos/zephyr/blob/39af51372dd2020e6a2397d0b2c04797102f3775/include/zephyr/arch/arm/aarch32/cortex_m/scripts/linker.ld#L38

allowing a defines snippet, because of this reason is a bad idea, as it suddenly allows users to bypass other config possibilities, such as devicetree / Kconfig.

It may even cause confusion and hard to debug / understand why settings from devicetree are are suddenly ignored.

There may be good reason for supporting this, but the current proposal and use-case stated has a risk of creating more confusion.
So currently I cannot approve.

2022-10-03 10:43 UTC, hakonfam commented
Not accepted, so closing to stop people wasting time on review :)

2022-10-03 10:43 UTC, closed without merging