twister: Add 'fail-on-skip' argument
zephyrproject-rtos/zephyr pull request #51093
Opened 2022-10-07 20:52 UTC by asemjonovs

When any tests are skipped with reason 'ztest skip' and fail-on-skip is specified, twister will return failure.

Signed-off-by: Al Semjonovs <asemjonovs@google.com>

2022-10-07 21:00 UTC, yperess approved these changes

2022-10-09 04:08 UTC, yperess requested changes
Missed this, please update the docs for twister (https://docs.zephyrproject.org/latest/develop/test/twister.html)

2022-10-10 07:45 UTC, PerMac reviewed
When such feature could be useful? Why skips for ztest cases are in particular interesting? I assumed that ztest should only skip a case when it is ordered within the source code.   
Maybe you can use some other variable name? It can be confusing, since test is IMO to vague in this context. Since the variable refers to ztest test cases only, maybe sth like `_skipped_zcases`?

2022-10-10 14:59 UTC, asemjonovs commented
> When such feature could be useful? Why skips for ztest cases are in particular interesting? I assumed that ztest should only skip a case when it is ordered within the source code. Maybe you can use some other variable name? It can be confusing, because `test` is IMO to vague in this context. Since the variable refers to ztest test cases only, maybe sth like `_skipped_zcases`?

@PerMac - a use case for this would be when a `zassume_*` fails in the setup phase of a test.  This will mark the test as skipped.  Twister will report success in this scenario.  With this flag we would be able to catch when `zassume` fails as well.  Ideally we should have a test that fails for what `zassume` is checking. I can update the variable to reflect whats being tracked.

2022-10-11 07:15 UTC, PerMac commented
Thanks for the explanation. I have some following questions (not that I am against, it's just interesting). So this functionality aims for the zassume skips? If so, maybe it would be more direct to check if it was zassume, and not other skip? 
I haven't yet played with zassume, hence my questions. How does `when a zassume_* fails in the setup phase of a test. This will mark the test as skipped.` align with https://github.com/zephyrproject-rtos/zephyr/pull/49640? Does it mean that if #49640 goes it, this PR is no longer needed?

2022-10-11 16:08 UTC, yperess commented
> Thanks for the explanation. I have some following questions (not that I am against, it's just interesting). So this functionality aims for the zassume skips? If so, maybe it would be more direct to check if it was zassume, and not other skip? I haven't yet played with zassume, hence my questions. How does `when a zassume_* fails in the setup phase of a test. This will mark the test as skipped.` align with #49640? Does it mean that if #49640 goes it, this PR is no longer needed?

Yes that's correct, honestly, I forgot about that PR. Either one of these should work for our needs.

2022-10-11 16:23 UTC, asemjonovs commented
> Thanks for the explanation. I have some following questions (not that I am against, it's just interesting). So this functionality aims for the zassume skips? If so, maybe it would be more direct to check if it was zassume, and not other skip? I haven't yet played with zassume, hence my questions. How does `when a zassume_* fails in the setup phase of a test. This will mark the test as skipped.` align with #49640? Does it mean that if #49640 goes it, this PR is no longer needed?

I wasn't aware of this PR, I actually think https://github.com/zephyrproject-rtos/zephyr/pull/49640 does a better job of associating a `zassume` to an overall failure.

2022-10-11 16:23 UTC, closed without merging