Devicetree: edtlib: fix possible AttributeError in Property.description
zephyrproject-rtos/zephyr pull request #51139
Opened 2022-10-10 16:03 UTC by dottspina

Attempting to access the Python property `Property.description` when `Property.spec.description` is `None` would raise:

```
AttributeError: 'NoneType' object has no attribute 'strip'.
```

Known DT properties that may not have a description (`Property.spec.description` is `None`):

- `compatible` for nodes such as `/`, `/soc`, `/soc/timer@e000e010`, `/leds` or `/pwmleds`
- `reg`        for nodes such as `/soc/timer@e000e010`
- `status`    for nodes such as `/soc/timer@e000e010`
- `gpios`     for nodes such as `/leds/led_0` or ` /buttons/button_0`
- `pwms`    for nodes such as `/pwmleds/pwm_led_0`

This patch checks the `PropertySpec.description` attribute before calling `strip()`: will return `None`, and not raise `AttributeError`.

**NOTE**: I'm not aware of any *legit* `edtlib` use (e.g. by scripts in [zephyr/scripts](https://github.com/zephyrproject-rtos/zephyr/tree/main/scripts)) that may trigger this issue, in particular I've never faced this `AttributeError` when building a Zephyr application. My use-case is slightly different (a shell-like interface to a devicetree and its bindings, [dtsh](https://github.com/dottspina/dtsh))

2022-10-12 04:52 UTC, mbolivar-nordic requested changes
Thanks for your fix!

We do not accept PRs with merge commit, though -- please fix your branch so it doesn't have the merge commit, and has a linear history of one commit on top of something in upstream instead. 

https://www.youtube.com/watch?v=mnVNLM7ynMQ

Patch itself looks good, thanks

2022-10-12 04:54 UTC, mbolivar-nordic commented
BTW, dtsh looks amazing! Please consider me officially interested in getting support for this into upstream Zephyr when you feel it has matured enough :). `west dtsh`, anyone?

cc @gmarull

2022-10-12 07:08 UTC, dottspina commented
@mbolivar-nordic Thanks for the review, and the link: I also prefer a linear git history, but wasn't sure of your policy regarding force push, now I know. I should have red the contribution guidelines more closely, though. Sorry for this.

2022-10-12 07:37 UTC, gmarull commented on scripts/dts/python-devicetree/src/devicetree/edtlib.py
> +        return None
```suggestion
        if self.spec.description:
            return self.spec.description.strip()
        return None
```

or

```suggestion
        return self.spec.description.strip() if self.spec.description else None
```

2022-10-12 09:10 UTC, mbolivar-nordic approved these changes

2022-10-12 17:18 UTC, dottspina commented
> You may find this easier than just heading straight to the source code: https://docs.zephyrproject.org/latest/develop/west/extensions.html#adding-a-west-extension

Yes, sure, thanks. OTOH, considering my weak Python-Fu, reading some *good* source code won't hurt ;-)

2022-10-12 18:07 UTC, galak approved these changes

2022-10-13 07:03 UTC, merged

2022-11-08 22:26 UTC, dottspina commented
> BTW, dtsh looks amazing! Please consider me officially interested in getting support for this into upstream Zephyr when you feel it has matured enough :). `west dtsh`, anyone?

@mbolivar-nordic, thanks for the kind words.

`dtsh` is slowly transitioning to beta: I plan to add *something* to show and query the SoC memory layout before the feature freeze for v0.1.0, and then spend some time on code review (as far as I can review Python code) and improving the unit tests coverage.

At this point (or even before), I'd like to have as many bug reports as possible, for as many different configurations as possible: is it appropriate to post an humble announce to `main@lists.zephyrproject.org` or `devel@lists.zephyrproject.org` ?

Also at this point, I may open a **draft** PR to start working on the `west dtsh` thing: is this the expected workflow to permit early comments without worrying Zephyr maintainers with unwanted notifications ?

Thanks.

--
chris

2022-11-14 19:57 UTC, mbolivar-nordic commented
> At this point (or even before), I'd like to have as many bug reports as possible, for as many different configurations as possible: is it appropriate to post an humble announce to `main@lists.zephyrproject.org` or `devel@lists.zephyrproject.org` ?

Yep, of course! I would recommend sending email to `devel` and cc'ing `users`.

> Also at this point, I may open a draft PR to start working on the west dtsh thing: is this the expected workflow to permit early comments without worrying Zephyr maintainers with unwanted notifications ?

Yep, a draft PR is fine.

Here is a (short!) talk which gives an overview of the upstreaming process: https://www.youtube.com/watch?v=mnVNLM7ynMQ

2023-07-06 14:05 UTC, dottspina commented
> BTW, dtsh looks amazing! Please consider me officially interested in getting support for this into upstream Zephyr when you feel it has matured enough :). `west dtsh`, anyone?
 
@mbolivar-nordic , sorry for the delay, I've been overwhelmed at work, then I needed some rest a little farther from keyboards. And apart from a couple updates, mostly to cope with a few edtlib API changes, dtsh did not really *mature*, until I eventually start to work on the `west dtsh` RFC.

I've updated design and implementation with some lessons learnt from the prototype, and tried to come to a sizeable PR that still implements enough to prove tasteful or useful: #59863.
Let me known if/when I can drop the Draft flag.

BTW:
- I've noticed edtlib has gradually added more and more Python type hinting *annotations*, looks like we all prefer when things are somewhat statically typed
- is it fine to contact you at your nordicsemi email address, when useful, to avoid spamming PR, issues, etc, with unrelated content ?  

Kind regards,
Thanks.