Not all boards require the various binary formats zephyr generates. So be selective based on the arch, SoC or board and only geenrate the binaries actually needed.
zephyrproject-rtos/zephyr pull request #5114
Opened 2017-11-22 18:32 UTC by nashif

Fixes #5009

2017-11-22 21:25 UTC, lpereira requested changes

2017-11-22 21:25 UTC, lpereira commented on misc/Kconfig
> +	default f
Shouldn't be `default n`?

2017-11-22 22:49 UTC, nashif commented on misc/Kconfig
> +	default f
yup

2017-11-23 07:40 UTC, erwango approved these changes

2017-11-23 10:58 UTC, tbursztyka approved these changes

2017-11-23 12:29 UTC, merged