add t1_test to kernel cases
zephyrproject-rtos/zephyr pull request #51288
Opened 2022-10-14 04:53 UTC by hakehuang

according to #51286 we need tag the t1 cases as t1_test

cases with explicit arch/platfrom requirement are excluded cases with platform_allow are excluded

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

2022-10-14 14:03 UTC, peter-mitsis approved these changes

2022-10-14 16:33 UTC, dcpleung approved these changes

2022-10-14 16:33 UTC, andyross commented
Nitpickery from someone who tends to be allergic to project bureaucracy:

I'm... not sure I completely get what's happening here?  Clicking through the links provided, I see "Tier 1" defined on page 8 of @nashif's slides as a hardware category.  What does a "tier 1 test" mean, exactly?  I'm guessing these are "The Tests We Expect Tier 1 Hardware To Pass"?  Can we be explicit about that in the commit message or somewhere in the doc/ tree?  Because I guarantee that people like me will come along and add tests and have no idea what "t1_test" means or whether they should copy it cargo-cult style into their new YAML files.

Maybe renaming this to "t1_mustpass" or "t1hw_requirement" might help?

No -1, just pointing out that the conventions here are getting thick.

2022-10-14 16:53 UTC, nashif requested changes
This needs to be documented first or some documation describing the purpose of this needs to be in place. What exactly is the requirement for a test to be tagged as `t1_test`?  additionally, we should not use cryptic names or even use tags for this. A set of tests will be used to test T1 boards, does not mean we have to call this t1_test. I would find another genric name, ie.. `Hardware Acceptance Test Plan` or whatever that is used for T1 boards tests but also for anyone who want to bring in a board into zephyr and verify that it works, without having to be Tier 1.

2022-10-17 03:21 UTC, hakehuang commented
> This needs to be documented first or some documation describing the purpose of this needs to be in place. What exactly is the requirement for a test to be tagged as `t1_test`? additionally, we should not use cryptic names or even use tags for this. A set of tests will be used to test T1 boards, does not mean we have to call this t1_test. I would find another genric name, ie.. `Hardware Acceptance Test Plan` or whatever that is used for T1 boards tests but also for anyone who want to bring in a board into zephyr and verify that it works, without having to be Tier 1.

@nashif we have been discussion the list of test suite in test working group for some time. and the discussion is listed in the https://github.com/zephyrproject-rtos/zephyr/issues/51286 .  During discussion, we find that helps for kernel expecters are needed to review the kernel cases for general test purpose. This PR is to list the cases to be selected, and we need some kernel expert to review the readiness of all kernel cases.  and this list can be convert to a test plan after reviewing. and we can start to define a name for this list.

2022-11-16 14:24 UTC, closed without merging