Bluetooth: crypto_toolbox: Move out Crypto Toolbox functions of host
zephyrproject-rtos/zephyr pull request #51429
Opened 2022-10-19 08:30 UTC by theob-pro

Create crypto_toolbox library that contain Crypto Toolbox functions from the BT specification.

Status:
Code is ready for review.
I will clean up the git history later.

2022-10-19 10:59 UTC, alwa-nordic requested changes

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/CMakeLists.txt
> +if(CONFIG_BT_BREDR)
I would prefer if crypto toolbox does not reference CONFIG_BT_BREDR. Let's discuss options offline.

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/Kconfig
> +    bool "Cryptographic Toolbox"
I think this should not have a prompt. I'm my mind this is not a user option.
```suggestion
    bool
```

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/Kconfig
> +      This option enable the Bluetooth Cryptographic Toolbox.
```suggestion
      This option enables the Bluetooth Cryptographic Toolbox.
```

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/Kconfig
> +	  This option enables debug support for the Bluetooth
```suggestion
	  This option enables debug log output for the Bluetooth
```

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/crypto_toolbox_f4.c
> +#include <zephyr/bluetooth/crypto_toolbox/aes_cmac.h>
Please run clang-format on all the new files.

2022-10-19 10:59 UTC, alwa-nordic commented on subsys/bluetooth/crypto_toolbox/include/zephyr/bluetooth/crypto_toolbox/h6.h
> + * @retval @-EIO
The `@` should not be there.

2022-10-31 14:04 UTC, carlescufi requested changes
Why `crypto_toolbox`? It is unnecessary long?
I would suggest `bt_crypto` or `host_crypto`.

2022-11-02 12:29 UTC, carlescufi commented
Superseded by #51809

2022-11-02 12:29 UTC, closed without merging