bluetooth: host: Check BT_DEV_ENABLE bit with bt_rand() calls
zephyrproject-rtos/zephyr pull request #51453
Opened 2022-10-19 15:35 UTC by ahmedmoheb-nordic

Check if BT_DEV_ENABLE flag in bt_dev.flags is set before generating a random number.

Signed-off-by: Ahmed Moheb <ahmed.moheb@nordicsemi.no>

2022-10-19 16:51 UTC, Thalley submitted a review, later dismissed

2022-10-20 08:25 UTC, jori-nordic approved these changes

2022-10-20 09:20 UTC, Thalley reviewed
It kind of feels like we are going into a rabbit whole with this check now :D 

If the BT dev is not enabled, `bt_hci_le_rand` would currently already return 
```c
	/* Check first that HCI_LE_Rand is supported */
	if (!BT_CMD_TEST(bt_dev.supported_commands, 27, 7)) {
		return -ENOTSUP;
	}
```

It could be argued that since all HCI commands does depend on the BT dev being enabled, the common check could be placed in `bt_hci_cmd_send_sync` and `bt_hci_cmd_send` (or even `bt_hci_cmd_create`), as `bt_hci_cmd_send_sync` and `bt_hci_cmd_send` are public functions that also can be called before `bt_enable` has been called. 

I am not sure what the correct course of action is, but it feels odd to only guard this specific HCI command. 

@jhedberg @alwa-nordic Should we, or should we not, guard calls that trigger HCI commands before `bt_enable` has been called?

2022-10-20 10:04 UTC, jhedberg requested changes
> @jhedberg @alwa-nordic Should we, or should we not, guard calls that trigger HCI commands before bt_enable has been called?

It's not even as simple as that, since there are initialisation commands as part of the HCI init procedure that are sent during the `bt_enable()` call. The HCI driver's `send()` callback will likely also return an error if the driver hasn't had its `open()` callback called, so I'm not sure we want to add new places to the host code to check for the same thing. Anyway, I do agree that what we definitely shouldn't do is to add command-specific tests like this PR is now doing.

2022-10-20 10:27 UTC, Thalley commented
> It's not even as simple as that, since there are initialisation commands as part of the HCI init procedure that are sent during the `bt_enable()` call. The HCI driver's `send()` callback will likely also return an error if the driver hasn't had its `open()` callback called, so I'm not sure we want to add new places to the host code to check for the same thing. Anyway, I do agree that what we definitely shouldn't do is to add command-specific tests like this PR is now doing.

But looking at something like `bt_hci_cmd_send_sync`, it would just put the command on the `bt_dev.cmd_tx_queue` and then timeout when it hasn't been handled. That would either do an assert (`BT_ASSERT_MSG(err == 0, "k_sem_take failed with err %d", err);`) or return `-EIO` after `HCI_CMD_TIMEOUT` (currently 10 seconds). 

So basically if someone calls anything that sends a HCI command, they will either get an assert, or an `-EIO` after 10 seconds, neither of which is a good indication that the BT stack isn't enabled. 

`bt_hci_cmd_send` works differently and calls `bt_dev.drv->send` directly, but it never checks if `bt_dev.drv->send` is non-NULL either, so instead of returning an error, it will probably throw a segmentation fault. 

Neither of the above is something I'd consider a good user experience, but it's been that way for a long time without any issues raised about it, so I understand if we do not want to change anything. 

@ahmedmoheb-nordic Did something specific happen that caused you to add these checks in the first place?

2022-10-20 10:48 UTC, ahmedmoheb-nordic commented
> @ahmedmoheb-nordic Did something specific happen that caused you to add these checks in the first place?

No, I'm currently working on adding UTs for different host modules, and I found that check being used in one place before calling `bt_rand()` but not used in other places with similar functionality.

2022-10-20 11:33 UTC, jhedberg commented
My current feeling is that we should add (assuming we don't have it already) a host-side flag to track whether hci_drv->open() has been successfully called, and clear this flag whenever hci_drv->close() gets called. The HCI command sending functions (both the sync and async ones) should then check for this flag and return an immediate error if the HCI transport is not open.

2022-10-20 13:01 UTC, jhedberg commented
> Can't we just check for bt_dev.drv->send == NULL?

@Thalley we never set it to NULL, nor can we, since the driver data is treated as const by the host. This also matches the actual HCI driver-side implementations of the struct: most, if not all drivers (native controller included) declare it as const, thereby placing it in ROM.

2022-10-24 10:49 UTC, alwa-nordic commented
I like @jhedberg's proposal. The HCI transport is a layer below the Host. Functions that just directly use HCI should not check `bt_dev.flags.BT_DEV_ENABLE` because that is for telling if *the Host* is available.

2022-10-24 13:52 UTC, Thalley commented
> I like @jhedberg's proposal. The HCI transport is a layer below the Host. Functions that just directly use HCI should not check `bt_dev.flags.BT_DEV_ENABLE` because that is for telling if _the Host_ is available.

Maybe a bit of nit-picking, but isn't that more for telling if the _controller_ is ready? 

Part of calling `bt_enable` is sending the `hci_reset` to put the controller into a known state

The flags are defined as 
```c
/* bt_dev flags: the flags defined here represent BT controller state */
enum {
	BT_DEV_ENABLE,
	...
```

But maybe that's no longer the case :)

2022-10-24 14:05 UTC, jhedberg commented
@Thalley the code comment about the flag is probably outdated. They’re meant to track any boolean-style state information that the host needs to track. Some of them may be about the state of the controller, others about the state of the HCI driver (eg “is the HCI transport open?”) and some about host-internal state. So I wouldn’t get hung up on that.

2022-10-28 14:07 UTC, alwa-nordic approved these changes, later dismissed

2022-11-23 13:51 UTC, jori-nordic approved these changes

2023-01-24 09:38 UTC, alwa-nordic approved these changes

2023-04-10 00:29 UTC, closed without merging