drivers: gpio: expose gpio_utils.h to external GPIO drivers
zephyrproject-rtos/zephyr pull request #51526
Opened 2022-10-21 18:55 UTC by balajikulkarni

Expose "gpio_utils.h" header for external GPIO drivers.

Fixes #48609.

Signed-off-by: Balaji Kulkarni <balaji.kulkarni92@gmail.com>

2022-10-26 03:34 UTC, balajikulkarni commented
@nashif, @carlescufi, @galak could you please have a look at the PR or suggest any other reviewers who need to review it?

2022-10-26 13:08 UTC, cfriedt commented on include/zephyr/drivers/gpio/gpio_utils.h
>  #define ZEPHYR_DRIVERS_GPIO_GPIO_UTILS_H_
```suggestion
#define ZEPHYR_INCLUDE_DRIVERS_GPIO_GPIO_UTILS_H_
```

2022-10-26 13:10 UTC, cfriedt requested changes
@balajikulkarni - please also need to get rid of the merge commits. 
```
git rebase -i <commit to remove>^
```

2022-10-26 23:43 UTC, cfriedt commented
@balajikulkarni - can you squash all of your changes into a single commit as well?
`git rebase -i HEAD~6` and then replace `pick` with `squash` for all but the first commit.

2022-10-27 03:12 UTC, balajikulkarni commented
> @balajikulkarni - can you squash all of your changes into a single commit as well? `git rebase -i HEAD~6` and then replace `pick` with `squash` for all but the first commit.

Done.

2022-10-27 10:17 UTC, cfriedt approved these changes

2022-10-27 10:18 UTC, cfriedt commented
@henrikbrixandersen - does this seem reasonable to you?

2022-10-27 10:20 UTC, henrikbrixandersen approved these changes
Yes.

2022-10-27 13:38 UTC, merged