samples: blinky_pwm: fix missing project renaming
zephyrproject-rtos/zephyr pull request #51542
Opened 2022-10-23 10:15 UTC by gportay

The commit bfb1040612b69307ec177ca87cf31ee591527757 has renamed the sample blink_led to blinky_pwm, however, the project still have the former name: blink_led.

This renames the project to its new name: blinky_pwm.

Signed-off-by: Gaël PORTAY <gael.portay@gmail.com>

2022-10-24 08:13 UTC, henrikbrixandersen requested changes

2022-10-24 08:13 UTC, henrikbrixandersen commented on samples/basic/blinky_pwm/CMakeLists.txt
> +project(blink_pwm)
```suggestion
project(blinky_pwm)
```

2022-10-24 09:09 UTC, gportay commented on samples/basic/blinky_pwm/CMakeLists.txt
> +project(blink_pwm)
:facepalm:

2022-10-24 09:25 UTC, henrikbrixandersen approved these changes
😁

2022-10-31 14:22 UTC, MaureenHelm approved these changes

2022-10-31 14:23 UTC, merged