mgmt: mcumgr: Move mgmt headers to include file
zephyrproject-rtos/zephyr pull request #51556
Opened 2022-10-24 10:54 UTC by nordicjm

This moves mgmt headers to the include directory so that they can be used in documentation output.

This has highlighted a bug in the zephyr mcumgr documentation which has mixed up 2 group IDs, and shows that things in the documentation e.g. IDs should not be manually generated and should automatically generated tables instead.

2022-10-26 13:34 UTC, de-nordic requested changes
Can't the documentation be fixed other way?
I am putting a lot of effort to move mcumgr headers out of common Zephyr space, and this works against that efforts.

2022-10-26 13:46 UTC, nordicjm commented
> Can't the documentation be fixed other way?

No, I asked @gmarull and it will only pick up files in `zephyr/include`

2022-10-26 15:42 UTC, de-nordic commented
> > Can't the documentation be fixed other way?
> 
> No, I asked @gmarull and it will only pick up files in `zephyr/include`

It is a bummer, because now every mcumgr header, that is API interface for something in mcumgr, I have placed under '<mgmt/mcumgr/whatever>', I will have to be moved to '<zephyr/mgmt/mcumgr/whatever>.

2022-10-27 06:51 UTC, nordicjm commented
@gmarull is there no way we can expand the sphinx documentation listing to subsystems, even if it's a long term goal?

2022-10-27 07:27 UTC, gmarull commented
> @gmarull is there no way we can expand the sphinx documentation listing to subsystems, even if it's a long term goal?

Afaik all subsystems have their public APIs in `include`, why should mcumgr be an exception?

2022-10-27 07:31 UTC, nordicjm commented
> Afaik all subsystems have their public APIs in include, why should mcumgr be an exception?

For mcumgr not everything is enabled by default, it is dependent upon configuration, for example fs_mgmt is only enabled if the corresponding Kconfig is set, otherwise it is disabled, so the includes would not be in zephyr's path.

2022-10-27 07:42 UTC, gmarull commented
> > Afaik all subsystems have their public APIs in include, why should mcumgr be an exception?
> 
> For mcumgr not everything is enabled by default, it is dependent upon configuration, for example fs_mgmt is only enabled if the corresponding Kconfig is set, otherwise it is disabled, so the includes would not be in zephyr's path.

I don't think we have such practice in other areas. You can always include a header, if not enabled you'll just get linker errors in most cases (compile errors if you have stuff like conditional declarations, struct fields, etc.).

2022-10-27 07:45 UTC, nordicjm commented
In that case, looks like https://github.com/zephyrproject-rtos/zephyr/pull/50936 will need to be reworked @de-nordic

2022-10-27 07:51 UTC, gmarull commented
> In that case, looks like #50936 will need to be reworked @de-nordic

One can always include headers conditionally (in fact, it's not a bad idea if you don't need them). But they can always be discoverable. If not following this rule, we should basically rework much of the content/practices in `include/`.

2022-11-17 10:26 UTC, de-nordic commented
@nordicjm You have already agreed to move the mgmt.h file here [include/zephyr/mgmt/mcumgr/mgmt/mgmt.h](https://github.com/zephyrproject-rtos/zephyr/pull/50936/files#diff-d14a8a93be33636e3d276481c6c53ca3e587a937726d7c8913803fcb170c52a6), so change the PR to do the same.

2022-11-17 14:38 UTC, de-nordic approved these changes, later dismissed

2022-11-17 15:27 UTC, de-nordic submitted a review, later dismissed

2022-11-22 10:07 UTC, de-nordic submitted a review, later dismissed

2022-11-23 11:12 UTC, de-nordic approved these changes

2022-11-23 11:19 UTC, carlescufi approved these changes

2022-11-23 11:19 UTC, merged