doc: samples: can: update sample path for mcp2515 board and isotp sample code block
zephyrproject-rtos/zephyr pull request #51615
Opened 2022-10-25 14:59 UTC by str4t0m

Update the path of the can counter sample in the mcp2515 shild docs,
as well as the path of the subsys/canbus/isotp code example in the docs.

2022-10-25 15:02 UTC, henrikbrixandersen requested changes
Looks good, but please split into two commits.

2022-10-25 15:10 UTC, str4t0m commented
I have now split it into 2 commits.

2022-10-25 15:12 UTC, henrikbrixandersen approved these changes
Thanks!

2022-10-26 10:01 UTC, martinjaeger approved these changes

2022-10-27 09:02 UTC, carlescufi approved these changes

2022-10-27 09:02 UTC, merged