ITE: drivers/i2c: Print the error messages when I2C transfers fail
zephyrproject-rtos/zephyr pull request #51634
Opened 2022-10-26 09:04 UTC by GTLin08

Print the error messages about the state of the host register when the I2C transfers fail. This is useful for debugging.

Signed-off-by: Tim Lin <tim2.lin@ite.corp-partner.google.com>

2022-10-26 13:41 UTC, teburd requested changes
printk's here should be ~LOG_DBG's~ LOG_ERR's

2022-10-26 15:07 UTC, keith-zephyr commented
> printk's here should be LOG_DBG's

`LOG_ERR` seems more appropriate in this case.

2022-10-27 03:25 UTC, GTLin08 commented
> > printk's here should be LOG_DBG's
> 
> `LOG_ERR` seems more appropriate in this case.

Done.

2022-10-27 17:00 UTC, keith-zephyr approved these changes

2022-10-27 19:42 UTC, teburd approved these changes

2022-10-28 07:55 UTC, merged