Extend settings_runtime_commit to support all commits
zephyrproject-rtos/zephyr pull request #51705
Opened 2022-10-27 10:36 UTC by hno-wires

This replaces settings_runtime_commit() with a wrapper for settings_commit_subtree(), extending the functionality to support global commit and nested subtree commits.

Fixes #51703

2022-10-27 10:39 UTC, carlescufi commented
@hno-addiva thanks!
See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

2022-10-27 10:46 UTC, de-nordic commented
Please also add commit with release notes entry mentioning the Zephyr issue being fixed.

2022-11-09 14:07 UTC, de-nordic commented
@hno-addiva ping?

2022-11-25 10:57 UTC, rakons commented
It seems that some settings related tests are failing.

2023-01-17 09:35 UTC, rakons requested changes
NAK as the tests are failing. It seems that settings_runtime_commit functionality was different than settings_commit_subtree.

2023-02-23 16:23 UTC, teburd commented
@mniestroj please take a look

2023-02-23 19:38 UTC, mniestroj commented on subsys/settings/src/settings_runtime.c
> +	return settings_commit_subtree(name);
> I also thought of proposing it to be dropped as useless.

I was not using `settings_runtime` recently and actually this was my first view into `settings_runtime_commit()` implementation. But my first impression was that it should be dropped.

This is also the reason why I referenced 94451b22fcc6a068de2a2982b202772c6bbefae8, which provides no explanation why it was introduced in the first place. And from that commit we can see that the only user of this API were some test cases.

Just sharing my concerns here, I don't have strong opinion on that. I think also that we lack some sort of guidelines for when to use settings vs settings_runtime and what should be the use cases. At least that is not clear to me, even after using both, I am still not certain that I am doing it in a valid way.

2023-03-09 16:30 UTC, MaureenHelm commented
@de-nordic ping

2023-04-03 10:08 UTC, de-nordic commented
> @de-nordic ping

There isn't that much interest in the change, and it seems that issue has not been raised by other developers so far.

By the comment https://github.com/zephyrproject-rtos/zephyr/pull/51705#discussion_r1116020316
> But not going to work more on this at the moment. The project where we was using Zephyr is unfortunately on hold (but not due to Zephyr fault). We will surely come back to Zephyr in future.
It seems that currently the fix will not be pursued by the author either. Test have also not been altered to work with the enhancement provided here.

If this is still considered need enhancement issue and anyone finds this work to be important improvement, please add Enhance request to Zephyr issues, describing what is currently done wrong and how proposed solution fixes that, and follow it with implementation (if any).

@MaureenHelm  Closing due to lack of interest at the moment.

2023-04-03 10:08 UTC, closed without merging