drivers: sensor: bmp388: Add I2C-base or SPI-base interface in build …
zephyrproject-rtos/zephyr pull request #51878
Opened 2022-11-02 06:57 UTC by Cherish-Gww

…time

move DT_DRV_COMPAT to bmp388.h. so that can be decide which interface to use. define struct bmp388_bus_io interface bmp388_i2c.c and bmp388_spi.c. redefined bus operation interface in bmp388.c, this allow the driver to decide which interface to use during construction

Signed-off-by: Cherish <guoweiwei@syriusrobotics.com>

2022-11-09 19:40 UTC, MaureenHelm commented
Closing and reopening to kick CI

2023-01-06 14:38 UTC, MaureenHelm requested changes

2023-01-06 14:38 UTC, MaureenHelm commented on drivers/sensor/bmp388/Kconfig
> +	default BMP388_TRIGGER_NONE
Is this really related to SPI/I2C?

2023-01-11 15:46 UTC, MaureenHelm reviewed
Code changes LGTM, but please fix the failed compliance check.
```
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 67c059a622faa177b14cbf9dbdbb3208b9c83e6a: author email (Cherish <guoweiwei@syriusrobotics.com>) does not follow the syntax: First Last <email>.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 1: UC2 Signed-off-by: must have a full name
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style for more details.

 CODE_INDENT: code indent should use tabs where possible
File:drivers/sensor/bmp[38](https://github.com/zephyrproject-rtos/zephyr/actions/runs/3889195593/jobs/6648105591#step:9:39)8/bmp388.c
Line:561
 LEADING_SPACE: please, no spaces at the start of a line
File:drivers/sensor/bmp388/bmp388.c
Line:561
 CODE_INDENT: code indent should use tabs where possible
File:drivers/sensor/bmp388/bmp388.c
Line:566
 LEADING_SPACE: please, no spaces at the start of a line
File:drivers/sensor/bmp388/bmp388.c
Line:566
```

2023-02-03 17:52 UTC, MaureenHelm approved these changes

2023-03-17 21:23 UTC, MaureenHelm commented
@teburd @yperess please take a look

2023-04-07 11:13 UTC, carlescufi approved these changes

2023-04-07 11:14 UTC, merged