drivers: adc: adc_sam: Introduce Atmel SAM ADC driver
zephyrproject-rtos/zephyr pull request #51885
Opened 2022-11-02 10:48 UTC by pdgendt

Introduce Atmel SAM ADC driver, and add it to the Atmel SAM4S SoC. 
All of the timings are currently set for the controller instead of individual channels, so only `ADC_ACQ_TIME_DEFAULT` is supported.

Tested on custom board.

@nandojve I will probably need to add this to the `sam4s_xplained` board to take it along in CI. Any suggestions to make it testable?

2022-11-02 19:59 UTC, nandojve commented
> Introduce Atmel SAM ADC driver, and add it to the Atmel SAM4S SoC. All of the timings are currently set for the controller instead of individual channels, so only `ADC_ACQ_TIME_DEFAULT` is supported.
> 
> Tested on custom board.
> 
> @nandojve I will probably need to add this to the `sam4s_xplained` board to take it along in CI. Any suggestions to make it testable?

Hi @pdgendt,

You can make PB0 and PB1 available as ADC inputs since this is instructed on the SAM4S_Xplained schematic.
About CI, it will be good if we can get both sample and tests running [adc sample](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/adc) + [adc tests](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/adc).

2022-11-07 14:42 UTC, pdgendt commented
@nandojve I've updated the boards/samples/tests

2023-01-07 12:06 UTC, nandojve commented
> @nandojve I've updated the boards/samples/tests

Hi @pdgendt ,

This still as a draft or you want to have it on v3.3?

2023-01-09 08:01 UTC, pdgendt commented
> This still as a draft or you want to have it on v3.3?

Hi @nandojve, I'll clean it up to get it in v3.3.

2023-01-13 14:13 UTC, pdgendt commented
Hi @nandojve, would you be able to test using the `sam4s_xplained` board?

2023-02-09 16:50 UTC, MaureenHelm commented
@nandojve ping

2023-02-12 15:13 UTC, nandojve commented
Hi @pdgendt ,

I configured sample to run as single end instead diff on channel 5 (PB1) and I didn't change temperature configuration.
It seems that there are something not proper with the driver. The read values oscillates and channel 5 not read correct.

The same HW configuration using ASF->SAM->Drivers->ADC sample show different behavior.

```diff
+++ b/samples/drivers/adc/boards/sam4s_xplained.overlay
@@ -9,7 +9,7 @@
 / {
        zephyr,user {
                /* adjust channel number according to pinmux in board.dts */
-               io-channels = <&adc0 2>, <&adc0 15>;
+               io-channels = <&adc0 5>, <&adc0 15>;
        };
 };
 
@@ -17,14 +17,13 @@
        #address-cells = <1>;
        #size-cells = <0>;
 
-       /* External ADC(+)/ADC(-) differential inputs */
-       channel@2 {
-               reg = <2>;
+       /* External ADC(+) */
+       channel@5 {
+               reg = <5>;
                zephyr,gain = "ADC_GAIN_1";
                zephyr,reference = "ADC_REF_EXTERNAL0";
                zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
-               zephyr,input-positive = <4>;
-               zephyr,input-negative = <5>;
+               zephyr,input-positive = <5>;
                zephyr,resolution = <12>;
        };

```

```
*** Booting Zephyr OS build v3.3.0-rc2-204-g86548f258c98 ***
ADC reading:
- adc@40038000, channel 5: 64 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 1716 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 1720 = 0 mV
ADC reading:
- adc@40038000, channel 5: 60 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 62 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 61 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 61 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 1726 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 1724 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 62 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 62 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 63 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 43 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 1754 = 0 mV
ADC reading:
- adc@40038000, channel 5: 39 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 67 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 0 = 0 mV
- adc@40038000, channel 15: 2047 = 0 mV
ADC reading:
- adc@40038000, channel 5: 146 = 0 mV
- adc@40038000, channel 15: 1717 = 0 mV
ADC reading:
- adc@40038000, channel 5: 1841 = 0 mV
- adc@40038000, channel 15: 1723 = 0 mV
ADC reading:                                                                       
- adc@40038000, channel 5: 3734 = 0 mV                                             
- adc@40038000, channel 15: 2047 = 0 mV
```

2023-03-02 16:22 UTC, teburd commented
@pdgendt please take a look

2023-03-12 14:34 UTC, nandojve commented
Hi @pdgendt ,

Any new driver should go after #55655.

2023-03-14 11:05 UTC, pdgendt commented
> Any new driver should go after #55655.

Hi @nandojve, I will update the PR once merged, for the test on `sam4s_xplained`, I think it's a clocking setting that should be tweaked.

Could you test again with the `prescaler` property set to the maximum `255`? I've done the same on my custom board and the internal temperature sensor is stable.

I don't know what sensible values would be for the timings on the `sam4s_xplained` board, any suggestions?

2023-03-14 17:52 UTC, nandojve commented
Hi @pdgendt ,

Thank you for look on it. I'll have time to look on HW at weekend. Right now my reference have been the example inside [Atmel ASF](https://ww1.microchip.com/downloads/en/DeviceDoc/asf-standalone-archive-3.52.0.113.zip) at ASF->SAM->Drivers->ADC.

2023-03-15 09:02 UTC, pdgendt commented
> Thank you for look on it. I'll have time to look on HW at weekend. Right now my reference have been the example inside [Atmel ASF](https://ww1.microchip.com/downloads/en/DeviceDoc/asf-standalone-archive-3.52.0.113.zip) at ASF->SAM->Drivers->ADC.

Great, thanks.

I used the example as a reference for my implementation, setting the `prescaler` did yield stable readings, so I guess the driver is functional.

Maybe the bindings could improve, I currently set these values as they would be set in the `MR` register. I could, for example, change the `prescaler` binding to `frequency` binding and calculate the value using your implementation for the peripheral clock.

2023-03-18 14:42 UTC, nandojve requested changes
Hi @pdgendt ,

I still not get good results. I don't know why but potentiometer oscillates which not happen with Atmel sample code, maybe a concurrency problem?

2023-03-18 14:42 UTC, nandojve commented on boards/arm/sam4s_xplained/sam4s_xplained.dts
> +	startup-time = <1>;
startup-time = <4>;

2023-03-18 14:42 UTC, nandojve commented on boards/arm/sam4s_xplained/sam4s_xplained.dts
> +	tracking-time = <2>;
tracking-time = <1>;

2023-03-18 14:42 UTC, nandojve commented on drivers/adc/adc_sam.c
> +		    | ADC_MR_TRACKTIM(cfg->tracking_time)
```diff
+                   | ADC_MR_TRANSFER(2)
```

2023-03-20 07:53 UTC, pdgendt commented on drivers/adc/adc_sam.c
> +		/* NOP */
0.5 gain is the default value after resetting, which is done before the switch/case with:

```c
	adc->ADC_CGR &= ~(ADC_CGR_GAIN0_Msk << (channel_id * 2U));
```

2023-03-20 08:06 UTC, pdgendt commented on dts/bindings/adc/atmel,sam-adc.yaml
> +    description: CPU clock prescaler applied to get the ADC clock.
The prescaler applies to all channels, can we use the `channel_cfg->acquisition_time` that applies to a single channel?

2023-03-20 08:26 UTC, pdgendt commented
Hi @nandojve,

Did you test using `prescaler = <10>`? This would yield an ADC frequency of 5,4 MHz (`120 / 2 / (prescaler + 1`). Which is higher than the allowed maximum of 1 MHz.

The minimum value is `prescaler = <59>` if I applied the correct formula (`120 / 2 / (59 + 1) = 1`).

2023-03-20 08:40 UTC, pdgendt commented on drivers/adc/adc_sam.c
> +		    | ADC_MR_ANACH_ALLOWED;
See comment https://github.com/zephyrproject-rtos/zephyr/pull/51885#discussion_r1141749364

2023-03-22 16:34 UTC, nandojve commented on dts/bindings/adc/atmel,sam-adc.yaml
> +    description: CPU clock prescaler applied to get the ADC clock.
Let's do this in another PR.

2023-03-22 16:36 UTC, nandojve approved these changes
LGTM!

2023-03-22 21:39 UTC, teburd approved these changes

2023-03-23 08:41 UTC, merged