Bluetooth: Mesh: Add specific number of keys & groups
zephyrproject-rtos/zephyr pull request #51890
Opened 2022-11-02 11:36 UTC by LingaoM

Since Mesh Spec and Mesh model sayes, some model no need groups and no need keys, 
such as Config Server, but the current implementation, all model use same configuration, 
which cause some ram ext comsume.

So that, change to specific way, but will consume more footprint size.

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

2022-11-04 10:49 UTC, Andrewpini requested changes
Seems legit. Couple of comments though

2022-11-04 11:08 UTC, PavelVPV requested changes
Good improvement! Just few minor comments from my side.

2022-11-08 07:05 UTC, Andrewpini approved these changes
Good 👍

2022-11-08 08:01 UTC, alxelax approved these changes

2022-11-08 08:02 UTC, PavelVPV approved these changes

2022-11-08 08:27 UTC, jhedberg approved these changes

2022-11-08 09:45 UTC, merged