arch/arc: Detect arcv2 TLS register automatically
zephyrproject-rtos/zephyr pull request #51922
Opened 2022-11-03 01:07 UTC by keith-packard

The compiler defines __ARC_TLS_REGNO__ as the number of the register used for TLS variables. Use that instead of hard-coding a specific register.

Signed-off-by: Keith Packard <keithp@keithp.com>

I couldn't see any other dependencies on the thread register number in the tree; with this, we should be able to switch which register is used.

2022-11-03 10:54 UTC, ruuddw requested changes
It looks like this works for ARCv2 when using GNU, but why isn't the ARCv3 + GNU case changed to use the same mechanism (line 130).
Furthermore, this solution will (probably) not work for other toolchains like MetaWare, when TLS support for Metaware is added.
It's not clear what 'problem' this PR solves.

2022-11-03 17:00 UTC, keith-packard commented
> It looks like this works for ARCv2 when using GNU, but why isn't the ARCv3 + GNU case changed to use the same mechanism (line 130). 

ARCv3 defines register 30 for this purpose and doesn't have (or need) a symbol defined in the compiler.

> Furthermore, this solution will (probably) not work for other toolchains like MetaWare, when TLS support for Metaware is added. It's not clear what 'problem' this PR solves.

When that is merged in, whatever mechanism is used to declare the TLS register can be added here.

The goal of this PR is to allow the toolchain to migrate from register 26 (the current Zephyr value) to register 25 (as used by Linux), or whatever register the toolchain reserves for this purpose without having to change this code for each toolchain.

2022-11-07 09:52 UTC, stephanosio approved these changes
> Furthermore, this solution will (probably) not work for other toolchains like MetaWare, when TLS support for Metaware is added.

This block is inside `#ifdef CONFIG_THREAD_LOCAL_STORAGE`; so, if MetaWare does not support TLS at this time, this will have no effect.

If MetaWare adds TLS support in the future and decides to provide the `__ARC_TLS_REGNO__`, then it will work as is; if not (but why not?), then MetaWare-specific handling can be added later as @keith-packard mentioned.

> It's not clear what 'problem' this PR solves.

Portability.

It allows ARCv2 arch code to use whichever register designated as the TLS register by the compiler, instead of assuming and hard-coding `r26` as the TLS register.

I do not see any reason to not do this.

2022-11-07 12:02 UTC, abrodkin commented
@keith-packard thank you so much for this nice improvement. Looks really nice and elegant to me.

2022-11-07 12:02 UTC, abrodkin approved these changes

2022-11-07 13:07 UTC, ruuddw approved these changes

2022-11-08 09:45 UTC, merged