ztest: cleanup phase should reset the timeout queue.
zephyrproject-rtos/zephyr pull request #5193
Opened 2017-11-29 11:05 UTC by AdithyaBaglody

Reusing the k_thread structure requires a cleanup of all essential
info. We need to remove the ztest_thread information from the timeout_q.

If left untouched, when a tick occurs the thread's delta_ticks_from_prev
would be corrupted. This inturn causes a chain reaction of problems.
Thus once the unit test is completed the timeout_q is scrubbed.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

2017-12-04 18:43 UTC, tyrantlizard77 requested changes
I don't think this is the fix we want.
We are basically playing around directly with internal kernel data structures, from the application, so that thread objects may be reused.
Under what circumstances does this happen anyway?
Why don't we make adjustments to the timeout queue in k_thread_abort instead?

2017-12-05 11:22 UTC, AdithyaBaglody commented
A unit test creates a new thread with the k_tid_t  ztest_thread. From there are I create another new thread(say foo). Which does some tests and tells ztest_pass(). Now the ztest_pass() will kill the new thread( i.e foo) and it doesn't kill the ztest_thread. So by the time this ztest_thread comes back to the entry function and call the abort on itself we would have reinitialized the k_thread stuct. so an abort never gets called.

We cant handle this in any kernel function because it a problem of the z test implementation.
So I understand that I shouldn't touch the data structures from ztest. I will call k thread abort on the k_tid_t ztest_thread during cleanup.

2017-12-08 07:17 UTC, SavinayDharmappa commented on tests/ztest/src/ztest.c
> +	 */
may be you have change your comment. I don't see a you are directly touching timeout queue and even your commit message as well.

2017-12-14 23:59 UTC, tyrantlizard77 requested changes
style nit.
substance of the patch looks good.

2017-12-14 23:59 UTC, andrewboie commented on tests/ztest/src/ztest.c
> +	#ifdef KERNEL
can you get rid of the leading whitespace before "#"?

2017-12-21 05:52 UTC, AdithyaBaglody commented
Delta:
Handled Andrew's review comments.

2017-12-21 06:39 UTC, punitvara commented
LGTM

2018-01-17 12:48 UTC, nashif approved these changes

2018-01-17 12:48 UTC, merged