boards: arm: nordic nrf91* nrf53* nrf52* nrf51*: Remove scratch areas
zephyrproject-rtos/zephyr pull request #52028
Opened 2022-11-07 16:11 UTC by nordicjm

The scratch partition is not needed since MCUboot now operates in
    swap using move mode instead of swap with scratch, as a result, the
    main partitions on Nordic nRF51, nRF52, nRF53 and nRF91 boards can be
    expanded to help in fitting large applications to them.

2022-11-08 09:45 UTC, de-nordic requested changes
It is still possible to configure mcuboot with `CONFIG_BOOT_SWAP_USING_SCRATCH=y`, which will make compilation fail.

2022-11-08 09:48 UTC, nordicjm commented
> It is still possible to configure mcuboot with CONFIG_BOOT_SWAP_USING_SCRATCH=y, which will make compilation fail.

I see no reason why anyone would do that given that swap using scratch is known broken and upstream MCUboot recommends avoiding it.

2022-12-13 11:00 UTC, carlescufi requested changes
Two requests:

- Add a release note
- Add somewhere (mcuboot or zephyr) documentation on how to add a scratch partition

2022-12-19 11:51 UTC, nordicjm commented
Added instructions for scratch mode setup here: https://github.com/mcu-tools/mcuboot/pull/1550

2022-12-20 10:55 UTC, carlescufi approved these changes

2022-12-20 10:56 UTC, de-nordic approved these changes

2022-12-20 10:57 UTC, merged