dts: xtensa: intel: fix alh instances
zephyrproject-rtos/zephyr pull request #52048
Opened 2022-11-08 07:46 UTC by abonislawski

"alh0: alh1:" will create only one instance and this needs to be reverted to original form with two instances

2022-11-08 08:35 UTC, juimonen approved these changes
yes lgtm, actually also have it here:
https://github.com/juimonen/zephyr/tree/native_drivers_test

just a note: in our production devices we see already more alh devices... in xtos sof we have currently 16 alh devices. So we should think how to add all of these. So should we just add all entries all come up with some other means to create all dais. same for hda.

2022-11-08 08:58 UTC, abonislawski commented
Yeap, this is true for MTL too. I just dont like this huge list of repeated devices but for now it looks like the only way to go without any refactor.

2022-11-08 09:07 UTC, kv2019i approved these changes

2022-11-08 19:48 UTC, tmleman approved these changes

2022-11-09 11:05 UTC, marcinszkudlinski approved these changes

2022-11-09 11:09 UTC, nashif approved these changes

2022-11-09 12:04 UTC, galak requested changes
Why do have 2 instances with the exact same reg properties?

2022-11-09 12:05 UTC, galak commented
@abonislawski abonislawski marking this as requesting change to understand what is going on here.

2022-11-09 15:09 UTC, galak approved these changes
OK for now, but we need to rework this completely in the future.

2022-11-09 15:09 UTC, merged