drivers: watchdog: stm32 iwdg: max prescaler value
zephyrproject-rtos/zephyr pull request #52050
Opened 2022-11-08 08:14 UTC by wojciechslenska

In some stm32 MUCs maximum prescaler value can be 1024.

Signed-off-by: Wojciech Slenska <wsl@trackunit.com>

2022-11-08 08:32 UTC, FRASTM submitted a review, later dismissed

2022-11-08 08:59 UTC, erwango approved these changes

2022-11-08 09:28 UTC, erwango requested changes
Impact on the following piece of code to be taken into account:

```
/*
 * Status register needs 5 LSI clock cycles divided by prescaler to be updated.
 * With highest prescaler (256) and considering clock variation, we will wait
 * maximum 6 cycles (48 ms at 32 kHz) for register update.
 */
#define IWDG_SR_UPDATE_TIMEOUT	(6U * IWDG_PRESCALER_MAX * \
				 MSEC_PER_SEC / LSI_VALUE)
```

2022-11-08 10:14 UTC, wojciechslenska commented
> Impact on the following piece of code to be taken into account:
> 
> ```
> /*
>  * Status register needs 5 LSI clock cycles divided by prescaler to be updated.
>  * With highest prescaler (256) and considering clock variation, we will wait
>  * maximum 6 cycles (48 ms at 32 kHz) for register update.
>  */
> #define IWDG_SR_UPDATE_TIMEOUT	(6U * IWDG_PRESCALER_MAX * \
> 				 MSEC_PER_SEC / LSI_VALUE)
> ```

I added the following logs to iwdt
```
	LOG_INF("t:%i, p:%i, r:%i", timeout, prescaler, reload);

	tickstart = k_uptime_get_32();

	LL_IWDG_Enable(iwdg);
	LL_IWDG_EnableWriteAccess(iwdg);

	LL_IWDG_SetPrescaler(iwdg, prescaler);
	LL_IWDG_SetReloadCounter(iwdg, reload);

	/* Wait for the update operation completed */
	while (LL_IWDG_IsReady(iwdg) == 0) {
		LOG_INF("not ready");
		if ((k_uptime_get_32() - tickstart) > IWDG_SR_UPDATE_TIMEOUT) {
			return -ENODEV;
		}
	}

	int diff = k_uptime_get_32() - tickstart;
	LOG_INF("max:%i, timeout:%i", (int)IWDG_SR_UPDATE_TIMEOUT, diff);
```
And I got the following results:
```
[00:00:00.000,000] <inf> iwdg: t:12000000, p:5, r:2999
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: not ready
[00:00:00.000,000] <inf> iwdg: max:192, timeout:0

[00:00:00.146,000] <inf> iwdg: t:130000000, p:8, r:4061
[00:00:00.146,000] <inf> iwdg: not ready
[00:00:00.146,000] <inf> iwdg: not ready
[00:00:00.147,000] <inf> iwdg: not ready
[00:00:00.147,000] <inf> iwdg: not ready
[00:00:00.147,000] <inf> iwdg: not ready
[00:00:00.147,000] <inf> iwdg: max:192, timeout:1
```
I don't know how this works on different MCUs but on STM32U5 there is information in RM
`takes up to three periods of the IWDG kernel clock iwdg_ker_ck`, so this maximum time is not depending on the prescaler at all.

2023-01-09 07:50 UTC, erwango commented
> I don't know how this works on different MCUs but on STM32U5 there is information in RM [...]

Ok, but still, comment should be updated to take this change into account as it mentions `highest prescaler (256)`

2023-01-20 13:10 UTC, erwango approved these changes

2023-01-20 14:10 UTC, gautierg-st approved these changes

2023-01-20 15:11 UTC, merged