Bluetooth: Fixing issue with adv_stop
zephyrproject-rtos/zephyr pull request #52149
Opened 2022-11-10 13:45 UTC by martintv

If adv stop was called form connected callback,
it would continue and unref the wrong conn object
if there where 2 connectable advertisers running,
but with only one 1 id configured.

2022-11-11 06:17 UTC, jhedberg requested changes
See my inline comments. Also a minor thing about the commit message: please use the imperative form of the verb to be consistent with the commit history, i.e. "Fix" instead of "Fixing".

2022-11-11 06:17 UTC, jhedberg commented on subsys/bluetooth/host/adv.c
> +#if (CONFIG_BT_MAX_CONN > 0) && (CONFIG_BT_EXT_ADV_MAX_ADV_SET > 1)
`BT_MAX_CONN` has a specified range with a minimum value of `1`, so testing for `> 0` will always be true if the macro is defined. Is it always guaranteed to be defined here, i.e. is `CONFIG_BT_CONN` always enabled in this part of the code? If yes, then just drop the first condition the if statement. If no, then the condition should read `#if defined(CONFIG_BT_CONN) && ...`.

2022-11-11 06:17 UTC, jhedberg commented on subsys/bluetooth/host/adv.c
> +#if (CONFIG_BT_MAX_CONN > 0) && (CONFIG_BT_EXT_ADV_MAX_ADV_SET > 1)
Same here, and in three other places (if I counted correctly), which I won't separately point out.

2022-11-11 07:26 UTC, martintv commented
> See my inline comments. Also a minor thing about the commit message: please use the imperative form of the verb to be consistent with the commit history, i.e. "Fix" instead of "Fixing".

Done

2022-11-11 09:24 UTC, jhedberg submitted a review, later dismissed

2022-11-14 08:04 UTC, jori-nordic approved these changes, later dismissed

2022-11-14 10:34 UTC, martintv commented
> I only updated the commit message to include "Fixes #52196", and rebased on main.

Sorry, I forcepushed from wrong folder locally previously, so CI failed again. Fixed now, and now the only change relative to when you approved previously is a rebase to main, and updated commitmessage.

2022-11-14 11:54 UTC, jori-nordic approved these changes

2022-11-14 12:03 UTC, jhedberg approved these changes

2022-11-14 12:07 UTC, merged