boards: arm: stm32157c-dk2: fix debug
zephyrproject-rtos/zephyr pull request #52164
Opened 2022-11-10 15:55 UTC by arnopo

Aim of this pull request :
- fixe gdb/openocd configuration to allow to to connect to the Cortex-M4 port by default
- use the openocd of the Zephyr sdk instead of the stm32mp157 sdk.
- update associated board doc

2022-11-14 10:50 UTC, erwango requested changes

2022-11-14 10:50 UTC, erwango commented on boards/arm/stm32mp157c_dk2/doc/stm32mp157_dk2.rst
> +is based on the attach to a preloded firmware, available only for a Linux
```suggestion
is based on the attach to a preloaded firmware, available only for a Linux
```

2022-11-14 10:50 UTC, erwango commented on boards/arm/stm32mp157c_dk2/doc/stm32mp157_dk2.rst
> +      west build -b stm32mp157c_dk2 samples/hello_world
Might be clearer to use codeblocks ?

.. code-block:: console

2022-11-15 08:07 UTC, erwango approved these changes

2022-11-15 11:20 UTC, FRASTM approved these changes

2022-11-15 12:18 UTC, merged