boards: mps2_an521: clean up memory map
zephyrproject-rtos/zephyr pull request #52249
Opened 2022-11-15 12:59 UTC by mbolivar-nordic

Fix comments in board DTS files referring to AN521 tables defining memory areas, and choose node label names that more accurately reflect the entries of interest in those tables.

@ktown this reflects the first couple of things we talked about. I thought about how to plumb the cpu1 start address from DT all the way through, but I think that's going to require system devicetree. It's an interesting use case that I hadn't considered, though, and will definitely affect the design.

2022-11-15 13:41 UTC, microbuilder commented
> Fix comments in board DTS files referring to AN521 tables defining memory areas, and choose node label names that more accurately reflect the entries of interest in those tables.
> 
> @ktown this reflects the first couple of things we talked about. I thought about how to plumb the cpu1 start address from DT all the way through, but I think that's going to require system devicetree. It's an interesting use case that I hadn't considered, though, and will definitely affect the design.

I think you're looking for @microbuilder sorry (terrible name from a company I ran lifetimes ago). I'm sure someone is very confused about who you are and what you're tagging them for. 😉

2022-11-15 13:45 UTC, microbuilder requested changes

2022-11-15 13:45 UTC, microbuilder commented on boards/arm/mps2_an521/mps2_an521_ns.dts
> +		 * https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
Perhaps better to point to Zephyr's fork, which is what we actually use at compile time:

```suggestion
		 * https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/master/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
```

2022-11-15 13:45 UTC, microbuilder commented on boards/arm/mps2_an521/mps2_an521_remote.dts
> +		 * https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
```suggestion
		 * https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/master/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
```

2022-11-15 13:46 UTC, microbuilder commented on boards/arm/mps2_an521/mps2_an521_remote.dts
> +		 * https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
```suggestion
		 * https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/master/platform/ext/target/arm/mps2/an521/partition/flash_layout.h
```

2023-01-30 17:47 UTC, mbolivar-nordic commented
Rebased with no changes to see if twister passes this time

2023-01-30 20:58 UTC, dcpleung approved these changes

2023-01-31 21:15 UTC, microbuilder approved these changes

2023-02-20 01:55 UTC, merged