boards/arm64/qemu_cortex_a53: Synchronize defconfigs
zephyrproject-rtos/zephyr pull request #52322
Opened 2022-11-17 10:42 UTC by hx-bora

The various qemu_cortex_a53 defconfigs diverged.

We harmonize these files, and put the config-specific features at the end.

2022-11-17 10:56 UTC, carlocaione requested changes

2022-11-17 10:56 UTC, carlocaione commented on boards/arm64/qemu_cortex_a53/qemu_cortex_a53_smp_defconfig
> +CONFIG_QEMU_ICOUNT_SLEEP=y
If we really really really do not need this, I'd leave this out.

2022-11-17 10:56 UTC, carlocaione commented on boards/arm64/qemu_cortex_a53/qemu_cortex_a53_xip_defconfig
> +
ditto

2022-11-17 12:02 UTC, carlocaione commented on boards/arm64/qemu_cortex_a53/qemu_cortex_a53_smp_defconfig
> +CONFIG_QEMU_ICOUNT_SLEEP=y
for the XIP is probably simply forgotten. The XIP should closely follow what's done for `qemu_cortex_a53`.

2022-11-17 13:05 UTC, carlocaione commented on boards/arm64/qemu_cortex_a53/qemu_cortex_a53_smp_defconfig
> +# (plus it is needed for SMP)
can you align this comment properly to 80 columns?

2022-11-18 08:40 UTC, carlocaione approved these changes

2022-11-18 09:40 UTC, SgrrZhf approved these changes
LGTM

2022-11-18 09:43 UTC, povergoing approved these changes

2022-11-18 12:00 UTC, merged