drivers: lpuart: enable rs485 mode
zephyrproject-rtos/zephyr pull request #52379
Opened 2022-11-18 21:22 UTC by GrixaYrev

NXP LPUART IP supports rs485 mode when transceiver driver enable using RTS. Allow setting rs485 mode up via the `nxp,rs485-mode` dts property. `nxp,rs485-de-active-low` dts property can be used for set RTS polarity.

I have tested this feature on [NXP MIMXRT1064-EVK](https://docs.zephyrproject.org/latest/boards/arm/mimxrt1064_evk/doc/index.html). I run [echo-bot](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/uart/echo_bot), which have additional file `boards/mimxrt1064_evk.overlay`:
```
/ {
  chosen {
    zephyr,shell-uart = &lpuart3;
  };
};

&csi {
  /* Some pins are shared between CSI and LPUART3 */
  status = "disabled";
};

&pinctrl {
  pinmux_lpuart3_rs485: pinmux_lpuart3_rs485 {
    group0 {
      pinmux = < &iomuxc_gpio_ad_b1_06_lpuart3_tx >,
               < &iomuxc_gpio_ad_b1_07_lpuart3_rx >,
               < &iomuxc_gpio_ad_b1_05_lpuart3_rts_b >;
      drive-strength = "r0-6";
      slew-rate = "slow";
      nxp,speed = "100-mhz";
    };
  };
};

&lpuart3 {
  status = "okay";
  pinctrl-0 = < &pinmux_lpuart3_rs485 >;
  nxp,rs485-mode;
};
```
In first i checked this overlay without `nxp,rs485-mode` (connected MCU to USB-UART converter), then i used RS485. 
Transceiver driver connect according table:

| Signal | Pin                     |
| -------|-------------------|
| TXD    | GPIO_AD_B1_06 |
| RXD    | GPIO_AD_B1_07 |
| DE      | GPIO_AD_B1_05 |

`nxp,rs485-de-active-low` working was tested additional using logic analyzer.

Original sample `echo-bot` (without DTS overlay) was tested also.

I checked this patch using `twister` with option `--platform mimxrt1064_evk`.

Also i use this improvement on my proprietary board at last six month. My proprietary board have two UART: one use `nxp,rs485-mode`, other no.

2022-11-28 17:10 UTC, dcpleung requested changes

2022-11-28 17:34 UTC, GrixaYrev commented on drivers/serial/uart_mcux_lpuart.c
> +	uart_config.enableTx = false;
@dcpleung, ready. Now `enableRx` is set to `true`.

2022-12-05 13:32 UTC, carlescufi commented
@dcpleung please take a look

2022-12-05 18:59 UTC, dcpleung reviewed
Just one Q.

2022-12-05 19:07 UTC, GrixaYrev commented on drivers/serial/uart_mcux_lpuart.c
> +	config->base->CTRL |= LPUART_CTRL_TE(true);
No, `uart_config` used in `LPUART_Init()` only (line 989).

2022-12-05 19:08 UTC, dcpleung approved these changes, later dismissed

2022-12-06 16:11 UTC, GrixaYrev commented on dts/bindings/serial/nxp,kinetis-lpuart.yaml
> +    nxp,rs485-mode:
@danieldegrasse, You want binding like this?

```
    nxp,rs485-mode:
      type: boolean
      required: false
      description: |
        Set to enable RTS signal, which can be used to enable the driver of an external
        RS-485 transceiver. Note hw-flow-control should be set to false.
```

English is not my language, so i trust you completely. If You think, that such description will be more clear, i fix it. Or this text need more changes?

2022-12-06 19:41 UTC, GrixaYrev commented on dts/bindings/serial/nxp,kinetis-lpuart.yaml
> +    nxp,rs485-mode:
@danieldegrasse, it is offtopic, but i need help. Should i click `re-request review` button, when i make changes? it is scared me all other reviewer removed when i click this button.

2022-12-06 21:58 UTC, danieldegrasse commented on dts/bindings/serial/nxp,kinetis-lpuart.yaml
> +    nxp,rs485-mode:
No worries- you can use `re-request review` to request a reviewer revisit your PR. Even if you don't click this, reviewers who have previously engaged with your PR will be notified you have updated your PR (how I got here). Reviewers will usually be re-requested when you force push to update your PR. Generally, I don't use `re-request review` unless a reviewer has requested I make a change to my PR.

2022-12-06 22:00 UTC, danieldegrasse approved these changes

2022-12-06 23:00 UTC, dcpleung approved these changes

2022-12-07 10:12 UTC, merged