settings: file: change FS (or file system) wording to File
zephyrproject-rtos/zephyr pull request #52438
Opened 2022-11-21 15:17 UTC by mniestroj

Currently there is inconsistency in repository file names, APIs, Kconfig
options and documentation around file / file-system backend for settings
storage, as both "file" and "FS (file system)" are used. As an example,
there is `CONFIG_SETTINGS_FS` Kconfig option, but the file that implements
this settings backend is called `settings_file.c`. Another example are
names of static functions that implement settings storage API:
`settings_file_load()`, `settings_file_save()` and
`settings_fs_storage_get()`.

This backend is actually storing all settings in a single file, so it makes
sense to use "File" as the name of backend, instead of a more general
"FS" (which would make sense if several files would be used to store
settings).

Fix inconsistency in used wording in the tree and unify it to "settings
file backend". This naming is more precise to how the implementation looks.
It will also make it easier to grep through the codebase and analyze
existing code.

2022-11-21 15:50 UTC, mzagrabski approved these changes, later dismissed

2022-11-21 16:17 UTC, de-nordic requested changes
This requires release notes entry, as Kconfig options and API change will affect people updating to the release.
I think this may be considered stable API change https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes and may requiring to follow the process.
You can probably weasel out of stable API change by deprecating the old function names while introducing new ones.

2022-11-21 18:19 UTC, mniestroj commented
I have left all `CONFIG_SETTINGS_FS*` options, so they can be used with downstream applications without issue (apart from deprecation warning). There is single public C function `settings_mount_fs_backend()` that needed to be deprecated.

Added release notes entries for deprecated Kconfig options and single C function.

2022-11-22 08:55 UTC, de-nordic approved these changes, later dismissed

2022-11-22 10:21 UTC, Laczen approved these changes, later dismissed

2022-11-22 23:30 UTC, mniestroj commented
Rebased on top of main just to fix CODEOWNERS compliance check.

2022-11-23 04:16 UTC, Laczen approved these changes

2022-11-23 08:55 UTC, de-nordic approved these changes

2022-11-24 08:36 UTC, merged