tests: logger-hook: convert sample to ztest and move to test/
zephyrproject-rtos/zephyr pull request #5245
Opened 2017-12-04 08:12 UTC by punitvara

issue: #3302

Signed-off-by: Punit Vara <punit.vara@intel.com>

2017-12-04 08:42 UTC, punitvara commented
@andrewboie  Anything more needed for this patch ?

2017-12-04 13:50 UTC, nashif requested changes
I do not see a single test in here, what are you testing exactly and how do we know if the output is actually the expected output?

2017-12-19 10:34 UTC, punitvara commented
@nashif updated commit

2018-01-05 12:31 UTC, nashif approved these changes

2018-01-05 23:18 UTC, merged