MAINTAINERS: update collaborator list
zephyrproject-rtos/zephyr pull request #52668
Opened 2022-11-30 11:19 UTC by sylvioalves

glaubermaroto is no longer working on Zephyr.
uLipe isn't maintaining the support.

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

2022-11-30 11:22 UTC, sylvioalves commented
@stephanosio, for some reason, I can't add @marekmatej as reviewer (same happened in `hal_espressif`, which is now working). Would you send a new request for him?

2022-11-30 11:26 UTC, stephanosio approved these changes

2022-11-30 11:26 UTC, stephanosio commented
> Would you send a new request for him?

done

2022-11-30 11:38 UTC, sylvioalves commented
> > Would you send a new request for him?
> 
> done

Thank you!

2022-11-30 16:15 UTC, uLipe requested changes
I think @glaubermaroto still contributes to espressif, no?

cc: @sylvioalves

2022-11-30 16:16 UTC, uLipe commented
Nervermind the comment above, I misread the PR description

2022-11-30 16:16 UTC, uLipe approved these changes

2022-12-01 08:49 UTC, merged

2022-12-01 12:29 UTC, marekmatej commented
Thanks guys!