Bluetooth: controller: use RX node piggy-back for NTF when possible
zephyrproject-rtos/zephyr pull request #52725
Opened 2022-12-01 15:27 UTC by erbr-ot

2023-01-03 12:10 UTC, erbr-ot commented
rebase

2023-01-06 07:57 UTC, erbr-ot commented
rebase

2023-01-06 10:29 UTC, thoh-ot requested changes

2023-01-06 10:29 UTC, thoh-ot commented on subsys/bluetooth/controller/ll_sw/ull_llcp_common.c
> +	/* Clear tx_ack/rx node reference */
Minor: Clarify why it's needed to clear tx_ack here.

2023-01-06 11:09 UTC, thoh-ot approved these changes

2023-01-19 08:13 UTC, kruithofa approved these changes

2023-01-19 08:56 UTC, erbr-ot commented
Setting DNM - as this is going to be superseded by a PR re. delayed notifications.
Since we decided to use piggy-backing even across instant.

2023-02-09 13:46 UTC, closed without merging