Cleanup and De-centralize CMakeLists.txt in subsys/net/<ip/lib>
zephyrproject-rtos/zephyr pull request #5280
Opened 2017-12-05 13:02 UTC by tbursztyka

2017-12-05 13:17 UTC, SebastianBoe approved these changes

2017-12-05 14:35 UTC, SebastianBoe requested changes

2017-12-05 14:35 UTC, SebastianBoe commented on subsys/net/ip/l2/CMakeLists.txt
> +zephyr_library()
Should be indented.

2017-12-06 08:39 UTC, SebastianBoe approved these changes

2017-12-06 08:40 UTC, SebastianBoe commented
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/5270

2017-12-11 14:34 UTC, nashif approved these changes

2017-12-11 14:34 UTC, merged