drivers: gpio: Add more flags for GPIO's in devicetree
zephyrproject-rtos/zephyr pull request #52876
Opened 2022-12-08 04:47 UTC by CodingVoid

Currently only a subset of possible GPIO Flags is available inside the devicetree. Add the remaining to ones from drivers/gpio.h into the gpio devicetree header so that people can configure GPIO's inside the devicetree.

Signed-off-by: Maximilian Brune <brune.max@aol.de>

2022-12-08 04:48 UTC, CodingVoid commented
#52875

2022-12-08 20:12 UTC, cfriedt approved these changes
I see nothing wrong with this, but I think it was from before my time. @pabigot you?

2022-12-08 20:44 UTC, henrikbrixandersen requested changes
We have had this discussion many times. Adding these flags (input, output etc.) to DTS is counter intuitive. The application still needs to call the GPIO API for configuring the GPIO in question not to mention use either the input or output GPIO API calls for using the GPIO. The application thus needs to know the _function_ of the given GPIO pin, and therefore also if it is input or output. Having this in the DTS does not improve anything, but it violates compatibility with Linux GPIO DTS bindings.

2022-12-09 21:38 UTC, CodingVoid commented
Since I was playing around with all this quite a bit I did three simple implementations in order to compare.
https://github.com/CodingVoid/zephyr-gpio-implementation-compare

1. One implementation is basically completely in code and therefore looks rather ugly, since it still somehow needs to match the port devices in the devicetree and therefore need to write a wrapper around the zephyr API. Also it requires quite some extra code for each board that want's to use it.
2. The other one is half devicetree and half code (similar to how it is done in basic samples like blinky in zephyr). The half devicetree half code solution has the disadvantage that you basically have to do the 'gpio table' twice. Once in devicetree and once in code to configure the GPIO.
3. The last one is done completely in devicetree (apart from doing the calls to zephyr's GPIO API). It basically defines one configuration table inside devicetree and the code only calls the zephyr GPIO API to configure them. That's also the one, that I would like to use. The full devicetree solution is the most compact and simple one in my opinion and that's why I am suggesting this change.

I did this change basically because I didn't want  to write two GPIO tables (one in code and one in DTS). It's not like I want zephyr to configure it. I still want to configure it myself, but I want to use the devicetree as mere table to know how to configure it.
But if it has already been discussed many times before, than I guess it doesn't make sense to bring it up again. Thanks though for the quick review.

2022-12-13 19:54 UTC, xyzzy42 commented
I remember this discussion since before Linux ARM was even using device trees.

I've come to accept the reason it keeps coming up, by, in my experience, everyone I've ever introduced to device trees on Linux or Zephyr, is because the answer of not being able to configure GPIOs is wrong.

If it wasn't wrong, the 2nd page in the wiki on GPIOs would be of a better way to configure GPIOs than using the device tree.  Everyone would read this, decide it is a better way, and it wouldn't keep coming up.  But there isn't because there isn't.

It's entirely possible to write code that configures GPIOs using device tree bindings, does so in a way that is not any less compatible with Linux than Zephyr already is, and is faster, smaller, and more efficient than what it done now w.r.t. setting initial hardware configuration that was known at compile time.

But it's like what end to break on egg on: too many parties are so firmly entrenched on one side to even allow discussion, much less serious consideration of alternatives.

2022-12-27 11:37 UTC, carlescufi commented
@henrikbrixandersen can you please take a look at the latest comments?

2022-12-28 22:28 UTC, xyzzy42 commented
If you want to be Linux compatible, do something like the gpio-hog system.  This adds nodes, to the gpio controller's node, that own a gpio (specified by index) and provide initial configuration.  This doesn't affect the bindings used between gpio provides and gpio users.  So there isn't some wide reaching syntax change that would touch many bindings.

2022-12-30 08:28 UTC, henrikbrixandersen commented
> If you want to be Linux compatible, do something like the gpio-hog system. This adds nodes, to the gpio controller's node, that own a gpio (specified by index) and provide initial configuration. This doesn't affect the bindings used between gpio provides and gpio users. So there isn't some wide reaching syntax change that would touch many bindings.

Agreed. I started working on this last time this issue came up, but I had to put it on hold due to end-of-year timelines. You can see my work-in-progress branch for adding gpio hogs support here: https://github.com/henrikbrixandersen/zephyr/tree/gpio_hogs

I plan to resume working on this in early January.

2023-01-10 16:10 UTC, carlescufi commented
Architecture WG:

- This solution is a stop-gap one and it breaks compatibility with the upstream Linux GPIO bindings
- @henrikbrixandersen proposes an alternative implementation that does something similar to the `gpio-hog` in Linux. It is prototyped in [this branch](https://github.com/henrikbrixandersen/zephyr/tree/gpio_hogs) and could be implemented in the Zephyr 3.4 timeframe

2023-01-25 16:58 UTC, henrikbrixandersen commented
GPIO hogs PR: https://github.com/zephyrproject-rtos/zephyr/pull/54110

2023-02-27 08:44 UTC, henrikbrixandersen commented
Closing as #54110 was merged.

2023-02-27 08:44 UTC, closed without merging