subsys: usb: device: cdc: Fix logger module registration
zephyrproject-rtos/zephyr pull request #52905
Opened 2022-12-08 15:49 UTC by wilu-nordic

Based on documentation:
```
Macro accepts one or two parameters:

- module name
- optional log level. If not provided then default log level is used in the file.
```

Signed-off-by: Witold Lukasik <witold.lukasik@nordicsemi.no>

2022-12-08 16:09 UTC, jfischer-no requested changes
okay, but why do you thing it is broken? To define LOG_LEVEL at file level is still valid, or have I missed something?

2022-12-08 16:56 UTC, wilu-nordic commented
> okay, but why do you think it is broken? To define LOG_LEVEL at file level is still valid, or have I missed something?

I tested LOG_LEVEL many times and it was not working for me. Based on the documentation, when there is no second argument in `LOG_MODULE_REGISTER`, the log level for the module is CONFIG_LOG_DEFAULT_LEVEL.

2022-12-08 17:18 UTC, jfischer-no commented
> > okay, but why do you think it is broken? To define LOG_LEVEL at file level is still valid, or have I missed something?
> 
> I tested `LOG_LEVEL `many times and it was not working for me. Based on the documentation, when there is no second argument in `LOG_MODULE_REGISTER`, the log level for the module is `CONFIG_LOG_DEFAULT_LEVEL`.

"Every module can specify its own logging level. The module must define the :c:macro:`LOG_LEVEL` macro before using the API." https://docs.zephyrproject.org/latest/services/logging/index.html

```
 * @note The module's state is defined, and the module is registered,                                                                        
 *       only if LOG_LEVEL for the current source file is non-zero or                                                                        
 *       it is not defined and CONFIG_LOG_DEFAULT_LEVEL is non-zero.                                                                         
 *       In other cases, this macro has no effect. 
```

`git grep -l "define LOG_LEVEL"`

The changes are okay, but not the commit message and justification.

2022-12-09 10:30 UTC, nordic-krch commented
I created a bug report #52925 and fix #52926. Anyway, i think that we should move toward removing this option so this PR is still valid.

2022-12-09 13:05 UTC, jfischer-no requested changes
@wilu-nordic Since you are touching it, can you please check what else from `git grep -l "define LOG_LEVEL" subsys/usb/device` can be updated?

You commit message should be like:
```

usb: device: update logging module registration

Update logging module registration and remove LOG_LEVEL macro...
```

2022-12-09 14:48 UTC, jfischer-no approved these changes

2022-12-12 10:19 UTC, desowin approved these changes

2022-12-12 14:57 UTC, merged