tests: Conditionally compile MKFS Fat FS test
zephyrproject-rtos/zephyr pull request #53021
Opened 2022-12-13 16:53 UTC by decsny

This is a hotfix to work around build issues due to this FS test using the flash API innappropriately.

2022-12-13 17:28 UTC, de-nordic requested changes
This comments ifdefs entire unit, just use CMakeLists if to do this.

2022-12-13 17:42 UTC, carlescufi commented
> This comments ifdefs entire unit, just use CMakeLists if to do this.



> This comments ifdefs entire unit, just use CMakeLists if to do this.

`*_sources_ifdef(CONFIG_X	x.c)`

2022-12-14 15:29 UTC, decsny commented
> @decsny Can you explain the problem a little bit? How to reproduce the problem?

If you are using the fat fs on a non flash device there will be a build error. The test is for fat fs not for flash, so there should not be flash functions in the test without some compilation guard.

2022-12-14 15:50 UTC, de-nordic commented
> > @decsny Can you explain the problem a little bit? How to reproduce the problem?
> 
> If you are using the fat fs on a non flash device there will be a build error. The test is for fat fs not for flash, so there should not be flash functions in the test without some compilation guard.

You mean that when you build for FAT FS via disk access on non-flash device?

2022-12-14 15:55 UTC, decsny commented
> > > @decsny Can you explain the problem a little bit? How to reproduce the problem?
> > 
> > 
> > If you are using the fat fs on a non flash device there will be a build error. The test is for fat fs not for flash, so there should not be flash functions in the test without some compilation guard.
> 
> You mean that when you build for FAT FS via disk access on non-flash device?

when you build this fat_fs_api test for a non flash device yes

2022-12-14 17:20 UTC, de-nordic approved these changes
OK for hotfix. 
Please log issue in Zephyr for the test to be fixed for non-CONFIG_FLASH devices.

2022-12-14 17:36 UTC, carlescufi approved these changes

2022-12-14 17:37 UTC, merged

2022-12-20 17:13 UTC, stephanosio commented
Related issue: https://github.com/zephyrproject-rtos/zephyr/pull/53021