drivers: timer: lptim timer clock on stm32u5 has a prescaler
zephyrproject-rtos/zephyr pull request #53056
Opened 2022-12-14 10:11 UTC by FRASTM

The stm32U5 devices shows a x2 factor on the LPTIM1,3,4 clock source but it acts as a prescaler.
The max lptim counter (timebase) is counting 4 sec The LPTIM count unit is double.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/53012

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2022-12-14 11:13 UTC, erwango requested changes

2023-01-05 08:23 UTC, FRASTM commented on drivers/timer/stm32_lptim_timer.c
> +	}
That was also to change the comment above, but changing the order is also possible to avoid reading the same lines inside each section

2023-01-05 09:26 UTC, FRASTM commented
Introducing a ` st,static-prescaler;`  optional property to adjust the lptim time base when a x2 factor is present at the LPTIM clock input, like on LPTIM1,3,4 of the stm32U5 devices

2023-01-05 10:06 UTC, erwango requested changes
Otherwise LGTM

2023-01-05 10:06 UTC, erwango commented on drivers/timer/stm32_lptim_timer.c
> +#else
let's take benefit of `IS_ENABLED` magic for readability:
    if (IS_ENEBLED(DT_PROP(DT_DRV_INST(0), st_static_prescaler))) {
           /*  bla */
           lptim_clock_freq = lptim_clock_freq / 2;
    }

2023-01-05 10:26 UTC, erwango commented on drivers/timer/stm32_lptim_timer.c
> +#else
I'm sure comment could be reviewed to fit a good old if() implementation

2023-01-05 10:29 UTC, FRASTM commented
version of the stm32_lptim_timer.c using `if (IS_ENABLED(DT_PROP(DT_DRV_INST(0), st_static_prescaler))) {`
instead of `#if DT_PROP(DT_DRV_INST(0), st_static_prescaler)`

2023-01-05 10:30 UTC, erwango approved these changes

2023-01-10 14:18 UTC, gautierg-st approved these changes

2023-01-10 15:54 UTC, merged