Update west.yml with latest STM32 HAL version
zephyrproject-rtos/zephyr pull request #53067
Opened 2022-12-14 15:40 UTC by gautierg-st

Update west.yml with latest STM32 HAL version

2022-12-22 10:16 UTC, erwango requested changes

2022-12-22 10:16 UTC, erwango commented on drivers/bluetooth/hci/ipm_stm32wb.c
> +	    CFG_BLE_LS_SOURCE,
Move this in a dedicate commit

2023-01-04 09:39 UTC, gautierg-st commented on drivers/bluetooth/hci/ipm_stm32wb.c
> +	    CFG_BLE_LS_SOURCE,
Done

2023-01-06 08:28 UTC, erwango approved these changes

2023-01-09 08:23 UTC, FRASTM approved these changes

2023-01-09 09:15 UTC, merged