drivers/i2c: stm32: Use dts for i2c clock source
zephyrproject-rtos/zephyr pull request #53216
Opened 2022-12-20 10:31 UTC by gautierg-st

This PR adds support of the I2C clock source for STM32 in the dts file.

2022-12-20 12:49 UTC, erwango requested changes

2022-12-20 12:49 UTC, erwango commented on include/zephyr/dt-bindings/clock/stm32f4_clock.h
> +/* Following definitions are for STM32F7X only */
Please introduce a dedicated stm32f7_clocks.h

2022-12-20 12:49 UTC, erwango commented on dts/arm/st/f0/stm32f0.dtsi
> -			clocks = <&rcc STM32_CLOCK_BUS_APB1 0x00200000>;
Please provide more comments in the commit message why we are defining default clock sources (which is not a common practice). According to existing code, I can see:
```
	 * STM32F0/3 I2C's independent clock source supports only
	 * HSI and SYSCLK, not APB1. We force I2C clock source to SYSCLK.
	 * I2C2 on STM32F0 uses APB1 clock as I2C clock source
```

2022-12-20 12:49 UTC, erwango commented on drivers/i2c/i2c_ll_stm32.c
> +#if (DT_NUM_CLOCKS(DT_NODELABEL(name)) > 1)
Contrary to `STM32_I2C_INIT()` case, `name` is undefined, this will likely not produce the expected result.

2022-12-20 14:08 UTC, erwango requested changes

2022-12-20 14:08 UTC, erwango commented on include/zephyr/dt-bindings/clock/stm32f7_clock.h
> + * Copyright (c) 2022 Linaro Limited
Fix copyright

2022-12-21 10:29 UTC, erwango approved these changes
LGTM

2022-12-21 11:17 UTC, carlescufi approved these changes

2022-12-21 11:17 UTC, merged