arm: ld: place .bss at the end
zephyrproject-rtos/zephyr pull request #53262
Opened 2022-12-21 13:45 UTC by yroeht

This is to avoid the binary padding caused by placing sections after the .bss noload gap, which causes the binary to be unnecessarily large. By placing the noload .bss at the end, we do not have to include it in the binary.

Signed-off-by: Théophile Ranquet <theophile.ranquet@gmail.com>

2022-12-21 14:00 UTC, stephanosio reviewed
We did basically the same thing for Cortex-M a while back. At the time, doing so broke userspace support, not sure if that is still the case -- see https://github.com/zephyrproject-rtos/zephyr/pull/21747.

2023-02-09 16:20 UTC, MaureenHelm commented
@microbuilder can you take a look at this or reassign?

2023-02-09 16:20 UTC, stephanosio commented
@ibirnbaum @bbolen Can you please take a look?

2023-02-09 16:22 UTC, microbuilder commented
> @microbuilder can you take a look at this or reassign?

Sorry, was waiting for feedback on comment from Stephanos, and fell off my radar since it wasn't tagged for 3.3.

2023-02-09 17:04 UTC, stephanosio commented
> @MaureenHelm @stephanosio Can this wait until after the 3.3 release? Trying to sort out a workable solution to the TF-M release blocker issue.

Yes, this is not for 3.3.

2023-02-10 08:36 UTC, ibirnbaum commented
As it happens, without remembering the existence of this PR, I ran into the same issue a few days ago after being generous with several heap settings and discovering that the resulting .bin image was unreasonably large. I'll cross-check with my modifications later today at the office, I think the padding issue wasn't just limited to .bss, but also to .noinit. It should also be checked if __data_region_end is somehow relevant for the MMU setup, as with the proposed change, the .bss section is now within the area marked with _image_ram_end / _end / z_mapped_end, but beyond whatever is supposed to be indicated with __data_region_end.

2023-02-10 12:42 UTC, ibirnbaum requested changes
Moving just the .bss section to the end of the image doesn't fully resolve the padding issue, as memory areas such as thread stacks or heaps are placed in the .noinit section, which, at the time being, is located just behind .bss and therefore in the middle of the image.

A quick test with an application which reserves heaps with an approximate total size of 30 MB resulted in the following image sizes:

- Linker command file as-is: 32.462.776
- .bss moved to the end of the image: 22.977.152
- both .bss and .noinit moved to the end of the image: 1.789.480

Therefore, the include statement for common-noinit.ld must be moved as well in order to fully resolve the padding issue.

With regards to the __data_region_end marker however, the behaviour is likely correct. This marker is used during startup in XIP operation mode when the initialized data sections are copied from flash to RAM. If the .bss and .noinit sections aren't contained in the flash, there's no point in copying random data from flash to RAM. Instead, .bss will be zeroed during early boot and .noinit is just left untouched.

2023-03-28 10:41 UTC, microbuilder commented
@yroeht Have time to reply to the feedback from @ibirnbaum ?

2023-07-13 12:18 UTC, microbuilder commented
@povergoing Assigning this to you, hoping that you and @SgrrZhf can address this as part of #60031 since the current PR has gone unresponsive.

2023-07-13 12:38 UTC, ibirnbaum commented
@microbuilder @povergoing As this is a relatively small and quick fix, I'd suggest that I open a separate PR later tonight which replaces this one. We can easily merge this change before tackling 'the big one'.

2023-07-14 02:50 UTC, povergoing commented
> @povergoing Assigning this to you, hoping that you and @SgrrZhf can address this as part of #60031 since the current PR has gone unresponsive.

Sure, and I saw that @ibirnbaum has already raised a fix for this.

> @microbuilder @povergoing As this is a relatively small and quick fix, I'd suggest that I open a separate PR later tonight which replaces this one. We can easily merge this change before tackling 'the big one'.

Agreed, really appreciate it.

2023-09-28 00:29 UTC, closed without merging