drivers: gic: support for GIC-600 power
zephyrproject-rtos/zephyr pull request #53261
Opened 2022-12-21 13:37 UTC by yroeht

This register controls the powerup sequence of the Redistributors. Software must write to this register during the powerup sequence.

Signed-off-by: Théophile Ranquet <theophile.ranquet@gmail.com>

As documented by ARM at:
    https://developer.arm.com/documentation/100336/0002/programmers-model/redistributor-registers-for-control-and-physical-lpis-summary/power-register--gicr-pwrr

2022-12-21 14:44 UTC, carlocaione requested changes

2022-12-21 14:44 UTC, carlocaione commented on drivers/interrupt_controller/intc_gicv3_priv.h
> +#define GICR_POWERR_RDG                        (1 << 16)
Why not `BIT()`?

2022-12-21 14:44 UTC, carlocaione commented on drivers/interrupt_controller/intc_gicv3.c
> +	pwrr = (pwrr | GICR_POWERR_RDAG) & ~GICR_POWERR_RDPD;
`|=`

2022-12-21 14:58 UTC, yroeht commented on drivers/interrupt_controller/intc_gicv3_priv.h
> +#define GICR_POWERR_RDG                        (1 << 16)
ok, no reason.

2022-12-21 14:58 UTC, yroeht commented on drivers/interrupt_controller/intc_gicv3.c
> +	pwrr = (pwrr | GICR_POWERR_RDAG) & ~GICR_POWERR_RDPD;
ok

2022-12-23 11:43 UTC, carlocaione requested changes

2022-12-23 11:43 UTC, carlocaione commented on drivers/interrupt_controller/Kconfig.gic
> +	select GIC_V3
this should be `depends on`

2022-12-23 12:09 UTC, yroeht commented on drivers/interrupt_controller/Kconfig.gic
> +	select GIC_V3
ok

2023-02-22 09:54 UTC, povergoing commented on drivers/interrupt_controller/intc_gicv3.c
> +	uint32_t pwrr = sys_read32(rdist + GICR_PWRR);
nit: we might use `GICD_IIDR >= 0x2` to indicate there is a need to set `GICR_PWRR`. Because GIC 700 also requires setting `GICR_PWRR`

2023-04-24 06:51 UTC, carlocaione commented
@yroeht do you plan to keep working on this?

2023-06-14 22:50 UTC, yroeht commented
> @yroeht do you plan to keep working on this?

Yes, as a matter of fact I am currently investigating some issues we are having with our interrupts which may require more work than the changes proposed here.

2023-06-21 14:55 UTC, quic-chadk commented
@yroeht , @carlocaione Can I help on this PR in any way?  I need these RDAG and RDPD changes in also.
I have been using my own RDAG and RDPD changes locally and they work with no issue.  I see this PR has been going on for 6 months so would like to help if I can.

2023-06-22 06:50 UTC, carlocaione commented
> @yroeht , @carlocaione Can I help on this PR in any way? I need these RDAG and RDPD changes in also. I have been using my own RDAG and RDPD changes locally and they work with no issue. I see this PR has been going on for 6 months so would like to help if I can.

@quic-chadk you can open a new PR with your changes, @yroeht can comment on that.

2023-06-22 18:16 UTC, quic-chadk commented
> > @yroeht , @carlocaione Can I help on this PR in any way? I need these RDAG and RDPD changes in also. I have been using my own RDAG and RDPD changes locally and they work with no issue. I see this PR has been going on for 6 months so would like to help if I can.
> 
> @quic-chadk you can open a new PR with your changes, @yroeht can comment on that.

Thanks @carlocaione, I will reply back here next week with link when I get the new PR opened.

2023-08-30 23:22 UTC, quic-chadk commented
Link for the new PR is: https://github.com/zephyrproject-rtos/zephyr/pull/62124

2023-08-31 07:00 UTC, closed without merging