arch/arm/soc/nxp_imx: added support to imx7d m4 core
zephyrproject-rtos/zephyr pull request #5330
Opened 2017-12-10 21:44 UTC by uLipe

board/colibri_imx7d_m4: added board support to toradex colibri imx7d single board computer

This change basically adds support of a popular IMX7D processors from NXP, which has a ARM Cortex A7 Core and a Cortex M4 Core, this change is targeted to the second one and now is possible to select it as a supported SoC, Toradex has some attractive single board computers with industrial grade using this processor and this change also the basic support of the board and the NXP supplied HAL.

This support is intended to increase the options of heterogeneous processors in Zephyr SoC portfolio, adds the SoC and Board template is the first step only, so I divided the change in two steps, first provide a functional SoC support to perform build and image generation to be flashed to TCMRAM (imx7d m4 core does not has built in flash), the next step is to provide the serial drivers and the IPM driver to communicate m4 core with a7 core, this approach was chosen to keep the changes not too large and hard to verify.

This changed was validated as follows:
 - built the hello world sample under build folder with: $cmake -DBOARD=colibri_imx7d_m4 .. and make.
 - the generated image can be loaded through a Jlink probe or with A7 running Linux + uBoot using the fatload command

Signed-off-by: Felipe Neves <ryukokki.felipe@gmail.com>

2017-12-11 15:11 UTC, galak requested changes
Can you split this into at least 2 patches, one for the soc code and one for the board.

2017-12-11 19:05 UTC, uLipe commented
Hi, yes I can. 


In this case I will modify this patch and the next one include board support.

Thanks

2017-12-11 19:16 UTC, pfalcon commented
@uLipe : Note that you can just make this pull request contain 2 commits (no need to create 2 pull requests for that).

2017-12-11 19:20 UTC, uLipe commented
@pfalcon, thanks for the tip, I will submit the just one PR containing the soc and board commits.

Best :)

2017-12-11 21:44 UTC, MaureenHelm requested changes
Hi @uLipe , thanks for the PR! This is something we have wanted to do for some time.

As others have already said, please split this up into multiple commits as it will help with the review process and keep the git history clean. It's ok to force push your branch to update the PR. I think you should have three commits, rather than two:
1. Import mcux hal for imx7d. Please reuse the existing ext/hal/nxp/mcux folder and configs rather than creating a new folder and configs.
2. Add imx7d SoC support
3. Add colibri board support. Please also add a board doc to this commit, refer to boards/arm/mimxrt1050_evk/doc/mimxrt1050_evk.rst as an example.

cc: @MarekNovakNXP

2017-12-11 21:44 UTC, MaureenHelm commented on boards/arm/colibri_imx7d_m4/colibri_imx7d_m4_defconfig
> +CONFIG_UART_NXP_IMX=y
Remove this line, we can select the appropriate uart driver in the SoC defconfig. See arch/arm/soc/nxp_imx/rt/Kconfig.defconfig.mimxrt1052 for an example.

2017-12-11 21:44 UTC, MaureenHelm commented on dts/arm/nxp/nxp_imx.dtsi
> +		tcram: tcram@1fff8000 {
Let's call this tcml to match the hardware reference manual, and add tcmu.

2017-12-11 21:44 UTC, MaureenHelm commented on dts/arm/nxp/nxp_imx.dtsi
> +			label = "CCM";
s/CCM/DDR/

2017-12-11 21:44 UTC, MaureenHelm commented on dts/arm/nxp/nxp_imx.dtsi
> +			reg = <0x30890000 0x4000>;
Base address should be 0x30870000

2017-12-11 21:44 UTC, MaureenHelm commented on ext/hal/Kconfig
> +source "ext/hal/nxp/imx/Kconfig"
Merge contents into existing ext/hal/nxp/mcux

2017-12-12 01:08 UTC, uLipe commented
@MaureenHelm , thanks for the tips I started to work in these changes, let me ask a question about the mcux hal and imx hal, I noted the nxp sdk for the IMX7 microcontroller side seems to not compatible with the new mcuxpresso drivers (the files are quite different and the IPs too), more than that currently the MCUX dashboard does not support the imx7d processors, the duplication of the hal was based on this incompatibility, but I agree with you to keep only the mcux hal.

Given this scenario the question is: Can I move the drivers source files of IMX7 directly to the mcuexpresso drivers/ directory? or should I create a second directory called for example: drivers_imx7d ?

2017-12-12 14:38 UTC, MaureenHelm commented
> I noted the nxp sdk for the IMX7 microcontroller side seems to not compatible with the new mcuxpresso drivers (the files are quite different and the IPs too), more than that currently the MCUX dashboard does not support the imx7d processors, the duplication of the hal was based on this incompatibility, but I agree with you to keep only the mcux hal.

My mistake, I thought we had imx7d m4 support in mcux 2.x but it turns out the drivers and headers are based on ksdk 1.x. Let me check with the internal development team to see if there are any plans to update it, and then we can decide how to proceed.

2017-12-13 17:01 UTC, galak commented
@MaureenHelm curious if the imx7d and imx6 code would be similar (for those imx6 devices with cortex-m as well).

2017-12-13 22:04 UTC, MaureenHelm commented
> @MaureenHelm curious if the imx7d and imx6 code would be similar (for those imx6 devices with cortex-m as well).

For now, yes. Existing imx6 and imx7 devices have similar ksdk 1.x based m4 drivers, but future devices in these families may have mcux 2.x. 


> My mistake, I thought we had imx7d m4 support in mcux 2.x but it turns out the drivers and headers are based on ksdk 1.x. Let me check with the internal development team to see if there are any plans to update it, and then we can decide how to proceed.

There are no plans to update this device to mcux 2.x, so I now agree with your original decision to create a new hal folder. I'm not sure I like "ext/hal/nxp/imx" and CONFIG_HAS_IMX_HAL though, as I think that will create confusion for imx devices that do have mcux. NXP releases the code in a "FreeRTOS BSP", which is based on ksdk 1.x, so some possible alternatives are:
ext/hal/nxp/freertos_bsp
ext/hal/nxp/ksdk

Thoughts?

2017-12-13 22:50 UTC, galak commented on .gitignore
> +*.DS_Store
I'm not really sure we should be adding this, and if it should be in a separate PR/commit.

2017-12-13 22:51 UTC, galak requested changes
Remove the .bin.inc files that are checked in.

2017-12-13 22:51 UTC, galak commented on samples/net/sockets/dumb_http_server/src/response_big.html.bin.inc
> +0x48, 0x54, 0x54, 0x50, 0x2f, 0x31, 0x2e, 0x30,
This file should not be check in.

2017-12-13 22:52 UTC, uLipe commented
Hi,

@MaureenHelm, thanks for the support, I agree the imx named folder in hal could cause confusion, ksdk seems confusing too since it refers to the old kinetis sdk.

freertos_bsp is also too generic but since it will contained in nxp folder, this can be a solution.

Should i proceed with hal/nxp/freertos_sdk(or bsp)?

Thanks again :)

2017-12-13 23:01 UTC, galak commented
> There are no plans to update this device to mcux 2.x, so I now agree with your original decision to create a new hal folder. I'm not sure I like "ext/hal/nxp/imx" and CONFIG_HAS_IMX_HAL though, as I think that will create confusion for imx devices that do have mcux. NXP releases the code in a "FreeRTOS BSP", which is based on ksdk 1.x, so some possible alternatives are:
> ext/hal/nxp/freertos_bsp
> ext/hal/nxp/ksdk
> 
> Thoughts?

Do you expect that something like i.mx8 would be supported by mcux?

I wondering if we should just have native drivers.  Wondering how many peripheral drivers would actually be used/supported?  @uLipe which devices do you see using from the Cortex-M4 on i.mx7d?

2017-12-14 14:16 UTC, MaureenHelm commented
> Do you expect that something like i.mx8 would be supported by mcux?

Yes

> I wondering if we should just have native drivers.

Why? We still need the device headers, so doing native drivers doesn't eliminate the problem of how to import the nxp freertos bsp.

> Should i proceed with hal/nxp/freertos_sdk(or bsp)

I think we should go with freertos_bsp. It's a little weird, but it's closest to the package name from nxp. @galak, do you agree?

2017-12-14 16:12 UTC, galak commented
> I think we should go with freertos_bsp. It's a little weird, but it's closest to the package name from nxp. @galak, do you agree?

Uugh, why'd you guys have to use freertos in the bsp name ;).  Could we do something like ext/hal/nxp/imx_legacy/ . or imx_6_7 or something like that to convey the SoCs we are supporting?

2017-12-15 22:13 UTC, MaureenHelm commented
> Uugh, why'd you guys have to use freertos in the bsp name ;). Could we do something like ext/hal/nxp/imx_legacy/ or 'imx_6_7' or something like that to convey the SoCs we are supporting?

No, there may be new SoCs in these families that have mcux. I don't like having freertos in the name either, but I still think keeping the folder name close to the nxp package name makes the origin clear.

2018-01-10 16:30 UTC, galak commented
@uLipe - any feedback to my question?

2018-01-11 17:24 UTC, uLipe commented
Hello all, sorry for long delayed response (I was travelling with very limited internet access).

Regarding the question, @galak , I don't think the mention of freertos is the more correct way, but based on sdk delivered by NXP and if the goal is to make the external resources on hal folder compliant with the chip manufacturer, the freertos_bsp is the better way to naming,using imx_legacy is not good at all too because IMX6 and 7 families as well their sdk are not obsolete, discontinued or even legacy, is just not compatible with the current mcux sdk. 

I used the name as just "imx" because it sounds a mid-term but at cost of some confusion risk by the user, @MaureenHelm can I keep the naming of the original PR? I think, because mcux incompatibility by the IMX7 SoCs, the naming solution chosen will aways have a drawback.

I will resume the PR task at this weekend. 

Thanks again by the support.

Felipe

2018-01-31 15:07 UTC, galak commented
@uLipe any chance you'll get back to this?

2018-02-02 03:20 UTC, uLipe commented
Hello @galak , I will suffering some busy times here and due this I will not be able to continue it, my colleague @diegosueiro will take this task from ahead.

Thanks for the support

2018-02-02 16:34 UTC, MaureenHelm commented
> I used the name as just "imx" because it sounds a mid-term but at cost of some confusion risk by the user, @MaureenHelm can I keep the naming of the original PR? I think, because mcux incompatibility by the IMX7 SoCs, the naming solution chosen will aways have a drawback.

Yes

> I will suffering some busy times here and due this I will not be able to continue it, my colleague @diegosueiro will take this task from ahead.

Understand. Thanks @diegosueiro for picking this up.

2018-02-03 07:22 UTC, diegosueiro commented
@MaureenHelm, 

It will be a pleasure to continue this PR.
Actually, I'm the original author of this porting and @uLipe helped me to adapt it to use cmake (when I started Zephyr was based on KBuild), among other things and created the PR.

I'm just wondering if it is better to create a new PR applying the changes suggested by you and @galak.

I'm just confused regarding the naming the hal directory. What should I use? "ext/hal/nxp/imx"?

2018-02-05 17:41 UTC, MaureenHelm commented
> I'm just wondering if it is better to create a new PR applying the changes suggested by you and @galak.

Either way is fine. We usually do force pushes to update a PR, but in this case you would have to force push to @uLipe 's repo. If you do create a new PR, please add a reference to this one in the description.

> I'm just confused regarding the naming the hal directory. What should I use? "ext/hal/nxp/imx"?

Yes, sorry for the confusion. I don't really like this name or any of the others we kicked around, but I don't have any better suggestions. Please also have a look at http://docs.zephyrproject.org/contribute/contribute_non-apache.html

2018-02-06 07:31 UTC, diegosueiro commented
@MaureenHelm,

> Either way is fine. We usually do force pushes to update a PR, but in this case you would have to force push to @uLipe 's repo. If you do create a new PR, please add a reference to this one in the description.

Got it. I'll create a new PR.

> Please also have a look at http://docs.zephyrproject.org/contribute/contribute_non-apache.html

The iMX7D drivers and utilities were taken from NXP FreeRTOS BSP and according to the file "SW-Content-Register-FreeRTOS-BSP-1.0.1-i.MX7D.txt" they are released under BSD-3-Clause.

In this case, should I need to make the submission for TSC review?

2018-02-06 21:57 UTC, MaureenHelm commented
> In this case, should I need to make the submission for TSC review?

Please add a README to your PR, and I'll submit it to the TSC/gov board for review.

2018-02-25 18:34 UTC, diegosueiro commented
@MaureenHelm,

Just to let you know that I just submitted the PR #6367

2018-02-26 16:57 UTC, MaureenHelm commented
> Just to let you know that I just submitted the PR #6367

Thanks!

2018-02-26 16:57 UTC, closed without merging