tests: power: Fix compiler definition flag
zephyrproject-rtos/zephyr pull request #5333
Opened 2017-12-11 09:08 UTC by mnirmaladevi

Enabled compiler definition flag TEST_CASE_SLEEP_SUCCESS
which was missing on migrating to cmake.

Signed-off-by: Nirmala Devi <nirmala.devix.m@intel.com>

2017-12-11 09:24 UTC, SebastianBoe approved these changes

2017-12-11 14:16 UTC, nashif requested changes
docs for the sample need to be updated, still talking about 

make TEST_CASE=sleep-fail

2017-12-13 18:36 UTC, dbkinder approved these changes

2017-12-19 21:54 UTC, nashif approved these changes

2017-12-19 21:54 UTC, merged