drivers: sensor: bmp388: add OSR/ODR timing validation
zephyrproject-rtos/zephyr pull request #53374
Opened 2022-12-28 16:49 UTC by matteoscordino

This is a fresh attempt at getting this feature merged, after I closed a previous PR, #53025, that got messed up

The BMP3xx won't start up correctly if the ODR/OSR settings are not consistent
(the IC won't exit sleep mode when asked to go normal), and without this patch
the driver is not detecting it; the init completes and the sensor looks
"active", but no data is sampled. In triggered mode you will get no trigger,
in polling mode you will loop forever doing I2C transactions to read the
status register waiting for DRDY.

Even worse, if `CONFIG_PM_DEVICE` is enabled, the state of the IC would get
out of sync with the state known by the PM logic.

So, consistency checking of the OSR/ODR setting is not a purely formal check.

An alternative (and simpler) approach would be to read back the power mode
register after init and ODR/OSR setting, but that has a few significant
drawbacks:

- it just says that init failed, not WHY
- it would add an I2C transaction to each attribute setting (assuming that dynamic setting is enabled)
- again for dynamic attribute setting, detecting the error after the fact would leave the IC in an inconsistent state, and require some form of recovery
- it would add an I2C transaction to init (not very significant, as it's a one-off)
- principle of least surprise: checking this is what the official Bosch driver does, so people coming from other platforms expect it

2023-02-23 16:45 UTC, teburd commented
@teburd @MaureenHelm @yperess lets take a look at this

2023-03-09 20:34 UTC, MaureenHelm requested changes
Thank you for the fix. I'm sorry for the delay in my review.

Please rebase and address the compliance errors. There are a lot of lines with leading spaces that need to be changed to tabs

2023-03-09 20:34 UTC, MaureenHelm commented on drivers/sensor/bmp388/bmp388.c
> +}
It looks like this function is always called with base = 2, so why not use a left shift instead?

2023-03-09 20:34 UTC, MaureenHelm commented on drivers/sensor/bmp388/bmp388.c
> +    return -EINVAL;
Suggest adding a LOG_ERR before returning

2023-03-09 20:34 UTC, MaureenHelm commented on drivers/sensor/bmp388/bmp388.c
> +	if ( 0 > bmp388_validate_osr_and_odr_settings(odr, data->osr_pressure, data->osr_temp))
```suggestion
	if (bmp388_validate_osr_and_odr_settings(odr, data->osr_pressure, data->osr_temp) < 0)
```
Please do this throughout

2023-03-09 20:34 UTC, MaureenHelm commented on drivers/sensor/bmp388/bmp388.c
> +														data->osr_temp))
It looks like you editor settings might be off; please set tab=8

2023-05-24 00:30 UTC, closed without merging