test: bluetooth: resume_adv: Create advertising resume tester (Bsim) for issue #51256
zephyrproject-rtos/zephyr pull request #53396
Opened 2022-12-30 14:21 UTC by eslam-cloud2nd

The tester includes three examples run on `babblesim` to simulate `To Reproduce` like #50438
1- First Application is central_hr to simulate "NRF Connect"
2- Second Application is peripheral_hr 
3- Third Application is central_peripheral_hr

Signed-off-by: Esalm Essa <eslam@cloud2gnd.com>

2023-01-02 21:01 UTC, Thalley requested changes

2023-01-02 21:01 UTC, Thalley commented on tests/bluetooth/bsim_bt/bsim_test_resume_adv/central_hr/boards/rv32m1_vega_ri5cy.overlay
> +};
Why are we adding board overlays for boards that are not the `nrf52_bsim` board in the BSIM test directory?

2023-01-02 21:01 UTC, Thalley commented on tests/bluetooth/bsim_bt/bsim_test_resume_adv/peripheral_hr/sample.yaml
> +    extra_args: SHIELD=frdm_kw41z
Why are we adding sample descriptions in the BSIM directory?

2023-01-02 21:01 UTC, Thalley commented on tests/bluetooth/bsim_bt/bsim_test_resume_adv/central_hr/README.rst
> +Zephyr tree.
Incorrect location and also not a sample

2023-01-06 09:13 UTC, aescolar requested changes
Same review as https://github.com/zephyrproject-rtos/zephyr/pull/53134#pullrequestreview-1238562085

2023-03-08 06:48 UTC, closed without merging