samples: Bluetooth: Demonstrate MTU update
zephyrproject-rtos/zephyr pull request #53593
Opened 2023-01-09 07:18 UTC by theob-pro

Add a new sample and a BabbleSim test for it. The goal of this sample is to demonstrate how to update the MTU to allow larger packet transmission as requested by https://github.com/zephyrproject-rtos/zephyr/issues/25648.

2023-01-12 11:37 UTC, jori-nordic requested changes

2023-01-12 11:37 UTC, jori-nordic commented on samples/bluetooth/mtu_update/README.rst
> +the Zephyr tree.
can you add a section on the hardware setup, e.g. that you need to flash this part to a device ,and that part to another device. 
and a little text about what you're expected to see if it works.

2023-01-12 11:37 UTC, jori-nordic commented on samples/bluetooth/mtu_update/peripheral/prj.conf
> +# BT_L2CAP_RX_MTU=CONFIG_BT_BUF_ACL_RX_SIZE-BT_L2CAP_HDR_SIZE
same comment about spaces

2023-01-12 11:37 UTC, jori-nordic commented on samples/bluetooth/mtu_update/peripheral/src/peripheral_mtu_update.c
> + * Copyright (c) 2022 Nordic Semiconductor ASA
check all copyright notices

2023-01-12 14:07 UTC, alwa-nordic commented on samples/bluetooth/mtu_update/README.rst
> +| Set :kconfig:option:`CONFIG_BT_BUF_ACL_RX_SIZE` to at least x + L2CAP header
What is the actual number for the size of the L2CAP header? I think we should have the number here.

2023-01-13 08:09 UTC, jori-nordic commented on samples/bluetooth/mtu_update/README.rst
> +  Question: I only want to *send* large packets. I don't need to receive large.
`large ones` or `large packets`

2023-01-13 08:10 UTC, jori-nordic commented on samples/bluetooth/mtu_update/README.rst
> +This sample use two application, two devices need to be setup.
applications

2023-01-13 08:11 UTC, jori-nordic commented on samples/bluetooth/mtu_update/README.rst
> +and send his MTU to the other device. If the MTU exchange succeed, the central
succeeds

2023-01-13 08:11 UTC, jori-nordic commented on samples/bluetooth/mtu_update/README.rst
> +Here are the output you should have on the devices:
`Here is the output` or `Here are the outputs`.

2023-01-13 08:56 UTC, alwa-nordic commented on samples/bluetooth/mtu_update/central/src/central_mtu_update.c
> +
Should we look in the ad data for the service before connecting?

2023-01-13 08:56 UTC, jori-nordic approved these changes

2023-01-13 11:10 UTC, alwa-nordic approved these changes

2023-01-16 08:08 UTC, wiba-nordic commented
I'm going over the Zephyr ⁠[sample definition](https://builds.zephyrproject.io/zephyr/pr/53593/docs/samples/sample_definition_and_criteria.html), and point 6 says that a sample should have minimal comments and not be explaining the WHY of something. But the sample currently has quite a bit of them, going into a lot the why and details of an MTU update. Would some of that be better served in a different part of the documentation instead of as part of a sample?

2023-01-16 08:47 UTC, alwa-nordic commented on samples/bluetooth/mtu_update/README.rst
> +The two devices need to be close enough to be able to connect.
It's a bit hard to understand what is meant by this sentence. I think we should reword so it's clear it's a feature.

```suggestion
The two devices will connect only if they are close to each other, thanks to RSSI filtering.
```

2023-01-16 08:51 UTC, theob-pro commented
> I'm going over the Zephyr ⁠[sample definition](https://builds.zephyrproject.io/zephyr/pr/53593/docs/samples/sample_definition_and_criteria.html), and point 6 says that a sample should have minimal comments and not be explaining the WHY of something. But the sample currently has quite a bit of them, going into a lot the why and details of an MTU update. Would some of that be better served in a different part of the documentation instead of as part of a sample?

I think that the point 6 refer to code comment and not the README documentation. Anyway, I don't think that limiting the comment on code make a lot of sense either, is there a good reason for that? @carlescufi 
For the "why", you're right, I will remove the sentence citing reasons to update the MTU.

2023-01-16 09:00 UTC, jhedberg approved these changes

2023-01-16 09:01 UTC, merged

2023-01-16 09:02 UTC, carlescufi commented
> > I'm going over the Zephyr ⁠[sample definition](https://builds.zephyrproject.io/zephyr/pr/53593/docs/samples/sample_definition_and_criteria.html), and point 6 says that a sample should have minimal comments and not be explaining the WHY of something. But the sample currently has quite a bit of them, going into a lot the why and details of an MTU update. Would some of that be better served in a different part of the documentation instead of as part of a sample?
> 
> I think that the point 6 refer to code comment and not the README documentation. Anyway, I don't think that limiting the comment on code make a lot of sense either, is there a good reason for that? @carlescufi For the "why", you're right, I will remove the sentence citing reasons to update the MTU.

In this particular case the documentation included in the sample is definitely helpful and belongs in it.