BLE:DF: Fix slot_plus_us by converting max CTE len to us
zephyrproject-rtos/zephyr pull request #53837
Opened 2023-01-16 15:03 UTC by saleh-unikie

Fixes #53786

Signed-off-by: Saleh Mehdikhani <saleh.mehdikhani@unikie.com>

2023-01-16 15:25 UTC, cvinayak requested changes
Minor nitpick and please fix the commit title:

>  1: UC3 Commit title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "BLE:DF: Fix slot_plus_us by converting max CTE len to us"

Use "Bluetooth: Controller: Fix slot_plus_us by converting max CTE len to us" 

Keep the length of the title upto 72 chars

2023-01-16 15:25 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ull_df.c
> +			slot_plus_us = BT_HCI_LE_CTE_LEN_MAX * 8;
```suggestion
			slot_plus_us = BT_HCI_LE_CTE_LEN_MAX * 8U;
```

2023-01-16 16:02 UTC, cvinayak requested changes
Code LGTM. But forgot to tell that please include a commit message stating the text you reference in the github issue. i.e. why this change and how the implementation was changed.

The "Fixes ..." is only needed in the github description, for github.

@ppryga-nordic Minor review for you.

2023-01-16 23:17 UTC, cvinayak approved these changes

2023-01-17 10:27 UTC, carlescufi approved these changes

2023-01-17 10:27 UTC, merged