Bluetooth: Mesh: Fix issues with rescheduling points
zephyrproject-rtos/zephyr pull request #53860
Opened 2023-01-17 11:34 UTC by PavelVPV

This PR fixes issues that could happen due to rescheduling points that can allow to enter a mesh code twice from different cooperative threads. Explanations are provided in the commit messages.

2023-01-17 15:29 UTC, alxelax submitted a review, later dismissed

2023-01-18 08:04 UTC, Andrewpini requested changes
There is a minor typo in in the first commit message `Bleutooth: Mesh:`. Unless of course you decided that you wanted to write it in french, then nwm 😊

2023-01-18 08:34 UTC, alxelax approved these changes

2023-01-18 08:36 UTC, Andrewpini approved these changes
Magnifique 👍

2023-01-18 09:47 UTC, merged