arch: arm: cortex_m: disable caches before reset
zephyrproject-rtos/zephyr pull request #53879
Opened 2023-01-18 07:41 UTC by arbrauns

This ensures that all pending writes to SRAM are committed. This is relevant for flags in .noinit SRAM that are read back after reset.

2023-01-18 08:40 UTC, carlocaione requested changes
Please, use the cache API functions and make it dependent on `CONFIG_ARCH_CACHE`. See https://github.com/zephyrproject-rtos/zephyr/pull/53670/commits/a6cfdb252347e9f25593a7b73cd811a974fd2b0b

2023-01-18 08:47 UTC, arbrauns commented
Ah, thanks! I wrote this patch on 3.2.0, then forward-ported it to master and missed the fact that an abstraction had been introduced in the meantime. I've moved it all to `sys_reboot()` now.

Do you have any idea when the next 3.x release is planned? There seems to have been quite a lot of activity in the past ~4 months, backporting patches is becoming a bit of a hassle.

2023-01-18 09:06 UTC, carlocaione commented
> Do you have any idea when the next 3.x release is planned? 

Very soon.

2023-01-18 09:07 UTC, carlocaione approved these changes

2023-01-18 13:07 UTC, povergoing approved these changes

2023-01-18 15:20 UTC, microbuilder approved these changes

2023-01-18 15:21 UTC, merged

2023-01-24 12:19 UTC, henrikbrixandersen commented
This broke `main` due to a missing header include statement. Fix here: https://github.com/zephyrproject-rtos/zephyr/pull/54046

2023-01-24 12:57 UTC, arbrauns commented
Whoops, sorry about that.