tests: Bluetooth: Unicast client and server improvements
zephyrproject-rtos/zephyr pull request #54099
Opened 2023-01-25 13:11 UTC by Thalley

Improves the testing of the BAP Unicast Client and Unicast Server

2023-01-30 14:03 UTC, cvinayak requested changes

2023-01-30 14:03 UTC, cvinayak commented on tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf
> +CONFIG_BT_CTLR_CENTRAL_ISO=y
This is duplicate of line 166

2023-01-30 15:49 UTC, cvinayak approved these changes

2023-02-03 10:52 UTC, MariuszSkamra approved these changes

2023-02-07 16:11 UTC, merged