ci: push test results to elasticsearch instance
zephyrproject-rtos/zephyr pull request #54115
Opened 2023-01-25 19:21 UTC by nashif

Move away from opensearch and switch to elasticsearch for reporting.
The results will be available at https://kibana.zephyrproject.io/

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2023-01-26 05:53 UTC, stephanosio requested changes

2023-01-26 05:53 UTC, stephanosio commented on .github/workflows/twister.yaml
>            pip3 install opensearch-py
```suggestion
          pip3 install elasticsearch
```

2023-01-26 11:55 UTC, stephanosio reviewed
There is a pylint failure.

2023-01-27 04:05 UTC, stephanosio approved these changes

2023-01-27 08:59 UTC, stephanosio commented
Will hold off merging this until the RC1 is tagged later today in order to prevent any potential CI breakages at the last minute before the feature freeze.

2023-01-27 10:47 UTC, nashif commented
> Will hold off merging this until the RC1 is tagged later today in order to prevent any potential CI breakages at the last minute before the feature freeze.

why would this break? and why it is ok to break after rc and not before it, if something breaks, it can be fixed quickly. That is a no brainer and simple enough. 
I am interested in starting the collection of data before the release cycle starts

2023-01-27 10:54 UTC, stephanosio commented
> why would this break?

Just trying to minimise risk.

> and why it is ok to break after rc and not before it, if something breaks, it can be fixed quickly. That is a no brainer and simple enough.

We are only hours away from the freeze and we would not want feature PRs not making this release because of failing CI, especially given that a rebase results in the dismissal of approvals.

2023-01-27 12:43 UTC, nashif commented
> We are only hours away from the freeze and we would not want feature PRs not making this release because of failing CI, especially given that a rebase results in the dismissal of approvals.

seriously now, you are basically introducing an RC0 here, risk management comes later in the release cycle, not when the development is still going on.

2023-01-27 13:57 UTC, stephanosio commented
Merging this now since this step runs on push (and not on pull requests), so the impact on pull requests CI runs should be none.

2023-01-27 13:57 UTC, merged