Da1469x watchdog driver
zephyrproject-rtos/zephyr pull request #54133
Opened 2023-01-26 13:10 UTC by blauret

This PR is adding the watchdog driver for the Renesas DA1469x microcontroller family

2023-01-26 13:25 UTC, nordicjm commented
Please see https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines - all commits need to be properly labelled as per the guidelines

2023-02-01 08:14 UTC, martinjaeger requested changes
Thanks for your contribution.

Only got a very minor comment. Otherwise looks very good.

Please note that we are in feature freeze at the moment and this PR will only get merged after v3.3 has been released (planned for 17 Feb 2023). We can still get everything ready in the meantime, though.

2023-02-01 08:14 UTC, martinjaeger commented on drivers/watchdog/wdt_smartbond.c
> +	struct wdog_smartbond_data *data = WDOG_SMARTBOND_DATA(dev);
```suggestion
	struct wdog_smartbond_data *data = (struct wdog_smartbond_data *)dev->data;
```
Using a custom macro to get the data pointer is not recommended anymore (even though still used in several drivers).

2023-02-01 08:14 UTC, martinjaeger commented on drivers/watchdog/wdt_smartbond.c
> +	struct wdog_smartbond_data *data = WDOG_SMARTBOND_DATA(dev);
See above.

2023-02-01 08:30 UTC, blauret commented
Thanks for the review. 

> Please note that we are in feature freeze at the moment and this PR will only get merged after v3.3 has been released (planned for 17 Feb 2023). We can still get everything ready in the meantime, though.

Thanks for letting me know.

2023-02-01 08:54 UTC, martinjaeger submitted a review, later dismissed

2023-02-07 13:19 UTC, ydamigos commented
Hi Ben
just with two lines:
```
diff --git a/boards/arm/da1469x_dk_pro/da1469x_dk_pro.dts b/boards/arm/da1469x_dk_pro/da1469x_dk_pro.dts
index e075a04f23..95154f5249 100644
--- a/boards/arm/da1469x_dk_pro/da1469x_dk_pro.dts
+++ b/boards/arm/da1469x_dk_pro/da1469x_dk_pro.dts
@@ -59,6 +59,7 @@

        aliases {
                led0 = &red_led;
+               watchdog0 = &wdog;
        };

        sysclk: system-clock {
diff --git a/boards/arm/da1469x_dk_pro/da1469x_dk_pro.yaml b/boards/arm/da1469x_dk_pro/da1469x_dk_pro.yaml
index 04935f5193..eebf1a7676 100644
--- a/boards/arm/da1469x_dk_pro/da1469x_dk_pro.yaml
+++ b/boards/arm/da1469x_dk_pro/da1469x_dk_pro.yaml
@@ -10,3 +10,4 @@ toolchain:
 supported:
   - arduino_gpio
   - gpio
+  - watchdog
```

you could allow twister to run watchdog_basic_api test cases:

```
./scripts/twister --device-testing --device-serial /dev/ttyUSB0 --device-serial-baud 115200 -p da1469x_dk_pro -T samples/drivers/watchdog -v -v -v

./scripts/twister --device-testing --device-serial /dev/ttyUSB0 --device-serial-baud 115200 -p da1469x_dk_pro -T tests/drivers/watchdog -v -v -v
```

2023-02-10 08:03 UTC, blauret commented
> you could allow twister to run watchdog sample and basic test cases:
> 
> ```
> ./scripts/twister --device-testing --device-serial /dev/ttyUSB0 --device-serial-baud 115200 -p da1469x_dk_pro -T samples/drivers/watchdog -v -v -v
> 
> ./scripts/twister --device-testing --device-serial /dev/ttyUSB0 --device-serial-baud 115200 -p da1469x_dk_pro -T tests/drivers/watchdog -v -v -v
> ```

Sorry, it took a while to test it's working fine. but it's done now. PR is updated. Thanks for the suggestion.

2023-02-10 16:32 UTC, ydamigos submitted a review, later dismissed

2023-02-11 09:30 UTC, martinjaeger approved these changes, later dismissed

2023-02-20 12:19 UTC, carlescufi commented
@blauret please rebase
@aaillet could you please review this?

2023-02-20 20:57 UTC, ydamigos approved these changes

2023-02-23 14:54 UTC, martinjaeger approved these changes

2023-03-03 10:02 UTC, carlescufi approved these changes

2023-03-03 10:02 UTC, merged