twister: doc: clarify harness
zephyrproject-rtos/zephyr pull request #54233
Opened 2023-01-30 15:15 UTC by nashif

Clarify the harness keyword in test metadata.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2023-01-30 15:32 UTC, MaureenHelm submitted a review, later dismissed

2023-01-30 15:56 UTC, PerMac commented on doc/develop/test/twister.rst
> +    keyboard interaction to reach verdict wheterh a test has passed or failed.
typo in whether

2023-01-30 16:53 UTC, pdietl requested changes

2023-01-30 16:53 UTC, pdietl commented on doc/develop/test/twister.rst
> +    A harness string is needed to run the tests successfully. Harness is a
```suggestion
    A harness string identifies a Twister harness needed to run a test successfully. A harness is a
```

2023-01-30 16:53 UTC, pdietl commented on doc/develop/test/twister.rst
> +    keyboard interaction to reach verdict whether a test has passed or failed.
```suggestion
    feature of Twister and is implemented by Twister, some harnesses are defined as
    placeholders and have no implementation yet. A harness can be seen as the
    handler that needs to be implemented in Twister for Twister to be able to evaluate a test's
    pass criteria. For example, a keyboard harness is set on tests that require
    keyboard interaction to reach verdict on whether a test has passed or failed. The console harness tells Twister to parse a test's text output for a regex defined in the test's YAML file.
```

2023-01-31 01:59 UTC, stephanosio submitted a review, later dismissed

2023-01-31 13:13 UTC, henrikbrixandersen requested changes

2023-02-27 08:42 UTC, henrikbrixandersen requested changes

2023-02-27 08:42 UTC, henrikbrixandersen commented on doc/develop/test/twister.rst
> +        be unique across all tests in the test suite.
Should be included in the previous commit instead?

2023-02-27 12:01 UTC, henrikbrixandersen approved these changes, later dismissed

2023-02-27 12:36 UTC, PerMac requested changes

2023-02-27 12:36 UTC, PerMac commented on doc/develop/test/twister.rst
> +    If true, twister will not try to run the test even if the test is buildable on the platform.
```suggestion
    If true, twister will not try to run the test even if the test is runnable on the platform.
``` 
? Sorry, just caught it at the last minute...

2023-02-27 13:03 UTC, PerMac approved these changes

2023-02-27 16:14 UTC, mbolivar-nordic approved these changes

2023-02-27 16:14 UTC, merged