Bluetooth: controller: Fix S2 coding tIFS trx switching
zephyrproject-rtos/zephyr pull request #5446
Opened 2017-12-20 06:26 UTC by cvinayak

Add implementation to consider differing Rx chain delays for
S2 and S8 Coded PHY PDU reception. These changes are
required to meet tIFS timings for transmission after a
reception on S8 coding.

Fix the S2 coding Rx chain delay timing constant based on
manual observations.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2017-12-20 08:45 UTC, jhedberg approved these changes
Is this something we'd want to consider for 1.10.1?

2017-12-20 10:24 UTC, carlescufi requested changes

2017-12-20 10:25 UTC, carlescufi commented
@cvinayak can you provide info about the criticality of this fix?

2017-12-20 10:37 UTC, cvinayak commented
This FIX is only related to Coded PHY, and only supported in connected roles; as there is no AE support yet or Host APIs, this is not critical to any release until its truely usable (i.e. long range connection setup)

2017-12-20 14:58 UTC, carlescufi requested changes

2017-12-20 14:58 UTC, carlescufi commented on subsys/bluetooth/controller/hal/nrf5/radio.c
>  			return 30; /* ciel(29.6) */
ceil()

2017-12-20 16:45 UTC, cvinayak commented on subsys/bluetooth/controller/hal/nrf5/radio.c
>  			return 30; /* ciel(29.6) */
ah.. its about the spelling !

2017-12-29 09:31 UTC, carlescufi approved these changes

2017-12-29 09:31 UTC, merged