Release allocated memory by mbed TLS on json_sign
zephyrproject-rtos/zephyr pull request #54511
Opened 2023-02-06 16:17 UTC by Yago-Caetano

Fixes: #54500 

This commit release allocated memory by mbedTLS on `json_sign` function

Signed-off-by: Yago Caetano <yago_caetano@outlook.com>

2023-03-09 16:10 UTC, MaureenHelm commented
please rebase

2023-03-10 09:21 UTC, joerchan requested changes
The changes looks good, but the merge-commit needs to be removed.

2023-03-10 09:21 UTC, joerchan commented on subsys/jwt/jwt.c
>  			      sig, sig_len, &sig_len,
Speaking of error handling, the call to `mbedtls_sha256` does not check the return value.
@Yago-Caetano Could you check that?

2023-03-10 13:52 UTC, joerchan commented on subsys/jwt/jwt.c
> +	if(res != 0){
```suggestion
	if (res != 0) {
```

2023-03-10 13:53 UTC, joerchan commented
@Yago-Caetano The zephyr workflow does not allow merge-commits, you now have two in your history. You need to use rebase instead.

2023-05-24 00:30 UTC, closed without merging