Bluetooth: tests: Add tests for Bluetooth privacy
zephyrproject-rtos/zephyr pull request #54708
Opened 2023-02-10 13:48 UTC by theob-pro

Add tests to check the following aspects of the Bluetooth privacy feature:

- On device privacy mode, scanner shall accept advertising packets from peer with any address type. That, even if they have previously exchanged IRK;
- After devices have exchanged IRK, they must correctly resolve RPA.

2023-02-13 11:55 UTC, alwa-nordic requested changes

2023-02-13 11:55 UTC, alwa-nordic commented on tests/bluetooth/bsim_bt/bsim_test_bt_privacy/README.rst
> +* On device privacy mode, scanner shall accept advertising packets from peer with any address type.
```suggestion
* In device-privacy mode, a scanner shall accept advertising packets from peers with any address type.
```

2023-02-13 15:37 UTC, alwa-nordic approved these changes

2023-02-23 08:08 UTC, carlescufi approved these changes

2023-02-23 08:08 UTC, merged