security: release notes
zephyrproject-rtos/zephyr pull request #54732
Opened 2023-02-10 23:51 UTC by ceolin

- Security release notes
- Information about previously published advisories.

2023-02-11 02:18 UTC, stephanosio approved these changes

2023-02-11 02:19 UTC, stephanosio requested changes
> Please remove blank lines at end of 'doc/security/vulnerabilities.rst'

@ceolin Can you please fix the coding guidelines check failure?

2023-02-11 16:07 UTC, ceolin commented
@stephanosio done !

2023-02-12 09:27 UTC, stephanosio approved these changes

2023-02-14 22:21 UTC, d3zd3z approved these changes

2023-02-14 22:21 UTC, d3zd3z commented on doc/security/vulnerabilities.rst
> +- `Zephyr project bug tracker GHSA-w525-fm68-ppq3
Do we want to say "project bug tracker", or "vulnerability tracker"?

2023-02-14 22:50 UTC, ceolin commented on doc/security/vulnerabilities.rst
> +- `Zephyr project bug tracker GHSA-w525-fm68-ppq3
The whole document is using "project bug tracker". We can do a batch change later though.

2023-02-15 10:22 UTC, merged