doc: zbus: Release notes Zephyr 3.3
zephyrproject-rtos/zephyr pull request #54791
Opened 2023-02-13 17:20 UTC by rodrigopex

Add zbus information to Zephyr 3.3 release notes.

Signed-off-by: Rodrigo Peixoto <rodrigopex@gmail.com>

2023-02-14 00:33 UTC, stephanosio approved these changes

2023-02-14 00:35 UTC, stephanosio requested changes
Looks good overall. Just a minor comment about the bullet point usage.

2023-02-14 00:35 UTC, stephanosio commented on doc/releases/release-notes-3.3.rst
> +    - Channel-centric multi-paradigm (message-passing and publish-subscribe) communication message bus;
```suggestion
    * Channel-centric multi-paradigm (message-passing and publish-subscribe) communication message bus;
```

2023-02-14 00:35 UTC, stephanosio commented on doc/releases/release-notes-3.3.rst
> +      - :ref:`zbus-hello-world-sample`
```suggestion
      * :ref:`zbus-hello-world-sample`
```

2023-02-14 10:56 UTC, rodrigopex commented on doc/releases/release-notes-3.3.rst
> +    - Channel-centric multi-paradigm (message-passing and publish-subscribe) communication message bus;
I will fix that.

2023-02-14 10:57 UTC, rodrigopex commented on doc/releases/release-notes-3.3.rst
> +      - :ref:`zbus-hello-world-sample`
I will fix that.

2023-02-14 11:18 UTC, rodrigopex commented on doc/releases/release-notes-3.3.rst
> +    - Channel-centric multi-paradigm (message-passing and publish-subscribe) communication message bus;
Done

2023-02-14 11:18 UTC, rodrigopex commented on doc/releases/release-notes-3.3.rst
> +      - :ref:`zbus-hello-world-sample`
Done

2023-02-14 11:20 UTC, rodrigopex reviewed
Requests attended.

2023-02-14 11:40 UTC, stephanosio approved these changes

2023-02-15 10:52 UTC, nordicjm approved these changes

2023-02-15 12:19 UTC, merged