toolchain: rename xcc-clang to xt-clang, and add linker profile xt-ld
zephyrproject-rtos/zephyr pull request #54836
Opened 2023-02-14 18:55 UTC by dcpleung

This renames the toolchain profile `xcc-clang` to `xt-clang` to better reflect the actual compiler being used.

This also adds a linker profile `xt-ld` so we can tailor support for Xtensa's linker. For now, it is simply to not pass `-no-pie`.

2023-02-14 22:53 UTC, andyross approved these changes, later dismissed
No complaints with this patch, but I still think we need to rethink the way we handle "gcc-like" toolchains to reduce all the cut/paste in the cmake tree.

2023-02-15 04:55 UTC, ceolin submitted a review, later dismissed

2023-02-15 07:49 UTC, tmleman submitted a review, later dismissed

2023-02-15 20:05 UTC, dcpleung commented
> No complaints with this patch, but I still think we need to rethink the way we handle "gcc-like" toolchains to reduce all the cut/paste in the cmake tree.

Xtensa tools tend to be way behind (like xt-ld being based on ld 2.34). The LD profile on main tracks latest binutils rather closely (as with the Zephyr SDK). So this is simply to avoid the main LD profile having incompatible changes to xt-ld.

2023-02-15 21:15 UTC, marc-hb commented
> Xtensa tools tend to be way behind (like xt-ld being based on ld 2.34). The LD profile on main tracks latest binutils rather closely (as with the Zephyr SDK). So this is simply to avoid the main LD profile having incompatible changes to xt-ld.

This is worth being stated at the top of the new file IMHO. Otherwise people will keep wondering about the duplication.

2023-02-17 11:01 UTC, nordicjm reviewed
No problem with the change but this seems to just instantly break anyone using `xcc-clang` with no deprecation notice to them or indication of how they cane update their workflow to remain compatible in the future

2023-02-17 15:26 UTC, tejlmand requested changes
please deprecate so that users are made aware about this change.

2023-02-17 15:26 UTC, tejlmand commented on cmake/modules/FindDeprecated.cmake
> +    message(DEPRECATION "XCC_USE_CLANG is deprecated. Please set ZEPHYR_TOOLCHAIN_VARIANT to 'xt-clang'")
Please add a deprecation warning here:
```diff
--- a/cmake/modules/FindDeprecated.cmake
+++ b/cmake/modules/FindDeprecated.cmake
@@ -50,6 +50,11 @@ if("XCC_USE_CLANG" IN_LIST Deprecated_FIND_COMPONENTS)
     set(ZEPHYR_TOOLCHAIN_VARIANT xt-clang CACHE STRING "Zephyr toolchain variant" FORCE)
     message(DEPRECATION "XCC_USE_CLANG is deprecated. Please set ZEPHYR_TOOLCHAIN_VARIANT to 'xt-clang'")
   endif()
+
+  if("${ZEPHYR_TOOLCHAIN_VARIANT}" STREQUAL "xcc-clang")
+    set(ZEPHYR_TOOLCHAIN_VARIANT xt-clang CACHE STRING "Zephyr toolchain variant" FORCE)
+    message(DEPRECATION "ZEPHYR_TOOLCHAIN_VARIANT 'xcc-clang' is deprecated. Please set ZEPHYR_TOOLCHAIN_VARIANT to 'xt-clang'")
+  endif()
 endif()
 
 if("CROSS_COMPILE" IN_LIST Deprecated_FIND_COMPONENTS)
```

2023-02-17 22:42 UTC, marc-hb commented
> this seems to just instantly break anyone using xcc-clang with no deprecation notice to them or indication of how they cane update their workflow to remain compatible in the future

This is exactly why it's being done now while very few people and machines are just getting started with `xt-clang`; before the backwards incompatibility situation you describe happens.

2023-02-18 01:59 UTC, nashif commented
> This is exactly why it's being done now while very few people and machines are just getting started with `xt-clang`; before the backwards incompatibility situation you describe happens.

we have been using xt-clang for quite a while, deprecation is still needed./

2023-02-20 07:32 UTC, nordicjm commented
> This is exactly why it's being done now while very few people and machines are just getting started with xt-clang; before the backwards incompatibility situation you describe happens.

It doesn't matter if it's 0, 1 or half of europe using it, you can't just silently break a whole setup by changing the name without having *some* level of warning to users for a period of time until it is removed.

2023-02-21 18:59 UTC, marc-hb commented
> It doesn't matter if it's 0, 1 or half of europe using it, you can't just silently break a whole setup by changing the name without having some level of warning to users for a period of time until it is removed.

Some level of warning is required _and_ it does matter for how many people it breaks.

2023-02-21 19:19 UTC, dcpleung commented on cmake/modules/FindDeprecated.cmake
> +    message(DEPRECATION "XCC_USE_CLANG is deprecated. Please set ZEPHYR_TOOLCHAIN_VARIANT to 'xt-clang'")
Added.

2023-02-21 19:19 UTC, galak reviewed
so probably better to just copy the files over to `xt-clang` and leave the `xcc-clang` files

2023-02-21 19:28 UTC, dcpleung commented
The snippet posted by @tejlmand above should provide the necessary deprecation warning.

2023-02-22 12:45 UTC, tejlmand approved these changes

2023-02-22 12:50 UTC, nashif approved these changes

2023-02-22 13:35 UTC, galak approved these changes

2023-02-22 13:35 UTC, merged