Miscellaneous devicetree improvements and cleanups
zephyrproject-rtos/zephyr pull request #55105
Opened 2023-02-22 22:13 UTC by mbolivar-nordic

This is a subset of the patches in https://github.com/zephyrproject-rtos/zephyr/pull/52272 that are standalone improvements and can IMO be merged now.

2023-02-23 11:00 UTC, nordicjm requested changes

2023-02-23 11:07 UTC, galak requested changes
Can you pull the cmake change into its own PR.  Thus @tejlmand can review that separately from the python lib changes.

2023-02-23 11:20 UTC, galak requested changes
Can you also split out the 'python-devicetree: re-work reg and ranges handling ' commit into its own PR.  All the other cleanup commits look good and will +1 (after the minor fix that was already mentioned).

Adding 'reg' and 'ranges' to dtlib.py concerns me as dtlib doesn't generally have much understanding of the contents of the tree.  I think it best to try and maintain that abstraction/separation.  I'd rather see 'reg' and 'ranges' add to edtlib.py.

2023-02-23 16:23 UTC, mbolivar-nordic commented
> I'd rather see 'reg' and 'ranges' add to edtlib.py.

That would defeat the purpose of being able to use them in sysdtlib, though, where we aren't using edtlib (because we don't need any bindings), but we still need to understand the DTSpec portions of the tree (to rewrite registers).

2023-02-23 19:18 UTC, mbolivar-nordic commented on scripts/dts/python-devicetree/src/devicetree/dtlib.py
> +        See the class documentation.
@nordicjm I don't see a problem. This is both documentation and a string, so both are correct. "Docstring" is a python term for this (see https://peps.python.org/pep-0257/), but the point of this commit is to make this docstring match all the other docstrings in this module. These all say "See the class documentation." and this commit is making this docstring match the rest of them.

2023-02-23 19:33 UTC, galak submitted a review, later dismissed

2023-02-23 19:34 UTC, mbolivar-nordic commented
@galak sorry, I caught an issue and pushed another change

2023-02-23 19:36 UTC, galak approved these changes

2023-02-23 19:37 UTC, galak commented
> @galak sorry, I caught an issue and pushed another change

Hmm, what's up with the scancode license?

2023-02-23 19:38 UTC, mbolivar-nordic commented
> Hmm, what's up with the scancode license?

I asked about this in `#ci` yesterday but got no response

2023-02-24 00:01 UTC, stephanosio commented
> > @galak sorry, I caught an issue and pushed another change
> 
> Hmm, what's up with the scancode license?

Nothing. License check failure on any non-Apache 2.0 files being added to the tree is normal. If sanctioned, the check failure can be overridden.

2023-02-24 19:46 UTC, mbolivar-nordic commented
> License check failure on any non-Apache 2.0 files being added to the
> tree is normal. If sanctioned, the check failure can be overridden.

This code is being copy/pasted from a file which already has a BSD 3
clause license, so we have to keep this license.

2023-02-27 15:31 UTC, nordicjm approved these changes

2023-02-27 16:44 UTC, merged