fix: doc: canbus: fix tx callback function name typo in code snippet
zephyrproject-rtos/zephyr pull request #55109
Opened 2023-02-23 02:36 UTC by kushnayak

In the `can_send()` example code snippet, it passed the `can_tx_callback_t` parameter as `tx_irq_callback` even though the function name was previously defined in the snippet as `tx_callback`. The function name has been updated to `tx_irq_callback` to maintain consistency.

2023-02-23 05:43 UTC, alexanderwachter approved these changes, later dismissed

2023-02-23 06:03 UTC, henrikbrixandersen requested changes
Please use `tx_callback` instead as this is consistent with the naming used in existing code.

2023-02-24 05:35 UTC, kushnayak commented
@henrikbrixandersen sure, ust updated the commit to reflect this.

2023-02-24 05:41 UTC, alexanderwachter approved these changes

2023-02-24 06:13 UTC, martinjaeger approved these changes

2023-02-24 06:16 UTC, henrikbrixandersen approved these changes
Thanks

2023-02-24 08:13 UTC, merged