usb: device: replace k_usleep with busy wait in set_endpoint
zephyrproject-rtos/zephyr pull request #55176
Opened 2023-02-24 18:34 UTC by mkaranki

set_device can be called in interrupt context at least with stm32u5 soc. Calling k_usleep from there causes the isr to run forever.

2023-02-24 22:46 UTC, jfischer-no requested changes

2023-02-24 22:46 UTC, jfischer-no commented on subsys/usb/device/usb_device.c
> +		k_busy_wait(150);
To block here is contrary to the statement "allow any canceled transfers to terminate".
The workaround for STM32F shim driver would probably to skip it in ISR context:
```suggestion
		if (!k_is_in_isr()) {
			k_usleep(150);
		}
```

2023-02-27 07:14 UTC, tmon-nordic approved these changes
Approved, although the original reason behind the sleep is somewhat shady. Hopefully the next USB stack won't have such issues.

2023-02-27 09:40 UTC, jfischer-no approved these changes

2023-02-27 10:34 UTC, merged