bindings: add grove gpio headers
zephyrproject-rtos/zephyr pull request #55190
Opened 2023-02-25 18:04 UTC by joelguittet

Add binding support for Grove header.

This is used for Wio Terminal board added with https://github.com/zephyrproject-rtos/zephyr/pull/54953.

This can be used later for other boards as well!

2023-03-03 08:19 UTC, henrikbrixandersen requested changes
Please add a groove header entry to at least one in-tree board.

2023-03-03 14:06 UTC, joelguittet commented
@henrikbrixandersen I have added initially the grove header on the board I'm currently proposing at https://github.com/zephyrproject-rtos/zephyr/pull/54953 but other maintainer required me to separate the PR.
We planned to do another PR to add the raspberrypi and grove headers on the board.

If you want to have an example here with the YAML (which I perfectly understand, I will be able to do it after the PR for the board is merged).

PS : I have no other board already in Zephyr with a Grove header.

2023-03-10 08:58 UTC, joelguittet commented
@henrikbrixandersen this is now available.

2023-03-10 13:50 UTC, henrikbrixandersen requested changes
Please split this into two commits. One adding the binding, another for using it in the Wio terminal board definition.

2023-03-12 20:01 UTC, henrikbrixandersen submitted a review, later dismissed

2023-03-12 20:47 UTC, joelguittet commented
Thanks @henrikbrixandersen !

2023-03-13 08:23 UTC, henrikbrixandersen approved these changes, later dismissed

2023-03-16 00:43 UTC, cfriedt approved these changes, later dismissed

2023-03-16 00:44 UTC, cfriedt commented
Hi @joelguittet - looks like there is a merge conflict. Can you please rebased and fix conflicts? @henrikbrixandersen & I will approve again.

2023-03-17 20:54 UTC, joelguittet commented
Hello @cfriedt yes normal it's due to https://github.com/zephyrproject-rtos/zephyr/pull/55189, I rebase right now! Thanks for your reviews!

2023-03-18 13:54 UTC, cfriedt approved these changes

2023-03-19 20:00 UTC, henrikbrixandersen approved these changes

2023-03-19 21:28 UTC, merged