drivers: dma: stm32 disabling stream waits for disable
zephyrproject-rtos/zephyr pull request #55312
Opened 2023-03-01 12:53 UTC by FRASTM

Add the loop to wait until the stream is really disable after disabling and also cleared the TCIF flag.
This is a specifity of the dma of type V1.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54805

Signed-off-by: Francois Ramu <francois.ramu@st.com>

2023-03-03 08:56 UTC, FRASTM commented
also fixes the tests/drivers/uart/uart_async_api/ running on the nucleo_f429zi:
```
Running TESTSUITE uart_async_write_abort
===================================================================
START - test_write_abort

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:526: uart_async_write_abort_test_write_abort: (sent not equal to received)
Sent is not equal to received.
 FAIL - test_write_abort in 0.120 seconds
```

2023-03-09 07:44 UTC, gautierg-st submitted a review, later dismissed

2023-03-09 12:42 UTC, erwango requested changes

2023-03-09 12:42 UTC, erwango commented on drivers/dma/dma_stm32_v1.c
> +	return 0;
Nit: Break a line.

2023-03-09 13:05 UTC, FRASTM commented
Rebase on b91aa2e28c1004141e452dee8cc1d1a8712e7d35
Add a break line before return

2023-03-09 14:37 UTC, erwango approved these changes

2023-03-15 13:27 UTC, gautierg-st approved these changes

2023-03-15 14:01 UTC, merged