tests: lib: cmis_dsp matrix_unary_f64 requires more than 64KB of RAM
zephyrproject-rtos/zephyr pull request #55322
Opened 2023-03-01 13:45 UTC by pkunieck

Increase the min ram configuration when running libraries.cmsis_dsp.matrix.unary_f64 testcase of the tests/lib/cmsis_dsp/matrix/  Issue occured on MEC172x after moved the cmsis_dsp tests to new ztest API in this commit: #50075 . Error from the test was "buffer allocation failed, " meaning it is running out of memory. This should have been included in #51883 but was skipped for some reason.

2023-03-13 16:44 UTC, galak requested changes
maybe set this to 65 instead of 128, as there might be boards w/96 or some other size between 64 and 128.

2023-03-14 16:51 UTC, stephanosio requested changes
Please amend the first commit instead of pushing new ones.

2023-03-14 16:51 UTC, stephanosio commented on tests/lib/cmsis_dsp/matrix/testcase.yaml
> +    min_ram: 65
We know that 64k is not enough for some platforms; but, is 65k enough?

Probably not; even if it is, there would be very little headroom to work with.

My suggestion would be to increment it more leniently (e.g. by 8) to ensure that we do not need another change like this in the next few months.

2023-04-20 17:35 UTC, nashif approved these changes

2023-04-20 19:05 UTC, stephanosio approved these changes

2023-04-21 14:09 UTC, galak approved these changes

2023-04-21 14:09 UTC, merged