ci: twister: Enable tests on bsim boards
zephyrproject-rtos/zephyr pull request #55365
Opened 2023-03-02 13:57 UTC by aescolar

Since the move to github workflows
e366d7948a536951d63392dd3bc63c36212e8081
we lost the ability to run in CI in twister the bsim boards. This means people cannot use the nrf52_bsim in normal twister workflows even if it would work perfectly fine otherwise (say as a stand alone test of the controller that does not require an actual BT pair).
It also meant changes to the bsim board itself where not tested with twister like for other boards, but relied solely on the BT tests.

Enable this kind of tests again.

2023-03-02 14:03 UTC, carlescufi approved these changes

2023-03-02 14:20 UTC, nashif commented
This is not working as expected though...
![image](https://user-images.githubusercontent.com/180017/222454526-4610088e-af44-4bdd-a51f-380bfb940c7e.png)


Isn't this already running as part of the bluetooth tests?

2023-03-02 14:26 UTC, nashif commented
Ok, this could be because of the stupid pull_request_target thing, so we might see results when this is merged, was this verified somewhere else, to avoid surprises?

2023-03-02 14:50 UTC, nashif commented
if I run twister with this board on my system, I get lots of errors maybe due to missing filter, so maybe we should limit the scope to bluetooth and a few other essential thing, given that we are not trying to duplicate what native_posix  already does.

I see this with `twister -p nrf52_sim`:
```
INFO    - 2215 test scenarios (2024 test instances) selected, 1651 configurations skipped (1517 by static filter, 134 at runtime).
INFO    - 357 of 2024 test configurations passed (95.71%), 4 failed, 12 errored, 1651 skipped with 0 warnings in 276.57 seconds
INFO    - In total 4348 test cases were executed, 6034 skipped on 1 out of total 547 platforms (0.18%)
INFO    - 318 test configurations executed on platforms, 55 test configurations were only built.
```

2023-03-02 15:51 UTC, aescolar commented
Another 2 failures fixed in https://github.com/zephyrproject-rtos/zephyr/pull/55374

2023-03-02 16:29 UTC, aescolar commented
Another coming here: https://github.com/zephyrproject-rtos/zephyr/pull/55375

2023-03-03 08:54 UTC, aescolar commented
Another 5 : https://github.com/zephyrproject-rtos/zephyr/pull/55391

2023-03-03 09:20 UTC, aescolar commented
Another 2 https://github.com/zephyrproject-rtos/zephyr/pull/55395 
samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing
tests/subsys/rtio/rtio_api/subsys.rtio.api

2023-03-03 09:50 UTC, aescolar commented
Another https://github.com/zephyrproject-rtos/zephyr/pull/55398
tests/lib/sys_util/libraries.sys_util

2023-03-07 13:27 UTC, aescolar commented
@stephanosio All tests should be fixed now (all needed PRs are merged). Could you give it a spin in the test repo and merge if you are happy with the result? (Feel free to disregard the DNM, now it is only to allow you to decide when to merge it)

2023-03-07 14:02 UTC, stephanosio requested changes, later dismissed
> @stephanosio All tests should be fixed now (all needed PRs are merged). Could you give it a spin in the test repo and merge if you are happy with the result? (Feel free to disregard the DNM, now it is only to allow you to decide when to merge it)

It looks like there are still some failures:

https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/4354747300/jobs/7610564622#step:13:865

2023-03-09 09:33 UTC, stephanosio approved these changes
Tested in https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/4372549682

2023-03-09 09:33 UTC, merged