kernel: posix: typedef should be defined into types.h file.
zephyrproject-rtos/zephyr pull request #5545
Opened 2018-01-03 10:17 UTC by youvedeep

As per POSIX standard typedef should be defined into sys/types.h file
So moving typedef from pthread.h to sys/types.h file (http://pubs.opengroup.org/onlinepubs/7908799/xsh/systypes.h.html)

Signed-off-by: Youvedeep Singh <youvedeep.singh@intel.com>

2018-01-03 16:55 UTC, nashif commented
shouldn't this header be part of the minimal libc? or why don't you use the newlib libc and depend o n the headers provided by newlib?

2018-01-03 17:47 UTC, lpereira commented
Please see the comment about using `#include_next` in another PR related to POSIX patches.  Also, please don't forget include guards.

2018-01-04 17:11 UTC, youvedeep commented
Addressed comments from @nashif and @lpereira .

2018-01-05 11:04 UTC, pfalcon approved these changes
Definitely a step in the right direction, thanks!

2018-01-05 22:41 UTC, lpereira requested changes
If you're going to use `#include_next`, use it to define types, constants, and prototypes that are *adding* to the definition found in any of the supported C libraries.  Even then, using it without modifying the build system to include the include path will lead to confusion as to which include is actually being included.

Imagine this scenario here:

Minimal libc `foo.h` in `${ZEPHYR_ROOT}/include`:
```C
#ifndef __FOO_H__
#define __FOO_H__

void make_foo(int bar);

#endif /* __FOO_H__ */
```

Zephyr applications are built with the `-I ${ZEPHYR_ROOT}/include` command line argument, so that a line such as `#include <foo.h>` will include the prototype for our hypothetical `make_foo()` function.  Say that we want to support the BARSIX standard, and that it also happens to extend `foo.h`. We have two options here:

* Modify `${ZEPHYR_ROOT}/include/foo.h` to include the BARSIX-specific foo.h include if we have `CONFIG_BARSIX_COMPAT` set
* Modify the build system, so that `-I ${ZEPHYR_ROOT}/include/barsix` is passed *before* the `/include` directory, so a `#include <foo.h>` will include BARSIX support's header file first

The first option is nice because there is no need to modify the build system, which is always a good thing.  Build systems are finicky.  However, you would have to modify also the headers for both the minimal C library and newlib.  If people end up using another C library, they would have to modify that other C library as well to include Zephyr's BARSIX support headers.

The second option, then, ends up being a clean solution: it'll include Zephyr's foo.h, regardless of which C library has been chosen, and then, it'll define its own types.   This will be transparent for the application.

I use this technique on a [personal project](https://github.com/lpereira/lwan/tree/master/src/lib/missing) to attain portability without having to sprinkle `#ifdef`s all over the place, and I like it. For instance, take a look at Lwan's [pthread.h](https://github.com/lpereira/lwan/blob/master/src/lib/missing/pthread.h), that defines pthread_barrier for systems that do not have it, without having to modify the system header files and create a mess of `#ifdef` in my application.

2018-01-08 16:22 UTC, youvedeep commented on include/posix/sys/types.h
> +
#endif /* CONFIG_PTHREAD_IPC */

2018-01-09 09:22 UTC, youvedeep commented
Hi @lpereira 

So basically you are recommending to go with option 2 (Modify the build system).
Going by this we have 2 <sys/types.h> files - 
1. include/posix/sys/types.h
2.  lib/libc/minimal/include


As we have put "#include_next <sys/posix.h>" inside posix specific sys/types.h file (include/posix/sys/types.h). 
Now we want to make sure "include/posix/sys/types.h" is getting called before libc specific sys/types.h ( lib/libc/minimal/includesys/types.h). 

My understanding is it is already happening :- 
1. As zephyr_include_directories(include) is occurring earlier than add_subdirectory(lib). 

Case 1 : 
CONFIG_NEWLIB_LIBC=y and CONFIG_PTHREAD_IPC=y (something like qemu_nios2 with posix enabled)
Then sys/types.h wrt to minlibc will be included (as CONFIG_NEWLIB_LIBC =y) along with posix specific typedef.

Case 2:- 
CONFIG_NEWLIB_LIBC=y and CONFIG_PTHREAD_IPC=n (something like qemu_nios2 with posix disbled)
Then only sys/types.h corresponding to minlibc will be included and POSIX specific declaration will be blocked by CONFIG_PTHREAD_IPC=n.

Case 3:- 
CONFIG_NEWLIB_LIBC=n and CONFIG_PTHREAD_IPC=y (something like qemu_cortex_m3 with posix enabled)
Then only sys/types.h corresponding  POSIX specific declaration will be included and minlibc specific will be blocked due to CONFIG_NEWLIB_LIBC=n

Case 4: 
CONFIG_NEWLIB_LIBC=n and CONFIG_PTHREAD_IPC=n (something like qemu_cortex_m3 with posix Disabled)
none of sys/type.c will be included.

2018-01-11 00:51 UTC, lpereira commented
The idea is to have a tree like the following:

```
+
|--- include/
|     +--- sys/
|     |     + types.h
|     +--- posix/
|           +--- sys/
|                 + types.h
```

You would not modify `include/sys/types.h`.   You would, howerver, write `include/posix/sys/types.h` like the following:

```C
#ifndef __POSIX_SYS_TYPES_H__
#define __POSIX_SYS_TYPES_H__

#include_next <sys/types.h>

#if defined(CONFIG_POSIX_COMPAT)

/* define POSIX-related stuff here */

#endif /* CONFIG_POSIX_COMPAT */

#endif /* __POSIX_SYS_TYPES_H__ */
```

And then modify the build system to include `include/posix` before any other include directory lookup path, so that any directive `#include <sys/types.h>` would do the right thing (include the next `sys/types.h` in line, under `include/`, and then define the POSIX stuff we need to support).

The `#if defined(CONFIG_POSIX_COMPAT)` guard isn't strictly necessary, because `include/posix` will only be added to the compiler's command line if POSIX compatibility is required, but it doesn't hurt.

Doing it like this will enable the usage of newlib's `sys/types.h` without modifying it twice.

2018-01-11 09:22 UTC, youvedeep commented
Thanks @laperie 


In Zephyr tree, we do not have any file - _include/sys/types.h_.  So we have only 2 “_sys/types.h_”. (one _include/posix/sys/types.h_ and another _lib/libc/minimal/include/sys/types.h_). 
Can you please comment on which <include/sys/types.h> file you are referring to (is this to address for some future issue when we create new include/sys/ypes.h ?).
wrt to sys/types.h tree looks something like this.

|--- include/
|     +--- posix/
|           +--- sys/
|                 + types.h
|
|------lib/
|	+----libc/
|		+minimal/
|			+include/
|				+sys/
|					+types.h
We have done exactly same as you mentioned, We are making sure that _include/posix/sys/types.h_ is included first and it inturn includes include next include (_lib/libc/minimal/include/sys/types.h_)




I have implemented "_include/posix/sys/types.h_" file same as your's sample file except _#include_next <sys/types.h>_ inclusion is guarded  with _CONFIG_NEWLIB_LIBC_.

2018-01-11 10:34 UTC, pfalcon commented
@lpereira 

> The idea is to have a tree like the following:

In general, do we have a separate ticket/email thread for an RFC of these ideas?

2018-01-11 21:24 UTC, lpereira commented
Youvedeep, it doesn't matter which `<sys/types.h>` it is, as long as the `-I` parameter to GCC picks them. Calling the compiler like so:

```
$ gcc -I /path/to/zephyr/include/posix -I /path/to/zephyr/lib/libc/minimal/include
```

Considering that there is a `sys/types.h`**(†)** in `/path/to/zephyr/include/posix` and a `sys/types.h`**(‡)** in `/path/to/zephyr/lib/libc/minimal/include`**(§)**, will make the compiler include **(†)** first; the `#include_next <sys/types.h>` directive will include the next file in the include lookup path; namely, **(‡)**.

If **(§)** is instead the newlib include directory, things should work the same way: **(†)** will `include_next` the file from newlib.

That's why the build system needs to be changed as well: the compiler should be invoked with the additional `-I` argument. The order these arguments are passed to gcc is important.

2018-01-13 17:49 UTC, youvedeep commented
patch in this PR is discussed as part of PR : https://github.com/zephyrproject-rtos/zephyr/pull/5667
So please have a look at https://github.com/zephyrproject-rtos/zephyr/pull/5667 and provide comment.

2018-01-24 12:38 UTC, youvedeep commented
This PR is put as part of - https://github.com/zephyrproject-rtos/zephyr/pull/5667.
So please give review comments as part of https://github.com/zephyrproject-rtos/zephyr/pull/5667

2018-01-24 12:38 UTC, closed without merging