Fix pathname for SMP sample examples
zephyrproject-rtos/zephyr pull request #55571
Opened 2023-03-07 21:06 UTC by KumarAmitMehta

2023-03-23 15:44 UTC, nashif submitted a review, later dismissed

2023-03-23 15:45 UTC, nashif commented
Please squash your commits.

2023-03-27 07:19 UTC, abrodkin requested changes
@KumarAmitMehta would be really good to add a rationale for that change in the PR description. Otherwise, it's not clear what kind of problem are we really fixing.

2023-03-27 08:05 UTC, finikorg commented
> @KumarAmitMehta would be really good to add a rationale for that change in the PR description. Otherwise, it's not clear what kind of problem are we really fixing.

It fixes broken documentation, check for example: https://docs.zephyrproject.org/latest/samples/arch/smp/pi/README.html

2023-03-27 08:07 UTC, finikorg approved these changes
LGTM

2023-03-27 08:15 UTC, henrikbrixandersen approved these changes

2023-03-27 09:11 UTC, abrodkin commented
> > @KumarAmitMehta would be really good to add a rationale for that change in the PR description. Otherwise, it's not clear what kind of problem are we really fixing.
> 
> It fixes broken documentation, check for example: https://docs.zephyrproject.org/latest/samples/arch/smp/pi/README.html

I'm not arguing a need for this change. But that PR has no information about real problem you're referring to. And looking forward it's always good to add a meaningful description to the PR, so looking at that later one may realize what was that and why it was done.

2023-03-27 11:36 UTC, uLipe requested changes
Would like to understand why the espressif_hal revision has been changed before reviewing this.

2023-03-27 14:29 UTC, MaureenHelm approved these changes

2023-03-27 14:37 UTC, teburd approved these changes

2023-03-27 14:50 UTC, uLipe approved these changes

2023-03-27 15:01 UTC, abrodkin approved these changes
Thanks for the update in the PR description.
Though it looks like there was an issue this PR is addressing, so if that's the case it would be nice to add that reference in this PR.

2023-03-27 15:06 UTC, merged