net: shell: Check connection & capabilities in any TWT operation
zephyrproject-rtos/zephyr pull request #55581
Opened 2023-03-08 07:03 UTC by ajayparida

Connection status & AP capabilities checked before any TWT operation is initiated.

2023-03-08 07:03 UTC, ajayparida commented
@krish2718 @sachinthegreen

2023-03-08 07:14 UTC, krish2718 requested changes

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +				status.twt_capable ? "Enabled" : "Disabled");
Should be Supported or Not supported

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		shell_fprintf(sh, SHELL_WARNING, "<TWT operation failed>: Link mode not 11AX\n");
`Wi-Fi 6/11 ax` is better, same as `wifi status`

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		shell_fprintf(sh, SHELL_WARNING, "<TWT operation failed> : Not connected\n");
Replace all `failed` with `locally rejected`.

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +static int wifi_link_status_info(const struct shell *sh)
`wifi_link_info`, status is redundant and not applicable in this case.

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		shell_fprintf(sh, SHELL_WARNING, "Status request failed\n");
`Wi-Fi status request`

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +	struct wifi_iface_status status = { 0 };
`info` is appropriate in this context

2023-03-08 07:14 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +	int ret = 0;
can be removed as its unused.

2023-03-08 11:04 UTC, sachinthegreen approved these changes, later dismissed

2023-03-09 12:33 UTC, ajayparida commented on subsys/net/l2/wifi/wifi_shell.c
> +	if (info.link_mode < WIFI_6) {
changing to '!='' will result in true for lower values  WIFI_5 etc

2023-03-10 08:36 UTC, rlubos approved these changes, later dismissed

2023-03-10 11:30 UTC, krish2718 requested changes

2023-03-10 11:30 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +static int wifi_link_info(const struct shell *sh)
Thinking a bit on this, these should be handled in the wifi_mgmt so that these are applicable for API as well.

2023-03-28 07:46 UTC, ajayparida commented
@rado17

2023-03-28 08:31 UTC, krish2718 requested changes

2023-03-28 08:31 UTC, krish2718 commented on include/zephyr/net/wifi.h
> +	[EAPNOTHECAPAB] = "AP not HE Caapble",
```suggestion
	[EAPNOTHECAPAB] = "Peer not HE Capable",
```

2023-03-28 08:31 UTC, krish2718 commented on include/zephyr/net/wifi.h
> +	[EAPNOTTWTCAPAB] = "AP not TWT capable",
```suggestion
	[EAPNOTTWTCAPAB] = "Peer not TWT capable",
```

2023-03-28 08:31 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +
extra newline

2023-03-28 08:31 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +
merge to above print?

2023-03-28 11:08 UTC, krish2718 submitted a review, later dismissed

2023-03-28 13:39 UTC, rlubos commented on include/zephyr/net/wifi.h
> +	    twt_err_code_tbl[-err_no]) {
This makes little sense, the array bounds were checked just above.

2023-04-13 15:43 UTC, ajayparida commented
> @ajayparida ping
Hi, If it is rearding the PR  comment changes, it is under progress.
It will be updated soon.

2023-04-18 10:11 UTC, ajayparida commented on include/zephyr/net/wifi.h
> +	EUNSPECIFIED = 0,
Please review the changes as per suggestion.

2023-04-19 09:58 UTC, rlubos submitted a review, later dismissed

2023-04-25 07:11 UTC, krish2718 submitted a review, later dismissed

2023-04-25 07:11 UTC, krish2718 commented on include/zephyr/net/wifi.h
> +	WIFI_TWT_FAIL_CMD_EXEC,
```suggestion
	WIFI_TWT_FAIL_CMD_EXEC_FAIL,
```

2023-04-25 09:15 UTC, krish2718 approved these changes

2023-04-25 11:31 UTC, rado17 approved these changes

2023-04-25 11:41 UTC, rlubos approved these changes

2023-04-27 05:21 UTC, ajayparida commented
@jukkar

2023-04-27 06:40 UTC, jukkar approved these changes

2023-04-27 07:52 UTC, merged