LE Audio: BAP shell improvements
zephyrproject-rtos/zephyr pull request #55721
Opened 2023-03-13 10:49 UTC by Thalley

This PR improves the BAP shell by

- Making presets constant, and moving stream-specific configuration into a new unicast_stream struct
- Improve metadata handling
- Refactor handling of QoS
- Refactor handling of default presets

2023-03-13 12:18 UTC, larsgk requested changes
Please update docs too :)

2023-03-13 13:05 UTC, larsgk approved these changes, later dismissed

2023-03-13 14:20 UTC, Thalley commented
Fixed segmentation fault and added additional commit to handle setting stream location as part of `cmd_config`

2023-03-13 15:10 UTC, larsgk approved these changes

2023-03-15 06:20 UTC, MariuszSkamra approved these changes

2023-03-15 08:12 UTC, merged