MAINTAINERS: Move intel bindings from ADSP to generic Intel X86
zephyrproject-rtos/zephyr pull request #55848
Opened 2023-03-16 09:39 UTC by finikorg

At the moment all Intel drivers get label Intel ADSP. I believe the right place would be the generic Intel X86.

2023-03-16 10:03 UTC, stephanosio approved these changes, later dismissed

2023-03-16 11:04 UTC, jhedberg approved these changes, later dismissed

2023-03-16 12:34 UTC, nashif requested changes
that just reverses the issue, now all adsp suff will be marked as X86, which is wrong. I would suggest to filter adsp stuff using the fact that most adsp bindings are `dts/bindings/*/intel,adsp.*`. Some of the binding names needs a cleanup to get more accuracy, but this solves the issue better.

2023-03-16 15:58 UTC, nashif commented on MAINTAINERS.yml
> +    - dts/bindings/*/intel,adsp.*
`dts/bindings/*/intel,adsp*`

2023-03-17 08:58 UTC, finikorg commented on MAINTAINERS.yml
> +    - dts/bindings/*/intel,adsp.*
changed as proposed

2023-03-17 10:41 UTC, stephanosio approved these changes

2023-03-17 10:45 UTC, nashif approved these changes

2023-03-17 10:45 UTC, merged