RISCV: Refactor inline ASM in favor of macro functions
zephyrproject-rtos/zephyr pull request #55888
Opened 2023-03-16 17:41 UTC by manoj153

This PR refactors the code to use macro functions from `csr.h` instead of repeating inline ASM, which results in cleaner and more maintainable code. 

- No impact on the existing logic of the code

2023-03-16 18:45 UTC, npitre commented
The two `csr_write_immediate()` new instances are fine,
but the corresponding inline asm statements were not removed.
Please fix.

2023-03-16 18:56 UTC, npitre commented
In fact, you don't need `csr_write_immediate()` at all.
Just use plain `csr_write()` with immediate arguments.
The inline asm constraint already accepts immediate values and the
assembler is smart enough to turn a csrw into a csrwi as appropriate.

2023-04-04 08:28 UTC, fkokosinski commented
Hi @manoj153, are you working on applying changes suggested by @npitre?

2023-04-19 15:55 UTC, npitre commented
Changes were trivial so I just pushed them here.

2023-04-19 15:55 UTC, npitre submitted a review, later dismissed

2023-04-19 16:12 UTC, carlocaione requested changes
Squash all the three commits together and write a proper commit message content.

2023-04-20 17:28 UTC, carlocaione requested changes
This is not a proper commit message. Please split the content from the subject.

2023-04-21 07:39 UTC, manoj153 commented
> This is not a proper commit message. Please split the content from the subject.

 I have updated it. Can you confirm whether the current commit message is satisfactory?

2023-04-21 07:41 UTC, carlocaione approved these changes

2023-04-21 08:32 UTC, fkokosinski approved these changes
LGTM

2023-04-21 10:54 UTC, merged