z_sched_init: don't use arch_num_cpus()
zephyrproject-rtos/zephyr pull request #55890
Opened 2023-03-16 22:06 UTC by npitre

The reason for arch_num_cpus() is to be able to dynamically adapt to
the actual number of available CPUs at run time. In such case the value
returned by arch_num_cpus() would always be 1 when z_sched_init() is
called as SMP is not yet initialized at that point.

2023-03-16 22:26 UTC, dcpleung approved these changes, later dismissed

2023-03-16 22:35 UTC, galak requested changes
This is not the case on xtensa, we set the number of CPUs in early init and thus it will be before this is called.

Also, why does this need changing?

2023-03-16 23:51 UTC, andyross approved these changes, later dismissed
This looks correct to me.  This is just the initialization of the cpu struct, so we want to be initializing the memory for all/any CPUs and not just the ones active in the runtime state.

Alternatively, we could look at doing this per-cpu in the SMP code, e.g. calling out to a z_sched_init_cpu() or whatever out of start_cpu() in smp.c.  Then we'd get it automatically when CPUs on/offline.

2023-03-17 15:04 UTC, npitre commented
@galak wrote:

> This is not the case on xtensa, we set the number of CPUs in early 
> init and thus it will be before this is called.

It doesn't mean it is the case for everyone though. Otherwise what is
the point of having a callable interface?

> Also, why does this need changing?

On RISC-V we don't want to send scheduler IPIs to CPUs that are not yet
online. The cleanest solution for that is to have `arch_num_cpus()`
reflect the actual number of active CPUs. And that is initiall;y 1.

In the `z_sched_init()` case, it is not the number of active CPUs that we
need but rather the number of potential CPUs and that is represented by
`CONFIG_MP_MAX_NUM_CPUS` not `arch_num_cpus()`.

2023-03-17 15:16 UTC, galak commented
> On RISC-V we don't want to send scheduler IPIs to CPUs that are not yet online. The cleanest solution for that is to have `arch_num_cpus()` reflect the actual number of active CPUs. And that is initiall;y 1.
> 

I don't think we should overload the use of arch_num_cpus() this way.  We should add something new for the number of online_cpus().

> In the `z_sched_init()` case, it is not the number of active CPUs that we need but rather the number of potential CPUs and that is represented by `CONFIG_MP_MAX_NUM_CPUS` not `arch_num_cpus()`.

So I think just updating the commit message to reflect why this change is needed and why its safe to make it not use `arch_num_cpus`.  The bit about it `would always be 1` isn't correct so we should remove that from the commit message.

2023-03-17 18:20 UTC, andyross approved these changes
Refresh +1, this still looks correct to me.  The argument about arch_num_cpus() semantics is sort of a side thing, regardless of the convention picked, the intent of this initialization code is to initialize the entire _kernel.cpus[] array, no matter which elements of it may be in use, and how.

2023-03-17 18:34 UTC, dcpleung approved these changes

2023-03-26 20:17 UTC, npitre commented
@galak: ping

2023-04-03 16:35 UTC, galak approved these changes

2023-04-03 16:36 UTC, merged