drivers: hwinfo: add wakeup flag cause
zephyrproject-rtos/zephyr pull request #55993
Opened 2023-03-20 12:59 UTC by Desvauxm-st

add retrieve wakeup flag of device and Clear wakeup flag

2023-03-22 11:07 UTC, erwango requested changes
Please squash the 3 first commits.
Otherwsie LGTM

2023-03-22 13:42 UTC, erwango submitted a review, later dismissed

2023-03-24 12:31 UTC, gautierg-st submitted a review, later dismissed

2023-03-24 13:32 UTC, FRASTM requested changes, later dismissed

2023-03-24 14:44 UTC, Desvauxm-st commented on drivers/hwinfo/hwinfo_stm32.c
> +	LL_PWR_ClearFlag_SB();
OK

2023-03-24 14:47 UTC, erwango approved these changes, later dismissed

2023-03-24 15:03 UTC, gautierg-st submitted a review, later dismissed

2023-03-29 11:17 UTC, FRASTM submitted a review, later dismissed

2023-03-29 13:15 UTC, alexanderwachter commented
@Desvauxm-st merge commits are not allowed in Zephyr. You need to rebase your commits on main instead.

2023-03-29 15:33 UTC, FRASTM approved these changes

2023-03-30 06:43 UTC, gautierg-st approved these changes

2023-03-30 07:50 UTC, merged

2023-03-30 14:01 UTC, KloudJack commented
Since this PR was merged, unit tests for STM32 hwinfo now fail.

See the [workflow result](https://github.com/zephyrproject-rtos/zephyr/pull/56330/checks?check_run_id=12397402575) for a PR I've rebased recently.