devicetree: Add DT_INST_PROP_LEN_OR
zephyrproject-rtos/zephyr pull request #56029
Opened 2023-03-21 13:41 UTC by pdgendt

Add the instance-based version of DT_PROP_LEN_OR.

2023-03-21 16:03 UTC, mbolivar-nordic requested changes
Thanks. This needs a test in tests/lib/devicetree/api.

2023-03-21 16:05 UTC, pdgendt commented
> Thanks. This needs a test in tests/lib/devicetree/api.

Hi @mbolivar-nordic, I've added the test already?

2023-03-21 17:07 UTC, mbolivar-nordic approved these changes
Weird, it wasn't showing up and is now saying it's changes since I last viewed. Thanks!

2023-03-23 09:23 UTC, henrikbrixandersen approved these changes

2023-03-23 09:30 UTC, carlescufi approved these changes

2023-03-23 09:30 UTC, merged