Bluetooth: audio: Expand AICS API
zephyrproject-rtos/zephyr pull request #56037
Opened 2023-03-21 15:42 UTC by szymon-czapracki

This PR adds new API functions for AICS
Setting automatic/manual only gain modes.
Setting mute disabled.

Auto-pts tests:
1/2   AICS    AICS/SR/SGGIT/CP/BI-03-C   PASS           36.713                  
2/2   AICS    AICS/SR/SGGIT/CP/BI-04-C   PASS           37.512

2023-03-21 16:39 UTC, Thalley requested changes
Minor request for more documentation

2023-03-21 16:39 UTC, Thalley commented on include/zephyr/bluetooth/audio/aics.h
> + */
Maybe we should add some documentation about this disabling support for setting the gain via `bt_aics_gain_set` or from clients

2023-03-28 11:11 UTC, Thalley requested changes

2023-03-28 11:11 UTC, Thalley commented on include/zephyr/bluetooth/audio/aics.h
> + * @param inst          The instance pointer.
I think perhaps we should add something like

```suggestion
 * @brief Disable mute in the Audio Input Control Service.
 *
 * Calling bt_aics_unmute() or bt_aics_mute() will enable mute again and set the
 * mute state to either unmuted or muted. 
 *
 * @param inst          The instance pointer.
```

2023-03-28 11:11 UTC, Thalley commented on tests/bluetooth/tester/src/btp_vcp.c
> +	LOG_DBG("AICS auto gain only set");
```suggestion
	LOG_DBG("AICS main gain only set");
```

2023-03-28 11:11 UTC, Thalley commented on tests/bluetooth/tester/src/btp_vcp.c
> +			     void *rsp, uint16_t *rsp_len)
```suggestion
static uint8_t aics_mute_disable(const void *cmd, uint16_t cmd_len,
				 void *rsp, uint16_t *rsp_len)
```

2023-03-28 11:11 UTC, Thalley commented on tests/bluetooth/tester/src/btp_vcp.c
> +			      void *rsp, uint16_t *rsp_len)
```suggestion
static uint8_t aics_auto_gain_only(const void *cmd, uint16_t cmd_len,
				   void *rsp, uint16_t *rsp_len)
```

2023-03-28 11:11 UTC, Thalley commented on tests/bluetooth/tester/src/btp_vcp.c
> +			      void *rsp, uint16_t *rsp_len)
```suggestion
static uint8_t aics_man_gain_only(const void *cmd, uint16_t cmd_len,
				  void *rsp, uint16_t *rsp_len)
```

2023-03-29 09:21 UTC, Thalley approved these changes

2023-03-30 12:24 UTC, MariuszSkamra approved these changes

2023-03-31 07:20 UTC, merged