samples: remove references to Quark SE board
zephyrproject-rtos/zephyr pull request #56131
Opened 2023-03-22 22:28 UTC by nashif

- samples: i2c fram: remove reference to obsolete board
- samples: zperf: remove reference to quark se
- samples: max44009: remove reference to quark se

2023-03-23 01:34 UTC, teburd submitted a review, later dismissed

2023-03-23 14:15 UTC, MaureenHelm requested changes

2023-03-23 15:42 UTC, nashif commented on samples/drivers/i2c_fujitsu_fram/README.rst
> +   :board: frdm_k64f
neither did the quark_se, this is an external module connected via i2c

2023-03-24 15:52 UTC, MaureenHelm commented on samples/drivers/i2c_fujitsu_fram/README.rst
> +   :board: frdm_k64f
There's nothing in the sample indicating an external module is required - no mention in the rst and no dts overlay. I think we should just remove it.

2023-03-27 14:25 UTC, MaureenHelm approved these changes

2023-03-29 15:17 UTC, teburd approved these changes

2023-03-29 15:26 UTC, merged