mgmt: mcumgr: accept "offset reverted" packets to improve robustness
zephyrproject-rtos/zephyr pull request #56287
Opened 2023-03-28 13:22 UTC by JiapengLi

`reverted offset` could be caused by ble connection is unstable or mcu high load. Overwrite `fs_mgmt_ctxt.off` to `off` to continue upload process, this improves upload success rate

2023-03-28 13:27 UTC, nordicjm requested changes
No, this is not valid, the MCUmgr client send a command, wait for a response. Bluetooth is a reliable transport, so if a packet is dropped, it will be resent until it is either acknowledged or the supervision timeout occurs, at which point the connection will be dropped.

2023-03-28 13:55 UTC, JiapengLi commented
@nordicjm Thank you for your prompt response. 

i am not sure how ble retry behaves, but i indeed test under ble link.
reverted offset also happens even if mcumgr client send the same packet at application layer. 
As I mentioned in the PR, reverted offset happens only at high mcu load (possible) or unstable BLE connection (may not)


my test log is like this:
 ```
                      off      fs_mgmt_ctxt.off
...
fs_mgmt_file_upload 285552 <-> 285552
fs_mgmt_file_upload 287972 <-> 287972
fs_mgmt_file_upload 290392 <-> 290392
# reverted offset
fs_mgmt_file_upload 285552 <-> 292812
fs_mgmt_file_upload 285552 <-> 292812
fs_mgmt_file_upload 285552 <-> 292812

# seesion aborted
 ```

my test environment:
- zephyr v3.2-branch
- nrf52840
- nRF Connect Device Manager v1.6.0

2023-03-28 14:52 UTC, nordicjm commented
You'd need to get a trace with e.g an nRF52840 loaded with the sniffer firmware showing where this "revert" is coming from, zephyr should not be sending a lower offset.

2023-03-28 15:04 UTC, JiapengLi commented
The reverted offset is sent by app, this is related to client upload api. 

OK. Let me try to sniff rf packets, and provide more details.

2023-03-28 15:09 UTC, nordicjm commented
@dinesharjani this sounds like an app bug?

2023-03-28 15:46 UTC, dinesharjani commented
@nordicjm this is Android? I think? The version number looks like Android. But I would not discount that this issue could be on the side of iOS as well, I can have a look at the code. Anyway, pinging @philips77

2023-03-29 00:48 UTC, JiapengLi commented
Yes. I tested through android nRF Connect Device Manager v1.6.0.

2023-03-30 14:33 UTC, de-nordic requested changes
It should not be possible to get random packet sequence via bluetooth, unless client app breaks something.
Btw. This part of code is not bluetooth specific.

2023-03-30 16:04 UTC, JiapengLi commented
i will provide more information. Please allow me some time.

In my point of view, the transport layer can't always guarantee each pkt will be received only once, from my experience it is not easy, and costive. (For example mqtt QoS 2: exactly once.)
For current implementation, even a retry packet would stop the process (of course you can say it is on transport, but it is not always the way).

I do agree my case is not a general case. This patch just improve robustness, and doesn't break anything. It is some sort none common sense, but it do good.

2023-03-31 06:47 UTC, nordicjm commented
> In my point of view, the transport layer can't always guarantee each pkt will be received only once, from my experience it is not easy, and costive. (For example mqtt QoS 2: exactly once.)

Well in bluetooth it does actually, MQTT does too. In fact they both work similarly, for TCP/IP the host sends the data, the receiving device then sends an ACK packet - if the ACK packet is not received then the message will be sent again - it will be marked as a retransmission and have the same IP header details as the previous packet, so if the receiving device gets it again, it knows that the ACK packet was lost and will retransmit it, it will not give that data to the application again. Likewise in BLE, _all_ transmissions are acknowledged, the difference is in where they are acknowledged, indications and write with response packets are acknowledged at the application level, notifications and write without response packets are acknowledged at the stack level - the difference being that if the applications buffers or configuration is such that it cannot accept the data, notifications/write without response data will be dropped whereas indication/write with response will not and will need to be resent until it is accepted. If that is the issue you are seeing, then chances are your devices buffer configuration is inadequate for the amount of data the phone is sending, but that would not explain why the file write position counter would be going backwards.

2023-06-14 00:29 UTC, closed without merging