Bluetooth: Add missing dependency for PAST feature
zephyrproject-rtos/zephyr pull request #56473
Opened 2023-04-03 13:11 UTC by Thalley

The PAST sender needs to support periodic advertising and the PAST receiver needs to support periodic advertising sync.

2023-04-03 13:17 UTC, hermabe requested changes

2023-04-03 13:17 UTC, hermabe commented on subsys/bluetooth/Kconfig
> +	depends on BT_PER_ADV && (!BT_CTLR || BT_CTLR_SYNC_TRANSFER_SENDER_SUPPORT)
The PAST sender could be a sync as well.

2023-04-03 13:25 UTC, hermabe approved these changes

2023-04-04 12:30 UTC, carlescufi approved these changes

2023-04-04 12:31 UTC, merged