Extended ps
zephyrproject-rtos/zephyr pull request #56591
Opened 2023-04-06 06:54 UTC by ajayparida

Support for listen interval and extened power save configuration from shell.

2023-04-06 06:56 UTC, ajayparida commented
@krish2718 @rado17 @sachinthegreen

2023-04-06 07:14 UTC, rlubos reviewed
I think we need to start to document those configs more thoroughly. What does "Extended PS" stand for (I'm guessing it's some abbreviaton for power save, but I'd rather know than guess). What's listen interval related to?

2023-04-06 07:47 UTC, rado17 requested changes

2023-04-06 07:47 UTC, rado17 commented on include/zephyr/net/wifi_mgmt.h
> +	NET_REQUEST_WIFI_CMD_LISTEN_INTERVAL,
NET_REQUEST_WIFI_CMD_LISTEN_INTERVAL should come after NET_REQUEST_WIFI_CMD_MAX. I see that this has been corrected in the next commit but please correct it in this commit as well

2023-04-06 08:12 UTC, ajayparida commented
> I think we need to start to document those configs more thoroughly. What does "Extended PS" stand for (I'm guessing it's some abbreviaton for power save, but I'd rather know than guess). What's listen interval related to?

Thanks, updated info related to configs.

2023-04-06 08:14 UTC, rado17 commented on include/zephyr/net/wifi_mgmt.h
> +	NET_REQUEST_WIFI_CMD_LISTEN_INTERVAL,
> NET_REQUEST_WIFI_CMD_LISTEN_INTERVAL should come after NET_REQUEST_WIFI_CMD_MAX. I see that this has been corrected in the next commit but please correct it in this commit as well

correction:  NET_REQUEST_WIFI_CMD_LISTEN_INTERVAL should come before NET_REQUEST_WIFI_CMD_MAX.

2023-04-06 08:40 UTC, chaitu-tk requested changes
We can combine all power save parameters to either `set_power_save` if applicable before/after association or `set_power_save_mode` if applicable only before association, we can get rid of

* set_power_save_timeout
* Listen interval
* extended PS

Instead keep only below

* set_power_save - before/after
   - on/off
* set_power_save_mode
   - mode
   - listen_interval
   - timeout (need to  document the meaning, currently this is too vague)

2023-04-06 08:40 UTC, chaitu-tk commented on subsys/net/l2/wifi/wifi_mgmt.c
> +static int wifi_set_listen_intvl(uint32_t mgmt_request, struct net_if *iface,
Please use full interval, I don't think we are saving anything with the short form.

2023-04-06 14:37 UTC, ajayparida commented
> We can combine all power save parameters to either `set_power_save` if applicable before/after association or `set_power_save_mode` if applicable only before association, we can get rid of
> 
> * set_power_save_timeout
> * Listen interval
> * extended PS
> 
> Instead keep only below
> 
> * set_power_save - before/after
>   
>   * on/off
> * set_power_save_mode (we could even rename this to set_power_save_preassoc to clarify the meaning)
>   
>   * mode
>   * listen_interval
>   * timeout (need to  document the meaning, currently this is too vague)

Will the below be sufficient
    - keep listen_interval & timeout configuration separate (as existing now)
And pass the other command rleated to power save as below
-  set_power_save_mode  legacy/wmm/extended_ps  on/off

As per UMAC team the "timeout" is only preassoc stuff others can be configured at any point of time, though configured value may take effect after connection establishment.

2023-04-25 07:15 UTC, ajayparida commented
Changes related to this PR now being handled in https://github.com/zephyrproject-rtos/zephyr/pull/57116

2023-04-25 07:15 UTC, closed without merging