Bluetooth: Audio: Add TMAS and two TMAP samples
zephyrproject-rtos/zephyr pull request #56686
Opened 2023-04-10 14:14 UTC by sp3030

Add implementation of the Telephony and Media Audio Service, as well as two sample applications.

tmap_central reflects a smartphone implementing the Unicast Media Sender and Call Gateway TMAP roles.

tmap_peripheral reflects an earbud implementing the Unicast Media Receiver and Call Terminal TMAP roles.

Upon connection, tmap_central starts an audio stream using CAP Initiator APIs.

CCP, MCP and VCP are discovered and used to send example commands.

Future improvements: 2-earbud support, add TMAP Broadcast roles, update with new CAP Acceptor/Commander APIs as they become available

2023-04-12 09:05 UTC, Thalley requested changes
I think this is a quite good start for the implementation. I've added some comments that should be addressed

2023-04-12 09:05 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/tmas_test.c
> +	(BT_TMAP_ROLE_UNICAST_MEDIA_RECEIVER) | (BT_TMAP_ROLE_CALL_TERMINAL), 0x00, /* TMAP Role */
```suggestion
	BT_TMAP_ROLE_UNICAST_MEDIA_RECEIVER | BT_TMAP_ROLE_CALL_TERMINAL, 0x00, /* TMAP Role */
```

2023-04-12 09:05 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/tmas_test.c
> +	bt_tmas_register_role((BT_TMAP_ROLE_CALL_TERMINAL) | (BT_TMAP_ROLE_UNICAST_MEDIA_RECEIVER));
```suggestion
	}
	
	bt_tmas_register_role(BT_TMAP_ROLE_CALL_TERMINAL | BT_TMAP_ROLE_UNICAST_MEDIA_RECEIVER);
```

2023-04-12 09:05 UTC, Thalley commented on tests/bsim/bluetooth/audio/test_scripts/tmas.sh
The BSIM shell scripts were recently refactored to not define the `Execute` function etc. but rather use a common shell file. Please have a look at the other test scripts and modify this to be similar to them

2023-04-12 10:37 UTC, sp3030 commented
> I think this is a quite good start for the implementation. I've added some comments that should be addressed

Thank you very much for the feedback, will get right on it.

2023-05-01 10:36 UTC, Thalley requested changes

2023-05-01 10:36 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> +void bt_tmap_register_role(enum bt_tmap_role role);
Duplicate of `bt_tmap_register`?

2023-05-01 10:36 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> + * @param role TMAP role of the device
Should better indicate that `role` can contain multiple `bt_tmap_role` values (i.e. that it is a bitfield)

2023-05-01 10:36 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> +	 *  @param err      0 if success, -EINVAL if TMAS was not discovered.
```suggestion
	 *  @param role     Peer TMAP role(s).
	 *  @param conn     Pointer to the connection
	 *  @param err      0 if success, -EINVAL if TMAS was not discovered.
```

2023-05-01 10:36 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> +	 *  @param err      0 if success, -EINVAL if TMAS was not discovered.
`EOPNOTSUPP` would also be better than `EINVAL` if we really want to return a errno value here. Alternatively we can just return the ATT error from the server

2023-05-01 10:36 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> +	void (*tmap_discovery_complete)(enum bt_tmap_role role, struct bt_conn *conn, int err);
```suggestion
	void (*discovery_complete)(enum bt_tmap_role role, struct bt_conn *conn, int err);
```

2023-05-01 10:36 UTC, Thalley commented on samples/bluetooth/tmap_central/src/cap_initiator.c
> +										CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT];
Some indentation went wrong here. Please note that tabs in Zephyr are 8 spaces :)

2023-05-01 10:36 UTC, Thalley commented on samples/bluetooth/tmap_central/src/cap_initiator.c
> +										CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT];
This seems to be a general issue in this commit :)

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/Kconfig.tmap
> +	  Enabling this will enable TMAP.
Should we add dependencies for the other profiles here? 
A TMAP device needs to be either a CAP Initiator or a CAP Acceptor, right?

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +		if (tmas_found == false) {
```suggestion
		if (!tmas_found) {
```

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +				cb->tmap_discovery_complete(0, conn, -EINVAL);
Suggest to either use `BT_ATT_ERR_ATTRIBUTE_NOT_FOUND` or `EOPNOTSUPP` instead of `EINVAL`

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +		tmas_found = false;
```suggestion
		}
		
		tmas_found = false;
```

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +static struct bt_gatt_read_params read_params;
If we want to support multiple discovery procedures in parallel (i.e. for multiple connections), then these values need to be in an array of some sort.

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +	return BT_GATT_ITER_STOP;
```suggestion
	}
	
	return BT_GATT_ITER_STOP;
```

2023-05-01 10:36 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +	enum bt_tmap_role peer_role = sys_get_le16(data);
We should not assume that the size of an `enum` can always hold a 16-bit value. 

Ideally we do something like 
```
uint16_t peer_role = sys_get_le16(data);

if (!peer_role_is_valid) {
	if (cb->tmap_discovery_complete) {
		cb->tmap_discovery_complete(0, conn, BT_ATT_ERR_VALUE_NOT_ALLOWED);
	}
} else {
	if (cb->tmap_discovery_complete) {
		cb->tmap_discovery_complete((enum bt_tmap_role)peer_role, conn, 0);
	}
}
```

We also should verify the length before we call `sys_get_le16` and should also check that `err == BT_ATT_ERR_SUCCESS` before attempting to extract any data

2023-05-01 10:36 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/main.c
> +	test_tmap_client_install,
Suggest to rename these to `tmap_central` and `tmap_peripheral` or `tmap_client` and `tmap_server`

2023-05-01 10:36 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/tmap_client_test.c
> +	if (!(sys_le16_to_cpu(peer_tmap_role) & BT_TMAP_ROLE_UMR)) {
```suggestion
	if (!(peer_tmap_role & BT_TMAP_ROLE_UMR)) {
```

2023-05-01 10:36 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/tmap_client_test.c
> +};
Can use the commonly defined `connected` callback and flag

2023-05-01 10:36 UTC, Thalley commented on tests/bsim/bluetooth/audio/src/tmap_test.c
> +};
Can use the common callback and flag (see the other tests)

2023-05-04 11:24 UTC, Thalley requested changes
A few comments. 

Please also follow the Contribution Workflow as defined by https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow and squash the commits to a single commit (instead of adding "fixing" commits). 

Could also consider splitting this PR in the following commits:
1) Add TMAP implementation
2) Add TMAP tests
3) Add TMAP samples

2023-05-04 11:24 UTC, Thalley commented on include/zephyr/bluetooth/audio/tmap.h
> + * @brief Register one or multiple TMAP roles dynamically.
```suggestion
 * @brief Set one or multiple TMAP roles dynamically.
```

2023-05-04 11:24 UTC, Thalley commented on samples/bluetooth/tmap_central/src/cap_initiator.c
> +			CONFIG_BT_ISO_TX_MTU + BT_ISO_CHAN_SEND_RESERVE, 8, NULL);
There still seems to be some general issues with the indentation :) Tabs are 8 spaces, and code should be indented to match previous lines (e.g. by `(`)

2023-05-04 11:24 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +		}
If `peer_role` is `0xFFFF` then it's an invalid role, but isn't caught by this check :)

2023-05-04 11:24 UTC, Thalley commented on subsys/bluetooth/audio/tmap.c
> +	uint16_t peer_role = sys_get_le16(data);
Declare `peer_role` at top of scope and do

```suggestion
	if (length != sizeof(peer_role)) {
		if (cb->discovery_complete) {
			cb->discovery_complete(0, conn, BT_ATT_ERR_INVALID_ATTRIBUTE_LEN);
		}

		return BT_GATT_ITER_STOP;
	}

	/* Extract the TMAP role of the peer and inform application fo the value found */
	peer_role = sys_get_le16(data);
```

2023-05-05 07:07 UTC, Thalley approved these changes
I don't have any other blocking comments - Nice work!

2023-05-24 12:18 UTC, MariuszSkamra approved these changes
LGTM

2023-05-24 14:39 UTC, merged