doc: Bluetooth: Mesh: update proxy solicitation docs
zephyrproject-rtos/zephyr pull request #56711
Opened 2023-04-11 09:16 UTC by akredalen

Updated related docs. Small fix in mesh/Kconfig and shell.rst.

2023-04-11 09:23 UTC, jhedberg approved these changes, later dismissed

2023-04-12 10:42 UTC, PavelVPV requested changes
I think it would be good if we could elaborate the Proxy Solicitation feature in the documentation a little bit more by explaining the idea behind it (that any Proxy Client can solicit a Proxy Server to establish GATT connection at any time), the additionally required features (Private Node Identity), where the related models are instantiated (some can only be instantiated on Configuration Manager (On-Demand Private Proxy Client), some on any devices (Solicitation PDU RPL Client)), how Solicitation PDU is generated and how the solicitation replay protection list works (how and when entries are stored). 

No need to explain in detail how everything works, maybe one-two sentences per each aspect of the feature, but this should give enough information to a user to help building a general overview of the feature.

We have a page related to Proxy feature: https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/connectivity/bluetooth/api/mesh/proxy.rst. Probably, most of this information can be explained there. Models' specific details can be described in the corresponding models pages. Not sure if we need `od.rst` and `srpl.rst` after this, but lets see this once we add more description.

2023-04-12 10:42 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/srpl_cli.rst
> +                                &start_rsp, &len_rsp);
Same as for On-Demand Private Proxy Client model. I'm not sure if we need such level of details. A user should be able to perceive this from the API description. If we have bad API description, we should fix it there.

2023-04-12 10:42 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/od_cli.rst
> +      bt_mesh_od_priv_proxy_cli_set(&my_ctx, new_val, &state_rsp);
I'm not sure if we need such level of details. For such kind of functionality, it should be clear how to use the API. I think snippets are useful for more complex scenarios.

2023-04-13 12:55 UTC, alxelax reviewed
LGTM, but Pavel's comments seem fair enough. When they will be fixed, I'll approve also.

2023-04-24 21:46 UTC, akredalen commented on doc/connectivity/bluetooth/api/mesh/od_cli.rst
> +and to adjust message transmission timeout. The State defines how long a node will advertise Mesh Proxy Service with
Should it be mentioned as a possible configuration, or is it unnecessary for this documentation? See the subsection further down.

2023-04-26 07:31 UTC, alxelax commented
Hi @mia-ko, could you please review this PR?

2023-04-26 10:16 UTC, PavelVPV requested changes

2023-04-27 12:25 UTC, PavelVPV requested changes

2023-04-27 12:25 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +randomizing the beacon input data. By advertising with this set of identification types,
Sentence `Private Beacons provide privacy by periodically randomizing the beacon input data.` is belongs to Private Beacons, but here we don't send beacons. The next sentence explains the need for Private types so I think this sentence can be removed.

2023-04-27 12:25 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +Mesh Private beacons must be supported by the node.
I think the last 2 sentences aren't needed. What needs to be supported by the node and what Private Proxy gives is explained above. This is more like a spec statement, but for a user to enable the support of this feature it is enough to instantiate Private Beacon Server model and enable GATT Proxy support (which is explained in the section above).
```
This functionality is called Private Proxy. For the Private Proxy functionality to be supported, the Proxy feature, Private Network Identity advertising, and Mesh Private beacons must be supported by the node.
```

2023-04-27 12:25 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +A node supporting the :ref:`bluetooth_mesh_models_priv_beacon_srv` can advertise with
```suggestion
A node supporting the Proxy feature and the :ref:`bluetooth_mesh_models_priv_beacon_srv` can advertise with
```

2023-04-27 13:59 UTC, PavelVPV reviewed
@mia-ko could you please have a look now?

2023-04-27 13:59 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +To solicit the device, a Proxy Client may send a solicitation PDU by calling the :func:`bt_mesh_proxy_solicit`.
```suggestion
To solicit the device, a legacy device should send a solicitation PDU by calling the :func:`bt_mesh_proxy_solicit`.
```

2023-04-27 13:59 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +and solicitation source (SSRC) pairs of valid Solicitation PDUs processed by the node.
```suggestion
and solicitation source (SSRC) pairs of valid Solicitation PDUs processed by the node.
The delay between updating the SRPL and storing the change to the persistent storage is defined by :kconfig:option:`CONFIG_BT_MESH_RPL_STORE_TIMEOUT`.
```

2023-04-27 13:59 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +advertisement can be configured by the On-Demand Private Proxy Server model.
Perhaps it should be client?
```suggestion
advertisement can be configured by the On-Demand Private Proxy client model.
```

2023-04-27 14:32 UTC, akredalen commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +the node is allowing its Proxy Client to connect to the network over GATT while maintaining the
"..the node is allowing its legacy device.." Is this correct? The legacy device is a potential node in a network, is it not? 
```suggestion
the legacy device is allowed to connect to the network over GATT while maintaining the
```

2023-04-27 14:37 UTC, PavelVPV commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +the node is allowing its Proxy Client to connect to the network over GATT while maintaining the
Ok, sounds weird. What about:
```
By advertising with this set of identification types, the node allows the legacy device to connect to the network over GATT while maintaining the privacy of the network.
```

2023-04-28 09:45 UTC, mia-ko requested changes

2023-04-28 09:45 UTC, mia-ko commented on doc/connectivity/bluetooth/api/mesh/srpl_srv.rst
> +The Solicitation PDU RPL Configuration Server model was introduced in the Bluetooth Mesh Profile
```suggestion
The Solicitation PDU RPL Configuration Server model was introduced in the Bluetooth Mesh Protocol
```

2023-04-28 09:45 UTC, mia-ko commented on doc/connectivity/bluetooth/api/mesh/srpl_srv.rst
> +successfully processed by a node, the SSRC field and SSEQ field of the message is stored in the node's SRPL.
```suggestion
The SRPL is used to reject Solicitation PDUs that are already processed by a node. When a valid Solicitation PDU message is
successfully processed by a node, the SSRC field and SSEQ field of the message are stored in the node's SRPL.
```

2023-04-28 09:45 UTC, mia-ko commented on doc/connectivity/bluetooth/api/mesh/srpl_srv.rst
> +a received Solicitation PDU is valid.
```suggestion
For the Solicitation PDU RPL Configuration Server model, the :kconfig:option:`CONFIG_BT_MESH_PROXY_SRPL_SIZE` option can be configured to set the size of the SRPL.
The SRPL is used to determine if a received Solicitation PDU is valid.
```

2023-04-28 12:32 UTC, akredalen commented on doc/connectivity/bluetooth/api/mesh/proxy.rst
> +A node that supports the Solicitation PDU RPL Configuration Client model can clear a section of the SRPL on the target by calling the :func:`bt_mesh_sol_pdu_rpl_clear`.
It is meant in a general sense :)

2023-04-28 13:00 UTC, alxelax approved these changes

2023-04-28 13:15 UTC, PavelVPV approved these changes

2023-04-28 18:37 UTC, merged