samples/tests: bluetooth: Remove qemu_cortex_m3
zephyrproject-rtos/zephyr pull request #56730
Opened 2023-04-11 14:46 UTC by galak

Remove qemu_cortex_m3 from various bluetooth tests and samples since they enable NVS which requires CONFIG_FLASH_PAGE_LAYOUT which is not supported on qemu_cortex_m3 since there is no flash driver.

We get build failures with the arm-clang compiler because nvs.c is referencing z_impl_flash_get_page_info_by_offs which does not exist.

Switch to qemu_x86 as the integration_platforms if it was qemu_cortex_m3 before.

2023-04-11 15:04 UTC, alxelax requested changes

2023-04-11 15:07 UTC, galak commented on tests/bluetooth/mesh_shell/testcase.yaml
> +    platform_allow: qemu_x86
removed the testcase.

2023-04-11 15:14 UTC, alxelax commented on tests/bluetooth/mesh_shell/testcase.yaml
> +    platform_allow: qemu_x86
sorry being nitpicking but `reduced_legacy.conf` should be removed too

2023-04-11 15:41 UTC, galak commented on tests/bluetooth/mesh_shell/testcase.yaml
> +    platform_allow: qemu_x86
oops, thanks for catching that.  Removed.

2023-04-11 20:21 UTC, alxelax approved these changes

2023-04-12 06:52 UTC, jhedberg approved these changes

2023-04-12 07:01 UTC, merged