toolchain: common: iterable sections: Add generic type macros
zephyrproject-rtos/zephyr pull request #56868
Opened 2023-04-14 19:36 UTC by galak

Add a set of macros that can be utilized for any type and redefine the struct macros to utilize these macros.  While the majority of uses for iterable sections are for structs, there are some cases where the elements of the section might be a union or some other type.

Also added <STRUCT|TYPE>_SECTION_<START|END>_EXTERN helper macros to give a common means to handle setting externs in rare case they are needed.

2023-04-15 09:43 UTC, martinjaeger requested changes
Thanks, that's a very useful addition.

It looks like `out_type` and `secname` refer to the same thing. I would suggest to replace `out_type` with `secname` (or `sec_name`) everywhere to avoid confusion.

2023-04-15 13:57 UTC, andyross approved these changes, later dismissed

2023-04-15 15:01 UTC, galak commented on include/zephyr/toolchain/common.h
> +	__in_section(_##section_prefix, static, section_postfix) __used __noasan
We can change the prefix, but not the postfix.  Thare are cases that the postfix is more than just the variable name (see shell.h).

2023-04-15 16:00 UTC, martinjaeger commented on include/zephyr/toolchain/common.h
> +	__in_section(_##section_prefix, static, section_postfix) __used __noasan
Maybe I misunderstand, but I see the new `TYPE_SECTION_ITERABLE` only being used for below macro, where `varname` is equal to `section_postfix`.

```C
#define STRUCT_SECTION_ITERABLE_ALTERNATE(secname, struct_type, varname) \
	TYPE_SECTION_ITERABLE(struct struct_type, varname, secname, varname)
```

Or are you planning to use `TYPE_SECTION_ITERABLE` with `section_postfix` different than `varname` in the future?

2023-04-15 17:38 UTC, galak commented on include/zephyr/toolchain/common.h
> +	__in_section(_##section_prefix, static, section_postfix) __used __noasan
Yeah, plan to rework various places to use this.  So for example in shell.h:

We will have something like:
```

#define Z_SHELL_UNDERSCORE(x) _##x
#define Z_SHELL_SUBCMD_NAME(...) \
        UTIL_CAT(shell_subcmds, MACRO_MAP_CAT(Z_SHELL_UNDERSCORE, __VA_ARGS__))
#define Z_SHELL_SUBCMD_SECTION_TAG(...) MACRO_MAP_CAT(Z_SHELL_UNDERSCORE, __VA_ARGS__)
#define Z_SHELL_SUBCMD_SET_SECTION_TAG(x) \
        Z_SHELL_SUBCMD_SECTION_TAG(NUM_VA_ARGS_LESS_1 x, __DEBRACKET x)
#define Z_SHELL_SUBCMD_ADD_SECTION_TAG(x, y) \
        Z_SHELL_SUBCMD_SECTION_TAG(NUM_VA_ARGS_LESS_1 x, __DEBRACKET x, y)

#define SHELL_SUBCMD_SET_CREATE(_name, _parent) \
       static const TYPE_SECTION_ITERABLE(struct shell_static_entry, _name, shell_subcmds, \
                                         Z_SHELL_SUBCMD_SET_SECTION_TAG(_parent))


#define SHELL_SUBCMD_COND_ADD(_flag, _parent, _syntax, _subcmd, _help, _handler, \
                           _mand, _opt) \
        COND_CODE_1(_flag, \
                (static const TYPE_SECTION_ITERABLE(struct shell_static_entry, \
                                        Z_SHELL_SUBCMD_NAME(__DEBRACKET _parent, _syntax), \
                                        shell_subcmds, \
                                        Z_SHELL_SUBCMD_ADD_SECTION_TAG(_parent, _syntax)) = \
...
```

2023-04-15 17:39 UTC, galak commented on include/zephyr/toolchain/common.h
> +	__in_section(_##section_prefix, static, section_postfix) __used __noasan
You can see varname is one thing and section_postfix is another.

2023-04-15 18:46 UTC, martinjaeger commented on include/zephyr/toolchain/common.h
> +	__in_section(_##section_prefix, static, section_postfix) __used __noasan
Ok, now I see.

2023-04-15 18:46 UTC, martinjaeger approved these changes

2023-04-16 03:05 UTC, cfriedt approved these changes

2023-04-17 08:19 UTC, merged