IPC: rpmsg: Changed checking endpoints on close
zephyrproject-rtos/zephyr pull request #57100
Opened 2023-04-20 21:01 UTC by pawelosyp

Initially this change was part of #56113 and there discussion about that started.
This change is due to situation I have got in project - network core creates two endpoints and app core creates only one. In that situation there are two endpoints, both of them have names and one of them is bounded - unused one has name.
So checking bounded by name returned false result in case of unused endpoint.

2023-04-21 06:49 UTC, carlocaione requested changes
You need to change https://github.com/zephyrproject-rtos/zephyr/blob/c2ec3d49cd2f952e0ead3dc7415d6cc9845a0db8/include/zephyr/ipc/ipc_service.h#L223-L225

Also please add an entry in the changelog file for this

2023-04-21 09:00 UTC, carlocaione requested changes

2023-04-21 09:00 UTC, carlocaione commented on include/zephyr/ipc/ipc_service.h
> + *  is called (the unused one can be left).
```suggestion
 *  is called.
```

2023-04-21 09:00 UTC, carlocaione commented on include/zephyr/ipc/ipc_service.h
> + *  is called (the unused one can be left).
Please add a note about this in `doc/releases/release-notes-3.4.rst`. It is an API change, so better document it.

2023-04-21 09:05 UTC, hubertmis approved these changes, later dismissed

2023-04-21 10:29 UTC, carlocaione requested changes

2023-04-21 10:29 UTC, carlocaione commented on doc/releases/release-notes-3.4.rst
> +  an IPC instance. The new one checks by bounded flag.
This is in the wrong section. Please add a new `IPC` section under the `Subsystems` section and reword like:
```
:c:func:`ipc_service_close_instance` now only acts on bounded endpoints.
```

2023-04-21 12:00 UTC, carlocaione approved these changes

2023-04-24 06:35 UTC, emob-nordic approved these changes

2023-04-24 13:12 UTC, hubertmis approved these changes

2023-04-24 13:45 UTC, merged