Support for Listen interval based ps
zephyrproject-rtos/zephyr pull request #57116
Opened 2023-04-21 10:03 UTC by ajayparida

@sachinthegree @krish2718 @rado17

2023-04-21 11:32 UTC, krish2718 requested changes

2023-04-21 11:32 UTC, krish2718 commented on include/zephyr/net/wifi_mgmt.h
> +struct wifi_ps_wake_interval_params {
This is not an interval, its wakeup mode

2023-04-21 11:32 UTC, krish2718 commented on include/zephyr/net/wifi_mgmt.h
> +	unsigned short listen_interval;
As discussed earlier, having a OP for each param is an overkill, can you please group these parameters and simplify the ops?

2023-04-21 11:32 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_mgmt.c
> +		return -ENOTSUP;
Shouldn't this be EIO or something?

2023-04-21 11:32 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		     "<dtim> : Set ps wake interval to Dtim\n"
```suggestion
		     "<dtim> : Set PS wake up period to DTIM interval\n"
```

2023-04-21 11:32 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		     "<listen_interval> : Set ps wake interval to listen interval",
```suggestion
		     "<listen_interval> : Set PS wake up period to listen interval",
```

2023-04-24 18:26 UTC, krish2718 requested changes
Overall at the design level we have two options: 

1. Treat each parameter as a separate configuration with its own structure, shell command and an API
2. Group parameters as suggested pre-assoc and anytime

The latest changes seem to do a hybrid, in which case we can simply make it an union of parameters as we only seem to allow individual parameter configuration. 

We really need to fix the design to avoid code churn in review.

@rlubos  any thoughts?

2023-04-24 18:26 UTC, krish2718 commented on include/zephyr/net/wifi_mgmt.h
> +	int ps_flag;
This should be named `oper` or `subcmd`, my earlier review comment to aggregate commands was to simplify the configuration, but this `subcmd` basically re-introduces the sub-commands but using a single structure. Also, the division of parameters doesn't looks correct:

* `num_twt_flows` is in `wifi_ps_params` but `twt_flows` is in `wifi_ps_config`
* `wifi_ps_config` and `wifi_ps_params` are synonymous
* `enabled` and `timeout_ms` in `wifi_ps_params` are dynamic parameters i.e., can be called at any time, but rest of them are only pre-association (mode, listen_interval)

I would suggest below split:

```
/* Static - should be configured before association and cannot be changed during lifetime */
struct wifi_ps_static_config {
   enum wifi_ps_mode mode;
   unsigned short listen_interval;
};

/* Dynamic PS config - Can be send any time, before or after association, and can be changed anytime */
struct wifi_ps_dynamic_config {
  enum wifi_ps enabled;
  unsigned int timeout_ms;
  enum wifi_ps_wakeup_mode wakeup_mode;   
  char num_twt_flows;
  struct wifi_twt_flow_info twt_flows[WIFI_MAX_TWT_FLOWS];
};
```

We could separate out TWT if that makes handling easier.

2023-04-24 18:26 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +	params.ps_flag = WIFI_PS_PARAM_LISTEN_INTERVAL;
This `subcmd` setting should be in wifi_mgmt.c as its a direct match b/w `NET_REQUEST_WIFI_LISTEN_INTERVAL` and is redundant to set both

2023-04-24 18:26 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +	if (net_mgmt(NET_REQUEST_WIFI_LISTEN_INTERVAL, iface, &params, sizeof(params))) {
`NET_REQUEST_WIFI_LISTEN_INTERVAL` where is this defined, I cannot seem to find it anywhere?

2023-04-25 09:24 UTC, krish2718 commented
> > Overall at the design level we have two options:
> > 
> > 1. Treat each parameter as a separate configuration with its own structure, shell command and an API
> > 2. Group parameters as suggested pre-assoc and anytime
> > 
> > The latest changes seem to do a hybrid, in which case we can simply make it an union of parameters as we only seem to allow individual parameter configuration.
> > We really need to fix the design to avoid code churn in review.
> > @rlubos any thoughts?
> 
> I'm not sure if I get the full context (it would really help if you started to provide the overall goal of the PR in the description) but when it comes to radio configuration, the device we have in 15.4 driver seems to work fine.

This PR is adding many OPs to configure individual params, so, was proposing a way to aggregate these for easier understanding and maintenance.

> 
> Instead of multiplying APIs/grouping configs we have single API function to set a config (https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/net/ieee802154_radio.h#L356) and each config is represented with an enum value. The config value is provided as an union (https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/net/ieee802154_radio.h#L231).

This looks reasonable, and is close to what the current changes in the PR do, so, we can proceed with that, thanks.

2023-04-25 17:02 UTC, krish2718 requested changes

2023-04-25 17:02 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +	long interval = 10;
Do we need a random default here?

2023-04-25 17:02 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		shell_fprintf(sh, SHELL_WARNING, "Setting ps wake period to %s failed\n",
```suggestion
		shell_fprintf(sh, SHELL_WARNING, "Setting ps wake up mode to %s failed\n",
```

2023-04-25 17:02 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		shell_fprintf(sh, SHELL_NORMAL, "PS wake up period: %s\n",
```suggestion
		shell_fprintf(sh, SHELL_NORMAL, "PS wake up mode: %s\n",
```

2023-04-25 17:02 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		     "<dtim> : Set PS wake up period to DTIM interval\n"
```suggestion
		     "<dtim> : Set PS wake up mode to DTIM interval\n"
```

2023-04-27 07:53 UTC, rado17 approved these changes, later dismissed

2023-04-28 09:29 UTC, krish2718 requested changes

2023-04-28 09:29 UTC, krish2718 commented on include/zephyr/net/wifi.h
> +#define WIFI_LISTEN_INTERVAL_MIN 3
As this is generic, we should follow protocol limits, any HW specific limits should be enforced by the underlying driver.

2023-05-04 07:46 UTC, rado17 submitted a review, later dismissed

2023-05-04 07:50 UTC, krish2718 submitted a review, later dismissed

2023-05-05 07:25 UTC, krish2718 approved these changes, later dismissed
Nits.

2023-05-05 07:25 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		      "<val> - Listen interval in the range of <3-65535>",
This still shows 3

2023-05-05 07:25 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		      "<val> - Power save inactivity timer(in ms)",
Use either PS or Power save but consistently.

2023-05-05 07:25 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +			      "Setting ps wake up mode to %s failed..Reason :%s\n",
PS

2023-05-05 10:01 UTC, ajayparida commented on subsys/net/l2/wifi/wifi_shell.c
> +		      "<val> - Power save inactivity timer(in ms)",
used PS

2023-05-05 11:01 UTC, krish2718 approved these changes

2023-05-08 08:37 UTC, sachinthegreen approved these changes

2023-05-08 11:49 UTC, rlubos approved these changes

2023-05-09 01:41 UTC, ajayparida commented
@jukkar

2023-05-09 06:45 UTC, sachinthegreen approved these changes

2023-05-09 07:35 UTC, krish2718 approved these changes

2023-05-09 11:51 UTC, jukkar approved these changes
LGTM.

I noticed that the wifi shell uses this pattern
```
struct net_if *iface = net_if_get_default();
```
This can be a bit problematic as it probably only works reliably if there is one network interface in the system.

2023-05-09 12:12 UTC, krish2718 commented
> LGTM.
> 
> I noticed that the wifi shell uses this pattern
> 
> ```
> struct net_if *iface = net_if_get_default();
> ```
> 
> This can be a bit problematic as it probably only works reliably if there is one network interface in the system.

Yes, definitely, it crashed for multi-VIF (netusb, 802.15.4). I have been meaning to address this, in downstream we have worked around by always setting Wi-Fi as default interface.

2023-05-09 12:27 UTC, jukkar commented
> I have been meaning to address this, in downstream we have worked around by always setting Wi-Fi as default interface

That is certainly possible but I would also recommend that user could give the network interface index as a parameter in various wifi commands (for example "-i <iface index>" or similar)

2023-05-09 13:04 UTC, merged