cmake: compiler: add double promotion warning
zephyrproject-rtos/zephyr pull request #57154
Opened 2023-04-22 21:28 UTC by XenuIsWatching

Too many times, code is pushed that includes floats that really becomes doubles and C implicit promotion rules will want to make floats into doubles very easily. As zephyr primarily targets low-end process that may not have a double precision floating point unit, enable this flag globally for now.

2023-04-25 12:59 UTC, tejlmand submitted a review, later dismissed

2023-04-25 22:28 UTC, keith-packard requested changes, later dismissed
Yes, we definitely want this warning enabled by default. Building picolibc with -Werror=double-promotion yielded dozens of fixes and made the resulting library free of double operations when using only float values.

However, fixes to make this work should probably land in separate PR/PRs, but having them appear here first so that we can let CI check to make sure they're sufficient seems like a good plan. Should we mark this as DNM until then?

Once the patches that fix the promotion bugs have landed, I'd be happy to approve this.

2023-04-26 01:29 UTC, XenuIsWatching commented
> Yes, we definitely want this warning enabled by default. Building picolibc with -Werror=double-promotion yielded dozens of fixes and made the resulting library free of double operations when using only float values.
> 
> However, fixes to make this work should probably land in separate PR/PRs, but having them appear here first so that we can let CI check to make sure they're sufficient seems like a good plan. Should we mark this as DNM until then?
> 
> Once the patches that fix the promotion bugs have landed, I'd be happy to approve this.

Agreed, it should be marked as DNM until all the little double promotion bugs are squashed in seperate PRs.

My only worry is with modules that have double-promotion issues, that's what stopped me the last time I try to integrated this flag by default to in zephyr

2023-04-26 02:23 UTC, keith-packard commented
> My only worry is with modules that have double-promotion issues, that's what stopped me the last time I try to integrated this flag by default to in zephyr, but some may of been fixed since then.... #38958

Yeah, it's tedious but there is a pretty reasonable process. Post a PR to the module repo, then post a PR to the zephyr repo that pulls the module branch. It's documented somewhere even ...

2023-04-26 07:46 UTC, XenuIsWatching commented
It appears CMSIS-DSP is getting dinged as well, but these were fixed in https://github.com/ARM-software/CMSIS-DSP/commit/5fac45cc967f2f6b8592856a32ce04fae2245143

Those should be resolved in the cmsis-dsp, cmsis-nn, tflite-micro update https://github.com/zephyrproject-rtos/zephyr/pull/56957

2023-04-26 13:31 UTC, evgeniy-paltsev submitted a review, later dismissed
ARC MWDT changes LGTM.

2023-04-26 23:02 UTC, XenuIsWatching commented
There two more modules, one is an ST audio library and another the hal_wurthelektronik.

both of these appear to be tied to upstream repos 

```
FAILED: modules/st/CMakeFiles/..__modules__hal__st.dir/audio/microphone/OpenPDMFilter.c.obj
ccache /opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DCORE_CM4 -DHSE_VALUE=16000000 -DKERNEL -DSTM32F412Cx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D__PROGRAM_START -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/96b_argonkey/samples/boards/96b_argonkey/microphone/sample.board.96b_argonkey.microphone/zephyr/include/generated -I/__w/zephyr/zephyr/soc/arm/st_stm32/stm32f4 -I/__w/zephyr/zephyr/drivers -I/__w/zephyr/zephyr/soc/arm/st_stm32/common -I/__w/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/__w/zephyr/modules/hal/st/audio/microphone -I/__w/zephyr/modules/hal/stm32/stm32cube/stm32f4xx/soc -I/__w/zephyr/modules/hal/stm32/stm32cube/stm32f4xx/drivers/include -I/__w/zephyr/modules/hal/stm32/stm32cube/stm32f4xx/drivers/include/Legacy -I/__w/zephyr/modules/hal/stm32/stm32cube/common_ll/include -isystem /__w/zephyr/zephyr/lib/libc/minimal/include -isystem /opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include -isystem /opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed -fno-strict-aliasing -Werror -Os -imacros /__w/zephyr/zephyr/twister-out/96b_argonkey/samples/boards/96b_argonkey/microphone/sample.board.96b_argonkey.microphone/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs --sysroot=/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/samples/boards/96b_argonkey/microphone=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT modules/st/CMakeFiles/..__modules__hal__st.dir/audio/microphone/OpenPDMFilter.c.obj -MF modules/st/CMakeFiles/..__modules__hal__st.dir/audio/microphone/OpenPDMFilter.c.obj.d -o modules/st/CMakeFiles/..__modules__hal__st.dir/audio/microphone/OpenPDMFilter.c.obj -c /__w/zephyr/modules/hal/st/audio/microphone/OpenPDMFilter.c
/__w/zephyr/modules/hal/st/audio/microphone/OpenPDMFilter.c: In function 'Open_PDM_Filter_Init':
/__w/zephyr/modules/hal/st/audio/microphone/OpenPDMFilter.c:180:88: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
  180 |   Param->LP_ALFA = (Param->LP_HZ != 0 ? (uint16_t) (Param->LP_HZ * 256 / (Param->LP_HZ + Param->Fs / (2 * 3.14159))) : 0);
      |                                                                                        ^
/__w/zephyr/modules/hal/st/audio/microphone/OpenPDMFilter.c:180:72: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
  180 |   Param->LP_ALFA = (Param->LP_HZ != 0 ? (uint16_t) (Param->LP_HZ * 256 / (Param->LP_HZ + Param->Fs / (2 * 3.14159))) : 0);
      |                                                                        ^
/__w/zephyr/modules/hal/st/audio/microphone/OpenPDMFilter.c:181:84: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
  181 |   Param->HP_ALFA = (Param->HP_HZ != 0 ? (uint16_t) (Param->Fs * 256 / (2 * 3.14159 * Param->HP_HZ + Param->Fs)) : 0);
      |                                                                                    ^
cc1: all warnings being treated as errors
```



```
[38/463] Building C object zephyr/CMakeFiles/zephyr.dir/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01/WSEN_PDUS_25131308XXX01.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01/WSEN_PDUS_25131308XXX01.c.obj
ccache /usr/lib/llvm-16/bin/clang -DKERNEL -D_POSIX_C_SOURCE=200809 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/kernel/include -I/__w/zephyr/zephyr/arch/posix/include -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/native_posix/tests/drivers/build_all/sensor/sensors.build.trigger.own/zephyr/include/generated -I/__w/zephyr/zephyr/soc/posix/inf_clock -I/__w/zephyr/zephyr/boards/posix/native_posix -I/__w/zephyr/zephyr/subsys/testsuite/include -I/__w/zephyr/modules/hal/st/sensor/vl53l0x/api/core/inc -I/__w/zephyr/zephyr/drivers/sensor/vl53l0x -I/__w/zephyr/modules/hal/st/sensor/vl53l1x/api/core/inc -I/__w/zephyr/zephyr/drivers/sensor/vl53l1x -I/__w/zephyr/modules/hal/st/sensor/stmemsc/hts221_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/i3g4250d_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/iis2dh_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/iis2dlpc_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/iis2iclx_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/iis2mdc_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/iis3dhhc_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/ism330dhcx_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/lis2ds12_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/lis2dw12_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/lis2mdl_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/lps22hh_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/lsm6dso_STdC/driver -I/__w/zephyr/modules/hal/st/sensor/stmemsc/stts751_STdC/driver -I/__w/zephyr/modules/hal/wurthelektronik/sensors/. -I/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK -I/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_HIDS_2523020210001 -I/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PADS_2511020213301 -I/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01 -I/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_TIDS_2521020222501 -fno-strict-aliasing -Werror -Os -imacros /__w/zephyr/zephyr/twister-out/native_posix/tests/drivers/build_all/sensor/sensors.build.trigger.own/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fcolor-diagnostics --config /__w/zephyr/zephyr/cmake/toolchain/llvm/clang.cfg -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-unused-but-set-variable -Wno-typedef-redefinition -Wno-deprecated-non-prototype -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wno-sometimes-uninitialized -Wno-shift-overflow -Wno-missing-braces -Wno-self-assign -Wno-address-of-packed-member -Wno-unused-function -Wno-initializer-overrides -Wno-section -Wno-unknown-warning-option -Wno-unused-variable -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -Wno-vla -fmacro-prefix-map=/__w/zephyr/zephyr/tests/drivers/build_all/sensor=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -m32 -include /__w/zephyr/zephyr/arch/posix/include/posix_cheats.h -std=c11 -MD -MT zephyr/CMakeFiles/zephyr.dir/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01/WSEN_PDUS_25131308XXX01.c.obj -MF zephyr/CMakeFiles/zephyr.dir/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01/WSEN_PDUS_25131308XXX01.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/__w/zephyr/modules/hal/wurthelektronik/sensors/WeSensorsSDK/WSEN_PDUS_25131308XXX01 [...]

2023-04-28 13:23 UTC, cfriedt commented
@XenuIsWatching - have you considered adding yourself as a collaborator to any areas in the `MAINTAINERS.yml` file? You've made a lot of really valuable additions all over the map, and we need more representation from Meta 😁 ♾️

2023-07-14 12:19 UTC, cfriedt commented
@nordic-krch - can you PTAL w.r.t. cbprintf errors?

2023-07-14 12:23 UTC, cfriedt commented
@erwango - assigned the related `hal_st` PR to you, PTAL

2023-07-14 12:24 UTC, cfriedt commented
@XenuIsWatching - please ping me if something isn't moving along for you.

2023-07-14 13:06 UTC, nordic-krch commented
@cfriedt I just starting one week vacation. I can take a look after that but were are those cbprintf errors? I could not find them when briefly inspected CI failures.

2023-07-14 13:33 UTC, cfriedt commented
> @cfriedt I just starting one week vacation. I can take a look after that but were are those cbprintf errors? I could not find them when briefly inspected CI failures.

Ah, no worries then - I'll see if I can pinpoint them. Enjoy! 🏖️🍹

2023-07-14 14:04 UTC, fabiobaltieri commented
@XenuIsWatching thanks for driving this effort! The CI run you are getting in this PR is going to be a different set of what runs on main after a push, so even if you can get a clear pass here then it may find more issues once it's merged and it'll likely have to be reverted. To test for that using the server CI you can use the https://github.com/zephyrproject-rtos/zephyr-testing/ repository, just make sure to match the CI push run wildcard `v*-branch`, then you can merge all your in-flight fixes locally and push it there, this is an example: https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-testing-branch. Not sure you have permissions to push there directly, but if not we can surely look into it.

2023-07-14 16:46 UTC, cfriedt commented
@XenuIsWatching - please update to resolve conflicts (`sqrtf.c` has been fixed in the linked PR)

2023-07-17 13:15 UTC, fabiobaltieri commented
> Apparently, I don't have permission to push directly to https://github.com/zephyrproject-rtos/zephyr-testing

There you go:
https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch
https://github.com/zephyrproject-rtos/zephyr-testing/runs/15095827873

Let me know if you need a rerun on an updated version.

2023-07-19 19:28 UTC, XenuIsWatching commented
> > Apparently, I don't have permission to push directly to https://github.com/zephyrproject-rtos/zephyr-testing
> 
> There you go: https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch https://github.com/zephyrproject-rtos/zephyr-testing/runs/15095827873
> 
> Let me know if you need a rerun on an updated version.

Thanks! I found alot with that. I cherry-pick'ed all the open PRs in to here, and now I need an updated version

2023-07-19 19:35 UTC, fabiobaltieri commented
> Thanks! I found alot with that. I cherry-pick'ed all the open PRs in to here, and now I need an updated version

Good stuff, updated https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch to 7615ee8d68, running now.

2023-07-19 23:45 UTC, XenuIsWatching commented
> > Thanks! I found alot with that. I cherry-pick'ed all the open PRs in to here, and now I need an updated version
> 
> Good stuff, updated https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch to [7615ee8](https://github.com/zephyrproject-rtos/zephyr/commit/7615ee8d685c5fb512d7ef9436f0b2a1720dc39b), running now.

It appears i dun goofed, I didn't wait for the CI to finish running on my new changes for https://github.com/zephyrproject-rtos/zephyr/pull/56957 and the error log is just too full :/  I'll get those fixed and likely we're going to have have to bring it over it again to zephyr-testing once I get that

2023-07-20 09:19 UTC, fabiobaltieri commented
> It appears i dun goofed, I didn't wait for the CI to finish running on my new changes for #56957 and the error log is just too full :/ I'll get those fixed and likely we're going to have have to bring it over it again to zephyr-testing once I get that

No prob, updated to 058fdcfef1.

2023-12-05 08:40 UTC, nordicjm commented
@XenuIsWatching looks like this needs a rebase

2023-12-05 17:45 UTC, XenuIsWatching commented
I rebased it as some things need to be merged, but there is still some work that needs to be done in one module, the "[zcbor](https://github.com/zephyrproject-rtos/zcbor)" as well as some modules need to have their commit hash updated to include the double promotions fixes

I don't know when I can get back to it as my daughter popped out in August and I'm on paternity leave until February.

2023-12-05 17:48 UTC, XenuIsWatching commented
> > It appears i dun goofed, I didn't wait for the CI to finish running on my new changes for #56957 and the error log is just too full :/ I'll get those fixed and likely we're going to have have to bring it over it again to zephyr-testing once I get that
> 
> No prob, updated to [058fdcf](https://github.com/zephyrproject-rtos/zephyr/commit/058fdcfef10055b8c0ac2a4a3a75f25da512aa6c).

@fabiobaltieri Would it be possible to do it again?

2023-12-05 18:02 UTC, fabiobaltieri commented
> @fabiobaltieri Would it be possible to do it again?

Of course, just ran `git fetch origin refs/pull/57154/head && git push -f testing FETCH_HEAD:refs/heads/vfabio-57154-branch`, https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch

2023-12-05 18:44 UTC, cfriedt commented
> I don't know when I can get back to it as my daughter popped out in August and I'm on paternity leave until February.

Congratulations 👶👨‍🍼 🎉

2023-12-06 17:01 UTC, keith-packard commented
I did a local `twister -b` run and it looks this is really close -- if we can get the proposed fixes merged in, we should be good to go. I'd be happy to shepherd this change in if Ryan would like to step away until Feb; all of the hard work has been done, and getting this merged requires careful coordination so that additional regressions don't get merged in the middle.

2023-12-06 18:40 UTC, XenuIsWatching commented
> I did a local `twister -b` run and it looks this is really close -- if we can get the proposed fixes merged in, we should be good to go. I'd be happy to shepherd this change in if Ryan would like to step away until Feb; all of the hard work has been done, and getting this merged requires careful coordination so that additional regressions don't get merged in the middle.

Yeah... it is close, except for the big one. zscilib is full of double promotion issues when I looked in to. I'd expect every single floating point constant within there would have to be within a macro which would put a `f` after it if it is compiling for single precision.

The other simple thing remaining is just getting the hashes updated for the modules. Those are already stacked within this PR

I did get around to pushing https://github.com/zephyrproject-rtos/zephyr/pull/66241 which looks like the only one that was introduced since then

2023-12-11 06:34 UTC, XenuIsWatching commented
It appears for the `test_sqrt` ""fixes"", NAN gets defined in picolibc which forces it to a float, which prevents the `test_sqrt.c` from using it's own definition. This is one of the CI failures that it uncovered.
https://github.com/picolibc/picolibc/blob/a97720d2a6970239b1dd3936685a372f13303339/newlib/libc/include/math.h#L68C15-L68C29

@keith-packard Do you have any thoughts on this?

2023-12-11 12:20 UTC, tejlmand commented
> I don't know when I can get back to it as my daughter popped out in August and I'm on paternity leave until February.

Congratulations 👶 🎉 🎁

2023-12-12 09:38 UTC, XenuIsWatching commented
@microbuilder When I try to run the tests for zscilib with `twister -p mps2_an521 -T modules/lib/zscilib/tests` locally, get this error
```
/home/ryanmcclelland/zephyrproject/modules/lib/zscilib/tests/prj.conf:4: warning: attempt to assign the value 'y' to the undefined symbol ZSL
/home/ryanmcclelland/zephyrproject/twister-out/mps2_an521/zsl.core.c.double/twister/testsuite_extra.conf:1: warning: attempt to assign the value 'n' to the undefined symbol ZSL_SINGLE_PRECISION
/home/ryanmcclelland/zephyrproject/twister-out/mps2_an521/zsl.core.c.double/twister/testsuite_extra.conf:2: warning: attempt to assign the value '0' to the undefined symbol ZSL_PLATFORM_OPT
error: Aborting due to Kconfig warnings
```
Am I missing something? I did a fresh west init and west update

2023-12-12 09:50 UTC, fabiobaltieri commented
@XenuIsWatching I tried here and no error either

```console
~/zephyrproject/zephyr$ ./scripts/twister -p mps2_an521 -T ../modules/lib/zscilib/tests
...
INFO    - Total complete:    2/   2  100%  skipped:    0, failed:    0, error:    0
...
~/zephyrproject/modules/lib/zscilib$ git grep 'config ZSL'
Kconfig.zscilib:config ZSL
```

Is it there?

2023-12-12 13:34 UTC, cfriedt approved these changes, later dismissed

2023-12-12 20:12 UTC, XenuIsWatching commented
> ```
> git grep 'config ZSL'
> ```

yep... I tried the same on a different linux computer and distro as well... same result
```
(.venv) ryanmcclelland@RyansComputer:~/zephyrproject/modules/lib/zscilib$ git grep 'config ZSL'
Kconfig.zscilib:config ZSL
Kconfig.zscilib:config ZSL_SINGLE_PRECISION
Kconfig.zscilib:config ZSL_PLATFORM_OPT
Kconfig.zscilib:config ZSL_VECTOR_INLINE
Kconfig.zscilib:config ZSL_MATRIX_INLINE
Kconfig.zscilib:config ZSL_BOUNDS_CHECKS
Kconfig.zscilib:config ZSL_SHELL
Kconfig.zscilib:config ZSL_SHELL_CLR
Kconfig.zscilib:config ZSL_SHELL_ORIENT
Kconfig.zscilib:config ZSL_CLR_RGBF_BOUND_CAP
```

2023-12-12 23:41 UTC, fabiobaltieri commented
@XenuIsWatching `zscilib` is an optional lib, do you have it enbled? `west config manifest.group-filter -- +optional`

2023-12-13 00:28 UTC, XenuIsWatching commented
> west config manifest.group-filter -- +optional

I see... that' must of been a new "feature" that I must of missed.

2023-12-13 04:07 UTC, XenuIsWatching commented
> It appears for the `test_sqrt` ""fixes"", NAN gets defined in picolibc which forces it to a float, which prevents the `test_sqrt.c` from using it's own definition. This is one of the CI failures that it uncovered. https://github.com/picolibc/picolibc/blob/a97720d2a6970239b1dd3936685a372f13303339/newlib/libc/include/math.h#L68C15-L68C29
> 
> @keith-packard Do you have any thoughts on this?

With zscilib fixed (hopefully), it looks like this is the last thing (I hope) before all the CIs are passing with this compilier flag

2023-12-13 07:59 UTC, nordicjm commented on west.yml
> -      revision: 67fd8bb88d3136738661fa8bb5f9989103f4599e
typo in this commit *zcbor

2023-12-13 07:59 UTC, nordicjm commented on west.yml
> +      revision: 196f985c31673a5e80a2c2959d61853f25a26551
@oyvindronningstad can you check the fix for zcbor?

2023-12-13 09:44 UTC, microbuilder commented
@XenuIsWatching I merged in the changes to zscilib if you want to update the manifest. Thanks for putting those together.

2023-12-13 09:47 UTC, oyvindronningstad approved these changes
zcbor:196f985c31673a5e80a2c2959d61853f25a26551 is ok

2023-12-13 18:54 UTC, XenuIsWatching commented
> zcbor:196f985c31673a5e80a2c2959d61853f25a26551 is ok

but it needs to be merged into https://github.com/zephyrproject-rtos/zcbor

2023-12-17 20:36 UTC, cfriedt approved these changes, later dismissed

2024-01-03 12:49 UTC, tejlmand submitted a review, later dismissed

2024-01-26 05:06 UTC, XenuIsWatching commented
@fabiobaltieri Can you merge this into zephyr-testing again? I really hope this is the last time as it now appears all the checkboxes are now checked :)

2024-01-26 09:19 UTC, fabiobaltieri commented
@XenuIsWatching  hey welcome back! There you have it: https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-57154-branch

2024-01-26 11:57 UTC, cfriedt approved these changes
LGTM 👍
https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/7666165016

2024-01-26 12:14 UTC, microbuilder approved these changes

2024-01-26 12:28 UTC, fabiobaltieri approved these changes
Let's go!

2024-01-26 13:37 UTC, nordicjm approved these changes

2024-01-26 15:10 UTC, jhedberg approved these changes

2024-01-26 15:43 UTC, MaureenHelm approved these changes

2024-01-26 21:47 UTC, keith-packard approved these changes
Let's get this merged before something breaks again :-)

2024-01-27 02:37 UTC, merged