fix typos in flash_shelll
zephyrproject-rtos/zephyr pull request #57262
Opened 2023-04-25 20:09 UTC by dale-herman

2023-04-28 11:17 UTC, henrikbrixandersen commented
@dale-herman Your PR contains a commit to the ISO-TP protocol as well as changes to the flash shell. Yet, without a proper description of the your PR (it only has a title), it is difficult to know what your intentions are.

Please fix this by limiting the PR to one isolated change and provide a proper description for the reviewers.

2023-04-28 11:19 UTC, henrikbrixandersen requested changes
Please limit the PR to one functional change.

2023-05-31 08:45 UTC, henrikbrixandersen commented
@dale-herman ping

2023-05-31 12:28 UTC, FRASTM commented on subsys/canbus/isotp/isotp_internal.h
> +#define ISOTP_USE_CAN_FD 1
defining the ISOTP_USE_CAN_FD, then ISOTP_USE_CAN_FD is defined : line 32 is true

2023-06-05 07:48 UTC, gautierg-st commented on drivers/adc/adc_stm32.c
> +#if defined(CONFIG_SOC_SERIES_STM32G4X) || defined(CONFIG_SOC_SERIES_STM32H7X)
Please rebase to latest main, this part is reworked and fixed.

2023-06-05 18:50 UTC, closed without merging