drivers: spi: esp32xx: Add chip select setup and hold time
zephyrproject-rtos/zephyr pull request #57570
Opened 2023-05-05 00:55 UTC by dean-at-evos

Added device tree bindings and implementation for setting the spi controllers chip select setup and hold time settings.

Sometimes an SPI peripheral requires a specific CS timing. This PR implements setting the chip select setup and hold times for the ESP32 hardware spi controller.
Examples with 20MHz SCLK on ESP32C3 SPI mode 0,0

![image](https://user-images.githubusercontent.com/119280044/236358354-d34dc516-447b-409a-b6ab-7a06ebb8a57e.png)
![image](https://user-images.githubusercontent.com/119280044/236358397-7872ad61-efbb-49ae-9288-f655cecb2062.png)
![image](https://user-images.githubusercontent.com/119280044/236358426-d9e5d9f7-ec3a-439d-8d44-e1ac9a547d4a.png)

2023-05-05 09:44 UTC, LucasTambor requested changes
Nice! Can you make it `required: False` and default the value to `0` if not set?

2023-05-05 12:48 UTC, dean-at-evos reviewed
In my test setup (I really only have ESP32C3) this change had no effect for existing code. But I could add the setting to board overlays and use it after. Not sure what you mean but defaulting it?

2023-05-05 12:49 UTC, LucasTambor commented
Oh I was thinking something like:

```
.cs_setup = DT_INST_PROP_OR(idx, cs_setup_time, 0),	\
.cs_hold = DT_INST_PROP_OR(idx, cs_hold_time, 0)	\
```

But nevermind, it works well as it is now.

2023-05-05 12:49 UTC, sylvioalves commented
> > Nice! Can you make it `required: False` and default the value to `0` if not set?
> 
> I thought I kind of did by including it as 0 in all base bindings. It tested as non breaking for existing code on my setup....
> 
> Although I did have the idea that it could be an array for each slave device, so that the device on the bus with the slowest timing requirements doesn't set the timing for others. If this makes it to the main branch I will put an issue in to it.

I am ok with the approach as well. Having an array for that in next PR makes sense.

2023-05-05 12:52 UTC, sylvioalves commented
> Oh I was thinking something like:
> 
> ```
> .cs_setup = DT_INST_PROP_OR(idx, cs_setup_time, 0),	\
> .cs_hold = DT_INST_PROP_OR(idx, cs_hold_time, 0)	\
> ```
> 
> But nevermind, it works well as it is now.

@dean-at-evos I also agree with Lucas. Perhaps both values should not be required and left as default 0. I understand you added all those .dtsi instances setting as 0, but should not be mandatory to have this.

2023-05-08 09:35 UTC, LucasTambor approved these changes

2023-05-09 11:14 UTC, marekmatej approved these changes
LGTM

2023-05-09 12:31 UTC, merged