modem: modem_iface_uart_async: handle RX errors
zephyrproject-rtos/zephyr pull request #57628
Opened 2023-05-06 07:59 UTC by JordanYates

Re-enable reception on the UART instance when `UART_RX_DISABLED`
  triggers, which can happen when errors occur on the line.

  This stops the driver permanently moving into an unresponsive state.

  Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

2023-05-06 09:20 UTC, bjarki-trackunit requested changes
Really nice to see error handling added :)

2023-05-06 09:20 UTC, bjarki-trackunit commented on drivers/modem/modem_iface_uart_async.c
> +		k_mem_slab_alloc(&uart_modem_async_rx_slab, (void **)&buf, K_FOREVER);
Following the UART API documentation https://docs.zephyrproject.org/latest/hardware/peripherals/uart.html, UART_RX_DISABLED could mean that there was no buffer available for the UART to switch to.

Please validate the return code of `k_mem_slab_alloc()` to ensure a buffer could be allocated before passing it to the UART as is done in the UART_RX_BUF_REQUEST switch case.

2023-05-06 14:29 UTC, bjarki-trackunit approved these changes

2023-05-08 14:32 UTC, rerickson1 approved these changes

2023-05-08 14:42 UTC, merged