Kconfig: experimental: Fix some experimental options
zephyrproject-rtos/zephyr pull request #57679
Opened 2023-05-08 22:38 UTC by ceolin

Select EXPERIMENTAL symbol for options that explicitly says that are experimental.

2023-05-09 08:37 UTC, jfischer-no requested changes
EXPERIMENTAL will be selected by USB_DEVICE_STACK_NEXT, this Kconfig option depends on it.

2023-05-09 09:44 UTC, canisLupus1313 approved these changes, later dismissed

2023-05-09 09:56 UTC, rlubos approved these changes, later dismissed
Net part LGTM

2023-05-09 16:26 UTC, ceolin commented
> USB_DEVICE_STACK_NEXT

fair enough, just removed all usb/device_next/class/* changes.

2023-05-09 16:42 UTC, stephanosio approved these changes

2023-05-10 05:22 UTC, tmon-nordic approved these changes

2023-05-10 09:09 UTC, jfischer-no approved these changes

2023-05-10 09:18 UTC, rlubos approved these changes

2023-05-10 09:26 UTC, canisLupus1313 approved these changes

2023-05-10 09:41 UTC, merged