samples: hello_world_user add memory domain usage
zephyrproject-rtos/zephyr pull request #57784
Opened 2023-05-11 10:35 UTC by Laczen

The modified sample shows how a memory partition can be defined and accessed in userspace.

This can also be used to allow access to a memory region from userspace without the need of a driver.

2023-05-11 10:39 UTC, nordicjm requested changes, later dismissed
We have a retained memory driver that does exactly this, why should the functionality be duplicated in a different way?

2023-05-11 11:10 UTC, Laczen commented
> We have a retained memory driver that does exactly this, why should the functionality be duplicated in a different way?

This is a sample that shows how the memory domain can be used to allow access to memory from userspace, it has nothing to do with the retained memory driver. The possibility to use it like this has always been present.

2023-05-11 11:12 UTC, nashif commented
> We have a retained memory driver that does exactly this, why should the functionality be duplicated in a different way?

how is this related to retained memory driver?

2023-05-11 11:14 UTC, nordicjm commented
> > We have a retained memory driver that does exactly this, why should the functionality be duplicated in a different way?
> 
> how is this related to retained memory driver?

It's similar to the RAM backend part of https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/retained_mem/api

2023-05-11 12:58 UTC, nashif commented
> It's similar to the RAM backend part of [`main`/tests/drivers/retained_mem/api](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/retained_mem/api?rgh-link-date=2023-05-11T11%3A14%3A43Z)

please elaborate how the the retained memory driver API is similar to userspace memory domains and how you would this changed be addressed using retained memory. Looks like I missed the memo where retained memory driver changed how we define memory domains in userspace, or we are talking past eachother here.

2023-05-11 16:37 UTC, ceolin requested changes, later dismissed
I don't think this is making this test any better tbh. We have other more complete tests/samples adding partitions and memory domains.

2023-05-11 16:47 UTC, nashif commented
> I don't think this is making this test any better tbh

this is a sample, not a test...

2023-05-11 18:01 UTC, Laczen commented
> I don't think this is making this test any better tbh. We have other more complete tests/samples adding partitions and memory domains.

Thank you for the feedback.

I agree that there are other samples that are more complex, but it is quite difficult to derive this simple example from the complex samples.

The sample illustrates the first thing that appears when using userspace: How can I create a variable that is accessable from userspace. This is also why I added it to the `hello_world_user` sample and have not created a new sample.

2023-07-11 11:54 UTC, Laczen commented
@ceolin, could you please revisit and comment why it is not a good idea to show how to create a variable that can be accessed from user space in the hello_world_user sample ?

2023-07-14 06:06 UTC, ceolin commented
> @ceolin, could you please revisit and comment why it is not a good idea to show how to create a variable that can be accessed from user space in the hello_world_user sample ?

IMHO no. Hello world should be as much simple as possible. We have samples showing how to do this,  e.g `samples/userspace/shared_mem` and `samples/userspace/prod_consumer`. 

That's said, I think it is totally reasonable having a simpler sample about how to do this, I just don't think it is in the hello world :)  But anyway, that is just my opinion and it is not reasonable enough to block it, I am removing the -1.

2023-09-25 21:36 UTC, dcpleung requested changes
I think a `hello_world` app should be simple... very simple that it only prints "hello world". Besides, to understand how memory partitions work, the `shared_mem` app would be more appropriate.

2023-09-26 03:55 UTC, Laczen commented
As this seems to complex I am closing the PR.

2023-09-26 03:55 UTC, closed without merging