Bluetooth: Controller: Fix LE Set CIG Param handles returned
zephyrproject-rtos/zephyr pull request #57911
Opened 2023-05-16 00:00 UTC by cvinayak

Fix LE Set Connected Isochronous Parameters Command Complete to return the correctly allocated Connected Isochronous stream connection handle instead of index of the iterator as handle.

Fixes #57904.

2023-05-17 07:57 UTC, Thalley approved these changes

2023-05-17 07:57 UTC, Thalley commented on subsys/bluetooth/controller/hci/hci.c
> +				struct ll_conn_iso_stream *cis;
```suggestion
				const struct ll_conn_iso_stream *cis;
```

2023-05-17 08:55 UTC, mtpr-ot commented
What is the purpose of this change?

2023-05-17 08:59 UTC, mtpr-ot requested changes
Please state the purpose of the change. What is the "fix"? The handle returned as iterator is the actual handle. If this is no longer the case, then `ll_conn_iso_stream_get` will not work.

2023-05-17 09:07 UTC, cvinayak commented
> Please state the purpose of the change. What is the "fix"? The handle returned as iterator is the actual handle. If this is no longer the case, then `ll_conn_iso_stream_get` will not work.

CIS contexts are allocated from memory pool and after CIG remove they are allocated back in LIFO order. The CIS context handle are stored as `cis->lll.handle`, returning the iterator does not reflect the correct allocated CIS context.

2023-05-17 09:13 UTC, mtpr-ot commented
> > Please state the purpose of the change. What is the "fix"? The handle returned as iterator is the actual handle. If this is no longer the case, then `ll_conn_iso_stream_get` will not work.
> 
> CIS contexts are allocated from memory pool and after CIG remove they are allocated back in LIFO order. The CIS context handle are stored as `cis->lll.handle`, returning the iterator does not reflect the correct allocated CIS context.

That's critical. I think we need to look for otherplaces then - as mentioned - `ll_conn_iso_stream_get` relies on the linear relation between index and handle.

2023-05-17 09:16 UTC, mtpr-ot approved these changes
This indicates that the assumption of a linear relation between the index and handle of a CIS is incorrect, and more code needs to be fixed.

2023-05-17 09:23 UTC, mtpr-ot requested changes
Just keeping this open for discussion.

2023-05-17 10:50 UTC, cvinayak commented
> In `ll_cig_parameters_commit`, the `cis->lll.handle` is assigned via `cis->lll.handle = ll_conn_iso_stream_handle_get(cis);` so how is it that they can be mixed up?

`ll_conn_iso_stream_handle_get()` uses `mem_index_get()` plus `LL_CIS_HANDLE_BASE` and that is correct. I do not see any mix up. As `mem_acquire()` is used to allocate, `cis->lll.handle` has the correct connection handle.

2023-05-17 10:51 UTC, cvinayak commented
> Please state the purpose of the change.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/57904.

2023-05-17 13:48 UTC, cvinayak commented
> > `ll_conn_iso_stream_handle_get()` uses `mem_index_get()` plus `LL_CIS_HANDLE_BASE` and that is correct. I do not see any mix up. As `mem_acquire()` is used to allocate, `cis->lll.handle` has the correct connection handle.
> 
> Yes my point exactly. So how is it that the handle obtained from the index+offset is not correct?

LHS `ll_conn_iso_stream_get_by_group()` return `handle` which is the iterator, which is incorrect. RHS `cis->lll.handle` is the correct connection handle for `cis`-es allocated to a CIG.

You could run the tests developed here https://github.com/zephyrproject-rtos/zephyr/pull/57032 to reproduce the incorrect handles returned after a CIG is removed.

2023-05-19 10:32 UTC, mtpr-ot commented
> `ll_conn_iso_stream_get_by_group()` return `handle` which is the iterator which is incorrect

The iterator _is_ the valid handle by design. The function returns the valid handle bound to the instance by the index + LL_CIS_HANDLE_BASE.
I think we should talk F2F, when would you have time for a call?

2023-05-22 18:22 UTC, mtpr-ot commented
Please consider #58154 as possible alternative fix.

2023-05-23 07:19 UTC, cvinayak commented
> > `ll_conn_iso_stream_get_by_group()` return `handle` which is the iterator which is incorrect
> 
> The iterator _is_ the valid handle by design. The function returns the valid handle bound to the instance by the index + LL_CIS_HANDLE_BASE. I think we should talk F2F, when would you have time for a call?

Contrary to your argument you are now in #58154 returning `cis->lll.handle` :
https://github.com/zephyrproject-rtos/zephyr/blob/45eb028b4abdabc050f202882188e530a7fdfaa6/subsys/bluetooth/controller/ll_sw/ull_central_iso.c#L334

Which is correct now in #58154, do you still need a F2F call?

@Emil-Gydesen-Bose Would you test if #58154 is an alternative fix for your GMAP testing? (I will close this PR when you approve/confirm #58154)

2023-05-23 09:29 UTC, mtpr-ot commented
> > > `ll_conn_iso_stream_get_by_group()` return `handle` which is the iterator which is incorrect
> > 
> > 
> > The iterator _is_ the valid handle by design. The function returns the valid handle bound to the instance by the index + LL_CIS_HANDLE_BASE. I think we should talk F2F, when would you have time for a call?
> 
> Contrary to your argument you are now in #58154 returning `cis->lll.handle` :
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/45eb028b4abdabc050f202882188e530a7fdfaa6/subsys/bluetooth/controller/ll_sw/ull_central_iso.c#L334
> 
> Which is correct now in #58154, do you still need a F2F call?
> 
> @Emil-Gydesen-Bose Would you test if #58154 is an alternative fix for your GMAP testing? (I will close this PR when you approve/confirm #58154)

My argument was not that it was wrong to return `cis->lll.handle`, but rather it is the same as the iterator handle, so if that change fixed something, things were not right...
In my code change `ll_conn_iso_stream_handle_get` is used to get the handle, which is the same way the iterator gets the handle.
I think we can do without the call if #58154 fixes the issue.

2023-05-23 11:05 UTC, Thalley commented
> @Thalley  Would you test if #58154 is an alternative fix for your GMAP testing? (I will close this PR when you approve/confirm #58154)

@cvinayak just did a trial run, and the CIS IDs are correctly set when using https://github.com/zephyrproject-rtos/zephyr/pull/58154

2023-05-23 11:17 UTC, cvinayak commented
Closing this in favor of #58154

2023-05-23 11:17 UTC, closed without merging