boards: arm: stm32l562 disco kit console clocked by HSI
zephyrproject-rtos/zephyr pull request #57931
Opened 2023-05-16 10:22 UTC by FRASTM

Configure the usart1 for the zephyr console so that the clock source is HSI instead of (default PCLK2). HSI oscillator is stable before the PCLK2. The first char is sent faster to the console output.

With usart1-console clocked by the (default) PCLK2, it can happen that some twister results fail due to missing char.
Example samples/subsys/zbus/hello_world output log is :
```
Sensor sample started raw reading, version 0.1-2!"
I: Channel list:
I: 0 - Channel acc_data_chan:
I:       Message size: 12
I:       Observers:
...
```

when expecting (sample.yaml)
```
Sensor sample started raw reading, version 0.1-2!"
I: Channel list:
I: 0 - Channel acc_data_chan:
I:       Message size: 12
I:       Observers:
...
```
--> first char is missing

2023-05-23 10:54 UTC, erwango requested changes

2023-07-31 08:12 UTC, FRASTM commented
Not useful anymore ; the testcase is now passed

2023-09-28 15:36 UTC, kartben commented
@FRASTM is this PR still meant be in draft state?

2023-10-12 11:28 UTC, FRASTM commented
No more issue reported

2023-10-12 11:28 UTC, closed without merging