drivers: serial: stm32: add support for RS485 configuration
zephyrproject-rtos/zephyr pull request #58192
Opened 2023-05-23 12:52 UTC by arbrauns

The stm32 UART can output a "driver enable" signal on the RTS pin that allows controlling e.g. external RS-485 drivers.

This can already be configured through the devicetree using the `de-*`
properties, but not through `uart_configure()`. This commit enables the use
of `.flow_ctrl=UART_CFG_FLOW_CTRL_RS485`.

This is supported on all devices other than l1, f1, f2, and f4.

2023-05-23 13:32 UTC, erwango commented
Would you mind checking https://github.com/zephyrproject-rtos/zephyr/pull/57524 ?

2023-05-24 22:20 UTC, legoabram commented
> For runtime configuration through uart_configure(), the existing RS485 flow control configuration is used.

I hadn't noticed that UART_CFG_FLOW_CTRL_RS485 was a thing! Lemme try implementing some of your changes.

2023-06-06 09:41 UTC, arbrauns commented
Rebased, now only contains changes related to `uart_configure()`, since #57524 already solved the devicetree stuff.

2023-06-19 15:11 UTC, erwango requested changes
One comment, otherwise LGTM.

2023-06-19 15:11 UTC, erwango commented on drivers/serial/uart_stm32.c
> +		return LL_USART_HWCONTROL_NONE;
Since the function already returns `LL_USART_HWCONTROL_NONE`, a mere comment would be enough.

2023-06-20 09:09 UTC, erwango approved these changes

2023-07-07 10:35 UTC, gautierg-st approved these changes

2023-07-07 11:16 UTC, merged