ARC: MWDT: rework GNU helper tools usage
zephyrproject-rtos/zephyr pull request #58329
Opened 2023-05-26 15:16 UTC by evgeniy-paltsev

As of today MWDT toolchain in case of Zephyr may use few tools from GNU toolchain - GNU compiler for DTS preprocessing and objcopy for section renaming.

Currently we were trying to find any GNU compiler & objcopy which start to cause compatibility issues for new targets - i.e. not every objcopy knows new ARC targets.

Let's use ARC GNU tools from Zephyr SDK as we still usually require it when building with MWDT for other tools like DTC (device tree compiler)

2023-05-30 08:52 UTC, abrodkin submitted a review, later dismissed

2023-05-30 22:01 UTC, abrodkin approved these changes, later dismissed

2023-06-02 06:51 UTC, tejlmand requested changes
Thanks for this proposal.

I noticed this PR is depending on the following PR in sdk-ng: https://github.com/zephyrproject-rtos/sdk-ng/pull/677

That PR takes Zephyr SDK in a direction I don't like, as it starts to couple internals of the Zephyr SDK itself to Zephyr, when in fact it would be better to improve existing interface between Zephyr and the Zephyr SDK.

I have made a small proposal which completely remove the need for https://github.com/zephyrproject-rtos/sdk-ng/pull/677, and also remove new `ARCMWDT_HELPER_x` symbols and instead relies on existing Zephyr SDK generic symbols.

This PR did reveal that Zephyr SDK can improve from an extra cleanup, but with proposed changes to this PR, then such cleanup can be done later, and be carefully thought through.

Benefits with proposed changes:
- Can be used with existing Zephyr SDK releases.
- No request for specific ARCMWDT helper symbols in Zephyr SDK
- Still uses `find_program` which allows users to explicitly point to an objcopy of their choice be setting a cache variable (advanced use-case)

2023-06-02 06:51 UTC, tejlmand commented on cmake/bintools/arcmwdt/target.cmake
> +set(CMAKE_OBJCOPY ${ARCMWDT_HELPER_OBJCOPY})
a hard `set()` here is not good.

The use of `find_program()` actually allows users to point to a specific installation of objcopy if they have such need.

Combined with the comment on Zephyr SDK lookup then I propose the following adjustment:
```suggestion
find_program(CMAKE_OBJCOPY ${ZEPHYR_CROSS_COMPILE}objcopy PATHS ${ZEPHYR_SDK_INSTALL_DIR} NO_DEFAULT_PATH)
```

2023-06-02 06:51 UTC, tejlmand commented on cmake/compiler/arcmwdt/generic.cmake
> +set(CMAKE_DTS_PREPROCESSOR ${ARCMWDT_HELPER_DTS_PREPROCESSOR})
similar to `CMAKE_OBJCOPY`.

With proposed changes, same principle can be applied:
```suggestion
find_program(CMAKE_DTS_PREPROCESSOR ${ZEPHYR_CROSS_COMPILE}gcc PATHS ${ZEPHYR_SDK_INSTALL_DIR} NO_DEFAULT_PATH)
```

2023-06-02 18:56 UTC, evgeniy-paltsev commented
@tejlmand thanks a lot for review!

Reusing CROSS_COMPILE from Zephyr's sdk `target.cmake` is really good idea. I've changed implementation as you've proposed.

2023-06-04 07:43 UTC, abrodkin submitted a review, later dismissed

2023-06-05 11:22 UTC, ruuddw submitted a review, later dismissed

2023-06-06 09:02 UTC, tejlmand reviewed
Looks much better, two minor nits on message printing.

Rest is 👍

2023-06-09 17:02 UTC, evgeniy-paltsev commented on cmake/bintools/arcmwdt/target.cmake
> +message(STATUS "Found GNU objcopy helper for MWDT: ${CMAKE_OBJCOPY} from zephyr ${SDK_VERSION}")
I've changed the last part, but I've kept the note that is't `helper for MWDT` - othervise it super unobvious and looks like an error (especially for user who not aware about all these implementation details) that we've found objcopy tool from Zephyr SDK and not from MWDT.

2023-06-09 21:55 UTC, ruuddw approved these changes

2023-06-12 11:29 UTC, tejlmand commented on cmake/bintools/arcmwdt/target.cmake
> +message(STATUS "Found GNU objcopy helper for MWDT: ${CMAKE_OBJCOPY} from zephyr ${SDK_VERSION}")
fair point.

2023-06-12 11:29 UTC, tejlmand approved these changes

2023-06-13 19:30 UTC, abrodkin approved these changes

2023-06-17 11:44 UTC, merged