scripts: Typo in the word 'platform'
zephyrproject-rtos/zephyr pull request #58323
Opened 2023-05-26 14:16 UTC by LukaszMrugala

`testinstance.py` contains a string literal comparison to the word `platform`, which has been misspelled as `plaform`.

That typo and a few others, contained within docstrings, have been corrected to `platform`.

The change is verified by a test expansion.

Fixes #58322

2023-05-26 14:47 UTC, asemjonovs approved these changes, later dismissed

2023-05-26 15:09 UTC, golowanow requested changes

2023-05-26 15:09 UTC, golowanow commented on scripts/tests/twister/test_testinstance.py
> +        testcase.extra_configs = extra_configs
@LukaszMrugala please split the `extra_configs` fix and the typo fix into separate commits and update the PR's description that there are two fixes here.

2023-05-26 15:14 UTC, golowanow submitted a review, later dismissed

2023-05-26 16:23 UTC, aasthagr approved these changes, later dismissed

2023-05-29 07:50 UTC, LukaszMrugala commented
`CONFIG_NULL` changed to `CONFIG_LOG`. `CONFIG_NULL` is not defined anywhere, so it failed compliance checks. `CONFIG_LOG` has been deemed as close to a `null` config (one that does nothing), so it is used instead.

2023-05-29 08:52 UTC, nashif commented
Can you please split the typo fixes in various tests into their own commits?

2023-05-29 09:02 UTC, LukaszMrugala commented
> Can you please split the typo fixes in various tests into their own commits?

Yes, I could do that. I am assuming that you'd like one commit for `test_*.py` and `testinstance.py` change and then one commit for every `*.c` typo changed?

2023-05-29 09:10 UTC, nashif commented
> Yes, I could do that. I am assuming that you'd like one commit for `test_*.py` and `testinstance.py` change and then one commit for every `*.c` typo changed?

no, one commit for the twister pytest tests, another for tests/ztest/.. and one more for test/lib/...

2023-05-29 09:38 UTC, nashif approved these changes

2023-05-29 11:27 UTC, golowanow commented
@LukaszMrugala the two new commits have identical description, could change subjects there like this:
`tests: lib: devicetree: Fixes docstring typo`
`tests: shared_multi_heap: Fixes docstring typo`

2023-05-29 15:28 UTC, hakehuang approved these changes

2023-05-29 17:11 UTC, golowanow approved these changes

2023-05-29 18:34 UTC, merged