drivers: intc: stm32: add appropriate operand types
zephyrproject-rtos/zephyr pull request #58339
Opened 2023-05-26 18:25 UTC by feraralashkar

1. add explicit unsigned long type suffix for decimal constants, avoiding possible [shiftTooManyBitsSigned], and

2. add an explicit uint32_t cast to right hand operands of left shift operators , thus complying with required [misra-c2012-10.1] rule which states; operands shall not be of an inappropriate essential type.

Found as a coding guideline violation (Rule 10.1) by static code scanning tool.

Note: Tested on STM32L5 Nucleo-144 board (stm32l552xx).

2023-05-29 15:47 UTC, FRASTM approved these changes

2023-05-30 17:27 UTC, dcpleung commented
Maybe you can use the macro `BIT()`?

2023-06-01 18:43 UTC, feraralashkar commented
@dcpleung , the `BIT(line)` approach is only correct if:
1.
```diff
diff --git a/drivers/gpio/gpio_stm32.c b/drivers/gpio/gpio_stm32.c
/**
  * @brief EXTI interrupt callback
  */
-static void gpio_stm32_isr(int line, void *arg)
+static void gpio_stm32_isr(uint8_t line, void *arg)
 {
        struct gpio_stm32_data *data = arg;
```
2.
```diff
diff --git a/include/zephyr/drivers/interrupt_controller/exti_stm32.h b/include/zephyr/drivers/interrupt_controller/exti_stm32.h

  *
  * @param line EXTI# line
  */
-void stm32_exti_enable(int line);
+void stm32_exti_enable(uint8_t line);
 
 /**
  * @brief disable EXTI interrupt for specific line
  *
  * @param line EXTI# line
  */
-void stm32_exti_disable(int line);
+void stm32_exti_disable(uint8_t line);
 
 /**
  * @brief EXTI trigger flags

  * @param line EXTI# line
  * @param trg  OR'ed stm32_exti_trigger flags
  */
-void stm32_exti_trigger(int line, int trg);
+void stm32_exti_trigger(uint8_t line, int trg);
 
 /* callback for exti interrupt */
-typedef void (*stm32_exti_callback_t) (int line, void *user);
+typedef void (*stm32_exti_callback_t) (uint8_t line, void *user);
 
 /**
  * @brief set EXTI interrupt callback

  * @param cb   user callback
  * @param data user data
  */
-int stm32_exti_set_callback(int line, stm32_exti_callback_t cb, void *data);
+int stm32_exti_set_callback(uint8_t line, stm32_exti_callback_t cb, void *data);
 
 /**
  * @brief unset EXTI interrupt callback
  *
  * @param line EXI# line
  */
-void stm32_exti_unset_callback(int line);
+void stm32_exti_unset_callback(uint8_t line);
 
 #endif /* ZEPHYR_DRIVERS_INTERRUPT_CONTROLLER_INTC_EXTI_STM32_H_ */
```
3.
```diff
diff --git a/drivers/interrupt_controller/intc_exti_stm32.c b/drivers/interrupt_controller/intc_exti_stm32.c
        struct __exti_cb cb[NUM_EXTI_LINES];
 };
 
-void stm32_exti_enable(int line)
+void stm32_exti_enable(uint8_t line)
 {
        int irqnum = 0;

        /* Enable requested line interrupt */
 #if defined(CONFIG_SOC_SERIES_STM32H7X) && defined(CONFIG_CPU_CORTEX_M4)
-       LL_C2_EXTI_EnableIT_0_31(1 << line);
+       LL_C2_EXTI_EnableIT_0_31(BIT(line));
 #else
-       LL_EXTI_EnableIT_0_31(1 << line);
+       LL_EXTI_EnableIT_0_31(BIT(line));
 #endif
 
        /* Enable exti irq interrupt */
        irq_enable(irqnum);
 }

-void stm32_exti_disable(int line)
+void stm32_exti_disable(uint8_t line)
 {
        z_stm32_hsem_lock(CFG_HW_EXTI_SEMID, HSEM_LOCK_DEFAULT_RETRY);
 
        if (line < 32) {
 #if defined(CONFIG_SOC_SERIES_STM32H7X) && defined(CONFIG_CPU_CORTEX_M4)
-               LL_C2_EXTI_DisableIT_0_31(1 << line);
+               LL_C2_EXTI_DisableIT_0_31(BIT(line));
 #else
-               LL_EXTI_DisableIT_0_31(1 << line);
+               LL_EXTI_DisableIT_0_31(BIT(line));
 #endif
        } else {
                __ASSERT_NO_MSG(line);
...
-void stm32_exti_trigger(int line, int trigger)
+void stm32_exti_trigger(uint8_t line, int trigger)
 {
 
        if (line >= 32) {
...
...
```
4. Note that:
```h
/**
 * @brief Provides a type to hold a GPIO pin index.
 *
 * This reduced-size type is sufficient to record a pin number,
 * e.g. from a devicetree GPIOS property.
 */
typedef uint8_t gpio_pin_t;
```

2023-06-02 07:42 UTC, FRASTM approved these changes, later dismissed

2023-06-02 16:23 UTC, dcpleung commented
I think you can still do `BIT((uint32_t)line)`. This or `BIT()` is fine with me. It's just that by using `BIT()`, you don't have to worry about marking the constant.

2023-06-05 14:31 UTC, erwango requested changes
Agree with @dcpleung, using a macro (BIT or a new dedicated local macro) would make the code lighter (as in "more digest to read", not on footprint ofc)

2023-06-06 06:47 UTC, erwango approved these changes

2023-06-06 07:18 UTC, gautierg-st approved these changes

2023-06-06 13:41 UTC, merged