57277_fix_missing_set_orientation_api
zephyrproject-rtos/zephyr pull request #58489
Opened 2023-05-31 14:30 UTC by dbongartz

SDL & dummy display driver did not set the set_orientation API pointer.
This causes crashes when used.

Added implementation check in display API for set_orientation API.

Fixes: #57277

2023-05-31 15:11 UTC, jfischer-no requested changes
Just

```diff
diff --git a/include/zephyr/drivers/display.h b/include/zephyr/drivers/display.h
index 1b869b30314..92dd2c27ce0 100644
--- a/include/zephyr/drivers/display.h
+++ b/include/zephyr/drivers/display.h
@@ -396,6 +396,7 @@ display_set_pixel_format(const struct device *dev,
  * @param orientation Orientation to be used by display
  *
  * @retval 0 on success else negative errno code.
+ * @retval -ENOSYS If the function is not implemented.
  */
 static inline int display_set_orientation(const struct device *dev,
                                          const enum display_orientation
@@ -404,6 +405,10 @@ static inline int display_set_orientation(const struct device *dev,
        struct display_driver_api *api =
                (struct display_driver_api *)dev->api;
 
+       if (api->set_orientation == NULL) {
+               return -ENOSYS;
+       }
+
        return api->set_orientation(dev, orientation);
 }
```

2023-05-31 15:17 UTC, jfischer-no commented
> Also works for me. Should I remove the dummy Implementations then?

Please, replace you patches with changes above and force push your branch.

2023-05-31 15:39 UTC, dbongartz commented
@jfischer-no Should this check then not be added to all or at least most function calls in `display.h`? Feels a bit inconsistent to me to only have it for one function.

2023-06-01 08:04 UTC, jfischer-no commented
> @jfischer-no Should this check then not be added to all or at least most function calls in `display.h`? Feels a bit inconsistent to me to only have it for one function. Other API's like `led.h` in fact do that.

Perhaps, but to decide what API is mandatory/optional is out of scope of your issue/PR.  Please keep the original intention. Please add errno.h.

```diff
diff --git a/include/zephyr/drivers/display.h b/include/zephyr/drivers/display.h
index 1b869b30314..973c2fa8e79 100644
--- a/include/zephyr/drivers/display.h
+++ b/include/zephyr/drivers/display.h
@@ -20,6 +20,7 @@
  */
 
 #include <zephyr/device.h>
+#include <errno.h>
 #include <stddef.h>
 #include <zephyr/types.h>
```

2023-07-06 20:40 UTC, jfischer-no approved these changes

2023-07-11 13:42 UTC, carlescufi approved these changes

2023-07-11 13:42 UTC, merged