boards: 96b_carbon: add supported features
zephyrproject-rtos/zephyr pull request #5867
Opened 2018-01-28 21:51 UTC by nashif

add i2c, spi and usb_device as supported feaures.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2018-01-29 06:52 UTC, ydamigos approved these changes

2018-01-29 10:34 UTC, erwango commented on boards/arm/96b_carbon/96b_carbon.yaml
> +  - usb_device
Shouldn't we add ble (or bluetooth)?

2018-01-29 15:28 UTC, galak commented on boards/arm/96b_carbon/96b_carbon.yaml
> +  - usb_device
Agreed, also gpio, pinmux?

2018-01-29 15:28 UTC, galak requested changes
If we are updating this, lets make it complete for netif and other peripherals.

2018-01-30 04:55 UTC, nashif commented
add ble, gpio
We have not added pinmux to any boards, kinda assumed. not sure what you want to put under netif, this thing does not have a networking adapter. if you mean ble, we have not done this for any board with ble support.

Anyways, all of this we need to start getting from dts, waiting for critical mass and additional things supported in dts then we can look at it again.

2018-01-30 15:01 UTC, galak approved these changes

2018-01-30 15:01 UTC, merged