Dummy mux
zephyrproject-rtos/zephyr pull request #58824
Opened 2023-06-05 07:11 UTC by SiyuanCheng-CN

ARC EMSDP board has some peripherals are internal connected, such as DW spi1 and DFSS i2c0. They are unmuxed and have fix
connection to spi-flash or sensor. For these peripheral, add dummy mux type to avoid pinctrl ENOENT error.

2023-06-05 22:30 UTC, evgeniy-paltsev requested changes

2023-06-05 22:30 UTC, evgeniy-paltsev commented on drivers/pinctrl/pinctrl_emsdp.c
> +	case INNER_CONNECT:
Let's avoid reading / writing MMIO when not required - we can just add

```c
if (pin == INNER_CONNECT) {
	return 0;
}
```

to the beggining of pinctrl_emsdp_set.

2023-06-06 12:33 UTC, evgeniy-paltsev commented on boards/arc/emsdp/emsdp-pinctrl.dtsi
> +	inner_connect: inner_connect {
@SiyuanCheng-CN please change the naming in the rest places as well (INNER_CONNECT -> UNMUXED_PIN).

2023-06-08 11:54 UTC, evgeniy-paltsev approved these changes

2023-06-08 12:01 UTC, ruuddw approved these changes

2023-06-13 08:25 UTC, abrodkin approved these changes

2023-06-13 11:02 UTC, merged