net: tcp: populate context's local address for incoming connections
zephyrproject-rtos/zephyr pull request #58835
Opened 2023-06-05 08:28 UTC by arbrauns

Someone with actual knowledge of the network stack please double check my reasoning here, I'm very unsure if this is a correct and safe thing to do:

`local_addr` would only be initialized if `context->local->sin*_addr` was non-null. However, since `context` is a fresh context object, `local_addr` always remains at its initial value of `INADDR_ANY`, which is propagated to the context by `net_context_bind()`.

By populating `local_addr` using the TCP endpoint, `getsockname()` now returns the correct local address.

2023-06-05 14:36 UTC, rlubos reviewed
Looks reasonable, `conn->src` should already have a valid address extracted from the header at that point. Just some style nits.

2023-06-05 14:36 UTC, rlubos commented on subsys/net/ip/tcp.c
> +			     &conn->src.sin6.sin6_addr);
```suggestion
		net_ipaddr_copy(&net_sin6(&local_addr)->sin6_addr,
				&conn->src.sin6.sin6_addr);
```

2023-06-05 14:36 UTC, rlubos commented on subsys/net/ip/tcp.c
> +			     &conn->src.sin.sin_addr);
```suggestion
		net_ipaddr_copy(&net_sin(&local_addr)->sin_addr,
				&conn->src.sin.sin_addr);
```

2023-06-05 15:01 UTC, rlubos approved these changes

2023-06-06 12:26 UTC, jukkar requested changes
This looks a bit dangerous and I am not sure why we would want to do this.
I fail to see how this is going to help, meaning that if the
`net_sin6_ptr(&context->local)->sin6_addr` is not null, then the old code would work just fine. But if it is null, then the new code would cause null pointer write and cause crash.

Note that for local address in net_context is not a typical sockaddr but the address is actually a pointer to the address stored in the network interface struct (see net_context.c:net_context_bind() and check the usage of ptr variable https://github.com/zephyrproject-rtos/zephyr/blob/97935bb0dcc621b6bcc2e65b5365b1f93c5993b4/subsys/net/ip/net_context.c#L590). The reason why the address value is a pointer is to save some memory especially if IPv6 is used as all the sockets can share the same address.

2023-06-06 12:33 UTC, arbrauns commented
> This looks a bit dangerous and I am not sure why we would want to do this. I fail to see how this is going to help, meaning that if the `net_sin6_ptr(&context->local)->sin6_addr` is not null, then the old code would work just fine.

I have not been able to come up with a scenario where this is the case. `context` comes fresh from `net_context_get`, I can't find anything that would populate its `local` field with an IP address.

> But if it is null, then the new code would cause null pointer write and cause crash.

How so? The code writes to `local_addr`, not `context->local` - that part is done by `net_context_bind()` (and always has been).

> Note that for local address in net_context is not a typical sockaddr but the address is actually a pointer to the address stored in the network interface struct (see `net_context.c:net_context_bind()` and check the usage of `ptr` variable

I'm aware, and `net_context_bind()` takes care of creating a long-lived pointer to put in `local.sin_addr`/`local.sin6_addr`, no matter what you pass in.

2023-06-06 12:39 UTC, jukkar commented
Ah, sorry my wooden eyes missed something vital in the commit, I missed the fact that you were copying different variables :see_no_evil: So my bad, the commit looks good after all.

2023-06-06 12:39 UTC, jukkar approved these changes

2023-06-06 13:40 UTC, merged