kconfig: Avoid possible incosistence in CPUs count
zephyrproject-rtos/zephyr pull request #58868
Opened 2023-06-05 18:40 UTC by ceolin

MP_NUM_CPUS has to be <= MAX_NUM_CPUS. Changing the range to be in this interval and avoid inconsistences if we change MAX_NUM_CPUS.

2023-06-05 18:48 UTC, dcpleung approved these changes

2023-06-05 18:51 UTC, dcpleung requested changes
Actually... no... SPIN_VALIDATE can only be enabled if there are <= 4 cores. Since it is using the lower (empty) 2 bits of 4-byte aligned addresses as storage. More bits used will alter those addresses.

2023-06-05 21:08 UTC, dcpleung approved these changes

2023-06-06 10:14 UTC, jxstelter approved these changes

2023-08-20 00:29 UTC, closed without merging