docs: bluetooth: mesh: Add note about storing runtime configuration
zephyrproject-rtos/zephyr pull request #58907
Opened 2023-06-06 14:51 UTC by PavelVPV

All public API declared in cfg.h won't schedule storing of the change persistently if BT_MESH_VALID flag is not set. The flag is set after the node is provisioned.

2023-06-06 15:28 UTC, Thalley submitted a review, later dismissed

2023-06-07 10:51 UTC, Balaklaka approved these changes

2023-06-08 05:26 UTC, Andrewpini approved these changes, later dismissed

2023-06-16 12:02 UTC, mia-ko requested changes

2023-06-16 12:02 UTC, mia-ko commented on doc/connectivity/bluetooth/api/mesh/cfg.rst
> +   will not be stored in the :ref:`persistent storage <bluetooth_mesh_persistent_storage>`.
```suggestion
   Runtime configuration changes before the node is provisioned will not be stored
   in the :ref:`persistent storage <bluetooth_mesh_persistent_storage>`.
```

2023-06-22 08:57 UTC, mia-ko approved these changes

2023-06-27 12:55 UTC, Andrewpini approved these changes

2023-06-28 14:13 UTC, alxelax approved these changes

2023-06-29 19:04 UTC, carlescufi approved these changes

2023-06-29 19:04 UTC, merged