Bluetooth: controller: Fix supported cmds and states
zephyrproject-rtos/zephyr pull request #590
Opened 2017-06-23 10:19 UTC by carlescufi

Properly use the role and feature Kconfig variables to populate both the
supported commands and the supported states in the controller.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2017-06-23 15:34 UTC, jhedberg requested changes
Just one minor coding style thing, for the rest I'm trusting that you got the various BIT(n) usages correct.

2017-06-23 15:34 UTC, jhedberg commented on subsys/bluetooth/controller/hci/hci.c
> +	BT_DBG("states: 0x%08x%08x\n", (u32_t)(states >> 32), (u32_t)(states));
Minor coding style stuff: no \n necessary for BT_DBG and the () around the last parameter is unnecessary.

2017-06-23 16:25 UTC, jhedberg approved these changes

2017-06-24 17:52 UTC, cvinayak approved these changes

2017-06-25 11:26 UTC, merged