PWM driver for xmc4xxx using ccu4 module
zephyrproject-rtos/zephyr pull request #59095
Opened 2023-06-09 13:07 UTC by talih0

Adds drivers for pwm on xmc4xxx using Capture Compare Unit 4 (CCU4)
module. There are four CCU4 modules with each one having four channels
(the channels are called slices in infineon documentation).
Thus it's possible to have up to 16 pwm output signals. The output of
each channel can only be connected to a specific port/pin. The possible
connections and gpio configurations are defined using pinctrl.

2023-06-09 20:33 UTC, ifyall requested changes

2023-06-12 02:25 UTC, talih0 commented on drivers/pwm/pwm_xmc4xxx_ccu4.c
> +		slice = (XMC_CCU4_SLICE_t *)((uint32_t)config->ccu4 + (i + 1) * 0x100);
thanks @ifyall, I updated the PR

2023-06-18 15:36 UTC, talih0 commented
I've updated PR to add PWM via CCU8, which can  generate complementary high-side/low-side signals for each output channel. A variable dead time can be added during the off to on transitions to make sure that the high-side/low-side signals are not on at the same time.

2023-07-04 14:52 UTC, talih0 commented
Hi @ifyall, @npal-cy, could you have another look at this PR when you have a moment pls?
It's a dependency for this PR: https://github.com/zephyrproject-rtos/zephyr/pull/59138

2023-07-15 00:17 UTC, ifyall submitted a review, later dismissed

2023-07-21 13:12 UTC, talih0 commented
@ifyall, I rebased to fix merge conflicts. Could you re-ack pls

2023-07-21 17:57 UTC, ifyall approved these changes

2023-07-26 13:09 UTC, carlescufi approved these changes

2023-07-26 13:09 UTC, merged