mgmt: mcumgr: grp: img_mgmt: Add image data written callback
zephyrproject-rtos/zephyr pull request #59156
Opened 2023-06-12 12:08 UTC by nordicjm

Adds an optional callback upon image data being written, can be
    used for syncing or timeout purposes.

and

    Adds a function which gets the callback ID index of a given
    event ID.

2023-06-15 09:34 UTC, de-nordic submitted a review, later dismissed

2023-06-19 07:46 UTC, MarekPieta requested changes

2023-06-19 07:46 UTC, MarekPieta commented on subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
> +			(void)mgmt_callback_notify(MGMT_EVT_OP_IMG_MGMT_DFU_WRITE_COMPLETE, NULL,
For the same reason, I would suggest to call it also if an error happens after application was notified that data is going to be stored (e.g. on `img_mgmt_erase_image_data` error) and if SHA matches so write would not be performed

2023-06-19 10:44 UTC, nordicjm commented on subsys/mgmt/mcumgr/mgmt/src/mgmt.c
> +uint16_t mgmt_evt_get_index(uint32_t event)
Fixed

2023-06-19 10:44 UTC, nordicjm commented on include/zephyr/mgmt/mcumgr/mgmt/callbacks.h
> +	MGMT_EVT_OP_IMG_MGMT_DFU_WRITE_COMPLETE	= MGMT_DEF_EVT_OP_ID(MGMT_EVT_GRP_IMG, 5),
Renamed

2023-07-11 15:27 UTC, de-nordic approved these changes

2023-07-12 14:53 UTC, MarekPieta commented on subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
> +			(void)mgmt_callback_notify(MGMT_EVT_OP_IMG_MGMT_DFU_WRITE_COMPLETE, NULL,
Discussed offline. We can leave it as is.

2023-07-12 15:02 UTC, MarekPieta approved these changes

2023-07-20 14:25 UTC, nordicjm commented
@fabiobaltieri could you please merge?

2023-07-20 14:55 UTC, fabiobaltieri approved these changes

2023-07-20 14:55 UTC, merged