boards: arm: mimxrt1170_evkb: add RT1170 EVKB
zephyrproject-rtos/zephyr pull request #59212
Opened 2023-06-13 23:18 UTC by danieldegrasse

Add RT1170 EVKB definition to Zephyr. This board is similar to the
RT1170 EVK, but uses a different quadspi flash chip, and includes
an audio connector as well as an additional display connection.

The following features have been tested with this port:
The following features have been verified to function on this board:
- GPIO 
- COUNTER
- CAN
- SPI
- I2C
- PWM
- ADC
- UART 
- DMA
- GPT
- WATCHDOG
- USB
- HWINFO
- DISPLAY
- CAAM
- SDHC
- Multicore boot

The following features are not currently tested/enabled:
- ENET (This board uses an unsupported PHY)
- SAI (Should work, but requires board modification to verify)
- ACMP (Untested)
- FLEXSPI (This board's flash chip is not supported)

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

2023-06-15 14:39 UTC, DerekSnell requested changes
Hi @danieldegrasse ,
Thank you for contributing this board.  Overall, this LGTM.  However, we also need to update the board doc page, and clarify both boards are supported.  Since these are in the same board folder and same doc page, we should be clear which features are supported on both boards.  Perhaps the Supported Features table should have separate columns: one for the new `EVKB`  revision, and another the original `EVK` revision.

Thanks

2023-06-15 14:39 UTC, DerekSnell commented on samples/subsys/ipc/openamp/boards/mimxrt1170_evkb_cm7.conf
> +CONFIG_INCLUDE_REMOTE_DIR=y
```suggestion
#
# Copyright 2023, NXP
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_INCLUDE_REMOTE_DIR=y
```

2023-06-15 14:39 UTC, DerekSnell commented on samples/subsys/ipc/openamp/remote/boards/mimxrt1170_evkb_cm4.conf
> +CONFIG_BUILD_OUTPUT_INFO_HEADER=y
```suggestion
#
# Copyright 2023, NXP
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_BUILD_OUTPUT_INFO_HEADER=y
```

2023-06-22 21:18 UTC, danieldegrasse commented
> 

Hi @danieldegrasse ,
Thank you for contributing this board. Overall, this LGTM. However, we also need to update the board doc page, and clarify both boards are supported. Since these are in the same board folder and same doc page, we should be clear which features are supported on both boards. Perhaps the Supported Features table should have separate columns: one for the new EVKB revision, and another the original EVK revision.

Thanks

Thanks for highlighting this @DerekSnell. I have added a table as you suggested, and tracked the status of features on each board. I have also added a "(M7)" specifier for any features that are only validated on the M7 core.

2023-06-26 10:06 UTC, DerekSnell approved these changes
LGTM, @danieldegrasse .  Thanks for updating the doc page

2023-06-26 14:07 UTC, mmahadevan108 commented on samples/drivers/display/boards/mimxrt1170_evkb_cm7.conf
> +CONFIG_HEAP_MEM_POOL_SIZE=4194304
WHy is this changed needed for EVKB and not EVK?

2023-06-26 14:22 UTC, decsny approved these changes

2023-06-29 19:05 UTC, merged