scripts: ci: check_compliance: add a no-modules Kconfig check
zephyrproject-rtos/zephyr pull request #59210
Opened 2023-06-13 17:49 UTC by fabiobaltieri

Hi, adding a CI check to ensure symbols used in the main repository are defined. Generates warnings like:

```
Running KconfigBasicNoModules tests in /home/fabiobaltieri/zephyrproject/zephyr ...
warning: undefined symbol ZEPHYR_LIBLC3_MODULE:

- Referenced at modules/Kconfig:66:

comment "liblc3 module not available."
        depends on !ZEPHYR_LIBLC3_MODULE
warning: undefined symbol ZEPHYR_CHRE_MODULE:

- Referenced at modules/Kconfig:96:

comment "CHRE module not available."
        depends on !ZEPHYR_CHRE_MODULE
warning: undefined symbol ZEPHYR_PICOLIBC_MODULE:

- Referenced at lib/libc/picolibc/Kconfig:6:

config PICOLIBC_USE_MODULE
        bool "Picolibc as module"
        default y if "" != "zephyr"
        depends on ZEPHYR_PICOLIBC_MODULE && !GLIBCXX_LIBCPP && PICOLIBC
        help
          Use picolibc module instead of picolibc included with toolchain.
          This is enabled by default for toolchains other than the Zephyr
          SDK.
1 checks failed
```

Found few symbols with this, fixed those too.

2023-06-19 07:21 UTC, MariuszSkamra approved these changes

2023-06-20 17:58 UTC, jeremybettis approved these changes

2023-06-21 07:29 UTC, carlescufi requested changes
Thanks, this LGTM in principle but would like @tejlmand to review it to ensure he's happy with this, given his involvement with modules and Kconfig.

2023-07-03 11:16 UTC, fabiobaltieri commented
@tejlmand ping :-)

2023-07-05 07:06 UTC, tejlmand approved these changes
lgtm

2023-07-05 07:10 UTC, carlescufi approved these changes

2023-07-05 07:11 UTC, merged