manifest: openthread: Regular openthread upmerge to `6d55738`
zephyrproject-rtos/zephyr pull request #59298
Opened 2023-06-16 07:21 UTC by canisLupus1313

Openthread upmerge to `6d55738`. Includes implementing of:
- `OPENTHREAD_CONFIG_RADIO_STATS_ENABLE`
- `OPENTHREAD_CONFIG_BORDER_ROUTING_DHCP6_PD_ENABLE`

2023-06-16 07:26 UTC, pdgendt requested changes

2023-06-16 07:26 UTC, pdgendt commented on modules/openthread/Kconfig.features
> +	bool "Dhcpv6 pd support in border routing"
Nit:
```suggestion
	bool "DHCPv6 pd support in border routing"
```

2023-06-16 07:26 UTC, pdgendt commented on modules/openthread/platform/openthread-core-zephyr-config.h
> +#endif
Inverse logic and copy-paste issue?

```suggestion
#ifdef CONFIG_OPENTHREAD_RADIO_STATS_ENABLE
#define OPENTHREAD_CONFIG_RADIO_STATS_ENABLE CONFIG_OPENTHREAD_RADIO_STATS_ENABLE
#endif
```

2023-06-16 07:37 UTC, pdgendt reviewed
Some compliance checks still need to be addressed.

2023-06-16 07:42 UTC, edmont approved these changes

2023-06-16 07:42 UTC, edmont commented on modules/openthread/Kconfig.features
> +	bool "DHCPv6 pd support in border routing"
```suggestion
	bool "DHCPv6-PD support in border routing"
```

2023-06-16 08:16 UTC, pdgendt commented on modules/openthread/platform/openthread-core-zephyr-config.h
> + * @def OPENTHREAD_CONFIG_RADIO_STATS
Nit:
```suggestion
/**
 * @def OPENTHREAD_CONFIG_RADIO_STATS
```

2023-06-16 09:55 UTC, pdgendt approved these changes, later dismissed

2023-06-16 11:15 UTC, rlubos commented
Seems that Babble sim tests have some trouble running. The devices start to communicate eventually, but there is some disturbance early in the test, due to both devices forming own mesh early (i. e. starting as `Leader`). One of them degrades to a `Child` after a while and joins the other mesh.

I'm not really sure why would it start to manifest on this PR though. @aescolar I'm curious, would it be possible to delay the execution of the second device for a few seconds, so that the first one has a chance to form a mesh before the other starts? Ideally, we could start the server device, wait a few seconds, and then start the client, which would then join the already existing mesh, instead of forming its own.

2023-06-16 11:43 UTC, aescolar commented
> ... @aescolar I'm curious, would it be possible to delay the execution of the second device for a few seconds, so that the first one has a chance to form a mesh before the other starts? Ideally, we could start the server device, wait a few seconds, and then start the client, which would then join the already existing mesh, instead of forming its own.

Yes, certainly, just add  `-start_offset=2e6`  to the second device command line to delay it by 2 seconds (2 million µs) of simulated time

2023-06-19 09:13 UTC, pdgendt approved these changes, later dismissed

2023-06-19 09:14 UTC, pdgendt commented on tests/bsim/net/sockets/echo_test/tests_scripts/echo_test_802154.sh
> +  -v=${verbosity_level} -s=${simulation_id} -start_offset=2e6 -d=0 -RealEncryption=1 \
Create a separate commit for this change, please.

2023-06-19 11:21 UTC, pdgendt approved these changes, later dismissed

2023-06-19 14:50 UTC, rlubos commented
@aescolar Any clue why are the Babblesim tests for OT failing now? The packet exchange rate seems decent now, but the test fails with:
> d_00: @00:00:23.998575  main: The TESTCASE FAILED with return code 1

2023-06-20 06:57 UTC, aescolar commented
Due to the 2s delay, the testcase just did not have time to pass.
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bsim/net/sockets/echo_test/src/echo_test.c#L18
(There was only 1 second margin before).
You can just increase the maximum simulation duration by 5 seconds:

```diff
diff --git a/tests/bsim/net/sockets/echo_test/tests_scripts/echo_test_ot.sh b/tests/bsim/net/sockets/echo_test/tests_scripts/echo_test_ot.sh
index 3516426122..a5b1f856d4 100755
--- a/tests/bsim/net/sockets/echo_test/tests_scripts/echo_test_ot.sh
+++ b/tests/bsim/net/sockets/echo_test/tests_scripts/echo_test_ot.sh
@@ -25,6 +25,6 @@ Execute ./bs_${BOARD}_samples_net_sockets_echo_server_prj_conf_overlay-ot_conf\
   -v=${verbosity_level} -s=${simulation_id} -d=1 -RealEncryption=1 \
 
 Execute ./bs_2G4_phy_v1 -v=${verbosity_level} -s=${simulation_id} \
-  -D=2 -sim_length=26e6 -argschannel -at=40 -argsmain $@
+  -D=2 -sim_length=30e6 -argschannel -at=40 -argsmain $@
 
 wait_for_background_jobs #Wait for all programs in background and return != 0 if any fails
```

2023-06-22 10:24 UTC, pdgendt submitted a review, later dismissed

2023-06-22 11:07 UTC, rlubos commented
Nice, it seems Babblesim tests are finally passing. Thanks @canisLupus1313 for addressing the problem and thanks @aescolar for your support.

2023-06-22 11:09 UTC, rlubos commented on west.yml
> +      revision: pull/97/head
`6d557383e8bc8654f813674e8631c2e56b8e70d0`

2023-06-22 11:39 UTC, canisLupus1313 commented on west.yml
> +      revision: pull/97/head
done

2023-06-22 11:41 UTC, pdgendt approved these changes

2023-06-22 11:47 UTC, rlubos approved these changes

2023-06-23 07:20 UTC, merged