drivers: i2c: nrf5: Make pins for Port 1 configurable
zephyrproject-rtos/zephyr pull request #5957
Opened 2018-02-02 14:14 UTC by tkln

CONFIG_I2C_NRF5_GPIO_SCA_PIN and CONFIG_I2C_NRF5_GPIO_SCL_PIN are
replaced with port specific versions. Board defconfigs relying on the
original names are updated. The driver is also modified to pass the
configure values to registers.

Signed-off-by: Aapo Vienamo <aapo.vienamo@iki.fi>

2018-02-02 20:27 UTC, tkln commented
Could you to take a look @carlescufi ?

2018-02-05 08:53 UTC, anangl commented
In general, it looks good to me.
But I think we should also take the opportunity and correct the typo in the SDA pin naming. It should not be SCA.

2018-02-05 08:54 UTC, anangl requested changes
In general, it looks good to me.
But I think we should also take the opportunity and correct the typo in the SDA pin naming. It should not be SCA.

2018-02-05 15:59 UTC, anangl approved these changes

2018-02-05 16:01 UTC, carlescufi approved these changes

2018-02-05 16:01 UTC, carlescufi commented
@tkln can you please rebase this on top of the latest master?

2018-02-05 21:12 UTC, merged