[drivers]: [modem]: Fixes Dereference before null check #5…
zephyrproject-rtos/zephyr pull request #59625
Opened 2023-06-22 15:16 UTC by jaiiarora

Fixes Dereference before null check.

Fixes #529532

2023-06-22 15:26 UTC, rerickson1 requested changes

2023-06-22 15:26 UTC, rerickson1 commented on drivers/modem/gsm_ppp.c
> +	int ret;
Variable definitions should always be at the top of the function.
Assigning values can be done later in the function.

2023-06-22 16:07 UTC, rerickson1 commented
Commits need to be squashed. Is there a useful change here? Per the PR there are no net changes now...

2023-08-18 06:00 UTC, kartben commented
ping @jaiiarora

2023-09-28 15:43 UTC, kartben commented
Hello @jaiiarora  -- could you please provide feedback here?

2023-10-26 15:31 UTC, kartben commented
@jaiiarora , will you be able to look at this?

2023-10-26 15:40 UTC, jaiiarora commented
Hi @kartben , Sorry for my late reply. Sure I will look into this

2023-11-21 19:04 UTC, jaiiarora commented
Hi @kartben , Can you let me know the issue number. I aam not able to find it hence not able to make progress

2023-11-21 19:20 UTC, closed without merging

2023-11-21 19:20 UTC, kartben commented
It looks like you were trying to fix https://github.com/zephyrproject-rtos/zephyr/issues/59532, but this has been taken care of already

2023-11-21 19:20 UTC, kartben commented
@jaiiarora Your PR was awkward as there were two commits cancelling one another, hence why it wasn't reviewed in time. I hope you will consider submitting other PRs in the future!

2023-11-21 19:22 UTC, jaiiarora commented
Sure