net: lwm2m: update internal API select_writer()
zephyrproject-rtos/zephyr pull request #5970
Opened 2018-02-05 09:46 UTC by rbtchc

As per review of PR #5893, this is a follow up patch to update
select_writer() API to match the behavior of select_reader() API.

Quote from OMA-TS-LightweightM2M-V1_0_1-20170704-A. 8.2.5
"An Object Instance or Resource is Read by sending a CoAP GET to the
 corresponding path. The response includes the value in the
 corresponding Plain Text, Opaque, TLV or JSON format according to
 the specified Content-Format (see section 6.4).The request MAY
 specify an Accept option containing the preferred Content-Format
 to receive. When the specified Content-Format is not supported by
 the LwM2M Client, the request MUST be rejected."

Therefore, we does not attempt to assign a content-format when the
requested one is not supported. Instead, we return an error code.

Signed-off-by: Robert Chou <robert.ch.chou@acer.com>

2018-02-07 06:47 UTC, mike-scott requested changes
Couple of nits, but patch overall looks good.

2018-02-07 10:20 UTC, rbtchc commented on subsys/net/lib/lwm2m/lwm2m_engine.c
> +	return 0;
Update commit subject to "net: lwm2m: update internal API select_writer() and select_reader()"

And add description below to the commit message
> 0 is returned when reader or writer has been successfully selected by select_reader() or select_writer()

2018-02-07 12:33 UTC, rbtchc commented on subsys/net/lib/lwm2m/lwm2m_engine.c
> -		SYS_LOG_ERR("Unknown Accept type %u, using LWM2M plain text",
added back the warning message

2018-02-07 21:58 UTC, mike-scott approved these changes
LGTM

2018-02-08 02:51 UTC, rbtchc commented
@jukkar please help to review the PR. Thanks.

2018-02-08 03:12 UTC, nashif approved these changes

2018-02-08 03:12 UTC, merged