linker: devicetree_regions: Infer VMA when defining section
zephyrproject-rtos/zephyr pull request #60022
Opened 2023-07-04 17:42 UTC by talih0

Explicitly setting the start of VMA can intefere if the memory region was used in another section, for example via zephyr_code_relocate().

2023-07-05 14:42 UTC, carlocaione requested changes
I'm not following here. What do you mean `if the memory
region was used in another section`? Can you make a practical example?

2023-07-05 15:06 UTC, talih0 commented
I can try to work on an example, but essentially

if we define a memory region:

 test_sram: sram@20010000 {
        compatible = "zephyr,memory-region", "mmio-sram";
        reg = < 0x20010000 0x1000 >;
        zephyr,memory-region = "FOOBAR";
 };

then relocate some variables to it with:
zephyr_code_relocate(LIBRARY xxx LOCATION FOOBAR_DATA)

^ this will create linker snippets incrementing the VMA in FOOBAR.

But, then the VMA will then get reset to its original value via the device tree include: 

FOOBAR 0x20010000 (NOLOAD) :
 {
         __FOOBAR_start = .;
         KEEP(*(FOOBAR))
         KEEP(*(FOOBAR.*))
         __FOOBAR_end = .;
 } > FOOBAR

2023-07-05 21:31 UTC, carlocaione commented
ok, the fix is possibly fine but I want to understand better the use case. Is this something that can be a problem in a real project?

This is a problem when you are using the `FOOBAR` section in your example for something else besides being the target of the relocation, for example when in the `FOOBAR` section you are placing some other variable, because in this case the variable is going to overwrite part of the relocated data. If you are using `FOOBAR` only as target of the relocation, the reset of the VMA should not be a problem.

Is this your case? What are you using the section for?

2023-07-06 13:08 UTC, talih0 commented
> ok, the fix is possibly fine but I want to understand better the use case. Is this something that can be a problem in a real project?
> 
> This is a problem when you are using the `FOOBAR` section in your example for something else besides being the target of the relocation, for example when in the `FOOBAR` section you are placing some other variable, because in this case the variable is going to overwrite part of the relocated data. If you are using `FOOBAR` only as target of the relocation, the reset of the VMA should not be a problem.
> 
> Is this your case? What are you using the section for?

yes, that's right. Using a relocation by itself will not cause any problems (nothing will be placed in the section after the reset of the VMA).

In my case, I'm working on an ethernet driver for XMC47xxx, where some of the variables must be in a specific memory region for the DMA to work properly. I'm implementing this with:
static uint8_t __aligned(4) rx_buf[CONFIG_ETH_XMC4XXX_NUM_RX_BUF][ETH_RX_BUF_SIZE] __GENERIC_SECTION(MEM_REGION);

This creates problems when any application code tries to relocate memory with zephyr_code_relocate() cmake function.

2023-07-06 13:51 UTC, carlocaione approved these changes
Quite a corner case this one.

2023-07-20 20:18 UTC, talih0 commented
@tejlmand, could you have a look when you have a moment pls

2023-08-01 11:53 UTC, talih0 commented
ping

2023-08-01 16:09 UTC, carlescufi approved these changes

2023-08-01 16:09 UTC, merged