drivers: udc: add option to allocate EP buffer with external storage
zephyrproject-rtos/zephyr pull request #60182
Opened 2023-07-09 12:34 UTC by benedekkupper

Currently there is no way to save on buffer space e.g. in case there is large read-only data to be sent to the host. Adding this API allows optimizing for such scenarios.

2023-07-10 08:31 UTC, tmon-nordic approved these changes, later dismissed

2023-07-17 05:37 UTC, tmon-nordic approved these changes

2023-07-17 14:21 UTC, jfischer-no requested changes
This is a worthy addition, but we cannot use external buffer here. The buffer has always to be in RAM and aligned. You could add an alignment check, but this is still the wrong layer to add that kind of functionality. Some other parts are missing as well.

2023-07-20 23:01 UTC, benedekkupper commented
> The buffer has always to be in RAM and aligned.

I understand the alignment requirement, that is something that should be required by the API (mentioned in the comment, and assert()-ed). As for the RAM placement, I already got this working for nRF, so I'm assuming you are talking about the NXP kinetis chipset that requires this. I know for a fact that those MCUs also allow sending data from flash, it's only a matter of configuring the memory controller to allow flash access to the USB controller. So I'd consider this a bug rather than a feature.

> this is still the wrong layer to add that kind of functionality

Are you talking about the MR in general here? I admit that this MR is not targeting to solve a need from the application side, I need this change so [my USB device stack](https://github.com/IntergatedCircuits/c2usb) can run on top of the UDC drivers. You might ask if I have such nice functionality in this other stack, why not implement them for Zephyr as well instead? a) because it's waaay more effort, than just patching c2usb together with UDC b) because the c2usb can serve baremetal MCU designs as well

> Some other parts are missing as well.

Can you elaborate on what's missing in order to for such changes to be accepted?

2023-07-24 19:44 UTC, benedekkupper commented
> This is exactly why it needs to be in RAM and aligned. Just to not have problems with different controllers being able to read from flash or not, buffer requirements, flash controller configuration, and so on. This will not change.

Is there really such a platform that completely prohibits transfers from flash though? Because each platform anyway has its own UDC driver, why not assign the responsibility of enabling access to the flash in the corresponding UDC driver? Also, this `net_buf_alloc_with_data` API (which is already present and being used in other parts of Zephyr) is not only for the use case of sending RO data, but for any kind of externally supplied data buffer.

> The UDC API is primary for USB device support in Zephyr RTOS. Third-party device stack requirements are not essential to the UDC API.

I fully understand this, and I wasn't entirely clear before, this is not a requirement for my stack, as all this patch does is eliminate some `memcpy()` and wasted RAM. - But this patch is also about so much more:
1. It can allow USB device applications to manage their own memory, which is crucial for allowing flexible composite USB device designs. Having a shared RAM pool creates hidden coupling between the functions that make up a composite design, so that for each combination of functions a different pool size has to be found, after painfully crafting a worst-case usage scenario for each combination (unless we can afford to spend a lot on extra RAM).
2. It can save a lot of RAM space in cases like HID where there is one big constant transfer (the HID report descriptor) that is often several hundreds of bytes, while the rest of the communication is barely reaching tens of bytes.

However it is not my intention to challenge the design of Zephyr's USB device stack, this patch simply exposes an available internal API to a middleware layer that is not used by the applications directly, so I don't see how it can cause any harm.

2023-07-24 21:02 UTC, jfischer-no commented
> > This is exactly why it needs to be in RAM and aligned. Just to not have problems with different controllers being able to read from flash or not, buffer requirements, flash controller configuration, and so on. This will not change.
> 
> Is there really such a platform that completely prohibits transfers from flash though? Because each platform anyway has its own UDC driver, why not assign the responsibility of enabling access to the flash in the corresponding UDC driver? Also, this `net_buf_alloc_with_data` API (which is already present and being used in other parts of Zephyr) is not only for the use case of sending RO data, but for any kind of externally supplied data buffer.

Yes, there are controllers that cannot handle buffers in flash. And under current conditions, we have the same behavior in all drivers. The advantage of passing few buffers directly from flash is greatly exaggerated. RAM buffers are needed anyway.

> 
> > The UDC API is primary for USB device support in Zephyr RTOS. Third-party device stack requirements are not essential to the UDC API.
> 
> I fully understand this, and I wasn't entirely clear before, this is not a requirement for my stack, as all this patch does is eliminate some `memcpy()` and wasted RAM. - But this patch is also about so much more:
> 
>     1. It can allow USB device applications to manage their own memory, which is crucial for allowing flexible composite USB device designs. Having a shared RAM pool creates hidden coupling between the functions that make up a composite design, so that for each combination of functions a different pool size has to be found, after painfully crafting a worst-case usage scenario for each combination (unless we can afford to spend a lot on extra RAM).
> 

Using the pool provided by the common part of UDC is not a requirement for applications or classes. You didn't look at it, did you?
How much is "a lot on extra RAM" in bathtubs?

>     2. It can save a lot of RAM space in cases like HID where there is one big constant transfer (the HID report descriptor) that is often several hundreds of bytes, while the rest of the communication is barely reaching tens of bytes.
> 
> 
> However it is not my intention to challenge the design of Zephyr's USB device stack, this patch simply exposes an available internal API to a middleware layer that is not used by the applications directly, so I don't see how it can cause any harm.

okay, can we close it?

2023-07-24 21:23 UTC, closed without merging