Bluetooth: Controller: Kconfig: Move BT_LL_SW_SPLIT specific configs
zephyrproject-rtos/zephyr pull request #60215
Opened 2023-07-10 13:29 UTC by rugeGerritsen

These configs are very tied to the BT_LL_SW_SPLIT implementation, so it makes sense that these are only visible when that link layer is used.

2023-07-11 00:34 UTC, cvinayak requested changes

2023-07-11 00:34 UTC, cvinayak commented on subsys/bluetooth/controller/Kconfig
> -	  addresses that can be filtered as duplicates while Extended Scanning.
Duplicate filtering is standard Bluetooth LE Feature, hence should be configurable in the top level Kconfig.

2023-07-12 05:48 UTC, cvinayak approved these changes

2023-07-27 07:47 UTC, kruithofa approved these changes

2023-07-27 08:20 UTC, carlescufi approved these changes

2023-07-27 08:20 UTC, merged