samples: net: echo_client/server: Fix two issues with the samples
zephyrproject-rtos/zephyr pull request #60354
Opened 2023-07-13 13:20 UTC by rlubos

I've encountered two issues with the echo samples when I was testing them on a new platform, details in the commit messages.

2023-07-13 19:54 UTC, jukkar requested changes

2023-07-13 19:54 UTC, jukkar commented on samples/net/sockets/echo_client/src/echo-client.c
> +	}
Could we do it same way as how `init_vlan()` is "guarded", so having a dummy init function in `common.h`

2023-07-17 20:15 UTC, jukkar approved these changes

2023-07-17 21:21 UTC, nashif approved these changes

2023-07-17 21:21 UTC, merged