Privacy whitelist and resolving list handling
zephyrproject-rtos/zephyr pull request #604
Opened 2017-06-25 16:31 UTC by carlescufi

2017-06-25 20:28 UTC, cvinayak requested changes

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
Why int? parameter to filter_insert is u8_t.

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
Why int?

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	/* Populate filter from wl peers */
Missing blank line

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	if (i >= 0) {
Missing blank line.

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +		if (!rl_enable || j == IDX_NONE || !rl[j].pirk || rl[j].dev) {
Missing blank line.

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	/* No whitelist: populate filter from rl peers */
Missing blank line

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +		if (!rl_enable || j == IDX_NONE || !rl[j].pirk || rl[j].dev) {
rl_enable should not be checked inside loop.

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +void ll_filters_update(int adv_fp, int scan_fp)
Have two different functions, saves on param passing and program stack usage.

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	for (i = 0; i < CONFIG_BLUETOOTH_CONTROLLER_RL_SIZE; i++) {
blank line

2017-06-25 20:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	i = ll_rl_find(id_addr->type, id_addr->a.val);
lets have ll_rl_find(type, addr, *free_idx); so that if not found use free_idx to insert device. Saves a subsequest loop to find empty slot.

2017-06-26 08:13 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_adv.c
> +		ll_filters_update(ll_adv.filter_policy, -1);
no, we are updating 2 filters

2017-06-26 08:14 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_filter.h
> +void ll_filters_update(int adv_fp, int scan_fp);
Well, logically this fits better together: a single function to update the filters whenever activity starts. I don't mind splitting this up though, I'll take a look

2017-06-26 08:16 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_scan.c
> +	u8_t  filter_policy:2;
Yes, they are 2 bits in the structures and they use u8_t as parameters

2017-06-26 08:18 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
I will change the parameter, I prefer to use ints whenever no specific width is required

2017-06-26 08:33 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +		if (!rl_enable || j == IDX_NONE || !rl[j].pirk || rl[j].dev) {
rl_enable is only modified in thread mode by cooperative threads

2017-06-26 08:51 UTC, carlescufi commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
Because I don't care about the width

2017-06-26 09:27 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
ok. agreed.

2017-06-26 09:28 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +	int index;
ok. agreed.

2017-06-26 09:35 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_filter.c
> +		if (!rl_enable || j == IDX_NONE || !rl[j].pirk || rl[j].dev) {
if you have the check for rl_enable outside the loop, you just need to loop i times calling filter_insert without carrying for reading j. This is just a optimization, more code, but faster by few cycles for each address.

2017-06-26 09:35 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/ll_scan.c
> +	u8_t  filter_policy:2;
ok.

2017-06-26 12:04 UTC, cvinayak approved these changes

2017-06-26 12:04 UTC, jhedberg approved these changes

2017-06-26 12:04 UTC, merged