Kconfig: Provide name to orphan configuration choice symbol
zephyrproject-rtos/zephyr pull request #60563
Opened 2023-07-19 09:03 UTC by erwango

Kconfig choice section for LINKER_OPRHAN configuration has no name. This prevents configuring a default value in .defconfig files and constrain to set in _defconfig /.prj files.
Then it is not possible to generalize this setting to a whole set of boards (soc series for instance) or make it dependent on another symbol. Provide it a name to add this flexibility.

2023-07-19 10:30 UTC, fabiobaltieri submitted a review, later dismissed

2023-07-19 10:31 UTC, fabiobaltieri commented
```
file: Kconfig.zephyr
Area matches: {}
labels: set()
collab: []
Submitted by: erwango
candidate maintainers: {}
Picked maintainer: None (0.00% ownership)
```

Feels like this should belong to some area...

2023-07-19 11:48 UTC, erwango commented
> ```
> file: Kconfig.zephyr
> Area matches: {}
> labels: set()
> collab: []
> Submitted by: erwango
> candidate maintainers: {}
> Picked maintainer: None (0.00% ownership)
> ```
> 
> Feels like this should belong to some area...

Right, there's a Kconfig subsystem. I'll push a PR to add it.

2023-07-19 12:14 UTC, erwango commented
See https://github.com/zephyrproject-rtos/zephyr/pull/60576

2023-07-27 09:39 UTC, nordicjm requested changes

2023-07-27 09:39 UTC, nordicjm commented on Kconfig.zephyr
> +choice LINKER_OPRHAN_CONFIGURATION
typo

2023-07-27 13:20 UTC, erwango commented on Kconfig.zephyr
> +choice LINKER_OPRHAN_CONFIGURATION
Right, fixed. Thanks

2023-07-27 13:24 UTC, nordicjm approved these changes

2023-07-27 13:59 UTC, fabiobaltieri approved these changes

2023-07-27 13:59 UTC, merged