Fix 59548
zephyrproject-rtos/zephyr pull request #60650
Opened 2023-07-20 16:54 UTC by dleach02

2023-07-20 16:56 UTC, danieldegrasse commented
It seems you may have a stray commit in this pr...

2023-07-20 16:59 UTC, dleach02 commented
Yes, noticed it... fixed

2023-07-20 17:09 UTC, danieldegrasse approved these changes

2023-07-20 18:52 UTC, nashif requested changes, later dismissed
PR title is too cryptic

2023-07-20 21:35 UTC, fabiobaltieri approved these changes

2023-07-21 10:55 UTC, merged

2023-07-21 10:55 UTC, fabiobaltieri commented
I'm surprised we don't have an AI that automatically summarizes multi-commit PRs already.

2023-07-26 22:10 UTC, dleach02 commented
yeah, the problem was that I initially had a stray commit so github grabbed things strangly. I fixed it but it didn't fix the title :-(