[Zephyr]: OpenOCD User Support Added
zephyrproject-rtos/zephyr pull request #60703
Opened 2023-07-21 19:08 UTC by dey-r

User guide is updated with support for OpenOCD using ModusToolbox

2023-07-21 20:15 UTC, ifyall approved these changes

2023-07-21 21:07 UTC, thedjnK requested changes
This is not the right way to title a PR, please read and follow https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

2023-07-21 21:37 UTC, dey-r commented
Reviewed changes updated

2023-08-09 13:13 UTC, npal-cy approved these changes

2023-08-09 13:44 UTC, merged