[Zephyr]: Masking added to ISR
zephyrproject-rtos/zephyr pull request #60704
Opened 2023-07-21 20:30 UTC by dey-r

Masking is added so that WDT is not invoked multiple times

2023-07-21 20:32 UTC, ifyall approved these changes

2023-07-21 21:07 UTC, thedjnK requested changes
This is not the right way to title a PR, please read and follow https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines e.g. something like `drivers: watchdog: wdt_ifx_cat1: some description`

2023-07-21 21:28 UTC, thedjnK commented
You need to amend the commit and change the actual commit title

2023-08-16 18:42 UTC, carlescufi approved these changes

2023-08-16 18:42 UTC, merged