toolchain: gcc: fix GCC < 11.0.0 build with -Wundef
zephyrproject-rtos/zephyr pull request #60755
Opened 2023-07-24 20:00 UTC by idruzhinin

toolchain: gcc: fix GCC < 11.0.0 build with -Wundef

When building using GCC version < 11.0.0, TOOLCHAIN_CLANG_VERSION is not
yet defined in gcc.h. Nevertheless, it's still needed due to reuse of
gcc.h in llvm.h.

Guard access to TOOLCHAIN_CLANG_VERSION to fix that.

2023-07-24 20:20 UTC, dcpleung requested changes
`llvm.h` includes `gcc.h`. If you wants to remove `TOOLCHAIN_CLANG_VERSION` from `gcc.h`, you will need to define `FUNC_NO_STACK_PROTECTOR` under `llvm.h`, and make `gcc.h` to NOT re-define it.

2023-07-24 21:41 UTC, dcpleung approved these changes, later dismissed

2023-07-25 17:17 UTC, idruzhinin commented
Alternatively, the diff below also work I think, if that's look nicer:
```
diff --git a/include/zephyr/toolchain/gcc.h b/include/zephyr/toolchain/gcc.h
index f81cb0a309..089ee4c9ca 100644
--- a/include/zephyr/toolchain/gcc.h
+++ b/include/zephyr/toolchain/gcc.h
@@ -633,7 +633,8 @@ do {                                                                    \
  *
  * @note Only supported for GCC >= 11.0.0 or Clang >= 7.
  */
-#if (TOOLCHAIN_GCC_VERSION >= 110000) || (TOOLCHAIN_CLANG_VERSION >= 70000)
+#if (TOOLCHAIN_GCC_VERSION >= 110000) || \
+    (defined(TOOLCHAIN_CLANG_VERSION) && (TOOLCHAIN_CLANG_VERSION >= 70000))
 #define FUNC_NO_STACK_PROTECTOR __attribute__((no_stack_protector))
 #else
 #define FUNC_NO_STACK_PROTECTOR
```

2023-09-29 13:44 UTC, kartben commented
Ping @idruzhinin :)

2023-09-29 14:00 UTC, idruzhinin commented
sorry, was tide up recently and forgot I had that one in queue
could you specify which version of the patch you'd prefer - the one in PR or alternative (from the comment above)?

2023-09-29 17:19 UTC, dcpleung approved these changes

2023-11-16 16:37 UTC, kartben commented
@tejlmand @stephanosio can you please have a look?

2023-11-24 12:47 UTC, tejlmand approved these changes

2023-11-24 13:45 UTC, merged