Bluetooth: Mesh: Add delay for Proxy Service registration
zephyrproject-rtos/zephyr pull request #60787
Opened 2023-07-25 14:06 UTC by PavelVPV

When settings_load() is not called from system workqueue, but still called from a cooperative thread, rescheduling during the settings loading can wake up system workqueue and try to register the Mesh Proxy Service, which can not be allowed yet. This is the case for bsim tests.

Postpone registering the service with some small timeout.

2023-07-26 07:35 UTC, alxelax requested changes

2023-07-26 07:35 UTC, alxelax commented on subsys/bluetooth/mesh/proxy_srv.c
> +		/* settings_load() didn't finish yet. Try again. */
What if gatt service cannot be registered for another reason? Will they forever invoke each other?

2023-07-26 07:35 UTC, alxelax commented on tests/bsim/bluetooth/mesh/src/test_advertiser.c
> +		ASSERT_TRUE(delta >= (interval - 1) &&
Should diff be more than 1 msec? 5?
I saw about 3 msec here for SDC

2023-07-26 08:08 UTC, alxelax approved these changes

2023-07-27 07:29 UTC, m-alperen-sener approved these changes

2023-08-14 08:48 UTC, Andrewpini approved these changes

2023-08-14 18:09 UTC, merged