scripts: set_assignee: support areas with multiple maintainers
zephyrproject-rtos/zephyr pull request #60798
Opened 2023-07-25 19:19 UTC by fabiobaltieri

Rework the set_assignees script to support ares with multiple maintainers. Internally key the maint dictionary by the maintainer set instead of the individual maintaine and then process the individual usernames at the end, assigning to all of them rather than only to the first one.

The rest of the logic is unchanged, but the special case of submitter == maintainer is removed, as that does not seem to be relevant anyway.

Example run:

$ ./scripts/set_assignees.py -v -y -P 54286
...
candidate maintainers: {('fabiobaltieri', 'keith-zephyr'): 7} Picked maintainer: ('fabiobaltieri', 'keith-zephyr') (50.00% ownership)

2023-07-25 19:22 UTC, fabiobaltieri commented
Followup from https://github.com/zephyrproject-rtos/zephyr/issues/60316

2023-08-24 17:52 UTC, fabiobaltieri commented
Hey @nashif we talked about this at dev meeting, were thinking, how about assigning a random person from areas with multiple maintainers instead?

2023-08-24 17:53 UTC, nashif commented
> Hey @nashif we talked about this at dev meeting, were thinking, how about assigning a random person from areas with multiple maintainers instead?

not sure what you mean..

2023-08-24 17:56 UTC, fabiobaltieri commented
> not sure what you mean..

If the script finds an area with more than one maintainer, instead of always assigning the RP to the first one in the list (what it does now), assign to a random one from the area

2023-08-24 18:03 UTC, nashif commented
> If the script finds an area with more than one maintainer, instead of always assigning the RP to the first one in the list (what it does now), assign to a random one from the area

sure, but that is not the issue, I was referring above to issues with multiple lables of multiple areas, which will end up in the script assigning to multiple maintainers of multiple areas. 

Bottom like is, we need to try and  end up with 1 assignee per issue.

2023-08-24 18:17 UTC, fabiobaltieri commented
> > If the script finds an area with more than one maintainer, instead of always assigning the RP to the first one in the list (what it does now), assign to a random one from the area
> 
> sure, but that is not the issue, I was referring above to issues with multiple lables of multiple areas, which will end up in the script assigning to multiple maintainers of multiple areas.
> 
> Bottom like is, we need to try and end up with 1 assignee per issue.

That was https://github.com/zephyrproject-rtos/zephyr/pull/61513, this is the one where I was changing how to handle PR assignment.

2023-08-24 22:36 UTC, nashif commented
> That was #61513, the one with the "assign issue" feature, this is the one where I was changing how to handle PR assignment. I also got the multi-label story story sorted btw, see [#61513 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/61513#issuecomment-1690378728).

oops, too many PR, got me confused. Random is ok and (not submitter if submitter is maintainer, which we have now)

2023-08-24 22:39 UTC, nashif commented
> The rest of the logic is unchanged, but the special case of submitter == maintainer is removed, as that does not seem to be relevant anyway.

why is this not relevant? 

If A and B are maintainers, A submits a PR, it should be assigned to B. This is some we discussed and we agreed to follow.

2023-08-24 22:39 UTC, nashif requested changes

2023-08-24 22:39 UTC, nashif commented on scripts/set_assignees.py
> -        # if the submitter is the same as the maintainer, check if we have
This should stay.

2023-08-25 16:58 UTC, fabiobaltieri commented
> > The rest of the logic is unchanged, but the special case of submitter == maintainer is removed, as that does not seem to be relevant anyway.
> 
> why is this not relevant?
> 
> If A and B are maintainers, A submits a PR, it should be assigned to B. This is some we discussed and we agreed to follow.

Because I was changing the behavior to assign to all maintainers in the area anyway, so that made no difference.

Anyway, I was reworking this and I think this change would hit more corner cases, need to think more about this and I'd also like to restructure the file a bit to make it easier to understand. That means the scope would change anyway, I'll close this down and think the whole story through for a bit longer and probably reopen a new PR.

Thanks for the feedback!

2023-08-25 16:58 UTC, closed without merging