pm: fix some misuses of PM_STATE_ACTIVE
zephyrproject-rtos/zephyr pull request #60881
Opened 2023-07-27 12:50 UTC by gmarull

2023-07-27 12:51 UTC, erwango approved these changes

2023-07-27 12:59 UTC, tmleman approved these changes

2023-07-27 13:44 UTC, nashif requested changes
your commit message mentions `pm_exit_post_ops()`, you probably mean  `pm_state_exit_post_ops()`?

2023-07-27 13:55 UTC, gmarull commented
> your commit message mentions `pm_exit_post_ops()`, you probably mean `pm_state_exit_post_ops()`?

fixed

2023-07-27 14:10 UTC, nashif approved these changes

2023-07-28 05:53 UTC, ceolin approved these changes

2023-07-28 06:49 UTC, erwango approved these changes

2023-07-28 09:09 UTC, merged