Bluetooth: controller: Added MAX_TRANSPORT_LATENCY check
zephyrproject-rtos/zephyr pull request #60908
Opened 2023-07-28 08:32 UTC by lutb-ot

- Substituted asserts with check of validity of MAX_TRANSPORT_LATENCY
  - If invalid return BT_HCI_ERR_INVALID_PARAM

2023-07-28 10:03 UTC, thoh-ot commented
Could you add which EBQ test this fixes in the description?

2023-07-28 10:48 UTC, thoh-ot approved these changes

2023-07-31 08:11 UTC, kruithofa approved these changes

2023-07-31 09:18 UTC, mtpr-ot requested changes

2023-07-31 09:18 UTC, mtpr-ot commented on subsys/bluetooth/controller/ll_sw/ull_central_iso.c
> +				return BT_HCI_ERR_INVALID_PARAM;
After CIG/CIS creation, it is not allowed to return without cleaning up. This fix needs the cleanup code of #60205

2023-07-31 09:22 UTC, mtpr-ot commented on subsys/bluetooth/controller/ll_sw/ull_central_iso.c
> +				return BT_HCI_ERR_INVALID_PARAM;
And #60205 has the same fix.

2023-07-31 09:42 UTC, mtpr-ot commented
I have confirmed that #60205 also fixes HCI/CIS/BI-12-C. I suggest to close this PR.

2023-07-31 10:22 UTC, lutb-ot commented
> I have confirmed that #60205 also fixes HCI/CIS/BI-12-C. I suggest to close this PR.

As this problem is fixed by another PR, this PR will be closed. Thanks to those who have reviewed.

2023-07-31 10:22 UTC, closed without merging