Bluetooth: Improve ccc.cfg_changed
zephyrproject-rtos/zephyr pull request #61170
Opened 2023-08-04 13:51 UTC by alwa-nordic

In this PR we improve `_bt_gatt_ccc.value` to use a more natural definition: bitwise-or instead of max. We ensure that only currently connected peers affect this value, so that the definitions stays independent of the CCC lazy loading kconfig. We document the use case for `_bt_gatt_ccc.value` and clarify the documentation of `cfg_changed`.

Resolves: https://github.com/zephyrproject-rtos/zephyr/issues/55373

2023-08-08 08:58 UTC, jori-nordic commented
should you add/extend a test for this? ie subscribing to indications, checking the CCC value on the server and then doing the same for notifications

2023-08-14 12:07 UTC, Thalley requested changes

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/adv.c
> +int bt_testlib_adv_conn(struct bt_conn **conn, int id, uint32_t adv_options)
```suggestion
int bt_testlib_adv_conn(struct bt_conn **conn, uint8_t id, uint32_t adv_options)
```
Suggest to use same type here as the `bt_le_adv_param.id`

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/att_read.c
> +	}
Consider having a `if (!att_err)` with the other 3 `if` insides of it. Not really any reason to check `att_err` 3 times

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/att_read.c
> +	int api_err;
Ditto

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/att_read.c
> +	if (!api_err) {
```suggestion
	api_err = bt_gatt_read(ctx->conn, &ctx->params);
	if (!api_err) {
```

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/att_read.c
> +			   IF_ENABLED(CONFIG_BT_EATT, (.chan_opt = bearer))},
This looks like it could be indented differently to be more readable. If using clang-format, try adding `,` after the last element

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/att_read.c
> +			   IF_ENABLED(CONFIG_BT_EATT, (.chan_opt = bearer))},
Ditto

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/connect.c
> +	if (!api_err) {
```suggestion
	api_err = bt_conn_le_create(peer, BT_CONN_LE_CREATE_CONN, BT_LE_CONN_PARAM_DEFAULT, conn);
	if (!api_err) {
```

2023-08-14 12:07 UTC, Thalley commented on tests/bsim/bluetooth/host/gatt/ccc_value/testlib/scan.c
> +		.wanted_name = name,
The simple pointer assignment assignment here indicates that `name` shall have a long life time (at least until the device is found), but that isn't really that obvious from the header file. Suggest to either do a copy, or to somehow indicate in the header file that the `name` argument cannot just be stack allocated.

2023-10-29 00:29 UTC, closed without merging