Bluetooth: ISO: Fix HCI SDU length sent to controller
zephyrproject-rtos/zephyr pull request #61226
Opened 2023-08-07 13:57 UTC by rugeGerritsen

Fixes a race condition that could occur if the TX queue was read out before iso_has_ts was set. In that case, the provided buffer is of wrong length.

2023-08-07 14:44 UTC, jori-nordic requested changes

2023-08-07 14:44 UTC, jori-nordic commented on subsys/bluetooth/host/conn.c
>  	tx_data(buf)->iso_has_ts = has_ts;
you have to move the userdata size check from _send_cb to above this line.

2023-08-07 14:47 UTC, alwa-nordic commented on subsys/bluetooth/host/conn.c
>  	 * Size check for the user_data is already done in `bt_conn_send_cb`.
```suggestion
```
This is no longer the case. It was actually the reason for the hack of putting the setting of `iso_has_ts` below the call to `bt_conn_send_cb`. (To save some code ROM.) Should add a copy of the check from inside `bt_conn_send_cb` to this function?

2023-08-08 06:55 UTC, jori-nordic approved these changes

2023-08-08 07:23 UTC, alwa-nordic approved these changes

2023-08-11 07:12 UTC, merged