drivers: sensor: stm32 Vref sensor calibration on 12bit
zephyrproject-rtos/zephyr pull request #61377
Opened 2023-08-10 13:09 UTC by FRASTM

The Calibration value of the VRef on stm32U5 is acquired on 14Bit by ADC1 and should be adjusted on 12bit becasue the resolution is 12bit in this stm32_vref driver.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/61368

2023-08-10 13:55 UTC, FRASTM commented
The regex in the samples/sensor/soc_voltage/sample.yaml does not detect correctly the error
PASSED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2146-g24cd2ea1efd8 ***
Sensor voltage[vref_1]: 3.32 V
```

FAILED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2146-g24cd2ea1efd8 ***
Sensor voltage[vref_1]: 13.29 V
```

PASSED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2145-g29d07d6020eb ***
Sensor voltage[vref_1]: 13.29 V
Sensor voltage[vbat_4]: 3.30 V
```

2023-08-23 07:23 UTC, gautierg-st requested changes
See my previous comment

2023-08-31 09:19 UTC, FRASTM commented
> See my previous comment

![stm32U5_adc_vrefint](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/76ac5cec-00e7-41cf-91d6-9e695e8c45cd)

Actually, The VREFINT Calibration value is measured by the ADC1 on 14bit and stored in the system memory.
In case VREF is read on channel 0 of the AD4 (on 12-bits), the CALIBRATIon value is still given by the system memory and is still a 14-bit value. That must be  converted to a 12-bit value as long as the stm32_vref.c is setting a 12bit resolution.
![stm32_vref](https://github.com/zephyrproject-rtos/zephyr/assets/51417392/3c8c72bb-d115-4f9f-8fe3-cbbc7e079835)

2023-08-31 09:54 UTC, gautierg-st approved these changes
You're right, I misunderstood the way it works, sorry.
LGTM

2023-08-31 11:32 UTC, erwango commented on drivers/sensor/stm32_vref/stm32_vref.c
> +#endif /* CONFIG_SOC_SERIES_STM32H5X */
Is there a way to get this information from device tree (`resolution` property)

2023-09-01 08:48 UTC, erwango approved these changes

2023-09-01 11:22 UTC, merged