Bluetooth: ISO: Remove bt_iso_chan_get_type() API declaration
zephyrproject-rtos/zephyr pull request #61404
Opened 2023-08-11 06:58 UTC by rugeGerritsen

The API was never implemented.
The channel type can also be obtained using bt_iso_chan_get_info(). If we would have to implement this API, it would share a lot of the implementation with bt_iso_chan_get_info().

Removing the API makes the ISO APIs more similar to the ACL APIs where we don't have a special API to fetch the role.

2023-08-11 09:02 UTC, kartben requested changes
mmh I don't think it would be ok to "just" drop it. It having never been implemented is probably not a good enough reason as Bluetooth is supposed to be a "stable" API, hence should follow proper deprecation policy.

Now, should Bluetooth at large be advertised as Stable (https://docs.zephyrproject.org/latest/develop/api/overview.html) would be a valid follow-up question, as it's a very broad space with new APIs being introduced regularly...

2023-08-11 09:17 UTC, rugeGerritsen commented
> mmh I don't think it would be ok to "just" drop it. It having never been implemented is probably not a good enough reason as Bluetooth is supposed to be a "stable" API, hence should follow proper deprecation policy.
> 
> Now, should Bluetooth at large be advertised as Stable (https://docs.zephyrproject.org/latest/develop/api/overview.html) would be a valid follow-up question, as it's a very broad space with new APIs being introduced regularly...

I agree that that the fact that it has never been implemented is alone not a good enough reason. But the fact that this API was introduced two years back, and it was never pointed out that the implementation is missing indicates to me that there is no use for it. There is another way to obtain this info.

With regards to API stability, this is an API related to Bluetooth ISO which is marked as experimental.

2023-08-11 09:43 UTC, kartben commented
> I agree that that the fact that it has never been implemented is alone not a good enough reason. But the fact that this API was introduced two years back, and it was never pointed out that the implementation is missing indicates to me that there is no use for it. There is another way to obtain this info.

Yep fair enough :) Although in theory there could very well be (and I know there is like a .00001% chance that is the case) people having relied on the existence of this public API to create their own implementation downstream.

> With regards to API stability, this is an API related to Bluetooth ISO which is marked as experimental.

+1 for just dropping, then as it's experimental (see note below). Still worth an entry in the release notes IMO.

Note to self (and definitely beyond the scope of this particular PR as this is an issue for a lot of the experimental features): only having the information re: experimental status in Kconfig is probably not enough and we need to find ways to surface that more prominently in other places of the documentation, so that people get a heads-up as soon as they start reading the documentation about a particular feature vs. actually starting to use it.

2023-08-15 08:33 UTC, Thalley approved these changes
Looking at the commit message that added this, it is clear that this was never supposed to be commited

2023-08-15 08:42 UTC, kartben approved these changes

2023-08-16 08:21 UTC, merged