Bluetooth: Shell: Fix the command bt adv-data
zephyrproject-rtos/zephyr pull request #61418
Opened 2023-08-11 12:52 UTC by rugeGerritsen

The command did no longer set the user specified data if the user specified more than 1 AD field.

We were using the return value of ad_init() to set the number of AD fields. This did not take into account the number of existing data fields. By chance this usually returned 1.

2023-08-12 13:15 UTC, jhedberg approved these changes, later dismissed

2023-08-15 08:39 UTC, Thalley requested changes

2023-08-15 08:39 UTC, Thalley commented on subsys/bluetooth/shell/bt.c
> +			 adv_set_opt[selected_adv]) + *data_len;
The error below, `shell_error(sh, "Failed to initialize stack advertising data");`, does not match this behavior. 

Suggest to do `ad_len += *data_len` after the `if (ad_len < 0)` check instead

2023-08-15 12:13 UTC, Thalley approved these changes

2023-08-15 13:06 UTC, alwa-nordic approved these changes

2023-08-15 13:27 UTC, jhedberg approved these changes

2023-08-15 21:54 UTC, merged