bluetooth:micp Wrong error response for invalid Mute Value.
zephyrproject-rtos/zephyr pull request #61461
Opened 2023-08-14 07:28 UTC by MSEEHenrik

Qualification test MICS/SR/SPE/BI-01-C [Invalid Mute Value]

Specification: Microphone Control Service Revision v1.0 Section 3.1.1

If the client writes a value of Disabled or RFU to the Mute characteristic, the server shall return an ATT Error Response with the ATT error code Value Not Allowed (0x13) as defined in Assigned Numbers.

2023-08-14 09:23 UTC, MariuszSkamra requested changes

2023-08-15 06:53 UTC, MSEEHenrik commented on include/zephyr/bluetooth/audio/micp.h
> +#define BT_MICP_ERR_VAL_OUT_OF_RANGE               BT_ATT_ERR_VALUE_NOT_ALLOWED
Done.

2023-08-15 09:43 UTC, Thalley approved these changes

2023-08-15 10:36 UTC, larsgk approved these changes

2023-08-16 06:02 UTC, MariuszSkamra approved these changes

2023-08-16 08:24 UTC, merged