[DNM][RFC] OpenAMP example application
zephyrproject-rtos/zephyr pull request #6153
Opened 2018-02-12 14:50 UTC by skordal

This pull request adds an example application using OpenAMP to do multiprocessor communication. It is adapted from the recently posted RPMsg-Lite example application, from PR #5960. This application is intended to provide a starting-point for comparison and benchmarking of RPMsg-Lite and OpenAMP, see issue #3065.

The relevant commit in this PR is the most recent commit, fc2989e. However, since the code is dependent on changes included in PR #5960, the commits from that PR is also included here.

I have added build instructions in a README.md file, located in samples/subsys/ipc/openamp/README.md.

Some details:
- The OpenAMP example uses the SRAMX RAM block as shared memory, to provide better separation between shared RAM and the RAM that is being used by the application. This also simplified the linking of the application.
- Heap size had to be overridden in the default board configuration for both the cores in the LPC54114. This is because the heap size is needed (at compile-time) for libmetal, and when compiling libraries outside of the zephyr application folders, only the default board configuration is used.
- Due to the use of static libraries, the order that the libraries are provided to the linker in matters. The libkernel.a must be linked last, and the CMakeLists.txt files contains code to fix this.

2018-02-12 14:55 UTC, carlescufi commented
CC @stanislav-poboril @wjliang

2018-02-12 19:33 UTC, dbkinder reviewed
Doc looks OK, but there are branch conflicts.

2018-02-12 23:52 UTC, dbkinder requested changes
.rst file for our Zephyr docs

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +OpenAMP Example Application
This file should be called README.rst (with an .rst extension)

Add a line before this with a document label to make it easier to reference externaly:

    .. _openAMP_example:

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +===========================
Our Zephyr doc standards use ### underlines for H1 headings, *** for H2, === for H3, and --- for H4.
So use ### underlines for this heading

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +--------
use *** underline for this heading

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +-------------------------
use *** underlines here

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +Building and running this application requires that libmetal and OpenAMP is
change that last ``is`` to ``are``

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +location:
maybe add:

    location (outside the Zephyr code tree):

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd open-amp
would this be instead:  ``cd ../../open-amp``

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd remote
I think the directory you want them to go to is ``cd $ZEPHYR_BASE/samples/subsys/ipc/ipm_mcux/remote``

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +Compile the remote application, by going to the toplevel folder of the example
I think you can delete the ", by going to the..." part of this sentence by the cd change below

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +Compile the master application, by going to the toplevel folder of the example
Same here (deleting the " by going to the...")

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd master
and I suspect this should be ``cd $ZEPHYR_BASE/samples/subsys/ipc/ipm_mcux/master``

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +
Use the code-block directive to get this formatted correctly:

    .. code-block:: bash

       git clone https://github.com/OpenAMP/libmetal.git
       git clone https://github.com/OpenAMP/open-amp.git

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd libmetal
use a code-block here too:

    .. code-block:: bash

       mkdir build-master build-remote
       cd build-master
       cmake -DWITH_ZEPHYR=ON -DBOARD=lpcxpresso54114 ..
       make
       cd ../build-remote
       cmake -DWITH_ZEPHYR=ON -DBOARD=lpcxpresso54114_m0 ..
       make

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd open-amp
use code-block here too

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd remote
code-block

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ cd master
you know what to do (code-block)

2018-02-12 23:52 UTC, dbkinder commented on samples/subsys/ipc/openamp/README.md
> +    $ make flash
one more code-block

2018-02-13 20:24 UTC, dbkinder approved these changes
Takk!  (But you still have merge conflicts that need to be resolved)

2018-02-15 09:39 UTC, skordal commented
Tenative comparison of executable sizes based on a build with default settings and GCC 7.2.1. The size of the image for the second core has been subtracted from the sizes of the `.text` section for the master applications.

| Executable                | .text | .data | .bss  |
|:--------------------------|------:|------:|------:|
| RPMsg-Lite master         | 16782 |   328 | 15744 |
| RPMsg-Lite remote         | 11040 |   128 | 8544  |
| OpenAMP master            | 24000 |   664 | 9512  |
| OpenAMP remote            | 18106 |   464 | 8456  |

2018-02-16 16:33 UTC, MarekNovakNXP commented
Cannot we have both implementations in /ext? Is it not what is /ext intended for?
Why there are for example two crypto libraries (tinycrypt and mbedtls) supported? I can see a similar situation here... 
Can we discuss on this?

2018-02-19 15:36 UTC, PetrLukas commented
@skordal could you please post also map files, you have used for code size comparison? 

Did RPMSG-lite use static or dynamic allocation option? Default settings uses dynamic allocation option. There could be also used static to decrease codesize quite a bit.

Thanks, Petr

2018-02-20 08:39 UTC, skordal commented
@PetrLukas I added the mapfiles to my comment above. I will get some numbers for RPMsg-Lite using the static API and add them to the table.

2018-02-20 09:39 UTC, PetrLukas commented
@skordal Thank you for analysis and map files. 

I was trying to find what is reason for big difference in master BSS size. It seems that in case of RPMSG Lite shared memory buffers are included in statistics (rpmsg_sh_mem), while in case of openAMP implementation it is not. If it would be included it would add another 30kB.

> #define SHM_START_ADDRESS       0x04000400
> #define SHM_SIZE                0x7c00

Speed comparison - I think it more or less depends on placement of shared buffers. In case of OpenAMP they are placed in SRAMX. It may impact performance for big buffer transfers. We should pace shared buffers to the same SRAM for both implementations.

2018-02-23 08:43 UTC, skordal commented
Thanks, I did not notice that the shared memory was included in the .bss section for the RPMsg-Lite code. I have updated the numbers to account for this.

I also did an experiment with the shared memory placement. Overall, there seems to be an average performance drop of around 1 % when using SRAMX. I added the numbers to the table in the comment above for comparison.

2018-03-02 12:05 UTC, MarekNovakNXP commented
Hello,
I reviewed the figures concerning the code size provided by @skordal  and I tried to remove the zephyr code from the comparison and to keep only RPMsg-Lite  / OpenAMP RPMsg code.
The difference in code size is about 60%.

I attach the excell sheet, where the computation is done. Let me know if you find any error in this benchmark, which reflects more the reality about code size comparison between OpenAMP RPMsg and RPMsg-Lite.

B/CODE | remote | master |   | remote | master
-- | -- | -- | -- | -- | --
lite | 3106 | 3256 |   | -60.8224 | -58.9304
openamp | 8174 | 7928 |   | 3.102926 | REF



[comparison.xlsx](https://github.com/zephyrproject-rtos/zephyr/files/1774971/comparison.xlsx)

2018-04-25 12:13 UTC, carlescufi commented
@skordal @MaureenHelm should we close this now?

2018-04-25 12:15 UTC, skordal commented
That's fine by me, there should be a new PR with a new example when OpenAMP is ready to be included in Zephyr.

2018-04-25 13:36 UTC, closed without merging