scripts: pin `Pillow` version
zephyrproject-rtos/zephyr pull request #61678
Opened 2023-08-20 17:53 UTC by narvalotech

The latest (v10.0) version doesn't work with the cfb script.

```
(zephyr) [john@420blz ~]$ ${ZEPHYR_BASE}/scripts/build/gen_cfb_font_header.py -i ~/Downloads/creep2.ttf -x 10 -y 16 -s 11 --center-x -o cfbv_creep
Traceback (most recent call last):
  File "/home/john/Software/zephyrproject/zephyr/scripts/build/gen_cfb_font_header.py", line 263, in <module>
    main()
  File "/home/john/Software/zephyrproject/zephyr/scripts/build/gen_cfb_font_header.py", line 260, in main
    generate_header()
  File "/home/john/Software/zephyrproject/zephyr/scripts/build/gen_cfb_font_header.py", line 174, in generate_header
    extract_font_glyphs()
  File "/home/john/Software/zephyrproject/zephyr/scripts/build/gen_cfb_font_header.py", line 79, in extract_font_glyphs
    fw, fh = font.getsize(chr(i))
             ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

```

Got the hint from googling:
https://github.com/ultralytics/yolov5/issues/11838

The alternative is to update the generator script.

2023-08-20 17:56 UTC, narvalotech commented
@pabigot fyi

2023-08-22 03:47 UTC, kartben commented
Based on the change log for 10.0, I think it might be a better solution on the long run to fix the script to be compatible with new Pillow versions
https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods
Would you be able to look into switching to getbbox()?

2023-08-22 20:40 UTC, narvalotech commented
@kartben made https://github.com/zephyrproject-rtos/zephyr/pull/61759 as competing PR. 
When re-generating the fonts I saw that the default fonts had not been updated every time the script was also updated. So I re-generated them.

2023-08-25 10:25 UTC, henrikbrixandersen requested changes
> Based on the change log for 10.0, I think it might be a better solution on the long run to fix the script to be compatible with new Pillow versions rather than pinning to 9.5. https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods Would you be able to look into switching to getbbox()?

I believe this is best way forward. Update the script to work with the new API and require a more recent version of Pillow.

I am the original author of this script. If @narvalotech do not wish to take on the task of converting the script to the new API, I can.

2023-08-25 11:19 UTC, narvalotech commented
> I believe this is best way forward

Will do that in the other PR then, and closing this as dupe.

2023-08-25 11:19 UTC, closed without merging