ci: consolidate workflows and run in sequence
zephyrproject-rtos/zephyr pull request #61702
Opened 2023-08-21 11:51 UTC by nashif

Run workflows in sequence and stop if we fail a long the way. If
compliance check fails, do not run tests, first get compliance passing
to allow for full test run.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2023-08-21 11:52 UTC, carlescufi requested changes
Can we please keep the files separate but instead add dependencies?

2023-08-21 11:53 UTC, nashif commented
on push:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/180017/1c92ee71-a57d-496d-adf3-383230db7822)

on pull request:

![image](https://github.com/zephyrproject-rtos/zephyr/assets/180017/c8d25660-a156-4f7b-9a27-01c9f0a855df)

2023-08-21 11:55 UTC, nashif commented
> Can we please keep the files separate but instead add dependencies?

Considered that, but it will make things more complicated and a few things will not work as expected.
Otherwise, What is the benefit of this?

2023-08-21 11:58 UTC, carlescufi commented
> > Can we please keep the files separate but instead add dependencies?
> 
> Considered that, but it will make things more complicated and a few things will not work as expected. Otherwise, What is the benefit of this?

Well, this is the paradigm we use for documentation building + publishing, and I think it keeps things nice and small and tidy:

https://github.com/zephyrproject-rtos/zephyr/blob/2218e80bc2d3a98a0f2c3e525eebc36d73fa779a/.github/workflows/doc-build.yml#L4
https://github.com/zephyrproject-rtos/zephyr/blob/2218e80bc2d3a98a0f2c3e525eebc36d73fa779a/.github/workflows/doc-publish.yml#L9

2023-08-21 12:01 UTC, gmarull commented
> > > Can we please keep the files separate but instead add dependencies?
> > 
> > 
> > Considered that, but it will make things more complicated and a few things will not work as expected. Otherwise, What is the benefit of this?
> 
> Well, this is the paradigm we use for documentation building + publishing, and I think it keeps things nice and small and tidy:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/2218e80bc2d3a98a0f2c3e525eebc36d73fa779a/.github/workflows/doc-build.yml#L4
> 
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/2218e80bc2d3a98a0f2c3e525eebc36d73fa779a/.github/workflows/doc-publish.yml#L8-L9

also because of safety issues related to pull_request_target.

2023-08-21 12:02 UTC, nashif commented
> Well, this is the paradigm we use for documentation building + publishing, and I think it keeps things nice and small and tidy:

i need to go back to a discussion I had with @stephanosio  about this, we considered this option, but this might not work and we decided to follow this path. We take another look.

2023-08-21 12:24 UTC, nashif commented
> also because of safety issues related to pull_request_target.

you mean moving check_compliance from pull_request to pull_request_target?

2023-08-21 13:33 UTC, nashif commented
@carlescufi I remove the compliance for now, this is just merging clang into main twister workflow which has its own savings

2023-08-21 13:37 UTC, carlescufi submitted a review, later dismissed

2023-10-20 10:29 UTC, carlescufi approved these changes, later dismissed
LGTM

2024-01-25 16:05 UTC, aescolar approved these changes, later dismissed

2024-01-25 16:05 UTC, aescolar commented
@nashif what happened to this one? it is a quite nice thing to do

2024-07-30 10:05 UTC, closed without merging