atomic: fix docstring regarding return value
zephyrproject-rtos/zephyr pull request #61758
Opened 2023-08-22 20:04 UTC by nashif

docstring for atomic_test_and_clear_bit was wrongly advertising it
returns the old value when it actually returns boolean.

Fixes #61661

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2023-08-22 21:35 UTC, kartben approved these changes

2023-08-22 22:07 UTC, dcpleung approved these changes

2023-08-23 08:02 UTC, carlescufi requested changes
Well it returns the old value of the bit, doesn't it?

2023-08-23 10:33 UTC, nashif commented
> Well it returns the old value of the bit, doesn't it?

no it does not, it returns a bool

2023-08-23 11:31 UTC, nashif commented
@ceolin  FYI

2023-10-20 10:31 UTC, carlescufi approved these changes

2024-03-05 00:29 UTC, closed without merging