scripts: Update CFB font generator
zephyrproject-rtos/zephyr pull request #61759
Opened 2023-08-22 20:39 UTC by narvalotech

Update CFB font generator so it works with Pillow version 10. They
deprecated some methods, with no direct replacements, so the generated
fonts might be slightly different.

2023-08-23 20:17 UTC, narvalotech commented on subsys/fb/cfbv_1016.c
> + * /home/john/Software/zephyrproject/zephyr/scripts/build/gen_cfb_font_header.py -i DroidSansMono.ttf -x 10 -y 16 -s 14 --center-x --y-offset -2 -o /home/john/Software/zephyrproject/zephyr/subsys/fb/
Should I remove this? the original font file, whilst being generated still had the copyright notice for both Phytec (who checked in the file I think) and google (who made the font).
The file as it is right now has not been tampered with, it's exactly what the script spits out.

2023-08-25 10:30 UTC, henrikbrixandersen requested changes
Please update the Pillow dependency to a version supporting the new API. 

Why were the in-tree fonts regenerated? I don't believe they were originally generated using this script.

2023-08-25 11:17 UTC, narvalotech commented
@henrikbrixandersen Will do. Is `==10.*` enough or should I be more precise?

The wording in the README suggested that. I'll drop the commit, that's probably also why the compliance is failing (the copyrights).

2023-08-25 11:23 UTC, henrikbrixandersen commented
> @henrikbrixandersen Will do. Is `==10.*` enough or should I be more precise?

How about just `>=10.0`?

2023-09-07 07:49 UTC, henrikbrixandersen approved these changes

2023-09-13 21:39 UTC, mbolivar-ampere approved these changes

2023-09-13 21:40 UTC, merged