ev11l78a: minimize memory usage in the default config.
zephyrproject-rtos/zephyr pull request #61797
Opened 2023-08-23 14:00 UTC by Flameeyes

ev11l78a: minimize memory usage in the default config.

The ATSAMD20E16 used in this board only has 8KiB SRAM, so the defaults
are not really suitable for anything close to useful, particularly the
sink sample that most closely resembles the original demo for the board.

This should also allow more tests not to be skipped for this board as
otherwise they overflow RAM usage.

Signed-off-by: Diego Elio Pettenò <flameeyes@meta.com>

2023-09-09 04:50 UTC, nandojve requested changes

2023-09-09 04:50 UTC, nandojve commented on boards/arm/adafruit_trinket_m0/adafruit_trinket_m0.dts
> +#include <atmel/samd2xx18.dtsi>
This should follow same solution of #61744 which is include main header inside `samd2xx18.dtsi`

2023-10-18 10:43 UTC, nandojve commented
You need rebase : )

2023-11-26 09:24 UTC, nandojve commented
Ping

2023-11-26 20:22 UTC, Flameeyes commented
Sorry, been a busy few months and this project took a significant back burner status. But rebased this PR as I think nothing stops it.

2023-11-27 17:02 UTC, nandojve approved these changes

2023-11-28 07:16 UTC, pdgendt approved these changes

2023-11-28 14:09 UTC, merged