Expand info about troubleshooting ModemManager
zephyrproject-rtos/zephyr pull request #6181
Opened 2018-02-13 16:10 UTC by IvanSanchez

2018-02-13 19:50 UTC, dbkinder requested changes

2018-02-13 20:58 UTC, carlescufi commented
@IvanSanchez you need to fix your commit message as per http://docs.zephyrproject.org/contribute/contribute_guidelines.html#commit-guidelines

2018-02-15 19:57 UTC, dbkinder commented
@IvanSanchez  There are issues with your commit message shown in the shippable details at https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/10789/4/tests 

- Add your name and email to your github configuration (see http://docs.zephyrproject.org/contribute/contribute_guidelines.html#contribution-tools-and-git-setup)
- Do a ``commit -s --amend`` to update the commit message (after making the suggested changes noted above) - that will add your name and email to the commit message
- Edit the commit message to fix the PR title to "doc: Update troubleshooting ModemManager info" (< 72 characters)
- add a  short description of the PR changes (PRs with only titles aren't allowed)

2018-03-16 16:47 UTC, dbkinder approved these changes
Thanks

2018-04-21 14:05 UTC, merged