net: lwm2m: remove calling device_periodic_service() every 10 seconds
zephyrproject-rtos/zephyr pull request #6193
Opened 2018-02-14 04:09 UTC by rbtchc

@mike-scott I'm not sure what is the purpose of calling device_periodic_service() every 10 seconds.
So, I remove the service registration and device_periodic_service() in this patch.

Please let me know if this makes sense to you or not.

2018-02-14 04:40 UTC, mike-scott requested changes
The periodic service is what allows the device object to send out time notifications when an observer is registered.  It will silently abort if there are no observers.

Please don't remove this.

2018-02-14 06:41 UTC, rbtchc commented
I tested the client w/ Leshan server. The time notifications (/3/0/13) will be sent out even without the function. Am I missing anything?

2018-02-14 07:28 UTC, mike-scott commented
Yes, the engine will eventually hit the max timer for an observation and read the current time, but the reality is it should trigger the observers every second and send a notification message back at the minimum time.  I chose 10 seconds as a "default" minimum for time notifications but it could be much lower.

2018-02-14 07:29 UTC, mike-scott commented
You can test this by setting pmin to something like 10 seconds and pmax to something like 100 seconds.  Without the periodic service you will only see the pmax notifications even though time has elapsed.

2018-02-20 16:30 UTC, mike-scott commented
@rbtchc Did you still want to pursue removing this periodic callback?  (If not, let's close this PR)

2018-02-21 01:45 UTC, rbtchc commented
No. I'm not.

2018-02-21 01:45 UTC, closed without merging