Bluetooth: audio: Change bt_audio_codec_cfg_get_val return value
zephyrproject-rtos/zephyr pull request #62036
Opened 2023-08-29 13:23 UTC by MariuszSkamra

This changes bt_audio_codec_cfg_get_val function to return the data length found. Otherwise, this function gives no information about the returned data length.

2023-08-29 14:43 UTC, Thalley requested changes

2023-08-29 14:43 UTC, Thalley commented on include/zephyr/bluetooth/audio/audio.h
> + *  @return data length
```suggestion
 *  @param[in]  codec_cfg  The codec data to search in.
 *  @param[in]  type       The type id to look for
 *  @param[out] data       Pointer to the data-pointer to update when item is found
 *  @return Length of found @p data, or 0 if not found
```

2023-08-30 07:43 UTC, Thalley approved these changes

2023-08-31 05:52 UTC, kruithofa approved these changes

2023-08-31 08:21 UTC, merged