sensor: icm42605: keep irq on while servicing
zephyrproject-rtos/zephyr pull request #62303
Opened 2023-09-05 15:05 UTC by mgritz

Turning the irq off in the isr and on again after servicing requires access to the NVIC configuration registers on cortex M. On STM32H7 dualcore devices this is guarded by a hardware semaphore which messes up timings when one core still boots while the other core already has an instance of the icm42605 driver running. This causes kernel panics from the HSEM not being acquired in time.

See also https://github.com/zephyrproject-rtos/zephyr/issues/62218

2023-09-05 15:43 UTC, yperess approved these changes

2023-10-13 06:39 UTC, mgritz commented
@avisconti @erwango Friendly reminder to please take a look at this :slightly_smiling_face: 

Also, the very similar icm42670 driver has the same structure. Do you want me apply the change it there as well?

2023-10-13 14:49 UTC, teburd requested changes
The gpio interrupt disable/enable are there to ensure progress can always be made on things. Without it its pretty easy to overload interrupts causing a variety of unwanted behavior. In effect the mask is there to rate limit the incoming interrupts from the sensor to a rate that can be processed.

Removing this will inevitably lead to someone having a high ODR on a slow SoC wondering why things are breaking.

Does the stm32h7 not have a core local way of masking interrupts?

2023-10-17 07:46 UTC, mgritz commented
Thanks for the insight @teburd. I see where you are coming from with this and I did not give that any thought.

So I looked into that a bit.
The H7 does indeed have core-dedicated IRQ mask registers, C1IMR and C2IMR in the EXTI register block.
Zephyr's interrupt controller driver also uses those in `drivers/interrupt_controller/intc_exti_stm32.c`.
The wired thing is, it still locks the HW-semaphore in a seemingly random subset of cases, e.g. in `stm32_exti_disable()`, where my issue comes from, but not int `stm32_exti_enable()`. I don't understand why and my feeling of gut tells me there might be a bug there, regardless of this thread here.

I will try if changing the EXTI driver instead also solves my problem (don't have hardware right now), however, getting that upstream would affect a lot more people than it would changing this driver.
As I am a first-time contributor to zephyr, do you have a hint for me how I get that onto the agenda for the maintainers there?

Also, I would like to mention that I personally would not see it as a concern of the sensor driver to introduce an obscure, automatic band-limit on the interrupt handling like so.
Instead, I would advocate for it to be our concern here to enable the users to configure the IMU in a way their MCU can cope with and accept the fact that it can stall their applications if configured incorrectly.

I am happy to look into this a bit more or ask a colleague to do that, if you see this worth the effort. WDYT?

2023-10-18 12:17 UTC, mgritz commented
> I will try if changing the EXTI driver instead also solves my problem

Indeed it does, see #64075.

2023-10-18 14:48 UTC, teburd commented
> Thanks for the insight @teburd. I see where you are coming from with this and I did not give that any thought.
> 
> So I looked into that a bit. The H7 does indeed have core-dedicated IRQ mask registers, C1IMR and C2IMR in the EXTI register block. Zephyr's interrupt controller driver also uses those in `drivers/interrupt_controller/intc_exti_stm32.c`. The wired thing is, it still locks the HW-semaphore in a seemingly random subset of cases, e.g. in `stm32_exti_disable()`, where my issue comes from, but not int `stm32_exti_enable()`. I don't understand why and my feeling of gut tells me there might be a bug there, regardless of this thread here.
> 
> I will try if changing the EXTI driver instead also solves my problem (don't have hardware right now), however, getting that upstream would affect a lot more people than it would changing this driver. As I am a first-time contributor to zephyr, do you have a hint for me how I get that onto the agenda for the maintainers there?
> 
> Also, I would like to mention that I personally would not see it as a concern of the sensor driver to introduce an obscure, automatic band-limit on the interrupt handling like so. Instead, I would advocate for it to be our concern here to enable the users to configure the IMU in a way their MCU can cope with and accept the fact that it can stall their applications if configured incorrectly.

So I guess this is a question about expected behavior. Do you expect that in the case of very fast gpio interrupts for sensors that...

1. The SoC become unresponsive until a reset by something, and potentially comes right back to this unresponsive state if configured to be this way
2. Samples are in effect dropped because the interrupt is masked while processing the last one

> 
> I am happy to look into this a bit more or ask a colleague to do that, if you see this worth the effort. WDYT?

I think its worth looking at and considering how we can better inform when samples are being dropped and why (interrupt rate limiting). Changing the behavior back to one where the SoC becomes unresponsive has in my experience lead to hard to debug situations as its not always possible to log/printk/attach gdb and actually see what the issue is, and unless you know what to look for it can be very confusing.

2023-10-20 07:00 UTC, mgritz commented
I agree, the situation where the SOC becomes unresponsive is difficult to debug especially in situations where the developer does not have physical access to the device (e.g. after a remote rollout) and this could have catastrophic consequences for the application.

>  I think its worth [...] considering how we can better inform when samples are being dropped and why.

Absolutely, as this is quite hard to debug, too. A typical use-case especially for the 'weaker' MCUs will be to not process the IMU samples themselves but stream those to some other device where the application consumes them. The dev's behind that application will have a _very hard_ time understanding what's cooking when they miss samples even though everyone configured everything correctly and the MCU ist just too week.

I presume, showing a LOG_ERR() in that case would be a good start so you get a chance of this happening even without the embedded dev' "understanding" the samples.

2023-10-23 07:18 UTC, mgritz commented
> Indeed it does, see https://github.com/zephyrproject-rtos/zephyr/pull/64075. As soon as that is through, I would agree to close this.

That is merged. I'll close this one.

2023-10-23 07:18 UTC, closed without merging