cpp: Add documentation about Pigweed as a solution
zephyrproject-rtos/zephyr pull request #62371
Opened 2023-09-07 03:46 UTC by yperess

Include documentation about:
- some C++ features via Pigweed
- instructions how to setup Pigweed

This PR addresses some aspects of #53851 by giving guidance but not making Pigweed the 'selected' approach to C++.

2023-09-07 10:11 UTC, kartben requested changes
this is great, thank you!

2023-09-07 10:11 UTC, kartben commented on doc/develop/languages/cpp/pigweed.rst
> +.. code-block:: console
```suggestion
.. code-block:: shell
```

2023-09-07 10:11 UTC, kartben commented on doc/develop/languages/cpp/pigweed.rst
> +.. code-block:: console
```suggestion
.. code-block:: shell
```

2023-09-07 11:09 UTC, henrikbrixandersen requested changes
This goes against what was discussed in the TSC meeting on 2023-08-30 regarding recommending using pigweed to make up for currently unimplemented C++ features in the main Zephyr code (see MoM https://docs.google.com/document/d/1cMkXkFN-Yje-7zIGZmWMfkrVCju85UNnKDfjng9vEv0/edit#heading=h.8cm9xcy7g2ul).

Adding pigweed references to the "Language Support" section of the main Zephyr documentation leads users to believe that this is the approach recommended by the Zephyr project, which the TSC discussion did not conclude.

2023-09-07 12:19 UTC, yperess commented on doc/develop/getting_started/index.rst
Done

2023-09-07 12:20 UTC, yperess commented on doc/develop/languages/cpp/pigweed.rst
> +Enable C++ Support with Pigweed
Done

2023-09-07 12:20 UTC, yperess commented on doc/develop/languages/cpp/pigweed.rst
> +.. code-block:: console
done

2023-09-07 12:24 UTC, yperess commented
> This goes against what was discussed in the TSC meeting on 2023-08-30 regarding recommending using pigweed to make up for currently unimplemented C++ features in the main Zephyr code (see MoM https://docs.google.com/document/d/1cMkXkFN-Yje-7zIGZmWMfkrVCju85UNnKDfjng9vEv0/edit#heading=h.8cm9xcy7g2ul).
> 
> Adding pigweed references to the "Language Support" section of the main Zephyr documentation leads users to believe that this is the approach recommended by the Zephyr project, which the TSC discussion did not conclude.

I read through all the notes before putting this PR together. I'm happy to discuss further, but we never excluded this from going into documentation. The discussion went around the use of it as a module and the delegation of saying "we're going to make this official". Unfortunately the meetings notes seem to be missing a key detail that I'm recalling which is that we did discuss having documentation for modules that we want to advertise but aren't in the manifest yet. Putting this in the C++ documentation is the most natural place IMO.

Happy to discuss further.

2023-09-07 12:33 UTC, carlescufi commented
@henrikbrixandersen @yperess @nashif 
I think a middle-ground may work here. We could add documentation for Pigweed in a separate section (i.e. move `pigweed.rst` elsewhere which by the way in my opinion is separate from the goal pursued in https://github.com/zephyrproject-rtos/zephyr/pull/61505, which just documents a list of all modules, and does not add specific module documentation) and then link to it from the C++ language support page:

`for an alterntative approach to C++ support please see Pigweed`

But for that we would need  `modules` top-level section in the doc that could document at least the default modules provided by Zephyr.

2023-09-07 12:36 UTC, nashif commented
> goal pursued in #61505, which just documents a list of all modules, and does not add specific module documentation) and then link to it from the C++ language support page:

that is not correct, see https://github.com/zephyrproject-rtos/zephyr/pull/61505/files#diff-c22a8fff0128e724a948e334206112f304cb2c0a00e4429abade35390dd7d890R130

2023-09-07 12:41 UTC, yperess commented
> @yperess  the idea was to add such documentation under external modules as being introduced in this PR https://github.com/zephyrproject-rtos/zephyr/pull/61505
> 
> 
> 

Sure, seems easy enough to just relocate the pigweed.rst. I just put it where people would most naturally look for it. We can either:

- merge this and move it when your PR lands
- wait and rebase when your PR lands

Personally I would prefer to land and move later just to have less things up in the air at the same time. The current layout (without the optional modules) makes sense to me and even with optional modules I would put a `:ref:` to the Pigweed docs from the C++ docs. So i guess I'm not seeing the harm in this being an interim solution.

2023-09-07 12:48 UTC, carlescufi commented
> > goal pursued in #61505, which just documents a list of all modules, and does not add specific module documentation) and then link to it from the C++ language support page:
> 
> that is not correct, see https://github.com/zephyrproject-rtos/zephyr/pull/61505/files#diff-c22a8fff0128e724a948e334206112f304cb2c0a00e4429abade35390dd7d890R130

OK, sorry I misunderstood this. Then I suggest we merge #61505 first and then add the link to it from the C++ language page.

2023-10-02 14:50 UTC, kartben commented
> OK, sorry I misunderstood this. Then I suggest we merge #61505 first and then add the link to it from the C++ language page.

fwiw #61605 has now been merged. cc @yperess

2023-11-29 18:27 UTC, kartben commented
@yperess did you want to revisit this one?

2023-11-29 18:52 UTC, yperess commented
> @yperess did you want to revisit this one?

Yes please, I'll rebase

2023-12-19 15:27 UTC, yperess commented
No code/doc changes, just a raw rebase. @kartben @nashif , what's the process for this now? Do I need to propose Pigweed as an addition to `submanifests/optional.yaml`? The original goal here was just to document that the option exists, I worry that adding it to the submanifest and having to request a fork will be a bit too much right now.

2023-12-21 18:17 UTC, kartben commented
@nashif can you help here? I don't think we have a requirement for *optional* modules to live as a fork under the `zephyrproject-rtos` GH org but I am not sure.

2023-12-21 19:14 UTC, fabiobaltieri commented
> @nashif can you help here? I don't think we have a requirement for _optional_ modules to live as a fork under the `zephyrproject-rtos` GH org but I am not sure.

Well they are fetched in CI, worth having the conversation but it may not be a bad idea to keep doing so.

2023-12-21 21:28 UTC, nashif commented
> @nashif can you help here? I don't think we have a requirement for _optional_ modules to live as a fork under the `zephyrproject-rtos` GH org but I am not sure.

there is a requirement, ?"optional modules" are not enabled/active by default, but otherwise follow the same requirement as enabled and active modules, external projects are those which do not exist in the manifest and do not need to be in the zephyr project org:

https://docs.zephyrproject.org/latest/contribute/external.html#integration-as-external-modules

2023-12-21 22:40 UTC, nashif commented
just submitted a PR for the template... 

#66860

2024-03-06 00:29 UTC, closed without merging