scripts/pylib/pytest-twister-harness: Do not fail on Unicode garbage
zephyrproject-rtos/zephyr pull request #62516
Opened 2023-09-11 23:50 UTC by edersondisouza

If pylib twister harness reads bytes that can't be decoded to Unicode, it would raise an exception at a separate "serial reader" process, that would fail without any warning.

This patch uses "errors='ignore'" paramter for Python str.decode() method, so that this doesn't happen.

2023-09-12 07:11 UTC, gchwier approved these changes

2023-09-12 07:16 UTC, gopiotr approved these changes, later dismissed

2023-09-12 08:59 UTC, PerMac requested changes
I am worrying that simply ignoring such errors can hinder some greater underlying issue. I would at least consider using "replace" instead of ignore. Then problematic characters will be replaced with "?" and a user will be at least able to see in logs, that decoding didn't work for all characters

2023-09-12 09:00 UTC, gchwier requested changes
Agree with @PerMac,
adding `error='replace'` shows us that something more is logged

2023-09-12 10:03 UTC, hakehuang approved these changes, later dismissed

2023-09-12 15:46 UTC, edersondisouza commented
v2:
  - Use "replace" instead of "ignore"

2023-09-12 16:07 UTC, nashif approved these changes

2023-09-12 16:38 UTC, gchwier approved these changes

2023-09-13 08:08 UTC, PerMac approved these changes

2023-09-13 08:14 UTC, gopiotr approved these changes

2023-09-13 09:34 UTC, merged