tinycrypt: Constify constant variables to save RAM
zephyrproject-rtos/zephyr pull request #626
Opened 2017-06-28 14:56 UTC by jhedberg

There are several variables in ecc.c that can be const, thereby saving
224 bytes in RAM usage for XIP targets. Making the variables const
also means that several function signatures need to get "const" as
well in order to avoid compiler warnings.

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

2017-06-28 15:05 UTC, galak requested changes
Have you tried sending this to upstream tinycrypt first?

2017-06-28 15:30 UTC, jhedberg commented
Yes, I realized that it's more appropriate for this to go through the TinyCrypt upstream tree first. The pull request is here: https://github.com/01org/tinycrypt/pull/22

2017-06-28 15:37 UTC, galak commented
Right, so let this pend til we see what resolution comes from the tinycrypt project.

2017-07-03 08:02 UTC, closed without merging

2017-07-03 08:03 UTC, jhedberg commented
I abandoned this since TinyCrypt upstream got some major recent overhaul which makes my patch obsolete. I hope the updated upstream version can be ported to Zephyr ASAP.