subsys: kernel_event_logger: change kernel event values
zephyrproject-rtos/zephyr pull request #6269
Opened 2018-02-20 11:48 UTC by SavinayDharmappa

Each bit of "_sys_k_event_logger_mask" corresponds to a
kernel event type. Hence KERNEL_EVENT_TYPE values should be
power of 2. Previous implementation was not adhering
to it ,because of which "sys_k_must_log_event" and
"sys_k_event_logger_set_mask" had unintended effects when
used to mask certain kernel events.

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

2018-02-22 18:25 UTC, tyrantlizard77 requested changes

2018-02-22 18:25 UTC, andrewboie commented on include/logging/kernel_event_logger.h
> +#define KERNEL_EVENT_LOGGER_SLEEP_EVENT_ID                      0x0004
ehhh
use BIT() macros from misc/util.h

2018-02-23 10:30 UTC, chunlinhan commented
I don't think the original design of event type requests that the vaule of id needs to be power of 2.
Please check:
http://docs.zephyrproject.org/subsystems/logging/kernel_event_logger.html#adding-a-custom-event-type

2018-02-23 12:29 UTC, nashif approved these changes

2018-02-23 12:29 UTC, merged