drivers: sensor: Add support for hm330x particle sensor
zephyrproject-rtos/zephyr pull request #62786
Opened 2023-09-18 17:14 UTC by kartben

wip

2023-09-19 13:59 UTC, MaureenHelm requested changes
Some small nits, but otherwise LGTM

2023-09-19 14:25 UTC, kartben commented on dts/bindings/sensor/seeed,hm330x.yaml
> +include: [i2c-device.yaml]
oops.

2023-09-19 14:25 UTC, kartben commented on drivers/sensor/hm330x/hm330x.h
> +};
+1, makes sense. and done.

2023-09-19 14:26 UTC, kartben commented
> Some small nits, but otherwise LGTM

Thanks for the quick review! I've addressed all your comments.

2023-09-19 14:31 UTC, MaureenHelm approved these changes

2023-09-25 17:53 UTC, carlescufi approved these changes
LGTM!

2023-09-25 17:53 UTC, merged