tests: boot_time: cleanup boot_time test to work on ARM
zephyrproject-rtos/zephyr pull request #628
Opened 2017-06-28 18:17 UTC by galak

Enabled the boot_time test on ARM SoCs, dropped the noinit on
__start_time_stamp so we at least start at 0 if we don't have some
initialization of it on a give architecture (like on ARM).  Also moved
to printing the values out as %u to increase the range of values.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2017-06-28 19:24 UTC, nashif requested changes

2017-06-28 19:24 UTC, nashif commented on kernel/init.c
> +u64_t __start_time_stamp; /* timestamp when kernel starts */
this now causes the number to always be zero? It is an important KPI to track on many platforms, i.e. to measure the time it takes to bootup zephyr including the bootloader. Right now it shows on x86 platforms:

tc_start() - Boot Time Measurement
Boot Result: Clock Frequency: 32 MHz
__start       : 7001108 cycles, 218784 us
_start->main(): 8489 cycles, 265 us
_start->task  : 8526 cycles, 266 us
_start->idle  : 328272 cycles, 10258 us
Boot Time Measurement finished

with the patch:

tc_start() - Boot Time Measurement
Boot Result: Clock Frequency: 32 MHz
__start       : 0 cycles, 0 us
_start->main(): 26453 cycles, 826 us
_start->task  : 26490 cycles, 827 us
_start->idle  : 346236 cycles, 10819 us
Boot Time Measurement finished

2017-06-28 20:19 UTC, andrewboie commented on kernel/init.c
> +u64_t __start_time_stamp; /* timestamp when kernel starts */
This *has* to be noinit. The TSC is read right at the entry point before BSS is zeroed. If it is in BSS the stored value will be clobbered.

2017-06-28 20:29 UTC, galak commented on kernel/init.c
> +u64_t __start_time_stamp; /* timestamp when kernel starts */
Ok, wasn't thinking about when bss gets cleared vs this gets set on x86.  Will move back to __noinit and explicitly setting to 0 on ARM.

2017-06-29 11:08 UTC, nashif approved these changes

2017-06-29 11:09 UTC, merged