doc: Bluetooth: Mesh: Remove "draft" word, fix DFU and MBT specs names
zephyrproject-rtos/zephyr pull request #62936
Opened 2023-09-21 13:32 UTC by PavelVPV

Mesh Protocol 1.1 is now adopted so we can remove "draft" word. The other changes fixing rendering of the note in Access layer page and DFU and MBT (BLOB) specification names.

2023-09-22 06:06 UTC, Andrewpini approved these changes, later dismissed

2023-09-22 06:51 UTC, mia-ko requested changes

2023-09-22 06:51 UTC, mia-ko commented on doc/connectivity/bluetooth/api/mesh/blob.rst
> +The Binary Large Object (BLOB) Transfer models implements the Bluetooth Mesh Binary Large Object Transfer Model specification version 1.0 and provide functionality for sending large binary objects fr
```suggestion
The Binary Large Object (BLOB) Transfer models implement the Bluetooth Mesh Binary Large Object Transfer Model specification version 1.0 and provide functionality for sending large binary objects from a single source to many Target nodes over the Bluetooth mesh network. It is the underlying transport method for the :ref:`bluetooth_mesh_dfu`, but may be used for other object transfer purposes. The implementation is in experimental state.
```

2023-09-22 07:04 UTC, mia-ko approved these changes

2023-09-25 07:25 UTC, Andrewpini approved these changes

2023-09-25 08:47 UTC, Thalley approved these changes

2023-09-25 11:32 UTC, jhedberg approved these changes

2023-09-25 14:42 UTC, merged