samples: subsys: usb: cdc_acm: add twister test for st boards
zephyrproject-rtos/zephyr pull request #62983
Opened 2023-09-22 12:04 UTC by Desvauxm-st

add one twister test : sample.usb.cdc-acm-otg-st.
if the second usb connector (the other than ST-link) is connect and the link is ok we must read the string: "Device configured"

2023-09-22 13:29 UTC, jfischer-no requested changes
What is wrong with `sample.usb.cdc-acm:`? Otherwise this does not make any sense.

2023-09-22 13:48 UTC, Desvauxm-st commented
@jfischer-no 
nothing is wrong with  the test sample.usb.cdc-acm it works well but:
with the test sample.usb.cdc-acm  even if nothing is connect on the user USB the test pass ( because we expected " wait for DTR")
we want to add a new test  that allow us to be sure that the user usb is connect and OK  ( in that case the expected string is "Device configured" and not only " wait for DTR")
it not the same test.

2023-09-22 14:00 UTC, jfischer-no commented
> @jfischer-no nothing is wrong with the test sample.usb.cdc-acm it works well but: with the test sample.usb.cdc-acm even if nothing is connect on the user USB the test pass ( because we expected " wait for DTR") we want to add a new test that allow us to be sure that the user usb is connect and OK ( in that case the expected string is "Device configured" and not only " wait for DTR") it not the same test.

This is a sample, not a test. It is fine as it is.

2023-09-25 07:27 UTC, Desvauxm-st commented
I don't understand
an automatic test does not harm a sample in any way
on the contrary if a new card is added tomorrow this specific functionality will be tested on this sample quickly with twister.
without this test on this future new card this specific functionality may not be seen as non-functional on this sample
this will in fact only strengthen the reliability of this sample

2023-09-25 13:39 UTC, Desvauxm-st commented
@jfischer-no 
samples/subsys/usb/cdc_acm
with nucleo_stm32H753zi for example
You can see all the code we run from the stm32 driver when the console message  “Device configured” is displayed

 
![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/86a84b50-ee39-4b35-b9dd-ee423da9fc78)


With 
CONFIG_USB_DRIVER_LOG_LEVEL_DBG=y
We can see all the code running under the Driver  ( see after)

 
![image](https://github.com/zephyrproject-rtos/zephyr/assets/119042859/c9e4cead-d5b2-410f-8fa4-b3a56165f6cb)




One other solution I can propose you is to add one special fixture =”Device configured” in sample.yaml  in that case  all the board not only for ST board can use it in Twister if the fixture is set.

Something like that:

   sample.usb.cdc-acm-otg:
    depends_on: usb_device
    tags: usb   
    harness: console
    harness_config:
      fixture: Device_Configured
      type: one_line
      regex:
        - "Device configured"



In that case the coverage for the driver is better for the sample.



[usb_cdc_acm_drivers_called.docx](https://github.com/zephyrproject-rtos/zephyr/files/12715733/usb_cdc_acm_drivers_called.docx)

2023-09-25 14:29 UTC, jfischer-no commented
> One other solution I can propose you is to add one special fixture =”Device configured” in sample.yaml in that case all the board not only for ST board can use it in Twister if the fixture is set.
> 
> Something like that:
> 
> sample.usb.cdc-acm-otg: depends_on: usb_device tags: usb harness: console harness_config: fixture: Device_Configured type: one_line regex: - "Device configured"

`fixture` should probably be `fixture: fixture_usb_host` or` fixture_usb_cdc` (console sample), but relying on the logging level of CDC ACM implementation is problematic, there could be status callback in the sample. But because of fixture, only few boards, if any, would "benefit" from this change. I am still not convinced.

2023-09-26 20:28 UTC, jfischer-no commented
> > But because of fixture, only few boards, if any, would "benefit" from this change. I am still not convinced.
> 
> This is the way fixtures work and this is highly valuable for HW in the loop testing. 

And again, this is not a test, and not "HW in the loop" testing because there is no real loop.

>With this small change in the .yaml

This is not done with changes in sample.yaml. Please read my comment.

2023-09-27 07:11 UTC, erwango commented
> And again, this is not a test, and not "HW in the loop" testing because there is no real loop.

If adding 2 lines here helps to significantly increase test coverage, is that such a big issue ?

> This is not done with changes in sample.yaml. 

This is done this way in several other drivers/subsystems.

> Please read my comment.

Sorry, but this isn't clear to me. Anyway, this is up to you I guess but if it can't be done that way, are there any plans to improve USB driver code coverage using USB tests ?

2023-10-04 13:30 UTC, Desvauxm-st commented
@jfischer-no
Ok I close this PR

2023-10-04 13:30 UTC, closed without merging