drivers: dma: intel_lpss: Added parent phandle
zephyrproject-rtos/zephyr pull request #62989
Opened 2023-09-22 14:28 UTC by akanisetti

Added parent phandle to get base address.

Signed-off-by: Anisetti Avinash Krishna <anisetti.avinash.krishna@intel.com>

2023-09-22 15:33 UTC, teburd approved these changes, later dismissed

2023-09-25 12:14 UTC, tbursztyka submitted a review, later dismissed

2023-09-25 12:40 UTC, nashif approved these changes, later dismissed

2023-09-25 13:33 UTC, jhedberg requested changes
@akanisetti thanks for the PR, I see many already approved, but I have a few concerns:

 - It would be good to answer the question "why?" in the commit messages. I don't see any explanation right now for why we can't have DMA nodes as child nodes for peripheral nodes.
 - Does some precedent exist for the `parent-dev` DT property (e.g. in Linux)? Would `dma-parent` have perhaps been better if this is DMA-specific?
 - Normally peripheral nodes have a reference to the DMA node, not vice versa, so you might be creating the possibility for a circular dependency here. Would it not be possible to have a reference to the DMA node from the peripheral node (like is usually the case) and have the peripheral driver initialize the DMA driver (at the same time passing the peripheral device pointer to the DMA driver)?

2023-09-25 13:36 UTC, jhedberg commented
@akanisetti note that besides the commit message issue, I'm not necessarily requesting other changes. For the other questions I'm also happy with a good explanation (if one exists) :)

2023-09-25 14:17 UTC, akanisetti commented
> @akanisetti thanks for the PR, I see many already approved, but I have a few concerns:
> 
> * It would be good to answer the question "why?" in the commit messages. I don't see any explanation right now for why we can't have DMA nodes as child nodes for peripheral nodes.
> * Does some precedent exist for the `parent-dev` DT property (e.g. in Linux)? Would `dma-parent` have perhaps been better if this is DMA-specific?
> * Normally peripheral nodes have a reference to the DMA node, not vice versa, so you might be creating the possibility for a circular dependency here. Would it not be possible to have a reference to the DMA node from the peripheral node (like is usually the case) and have the peripheral driver initialize the DMA driver (at the same time passing the peripheral device pointer to the DMA driver)?

1. Updated commit message explaining the reason for the change.
2. Agree with phandle name change as it is more meaningful, updated it.
3. Yes, normally DMA node is provided to peripheral in case of independent DMA but in case of LPSS DMA it depends on the peripheral to get its base address. During init of the DMA itself we need the peripherals reg address and DMA device pointer is needed during the API call of peripheral. Regarding circular dependency, I will be getting the DMAs device node using `device_supported_handles_get` and enabling `DEVICE_DEPS` config.

2023-09-25 16:07 UTC, jhedberg approved these changes

2023-09-25 18:53 UTC, teburd approved these changes

2023-09-25 22:43 UTC, merged