Add CONFIG_MCUBOOT_BOOTLOADER_MODE_WITH_DOWNGRADE_PREVENTION to MCUboot module
zephyrproject-rtos/zephyr pull request #63053
Opened 2023-09-25 13:49 UTC by de-nordic

2023-09-25 14:05 UTC, nordicjm reviewed
What would be good for this is if an option was added to sysbuild so that it could enable the option in MCUboot automatically

2023-09-25 14:09 UTC, de-nordic commented on doc/releases/release-notes-3.5.rst
> +    with download prevention enabled. This option is automatically selected for
Fixed

2023-09-25 14:17 UTC, nordicjm commented on modules/Kconfig.mcuboot
> +	  Selected mode supports downgrade prevention, where you cannot switch to
Duplicated line

2023-09-25 14:17 UTC, nordicjm commented on doc/releases/release-notes-3.5.rst
> +    with downgrade  prevention enabled. This option is automatically selected for
double space

2023-09-25 14:59 UTC, de-nordic commented on modules/Kconfig.mcuboot
> +	  Selected mode supports downgrade prevention, where you cannot switch to
Fixed

2023-09-25 14:59 UTC, de-nordic commented on doc/releases/release-notes-3.5.rst
> +    with downgrade  prevention enabled. This option is automatically selected for
Fixed

2023-09-26 11:54 UTC, carlescufi requested changes

2023-09-26 11:54 UTC, carlescufi commented on modules/Kconfig.mcuboot
> +config MCUBOOT_BOOTLOADER_MODE_SUPPORTS_DOWNGRADE_PREVENTION
`MCUBOOT_BOOTLOADER_MODE_HAS_NO_DOWNGRADE`

2023-09-26 11:54 UTC, carlescufi commented on modules/Kconfig.mcuboot
> +config MCUBOOT_BOOTLOADER_MODE_WITH_DOWNGRADE_PREVENTION
`MCUBOOT_BOOTLOADER_NO_DOWNGRADE`

2023-09-26 14:10 UTC, carlescufi approved these changes

2023-09-26 14:41 UTC, nordicjm approved these changes

2023-09-26 14:41 UTC, merged