doc: security: Info for CVE 2023 4264
zephyrproject-rtos/zephyr pull request #63119
Opened 2023-09-26 18:45 UTC by ceolin

Add information about CVE-2023-4264

2023-09-26 20:04 UTC, jhedberg submitted a review, later dismissed

2023-09-27 00:31 UTC, nashif approved these changes, later dismissed

2023-09-29 13:14 UTC, kartben requested changes

2023-09-29 13:14 UTC, kartben commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/pull/61845>`_
Shouldn't backports be listed too?

2023-09-29 13:14 UTC, kartben commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/security/advisories/GHSA-rgx6-3w4j-gf5j>`_
it looks like the advisory only captures #60465 in the list of patches? I don't think that's right as we want people digging into the CVE from someplace else (ex. NIST database) to easily be able to access complete info?

2023-10-03 21:48 UTC, ceolin commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/pull/61845>`_
They were not backported

2023-10-03 21:50 UTC, ceolin commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/security/advisories/GHSA-rgx6-3w4j-gf5j>`_
Yep you are right. I've updated the advisory.

2023-10-03 21:51 UTC, ceolin commented
@kartben AFAICT there is nothing to change in this pr. Have I missed something ?

2023-10-03 22:04 UTC, ceolin commented
pr rebased.

2023-10-04 07:18 UTC, jhedberg submitted a review, later dismissed

2023-10-04 08:51 UTC, kartben commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/pull/61845>`_
looks like at least one was (so maybe others should be to, at least for 3.4)? https://github.com/zephyrproject-rtos/zephyr/pull/61385

2023-10-04 08:52 UTC, kartben commented
> @kartben AFAICT there is nothing to change in this pr. Have I missed something ?

see my latest comment, at least one backport is missing.

2023-10-04 17:36 UTC, ceolin commented on doc/security/vulnerabilities.rst
> +  <https://github.com/zephyrproject-rtos/zephyr/pull/61845>`_
oh, thanks for pointing it out.

2023-10-04 17:36 UTC, ceolin commented
> > @kartben AFAICT there is nothing to change in this pr. Have I missed something ?
> 
> see my latest comment, at least one backport is missing.

thanks ! Added the backported pr.

2023-10-04 18:00 UTC, kartben approved these changes
Thanks

2023-10-04 18:46 UTC, jhedberg approved these changes

2023-10-04 18:46 UTC, merged