tests: kernel: Verify the call to thread abort handler
zephyrproject-rtos/zephyr pull request #6314
Opened 2018-02-22 07:40 UTC by spoorthik

The test sets an abort handler and checks if it is called
when the thread is aborted.

Signed-off-by: Spoorthi K <spoorthi.k@intel.com>

2018-02-22 12:11 UTC, nashif requested changes

2018-02-22 12:11 UTC, nashif commented on tests/kernel/threads/lifecycle/lifecycle_api/src/main.c
> +			 ztest_unit_test(thread_abort_function)
please use test_\<test name\> for test functions.

2018-02-22 18:17 UTC, tyrantlizard77 approved these changes
LGTM other than @nashif comment on naming.
We really need a proper API for setting thread abort functions though, people should not be directly fiddling with struct k_thread members.

2018-02-23 05:17 UTC, spoorthik commented
@nashif @andrewboie : Thanks for the review comments. I have addressed them.

2018-02-23 18:45 UTC, nashif approved these changes

2018-02-23 18:45 UTC, merged