Bluetooth: Audio: Update audio location definitions
zephyrproject-rtos/zephyr pull request #63272
Opened 2023-09-29 03:15 UTC by 0bijian0

The meaning of bit0 in the audio location bitmap will change to mono audio, so we update the audio location macro and releated test cases.

Refer to BT SIG ES-22266.

2023-09-29 08:03 UTC, Thalley commented
@0bijian0 Why was this PR recreated, rather than updating https://github.com/zephyrproject-rtos/zephyr/pull/61446?

2023-09-29 08:04 UTC, Thalley commented
Link to the erratum: https://bluetooth.atlassian.net/jira/software/c/projects/ES/issues/ES-22266

It has been approved, but not incorporated yet, thus marking this with DNM until it has been incorporated

2023-09-29 08:06 UTC, 0bijian0 commented
> Link to the erratum: https://bluetooth.atlassian.net/jira/software/c/projects/ES/issues/ES-22266
> 
> It has been approved, but not incorporated yet, thus marking this with DNM until it has been incorporated

ok

2023-09-29 08:08 UTC, 0bijian0 commented
> @0bijian0 Why was this PR recreated, rather than updating #61446?

there are some issues when rebase update, so close old PR

2023-09-29 08:11 UTC, Thalley commented
> > @0bijian0 Why was this PR recreated, rather than updating #61446?
> 
> there are some issues when rebase update, so close old PR

In the future please try to fix the issues instead of recreating PRs - Feel free to ask for help if you have trouble doing that :) We lose all comment history etc. when you create a new PR

2023-09-29 08:12 UTC, 0bijian0 commented
> > > @0bijian0 Why was this PR recreated, rather than updating #61446?
> > 
> > 
> > there are some issues when rebase update, so close old PR
> 
> In the future please try to fix the issues instead of recreating PRs - Feel free to ask for help if you have trouble doing that :) We lose all comment history etc. when you create a new PR

Get, thanks a lot.

2023-12-21 01:55 UTC, 0bijian0 commented
@Thalley this Adopted in https://www.bluetooth.com/specifications/specs/basic-audio-profile-1-0-1/
shall we merge it ?

2023-12-21 08:45 UTC, Thalley commented
> @Thalley this Adopted in https://www.bluetooth.com/specifications/specs/basic-audio-profile-1-0-1/ shall we merge it ?

The erratum is not yet released, it has only been approved. It will likely be part of BAP 1.0.2 which has not yet been released, so we cannot release this yet.

2024-01-16 08:27 UTC, thoh-ot commented
Errata 22266 was expedited and approved by the Bluetooth SIG Board of Directors, 19th December 2023 and is now mandatory to support when claiming support for BAP 1.0.1 as stated by https://www.bluetooth.com/specifications/specs/basic-audio-profile-1-0-1/

2024-01-16 10:03 UTC, Thalley requested changes
Please also have a look at `pacs.c` to see if there are any changes necessary there, e.g. https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/pacs.c#L411 should not reject `location == 0` anymore.

2024-01-16 13:31 UTC, Thalley approved these changes

2024-01-16 14:37 UTC, kruithofa approved these changes

2024-01-16 19:27 UTC, merged