drivers: modem: modem_cellular: extend CMUX timeout
zephyrproject-rtos/zephyr pull request #63406
Opened 2023-10-02 17:03 UTC by bjarki-trackunit

This commit adds a timeout of 300ms to the generic (gsm_ppp) init chat script. This delay is required for some modems (discovered on a Telit ME910G1-WW) to allow it to enter CMUX mode. Without this delay, the modem simply refuses to respond to any CMUX commands.

2023-10-02 17:05 UTC, rerickson1 requested changes
Add a comment in the source to describe why a delay is important.

2023-10-02 17:14 UTC, bjarki-trackunit commented
@rerickson1 Comment added. An issue is nearly created and will be linked to this PR shortly as well :)

2023-10-02 17:22 UTC, rerickson1 approved these changes

2023-10-03 02:31 UTC, ycsin commented
Would it make sense to make the delay Kconfig-configurable?

2023-10-03 02:38 UTC, ycsin reviewed
Given that there is always a possibility that a modem might need longer delay, would it make sense to make the delay Kconfig(all modem instances use the same delay) or devicetree(per-modem delay) -configurable?

2023-10-03 06:07 UTC, bjarki-trackunit commented
@ycsin  There is a "default" or minimum delay of 100ms, we can make this configurable with Kconfig, but I am unsure if this change is a feature or a bugfix :) WDYT?

2023-10-03 06:19 UTC, ycsin commented
> but I am unsure if this change is a feature or a bugfix

To me it is a bugfix, cc @jhedberg

2023-10-03 07:28 UTC, jhedberg approved these changes

2023-10-03 14:13 UTC, merged