[RFC] dts: bindings: uart-controller: Set detailed flow control options
zephyrproject-rtos/zephyr pull request #63423
Opened 2023-10-03 06:20 UTC by casparfriedrich

Add options to configure all hardware flow control mechanisms provided by the UART API.

This enables user to configure their desired flow control mechanism via device tree. Like the options for parity and stop bits, this one matches the enum provided by the UART API header `uart_config_flow_control` and can be used in a similar way.

As for the RFC: This is a breaking change as it changes the type of the option from `boolean` to `string`

Another option would be to to add a new option like `flow-control` for this and mark `hw-flow-control` as depricated but I'm not sure what the correct way would be.

2023-10-05 20:47 UTC, dcpleung approved these changes, later dismissed

2023-10-07 09:38 UTC, casparfriedrich commented
Rebased and fixed a type. Sorry for the inconvenience @dcpleung.

2023-10-09 17:15 UTC, dcpleung approved these changes

2023-11-19 20:16 UTC, casparfriedrich commented
Rebased

2024-01-19 17:35 UTC, casparfriedrich commented
rebased

2024-01-19 17:40 UTC, dcpleung approved these changes

2024-03-26 13:37 UTC, decsny approved these changes

2024-04-07 18:47 UTC, casparfriedrich commented
Rebased

2024-04-19 13:39 UTC, galak requested changes
Would be good to see the other side of this (ie the code change that will use this property).

Also, as this is the base controller binding, it shouldn't use `default`.

2024-04-19 13:39 UTC, galak commented on dts/bindings/serial/uart-controller.yaml
> +    default: "none"
There shouldn't be a default here.

2024-08-09 17:07 UTC, kartben commented
@casparfriedrich will you be able to address @galak 's comments?

2024-08-09 20:52 UTC, casparfriedrich commented
Thanks for the heads up! I'm quite busy at the moment but I I'll try. Not sure though if I add something ti this pr. I'm working on A driver that would make use of this.

2024-10-23 00:33 UTC, closed without merging