twister: gdbstub: Add GDBStub harness and tests
zephyrproject-rtos/zephyr pull request #63472
Opened 2023-10-03 16:49 UTC by golowanow

Introduce optional debug harness at Twister TestSuite to allow two simultaneous data streams from a test application:
in addition to the test application log the test suite is also able to check another output stream from debugging session which runs with the test.

The Gdbstub Console Harness is implemented to work with GDB Stub Serial backend: Twister starts another process with GDB running a script to connect to the test application and take control over its execution expecting results aligned with the test case.

Add GDBstub over serial test suite.

Add GDBSTUB_TRACE config option to extend GDB backend logging for remote commands received and to debug the GDB stub itself  when needed.

Fix the Twister Console harness ordered 'multi_line' and 'one_line' pattern matching to treat the test as failed if not all the given patterns were found in the console output even if the test application itself returns success.

2023-10-04 17:34 UTC, dcpleung commented on subsys/debug/Kconfig
> +	default n
Default is `n` so there is no need for this line.

2023-10-05 08:12 UTC, gchwier commented
Can you check PR #63061 ?
Maybe could be easier to use pytest instead of adding new harness to twister?

2023-10-05 08:31 UTC, golowanow commented
> Can you check PR #63061 ? Maybe could be easier to use pytest instead of adding new harness to twister?

@gchwier 
with the proposed Twister  debug harness is it possible to extend any twister test with additional GDB control flow using the same yaml syntax for test cases. This feature can be used to automate investigations e.g. of test cases with 'random' errors.

The pytest plugin with gdbstub  is useful for sure with pytest-oriented test collections or to automate some complex non-linear debugging scenario. I'm going to extend #63061 sample as well and compare its performance on bulk CI executions.

2023-10-05 14:51 UTC, nashif requested changes
This is duplicating functionality already proivided by pytest. Using console evaluation based on regex is something we want to avoid in tests, this primarily reserved for samples. It will be very difficult to maintain something like this cross architecture and extend tests.

| This feature can be used to automate investigations e.g. of test cases with 'random' errors.

such investigation need to be done outside of twister. We should not look at twister as a debugging tool.

Adding such usecase/feature specific harnesses, i.e. gdb_stub is not scalable and will introduce more complexity into twister, something we can avoid by using pytest. 

I suggest to move the gdb stub to become a test and enhance it instead of introducing a dedicated gdb stub harness that will be limited, i.e. you will not be able to simulate interactive  gdb sessions with that...

2023-10-05 15:48 UTC, golowanow commented
@nashif, this proposal is to to extend debug capabilities while testing to investigate difficult issues while running tests on CI ('at scale').

It is currently related to the GDBstub Zephyr software backend, but the same 'debug harness' can be used with other debug agents.

It doesn't depend on pytest plugin for simplicity and to allow any existent test to be debugged if needed.

For example, if we have some test for HW sensors which sometimes/rarely fails and it is difficult to catch manually why.
We can quite simply add debug harness definition to that test and to collect more low level data while the test application runs almost as usual, at certain GDB watchpoints, without changing the application itself, just with GDB script and few optional regexp patterns to check the gdb script itself works properly.
Another related use case is to quickly implement a mock, e.g. for a sensor.
These use cases will reuse what developer has done to investigate a problem manually with gdb. It does not require someone to develop a new python test for that.

An interactive test is also possible to implement this way, as a GDB script with some if/else logic, but it is not a main purpose for this feature extension.

2024-12-19 00:35 UTC, closed without merging