kernel: timer: Fix race condition in k_timer_start
zephyrproject-rtos/zephyr pull request #63491
Opened 2023-10-03 23:51 UTC by sousapedro596

The documentation suggests that k_timer_start can be invoked from ISR and preemptive contexts, however, an assertion failure occurs if one k_timer_start call preempts another for the same timer instance. This commit mitigates the issue by implementing a spinlock throughout the k_timer_start function, ensuring thread safety.

Fixes: #62908

#### Problems addressed:
* Concurrent calls to `k_timer_start` for the same timer instance from different contexts could lead to a race condition.
* The race condition could trigger an assertion failure if one `k_timer_start` call preempts another (	`__ASSERT(!sys_dnode_is_linked(&to->node), "");`
)
* Due to the race condition, the timer configuration could be incorrect, causing unexpected behavior.

Used the sample mentioned in the issue (#62908) to test and created this one and also replicated with `qemu_x86-64`: https://github.com/zephyrproject-rtos/zephyr/commit/d2d84e94b9487e0003b4835910eb2ed1022a6de0

**Note:** This is my first Pull Request to Zephyr, decided to start after checking issue #62908 (all the credit to the finding) Feedback is highly appreciated and please help me to review any potential problems with this change that I might be overlooking.

2023-10-04 13:18 UTC, peter-mitsis commented
This is a nice find! However, upon further reading, I observe that we still have a mismatch between that which is documented for _k_timer_start()_ and that which is implemented.

The documentation states ...

> Attempting to start a timer that is already running is permitted. The timer's status is reset to zero and the timer begins counting down using the new duration and period values.

This would suggest that if the _duration_ parameter is set to _K_FOREVER_, then that should not result in an immediate return, but should instead reset the timer.

2023-10-04 15:32 UTC, p-sousa commented
@peter-mitsis Thank you! Really happy to take care of that too, do you think it should be solved in the scope of this PR?

> This would suggest that if the duration parameter is set to K_FOREVER, then that should not result in an immediate return, but should instead reset the timer.

Did not tested yet, but basically, if we reschedule with `k_timer_start` with `duration` set to `K_FOREVER` the timer will keep the previous configuration. How do you think this could be addressed? 
I have a couple of concerns:
* Despite the documentation this may break existing applications that are doing this and still rely on a running timmer afterward. Not sure if I should worry about this one.
* What would be the point of rescheduling to `K_FOREVER` instead of using `k_timer_stop`? 
The only thing that comes to mind is to stop the timer without calling the `stop_fn`. But in this case, the documentation of `K_TIMER_DEFINE` and `k_timer_init`gets ambiguous too:
    > stop_fn	Function to invoke if the timer is stopped while running.
    
    Since we define a function that will be called when the timer stops, `stop_fn`, and in practice, both `k_timer_stop` and a `k_timer_start` rescheduling to `K_FOREVER` will effectively stop the timer. Would it be ok to assume that the `stop_fn` will only be called with `k_timer_Stop`?
    Moreover, if we go this way we also need to handle the case for `k_timer_start` with `duration` set to `K_FOREVER` the first time it is called (not rescheduling) and in that specific case it looks okay to behave as it is today.

At this point I may be overthinking this, can you pl share your thoughts @peter-mitsis? Do you agree with my reasoning?

2023-10-04 16:00 UTC, cfriedt submitted a review, later dismissed

2023-10-04 18:03 UTC, peter-mitsis submitted a review, later dismissed
As I ponder things, the issue I identified is a separate issue and does not need to be dealt with within the bounds of this PR.

2023-10-05 07:22 UTC, carlescufi requested changes

2023-10-05 07:22 UTC, carlescufi commented on kernel/timer.c
> +	 * This addresses the race condition described in issue #62908.
Please don't refer to GitHub issues in the kernel code comments. Use the commit message for that.

2023-10-05 07:22 UTC, carlescufi commented on kernel/timer.c
> +	 * mitigating issues when k_timer_start is called concurrently
mitigating or eliminating? It's important to be clear here

2023-10-05 14:51 UTC, sousapedro596 commented
@carlescufi Rephrased the whole comment and removed the mention of the issue, please re-review. 
@cfriedt @peter-mitsis please re-review.
Thank you!

2023-10-05 17:35 UTC, peter-mitsis approved these changes

2023-10-18 12:58 UTC, fabiobaltieri approved these changes

2023-10-18 13:02 UTC, fabiobaltieri commented
@andyross (and other Kernel collabs) could you take a look? We are pretty late in the release stages, if you want to discuss whether this should classify as release blocker this is the right moment, otherwise we could let it go for 3.6 and backport it later.

2023-10-18 13:12 UTC, peter-mitsis commented
FWIW, my vote is to backport it at a later time as I suspect that this is a situation that we do not run into all that often.

2023-10-18 13:19 UTC, nashif approved these changes

2023-10-18 15:12 UTC, andyross approved these changes
Nice catch.

2023-10-18 15:12 UTC, andyross commented on kernel/timer.c
> +	 * timer instance.
Not worth a -1, but if you respin I'd suggest removing this comment.  This locking strategy is 100% conventional and the comment is basically just saying "this needs a lock".  Synchronization comments should explain weird of surprising interactions, not the normal stuff.

2023-10-18 15:12 UTC, andyross commented on kernel/timer.c
> +		k_spin_unlock(&lock, key);
No need to check this inside the lock, FWIW.  Saves a line of code and a tiny bit of CPU time for a pathological case.

2023-10-18 15:14 UTC, andyross commented
Regarding release management: this is a real fix, but seems low priority unless someone is being bitten by it in production code.  No preference on my part as to squeezing into the release vs. waiting for a backport.

2023-10-18 15:44 UTC, fabiobaltieri commented
> Regarding release management: this is a real fix, but seems low priority unless someone is being bitten by it in production code. No preference on my part as to squeezing into the release vs. waiting for a backport.

Thanks Andy, since we are very late in the release stage, if there's no strong feeling I think it's fair to relegate this to a backport. (cc @jhedberg)

2023-10-19 01:17 UTC, cfriedt approved these changes
Lgtm - I would also recommend argument checking before the lock. Otherwise 👍

2023-10-23 10:10 UTC, carlescufi approved these changes

2023-10-23 10:10 UTC, merged