boards: add support for QT Py RP2040
zephyrproject-rtos/zephyr pull request #63554
Opened 2023-10-05 01:24 UTC by hlord2000

Adds support for the Adafruit QT Py RP2040.

2023-10-16 05:35 UTC, soburi requested changes

2023-10-16 05:35 UTC, soburi commented on boards/arm/adafruit_qt_py_rp2040/adafruit_qt_py_rp2040.dts
> +&usbd {
In generally, usbd has set zephyr_udc0 label.
It seems better to follow that custom.

2023-11-26 21:08 UTC, yonsch approved these changes
LGTM, @hlord2000 can you fix the request made by @soburi ?

2023-12-16 14:56 UTC, raveious commented
bump!

2023-12-16 15:37 UTC, raveious commented
So I was just about to open a PR for the same board when I found this PR. I pulled change and it seems to work just fine with the samples I tried out on it.

Is there any reason why USB CDC ACM is setup as the console? A lot of the RP2040 boards have a UART as the console, and this board seems to be able to do it too.

Is there anything I can do to help get this merged?

2023-12-17 00:20 UTC, raveious commented
Ok. I got bored. I pulled this branch and did all the actions. If this PR doesn't get figured out, I can open a new one with everything done.

2023-12-17 01:56 UTC, hlord2000 commented
> So I was just about to open a PR for the same board when I found this PR. I pulled change and it seems to work just fine with the samples I tried out on it.
> 
> 
> 
> Is there any reason why USB CDC ACM is setup as the console? A lot of the RP2040 boards have a UART as the console, and this board seems to be able to do it too.
> 
> 
> 
> @hlord2000 @soburi Is there anything I can do to help get this merged?

#I will update based on your fork in a bit. I chose USB CDC ACM for this board since it's what circuitpython etc use on xiao form factor boards, may be best to switch back.

2023-12-17 02:58 UTC, raveious commented
> > So I was just about to open a PR for the same board when I found this PR. I pulled change and it seems to work just fine with the samples I tried out on it.
> > Is there any reason why USB CDC ACM is setup as the console? A lot of the RP2040 boards have a UART as the console, and this board seems to be able to do it too.
> > @hlord2000 @soburi Is there anything I can do to help get this merged?
> 
> #I will update based on your fork in a bit. I chose USB CDC ACM for this board since it's what circuitpython etc use on xiao form factor boards, may be best to switch back.

I have everything done. Want me to just make a new PR?

2023-12-17 03:00 UTC, hlord2000 commented
> > > So I was just about to open a PR for the same board when I found this PR. I pulled change and it seems to work just fine with the samples I tried out on it.
> 
> > > Is there any reason why USB CDC ACM is setup as the console? A lot of the RP2040 boards have a UART as the console, and this board seems to be able to do it too.
> 
> > > @hlord2000 @soburi Is there anything I can do to help get this merged?
> 
> > 
> 
> > #I will update based on your fork in a bit. I chose USB CDC ACM for this board since it's what circuitpython etc use on xiao form factor boards, may be best to switch back.
> 
> 
> 
> I have everything done. Want me to just make a new PR?

Sure! Can you comment the PR link so I can check it out too? Thanks for fixing things.

2023-12-17 12:19 UTC, raveious commented
> > > > So I was just about to open a PR for the same board when I found this PR. I pulled change and it seems to work just fine with the samples I tried out on it.
> > 
> > 
> > > > Is there any reason why USB CDC ACM is setup as the console? A lot of the RP2040 boards have a UART as the console, and this board seems to be able to do it too.
> > 
> > 
> > > > @hlord2000 @soburi Is there anything I can do to help get this merged?
> > 
> > 
> > > 
> > 
> > 
> > > #I will update based on your fork in a bit. I chose USB CDC ACM for this board since it's what circuitpython etc use on xiao form factor boards, may be best to switch back.
> > 
> > 
> > I have everything done. Want me to just make a new PR?
> 
> Sure! Can you comment the PR link so I can check it out too? Thanks for fixing things.

Take a look at #66603

2023-12-22 11:26 UTC, raveious commented
Other PR merged, so this can be closed now.

2023-12-22 11:35 UTC, closed without merging