Gd32 f4xx usb
zephyrproject-rtos/zephyr pull request #63585
Opened 2023-10-05 15:20 UTC by lmikl

Begin to USB for gigadevice GD32f4xx. only FS.

Only issue : Sometimes it have 2 "same" interrupts on the receive endpoint. So it receive 2 times the same message.
If someone can be search the issue.

2023-10-05 15:57 UTC, jfischer-no requested changes
Please read
- https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style
- https://kernel.org/doc/html/latest/process/coding-style.html
- https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines
- https://docs.zephyrproject.org/latest/connectivity/usb/device/api/usb_dc.html
- Please no "remove comment" or similar commits.
- There must be no doxygen comments in the driver source code.

2023-10-18 10:36 UTC, nandojve requested changes
I took liberty to change PR name to reflect the driver. This is an USB IP shared between devices and not specific to a particular one.

I didn't look the driver itself and I'll review hal in another time.

2023-10-18 10:36 UTC, nandojve commented on dts/bindings/usb/gd,gd32-otgfs.yaml
> +
Try use up to 80 cols always possible.
You must add devicetree documentation here with examples. Each non standard property should be very well documented in a way that devicetree maintainers don't need look in the datasheet.

2023-10-18 10:36 UTC, nandojve commented on dts/bindings/usb/gd,gd32-otgfs.yaml
> +    description: PHY provider specifier
You must add devicetree documentation here with examples. Each non standard property should be very well documented in a way that devicetree maintainers don't need look in the datasheet.

2023-11-28 17:52 UTC, closed without merging