drivers: spi: nrfx: minor driver improvements
zephyrproject-rtos/zephyr pull request #63623
Opened 2023-10-06 12:57 UTC by awojasinski-nordicsemi

Gathered a few small patches with minor improvements in Nordic's SPI SHIM

2023-10-27 07:40 UTC, anangl requested changes
Please remove those "cherry picked from" notes from commit messages in 4f7c889fe678708cdb729e01280ead3119392561 and 5d65932efb0b8b04f5f925014f1e734c92863c00.

2023-11-14 07:19 UTC, anangl approved these changes

2023-11-15 14:25 UTC, awojasinski-nordicsemi commented
@tbursztyka @teburd please take a look

2023-11-29 10:29 UTC, carlescufi approved these changes

2023-11-29 10:30 UTC, merged