boards: doc: Add programming tabs for mimx8mq_evk
zephyrproject-rtos/zephyr pull request #63676
Opened 2023-10-09 07:48 UTC by jeppenodgaard

Improve documentation by putting programming methods into tabs.

2023-10-09 08:25 UTC, dbaluta approved these changes, later dismissed

2023-10-09 09:38 UTC, kartben requested changes
good idea!
Note that you may also want to look into fixing the rendering of L129-L139, it doesn't look quite right and probably shouldn't be a code block? Might also make sense to explain what are the differences between all the available flash and sram options?

2023-10-09 09:38 UTC, kartben commented on boards/arm/mimx8mq_evk/doc/index.rst
> +      This procedure requires `screen` and `lrzsz` to be installed.
```suggestion
      This procedure requires ``screen`` and ``lrzsz`` to be installed.
```

2023-10-09 09:38 UTC, kartben commented on boards/arm/mimx8mq_evk/doc/index.rst
> +      Send the compiled ``zephyr.bin`` with ``sx`` by pressing Ctrl-a followed by ':'
```suggestion
      Send the compiled ``zephyr.bin`` with ``sx`` by pressing :kbd:`Ctrl-a` followed by :kbd:`:`
```

2023-10-09 14:09 UTC, jeppenodgaard commented
> good idea! Note that you may also want to look into fixing the rendering of L129-L139, it doesn't look quite right and probably shouldn't be a code block? Might also make sense to explain what are the differences between all the available flash and sram options?

Thanks @kartben ! I've added your suggestions.
I am not quite sure how to fix that part of the documentation.
It was added in https://github.com/zephyrproject-rtos/zephyr/pull/37158. Maybe @KwonTae-young has an idea?

2023-10-16 08:41 UTC, jeppenodgaard commented
Hi @kartben.
Since @KwonTae-young has not yet responded, is it ok to consider your L129-L139 suggestions to be out of scope of this PR?

2023-10-16 09:11 UTC, kartben approved these changes

2023-10-16 09:14 UTC, jeppenodgaard commented
Hi @dbaluta. Can you re-review please?

2023-10-16 09:16 UTC, iuliana-prodan approved these changes

2023-10-16 11:08 UTC, jhedberg approved these changes

2023-10-16 14:34 UTC, fabiobaltieri approved these changes

2023-10-16 14:35 UTC, merged