doc: release-notes: Add 3.5.0 release notes for random and entropy
zephyrproject-rtos/zephyr pull request #63715
Opened 2023-10-09 20:00 UTC by ceolin

Release notes for entropy drivers and random subsys.

2023-10-09 20:15 UTC, kartben requested changes

2023-10-09 20:15 UTC, kartben commented on doc/releases/release-notes-3.5.rst
> +  * Add a requirement to method entropy_get_entropy() be thread safe because
```suggestion
  * Added a requirement for ``entropy_get_entropy()`` to be thread-safe because
```

2023-10-09 20:15 UTC, kartben commented on doc/releases/release-notes-3.5.rst
> +  * :kconfig:option:`CONFIG_XOROSHIRO_RANDOM_GENERATOR`, deprecated long time ago, is finally removed.
If it's removed then:


```suggestion
  * ``CONFIG_XOROSHIRO_RANDOM_GENERATOR``, deprecated a long time ago, is finally removed.
```

2023-10-10 01:48 UTC, kartben approved these changes

2023-10-10 09:41 UTC, fabiobaltieri approved these changes

2023-10-10 09:42 UTC, jhedberg approved these changes

2023-10-10 09:42 UTC, merged