Add ztest for kernel event logger.
zephyrproject-rtos/zephyr pull request #6381
Opened 2018-02-26 13:05 UTC by SavinayDharmappa

2018-02-27 21:31 UTC, lpereira commented on subsys/logging/kernel_event_logger.c
> +sys_k_timer_func_t _sys_k_get_time = _timer_cycle_get_32;
What is the build error this is fixing?

2018-02-27 22:42 UTC, lpereira reviewed
I'm having a hard time figuring out what this is testing exactly.  What are you looking at when things fail?  What are you looking at when things are working as they should?

2018-03-04 21:15 UTC, nashif requested changes

2018-03-04 21:15 UTC, nashif commented on tests/subsys/logging/kernel_event_logger/src/main.c
> +	event_logger();
shouldnt this be started is coop thread?

2018-03-04 21:15 UTC, nashif commented on tests/subsys/logging/kernel_event_logger/testcase.yaml
> +    platform_whitelist: qemu_x86
why are we whitelisting only qemu?

2018-03-04 21:15 UTC, nashif commented on tests/subsys/logging/kernel_event_logger/src/main.c
> +		zassert_not_equal(UNKNOWN_EVENT, event_id, "Unknown event");
that is the only test I see in here, how are we verifying all events you have below?

2018-04-07 03:02 UTC, nashif commented
closing, this interface will be deprecated.

2018-04-07 03:02 UTC, closed without merging