Document modem subsystem
zephyrproject-rtos/zephyr pull request #63949
Opened 2023-10-14 14:26 UTC by bjarki-trackunit

2023-10-16 21:12 UTC, fabiobaltieri approved these changes, later dismissed

2023-10-16 21:19 UTC, kartben requested changes
Thanks Bjarki!
Spotted a small typo

2023-10-16 21:19 UTC, kartben commented on doc/services/modem/index.rst
> +Modems are self-contained devices which implement the hardware and
nit:
```suggestion
Modems are self-contained devices that implement the hardware and
```

2023-10-17 16:13 UTC, bjarki-trackunit commented on doc/services/modem/index.rst
> +Modems are self-contained devices which implement the hardware and
corrected

2023-10-17 16:14 UTC, kartben approved these changes, later dismissed

2023-10-17 16:33 UTC, fabiobaltieri submitted a review, later dismissed

2023-10-17 16:43 UTC, bjarki-trackunit commented
I just rebased it :D

2023-10-17 16:46 UTC, kartben commented
> I just rebased it :D

Darn, I should have added my newly found nits then :D

2023-10-17 16:46 UTC, kartben approved these changes

2023-10-17 16:47 UTC, fabiobaltieri approved these changes

2023-10-17 16:49 UTC, bjarki-trackunit commented
@kartben I will happily fix them after this is merged so I don't have to race against the release notes :)

2023-10-17 16:56 UTC, jhedberg approved these changes

2023-10-17 18:58 UTC, merged