tfm: Enable TFM_EXCEPTION_INFO_DUMP by default
zephyrproject-rtos/zephyr pull request #63978
Opened 2023-10-16 10:50 UTC by SebastianBoe

Exception info dump is a very basic feature so it should IMHO be enabled by default.

For instance, a simple null-pointer exception in the non-secure app will not be logged unless this option is enabled.

2023-10-16 10:53 UTC, microbuilder approved these changes

2023-10-16 12:15 UTC, microbuilder requested changes
Sorry, afterthought ... but should we ensure this is set the 'n' in the hardening list here: https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/kconfig/hardened.csv ?

2023-10-16 13:29 UTC, microbuilder approved these changes, later dismissed

2023-10-17 12:00 UTC, microbuilder commented
@joerchan Hardening is really an afterthought. There are probably plenty of other potentially leaky things we're not flagging, anyway. If you think it isn't useful here, I don't have strong feelings about it either, and feel free to remove it.

2023-10-17 12:03 UTC, microbuilder commented
@d3zd3z Any thoughts yourself on having these things in the hardening CSV or not? 

Maybe we should do this in a separate PR, anyway, and look at other potential TFM flags to add to the list?

2023-10-17 12:06 UTC, joerchan commented
> @joerchan Hardening is really an afterthought. There are probably plenty of other potentially leaky things we're not flagging, anyway. If you think it isn't useful here, I don't have strong feelings about it either, and feel free to remove it.

If you're using TF-M you're probably also interested in hardening though. Right?

2023-10-17 12:09 UTC, microbuilder commented
> If you're using TF-M you're probably also interested in hardening though. Right?

Yes, which is why I suggested it after the fact, but let's think about the other flags we should perhaps be adding rather than a quick one off proposal here.

I meant "afterthought" in the sense thet it occurred to me after I'd already approved this PR, not that hardening is an afterthought itself.

I'd suggested removing it here for now, and we can discuss the approach in a new PR, and debate the pros and cons there?

2023-10-17 12:15 UTC, joerchan commented
> I meant "afterthought" in the sense thet it occurred to me after I'd already approved this PR, not that hardening is an afterthought itself.

Thanks for clarifying, I interpreted it the other way.

It makes more to me go through TF-M hardening in a different PR / issue.

I don't object to changing the default.

2023-10-17 12:19 UTC, SebastianBoe commented
removed the patch to hardening.csv

2023-10-17 12:20 UTC, joerchan approved these changes

2023-10-17 12:23 UTC, joerchan commented
Just as a note to the potential hardening update:
In TF-M the option specifies: "Print the info if the SPM log level is sufficient."
It's the SPM log level that may have to be hardened against, which additionally outputs context information.
Without sufficient log level it just says the type of exception / fault that occured.

2023-10-17 12:25 UTC, microbuilder approved these changes

2023-10-20 17:29 UTC, carlescufi approved these changes

2023-10-20 17:29 UTC, merged