Fixed typos
zephyrproject-rtos/zephyr pull request #64068
Opened 2023-10-18 07:55 UTC by polluks

2023-10-18 08:19 UTC, jukkar commented on doc/_doxygen/doxygen-awesome.css
>      --side-nav-arrow-opacity: 0;
The changes look ok, you need to tweak the commit message a bit.
Please set the commit message something like
```
doc: Fix typos

Fix typos in the documentation.

Signed-off-by: <add here your email id>
```

2023-10-18 12:57 UTC, kartben commented
@polluks Thank you very much for taking the time to send this PR. Any chance you could amend your commit as per @jukkar 's recommendation? You will also need to properly set your author name in the form "First Last".
Thank you!

2023-10-23 13:41 UTC, tejlmand commented
@polluks thanks for fixing all those typos.

Regarding the comment by @jukkar, then please note that you only changed the text in the PR title and description, but not in the commit message itself.

You can read more on commit messages here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

To update your current commit, then you can do:
```
$ git commit --amend
```
and then edit the commit message, and once it has been updated, then push your changes to your branch using `git push -f https://github.com/polluks/zephyr HEAD:main`

2023-10-26 01:44 UTC, mbolivar-ampere requested changes
Thank you! But please drop the 'lowercased' changes from the devicetree docs.

2023-10-26 01:44 UTC, mbolivar-ampere commented on doc/build/dts/intro-scope-purpose.rst
> -generated macros have some lowercased letters, while the ``devicetree.h`` macro
"lowercased" is not a typo:

> lowercase
> [verb](https://www.merriam-webster.com/dictionary/verb)
> lowercased; lowercasing
>
> [transitive verb](https://www.merriam-webster.com/dictionary/transitive)
> : to print or set in lowercase letters

https://www.merriam-webster.com/dictionary/lowercase

2023-10-26 14:00 UTC, jukkar commented
Please squash the commits together, fix the commit message as described before and force push the changes.

2023-10-27 11:06 UTC, polluks commented
> Please squash the commits together, fix the commit message as described before and force push the changes.

I'm not fit in rebasing...

2023-10-27 12:42 UTC, kartben commented
> > Please squash the commits together, fix the commit message as described before and force push the changes.
> 
> I'm not fit in rebasing...

@polluks this should help https://asciinema.org/a/tcQBUH1UXUi3ZxdPg00vOGUby

2024-03-06 00:29 UTC, closed without merging