drivers: mfd: gpio: adjust init priority
zephyrproject-rtos/zephyr pull request #64072
Opened 2023-10-18 11:47 UTC by bbilas

Take into account the SPI bus init priority that can be used for MFD drivers.

2023-10-18 15:38 UTC, aasinclair commented
This one needs updating too:
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/watchdog/Kconfig.npm1300#L16

2023-10-23 12:44 UTC, aasinclair approved these changes

2023-10-25 11:45 UTC, bbilas commented
@gmarull would you mind taking a look at it?

2023-10-25 11:47 UTC, gmarull requested changes
some of these devices are I2C only, so why are they changed?

2023-10-25 11:54 UTC, bbilas commented
> some of these devices are I2C only, so why are they changed?

Due to `MFD_INIT_PRIORITY` change. Let me know if I'm wrong but I thought if they depend on that priority, they also should be changed accordingly.

2023-10-26 07:47 UTC, gmarull approved these changes

2023-10-26 07:50 UTC, merged