drivers: rtc: new maxim ds1307 rtc driver
zephyrproject-rtos/zephyr pull request #64219
Opened 2023-10-22 12:19 UTC by arun-mani-tech

Added rtc driver for ds1307. It allows to read and set the date and time

2023-10-24 05:02 UTC, arun-mani-tech commented
@bjarki-trackunit Kindly have a look

2023-10-24 06:27 UTC, bjarki-trackunit requested changes
Overall it looks good, I have a few requests I have outlined that need to be addressed :)

2023-10-24 06:27 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +	struct k_mutex lock;
You should use a spinlock here, since mutex ownership is not used :)

2023-10-24 06:27 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +
You should add a check here to validate the chip is indeed in 24 hour mode, if not, return -ENODATA as the time has not been configured correctly :)

2023-10-24 06:27 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +	return ((ch >> 7) & 0x1);
The init function must succeed if the device was initialized properly, not if its configured properly (time is set). If the time is not set, the get_time function will fail with -ENODATA with the addition i suggested, and the device will be configured once the time is set on the next rtc_set_time().

A failing init will prevent the system from booting, preventing it from setting the time correctly later

2023-10-24 06:27 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> + */
Remove these comments based on the suggestion later in the init function :)

2023-10-24 06:27 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +
Add an init of the control register here, ensuring no square wave is sent to any output. You can add configuration of the square wave to the devicetree if you want to, but without it, default to no square wave :)

2023-10-25 15:10 UTC, arun-mani-tech commented
@bjarki-trackunit Please review

2023-10-25 15:41 UTC, bjarki-trackunit commented
Looks good, last request, could you run the [RTC API test suite](https://docs.zephyrproject.org/latest/hardware/peripherals/rtc.html#rtc-device-driver-test-suite)? (ignore the y2k test failing once you run it)

2023-10-26 09:19 UTC, arun-mani-tech commented
@bjarki-trackunit I ran RTC API test_suite. All checks are passed except yday, isdst, nsec. Because this chip does not support that

2023-10-26 12:02 UTC, bjarki-trackunit requested changes
This last change should allow it to fail only because of the missing yday :)

2023-10-26 12:02 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +	timeptr->tm_year = bcd2bin(regs[6] & YEAR_BITS);
You must initialize all fields of the `struct tm` according to the documentation here https://docs.zephyrproject.org/latest/hardware/peripherals/rtc.html#c.rtc_time.tm_yday

So add
```
	timeptr->tm_yday = -1;
	timeptr->tm_isdst =  -1;
	timeptr->tm_nsec =  0;
```

2023-10-26 12:28 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ds1307.c
> +	timeptr->tm_year = bcd2bin(regs[6] & YEAR_BITS);
I'm fixing the test as well with this PR https://github.com/zephyrproject-rtos/zephyr/pull/64447, you don't have to wait for it to be merged or anything, just pointing it out :)

2023-10-26 15:47 UTC, bjarki-trackunit approved these changes, later dismissed
Nice work!

2023-10-26 15:52 UTC, arun-mani-tech commented
@bjarki-trackunit Thanks for the review

2023-10-26 17:38 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +		return -ENODATA;
this should probably set `err` and `goto unlock;`

2023-10-26 17:39 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +#define DS1307_INIT(inst)                                                                          \
nit: these are normally named something like `DS1307_DEFINE`, init is the initialization function, this is defining a bunch of stuff.

2023-10-26 17:40 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +	if (regs[2] & (1 << 6)) {
you could probably use a define for this, and use `BIT(6)` to define it.

2023-10-26 17:41 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +	timeptr->tm_isdst =  -1;
nit: double space

2023-10-26 17:41 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +#define DS1307_I2C_ADDR 0x68
leftover definition? the address is taken from the tree

2023-10-26 17:42 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +#include <zephyr/drivers/gpio.h>
I think you can drop this, you don't do any gpio operation in this file

2023-10-26 17:44 UTC, fabiobaltieri commented on dts/bindings/rtc/maxim,ds1307.yaml
> +description: MAXIM DS1307 RTC
nit: Maxim

2023-10-26 18:50 UTC, fabiobaltieri submitted a review, later dismissed

2023-10-26 18:50 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +	if (regs[2] & BIT(6)) {
ok much better, can you add a `#define` for `BIT(6)` though?

2023-10-26 18:50 UTC, fabiobaltieri commented on drivers/rtc/rtc_ds1307.c
> +	err = i2c_write_dt(&config->i2c_bus, tx_buf, sizeof(tx_buf));
I think you could use `i2c_reg_write_byte_dt(&config->i2c_bus, DS1307_REG_CTRL, 0x00);` here and drop the local buffer. A bit more compact.

2023-10-27 04:31 UTC, arun-mani-tech commented
@bjarki-trackunit @fabiobaltieri Gentle ping!

2023-10-27 06:56 UTC, bjarki-trackunit approved these changes

2023-10-27 07:41 UTC, fabiobaltieri approved these changes

2023-10-27 07:43 UTC, fabiobaltieri commented
> @bjarki-trackunit @fabiobaltieri Gentle ping!

No need to ping, GitHub notifications already do it for you.

2023-10-27 08:50 UTC, merged