[v3.2] dts: vendor-prefixes: deprecate facebook and add meta
zephyrproject-rtos/zephyr pull request #64274
Opened 2023-10-23 17:46 UTC by cfriedt

Backport of #61351 for `v3.2-branch`.

Fixes #61337

2023-10-23 18:02 UTC, fabiobaltieri commented
hey @cfriedt, 3.2 is unsupported, don't think we should backport that far

2023-10-23 18:31 UTC, cfriedt commented
@fabiobaltieri - I think we might have had some teams using that branch internally.. but ... trying very much to upstream / reduce forking internally and this is (maybe surprisingly) the easiest way to at least set a good example to ensure things are consistent.

I'm fine with this is dropped, but @henrikbrixandersen reminded me that I had broken backports to update.

CC @DaWei8823

2023-10-23 19:27 UTC, fabiobaltieri commented
I see your point but unless it's really an major obstacle for you I'd rather close this and not push anything on unsupported releases. This in particular is not a big deal, but then we'd end up merging on old release branches forever. I think at that point you should really keep your fork if you are based on a way out of date release.

2023-10-23 20:00 UTC, henrikbrixandersen commented
Not entirely sure why this even needs to be backported (to any branch)? I mean, we usually do not backport deprecations - and we support out-of-tree lists of vendor prefixes.

2023-10-24 17:38 UTC, cfriedt commented
> Not entirely sure why this even needs to be backported (to any branch)? 

Well, it's because facebook legally changed it's name a while ago, we have internal forks of Zephyr, and several teams will need a coherent migration strategy.

> I mean, we usually do not backport deprecations

Yea. I'm not actually sure why facebook was added here in the first place without having an in-tree driver of some kind, but it's there, and we should try not to break out of tree users. I think we have a few drivers that could be submitted upstream before LTS.

> and we support out-of-tree lists of vendor prefixes.

As I mentioned already, doing it in-tree is (maybe surprisingly) the easiest way for me to ensure that it is consistent.

2023-10-24 19:53 UTC, henrikbrixandersen requested changes
I don't think we should backport these kind of changes. We support out-of-tree vendor prefix files for this.

2023-10-25 02:38 UTC, ycsin approved these changes

2023-10-26 00:28 UTC, dkalowsk approved these changes
I don't see the value in the backport to 3.2 as it's not supported, and I don't see Zephyr looking to make a 3.2.x release any time soon.  That said, if it makes a supporter of Zephyr's life easier to have unreleased changes in an upstream branch that won't impact anyone else.. I don't see the downside here.

2023-10-26 02:46 UTC, mbolivar-ampere commented
I agree with @dkalowsk

2023-11-08 12:37 UTC, closed without merging