tests: kernel: Add a test to verify early sleep
zephyrproject-rtos/zephyr pull request #6440
Opened 2018-03-03 15:34 UTC by ramakrishnapallala

Add a test to verify that k_sleep() can be used to put
the calling thread to sleep for a specified number of
ticks during system initialization.

This test is inspired from legacy test_early_sleep test
from v1.7.0 release.

Signed-off-by: Ramakrishna Pallala <ramakrishna.pallala@intel.com>

2018-03-05 10:34 UTC, rgundi requested changes

2018-03-05 22:28 UTC, tyrantlizard77 reviewed
just a minor comment otherwise LGTM

2018-03-06 01:48 UTC, ramakrishnapallala commented on tests/kernel/early_sleep/src/early_sleep.c
> +#if defined(CONFIG_ASSERT) && defined(CONFIG_DEBUG)
yeah, I reused the sleep test, I did not pay much attention this. will fix it,

2018-03-06 02:29 UTC, rgundi approved these changes

2018-03-06 03:00 UTC, nashif approved these changes

2018-03-06 03:00 UTC, merged