doc: drivers: add a paragraph mentioning the initlevels target
zephyrproject-rtos/zephyr pull request #64485
Opened 2023-10-27 09:23 UTC by fabiobaltieri

Add a paragraph mentioning the initlevels target for inspecting the DEVICE_DEFINE and SYS_INIT sequence.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/63867

2023-10-27 09:27 UTC, gmarull submitted a review, later dismissed

2023-10-27 09:31 UTC, kartben requested changes

2023-10-27 09:31 UTC, kartben commented on doc/kernel/drivers/index.rst
> +call as produced by the linker. To do that, use the `initlevel` CMake target,
```suggestion
call as produced by the linker. To do that, use the ``initlevel`` CMake target,
```

2023-10-27 09:32 UTC, fabiobaltieri commented on doc/kernel/drivers/index.rst
> +call as produced by the linker. To do that, use the `initlevel` CMake target,
initlevelS

2023-10-27 09:33 UTC, fabiobaltieri commented on doc/kernel/drivers/index.rst
> +call as produced by the linker. To do that, use the `initlevel` CMake target,
fixed

2023-10-27 09:34 UTC, kartben approved these changes

2023-10-27 15:56 UTC, dcpleung approved these changes

2023-10-27 18:27 UTC, MaureenHelm approved these changes

2023-10-27 20:32 UTC, kartben approved these changes

2023-10-28 02:31 UTC, cfriedt approved these changes

2023-10-28 21:19 UTC, henrikbrixandersen approved these changes

2023-10-28 21:19 UTC, merged