modules: lvgl: make the LVGL module optional
zephyrproject-rtos/zephyr pull request #64495
Opened 2023-10-27 10:52 UTC by faxe1008

Make the LVGL module optional.

2023-10-27 10:58 UTC, kartben requested changes
Didn't realize that LVGL repo is 170MB so I guess it makes sense.
Just a minor request for change.

2023-10-27 10:58 UTC, kartben commented on samples/modules/lvgl/accelerometer_chart/README.rst
> +   .. code-block:: console
```suggestion
   .. code-block:: shell
```

I know this is kinda weird (and tons of occurrences will need to be updated in current docs eventually...) -- see the note here: https://docs.zephyrproject.org/latest/contribute/documentation/guidelines.html#code-and-command-examples about shell  vs. console.

2023-10-27 10:58 UTC, kartben commented on samples/modules/lvgl/demos/README.rst
> +   .. code-block:: console
ditto

2023-10-27 10:58 UTC, kartben commented on samples/subsys/display/lvgl/README.rst
> +   .. code-block:: console
ditto

2023-10-27 11:06 UTC, pdgendt commented on samples/modules/lvgl/accelerometer_chart/README.rst
> +      west config manifest.group-filter +optional
Narrow down to a project filter (ref https://github.com/zephyrproject-rtos/west/issues/696)

```suggestion
      west config manifest.project-filter -- +lvgl
```

2023-10-27 12:04 UTC, pdgendt approved these changes

2023-10-27 12:07 UTC, kartben approved these changes

2023-10-27 12:14 UTC, henrikbrixandersen approved these changes

2023-10-27 12:32 UTC, jfischer-no requested changes
This is too tightly coupled with Zephyr and should not be optional.

2023-10-27 12:48 UTC, faxe1008 commented
> This is too tightly coupled with Zephyr and should not be optional.

From the original PR #61505 the intention of the optional modules is:
```
The idea is to look at the optional manifest as an area for modules that work with Zephyr, but not needed directly by zephyr.
```
At least from my point of view the LVGL module ticks all of those boxes.

2023-10-30 20:24 UTC, MaureenHelm approved these changes

2023-10-30 20:29 UTC, nashif commented
> This is too tightly coupled with Zephyr and should not be optional.

Can you elaborate how is this tightly coupled?

2023-10-30 22:26 UTC, jfischer-no commented
> @jfischer-no
> 
> > This is too tightly coupled with Zephyr and should not be optional.
> 
> Can you elaborate how is this tightly coupled?

We have 11 shields and 12 board containing LVGL configuration, there is also three samples and one test for LVGL in Zephyr tree.  
From the [Integration as optional modules](https://docs.zephyrproject.org/latest/contribute/external.html#integration-as-optional-modules),
"There shall not be any direct dependency added in the Zephyr code tree (Git repository) and all sample or test code shall be maintained as part of the module."

Either this dependencies are removed from the Zephyr tree, or it must remain non-optional.
(Btw, the move to optional breaks user application and IMO should be documented in the migration-guide.)

2023-10-31 11:14 UTC, fabiobaltieri commented
I think @jfischer-no argument make sense, there's quite few boards referring to this from different vendors, it'd be nice to leave it in by default and have one less step for new users to check out a graphic stack.

2023-11-02 08:01 UTC, faxe1008 commented
> We have 11 shields and 12 board containing LVGL configuration, there is also three samples and one test for LVGL in Zephyr tree.
> From the [Integration as optional modules](https://docs.zephyrproject.org/latest/contribute/external.html#integration-as-optional-modules),

Ack. I did not consider this depedency. Thanks for raising your concern 👍

2023-11-02 08:01 UTC, closed without merging