scripts: Fix string pattern on byte like objects error
zephyrproject-rtos/zephyr pull request #646
Opened 2017-06-30 05:25 UTC by punitvara

This patch fixes following error which was blocking -e
argument of python script.

TypeError: cannot use a string pattern on a bytes-like object

Jira: ZEP-2290

Signed-off-by: Punit Vara <punit.vara@intel.com>

2017-06-30 10:43 UTC, nashif requested changes
This does not fix the issue, did you test it?

2017-07-13 18:18 UTC, dbkinder commented on scripts/filter-known-issues.py
> +            for m in re.finditer(b"config_regex", mm, re.MULTILINE):
I'm going to guess that multiline expression matching broke with this change.  @inakypg ?

2017-07-14 10:39 UTC, pfalcon requested changes

2017-07-14 10:39 UTC, pfalcon commented on scripts/filter-known-issues.py
> +            for m in re.finditer(b"config_regex", mm, re.MULTILINE):
This definitely can't be right. Original code used value of `config_regex` var, changed uses literal bytes string `"config_regex"`. If you want to turn `config_regex`'s value to be bytes, you need to put `b` before its value in initialization (before each "subvalue").

2017-07-14 10:44 UTC, pfalcon commented on scripts/filter-known-issues.py
> +    warnings = open(args.warnings, "wb")
The same question. The idea is simple - if a file context text information, it should be open as text (like it was), if it contains binary data - as binary. I doubt that args.warnings refers to a binary file.

2017-07-14 10:47 UTC, pfalcon requested changes
This refers to https://jira.zephyrproject.org/browse/ZEP-2290 , but unfortunately, it doesn't give a way to reproduce the issue. Instead, it shows just a single exception on a single line. Then, this patch looks like overfixing the issue - the problem is in line 62, and that's what needs to be fixed, maybe couple of lines more, not a dozen lines around a script.

2017-07-20 05:55 UTC, punitvara commented
OK. @dbkinder Why shippable is showing errors in documentation ?

2017-07-20 06:00 UTC, punitvara commented on scripts/filter-known-issues.py
> +            for m in re.finditer(b"config_regex", mm, re.MULTILINE):
I tried to add b before 

```
config_regex = \
    "(?P<comment>(^\s*#.*\n)+)" \
    "(?P<regex>(^[^#].*\n)+)"

```
It was throwing me error. Any idea why ?

2017-07-20 06:45 UTC, nashif commented
To see how to reproduce this, look at .shippable.yml.

2017-07-20 07:08 UTC, nashif commented
> OK. @dbkinder @pfalcon Why shippable is showing errors in documentation ?

This script is all about documentation and filtering out known issues. To test it correctly, remove the workaround in .shippable.yml that invokes the script using python2. Now it seems that with your changes  it is not working with python2 as well

2017-07-20 08:13 UTC, pfalcon commented on scripts/filter-known-issues.py
> +            for m in re.finditer(b"config_regex", mm, re.MULTILINE):
@punitvara : there should be `b` before each opening doublequote, i.e.:
~~~
config_regex = \
    b"(?P<comment>(^\s*#.*\n)+)" \
    b"(?P<regex>(^[^#].*\n)+)"
~~~

2017-07-20 09:22 UTC, punitvara commented
This changes removed "byte like object error" but it still now able to find doc.log. I am working on resolution

2017-07-20 09:53 UTC, punitvara commented on scripts/filter-known-issues.py
> +            for m in re.finditer(b"config_regex", mm, re.MULTILINE):
Thanks

2017-07-25 12:02 UTC, nashif requested changes

2017-07-25 12:02 UTC, nashif commented on .shippable.yml
> -            python2 ./scripts/filter-known-issues.py --config-dir .known-issues/doc/ doc.log > doc.warnings;
just remove python2, not the whole line!

2017-07-25 12:12 UTC, punitvara commented on .shippable.yml
> -            python2 ./scripts/filter-known-issues.py --config-dir .known-issues/doc/ doc.log > doc.warnings;
Done

2017-07-26 10:52 UTC, nashif approved these changes

2017-07-26 10:54 UTC, merged