Bt samples bsim
zephyrproject-rtos/zephyr pull request #64628
Opened 2023-10-31 12:53 UTC by aescolar

2023-11-01 10:14 UTC, nordicjm requested changes
sysbuild parts OK

2023-11-01 10:14 UTC, nordicjm commented on samples/bluetooth/unicast_audio_server/sysbuild.cmake
> +		set_property(TARGET ${DEFAULT_IMAGE} APPEND_STRING PROPERTY CONFIG
`set_config_string()` exists for this, but not an issue just a note

2023-11-01 10:14 UTC, nordicjm submitted a review, later dismissed

2023-11-01 10:26 UTC, jhedberg approved these changes, later dismissed

2023-11-01 11:04 UTC, Thalley requested changes

2023-11-01 11:04 UTC, Thalley commented on samples/bluetooth/unicast_audio_server/Kconfig.sysbuild
These `Kconfig.sysbuild` seem to only relate to the nRF5340. Maybe that information should be embedded in the filename?

2023-11-01 11:04 UTC, Thalley commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpunet.conf
Since the sample is referring to `hci_rpmsg` with a specific overlay file, wouldn't it make sense to use that overlay file here? 

Otherwise we wouldn't catch issues with the overlay files.

2023-11-01 11:04 UTC, Thalley commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpuapp.conf
If the purpose of this is to test the sample, shouldn't we use the .conf files from the sample instead?

2023-11-01 11:14 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpunet.conf
Note this is for the simulated cpu net with "infinite" RAM & flash :)
This configuration file exists in case one wants to run these samples tests also in the nrf5340bsim_nrf5340_cpunet bsim regression tests (currently not enabled in CI)

2023-11-01 11:14 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/sample.yaml
> +      - native_sim
The native_posix board file was renamed to native_sim

2023-11-01 11:16 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/src/main.c
> +			unicast_audio_recv_ctr);
PRIu64 is the correct way :), as in principle you cannot assume llu matches a uint64_t type.
I tend recall a couple of years ago a cleanup in the whole tree to align this. I don't recall guidelines though.

2023-11-01 11:21 UTC, aescolar commented on samples/bluetooth/unicast_audio_server/Kconfig.sysbuild
> These Kconfig.sysbuild seem to only relate to the nRF5340

Not exactly. Today it is the only target that requires specificial sysbuild kconfig options. But tomorrow others may follow.

Note the filename is expected by the sysbuild cmake code.

2023-11-01 11:37 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/sysbuild.cmake
> +if(NOT("${SB_CONFIG_NET_CORE_BOARD}" STREQUAL ""))
I wonder... we could end up with a lot of boilerplate really fast.
And [the sysbuild documentation](https://docs.zephyrproject.org/latest/build/sysbuild/index.html) explains how this files are used.
@nordicjm thoughts?

2023-11-01 11:42 UTC, aescolar commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpuapp.conf
I would have liked myself, but I don't see any good way of doing it.
Ideally we would `include` the sample one, but .confs cannot include other files, and cmake picks the specific board overlay automagically from the app main directory `/boards` folder.

2023-11-01 11:46 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/src/main.c
> +
Uhm, then we need a header to share that structure type, and some way for the test to also know how many streams were meant to be running and checked?
Should this be a follow up PR done by somebody who knows this code better than me? :)

2023-11-01 12:04 UTC, aescolar commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpunet.conf
changed

2023-11-01 12:06 UTC, nordicjm commented on samples/bluetooth/unicast_audio_client/sysbuild.cmake
> +if(NOT("${SB_CONFIG_NET_CORE_BOARD}" STREQUAL ""))
I don't see why we would put any documentation like that in these files, we don't put an explanation of what prj.conf files do at the top of them as headers

2023-11-01 12:19 UTC, Thalley commented on samples/bluetooth/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpunet.conf
If the file is not for running the sample as sample (rather than a test), then should it really be in the sample directory?

2023-11-01 12:21 UTC, Thalley commented on samples/bluetooth/unicast_audio_client/src/main.c
> +
> Should this be a follow up PR done by somebody who knows this code better than me? :)

Probably ;) 

It is OK for now, and then we can fix later.

2023-11-01 12:21 UTC, Thalley commented on samples/bluetooth/unicast_audio_client/src/main.c
> +			unicast_audio_recv_ctr);
Right. Perhaps I should start using the `PRI` valuesinstead going forward myself then :)

2023-11-01 12:22 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpunet.conf
In this particular file case, this file is only useful for building the sample locally and giving it a spin against the server sample. As for the test we use the test provided board/.conf.
Still, it has a bit of use, and it does not seem to do much harm there :).

2023-11-01 12:23 UTC, Thalley commented on samples/bluetooth/unicast_audio_client/sysbuild.cmake
> +if(NOT("${SB_CONFIG_NET_CORE_BOARD}" STREQUAL ""))
That's a fair point, although `prj.conf` are used _everywhere_ so it's not a great comparison.

2023-11-01 12:27 UTC, Thalley commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpuapp.conf
I see. So it's from a Cmake perspective impossible to actually test the sample-as-is? We can only test it with some config file we create ourselves here, and then somehow need to manually ensure that they are in sync? Seems like an issue waiting to happen :D 

But if it is not possible, then there's not much we can do, unless we can improve how CMake choses the conf files.

2023-11-01 12:30 UTC, aescolar commented on tests/bsim/bluetooth/audio_samples/unicast_audio_client/boards/nrf5340bsim_nrf5340_cpuapp.conf
correct

2023-11-01 12:31 UTC, Thalley submitted a review, later dismissed

2023-11-01 12:42 UTC, nordicjm submitted a review, later dismissed
sysbuild parts OK

2023-11-01 14:02 UTC, aescolar commented
Added DNM to avoid breaking CI while https://github.com/zephyrproject-rtos/zephyr/pull/64391 is merged.

2023-11-01 14:28 UTC, larsgk commented on samples/bluetooth/unicast_audio_client/README.rst
I think this is great to have included :)

Could it also make sense to add nrf5340_audio_dk_nrf5340_cpuapp in the mix? (even though it's a small local change from the standard dk)

2023-11-01 15:11 UTC, aescolar commented on samples/bluetooth/unicast_audio_client/README.rst
> Could it also make sense to add nrf5340_audio_dk_nrf5340_cpuapp in the mix? 
Added (Though it would have been trivial to add it afterwards)

2023-11-02 14:11 UTC, Thalley commented
@aescolar after the hci_rpmsg rename, it looks as though the sample readmes needs to be updated

2023-11-02 19:58 UTC, Thalley approved these changes

2023-11-03 05:55 UTC, jhedberg approved these changes

2023-11-03 07:35 UTC, merged