modem modules: Add experimental tag
zephyrproject-rtos/zephyr pull request #64663
Opened 2023-10-31 19:40 UTC by bjarki-trackunit

The modem modules are novel and should therefore be marked experimental.

2023-10-31 20:47 UTC, rerickson1 approved these changes, later dismissed

2023-10-31 21:16 UTC, kartben requested changes
Could you also add to https://docs.zephyrproject.org/latest/develop/api/overview.html? Thanks!

2023-11-02 09:18 UTC, kartben approved these changes

2023-11-02 11:50 UTC, nashif approved these changes

2023-11-02 12:59 UTC, rerickson1 approved these changes

2023-11-03 08:56 UTC, merged