board: thingy:52 add mpu9250
zephyrproject-rtos/zephyr pull request #64700
Opened 2023-11-01 15:32 UTC by guissalustiano

I'm trying to add the [Nine-axis motion sensor MPU9250](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_thingy52%2FUG%2Fthingy52%2Fintro%2Ffrontpage.html) to the thing:52, he is supplied by the mpu_regulator already described in the device tree.

I follow the ccs example and [this topic](https://devzone.nordicsemi.com/f/nordic-q-a/64653/thingy52-zephyr-rtos-and-sensor-mpu6060-sample-not-working) in nrf forum but when I run I always receive NIO.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/32439070/e84c4c06-112a-46ca-b40b-f97985d057bf)

I'm messing with this for the first time so I need help figuring out the problem

2023-11-07 15:57 UTC, MaureenHelm requested changes

2023-11-07 15:57 UTC, MaureenHelm commented on boards/arm/thingy52_nrf52832/board.c
> +static int mpu_pwr_ctrl_init(void)
Instead you can update the `status` property of the `mpu_pwr` node in the devicetree

2023-11-07 15:57 UTC, MaureenHelm commented on boards/arm/thingy52_nrf52832/thingy52_nrf52832.dts
> +		accel-dlpf="5.05";
```suggestion
		accel-dlpf = "5.05";
```

2023-11-07 15:59 UTC, gmarull requested changes
make sure sensor driver supports regulator (it needs to be done manually now)

2023-11-07 17:58 UTC, guissalustiano commented
Oops, I got all messed up with the rebase here, I will open a new PR

2023-11-07 17:58 UTC, closed without merging

2023-11-07 22:08 UTC, MaureenHelm commented
> Oops, I got all messed up with the rebase here, I will open a new PR

Please reopen and update this PR instead of creating a new one

2023-11-07 23:49 UTC, guissalustiano commented
Apparently, I couldn't anymore. I needed to rewrite all the commits to remove my mess. Sorry.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/32439070/b3b57e92-3127-4aa0-b012-20ba1b8d7cc1)

2023-11-08 07:52 UTC, martinjaeger commented
You were using your main branch for the PR, which is not recommended.