soc: arm: nxp_imx: rt5xx: make deepsleep pin config functions weak
zephyrproject-rtos/zephyr pull request #64808
Opened 2023-11-04 00:05 UTC by mjchen0

Allows a board to override. A board might not want the ISP pins to be changed because they were configured for alternate function during runtime. A board might also want to do additional deepsleep pin configurations.

2023-11-04 01:37 UTC, dleach02 approved these changes

2023-11-06 18:45 UTC, mjchen0 commented
> > A board might also want to do additional deepsleep pin configurations.
> 
> For this issue, would `pm_notifier_register` be useful?
> 
> @mmahadevan108 - would it be possible to instead make this behavior optional with a Kconfig? That seems a bit more inline with the "Zephyr" way of handling an issue like this

If the current code used a notifier to change the ISP pins, we'd still need to change the notifier if it was in rt5xx/power.c

Flexspi also changes pincfg, but uses the CONFIG_PM_DEVICE method to switch pinctrl config. But ISP isn't a device, so I presume it's using this method instead. I'm wondering if those code should actually be moved. If the ISP pins have default pulls, wouldn't it be better to disable those pulls all the time once we're booted, and not just in deep sleep? Why waste power during runtime? If this code was moved to like board/mimxrt595_evk/board.c's mimxrt595_evk_init(), wouldn't it save power all the time? I wasn't sure if there was any reset path that would get messed up by this though. Is it the ROM that reads the ISP pin values and determines boot, and is it enabling the pulls, or are the pulls enabled by default and the ROM expects the pulls to be enabled when it reads the ISP pins?

2023-11-07 14:46 UTC, DerekSnell commented
Hi @mjchen0 ,
I agree that these pin config functions should be moved to the board files, and removed from the SOC folder.  The board will determine how these pins are used.  And the optimization and usage of these pins should be done at the board level.

Yes, the ROM reads the ISP pins by default after reset.  The ROM uses those pins to determine how it should boot.  And using those ISP pins at boot can also be disabled by programming the OTP fuses.

The app could disable the ISP pull-down resistors all the time to conserve power.  The examples for the NXP EVK only do that during the lowest power modes for ease of use.  But users should have easier control of this in their board files.

Thanks for raising this.

2023-11-07 18:01 UTC, mmahadevan108 approved these changes

2023-11-07 20:05 UTC, danieldegrasse requested changes
I'm going to block this for the time being. I think in this case, we don't need to resort to weak functions to fix the issue here. @mmahadevan108 has offered to create a PR that moves the deepsleep pin configuration code into the RT595 EVK board port (using pm subsystem state callbacks), and should fix this issue in a way that doesn't require the user to redefine these functions at the board level

2024-01-10 17:11 UTC, mmahadevan108 commented
https://github.com/zephyrproject-rtos/zephyr/pull/67453 should fix this issue.

2024-02-01 15:34 UTC, decsny commented
Declining because #67453 removed this code anyways and addressed the same problem, feel free to reopen if you feel otherwise

2024-02-01 15:34 UTC, closed without merging