Bluetooth: Mesh: make sending solicitation pdu independent on gatt proxy client
zephyrproject-rtos/zephyr pull request #64868
Opened 2023-11-06 15:26 UTC by alxelax

The mesh specification doesn't mandate to have both functionalities(sending solicitation pdu and gatt proxy client) at the same time.
PR makes them independent.

2023-11-07 10:19 UTC, akredalen requested changes

2023-11-07 10:19 UTC, akredalen commented on subsys/bluetooth/mesh/shell/od_priv_proxy.c
> +	uint16_t net_idx = bt_mesh_shell_target_ctx.net_idx;
Should this be explicitly defined in shell.c like `dst`?

2023-11-07 10:19 UTC, akredalen commented on subsys/bluetooth/mesh/shell/od_priv_proxy.c
> +		err = bt_mesh_od_priv_proxy_cli_get(net_idx, addr, &val_rsp);
These _get and _set-functions are still expecting `struct bt_mesh_msg_ctx`?

2023-11-07 10:28 UTC, akredalen commented on subsys/bluetooth/mesh/shell/od_priv_proxy.c
> +		err = bt_mesh_od_priv_proxy_cli_get(net_idx, addr, &val_rsp);
Sorry, my code was not up to date.

2023-11-07 16:28 UTC, PavelVPV approved these changes

2023-11-08 08:11 UTC, akredalen approved these changes

2023-11-08 09:08 UTC, merged