runners: jlink: Add support for J-Link ethernet
zephyrproject-rtos/zephyr pull request #64915
Opened 2023-11-07 13:25 UTC by marnold-b

Add support for J-Link with ethernet and J-Link remote server.
`--select=ip` enables the feature and the `--dev-id` is used for the ip
to select the debugger.

The change is backwards compatible, usb is selected by default.

Example to enable ethernet support for any device supported by J-Link in `board.cmake` in the board configuration:

```
board_runner_args(jlink "--device=<device>" "--iface=jtag" "--tool-opt=-jtagconf -1,-1 -AutoConnect 1" "--speed=4000"  "--select=ip")
include(${ZEPHYR_BASE}/boards/common/jlink.board.cmake)
```

Command to flash:
```
west -v flash --dev-id=<ip> -r jlink
```

2023-11-07 13:26 UTC, carlescufi requested changes

2023-11-07 13:26 UTC, carlescufi commented on scripts/west_commands/runners/jlink.py
> +                 select="usb",
I think we should name this `transport` instead, because we may want to generalize this in the future, given that several debuggers support this.

2023-11-07 13:31 UTC, carlescufi commented
Also see https://github.com/zephyrproject-rtos/zephyr/pull/52140.

2023-11-07 13:33 UTC, carlescufi commented on scripts/west_commands/runners/jlink.py
> +                  of the device connected over USB. If the J-Link over ethernet
Please do not use "ethernet" anywhere. Instead please use "ip" or "IP".

2023-11-14 13:17 UTC, marnold-b commented
From my side the requested changes are addressed.
I am also open to the suggested solution in https://github.com/zephyrproject-rtos/zephyr/pull/64915#discussion_r1384923011, just let me know which solution is preferred.

2023-11-14 21:54 UTC, jukkar commented on scripts/west_commands/runners/jlink.py
> +        parser.add_argument('--select', default='usb',
Using dev_id for ip address sounds good. +1 from me.

2023-11-16 08:57 UTC, marnold-b commented on scripts/west_commands/runners/jlink.py
> +        parser.add_argument('--select', default='usb',
@carlescufi I updated the PR to your suggested solution.

2023-12-01 11:49 UTC, marnold-b commented
@carlescufi can you have another look?

2024-01-09 13:44 UTC, carlescufi approved these changes

2024-01-09 13:47 UTC, jukkar approved these changes

2024-01-09 13:49 UTC, merged