drivers: udc: add initial support for DWC2 device controller
zephyrproject-rtos/zephyr pull request #64943
Opened 2023-11-07 23:12 UTC by jfischer-no

Add common DWC2 register header initial device support (UDC API) for DWC2 controller.

2023-11-15 09:55 UTC, tmon-nordic requested changes

2023-11-15 09:55 UTC, tmon-nordic commented on drivers/usb/udc/udc_dwc2.c
> +	unsigned int outeps : 8;
Why not use `uint8_t`?

2023-11-15 10:55 UTC, carlescufi commented
@erwango this driver should work on STM32 devices that use the Synopsys DWC2 IP. Would it be possible for you to test it on those? Additional reviews would be great.

Note: I am aware that there is a [dedicated shim driver](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/usb/udc/udc_stm32.c) that supports all STM32 devices, but this DWC2-specific one should work on any ICs using that IP.

2023-11-16 15:09 UTC, erwango commented
> @erwango this driver should work on STM32 devices that use the Synopsys DWC2 IP. Would it be possible for you to test it on those? Additional reviews would be great.

We can help to test for sure. What would be nice is to add ready-to-use test configurations on impacted boards which would save us some time and allow at least building (and testing) reproducibility. This hasn't been made for https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ethernet/eth_dwmac_stm32h7x.c which isn't build or tested (at least in tree) since years maybe. 
Also maybe increasing automated USB test coverage would be helpful (see https://github.com/zephyrproject-rtos/zephyr/pull/62983) which was rejected for arguable reasons.

> Note: I am aware that there is a [dedicated shim driver](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/usb/udc/udc_stm32.c) that supports all STM32 devices, but this DWC2-specific one should work on any ICs using that IP. We are not talking about replacing the existing driver as was [suggested in this issue](https://github.com/zephyrproject-rtos/zephyr/issues/4412) but rather to verify that this driver does work on the relevant STM32 ICs.

Sure, I'm getting it.

2023-12-15 15:47 UTC, tmon-nordic approved these changes

2023-12-18 08:48 UTC, carlescufi approved these changes

2023-12-18 08:48 UTC, merged