tests: drivers: adc: move ad5592-adc node into native_posix.overlay
zephyrproject-rtos/zephyr pull request #64975
Opened 2023-11-08 15:18 UTC by bbilas

Remove the `app.overlay` file which has been wrongly added in ad3c5a2 commit. Instead of that add the ad5592-adc node into `native_posix.overlay` file.

2023-11-08 15:26 UTC, gmarull approved these changes, later dismissed

2023-11-08 15:33 UTC, martinjaeger requested changes
You need to add one more line to the `cs-gpios`, I think.

2023-11-08 15:34 UTC, bbilas commented
> You need to add one more line to the `cs-gpios`, I think.

Right, thanks.

2023-11-08 15:39 UTC, martinjaeger approved these changes

2023-11-08 15:52 UTC, gmarull approved these changes

2023-11-08 18:00 UTC, MaureenHelm approved these changes

2023-11-08 21:26 UTC, fabiobaltieri approved these changes

2023-11-09 10:23 UTC, carlescufi approved these changes

2023-11-09 10:23 UTC, merged