arch: arm: cortex_m: Move default configs to a file and add consistency checks
zephyrproject-rtos/zephyr pull request #64978
Opened 2023-11-08 15:59 UTC by ithinuel

This PR separates the default configuration setting from main `cmsis_core.h` path and add checks ensuring that Kconfig defines do match CMSIS' configuration.

2023-11-21 16:05 UTC, ithinuel commented
I get the same error on `main` locally, so I'm not sure this issue is related to the changes in this PR.

2023-11-27 08:08 UTC, microbuilder requested changes

2023-11-27 13:58 UTC, microbuilder approved these changes

2023-12-05 06:06 UTC, povergoing approved these changes

2023-12-05 10:19 UTC, merged