cmake: quote MD5_SUM variable in SUBSTRING operation
zephyrproject-rtos/zephyr pull request #64991
Opened 2023-11-08 20:32 UTC by cfriedt

This mitigates the possibility of the following warning

share/zephyr-package/cmake/zephyr_export.cmake:19 (string):
  string sub-command SUBSTRING requires four arguments.

Ideally, we would not need to write a temporary file into the source directory.

Fixes #64990

2023-11-09 13:49 UTC, 57300 commented
> Ideally, we would not need to write a temporary file into the source directory.

Not sure why this was done, but we can do without it:
```cmake
string(MD5 MD5_SUM "${CMAKE_CURRENT_LIST_DIR}")
```

2023-11-09 21:24 UTC, tejlmand submitted a review, later dismissed

2023-11-10 11:38 UTC, nordicjm submitted a review, later dismissed

2023-11-10 11:57 UTC, cfriedt commented
I could add a second commit with the less invasive md5 calculator.

My guess is that the old way was used to support an older version of CMake, but it's probably fair to say that we all have at least the minimum required version now, I would guess.

2023-11-10 12:48 UTC, cfriedt commented
* added commit to use the built-in string(md5 ..) approach
* squashed

2023-11-10 15:13 UTC, 57300 approved these changes

2023-11-12 13:06 UTC, cfriedt commented
@tejlmand - look OK to you?

2023-11-20 17:51 UTC, cfriedt commented
@nordicjm - would you be so kind as to re-ack?

2023-11-20 19:14 UTC, nashif approved these changes

2023-11-21 07:39 UTC, nordicjm approved these changes

2023-11-21 09:12 UTC, tejlmand requested changes
> My guess is that the old way was used to support an older version of CMake, but it's probably fair to say that we all have at least the minimum required version now, I would guess.

I remember facing some issues at the time of creating this, but can't remember if it could be due to old CMake versions in path or if it was due to different MD5 calc result, due to a slight difference between what is calculated when it's a string compared to file content. (couple of things comming to mind could be escaped-chars, spaces in string, trailing (or missing) newlines).

iirc it was related to the content vs a var string, but let me take some time to see if I can find the original reason for current construct.

Temp nack to allow time to investigate on various OS'es

2023-12-02 17:54 UTC, cfriedt commented
@tejlmand - have you had a chance to check this?

2023-12-12 02:12 UTC, cfriedt commented
ping @tejlmand

2023-12-12 09:05 UTC, tejlmand approved these changes
Been checking this in Linux and Windows.

The updated md5 calculation returns identical result as current implementation, which again has been verified to produce same result as `export(PACKAGE Zephyr)` function which is our point of reference.

For those curios, the reason we are not using `export(PACKAGE Zephyr)` is due to the fact that the `export()` function is not available in script mode.

2023-12-12 09:56 UTC, merged