tests: kernel: work_q: Add a testcase
zephyrproject-rtos/zephyr pull request #6519
Opened 2018-03-08 17:18 UTC by SavinayDharmappa

Add a testcase where single work is submitted to
multiple queue. In this case handler invoked only
once as single work cannot be submitted to multiple
queue.

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

2018-03-11 01:45 UTC, nashif requested changes

2018-03-11 01:45 UTC, nashif commented on tests/kernel/workq/work_queue_api/src/test_workq_api.c
> +	zassert_true(k_delayed_work_submit(&new_work, TIMEOUT) < 0, NULL);
check for exact return value here with zassert_equal

2018-03-11 02:10 UTC, nashif commented
there is another branch in the code that is not covered, can you please create a test for this:

https://codecov.io/gh/zephyrproject-rtos/zephyr/src/97331d1e9829c80231e3d336996fba750cb74821/kernel/work_q.c#L130

2018-03-12 14:11 UTC, SavinayDharmappa commented
@nashif incorporated the review comments

2018-03-13 05:31 UTC, ramakrishnapallala submitted a review, later dismissed

2018-03-13 05:31 UTC, ramakrishnapallala commented on tests/kernel/workq/work_queue_api/src/test_workq_api.c
> +	*/
comment is not clear, also use single * in second line.

2018-03-13 14:54 UTC, nashif approved these changes

2018-03-13 14:55 UTC, merged