soc: intel_adsp: call framework callback function for restore
zephyrproject-rtos/zephyr pull request #65394
Opened 2023-11-17 07:52 UTC by RanderWang

Sof will use smp utility in framework and call framework callback function to complete secondary cpu restore.

This PR align with https://github.com/zephyrproject-rtos/zephyr/pull/64755 and https://github.com/zephyrproject-rtos/sof/pull/32

2023-11-17 17:56 UTC, dcpleung requested changes
Please don't use `z_` as prefix. Since it is SoC public, `soc_intel_adsp_` would be better.

2023-11-20 01:19 UTC, RanderWang commented
> Please don't use `z_` as prefix. Since it is SoC public, `soc_intel_adsp_` would be better.

Thanks. I remove the "z_".  I don't adopt "intel_adsp" as prefix since these files are in the directory of "intel_adsp" and follow other function name style.

2023-11-20 16:24 UTC, dcpleung submitted a review, later dismissed

2023-12-13 14:59 UTC, kv2019i requested changes
I have to complain again about the commit message. 

First "Sof" (SOF!) is just one application and doesn't make much sense in context of a Zephyr commit touching low-level SoC code.

And what is "smp utility"? 

How about::
```
When exiting power gated state, call the CPU start function passed to arch_start_cpu(). 
```

2023-12-14 07:33 UTC, RanderWang commented
> I have to complain again about the commit message.
> 
> First "Sof" (SOF!) is just one application and doesn't make much sense in context of a Zephyr commit touching low-level SoC code.
> 
> And what is "smp utility"?
> 
> How about::
> 
> ```
> When exiting power gated state, call the CPU start function passed to arch_start_cpu(). 
> ```

Thanks! much better than mine

2024-01-03 12:01 UTC, kv2019i approved these changes

2024-01-22 02:04 UTC, RanderWang commented
Merged

2024-01-22 02:04 UTC, closed without merging