drivers: can_sam0: added clock configuration for SAME5x devices
zephyrproject-rtos/zephyr pull request #65513
Opened 2023-11-21 10:47 UTC by sebastianschlupp

drivers: can_sam0: added clock configuration for SAME5x devices

also modified the following to support CAN:
soc: same51 and same54: added DFLL48 frequency information
dts: arm: atmel: added can peripherals to same5x.dtsi

Signed-off-by: Sebastian Schlupp <sebastian.schlupp@gmail.com>

2023-11-21 11:16 UTC, str4t0m approved these changes, later dismissed

2023-11-21 12:41 UTC, sebastianschlupp commented
Removed the trailing spaces in the same5x.dtsi file as requested.
Sorry for the mess with merging / reverting, etc. Hope everything is fine now.

2023-11-21 13:25 UTC, henrikbrixandersen requested changes
Please fix indentation and if-clauses as suggested for all occurrences.

2023-11-21 13:25 UTC, henrikbrixandersen commented on drivers/can/can_sam0.c
> +	#if (CONFIG_SOC_SERIES_SAME51 || CONFIG_SOC_SERIES_SAME54)
```suggestion
#if defined(CONFIG_SOC_SERIES_SAME51) || defined(CONFIG_SOC_SERIES_SAME54)
```

2023-11-21 13:25 UTC, henrikbrixandersen commented on drivers/can/can_sam0.c
> +	#elif (CONFIG_SOC_SERIES_SAMC21)
```suggestion
#elif defined(CONFIG_SOC_SERIES_SAMC21)
```

2023-11-21 13:25 UTC, henrikbrixandersen commented on drivers/can/can_sam0.c
> +	#endif
```suggestion
#endif
```

2023-11-21 13:25 UTC, henrikbrixandersen commented on soc/arm/atmel_sam0/same51/soc.h
> + * Copyright (c) 2023 Sebastian Schlupp
Normally, adding a few lines to an existing file does not warrant a copyright notice. Otherwise our files would have _really_ many copyright lines.

2023-11-21 14:35 UTC, sebastianschlupp commented
I did make a mess with the 3 commits which should have been 1. Would it be best to just close the pull-request and open a new one on a new branch with a single commit or should I attempt to get rid of the last commits with the "git reset --hard HEAD~2" command and just amend the required changes to the first commit? I feel like it's the moment to stop attempting to fix it on my own while digging myself deeper and deeper and to wait for feedback of which direction to go :P

2023-11-22 10:37 UTC, sebastianschlupp commented
Considering the failures on the nucleo_f429zi which are completely unrelated to this is there anything else I'd need to do? First contribution here so not exactly if I just need to wait or if something needs to be done by me.

2023-11-26 08:52 UTC, nandojve commented
Hi @sebastianschlupp ,

You should split this PR in 3 commit:

1- dts: arm: atmel: added can peripherals to same5x.dtsi
2- soc: same51 and same54: added DFLL48 frequency information
3- update CAN driver

These 3 commit should be rebased on top of current main.

2023-11-30 13:55 UTC, sebastianschlupp commented
> Hi @sebastianschlupp ,
> 
> You should split this PR in 3 commit:
> 
> 1- dts: arm: atmel: added can peripherals to same5x.dtsi 2- soc: same51 and same54: added DFLL48 frequency information 3- update CAN driver
> 
> These 3 commit should be rebased on top of current main.

done as requested

2023-11-30 17:37 UTC, nandojve submitted a review, later dismissed

2023-11-30 18:43 UTC, str4t0m requested changes
Please fix the commit messages and indentation of the code as reported by the compliance checks (No leading spaces, ... ).

2023-12-01 13:21 UTC, sebastianschlupp commented
> Please fix the commit messages and indentation of the code as reported by the compliance checks (No leading spaces, ... ).

done as requested

2023-12-01 14:10 UTC, henrikbrixandersen commented
> done as requested

Unfortunately, you still missed some. Please take a look at the CI job output (available here for your current push on this PR: https://github.com/zephyrproject-rtos/zephyr/actions/runs/7058482799/job/19221219219?pr=65513) and fix any issues reported there.

2023-12-04 15:49 UTC, nandojve submitted a review, later dismissed

2023-12-04 15:51 UTC, henrikbrixandersen submitted a review, later dismissed

2023-12-04 15:52 UTC, henrikbrixandersen commented
@str4t0m Please revisit.

2023-12-04 19:09 UTC, str4t0m requested changes
Thanks for addressing all the issues!
I didn't check the rationale of the clock source selection in the datasheet, but everything looks fine for me now.
Just one NIT regarding the interrupt priority definitions.

Also, I assume you have tested this on a custom board, but don't have access to the atsame54_xpro board? Because if you would have access to the board, it would be nice to also add definitions for the board such that the driver can be built in CI for this SoC and any regression is detected earlier.

2023-12-05 09:18 UTC, sebastianschlupp commented
> Thanks for addressing all the issues! I didn't check the rationale of the clock source selection in the datasheet, but everything looks fine for me now. Just one NIT regarding the interrupt priority definitions.
> 
> Also, I assume you have tested this on a custom board, but don't have access to the atsame54_xpro board? Because if you would have access to the board, it would be nice to also add definitions for the board such that the driver can be built in CI for this SoC and any regression is detected earlier.

Regarding the rationale for clock source selection, the E5x devices don't have the internal 48MHz oscillator which is used by default for the SAMC21. They have the possibility to use either an external oscillator (XOSC0, XOSC1, XOSC32K) directly or the output of the digital frequency locked loop (fixed to 48MHz). Because this is enabled by default, also fixed in value (like the internal 48MHz oscillator of the C21) and because it has the same value the driver was designed to work with, I chose that as a source. The source for the DFLL48M can be either the internal 32kHz oscillator or an external 32kHz oscillator. In both of the atsame54_xpro boards as well as the atsame51_cnano boards an external 32kHz oscillator is available and used.

Regarding the interrupts, I have only used LINE_0 interrupt initially. After asking about this on discord I have been pointed to the question raised about exactly this topic here: https://github.com/zephyrproject-rtos/zephyr/discussions/61014
I have compared by changes with the ones mentioned by the OP and decided to add the LINE_1 interrupt as well for possible other, future uses. I didn't really spend time on deciding which priority to select. Want me to change this as follows?
interrupts = <78 0>, <78 0>; for both CAN channels?

2023-12-05 12:04 UTC, sebastianschlupp commented on dts/arm/atmel/same5x.dtsi
> +			interrupts = <78 0>, <78 1>;
@str4t0m please see reply in thread

2023-12-07 10:36 UTC, str4t0m commented
> Regarding the interrupts, I have only used LINE_0 interrupt initially. After asking about this on discord I have been pointed to the question raised about exactly this topic here: #61014
> I have compared by changes with the ones mentioned by the OP and decided to add the LINE_1 interrupt as well for possible other, future uses. I didn't really spend time on deciding which priority to select. Want me to change this as follows?
> interrupts = <78 0>, <78 0>; for both CAN channels?

Thanks for the explanations. Yeah that is how I had the change in mind.

2023-12-11 09:49 UTC, henrikbrixandersen approved these changes

2023-12-12 15:04 UTC, str4t0m approved these changes

2023-12-12 15:05 UTC, nandojve approved these changes

2023-12-12 15:25 UTC, merged