drivers: adc: stm32 adc driver for the stm32F1 serie
zephyrproject-rtos/zephyr pull request #65752
Opened 2023-11-24 16:22 UTC by FRASTM

Configure the sw trigger just after calibration on the ADC of the stm32F1 serie

So the conversion can start on regular channel on the software control bit.

Without this trigger the conversion is never started (no ADC irq). For example running the tests/drivers/adc/adc_api/ on the nucleo_f103rb, testcase is stuck in the adc_context_wait_for_completion() as follows:
```
Running TESTSUITE adc_basic
===================================================================
START - test_adc_asynchronous_call

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/adc/adc_api/s)
k_poll failed with error -11
 FAIL - test_adc_asynchronous_call in 1.015 seconds
===================================================================
START - test_adc_invalid_request
```

That configuration was missing on  when refactoring the calibration in PR https://github.com/zephyrproject-rtos/zephyr/pull/64191

2023-11-27 07:30 UTC, gautierg-st approved these changes

2023-11-27 08:01 UTC, erwango requested changes
Please provide accurate change title ("drivers: adc: stm32 adc driver for the stm32F1 serie ") > When reading this, I though "Why? F1 adc isn't already supported?"

2023-11-29 16:04 UTC, FRASTM commented
changing commit title

2023-11-30 10:46 UTC, erwango approved these changes

2023-11-30 11:22 UTC, merged