tests: Bluetooth: add babblesim connection stress test
zephyrproject-rtos/zephyr pull request #65815
Opened 2023-11-27 13:06 UTC by jori-nordic

This is supposed to stress the host buffer and metadata handling.

It is not really testing any particular thing, ie. the pass criteria is just that each peripheral can send and receive a fixed number of GATT notifications without any device crashing or locking up.

Original version by Ahmed Moheib (from cloud2ground).

2023-11-27 13:07 UTC, jori-nordic commented
This test is intended for local development only.
The final goal is to enable it in CI, but we're not there yet, both in the host and controller.

Still, merging it will make it easier to point to problems when we file bugs and refactor the host.

2023-12-06 07:58 UTC, theob-pro commented on tests/bsim/bluetooth/host/misc/conn_stress/central/CMakeLists.txt
> +target_sources(app PRIVATE ${app_sources})
```suggestion
target_sources(app PRIVATE
  src/main.c
)
```

2023-12-06 12:36 UTC, alwa-nordic approved these changes, later dismissed

2023-12-06 15:06 UTC, kruithofa requested changes

2023-12-06 15:06 UTC, kruithofa commented on tests/bsim/bluetooth/host/misc/conn_stress/scripts/_conn_stress.sh
> +    i=$(printf '%02i' $j)
```suggestion
for i in {00..12}; do
```
or
```suggestion
for i in `seq -w 0 $nr_of_units`; do
```

2023-12-12 08:34 UTC, theob-pro approved these changes

2023-12-12 10:15 UTC, alwa-nordic approved these changes

2023-12-12 14:51 UTC, kruithofa approved these changes

2023-12-12 19:43 UTC, jhedberg approved these changes

2023-12-12 19:43 UTC, merged