cmake: Remove support for deprecated prj_board.conf
zephyrproject-rtos/zephyr pull request #66032
Opened 2023-12-01 13:09 UTC by nordicjm

Removes support for the deprecated features of having a prj file
    which has the board name on the end of it. Board Kconfig fragments
    should be used instead.

2023-12-01 13:15 UTC, henrikbrixandersen requested changes

2023-12-01 13:15 UTC, henrikbrixandersen commented on doc/releases/migration-guide-3.6.rst
> +* The deprecated ``prj_<board>.conf`` Kconfig file support has been removed, prjects that use
Typo
```suggestion
* The deprecated ``prj_<board>.conf`` Kconfig file support has been removed, projects that use
```

2023-12-01 13:17 UTC, nordicjm commented on doc/releases/migration-guide-3.6.rst
> +* The deprecated ``prj_<board>.conf`` Kconfig file support has been removed, prjects that use
Good catch, fixed

2023-12-01 13:18 UTC, henrikbrixandersen approved these changes

2023-12-01 13:20 UTC, kartben approved these changes

2023-12-01 14:43 UTC, MaureenHelm approved these changes

2023-12-05 10:21 UTC, fabiobaltieri approved these changes

2023-12-06 14:48 UTC, tejlmand approved these changes

2023-12-06 15:28 UTC, merged