boards: arm: introduce support for ST Nucleo F722ZE
zephyrproject-rtos/zephyr pull request #66050
Opened 2023-12-01 21:42 UTC by ryukoposting

Nucleo F722ZE is a development board for the STM32F722ZE, one of ST's higher-end MCU offerings. Add support for the board, aligning with conventions set by similar boards already in the Zephyr distribution.

Some notes:
- `nucleo_f722ze`'s pinout is virtually identical to the existing `nucleo_f446ze` board.
- The `STM32F722XX` SoC is almost identical to the existing `STM32F723XX` SoC. The only difference is in the USB PHY peripherals.
- I am not affiliated with ST in any capacity.

I have tested several sample programs on my Nucleo F722ZE, including:

- samples/hello_world
- samples/basic/blinky
- samples/basic/button
- samples/drivers/watchdog
- samples/sensor/die_temp_polling
- samples/sensor/soc_voltage
- samples/subsys/shell/devmem_load (with `-DCONFIG_HWINFO_SHELL` added)

I have also run the above samples using the USB CDC-ACM and Segger RTT as consoles.

I have also tested these samples, though they require overlay files that aren't included in this PR (I'll add those later):

- samples/basic/fade_led
- samples/drivers/adc
- samples/drivers/dac

2023-12-04 15:40 UTC, ryukoposting commented
Apologies for the repeated force-pushes to get this thing going. I'm hoping this will be the last one - just a couple of tweaks to indentation in devicetree files.

2023-12-08 15:14 UTC, erwango requested changes
LGTM aside one comment.
Also, please split the change in order to at least separate the tests changes from the board/soc additions. (Ideally also split board and soc additions but I won't block for this).

2023-12-08 15:22 UTC, ryukoposting commented
> LGTM aside one comment. Also, please split the change in order to at least separate the tests changes from the board/soc additions. (Ideally also split board and soc additions but I won't block for this).

Okay @erwango ! Just to make sure I understand properly, I _should_ have three PRs open:

1. The SoC definition (you're fine with me combining this with PR 2)
2. The board definition
3. Test overlay files for the board

Here's the thing... if I separate the test overlay files from the board definition, then tests won't pass on the second PR. Is that okay? Should I do something to force the tests to pass?

2023-12-13 08:42 UTC, gautierg-st approved these changes

2023-12-13 09:41 UTC, erwango approved these changes

2023-12-13 12:57 UTC, merged