bluetooth: tester: csip: Added support for testing CSIP.
zephyrproject-rtos/zephyr pull request #66151
Opened 2023-12-05 11:54 UTC by MSEEHenrik

- PRIVACY truned ON (needed by CSIP).
- RPA timeout set to 120 seconds.

2023-12-05 12:55 UTC, larsgk approved these changes

2023-12-05 17:22 UTC, Thalley approved these changes

2023-12-06 14:38 UTC, jhedberg approved these changes

2023-12-07 07:40 UTC, sjanc requested changes
this will break some GAP and SM tests,   for tests that explicitly require privacy we have overlay in autopts

2023-12-08 10:12 UTC, closed without merging

2023-12-08 10:13 UTC, MSEEHenrik commented
Changes added to dynamic configuration "csip_privacy.conf" in auto-pts.