renode: Allow extend RENODE_TEST_FLAGS
zephyrproject-rtos/zephyr pull request #66193
Opened 2023-12-05 21:47 UTC by nandojve

When running renode using twister or west is not possible to pass flags to renode-test application. This injects from a environment variable arguments defined by the user to tune renode-test applicatio.

2023-12-05 21:56 UTC, otavio approved these changes

2024-01-09 11:21 UTC, mateusz-holenko approved these changes
LGTM

2024-01-12 09:57 UTC, tejlmand requested changes
blocking, we should not be picking up environment variables post-build settings like proposed in this PR.

I noticed this was introduced with https://github.com/zephyrproject-rtos/zephyr/pull/56770, but went unnoticed to me.

CMake, and ninja / make forms the build system, and is not intended for running commands with arguments, as you seem to have noticed.

Therefore should functionality should be implemented as a `west` extension command.
A `west` extension command allows you to implement an arg parser and support any extra arguments we need.

Just like it's done with `west flash`.
Reason why `ninja / make flash` is still supported i because the originates from before `west` was made.

2024-01-12 09:57 UTC, tejlmand commented on cmake/emu/renode.cmake
> +  $$RENODE_TEST_FLAGS
no, we should not be picking up environment variables post-build like this.

2024-01-15 16:33 UTC, nandojve commented
Hi @tejlmand ,

Thank you for point out this issue to us. In my case, I don't know how to proceed here.

My problem is that there are many slow tests that took several hours to complete and it is necessary to select between the slow and fast tests at least. So, fast tests execute first and if those pass the slow ones start to run. I have in my list many renode contributions in the queue but this blocks our CI completely.

@mateusz-holenko do you have any plan how to address this ?

2024-01-15 17:08 UTC, otavio commented
While I appreciate the valuable feedback provided by @tejlmand, I tend to agree with @nandojve that the suggested changes may not be directly related to the current pull request. However, I believe that their suggestions and ideas could be considered for future pull requests, as they have the potential to enhance the overall quality of the codebase.

2024-01-16 14:53 UTC, mateusz-holenko commented
Hi @tejlmand, thanks for your suggestion.

For the record, the `renode_run_test` target was originally introduced as a "bonus" functionality for the Robot framework integration and was intended to simplify the process of creating and debugging tests.

We understand the argument that using custom env variables to control execution of the target is not optimal and harder to maintain than using an additional west command.

We'll take a look at `zephyr/scripts/west_commands` and try to rewrite the existing logic into a new command (e.g., `renode_test`) with well-defined parameters, it's an interesting idea.

From our perspective using an environment variable could be a good stop-gap solution.

2024-01-18 14:58 UTC, tejlmand commented
> My problem is that there are many slow tests that took several hours to complete and it is necessary to select between the slow and fast tests at least. 

I understand the desire to have an ability to filter between fast and slow tests, but to me this appears not only problematic in the sense that it sets a precedence of allowing build targets to be picking up settings from environment, but also to be able to filter which tests are being executed by bypassing twister's filtering capabilities.

`twister` itself already supports various ways of running specific testsuites or filtering based on tags.
For example:
```
-T TESTSUITE_ROOT
-s TEST
-t TAG
-e EXCLUDE_TAG
```

why do we need one more way of filtering ?
Even one which is quite hidden when using twister as the launcher as it is not describe using `twister --help`.

Why is it not possible to integrate with twister as well as making use of existing filtering mechanism ?
You may even tag slow test cases with a `renode_slow` tag or similar, and that way exlude those tests from running.

I guess @PerMac can provide more details on how to make full use of twister's filtering capabilities.

2024-01-20 09:46 UTC, nandojve commented
> > My problem is that there are many slow tests that took several hours to complete and it is necessary to select between the slow and fast tests at least.
> 
> I understand the desire to have an ability to filter between fast and slow tests, but to me this appears not only problematic in the sense that it sets a precedence of allowing build targets to be picking up settings from environment, but also to be able to filter which tests are being executed by bypassing twister's filtering capabilities.
> 
> `twister` itself already supports various ways of running specific testsuites or filtering based on tags. For example:
> 
> ```
> -T TESTSUITE_ROOT
> -s TEST
> -t TAG
> -e EXCLUDE_TAG
> ```
> 
> why do we need one more way of filtering ? Even one which is quite hidden when using twister as the launcher as it is not describe using `twister --help`.
> 
> Why is it not possible to integrate with twister as well as making use of existing filtering mechanism ? You may even tag slow test cases with a `renode_slow` tag or similar, and that way exlude those tests from running.
> 
> I guess @PerMac can provide more details on how to make full use of twister's filtering capabilities.

I decided wait for @mateusz-holenko proposal

2024-01-20 09:46 UTC, closed without merging

2024-01-25 16:08 UTC, PerMac commented
Slow tests should be marked accordingly in yamls (e.g. https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/benchmarks/sched/testcase.yaml#L9). Twister doesn't run such tests by default, only when --enable-slow is added to twister call. Then you could call twister twice, for regular (not slow) and for slow