modules: lvgl: support link mem pool to customer section
zephyrproject-rtos/zephyr pull request #66270
Opened 2023-12-07 11:56 UTC by ZhuZhongjie

Add a Kconfig LV_Z_MEMORY_POOL_CUSTOM_SECTION to support change the lvgl heap pool to a custom section ".lvgl_heap".

2023-12-07 12:02 UTC, pdgendt commented
@ZhuZhongjie Please do not close and open new pull requests, simply force-push to overwrite your changes.

2023-12-08 16:58 UTC, faxe1008 requested changes

2023-12-08 16:58 UTC, faxe1008 commented on modules/lvgl/Kconfig.memory
> +
Please move this out of the choice.

2023-12-09 09:29 UTC, faxe1008 commented on modules/lvgl/Kconfig.memory
>  		help
Also: check the commit message, typo `customer`

2024-02-26 00:29 UTC, closed without merging