soc: arm: atmel_sam: Sys_arch_reboot using RSTC
zephyrproject-rtos/zephyr pull request #66277
Opened 2023-12-07 14:02 UTC by javlands

The previous implementation of the sys_arch_reboot function for the Atmel SAM series was using NVIC_SystemReset. This caused a reboot time of around 20 seconds on a SAM4SA16CA, which is now reduced by directly writing to the
reset controller control register (RSTC_CR).

2023-12-07 14:32 UTC, pdgendt commented
@nandojve I'm puzzled by the circular `Kconfig` dependency, do we need to set `default y if REBOOT` instead?

2023-12-08 17:10 UTC, nandojve commented
Hi @javlands ,

I was looking in your proposal and it is doable to add the functionality. However, the PR should be complete reworked.

1- Rollback all Kconfig changes
2- create a soc_power.c file instead soc_rstc.c
3- the soc_power.c should be always added in the makefile `zephyr_library_sources_ifndef(CONFIG_SOC_SERIES_SAM4L soc_power.c)` (keep alpha order)
4- Replace the code with:

```c
#define SAM_DT_RSTC_DRIVER DT_INST(0, atmel_sam_rstc)

#include <zephyr/kernel.h>
#if defined(CONFIG_REBOOT)
#include <zephyr/sys/reboot.h>
#endif

#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(soc_power, CONFIG_SOC_LOG_LEVEL_DEFAULT);

#if defined(CONFIG_REBOOT)
#if DT_NUM_INST_STATUS_OKAY(SAM_DT_RSTC_DRIVER)

void sys_arch_reboot(int type)
{
	Rstc *regs = (Rstc *)DT_REG_ADDR_BY_IDX(SAM_DT_RSTC_DRIVER, 0);

	switch (type) {
	case SYS_REBOOT_COLD:
		regs->RSTC_CR = RSTC_CR_KEY_PASSWD
			      | RSTC_CR_PROCRST
#if defined(CONFIG_SOC_SERIES_SAM3X) || defined(CONFIG_SOC_SERIES_SAM4S) || defined(CONFIG_SOC_SERIES_SAM4E)
			      | RSTC_CR_PERRST
#endif /* CONFIG_SOC_SERIES_SAM3X || CONFIG_SOC_SERIES_SAM4S || CONFIG_SOC_SERIES_SAM4E */
			      ;
		break;
	default:
		LOG_DBG("Reset type not implemented");
		break;
	}
}

#endif /* DT_NUM_INST_STATUS_OKAY */
#endif /* CONFIG_REBOOT */
```
5- Make sure you follow [contribution-guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-guidelines)
6- Add `Co-authored-by: Gerson Fernando Budke <nandojve@gmail.com>` on the next line after your `Signed-off-by` clause.

CC: @pdgendt

2023-12-11 08:25 UTC, pdgendt commented on soc/arm/atmel_sam/common/soc_power.c
> +	Rstc *regs = (Rstc *)DT_REG_ADDR_BY_IDX(SAM_DT_RSTC_DRIVER, 0);
```suggestion
	Rstc *regs = (Rstc *)DT_REG_ADDR(SAM_DT_RSTC_DRIVER);
```

2023-12-11 08:28 UTC, pdgendt approved these changes

2023-12-11 09:16 UTC, pdgendt requested changes

2023-12-11 09:27 UTC, pdgendt submitted a review, later dismissed

2023-12-11 11:14 UTC, pdgendt submitted a review, later dismissed

2023-12-11 11:28 UTC, attie-argentum submitted a review, later dismissed

2023-12-11 12:54 UTC, pdgendt commented
Removed my approval, I'd like @nandojve to have a chance to review the latest changes.

2023-12-18 10:00 UTC, pdgendt commented
Friendly ping @nandojve

2023-12-18 16:50 UTC, nandojve requested changes

2023-12-18 16:50 UTC, nandojve commented on soc/arm/atmel_sam/common/soc_power.c
> +			;
As mentioned in the examples the "|" should be vertically align with "=". You should use tab (8 spaces) most you can and then complete with spaces.

```c
		regs->RSTC_CR = RSTC_CR_KEY_PASSWD
			      | RSTC_CR_PROCRST
#if defined(CONFIG_SOC_SERIES_SAM3X) || defined(CONFIG_SOC_SERIES_SAM4S) || defined(CONFIG_SOC_SERIES_SAM4E)
			      | RSTC_CR_PERRST
#endif /* CONFIG_SOC_SERIES_SAM3X || CONFIG_SOC_SERIES_SAM4S || CONFIG_SOC_SERIES_SAM4E */
			      ;
```

2023-12-27 11:21 UTC, nandojve approved these changes

2023-12-27 11:21 UTC, pdgendt approved these changes

2023-12-28 12:05 UTC, merged