boards: arm: change display driver to ltdc on stm32f429i_disc1
zephyrproject-rtos/zephyr pull request #66271
Opened 2023-12-07 11:59 UTC by ZhuZhongjie

Change display driver to ltdc on stm32f429i_disc1 board.

2023-12-11 16:03 UTC, erwango commented
@ajarmouni-st Can you test it is OK ?

2023-12-12 09:02 UTC, ajarmouni-st commented
> Change display driver to ltdc on stm32f429i_disc1 board.

Can you elaborate why this change is needed?

2023-12-13 04:58 UTC, ZhuZhongjie commented
> > Change display driver to ltdc on stm32f429i_disc1 board.
> 
> @ZhuZhongjie Can you elaborate why this change is needed?
The LCD on the  stm32F429IDISCOVERY Discovery kit is using the RGB protocol, so this should change to the lcdc driver, the spi interface connected to the ILI9341 LCD controller is used to initial the LCD.

2023-12-13 05:00 UTC, ZhuZhongjie commented
> @ajarmouni-st Can you test it is OK ?

Yes, it is OK in my stm32f429i Discovery kit board

2023-12-13 08:28 UTC, ajarmouni-st commented
> Yes, it is OK in my stm32f429i Discovery kit board
I tested with sample/drivers/display & I get nothing with your modif, but with &ili9341 I have some output on the display, although I don't think it's exactly what the sample is meant to output.

2023-12-13 08:39 UTC, ajarmouni-st commented
> > The LCD on the  stm32F429IDISCOVERY Discovery kit is using the RGB protocol, so this should change to the ltdc driver, the spi interface connected to the ILI9341 LCD controller is used to initialize the LCD.

@ZhuZhongjie In page 7 of https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf , you can see that the ILI9341 controller supports 3 interfaces inc. serial interface.

My understanding is that in order to use the RGB protocol with ILI9341, the ILI9341 driver needs to be modified to support it.

2023-12-13 09:52 UTC, erwango requested changes

2023-12-13 09:52 UTC, erwango commented on boards/arm/stm32f429i_disc1/stm32f429i_disc1.dts
> +		zephyr,display = &ltdc;
This modification is not sufficient.
Node should also be enabled, maybe pins configured, ...

2023-12-19 03:02 UTC, ZhuZhongjie commented
> > > The LCD on the  stm32F429IDISCOVERY Discovery kit is using the RGB protocol, so this should change to the ltdc driver, the spi interface connected to the ILI9341 LCD controller is used to initialize the LCD.
> 
> @ZhuZhongjie In page 7 of https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf , you can see that the ILI9341 controller supports 3 interfaces inc. serial interface.
> 
> My understanding is that in order to use the RGB protocol with ILI9341, the ILI9341 driver needs to be modified to support it.

https://www.st.com/content/ccc/resource/technical/document/user_manual/6b/25/05/23/a9/45/4d/6a/DM00093903.pdf/files/DM00093903.pdf/jcr:content/translations/en.DM00093903.pdf
![image](https://github.com/zephyrproject-rtos/zephyr/assets/52530903/69301640-b612-4d7f-b15e-287205001103)
the section 6.9 the lcd is using RGB protocol.

2023-12-22 14:14 UTC, ajarmouni-st commented
> Yes, it is OK in my stm32f429i Discovery kit board

Did you test using samples/drivers/display or something else?

2024-01-24 12:12 UTC, ajarmouni-st approved these changes

2024-01-24 13:53 UTC, ajarmouni-st commented
> > Yes, it is OK in my stm32f429i Discovery kit board
> 
> @ZhuZhongjie Did you test using samples/drivers/display or something else?

@ZhuZhongjie I was able to validate that this change is needed using the samples /driver/display /modules/lvgl/demos & /subsys/display/lvgl, but only after patching display_ili9341.c (will open a PR). Without my patch, we get a white screen.

2024-01-29 14:35 UTC, erwango approved these changes

2024-01-29 14:57 UTC, merged