net: lib: coap: Change coap_pending_init()
zephyrproject-rtos/zephyr pull request #66482
Opened 2023-12-13 11:24 UTC by juhaylinen

Replace function parameter 'retries' with pointer to structure holding coap transmission parameters. This allows setting the retransmission parameters individually for each pending request.

Add coap transmission parameters to coap_pending structure.

Update migration guide and release notes.

2023-12-13 11:33 UTC, pdgendt commented on doc/releases/release-notes-3.6.rst
> +  * Added new API functions:
Nit: add a newline between list items.

2023-12-13 11:33 UTC, pdgendt commented on tests/net/lib/coap/src/main.c
Can you add actual testing of the parameters?

2023-12-13 11:33 UTC, rlubos commented on include/zephyr/net/coap.h
> + * or NULL to use default values set by Kconfig
nit: I'd drop the `set by Kconfig` part, as it's not necessarily correct - the initial Kconfig values could be overwritten by `coap_set_transmission_parameters()`.

2023-12-13 13:00 UTC, juhaylinen commented on tests/net/lib/coap/src/main.c
Added new test case for the parameters.

2023-12-13 13:10 UTC, pdgendt commented on tests/net/lib/coap/src/main.c
> +ZTEST(coap, test_transmission_parameters)
Fix the compliance issues and add a separate commit for this test.

2023-12-13 14:30 UTC, juhaylinen commented on subsys/net/lib/coap/coap_server.c
> +		ret = coap_pending_init(pending, cpkt, addr, &params);
@pdgendt feel free to make the changes.

2023-12-13 14:58 UTC, pdgendt submitted a review, later dismissed

2023-12-13 15:16 UTC, rlubos submitted a review, later dismissed

2023-12-14 08:25 UTC, SeppoTakalo requested changes

2023-12-14 14:35 UTC, rlubos approved these changes

2023-12-14 14:36 UTC, pdgendt approved these changes

2023-12-14 14:37 UTC, SeppoTakalo approved these changes

2023-12-15 11:41 UTC, merged