scripts: tests: twister_blackbox: Add more tests to test_report.py
zephyrproject-rtos/zephyr pull request #66563
Opened 2023-12-15 13:33 UTC by KamilxPaszkiet

add tests to test_report.py:
 - log-file
 - coverage

2023-12-21 11:45 UTC, PerMac submitted a review, later dismissed

2024-01-09 15:04 UTC, LukaszMrugala commented
Seems to fail the `test_coverage` test after rebasing locally onto current `main`. I suspect 3bbd34d1b636a269d4123fd346779b9ee140a83b or a similar commit.

2024-01-11 12:42 UTC, LukaszMrugala requested changes
Conflicts caused by the https://github.com/zephyrproject-rtos/zephyr/pull/66752 merge must be resolved before merging this PR.

2024-01-15 13:35 UTC, mdubielx approved these changes

2024-01-15 14:39 UTC, LukaszMrugala approved these changes, later dismissed

2024-01-15 14:55 UTC, arikgreen approved these changes, later dismissed

2024-01-24 03:53 UTC, nashif approved these changes

2024-01-26 15:15 UTC, LukaszMrugala approved these changes

2024-01-26 15:53 UTC, merged