Misc. Kconfig fixes and enhancements
zephyrproject-rtos/zephyr pull request #666
Opened 2017-07-02 12:18 UTC by nashif

This all is part of an attemp to cleanup tests and samples and increase
coverage of tests.

2017-07-04 15:16 UTC, galak commented on tests/crypto/mbedtls/prj.conf
> -CONFIG_ARC_INIT=n
What does the ARC_INIT have to do with DEBUG?

2017-07-04 15:19 UTC, galak requested changes
The spi move seems to have one too many spi/spi/ dirs.  We should probably either rename the test or reduce a level of dir.

2017-07-04 15:19 UTC, galak commented on tests/crypto/mbedtls/testcase.yaml
> +        filter: not CONFIG_DEBUG
should we have a bug opened for the fact that mbedtls has issues with DEBUG (not sure what those issues are)?

2017-07-04 16:57 UTC, nashif commented on tests/crypto/mbedtls/testcase.yaml
> +        filter: not CONFIG_DEBUG
the issues is related to our warnings turning into errors, it is not necessarily an issue in mbedTLS, so opening a bug here will just make it stay open forever, not sure it is worth the trouble.

2017-07-04 16:58 UTC, nashif commented
updated

2017-07-05 16:15 UTC, galak commented
The kw41z board should have ieee802154 marked in its HW support

2017-07-05 16:23 UTC, galak requested changes
some changes, needed.  Created PR #693 to pull the commits that are ready to merge into, so only those commits that need fixing up will need to get reviewed.

2017-07-05 16:23 UTC, galak commented on boards/arm/frdm_k64f/frdm_k64f.yaml
> +  - net
we should make this be ethernet not net

2017-07-05 16:23 UTC, galak commented on include/misc/stack.h
> +#if defined(STACK_GROWS_UP)
where is STACK_GROWS_UP defined anywhere?

2017-07-05 16:23 UTC, galak commented on tests/crypto/mbedtls/src/mbedtls_test.c
> +	;
this seems odd, why do we even have the ;

2017-07-05 16:34 UTC, nashif commented on include/misc/stack.h
> +#if defined(STACK_GROWS_UP)
read the comment on top of this line

2017-07-05 17:27 UTC, galak commented on include/misc/stack.h
> +#if defined(STACK_GROWS_UP)
Ah

2017-07-05 21:04 UTC, galak commented on boards/arm/frdm_kw41z/frdm_kw41z.yaml
> +  - ieee802154
should we put ble here, even if the sw doesn't support it?

2017-07-05 21:05 UTC, galak commented on boards/x86/qemu_x86/qemu_x86.yaml
> +  - net
what is net suppose to mean here?

2017-07-05 21:06 UTC, galak requested changes
what is 'net' suppose to be mean for qemu?

2017-07-05 21:06 UTC, galak commented on boards/x86/qemu_x86/qemu_x86_iamcu.yaml
> +  - net
what is net suppose to mean here?

2017-07-05 21:07 UTC, galak commented
Also, don't we have networking support on qemu_cortex_m3?

2017-07-05 23:11 UTC, nashif commented on boards/x86/qemu_x86/qemu_x86.yaml
> +  - net
networking in general, this is not not tied to a HW device.

2017-07-05 23:13 UTC, nashif commented
> Also, don't we have networking support on qemu_cortex_m3?

via SLIP yes, but does it make sense to test on all QEMUs? We need to pick one and do the test via SLIP on one. This is pretty much the same and we are not testing HW features here, we are testing the IP stack. Dont care which we use, qemu_x86 was used sofar.

2017-07-06 14:17 UTC, galak commented
Lets see if @pfalcon has a feeling on testing net with qemu.  I know he's dealt with this and want to make sure the qemu works reasonable for it on any/all platforms that we support.

2017-07-06 14:57 UTC, pfalcon commented
Well, ideally, we'd test both qemu_x86 and qemu_cortex_m3, to make sure there're no regressions in qemu_cortex_m3, because nobody likely uses it for testing ;-).

Otherwise, to run Zephyr sample with SLIP enabled in QEMU, there should be running daemons for SLIP/TAP conversion - at the very least. So, we can't run such tests using normal sanitycheck processing (and indeed, there're nos such *tests*), and fairly speaking, I don't know how to handle that at all (there can be various ideas of course). But that matter needs to be addressed somehow, as the net code is already complex, and complex refactors keep being applied to it (I just complained on that at https://github.com/zephyrproject-rtos/zephyr/pull/691#issuecomment-313415170), and there're no good way to regression-test them.

2017-07-06 15:34 UTC, galak approved these changes

2017-07-06 15:34 UTC, merged