board: add usb_otg_hs instance to stm32f429i_disc1
zephyrproject-rtos/zephyr pull request #66605
Opened 2023-12-17 23:50 UTC by jrsa

2023-12-18 14:16 UTC, erwango requested changes
LGTM but please update board's documentation

2023-12-20 07:21 UTC, erwango submitted a review, later dismissed

2023-12-21 08:44 UTC, erwango approved these changes

2023-12-21 16:41 UTC, MaureenHelm approved these changes

2023-12-22 14:40 UTC, merged