slist find without remove #65973
zephyrproject-rtos/zephyr pull request #66621
Opened 2023-12-18 13:17 UTC by moonlight83340

I added a function to check if a node is linked.
I found the idea of  @peter-mitsis great, so I try to implement it.
 "bool sys_snode_is_linked(sys_slist_t * list, sys_snode_t *node, sys_snode_t **prev);"
 

>  Thinking aloud ...
> 
> Searching for a specific node in a slist requires a linear search which is an O(N) operation. This is something that we would not want as default behaviour in sys_slist_append(). Probably not for debugging behaviour either as that linear search would come with an expected high performance penalty. I would expect the better practice would be to foist the responsibility of a search onto the caller so that the penalty is not incurred by all users of sys_slist_append()--even in a debugging scenario.
> 
> If it is done, then my preference would be for naming it something like ...
>     bool sys_snode_is_linked(sys_slist_t * list, sys_snode_t *node, sys_snode_t **prev);
> If the node does need to be removed later, it may then be done more quickly and easily without necessarily incurring the penalty of another linear search.

I think also that a linear search shouldn't be apply every time we use sys_slist_append(), and that should be used only in case to case.

My solution isn't perfect, and would like to discuss about it !

2023-12-18 13:42 UTC, moonlight83340 commented on include/zephyr/sys/list_gen.h
> +#define Z_GENLIST_NODE_IS_LINKED(__lname, __nname,__nname) \
Auto review :
#define Z_GENLIST_NODE_IS_LINKED(__lname, __nname)

2023-12-18 13:43 UTC, moonlight83340 commented on include/zephyr/sys/list_gen.h
> + * @param __nname The next node name
/**
 * @brief Macro to check if a node is linked in a generic list
 * 
 * @param __lname The list name
 * @param __nname The node name
 * @param __nname The previous node name

2023-12-21 01:57 UTC, peter-mitsis commented
@moonlight83340 - I'm seeing a lot of white space changes in addition to the desired changes. If the white space changes are necessary, can you please split them into a separate commit? This facilitates reviews by making it easier to both identify and assess the changes.

2023-12-21 02:00 UTC, moonlight83340 commented
> @moonlight83340 - I'm seeing a lot of white space changes in addition to the desired changes. If the white space changes are necessary, can you please split them into a separate commit? This facilitates reviews by making it easier to both identify and assess the changes.

This append after using clang-format on file. I can split the commit to avoid that blank line, I will try to do that after work.

2023-12-21 05:54 UTC, moonlight83340 commented
@peter-mitsis I revert my commit and commit again only the changed part.

2023-12-29 19:36 UTC, andyross reviewed
Just saw some chatter.  I don't see any reason not to include a function like this, searching lists is a very reasonable thing to do.

I will say that I'd prefer it be called something like "find" or "search" than "is_linked".  With a dlist, we actually do have the distinction between a linked node and one that isn't (which has null pointers), for historical reasons that have to do with the need to know thread state in the scheduler more than data structure hygiene.  There, "is_linked" is implemented the way it sounds, as a simple boolean predicate that tests the pointers vs. NULL.

But the slist doesn't have that, and doesn't really want it.   I'd prefer naming it for what it's doing, to make the O(N) behavior clearer.  Would also be good to clarify that in the docs too.

2024-01-07 01:47 UTC, moonlight83340 commented
> Just saw some chatter. I don't see any reason not to include a function like this, searching lists is a very reasonable thing to do.
> 
> I will say that I'd prefer it be called something like "find" or "search" than "is_linked". With a dlist, we actually do have the distinction between a linked node and one that isn't (which has null pointers), for historical reasons that have to do with the need to know thread state in the scheduler more than data structure hygiene. There, "is_linked" is implemented the way it sounds, as a simple boolean predicate that tests the pointers vs. NULL.
> 
> But the slist doesn't have that, and doesn't really want it. I'd prefer naming it for what it's doing, to make the O(N) behavior clearer. Would also be good to clarify that in the docs too.

Hope I understand your message well, I rename the function. ( Commit message should be change, I will squash them later.)

2024-01-07 05:13 UTC, andyross submitted a review, later dismissed
This looks good to me.  Those "need consistent spacing" errors look like false positives to me.  That style is correct for Zephyr; I guess the script doesn't understand the token pasting going on?

2024-01-07 13:59 UTC, cfriedt commented on include/zephyr/sys/slist.h
> + * @param prev A pointer to the previous node (output parameter)
Just a minor nit, otherwise, LGTM
```suggestion
 * @param[out] prev A pointer to the previous node
```

2024-01-07 14:45 UTC, cfriedt requested changes
Additional quick scan of `tests/` shows that we don't have any test coverage for `sys_slist_find()` either.

Can you please create a second commit with tests for this API, @moonlight83340?

2024-01-07 14:50 UTC, moonlight83340 commented
> Additional quick scan of `tests/` shows that we don't have any test coverage for `sys_slist_find()` either.
> 
> Can you please create a second commit with tests for this API, @moonlight83340?


Thanks, will do that in this week.

2024-01-08 03:44 UTC, moonlight83340 commented
Not sure on the form and where I should test, I try something tests/unit/list/slist.c

2024-01-09 04:31 UTC, cfriedt commented on tests/unit/list/slist.c
> +	sys_snode_t *test_node_1_prev = NULL;
It might be a good idea to set this to a value other than null so that we can verify that the function modified it

2024-01-09 04:31 UTC, cfriedt commented on tests/unit/list/slist.c
> +	zassert_true((test_node_1_prev == NULL),
It might be better to use `zassert_is_null()` here

2024-01-09 04:31 UTC, cfriedt commented on tests/unit/list/slist.c
> +	zassert_true((&test_node_2.node == test_node_4_prev),
`zassert_equal(a, b)` might be better here.

2024-01-09 04:31 UTC, cfriedt commented on tests/unit/list/slist.c
> +		     "test_list didn't founded node ");
Minor suggestion
```suggestion
		     "test_list did not find node");
```

2024-01-09 23:53 UTC, cfriedt approved these changes
LGTM now, thanks @moonlight83340 . @andyross - probably ok to refresh your +1. Compliance looks consistent with before

2024-01-10 00:18 UTC, andyross approved these changes
Still good

2024-02-06 09:04 UTC, moonlight83340 commented
Is the compliance checks a merge blocking thing ?

2024-02-06 12:45 UTC, cfriedt commented
> Is the compliance checks a merge blocking thing ?

It seems to be a false positive.

2024-02-06 12:45 UTC, cfriedt approved these changes

2024-03-12 17:46 UTC, merged