soc: stm32wba: hci_if: Implement HW_RNG_EnableClock API
zephyrproject-rtos/zephyr pull request #66655
Opened 2023-12-19 13:46 UTC by erwango

STM32WBA controller uses a PKA driver to perform cyphering operations on keys. Since PKA hardware block requires RNG clock to be enabled, a synchronization with zephyr RNG driver is needed.

Use RNG enable status to check if RNG could be switched off or needs to be switched on.
Similarly in entropy driver, don't cut RNG clock if PKA is enabled.

Signed-off-by: Erwan Gouriou <erwan.gouriou@st.com>

2023-12-19 14:06 UTC, gautierg-st requested changes
Just remove "# Conflicts:" from your commit message. Otherwise LGTM.

2023-12-19 16:18 UTC, erwango commented
> Just remove "# Conflicts:" from your commit message. Otherwise LGTM.

Thanks. Done !

2023-12-20 07:35 UTC, gautierg-st approved these changes

2023-12-20 08:19 UTC, FRASTM approved these changes

2023-12-20 11:13 UTC, fabiobaltieri approved these changes

2023-12-21 08:18 UTC, merged