linkserver: nxp: add support for frdm-k64f
zephyrproject-rtos/zephyr pull request #66672
Opened 2023-12-19 19:53 UTC by yvanderv

- board.cmake is augmented for LinkServer
 - the board's doc file is updated as well

2023-12-20 14:38 UTC, danieldegrasse reviewed
Hi, thanks for getting this enabled! A few comments here:
- we should not remove the `pyocd` installation instructions in this PR- that host tool is still the default for this board, and we should make sure users are aware of how to set it up when they look at the board documentation page
- the commit title should be something like the following `boards: frdm_k64f: enable linkserver support`

2023-12-20 17:23 UTC, mmahadevan108 commented on boards/arm/frdm_k64f/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/linkserver.board.cmake)
Recommend this be moved to be first so LinkServer is the default.

2023-12-20 21:04 UTC, mmahadevan108 commented
Please update the commit message to indicate that linkserver is the new default.

2023-12-21 19:21 UTC, mmahadevan108 submitted a review, later dismissed

2023-12-21 20:28 UTC, danieldegrasse commented on boards/arm/frdm_k64f/doc/index.rst
> +        Linkserver is the default for this board, ``west flash`` and ``west debug`` will
When I test this PR locally, Linkserver does not appear to be the defaut:

```
(.venv) ~/zephyr/zephyrproject/zephyr:(177314f17a...) ❯ west flash
-- west flash: rebuilding
[1/1] cd /home/danieldegrasse/zephyr/zephyrproject...ephyr/zephyrproject/zephyr/build/zephyr/zephyr.elf
-- west flash: using runner pyocd
WARNING: runners.pyocd: hex file (None) does not exist; falling back on .bin (/home/danieldegrasse/zephyr/zephyrproject/zephyr/build/zephyr/zephyr.bin). Consider enabling CONFIG_BUILD_OUTPUT_HEX.
-- runners.pyocd: Flashing file: /home/danieldegrasse/zephyr/zephyrproject/zephyr/build/zephyr/zephyr.bin
0001551 I Loading /home/danieldegrasse/zephyr/zephyrproject/zephyr/build/zephyr/zephyr.bin [load_cmd]
[==================================================] 100%
0002650 I Erased 0 bytes (0 sectors), programmed 0 bytes (0 pages), skipped 20480 bytes (5 pages) at 18.21 kB/s [loader]
(.venv) ~/zephyr/zephyrproject/zephyr:(177314f17a...) 
```
versus: 
```
west flash -r linkserver
-- west flash: rebuilding
[1/1] cd /home/danieldegrasse/zephyr/zephyrproject...ephyr/zephyrproject/zephyr/build/zephyr/zephyr.elf
-- west flash: using runner linkserver
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v1.3.15
INFO: Exact match for MK64FN1M0xxx12:FRDM-K64F found
INFO: Selected device MK64FN1M0xxx12:FRDM-K64F
INFO: Getting available probes
INFO: Selecting probe by index
INFO: Selected probe #1 02400b0128884e45004400106bf000478021000097969900 (DAPLink CMSIS-DAP
```

2023-12-21 20:30 UTC, danieldegrasse reviewed
We need to update the `linkserver.board.cmake` file to include `board_set_flasher_ifnset` directives, like other runner cmake files do: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/common/jlink.board.cmake#L3. Otherwise, linkserver will not actually become the default

2023-12-27 13:12 UTC, DerekSnell requested changes
Thanks @yvanderv for this update.
But the doc page needs some updates, thanks

2023-12-27 13:12 UTC, DerekSnell commented on boards/arm/frdm_k64f/doc/index.rst
> +        Linkserver is the default for this board, ``west flash`` and ``west debug`` will
When LinkServer is the default runner, this doc needs some additional changes.  On the tab "OpenSDA JLink Onboard", change this sentence:
> Add the arguments ... when you invoke west build to override the default runner from pyOCD to J-Link.

to
> Add the arguments ... when you invoke west build to override the default runner to J-Link.

2024-01-03 17:33 UTC, yvanderv commented
> We need to update the `linkserver.board.cmake` file to include `board_set_flasher_ifnset` directives, like other runner cmake files do: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/common/jlink.board.cmake#L3. Otherwise, linkserver will not actually become the default

Sure, will submit a separate PR.

2024-01-03 18:42 UTC, danieldegrasse commented
> Sure, will submit a separate PR.

Ok, and I assume that this PR would then be dependent on that one, since we want to move linkserver to be the default on this board?

2024-01-05 17:21 UTC, DerekSnell approved these changes
Thanks, @yvanderv !
LinkServer is now the default runner.

2024-01-05 18:02 UTC, danieldegrasse approved these changes

2024-01-08 09:08 UTC, merged