DAC: sam no size check zephyrproject-rtos#65021
zephyrproject-rtos/zephyr pull request #66990
Opened 2023-12-25 06:49 UTC by moonlight83340

Add size check to dac sam but
not sure on the size checked...

2023-12-27 09:57 UTC, nandojve requested changes
Hi @moonlight83340 ,

I don't see issues to warn users about data value be higher than max of 12 bits. Take in consideration that both drivers are limited implementations.

BTW, you need change the commit message. Follow Zephyr rules related to [coding-style](https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style).

2023-12-27 09:57 UTC, nandojve commented on drivers/dac/dac_sam.c
> +	if (value >= 4096) {
```diff
-	if (value >= 4096) {
+	if (value >= BIT(12)) {
```

2023-12-27 09:57 UTC, nandojve commented on drivers/dac/dac_sam0.c
> +	if (value >= 4096) {
```diff
-	if (value >= 4096) {
+	if (value >= BIT(12)) {
```

2023-12-27 15:53 UTC, nandojve commented
Hi @moonlight83340 ,

Thank you for the changes. The brief message in the commit must be changed. I suggest:

```diff
-DAC: sam no size check #65021
+drivers: dac: sam: Add max value check
```

2023-12-27 23:26 UTC, moonlight83340 commented
> Hi @moonlight83340 ,
> 
> Thank you for the changes. The brief message in the commit must be changed. I suggest:
> 
> ```diff
> -DAC: sam no size check #65021
> +drivers: dac: sam: Add max value check
> ```

Done, thank you for your review 👍

2023-12-27 23:29 UTC, martinjaeger approved these changes

2023-12-28 08:57 UTC, nandojve approved these changes

2023-12-28 12:08 UTC, merged