tests: drivers: bbram: add test BBRAM on twister
zephyrproject-rtos/zephyr pull request #67206
Opened 2024-01-04 14:54 UTC by Desvauxm-st

add tests BBRAM on twister (on hw in CI)
add test for following boards:
nucleo_f429zi, nucleo_f207zg,nucleo_f303re,
nucleo_f746zg, nucleo_h743zi,nucleo_l152re,
disco_l475_iot1, nucleo_wb55rg

2024-01-04 15:46 UTC, FRASTM commented on boards/arm/nucleo_h743zi/nucleo_h743zi.dts
> +	backup_regs {
add a line break

2024-01-04 15:48 UTC, FRASTM requested changes

2024-01-04 15:48 UTC, FRASTM commented on tests/drivers/bbram/testcase.yaml
> +    platform_allow:
`build_only: true` removed here is it correct ?

2024-01-04 15:48 UTC, FRASTM commented on tests/drivers/bbram/testcase.yaml
> +    platform_allow:
`build_only: true` removed here is it correct ?

2024-01-04 15:48 UTC, FRASTM commented on tests/drivers/bbram/testcase.yaml
> +      - nucleo_f746zg
is this one really needed ? --> already supporting stm32f746g_disco

2024-01-04 15:48 UTC, FRASTM commented on tests/drivers/bbram/testcase.yaml
> +      - nucleo_f746zg
is this one really needed ? --> already supporting stm32f746g_disco

2024-01-05 14:41 UTC, FRASTM commented
This testcase is build only: Could we have a more pertinent testing like the sample : samples/boards/stm32/backup_sram/

2024-01-08 09:41 UTC, Desvauxm-st commented
I will do another test into samples/boards/stm32/...

2024-01-08 09:41 UTC, closed without merging