Update the ppp documentation
zephyrproject-rtos/zephyr pull request #67252
Opened 2024-01-05 14:33 UTC by jukkar

2024-01-05 15:03 UTC, kartben requested changes
Thanks!

"The actual gsm-modem sample was removed earlier [...]" - was it / should it be? AFAIKT it is still there?

2024-01-05 15:03 UTC, kartben commented on doc/connectivity/networking/api/gsm_modem.rst
please introduce an appropriate redirect for this page for folks browsing old versions of the documentation (in `doc/_scripts/redirects.py`)

2024-01-05 16:33 UTC, jukkar commented
> "The actual gsm-modem sample was removed earlier [...]" - was it / should it be? AFAIKT it is still there?

Ah, yes. It was deprecated but not yet removed.

2024-01-05 16:56 UTC, kartben commented
> > "The actual gsm-modem sample was removed earlier [...]" - was it / should it be? AFAIKT it is still there?
> 
> Ah, yes. It was deprecated but not yet removed.

so maybe it's also premature to delete `doc/connectivity/networking/api/gsm_modem.rst`? I will leave it up to decide what you (and maybe @bjarki-trackunit) think is best

2024-01-09 08:41 UTC, kartben approved these changes
👍🏼

2024-01-10 10:23 UTC, rlubos approved these changes

2024-01-10 11:06 UTC, merged