Maintainers: Updates charging API maintainers
zephyrproject-rtos/zephyr pull request #67404
Opened 2024-01-09 20:21 UTC by rriveramcrus

Swaps aaronemassey for GRobertZieba as the new charger maintainer.

2024-01-09 20:22 UTC, aaronemassey approved these changes

2024-01-09 20:47 UTC, GRobertZieba approved these changes

2024-01-18 21:44 UTC, nashif requested changes
There is a process for getting into the maintainer file as a maintaine, https://docs.zephyrproject.org/latest/project/project_roles.html I see that @GRobertZieba is not in the zephyr project as collaborator, so this will not work.
Given that we have one maintainer already, I would remove @aaronemassey  and get @GRobertZieba into the collborator section following the process.

Thanks.

2024-01-25 18:15 UTC, GRobertZieba commented
@rriveramcrus Do you want to revert this change and we can work on following the proper procedure? The PEC PR that I have open is probably gonna take a while to resolve, but I do have at least two smaller Zephyr changes in my backlog that I can work on so I can get collaborator status.

2024-01-25 19:06 UTC, rriveramcrus commented
> @rriveramcrus Do you want to revert this change and we can work on following the proper procedure? The PEC PR that I have open is probably gonna take a while to resolve, but I do have at least two smaller Zephyr changes in my backlog that I can work on so I can get collaborator status.

Sounds good, I'll close it out.

2024-01-25 19:06 UTC, closed without merging