doc: subsystem: runtime configuration system
zephyrproject-rtos/zephyr pull request #6750
Opened 2018-03-22 15:18 UTC by nvlsianpu

This patch introduce doc for runtime configuration
system with FCB and File System beck-ends.

This is addendum to the #6408 PR

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2018-03-22 15:29 UTC, carlescufi commented
@nvlsianpu shouldn't we first decide on the prefix we are going to use in the code itself? or is `conf_` already decided for that?

2018-03-22 18:59 UTC, dbkinder requested changes

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +.. _conf_s11n
add a colon

    .. _conf_s11n:

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +Config subsystem is meant for persisting per-device configuration
The config subsystem gives modules a way to store persistent
    per-device configuration and runtime state.

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +Configuration items are stored as key-value pairs, where both the key and
How about:

    Configuration items are stored as key-value pair strings.  By convention,
    the keys can be organized by the package and subtree defining the key,
    for example the key ``id/serial`` would define the ``serial`` configuration
    element for the package ``id``.

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +There are convenience routines for converting value back and forth
How about:

    Convenience routines are provided for converting a key value to
    and from a string type.

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +.. doxygengroup:: sys_config
#6408 needs to be merged before this reference will not generate an error.

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +    This gets called when somebody asks for a config element value
This gets called when asking for a config element value by its name
    using ``conf_get_value()``.

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +    This is called when value is being set using ``conf_set_value()``, and
This gets called when the value ...

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +    This gets called after configuration has been loaded in full.
after the configuration

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +    also when configuration is loaded from persisted storage with
when the configuration

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +    This gets called to dump all current configuration. This happens
Would ``write`` be better than ``dump``?

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +Backend storage for the config can be either FCB, a file in filesystem,
in the filesystem

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +data is stored when you call ``conf_save()``, or conf_save_one().
or ``conf_save_one()``

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +using ``conf_fcb_dst()``. ``conf_fcb_src()`` as side-effect initializes the
As a side-effect, ``conf_fcb_src()`` initializes the ...

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +File read target is registered using ``conf_file_src()``, and write target
and write target by using

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +storage thanks to ''storage_func'' (it is possible to implement another export
``storage_func()``.  The user can also implement some other export
    functionality, for example, writing to the shell console).

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +.. code:: c
.. code-block:: c

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +there is only ``ch_set`` defined, which is used when restoring value from
In this example, only ``ch_set`` is defined, ....

    restoring the value

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +This is a simple example, config handler only implements ``ch_set`` and
where the config handler

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +``ch_export``. ``ch_set`` is called when value is restored from storage (or
when the value

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +There's foo_callout function which increments foo_val, and then
In this example, the ``foo_callout`` function increments ``foo_val`` ...

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +persists the latest number. When system restarts, the application calls
When the system

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +``conf_load()`` while initializing, foo_val will continue counting up from where
and ``foo_val``

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +.. code:: c
.. code-block:: c

2018-03-22 18:59 UTC, dbkinder commented on doc/subsystems/conf_s11n/conf_s11n.rst
> +The API of runtime configuration APIs are provided by conf_s11n.h:
The runtime configuration APIs are provided by ``conf_s11n.h``:

2018-03-29 13:06 UTC, nvlsianpu commented
Hi all - I have updated the doc. Finally the name of this module stand as "Settings".

2018-03-29 14:13 UTC, dbkinder requested changes
thanks for updating the docs.  almost there.

2018-03-29 14:13 UTC, dbkinder commented on doc/subsystems/settings/settings.rst
> +    This gets called after the settings has been loaded in full.
``settings have been``

2018-03-29 14:13 UTC, dbkinder commented on doc/subsystems/settings/settings.rst
> +    Sometimes you don't want individual setting value to take
``want an individual``

2018-03-29 14:13 UTC, dbkinder commented on doc/subsystems/settings/settings.rst
> +initializes the FCB area, so it must be called when calling
``called before calling``

2018-04-05 11:26 UTC, nvlsianpu commented
@dbkinder updated

2018-04-05 15:01 UTC, dbkinder approved these changes
Thanks!

2018-04-06 05:51 UTC, nvlsianpu commented
@carlescufi can we merge this?

2018-04-06 10:46 UTC, merged