modbus: Remove mode reset in modbus_disable function
zephyrproject-rtos/zephyr pull request #67541
Opened 2024-01-12 10:21 UTC by 73jn

This commit removes the line resetting the MODBUS mode in the modbus_disable function. This change ensures that the MODBUS interface, when disabled in raw interface mode, does not alter its mode setting, maintaining expected functionality.

2024-01-12 10:46 UTC, jfischer-no requested changes
Please clarify your expectations for functionality when the interface is disabled. For me, a disabled interface is not functional.

2024-01-12 11:54 UTC, 73jn commented
> his commit removes the line resetting the MODBUS mode in the modbus_disable function. This change ensures that the MODBUS interface, when disabled in raw interface mode, does not alter its mode setting, maintaining expected functionality.

Hello @jfischer-no, i wanted to further clarify: for raw interfaces, ctx->mode is initially set to MODBUS_MODE_RAW. However, due to the line I removed, when a raw interface is disabled and then reconfigured, ctx->mode erroneously switches to MODBUS_MODE_RTU. This switch causes an -ENOTSUP error when reconfiguring the interface with modbus_raw_init(), as the expected mode should remain MODBUS_MODE_RAW. My commit corrects this by ensuring the mode for raw interfaces doesn't change when disabled, allowing proper reconfiguration without errors

2024-01-19 15:19 UTC, jfischer-no approved these changes

2024-01-24 17:13 UTC, jfischer-no commented
@73jn Please rebase your PR on the latest Zephyr main to get rid of the CI issue, thanks.

2024-01-25 15:10 UTC, 73jn commented
@jfischer-no @carlescufi done !

2024-01-25 15:35 UTC, kartben approved these changes

2024-01-25 16:00 UTC, merged