drivers: i2c: correct spelling
zephyrproject-rtos/zephyr pull request #67563
Opened 2024-01-12 17:56 UTC by ndrs-pst

Employ a code spell checking tool to scan and correct spelling errors in all files within the drivers/i2c directory.

2024-01-12 18:10 UTC, dcpleung approved these changes, later dismissed

2024-01-12 18:17 UTC, teburd approved these changes, later dismissed

2024-01-12 18:19 UTC, kartben requested changes

2024-01-12 18:23 UTC, ndrs-pst commented on drivers/i2c/Kconfig.dw
> +	  data transfers. All Tx operation are done using dma channel 0 and
Got it will push new commit

2024-01-12 18:36 UTC, kartben approved these changes

2024-01-13 18:41 UTC, fabiobaltieri approved these changes

2024-01-13 19:42 UTC, teburd approved these changes

2024-01-15 04:01 UTC, MulinChao approved these changes

2024-01-15 08:06 UTC, erwango approved these changes

2024-01-15 08:59 UTC, merged