documentation: Fixed a typo in Rpi Pico index page
zephyrproject-rtos/zephyr pull request #67566
Opened 2024-01-12 20:44 UTC by HimaSava

Fixes #67435

There was a typo on the index page of Rpi Pico. Changed "Bluetoth" to "Bluetooth".

2024-01-12 22:16 UTC, soburi approved these changes

2024-01-13 03:04 UTC, soburi requested changes

2024-01-13 03:04 UTC, soburi commented on boards/arm/rpi_pico/doc/index.rst
> +Infineon CYW43439 2.4 GHz Wi-Fi/Bluetooth module. The USB bootloader allows the
Please fix CI error.

2024-01-16 01:18 UTC, soburi commented
@HimaSava 
CI errors are still remaining.
https://github.com/zephyrproject-rtos/zephyr/actions/runs/7511136103/job/20454348524?pr=67566

2024-02-05 12:04 UTC, henrikbrixandersen approved these changes

2024-02-05 12:05 UTC, henrikbrixandersen commented
@HimaSava You'll need to fix the commit log for this to be merged:

3: UC4 Commit message body line exceeds max length (82>75): "There was a typo on the index page of Rpi Pico. Changed "Bluetoth" to "Bluetooth"."
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 cd1893fd14b8e95d212ff7c0d6091f3b8631b780: author email (Himanshu Savargaonkar <H.Savargaonkar@student.tudelft.nl>) needs to match one of the signed-off-by entries.
Error: Process completed with exit code 1.

2024-03-05 04:48 UTC, soburi commented
@HimaSava

Could you rebase it, please?

2024-03-26 14:18 UTC, nashif commented
has been already addressed.

2024-03-26 14:18 UTC, closed without merging