MAINTAINERS: Create NXP IP group
zephyrproject-rtos/zephyr pull request #67797
Opened 2024-01-18 14:43 UTC by decsny

Create NXP IP group separate from the platforms.
The idea being that currently there are two problems:

- All the IP drivers are falling under the responsibility of the MCUX platforms' maintainers, some of whom do not have the cycles or interest to maintain these things, so this is wrong.

- The maintainers of the other platform groups do not get counted as reviewers of the IP drivers that their platforms use. This is also wrong.

So, separate all the driver files from the MCUX platforms, and add the relevant people who have an interest in maintaining the IP, including:

- At least one maintainer of each platform group, and
- The NXP contributors who are highly active in maintaining and reviewing the NXP drivers in upstream Zephyr.

Also add a few file paths to some of these groups to cover a few missed files, and add descriptions of the NXP groups in the maintainers yaml.

2024-01-18 14:52 UTC, nashif commented on MAINTAINERS.yml
> +NXP IP:
Can we please just call this NXP Drivers?

2024-01-18 22:35 UTC, DerekSnell commented
Thanks @decsny , I am looking forward to this change.

One existing line I suggest you change:
> NXP Platforms (MCUX):
    - boards/arm/frdm_k*/
 
Make this `boards/arm/frdm*/`.  We will soon be upstreaming support for the FRDM-MCXN947, with more MCX boards coming this year.

Thanks

2024-01-22 13:59 UTC, dbaluta commented on MAINTAINERS.yml
> +  status: maintained
I would split this commit into 3 patches:
- 1) add description for  NXP Xtensa platforms
- 2) create NXP Platforms (S32)
- 3) create NXP drivers entry

2024-01-22 14:13 UTC, dbaluta submitted a review, later dismissed

2024-01-22 14:15 UTC, decsny commented on MAINTAINERS.yml
> +    - boards/arm/s32*/
@manuargue updated with your feedback

2024-01-22 14:19 UTC, bperseghetti requested changes

2024-01-22 14:19 UTC, bperseghetti commented on MAINTAINERS.yml
>      - boards/arm/twr_*/
Add new line below:
```
- boards/arm/vmu*/
```

2024-01-22 14:52 UTC, bperseghetti approved these changes

2024-01-22 15:25 UTC, dbaluta approved these changes

2024-01-22 19:49 UTC, dleach02 approved these changes

2024-01-22 19:50 UTC, dleach02 commented
@MaureenHelm, I think NXP maintainers are good with this change now.

2024-01-22 19:53 UTC, nashif approved these changes

2024-01-22 20:03 UTC, MaureenHelm approved these changes

2024-01-22 20:25 UTC, merged