drivers: usb: device: can only receive one message
zephyrproject-rtos/zephyr pull request #67826
Opened 2024-01-19 09:41 UTC by Desvauxm-st

driver can only receive one message when the maximum packet length of an endpoint of the USB_EP_TYPE_BULK out type is 16

see issue #62577

2024-01-19 09:43 UTC, Desvauxm-st commented
This pr is in relation with 
The STM32 USB device driver can only receive one message when the maximum packet length of an endpoint of the USB_EP_TYPE_BULK out type is 16 #62577

2024-01-19 10:12 UTC, erwango commented
Please add Loic in Sign-off

@loicpoulain, is that fine with you?

2024-01-19 10:13 UTC, tmon-nordic requested changes
Commit message must explain the issue and what the fix does.

2024-01-22 11:55 UTC, Desvauxm-st commented
OK

2024-01-22 14:33 UTC, jfischer-no reviewed
How I understood the issue and would write commit message:

```
drivers: usb_dc_stm32: Fix OUT transfer issue

The driver cannot handle OUT transactions for an endpoint with an
MPS smaller than 64 bytes. To solve the issue, we will not use one
fixed value, EP_MPS, but instead use the actual MPS of an endpoint,
ep_state->ep_mps.

Signed-off-by: Marc Desvaux <marc.desvaux-ext@st.com>
Signed-off-by: Loic Poulain <loic.poulain@linaro.org>
```

2024-01-22 14:39 UTC, Desvauxm-st commented
ok thanks you

2024-01-22 15:51 UTC, jfischer-no approved these changes

2024-01-22 16:10 UTC, erwango approved these changes

2024-01-29 10:56 UTC, tmon-nordic approved these changes

2024-01-29 11:07 UTC, merged