Add BeagleBoard Platforms
zephyrproject-rtos/zephyr pull request #67841
Opened 2024-01-19 14:06 UTC by Ayush1325

- Due to the incresing support for ZephyrRTOS in BeagleBoard boards, it would be good to have this entry.
- Was discussed in Discord when asking for help for PR review

Details about BealgeBoard boards can be found here:
- https://www.beagleboard.org
- https://docs.beagleboard.org/latest/

cc @cfriedt

2024-01-19 14:11 UTC, cfriedt reviewed
I think there was an effort (at least at some time) to keep entries in alphabetical order. Can this be moved up to the right location?

2024-01-19 14:30 UTC, kartben requested changes
also, alphabetical order like Chris mentioned. Thanks!

2024-01-19 14:30 UTC, kartben commented on MAINTAINERS.yml
> +    - "area: BeagleBOard Platforms"
```suggestion
    - "area: BeagleBoard Platforms"
```

2024-01-19 14:30 UTC, kartben commented on MAINTAINERS.yml
> +    - "area: BeagleBoard Platforms"
```suggestion
    - "platform: BeagleBoard"
```

2024-01-19 14:30 UTC, kartben commented on MAINTAINERS.yml
> +    - boards/riscv/beaglev_fire/
probably doesn't hurt to do it this way:

```suggestion
    - boards/arm/beagle*
    - boards/riscv/beagle*
```

2024-01-19 14:40 UTC, Ayush1325 commented
Well, not sure why that is failing.

2024-01-19 14:46 UTC, kartben commented on MAINTAINERS.yml
> +    - "platform: BeagleBoard Platforms"
don't think any other platform label has "... Platforms" in them, hence why my previous suggestion :) 

```suggestion
    - "platform: BeagleBoard"
```

2024-01-19 14:48 UTC, kartben commented on MAINTAINERS.yml
> +    - boards/riscv/beagle*
failure is my fault, sorry, should have a trailing slash

```suggestion
    - boards/arm/beagle*/
    - boards/riscv/beagle*/
```

2024-01-19 15:14 UTC, jadonk commented
Do you need a signed-off-by from me? Do you have the removal of the term "Platforms"?

2024-01-19 15:14 UTC, kartben approved these changes

2024-01-19 15:15 UTC, kartben commented
> Do you need a signed-off-by from me? Do you have the removal of the term "Platforms"?

I do not think so, your +1 here should be more than enough

2024-01-19 16:31 UTC, cfriedt approved these changes

2024-01-22 14:29 UTC, MaureenHelm approved these changes

2024-01-23 09:02 UTC, merged

2024-01-26 11:04 UTC, kartben commented
@jadonk thanks for stepping up as a maintainer! Feel free to claim your Zephyr Maintainer badge here: https://forms.gle/oCw9iAPLhUsHTapc8 :)