drivers: sensor: SHT2X Added support
zephyrproject-rtos/zephyr pull request #67875
Opened 2024-01-20 18:09 UTC by panicking

This adds support for Sensirion's SHT2X temperature and humidity sensor.

2024-01-22 19:16 UTC, MaureenHelm requested changes
Please add this sensor to `tests/drivers/build_all/sensor`

2024-01-22 19:16 UTC, MaureenHelm commented on drivers/sensor/sht2x/sht2x.c
> +	if (!device_is_ready(cfg->bus.bus)) {
Use `i2c_is_ready_dt`

2024-01-22 19:16 UTC, MaureenHelm commented on drivers/sensor/sht2x/sht2x.c
> +	DEVICE_DT_INST_DEFINE(n,				\
Use `SENSOR_DEVICE_DT_INST_DEFINE`

2024-01-22 19:16 UTC, MaureenHelm commented on include/zephyr/drivers/sensor/sht2x.h
> +int sht2x_fetch_with_heater(const struct device *dev);
This isn't implemented anywhere

2024-01-24 18:37 UTC, str4t0m commented
Thanks for this contribution, but there is not really a need to add a completely new driver for these sensors.
Please have a look at the existing si7006 driver, https://github.com/zephyrproject-rtos/zephyr/pull/56227, and https://github.com/zephyrproject-rtos/zephyr/pull/22862#pullrequestreview-359397725.

2024-02-03 09:23 UTC, xyzzy42 commented
I have had a PR out for nearly a year, waiting, that adds support without adding a new driver.

2024-04-19 00:29 UTC, closed without merging