Quark d2000 dts
zephyrproject-rtos/zephyr pull request #679
Opened 2017-07-04 06:05 UTC by SavinayDharmappa

This patches add device tree support for mintvalley board and quark_d2000 microcontroller

2017-07-04 15:32 UTC, galak requested changes
Some fixups are needed.

2017-07-04 15:32 UTC, galak commented on dts/x86/quark_d2000_crb.dts
> +	model = "intel,quark";
model should be the board model.

2017-07-04 15:32 UTC, galak commented on dts/x86/quark_d2000_crb.dts
> +	compatible = "intel,quark";
should include the board compat first (like we have in dts/x86/arduino_101.dts)

2017-07-04 15:32 UTC, galak commented on dts/x86/intel_quark_d2000.dtsi
> +			compatible = "intel,quark";
is the cpu core the same as on quark_se_c1000?  Is there really only one quark cpu core?

2017-07-04 15:32 UTC, galak commented on dts/x86/quark_d2000_crb.dts
> +	compatible = "intel,quark";
Actually this should be something like:

compatible = "intel,quark-d2000-crb", "intel-quark-d2000", "intel,quark";

(I'm not sure if the "intel,quark" actually makes sense).

2017-07-05 13:42 UTC, SavinayDharmappa commented on dts/x86/intel_quark_d2000.dtsi
> +			compatible = "intel,quark";
quark_d2000 and quark_se_c1000 have same cpu. But quark_se_c1000 also have sensor subsystem which is arc cpu which not present in quark_d2000

2017-07-05 13:42 UTC, SavinayDharmappa commented on dts/x86/quark_d2000_crb.dts
> +	compatible = "intel,quark";
will correct it

2017-07-05 16:10 UTC, galak commented on dts/x86/intel_quark_d2000.dtsi
> +			compatible = "intel,quark";
that's fine, just that the 'cpu' section here is meant for the type of core(s) in the SoC.  So from what you say, they should have the same compatible between quark_d2000 & quark_se_c1000.

2017-07-14 13:21 UTC, galak requested changes
some minor things

2017-07-14 13:21 UTC, galak commented on dts/x86/quark_d2000_crb.dts
> +	model = "Mintvalley board";
seems like mintvalley is an internal name for the board, not seeing that referenced in our board docs for the board.  Probably not the best choice for model.

2017-07-14 13:21 UTC, galak commented on dts/x86/quark_d2000_crb.dts
> +	compatible = "intel,quark-d2000-crb","intel,quark-d2000";
nit, space after the comma

2017-07-14 13:21 UTC, galak commented on dts/x86/Makefile
> +dtb-$(CONFIG_SOC_SERIES_QUARK_D2000)	=	quark_d2000_crb.dts_compiled
should be in the board patch.

2017-07-19 15:25 UTC, galak approved these changes

2017-07-19 15:25 UTC, merged