Bluetooth: Audio: Use utf8_lcpy to copy UTF8 strings with termination.
zephyrproject-rtos/zephyr pull request #68092
Opened 2024-01-25 09:14 UTC by pin-zephyr

use the function utf8_lcpy to ensure that UTF8 encoded strings are properly copied and NULL terminated.

Fixes #42128

2024-01-25 12:49 UTC, Thalley requested changes
Minor formatting issues, otherwise LGTM

2024-01-25 12:49 UTC, Thalley commented on subsys/bluetooth/audio/aics.c
> +			sizeof(aics->srv.description));
```suggestion
		(void)utf8_lcpy(aics->srv.description, param->description,
				sizeof(aics->srv.description));
```

2024-01-25 12:49 UTC, Thalley commented on subsys/bluetooth/audio/tbs.c
> +			  sizeof(inst->uri_scheme_list));
```suggestion
	(void)utf8_lcpy(inst->uri_scheme_list, CONFIG_BT_TBS_URI_SCHEMES_LIST,
			sizeof(inst->uri_scheme_list));
```

2024-01-25 12:49 UTC, Thalley commented on subsys/bluetooth/audio/vocs.c
> +			sizeof(inst->output_desc));
```suggestion
		(void)utf8_lcpy(inst->output_desc, param->output_desc,
				sizeof(inst->output_desc));
```

2024-01-25 12:58 UTC, Thalley commented
This PR supersedes https://github.com/zephyrproject-rtos/zephyr/pull/67902 and thus also fixes https://github.com/zephyrproject-rtos/zephyr/issues/67953

2024-01-26 08:18 UTC, Thalley approved these changes

2024-01-26 08:41 UTC, larsgk approved these changes

2024-01-29 09:28 UTC, merged