doc: Update Zephyr SDK install instructions to use code-blocks
zephyrproject-rtos/zephyr pull request #68192
Opened 2024-01-27 23:21 UTC by psarvesh

I was going through the getting started documentation and noticed that some commands for installing the Zephyr SDK were not being shown correctly. 

I created this commit to fix that.
I tested this by generating the HTML documentation locally.

2024-01-28 01:18 UTC, kartben requested changes
Unfortunately this does not work -- see how the SDK version is not properly substituted anymore :/

2024-01-28 01:21 UTC, kartben commented
See https://github.com/zephyrproject-rtos/zephyr/pull/67603#discussion_r1455043627 for more context. It would be awesome if you find a solution though, as it definitely bothers me too that these blocks render differently and don't have the handy "copy" button.

2024-01-28 03:15 UTC, psarvesh commented
That's a good point. I hadn't seen the substitution part working.

From searching a bit, I found a different project that supports substitutions in code-block directives (https://github.com/adamtheturtle/sphinx-substitution-extensions). 

But before I explore that direction, maybe it would be a good idea to update `doc/conf.py` to do SDK version related substitutions using python.

2024-02-08 05:18 UTC, psarvesh commented
I am not sure if I am going in a good direction with this. So, I made a work-in-progress commit. Please feel free to provide feedback if you get a chance. Thanks! :v:

2024-02-08 08:41 UTC, gmarull requested changes
-1 to python hackery

2024-02-09 01:43 UTC, psarvesh commented
Thanks for letting me know! I do not have any other ideas beyond this for the time being. Should I move this pull request to draft or close it?

2024-02-13 08:53 UTC, gmarull commented
Closing, as current solution is good enough and we don't want Python hackery into the build pipe.

2024-02-13 08:53 UTC, closed without merging