Bluetooth: Audio: Moved seq_num check
zephyrproject-rtos/zephyr pull request #68235
Opened 2024-01-29 15:51 UTC by koffes

Moved seq_num check to after bt_iso_chan_send

2024-01-29 21:43 UTC, Thalley requested changes

2024-01-29 21:43 UTC, Thalley commented on subsys/bluetooth/audio/bap_stream.c
> +				buf, seq_num, ts);
```suggestion
	err = bt_iso_chan_send(bt_bap_stream_iso_chan_get(stream),
			       buf, seq_num, ts);
```

2024-01-29 21:43 UTC, Thalley commented on subsys/bluetooth/audio/bap_stream.c
> +	int err;
```suggestion
	int ret;
```

Since `bt_iso_chan_send` returns number of bytes sent or a negative value, `ret` is more accurate than `err`.

2024-01-29 21:43 UTC, Thalley commented on subsys/bluetooth/audio/bap_stream.c
> +	return 0;
Since `err` (or `ret`) returns the number of bytes sent, this should be
```suggestion
	return err;
```

2024-01-30 16:54 UTC, Thalley commented
@koffes Github claims that you pushed something 3 hours ago, but I don't see any change. Did you forgot a `git add`? :)

2024-01-31 08:19 UTC, Thalley approved these changes

2024-01-31 09:41 UTC, alexsven approved these changes

2024-01-31 10:31 UTC, kruithofa approved these changes

2024-01-31 21:13 UTC, merged