drivers: serial: stm32: always enable clock when exiting low power
zephyrproject-rtos/zephyr pull request #68236
Opened 2024-01-29 15:56 UTC by gautierg-st

Systematically enable the UART clock again when exiting a low power mode before reading the UART register.
Even though the previous code worked on STM32WBA, for most series, it is necessary to enable the clock to access the registers, otherwise they read as 0.

2024-01-29 16:19 UTC, erwango requested changes
I have an issue with this as initially pinctrl config was done before UART clock activation to avoid glitches on the line.
Is there any other way to do this ?

2024-01-30 08:40 UTC, gautierg-st commented
I suppose we'll have to do the pinctrl, then the clock, and if necessary the full init (or maybe just the rest of the init).

2024-02-01 15:54 UTC, erwango approved these changes, later dismissed

2024-02-02 08:25 UTC, FRASTM submitted a review, later dismissed
minor else LGTM

2024-02-02 08:54 UTC, gautierg-st commented on drivers/serial/uart_stm32.c
> +		if (err != 0) {
Done

2024-02-02 09:33 UTC, erwango approved these changes

2024-02-05 20:37 UTC, henrikbrixandersen approved these changes

2024-02-06 11:27 UTC, fabiobaltieri approved these changes

2024-02-06 14:48 UTC, merged