Bluetooth: Audio: Change samples and shell to use sinf
zephyrproject-rtos/zephyr pull request #68255
Opened 2024-01-29 23:21 UTC by Thalley

Change the samples and shell to use sinf instead of sin, as that return the expect float data type, instead of a double.

This change unblocks some Bluetooth PRs in CI

2024-01-29 23:24 UTC, kartben approved these changes

2024-01-30 09:03 UTC, cvinayak approved these changes

2024-01-30 09:59 UTC, henrikbrixandersen requested changes
@aescolar, @cfriedt Does `sinf()` require _POSIX_C_SOURCE >= 200112L?

2024-01-30 10:25 UTC, Thalley commented
> @aescolar, @cfriedt Does `sinf()` require _POSIX_C_SOURCE >= 200112L?

According to https://en.cppreference.com/w/c/numeric/math/sin it should be there since C99. 
The alternative solution here would be to cast input and output to `float`

2024-01-30 11:16 UTC, aescolar commented
> > @aescolar, @cfriedt Does `sinf()` require _POSIX_C_SOURCE >= 200112L?
> 
> According to https://en.cppreference.com/w/c/numeric/math/sin it should be there since C99. The alternative solution here would be to cast input to `double` and output to `float`

Either fix seems fine to me.

2024-01-30 11:17 UTC, aescolar approved these changes

2024-01-30 11:38 UTC, kruithofa approved these changes

2024-01-30 11:44 UTC, henrikbrixandersen approved these changes

2024-01-30 11:45 UTC, merged