STM32  nor flash controller gets address and size
zephyrproject-rtos/zephyr pull request #68274
Opened 2024-01-30 08:33 UTC by FRASTM

the stm32  qspi and ospi flash drivers can retrieve the NOR flash address and size directly from the device tree 
of their `compatible = "st,stm32-qspi-nor";`  or `compatible = "st,stm32-ospi-nor";`
This is done with the <reg> property of the qspi-nor-flash or ospi-nor-flash node as follows:

```
 mx25lm51245: ospi-nor-flash@70000000 {
                 compatible = "st,stm32-ospi-nor";
                reg = <0x70000000 DT_SIZE_M(64)>; /* 512 Mbits */
```

That will make the nor-flash controller driver using the address and size property and will prepare the flash controller for the memory mapped mode (XIP).
That will avoid confusion around the <size> expressed in bits or in byte : here is the reg second param a size in Bytes.

2024-01-30 11:18 UTC, erwango reviewed
Please also update migration guide `doc/releases/migration-guide-3.6.rst`

2024-01-31 07:48 UTC, Laczen submitted a review, later dismissed
LGTM, it is nice to see the size removed.

2024-01-31 08:01 UTC, erwango requested changes
Otherwise LGTM

2024-01-31 08:01 UTC, erwango commented on drivers/flash/flash_stm32_ospi.c
> +	.flash_size = DT_REG_ADDR_BY_IDX(DT_INST(0, st_stm32_ospi_nor), 1),
What about using `DT_INST_REG_ADDR_BY_IDX` directly ?

2024-01-31 10:29 UTC, FRASTM commented
same with DT_INST_REG_ADDR(0) and DT_INST_REG_ADDR_BY_IDX(0, 1)  macro

2024-01-31 10:35 UTC, erwango approved these changes
Thanks

2024-01-31 10:52 UTC, Laczen approved these changes

2024-01-31 11:16 UTC, de-nordic approved these changes

2024-01-31 12:43 UTC, erwango commented
CI issue under fix in https://github.com/zephyrproject-rtos/zephyr/pull/68285

2024-02-01 12:56 UTC, henrikbrixandersen approved these changes

2024-02-01 13:26 UTC, fabiobaltieri commented
```
/__w/zephyr/zephyr/samples/sensor/lsm6dsl/src/main.c:150:59: error: implicit conversion from 'float' to 'double' when passing argument to function [-Werror=double-promotion]
  150 |                                                           out_ev(&accel_x_out),
      |                                                           ^~~~~~~~~~~~~~~~~~~~
```

CI is sad

2024-02-01 13:38 UTC, erwango commented
> CI is sad

CI issue under fix in https://github.com/zephyrproject-rtos/zephyr/pull/68285

2024-02-02 12:48 UTC, merged