twister: only parse specified tests when using --test
zephyrproject-rtos/zephyr pull request #68312
Opened 2024-01-30 21:27 UTC by nashif

Enhance the -s option of twister, used to point to a single scenario in
a testsuite.
- Now accept --scenario on the command line, --test still supported.
- If no testsuite is provided, extract testsuite from scenario
  identifier and avoid parsing the whole tree if we only want to address
  one scenario in a testsuite.
- If just the identifier of the scenario is provided to
  --test/--scenario option, try to find this as well, do not need the
  full path for that.

Something like this is now possible:

twister  --scenario kernel.threads.init --list-tests
twister -T <path> --scenario kernel.threads.init --list-tests
twister -T <path>/kernel.threads.init --list-tests

All should print the same output.

Fixes #67307

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2024-01-31 03:52 UTC, hakehuang submitted a review, later dismissed

2024-02-02 16:04 UTC, PerMac requested changes
Just a quick spin but I think sth is wrong. I tried
`scripts/twister -s sample.basic.helloworld -v -p native_posix` and the sample got skipped instead executed. With `-T samples/hello_world" it executed correctly. Can debug deeper next week to see what's going on.

2024-02-02 16:04 UTC, PerMac commented on scripts/tests/twister_blackbox/test_error.py
> +        print(args)
debug leftover?

2024-02-02 19:25 UTC, nashif commented on scripts/tests/twister_blackbox/test_error.py
> +        print(args)
removed

2024-02-05 09:53 UTC, PerMac approved these changes

2024-02-05 12:08 UTC, gchwier commented on scripts/pylib/twister/twisterlib/environment.py
> +                    options.testsuite_root.append(dirname)
We can also think to remove path from testsuite name:
https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib/testsuite.py#L446
and use always as a testsuite name the name of scenario from testcase/sample yaml (if names are not unique, then must be updated).
The path of test is now added to report files (testplan.json, twister.json) so we do not need to duplicate it.

2024-02-15 16:40 UTC, hakehuang approved these changes

2024-02-16 10:24 UTC, henrikbrixandersen commented
@fabiobaltieri This looks like an enhancement. Why did you add it to the v3.6.0 milestone?

2024-02-16 10:35 UTC, fabiobaltieri commented
> @fabiobaltieri This looks like an enhancement. Why did you add it to the v3.6.0 milestone?

The attached issue is tagged as bug and sounds like one (twister erroring out when it shouldn't). Could keep it as a followup and backport later? @nashif what do you think?

2024-02-16 12:00 UTC, merged