kernel: provide Platform abstract interface for device drivers which are designed to works seamlessly on PCI bus, ACPI and DTS
zephyrproject-rtos/zephyr pull request #68411
Opened 2024-02-01 12:48 UTC by najumon1980

Provide Platform abstract interface for device drivers which are designed to work on multiple bus topologies such as PCI, ACPI or just DTS base. Driver developers can use the new PLATFORM_DT_DEV_INST_DEFINE macro instead of DEVICE_DT_INST_DEFINE in case they have to design drivers which need to works seamlessly on PCI bus, ACPI and DTS base.  Currently  there is no support for MSI and multi vectors. Following are some of the key features/highlight:

- Abstract underlying bus/parent complexity and providing a generic interface to driver developers. Using the new interface, driver developers need not want to bother about underlying bus interface and associated complexity. 
- Based on their parent node type, the interface will automatically enumerate resource such as MMIO and IRQ resources and configure them which will be completely transparent to device drivers
- The interface will take care of memory map of MMIO address in case platform support MMU
- The new PLATFORM_DT_DEV_INST_DEFINE  interface take ISR as on of the argument and will take care the ISR registration based on underlying bus/parent node  type(PCI/ACPI or just DTS). 
- The new interface add very little overhead (almost NIL)

2024-02-26 17:42 UTC, dcpleung requested changes
I still think this is complicating things too much. Can this be flowed into `DEVICE_MMIO_*` so you are not introducing yet another API?

2024-03-05 02:26 UTC, najumon1980 commented
> I still think this is complicating things too much. Can this be flowed into `DEVICE_MMIO_*` so you are not introducing yet another API?

my suggestion is better to be a new API and drivers which need to enable on PCI/ACPI can make use of this new API.

2024-03-05 02:26 UTC, najumon1980 commented on dts/bindings/base/base.yaml
> +
moved to a new yaml file

2024-03-05 02:26 UTC, najumon1980 commented on include/zephyr/platform.h
> +/*
updated

2024-03-05 02:26 UTC, najumon1980 commented on include/zephyr/platform.h
> +	struct pcie_dev *pcie
macro defined based on node position (parent node) and pcie struct is only if it is on PCIe bus/parent node (and if not it simply defined to DEVICE_MMIO_RAM)

2024-03-05 02:26 UTC, najumon1980 commented on include/zephyr/platform.h
> +#define Z_PLATFORM_PCI_DECLARE(n) _CONCAT(PLATFORM_PCI_DECLARE_, DT_INST_ON_BUS(n, pcie))(n)
updated

2024-03-05 19:40 UTC, dcpleung commented
> > I still think this is complicating things too much. Can this be flowed into `DEVICE_MMIO_*` so you are not introducing yet another API?
> 
> my suggestion is better to be a new API and drivers which need to enable on PCI/ACPI can make use of this new API.

But you are introducing another API with prefix `PLATFORM_` which absolutely adds to the confusion. Devices are devices, no matter which buses they are on.

2024-03-27 04:12 UTC, najumon1980 commented
> > > I still think this is complicating things too much. Can this be flowed into `DEVICE_MMIO_*` so you are not introducing yet another API?
> > 
> > 
> > my suggestion is better to be a new API and drivers which need to enable on PCI/ACPI can make use of this new API.
> 
> But you are introducing another API with prefix `PLATFORM_` which absolutely adds to the confusion. Devices are devices, no matter which buses they are on.

Agree and we can use same name (or flowed into) as standard DEVICE_XX macros. But my intention was that we need to distinguish these macros from standard DEVICE_XX macros and driver which plan to use in PCI bus or ACPI apart from DTS base shall only use these macros. Also I just renamed these macros to BUS_DEV_XX which avoid/reduce confusion

2024-04-10 00:50 UTC, najumon1980 commented
@dcpleung updated as per your comments and also responded to your comments as well.

2024-04-10 15:53 UTC, dcpleung commented
Changing the prefix from `PLATFORM_` to `BUS_` doesn't really solve the underlying issue: that you are introducing a new, separate/parallel way for device initialization. Both the NS16550 and RTC drivers (in this PR) require changes to utilize this. 

Do you mind sending a RFC to the mailing list to gather more comments on this?

2024-06-24 00:30 UTC, closed without merging