boards: arm: Add basic support for Silabs EFR32 SLWSTK6061A board
zephyrproject-rtos/zephyr pull request #6841
Opened 2018-03-28 16:11 UTC by chrta

2018-03-29 05:42 UTC, dbkinder requested changes
a few doc changes recommended

2018-03-29 05:42 UTC, dbkinder commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +System-On-Chip from the EFR32FG family built on ARM® Cortex®-M4F processor
``on an ARM``

2018-03-29 05:42 UTC, dbkinder commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +For more information about the EFR32FG1 SoC and EFR32-SLWSTK6061A board:
``board, refer to these documents:``

2018-03-29 05:42 UTC, dbkinder commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +The EFR32FG1P SoC has five gpio controllers (PORTA to PORTD and PORTF). All of
``GPIO``

2018-03-29 05:42 UTC, dbkinder commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +In the following table, the column Name contains Pin names. For example, PA2
``**Name**``  (to make it bold)

2018-03-29 08:46 UTC, chrta commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +System-On-Chip from the EFR32FG family built on ARM® Cortex®-M4F processor
done

2018-03-29 08:47 UTC, chrta commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +For more information about the EFR32FG1 SoC and EFR32-SLWSTK6061A board:
done

2018-03-29 08:47 UTC, chrta commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +The EFR32FG1P SoC has five gpio controllers (PORTA to PORTD and PORTF). All of
done

2018-03-29 08:47 UTC, chrta commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +In the following table, the column Name contains Pin names. For example, PA2
done

2018-04-05 13:46 UTC, galak reviewed
Any plans for a board code that uses this soc?

2018-04-05 19:50 UTC, chrta commented
> Any plans for a board code that uses this soc?

Basic support for one board is already included (without radio functionality, only gpio and uart), see https://github.com/zephyrproject-rtos/zephyr/pull/6841/commits/cf776eb21777879b53994d23b2baa98fb8410d39

The radio support will have to wait a few month until Silabs releases their radio API under an open license.

2018-04-05 20:43 UTC, chrta commented on boards/arm/efr32_slwstk6061a/doc/efr32_slwstk6061a.rst
> +   EFR32-SLWSTK6061A (image courtesy of Silicon Labs)
I added this note below the board image to credit Silicon Labs, see https://www.silabs.com/community/general-interest/forum.topic.html/usage_of_board_pictu-ydFZ

2018-04-11 22:42 UTC, dbkinder approved these changes
Thanks!

2018-07-09 19:22 UTC, chrta commented
@galak @MaureenHelm Is there anything blocking this or is there anything i can/must do to get this merged?

2018-07-09 20:09 UTC, diegosueiro commented on drivers/gpio/gpio_gecko.c
> +			BUS_RegBitWrite(&gpio_base->DOUT, pin, 1);
I think you can use a more clear assignment like:
gpio_base->DOUT |= BIT(pin);

2018-07-09 20:09 UTC, diegosueiro commented on drivers/gpio/gpio_gecko.c
> +			BUS_RegBitWrite(&gpio_base->DOUT, pin, 0);
I think you can use a more clear assignment like:
gpio_base->DOUT &= ~BIT(pin);

2018-07-09 21:06 UTC, galak commented
I think it would be good to rebase, as I think there are a few changes from upstream that this needs updating to.

2018-07-10 16:31 UTC, galak commented
> I think it would be good to rebase, as I think there are a few changes from upstream that this needs updating to.

I went ahead and rebased this and fixed up the few Kconfig related issues.

2018-07-10 17:53 UTC, merged

2018-07-10 19:08 UTC, chrta commented
Great, thank you