toolchain: do not use posix C code for asm language in gcc.h
zephyrproject-rtos/zephyr pull request #68474
Opened 2024-02-02 14:10 UTC by al1img

I have asm file to built-in some data into the final image as following:

```asm
#include <zephyr/toolchain.h>

.section .data.aos_root_ca,"a"
GDATA(__aos_root_ca_start)
GDATA(__aos_root_ca_end)
.align 8
__aos_root_ca_start:
.incbin  CONFIG_MY_DATA_FILE
__aos_root_ca_end:
```

This file is not compiled for `native_posix` boards due to the following error:

```bash
zephyr/arch/posix/posix_trace.h: Assembler messages:
zephyr/arch/posix/posix_trace.h:13: Error: no such instruction: `void posix_print_error_and_exit(const char *format,...)'
zephyr/arch/posix/posix_trace.h:14: Error: no such instruction: `void posix_print_warning(const char *format,...)'
zephyr/arch/posix/posix_trace.h:15: Error: no such instruction: `void posix_print_trace(const char *format,...)'
zephyr/arch/posix/posix_trace.h:28: Error: junk `(int output)' after expression
zephyr/arch/posix/posix_trace.h:28: Error: operand size mismatch for `int'
```

Including `<zephyr/arch/posix/posix_trace.h>` in `<toolchain/gcc.h>` causes the issues. The proposal fix is to remove the posix header for `asm` language conditionally.

2024-02-02 14:13 UTC, stephanosio approved these changes

2024-02-02 14:13 UTC, stephanosio requested changes

2024-02-02 14:13 UTC, stephanosio commented on include/zephyr/toolchain/gcc.h
> +#if defined(CONFIG_ARCH_POSIX) and !defined(_ASMLANGUAGE)
```suggestion
#if defined(CONFIG_ARCH_POSIX) && !defined(_ASMLANGUAGE)
```

2024-02-02 14:57 UTC, stephanosio approved these changes

2024-02-02 15:05 UTC, firscity approved these changes

2024-02-02 17:08 UTC, aescolar approved these changes
Thank you

2024-02-07 21:45 UTC, henrikbrixandersen approved these changes

2024-02-12 11:12 UTC, henrikbrixandersen commented
@tejlmand Please review.

2024-02-14 21:17 UTC, tejlmand approved these changes

2024-02-14 21:27 UTC, merged