Bluetooth: Support Zephyr controller `BT_RECV_WORKQ_BT`
zephyrproject-rtos/zephyr pull request #68510
Opened 2024-02-04 21:35 UTC by alwa-nordic

This patch allows selecting the combination of `CONFIG_BT_RECV_WORKQ_BT` and `BT_LL_SW_SPLIT`. The implementation of `bt_recv_prio` is copied from `hci_raw.c`. This ensures the order of packets is the same as when the controller's `hci_driver.c` is off-chip and sends HCI over UART.

2024-02-05 08:59 UTC, jori-nordic approved these changes, later dismissed

2024-02-05 09:14 UTC, alwa-nordic commented
Updated comment and commit message.

2024-02-05 09:37 UTC, cvinayak requested changes
Is there a `tests/bluetooth/init/` build that covers `CONFIG_BT_RECV_BLOCKING=n` and `CONFIG_BT_RECV_BLOCKING=y` ?

2024-02-05 10:17 UTC, jori-nordic commented
> Is there a `tests/bluetooth/init/` build that covers `CONFIG_BT_RECV_BLOCKING=n` and `CONFIG_BT_RECV_BLOCKING=y` ?

> This patch is a step towards the deprecation of `CONFIG_BT_RECV_BLOCKING`

It's going away very soon.

2024-02-05 12:56 UTC, alwa-nordic commented
> Is there a `tests/bluetooth/init/` build that covers `CONFIG_BT_RECV_BLOCKING=n` and `CONFIG_BT_RECV_BLOCKING=y` ?

I added an entry to `tests/bluetooth/init/testcase.yaml`.

2024-02-05 14:37 UTC, jori-nordic approved these changes, later dismissed

2024-02-06 04:59 UTC, cvinayak commented
> > Is there a `tests/bluetooth/init/` build that covers `CONFIG_BT_RECV_BLOCKING=n` and `CONFIG_BT_RECV_BLOCKING=y` ?
> 
> I added an entry to `tests/bluetooth/init/testcase.yaml`.

Latest head on the PR does not have it, your force-push removed it...

2024-02-06 08:40 UTC, cvinayak commented on tests/bluetooth/init/testcase.yaml
> +    platform_allow: qemu_cortex_m3
Why QEMU and not nRF5x SoC?
```suggestion
    platform_allow:
      - nrf52840dk_nrf52840
```

2024-02-06 08:43 UTC, cvinayak commented on tests/bluetooth/init/testcase.yaml
> +    extra_args:
```suggestion
  bluetooth.init.test_config_bt_recv_workq_bt:
    extra_args:
      - CONF_FILE=prj_ctlr.conf
```

2024-02-06 10:26 UTC, cvinayak approved these changes

2024-02-06 10:56 UTC, Thalley approved these changes

2024-02-06 11:28 UTC, jori-nordic approved these changes

2024-02-06 11:28 UTC, kruithofa approved these changes

2024-02-06 13:39 UTC, jhedberg approved these changes

2024-02-06 17:25 UTC, aescolar commented
@alwa-nordic  @cvinayak Should this target 3.7 (given that we are after rc1 for 3.6) or is this considered a bug?

2024-02-06 17:42 UTC, alwa-nordic commented
> @alwa-nordic @cvinayak Should this target 3.7 (given that we are after rc1 for 3.6) or is this considered a bug?

I think we don't need to treat it as a bug. We have not had a bug report for this from any user. It is possible to select a `CONFIG_BT_RECV_CONTEXT` kconfig that will result in a bug, but I doubt anyone would do this. The `CONFIG_BT_RECV_CONTEXT` has defaults that are ok, and there is no reason for users to change it.

2024-02-26 11:36 UTC, merged