hwmv2: Port STM32F3X SoCs & boards
zephyrproject-rtos/zephyr pull request #68638
Opened 2024-02-06 13:56 UTC by ajarmouni-st

Port STM32F3X SoCs & boards to Hardware Model V2.

2024-02-08 09:55 UTC, erwango requested changes

2024-02-08 09:55 UTC, erwango commented on boards/st/stm32373c_eval/stm32373c_eval_defconfig
> -
Comments to be cleaned up

2024-02-08 10:39 UTC, ajarmouni-st commented
Rebased to solve conflicts & address comments above.

2024-02-08 11:55 UTC, nordicjm commented
rebase needed

2024-02-08 13:03 UTC, erwango requested changes

2024-02-08 13:03 UTC, erwango commented on boards/st/stm32f3_disco/revision.cmake
This file could be removed.

2024-02-08 13:03 UTC, erwango commented on boards/st/nucleo_f334r8/nucleo_f334r8_defconfig
>  # Platform Configuration
Obsolete comments should be removed.

2024-02-08 15:10 UTC, erwango approved these changes

2024-02-09 07:15 UTC, nordicjm commented
Rebase needed

2024-02-09 08:51 UTC, ajarmouni-st commented
> Rebase needed

Done

2024-02-09 09:23 UTC, merged