arch: riscv: always set CONFIG_ARCH to 'riscv'
zephyrproject-rtos/zephyr pull request #68684
Opened 2024-02-07 10:29 UTC by gmarull

2024-02-07 12:11 UTC, gmarull commented
note: CI issue unrelated, will rebase once fixed.

2024-02-07 12:43 UTC, henrikbrixandersen submitted a review, later dismissed

2024-02-07 13:10 UTC, fkokosinski submitted a review, later dismissed

2024-02-07 13:55 UTC, nordicjm approved these changes

2024-02-07 14:10 UTC, nashif approved these changes, later dismissed

2024-02-07 14:41 UTC, carlocaione commented
mmmh, you sure about this? We did exactly the opposite with ARM because we had several problems keep the two together and now we are going in the opposite direction with RISCV?

2024-02-07 14:52 UTC, npitre commented
ARM32 and ARM64 are arguably two different architectures.
Differences between RISCV32 and RISCV64 are much much smaller.

2024-02-07 14:52 UTC, npitre approved these changes, later dismissed

2024-02-07 14:59 UTC, soburi submitted a review, later dismissed

2024-02-07 15:20 UTC, tejlmand submitted a review, later dismissed

2024-02-07 16:52 UTC, dleach02 submitted a review, later dismissed

2024-02-07 16:54 UTC, dleach02 commented
and, of course, CI failure in LPC, which has nothing to do with risc plaforms, is being invoked in twister... sigh

2024-02-08 11:31 UTC, gmarull commented
> and, of course, CI failure in LPC, which has nothing to do with risc plaforms, is being invoked in twister... sigh

We need TwisterGPT

2024-02-12 10:58 UTC, nordicjm requested changes
This is actually not working, don't know why CI isn't picking it up:
```
Failed processing /tmp/aa/zephyr/tests/kernel/fpu_sharing/generic   0, error:    0
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1289, in pipeline_mgr
    pb.process(pipeline, done_queue, task, lock, results)
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 596, in process
    ret = self.cmake(filter_stages=self.instance.filter_stages)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1052, in cmake
    return self.run_cmake(args,filter_stages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 401, in run_cmake
    filter_results = self.parse_generated(filter_stages)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 519, in parse_generated
    raise se
  File "/tmp/aa/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 514, in parse_generated
    ret = expr_parser.parse(self.testsuite.filter, filter_data, edt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/zephyr/scripts/pylib/twister/expr_parser.py", line 313, in parse
    ast = parser.parse(expr_text)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
        ^^^^^^^^^^^^^^^^
  File "/tmp/aa/zephyr/scripts/pylib/twister/expr_parser.py", line 179, in p_error
    raise SyntaxError("Unexpected token '%s'" % p.value)
SyntaxError: Unexpected token 'CONFIG_64BIT'
```

2024-02-12 11:03 UTC, nordicjm commented on tests/kernel/fpu_sharing/generic/testcase.yaml
> +    filter: CONFIG_CPU_HAS_FPU && !CONFIG_64BIT
```suggestion
    filter: CONFIG_CPU_HAS_FPU and not CONFIG_64BIT
```

2024-02-12 11:03 UTC, nordicjm commented on tests/kernel/fpu_sharing/generic/testcase.yaml
> +    filter: CONFIG_CPU_HAS_FPU && CONFIG_64BIT
```suggestion
    filter: CONFIG_CPU_HAS_FPU and CONFIG_64BIT
```

2024-02-13 08:31 UTC, gmarull commented on tests/kernel/fpu_sharing/generic/testcase.yaml
> +    filter: CONFIG_CPU_HAS_FPU && !CONFIG_64BIT
thanks, good catch

2024-02-13 08:42 UTC, gmarull commented
last push: fixed some syntax errors, also updated patch set to be bisectable.

2024-02-13 08:56 UTC, henrikbrixandersen approved these changes

2024-02-13 08:57 UTC, fkokosinski approved these changes

2024-02-13 09:06 UTC, nordicjm approved these changes

2024-02-13 10:22 UTC, fabiobaltieri approved these changes

2024-02-13 13:53 UTC, dleach02 approved these changes

2024-02-13 17:57 UTC, fabiobaltieri commented
@carlescufi we settle for 3.7 for this right?

2024-02-23 11:09 UTC, tejlmand approved these changes

2024-02-26 11:49 UTC, merged