hwmv2: STM32: Fixes
zephyrproject-rtos/zephyr pull request #68819
Opened 2024-02-09 16:22 UTC by ajarmouni-st

Cleanup & fix for CI issue https://github.com/zephyrproject-rtos/zephyr/pull/68801#issuecomment-1935986243

2024-02-09 16:35 UTC, erwango commented on boards/st/stm32f3_disco/stm32f3_disco_stm32f303xc_E.overlay
Shouldn't we update .conf and .yaml files as well ?

2024-02-09 16:36 UTC, erwango requested changes

2024-02-09 16:36 UTC, erwango commented on boards/st/nucleo_f030r8/nucleo_f030r8_1.overlay
Should be in previous commit

2024-02-09 16:36 UTC, erwango commented on boards/st/stm32f3_disco/stm32f3_disco_E.overlay
Should be in previous commit

2024-02-09 16:42 UTC, ajarmouni-st commented on boards/st/stm32f3_disco/stm32f3_disco_stm32f303xc_E.overlay
I don't think so

2024-02-13 13:37 UTC, erwango approved these changes

2024-02-13 16:23 UTC, nordicjm approved these changes

2024-02-13 16:23 UTC, nordicjm requested changes
> ERROR   - tests/drivers/clock_control/stm32_clock_configuration/stm32_common_devices/drivers.clock.stm32_clock_configuration.common_device.f3.i2c1_hsi - platform_allow - unrecognized platform - stm32f3_disco

2024-02-14 07:54 UTC, nordicjm approved these changes

2024-02-14 07:54 UTC, merged