boards: lpcxpresso55s69: Fix misnomer
zephyrproject-rtos/zephyr pull request #68898
Opened 2024-02-12 20:44 UTC by decsny

pinmux.c is inaptly named since it has nothing to do with pinmux. Also, remove inclusion of iocon.h since this file does not use it, as this file has nothing to do with pinmux.

Fixes #59185

2024-02-13 08:20 UTC, gmarull requested changes, later dismissed
see my comment on the issue, thanks

2024-03-04 07:47 UTC, nordicjm requested changes
Needs converting to hwmv2

2024-03-08 18:58 UTC, decsny commented
closing because this was fixed during hwmv2 porting

2024-03-11 13:59 UTC, henrikbrixandersen approved these changes

2024-03-11 14:00 UTC, henrikbrixandersen commented
@nordicjm PTAL

2024-03-12 11:24 UTC, nordicjm approved these changes

2024-03-12 20:10 UTC, yvanderv approved these changes

2024-03-12 20:11 UTC, dleach02 approved these changes

2024-03-12 20:26 UTC, merged