Add vl53l0cxv0dh stm32wb5mm dk
zephyrproject-rtos/zephyr pull request #68926
Opened 2024-02-13 10:44 UTC by javad123javad

Add device tree node for `VL53L0CXV0DH/1` and `ISM330DHCX` sensors

2024-02-28 12:25 UTC, erwango approved these changes, later dismissed

2024-03-04 07:47 UTC, nordicjm submitted a review, later dismissed
Needs converting to hwmv2

2024-03-06 06:34 UTC, javad123javad commented
> Needs converting to hwmv2

Thanks,
Should I open a new PR?

2024-03-06 07:31 UTC, nordicjm commented
> > Needs converting to hwmv2
> 
> Thanks, Should I open a new PR?

No, update this one

2024-03-11 13:31 UTC, erwango submitted a review, later dismissed

2024-03-11 21:30 UTC, GeorgeCGV requested changes, later dismissed

2024-03-11 21:30 UTC, GeorgeCGV commented on boards/st/stm32wb5mm_dk/stm32wb5mm_dk.dts
> +		gyro-odr=<2>;
```suggestion
		accel-odr = <ISM330DHCX_DT_ODR_52Hz>;
		gyro-odr = <ISM330DHCX_DT_ODR_26H>;
```

2024-05-03 15:49 UTC, erwango submitted a review, later dismissed

2024-06-07 17:10 UTC, kartben commented
rebased to resolve merge conflict

2024-06-11 07:31 UTC, ajarmouni-st approved these changes

2024-06-11 09:01 UTC, erwango commented
@GeorgeCGV PTAL

2024-06-12 10:45 UTC, kartben approved these changes

2024-06-12 11:58 UTC, erwango approved these changes

2024-06-12 16:53 UTC, merged