dts: stm32h7.dtsi: Add missing timer definitions
zephyrproject-rtos/zephyr pull request #68948
Opened 2024-02-13 17:09 UTC by sageve

TIM23/TIM24 are functionally equal to TIM2/TIM5, but regarding @erwango they are just not defined in stm32h7.dtsi. This PR adds their definitions.

2024-02-14 08:16 UTC, gautierg-st requested changes
From what I can tell, TIM23 and TIM24 are only available on STM32H72x and H73x, so their definitions should be in stm32h723.dtsi instead of stm32h7.dtsi.

2024-02-14 10:45 UTC, gautierg-st requested changes
LGTM, but please squash your commits in a single one.

2024-02-14 13:29 UTC, gautierg-st approved these changes
Thanks for this!

2024-02-15 10:45 UTC, erwango approved these changes

2024-02-27 13:58 UTC, aescolar commented
@fabiobaltieri @erwango are your 2 week old requests for extra reviews gating this from being merged?

2024-02-27 14:14 UTC, fabiobaltieri commented
> @fabiobaltieri @erwango are your 2 week old requests for extra reviews gating this from being merged?

No this can go in.

2024-02-27 14:14 UTC, merged