soc: arm: stm32 with USB Type-C dead battery disabled if needed
zephyrproject-rtos/zephyr pull request #68980
Opened 2024-02-14 12:32 UTC by FRASTM

Check the driver configuration to disable
the USB Type-C dead battery, only if
- a USB PD system is in place (the UCPD node is enabled)
- or the user does not require USB PHY anyway

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/68577

2024-02-15 08:25 UTC, erwango commented
^^@JPHutchins

2024-02-20 13:50 UTC, erwango submitted a review, later dismissed

2024-02-20 16:38 UTC, JPHutchins approved these changes

2024-03-04 07:47 UTC, nordicjm requested changes, later dismissed
Needs converting to hwmv2

2024-03-12 14:51 UTC, erwango approved these changes

2024-03-13 07:47 UTC, gautierg-st approved these changes

2024-03-13 11:09 UTC, merged