boards: thingy52: deprecate board
zephyrproject-rtos/zephyr pull request #69077
Opened 2024-02-16 10:24 UTC by gmarull

Nordic Semiconductor no longer offers support for this board, so flag it as deprecated and warn users to avoid it for new prototypes.

2024-02-16 11:01 UTC, pdunaj approved these changes

2024-02-16 11:05 UTC, henrikbrixandersen requested changes
Why deprecate the board? Lots of the boards we have support for in-tree receive little or no vendor support.

People who already have this board should be able to continue using it with Zephyr going forward. Given the near-product like features of this board, they may even have bought it based on the Zephyr support.

Personally, I have two of these in use and I see no reason for deprecating support for them.

2024-02-16 11:10 UTC, gmarull commented
> Why deprecate the board? Lots of the boards we have support for in-tree receive little or no vendor support.
> 
> People who already have this board should be able to continue using it with Zephyr going forward. Given the near-product like features of this board, they may even have bought it based on the Zephyr support.
> 
> Personally, I have two of these in use and I see no reason for deprecating support for them.

We basically need a mechanism to inform people that this board is no longer supported. Maybe DEPRECATED is not the best choice. We could add a new option like BOARD_DISCONTINUED that issues a CMake warning?

2024-02-16 11:16 UTC, gmarull commented
Another idea I had is to introduce a new “status” field in the HWMv2 board.yml, that allows is to set “supported”, “discontinued”, “beta”, etc. and issue warnings for levels that may require some attention.

2024-02-16 11:18 UTC, henrikbrixandersen commented
> Another idea I had is to introduce a new “status” field in the HWMv2 board.yml, that allows is to set “supported”, “discontinued”, “beta”, etc. and issue warnings for levels that may require some attention.

I think we are overcomplicating things. How about just introducing a warning or notice in the board documentation?

2024-02-16 16:14 UTC, gmarull commented
> > Another idea I had is to introduce a new “status” field in the HWMv2 board.yml, that allows is to set “supported”, “discontinued”, “beta”, etc. and issue warnings for levels that may require some attention.
> 
> I think we are overcomplicating things. How about just introducing a warning or notice in the board documentation?

fair enough, but I think a warning telling users that such board is discontinued doesn't hurt either.

2024-02-16 16:18 UTC, henrikbrixandersen commented
> fair enough, but I think a warning telling users that such board is discontinued doesn't hurt either.

The problem with using deprecation (without a replacement) is that it signals that support will be removed after a period of time.

2024-02-16 16:19 UTC, gmarull commented
> > fair enough, but I think a warning telling users that such board is discontinued doesn't hurt either.
> 
> The problem with using deprecation (without a replacement) is that it signals that support will be removed after a period of time.

this is why I was suggesting to add a new flag that does not imply removal, but still issues a warning

2024-02-16 16:22 UTC, henrikbrixandersen commented
I really don't see why we need to issue a build warning just because someone is building for a board, that has been discontinued by the vendor. 

This does not affect the build in any way.

2024-02-16 21:12 UTC, tagunil commented
There are so many of these boards in existence, that they'll be used for years to come for different prototyping needs.

2024-02-19 07:52 UTC, nordicjm commented
I don't really see the point in this. If you add a cmake warning then you can no longer build anything with the boar in CI which then does mean something is going to break, we still allow building for the nrf51dk without any issue so I don't see why the same can't be said of the thingy52

2024-02-19 07:53 UTC, kartben approved these changes, later dismissed

2024-02-19 10:57 UTC, gmarull commented
just left a warning in the docs

2024-02-19 11:04 UTC, nordicjm approved these changes, later dismissed

2024-02-19 11:07 UTC, henrikbrixandersen approved these changes, later dismissed

2024-02-19 11:15 UTC, kartben submitted a review, later dismissed

2024-03-04 08:40 UTC, nordicjm approved these changes

2024-03-04 08:45 UTC, kartben approved these changes

2024-03-04 08:47 UTC, henrikbrixandersen approved these changes

2024-03-04 09:12 UTC, pdunaj approved these changes

2024-03-08 10:09 UTC, fabiobaltieri commented
@anangl ping

2024-03-08 10:19 UTC, anangl approved these changes

2024-03-08 10:32 UTC, merged