doc: release-notes-3.6: MDIO changes
zephyrproject-rtos/zephyr pull request #69104
Opened 2024-02-16 21:55 UTC by decsny

Add changes to 3.6 release notes for MDIO drivers

2024-02-16 22:57 UTC, kartben requested changes

2024-02-16 22:57 UTC, kartben commented on doc/releases/release-notes-3.6.rst
> +  * Fixed ESP32 MDIO driver being enabled when node was not staus okay.
```suggestion
  * Fixed ESP32 MDIO driver being enabled when node was not status okay.
```

2024-02-16 22:57 UTC, kartben commented on doc/releases/release-notes-3.6.rst
> +  * Fixed SAM GMAC transfer timeout errors caused by mdio clock not being initialized.
I would recommend using consistent uppercase spelling of "MDIO" across the entire changeset

2024-02-16 22:57 UTC, kartben commented on doc/releases/release-notes-3.6.rst
> +  * Supported C22 and C45 apis on S32 GMAC.
```suggestion
  * Added support for C22 and C45 APIs on S32 GMAC.
```

2024-02-17 02:16 UTC, kartben approved these changes

2024-02-17 11:07 UTC, henrikbrixandersen approved these changes

2024-02-17 13:17 UTC, merged