boards: sam_e70_xplained: Enable userspace
zephyrproject-rtos/zephyr pull request #6915
Opened 2018-04-04 08:38 UTC by AdithyaBaglody

Enabled usersapce support for Atmel SAMe70.

Confirmed this works on tests/kernel/mem_protect/usersapce and tests/kernel/mem_protect/mem_protect.

2018-04-04 09:54 UTC, jukkar reviewed
Typo in commit message, s/usersapce/userspace/

2018-04-05 03:10 UTC, AdithyaBaglody commented
@jukkar thanks for catching it

2018-04-05 03:43 UTC, tyrantlizard77 requested changes

2018-04-05 03:43 UTC, andrewboie commented on arch/arm/soc/atmel_sam/common/arm_mpu_regions.c
> +static struct arm_mpu_region mpu_regions[] = {
I suspect we can drastically reduce the size of this.
Right now there is a background mapping set in the MPU which grants supervisor mode RW (no execute) access to the entire memory map, which acts as a least-precedence region for the entire address space.
We will need to keep the FLASH_0 region.
But with the background map I think we can discard RAM_0, PERIPHERAL_0, and PPB_0. Hence freeing up more regions for use with memory domains.
@agross-linaro @chunlinhan is my thinking sound on this?

2018-04-05 03:43 UTC, andrewboie commented on arch/arm/soc/atmel_sam/common/arm_mpu_regions.c
> +			 REGION_RAM_ATTR(REGION_SRAM_0_SIZE)),
If my above assertion is NOT correct, why don't we have a region for the REGION_SRAM1 stuff you put in the arm_mpu_mem_cfg.h? Not all memory will be able to be addressed.
This is probably moot though, I think we can just leverage the background map and get rid of this entirely.

2018-04-10 04:22 UTC, agross-oss approved these changes
the long ifdef elif blocks are a little brute force, but i suppose it's ok.

2018-04-12 09:57 UTC, AdithyaBaglody commented
Delta:
Fixed the extraneous memory region definitions.

2018-04-16 16:01 UTC, tyrantlizard77 approved these changes

2018-04-16 16:01 UTC, merged