Beechwoods fixes
zephyrproject-rtos/zephyr pull request #69300
Opened 2024-02-21 16:21 UTC by cliu5764

Fixed the following compiler warnings/errors:
include/zephyr/net/buf.h - casts assignment to prevent warning 
include/zephyr/net/hostname.h - Just prevents a compiler warning due to unused arg. Should use "ARG_UNUSED(<arg>) rather than "(void) <arg>;"
include/zephyr/net/net_context.h - casts and ARG_UNUSED() to prevent compiler warnings.
include/zephyr/net/net_if.h - several ARG_UNUSED().
include/zephyr/net/net_ip.h - cast in an assignment (presumably to prevent warning).
include/zephyr/posix/time.h - cast to prevent warning
include/zephyr/sys/byteorder.h - lots of casts to prevent warnings
include/zephyr/sys/util.h - cast to prevent warnings

2024-02-21 16:32 UTC, thedjnK requested changes

2024-02-21 16:32 UTC, thedjnK commented on include/zephyr/net/hostname.h
> +	(void) hostname_postfix;
zephyr uses ARG_UNUSED() for this

2024-02-21 16:32 UTC, thedjnK commented on include/zephyr/net/net_context.h
> +	  context->flags &= (uint16_t)~NET_CONTEXT_ACCEPTING_SOCK;
??

2024-02-22 10:14 UTC, jukkar commented
Some general notes:
* Please do not use merge commits in the PRs.
* See https://docs.zephyrproject.org/latest/contribute/guidelines.html#pull-requests-and-issues for some contribution guidelines. Each commit needs to have clear subject, body and signed-off-by lines
* Split the changes to logical components, all network related fixes to one commit, posix to one, and utility fixes to one commit inside this PR.

2024-02-22 17:28 UTC, closed without merging

2024-02-22 17:29 UTC, cliu5764 commented
Going to redo it with 3.6 release