drivers: i2c: Fix TOCTOU while transferring I2C messages
zephyrproject-rtos/zephyr pull request #6933
Opened 2018-04-04 23:22 UTC by lpereira

All the mesages are checked with _SYSCALL_MEMORY() prior to calling the
actual implementation function.  However, a race condition might happen
between the check and the call to _impl_i2c_transfer() itself.  Copy
the msgs vector to a locally allocated array and pass it to the
transfer implementation.

Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

2018-04-10 15:20 UTC, tyrantlizard77 requested changes

2018-04-10 15:20 UTC, andrewboie commented on drivers/i2c/i2c_handlers.c
> +	struct i2c_msgs copy[num_msgs];
the data type is "struct i2c_msg"

try building tests/drivers/build_all with test_build_sensors_a_m.conf on qemu_x86 to see the build error

2018-04-25 00:24 UTC, lpereira commented
@andrewboie This is now building and passing, could you please re-review/merge?

2018-04-25 01:29 UTC, tyrantlizard77 approved these changes

2018-04-25 01:30 UTC, merged