drivers: adc: fix warning when using `ADC_DT_SPEC_GET` macro on C++
zephyrproject-rtos/zephyr pull request #69419
Opened 2024-02-24 18:34 UTC by ArchieAtkinson

Modifies the `ADC_CHANNEL_CFG_DT` macro to always initialise the `differential` property to prevent the `-Wmissing-field-initializers` warning when using `ADC_DT_SPEC_GET` macros in C++ when not using a `differential` ADC.

2024-02-25 02:22 UTC, marc-hb requested changes
A similar, recent change broke one of our toolchains:
- #68118

Please hold this back until the corresponding policy has been discussed and approved and this flag added in CI.
- #67396

This policy should be either enforced everywhere or nowhere.

See also:
- #69411

2024-03-02 01:25 UTC, marc-hb commented
Enforcing this policy could be as simple as making sure CI compiles every .h file with `g++ -std=c++20` at least once.

https://github.com/zephyrproject-rtos/zephyr/pull/69486/files explains why.

2024-03-02 16:19 UTC, ArchieAtkinson commented
> Enforcing this policy could be as simple as making sure CI compiles every .h file with `g++ -std=c++20` at least once.
> 
> https://github.com/zephyrproject-rtos/zephyr/pull/69486/files explains why.
> 
> This would of course catch ALL OTHER C++ compatibility issues, not just this initializer warning.

As someone who uses Zephyr with C++20 in production code, I would love to see these compatibility issues solved and be part of the effort to do so. However, I think there would have to be an appetite for it within the project as macros like `CONTAINER_OF()` that are widely used trigger C++ warnings.

2024-03-10 18:37 UTC, marc-hb commented
> Enforcing this policy could be as simple as making sure CI compiles every .h file with g++ -std=c++20 at least once.

This could be as simple as compiling a file with a lot of `#include` in `tests/lib/cpp`. You should give it a try.

2024-03-20 03:58 UTC, marc-hb commented
> This could be as simple as compiling a file with a lot of #include in tests/lib/cpp. You should give it a try.

It's a bit more complicated because unused macros are parsed but not compiled.

It can be done though, see how I'm adding C++ compilation of `device.h` in #70403 with just one additional line in [tests/lib/cpp/cxx/src/main.cpp](https://github.com/zephyrproject-rtos/zephyr/pull/70403/files#diff-fbd9fec725dfad3be0795b7db59e15bb84a7f46490e452e569c793fbe3fb731b)

See if you can actually compile ADC_CHANNEL_CFG_DT() in C++ using some `tests/` change too.

2024-06-04 00:29 UTC, closed without merging