fix: sensor: veml7700
zephyrproject-rtos/zephyr pull request #69430
Opened 2024-02-25 20:02 UTC by jilaypandya

This commit introduces checks in order to sanitize input data.
Following Issues should be resolved with this change.

https://github.com/zephyrproject-rtos/zephyr/issues/69114
https://github.com/zephyrproject-rtos/zephyr/issues/69116
https://github.com/zephyrproject-rtos/zephyr/issues/69120
https://github.com/zephyrproject-rtos/zephyr/issues/69123
https://github.com/zephyrproject-rtos/zephyr/issues/69124
https://github.com/zephyrproject-rtos/zephyr/issues/69127
https://github.com/zephyrproject-rtos/zephyr/issues/69128

2024-02-25 20:05 UTC, jilaypandya commented
Hi @jeffwelder-ellenbytech, could you quickly test out the changes on your hardware?

2024-02-26 20:44 UTC, jeffwelder-ellenbytech commented
@jilaypandya Ran a quick test on my hardware with your changes, everything seemed to work as expected. 
My application did a fetch all and got lux, als, and white channels with no issues. :)

2024-04-10 20:54 UTC, MaureenHelm requested changes
Sorry this fell through the cracks.

Please rebase and split the unrelated whitespace changes to a separate commit.

2024-04-11 16:12 UTC, MaureenHelm requested changes
Some minor nits, but otherwise looks good

2024-04-11 16:12 UTC, MaureenHelm commented on drivers/sensor/vishay/veml7700/veml7700.c
> +				  uint32_t *return_value)
Rename `return_value` to `lux`

2024-04-11 16:23 UTC, MaureenHelm approved these changes

2024-04-11 17:39 UTC, teburd approved these changes

2024-04-11 17:53 UTC, dipakgmx approved these changes

2024-04-11 18:10 UTC, merged