drivers: udc: eliminate C++ errors by casting void* to the target type
zephyrproject-rtos/zephyr pull request #69490
Opened 2024-02-26 20:44 UTC by benedekkupper

When this header is included in a C++ source file, compilation fails due to invalid syntax. It can be converted to a warning with `-fpermissive`, but the long term solution is to just perform the missing casts as done here.

2024-02-28 10:31 UTC, tmon-nordic submitted a review, later dismissed

2024-02-28 11:30 UTC, de-nordic submitted a review, later dismissed

2024-04-30 08:02 UTC, benedekkupper commented
@jfischer-no is there anything to be done to move this PR forward?

2024-05-28 16:54 UTC, jfischer-no requested changes
Here in project, we are using C language. Implicit conversion to a pointer to void is fine and vice versa.
What this PR is trying to fix?

2024-05-28 17:44 UTC, yperess approved these changes, later dismissed

2024-05-28 20:23 UTC, benedekkupper commented
It may be that the bugfix in the branch name is a misnomer, since the Zephyr codebase itself builds without issues. However, Zephyr [claims](https://docs.zephyrproject.org/latest/develop/languages/cpp/index.html) to support applications written in both C and C++. This PR is a step to reach this claim in effect. It has absolutely no adverse effects when compiled into C, but this change is vital to allow compilation into C++.

2024-06-24 21:54 UTC, henrikbrixandersen approved these changes, later dismissed

2024-08-09 21:20 UTC, kartben commented
@jfischer-no please revisit

2024-10-03 07:24 UTC, tmon-nordic approved these changes

2024-10-03 07:46 UTC, de-nordic approved these changes

2024-11-19 10:26 UTC, henrikbrixandersen approved these changes

2024-11-19 10:27 UTC, henrikbrixandersen commented
> Here in project, we are using C language. Implicit conversion to a pointer to void is fine and vice versa. 

But we do support out-of-tree applications written in C++, where implicit pointer conversion leads to a warning.

2025-01-10 09:56 UTC, kartben commented
@jfischer-no please revisit. There are many drivers in-tree that do this already so I find it really hard to justify why this would be an issue. Thanks!

2025-01-10 10:01 UTC, henrikbrixandersen commented
> @jfischer-no please revisit. There are many drivers in-tree that do this already so I find it really hard to justify why this would be an issue. Thanks!

We even have a dedicated test for including device driver headers from C++: https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/lib/cpp/cxx/src/main.cpp

2025-01-10 14:46 UTC, jfischer-no requested changes
This is UDC driver API, for the drivers written in C, for the USB device stack written in C, you have to compile it with C compiler not C++. There is no need for this type conversion in C!

2025-01-10 15:10 UTC, carlescufi commented
@benedekkupper can you expand on your use case to try and figure out what the issue is here? Are you trying to write a UDC driver in C++, or are you including the `udc.h` header in a C++ file? or is it being auto-included making your build fail?

2025-01-10 21:12 UTC, benedekkupper commented
I am using the UDC driver (and zephyr itself) as one of the supported platforms of an [alternative USB device stack](https://github.com/IntergatedCircuits/c2usb-zephyr-examples) (written in C++).

You might be asking, why not using zephyr's own USB device stack instead?
1. Our project (UHK-80) started 2 years ago, when zephyr's USB device stack was nowhere yet, we needed something working sooner.
2. C++ allows for a compile-time HID report descriptor parser, so with this solution the USB endpoint max packet sizes are calculated from the report descriptor directly, providing a single source of truth. (It also provides the number of BLE HOGP attributes needed in compile-time, making GATT characteristic and UUID pools unnecessary - but that's nrf sdk territory.)

And now a question from my side: why put so much effort into such a well-defined and well-designed separation between the USB device stack and the UDC driver, if you don't let them be used on their own?

2025-01-12 19:47 UTC, carlescufi commented
> I am using the UDC driver (and zephyr itself) as one of the supported platforms of an [alternative USB device stack](https://github.com/IntergatedCircuits/c2usb-zephyr-examples) (written in C++).
> 
> You might be asking, why not using zephyr's own USB device stack instead?
> 
> 1. Our project (UHK-80) started 2 years ago, when zephyr's USB device stack was nowhere yet, we needed something working sooner.
> 2. C++ allows for a compile-time HID report descriptor parser, so with this solution the USB endpoint max packet sizes are calculated from the report descriptor directly, providing a single source of truth. (It also provides the number of BLE HOGP attributes needed in compile-time, making GATT characteristic and UUID pools unnecessary - but that's nrf sdk territory.)
> 
> And now a question from my side: why put so much effort into such a well-defined and well-designed separation between the USB device stack and the UDC driver, if you don't let them be used on their own?

Thanks @benedekkupper! This explains it very clearly. I am very much in favor of this change following your explanation. This is a +1 from me.

2025-01-12 19:47 UTC, carlescufi approved these changes

2025-01-24 11:35 UTC, jfischer-no commented
> I am using the UDC driver (and zephyr itself) as one of the supported platforms of an [alternative USB device stack](https://github.com/IntergatedCircuits/c2usb-zephyr-examples) (written in C++).
> 
> You might be asking, why not using zephyr's own USB device stack instead?
> 
>     1. Our project (UHK-80) started 2 years ago, when zephyr's USB device stack was nowhere yet, we needed something working sooner.
> 
>     2. C++ allows for a compile-time HID report descriptor parser, so with this solution the USB endpoint max packet sizes are calculated from the report descriptor directly, providing a single source of truth. (It also provides the number of BLE HOGP attributes needed in compile-time, making GATT characteristic and UUID pools unnecessary - but that's nrf sdk territory.)

(1) there was a USB device stack there more than two years ago, (2) there is no advantage to doing this for USB transfers.

> And now a question from my side: why put so much effort into such a well-defined and well-designed separation between the USB device stack and the UDC driver, if you don't let them be used on their own?

Certainly not for third-party layers, but to enforce consistent behavior and maintainability of the drivers and stack. Unfortunately, there is no clear separation between user and internal headers/interfaces in Zephyr, such as include/zephyr/uapi, which would make it clearer which interfaces are for users.

You provide no information as to why you cannot fix this in your stack where you interface with the UDC API.

2025-01-24 16:49 UTC, yperess approved these changes

2025-01-24 16:49 UTC, yperess commented
I run into these issues all the time. If it's in a header we need to make it compatible with C++ which means cast it.

2025-01-24 17:17 UTC, jfischer-no commented
> > (1) there was a USB device stack there more than two years ago
> 
> Which didn't have the necessary feature-set that we needed, but I shouldn't need to explain this any more than you did when creating the USB device_next stack.
> 
> > (2) there is no advantage to doing this for USB transfers
> 
> You are confused, the HID report sizes are calculated and used to populate the USB max packet size fields of the endpoint descriptors. Much less error-prone than having an independent definition of these descriptors, and having to remember to keep the two things in sync.

I am not, especially on nRF USB the maximum allowable interrupt data payload size is 64 bytes or less, so there is no real benefit of using smaller endpoint MPS and no bandwidth issues.

> 
> > You provide no information as to why you cannot fix this in your stack where you interface with the UDC API.
> 
> The issue that this patch is trying to fix is syntactic, I have no control over the C++ syntax rules. I can't not include this C header, because the header provides the UDC API types and functions.

You can add your own header as interface to the UDC API and do there what ever you want.

Also you commit message states:
"It would be nice if C warning was raised for these cases,
so they can be caught faster."
Implicit void pointer conversions are just fine in C and are widely used in Zephyr tree, because we write the code in C not c++. Please rework you commit message to reflect the issue you are facing, describing that the implicit pointer conversion in c++ is not possible.

2025-01-24 20:53 UTC, benedekkupper commented
> Please rework you commit message to reflect the issue you are facing, describing that the implicit pointer conversion in c++ is not possible.

Done, please review.

2025-01-24 21:45 UTC, henrikbrixandersen approved these changes

2025-01-27 12:27 UTC, jfischer-no approved these changes
Okay, but in general C++ limitations should not weaken our interfaces.

2025-01-27 16:14 UTC, merged

2025-01-27 16:16 UTC, kartben commented
@benedekkupper thanks so much for your patience! Glad this is now merged :)