samples: drivers: watchdog testing on stm32c031 nucleo board
zephyrproject-rtos/zephyr pull request #69502
Opened 2024-02-27 08:24 UTC by FRASTM

Add the nucleo_c031c6 target to run the samples/drivers/watchdog for iwdg and wwdg on the stm32c0 serie.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/69035

2024-02-27 12:26 UTC, FRASTM commented
Note that tests/drivers/watchdog/wdt_basic_api/ on the window watchdog 
exceeds the flash size of 32Kbytes
--> cannot `west build  -p auto -b nucleo_c031c6  tests/drivers/watchdog/wdt_basic_api/ -- -DDTC_OVERLAY_FILE="boards/stm32_wwdg.overlay"`

2024-02-27 14:22 UTC, martinjaeger submitted a review, later dismissed

2024-02-28 12:04 UTC, erwango requested changes

2024-02-28 14:21 UTC, FRASTM commented on tests/drivers/watchdog/wdt_basic_api/testcase.yaml
> +      - nucleo_c031c6
then removed

2024-02-28 16:57 UTC, martinjaeger approved these changes

2024-02-28 17:09 UTC, erwango approved these changes

2024-02-28 18:16 UTC, kartben approved these changes

2024-03-03 18:00 UTC, merged