kernel: mutex: Move assertions to syscall handler
zephyrproject-rtos/zephyr pull request #6950
Opened 2018-04-05 17:18 UTC by lpereira

Always ensure that the mutex owner is the current thread and that the
count is sane.

Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

2018-04-05 17:38 UTC, tyrantlizard77 approved these changes

2018-04-05 20:41 UTC, nashif approved these changes

2018-04-06 03:52 UTC, tyrantlizard77 requested changes
Actually --
the general pattern is to leave assertions where they are, just enforce them with checks in the handler.
That way people can assert correctness of supervisor-only code by enabling CONFIG_ASSERT.
Can you restore the asserts that were removed?

2018-04-06 18:52 UTC, tyrantlizard77 approved these changes

2018-04-06 18:52 UTC, merged