MAINTAINERS: Add tomi-font as modem subsys collaborator
zephyrproject-rtos/zephyr pull request #69601
Opened 2024-02-29 08:44 UTC by bjarki-trackunit

Add tomi-font as modem subsystem collaborator

2024-02-29 08:46 UTC, kartben approved these changes

2024-02-29 08:56 UTC, rlubos approved these changes

2024-02-29 09:19 UTC, jukkar approved these changes

2024-02-29 11:37 UTC, fabiobaltieri approved these changes

2024-02-29 14:55 UTC, MaureenHelm approved these changes

2024-03-01 13:59 UTC, rerickson1 approved these changes

2024-03-04 13:14 UTC, aescolar requested changes
@bjarki-trackunit  @tomi-font does not seem to be yet a Zephyr contributor overall(?)
can you please create a request (issue) for him to become a contributor?
Also @tomi-font needs to approve this PR himself.

2024-03-04 13:18 UTC, tomi-font commented
Unfortunately I cannot add myself as a reviewer. But here is my check mark: :white_check_mark:

2024-03-04 13:30 UTC, bjarki-trackunit commented
@aescolar Completely forgot about contributor nomination

Contributor nomination created #69761

2024-03-12 11:42 UTC, tomi-font approved these changes

2024-03-12 11:44 UTC, aescolar approved these changes

2024-03-12 11:45 UTC, merged