Bluetooth: Controller: Fix per adv interval value check
zephyrproject-rtos/zephyr pull request #69616
Opened 2024-02-29 14:11 UTC by Tronil

Invalid values should result in BT_HCI_ERR_INVALID_PARAM

The interval check should only fail with
BT_HCI_ERR_UNSUPP_FEATURE_PARAM_VAL if the requested range cannot be fulfilled by the controller (ie. there is no overlap with the supported range)

Fixes EBQ tests HCI/DDI/BI-53-C through HCI/DDI/BI-61-C and HCI/CCO/BI-64-C

2024-02-29 20:26 UTC, cvinayak requested changes
Minor change requested, otherwise LGTM.

2024-02-29 20:26 UTC, cvinayak commented on subsys/bluetooth/controller/hci/hci.c
> +		}
Insert a blank line.

```suggestion

		if (max_interval > CONFIG_BT_CTLR_ADV_PERIODIC_INTERVAL_MAX) {
			max_interval = CONFIG_BT_CTLR_ADV_PERIODIC_INTERVAL_MAX;
		}
```

2024-03-01 08:06 UTC, Tronil commented on subsys/bluetooth/controller/hci/hci.c
> +		}
Done

2024-03-01 14:40 UTC, cvinayak approved these changes

2024-03-07 07:26 UTC, kruithofa approved these changes

2024-03-07 10:58 UTC, merged