boards: sheilds: Add RaspberryPi Pico to UNO FlexyPin Adapter
zephyrproject-rtos/zephyr pull request #69716
Opened 2024-03-03 09:29 UTC by soburi

Add "RaspberryPi Pico to UNO FlexyPin Adapter".
It is a converter-PCB to Arduino UNO form-factor
from Raspberry Pi Pico that is released in Open Source Hardware.

https://www.solder.party/docs/flexypin/adapters/#raspberry-pi-pico-to-uno-flexypin-adapter

2024-03-12 08:00 UTC, erwango requested changes

2024-03-12 10:00 UTC, erwango approved these changes

2024-03-26 07:07 UTC, soburi commented
@kartben 

Could you take a look, please?

2024-04-08 07:08 UTC, fabiobaltieri approved these changes

2024-04-08 13:27 UTC, nashif approved these changes

2024-04-08 13:28 UTC, merged