x86: revert removing soc.h from atom soc
zephyrproject-rtos/zephyr pull request #69758
Opened 2024-03-04 12:59 UTC by nashif

This was part of the mega hwmv2 commit. Looks like hpet drivers heavily
relies on soc.h. Reverting this for now while we look for a proper fix
and remove reliance on soc.h for drivers.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2024-03-04 13:39 UTC, jhedberg commented on subsys/bluetooth/host/hci_core.c
> +#include <soc.h>
This is a bit surprising. What does hci_core.c need this for? I'd have expected to see reports of build failures, etc if it was absolutely necessary there.

2024-03-04 13:55 UTC, gmarull commented on subsys/bluetooth/host/hci_core.c
> +#include <soc.h>
soc.h should not be on a subsys level file

2024-03-04 13:56 UTC, gmarull requested changes, later dismissed

2024-03-04 13:56 UTC, gmarull commented on soc/intel/atom/soc.h
> +#endif
none of these seem to be required by this file, only toolchain.h for ARG_UNUSED?

2024-03-04 14:04 UTC, nashif commented
Guys, I am reverting a commit with this, I do not want to go through partial fixes, will come back to this and give it another go, but this is blocking and breaking few platforms and I do not want to be selective in the revert. The commit in question:

[`ffd1c15` (#69039)](https://github.com/zephyrproject-rtos/zephyr/pull/69039/commits/ffd1c1566c6177d3f1570a1a8545c44293da0e87)

2024-03-04 15:29 UTC, teburd approved these changes
Simple revert for fixing issues, seems fine

2024-03-04 15:53 UTC, jhedberg approved these changes

2024-03-04 19:07 UTC, merged

2024-09-19 02:20 UTC, ycsin commented
I'm working on #78670 and trying to incorporate test into `samples/subsys/shell/shell_module` and found that this doesn't build on the `qemu_riscv64`, is there an issue tracking this?