drivers: usb: device: fix Rx FIFO min size
zephyrproject-rtos/zephyr pull request #69897
Opened 2024-03-07 08:43 UTC by Desvauxm-st

the FIFO Rx need to have a minimum memory to works but the current value of 160 byte must be
revised downwards because STM32F4xx no longer
works correctly

2024-03-07 10:38 UTC, loicpoulain approved these changes

2024-03-07 10:52 UTC, tmon-nordic requested changes
Could you please explain how exactly this change fixes the issue? Because to the outsiders the commit message doesn't explain anything and it all just seems like changing one arbitrary number to another arbitrary number.

2024-03-07 13:09 UTC, Desvauxm-st commented
@tmon-nordic
I don't know how to calculate this number.
what I know tangibly is that:

The smallest USB data RAM size available on the STM is 1.25 kb on the STM32F4 (OTG_FS).
we decreased the value of USB_FIFO_RX_MIN until samples/subsys/usb/console worked on STM32F4.

we also took care to test the STM32F4, STM32F7, STM32H7, STM32U5 types with samples/subsys/usb/cdc_acm and samples/subsys/usb/console with USB_FIFO_RX_MIN set to 120

2024-03-07 15:07 UTC, loicpoulain commented
The documentation is not really clear or accurate about that, but the RX FiFo configuration is in word unit (4-bytes), and it should be able to store the largest packet packet + some extra space for status information (1 word). The documentation says:
`A minimum space of (Largest Packet Size / 4) + 1 must be allocated to receive packets` 
but per experiment, anything under 64 words (256bytes) does not work reliably, even if mps is 64 bytes...

So 120 'looks' fine for full-speed device, but it indeed deserve clarification in the commit message.

2024-03-18 11:11 UTC, tmon-nordic requested changes
When referring to commits in commit message do not paste github link but rather do the first 12 hash characters followed by ("commit title"), in this case:
```
1204aa25c827 ("drivers: usb: device: fix Rx FIFO min size")
```
This allows easy navigation in multiple tools like gitk or even in GitHub Web UI.

2024-03-21 13:09 UTC, Desvauxm-st commented
OK

2024-03-21 13:26 UTC, erwango approved these changes

2024-03-28 08:13 UTC, arbrauns commented
I doubt the bug you saw was due to this arbitrary value being too large, but rather that it was #70789, fixed by #70795.

2024-04-03 07:27 UTC, erwango commented
Superseded by https://github.com/zephyrproject-rtos/zephyr/pull/70795

2024-04-03 07:27 UTC, closed without merging