gdbstub: Ignore indexing warning with -Warray-bounds
zephyrproject-rtos/zephyr pull request #69930
Opened 2024-03-07 15:31 UTC by GRobertZieba

The current implementation can raise a warning as the compiler sees
an attempt to index an array with a size of zero. This can be fixed by
giving `gdb_mem_num_regions` a default value of zero, but this gets
flagged by CI checks. Disable the warning around the array access.

2024-03-07 16:28 UTC, dcpleung requested changes

2024-03-07 16:28 UTC, dcpleung commented on subsys/debug/gdbstub.c
> +__weak const size_t gdb_mem_num_regions;
Please revert the change on this line.

2024-03-07 21:27 UTC, dcpleung commented on subsys/debug/gdbstub.c
>  /* Empty memory region array */
Also need to update this comment to reflect the changes.

2024-03-07 21:28 UTC, dcpleung commented
Hm... I have to ask... which compiler complains about this? The Zephyr SDK seems to be okay with this.

2024-03-07 23:08 UTC, GRobertZieba commented
I'm encountering issues with gcc, though you may need to have `-Werror=array-bounds` enabled. The exact errors are of the form:
```
zephyr/main/subsys/debug/gdbstub.c:67:21: error: array subscript idx is outside array bounds of 'const struct gdb_mem_region[0]' [-Werror=array-bounds]
```

I did notice that initializing `gdb_mem_num_regions` to zero also fixes this so I'd be open to making that change instead.

2024-03-07 23:38 UTC, dcpleung commented
I think it is better to do this
```
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif

__weak const struct gdb_mem_region gdb_mem_region_array[0];

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
```, instead of forcing the whole memory to be accessible, because of the side effect of having the whole memory accessible.

2024-03-11 16:07 UTC, GRobertZieba commented
What about leaving the array as `[0]`, but changing the region count to `__weak const size_t gdb_mem_num_regions = 0`? That resolves the warning and avoids having to test for specific compiler features.

2024-03-11 16:26 UTC, dcpleung commented
You can try and see. Though I remember some compilers would complain about not setting 0 on global variables as they should be 0 at boot.

2024-03-12 22:09 UTC, dcpleung approved these changes

2024-03-27 13:58 UTC, nashif approved these changes

2024-03-27 13:58 UTC, merged