doc/develop api_lifecycle: Mention adding the arch review label
zephyrproject-rtos/zephyr pull request #70033
Opened 2024-03-11 11:16 UTC by aescolar

For breaking API changes, let's mention explicity the PR should be labelled with the "Architecture Review" label, as that is the one we base the automation on.
As otherwise it is not clear enough for developers that they should add it, and without it (and the automation surrounding it), it is too easy for a PR to be merged by mistake.

2024-03-11 11:20 UTC, henrikbrixandersen requested changes
Actually, it should be added to the Arch WG project instead.

2024-03-11 11:48 UTC, fabiobaltieri commented
Yeah it's automatic.
No I don't have permissions to remove it now :-) sorry @carlescufi

2024-03-11 11:48 UTC, fabiobaltieri approved these changes

2024-03-11 11:57 UTC, carlescufi requested changes
I suggest we focus on the project, not the label. This is because one cad add the issue to the project without adding the label

2024-03-11 11:58 UTC, henrikbrixandersen approved these changes
If the presence of the label automatically adds the issue/PR to the Arch WG project, fine by me.

2024-03-11 19:22 UTC, carlescufi approved these changes

2024-03-12 10:31 UTC, kartben approved these changes

2024-03-12 13:32 UTC, MaureenHelm approved these changes

2024-03-12 13:36 UTC, nashif approved these changes

2024-03-13 16:45 UTC, merged