stm32: ns: Clean up and fixes
zephyrproject-rtos/zephyr pull request #70121
Opened 2024-03-12 17:12 UTC by erwango

2024-03-13 08:39 UTC, nordicjm approved these changes, later dismissed

2024-03-14 08:20 UTC, tejlmand approved these changes, later dismissed

2024-03-15 14:38 UTC, gautierg-st approved these changes, later dismissed

2024-03-19 13:26 UTC, nordicjm requested changes

2024-03-19 13:26 UTC, nordicjm commented on soc/st/stm32/Kconfig
> +	  enable building with TF-M as the Secure Execution Environment.
This would go in `Kconfig.defconfig`

2024-03-19 13:26 UTC, nordicjm commented on soc/st/stm32/Kconfig
> +	  enable building with TF-M as the Secure Execution Environment.
And no help text

2024-03-22 07:22 UTC, nordicjm commented on boards/st/nucleo_l552ze_q/nucleo_l552ze_q_stm32l552xx_ns.dts
> +		};
secondary

2024-03-22 07:29 UTC, erwango commented on boards/st/nucleo_l552ze_q/nucleo_l552ze_q_stm32l552xx_ns.dts
> +		};
Good catch, thanks

2024-03-22 07:47 UTC, nordicjm approved these changes

2024-03-22 08:42 UTC, gautierg-st approved these changes

2024-03-22 09:23 UTC, merged