fixes #69198 esp32 dac incorrect clock init
zephyrproject-rtos/zephyr pull request #70296
Opened 2024-03-15 13:42 UTC by ku3mich

2024-03-23 05:56 UTC, uLipe approved these changes

2024-03-23 22:52 UTC, martinjaeger requested changes
Hello @ku3mich. Thanks for your PR.

Please add a PR description and squash both commits into a single one. Also see the links to the guidelines posted above.

2024-04-01 13:06 UTC, sylvioalves approved these changes

2024-04-01 13:07 UTC, sylvioalves commented
@ku3mich do you intend to update this PR?

2024-06-16 00:30 UTC, closed without merging