boards: use unique names
zephyrproject-rtos/zephyr pull request #70294
Opened 2024-03-15 13:02 UTC by wsipak

The pretty names specified in the YAML files of each board are not unique.
Let's rename them.

2024-03-15 16:10 UTC, ifyall submitted a review, later dismissed

2024-03-23 05:56 UTC, uLipe approved these changes, later dismissed

2024-03-25 10:04 UTC, fabiobaltieri commented
hey this needs a rebase

2024-03-25 11:50 UTC, wsipak commented
@fabiobaltieri Thanks, I've rebased this. Could you take a look again?

Also @ifyall and @uLipe could you take a look again?

2024-03-25 11:53 UTC, fabiobaltieri submitted a review, later dismissed

2024-03-25 11:55 UTC, nordicjm requested changes
Agree with changes but needs to be made after https://github.com/zephyrproject-rtos/zephyr/pull/70548 is merged (temp. block)

2024-04-15 23:31 UTC, ifyall approved these changes, later dismissed

2024-04-16 00:18 UTC, sylvioalves approved these changes, later dismissed

2024-05-09 08:59 UTC, nordicjm approved these changes

2024-05-09 09:38 UTC, sylvioalves approved these changes

2024-05-09 21:44 UTC, nashif approved these changes

2024-05-12 16:01 UTC, fabiobaltieri approved these changes

2024-05-13 07:16 UTC, ruuddw approved these changes

2024-05-13 07:45 UTC, merged