mgmt: mcumgr: Add Kconfig option to manage SMP service registration
zephyrproject-rtos/zephyr pull request #70381
Opened 2024-03-18 15:48 UTC by mkapala-nordic

Added the CONFIG_MCUMGR_TRANSPORT_BT_DYNAMIC_SVC_REGISTRATION Kconfig option to manage how the SMP service should be registered. By default the SMP service must be registered at runtime. If this Kconfig option is disabled, the SMP service is statically defined and registered.

This change allows to opt out of using the CONFIG_BT_GATT_DYNAMIC_DB Kconfig option and as a result, lower the memory usage.

CC: @kapi-no @MarekPieta @zycz

2024-03-19 07:14 UTC, nordicjm requested changes
Changes are OK. Compliance needs fixing, replace the 8-space blocks with tabs

2024-03-19 07:14 UTC, nordicjm commented on subsys/mgmt/mcumgr/transport/Kconfig.bluetooth
> +	  When enabled, the SMP service must be registred at runtime.
*registered

2024-03-19 08:50 UTC, kapi-no commented
Please add the CI build configuration for the non-default value of the `MCUMGR_TRANSPORT_BT_DYNAMIC_SVC_REGISTRATION` Kconfig:

`CONFIG_MCUMGR_TRANSPORT_BT_DYNAMIC_SVC_REGISTRATION=n`

It should ensure that both variants compile correctly.

(SMP SVR sample should be a proper place to add this configuration.)

2024-03-19 09:28 UTC, MarekPieta approved these changes

2024-03-19 09:28 UTC, MarekPieta commented on subsys/mgmt/mcumgr/transport/Kconfig.bluetooth
> +	  When enabled, the SMP service must be registred at runtime.
`is automatically registered during boot and then can be dynamically registered/unregistered using dedicated API.`
(application actually dose not need to register the service on boot)

2024-03-19 10:33 UTC, MarekPieta approved these changes

2024-03-19 10:43 UTC, kapi-no approved these changes

2024-03-19 18:31 UTC, de-nordic approved these changes

2024-03-20 10:40 UTC, nordicjm approved these changes

2024-03-20 16:27 UTC, merged