doc: security: Add information about Open Security Training
zephyrproject-rtos/zephyr pull request #70391
Opened 2024-03-18 19:56 UTC by ceolin

Add information and links for open source security training.

2024-03-20 17:04 UTC, ceolin commented
@dleach02 @d3zd3z ping review :)

2024-03-21 21:38 UTC, kartben requested changes
added a blank line to make it a different paragraph + proposed wording improvements. Thanks!

2024-03-25 17:10 UTC, ceolin reviewed
Thanks @kartben. Would you mind take a look again ?

2024-03-25 17:11 UTC, kartben approved these changes

2024-03-26 17:11 UTC, d3zd3z approved these changes

2024-03-26 20:16 UTC, merged