cmake: add --dirty flag to APP_BUILD_VERSION command
zephyrproject-rtos/zephyr pull request #70546
Opened 2024-03-21 09:44 UTC by hakonfam

Without this it is possible to make the incorrect assumption that the repo was in a clean state when the code was compiled. With this flag it is clear when a build is dirty or not.

2024-03-21 09:47 UTC, nordicjm approved these changes

2024-03-21 13:11 UTC, tejlmand requested changes
i'm personally in favor of applying `--dirty`\* if it can be done in a **safe way / without having surprising edge-cases**.

I don't have time atm to verify that no edge-cases exists, so would need some assurances that this doesn't have a risk of not presenting `--dirty` when a build is indeed dirty.


But please also take a look at other use-cases described here:
https://github.com/zephyrproject-rtos/zephyr/pull/13608#pullrequestreview-206725920
https://github.com/zephyrproject-rtos/zephyr/issues/39503#issuecomment-961686122

So as minimum we should update documentation and highlight how one can make re-builds which doesn't change the version between stashes.


\* = Ref: https://github.com/zephyrproject-rtos/zephyr/issues/39503
> **Additional context**
Would be nice if boot banner also contains information whether the repository is considered dirty, git describe --dirty.
But that can be seen as an enhancement.

2024-03-21 13:13 UTC, tejlmand commented
I guess this PR should be marked as fixing: https://github.com/zephyrproject-rtos/zephyr/issues/70509

2024-05-29 16:28 UTC, FARLY7 commented
I am in favour of this change.

Can I also propose that the `--tags` flag be added to `git describe`? Without it, only _annotated_ tags are included, not _lightweight_ tags. I don't think this is desirable, as not all tags require annotation. We do not annotate tags as the tag name itself is enough to denote it as a release.

Without this change, the VERSION file route is also unusable for us due to prior tags not including annotation.

I also don't think the VERSION route correctly follows the [SemVer](https://semver.org/) standard (not sure if this is intentional or not). `APP_BUILD_VERSION` should use a `+`, not `-` before the git commit has (and planned dirty annotation) to denote additional build metadata that is not part of the version calculation.

2024-08-12 00:30 UTC, closed without merging