Add bbram driver for ENE KB1200
zephyrproject-rtos/zephyr pull request #70653
Opened 2024-03-25 07:47 UTC by ene-steven

Add bbram driver for ENE KB1200

2024-04-08 03:38 UTC, yperess approved these changes, later dismissed

2024-04-29 14:32 UTC, decsny commented on dts/arm/ene/kb1200.dtsi
> +			bbram-size = <124>;
what is the difference between `bbram-size` and the size cell of the `reg` property here? I see the value is slightly different but similar

2024-04-29 14:32 UTC, decsny requested changes

2024-04-29 14:32 UTC, decsny commented on dts/bindings/memory-controllers/ene,kb1200-bbram.yaml
> +  bbram-size:
this needs a description

2024-04-29 14:37 UTC, henrikbrixandersen requested changes, later dismissed
Please split this into multiple PRs, each adding one driver.  

This keeps the PR size manageable. Note that each driver subsystem in Zephyr has separate maintainers, so putting all of this into one big PR will make it really difficult to get it reviewed and approved.

2024-04-29 14:40 UTC, decsny commented
also, how is this going to be tested, I don't see any twister yaml changes

2024-04-30 13:32 UTC, decsny commented on boards/ene/kb1200_evb/kb1200_evb.yaml
> +  - tach
I don't think "tach" is a real twister tag

2024-05-03 16:46 UTC, decsny submitted a review, later dismissed

2024-05-28 17:28 UTC, yperess requested changes

2024-05-28 17:28 UTC, yperess commented on drivers/bbram/bbram_ene_kb1200.c
> +		.vbat_ptr = (struct vbat_regs *)DT_INST_REG_ADDR(inst),                            \
Is the size not configurable?

2024-05-29 01:42 UTC, ene-steven commented on drivers/bbram/bbram_ene_kb1200.c
> +		.vbat_ptr = (struct vbat_regs *)DT_INST_REG_ADDR(inst),                            \
Yes, the size is fixed.

2024-08-29 00:30 UTC, closed without merging