wifi: shell: series of code refactor
zephyrproject-rtos/zephyr pull request #70676
Opened 2024-03-25 13:39 UTC by ndrs-pst

This PR aims to refactor `wifi_shell.c` with the following commits:
- Streamlining local variable initializations
- Applying `struct option` as `static const`
- Adopting `getopt_state` for safer `optarg` access

2024-03-25 16:20 UTC, krish2718 approved these changes

2024-03-26 08:49 UTC, rlubos approved these changes

2024-03-26 08:58 UTC, jukkar approved these changes

2024-03-26 10:34 UTC, jukkar requested changes
Missed this earlier, please change the commit subject to `net: wifi: shell: ....`

2024-03-26 18:29 UTC, ndrs-pst commented
> Missed this earlier, please change the commit subject to `net: wifi: shell: ....`

Just address your comment and push the new commit subject.

2024-03-26 21:16 UTC, jukkar approved these changes
Thanks!

2024-03-27 14:33 UTC, merged