net: http: Timeout the req only if receiving nothing
zephyrproject-rtos/zephyr pull request #70816
Opened 2024-03-28 07:29 UTC by jukkar

If we receive some data from the server but not actual data, then return 0 from http_client_req() like we used to do earlier before the commit 28a46c0f60aba41f7f0d099a93dfad80436a6d97

2024-03-28 07:54 UTC, nordicjm approved these changes

2024-03-29 00:35 UTC, glarsennordic requested changes
This does not actually restore the desired behavior -- We want to distinguish between unresponsive server, and FINACK with zero TLS payload. So there will not be HTTP headers either. 

I've been doing some digging -- it turns out `http_wait_data` switched to polling at some point:
https://github.com/zephyrproject-rtos/zephyr/pull/54009/commits/7f6b06cbe2d10e3baf9e2acacc95f73fb994c8b9


It would seem that commit incorrectly made `http_wait_data` treat data timeout the same way NULL response from server is handled:
Notice that `else if (fds[0].revents & ZSOCK_POLLHUP)` and `if (ret == 0)` both result in `goto finalize_data`, which triggers `http_data_final_null_resp`.

IE, empty data due to timeout is being treated identically to empty data due to FINACK, and that is not correct.

It results in the two being now indistinguishable, hence the issues you are encountering.

The correct fix would be to restore the distinguishability between FINACK without payload and unresponsive server


I'll look into that tomorrow if you don't beat me to it

2024-03-29 19:06 UTC, glarsennordic commented
It gets worse -- Even my original PR had a mistake 🤦

Check it out:

https://github.com/zephyrproject-rtos/zephyr/issues/42988

After that PR, if the HTTP server closes the TLS socket mid-way through transmission, it will result in HTTP status 0 (which was not the original behavior, I believe).

So now that makes ***three*** commits with unintentional changes to how `http_client` handles unexpected FINACK 😅

I am working on a PR of my own which should rectify all of this. But it does raise the question:

What ***should*** we do if the HTTP server raises finack after sending a partial (rather than NULL) HTTP response? I'm thinking this should surely result in an error, right? NULL response was already an obscure behavior - I cannot think of any good reason for an invalid response to be sent.

To be fair, to even do this you'd have to essentially hijack the TLS socket of your HTTP server, or the server would have to crash, or some other extremely unexpected thing would have to happen, making this edge case extremely rare.

I'll proceed under the assumption that returning an error is reasonable in that case

2024-04-02 08:26 UTC, jukkar commented
Closing this in favor of https://github.com/zephyrproject-rtos/zephyr/pull/70911

2024-04-02 08:26 UTC, closed without merging