doc: releases: release-notes: 3.7: add informations on dhcpv4 options
zephyrproject-rtos/zephyr pull request #70840
Opened 2024-03-28 11:52 UTC by maass-hamburg

Add release notes for:

https://github.com/zephyrproject-rtos/zephyr/pull/68767
https://github.com/zephyrproject-rtos/zephyr/pull/69036
https://github.com/zephyrproject-rtos/zephyr/pull/69328
https://github.com/zephyrproject-rtos/zephyr/pull/69476

2024-03-28 11:58 UTC, jukkar approved these changes, later dismissed

2024-03-28 12:18 UTC, rlubos submitted a review, later dismissed
Thanks

2024-03-28 12:19 UTC, kartben requested changes

2024-03-28 12:47 UTC, maass-hamburg commented on doc/releases/release-notes-3.7.rst
> +  * The NTP server from the DHCPv4 option can now be used to set the system time.
for NTP it is enabled by default, if `CONFIG_NET_CONFIG_CLOCK_SNTP_INIT` is enabled

2024-03-28 12:49 UTC, kartben approved these changes

2024-03-28 12:54 UTC, rlubos approved these changes

2024-03-28 12:59 UTC, jukkar approved these changes

2024-03-29 11:04 UTC, nashif approved these changes

2024-03-29 11:15 UTC, merged