docs: Bluetooth: Add sections on GTBS and GMCS
zephyrproject-rtos/zephyr pull request #70884
Opened 2024-03-29 09:08 UTC by Thalley

Since GTBS and GMCS in both spec definitions and
in the Zephyr implemenation are notably different, it is worthwhile pointing these out in the documentation for content control.

2024-04-03 13:39 UTC, kruithofa requested changes
Some minor typos

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +This means that a GTBS instance represent one or more telephone bearers.
```suggestion
This means that a GTBS instance represents one or more telephone bearers.
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +such the default Call application on a smartphone,
```suggestion
such as the default Call application on a smartphone,
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +Similarly the supported URIs for each bearer at also made into a union in GTBS, and when placing
```suggestion
Similarly the supported URIs for each bearer are also made into a union in GTBS, and when placing
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +a call using the GTBS the server will pick the most suited bearer depending on the UCI.
```suggestion
a call using the GTBS the server will pick the most suited bearer depending on the URI.
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +The MCS spec defineds GMCS as
```suggestion
The MCS spec defines GMCS as
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +Thus if a device have multiple MCS instances,
```suggestion
Thus if a device has multiple MCS instances,
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +and currently only supports either instanciating a single instance that can either be a MCS or GMCS.
```suggestion
and currently only supports instantiating a single instance that can be either an MCS or GMCS.
```

2024-04-03 13:39 UTC, kruithofa commented on doc/connectivity/bluetooth/bluetooth-le-audio-arch.rst
> +This means that the implementation is neither complete not spec-compliant.
```suggestion
This means that the implementation is neither complete nor spec-compliant.
```

2024-04-05 12:03 UTC, kruithofa approved these changes

2024-04-05 13:33 UTC, jhedberg approved these changes

2024-04-05 13:46 UTC, merged