samples: subsys: task_wdt on the IWDG of the stm32f4
zephyrproject-rtos/zephyr pull request #70891
Opened 2024-03-29 10:19 UTC by FRASTM

Run the sample on the IWDG of stm32f4 nucleo boards instead of WWDG because the APB1 prescaler cannot
set a WWDG input clock source matching the wd timeout

when running on the WWDG:
```
*** Booting Zephyr OS build v3.6.0-443-g78c40fe31bf2 ***                                                                                               
Task watchdog sample application.                                                                                                                       
[00:00:00.008,000] <dbg> wdt_wwdg_stm32: wwdg_stm32_install_timeout: prescaler: 8                                                                       
[00:00:00.015,000] <dbg> wdt_wwdg_stm32: wwdg_stm32_install_timeout: Desired WDT: 700000 us                                                             
[00:00:00.024,000] <dbg> wdt_wwdg_stm32: wwdg_stm32_install_timeout: Set WDT:     43690 us                                                              
[00:00:00.033,000] <err> task_wdt: hw_wdt install timeout failed: -22                                                                                   
task wdt init failure: -22     
``` 

When running on the IWDG:
```
*** Booting Zephyr OS build v3.6.0-1434-g0301ae65ee9d ***                                                                                               
Task watchdog sample application.                                                                                                                       
Main thread still alive...                                                                                                                              
Control thread started.                                                                                                                                 
Main thread still alive...                                                                                                                              
Main thread still alive...                                                                                                                              
Main thread still alive...                                                                                                                              
Control thread getting stuck...                                                                                                                         
Task watchdog channel 1 callback, thread: control                                                                                                       
Resetting device...�*** Booting Zephyr OS build v3.6.0-1434-g0301ae65ee9d ***                                                                           

```

2024-04-04 10:00 UTC, erwango submitted a review, later dismissed

2024-04-04 10:23 UTC, martinjaeger submitted a review, later dismissed

2024-04-10 13:55 UTC, nordic-segl approved these changes

2024-04-11 06:21 UTC, kartben requested changes

2024-04-11 06:21 UTC, kartben commented on samples/subsys/task_wdt/boards/nucleo_f401re.overlay
> + * then the sample is running on the IWDG
```suggestion
 * when the sample is running on the IWDG
```

2024-04-11 06:21 UTC, kartben commented on samples/subsys/task_wdt/boards/nucleo_f411re.overlay
> + * then the sample is running on the IWDG
```suggestion
 * when the sample is running on the IWDG
```

2024-04-11 07:40 UTC, FRASTM commented
Changing comment and rebase on ba90f160b9865530e6b8d66bbc23d024849a7c9c

2024-04-11 07:42 UTC, kartben submitted a review, later dismissed

2024-04-11 08:00 UTC, nordic-segl commented
I'm bit confused with the comments. Isn't that WWDG can't be used due to APB1 prescaler values. Thus, the sample must be using IWDG.
???

2024-04-30 10:03 UTC, kartben commented
> I'm bit confused with the comments. Isn't that WWDG can't be used due to APB1 prescaler values. Thus, the sample must be using IWDG. ???

@FRASTM can you help clarify?

2024-05-30 12:30 UTC, kartben commented
ping @FRASTM

2024-06-14 13:22 UTC, FRASTM commented
rebase on d45605e6a3dfe68e43207d15e3bfc003cbfaa72f
Clarify the comment

2024-06-14 13:23 UTC, kartben approved these changes

2024-06-14 13:24 UTC, FRASTM commented
> > I'm bit confused with the comments. Isn't that WWDG can't be used due to APB1 prescaler values. Thus, the sample must be using IWDG. ???
> 
> @FRASTM can you help clarify?

For stm32F401 and stm32F411, we decide to run the sample on the IWDG (not on WWDG because of its clock freq)

2024-06-14 13:57 UTC, erwango approved these changes

2024-06-14 17:32 UTC, martinjaeger approved these changes

2024-06-14 17:34 UTC, merged