west: jlink: flash add progress bar
zephyrproject-rtos/zephyr pull request #71194
Opened 2024-04-07 11:10 UTC by PetervdPerk-NXP

When flashing with a jlink probe using `west flash` you don't get feedback on the process.

This PR adds a progress bar and detects if the contents already matches.

![ezgif-2-a13c98022b](https://github.com/zephyrproject-rtos/zephyr/assets/57130844/f8906e66-b973-4e57-b3c7-37319f540bfe)

2024-04-07 14:39 UTC, bperseghetti submitted a review, later dismissed

2024-04-08 06:34 UTC, fabiobaltieri commented
There's few potential issues I see with this:
- adding a new python dependency to the jlink flasher, going to break few setups, it's understandable for basic functionalities but this is just a fancy UI, bare minimum it should be optional and only kick in if the library is already installed
- screen scraping the JLink output does not strike me as a particularly good idea, the command does not really have an output meant to be stable, this is asking for troubles down the road
- the UI of this is, in my opinion, not great. On a bigger terminal it wipes the screen and leaves a long gap in he center for the sake of pinning the bar on the bottom, if the execution is quick (as it is on small devices) it just looks a bit broken

Sorry I realize that quite some tedious work went into this, curious to hear what the others think as well.

2024-04-08 08:28 UTC, gmarull requested changes
I think runners should be as transparent as possible, ie, just print what JLink gives us. It should be JLink that provides a nice UI. Also, as said, adding new dependencies to the base install just for a runner seems too much.

2024-04-08 09:05 UTC, PetervdPerk-NXP commented
> adding a new python dependency to the jlink flasher, going to break few setups, it's understandable for basic functionalities but this is just a fancy UI, bare minimum it should be optional and only kick in if the library is already installed

Good point, I guess we could put the dependency behind a `try import` and if that fails just fallback to the old behaviour.

> screen scraping the JLink output does not strike me as a particularly good idea, the command does not really have an output meant to be stable, this is asking for troubles down the road

I agree, It's hard to make it stable, but the intend is that using regular expressions the worst case what could happen with an incompatibility is that the bars don't show up.

> the UI of this is, in my opinion, not great. On a bigger terminal it wipes the screen and leaves a long gap in he center for the sake of pinning the bar on the bottom, if the execution is quick (as it is on small devices) it just looks a bit broken

Happy to switch to another progress bar library that doesn't put the cursor to the bottom.

> I think runners should be as transparent as possible, ie, just print what JLink gives us. It should be JLink that provides a nice UI. Also, as said, adding new dependencies to the base install just for a runner seems too much.

Indeed that could also be an approach right now `west flash` is quite opaque and you just don't know what's going on. For example when flashing a big target 64MB you don't know how far the progress is or when you get an error you don't know what's going on.

Redirecting stdout by default from `west flash` wouldn't be bad idea either.

2024-04-08 13:05 UTC, fabiobaltieri commented
> Redirecting stdout by default from `west flash` wouldn't be bad idea either.

How about a runner option to do that? Then one could enable it for the specific board, I see how it could be useful if your project ends up with a multi-MB image.

2024-04-09 12:40 UTC, PetervdPerk-NXP commented
@fabiobaltieri Swapped the bar implementation with another one that doesn't wipe the screen.
Also added `try import` for the dependency I pull in, so it isn't mandatory with a fallback to the old silent output method.

2024-04-20 02:11 UTC, PetervdPerk-NXP commented on .github/workflows/west_cmds.yml
> +        pip3 install pytest west pyelftools canopen alive-progress natsort progress mypy intelhex psutil ply pyserial
I've looked at `progress` but it's api isn't that great and hasn't been maintained since 2021.
https://pypi.org/project/progress/

2024-04-20 02:47 UTC, PetervdPerk-NXP commented
@fabiobaltieri  thanks for the remark `progress` already being installed, I've modified the code to use that instead.

@gmarull as of now we're not pulling any new dependences beyond the existing base install.

2024-04-20 02:54 UTC, fabiobaltieri commented
ok couple more concerns:
- should there be a runner option to go back to just executing the command? for stuff like batch processing or as quick workaround if something break with screenscraping jlink (I know it should fall back, but just in case)
- how does this look if the output is not a tty? (also for batch processing, it should probably not do the progressbar or do something logfile friendly)

2024-04-20 02:59 UTC, PetervdPerk-NXP commented
> should there be a runner option to go back to just executing the command? for stuff like batch processing or as quick workaround if something break with screenscraping jlink (I know it should fall back, but just in case)

A generalized runner option or environment variable wouldn't be a bad idea. I might port the progress as well to pyocd because there typically flash algorithms are quite slow

> how does this look if the output is not a tty? (also for batch processing, it should probably not do the progressbar or do something logfile friendly)
`progress` uses VT100 sequences so you would get every percentage update and the cursor command in plain text. It shouldn't fail though.

2024-06-07 17:49 UTC, decsny commented
bump

2024-06-14 18:16 UTC, decsny commented
@fabiobaltieri @PetervdPerk-NXP what is the state of this PR? can we get it into LTS?

2024-06-14 19:09 UTC, bperseghetti approved these changes, later dismissed

2024-06-14 19:09 UTC, PetervdPerk-NXP commented
It's all okay from my end.

2024-06-14 20:50 UTC, decsny approved these changes, later dismissed

2024-08-05 14:59 UTC, kartben commented
@carlescufi can you help land this?

2024-08-05 14:59 UTC, kartben commented on scripts/west_commands/runners/jlink.py
> +                if c[0] == 0x8:
why not \b ?
```suggestion
                if c[0] == b'\b':
```

2024-08-05 14:59 UTC, kartben commented on scripts/west_commands/runners/jlink.py
> +                                if c[0] == 0x8:
ditto

2024-08-05 16:01 UTC, kartben approved these changes

2024-08-05 16:02 UTC, bperseghetti approved these changes

2024-08-06 08:01 UTC, gmarull requested changes
This feature should be added as an option, there can be users relying on the standard JLink output.

2024-08-06 08:03 UTC, PetervdPerk-NXP commented
> This feature should be added as an option, there can be users relying on the standard JLink output.

But there's no standard output there's only the process return code.

2024-08-06 08:08 UTC, gmarull commented
> > This feature should be added as an option, there can be users relying on the standard JLink output.
> 
> But there's no standard output there's only the process return code.

Then keep it silent by default, show progress if enabled. What if I prefer non-fancy bars on my terminal?

2024-08-06 08:11 UTC, PetervdPerk-NXP commented
> Then keep it silent by default, show progress if enabled. What if I prefer non-fancy bars on my terminal?

So `west build` CMake progress should now also be silent?
There's always pipe to /dev/null.

2024-08-22 07:04 UTC, gmarull commented
my request: make this an opt-in feature, not default.

2024-08-22 07:32 UTC, henrikbrixandersen requested changes
> my request: make this an opt-in feature, not default.

I agree with this. We use the J-Link runner in our downstream CI, where the addition of such a progress bar will mess up the logs.

2024-08-22 07:46 UTC, pdgendt commented
How about a `west` config option?

```shell
$ west config runners.jlink-progressbar true
```

2024-08-22 14:57 UTC, PetervdPerk-NXP commented
I'm curious what's up with the consensus that a progress bar would screw up your logs. I would say it's opposite you would see more information in your logs i.e. failing partway. 
@henrikbrixandersen  would you be able to try this PR on your CI and actually report what would be wrong then?
Also the canopen runner is also running a progress bar without any problems
https://github.com/zephyrproject-rtos/zephyr/blob/65051c8a242e4bb5dd2c0625756d468c716b4616/scripts/west_commands/runners/canopen_program.py#L15

2024-08-22 16:30 UTC, nordicjm commented
Fine with this being added but as others have said, opt in, not opt out - do not want to see this at all on my machine, do not want to have to deal with this in CI.

2024-11-06 00:33 UTC, closed without merging