net: ipv6: Fix crash from double free of fragment
zephyrproject-rtos/zephyr pull request #7124
Opened 2018-04-19 14:16 UTC by rmstoi

This commit fixes crash caused by double free from message sequence
fragmentation. When double free happens the call stack is:

0  reassembly_cancel
1  handle_fragment_hdr
2  net_ipv6_process_pkt
3  process_data
4  processing_data
5  net_rx
6  process_rx_packet
7  work_q_main
8  _thread_entry

So at first packet is unrefed in reassembly_cancel and then also in
processing_data.

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

2018-04-20 07:37 UTC, rmstoi commented
recheck

2018-04-23 12:10 UTC, jukkar requested changes
Ruslan commented offline that there is still some issues with this so it needs some more TLC.

2018-04-24 13:00 UTC, rmstoi commented
@jukkar I pushed updated patch, did not notice memory regressions with this one, please review

2018-04-26 04:57 UTC, jukkar approved these changes

2018-04-26 04:58 UTC, merged