lib: smf: make number of arguments constant for SMF_CREATE_STATE()
zephyrproject-rtos/zephyr pull request #71250
Opened 2024-04-09 08:11 UTC by maass-hamburg

Currently the number of arguments of `SMF_CREATE_STATE()` is dependent on the Kconfig options `CONFIG_SMF_ANCESTOR_SUPPORT` and `CONFIG_SMF_INITIAL_TRANSITION`, IMO this is bad, as it breaks existing code if a Kconfig option is enabled, that wasn't enabled when the existing code was written. 

Explicitly as the USB-C subsystem uses the SMF with `CONFIG_SMF_ANCESTOR_SUPPORT` enabled and `CONFIG_SMF_INITIAL_TRANSITION` disabled, so the user can’t use hierarchical state machine with support for initial transitions in the same project together with using the USB-C subsystem, as enabling `CONFIG_SMF_INITIAL_TRANSITION` would break the USB-C subsystem.

Therefore `SMF_CREATE_STATE()` should always have 5 arguments and the unused arguments should be set to `NULL`

2024-04-09 11:21 UTC, henrikbrixandersen requested changes
I think this is a good idea, but since it is a breaking API change, it needs to go through the process for introducing such changes. 

Also, this PR is missing an entry in the migration guide.

2024-04-09 12:36 UTC, henrikbrixandersen commented
@maass-hamburg You need to follow the process described here: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes

2024-04-10 12:27 UTC, jfischer-no commented
> I think this is a good idea, but since it is a breaking API change, it needs to go through the process for introducing such changes.
> 
> Also, this PR is missing an entry in the migration guide.

Where has it been marked stable? https://docs.zephyrproject.org/latest/develop/api/overview.html

2024-04-19 18:12 UTC, keith-zephyr requested changes

2024-04-19 18:12 UTC, keith-zephyr commented on include/zephyr/smf.h
> +#define SMF_CREATE_STATE(_entry, _run, _exit, _parent, _initial) \
This change should be squashed with the changes to the SMF_CREATE_STATE users.  Otherwise this breaks bisect-ability.

2024-04-19 18:12 UTC, keith-zephyr commented on tests/lib/smf/src/test_lib_flat_smf.c
> +	[STATE_A] = SMF_CREATE_STATE(state_a_entry, state_a_run, state_a_exit, NULL, NULL),
Squash this commit into the commit that modifies smf.h

2024-04-19 18:12 UTC, keith-zephyr commented on subsys/usb/usb_c/usbc_pe_common.c
> +		NULL,
Squash into smf.h commit.

2024-04-21 09:14 UTC, ycsin reviewed
Haven't looked at the code thoroughly, I wonder if we can use some macro `__VA_ARGS__` magic so that the API appears to be the same and we do not need to modify existing applications?

2024-04-21 14:17 UTC, maass-hamburg commented
> Haven't looked at the code thoroughly, I wonder if we can use some macro `__VA_ARGS__` magic so that the API appears to be the same and we do not need to modify existing applications?

The problem is, that `SMF_CREATE_STATE()` is a macro and not a function. Macros can't use `__VA_ARGS__` to get the single parameters.

2024-04-21 16:47 UTC, glenn-andrews commented on doc/releases/migration-guide-3.7.rst
> +* The :c:macro:`SMF_CREATE_STATE` marcro now always takes 5 arguments. The amount of arguments is
macro not marcro

2024-04-21 16:57 UTC, glenn-andrews commented on doc/releases/release-notes-3.7.rst
> +  * The :c:macro:`SMF_CREATE_STATE` marcro now always takes 5 arguments.
macro not marcro

2024-04-22 06:07 UTC, ycsin commented
> The problem is, that `SMF_CREATE_STATE()` is a macro and not a function. Macros can't use `__VA_ARGS__` to get the single parameters.

i.e.:

```c
#ifdef CONFIG_SMF_ANCESTOR_SUPPORT
#ifndef CONFIG_SMF_INITIAL_TRANSITION
#define Z_SMF_CREATE_STATE(_entry, _run, _exit, _parent) \
{ \
	.entry   = _entry,  \
	.run     = _run,    \
	.exit    = _exit,   \
	.parent  = _parent, \
}
#define SMF_CREATE_STATE(_entry, _run, _exit, ...) Z_SMF_CREATE_STATE(_entry, _run, _exit, __VA_ARGS__)
#else
#define Z_SMF_CREATE_STATE(_entry, _run, _exit, _parent, _initial)\
{ \
	.entry   = _entry,  \
	.run     = _run,    \
	.exit    = _exit,   \
	.parent  = _parent, \
	.initial  = _initial, \
}
#define SMF_CREATE_STATE(_entry, _run, _exit, ...) Z_SMF_CREATE_STATE(_entry, _run, _exit, __VA_ARGS__)
#endif
#else
#define SMF_CREATE_STATE(_entry, _run, _exit, ...) \
{ \
	.entry   = _entry,  \
	.run     = _run,    \
	.exit    = _exit,   \
}
#endif
```

Could potentially be made into a more presentable state by using things like:
- `IS_ENABLED`
- `IS_EQ`
- `IF_ENABLED`
- `GET_ARG_N`

2024-04-22 13:07 UTC, maass-hamburg commented
> > The problem is, that `SMF_CREATE_STATE()` is a macro and not a function. Macros can't use `__VA_ARGS__` to get the single parameters.
> 
> i.e.:
> 
> ```c
> #ifdef CONFIG_SMF_ANCESTOR_SUPPORT
> #ifndef CONFIG_SMF_INITIAL_TRANSITION
> #define Z_SMF_CREATE_STATE(_entry, _run, _exit, _parent) \
> { \
> 	.entry   = _entry,  \
> 	.run     = _run,    \
> 	.exit    = _exit,   \
> 	.parent  = _parent, \
> }
> #define SMF_CREATE_STATE(_entry, _run, _exit, ...) Z_SMF_CREATE_STATE(_entry, _run, _exit, __VA_ARGS__)
> #else
> #define Z_SMF_CREATE_STATE(_entry, _run, _exit, _parent, _initial)\
> { \
> 	.entry   = _entry,  \
> 	.run     = _run,    \
> 	.exit    = _exit,   \
> 	.parent  = _parent, \
> 	.initial  = _initial, \
> }
> #define SMF_CREATE_STATE(_entry, _run, _exit, ...) Z_SMF_CREATE_STATE(_entry, _run, _exit, __VA_ARGS__)
> #endif
> #else
> #define SMF_CREATE_STATE(_entry, _run, _exit, ...) \
> { \
> 	.entry   = _entry,  \
> 	.run     = _run,    \
> 	.exit    = _exit,   \
> }
> #endif
> ```
> 
> Could potentially be made into a more presentable state by using things like:
> 
> * `IS_ENABLED`
> * `IS_EQ`
> * `IF_ENABLED`
> * `GET_ARG_N`

If the architecture WG is not approving the RFC, that could be an alternative. But having a constant number of arguments is still the more beautiful and better IMO, even if it breaks existing code (but easily fixable).

2024-04-22 16:38 UTC, ycsin commented on include/zephyr/smf.h
> +	COND_CODE_1(CONFIG_SMF_ANCESTOR_SUPPORT, (.parent = _parent,), ())     \
could be further simplified
```suggestion
	IF_ENABLED(CONFIG_SMF_ANCESTOR_SUPPORT, (.parent = _parent,))     \
```

2024-05-02 05:44 UTC, maass-hamburg commented
The architecture WG has no objections:
https://github.com/zephyrproject-rtos/zephyr/issues/71252#issuecomment-2085585788
@sambhurst @keith-zephyr looking towards getting a approving review.

2024-05-02 13:11 UTC, ycsin approved these changes

2024-05-02 13:11 UTC, ycsin commented on doc/releases/release-notes-3.7.rst
> +  * The :c:macro:`SMF_CREATE_STATE` macro now always takes 5 arguments.
I think we should also mention:
```rst
independent of the values of :kconfig:option:`CONFIG_SMF_ANCESTOR_SUPPORT` and
  :kconfig:option:`CONFIG_SMF_INITIAL_TRANSITION`
```

2024-05-05 13:39 UTC, henrikbrixandersen approved these changes

2024-05-07 15:04 UTC, carlescufi commented
@keith-zephyr please take another look

2024-05-07 15:28 UTC, keith-zephyr approved these changes

2024-05-07 15:46 UTC, merged