boards: dts: Add i2c to nrf5X_pcaX board dts.
zephyrproject-rtos/zephyr pull request #7139
Opened 2018-04-20 13:46 UTC by hakonfam

Fixes #7137

Enables the i2c drivers for these boards, allowing I2C to be used.
Required to enable i2c with these boards.
Tested building samples/bluetooth/beacon for nrf52_pca10040 with i2c enabled.

Parameters used for enabling i2c:
CONFIG_I2C=y
CONFIG_I2C_0=y
CONFIG_I2C_NRF5=y
CONFIG_I2C_NRF5_0_GPIO_SCL_PIN=6
CONFIG_I2C_NRF5_0_GPIO_SDA_PIN=7

Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.com>

2018-04-20 13:50 UTC, carlescufi requested changes
Why not add this to the 52840_pca10056 as well?

2018-04-20 17:49 UTC, hakonfam commented
Added to nrf52840_pca10056 as well.

2018-04-21 15:43 UTC, carlescufi approved these changes
Approved, but you'll need to fix your commit message. One of the lines is too long.

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/13694/5/tests

2018-04-23 14:06 UTC, galak approved these changes

2018-04-23 14:07 UTC, merged