samples: bluetooth: Add Apple iBeacon demo application
zephyrproject-rtos/zephyr pull request #7143
Opened 2018-04-21 19:37 UTC by henrikbrixandersen

Add a simple demo implementation of an Apple iBeacon BLE broadcaster.

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

2018-04-21 20:37 UTC, henrikbrixandersen commented
recheck

2018-04-22 00:26 UTC, jhedberg approved these changes

2018-04-23 18:43 UTC, dbkinder requested changes
One little tweak, otherwise looks OK.

2018-04-23 18:43 UTC, dbkinder commented on samples/bluetooth/ibeacon/README.rst
> +A simple application demonstrating the BLE Broadcaster role
Let's make this a sentence:

    This simple application demonstrates the BLE ...

2018-04-23 19:17 UTC, henrikbrixandersen commented
@dbkinder Good suggestion, thanks. I have changed it into a sentence.

2018-04-26 11:52 UTC, Vudentz approved these changes
LGTM

2018-04-28 07:55 UTC, jhedberg commented
I'll merge this since it seems the change request from @dbkinder has been taken care of.

2018-04-28 07:55 UTC, merged