posix: signal: only define `sigset_t` if not defined
zephyrproject-rtos/zephyr pull request #71458
Opened 2024-04-13 05:45 UTC by JordanYates

Only define `sigset_t` if it has not already been defined externally, for example in `picolibc/include/sys/signal.h`.

This appears to be standard way of preventing redefinitions, see:
* https://github.com/f32c/arduino/blob/7d8cbb33fab873e2d2c6660be4eb42e09ac3eee0/hardware/fpga/f32c/system/include/sys/select.h#L47
* https://github.com/bminor/newlib/blob/730703bdb8e1ae671517efaa0b9e273eef52d724/newlib/libc/include/sys/select.h#L18
* https://github.com/picolibc/picolibc/blob/58d6157cc2135df5043d62c3e89feedc20ffcd57/newlib/libc/include/sys/signal.h#L45

2024-04-13 09:58 UTC, cfriedt reviewed
FWICT, the external definition in picolibc and newlib is broken for the posix use case if realtime signals are enabled, depending on the platform, as `unsigned long` (`__sigset_t`) is only 32 bits on 32-bit platforms and realtime signals can add several extra bits.

Curious what @ycsin thinks about it though.

Timing-wise, I was actually in the process of defining some signal facilities at the kernel level too, so it will be interesting to see how this plays out.

2024-04-14 13:40 UTC, ycsin commented
> Curious what @ycsin thinks about it though.

I wonder how it will work out since the underlying implementation should be different?

2024-04-23 22:36 UTC, JordanYates commented
> > Curious what @ycsin thinks about it though.
> 
> I wonder how it will work out since the underlying implementation should be different?

This only fixs the first problem, which is the compiler erroring out because of a redefinition of the struct.
It makes no claims as to whether the underlying implementations will work properly.
I was hitting this case in external module code where both this file and standard library signal file were both included, even though they weren't being used AFAICT.

2024-05-22 00:21 UTC, cfriedt commented
@JordanYates - this is still on my radar, but there is a pretty big change that I think it overlaps with. My hopes are that we can have a single location for defining `sigset_t` as a result.

2024-05-22 00:32 UTC, JordanYates commented
> @JordanYates - this is still on my radar, but there is a pretty big change that I think it overlaps with. My hopes are that we can have a single location for defining `sigset_t` as a result.

Happy for a more complete solution upstream instead of this bandaid.

2024-07-10 01:55 UTC, cfriedt commented
A more complete solution was scheduled as a bugfix for v3.7.0, but I have my doubts that the prerequisite PRs will make it in, so it looks like the fix for this will also not be a part of v3.7

2024-08-22 15:40 UTC, MaureenHelm commented
@cfriedt please revisit

2024-12-22 11:30 UTC, kartben commented
ping @cfriedt @ycsin @aescolar @keith-packard

2024-12-22 11:41 UTC, cfriedt requested changes
I think if the definition for sigset were moved to a separate header, `<zephyr/posix/sys/_sigset.h>`, and that header was included here, I would be more inclined to approve.

2025-01-21 12:17 UTC, JordanYates commented
> I think if the definition for sigset were moved to a separate header, `<zephyr/posix/sys/_sigset.h>`, and that header was included here, I would be more included to approve.

Why is a dedicated header preferred? It's not the pattern I see in the other usage.

2025-01-21 12:34 UTC, cfriedt commented
> Why is a dedicated header preferred? It's not the pattern I see in the other usage.

Because that's the change that I have had staged in another WIP PR for a while.

2025-04-06 01:13 UTC, JordanYates commented
> > Why is a dedicated header preferred? It's not the pattern I see in the other usage.
> 
> Because that's the change that I have had staged in another WIP PR for a while.

I don't think it is worth complicating this PR in order to align with a PR that has been WIP for almost a year, unless there is some reason why merging this change is incompatible with whatever you are working on. This is a trivial change that solves a real problem.

2025-04-15 23:18 UTC, JordanYates commented
Damn, I missed the first birthday of this PR :)

2025-11-04 00:38 UTC, closed without merging