Cap broadcast start shell
zephyrproject-rtos/zephyr pull request #71512
Opened 2024-04-15 13:26 UTC by kruithofa

Added the shell command for the new broadcast reception start procedure

2024-05-20 08:31 UTC, Thalley requested changes
Minor request, otherwise LGTM

2024-05-20 08:31 UTC, Thalley commented on subsys/bluetooth/audio/shell/cap_commander.c
> +	}
Suggest to add a comment on why we are copying the parameters

2024-05-20 15:07 UTC, Thalley approved these changes, later dismissed

2024-05-30 13:06 UTC, Thalley requested changes

2024-05-30 13:06 UTC, Thalley commented on subsys/bluetooth/audio/shell/cap_commander.c
> +	shell_print(sh, "Starting broadcast on %zu connections", param.count);
```suggestion
	shell_print(sh, "Starting broadcast reception on %zu connections", param.count);
```

2024-05-30 13:06 UTC, Thalley commented on doc/connectivity/bluetooth/api/audio/shell/cap.rst
> +   Starting broadcast on 1 connections
```suggestion
   Starting broadcast reception on 1 connections
```

2024-05-30 13:06 UTC, Thalley commented on subsys/bluetooth/audio/shell/cap_commander.c
> +	shell_print(ctx_shell, "Broadcap reception start completed");
```suggestion
	}
	
	shell_print(ctx_shell, "Broadcast reception start completed");
```

2024-05-30 13:06 UTC, Thalley commented on subsys/bluetooth/audio/shell/cap_commander.c
> +		shell_error(ctx_shell, "Broadcap reception start failed (%d)", err);
```suggestion
		shell_error(ctx_shell, "Broadcast reception start failed (%d)", err);
```

2024-05-30 14:54 UTC, Thalley approved these changes

2024-05-30 21:21 UTC, larsgk approved these changes

2024-05-30 21:21 UTC, larsgk commented on doc/connectivity/bluetooth/api/audio/shell/cap.rst
> +   discovery completed with CSIS
Can we do this with more than 1 device? If so, maybe a good example

2024-05-30 21:44 UTC, merged