drivers: udc: the queued transfer after stall is not triggered
zephyrproject-rtos/zephyr pull request #71543
Opened 2024-04-16 10:42 UTC by MarkWangChinese

test the samples\subsys\usb\mass and find this issue.

2024-04-16 10:53 UTC, tmon-nordic requested changes
PR looks OK, but the commit message "drivers: udc: the queued transfer after stall is not triggered test the samples\subsys\usb\mass and find this issue." is rather vague and has to be replaced with proper commit description.

I would go with something like:
"driver: udc: trigger queued transfer on halt clear

Submit USBFSOTG_EVT_XFER on halt clear to allow queued transfers to execute as soon as endpoint STALL is cleared."

2024-04-16 13:41 UTC, MarkWangChinese commented
> PR looks OK, but the commit message "drivers: udc: the queued transfer after stall is not triggered test the samples\subsys\usb\mass and find this issue." is rather vague and has to be replaced with proper commit description.
> 
> I would go with something like: "driver: udc: trigger queued transfer on halt clear
> 
> Submit USBFSOTG_EVT_XFER on halt clear to allow queued transfers to execute as soon as endpoint STALL is cleared."

Fixed

2024-04-17 06:31 UTC, tmon-nordic approved these changes

2024-04-18 14:36 UTC, jfischer-no approved these changes

2024-04-18 15:05 UTC, merged