dts: xtensa: intel_adsp_ace15/ace20/tgph: correct SSP definition
zephyrproject-rtos/zephyr pull request #71551
Opened 2024-04-16 13:43 UTC by kv2019i

Fix the SSP definitions for multiple adsp platforms.

2024-04-16 13:52 UTC, plbossart requested changes

2024-04-16 13:52 UTC, plbossart commented on dts/xtensa/intel/intel_adsp_ace15_mtpm.dtsi
> -
I don't think this is correct. APL has 6 SSPs. That's the only case we have where all 6 SSPs needs to be exposed.

2024-04-16 13:53 UTC, plbossart commented on dts/xtensa/intel/intel_adsp_ace15_mtpm.dtsi
> -
never mind, I read cavs15, need more coffee.

2024-04-16 13:53 UTC, plbossart approved these changes

2024-04-16 14:01 UTC, dnikodem commented
@kv2019i  What about the cavs25.dtsi file? Shouldn't it also be changed?

2024-04-16 14:04 UTC, tmleman approved these changes

2024-04-16 14:05 UTC, kv2019i commented
@dnikodem the cavs25/tgp definition is actually correct, it has 6 SSP instances. the tgph variant has 3.

2024-04-16 14:06 UTC, dnikodem approved these changes

2024-04-16 16:57 UTC, dcpleung approved these changes

2024-04-20 13:17 UTC, nashif approved these changes

2024-04-21 10:28 UTC, merged