Add SNPS RMX500 platform support in terms of HWMv2
zephyrproject-rtos/zephyr pull request #71573
Opened 2024-04-16 17:13 UTC by kokas-a

Draft PR to make internal discussion about the concept itself in general

2024-04-17 07:00 UTC, nordicjm requested changes

2024-04-17 07:00 UTC, nordicjm commented on boards/snps/nsim/arc/Kconfig
do not rename folder to have arc in them, we are not going back to hwmv1

2024-04-17 07:33 UTC, kokas-a commented
@evgeniy-paltsev, @ruuddw , @abrodkin , please join to discussion

2024-04-17 07:54 UTC, kokas-a commented on boards/snps/nsim/arc/Kconfig
Hi @nordicjm,

Such scheme of naming was suggested in internal Synopsys discussion. The point is board name "nsim" - it is emulator, that supports 2 architectures, and we need somehow separate variants of the same "board" with different cores inside (arc and risc-v). Could you adwise the correct way to to that?

2024-04-17 08:08 UTC, nordicjm commented on boards/snps/nsim/arc/Kconfig
By naming the files with the CPU cluster in it, for example https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/nxp/imx8mp_evk which has an ARM core (cortex M4, CPU cluster is `m4`), AARCH64 (ARM64) core (cortex a53, CPU cluster is `a53`) and xtensa core (tensilica HiFi4, CPU cluster is `adsp`)

2024-04-17 08:29 UTC, ruuddw commented on boards/snps/nsim/arc/Kconfig
This is different, nsim is an instruction set simulator. The pattern followed here is like qemu. It has various simulated CPU flavors grouped in subdirs. nsim doesn't have all CPUs together in one SoC, these are "SoC" variants with a different CPU.

To make this more clear, I'd recomment to rename arc to arcv2 (not fully accurate, as it has some arcv3 cores in there but close enough, arc_v2_3 and arc_v5 may be better?).

2024-04-17 09:03 UTC, kokas-a commented on boards/snps/nsim/arc/Kconfig
Yes, indeed. Qemu is good exanple to describe situatoin with nSIM

2024-05-01 11:21 UTC, kokas-a commented
Replaced with new one: https://github.com/zephyrproject-rtos/zephyr/pull/72021

2024-05-01 11:21 UTC, closed without merging