scripts: west_commands: runners: Add support for probe-rs
zephyrproject-rtos/zephyr pull request #71627
Opened 2024-04-17 17:29 UTC by xingrz

[probe-rs](https://probe.rs/) is a new programming and debugging tool written in Rust, supports many probes and targets.

This PR introduces initial support for probe-rs to Zephyr.

2024-04-19 14:02 UTC, erwango requested changes
Thanks for contributing this probe.
Please update doc/develop/flash_debug/host-tools.rst, which will also be useful for review and testing

2024-07-31 11:41 UTC, jaredwolff commented
It would be great to see this go through. Was there anything else you wanted to see in `host-tools.rst` @erwango?

2024-07-31 12:09 UTC, kartben requested changes
a small typo

2024-07-31 12:20 UTC, xingrz commented on doc/develop/flash_debug/host-tools.rst
> +probe-rs is an open-source emmbedded toolkit written in Rust. It provides
Thank you

2024-07-31 12:23 UTC, kartben approved these changes

2024-07-31 13:30 UTC, erwango approved these changes
Txs for the update

2024-08-01 10:39 UTC, carlescufi approved these changes

2024-08-01 10:39 UTC, merged