boards: frdm_mcxn947: Add clock setup for FlexSPI
zephyrproject-rtos/zephyr pull request #71621
Opened 2024-04-17 16:04 UTC by mmahadevan108

The MEMC driver is initialized before the FlexSPI driver and hangs during FlexSPI init. Initialize the FlexSPI clock to 50MHz before the speed is set to the optimum speed by the FlexSPI driver.

2024-04-17 16:28 UTC, decsny requested changes
which memc driver are you talking about? it should be clarified in the commit message first of all, and need to know if we need to find a better solution if this problem will occur generally

2024-04-17 16:42 UTC, danieldegrasse commented
> The MEMC driver is initialized before the FlexSPI driver and hangs during FlexSPI init. Initialize the FlexSPI clock to 50MHz before the speed is set to the optimum speed by the FlexSPI driver.

Is the issue here that the FlexSPI was previously not being clocked prior to memc init, causing a hang? If so, I think this solution generally follows the pattern we are currently using for other peripheral clocking

2024-04-18 14:56 UTC, mmahadevan108 commented
> which memc driver are you talking about? it should be clarified in the commit message first of all, and need to know if we need to find a better solution if this problem will occur generally

Commit message updated to include the memc driver details.

2024-04-18 14:58 UTC, mmahadevan108 commented
> > The MEMC driver is initialized before the FlexSPI driver and hangs during FlexSPI init. Initialize the FlexSPI clock to 50MHz before the speed is set to the optimum speed by the FlexSPI driver.
> 
> Is the issue here that the FlexSPI was previously not being clocked prior to memc init, causing a hang? If so, I think this solution generally follows the pattern we are currently using for other peripheral clocking

Yes. FlexSPI clock is left un initialized at boot time causing a hang.

2024-04-18 15:44 UTC, decsny commented
> > which memc driver are you talking about? it should be clarified in the commit message first of all, and need to know if we need to find a better solution if this problem will occur generally
> 
> Commit message updated to include the memc driver details.

The commit message should also say what the "flexspi driver" is, as there are multiple flexspi drivers just like there are multiple memc drivers.

2024-04-19 04:27 UTC, danieldegrasse submitted a review, later dismissed

2024-04-22 14:50 UTC, mmahadevan108 commented
@decsny, kindly re-review

2024-04-22 15:09 UTC, decsny approved these changes, later dismissed

2024-04-22 15:10 UTC, decsny commented
I still think this should not have to be done in board code but don't know the complications so not blocking it right now

2024-04-22 18:35 UTC, mmahadevan108 commented
@dleach02, can you please review and approve

2024-04-24 18:53 UTC, decsny approved these changes
reapprove

2024-04-24 20:12 UTC, danieldegrasse approved these changes

2024-04-24 21:45 UTC, dleach02 approved these changes

2024-04-25 08:08 UTC, henrikbrixandersen approved these changes
I take it this (board.c used for clock setup) is an interim solution until we have something like https://github.com/zephyrproject-rtos/zephyr/pull/70467 available?

2024-04-25 09:55 UTC, merged