#71134 USB: Fix for Mass storage not working with USB Next on STM32.
zephyrproject-rtos/zephyr pull request #71702
Opened 2024-04-19 12:10 UTC by arnebdr

Fix for Issue 71134. USB MSC class enumeration failed with STM32 using USB Next stack, because in function udc_stm32_ep_mem_config(), priv->occupied_mem was only counted up on enable, but not down on endpoint disable.

Fixes: #71134

2024-04-19 12:43 UTC, tmon-nordic requested changes
Commits should be squashed and commit message has to be reworded. The prefix for next USB stack is `usb: device_next:`

2024-04-22 06:58 UTC, arnebdr commented
Ok I've squashed the two commits and changed the commit message. Hope its all ok now

2024-04-22 10:46 UTC, tmon-nordic commented
I would reword the commit message to be more concise.

```
usb: device_next: Fix Mass Storage on STM32

Mass Storage enumeration failed because udc_stm32_ep_mem_config() was only
increasing priv->occupied_mem on endpoint enable, and not decreasing it on
endpoint disable. Fix the issue by decreasing priv->occupied_mem on endpoint
disable.
```

2024-04-22 12:29 UTC, erwango approved these changes

2024-04-23 07:18 UTC, arnebdr commented
Ok, updated the commit message.

2024-04-23 09:20 UTC, tmon-nordic approved these changes

2024-04-23 21:26 UTC, merged