doc: release-notes: 3.7: new hawkbit features
zephyrproject-rtos/zephyr pull request #71712
Opened 2024-04-19 18:14 UTC by maass-hamburg

Mention new features of hawkbit in the release notes.

https://github.com/zephyrproject-rtos/zephyr/pull/70241
https://github.com/zephyrproject-rtos/zephyr/pull/70207
https://github.com/zephyrproject-rtos/zephyr/pull/69293

2024-04-20 13:18 UTC, nashif approved these changes, later dismissed

2024-04-20 13:36 UTC, ycsin approved these changes, later dismissed

2024-04-20 13:39 UTC, kartben requested changes

2024-04-20 13:39 UTC, kartben commented on doc/releases/release-notes-3.7.rst
> +    * When using the hawkBit autohandler and a update is installed, the device will now
```suggestion
    * When using the hawkBit autohandler and an update is installed, the device will now
```

2024-04-22 08:31 UTC, kartben approved these changes

2024-04-22 08:33 UTC, aescolar approved these changes

2024-04-22 10:44 UTC, ycsin approved these changes

2024-04-22 13:09 UTC, merged