net: tcp: use PSA functions for ISN generation instead of legacy MbedTLS ones
zephyrproject-rtos/zephyr pull request #71827
Opened 2024-04-23 15:01 UTC by valeriosetti

This PR:

- replaces MD5 with SHA256 for the computation of ISN (see [this comment](https://github.com/zephyrproject-rtos/zephyr/pull/71747#discussion_r1575859082) for details)
- replaces `mbedtls_xxx()` with `psa_hash_compute()`
- adds `sys_csrand_get()` as alternative to `sys_rand_get()` which allows to make use of PSA based entropy generators

This PR is an alternative to #71747 in the sense that there is no `mbedtls_sha256()` alternative option. We go directly to PSA functions instead.

2024-04-25 07:08 UTC, jukkar approved these changes, later dismissed
+1 to networking changes.

2024-04-25 07:38 UTC, rlubos approved these changes, later dismissed

2024-04-26 16:48 UTC, ceolin requested changes
It needs clarification about the mix usage of cryptographically safe random generator.
Please check comments.

2024-04-26 16:49 UTC, ceolin requested changes
It needs clarification about the mix usage of cryptographically safe random generator.
Please check comments.

2024-05-06 13:36 UTC, valeriosetti commented on modules/mbedtls/zephyr_init.c
> +	sys_rand_get(output, output_size);
Yes, sorry, I pushed an updated version that fixes this.

2024-05-07 13:04 UTC, frkv commented on subsys/net/ip/Kconfig.tcp
> +	select MBEDTLS_PSA_CRYPTO_C
```suggestion
	select MBEDTLS_PSA_CRYPTO_C depens on !BUILD_WITH_TFM
```
Selecting MBEDTLS_PSA_CRYPTO_C is incompatible with BUILD_WITH_TFM. Not sure if this depends will help, but you could try it out

2024-05-07 13:06 UTC, frkv commented on subsys/net/ip/tcp.c
> +#endif
Not easy to guess sys_csrand_get doesn't allow test-modes (If I'm not mistaken). If you have predictive RNG numbers then they are definitely guessable. Please use only sys_csrand_get so we can't remove any possible weak holes

2024-05-08 08:31 UTC, tomi-font submitted a review, later dismissed
Noting that
- some MbedTLS configuration changes come from #71947,
- the non-default enabling of `MBEDTLS_USE_PSA_CRYPTO` if `MBEDTLS_PSA_CRYPTO_C` is temporary (will be possible to revert with #72243),
- and that the newly introduced Kconfig options relating to PSA in `Kconfig.tls-generic` will be moved to `Kconfig.psa` when rebasing this PR.

2024-05-08 10:26 UTC, jukkar commented on subsys/net/ip/tcp.c
> +					 hash, sizeof(hash), &hash_len);
alignment

2024-05-08 10:26 UTC, jukkar commented on subsys/net/ip/tcp.c
> +					 hash, sizeof(hash), &hash_len);
ditto

2024-05-08 12:28 UTC, frkv approved these changes
LGTM (assuming alignment is fixed)

2024-05-08 14:30 UTC, valeriosetti commented on subsys/net/ip/tcp.c
> +					 hash, sizeof(hash), &hash_len);
Both indentations should be OK now

2024-05-08 14:30 UTC, jukkar approved these changes

2024-05-09 05:18 UTC, ceolin approved these changes

2024-05-09 08:27 UTC, merged