linker: Add ROM_SECTIONS location
zephyrproject-rtos/zephyr pull request #71911
Opened 2024-04-25 07:18 UTC by pdgendt

Allow putting sections after `common-rom`.

2024-04-25 08:17 UTC, ithinuel requested changes

2024-04-25 08:17 UTC, ithinuel commented on include/zephyr/arch/arm/cortex_m/scripts/linker.ld
> +#include <snippets-rom-sections.ld>
Like for the other occcurences of snippet, this should be documented with something of the form
```
/* Located in generated directory. This file is populated by calling
 * zephyr_linker_sources(ROM_SECTIONS ...). <description of typical use>.
 */
#include <snippets-rom-sections.ld>
```

2024-04-25 16:53 UTC, dcpleung submitted a review, later dismissed

2024-04-26 11:46 UTC, gmarull submitted a review, later dismissed

2024-04-26 11:49 UTC, pdgendt commented
I actually no longer have a dependency on this, but I guess it doesn't harm either?
In-tree there are many uses of `zephyr_linker_sources(SECTIONS ...)`, which I thought had the behavior I was expecting like the `ROM_SECTIONS` in this PR.

2024-05-14 08:06 UTC, pdgendt commented
Ping @ithinuel is comment addressed?

2024-05-14 10:21 UTC, ithinuel approved these changes, later dismissed

2024-05-15 10:10 UTC, nashif commented
> Allow putting sections after common-rom.

More details in the commit message following https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-body are appreciated, This is very short and missing the why and any further details.

2024-06-05 08:48 UTC, pdgendt commented
@nashif I've updated the commit message

@tejlmand does the `SECTIONS` put after bss/noinit make sense to begin with? Shouldn't it be always in ROM? Ref #72307

2024-06-05 12:54 UTC, nashif approved these changes

2024-06-05 13:51 UTC, pdgendt commented
Assigned to @tejlmand to get feedback

2024-06-20 13:55 UTC, tejlmand approved these changes

2024-06-20 16:08 UTC, merged