Bluetooth: controller: fixing rx node leak on CPR reject of parallel CPR
zephyrproject-rtos/zephyr pull request #71934
Opened 2024-04-25 11:13 UTC by erbr-ot

In case a CPR is intiated but rejected due to CPR active on other connection, rx nodes are leaked due to retained node not being properly released.

2024-05-16 07:37 UTC, erbr-ot commented
fixes https://github.com/zephyrproject-rtos/zephyr/issues/72845

2024-05-16 10:40 UTC, thoh-ot requested changes

2024-05-16 10:47 UTC, erbr-ot commented on subsys/bluetooth/controller/ll_sw/ull_llcp_remote.c
> +	/* If rx node was not retained 'release' reference */
ack

2024-05-16 10:47 UTC, erbr-ot commented on subsys/bluetooth/controller/ll_sw/ull_llcp_local.c
> +	/* If rx node was not retained 'release' reference */
ack

2024-05-16 12:05 UTC, thoh-ot approved these changes

2024-05-17 17:53 UTC, cvinayak approved these changes

2024-05-20 07:56 UTC, merged