Bluetooth: Audio: Shell: Add encryption to audio shell
zephyrproject-rtos/zephyr pull request #71944
Opened 2024-04-25 12:38 UTC by pin-zephyr

The audio shell does not enable encryption. It causes a legacy pairing instead of LE Secure Connections. Therefore, BASS discover return err=14.

This commit enable encryption to establish LE Secure connection for audio shell.

2024-04-25 12:57 UTC, Thalley requested changes
Change is good, but suggest to reword commit. 

This does not add encryption, but rather adds support for LESC in the host if the controller does not support the public key generation for ECDH.

2024-04-25 13:19 UTC, Thalley approved these changes

2024-04-26 12:04 UTC, larsgk approved these changes

2024-05-28 06:41 UTC, Thalley commented
@pin-zephyr please rebase

2024-06-11 06:34 UTC, Thalley commented
@pin-zephyr Please rebase

2024-06-11 07:33 UTC, pin-zephyr commented
@Thalley , probably we can discard this open PR. 

my code has been merged to upstream.

$ git show 291b81bc3836
commit 291b81bc38363f970f7ae1dab0bbb949f46b11e3
Author: Ping Wang <pinw@demant.com>
Date:   Thu Apr 25 14:30:59 2024 +0200

    Bluetooth: Audio: Shell: adds support for LESC in the host
    
    The commit adds support for LESC in the host if the controller
    does not support the public key generation for ECDH.
    
    Signed-off-by: Ping Wang <pinw@demant.com>

2024-06-11 11:05 UTC, Thalley commented
> @Thalley , probably we can discard this open PR.
> 
> my code has been merged to upstream.
> 
> $ git show [291b81b](https://github.com/zephyrproject-rtos/zephyr/commit/291b81bc38363f970f7ae1dab0bbb949f46b11e3) commit [291b81b](https://github.com/zephyrproject-rtos/zephyr/commit/291b81bc38363f970f7ae1dab0bbb949f46b11e3) Author: Ping Wang [pinw@demant.com](mailto:pinw@demant.com) Date: Thu Apr 25 14:30:59 2024 +0200
> 
> ```
> Bluetooth: Audio: Shell: adds support for LESC in the host
> 
> The commit adds support for LESC in the host if the controller
> does not support the public key generation for ECDH.
> 
> Signed-off-by: Ping Wang <pinw@demant.com>
> ```
> 
> However, I did not get why this PR is still has "OPEN" status.

Yeah, looks like a duplicate indeed. I'll close this

2024-06-11 11:05 UTC, closed without merging