i2c: Simple-ish RTIO driver for STM32 I2C v2
zephyrproject-rtos/zephyr pull request #71961
Opened 2024-04-25 17:39 UTC by teburd

Adds a simple I2C driver for ST's v2 IP block, and verified using i2c sram with the i2c_ram test.

Does not support autoreload (or longer than 255 byte transfers) because an issue was found in trying to enable that. But to start... I think this gets something in the tree others can look at, use, and try to extend as needed.

Depends on #71958 and #71959 

Marked draft until those are in.

2024-05-07 12:14 UTC, teburd commented
Gotta rebase

2024-05-15 14:53 UTC, kartben submitted a review, later dismissed

2024-05-15 14:53 UTC, kartben commented on tests/drivers/i2c/i2c_ram/boards/nucleo_h723zg.overlay
> +    status = "okay";
should be tabs?

2024-05-15 14:53 UTC, kartben commented on drivers/i2c/CMakeLists.txt
> +if(CONFIG_I2C_RTIO)
inconsistent use of tabs/spaces?

2024-05-21 09:54 UTC, erwango requested changes
Sorry for the delayed review. Thanks again for working on this driver.

Main request would be to split the driver refactorization from the RTIO introduction in different commits.

Then my second concern is about some functions that are being duplicated. Aside from maintenance issues this this also question the point of  RTIO API coexistence with other APIs.
These seem mutually exclusive for now, so:
if one client uses RTIO API, no other client could use the current API.
Will it remain this way ?
If yes, does it mean that, at one point RTIO will replace other APIs

2024-05-21 09:54 UTC, erwango commented on drivers/i2c/i2c_ll_stm32_rtio.c
> +				      sqe->buf, sqe->buf_len, dt_spec->addr);
Nit, non blocking: Do you actually need last addr arg ?

2024-05-21 09:54 UTC, erwango commented on drivers/i2c/i2c_ll_stm32_rtio.c
> +int i2c_stm32_configure_timing(const struct device *dev, uint32_t clock)
Any way not duplicating this function ?

2024-05-21 09:54 UTC, erwango commented on drivers/i2c/i2c_ll_stm32_rtio.c
```suggestion
drivers/i2c/i2c_ll_stm32_v2_rtio.c
```

2024-05-21 09:54 UTC, erwango commented on drivers/i2c/i2c_ll_stm32_rtio.c
> +static void i2c_stm32_disable_transfer_interrupts(const struct device *dev)
Any possibility this function in not duplicated ?

2024-06-03 23:19 UTC, teburd commented
> Sorry for the delayed review. Thanks again for working on this driver.
> 
> Main request would be to split the driver refactorization from the RTIO introduction in different commits.
> 
> Then my second concern is about some functions that are being duplicated. Aside from maintenance issues this this also question the point of RTIO API coexistence with other APIs. These seem mutually exclusive for now, so: if one client uses RTIO API, no other client could use the current API. Will it remain this way ? If yes, does it mean that, at one point RTIO will replace other APIs



> Sorry for the delayed review. Thanks again for working on this driver.
> 
> Main request would be to split the driver refactorization from the RTIO introduction in different commits.
> 
> Then my second concern is about some functions that are being duplicated. Aside from maintenance issues this this also question the point of RTIO API coexistence with other APIs. These seem mutually exclusive for now, so: if one client uses RTIO API, no other client could use the current API. Will it remain this way ? If yes, does it mean that, at one point RTIO will replace other APIs

The current API (i2c_transfer) and all blocking calls (i2c_recovery, i2c_get_config, i2c_set_config) work as expected. The missing feature today is using i2c target mode which has some interesting quirks with the existing API anyways and probably deserves a harder look.'

I'll try and revisit this PR after 3.7

2024-11-07 15:58 UTC, avisconti commented
This is very nice. I'm in the process to add RTIO streaming to lsm6dsv16x driver. Currently I'm using I2C rtio default driver as I do not have any board with a spi/i2c rtio-enabled controller driver. But I stream the FIFO fine! I hope this PR would eventually be merged in, but it is not blocking my PR which should be submitted by the end of next week...

2024-12-03 13:54 UTC, avisconti commented
Is there any possibility to rebase/align this PR to latest commit with current rtio?
@teburd

2024-12-03 14:16 UTC, erwango commented
> Is there any possibility to rebase/align this PR to latest commit with current rtio?

Idea was that we would complete this effort actually. Though, we're busy with other stuff atm and I hope we should be able to finally start this on January.

2024-12-03 14:52 UTC, avisconti commented
> > Is there any possibility to rebase/align this PR to latest commit with current rtio?
> 
> Idea was that we would complete this effort actually. Though, we're busy with other stuff atm and I hope we should be able to finally start this on January.

That's fine with me Erwan.

2025-04-17 13:12 UTC, closed without merging