boards: phytec: Remove Messtechnik GmbH
zephyrproject-rtos/zephyr pull request #72012
Opened 2024-04-26 15:05 UTC by dnltz

PHYTEC has multiple offices in different locations like the US, France, India and China. The headquarter is located in Germany. Since now 50% of the PHYTEC boards are from the US office, we should drop 'Messtechnik GmbH', which is the offical title of the German office, and keep the name more general.

2024-04-26 15:19 UTC, vaishnavachath submitted a review, later dismissed

2024-05-08 18:01 UTC, dnltz commented
@tejlmand can you help me to simplify our company name? I saw you changed to hw v2 but we there is no maintainer for this file.

2024-05-15 10:44 UTC, kartben approved these changes, later dismissed

2024-05-15 11:24 UTC, henrikbrixandersen requested changes
You likely want to update your entry in `dts/bindings/vendor-prefixes.txt` as well.

2024-05-15 11:39 UTC, henrikbrixandersen approved these changes

2024-05-15 11:48 UTC, kartben approved these changes

2024-05-15 14:09 UTC, merged