drivers: gpio: Avoid conflicts
zephyrproject-rtos/zephyr pull request #72040
Opened 2024-04-27 21:47 UTC by rettichschnidi

By sorting the lines alphabetically, conflicts can be reduced.

## Background

For a while now, I am working on support for a new SoC. Often, when rebasing my WIP branch on the most recent main, conflicts happen because everyone adds new drivers at the bottom. By biting the bullet now, this kind of conflict can (most of the time) be avoided in the future.

2024-04-28 20:31 UTC, henrikbrixandersen requested changes
Please use the markers for ensuring future sorting is checked by CI.

2024-04-28 20:31 UTC, henrikbrixandersen commented on drivers/gpio/CMakeLists.txt
> +# Please keep this list sorted alphabetically
```suggestion
# zephyr-keep-sorted-start
```

2024-04-28 20:31 UTC, henrikbrixandersen commented on drivers/gpio/CMakeLists.txt
> +zephyr_library_sources_ifdef(CONFIG_USERSPACE   gpio_handlers.c)
```suggestion
zephyr_library_sources_ifdef(CONFIG_USERSPACE   gpio_handlers.c)
# zephyr-keep-sorted-stop
```

2024-04-28 20:31 UTC, henrikbrixandersen commented on drivers/gpio/Kconfig
> +# Please keep this list sorted alphabetically
```suggestion
# zephyr-keep-sorted-start
```

2024-04-28 20:31 UTC, henrikbrixandersen commented on drivers/gpio/Kconfig
> +source "drivers/gpio/Kconfig.xmc4xxx"
```suggestion
source "drivers/gpio/Kconfig.xmc4xxx"
# zephyr-keep-sorted-stop
```

2024-04-29 05:30 UTC, henrikbrixandersen approved these changes

2024-04-29 06:53 UTC, pdgendt approved these changes

2024-05-01 08:29 UTC, merged