samples: Bluetooth: add `code-sample` tags to hci_ samples
zephyrproject-rtos/zephyr pull request #72104
Opened 2024-04-29 15:25 UTC by jori-nordic

Add `zephyr:code-sample` header to the samples exposing the controller over HCI.

They should now be linked to the `hci_raw` documentation page, along with a nicer overlay when referring to them from other places in the docs.

2024-04-29 18:05 UTC, carlescufi approved these changes

2024-04-30 07:15 UTC, alwa-nordic approved these changes

2024-04-30 07:22 UTC, jhedberg approved these changes

2024-04-30 07:38 UTC, Andrewpini approved these changes

2024-04-30 09:01 UTC, kartben requested changes
Thanks for doing this! 

Not sure why the doc build failure in CI (still some `:ref:`s that need updating it looks like) was not making this PR "red" though? Looks like it might not even have pingged you @jori-nordic about the failure?

2024-06-20 15:30 UTC, jori-nordic commented
I don't have time for this, sorry..

2024-06-20 15:30 UTC, closed without merging