Add 'Zephyr FSM plan' to glossary
zephyrproject-rtos/zephyr pull request #72118
Opened 2024-04-29 21:18 UTC by romkell

Add 'Zephyr FSM plan' to glossary
as used in the zephyr functional safety management plan.

2024-05-15 20:04 UTC, henrikbrixandersen reviewed
"FSM" is a well-established abbreviation of "Finite-state machine". I would be very careful in reusing it for something like this within the Zephyr project.

2024-08-01 15:07 UTC, ubieda commented
Agree on not re-using the FSM acronym

2024-09-27 12:56 UTC, simhein requested changes

2024-09-27 12:56 UTC, simhein commented on doc/glossary.rst
> +      Lifecycle.
```suggestion
   Zephyr safety plan
      The safety plan also known as functional safety management plan contains the planning
      and mapping of methods and resources of the activities of the Zephyr safety
      lifecycle.
```

2024-11-13 16:16 UTC, kartben requested changes
@simhein's suggestion goes in the right direction. This new entry needs to be reference from at least somewhere though, as we don't want to add entries to the glossary just for the sake of it, but rather have these entries being pointed to from other pages in the docs.

2024-11-18 08:15 UTC, simhein commented
> @simhein's suggestion goes in the right direction. This new entry needs to be reference from at least somewhere though, as we don't want to add entries to the glossary just for the sake of it, but rather have these entries being pointed to from other pages in the docs.

True I generally agree with that, I will check on it how we can integrate the safety plan and reference to it in the docs because we can't publish the whole plan because of legal issues with references and text to the safety standard

2024-12-11 16:46 UTC, kartben commented
closing this PR as it looks like there is agreement on taking a different approach than adding safety terms in the general Zephyr glossary

2024-12-11 16:46 UTC, closed without merging