boards: shields: add rk043fn02h_ct and rk043fn66hs_ctg shields
zephyrproject-rtos/zephyr pull request #72174
Opened 2024-04-30 20:24 UTC by danieldegrasse

Add `rk043fn02h_ct` and `rk043fn66hs_ctg` shields. These shields both describe Rocktech panels available from NXP, and compatible with several NXP iMX RT EVKs using a FPC interface.

Define nodelabel aliases for these FPC interfaces, and update the RT1060 EVK board definition to no longer define the RK043FN02H_CT as a panel at the board level (and use the shield instead)

Support for additional NXP EVKs (RT1064, RT1050, RT1040) will be added in follow up PRs.

2024-05-14 19:34 UTC, DerekSnell requested changes
@danieldegrasse and @dleach02 ,
This PR works well on my hardware.  I tested with the following combinations:
* `mimxrt1050_evk` board with `rk043fn02h_ct` shield
* `mimxrt1060_evkb` board with `rk043fn66hs_ctg` shield

The doc page has some typos to fix for the build instructions.  Otherwise, this looks good to me.

2024-05-14 22:09 UTC, danieldegrasse commented
> @danieldegrasse and @dleach02 , This PR works well on my hardware. I tested with the following combinations:
> 
>     * `mimxrt1050_evk` board with `rk043fn02h_ct` shield
> 
>     * `mimxrt1060_evkb` board with `rk043fn66hs_ctg` shield
> 
> 
> The doc page has some typos to fix for the build instructions. Otherwise, this looks good to me.

Thanks for catching these- both should be fixed now

2024-05-15 14:58 UTC, DerekSnell submitted a review, later dismissed

2024-05-16 01:48 UTC, dleach02 submitted a review, later dismissed

2024-05-17 03:57 UTC, dleach02 commented
@kartben need your approval

2024-05-28 01:17 UTC, dleach02 commented
@kartben please give this attention or reassign it to someone else (me)

2024-05-30 17:16 UTC, MaureenHelm submitted a review, later dismissed

2024-05-30 17:22 UTC, kartben requested changes

2024-05-31 14:36 UTC, danieldegrasse commented on boards/nxp/mimxrt1060_evk/mimxrt1060_evk.dts
> +	};
Good point. I've added compatibles for both connections

2024-06-03 17:53 UTC, dleach02 submitted a review, later dismissed

2024-06-03 17:54 UTC, dleach02 commented
@kartben need you to review Daniel's change.

@MaureenHelm @DerekSnell please review as your approvals were dropped when @danieldegrasse addressed @kartben change request.

2024-06-03 18:03 UTC, MaureenHelm reviewed
It seems we're inconsistent about whether the vendor should be followed by a comma or a dash in the gpio header bindings. But it looks strange not to have a comma

2024-06-03 18:03 UTC, MaureenHelm commented on dts/bindings/gpio/nxp-i2c-tsc-fpc.yaml
> +compatible: "nxp-i2c-tsc-fpc"
```suggestion
compatible: "nxp,i2c-tsc-fpc"
```

2024-06-03 18:03 UTC, MaureenHelm commented on dts/bindings/gpio/nxp-parallel-lcd-connector.yaml
> +compatible: "nxp-parallel-lcd-connector"
```suggestion
compatible: "nxp,parallel-lcd-connector"
```

2024-06-03 18:20 UTC, danieldegrasse commented
> It seems we're inconsistent about whether the vendor should be followed by a comma or a dash in the gpio header bindings. But it looks strange not to have a comma

Good point- both bindings have been updated to have a comma

2024-06-05 10:24 UTC, kartben approved these changes

2024-06-05 13:57 UTC, dleach02 approved these changes

2024-06-06 07:37 UTC, merged