test: pwm: add mimxrt1060_evk support for pwm
zephyrproject-rtos/zephyr pull request #72244
Opened 2024-05-02 15:38 UTC by hakehuang

add missing board and overlay support

2024-05-02 17:36 UTC, henrikbrixandersen approved these changes

2024-05-02 20:18 UTC, decsny requested changes

2024-05-02 20:18 UTC, decsny commented on boards/nxp/mimxrt1060_evk/mimxrt1060_evk_mimxrt1062_qspi.yaml
> -  - dma
why is dma removed?

2024-05-02 20:19 UTC, decsny approved these changes
nevermind, I see now it is a repeat

2024-05-06 14:59 UTC, danieldegrasse approved these changes

2024-05-10 18:44 UTC, dleach02 approved these changes

2024-05-10 22:07 UTC, merged