samples: Bluetooth: broadcast_audio_sink: remove nRF52820 from sample.yaml
zephyrproject-rtos/zephyr pull request #72252
Opened 2024-05-02 19:18 UTC by Ballen7

nrf52833dk/nrf52820 does not compile so remove it from platform_allow list

2024-05-03 08:57 UTC, Thalley approved these changes

2024-05-03 17:34 UTC, cvinayak commented
Please fix commit title "sample: Bluetooth: broadcast_audio_sink: remove nrf52820 from sample.yaml"

2024-05-03 17:35 UTC, cvinayak requested changes
Fix commit title...

2024-05-04 08:26 UTC, jhedberg approved these changes

2024-05-04 19:24 UTC, cvinayak approved these changes

2024-05-06 13:59 UTC, merged