drivers: serial: added missing parenthesis
zephyrproject-rtos/zephyr pull request #72343
Opened 2024-05-06 08:52 UTC by tychofrei02

Added missing parentheses around macro argument expansion.

This corresponds to following coding guideline:

> Expressions resulting from the expansion of macro parameters shall be enclosed in parentheses

This PR is part of the enhancement issue https://github.com/zephyrproject-rtos/zephyr/issues/48002 which port the coding guideline fixes done by BUGSENG on the https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-auditable-branch back to main

The commit in this PR is a subset of the original auditable-branch commit:
https://github.com/zephyrproject-rtos/zephyr/commit/08619905cd74d4d8bce23cd034e34a95ffa10057

2024-05-06 08:54 UTC, kartben approved these changes

2024-05-13 19:20 UTC, dcpleung approved these changes

2024-05-13 19:32 UTC, kartben requested changes
As pointed out by @fabiobaltieri in another similar pull request, there is probably no actual coding guideline violation being fixed by this particular PR, would you agree @tychofrei02? Knowing that, I am not sure the change is worth it?

2024-05-13 19:35 UTC, fabiobaltieri requested changes
Yeah this is not what https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/-/blob/master/R_20_07.c says

2024-05-14 09:27 UTC, tychofrei02 commented
I do think there is a violation, however the more efficient way to address it would be by fixing it at the macro definition. I will therefore close this pull request.

2024-05-14 09:27 UTC, closed without merging