doc: releases: Enforce linking to Pull Requests in migration guide
zephyrproject-rtos/zephyr pull request #72515
Opened 2024-05-09 11:51 UTC by carlescufi

In order to provide additional context and information to Zephyr users,
    ensure that each entry in the migration guide contains a link to the
    GitHub Pull Request that introduced the corresponding change.

2024-05-09 17:38 UTC, fabiobaltieri submitted a review, later dismissed
good idea

2024-05-09 18:00 UTC, RichardSWheatley commented on doc/releases/migration-guide-3.7.rst
> +  :ref:`hw_model_v2` for more detailed information. (:github:`69607`)
@carlescufi is the (:github:'69607') Intended to add a link to a PR? or Issue?
Just a question as I am looking at doing something similar outside of Zephyr.

2024-05-09 20:14 UTC, henrikbrixandersen reviewed
This doesn't enforce anything, though.

It puts the work of ensuring each entry contains a link to a PR on the shoulders of the reviewers.

I tried to insist people do this at the start of the v3.6 release cycle, but gave up since it's quite difficult to manage without an automated check.

2024-05-09 20:17 UTC, RichardSWheatley commented
> This doesn't enforce anything, though.
> 
> It puts the work of ensuring each entry contains a link to a PR on the shoulders of the reviewers.
> 
> I tried to insist people do this at the start of the v3.6 release cycle, but gave up since it's quite difficult to manage without an automated check. 

I tried viewing the rst file in the source directory and the PR did not contain a link but just said the number. How should I view it to see the link?

2024-05-09 20:27 UTC, henrikbrixandersen commented
> I tried viewing the rst file in the source directory and the PR did not contain a link but just said the number. How should I view it to see the link?

You need to look at the rendered output from this PR by following the link in the Documentation Build CI check: https://docs.zephyrproject.org/latest/index.html

2024-05-10 07:15 UTC, aescolar requested changes

2024-05-10 07:15 UTC, aescolar commented on doc/releases/migration-guide-3.7.rst
> +    ``samples/subsys/debug/fuzz/`` for an example. (:github:`69690`)
71378

2024-05-10 07:15 UTC, aescolar commented on doc/releases/migration-guide-3.7.rst
> +  renamed to :kconfig:option:`MODEM_CHAT_LOG_BUFFER_SIZE`. (:github:`70405`)
This is really tangentional but if you are changing this line can you fix this:
```suggestion
  renamed to :kconfig:option:`CONFIG_MODEM_CHAT_LOG_BUFFER_SIZE`. (:github:`70405`)
```

2024-05-10 07:15 UTC, aescolar commented on doc/releases/migration-guide-3.7.rst
> +  actual PWM driver. (:github:`71097`)
68433

2024-05-10 09:28 UTC, carlescufi commented
> This doesn't enforce anything, though.

It documents that it is required to include the link, it's a first start.

> It puts the work of ensuring each entry contains a link to a PR on the shoulders of the reviewers.

Agreed, we will take a look at a check later.

2024-05-10 09:57 UTC, aescolar approved these changes

2024-05-13 12:44 UTC, kartben approved these changes
I thought we had documented this already when we discussed introducing this change, so thanks for actually taking care of it! :)

2024-05-13 15:01 UTC, henrikbrixandersen reviewed
While I think introducing this requirement for migration guide entries is a good idea, I fear introducing it without any checks in place will place the burden on the reviewers and release managers.

2024-05-13 15:12 UTC, fabiobaltieri commented
> While I think introducing this requirement for migration guide entries is a good idea, I fear introducing it without any checks in place will place the burden on the reviewers and release managers.

Yeah at the scale at which the project operates and with many people rotating through the roles it would be a good idea if any changes like this one were introduced directly as a compliance check rather than (just) documentation. In this state you may as well consider it just a guideline.

2024-05-13 15:13 UTC, fabiobaltieri commented
So actually the PR title is misleading. It's not really enforcing anything.

2024-05-13 15:14 UTC, carlescufi commented
> So actually the PR title is misleading. It's not really enforcing anything.

The documentation uses the verb "must", that's "enforcing" in this context.

2024-05-13 20:04 UTC, merged