include: storage: flash_map: _NODE macros
zephyrproject-rtos/zephyr pull request #72582
Opened 2024-05-10 14:29 UTC by michalek-no

adds size, offset and divice access macros that are operating with nodes as an argumet.

2024-05-13 08:55 UTC, de-nordic reviewed
LGTM.
Nevertheless the Flash Map API is considered stable API (https://docs.zephyrproject.org/2.7.5/reference/api/overview.html#api-overview) and therefore tests scenarios are required by the change.

2024-05-13 11:49 UTC, sigvartmh approved these changes

2024-05-14 11:57 UTC, michalek-no commented
rebase + tests

2024-05-14 17:19 UTC, de-nordic approved these changes, later dismissed

2024-05-15 14:12 UTC, carlescufi approved these changes, later dismissed

2024-05-15 14:21 UTC, kartben requested changes
couple typos spotted

2024-05-15 14:21 UTC, kartben commented on include/zephyr/storage/flash_map.h
> + * @return fixed-partition offset, as defined for the partition in DTS.
```suggestion
 * @return fixed-partition size, as defined for the partition in DTS.
```

2024-05-15 14:21 UTC, kartben commented on tests/subsys/storage/flash_map/src/main.c
> +ZTEST(flash_map, test_fixed_partition_noded_macros)
```suggestion
ZTEST(flash_map, test_fixed_partition_node_macros)
```

2024-05-16 14:16 UTC, carlescufi approved these changes

2024-05-16 14:17 UTC, kartben approved these changes

2024-05-16 14:21 UTC, merged