boards: st: nucleo_wba55cg: define all LEDs/buttons and add MCUboot related LED/button aliases
zephyrproject-rtos/zephyr pull request #72795
Opened 2024-05-15 11:55 UTC by pepe2k

This includes the following two commits, focused on LEDs and buttons definitions for `nucleo_wba55cg` board:

- **boards: st: nucleo_wba55cg: define all LEDs and buttons**
This board includes three gpio-connected LEDs and push-buttons. Include all missing defines in board's DTS and while at it, fix existing button definition (missing pull-up enable) and align node names with other boards (e.g. `nucleo_wb55rg`).

   Provided changes were tested on real board with `blinky` and `button` samples.

- **boards: st: nucleo_wba55cg: add mcuboot-{led0,button0} aliases**
This adds DT aliases for LED and button used in recovery mode of the `MCUboot` bootloader, on the `nucleo_wba55cg` board.

2024-05-16 09:46 UTC, erwango requested changes
Please fix issue reported by CI [here](https://github.com/zephyrproject-rtos/zephyr/actions/runs/9095177541/job/24998062524?pr=72795#step:12:179)
```
devicetree error: Label 'red_led_3' appears on /leds/led_2 and on /leds/led_3
```

2024-05-16 20:22 UTC, pepe2k commented
> Please fix issue reported by CI [here](https://github.com/zephyrproject-rtos/zephyr/actions/runs/9095177541/job/24998062524?pr=72795#step:12:179)
> 
> ```
> devicetree error: Label 'red_led_3' appears on /leds/led_2 and on /leds/led_3
> ```

Ouch, sorry, I missed that one. Fixed force pushed (with rebase on top of `main`).

2024-05-17 07:11 UTC, erwango approved these changes

2024-05-17 07:24 UTC, FRASTM approved these changes

2024-05-17 13:07 UTC, merged