drivers: rtc: stm32: fix error handling in rtc_stm32_set_time()
zephyrproject-rtos/zephyr pull request #72811
Opened 2024-05-15 14:39 UTC by ajarmouni-st

re-enable RTC registers Write Protection when entering Init Mode return error.

2024-05-15 17:46 UTC, bjarki-trackunit requested changes

2024-05-15 17:46 UTC, bjarki-trackunit commented on drivers/rtc/rtc_ll_stm32.c
> +end:
`goto` name should describe what it does, something like `protect_unlock_return:`

2024-05-16 12:29 UTC, erwango approved these changes

2024-05-16 12:55 UTC, bjarki-trackunit approved these changes

2024-05-16 13:33 UTC, FRASTM approved these changes

2024-05-17 07:03 UTC, gautierg-st approved these changes

2024-05-17 19:47 UTC, merged