assert: Expand to (void)test when asserts are disabled
zephyrproject-rtos/zephyr pull request #72854
Opened 2024-05-16 08:23 UTC by jori-nordic

If a convenience variable is used for `test`, then compilers will raise an "unused variable" warning when asserts are disabled.

The alternative is guarding that variable behind an ifdef, or using __ASSERT_EVAL() which both hinder readability. We have enough ifdefs as it is.

E.g. this code will raise a warning:
```c
static void lower_data_ready(struct bt_l2cap_br_chan *br_chan)
{
	struct bt_conn *conn = br_chan->chan.conn;
	sys_snode_t *s = sys_slist_get(&conn->l2cap_data_ready);

	__ASSERT_NO_MSG(s == &br_chan->_pdu_ready);
```

2024-05-16 08:28 UTC, pdgendt commented on include/zephyr/sys/__assert.h
> +#define __ASSERT(test, fmt, ...) {(void)test}
This does change the behavior too, but I guess this is fine?

We should add parentheses though.

```suggestion
#define __ASSERT(test, fmt, ...) {(void)(test)}
```

2024-05-16 12:40 UTC, pdgendt requested changes
Actually thinking more about this, an `assert` should be a no-op if disabled, as you don't want to waste the CPU cycles. So I guess this isn't a "fix".

-1 for now

2024-05-16 14:13 UTC, andyross commented
Yeah, I actually remember thinking about something like this long ago.  I don't think this is a solvable problem at the level of the preprocessor: you want the result of the expansion to (1) generate a compiler-visible reference to any symbols that may be included in the macro arguments but (2) generate absolutely no code or side effects.  But that's not possible without somehow **parsing** the expression arguments, which obviously you can't do.

But if you want to try where I failed: look at getting ASSERT() to emit a GCC nested function which can be made to "evaluate" under an if(0) or whatever.  That gets you (2) (maybe -- again I never made this work) but still fails on the side effect test.  But then again, we absolutely shouldn't have side effects in an optional assert anyway.  Though this does then demand that we have some way to detect them.

Anyway, it sounds fun.

2024-05-16 18:54 UTC, jori-nordic commented
I see. 
I guess for Bluetooth we'll just have our own `BT_ASSERT()` <sub>with blackjack and (...)</sub>

Here are my thoughts which sparked this PR btw: https://github.com/zephyrproject-rtos/zephyr/pull/72090#discussion_r1599469804

2024-05-16 19:40 UTC, jori-nordic commented
> an assert should be a no-op if disabled

I tried it on compiler-explorer and got a no-op on `-O1`, on arm-gcc. Am I missing something?

2024-05-21 07:05 UTC, jori-nordic commented
Thanks for the explanation, I didn't consider extern functions.

> clearly there "shouldn't" be any in a correctly-written assertion

Can't we just declare (in the docs) that if you have side-effects in your asserts you're Doing it Wrong (TM)?

IMO, it feels wrong to penalize all the users in order to cater to badly-written code.

2024-05-21 11:19 UTC, alwa-nordic commented
> Yeah, I actually remember thinking about something like this long ago. I don't think this is a solvable problem at the level of the preprocessor: you want the result of the expansion to (1) generate a compiler-visible reference to any symbols that may be included in the macro arguments but (2) generate absolutely no code or side effects. But that's not possible without somehow parsing the expression arguments, which obviously you can't do.

Would the following work?

```c
/* Double parens to reject types. E.g. sizeof((char)) fails compilation. */
#define __ASSERT_NO_MSG(test) ( (void)sizeof((test)) )
```

2024-05-21 11:33 UTC, alwa-nordic commented
Here is an alternative that uses the expression as a predicate. I think this type-checks as-if it was in an if-condition.

```c
#define __ASSERT_NO_MSG(test) ( (void)sizeof((test) ? 1 : 0) )
```

2024-05-21 13:10 UTC, andyross commented
I'll admit I'm not 100% sure how compilers treat the argument to sizeof.  Expressions work, but they only need to recurse as far as an explicit type (i.e. "+" needs to check the types on either side, but "foo(xxx)" has the declared type of foo() and doesn't depend on an argument inside the list).  Do they fool the unused argument detector or is the compiler too smart?

2024-05-21 15:06 UTC, alwa-nordic commented
> I'll admit I'm not 100% sure how compilers treat the argument to sizeof. Expressions work, but they only need to recurse as far as an explicit type (i.e. "+" needs to check the types on either side, but "foo(xxx)" has the declared type of foo() and doesn't depend on an argument inside the list). Do they fool the unused argument detector or is the compiler too smart?

I guess the only way to know is to test it.

But I'm pretty confident it should work. The symbols will be referenced in the input to the compiler (unlike removed by the preprocessor). And compilers normally don't complain about variables that get optimized away. It should be similar to wrapping it in `while (0) {}`.

2024-05-27 07:25 UTC, alwa-nordic commented
I tried changing `__ASSERT` to `(void)sizeof((test) ? 1 : 0)`. It works well to mark variables as used. However, there are some in-tree cases of variables only defined when asserts are enabled. So this breaks the build. I suppose we can't rely on the compiler to optimize those variables out.

I checked how GCC's assert.h works, and it too leaves the variables unused when `NDEBUG=1`.

I think the solution is to do `if (test) {__ASSERT_NO_MSG(false);}`.

2024-05-27 15:18 UTC, peter-mitsis commented
Tossing out an idea ... would tagging those variables of convenience with the `__maybe_unused` attribute be a viable alternative? It may add some degree of clutter, but ...
   1. It ought to be less clutter than wrapping them with #ifdef/#endif.
   2. It informs both the compiler and human that in some configurations that variable is unused.

2024-05-27 15:29 UTC, jori-nordic commented
That's a good suggestion, I'll try it in my other patch to see if the CI gods also agree :)

2024-06-12 06:10 UTC, jori-nordic commented
Closing as the solution doesn't please everyone.
@peter-mitsis 's solution works well enough, thanks!

2024-06-12 06:10 UTC, closed without merging