Bluetooth: Remove useless field `init_credits`
zephyrproject-rtos/zephyr pull request #72872
Opened 2024-05-16 12:05 UTC by alwa-nordic

Remove `bt_l2cap_le_endpoint.init_credits` that has zero uses and is just taking up RAM for no reason.

2024-05-16 13:53 UTC, hermabe approved these changes, later dismissed

2024-05-16 13:55 UTC, Thalley reviewed
I guess this is another instance of a public API struct field we just assume no one is using, and shouldn't be considered a stable API breaking change?

2024-05-16 14:30 UTC, jhedberg commented
> I guess this is another instance of a public API struct field we just assume no one is using, and shouldn't be considered a stable API breaking change?

Yeah.. might still make sense to mention it in the migration-guide. I mean, *if* someone was using it (writing some value to it), it was essentially a placebo. Removing the usage will not make any difference, but might help to let people know this by having some documentation note about it.

2024-05-16 14:44 UTC, Thalley commented
> > I guess this is another instance of a public API struct field we just assume no one is using, and shouldn't be considered a stable API breaking change?
> 
> Yeah.. might still make sense to mention it in the migration-guide. I mean, _if_ someone was using it (writing some value to it), it was essentially a placebo. Removing the usage will not make any difference, but might help to let people know this by having some documentation note about it.

Indeed. It may not affect behavior, but it may break compiling for some applications, which is one of the criteria for the migration guide IIRC

2024-05-16 18:57 UTC, jori-nordic requested changes
the people want their migration guide :)
Don't know what you can write there, other than "field went poof"...

2024-05-16 20:15 UTC, Thalley commented
> the people want their migration guide :) Don't know what you can write there, other than "field went poof"...

Something along the lines of "The field `init_credits` was removed as it was unused, and any usage can safely be removed".

2024-05-21 09:04 UTC, jori-nordic approved these changes

2024-05-21 10:45 UTC, hermabe approved these changes

2024-05-21 11:46 UTC, Thalley approved these changes

2024-05-21 19:42 UTC, aescolar approved these changes

2024-05-21 20:45 UTC, merged