drivers: entropy: stm32 entropy driver add semaphore protection
zephyrproject-rtos/zephyr pull request #72882
Opened 2024-05-16 13:56 UTC by FRASTM

Add a semaphore to protect the disable access to the RNG peripheral when the PM is going to suspend mode.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/72640

2024-05-16 15:14 UTC, erwango requested changes
Issue is that in `release_rng` following is done:
```
	entropy_stm32_suspend();
#if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
	z_stm32_hsem_unlock(CFG_HW_RNG_SEMID);
#endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
```
So current implementation will end up with 2 consecutive `z_stm32_hsem_unlock`.

To take this into account, what about:
Calling `release_rng` instead of `entropy_stm32_suspend` and call lock semaphore before calls in `entropy_stm32_rng_pm_action`.

(maybe some function renaming would be required in the end to make all this more clear)

2024-06-03 15:14 UTC, FRASTM commented
change as suggested

2024-06-04 07:17 UTC, erwango approved these changes

2024-06-04 07:59 UTC, gautierg-st approved these changes

2024-06-04 11:37 UTC, merged