drivers: i2c: Add support for Apollo3 SoCs I2C
zephyrproject-rtos/zephyr pull request #72913
Opened 2024-05-17 07:37 UTC by AlessandroLuo

This commit adds support for the I2C which
can be found in Apollo3 SoCs, it can work in
both DMA and non-DMA modes

2024-05-17 13:35 UTC, teburd requested changes

2024-05-17 13:35 UTC, teburd commented on drivers/i2c/i2c_ambiq.c
> +static __aligned(32) uint32_t I2CDMATCBBuffer[CONFIG_I2C_DMA_TCB_BUFFER_SIZE]
No camel case please

2024-05-17 13:35 UTC, teburd commented on drivers/i2c/i2c_ambiq.c
> +static void pfnI2C_Callback(void *pCallbackCtxt, uint32_t status)
no camel case please

2024-05-17 13:35 UTC, teburd commented on drivers/i2c/i2c_ambiq.c
> +		LOG_ERR("Timeout waiting for transfer complete");
This isn't a real hardware timeout, if someone tries to reuse this device immediately after the timeout, what happens? Would it correctly reinitialize without causing faults?

2024-05-17 13:35 UTC, teburd commented on drivers/i2c/i2c_ambiq.c
> +	config->pwr_func();
if pwr_func() is fallible (as it seems to be given the ret = prior to this change, that should likely be accounted for

2024-05-17 21:08 UTC, teburd submitted a review, later dismissed

2024-05-20 02:00 UTC, aaronyegx submitted a review, later dismissed
Looks good to me.

2024-05-21 02:16 UTC, aaronyegx approved these changes

2024-05-21 13:22 UTC, teburd approved these changes

2024-05-21 13:25 UTC, RichardSWheatley approved these changes
Looks good!

LGTM

2024-05-22 00:55 UTC, merged