Bluetooth samples: Fix broadcast source device name
zephyrproject-rtos/zephyr pull request #72915
Opened 2024-05-17 07:54 UTC by jthm-ot

The device name explicitly added in the advertising data.

2024-05-17 08:34 UTC, Thalley requested changes
Nice catch. I want to suggest that we, instead of having 2 advertising data sets (`ad` and `ext_ad`), we only keep one of them.

2024-05-21 07:54 UTC, larsgk approved these changes

2024-05-21 08:10 UTC, Thalley approved these changes

2024-05-22 10:16 UTC, jhedberg approved these changes

2024-05-22 18:45 UTC, merged