include: drivers: gpio: fix gpio_dt_flags_t overflow
zephyrproject-rtos/zephyr pull request #72946
Opened 2024-05-17 13:53 UTC by ajarmouni-st

when `GPIO_INT_WAKEUP` flag is used in a DT `gpios` property the `gpio_dt_flags_t` var that holds the flags overflows.

2024-05-17 14:50 UTC, ubieda commented on include/zephyr/drivers/gpio.h
> +typedef uint32_t gpio_dt_flags_t;
Should we also update the description?

2024-05-22 07:55 UTC, henrikbrixandersen requested changes
Why not simply move `GPIO_INT_WAKEUP` to bit 6?

2024-05-22 12:51 UTC, ubieda approved these changes

2024-05-22 13:32 UTC, henrikbrixandersen requested changes
Looks good, but please update the commit message to describe this new solution better.

2024-05-22 13:38 UTC, henrikbrixandersen approved these changes

2024-05-22 17:08 UTC, mmahadevan108 approved these changes

2024-05-28 15:53 UTC, merged