boards: arm: doc: Add I2C feature and serial port section
zephyrproject-rtos/zephyr pull request #730
Opened 2017-07-09 13:46 UTC by ydamigos

This patch add I2C to supported features of 96b_carbon,
nucleof401re and olimexino_stm32.

It also adds serial port section to 96b_carbon and olimexino_stm32

Signed-off-by: Yannis Damigos <giannis.damigos@gmail.com>

2017-07-10 07:10 UTC, erwango requested changes
Let's add the I2C pinmux configuration for these boards.
Otherwise, sounds good.

2017-07-10 07:58 UTC, ydamigos commented
Added I2C section with Zephyr's default I2C mapping.

2017-07-10 12:50 UTC, ydamigos commented
Something is wrong with Shippable. It was not triggered correctly after the PR update.

2017-07-10 16:16 UTC, dbkinder approved these changes
LGTM

2017-07-11 15:07 UTC, erwango approved these changes

2017-07-11 16:39 UTC, merged