CI: Fix Coverage Analysis.
zephyrproject-rtos/zephyr pull request #73029
Opened 2024-05-20 14:42 UTC by gbarkadiusz

FIX: The coverage_analysis.py while generating report, duplicates some files and functions of components.
e.g for bluetooth.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/122030181/8cad63e2-13b6-4e9d-9d01-01419eb06020)

After the fix.
![image](https://github.com/zephyrproject-rtos/zephyr/assets/122030181/f15bdb82-5428-4141-91eb-8764758c83f1)

2024-05-21 07:35 UTC, arikgreen requested changes

2024-05-21 07:35 UTC, arikgreen commented on scripts/ci/coverage/coverage_analysis.py
> +        return False
```suggestion
        res = [x for x in json_list if x['Name'] == new_file['Name']]
        return res
```

2024-05-21 08:21 UTC, arikgreen requested changes

2024-05-21 08:21 UTC, arikgreen commented on scripts/ci/coverage/coverage_analysis.py
> +                                    if not self.is_duplicate(json_file, json_files):
```suggestion
                                    comp_exists = [x for x in json_files if x['Name'] == json_file['Name']]
                                    if not comp_exists:
```

2024-05-21 08:21 UTC, arikgreen commented on scripts/ci/coverage/coverage_analysis.py
> +
```suggestion
   
```

2024-05-21 08:38 UTC, gbarkadiusz commented
@arikgreen  Please take a look again.

2024-05-21 10:34 UTC, arikgreen submitted a review, later dismissed

2024-05-22 07:32 UTC, arikgreen approved these changes

2024-05-28 17:14 UTC, nashif approved these changes

2024-05-29 05:33 UTC, merged