bluetooth: keys_br: Improve bt_foreach_bond
zephyrproject-rtos/zephyr pull request #73167
Opened 2024-05-22 13:33 UTC by lylezhu2012

The BR Keys cannot be scanned by function bt_foreach_bond.

Add function bt_foreach_bond_br for br.

The function bt_foreach_bond_br will be called by bt_foreach_bond if the BR is enabled.

2024-05-22 14:02 UTC, Thalley requested changes
a few minor things

2024-05-22 14:02 UTC, Thalley commented on subsys/bluetooth/host/classic/keys_br.c
> +					   void *user_data), void *user_data)
Indentation is off here

2024-05-22 14:02 UTC, Thalley commented on subsys/bluetooth/host/classic/keys_br.c
> +		struct bt_keys_link_key *key = &key_pool[i];
```suggestion
		const struct bt_keys_link_key *key = &key_pool[i];
```

2024-05-22 14:02 UTC, Thalley commented on subsys/bluetooth/host/keys.h
> +					   void *user_data), void *user_data);
Ditto with indentation

2024-05-23 03:05 UTC, lylezhu2012 commented on subsys/bluetooth/host/classic/keys_br.c
> +	for (i = 0; i < ARRAY_SIZE(key_pool); i++) {
Updated

2024-05-23 03:05 UTC, lylezhu2012 commented on subsys/bluetooth/host/classic/keys_br.c
> +		struct bt_keys_link_key *key = &key_pool[i];
Updated

2024-05-23 03:05 UTC, lylezhu2012 commented on subsys/bluetooth/host/keys.h
> +					   void *user_data), void *user_data);
Updated

2024-05-23 03:06 UTC, lylezhu2012 commented on subsys/bluetooth/host/classic/keys_br.c
> +					   void *user_data), void *user_data)
Updated

2024-05-23 07:26 UTC, Thalley approved these changes

2024-05-25 07:38 UTC, jhedberg approved these changes

2024-05-25 11:38 UTC, jori-nordic approved these changes

2024-05-25 18:39 UTC, merged