sensors: ccs811: Implement sampling mode switching
zephyrproject-rtos/zephyr pull request #7320
Opened 2018-05-02 22:55 UTC by tkln

CCS811 measurement mode selection is implemented with sensor attributes.
A new measurement interval sensor attribute is introduced.

2018-05-03 15:38 UTC, Mani-Sadhasivam reviewed
Hi @tkln,

Overall it looks good. Just one query inline.

2018-05-03 15:38 UTC, Mani-Sadhasivam commented on drivers/sensor/ccs811/ccs811.c
> +	} else {
Not implementing `CCS811_MODE_RAW_DATA`? It might be useful in some cases.

2018-05-06 12:27 UTC, tkln commented
@Mani-Sadhasivam I've not implemented switching to Mode 4 because SENSOR_CHAN_CO2 and SENSOR_CHAN_VOC readings cannot be used in Mode 4. I'm mostly just interested in changing the measurement mode due to the lower power consumption of the other modes.

2018-05-06 13:00 UTC, Mani-Sadhasivam commented
@tkln SInce we support `CURRENT` and `VOLTAGE` measurements in the driver, the corresponding mode should also be enabled. I can't figure out a valid usecase for this but it would be good to have.

2018-05-12 20:09 UTC, tkln commented
@Mani-Sadhasivam I've now added Mode 4 and also made the polling delays to adjust accordingly with the measurement time.

2018-06-02 04:04 UTC, Mani-Sadhasivam commented on drivers/sensor/ccs811/ccs811.c
> +		mode = CCS811_MODE_IAQ_60SEC;
Should be CCS811_MODE_RAW_DATA?

2018-06-02 04:05 UTC, Mani-Sadhasivam requested changes
Looks like you haven't updated the mode in setting!

2019-12-19 12:40 UTC, closed without merging