Bluetooth: Host: more secure defaults for key size and legacy pairing
zephyrproject-rtos/zephyr pull request #73217
Opened 2024-05-23 12:45 UTC by seko-nordic

Default the Minimum encryption key size to 16.
Key with reduced size is easier to brut force.
Disable LE legacy pairing by default since it's not secure.

These defaults should suite majority of newly developed applications. It's better to use sensible more secure defaults,
so applications that really need less secure option consciously change it, not the other way around.
This may help to prevent downgrade attacks.

2024-05-23 13:00 UTC, sjanc commented
I'm fine with tuning defaults but bluetooth tester configuration should be updated to accommodate this

2024-05-23 13:01 UTC, sjanc commented
#AutoPTS run zephyr nrf52 SM

2024-05-23 13:09 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2127051353, board: nrf52, estimated start time: 15:10:09, test case count: 657, estimated duration: 11:00:15<details><summary>Test cases to be run</summary>MBT/SR/BT/BV-01-C<br>MBT/SR/BT/BV-02-C<br>MBT/SR/BT/BV-03-C<br>MBT/SR/BT/BV-04-C<br>MBT/SR/BT/BV-05-C<br>MBT/SR/BT/BV-06-C<br>MBT/SR/BT/BV-07-C<br>MBT/SR/BT/BV-08-C<br>MBT/SR/BT/BV-09-C<br>MBT/SR/BT/BV-10-C<br>MBT/SR/BT/BV-11-C<br>MBT/SR/BT/BV-12-C<br>MBT/SR/BT/BV-13-C<br>MBT/SR/BT/BV-14-C<br>MBT/SR/BT/BV-15-C<br>MBT/SR/BT/BV-16-C<br>MBT/SR/BT/BV-17-C<br>MBT/SR/BT/BV-18-C<br>MBT/SR/BT/BV-19-C<br>MBT/SR/BT/BV-20-C<br>MBT/SR/BT/BV-21-C<br>MBT/SR/BT/BV-22-C<br>MBT/SR/BT/BV-23-C<br>MBT/SR/BT/BV-24-C<br>MBT/SR/BT/BV-25-C<br>MBT/SR/BT/BV-26-C<br>MBT/SR/BT/BV-27-C<br>MBT/SR/BT/BV-28-C<br>MBT/SR/BT/BV-29-C<br>MBT/SR/BT/BV-30-C<br>MBT/SR/BT/BV-31-C<br>MBT/SR/BT/BV-32-C<br>MBT/SR/BT/BV-33-C<br>MBT/SR/BT/BV-34-C<br>MBT/SR/BT/BV-35-C<br>MBT/SR/BT/BV-36-C<br>MBT/SR/BT/BV-37-C<br>MBT/SR/BT/BV-38-C<br>MBT/SR/BT/BI-01-C<br>MBT/SR/BT/BI-02-C<br>MBT/CL/BT/BV-01-C<br>MBT/CL/BT/BV-02-C<br>MBT/CL/BT/BV-03-C<br>MBT/CL/BT/BV-04-C<br>MBT/CL/BT/BV-05-C<br>MBT/CL/BT/BV-06-C<br>MBT/CL/BT/BV-07-C<br>MBT/CL/BT/BV-08-C<br>MCP/CL/CGGIT/SER/BV-02-C<br>MCP/CL/CGGIT/SER/BV-03-C<br>MCP/CL/CGGIT/CHA/BV-23-C<br>MCP/CL/CGGIT/CHA/BV-02-C<br>MCP/CL/CGGIT/CHA/BV-03-C<br>MCP/CL/CGGIT/CHA/BV-04-C<br>MCP/CL/CGGIT/CHA/BV-05-C<br>MCP/CL/CGGIT/CHA/BV-06-C<br>MCP/CL/CGGIT/CHA/BV-07-C<br>MCP/CL/CGGIT/CHA/BV-08-C<br>MCP/CL/CGGIT/CHA/BV-09-C<br>MCP/CL/CGGIT/CHA/BV-10-C<br>MCP/CL/CGGIT/CHA/BV-11-C<br>MCP/CL/CGGIT/CHA/BV-12-C<br>MCP/CL/CGGIT/CHA/BV-13-C<br>MCP/CL/CGGIT/CHA/BV-14-C<br>MCP/CL/CGGIT/CHA/BV-15-C<br>MCP/CL/CGGIT/CHA/BV-16-C<br>MCP/CL/CGGIT/CHA/BV-17-C<br>MCP/CL/CGGIT/CHA/BV-18-C<br>MCP/CL/CGGIT/CHA/BV-19-C<br>MCP/CL/CGGIT/CHA/BV-20-C<br>MCP/CL/CGGIT/CHA/BV-21-C<br>MCP/CL/CGGIT/CHA/BV-22-C<br>MCP/CL/MCCP/BV-01-C<br>MCP/CL/MCCP/BV-02-C<br>MCP/CL/MCCP/BV-03-C<br>MCP/CL/MCCP/BV-04-C<br>MCP/CL/MCCP/BV-05-C<br>MCP/CL/MCCP/BV-06-C<br>MCP/CL/MCCP/BV-07-C<br>MCP/CL/MCCP/BV-08-C<br>MCP/CL/MCCP/BV-09-C<br>MCP/CL/MCCP/BV-10-C<br>MCP/CL/MCCP/BV-11-C<br>MCP/CL/MCCP/BV-12-C<br>MCP/CL/MCCP/BV-13-C<br>MCP/CL/MCCP/BV-14-C<br>MCP/CL/MCCP/BV-15-C<br>MCP/CL/MCCP/BV-16-C<br>MCP/CL/MCCP/BV-17-C<br>MCP/CL/MCCP/BV-18-C<br>MCP/CL/MCCP/BV-19-C<br>MCP/CL/MCCP/BV-20-C<br>MCP/CL/MCCP/BV-21-C<br>MCP/SR/SP/BV-01-C<br>MCP/CL/SCP/BV-01-C<br>MCP/CL/SCP/BV-02-C<br>MCP/CL/SCP/BV-03-C<br>MCP/CL/SCP/BV-04-C<br>MCP/CL/SCP/BV-05-C<br>MCP/CL/SCP/BV-06-C<br>MCP/CL/SCP/BV-07-C<br>MCP/CL/SCP/BV-08-C<br>MCP/CL/SCP/BV-09-C<br>MCP/CL/SPE/BI-01-C<br>MCP/CL/SPE/BI-02-C<br>MESH/NODE/PBADV/BV-01-C<br>MESH/NODE/PBADV/BV-02-C<br>MESH/NODE/PBADV/BV-03-C<br>MESH/NODE/PBADV/BV-04-C<br>MESH/PVNR/PBADV/BV-01-C<br>MESH/PVNR/PBADV/BV-02-C<br>MESH/PVNR/PBADV/BV-03-C<br>MESH/PVNR/PBADV/BI-01-C<br>MESH/NODE/PBADV/BI-01-C<br>MESH/NODE/PBADV/BI-02-C<br>MESH/NODE/PBADV/BI-03-C<br>MESH/NODE/PBADV/BI-04-C<br>MESH/NODE/MPS/BV-01-C<br>MESH/NODE/MPS/BV-02-C<br>MESH/NODE/MPS/BV-03-C<br>MESH/NODE/MPS/BV-04-C<br>MESH/NODE/MPS/BV-05-C<br>MESH/NODE/MPS/BV-06-C<br>MESH/NODE/MPS/BV-07-C<br>MESH/NODE/MPS/BV-08-C<br>MESH/NODE/MPS/BV-09-C<br>MESH/NODE/MPS/BV-10-C<br>MESH/NODE/MPS/BI-01-C<br>MESH/PVNR/MPS/BV-01-C<br>MESH/PVNR/MPS/BV-02-C<br>MESH/PVNR/MPS/BV-03-C<br>MESH/PVNR/MPS/BV-04-C<br>MESH/PVNR/MPS/BV-05-C<br>MESH/PVNR/MPS/BV-06-C<br>MESH/PVNR/MPS/BV-08-C<br>MESH/PVNR/MPS/BV-09-C<br>MESH/NODE/PROV/BV-07-C<br>MESH/NODE/PROV/BV-08-C<br>MESH/NODE/PROV/BV-13-C<br>MESH/NODE/PROV/BV-14-C<br>MESH/NODE/PROV/BV-15-C<br>MESH/NODE/PROV/BV-16-C<br>MESH/NODE/PROV/BV-17-C<br>MESH/NODE/PROV/BV-18-C<br>MESH/NODE/PROV/BV-19-C<br>MESH/NODE/PROV/BV-20-C<br>MESH/NODE/PROV/BV-09-C<br>MESH/NODE/PROV/BV-10-C<br>MESH/NODE/PROV/BV-11-C<br>MESH/NODE/PROV/BV-12-C<br>MESH/NODE/PROV/BI-01-C<br>MESH/NODE/PROV/BI-02-C<br>MESH/NODE/PROV/BI-03-C<br>MESH/NODE/PROV/BI-13-C<br>MESH/NODE/PROV/BI-15-C<br>MESH/NODE/PROV/BI-17-C<br>MESH/PVNR/PROV/BV-01-C<br>MESH/PVNR/PROV/BV-02-C<br>MESH/PVNR/PROV/BV-03-C<br>MESH/PVNR/PROV/BV-04-C<br>MESH/PVNR/PROV/BV-05-C<br>MESH/PVNR/PROV/BV-06-C<br>MESH/PVNR/PROV/BV-07-C<br>MESH/PVNR/PROV/BV-08-C<br>MESH/PVNR/PROV/BV-11-C<br>MESH/PVNR/PROV/BV-12-C<br>MESH/PVNR/PROV/BV-13-C<br>MESH/PVNR/PROV/BV-14-C<br>MESH/PVNR/PROV/BV-15-C<br>MESH/PVNR/PROV/BV-16-C<br>MESH/PVNR/PROV/BV-17-C<br>MESH/PVNR/PROV/BV-18-C<br>MESH/PVNR/PROV/BV-09-C<br>MESH/PVNR/PROV/BV-10-C<br>MESH/PVNR/PROV/BI-14-C<br>MESH/PVNR/PROV/BI-16-C<br>MESH/PVNR/PROV/BI-18-C<br>MESH/NODE/BCN/SNB/BV-01-C<br>MESH/NODE/BCN/PRB/BV-01-C<br>MESH/NODE/BCN/PRB/BV-02-C<br>MESH/NODE/NET/BV-01-C<br>MESH/NODE/NET/BV-02-C<br>MESH/NODE/NET/BV-03-C<br>MESH/NODE/NET/BV-04-C<br>MESH/NODE/NET/BV-05-C<br>MESH/NODE/NET/BV-06-C<br>MESH/NODE/NET/BV-07-C<br>MESH/NODE/NET/BV-08-C<br>MESH/NODE/NET/BV-09-C<br>MESH/NODE/NET/BV-10-C<br>MESH/NODE/NET/BV-11-C<br>MESH/NODE/NET/BV-12-C<br>MESH/NODE/NET/BV-13-C<br>MESH/NODE/NET/BV-14-C<br>MESH/NODE/NET/BI-01-C<br>MESH/NODE/NET/BI-02-C<br>MESH/NODE/NET/BI-03-C<br>MESH/NODE/RLY/BV-01-C<br>MESH/NODE/RLY/BV-02-C<br>MESH/NODE/RLY/BI-01-C<br>MESH/NODE/RLY/BI-02-C<br>MESH/NODE/TNPT/BV-01-C<br>MESH/NODE/TNPT/BV-02-C<br>MESH/NODE/TNPT/BV-03-C<br>MESH/NODE/TNPT/BV-04-C<br>MESH/NODE/TNPT/BV-05-C<br>MESH/NODE/TNPT/BV-06-C<br>MESH/NODE/TNPT/BV-07-C<br>MESH/NODE/TNPT/BV-08-C<br>MESH/NODE/TNPT/BV-09-C<br>MESH/NODE/TNPT/BV-10-C<br>MESH/NODE/TNPT/BV-11-C<br>MESH/NODE/TNPT/BV-13-C<br>MESH/NODE/TNPT/BI-01-C<br>MESH/NODE/TNPT/BI-02-C<br>MESH/NODE/TNPT/BV-14-C<br>MESH/NODE/TNPT/BV-15-C<br>MESH/NODE/TNPT/BV-16-C<br>MESH/NODE/TNPT/BV-17-C<br>MESH/NODE/TNPT/BV-18-C<br>MESH/NODE/TNPT/BV-19-C<br>MESH/NODE/TNPT/BV-20-C<br>MESH/NODE/TNPT/BV-21-C<br>MESH/NODE/TNPT/BI-03-C<br>MESH/NODE/IVU/BV-01-C<br>MESH/NODE/IVU/BV-06-C<br>MESH/NODE/IVU/BV-02-C<br>MESH/NODE/IVU/BV-07-C<br>MESH/NODE/IVU/BV-03-C<br>MESH/NODE/IVU/BV-08-C<br>MESH/NODE/IVU/BV-04-C<br>MESH/NODE/IVU/BV-09-C<br>MESH/NODE/IVU/BV-05-C<br>MESH/NODE/IVU/BV-10-C<br>MESH/NODE/IVU/BI-01-C<br>MESH/NODE/IVU/BI-07-C<br>MESH/NODE/IVU/BI-02-C<br>MESH/NODE/IVU/BI-08-C<br>MESH/NODE/IVU/BI-04-C<br>MESH/NODE/IVU/BI-09-C<br>MESH/NODE/IVU/BI-05-C<br>MESH/NODE/IVU/BI-10-C<br>MESH/NODE/IVU/BI-06-C<br>MESH/NODE/IVU/BI-11-C<br>MESH/NODE/KR/BV-01-C<br>MESH/NODE/KR/BV-02-C<br>MESH/NODE/KR/BV-04-C<br>MESH/NODE/KR/BV-03-C<br>MESH/NODE/KR/BV-05-C<br>MESH/CFGCL/KR/BV-01-C<br>MESH/CFGCL/KR/BV-02-C<br>MESH/CFGCL/KR/BV-05-C<br>MESH/CFGCL/KR/BV-03-C<br>MESH/CFGCL/KR/BV-04-C<br>MESH/CFGCL/KR/BV-06-C<br>MESH/NODE/KR/BI-01-C<br>MESH/NODE/KR/BI-02-C<br>MESH/NODE/KR/BI-03-C<br>MESH/NODE/KR/BI-04-C<br>MESH/NODE/KR/BI-05-C<br>MESH/NODE/KR/BI-06-C<br>MESH/NODE/FRND/FN/BV-01-C<br>MESH/NODE/FRND/FN/BV-02-C<br>MESH/NODE/FRND/FN/BV-03-C<br>MESH/NODE/FRND/FN/BV-04-C<br>MESH/NODE/FRND/FN/BV-24-C<br>MESH/NODE/FRND/FN/BV-05-C<br>MESH/NODE/FRND/FN/BV-06-C<br>MESH/NODE/FRND/FN/BV-07-C<br>MESH/NODE/FRND/FN/BV-08-C<br>MESH/NODE/FRND/FN/BV-09-C<br>MESH/NODE/FRND/FN/BV-10-C<br>MESH/NODE/FRND/FN/BV-11-C<br>MESH/NODE/FRND/FN/BV-12-C<br>MESH/NODE/FRND/FN/BV-13-C<br>MESH/NODE/FRND/FN/BV-14-C<br>MESH/NODE/FRND/FN/BV-25-C<br>MESH/NODE/FRND/FN/BV-15-C<br>MESH/NODE/FRND/FN/BV-16-C<br>MESH/NODE/FRND/FN/BV-17-C<br>MESH/NODE/FRND/FN/BV-18-C<br>MESH/NODE/FRND/FN/BV-19-C<br>MESH/NODE/FRND/FN/BV-20-C<br>MESH/NODE/FRND/FN/BV-26-C<br>MESH/NODE/FRND/FN/BV-21-C<br>MESH/NODE/FRND/FN/BV-22-C<br>MESH/NODE/FRND/FN/BV-23-C<br>MESH/NODE/FRND/FN/BI-01-C<br>MESH/NODE/FRND/FN/BI-02-C<br>MESH/NODE/FRND/FN/BI-03-C<br>MESH/NODE/FRND/LPN/BV-01-C<br>MESH/NODE/FRND/LPN/BV-02-C<br>MESH/NODE/FRND/LPN/BV-03-C<br>MESH/NODE/FRND/LPN/BV-04-C<br>MESH/NODE/FRND/LPN/BV-05-C<br>MESH/NODE/FRND/LPN/BV-06-C<br>MESH/NODE/FRND/LPN/BV-07-C<br>MESH/NODE/FRND/LPN/BV-08-C<br>MESH/NODE/FRND/LPN/BI-01-C<br>MESH/NODE/FRND/LPN/BI-02-C<br>MESH/NODE/FRND/LPN/BI-03-C<br>MESH/SR/PROX/BV-01-C<br>MESH/SR/PROX/BV-02-C<br>MESH/SR/PROX/BV-16-C<br>MESH/SR/PROX/BV-03-C<br>MESH/SR/PROX/BV-04-C<br>MESH/SR/PROX/BV-17-C<br>MESH/SR/PROX/BV-05-C<br>MESH/SR/ [...]

2024-05-23 13:10 UTC, codecoup-tester commented
Job triggered with https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2127051353 has been canceled

2024-05-23 13:15 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2127051353, board: nrf52, estimated start time: 15:16:55, test case count: 657, estimated duration: 11:00:15<details><summary>Test cases to be run</summary>MBT/SR/BT/BV-01-C<br>MBT/SR/BT/BV-02-C<br>MBT/SR/BT/BV-03-C<br>MBT/SR/BT/BV-04-C<br>MBT/SR/BT/BV-05-C<br>MBT/SR/BT/BV-06-C<br>MBT/SR/BT/BV-07-C<br>MBT/SR/BT/BV-08-C<br>MBT/SR/BT/BV-09-C<br>MBT/SR/BT/BV-10-C<br>MBT/SR/BT/BV-11-C<br>MBT/SR/BT/BV-12-C<br>MBT/SR/BT/BV-13-C<br>MBT/SR/BT/BV-14-C<br>MBT/SR/BT/BV-15-C<br>MBT/SR/BT/BV-16-C<br>MBT/SR/BT/BV-17-C<br>MBT/SR/BT/BV-18-C<br>MBT/SR/BT/BV-19-C<br>MBT/SR/BT/BV-20-C<br>MBT/SR/BT/BV-21-C<br>MBT/SR/BT/BV-22-C<br>MBT/SR/BT/BV-23-C<br>MBT/SR/BT/BV-24-C<br>MBT/SR/BT/BV-25-C<br>MBT/SR/BT/BV-26-C<br>MBT/SR/BT/BV-27-C<br>MBT/SR/BT/BV-28-C<br>MBT/SR/BT/BV-29-C<br>MBT/SR/BT/BV-30-C<br>MBT/SR/BT/BV-31-C<br>MBT/SR/BT/BV-32-C<br>MBT/SR/BT/BV-33-C<br>MBT/SR/BT/BV-34-C<br>MBT/SR/BT/BV-35-C<br>MBT/SR/BT/BV-36-C<br>MBT/SR/BT/BV-37-C<br>MBT/SR/BT/BV-38-C<br>MBT/SR/BT/BI-01-C<br>MBT/SR/BT/BI-02-C<br>MBT/CL/BT/BV-01-C<br>MBT/CL/BT/BV-02-C<br>MBT/CL/BT/BV-03-C<br>MBT/CL/BT/BV-04-C<br>MBT/CL/BT/BV-05-C<br>MBT/CL/BT/BV-06-C<br>MBT/CL/BT/BV-07-C<br>MBT/CL/BT/BV-08-C<br>MCP/CL/CGGIT/SER/BV-02-C<br>MCP/CL/CGGIT/SER/BV-03-C<br>MCP/CL/CGGIT/CHA/BV-23-C<br>MCP/CL/CGGIT/CHA/BV-02-C<br>MCP/CL/CGGIT/CHA/BV-03-C<br>MCP/CL/CGGIT/CHA/BV-04-C<br>MCP/CL/CGGIT/CHA/BV-05-C<br>MCP/CL/CGGIT/CHA/BV-06-C<br>MCP/CL/CGGIT/CHA/BV-07-C<br>MCP/CL/CGGIT/CHA/BV-08-C<br>MCP/CL/CGGIT/CHA/BV-09-C<br>MCP/CL/CGGIT/CHA/BV-10-C<br>MCP/CL/CGGIT/CHA/BV-11-C<br>MCP/CL/CGGIT/CHA/BV-12-C<br>MCP/CL/CGGIT/CHA/BV-13-C<br>MCP/CL/CGGIT/CHA/BV-14-C<br>MCP/CL/CGGIT/CHA/BV-15-C<br>MCP/CL/CGGIT/CHA/BV-16-C<br>MCP/CL/CGGIT/CHA/BV-17-C<br>MCP/CL/CGGIT/CHA/BV-18-C<br>MCP/CL/CGGIT/CHA/BV-19-C<br>MCP/CL/CGGIT/CHA/BV-20-C<br>MCP/CL/CGGIT/CHA/BV-21-C<br>MCP/CL/CGGIT/CHA/BV-22-C<br>MCP/CL/MCCP/BV-01-C<br>MCP/CL/MCCP/BV-02-C<br>MCP/CL/MCCP/BV-03-C<br>MCP/CL/MCCP/BV-04-C<br>MCP/CL/MCCP/BV-05-C<br>MCP/CL/MCCP/BV-06-C<br>MCP/CL/MCCP/BV-07-C<br>MCP/CL/MCCP/BV-08-C<br>MCP/CL/MCCP/BV-09-C<br>MCP/CL/MCCP/BV-10-C<br>MCP/CL/MCCP/BV-11-C<br>MCP/CL/MCCP/BV-12-C<br>MCP/CL/MCCP/BV-13-C<br>MCP/CL/MCCP/BV-14-C<br>MCP/CL/MCCP/BV-15-C<br>MCP/CL/MCCP/BV-16-C<br>MCP/CL/MCCP/BV-17-C<br>MCP/CL/MCCP/BV-18-C<br>MCP/CL/MCCP/BV-19-C<br>MCP/CL/MCCP/BV-20-C<br>MCP/CL/MCCP/BV-21-C<br>MCP/SR/SP/BV-01-C<br>MCP/CL/SCP/BV-01-C<br>MCP/CL/SCP/BV-02-C<br>MCP/CL/SCP/BV-03-C<br>MCP/CL/SCP/BV-04-C<br>MCP/CL/SCP/BV-05-C<br>MCP/CL/SCP/BV-06-C<br>MCP/CL/SCP/BV-07-C<br>MCP/CL/SCP/BV-08-C<br>MCP/CL/SCP/BV-09-C<br>MCP/CL/SPE/BI-01-C<br>MCP/CL/SPE/BI-02-C<br>MESH/NODE/PBADV/BV-01-C<br>MESH/NODE/PBADV/BV-02-C<br>MESH/NODE/PBADV/BV-03-C<br>MESH/NODE/PBADV/BV-04-C<br>MESH/PVNR/PBADV/BV-01-C<br>MESH/PVNR/PBADV/BV-02-C<br>MESH/PVNR/PBADV/BV-03-C<br>MESH/PVNR/PBADV/BI-01-C<br>MESH/NODE/PBADV/BI-01-C<br>MESH/NODE/PBADV/BI-02-C<br>MESH/NODE/PBADV/BI-03-C<br>MESH/NODE/PBADV/BI-04-C<br>MESH/NODE/MPS/BV-01-C<br>MESH/NODE/MPS/BV-02-C<br>MESH/NODE/MPS/BV-03-C<br>MESH/NODE/MPS/BV-04-C<br>MESH/NODE/MPS/BV-05-C<br>MESH/NODE/MPS/BV-06-C<br>MESH/NODE/MPS/BV-07-C<br>MESH/NODE/MPS/BV-08-C<br>MESH/NODE/MPS/BV-09-C<br>MESH/NODE/MPS/BV-10-C<br>MESH/NODE/MPS/BI-01-C<br>MESH/PVNR/MPS/BV-01-C<br>MESH/PVNR/MPS/BV-02-C<br>MESH/PVNR/MPS/BV-03-C<br>MESH/PVNR/MPS/BV-04-C<br>MESH/PVNR/MPS/BV-05-C<br>MESH/PVNR/MPS/BV-06-C<br>MESH/PVNR/MPS/BV-08-C<br>MESH/PVNR/MPS/BV-09-C<br>MESH/NODE/PROV/BV-07-C<br>MESH/NODE/PROV/BV-08-C<br>MESH/NODE/PROV/BV-13-C<br>MESH/NODE/PROV/BV-14-C<br>MESH/NODE/PROV/BV-15-C<br>MESH/NODE/PROV/BV-16-C<br>MESH/NODE/PROV/BV-17-C<br>MESH/NODE/PROV/BV-18-C<br>MESH/NODE/PROV/BV-19-C<br>MESH/NODE/PROV/BV-20-C<br>MESH/NODE/PROV/BV-09-C<br>MESH/NODE/PROV/BV-10-C<br>MESH/NODE/PROV/BV-11-C<br>MESH/NODE/PROV/BV-12-C<br>MESH/NODE/PROV/BI-01-C<br>MESH/NODE/PROV/BI-02-C<br>MESH/NODE/PROV/BI-03-C<br>MESH/NODE/PROV/BI-13-C<br>MESH/NODE/PROV/BI-15-C<br>MESH/NODE/PROV/BI-17-C<br>MESH/PVNR/PROV/BV-01-C<br>MESH/PVNR/PROV/BV-02-C<br>MESH/PVNR/PROV/BV-03-C<br>MESH/PVNR/PROV/BV-04-C<br>MESH/PVNR/PROV/BV-05-C<br>MESH/PVNR/PROV/BV-06-C<br>MESH/PVNR/PROV/BV-07-C<br>MESH/PVNR/PROV/BV-08-C<br>MESH/PVNR/PROV/BV-11-C<br>MESH/PVNR/PROV/BV-12-C<br>MESH/PVNR/PROV/BV-13-C<br>MESH/PVNR/PROV/BV-14-C<br>MESH/PVNR/PROV/BV-15-C<br>MESH/PVNR/PROV/BV-16-C<br>MESH/PVNR/PROV/BV-17-C<br>MESH/PVNR/PROV/BV-18-C<br>MESH/PVNR/PROV/BV-09-C<br>MESH/PVNR/PROV/BV-10-C<br>MESH/PVNR/PROV/BI-14-C<br>MESH/PVNR/PROV/BI-16-C<br>MESH/PVNR/PROV/BI-18-C<br>MESH/NODE/BCN/SNB/BV-01-C<br>MESH/NODE/BCN/PRB/BV-01-C<br>MESH/NODE/BCN/PRB/BV-02-C<br>MESH/NODE/NET/BV-01-C<br>MESH/NODE/NET/BV-02-C<br>MESH/NODE/NET/BV-03-C<br>MESH/NODE/NET/BV-04-C<br>MESH/NODE/NET/BV-05-C<br>MESH/NODE/NET/BV-06-C<br>MESH/NODE/NET/BV-07-C<br>MESH/NODE/NET/BV-08-C<br>MESH/NODE/NET/BV-09-C<br>MESH/NODE/NET/BV-10-C<br>MESH/NODE/NET/BV-11-C<br>MESH/NODE/NET/BV-12-C<br>MESH/NODE/NET/BV-13-C<br>MESH/NODE/NET/BV-14-C<br>MESH/NODE/NET/BI-01-C<br>MESH/NODE/NET/BI-02-C<br>MESH/NODE/NET/BI-03-C<br>MESH/NODE/RLY/BV-01-C<br>MESH/NODE/RLY/BV-02-C<br>MESH/NODE/RLY/BI-01-C<br>MESH/NODE/RLY/BI-02-C<br>MESH/NODE/TNPT/BV-01-C<br>MESH/NODE/TNPT/BV-02-C<br>MESH/NODE/TNPT/BV-03-C<br>MESH/NODE/TNPT/BV-04-C<br>MESH/NODE/TNPT/BV-05-C<br>MESH/NODE/TNPT/BV-06-C<br>MESH/NODE/TNPT/BV-07-C<br>MESH/NODE/TNPT/BV-08-C<br>MESH/NODE/TNPT/BV-09-C<br>MESH/NODE/TNPT/BV-10-C<br>MESH/NODE/TNPT/BV-11-C<br>MESH/NODE/TNPT/BV-13-C<br>MESH/NODE/TNPT/BI-01-C<br>MESH/NODE/TNPT/BI-02-C<br>MESH/NODE/TNPT/BV-14-C<br>MESH/NODE/TNPT/BV-15-C<br>MESH/NODE/TNPT/BV-16-C<br>MESH/NODE/TNPT/BV-17-C<br>MESH/NODE/TNPT/BV-18-C<br>MESH/NODE/TNPT/BV-19-C<br>MESH/NODE/TNPT/BV-20-C<br>MESH/NODE/TNPT/BV-21-C<br>MESH/NODE/TNPT/BI-03-C<br>MESH/NODE/IVU/BV-01-C<br>MESH/NODE/IVU/BV-06-C<br>MESH/NODE/IVU/BV-02-C<br>MESH/NODE/IVU/BV-07-C<br>MESH/NODE/IVU/BV-03-C<br>MESH/NODE/IVU/BV-08-C<br>MESH/NODE/IVU/BV-04-C<br>MESH/NODE/IVU/BV-09-C<br>MESH/NODE/IVU/BV-05-C<br>MESH/NODE/IVU/BV-10-C<br>MESH/NODE/IVU/BI-01-C<br>MESH/NODE/IVU/BI-07-C<br>MESH/NODE/IVU/BI-02-C<br>MESH/NODE/IVU/BI-08-C<br>MESH/NODE/IVU/BI-04-C<br>MESH/NODE/IVU/BI-09-C<br>MESH/NODE/IVU/BI-05-C<br>MESH/NODE/IVU/BI-10-C<br>MESH/NODE/IVU/BI-06-C<br>MESH/NODE/IVU/BI-11-C<br>MESH/NODE/KR/BV-01-C<br>MESH/NODE/KR/BV-02-C<br>MESH/NODE/KR/BV-04-C<br>MESH/NODE/KR/BV-03-C<br>MESH/NODE/KR/BV-05-C<br>MESH/CFGCL/KR/BV-01-C<br>MESH/CFGCL/KR/BV-02-C<br>MESH/CFGCL/KR/BV-05-C<br>MESH/CFGCL/KR/BV-03-C<br>MESH/CFGCL/KR/BV-04-C<br>MESH/CFGCL/KR/BV-06-C<br>MESH/NODE/KR/BI-01-C<br>MESH/NODE/KR/BI-02-C<br>MESH/NODE/KR/BI-03-C<br>MESH/NODE/KR/BI-04-C<br>MESH/NODE/KR/BI-05-C<br>MESH/NODE/KR/BI-06-C<br>MESH/NODE/FRND/FN/BV-01-C<br>MESH/NODE/FRND/FN/BV-02-C<br>MESH/NODE/FRND/FN/BV-03-C<br>MESH/NODE/FRND/FN/BV-04-C<br>MESH/NODE/FRND/FN/BV-24-C<br>MESH/NODE/FRND/FN/BV-05-C<br>MESH/NODE/FRND/FN/BV-06-C<br>MESH/NODE/FRND/FN/BV-07-C<br>MESH/NODE/FRND/FN/BV-08-C<br>MESH/NODE/FRND/FN/BV-09-C<br>MESH/NODE/FRND/FN/BV-10-C<br>MESH/NODE/FRND/FN/BV-11-C<br>MESH/NODE/FRND/FN/BV-12-C<br>MESH/NODE/FRND/FN/BV-13-C<br>MESH/NODE/FRND/FN/BV-14-C<br>MESH/NODE/FRND/FN/BV-25-C<br>MESH/NODE/FRND/FN/BV-15-C<br>MESH/NODE/FRND/FN/BV-16-C<br>MESH/NODE/FRND/FN/BV-17-C<br>MESH/NODE/FRND/FN/BV-18-C<br>MESH/NODE/FRND/FN/BV-19-C<br>MESH/NODE/FRND/FN/BV-20-C<br>MESH/NODE/FRND/FN/BV-26-C<br>MESH/NODE/FRND/FN/BV-21-C<br>MESH/NODE/FRND/FN/BV-22-C<br>MESH/NODE/FRND/FN/BV-23-C<br>MESH/NODE/FRND/FN/BI-01-C<br>MESH/NODE/FRND/FN/BI-02-C<br>MESH/NODE/FRND/FN/BI-03-C<br>MESH/NODE/FRND/LPN/BV-01-C<br>MESH/NODE/FRND/LPN/BV-02-C<br>MESH/NODE/FRND/LPN/BV-03-C<br>MESH/NODE/FRND/LPN/BV-04-C<br>MESH/NODE/FRND/LPN/BV-05-C<br>MESH/NODE/FRND/LPN/BV-06-C<br>MESH/NODE/FRND/LPN/BV-07-C<br>MESH/NODE/FRND/LPN/BV-08-C<br>MESH/NODE/FRND/LPN/BI-01-C<br>MESH/NODE/FRND/LPN/BI-02-C<br>MESH/NODE/FRND/LPN/BI-03-C<br>MESH/SR/PROX/BV-01-C<br>MESH/SR/PROX/BV-02-C<br>MESH/SR/PROX/BV-16-C<br>MESH/SR/PROX/BV-03-C<br>MESH/SR/PROX/BV-04-C<br>MESH/SR/PROX/BV-17-C<br>MESH/SR/PROX/BV-05-C<br>MESH/SR/ [...]

2024-05-23 13:36 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2127051353, board: nrf52, estimated start time: 15:37:22, test case count: 70, estimated duration: 0:22:16<details><summary>Test cases to be run</summary>SM/CEN/PROT/BV-01-C<br>SM/CEN/JW/BV-05-C<br>SM/CEN/JW/BI-04-C<br>SM/CEN/JW/BI-01-C<br>SM/CEN/PKE/BV-01-C<br>SM/CEN/PKE/BV-04-C<br>SM/CEN/PKE/BI-01-C<br>SM/CEN/PKE/BI-02-C<br>SM/CEN/OOB/BV-01-C<br>SM/CEN/OOB/BV-03-C<br>SM/CEN/OOB/BV-09-C<br>SM/CEN/OOB/BI-01-C<br>SM/CEN/EKS/BV-01-C<br>SM/CEN/EKS/BI-01-C<br>SM/CEN/SIGN/BV-01-C<br>SM/CEN/SIGN/BV-03-C<br>SM/CEN/SIGN/BI-01-C<br>SM/CEN/KDU/BV-04-C<br>SM/CEN/KDU/BV-05-C<br>SM/CEN/KDU/BV-06-C<br>SM/CEN/KDU/BV-10-C<br>SM/CEN/KDU/BV-11-C<br>SM/CEN/KDU/BI-01-C<br>SM/CEN/SIP/BV-02-C<br>SM/CEN/SCJW/BV-01-C<br>SM/CEN/SCJW/BV-04-C<br>SM/CEN/SCJW/BI-01-C<br>SM/CEN/SCPK/BV-01-C<br>SM/CEN/SCPK/BV-04-C<br>SM/CEN/SCPK/BI-01-C<br>SM/CEN/SCPK/BI-02-C<br>SM/CEN/SCOB/BV-01-C<br>SM/CEN/SCOB/BV-04-C<br>SM/CEN/SCOB/BI-01-C<br>SM/CEN/SCOB/BI-04-C<br>SM/PER/PROT/BV-02-C<br>SM/PER/JW/BV-02-C<br>SM/PER/JW/BI-03-C<br>SM/PER/JW/BI-02-C<br>SM/PER/PKE/BV-02-C<br>SM/PER/PKE/BV-05-C<br>SM/PER/PKE/BI-03-C<br>SM/PER/OOB/BV-02-C<br>SM/PER/OOB/BV-04-C<br>SM/PER/OOB/BV-10-C<br>SM/PER/OOB/BI-02-C<br>SM/PER/EKS/BV-02-C<br>SM/PER/EKS/BI-02-C<br>SM/PER/KDU/BV-01-C<br>SM/PER/KDU/BV-02-C<br>SM/PER/KDU/BV-03-C<br>SM/PER/KDU/BV-07-C<br>SM/PER/KDU/BV-08-C<br>SM/PER/KDU/BV-09-C<br>SM/PER/KDU/BI-01-C<br>SM/PER/KDU/BI-02-C<br>SM/PER/KDU/BI-03-C<br>SM/PER/SIP/BV-01-C<br>SM/PER/SIE/BV-01-C<br>SM/PER/SCJW/BV-02-C<br>SM/PER/SCJW/BV-03-C<br>SM/PER/SCJW/BI-02-C<br>SM/PER/SCPK/BV-02-C<br>SM/PER/SCPK/BV-03-C<br>SM/PER/SCPK/BI-03-C<br>SM/PER/SCPK/BI-04-C<br>SM/PER/SCOB/BV-02-C<br>SM/PER/SCOB/BV-03-C<br>SM/PER/SCOB/BI-02-C<br>SM/PER/SCOB/BI-03-C</details>

2024-05-23 13:59 UTC, Thalley requested changes
I am OK with the changes, but we need to add this to migration guide, as it is likely to break a lot of applications that use legacy pairing.

2024-05-23 14:21 UTC, codecoup-tester commented
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/EKS/BV-01-C              PASS<br>SM      SM/CEN/JW/BI-01-C               PASS<br>SM      SM/CEN/JW/BI-04-C               PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BI-01-C              PASS<br>SM      SM/CEN/KDU/BV-04-C              PASS<br>SM      SM/CEN/KDU/BV-05-C              PASS<br>SM      SM/CEN/KDU/BV-06-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/KDU/BV-11-C              PASS<br>SM      SM/CEN/OOB/BI-01-C              PASS<br>SM      SM/CEN/OOB/BV-01-C              PASS<br>SM      SM/CEN/OOB/BV-03-C              PASS<br>SM      SM/CEN/OOB/BV-09-C              PASS<br>SM      SM/CEN/PKE/BI-01-C              PASS<br>SM      SM/CEN/PKE/BI-02-C              PASS<br>SM      SM/CEN/PKE/BV-01-C              PASS<br>SM      SM/CEN/PKE/BV-04-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/CEN/SIGN/BI-01-C             PASS<br>SM      SM/CEN/SIGN/BV-01-C             PASS<br>SM      SM/CEN/SIGN/BV-03-C             PASS<br>SM      SM/CEN/SIP/BV-02-C              PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/EKS/BV-02-C              PASS<br>SM      SM/PER/JW/BI-02-C               PASS<br>SM      SM/PER/JW/BI-03-C               PASS<br>SM      SM/PER/JW/BV-02-C               PASS<br>SM      SM/PER/KDU/BI-01-C              PASS<br>SM      SM/PER/KDU/BI-02-C              PASS<br>SM      SM/PER/KDU/BI-03-C              PASS<br>SM      SM/PER/KDU/BV-01-C              PASS<br>SM      SM/PER/KDU/BV-02-C              PASS<br>SM      SM/PER/KDU/BV-03-C              PASS<br>SM      SM/PER/KDU/BV-07-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/KDU/BV-09-C              PASS<br>SM      SM/PER/OOB/BI-02-C              PASS<br>SM      SM/PER/OOB/BV-02-C              PASS<br>SM      SM/PER/OOB/BV-04-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PKE/BI-03-C              PASS<br>SM      SM/PER/PKE/BV-02-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/PROT/BV-02-C             PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS<br>SM      SM/PER/SIE/BV-01-C              PASS<br>SM      SM/PER/SIP/BV-01-C              PASS</details>

2024-05-24 09:49 UTC, jhedberg requested changes

2024-05-24 09:49 UTC, jhedberg commented on subsys/bluetooth/host/Kconfig
> +	default y
This change should be mentioned in `doc/releases/migration-guide-3.7.rst`

2024-05-24 09:50 UTC, jhedberg commented on subsys/bluetooth/host/Kconfig
> +	default y
Ah, I see @Thalley already pointed it out :)

2024-05-24 11:49 UTC, sjanc commented
#AutoPTS run zephyr nrf52 SM/PER/KDU/BV-03-C

2024-05-24 11:50 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2129336290, board: nrf52, estimated start time: 13:51:03, test case count: 2374, estimated duration: 1 day, 7:30:49<details><summary>Test cases to be run</summary>AICS/SR/SGGIT/SER/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-02-C<br>AICS/SR/SGGIT/CHA/BV-03-C<br>AICS/SR/SGGIT/CHA/BV-04-C<br>AICS/SR/SGGIT/CHA/BV-05-C<br>AICS/SR/SGGIT/CHA/BV-06-C<br>AICS/SR/SGGIT/CP/BI-01-C<br>AICS/SR/SGGIT/CP/BI-02-C<br>AICS/SR/SGGIT/CP/BI-03-C<br>AICS/SR/SGGIT/CP/BI-04-C<br>AICS/SR/SPN/BV-01-C<br>AICS/SR/SPN/BV-02-C<br>AICS/SR/CP/BV-01-C<br>AICS/SR/CP/BV-02-C<br>AICS/SR/CP/BV-03-C<br>AICS/SR/CP/BV-04-C<br>AICS/SR/CP/BV-05-C<br>AICS/SR/SPE/BI-01-C<br>ASCS/SR/SGGIT/SER/BV-01-C<br>ASCS/SR/SGGIT/CHA/BV-01-C<br>ASCS/SR/SGGIT/CHA/BV-02-C<br>ASCS/SR/SGGIT/CHA/BV-03-C<br>ASCS/SR/ASR/BV-01-C<br>ASCS/SR/ACP/BV-01-C<br>ASCS/SR/ACP/BV-02-C<br>ASCS/SR/ACP/BV-03-C<br>ASCS/SR/ACP/BV-04-C<br>ASCS/SR/ACP/BV-05-C<br>ASCS/SR/ACP/BV-06-C<br>ASCS/SR/ACP/BV-07-C<br>ASCS/SR/ACP/BV-08-C<br>ASCS/SR/ACP/BV-09-C<br>ASCS/SR/ACP/BV-10-C<br>ASCS/SR/ACP/BV-11-C<br>ASCS/SR/ACP/BV-12-C<br>ASCS/SR/ACP/BV-13-C<br>ASCS/SR/ACP/BV-14-C<br>ASCS/SR/ACP/BV-15-C<br>ASCS/SR/ACP/BV-16-C<br>ASCS/SR/ACP/BV-17-C<br>ASCS/SR/ACP/BV-18-C<br>ASCS/SR/ACP/BV-19-C<br>ASCS/SR/ACP/BV-20-C<br>ASCS/SR/ACP/BV-21-C<br>ASCS/SR/ACP/BV-22-C<br>ASCS/SR/ACP/BV-23-C<br>ASCS/SR/ACP/BV-24-C<br>ASCS/SR/ACP/BV-25-C<br>ASCS/SR/ACP/BV-26-C<br>ASCS/SR/ACP/BV-27-C<br>ASCS/SR/ACP/BV-28-C<br>ASCS/SR/ACP/BV-29-C<br>ASCS/SR/ACP/BV-30-C<br>ASCS/SR/ACP/BV-31-C<br>ASCS/SR/SPE/BI-01-C<br>ASCS/SR/SPE/BI-02-C<br>ASCS/SR/SPE/BI-03-C<br>ASCS/SR/SPE/BI-04-C<br>ASCS/SR/SPE/BI-05-C<br>ASCS/SR/SPE/BI-06-C<br>ASCS/SR/SPE/BI-07-C<br>ASCS/SR/SPE/BI-08-C<br>ASCS/SR/SPE/BI-09-C<br>ASCS/SR/SPE/BI-10-C<br>ASCS/SR/SPE/BI-11-C<br>ASCS/SR/SPE/BI-12-C<br>ASCS/SR/SPE/BI-13-C<br>ASCS/SR/SPE/BI-14-C<br>ASCS/SR/SPE/BI-15-C<br>ASCS/SR/SPE/BI-16-C<br>ASCS/SR/SPE/BI-17-C<br>ASCS/SR/SPE/BI-18-C<br>ASCS/SR/SPE/BI-19-C<br>ASCS/SR/SPE/BI-20-C<br>BAP/CL/CGGIT/SER/BV-01-C<br>BAP/CL/CGGIT/CHA/BV-01-C<br>BAP/CL/CGGIT/CHA/BV-02-C<br>BAP/CL/CGGIT/CHA/BV-03-C<br>BAP/CL/CGGIT/CHA/BV-04-C<br>BAP/CL/CGGIT/CHA/BV-05-C<br>BAP/CL/CGGIT/CHA/BV-06-C<br>BAP/UCL/CGGIT/SER/BV-01-C<br>BAP/UCL/CGGIT/CHA/BV-01-C<br>BAP/UCL/CGGIT/CHA/BV-02-C<br>BAP/UCL/CGGIT/CHA/BV-03-C<br>BAP/UCL/DISC/BV-01-C<br>BAP/UCL/DISC/BV-02-C<br>BAP/UCL/DISC/BV-03-C<br>BAP/UCL/DISC/BV-04-C<br>BAP/UCL/DISC/BV-05-C<br>BAP/UCL/DISC/BV-06-C<br>BAP/UCL/ADV/BV-01-C<br>BAP/UCL/SCC/BV-001-C<br>BAP/UCL/SCC/BV-002-C<br>BAP/UCL/SCC/BV-003-C<br>BAP/UCL/SCC/BV-004-C<br>BAP/UCL/SCC/BV-005-C<br>BAP/UCL/SCC/BV-006-C<br>BAP/UCL/SCC/BV-007-C<br>BAP/UCL/SCC/BV-008-C<br>BAP/UCL/SCC/BV-009-C<br>BAP/UCL/SCC/BV-010-C<br>BAP/UCL/SCC/BV-011-C<br>BAP/UCL/SCC/BV-012-C<br>BAP/UCL/SCC/BV-013-C<br>BAP/UCL/SCC/BV-014-C<br>BAP/UCL/SCC/BV-015-C<br>BAP/UCL/SCC/BV-016-C<br>BAP/UCL/SCC/BV-017-C<br>BAP/UCL/SCC/BV-018-C<br>BAP/UCL/SCC/BV-019-C<br>BAP/UCL/SCC/BV-020-C<br>BAP/UCL/SCC/BV-021-C<br>BAP/UCL/SCC/BV-022-C<br>BAP/UCL/SCC/BV-023-C<br>BAP/UCL/SCC/BV-024-C<br>BAP/UCL/SCC/BV-025-C<br>BAP/UCL/SCC/BV-026-C<br>BAP/UCL/SCC/BV-027-C<br>BAP/UCL/SCC/BV-028-C<br>BAP/UCL/SCC/BV-029-C<br>BAP/UCL/SCC/BV-030-C<br>BAP/UCL/SCC/BV-031-C<br>BAP/UCL/SCC/BV-032-C<br>BAP/UCL/SCC/BV-033-C<br>BAP/UCL/SCC/BV-034-C<br>BAP/UCL/SCC/BV-035-C<br>BAP/UCL/SCC/BV-036-C<br>BAP/UCL/SCC/BV-037-C<br>BAP/UCL/SCC/BV-038-C<br>BAP/UCL/SCC/BV-039-C<br>BAP/UCL/SCC/BV-040-C<br>BAP/UCL/SCC/BV-041-C<br>BAP/UCL/SCC/BV-042-C<br>BAP/UCL/SCC/BV-043-C<br>BAP/UCL/SCC/BV-044-C<br>BAP/UCL/SCC/BV-045-C<br>BAP/UCL/SCC/BV-046-C<br>BAP/UCL/SCC/BV-047-C<br>BAP/UCL/SCC/BV-048-C<br>BAP/UCL/SCC/BV-049-C<br>BAP/UCL/SCC/BV-050-C<br>BAP/UCL/SCC/BV-051-C<br>BAP/UCL/SCC/BV-052-C<br>BAP/UCL/SCC/BV-053-C<br>BAP/UCL/SCC/BV-054-C<br>BAP/UCL/SCC/BV-055-C<br>BAP/UCL/SCC/BV-056-C<br>BAP/UCL/SCC/BV-057-C<br>BAP/UCL/SCC/BV-058-C<br>BAP/UCL/SCC/BV-059-C<br>BAP/UCL/SCC/BV-060-C<br>BAP/UCL/SCC/BV-061-C<br>BAP/UCL/SCC/BV-062-C<br>BAP/UCL/SCC/BV-063-C<br>BAP/UCL/SCC/BV-064-C<br>BAP/UCL/SCC/BV-065-C<br>BAP/UCL/SCC/BV-066-C<br>BAP/UCL/SCC/BV-067-C<br>BAP/UCL/SCC/BV-068-C<br>BAP/UCL/SCC/BV-069-C<br>BAP/UCL/SCC/BV-070-C<br>BAP/UCL/SCC/BV-071-C<br>BAP/UCL/SCC/BV-072-C<br>BAP/UCL/SCC/BV-073-C<br>BAP/UCL/SCC/BV-074-C<br>BAP/UCL/SCC/BV-075-C<br>BAP/UCL/SCC/BV-076-C<br>BAP/UCL/SCC/BV-077-C<br>BAP/UCL/SCC/BV-078-C<br>BAP/UCL/SCC/BV-079-C<br>BAP/UCL/SCC/BV-080-C<br>BAP/UCL/SCC/BV-081-C<br>BAP/UCL/SCC/BV-082-C<br>BAP/UCL/SCC/BV-083-C<br>BAP/UCL/SCC/BV-084-C<br>BAP/UCL/SCC/BV-085-C<br>BAP/UCL/SCC/BV-086-C<br>BAP/UCL/SCC/BV-087-C<br>BAP/UCL/SCC/BV-088-C<br>BAP/UCL/SCC/BV-089-C<br>BAP/UCL/SCC/BV-090-C<br>BAP/UCL/SCC/BV-091-C<br>BAP/UCL/SCC/BV-092-C<br>BAP/UCL/SCC/BV-093-C<br>BAP/UCL/SCC/BV-094-C<br>BAP/UCL/SCC/BV-095-C<br>BAP/UCL/SCC/BV-096-C<br>BAP/UCL/SCC/BV-097-C<br>BAP/UCL/SCC/BV-098-C<br>BAP/UCL/SCC/BV-099-C<br>BAP/UCL/SCC/BV-100-C<br>BAP/UCL/SCC/BV-101-C<br>BAP/UCL/SCC/BV-102-C<br>BAP/UCL/SCC/BV-103-C<br>BAP/UCL/SCC/BV-104-C<br>BAP/UCL/SCC/BV-105-C<br>BAP/UCL/SCC/BV-106-C<br>BAP/UCL/SCC/BV-107-C<br>BAP/UCL/SCC/BV-108-C<br>BAP/UCL/SCC/BV-109-C<br>BAP/UCL/SCC/BV-110-C<br>BAP/UCL/SCC/BV-111-C<br>BAP/UCL/SCC/BV-112-C<br>BAP/UCL/SCC/BV-113-C<br>BAP/UCL/SCC/BV-115-C<br>BAP/UCL/SCC/BV-116-C<br>BAP/UCL/SCC/BV-117-C<br>BAP/UCL/PD/BV-01-C<br>BAP/UCL/PD/BV-02-C<br>BAP/UCL/PD/BV-03-C<br>BAP/UCL/PD/BV-04-C<br>BAP/UCL/STR/BV-535-C<br>BAP/UCL/STR/BV-552-C<br>BAP/UCL/STR/BV-553-C<br>BAP/UCL/STR/BV-554-C<br>BAP/UCL/STR/BV-555-C<br>BAP/UCL/STR/BV-536-C<br>BAP/UCL/STR/BV-537-C<br>BAP/UCL/STR/BV-556-C<br>BAP/UCL/STR/BV-557-C<br>BAP/UCL/STR/BV-558-C<br>BAP/UCL/STR/BV-559-C<br>BAP/UCL/STR/BV-538-C<br>BAP/UCL/STR/BV-523-C<br>BAP/UCL/STR/BV-524-C<br>BAP/UCL/STR/BV-525-C<br>BAP/UCL/STR/BV-526-C<br>BAP/UCL/STR/BV-527-C<br>BAP/UCL/STR/BV-528-C<br>BAP/UCL/STR/BV-529-C<br>BAP/UCL/STR/BV-530-C<br>BAP/UCL/STR/BV-531-C<br>BAP/UCL/STR/BV-532-C<br>BAP/UCL/STR/BV-533-C<br>BAP/UCL/STR/BV-534-C<br>BAP/USR/DISC/BV-01-C<br>BAP/USR/DISC/BV-02-C<br>BAP/USR/DISC/BV-05-C<br>BAP/USR/DISC/BV-06-C<br>BAP/USR/DISC/BV-07-C<br>BAP/USR/ADV/BV-01-C<br>BAP/USR/ADV/BV-04-C<br>BAP/USR/SCC/BV-001-C<br>BAP/USR/SCC/BV-002-C<br>BAP/USR/SCC/BV-003-C<br>BAP/USR/SCC/BV-004-C<br>BAP/USR/SCC/BV-005-C<br>BAP/USR/SCC/BV-006-C<br>BAP/USR/SCC/BV-007-C<br>BAP/USR/SCC/BV-008-C<br>BAP/USR/SCC/BV-009-C<br>BAP/USR/SCC/BV-010-C<br>BAP/USR/SCC/BV-011-C<br>BAP/USR/SCC/BV-012-C<br>BAP/USR/SCC/BV-013-C<br>BAP/USR/SCC/BV-014-C<br>BAP/USR/SCC/BV-015-C<br>BAP/USR/SCC/BV-016-C<br>BAP/USR/SCC/BV-017-C<br>BAP/USR/SCC/BV-018-C<br>BAP/USR/SCC/BV-019-C<br>BAP/USR/SCC/BV-020-C<br>BAP/USR/SCC/BV-021-C<br>BAP/USR/SCC/BV-022-C<br>BAP/USR/SCC/BV-023-C<br>BAP/USR/SCC/BV-024-C<br>BAP/USR/SCC/BV-025-C<br>BAP/USR/SCC/BV-026-C<br>BAP/USR/SCC/BV-027-C<br>BAP/USR/SCC/BV-028-C<br>BAP/USR/SCC/BV-029-C<br>BAP/USR/SCC/BV-030-C<br>BAP/USR/SCC/BV-031-C<br>BAP/USR/SCC/BV-032-C<br>BAP/USR/SCC/BV-033-C<br>BAP/USR/SCC/BV-034-C<br>BAP/USR/SCC/BV-035-C<br>BAP/USR/SCC/BV-036-C<br>BAP/USR/SCC/BV-037-C<br>BAP/USR/SCC/BV-038-C<br>BAP/USR/SCC/BV-039-C<br>BAP/USR/SCC/BV-040-C<br>BAP/USR/SCC/BV-041-C<br>BAP/USR/SCC/BV-042-C<br>BAP/USR/SCC/BV-043-C<br>BAP/USR/SCC/BV-044-C<br>BAP/USR/SCC/BV-045-C<br>BAP/USR/SCC/BV-046-C<br>BAP/USR/SCC/BV-047-C<br>BAP/USR/SCC/BV-048-C<br>BAP/USR/SCC/BV-049-C<br>BAP/USR/SCC/BV-050-C<br>BAP/USR/SCC/BV-051-C<br>BAP/USR/SCC/BV-052-C<br>BAP/USR/SCC/BV-053-C<br>BAP/USR/SCC/BV-054-C<br>BAP/USR/SCC/BV-055-C<br>BAP/USR/SCC/BV-056-C<br>BAP/USR/SCC/BV-057-C<br>BAP/USR/SCC/BV-058-C<br>BAP/USR/SCC/BV-059-C<br>BAP/USR/SCC/BV-060-C<br>BAP/USR/SCC/BV-061-C<br>BAP/USR/SCC/BV-062-C<br>BAP/USR/SCC/BV-063-C<br>BAP/USR/SCC/BV-064-C<br>BAP/USR/SCC/BV-065-C<br>BAP/USR/SCC/BV-066-C<br>BAP/USR/SCC/BV-067-C<br>BAP/USR/SCC/BV-068-C<br>BAP/USR/SCC/BV-069-C<br>BAP/USR/SCC/BV-070-C<br>BAP/USR/SCC/BV-071-C<br>BAP/USR/SCC/BV-072-C<br>BAP/USR/SCC/BV-073-C<br>BAP/USR/SCC/BV-074-C<br>BAP/USR/SCC/BV-075-C<br>BAP/USR/SCC/BV-076-C<br>BAP/USR/SCC/BV-077-C<br>BAP/USR/ [...]

2024-05-24 11:50 UTC, codecoup-tester commented
Job triggered with https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2129336290 has been canceled

2024-05-24 11:58 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2129336290, board: nrf52, estimated start time: 13:59:48, test case count: 1, estimated duration: 0:00:17<details><summary>Test cases to be run</summary>SM/PER/KDU/BV-03-C</details>

2024-05-24 12:09 UTC, codecoup-tester commented
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>SM      SM/PER/KDU/BV-03-C              PASS</details>

2024-05-24 12:24 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2129336290, board: nrf52, estimated start time: 14:25:11, test case count: 1, estimated duration: 0:00:17<details><summary>Test cases to be run</summary>SM/PER/KDU/BV-03-C</details>

2024-05-24 12:36 UTC, codecoup-tester commented
AutoPTS Bot results:
<details><summary>Failed tests</summary>SM      SM/PER/KDU/BV-03-C              INCONC</details>

2024-05-24 14:16 UTC, codecoup-tester commented
AutoPTS Bot results:
<details><summary>Failed tests</summary>SM      SM/CEN/EKS/BV-01-C              INCONC<br>SM      SM/CEN/JW/BI-01-C               FAIL<br>SM      SM/CEN/JW/BI-04-C               INCONC<br>SM      SM/CEN/KDU/BV-04-C              INCONC<br>SM      SM/CEN/KDU/BV-05-C              INCONC<br>SM      SM/CEN/KDU/BV-06-C              INCONC<br>SM      SM/CEN/OOB/BI-01-C              FAIL<br>SM      SM/CEN/OOB/BV-01-C              INCONC<br>SM      SM/CEN/OOB/BV-03-C              INCONC<br>SM      SM/CEN/OOB/BV-09-C              INCONC<br>SM      SM/CEN/PKE/BI-01-C              FATAL ERROR<br>SM      SM/CEN/PKE/BI-02-C              FATAL ERROR<br>SM      SM/CEN/PKE/BV-01-C              INCONC<br>SM      SM/CEN/PKE/BV-04-C              INCONC<br>SM      SM/CEN/SIGN/BI-01-C             INCONC<br>SM      SM/CEN/SIGN/BV-01-C             INCONC<br>SM      SM/CEN/SIGN/BV-03-C             INCONC<br>SM      SM/CEN/SIP/BV-02-C              FAIL<br>SM      SM/PER/EKS/BV-02-C              INCONC<br>SM      SM/PER/JW/BI-02-C               INCONC<br>SM      SM/PER/JW/BI-03-C               INCONC<br>SM      SM/PER/JW/BV-02-C               INCONC<br>SM      SM/PER/KDU/BI-02-C              INCONC<br>SM      SM/PER/KDU/BV-01-C              INCONC<br>SM      SM/PER/KDU/BV-02-C              INCONC<br>SM      SM/PER/KDU/BV-03-C              INCONC<br>SM      SM/PER/KDU/BV-07-C              INCONC<br>SM      SM/PER/OOB/BI-02-C              INCONC<br>SM      SM/PER/OOB/BV-02-C              INCONC<br>SM      SM/PER/OOB/BV-04-C              INCONC<br>SM      SM/PER/PKE/BI-03-C              INCONC<br>SM      SM/PER/PKE/BV-02-C              INCONC<br>SM      SM/PER/PROT/BV-02-C             INCONC<br>SM      SM/PER/SIE/BV-01-C              INCONC<br>SM      SM/PER/SIP/BV-01-C              INCONC</details>
<details><summary>Successful tests</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BI-01-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/KDU/BV-11-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/KDU/BI-01-C              PASS<br>SM      SM/PER/KDU/BI-03-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/KDU/BV-09-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS</details>

2024-11-26 14:51 UTC, seko-nordic commented
> #AutoPTS run zephyr nrf52 SM

@sjanc can you rerun PTS please

2024-11-26 16:14 UTC, Thalley commented
#AutoPTS run zephyr nrf52 SM

2024-11-26 16:14 UTC, codecoup-tester commented
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/73217#issuecomment-2501280745, board: nrf52, estimated start time: 17:15:54, test case count: 71, estimated duration: 0:23:03<details><summary>Test cases to be run</summary>SM/CEN/PROT/BV-01-C<br>SM/CEN/JW/BV-05-C<br>SM/CEN/JW/BI-04-C<br>SM/CEN/JW/BI-01-C<br>SM/CEN/PKE/BV-01-C<br>SM/CEN/PKE/BV-04-C<br>SM/CEN/PKE/BI-01-C<br>SM/CEN/PKE/BI-02-C<br>SM/CEN/OOB/BV-01-C<br>SM/CEN/OOB/BV-03-C<br>SM/CEN/OOB/BV-09-C<br>SM/CEN/OOB/BI-01-C<br>SM/CEN/EKS/BV-01-C<br>SM/CEN/EKS/BI-01-C<br>SM/CEN/SIGN/BV-01-C<br>SM/CEN/SIGN/BV-03-C<br>SM/CEN/SIGN/BI-01-C<br>SM/CEN/KDU/BV-04-C<br>SM/CEN/KDU/BV-05-C<br>SM/CEN/KDU/BV-06-C<br>SM/CEN/KDU/BV-10-C<br>SM/CEN/KDU/BV-11-C<br>SM/CEN/KDU/BI-04-C<br>SM/CEN/PIS/BV-02-C<br>SM/CEN/PIS/BV-03-C<br>SM/CEN/SCJW/BV-01-C<br>SM/CEN/SCJW/BV-04-C<br>SM/CEN/SCJW/BI-01-C<br>SM/CEN/SCPK/BV-01-C<br>SM/CEN/SCPK/BV-04-C<br>SM/CEN/SCPK/BI-01-C<br>SM/CEN/SCPK/BI-02-C<br>SM/CEN/SCOB/BV-01-C<br>SM/CEN/SCOB/BV-04-C<br>SM/CEN/SCOB/BI-01-C<br>SM/CEN/SCOB/BI-04-C<br>SM/PER/PROT/BV-02-C<br>SM/PER/JW/BV-02-C<br>SM/PER/JW/BI-03-C<br>SM/PER/JW/BI-02-C<br>SM/PER/PKE/BV-02-C<br>SM/PER/PKE/BV-05-C<br>SM/PER/PKE/BI-03-C<br>SM/PER/OOB/BV-02-C<br>SM/PER/OOB/BV-04-C<br>SM/PER/OOB/BV-10-C<br>SM/PER/OOB/BI-02-C<br>SM/PER/EKS/BV-02-C<br>SM/PER/EKS/BI-02-C<br>SM/PER/KDU/BV-01-C<br>SM/PER/KDU/BV-02-C<br>SM/PER/KDU/BV-03-C<br>SM/PER/KDU/BV-07-C<br>SM/PER/KDU/BV-08-C<br>SM/PER/KDU/BV-09-C<br>SM/PER/KDU/BI-02-C<br>SM/PER/KDU/BI-03-C<br>SM/PER/KDU/BI-04-C<br>SM/PER/PIS/BV-01-C<br>SM/PER/PIS/BV-02-C<br>SM/PER/SCJW/BV-02-C<br>SM/PER/SCJW/BV-03-C<br>SM/PER/SCJW/BI-02-C<br>SM/PER/SCPK/BV-02-C<br>SM/PER/SCPK/BV-03-C<br>SM/PER/SCPK/BI-03-C<br>SM/PER/SCPK/BI-04-C<br>SM/PER/SCOB/BV-02-C<br>SM/PER/SCOB/BV-03-C<br>SM/PER/SCOB/BI-02-C<br>SM/PER/SCOB/BI-03-C</details>

2024-11-26 17:03 UTC, codecoup-tester commented
AutoPTS Bot results:
<details><summary>Failed tests (2)</summary>SM      SM/CEN/KDU/BI-04-C              FAIL<br>SM      SM/PER/KDU/BI-04-C              FAIL</details>
<details><summary>Successful tests (69)</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/EKS/BV-01-C              PASS<br>SM      SM/CEN/JW/BI-01-C               PASS<br>SM      SM/CEN/JW/BI-04-C               PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BV-04-C              PASS<br>SM      SM/CEN/KDU/BV-05-C              PASS<br>SM      SM/CEN/KDU/BV-06-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/KDU/BV-11-C              PASS<br>SM      SM/CEN/OOB/BI-01-C              PASS<br>SM      SM/CEN/OOB/BV-01-C              PASS<br>SM      SM/CEN/OOB/BV-03-C              PASS<br>SM      SM/CEN/OOB/BV-09-C              PASS<br>SM      SM/CEN/PIS/BV-02-C              PASS<br>SM      SM/CEN/PIS/BV-03-C              PASS<br>SM      SM/CEN/PKE/BI-01-C              PASS<br>SM      SM/CEN/PKE/BI-02-C              PASS<br>SM      SM/CEN/PKE/BV-01-C              PASS<br>SM      SM/CEN/PKE/BV-04-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/CEN/SIGN/BI-01-C             PASS<br>SM      SM/CEN/SIGN/BV-01-C             PASS<br>SM      SM/CEN/SIGN/BV-03-C             PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/EKS/BV-02-C              PASS<br>SM      SM/PER/JW/BI-02-C               PASS<br>SM      SM/PER/JW/BI-03-C               PASS<br>SM      SM/PER/JW/BV-02-C               PASS<br>SM      SM/PER/KDU/BI-02-C              PASS<br>SM      SM/PER/KDU/BI-03-C              PASS<br>SM      SM/PER/KDU/BV-01-C              PASS<br>SM      SM/PER/KDU/BV-02-C              PASS<br>SM      SM/PER/KDU/BV-03-C              PASS<br>SM      SM/PER/KDU/BV-07-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/KDU/BV-09-C              PASS<br>SM      SM/PER/OOB/BI-02-C              PASS<br>SM      SM/PER/OOB/BV-02-C              PASS<br>SM      SM/PER/OOB/BV-04-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PIS/BV-01-C              PASS<br>SM      SM/PER/PIS/BV-02-C              PASS<br>SM      SM/PER/PKE/BI-03-C              PASS<br>SM      SM/PER/PKE/BV-02-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/PROT/BV-02-C             PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS</details>

2024-11-26 17:36 UTC, Thalley commented
@seko-nordic the 2 failing PTS tests are failing on `main` as well, so not related to this PR

2024-11-26 17:38 UTC, Thalley submitted a review, later dismissed

2024-11-26 20:46 UTC, sjanc approved these changes, later dismissed

2024-11-26 21:34 UTC, jhedberg submitted a review, later dismissed

2024-11-28 12:59 UTC, jhedberg submitted a review, later dismissed

2024-11-28 13:04 UTC, Thalley approved these changes, later dismissed

2024-11-28 15:03 UTC, alwa-nordic submitted a review, later dismissed

2024-12-03 12:33 UTC, jhedberg approved these changes

2024-12-03 12:45 UTC, theob-pro approved these changes

2024-12-03 16:18 UTC, Thalley approved these changes

2024-12-03 18:09 UTC, sjanc approved these changes

2024-12-04 08:29 UTC, alwa-nordic approved these changes

2024-12-04 11:10 UTC, merged