drivers: sensor: bosch: add support for bmp180
zephyrproject-rtos/zephyr pull request #73218
Opened 2024-05-23 12:46 UTC by jovicjakov

This PR aims to add driver support for the Bosch BMP180 digital pressure and temperature sensor.

2024-05-23 13:03 UTC, kartben submitted a review, later dismissed
some early comments. thanks for this new driver!

2024-05-23 13:03 UTC, kartben commented on samples/sensor/bmp180/src/main.c
please just drop this sample altogether as it's not adding anything useful compared to e.g. sensor_shell sample which folks can use to quickly test their sensor.

2024-05-23 14:36 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/bmp180.c
> +		LOG_ERR("Failed to start the temperature measurement.");
will do

2024-05-23 14:37 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/bmp180.c
> +		val->val2 = 0;
good catch, thanks

2024-05-23 14:37 UTC, jovicjakov commented on samples/sensor/bmp180/src/main.c
I agree, I'll remove the commit

2024-05-28 14:31 UTC, decsny approved these changes, later dismissed

2024-05-28 16:41 UTC, ubieda reviewed
Thanks for your contribution! Small suggestion, otherwise looks good!

2024-05-28 17:58 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/bmp180.c
> +	data->uncomp_press = ((int32_t)buf[0] << 16) | ((int32_t)buf[1] << 8) | buf[2];
ofc, I'll refactor

2024-05-28 22:40 UTC, ubieda submitted a review, later dismissed

2024-05-30 15:40 UTC, jovicjakov commented
@decsny, when you have time, could you take another look at this? Thanks!

2024-05-30 15:48 UTC, decsny approved these changes, later dismissed

2024-05-31 20:19 UTC, MaureenHelm requested changes
Some nits, but otherwise looks good. Thanks for your contribution!

2024-05-31 20:19 UTC, MaureenHelm commented on drivers/sensor/bosch/bmp180/bmp180.c
> +int bmp180_init(const struct device *dev)
```suggestion
static int bmp180_init(const struct device *dev)
```

2024-05-31 20:19 UTC, MaureenHelm commented on drivers/sensor/bosch/bmp180/bmp180.c
> +	if (!device_is_ready(config->i2c.bus)) {
```suggestion
	if (!i2c_is_ready_dt(&config->i2c)) {
```

2024-05-31 20:19 UTC, MaureenHelm commented on drivers/sensor/bosch/bmp180/Kconfig
> +		Enable the driver for the Bosch BMP180 pressure sensor.
```suggestion
	  Enable the driver for the Bosch BMP180 pressure sensor.
```

2024-05-31 20:52 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/bmp180.c
> +int bmp180_init(const struct device *dev)
Thanks, resolved

2024-05-31 20:52 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/bmp180.c
> +	if (!device_is_ready(config->i2c.bus)) {
Thanks, resolved

2024-05-31 20:52 UTC, jovicjakov commented on drivers/sensor/bosch/bmp180/Kconfig
> +		Enable the driver for the Bosch BMP180 pressure sensor.
Thanks, resolved

2024-05-31 20:56 UTC, jovicjakov commented
@MaureenHelm Thank you for the review! I've fixed the issues you pointed out. Please take another look when you have a chance.  :)

2024-06-14 22:49 UTC, ubieda commented
@MaureenHelm it does appear everything's addressed. There's a conflict resolution required but seems trivial to fix.

2024-06-14 22:49 UTC, ubieda approved these changes, later dismissed

2024-06-14 22:56 UTC, kartben commented
> @MaureenHelm it does appear everything's addressed. There's a conflict resolution required but seems trivial to fix.

@ubieda  feel free to directly push to the branch to save some time :)

2024-06-14 23:02 UTC, ubieda approved these changes, later dismissed
Re-approving after rebasing

2024-06-15 02:25 UTC, teburd approved these changes, later dismissed

2024-06-17 13:16 UTC, aescolar commented
Bulk changing the milestone from everything which did not make it to the v3.7.0 freeze deadline
and which is not labeled as a bug or documentation (or does not appear clearly as only containing
a bug fix or a documentation change).
If you disagree about this change please add the milestone again.

Please note that until rc2 only PRs containing bug fixes, docs and tests can be merged.
After that and until release only bug fixes and docs changes.

Exceptions require approval by the release team and a vote by the TSC.
https://docs.zephyrproject.org/latest/project/release_process.html#stabilization-phase

2024-06-17 13:16 UTC, aescolar commented
@jovicjakov rebase needed

2024-08-13 10:49 UTC, kartben commented
rebased to resolve conflict

2024-08-13 11:50 UTC, ubieda approved these changes

2024-08-13 11:52 UTC, kartben approved these changes

2024-08-13 12:20 UTC, aescolar commented
@MaureenHelm please re-review

2024-08-17 12:48 UTC, mariopaja commented
This driver can also be used on BMP085. Maybe it can be documented somewhere since https://github.com/zephyrproject-rtos/zephyr/pull/67612 was blocked

2024-08-18 04:30 UTC, ruehlchris commented on drivers/sensor/bosch/bmp180/bmp180.c
> +		/* Pressure is calculated in steps of 1 Pa */
CHAN PRESSURE for the Senor API should be in kPa not Pa.

2024-08-18 05:33 UTC, ruehlchris commented on drivers/sensor/bosch/bmp180/bmp180.c
> +	x2 = (data->ac2 * b6) >> 11;
you might want to simplify from the original data-sheet example to 
x1 = ((b2 * (b6 * b6)>>12))>>11;
x1 = ((b2 * b6 * b6) / pow(2,12) )/ pow(2,11)
x1 = (b2 * b6 *b6) (pow(2,12) * pow(2,11))
x1 = (b2 * b6 * b6) / 0x800000;  << much

2024-08-18 05:36 UTC, ruehlchris commented on drivers/sensor/bosch/bmp180/bmp180.c
> +
I wondered the if (b7< xx) statement here from the datasheet example
math wise it is exactly same  only a data overflow can happen if b7 is too big
so b7/b4 *2 would always be safe and no need for a if()

2024-08-18 07:09 UTC, ruehlchris commented
Hi @jovicjakov ,  it is a pity that I missed you PR request and did my own implementation. 
Not a problem but wast a bit of time.  I saw in your implementation a lot of the original code from the datasheet which are not optimal (IMHO). I add some comments to your code lately. 
As well, you exit with an error if the command ready bit(5) not 0 rather wait for the convention is ready.
The Sensor API wants the Pressure return as kPa your implementation return Pa.
Please have a look into my PR and use it to your benefit.  #77182

2024-08-18 14:14 UTC, jovicjakov commented
Hi everyone,

I just wanted to inform you that I have started an internship recently, and due to the terms of my contract, I am not allowed to contribute to open-source projects, not at this moment at least. I won't be able to continue working on this PR or addressing the remaining comments.

If any further changes are required, I may be unable to make them myself. I would be grateful if someone else could take over from here. Thanks!

2024-09-17 18:41 UTC, closed without merging