samples: sensors: nucleo_f756zg added to die_temp_polling
zephyrproject-rtos/zephyr pull request #73227
Opened 2024-05-23 13:40 UTC by noahp

Added board overlay file to permit internal temperature sensor testing:

- `nucleo_f756zg`

Signed-off-by: Noah Pendleton <noah.pendleton@gmail.com>

2024-05-23 15:09 UTC, ubieda submitted a review, later dismissed

2024-05-23 15:30 UTC, MaureenHelm requested changes

2024-05-23 15:30 UTC, MaureenHelm commented on samples/sensor/die_temp_polling/boards/nucleo_f756zg.overlay
> +/ {
Please add a license/copyright header

2024-05-24 14:56 UTC, noahp commented on samples/sensor/die_temp_polling/boards/nucleo_f756zg.overlay
> +/ {
Done, thank you!

2024-05-24 15:06 UTC, MaureenHelm approved these changes

2024-05-24 15:07 UTC, ubieda approved these changes

2024-05-27 07:08 UTC, erwango approved these changes

2024-05-27 07:16 UTC, kartben approved these changes

2024-05-27 15:15 UTC, merged