twister: cleanup how we capture results of handlers
zephyrproject-rtos/zephyr pull request #73358
Opened 2024-05-27 14:51 UTC by nashif

we use reason for a failure to indicate state and then set the status
later and reason for the failure, in case of the failure is taken from
the handler status. Clean this up by setting status and reason coming
from the handler very early, so we do not have to go through replacing
meaning later.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2024-05-28 07:31 UTC, LukaszMrugala requested changes
Minor logging inconsistencies

2024-05-28 07:31 UTC, LukaszMrugala commented on scripts/pylib/twister/twisterlib/handlers.py
> +        logger.debug(f"QEMU ({pid}) complete ({_status} / {_reason}) after {handler_time} seconds")
To be consistent with https://github.com/zephyrproject-rtos/zephyr/blob/a70bf0e488c5327ad67512c2854987d113318c79/scripts/pylib/twister/twisterlib/reports.py#L471, it should be more akin to: `logger.debug(f"QEMU ({pid}) complete with status: {_status} ({_reason}) after {handler_time} seconds")`

2024-05-28 07:31 UTC, LukaszMrugala commented on scripts/pylib/twister/twisterlib/handlers.py
> +        logger.debug(f"QEMU ({self.pid}) complete ({_status}) after {handler_time} seconds")
Inconsistent with the previous `logger.debug()`

2024-05-28 08:38 UTC, golowanow commented on scripts/pylib/twister/twisterlib/handlers.py
> +                        if cpu_time < timeout and not _status:
nit (here and at other similar places)
```suggestion
                        if cpu_time < timeout and _status is None:
```

2024-06-04 13:45 UTC, LukaszMrugala approved these changes
The compliance failure is a known false positive.

2024-06-12 14:54 UTC, PerMac approved these changes

2024-06-13 01:12 UTC, merged