drivers/ethernet: stm32: Don't exit driver init on HAL timeout
zephyrproject-rtos/zephyr pull request #7344
Opened 2018-05-04 09:13 UTC by erwango

In case ethernet cable is unplugged, stm32 ethernet driver triggers
an error, driver initialization fails and fw crashes.
This could be enhanced as in case not cable is connected, HAL
returns a Time out, and will resume its initialization when
cable is plugged.
Treat HAL timeout in ethernet driver initialization as a
recoverable error and continues driver init when it happens.

Tested with sample/net/dhcpv4_client. Start board with cable
unplugged. Wait some time before plugging the cable. DHCP request
is correctly performed when cable is plugged.

Fixes: #7127

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

2018-05-04 09:34 UTC, jukkar approved these changes

2018-05-04 12:22 UTC, tbursztyka requested changes
tiny comment

That reminds me we would need to implement carrier detection in ethernet drivers at some point (it could raise a carrier event then)

2018-05-14 10:00 UTC, erwango commented
@tbursztyka , I made the change, is that ok now? Thanks

2018-05-23 13:38 UTC, erwango commented
@tbursztyka ping

2018-05-24 06:54 UTC, tbursztyka approved these changes

2018-05-25 18:06 UTC, galak approved these changes

2018-05-25 18:07 UTC, merged