cmake: set big-endian flags to TOOLCHAIN_*_FLAGS
zephyrproject-rtos/zephyr pull request #73563
Opened 2024-05-31 09:10 UTC by ntavish

This PR is related to https://github.com/zephyrproject-rtos/sdk-ng/pull/765

2024-07-04 12:52 UTC, tejlmand requested changes
Seems ok, but some small clarification is needed as this doesn't seem to really add support for big endian on v7-r.

Also this help text needs an update, as it doesn't include the flags on the compiler.
https://github.com/zephyrproject-rtos/zephyr/blob/2457f730f43079d8d0626f6dee6f51765a29605d/arch/Kconfig#L183-L184

2024-07-04 12:52 UTC, tejlmand commented on cmake/compiler/gcc/target_arm.cmake
> +if(CONFIG_BIG_ENDIAN)
currently `BIG_ENDIAN` is a promptless symbol, meaning it depends on something having a `select BIG_ENDIAN` (or a change of default).

Currently the arch for which that is done is `SPARC`:
https://github.com/zephyrproject-rtos/zephyr/blob/2457f730f43079d8d0626f6dee6f51765a29605d/arch/Kconfig#L65
https://github.com/zephyrproject-rtos/zephyr/blob/2457f730f43079d8d0626f6dee6f51765a29605d/arch/Kconfig#L70

so how is this expected to be selected for `arm v7-r` and thus selecting this code path ?

2024-07-20 12:54 UTC, ntavish commented
@tejlmand sorry for the delay, made the changes you have requested for `zephyr/arch/Kconfig`.

2024-08-07 07:53 UTC, tejlmand commented
> @tejlmand sorry for the delay, made the changes you have requested for `zephyr/arch/Kconfig`.

Sorry, but I don't see any reply to this comment: https://github.com/zephyrproject-rtos/zephyr/pull/73563#discussion_r1665666538

2024-08-08 03:34 UTC, ntavish commented
> Sorry, but I don't see any reply to this comment: [#73563 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/73563#discussion_r1665666538)

Oops, it was still 'pending', should be visible now.

2024-09-12 11:48 UTC, tejlmand approved these changes

2024-09-19 04:28 UTC, stephanosio approved these changes

2024-09-19 07:30 UTC, merged