drivers: can: mcp251xfd: Fix initialization sequence
zephyrproject-rtos/zephyr pull request #73714
Opened 2024-06-04 10:09 UTC by melvinvdb

This fixes #73586
The mcp251xfd sometimes fails to initialize on mcu reboot. This is caused by trying to communicate with the mcp too soon (the mcp is still resetting).
This PR adds a 5ms delay.
On init failure (failing to configure the device after reset etc) no console errors would show up which causes confusing for the user/developer.
This PR also makes sure an error would show up in the console log.

2024-06-04 14:46 UTC, talih0 requested changes

2024-06-04 14:46 UTC, talih0 commented on drivers/can/can_mcp251xfd.c
> +		ret = -EIO;
I think it will be cleaner just to forward the error at these points and get rid of the done label.

2024-06-27 09:36 UTC, henrikbrixandersen requested changes
Please update this PR as per the suggestion from @talih0 to get rid of the `done` label.

2024-09-09 11:22 UTC, henrikbrixandersen commented
Closing in favor of https://github.com/zephyrproject-rtos/zephyr/pull/77816

2024-09-09 11:22 UTC, closed without merging