docs: Move sensor.rst  to sensor/index.rst
zephyrproject-rtos/zephyr pull request #73740
Opened 2024-06-04 17:26 UTC by teburd

Looking to expand the sensor docs and break out significant sections. First though to move this to a directory to allow for multiple sensor related rst docs.

2024-06-04 18:41 UTC, ubieda submitted a review, later dismissed

2024-06-04 19:13 UTC, nashif approved these changes, later dismissed

2024-06-04 19:56 UTC, kartben requested changes
As you're renaming an existing page, can you please add a redirect in `doc/_scripts/redirects.py`?
This way people navigating e.g. https://docs.zephyrproject.org/2.7.6/reference/peripherals/sensor.html don't get a 404 when clicking to "see the latest version of this page". Thanks!

2024-06-04 21:43 UTC, teburd commented
> As you're renaming an existing page, can you please add a redirect in `doc/_scripts/redirects.py`? This way people navigating e.g. https://docs.zephyrproject.org/2.7.6/reference/peripherals/sensor.html don't get a 404 when clicking to "see the latest version of this page". Thanks!

done, but I'm not sure if I did it right

2024-06-05 07:02 UTC, kartben commented
> done, but I'm not sure if I did it right

you did :) thanks!
https://builds.zephyrproject.io/zephyr/pr/73740/docs/hardware/peripherals/sensor.html

2024-06-05 07:02 UTC, kartben approved these changes

2024-06-05 07:40 UTC, gmarull approved these changes

2024-06-05 11:35 UTC, ubieda approved these changes

2024-06-05 14:40 UTC, MaureenHelm approved these changes

2024-06-05 22:38 UTC, merged