spi: stm32: minor enhancements to driver & tests
zephyrproject-rtos/zephyr pull request #73874
Opened 2024-06-06 16:00 UTC by ajarmouni-st

2024-06-07 08:29 UTC, gautierg-st approved these changes, later dismissed

2024-06-12 07:41 UTC, erwango requested changes
Minor comment, otherwise a welcomed change

2024-06-12 07:41 UTC, erwango commented on drivers/spi/spi_ll_stm32.c
We should also do ARG_UNUSED(dma_dev)

2024-06-12 07:49 UTC, FRASTM commented on drivers/spi/spi_ll_stm32.c
> +	struct spi_stm32_data *dma_channel_data = arg;
Would it make any confusion naming a variable _dma_channel_data_  of type  _spi_stm32_data_ ?
In the end this _dma_channel_data_.dma_tx or _dma_channel_data_.dma_rx are dma stream structure

2024-06-12 08:55 UTC, erwango approved these changes

2024-06-12 09:00 UTC, tbursztyka approved these changes

2024-06-12 11:28 UTC, merged