sysbuild: dts: Introduce sysbuild_dt_* API
zephyrproject-rtos/zephyr pull request #73903
Opened 2024-06-07 10:03 UTC by 57300

Add new functions to `sysbuild_extensions.cmake`, which will mirror the
familiar dt_* API from Zephyr `extensions.cmake`. For example:
```
dt_nodelabel(<var> NODELABEL <label>)
```
gets the following sysbuild counterpart, with one extra argument:
```
sysbuild_dt_nodelabel(<var> IMAGE <image> NODELABEL <label>)
```
This API allows sysbuild to retrieve devicetree information for a given
<image>, only after its respective `ExternalZephyrProject_Cmake()` call.

This works by importing the generated `dts.cmake` files from each
image's build directory, and creating multiple CMake targets to hold the
generated properties - much like how the `CMakeCache.txt` and `.config`
are also imported to be used by the related `sysbuild_get()` function.

The dt_* API itself also has to be updated, in order to read properties
from a variable `DEVICETREE_TARGET` set in the parent scope.

2024-07-17 06:37 UTC, nordicjm submitted a review, later dismissed
Very useful addition!

2024-09-18 07:59 UTC, bjarki-andreasen commented
Could we add these additions to the docs somewhere? Looking at the current docs, only reference to these macros seems to be in an old release note, it would be great to actually have these macros (including the existing dt_ ones) somewhere :) until now, I have to look to the scripts to figure out what we support

2024-09-18 08:16 UTC, 57300 commented
> Could we add these additions to the docs somewhere? Looking at the current docs, only reference to these macros seems to be in an old release note, it would be great to actually have these macros (including the existing dt_ ones) somewhere :) until now, I have to look to the scripts to figure out what we support

I don't know how many CMake extensions are currently documented, but it seems to be that most aren't. I think it might be nice to first consider creating some API doc auto-generation for CMake (or finding an existing solution) to avoid maintaining multiple copies of the same text. Maybe @tejlmand knows more about this?

2024-09-18 08:57 UTC, bjarki-andreasen commented
> > Could we add these additions to the docs somewhere? Looking at the current docs, only reference to these macros seems to be in an old release note, it would be great to actually have these macros (including the existing dt_ ones) somewhere :) until now, I have to look to the scripts to figure out what we support
> 
> I don't know how many CMake extensions are currently documented, but it seems to be that most aren't. I think it might be nice to first consider creating some API doc auto-generation for CMake (or finding an existing solution) to avoid maintaining multiple copies of the same text. Maybe @tejlmand knows more about this?

Maybe we can add some sample which uses the new extensions? or at least test cases for it?

2024-09-18 09:23 UTC, 57300 commented
> Maybe we can add some sample which uses the new extensions? or at least test cases for it?

I think adding unit tests would make sense, maybe similar to the ones I had written for `zephyr_get()`. Right now I don't have the bandwidth for that though.

2024-09-18 10:01 UTC, bjarki-andreasen commented
> > Maybe we can add some sample which uses the new extensions? or at least test cases for it?
> 
> I think adding unit tests would make sense, maybe similar to the ones I had written for `zephyr_get()`. Right now I don't have the bandwidth for that though.

ok, I would like to have some tests or similar before the PR is merged, I have added the DNM label until then :)

2025-02-21 10:15 UTC, nordicjm approved these changes, later dismissed

2025-02-21 10:16 UTC, nordicjm commented
@57300 why is this DNM?
@tejlmand please review

2025-02-21 10:28 UTC, 57300 commented
> @57300 why is this DNM?

@bjarki-andreasen marked it because he came in and asked for tests: https://github.com/zephyrproject-rtos/zephyr/pull/73903#issuecomment-2358032482

I had agreed initially, but I would first need to add tests for the regular `dt_*` API, which deserves a separate PR.

2025-05-08 09:48 UTC, pdgendt commented
Needs a rebase

2025-05-08 11:26 UTC, bjarki-andreasen submitted a review, later dismissed

2025-05-08 11:28 UTC, nordicjm submitted a review, later dismissed

2025-05-09 02:13 UTC, rruuaanng approved these changes, later dismissed

2025-05-15 15:04 UTC, tejlmand requested changes
Thanks for this proposal.

Having devicetrees from images available is really needed and the proposal appreciated.
There are some comments related to some of the suggested ideas.

2025-05-15 15:04 UTC, tejlmand commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +    cmake_language(CALL ${name} ${var} ${SBDT_UNPARSED_ARGUMENTS})
this is bound to break at some point.

Forwarding arguments blindly will not work in all cases, so when using functions like `cmake_language()` and / or forwarding arguments then we really need to have full control / knowledge how this is being called.

This proposal can lead to unexpected surprises / hard to debug issues.

Please also take a look at: https://crascit.com/2019/01/29/forwarding-command-arguments-in-cmake/

2025-05-15 16:30 UTC, 57300 commented on cmake/modules/extensions.cmake
> +  endif()
Good point. I can't remember why I convinced myself that using a parent scope variable was okay.

If it's acceptable to add a `TARGET` argument to all `dt_*` functions, then that would practically remove the need for `sysbuild_dt_*` functions, since one would be free to use e.g.:
```cmake
# in sysbuild:
dt_nodelabel(var TARGET image NODELABEL label)

# instead of:
sysbuild_dt_nodelabel(var IMAGE image NODELABEL label)
```

If that feels right to you, then that would also remove the complexity involved in forwarding arguments from `sysbuild_dt_*` functions, which I didn't get right the first time: https://github.com/zephyrproject-rtos/zephyr/pull/73903#discussion_r2091405265

2025-05-15 17:04 UTC, 57300 commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +  include(${BINARY_DIR}/zephyr/dts.cmake)
I didn't think much of it, because our CMake modules also expect certain variables to be set beforehand, which are documented as "inputs", so it's not like this is a bad practice for CMake files in general.

It's not quite so blatant there as it is here, though, and maybe dealing with a generated file also feels different.

I'm skeptical of going the `import_kconfig()` route, because that function parses an actual `.config` file, whereas an `import_dt()` couldn't feasibly take an actual `.dts` file, much less an `edt.pickle`. We could at least replace the generated `dts.cmake` with a JSON file or something, and use it to populate target properties, as long as we don't have to rework the whole CMake DT solution from the ground up.

2025-05-15 19:21 UTC, tejlmand commented on cmake/modules/extensions.cmake
> +  endif()
> If it's acceptable to add a `TARGET` argument to all `dt_*` functions, then that would practically remove the need for `sysbuild_dt_*` functions, since one would be free to use e.g.:

I would say it is.
It's very similar to other functions where we allow flexibility by using custom targets for scoping, for example `import_kconfig`.
Or you can say `zephyr_get()` indirectly uses target, although less visible because the SYSBUILD flag.

> If that feels right to you, then that would also remove the complexity involved in forwarding arguments from sysbuild_dt_* functions, which I didn't get right the first time: https://github.com/zephyrproject-rtos/zephyr/pull/73903#discussion_r2091405265

Sounds like a win-win :+1:

2025-05-16 09:03 UTC, tejlmand commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +  include(${BINARY_DIR}/zephyr/dts.cmake)
> I'm skeptical of going the import_kconfig() route, because that function parses an actual .config file, whereas an import_dt() couldn't feasibly take an actual .dts file, much less an edt.pickle, so it would feel asymmetrical.

The intention was not to go exactly the Kconfig route but to have a function for loading devicetree.
A function which build system can call, and which would allow adjusting how content is loaded. Similar to how you can request `import_kconfig()` to use a different prefix or populate a specific target.

So minimum request is to have a function call where the caller decides how to load and adjust content.
Could be `import_dts()`.
Having such call will also allow to rework the solution any way we like without impacting callers of `import_dts()`

> We could at least replace the generated dts.cmake with a JSON file or something, and use it to populate target properties, as long as we don't have to rework the whole CMake DT solution from the ground up.

Now you're bring up the topic of changing the format of the python generated output file :wink: .

If we are to adjust, then json could be an option, or we could consider aligning with zephyr_modules.py which makes semicolon lists like this:
```
"DTS_ROOT":"/projects/github/ncs/modules/hal/adi"
```
or:
```
"nrf":"/projects/github/review/nrf":"/projects/github/review/nrf"                                   
```
but if content loading is handled through a function, then we can change any way we like in future.
But I do consider such re-write outside scope of this PR, unless you have time and believe it to be a good idea.

Note, the comment: `Perhaps generating a CMake dts file from python is not the best way if we need to do such hacks.` was more an observation and not a request to do such big changes in this PR.

> because our CMake modules also expect certain variables to be set beforehand

True, and it would be nice to find the time to do a followup to #41301 so that Zephyr's CMake modules became even cleaner, while keeping current re-usability.

2025-05-16 10:41 UTC, 57300 commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +  include(${BINARY_DIR}/zephyr/dts.cmake)
Thanks for clarifying.

> Now you're bring up the topic of changing the format of the python generated output file 😉 .

I'm just thinking out loud about how to apply your suggestion and make it architecturally sound :)

I guess there's no need to change the format in this PR. I only considered it because I imagined that `import_dts()` would only be able to take `dts.cmake` as input, which is very esoteric, so that didn't sit right with me.

Now I'm considering moving this Python invocation:
https://github.com/zephyrproject-rtos/zephyr/blob/6e34acc4e296b44b0b2142ba56480a6f2ee08e38/cmake/modules/dts.cmake#L368-L374

to encapsulate it in the new CMake function and take `edt.pickle` as input:

```cmake
function(import_edt file)
  if(${file} IS_NEWER_THAN ${file}.cmake)
    # run python script
  endif()
  set(DEVICETREE_TARGET devicetree_target)
  include(${file}.cmake)
endfunction()
```

There would be a byproduct `edt.pickle.cmake`, which could be loaded multiple times without rerunning the script, as long as the corresponding `edt.pickle` doesn't change.

> Having such call will also allow to rework the solution any way we like without impacting callers of `import_dts()`

I propose calling the function `import_edt()`, so that the API stability would largely be tied to edtlib.

2025-05-16 12:14 UTC, tejlmand commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +  include(${BINARY_DIR}/zephyr/dts.cmake)
> I only considered it because I imagined that import_dts() would only be able to take dts.cmake as input, which is very esoteric

I agree with you there.
Was mostly trying to see how we could improve PR without requesting a major restructure / update.

> Now I'm considering moving this Python invocation:
> ...
> to encapsulate it in the new CMake function and take edt.pickle as input:

Having the function being able to take `edt.pickle` as input makes the function much cleaner seen from the caller's perspective.

Thanks for that proposal :+1: 

> I propose calling the function import_edt(), so that the API stability would largely be tied to edtlib.

:+1: for that.

2025-05-20 14:45 UTC, 57300 commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +    cmake_language(CALL ${name} ${var} ${SBDT_UNPARSED_ARGUMENTS})
Removed.

2025-05-20 14:45 UTC, 57300 commented on share/sysbuild/cmake/modules/sysbuild_extensions.cmake
> +  include(${BINARY_DIR}/zephyr/dts.cmake)
Added as `zephyr_dt_import(EDT_PICKLE_FILE ...)` to fit into an existing `extensions.cmake` section.

2025-05-22 08:15 UTC, tejlmand approved these changes

2025-05-22 09:42 UTC, rruuaanng approved these changes

2025-05-22 09:49 UTC, carlescufi approved these changes

2025-05-22 11:31 UTC, bjarki-andreasen approved these changes

2025-05-22 11:44 UTC, merged