tests: drivers: gpio: Add nrf54h20dk/nrf54h20/cpuppr targets
zephyrproject-rtos/zephyr pull request #73913
Opened 2024-06-07 12:47 UTC by nordic-krch

Add overlays for cpuppr targets in `gpio_basic_api` and `gpio_api_1pin`.

2024-06-11 06:38 UTC, nordic-krch commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
Created #74051 for that.

2024-06-11 06:54 UTC, 57300 commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
You can have `boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay` picked up automatically by moving it to this subdirectory:
```
sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
sysbuild/vpr_launcher/prj.conf # empty
```
`sysbuild/vpr_launcher` will be picked up as the new `APPLICATION_CONFIG_DIR` for `vpr_launcher`

2024-06-11 09:22 UTC, nordic-krch commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
I see that `sysbuild/vpr_launcher/prj.conf` is taken but overlays are not. Tried `sysbuild/vpr_launcher/nrf54h20dk_nrf54h20_cpuapp.overlay` and `sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay`

2024-06-11 09:25 UTC, nordic-krch commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
i tried changing DTC_OVERLAY_FILE in testcase.yaml to `vpr_launcher_DTC_OVERLAY_FILE="boards/nrf54h20dk_nrf54h20_cpuapp.overlay` and tried to remove it as well but in both cases it failed.

2024-06-11 09:37 UTC, 57300 commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
Hmm. Worked on my end with `west build -p -b nrf54h20dk//cpuppr --sysbuild --cmake-only`
```
   **********************************
   * Running CMake for vpr_launcher *
   **********************************
...
-- Found devicetree overlay: /ncs/zephyr/tests/drivers/gpio/gpio_api_1pin/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
-- Found devicetree overlay: /ncs/zephyr/snippets/nordic-ppr/nordic-ppr.overlay
-- Found devicetree overlay: /ncs/zephyr/snippets/nordic-ppr/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
...
```

2024-06-11 14:56 UTC, nordic-krch commented on tests/drivers/gpio/gpio_api_1pin/testcase.yaml
> +      - vpr_launcher_DTC_OVERLAY_FILE="../../../tests/drivers/gpio/gpio_api_1pin/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay"
i did rebase and it worked now. not sure if something fixed it or i did something wrong on the first run. I've updated overlay locations but still using ugly paths for toml file.

2024-06-12 18:43 UTC, 57300 requested changes
Placing a NACK until we can remove the TOML files.

2024-10-14 06:33 UTC, nordic-krch commented
> Placing a NACK until we can remove the TOML files.

@57300 any news here?

2025-05-20 14:31 UTC, closed without merging