boards: frdm_ke1 series: Suppress no-simple-bus DTC warning
zephyrproject-rtos/zephyr pull request #73969
Opened 2024-06-09 03:40 UTC by dleach02

All KE1xz GPIOs share a common register and need the dtc warning suppressed.

2024-06-09 14:04 UTC, dleach02 commented
currently blocking #71284

2024-06-10 14:16 UTC, danieldegrasse approved these changes

2024-06-10 14:20 UTC, danieldegrasse commented
I'm going to remove the hotfix label, as (at least as far as I can tell) this issue is not the root cause of the CI failure on that PR. Feel free to reapply it if needed

2024-06-10 14:27 UTC, EmilioCBen approved these changes

2024-06-10 14:33 UTC, dleach02 commented
> I'm going to remove the hotfix label, as (at least as far as I can tell) this issue is not the root cause of the CI failure on that PR. Feel free to reapply it if needed

it may not be but the PR does try to build the synchronization sample for the KE17Z platform and that will generate the warning this PR addresses. So even if they fix the west.yml I suspect the PR will potentially still try to build this target+sample

2024-06-10 14:41 UTC, danieldegrasse commented
> it may not be but the PR does try to build the synchronization sample for the KE17Z platform and that will generate the warning this PR addresses. So even if they fix the west.yml I suspect the PR will potentially still try to build this target+sample. But trivial/hotfix have a similar impact

Exactly why I added the label- still think the PR can merge quickly, just want to make sure we narrow down root cause of the failure on #71284

2024-06-10 15:39 UTC, decsny approved these changes

2024-06-10 16:57 UTC, decsny requested changes
prefer this fix: #74028

2024-06-11 00:30 UTC, dleach02 commented
> prefer this fix: #74028

Sounds good

2024-06-11 00:30 UTC, closed without merging