west.yml: hal_stm32: prefix autoconf.h with zephyr/
zephyrproject-rtos/zephyr pull request #73991
Opened 2024-06-10 09:32 UTC by erwango

Sync with hal_stm32 PR

2024-07-01 09:13 UTC, gmarull approved these changes

2024-07-01 09:25 UTC, henrikbrixandersen requested changes
The commit massage should be updated to match the actual change.

2024-07-01 09:46 UTC, erwango commented
> The commit massage should be updated to match the actual change.

Thanks, fixed, ptal.

2024-07-01 09:47 UTC, gmarull approved these changes, later dismissed

2024-07-01 11:42 UTC, henrikbrixandersen submitted a review, later dismissed

2024-07-01 11:51 UTC, str4t0m approved these changes, later dismissed

2024-07-01 16:05 UTC, ycsin approved these changes, later dismissed

2024-07-02 09:12 UTC, ycsin approved these changes

2024-07-02 09:33 UTC, henrikbrixandersen approved these changes

2024-07-02 12:25 UTC, aescolar approved these changes

2024-07-02 12:25 UTC, merged