samples: boards: stm32: wkup_pins: no need to configure button GPIO pin
zephyrproject-rtos/zephyr pull request #74077
Opened 2024-06-11 12:18 UTC by ajarmouni-st

The gpio pin that will be used as a source for PWR wake-up pins does not actually need to be configured as input, hence `input_gpio_keys` driver does not need to be involved. As far as GPIO controller is concerned, the pin can be in analog state.

Also, it's clearer & safer to call `gpio_pin_configure_dt` directly in the application with the `STM32_GPIO_WKUP` flag, just before calling Poweroff, instead of relying on a driver, like `input_gpio_keys` to do it just after boot behind the scenes, & risk not having the correct wake-up pins config when Poweroff is finally called.

2024-06-11 15:10 UTC, erwango requested changes

2024-06-12 12:26 UTC, erwango commented on samples/boards/stm32/power_mgmt/wkup_pins/prj.conf
>  CONFIG_PM_DEVICE_RUNTIME=n
Those are default n. Is that really required ,

2024-06-12 12:47 UTC, erwango approved these changes

2024-06-12 14:02 UTC, gautierg-st approved these changes

2024-06-13 15:51 UTC, merged