config: esp32:  configurable UART FIFO thresholds
zephyrproject-rtos/zephyr pull request #74312
Opened 2024-06-14 12:00 UTC by OmerGozderesi

Introduce Kconfig options to define both the RX and TX FIFO thresholds for the ESP32 UART, enabling configurability while maintaining a default value of 1. fixes #74311

2024-06-14 12:19 UTC, sylvioalves submitted a review, later dismissed

2024-06-14 12:50 UTC, marekmatej requested changes

2024-06-14 13:03 UTC, OmerGozderesi commented on drivers/serial/Kconfig.esp32
> +	default 1
updated, thanks for review.

2024-06-14 13:04 UTC, marekmatej commented
Hi @OmerGozderesi Thanks for your work! Please note, the previously used default values were
```
#define UART_TX_FIFO_THRESH 0x1
#define UART_RX_FIFO_THRESH 0x16
```

You should leave them in the newly created configs as it was before.

2024-06-14 13:05 UTC, marekmatej commented
Also, please squash those commits changing the same file together.

2024-06-15 15:35 UTC, OmerGozderesi commented
updated, thanks again for reviews

2024-06-16 19:54 UTC, dcpleung approved these changes

2024-07-09 16:42 UTC, aescolar commented
@marekmatej @sylvioalves please review

2024-07-09 16:43 UTC, sylvioalves approved these changes

2024-07-09 18:25 UTC, marekmatej approved these changes

2024-07-09 19:24 UTC, merged