doc: Misc trivial formatting clean-ups
zephyrproject-rtos/zephyr pull request #74491
Opened 2024-06-18 13:06 UTC by kartben

See commits, everything should be pretty straightforward and they're only fixing actual rendering issues (or sub-optimal rendering, ex. syntax highlighting), content hasn't been touched.

**Note**: the fix made to https://docs.zephyrproject.org/latest/project/dev_env_and_tools.html#labels-applicable-to-issues-only (a preview of the new look being captured below for convenience) in the last commit is maybe slightly more substantial than the other changes, so I can move this to another PR if people prefer...

# BEFORE

![image](https://github.com/zephyrproject-rtos/zephyr/assets/128251/bf6ec60b-e152-4427-a995-fedbef9a72c5)

# AFTER

![image](https://github.com/zephyrproject-rtos/zephyr/assets/128251/37b05f56-3570-40ea-9f44-b2ac60f941aa)

2024-06-18 19:22 UTC, pdgendt submitted a review, later dismissed
Nice

2024-06-19 06:48 UTC, erwango submitted a review, later dismissed

2024-06-19 07:16 UTC, aescolar requested changes
Thanks @kartben 
Except for the new trivial label description all other changes seem very nice.
I have 2 extra proposals in lines you are changing but you can ignore them if you want.

2024-06-19 07:34 UTC, kartben commented on samples/net/tftp_client/README.rst
> +Sample can be run on native_sim platform with TFTP server on host machine.
definitely -- initial wording was far from ideal and I only made a minimal attempt at improving it. This is much better for sure

2024-06-19 07:36 UTC, kartben commented on doc/project/dev_env_and_tools.rst
> +     - Changes that can be reviewed by anyone, i.e. doc changes, minor build system tweaks, etc.
I actually copied the description from our GitHub :)

![image](https://github.com/zephyrproject-rtos/zephyr/assets/128251/bffd3771-518a-49f2-a457-6491647c6d1f)

2024-06-19 07:41 UTC, aescolar commented on doc/project/dev_env_and_tools.rst
> +     - Changes that can be reviewed by anyone, i.e. doc changes, minor build system tweaks, etc.
Unfortunately github labels can be changed by too many people too easily. I would not take that as canon :)

2024-06-19 07:46 UTC, kartben commented on doc/project/dev_env_and_tools.rst
> +     - Changes that can be reviewed by anyone, i.e. doc changes, minor build system tweaks, etc.
Of course. My point was that it would make sense to have both descriptions be the same, at least at day one :) Anyway, I've applied your suggestion!

2024-06-19 09:00 UTC, pdgendt approved these changes

2024-06-19 09:06 UTC, jukkar approved these changes

2024-06-19 09:07 UTC, rlubos approved these changes

2024-06-19 11:23 UTC, aescolar approved these changes
Thank you @kartben

2024-06-20 18:07 UTC, merged