Adds RTC driver for Infineon XMC4xxx devices
zephyrproject-rtos/zephyr pull request #74840
Opened 2024-06-24 02:35 UTC by talih0

Adds support for settings/getting RTC time and using alarm/update feature.
    
The alarm option needs all fields to be set due to a hardware limitation.
    
RTC shares the same interrupt with the watchdog. Thus shared
interrupts must be enabled when WDT and RTC both need to trigger the ISR.

Devicetree for boards xmc45_relax_kit and xmc47_relax_kit are also updated to include RTC.

![image](https://github.com/zephyrproject-rtos/zephyr/assets/17433307/ec8261a8-87a5-402d-941f-99fa376ab1ca)

2024-06-24 03:19 UTC, talih0 commented
The compliance failure is a false positive. Though INTERUPT is misspelled it is referring to a function from Infineon hal.

2024-06-25 05:07 UTC, bjarki-andreasen requested changes

2024-06-25 05:07 UTC, bjarki-andreasen commented on drivers/rtc/rtc_xmc4xxx.c
> +	}
The RTC should not be started and set to a random value at init, time is set manually using the rtc_set_time api :)

2024-06-25 05:09 UTC, bjarki-andreasen commented
Please run the alarm test suite using this PR #78739 it allows you to set the alarm time mask using Kconfig to match the rtc :)

2024-06-30 03:27 UTC, talih0 commented
> Please run the alarm test suite using this PR #73789 it allows you to set the alarm time mask using Kconfig to match the rtc :)

thanks, I rebased after the commit was merged:
![image](https://github.com/zephyrproject-rtos/zephyr/assets/17433307/33de5f72-e95b-4078-a8a0-92a67b38e5f7)

2024-06-30 05:05 UTC, bjarki-andreasen requested changes
Could you split the PR into
1. add device driver
2. add rtc to boards
3. add boards to RTC test suite

It keeps bisectability high and makes reviews a bit easier :)

2024-06-30 21:34 UTC, talih0 commented on drivers/rtc/rtc_xmc4xxx.c
> +		dev_data->is_time_set = true;
yep, thanks.

2024-07-01 04:13 UTC, bjarki-andreasen approved these changes, later dismissed
Nice work!

2024-07-02 03:48 UTC, ifyall approved these changes, later dismissed

2024-07-02 13:19 UTC, bjarki-andreasen commented
Please ping me after feature freeze if I forget about this PR, we need to ping around a bit to get it merged with a CI failure ;)

2024-08-30 14:12 UTC, talih0 commented
@bjarki-andreasen, I removed the function name that was causing the compliance problem.

2024-08-30 17:41 UTC, bjarki-andreasen approved these changes

2024-09-03 22:51 UTC, ifyall approved these changes

2024-09-04 07:54 UTC, merged