Bluetooth: GATT: Rework BT_GATT_CHARACTERISTIC
zephyrproject-rtos/zephyr pull request #7488
Opened 2018-05-11 19:49 UTC by Vudentz

These changes ensure the Characteristic Value is always declared with the same UUID as indicated in the characteristic declaration.

2018-05-12 16:52 UTC, jhedberg approved these changes
Looks ok to me

2018-05-14 09:11 UTC, carlescufi approved these changes
Thank you @Vudentz. This more than solves my concerns there with the current macros.

2018-05-14 09:14 UTC, carlescufi requested changes

2018-05-14 09:14 UTC, carlescufi commented on samples/bluetooth/gatt/hrs.c
> +			       BT_GATT_PERM_READ, NULL, NULL, NULL),
This should not have `PERM_READ`

2018-05-14 09:26 UTC, asbjornsabo reviewed
I am in favour of this change.  The previous behaviour, using DESCRIPTOR to add the value of a characteristic, confused me.  Neither did this previous use of DESCRIPTOR correspond to what a descriptor really is.

2018-05-14 11:03 UTC, Vudentz commented
Patches updated.

2018-05-14 11:03 UTC, carlescufi approved these changes

2018-05-14 15:51 UTC, merged