STM32 ADC fix calibration
zephyrproject-rtos/zephyr pull request #75048
Opened 2024-06-26 15:08 UTC by gautierg-st

For STM32H7, U5 and WBA, check the LDO status flag after enabling the internal regulator instead of waiting a predetermined delay. In some cases, the delay was not long enough, and the calibration started when the LDO was not stabilized, resulting in wrong measurements.
Also add an extended calibration on U5 to enhance precision.

2024-06-27 13:33 UTC, erwango requested changes

2024-06-28 06:45 UTC, gautierg-st commented on drivers/adc/adc_stm32.c
> +			adc_stm32_disable(adc);
Agreed, and done!

2024-06-28 07:23 UTC, erwango approved these changes, later dismissed

2024-06-28 07:41 UTC, FRASTM approved these changes

2024-07-01 09:15 UTC, erwango approved these changes

2024-07-01 13:06 UTC, merged