doc: flashing: configuration: fix yaml example
zephyrproject-rtos/zephyr pull request #75266
Opened 2024-07-01 12:59 UTC by butok

Fix the flashing configuration yaml example
to follow the Zephyr CI YAMLLint rules.

2024-07-01 13:08 UTC, nordicjm reviewed
typo *configuration

2024-07-01 13:16 UTC, butok commented
> typo *configuration

Thanks. The commit message has been fixed.

2024-07-04 11:39 UTC, tejlmand approved these changes

2024-07-23 10:42 UTC, butok commented
UP

2024-07-23 11:13 UTC, nordicjm requested changes
This file does not fail the yamllint check when I run it locally in the original format so I see no reason to change it to a much more unreadable format

2024-07-23 11:14 UTC, nordicjm commented
Note: in-tree yml file in the original format without CI issues: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/soc.yml

2024-07-23 11:25 UTC, butok commented
> Note: in-tree yml file in the original format without CI issues: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/soc.yml

On-line CI was failed for this formatting, when I was adding the configurations for NXP platforms.
So finally to pass On-line CI, I had to reformat it. 
Please look, for example: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nxp/lpc/soc.yml
That is why this PR was created.

2024-07-23 11:28 UTC, nordicjm commented
> > Note: in-tree yml file in the original format without CI issues: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/soc.yml
> 
> On-line CI was failed for this formatting, when I was adding the configurations for NXP platforms. So finally to pass On-line CI, I had to reformat it. Please look, for example: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nxp/lpc/soc.yml That is why this PR was created.

That would be because you **mixed** formatting which is not allowed, you need to have uniform spacing in a file, so if you use 2 spaces for the first item, you must use 2 spaces throughout, you have used 0 spaces so your formatting must use 0 throughout

2024-07-23 11:31 UTC, butok commented
OK. 
The formatting is dictated by the whole file.

2024-07-23 11:31 UTC, closed without merging