Bluetooth: host: disallow scan with timeout when BT_PRIVACY=y
zephyrproject-rtos/zephyr pull request #75393
Opened 2024-07-03 15:00 UTC by jori-nordic

See comment in code.

Fixes #73634

2024-07-03 15:22 UTC, alwa-nordic submitted a review, later dismissed

2024-07-03 15:25 UTC, jhedberg submitted a review, later dismissed

2024-07-03 21:07 UTC, Thalley requested changes

2024-07-03 21:07 UTC, Thalley commented on include/zephyr/bluetooth/bluetooth.h
> + *       will result in an -EINVAL error code.
It only affects active scan, right? 

```suggestion
 * @note Setting the `param.timeout` parameter is not supported when
 *       @kconfig{CONFIG_BT_PRIVACY} is enabled when the param.type is @ref BT_LE_SCAN_TYPE_ACTIVE. Supplying a nonzero timeout
 *       will result in an -EINVAL error code.
```

2024-07-04 07:08 UTC, jori-nordic commented on include/zephyr/bluetooth/bluetooth.h
> + *       will result in an -EINVAL error code.
Yes, that's right.

2024-07-04 07:15 UTC, jhedberg approved these changes

2024-07-04 07:18 UTC, alwa-nordic approved these changes

2024-07-04 07:21 UTC, Thalley approved these changes

2024-07-05 16:43 UTC, merged