dts: riscv32: riscv32-qemu: Add device tree support
zephyrproject-rtos/zephyr pull request #7543
Opened 2018-05-15 12:35 UTC by SavinayDharmappa

add device tree support for riscv32-qemu

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

2018-05-15 12:53 UTC, galak commented on dts/bindings/serial/riscv,qemu-uart.yaml
> +id: altera,jtag-uart
fix id.

2018-05-16 19:55 UTC, kgugala requested changes

2018-05-16 19:55 UTC, kgugala commented on dts/riscv32/riscv32-qemu.dtsi
> +#define __SIZE_K(x) (x * 1024)
Why do we need this define? It is not used anywhere in the RISC-V code.

2018-05-22 05:21 UTC, kgugala approved these changes

2018-05-22 05:22 UTC, pgielda approved these changes

2018-06-12 18:16 UTC, kgugala commented
This is hanging here for quite some time. @galak can you merge it?

2018-06-13 12:47 UTC, merged