Bluetooth: ISO: Make setting ISO data explicit
zephyrproject-rtos/zephyr pull request #75549
Opened 2024-07-07 12:26 UTC by Thalley

The stack will no longer implicitly set the data path for ISO channel, and the responsibility for doing that is now for the upper layers/applications.

This provides additional flexibility for the higher layers as they can better control the values and timing of the data path, as well as support removing and even reconfiguring the data path at will.

Finally this also removes some complexity from the stack.

2024-07-08 11:05 UTC, Thalley commented
Reverted to draft as CI fails due to a race condition that we need to look into. 

The race condition happens when
1) App sends some ISO data that is then enqueued
2) App removes the data path
3) bt_conn_tx_processor is then called but fails due to 
 
d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_ctlr_hci: hci_iso_handle: Input data path not set for HCI
d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_conn: send_buf: Unable to send to driver (err -22)
d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_conn: bt_conn_tx_processor: Fatal error (-5). Disconnecting 0x8258240
d_00: @00:00:15.694387  [00:00:15.694,366] <wrn> bt_conn: bt_conn_tx_processor: conn 0x8258240: not connected

We can work around this by not removing the data path while connected (which kind of defeats the purpose of the changes in this PR).

2024-07-08 14:52 UTC, Thalley commented
> Reverted to draft as CI fails due to a race condition that we need to look into.
> 
> The race condition happens when
> 
>     1. App sends some ISO data that is then enqueued
> 
>     2. App removes the data path
> 
>     3. bt_conn_tx_processor is then called but fails due to
> 
> 
> ```
> d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_ctlr_hci: hci_iso_handle: Input data path not set for HCI
> d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_conn: send_buf: Unable to send to driver (err -22)
> d_00: @00:00:15.694387  [00:00:15.694,366] <err> bt_conn: bt_conn_tx_processor: Fatal error (-5). Disconnecting 0x8258240
> d_00: @00:00:15.694387  [00:00:15.694,366] <wrn> bt_conn: bt_conn_tx_processor: conn 0x8258240: not connected
> ```
> 
> We can work around this by not removing the data path while connected (which kind of defeats the purpose of the changes in this PR).

The issue was discussed in [Discord](https://discordapp.com/channels/720317445772017664/1259836843374149784), and seems to be an issue with the HCI drivers. Will rebase on whatever solution comes from that, but the changes in this PR are ready for review

2024-07-10 13:20 UTC, kruithofa approved these changes, later dismissed

2024-07-10 13:34 UTC, Thalley commented
Rebased to solve merge conflicts

2024-07-12 10:49 UTC, kruithofa approved these changes, later dismissed

2024-08-22 13:10 UTC, Thalley commented
Blocked by https://github.com/zephyrproject-rtos/zephyr/issues/77387

2024-09-20 09:24 UTC, Thalley commented
Marking as draft until https://github.com/zephyrproject-rtos/zephyr/issues/77387 is fixed

2025-03-11 15:16 UTC, rugeGerritsen requested changes
Looked at API docs only. 
Will you also add a new test testing adding a data path twice/removing it twice?

2025-03-11 15:16 UTC, rugeGerritsen commented on include/zephyr/bluetooth/iso.h
> +	BT_ISO_CHAN_TYPE_PERIPHERAL,    /**< Connected as peripheral */
This is also an API change which would need an entry in the migration guide

2025-03-11 15:16 UTC, rugeGerritsen commented on include/zephyr/bluetooth/iso.h
> +	uint8_t cc_len;
Somewhat unrelated: Now that we are changing the API, would it make sense to change the name to make it easier to understand? `cc_len -> codec_config_len`

2025-03-11 15:16 UTC, rugeGerritsen commented on include/zephyr/bluetooth/iso.h
> +	 * For the above reason it is still possible to use bt_iso_chan_get_info() on the @p chan.
I didn't really understand what is meant with this section. Could you elaborate a bit on this?

From a controller point of view, the CIS Central handles remain valid after a disconnection, but this is not the case for a peripheral.

2025-03-11 15:16 UTC, rugeGerritsen commented on include/zephyr/bluetooth/iso.h
> + * As per Bluetooth Core specification 5.4, Vol 4, Part E, Section 7.7.5, the data paths of CIS for
Minor: Here we should reference the newest core spec (6.0.)

2025-03-11 15:16 UTC, rugeGerritsen commented on include/zephyr/bluetooth/iso.h
> + * As per Bluetooth Core specification 5.4, Vol 4, Part E, Section 7.7.5, the data paths of CIS for
The important part of the sentence comes at the very end of a long sentence. I would suggest to flip it around to make it easier to read:
```suggestion
 * The data paths for a CIS for a Peripheral are removed upon disconnection as per ....
```

2025-03-11 15:16 UTC, rugeGerritsen commented on samples/bluetooth/iso_connected_benchmark/src/main.c
> + * Copyright (c) 2021-2024 Nordic Semiconductor ASA
I guess we are in 2025 now :)

2025-03-12 08:03 UTC, Thalley commented on include/zephyr/bluetooth/iso.h
> +	uint8_t cc_len;
I'd rather not. This PR is already large enough, and adding more API changes will just make it larger. If we want to do any renames, then I suggest to do that in a follow-up PR while the API is still considered unstable.

2025-03-12 08:06 UTC, Thalley commented on include/zephyr/bluetooth/iso.h
> +	 * For the above reason it is still possible to use bt_iso_chan_get_info() on the @p chan.
Redid the text a bit. The main purpose was to document that this callback is similar to the bt_conn.disconnected callback, and the `chan` object is still valid in the host until after this function returns.

2025-03-13 11:41 UTC, rugeGerritsen approved these changes

2025-03-17 13:39 UTC, larsgk reviewed
LGTM, but would like to have an extra set of eyes on it (trying to poke someone)

2025-03-19 07:30 UTC, fredrikdanebjer approved these changes

2025-03-19 09:56 UTC, merged