soc: nrf54h20: Add missing soc_nv_flash compatible
zephyrproject-rtos/zephyr pull request #75807
Opened 2024-07-12 08:36 UTC by KAGA164

This adds missing soc-nf-flash compatible to mram1x memory. Now this memory can be used with NVS drivers.

2024-07-12 08:41 UTC, 57300 commented
What is the exact problem that occurs without this compatible?

2024-07-12 09:54 UTC, KAGA164 commented
> What is the exact problem that occurs without this compatible?

@57300 Customers are confusing, because they what to use flash drivers and construction of drivers requires that partition grandfather needs to have this compatible and all ours SoCs have it by default for flash controller. The next things is that "nordic,mram" bindings includes properties from  soc_nv_flash bindings but lack of this compatible in dts makes it unusable

2024-07-12 10:11 UTC, 57300 requested changes
> Customers are confusing, because they what to use flash drivers and construction of drivers requires that partition grandfather needs to have this compatible

The upstream MRAM driver doesn't depend on this structure, and any code that uses the `FIXED_PARTITION` macros correctly shouldn't be affected by this. If customers are facing issues then I hope we can help them adapt.

> The next things is that "nordic,mram" bindings includes properties from soc_nv_flash bindings but lack of this compatible in dts makes it unusable

We borrow properties from `soc-nv-flash` because those are standard for Zephyr flash drivers. However, we can't actually use this compatible in dts, because it would expect the parent of `mram1x` - `/soc` - to be a flash controller device. Unless we add a dummy `mram-controller` node, some of the existing code will break. But doing so would be a bad practice, because nRF54H20 doesn't have an MRAM controller that's addressable by local domains (it's not described in the public datasheet).

2024-07-12 10:43 UTC, KAGA164 commented
> `FIXED_PARTITION`

@57300 Probably you are right. I will try to get access to the customer codebase and check this

2024-07-15 07:45 UTC, nvlsianpu commented
As  I can see flash_area/map/FIXED_PARTITIONs API are designed to be used with assumption that DT macros are able to find properties/nodes basing on  soc-nv-flash compatible. This api is used by some tests, and not by NVS directly.
https://github.com/search?q=repo%3Azephyrproject-rtos%2Fzephyr+DT_MTD_FROM_FIXED_PARTITION&type=code
https://github.com/search?q=repo%3Azephyrproject-rtos%2Fzephyr%20DT_MEM_FROM_FIXED_PARTITION(&type=code
So maybe this patch is not needed.

2024-08-12 06:56 UTC, closed without merging

2024-08-12 06:56 UTC, KAGA164 commented
I solved it on customer side with success