posix: deprecated: include dependencies from before deprecationd
zephyrproject-rtos/zephyr pull request #75855
Opened 2024-07-14 11:34 UTC by cfriedt

Many deprecated POSIX-related options were historically not gated by any Kconfig option prior to being deprecated.

These options include:

* EVENTFD_MAX (Note: eventfd is technically not part of POSIX)
* FNMATCH
* GETOPT
* PTHREAD
* MAX_TIMER_COUNT
* POSIX_MAX_FDS
* POSIX_MQUEUE
* POSIX_PUTMSG
* POSIX_SIGNAL
* POSIX_SYSCONF
* TIMER
* SEM_NAMELEN_MAX
* SEM_VALUE_MAX

Some were gated by other Kconfig options (some also deprecated). These deprecated options have been updated to reflect their old dependencies.

* MAX_PTHREAD_COUNT (PTHREAD)
* MAX_PTHREAD_KEY_COUNT (PTHREAD)
* MSG_COUNT_MAX (POSIX_MQUEUE)
* POSIX_CLOCK (!NATIVE_LIBC)
* POSIX_FS (FILE_SYSTEM)
* POSIX_LIMITS_RTSIG_MAX (POSIX_SIGNAL, not plural)
* POSIX_MAX_OPEN_FILES (POSIX_FS)
* PTHREAD (PTHREAD_IPC)
* PTHREAD_BARRIER (PTHREAD_IPC)
* PTHREAD_COND (PTHREAD_IPC)
* PTHREAD_IPC (POSIX_CLOCK)
* PTHREAD_MUTEX (PTHREAD_IPC)
* PTHREAD_RWLOCK (PTHREAD_IPC)
* PTHREAD_SPINLOCK (PTHREAD_IPC)
* TIMER_DELAYTIMER_MAX (TIMER)

A few previously deprecated Kconfig options have not yet been present for 1 release cycle and can (theoretically) just be removed, without deprecation.

* GETENTROPY
* POSIX_CONFSTR
* POSIX_ENV
* POSIX_SYSLOG

For dependency information, please see
https://docs.zephyrproject.org/3.6.0/kconfig.html#kconfig-search

Fixes #75843

2024-07-15 01:48 UTC, ycsin approved these changes

2024-07-16 01:10 UTC, nashif requested changes
This does not resolve https://github.com/zephyrproject-rtos/zephyr/issues/75843 completely:

`west build -b mps2/an385  samples/hello_world/`

look at `build/zephyr/.config`:

```
#
# POSIX API Support
#

#
# POSIX Options
#
# CONFIG_POSIX_API is not set
CONFIG_POSIX_AEP_CHOICE_NONE=y
# CONFIG_POSIX_AEP_CHOICE_BASE is not set
# CONFIG_POSIX_AEP_CHOICE_PSE51 is not set
# CONFIG_POSIX_AEP_CHOICE_PSE52 is not set
# CONFIG_POSIX_AEP_CHOICE_PSE53 is not set
# CONFIG_POSIX_ASYNCHRONOUS_IO is not set
# CONFIG_POSIX_BARRIERS is not set
# CONFIG_POSIX_C_LIB_EXT is not set

#
# POSIX device I/O
#
# CONFIG_POSIX_DEVICE_IO is not set
CONFIG_POSIX_OPEN_MAX=4
# end of POSIX device I/O

# CONFIG_POSIX_FD_MGMT is not set
# CONFIG_POSIX_FILE_SYSTEM is not set

#
# POSIX memory
#
CONFIG_POSIX_PAGE_SIZE=0x40
# CONFIG_POSIX_SHARED_MEMORY_OBJECTS is not set
# CONFIG_POSIX_MAPPED_FILES is not set
# CONFIG_POSIX_MEMORY_PROTECTION is not set
# end of POSIX memory

# CONFIG_POSIX_MESSAGE_PASSING is not set
# CONFIG_POSIX_SINGLE_PROCESS is not set
# CONFIG_POSIX_MULTI_PROCESS is not set
# CONFIG_POSIX_THREADS is not set
# CONFIG_POSIX_READER_WRITER_LOCKS is not set

#
# POSIX scheduler options
#
# CONFIG_POSIX_PRIORITY_SCHEDULING is not set
# end of POSIX scheduler options

# CONFIG_POSIX_SEMAPHORES is not set

#
# POSIX signals
#
# CONFIG_POSIX_REALTIME_SIGNALS is not set
# CONFIG_POSIX_SIGNALS is not set
# end of POSIX signals

# CONFIG_POSIX_SPIN_LOCKS is not set

#
# POSIX synchronized I/O
#
# CONFIG_POSIX_FSYNC is not set
# CONFIG_POSIX_SYNCHRONIZED_IO is not set
# end of POSIX synchronized I/O

# CONFIG_POSIX_TIMERS is not set

#
# X/Open system interfaces
#
# CONFIG_XOPEN_STREAMS is not set
# CONFIG_XSI_SYSTEM_LOGGING is not set
# CONFIG_XSI_THREADS_EXT is not set
# end of X/Open system interfaces

#
# Miscellaneous POSIX-related options
#
# CONFIG_EVENTFD is not set
# end of Miscellaneous POSIX-related options

#
# Deprecated POSIX options
#
CONFIG_EVENTFD_MAX=0
# CONFIG_FNMATCH is not set
# CONFIG_GETOPT is not set
CONFIG_MAX_TIMER_COUNT=0
# CONFIG_POSIX_CLOCK is not set
# CONFIG_POSIX_FS is not set
CONFIG_POSIX_MAX_FDS=4
# CONFIG_POSIX_MQUEUE is not set
# CONFIG_POSIX_PUTMSG is not set
# CONFIG_POSIX_SIGNAL is not set
# CONFIG_POSIX_SYSCONF is not set
# CONFIG_POSIX_UNAME is not set
# CONFIG_TIMER is not set
CONFIG_SEM_NAMELEN_MAX=0
CONFIG_SEM_VALUE_MAX=0
# end of Deprecated POSIX options
# end of POSIX Options

#
# POSIX Shell Utilities
#
# end of POSIX Shell Utilities
# end of POSIX API Support
```

some enabled, some are not, but none of that need to be there, probably one top level Kconfig that is not enabled, not all the kconfig tree of that features, similar to `CONFIG_NETWORKING`:

```
#
# Networking
#
# CONFIG_NET_BUF is not set
# CONFIG_NETWORKING is not set
# end of Networking
```

or `CONFIG_BT`:

```
# CONFIG_BT is not set
```

and we do not show anything of their trees.
```

2024-07-16 01:14 UTC, cfriedt commented
@nashif - my point was that we will not be able to add a Kconfig option to gate all POSIX options because that would introduce a regression.

I would rather not do that at this point.

2024-07-16 01:19 UTC, nashif commented
> @nashif - my point was that we will not be able to add a Kconfig option to gate all POSIX options because that would introduce many regressions
> 
> I would rather not do that at this point.

Does not need to be done now and for 3.7, this can be done after 3.7.

2024-07-16 16:28 UTC, cfriedt commented
**Release Meeting 20240716**

There was some consensus that we need to have a gating Kconfig option for POSIX APIs, so that can be done after the release (it will go into 4.0).

Doing a rework of this PR so that we can drop the following Kconfig options without having to put them through the deprecation process.

* GETENTROPY
* POSIX_CONFSTR
* POSIX_ENV
* POSIX_SYSLOG

2024-10-13 00:35 UTC, closed without merging