arc: nsim: vpx5: fix SoC config issue which leads to cmake error
zephyrproject-rtos/zephyr pull request #75896
Opened 2024-07-15 17:32 UTC by evgeniy-paltsev

After recent nsim SoCs & boards reorganization the `SOC_SERIES_*` config is missing for vpx5 SoC which leads to cmake errors when building against nsim/nsim_vpx5 configuration.

Fix that.

2024-07-15 17:49 UTC, nashif submitted a review, later dismissed

2024-07-16 07:01 UTC, abrodkin submitted a review, later dismissed

2024-07-16 07:14 UTC, nordicjm requested changes
Invalid, there is no soc series nsim_vpx5 in soc.yml

2024-07-16 13:04 UTC, abrodkin approved these changes

2024-07-17 06:34 UTC, nordicjm approved these changes

2024-07-17 15:44 UTC, nashif approved these changes

2024-07-17 20:18 UTC, merged