drivers/pinctrl: it8xxx2: Fix I2C5 pin leakage
zephyrproject-rtos/zephyr pull request #75911
Opened 2024-07-16 01:43 UTC by GTLin08

When setting these pins as I2C alternate mode and then setting GCR7 or func3-ext of GPIO extended, it will cause leakage. In order to prevent leakage, it must be set to GPIO INPUT mode.

2024-07-17 08:13 UTC, GTLin08 commented on include/zephyr/drivers/i2c/i2c_ite_enhance.h
> +struct i2c_enhance_config {
Done.

2024-07-19 16:33 UTC, keith-zephyr approved these changes, later dismissed

2024-07-22 05:36 UTC, Dino-Li approved these changes, later dismissed

2024-07-24 07:48 UTC, gmarull requested changes
in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)

2024-07-24 19:45 UTC, keith-zephyr commented
> in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)

ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.

https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81

2024-07-25 14:44 UTC, gmarull commented
> > in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)
> 
> ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81

then why not use them?

2024-07-26 00:49 UTC, GTLin08 commented
> > > in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)
> > 
> > 
> > ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.
> > https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81
> 
> then why not use them?

Hi @gmarull ,

As Keith mentioned, our I2C already have the `sda-gpios` and `scl-gpios` as recovery functionality.
This PR is intended to obtain the information of the GPIO pins(`sda-gpios` and `scl-gpios`) used by I2C5 of the I2C driver in pinctrl init and set them as GPIO input to avoid power leakage.

2024-08-05 07:32 UTC, gmarull commented
> > > > in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)
> > > 
> > > 
> > > ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.
> > > https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81
> > 
> > 
> > then why not use them?
> 
> Hi @gmarull ,
> 
> As Keith mentioned, our I2C already have the `sda-gpios` and `scl-gpios` as recovery functionality. This PR is intended to obtain the information of the GPIO pins(`sda-gpios` and `scl-gpios`) used by I2C5 of the I2C driver in pinctrl init and set them as GPIO input to avoid power leakage.

There's no need to add a new API for that, information is known at compile time from DT.

2024-08-05 08:34 UTC, GTLin08 commented
> > > > > in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)
> > > > 
> > > > 
> > > > ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.
> > > > https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81
> > > 
> > > 
> > > then why not use them?
> > 
> > 
> > Hi @gmarull ,
> > As Keith mentioned, our I2C already have the `sda-gpios` and `scl-gpios` as recovery functionality. This PR is intended to obtain the information of the GPIO pins(`sda-gpios` and `scl-gpios`) used by I2C5 of the I2C driver in pinctrl init and set them as GPIO input to avoid power leakage.
> 
> There's no need to add a new API for that, information is known at compile time from DT.

While it is true that the information can be known at compile time from the DT and is accessible in i2c_ite_enhance.c for `scl_gpios` and `sda_gpios`, this information is not directly available in pinctrl_ite_it8xxx2.c. Therefore, the new API is necessary to provide the required GPIO information in the pin control context.

2024-08-05 08:38 UTC, gmarull commented
> > > > > > in scenarios where I2C gpios need to be known (eg for recovery), additional properties like `sda-gpios`, `scl-gpios` should be introduced (see other cases in tree)
> > > > > 
> > > > > 
> > > > > ITE's I2C drivers already provide `sda-gpios` and `scl-gpios`.
> > > > > https://github.com/zephyrproject-rtos/zephyr/blob/d6afb8fb521844ff8a24d70f1432a428b975a1bd/dts/bindings/i2c/ite%2Ccommon-i2c.yaml#L81
> > > > 
> > > > 
> > > > then why not use them?
> > > 
> > > 
> > > Hi @gmarull ,
> > > As Keith mentioned, our I2C already have the `sda-gpios` and `scl-gpios` as recovery functionality. This PR is intended to obtain the information of the GPIO pins(`sda-gpios` and `scl-gpios`) used by I2C5 of the I2C driver in pinctrl init and set them as GPIO input to avoid power leakage.
> > 
> > 
> > There's no need to add a new API for that, information is known at compile time from DT.
> 
> While it is true that the information can be known at compile time from the DT and is accessible in i2c_ite_enhance.c for `scl_gpios` and `sda_gpios`, this information is not directly available in pinctrl_ite_it8xxx2.c. Therefore, the new API is necessary to provide the required GPIO information in the pin control context.

You can access the entire DT from wherever you want

2024-08-05 09:21 UTC, GTLin08 commented
> You can access the entire DT from wherever you want

Are you suggesting an approach similar to the following code snippet?
```
#if defined(CONFIG_I2C_ITE_ENHANCE) && DT_NODE_HAS_STATUS(DT_NODELABEL(i2c5), okay)
	const struct device *const i2c5_dev = DEVICE_DT_GET(DT_NODELABEL(i2c5));
	const struct i2c_enhance_config *i2c5_cfg = i2c5_dev->config;

	/*
	 * When setting these pins as I2C alternate mode and then setting
	 * GCR7 or func3-ext of GPIO extended, it will cause leakage.
	 * In order to prevent leakage, it must be set to GPIO INPUT mode.
	 */
	/* Set I2C5 SCL as GPIO input to prevent leakage */
	gpio_pin_configure_dt(&i2c5_cfg->scl_gpios, GPIO_INPUT);
	/* Set I2C5 SDA as GPIO input to prevent leakage */
	gpio_pin_configure_dt(&i2c5_cfg->sda_gpios, GPIO_INPUT);
#endif
```
If so, then `i2c_enhance_config `would need to be moved from i2c_ite_enhance.c to i2c_ite_enhance.h to make it accessible. Is this what you are suggesting?

2024-08-05 09:59 UTC, gmarull commented
> > You can access the entire DT from wherever you want
> 
> Are you suggesting an approach similar to the following code snippet?
> 
> ```
> #if defined(CONFIG_I2C_ITE_ENHANCE) && DT_NODE_HAS_STATUS(DT_NODELABEL(i2c5), okay)
> 	const struct device *const i2c5_dev = DEVICE_DT_GET(DT_NODELABEL(i2c5));
> 	const struct i2c_enhance_config *i2c5_cfg = i2c5_dev->config;
> 
> 	/*
> 	 * When setting these pins as I2C alternate mode and then setting
> 	 * GCR7 or func3-ext of GPIO extended, it will cause leakage.
> 	 * In order to prevent leakage, it must be set to GPIO INPUT mode.
> 	 */
> 	/* Set I2C5 SCL as GPIO input to prevent leakage */
> 	gpio_pin_configure_dt(&i2c5_cfg->scl_gpios, GPIO_INPUT);
> 	/* Set I2C5 SDA as GPIO input to prevent leakage */
> 	gpio_pin_configure_dt(&i2c5_cfg->sda_gpios, GPIO_INPUT);
> #endif
> ```
> 
> If so, then `i2c_enhance_config `would need to be moved from i2c_ite_enhance.c to i2c_ite_enhance.h to make it accessible. Is this what you are suggesting?

No, just obtain the dt-spec from DT directly in the pinctrl driver.

2024-08-05 11:04 UTC, GTLin08 commented
> > > You can access the entire DT from wherever you want
> > 
> > 
> > Are you suggesting an approach similar to the following code snippet?
> > ```
> > #if defined(CONFIG_I2C_ITE_ENHANCE) && DT_NODE_HAS_STATUS(DT_NODELABEL(i2c5), okay)
> > 	const struct device *const i2c5_dev = DEVICE_DT_GET(DT_NODELABEL(i2c5));
> > 	const struct i2c_enhance_config *i2c5_cfg = i2c5_dev->config;
> > 
> > 	/*
> > 	 * When setting these pins as I2C alternate mode and then setting
> > 	 * GCR7 or func3-ext of GPIO extended, it will cause leakage.
> > 	 * In order to prevent leakage, it must be set to GPIO INPUT mode.
> > 	 */
> > 	/* Set I2C5 SCL as GPIO input to prevent leakage */
> > 	gpio_pin_configure_dt(&i2c5_cfg->scl_gpios, GPIO_INPUT);
> > 	/* Set I2C5 SDA as GPIO input to prevent leakage */
> > 	gpio_pin_configure_dt(&i2c5_cfg->sda_gpios, GPIO_INPUT);
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If so, then `i2c_enhance_config `would need to be moved from i2c_ite_enhance.c to i2c_ite_enhance.h to make it accessible. Is this what you are suggesting?
> 
> No, just obtain the dt-spec from DT directly in the pinctrl driver.

Done.

2024-08-05 11:28 UTC, gmarull approved these changes

2024-08-05 15:11 UTC, keith-zephyr approved these changes

2024-08-08 10:47 UTC, Dino-Li approved these changes

2024-08-13 12:55 UTC, merged