drivers: spi: stm32 half duplex support
zephyrproject-rtos/zephyr pull request #75983
Opened 2024-07-17 07:27 UTC by vai-rikar

Add support for `SPI_HALF_DUPLEX ` flag for STM32 SPI driver. Tested with stm32u575 with and without `CONFIG_SPI_STM32_INTERRUPT`, and with DMA.

2024-09-17 06:48 UTC, erwango commented
I'm quite late to answer but thanks for this work, we'll review in coming weeks

2024-11-27 11:13 UTC, erwango requested changes
Sorry for very late review.

Looks sane a priori. I didn't fully completed the review, but some comments.

I have 2 requests:
- Would you mind rebasing (even if there is no conflicts), because I'd like to perform some testing on our test farm but this require to be in recent main due to recent ci changes in twister.
- Any way we can excercise this code in CI ?

2024-11-27 11:13 UTC, erwango commented on drivers/spi/spi_ll_stm32.c
> +	LL_SPI_SetTransferSize(spi, 0);
This change isn't directly linked to half duplex support. Would you  mind making it a dedicated commit, with proper justification ?

2024-11-27 11:13 UTC, erwango commented on drivers/spi/spi_ll_stm32.c
> +	bool write)
Indentation

2024-12-03 11:04 UTC, vai-rikar commented
Thanks for the review and comments.

> * Would you mind rebasing (even if there is no conflicts), because I'd like to perform some testing on our test farm but this require to be in recent main due to recent ci changes in twister.

Rebase done and fixed the issues mentioned.

> * Any way we can excercise this code in CI ?

Would be great if there were tests for this in CI. I'm not sure how this should be done and unfortunately I don't have time to looking into it in the next couple of months.

2024-12-06 14:18 UTC, erwango approved these changes

2024-12-10 10:30 UTC, vai-rikar commented on drivers/spi/spi_ll_stm32.c
> +			spi_context_update_rx(&data->ctx, frame_size_bytes, dma_len);
Currently transfer direction is set only to `LL_SPI_FULL_DUPLEX`, `LL_SPI_HALF_DUPLEX_TX` or `LL_SPI_HALF_DUPLEX_RX`. So `LL_SPI_HALF_DUPLEX_RX` is the only possibility in the else branch. I see that there are `LL_SPI_SIMPLEX_TX/RX` (stm32h7xx_ll_spi.h) definitions also but those are currently not used.

I can change this if you like, but there are multiple places where the if is omitted from the else branch.

2024-12-18 02:18 UTC, kartben commented
@FRASTM are you able to actually go as far as giving a +1 to move this forward?

2025-01-09 03:03 UTC, kartben commented
Ping @FRASTM

2025-01-09 08:45 UTC, FRASTM approved these changes

2025-01-09 08:51 UTC, merged