doc: releases: Add logging release notes
zephyrproject-rtos/zephyr pull request #75993
Opened 2024-07-17 10:56 UTC by nordic-krch

Add release notes for 3.7 for logging subsystem.

2024-07-17 11:14 UTC, aescolar submitted a review, later dismissed

2024-07-17 11:47 UTC, nashif submitted a review, later dismissed

2024-07-17 13:20 UTC, kartben requested changes

2024-07-17 13:20 UTC, kartben commented on doc/releases/release-notes-3.7.rst
> +  * Add c:func:`log_thread_trigger` for triggering processing of the log messages.
```suggestion
  * Add :c:macro:`LOG_WRN_ONCE` for logging warning message where only the first occurrence is
    logged.

  * Add :c:func:`log_thread_trigger` for triggering processing of the log messages.
```

2024-07-19 07:05 UTC, aescolar approved these changes

2024-07-19 07:05 UTC, aescolar commented
@kartben please take another look :)

2024-07-20 08:24 UTC, kartben approved these changes

2024-07-20 08:26 UTC, merged