bluetooth: Kconfig: include shell even if !BT_HCI
zephyrproject-rtos/zephyr pull request #76007
Opened 2024-07-17 13:36 UTC by Damian-Nordic

We need use the bluetooth shell commands with a custom BLE stack that implements the Zephyr BLE API.

The shell commands build properly even without using BT_HCI so there's no reason to restrict them to HCI-based stack.

2024-07-17 20:10 UTC, alxelax approved these changes

2024-07-18 09:17 UTC, canisLupus1313 approved these changes

2024-07-18 09:55 UTC, carlescufi requested changes
Please provide a bit more context.

2024-07-18 10:51 UTC, carlescufi approved these changes
Additional context: This is used when the application resides in a core different from the core running the Host and Controller in an AMP configuration. This means the application invokes the Zephyr Bluetooth APIs via an RPC mechanism, but with no Bluetooth implementation in the build.
More information here:
https://github.com/nrfconnect/sdk-nrf/tree/collab-serial-ble-ot/applications/protocols_serialization

2024-07-22 08:56 UTC, jhedberg requested changes
There seems to be a few minor things to fix if we do this:

 - `subsys/bluetooth/shell/hci.c` doesn't right now depend on `BT_HCI` being enabled
 - It seems like it should be valid to also build `subsys/bluetooth/services` even if `BT_HCI` is not enabled (if we go with the assumption that the Zephyr Bluetooth API can still be made available then). Right now the `services/Kconfig` is included from `host/Kconfig` which seems wrong to me - it should get included from the top-level Bluetooth Kconfig file.

2024-07-23 10:24 UTC, jori-nordic approved these changes
I also agree with @jhedberg services could be enabled too. 
`host/shell/hci.c` it seems it's just a wrapper for one mesh command, we should move the hci command helpers into it at some point.

I think all of these points can be addressed in a future PR.

2024-07-23 11:12 UTC, Damian-Nordic commented
I realized that sourcing `services/Kconfig` had intentionally been moved to `host/Kconfig` by https://github.com/zephyrproject-rtos/zephyr/pull/42852/files to reduce the number of options for controller-only builds. I would revert this change back if I were to address the comments in this PR, so I guess a proper solution would be adding some Kconfig indicating that any Bluetooth host is present (not just BT_HCI).

For this I don't have time and I found an alternative way to fix the build in our scenario so closing this PR.

2024-07-23 11:12 UTC, closed without merging