release: Zephyr v3.7.0
zephyrproject-rtos/zephyr pull request #76047
Opened 2024-07-18 08:18 UTC by aescolar

* Set the version to v3.7.0
* Remove working draft status from the v3.7.0 release notes and migration guide.
* doc: release: Add v3.7.0 to the list of supported releases

Note the 3.5 release is not yet removed as its EOL is 1 week after release of 3.7.0

--------

Just like for the candidates, readying the version update and leaving it as DNM by now

2024-07-18 08:33 UTC, gmarull submitted a review, later dismissed

2024-07-18 08:39 UTC, kartben requested changes

2024-07-18 08:39 UTC, kartben commented on doc/conf.py
> +        ("3.7.0", "/3.7.0/"),
```suggestion
        ("3.7.0 (LTS)", "/3.7.0/"),
```

2024-07-18 09:34 UTC, fabiobaltieri approved these changes

2024-07-18 10:05 UTC, kartben approved these changes

2024-07-18 10:11 UTC, henrikbrixandersen approved these changes

2024-07-18 14:33 UTC, MaureenHelm approved these changes

2024-07-18 17:11 UTC, teburd approved these changes

2024-07-19 01:21 UTC, dkalowsk approved these changes

2024-07-26 11:17 UTC, merged