drivers: usb: udc: add USB device controller SoF report capability
zephyrproject-rtos/zephyr pull request #76073
Opened 2024-07-18 21:02 UTC by henrikbrixandersen

- Add capability for whether a USB device controller reports Start of Frame (SoF) events.
- Add `usbd_reports_sof()` wrapper function for determining whether the underlying USB device controller report Start of Frame (SoF) events.

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

2024-07-18 22:47 UTC, jfischer-no commented
I am confused, what controller would not have this capability?

2024-07-18 23:36 UTC, henrikbrixandersen commented
> I am confused, what controller would not have this capability?

As far as I can tell, only the controller drivers I've modified here support SoF event reporting.

The `udc_mcux_ip3511.c` driver, as an example, doesn't support it - and as far as I can tell from the reference manuals, it's not just the driver, the hardware doesn't seem to support it either.

2024-07-19 06:46 UTC, tmon-nordic commented
> The `udc_mcux_ip3511.c` driver, as an example, doesn't support it - and as far as I can tell from the reference manuals, it's not just the driver, the hardware doesn't seem to support it either.

Can you link to the reference manual? Googling for IP3511 leads only to the source code and not actual reference manual.

2024-07-19 07:21 UTC, henrikbrixandersen commented
> Can you link to the reference manual? Googling for IP3511 leads only to the source code and not actual reference manual.

The details are in the user manual for the SoCs where it is used. Check for instance NXP UM11295, the user manual for the LPC551x/LPC55S1x: https://www.nxp.com/webapp/Download?colCode=UM11295 (requires login).

2024-07-19 07:31 UTC, tmon-nordic commented
> The details are in the user manual for the SoCs where it is used. Check for instance NXP UM11295, the user manual for the LPC551x/LPC55S1x: https://www.nxp.com/webapp/Download?colCode=UM11295 (requires login).

It has SoF interrupt, just named FRAME_INT enabled with FRAME_INT_EN bit.

Besides the SoF interrupt, it also has dedicated output pin that toggles on each SoF packet.

2024-07-19 07:32 UTC, tmon-nordic requested changes
Blocking unless there indeed is a controller in the wild lacking SoF interrupt capability.

2024-07-19 07:50 UTC, henrikbrixandersen commented
> Blocking unless there indeed is a controller in the wild lacking SoF interrupt capability.

That's fair, but the current state is that the following _drivers_ seemingly do not support reporting of `UDC_EVT_SOF`:
- `drivers/usb/udc/udc_it82xx2.c`
- `drivers/usb/udc/udc_kinetis.c`
- `drivers/usb/udc/udc_mcux_ehci.c`
- `drivers/usb/udc/udc_mcux_ip3511.c`
- `drivers/usb/udc/udc_virtual.c`

I will open a separate issue for these.

2024-07-19 07:58 UTC, jfischer-no commented
> > Blocking unless there indeed is a controller in the wild lacking SoF interrupt capability.
> 
> That's fair, but the current state is that the following _drivers_ seemingly do not support reporting of `UDC_EVT_SOF`:


What is the problem with not supporting SOF events? Tell us what you want to use it for.

2024-07-19 08:06 UTC, henrikbrixandersen commented
> What is the problem with not supporting SOF events? Tell us what you want to use it for.

I am using SoF for hardware timestamping in a USB-to-CAN adapter. The SoF event provides means for synchronization between the host clock and the USB device ("give me the timestamp from when I initialized this USB control transfer), allowing for a much higher accuracy of the Rx/Tx timestamps.

2024-07-19 09:05 UTC, jfischer-no commented
> > What is the problem with not supporting SOF events? Tell us what you want to use it for.
> 
> I am using SoF for hardware timestamping in a USB-to-CAN adapter. The SoF event provides means for synchronization between the host clock and the USB device ("give me the timestamp from when I initialized this USB control transfer"), allowing for a much higher accuracy of the Rx/Tx timestamps.

I want to add timestamps to SoF events, so stamping would be at the SoF interrupt in the USB device controller driver, perhaps using k_uptime_ticks()(?). Is is something you can reuse?

2024-07-19 09:12 UTC, henrikbrixandersen commented
> I want to add timestamps to SoF events, so stamping would be at the SoF interrupt in the USB device controller driver, perhaps using k_uptime_ticks()(?). Is is something you can reuse?

I don't think so. The currently established protocol relies on a free-running 32-bit counter @ 1MHz, providing microsecond resolution timestamps, which is both used for synchronizing host and device timestamps and timestamping of CAN Rx/Tx events asynchronous to USB transfers.

2024-07-23 13:48 UTC, henrikbrixandersen commented
> I will open a separate issue for these.

I have now opened an issue for each USB udc driver not reporting the `UDC_EVT_SOF` event (as linked above).

2024-07-23 16:09 UTC, henrikbrixandersen commented
> > I will open a separate issue for these.
> 
> I have now opened an issue for each USB udc driver not reporting the `UDC_EVT_SOF` event (as linked above).

@jfischer-no I see you have changed all those issues from bug to enhancement. If those are really enhancements and not bugs, we need to re-consider this PR for inclusion.

Application code needing SoF events does not care whether missing SoF event support is due to a hardware or a driver limitation.

2024-07-24 10:14 UTC, henrikbrixandersen commented
@tmon-nordic Please reconsider. Either SoF event support is an optional capability (and therefore missing SoF event support is not a bug) or the issues, I have created, should remain as bugs and not enhancements.

2024-07-24 10:46 UTC, fabiobaltieri commented
Well I guess it does not really change much how the issue is flagged... @henrikbrixandersen are you adding a driver with the capability? https://github.com/zephyrproject-rtos/zephyr/pull/76073#pullrequestreview-2187539793 sounds like a reasonable request

2024-07-24 11:13 UTC, henrikbrixandersen commented
> Well I guess it does not really change much how the issue is flagged... @henrikbrixandersen are you adding a driver with the capability? [#76073 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/76073#pullrequestreview-2187539793) sounds like a reasonable request

The following in-tree drivers already support reporting `USBD_EVT_SOF`:
- `drivers/usb/udc/udc_dwc2.c`
- `drivers/usb/udc/udc_nrf.c`
- `drivers/usb/udc/udc_stm32.c`

2024-07-24 11:15 UTC, fabiobaltieri commented
Sorry I see that now, so that question is already addressed @tmon-nordic?

2024-07-24 11:18 UTC, tmon-nordic commented
> Sorry I see that now, so that question is already addressed @tmon-nordic?

I cannot quite imagine why a controller might not be capable of reporting SoF. I wouldn't make this optional feature unless there is really a controller out there that simply cannot handle it (and therefore some sort of solution would be necessary).

2024-07-24 11:21 UTC, henrikbrixandersen commented
> I cannot quite imagine why a controller might not be capable of reporting SoF. I wouldn't make this optional feature unless there is really a controller out there that simply cannot handle it (and therefore some sort of solution would be necessary).

I get that. This is why I reported the bugs linked above, but these were changed from bug to enhancement by @jfischer-no. Either not implementing SoF is a bug and needs to fixed, or SoF support is an "enhancement" (meaning optional in my interpretation), and this capability makes sense.

2024-07-24 11:29 UTC, tmon-nordic commented
> I get that. This is why I reported the bugs linked above, but these were changed from bug to enhancement by @jfischer-no. Either not implementing SoF is a bug and needs to fixed, or SoF support is an "enhancement" (meaning optional in my interpretation), and this capability makes sense.

If the underlying HW does support it then I consider the issues to be bugs.

2024-07-24 15:09 UTC, jfischer-no commented
> > I cannot quite imagine why a controller might not be capable of reporting SoF. I wouldn't make this optional feature unless there is really a controller out there that simply cannot handle it (and therefore some sort of solution would be necessary).
> 
> I get that. This is why I reported the bugs linked above, but these were changed from bug to enhancement by @jfischer-no. Either not implementing SoF is a bug and needs to fixed, or SoF support is an "enhancement" (meaning optional in my interpretation), and this capability makes sense.

As long as the support is experimental and there is nothing broken in the tree because a driver does not implement SoF events, I do not consider it a bug. And since it is very unlikely that there is a controller that does not support SoF interrupt, it does not make sense to introduce this capability flag.

2024-07-30 12:58 UTC, MarkWangChinese commented
I have one concern. The USB sof is 1ms for FS, 125us for HS. If enable it, the corresponding interrupt will happen every 1ms or 12us. Do you plan to enable it default? Do we need one Kconfig macro (default disabled) to control it?

2024-07-30 13:30 UTC, fabiobaltieri commented
> I think HID can benefit from having the SOF interrupt.

Why is that? Polling for stuff like buttons just in time?

2024-07-30 13:56 UTC, henrikbrixandersen commented
> @jfischer-no Should we have compile-time and/or runtime check whether SOF is needed and only enable it if necessary?

A compile-time option defaulting to off is a good idea.

2024-07-31 06:23 UTC, tmon-nordic commented
> > I think HID can benefit from having the SOF interrupt.
> 
> Why is that? Polling for stuff like buttons just in time?

With bInterval = 1 there will be a single IN (or up to 3 INs for High-Bandwidth endpoints, but if you're late with the first one there won't be more) anywhere between the two subsequent SOFs. It can be that the IN during SOF n will be at the very end of the (micro-)frame and the IN during SOF n+1 will be at the very beginning => the time between two INs can be significantly shorter than the time between two SOFs. Therefore, tying the report generation to "IN data ACKed" can leave too little time for SW to process the data.

This only matters if you do not want to miss any chance the device had to transfer data, otherwise it can be ignored.

2024-07-31 10:35 UTC, fabiobaltieri commented
> This only matters if you do not want to miss any chance the device had to transfer data, otherwise it can be ignored.

Interesting, never thought about that use case, so in a situation where you had input devices generating data asyncronously and the controller supports SOF frame generation, it sounds like it would make sense to keep the most up-to-date report in memory, keep updating it and only send on an SOF event, right? But then you do indeed need to make sure that the driver supports that. (sorry for the parallel conversation, just trying to understand the use case)

2024-07-31 11:01 UTC, tmon-nordic commented
> > This only matters if you do not want to miss any chance the device had to transfer data, otherwise it can be ignored.
> 
> Interesting, never thought about that use case, so in a situation where you had input devices generating data asyncronously and the controller supports SOF frame generation, it sounds like it would make sense to keep the most up-to-date report in memory, keep updating it and only send on an SOF event, right? But then you do indeed need to make sure that the driver supports that. (sorry for the parallel conversation, just trying to understand the use case)

Correct, except I would do keep updating the most up-to-date report in memory, but enqueue it immediately after the previous one is completed (using the "pre-generated" report data at SOF). But note that there are implementation challenges like what to do with buttons that were pressed and depressed in between the INs.

This problem is rather simple to solve on FPGA (when you run the USB stack and USB device driver on FPGA), but it is really hard to do in SW (SW will always have some window for the "time between subsequent INs" where it simply cannot be fast enough).

2024-07-31 14:48 UTC, jfischer-no commented
> > @jfischer-no Should we have compile-time and/or runtime check whether SOF is needed and only enable it if necessary?
> 
> A compile-time option defaulting to off is a good idea.

If at all, depending on how it is implemented, .e.g. no way for #ifdefs, then with default y.

2024-08-19 19:08 UTC, henrikbrixandersen commented
Seeing that most usbd drivers in-tree now support the SoF event, I'll close this proposal. 

Thanks to all for taking part of discussions here, which lead to a better solution.

2024-08-19 19:08 UTC, closed without merging