boards: *nrf52840: fix `usb_cdc` support
zephyrproject-rtos/zephyr pull request #76096
Opened 2024-07-19 10:29 UTC by JordanYates

`usb_cdc` as a supported tag was removed with #73273, and as nrf52840 based platforms they support the `usbd` tag introduced in #73269.

2024-07-19 11:15 UTC, bjarki-andreasen approved these changes, later dismissed

2024-07-23 13:50 UTC, henrikbrixandersen approved these changes, later dismissed

2024-07-23 23:27 UTC, JordanYates commented
Fairly certain any twister runtime failures cannot be the result of this PR, or the manifest check failure

2024-07-24 07:26 UTC, bjarki-andreasen commented
The change causes test suites filtered on `usbd` supoort to be built for `ctcc_nrf52840` which then fail, are we sure the `ctcc_nrf52840` supports `usbd`?

```
INFO    - 1) samples/subsys/usb/cdc_acm/sample.usb_device_next.cdc-acm on ctcc/nrf52840 error (Build failure)
INFO    - 2) samples/subsys/usb/mass/sample.usb_device_next.mass_ram_none on ctcc/nrf52840 error (Build failure)
INFO    - 3) samples/subsys/usb/shell/sample.usbd.shell on ctcc/nrf52840 error (Build failure)
INFO    - 4) tests/drivers/udc/drivers.usb.udc on ctcc/nrf52840 error (Build failure)
```

The issue is:
```
gen_isr_tables.py: error: multiple registrations at table_index 39 for irq 39 (0x27)
```
which seems to be a shared interrupt not being handled properly :)

2024-07-24 07:37 UTC, JordanYates commented
> The change causes test suites filtered on `usbd` supoort to be built for `ctcc_nrf52840` which then fail, are we sure the `ctcc_nrf52840` supports `usbd`?
> 
> ```
> INFO    - 1) samples/subsys/usb/cdc_acm/sample.usb_device_next.cdc-acm on ctcc/nrf52840 error (Build failure)
> INFO    - 2) samples/subsys/usb/mass/sample.usb_device_next.mass_ram_none on ctcc/nrf52840 error (Build failure)
> INFO    - 3) samples/subsys/usb/shell/sample.usbd.shell on ctcc/nrf52840 error (Build failure)
> INFO    - 4) tests/drivers/udc/drivers.usb.udc on ctcc/nrf52840 error (Build failure)
> ```
> 
> The issue is:
> 
> ```
> gen_isr_tables.py: error: multiple registrations at table_index 39 for irq 39 (0x27)
> ```
> 
> which seems to be a shared interrupt not being handled properly :)

Apparently the switch is not always valid with only the changes to the SoC. Dropped the tag from that board.

2024-07-24 09:35 UTC, bjarki-andreasen submitted a review, later dismissed

2024-07-24 10:10 UTC, henrikbrixandersen submitted a review, later dismissed

2024-07-24 14:22 UTC, jfischer-no requested changes
usb_cdc was not a supported tag, but a test feature. Please use commit references.

```
boards: *nrf52840: remove test feature usb_cdc

Follow-up on commit 0809b75b42e6
("boards: remove test feature usb_cdc")
```

There is no need to add `usbd` to `boards/sparkfun/micromod/micromod_nrf52840.yaml` yet.

2024-07-25 07:54 UTC, bjarki-andreasen approved these changes

2024-07-30 15:54 UTC, kartben approved these changes

2024-08-16 15:41 UTC, ubieda approved these changes

2024-08-16 17:33 UTC, jfischer-no requested changes
Commit message not addressed as requested in https://github.com/zephyrproject-rtos/zephyr/pull/76096#pullrequestreview-2196904801

2024-08-17 00:12 UTC, JordanYates commented
> Commit message not addressed as requested in [#76096 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/76096#pullrequestreview-2196904801)

Is this a nack because the commit title and message are not formatted exactly as you would have written? Or have I missed something?
It refers to the commit as you wished, whether it was a test feature or a supported tag is a matter of semantics, it was in the tree, on dozens of boards, ergo it was supported.

2024-08-17 07:04 UTC, henrikbrixandersen approved these changes

2024-08-21 21:51 UTC, jfischer-no commented
> > Commit message not addressed as requested in [#76096 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/76096#pullrequestreview-2196904801)
> 
> Is this a nack because the commit title and message are not formatted exactly as you would have written? Or have I missed something? It refers to the commit as you wished, whether it was a test feature or a supported tag is a matter of semantics, it was in the tree, on dozens of boards, ergo it was supported.

Mostly because of "`usb_cdc` as a supported tag was removed in...". "supported" is wrong, there was nothing like "usb_cdc" supported by anything. Also, missing a feature does not mean that a board does not support it. For example, missing the feature usb_device does not mean that a board does not support USB device controller, just that it is not used by a test scenario that depends on usb_device. And these copy-paste (errors) are caused by the impression that the feature list used only by Test Runner are checkboxes that one absolutely have to set.

2024-10-10 08:34 UTC, JordanYates commented
> > > Commit message not addressed as requested in [#76096 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/76096#pullrequestreview-2196904801)
> > 
> > 
> > Is this a nack because the commit title and message are not formatted exactly as you would have written? Or have I missed something? It refers to the commit as you wished, whether it was a test feature or a supported tag is a matter of semantics, it was in the tree, on dozens of boards, ergo it was supported.
> 
> Mostly because of "`usb_cdc` as a supported tag was removed in...". "supported" is wrong, there was nothing like "usb_cdc" supported by anything. Also, missing a feature does not mean that a board does not support it. For example, missing the feature usb_device does not mean that a board does not support USB device controller, just that it is not used by a test scenario that depends on usb_device. And these copy-paste (errors) are caused by the impression that the feature list used only by Test Runner are checkboxes that one absolutely have to set.

Please provide the exact commit message that you would like to see in order to approve this PR then, as I don't see the distinction.

2024-11-13 11:59 UTC, jfischer-no commented
> > > > Commit message not addressed as requested in [#76096 (review)](https://github.com/zephyrproject-rtos/zephyr/pull/76096#pullrequestreview-2196904801)
> > > 
> > > 
> > > Is this a nack because the commit title and message are not formatted exactly as you would have written? Or have I missed something? It refers to the commit as you wished, whether it was a test feature or a supported tag is a matter of semantics, it was in the tree, on dozens of boards, ergo it was supported.
> > 
> > 
> > Mostly because of "`usb_cdc` as a supported tag was removed in...". "supported" is wrong, there was nothing like "usb_cdc" supported by anything. Also, missing a feature does not mean that a board does not support it. For example, missing the feature usb_device does not mean that a board does not support USB device controller, just that it is not used by a test scenario that depends on usb_device. And these copy-paste (errors) are caused by the impression that the feature list used only by Test Runner are checkboxes that one absolutely have to set.
> 
> Please provide the exact commit message that you would like to see in order to approve this PR then, as I don't see the distinction.

There should not be any `usb_cdc` in the tree anymore. Not sure why it does not conflict.

2024-11-13 12:02 UTC, closed without merging

2024-11-13 12:02 UTC, JordanYates commented
Giving up, PR blocked based on wording quibbles with no clear guidance on what wording would be acceptable.