boards: ct: ctcc: add M.2 picture and fix pictures quality
zephyrproject-rtos/zephyr pull request #76107
Opened 2024-07-19 13:50 UTC by kowalewskijan

Provides a picture of M.2 version of a card and fixes quality mPCIe version.

2024-07-20 08:09 UTC, aescolar reviewed
That's an extra 170KB of binary data in the tree. The original picture seems quite enough for Zephyr's documentation.
@kartben do we have some policy about this?

2024-07-20 08:28 UTC, aescolar requested changes, later dismissed
If you could remove the pictures change and leave only release notes change we could merge the release notes change right away and defer the discussion about the new pictures. Thank you.

2024-07-22 06:30 UTC, nordicjm requested changes

2024-07-22 06:30 UTC, nordicjm commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.png
Remove excess spacing on images, convert to webp and put through https://tinypng.com/

2024-07-22 08:38 UTC, kowalewskijan commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.png
is it really necessary to have them in webp? I think it is allowed to have `.png`, `.jpeg`, `.jpg` or `.svg`

2024-07-22 08:41 UTC, kowalewskijan commented
> If you could remove the pictures change and leave only release notes change we could merge the release notes change right away and defer the discussion about the new pictures. Thank you.

According to compliance check, each picture can have up to 100kB. Right now the current picture seems really blurred and since the documentation mentions also M.2 version I wanted to add a picture of such version also.

2024-07-22 08:53 UTC, kartben commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.png
the point is to try to use as modern of a file format as possible, and webp is typically the best for boards images where we kind of want the best of both PNG (with ability to have a transparent background) and JPG (overall compression)

2024-07-22 09:01 UTC, kartben commented
> > If you could remove the pictures change and leave only release notes change we could merge the release notes change right away and defer the discussion about the new pictures. Thank you.
> 
> @aescolar According to compliance check, each picture can have up to 100kB. Right now the current picture seems really blurred and since the documentation mentions also M.2 version I wanted to add a picture of such version also.

The images you contributed are also quite blurry, fwiw, and probably mainly because you had to make them pretty small, pixel-wise, to fit under 100K.

This one https://raw.githubusercontent.com/zephyrproject-rtos/zephyr/34de9cc150a9e88851b486b92fd00429b7e9add1/boards/ct/ctcc/doc/img/ctcc_nrf52840_mpcie.png , besides not having a transparent background, is basically only 13K if converted to Webp

I would recommend you try to use your original hi-res 3D renders (if you have access to them) and convert them to 600px wide webp image. This way you'll have a transparent background, and best visual quality.

TLDR: yes compliance check says 100K max but above all we want to be mindful of the fact these are resources that end up making the Git repo increasingly large, so each new image being introduced should be "worth it".

Thanks!

2024-07-22 09:08 UTC, kowalewskijan commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.png
Ok, thanks. I'll use original renders and convert them to webp

2024-07-22 14:46 UTC, kowalewskijan commented
@aescolar @kartben @nordicjm - I converted images to webp and to equal size of 600x800 which gave 32kB each. Let me know if it's fine.

2024-07-22 15:59 UTC, aescolar commented
@kowalewskijan would it make sense to crop all that white away?

2024-07-22 16:32 UTC, kowalewskijan commented
Pictures have transparent background, I checked that by viewing `index.rst`

2024-07-23 15:11 UTC, kowalewskijan commented
@kartben @nordicjm PTAL

2024-07-23 16:29 UTC, kartben submitted a review, later dismissed

2024-07-24 10:01 UTC, nordicjm commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.webp
Why is there such excess spacing on these images? It looks very silly on https://builds.zephyrproject.io/zephyr/pr/76107/docs/boards/ct/ctcc/doc/index.html

I imagine it makes the pdf look worse

2024-07-24 15:35 UTC, kowalewskijan commented on boards/ct/ctcc/doc/img/ctcc_nrf52840_m2.webp
I trimmed the excessive spacing around images. PTAL

2024-07-25 07:14 UTC, nordicjm approved these changes

2024-07-25 12:54 UTC, kowalewskijan commented
@kartben, could you take a look one more time?

2024-07-26 08:00 UTC, kartben approved these changes

2024-07-26 08:01 UTC, merged