soc: stm32f1: add port uart4
zephyrproject-rtos/zephyr pull request #7616
Opened 2018-05-17 07:42 UTC by jli157

Enable supporting UART4 on STM32F1 SoC.

Signed-off-by: Jun Li <jun.r.li@intel.com>

2018-05-17 08:34 UTC, erwango requested changes
One comment, otherwise looks good

2018-05-17 08:34 UTC, erwango commented on dts/arm/st/stm32f1.dtsi
> +		usart4: serial@40004c00 {
Looking in ext/hal/st/stm32cube/stm32f1xx/soc/stm32f1*.h files, it appears UART4 is present only in half of SoCs of STM32F1 series.
So, if you need UART4, you need to add it in the variant dsti file (stm32f103xe.dsti or stm32f107.dtsi)

2018-05-17 09:44 UTC, ydamigos commented
In ext/hal/st/stm32cube/stm32f1xx/soc/stm32f1*.h files, it appears UART4 and in this PR all it appears as USART4, shouldn't we change it to UART4 like in the DT files of stm32f4 series?

2018-05-17 09:48 UTC, erwango commented
> In ext/hal/st/stm32cube/stm32f1xx/soc/stm32f1*.h files, it appears UART4 and in this PR it appears as USART4, shouldn't we change it to UART4 like in the DT files of stm32f4 series?

Indeed, this is UART and not USART, thanks for catching that.

2018-05-22 11:30 UTC, erwango requested changes
Some additional comments.
Otherwise we're good

2018-05-22 11:30 UTC, erwango commented on dts/arm/st/stm32f107.dtsi
> +
remove this blank line

2018-05-22 11:30 UTC, erwango commented on dts/arm/st/stm32f103Xe.dtsi
> +			compatible = "st,stm32-usart", "st,stm32-uart";
Remove compatible "st,stm32-usart"

2018-05-22 11:30 UTC, erwango commented on dts/arm/st/stm32f107.dtsi
> +			compatible = "st,stm32-usart", "st,stm32-uart";
remove compatible "st,stm32-usart"

2018-05-22 17:42 UTC, jli157 commented
Revised the code again based on the further comments. Also, fixed naming bugs in the file: arch/arm/soc/st_stm32/stm32f1/dts.fixup where all `ST_STM32_USART_40004C00` shall be replaced by `ST_STM32_UART_40004C00`.

2018-05-22 17:45 UTC, ydamigos approved these changes
LGTM

2018-05-23 07:09 UTC, erwango approved these changes

2018-05-25 16:58 UTC, galak approved these changes

2018-05-25 16:58 UTC, merged