Bluetooth: mesh: Add split build configuration for sample
zephyrproject-rtos/zephyr pull request #76161
Opened 2024-07-22 10:34 UTC by jori-nordic

Add a build configuration that enables mesh when building one of the hci_something applications.

Also direct users to it from the README.

2024-07-22 10:37 UTC, matt-wood-ct commented
+1

2024-07-22 11:13 UTC, jhedberg approved these changes

2024-07-22 11:23 UTC, omkar3141 reviewed
Additionally, 

1. It is worth to add [nrf52840dk_nrf52840.overlay](https://github.com/jori-nordic/zephyr/commit/bfb3e3090dc534ec7d3797eb6667685e8de2ff38#diff-6f9f906e09e271441b576edfc25e1ae2ccfd9b706b9d8981b2322330bfd9d80d) to "hci_spi"

2. and [nrf52840dk_nrf52840.overlay](https://github.com/jori-nordic/zephyr/commit/bfb3e3090dc534ec7d3797eb6667685e8de2ff38#diff-59f35f36f5b959fa26306c205029a8b020ea94d075b8b4b410c4c18211c93bb3) as "nrf52840dk_nrf52840_hci_spi.overlay" to mesh sample.

This along with doc changes would allow users to evaluate this properly.

2024-07-22 11:23 UTC, omkar3141 commented on samples/bluetooth/mesh/README.rst
> +Additional kconfig options need to be set on the Bluetooth controller
It is worth to set this off as a subsection in sample docs (and move it as a last para):
```suggestion
Bluetooth controller on different device:
=========================================
Additional kconfig options need to be set on the Bluetooth controller
```

2024-07-22 12:26 UTC, alxelax requested changes

2024-07-22 12:34 UTC, jori-nordic commented on samples/bluetooth/mesh/README.rst
> +Additional kconfig options need to be set on the Bluetooth controller
can you please do it then?

2024-07-22 12:36 UTC, alxelax commented on samples/bluetooth/mesh/README.rst
> +Additional kconfig options need to be set on the Bluetooth controller
Copy-paste this in other 2 files? :)

2024-07-22 13:54 UTC, alxelax commented
Hi @jori-nordic, please apply my patch: https://github.com/alxelax/zephyr/commit/ea3784f6cd97afb347f77b4a9db07b06e54ccc83

2024-07-22 15:10 UTC, omkar3141 commented on samples/bluetooth/mesh/README.rst
> +Additional kconfig options need to be set on the Bluetooth controller
I thought about this earlier. 

Perhaps we should have a common RST fragment that tells how to run sample using the split config, and include that in both readmes. 

I feel, after following the instructions in this sample and then by using hci_spi sample, users should ideally be able to fully evaluate this, at least on 52 platform (other platform support could be enabled in hci_spi by respective contributors) without having to add any extra magic settings.

2024-07-23 06:00 UTC, jori-nordic commented
I think documenting this properly is better handled by the mesh experts 📜🧙

2024-07-23 06:00 UTC, closed without merging