kconfig: zephyr: Set default BUILD_NO_GAP_FILL to Y
zephyrproject-rtos/zephyr pull request #76214
Opened 2024-07-23 11:08 UTC by butok

Set default BUILD_NO_GAP_FILL to Y.
It fixes generation of huge .hex files, even they can have many gigabytes. 
.elf files do not have filled gaps, so no any need to fill gaps for .hex.

2024-07-23 11:18 UTC, nordicjm requested changes
That might be the case with hex file but is certainly not the case with bin files, for which things like MCUboot signing rely upon

2024-07-23 11:34 UTC, butok commented
> That might be the case with hex file but is certainly not the case with bin files, for which things like MCUboot signing rely upon

No problem The BUILD_NO_GAP_FILL influence the behaviour for the .hex files.
Just checked with the MCUBoot test application. No issues.
Also many platforms already set it to Y.
Guess, it was not set to Y by mistake.

2024-07-24 06:34 UTC, butok commented
Hi @nordicjm 
Are you still asking for a rework? What exactly?

2024-08-06 08:21 UTC, nordicjm approved these changes, later dismissed
Works with MCUboot builds

2024-08-06 08:28 UTC, tejlmand requested changes
> It fixes generation of huge .hex files, even they can have many gigabytes.

To fix something then it must be considered broken :wink: 

Whether gap fill per default is to be considered broken depends highly on the target.
Especially bin files often needs to be gap filled, as a bin file doesn't contain address information.

This change is impacting all board targets (as well as hex, bin,and s19 file conversion) and thus might cause regression which are not discovered until later, because ci doesn't flash all boards.

However, this change does do something good for llvm, because the llvm objcopy doesn't support gap fill per default.

Huge hex files will only be generated on targets where the hex file has content at both low and high addresses in the address space.

For now I would prefer a less intrusive PR, perhaps one which targets the SoC family in question, like it's done here: https://github.com/zephyrproject-rtos/zephyr/blob/9036400ad0d034a8db05504d3620ce7190deb893/soc/ti/k3/am6x/Kconfig.defconfig#L45-L46

Also feel free to have the adjustment enabled per default when llvm is used as toolchain.

2024-08-06 08:42 UTC, tejlmand commented
See also: https://github.com/zephyrproject-rtos/zephyr/pull/71414/commits/2bce63e526856b82d232f24ff4199845b660c5f4

2024-08-06 10:57 UTC, butok commented
> > It fixes generation of huge .hex files, even they can have many gigabytes.
> 
> To fix something then it must be considered broken 😉
> 
> Whether gap fill per default is to be considered broken depends highly on the target. Especially bin files often needs to be gap filled, as a bin file doesn't contain address information.
> 
> This change is impacting all board targets (as well as hex, bin,and s19 file conversion) and thus might cause regression which are not discovered until later, because ci doesn't flash all boards.
> 
> However, this change does do something good for llvm, because the llvm objcopy doesn't support gap fill per default.
> 
> Huge hex files will only be generated on targets where the hex file has content at both low and high addresses in the address space.
> 
> For now I would prefer a less intrusive PR, perhaps one which targets the SoC family in question, like it's done here:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/9036400ad0d034a8db05504d3620ce7190deb893/soc/ti/k3/am6x/Kconfig.defconfig#L45-L46
> 
> Also feel free to have the adjustment enabled per default when llvm is used as toolchain.

Hi @tejlmand 

The mentioned "default y if SOC_<name>" is just a very narrow workaround.

In this commit we are making a fix for all platforms, as there is no use case in Zephyr that requires gap filling in .hex.
Since we don't fill gaps for elf, we don't want to fill them in .hex, **especially as a default behavior.**

2024-08-06 11:42 UTC, tejlmand commented
@butok seems you missed:
> Especially bin files often needs to be gap filled, as a bin file doesn't contain address information.

even if removing gap fill setting, objcopy will still fill the gap when converting to bin files, because bin files does not contain address information. But now you get gaps filled with 0x00, instead of 0xFF, which is not optimal for a flash.

> as there is no use case in Zephyr that requires gap filling in .hex.

https://github.com/zephyrproject-rtos/zephyr/pull/8822

2024-08-06 12:10 UTC, butok commented
> @butok seems you missed:
> 
> > Especially bin files often needs to be gap filled, as a bin file doesn't contain address information.
> 
> even if removing gap fill setting, objcopy will still fill the gap when converting to bin files, because bin files does not contain address information. But now you get gaps filled with 0x00, instead of 0xFF, which is not optimal for a flash.
> 
> > as there is no use case in Zephyr that requires gap filling in .hex.
> 
> #8822



> @butok seems you missed:
> 
> > Especially bin files often needs to be gap filled, as a bin file doesn't contain address information.
> 
> even if removing gap fill setting, objcopy will still fill the gap when converting to bin files, because bin files does not contain address information. But now you get gaps filled with 0x00, instead of 0xFF, which is not optimal for a flash.
> 
> > as there is no use case in Zephyr that requires gap filling in .hex.
> 
> #8822

Zephyr is using objcopy to generate binary files from **.elf (not from .hex)**
As this configuration parameter has no influence on .bin, the .bin file is not touched.

2024-08-06 13:03 UTC, tejlmand commented
> Zephyr is using objcopy to generate binary files from .elf (not from .hex)

and did anyone write that bin files were created from hex files ?

Bin files are created from the elf file, and the gap fill setting is used for s19, hex, and bin files, as I wrote earlier.

And if you read the help text for the setting you are changing then that should be clear:
https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/Kconfig.zephyr#L696-L697

Although the help text could be improved, because objcopy (which is used for gnu and llvm toolchains) will actually always gap fill, but objcopy defaults to `0x00` if no gap fill argument is given (and as explained earlier, 0x00 is not desirable).

> As this configuration parameter has no influence on .bin, the .bin file is not touched.

Wrong.
https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/CMakeLists.txt#L1583-L1585
https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/CMakeLists.txt#L1666-L1670

Please take the needed time to look how a given setting is used before changing its default behavior.

2024-08-06 13:39 UTC, butok commented
> > Zephyr is using objcopy to generate binary files from .elf (not from .hex)
> 
> and did anyone write that bin files were created from hex files ?
> 
> Bin files are created from the elf file, and the gap fill setting is used for s19, hex, and bin files, as I wrote earlier.
> 
> And if you read the help text for the setting you are changing then that should be clear:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/Kconfig.zephyr#L696-L697
> 
> Although the help text could be improved, because objcopy (which is used for gnu and llvm toolchains) will actually always gap fill, but objcopy defaults to `0x00` if no gap fill argument is given (and as explained earlier, 0x00 is not desirable).
> 
> > As this configuration parameter has no influence on .bin, the .bin file is not touched.
> 
> Wrong.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/CMakeLists.txt#L1583-L1585
> 
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/edb71f0ba176edb96a1ffd212b2c0a5de09392bc/CMakeLists.txt#L1666-L1670
> 
> Please take the needed time to look how a given setting is used before changing its default behavior.

Now we have.
- Elf (no gaps) =>.hex (gaps filled by 0xFF by default) 
- Elf (no gaps) =>.bin (gaps filled by 0xFF by default, by 0x00 otherwise) 

New proposal:
To split CONFIG_BUILD_NO_GAP_FILL to 2 configuration parameters for better output control: CONFIG_BUILD_BIN_NO_GAP_FILL (default N) and CONFIG_BUILD_HEX_NO_GAP_FILL (default Y):
- Elf (no gaps) => .hex (no gaps, by default. Same as .elf) 
- Elf (no gaps) => .bin (gaps filled by 0xFF by default, by 0x00 otherwise) 

What do you think?

2024-08-21 09:55 UTC, tejlmand commented
> New proposal:
> To split CONFIG_BUILD_NO_GAP_FILL to 2 configuration parameters for better output control: CONFIG_BUILD_BIN_NO_GAP_FILL (default N) and CONFIG_BUILD_HEX_NO_GAP_FILL (default Y):

I understand you proposal, but is this really adding value to users ?

Now users creating both bin and hex files needs to enable or disable gap fill for both.

So far I don't see any real value in splitting the config into two, unless one wanted to keep the option of having a bin file with a gap-fill of 0xFF, but no gap-fill for the hex. But that's not your use-case because your board most likely already disables bin-output, because the bin file in your case would suffer the huge file (regardless of gap-fill) due to the address space in use.

Also you never replied to the original reason for having gap fill in hex files:
> > as there is no use case in Zephyr that requires gap filling in .hex.
>
> https://github.com/zephyrproject-rtos/zephyr/pull/8822

regarding nRF boards, enabling or disabling gap fill is not impacting flashing times in my local tests, so i'm not having a strong opinion on that specific part, but others might, ref: https://github.com/zephyrproject-rtos/zephyr/pull/8822#pullrequestreview-136488615.
I will let others comment on whether flash time is significantly impacted by no gap fill.

My main concern lies with changing a default value in ways that suddenly impact others in unexpected ways, unless this has been discussed within a broader audience.

2024-08-21 10:06 UTC, butok commented
> Also you never replied to the original reason for having gap fill in hex files:

There is no any reason to fill gaps for .hex files. 

I am going to do a new PR 
- avoid any gaps for .hex files to make it equal to .elf. 
- no change for the BUILD_NO_GAP_FILL default value. 
- BUILD_NO_GAP_FILL will control only .bin files.

2024-08-21 12:07 UTC, tejlmand commented
> > Also you never replied to the original reason for having gap fill in hex files:
> 
> There is no any reason to fill gaps for .hex files.

there should not be.
And re-checking #8822, then it actually could be that they are flashing the bin-files, and not the hex files.

Flashing bin-files would more logically explain why flash writing times improves (writing 0x00 vs. no writing on 0xFF).

As bin files are always gap-filled, then it's not a matter on gap fill for those, more the pattern to use.
Thus introducing a `gap-fill` pattern with default value of `0xFF`.
Then a `BUILD_HEX_GAP_FILL` can be introduced instead of `BUILD_NO_GAP_FILL`.
Old setting should be deprecated and kept for two releases.

2024-09-02 13:37 UTC, closed without merging

2024-09-02 13:38 UTC, butok commented
Closed this PR.  
An improvement to be done in a different form.