boards: shields: Add support for Mikroe BLE TINY Click shield
zephyrproject-rtos/zephyr pull request #76246
Opened 2024-07-23 20:13 UTC by iandmorris

Add support for the Mikroe BLE TINY Click shield that contains the Renesas DA14531 Bluetooth LE Module.

2024-07-29 09:31 UTC, kartben requested changes
very nice! Thanks for the contribution

2024-07-29 09:31 UTC, kartben commented on boards/shields/mikroe_ble_tiny_click/doc/ble-tiny-click.jpg
please use webp (smaller file size, supports transparent background) and crop excess white space

you may directly use https://gist.githubusercontent.com/kartben/493373edfcb0940a7c9c0a230fd2e821/raw/7f727942d35c41ce7aff579d7d544d44c46a3d96/ble_tiny_click.webp

2024-07-29 09:31 UTC, kartben commented on boards/shields/mikroe_ble_tiny_click/doc/da14531-hci-binary.jpg
please convert to webp

https://gist.githubusercontent.com/kartben/493373edfcb0940a7c9c0a230fd2e821/raw/84844690fdca3f52bbd58590b6c696c5a22b58bb/da14531-hci-binary.webp

2024-07-30 10:58 UTC, kartben reviewed
spotted some minor typos, apologies that I missed them during earlier pass
LGTM otherwise, thanks again!

2024-07-30 10:58 UTC, kartben commented on boards/shields/mikroe_ble_tiny_click/doc/index.rst
> +   host system unintentinally holding the DA14531 Module in reset. This issue
```suggestion
   host system unintentionally holding the DA14531 Module in reset. This issue
```

2024-07-30 10:58 UTC, kartben commented on boards/shields/mikroe_ble_tiny_click/doc/index.rst
> +The DA14531 Module contained on the shield must programmed with a binary file
```suggestion
The DA14531 Module contained on the shield must be programmed with a binary file
```

2024-07-30 10:58 UTC, kartben commented on boards/shields/mikroe_ble_tiny_click/doc/index.rst
> +these signals are not support on the Click footprint.
```suggestion
these signals are not supported on the Click footprint.
```

2024-07-30 10:59 UTC, kartben commented
@iandmorris please also rebase to address unrelated CI failure

2024-07-30 15:52 UTC, kartben approved these changes

2024-07-31 23:19 UTC, jfischer-no approved these changes

2024-08-01 08:11 UTC, merged