Add support for I2C driver on EK-RA8M1
zephyrproject-rtos/zephyr pull request #76394
Opened 2024-07-28 17:00 UTC by thaoluonguw

Add minimal support for I2C driver use IIC on EK-RA8M1

Improve for tests/drivers/i2c/i2c_api to choose using GY271_HMC or GY271_QMC for testing.

2024-07-29 06:52 UTC, ydamigos commented on drivers/i2c/i2c_renesas_ra_iic.c
> +	const double fall_time_ns = config->fall_time_ns / RA_IIC_MASTER_DIV_TIME_NS;
Could we move those divisions in `i2c_ra_iic_config_##index` definition so it will happen in compile time?

2024-07-29 06:54 UTC, ydamigos requested changes

2024-07-29 06:54 UTC, ydamigos commented on drivers/i2c/i2c_renesas_ra_iic.c
> +	const double fall_time_ns = config->fall_time_ns / RA_IIC_MASTER_DIV_TIME_NS;
Could we move those divisions in `i2c_ra_iic_config_##index` definition so it will happen in compile time?

2024-08-02 07:49 UTC, ydamigos submitted a review, later dismissed

2024-08-13 08:38 UTC, ydamigos approved these changes

2024-08-14 07:39 UTC, KhiemNguyenT approved these changes

2024-08-14 07:42 UTC, soburi approved these changes

2024-08-14 20:05 UTC, nashif commented
@teburd  PTAL

2024-08-14 20:25 UTC, teburd approved these changes
Looks ok to me, an open question about hardware related to other discussions about what is/isn't possible with i2c controllers and this API.

2024-08-14 20:25 UTC, teburd commented on drivers/i2c/i2c_renesas_ra_iic.c
> +			/* Stop condition is only allowed on last message */
Is this a hardware limitation?

2024-08-14 20:53 UTC, merged