bluetooth: make monitor timestamps roll over less
zephyrproject-rtos/zephyr pull request #76529
Opened 2024-07-31 07:54 UTC by arbrauns

With e.g. a 216MHz core clock, the signed 32-bit cycle counter overflows after just 10 seconds. The unsigned 32-bit monitor timestamp (100us resolution) overflows after around five days regardless of what we do, but we should try our best to reach that.

2024-07-31 08:03 UTC, Thalley requested changes

2024-07-31 08:03 UTC, Thalley commented on subsys/bluetooth/host/monitor.c
> +	int64_t cycle;
```suggestion
	uint64_t cycle;
```

`k_cycle_get_64` returns a `uint64_t`

2024-07-31 08:16 UTC, Thalley approved these changes, later dismissed

2024-07-31 10:32 UTC, jhedberg approved these changes, later dismissed
Looks good, thanks. There's one minor cosmetic thing I commented on.

2024-07-31 10:32 UTC, jhedberg commented on subsys/bluetooth/host/monitor.c
> +	return (cycle / (sys_clock_hw_cycles_per_sec() / MONITOR_TS_FREQ));
really minor style thing: I'd add an empty line before the return statement.

2024-08-01 07:22 UTC, jori-nordic approved these changes

2024-08-01 07:22 UTC, Thalley approved these changes

2024-08-01 07:27 UTC, alwa-nordic approved these changes

2024-08-01 07:47 UTC, jhedberg approved these changes

2024-08-02 11:41 UTC, merged