stm32: add supports for configure MCO when startup
zephyrproject-rtos/zephyr pull request #7672
Opened 2018-05-19 09:10 UTC by zhaozhongchen

tested in nucleo_f070rb (MCO  pin is PA8)

```
CONFIG_CLOCK_STM32_MCO1_SRC_LSI=1
CONFIG_CLOCK_STM32_MCO1_DIV=1
```

2018-05-19 09:12 UTC, zhaozhongchen commented
@erwango @ydamigos please have a look.

I had only tested this pr on nucleo_f070rb, and haven't add pinmux for stm32f1, f3, f4, f7, l0, l4. Will do that later.

2018-05-22 09:42 UTC, erwango commented
@QianFan-Zhao , thanks for this change.
As this change is impacting all series and boards, it will take me sometime to review and test in deep.
I'll try to get back to you next week on it.

2018-05-25 05:14 UTC, zhaozhongchen commented
Add 'STM32_OSPEEDR_VERY_HIGH_SPEED' flag to MCO pin and force push

2018-05-29 08:46 UTC, zhaozhongchen commented
ping @erwango

2018-06-04 09:43 UTC, erwango requested changes
Looks nice.
Some initial comments.

I wonder if it is reasonnable to implement for all series right away, as this will request lot of test effort.

2018-06-04 09:43 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> +	#define LL_RCC_MCO1SOURCE		LL_RCC_MCO1SOURCE_NOCLOCK
"LL_RCC_MCO1SOURCE": You could not add your own defines using STM32Cube namespace (LL_RCC), unless it is a redefinition of existing define (for a good reason).
We should keep clear separation between STM32Cube definitions and the one created for Zephyr driver.
"MCO1_SOURCE" should be sufficient.

2018-06-04 09:43 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> +#ifndef CONFIG_CLOCK_STM32_MCO1_SRC_NOCLOCK
Please put this under a specific function (stm32clock_control_mco_init for instance)
stm32_clock_control_init is already rather long, we should not add too much things.

2018-06-04 09:43 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> +#ifndef CONFIG_CLOCK_STM32_MCO1_SRC_NOCLOCK
Besides, according to Reference manual, it should be done before PLL activation.

2018-06-04 09:43 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> +	LL_RCC_ConfigMCO(LL_RCC_MCO1SOURCE);
Please add a comment that MCO does not activate requested source and on matching source activation should be checked

2018-06-05 12:56 UTC, zhaozhongchen commented
@erwango stm32 all series MCO is quiet similer, so I want add them at all.

2018-06-05 13:33 UTC, erwango commented
> @erwango stm32 all series MCO is quiet similer, so I want add them at all.

@zhaozhongchen , I agree this makes sense to take advantage of your developments, but we need to test on all series

2018-06-05 13:39 UTC, zhaozhongchen commented
> but we need to test on all series

@erwango Should I remove all soc except STM32F0 to make the test easier?

2018-09-10 07:35 UTC, erwango requested changes
@qianfan-Zhao , sorry for delay in reviewing your change.
I have some few additional comments, then we're good for merge

2018-09-10 07:35 UTC, erwango commented on drivers/clock_control/Kconfig.stm32
> +# Will add others SOC supports later
Please remove this line

2018-09-10 07:35 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> + * MCO configure doesn't active requested clock source,
Then we should activate source clock in stm32_clock_control_mco_init,
at least a check clock is enabled would be required.

2018-09-10 07:35 UTC, erwango commented on drivers/clock_control/stm32_ll_clock.c
> +	stm32_clock_control_mco_init();
Please move this call to the end of the function

2018-09-27 11:47 UTC, galak commented
@qianfan-Zhao Any plans to update?

2018-09-27 11:53 UTC, qianfan-Zhao commented
@galak  Yes I will update this pr in recent days

2018-09-27 11:53 UTC, qianfan-Zhao commented
@galak  Yes I will update this pr in recent days

2018-10-08 09:01 UTC, erwango requested changes
Some last comments and we're good.

2018-10-19 14:09 UTC, erwango commented
^^@qianfan

2018-10-21 07:10 UTC, qianfan-Zhao commented on drivers/clock_control/Kconfig.stm32
> +config CLOCK_STM32_MCO2_SRC_PLLI2S
On RM0090 Rev17 Section 6.2.10:
```
You can output four different clock sources onto the MCO2 pin (PC9) using the
configurable prescaler (from 1 to 5):
– HSE clock
– PLL clock
– System clock (SYSCLK)
– PLLI2S clock
```

Which version of RM0090 you used?

2018-10-21 07:43 UTC, qianfan-Zhao commented
@erwango Sorry for my later update.

2018-10-30 14:59 UTC, erwango commented on drivers/clock_control/Kconfig.stm32
> +config CLOCK_STM32_MCO2_SRC_PLLI2S
I was referring to the clock tree.
If PLLI2S is used elsewhere, I'm good with that too.

2018-10-30 15:00 UTC, erwango approved these changes

2018-11-12 10:55 UTC, erwango commented
@galak ^^

2018-11-13 13:11 UTC, merged