Dev pnp
zephyrproject-rtos/zephyr pull request #77044
Opened 2024-08-14 04:52 UTC by chengkai15

add bt pnp feature

2024-08-14 17:27 UTC, kartben commented on scripts/kconfig/hardened.csv
> +BT_PNP,n,experimental
updating this file won't be needed if you rebase to pick up a recent change implemented in the hardening tool. Thanks for the attention to this though!

2024-08-19 07:47 UTC, lylezhu2012 requested changes

2024-08-19 07:47 UTC, lylezhu2012 commented on subsys/bluetooth/shell/bredr.c
> +	SHELL_CMD_ARG(pnp, NULL, "<PNP>", cmd_pnp_discover, 1, 0),
There is a command `sdp-find`. we can expand the command. I don't think it is necessary to add this command.

2024-08-19 07:47 UTC, lylezhu2012 commented on subsys/bluetooth/host/classic/pnp.c
If the functionality of this file is just discovery peer PnP SDP record, I don't think we need to add this file.

2024-11-02 00:32 UTC, closed without merging