boards: TDK Robokit1
zephyrproject-rtos/zephyr pull request #77098
Opened 2024-08-14 20:21 UTC by teburd

Enable i2c and spi rtio drivers by default, enable spi dma usage by default.

2024-08-16 14:29 UTC, ubieda approved these changes

2024-08-16 14:30 UTC, ubieda commented
Trivial, maybe?

2024-08-16 16:02 UTC, jeppenodgaard approved these changes

2024-08-19 07:15 UTC, nordic-segl approved these changes

2024-08-19 14:10 UTC, MaureenHelm requested changes

2024-08-19 14:10 UTC, MaureenHelm commented on boards/tdk/robokit1/robokit1_defconfig
> +CONFIG_SPI_SAM_DMA=y
Need to do this in `Kconfig.robokit1` to avoid overriding the dependencies on CONFIG_I2C and CONFIG_SPI.

2025-03-16 00:38 UTC, closed without merging