bluetooth: hci: enable `BT_SPI` from DT
zephyrproject-rtos/zephyr pull request #77161
Opened 2024-08-16 10:52 UTC by JordanYates

Enable the `BT_SPI` driver by default when the devicetree node exists.
This brings the driver in line with all the other HCI backends

2024-08-16 11:24 UTC, jhedberg commented
Not sure if this is quite correct, due to this hackery in `CMakeLists.txt` (which I'd gladly get rid of, but it may require some refactoring somewhere):
https://github.com/zephyrproject-rtos/zephyr/blob/1aaea30adb62df1aff2ccb167966db443667d5f6/drivers/bluetooth/hci/CMakeLists.txt#L20-L26

2024-08-16 11:35 UTC, JordanYates commented
> Not sure if this is quite correct, due to this hackery in `CMakeLists.txt` (which I'd gladly get rid of, but it may require some refactoring somewhere):
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/1aaea30adb62df1aff2ccb167966db443667d5f6/drivers/bluetooth/hci/CMakeLists.txt#L20-L26

Yea noticed this after pushing, working on it now

2024-08-16 11:50 UTC, jhedberg approved these changes, later dismissed

2024-08-19 09:54 UTC, HoZHel commented on drivers/bluetooth/hci/Kconfig
> +	bool "SPI HCI as implemented by Zephyr"
```suggestion
	bool "HCI over SPI as implemented by Zephyr"
```

2024-08-19 09:54 UTC, HoZHel commented on drivers/bluetooth/hci/Kconfig
> +	  Bluetooth HCI driver for communication with Bluetooth controllers
```suggestion
	  Bluetooth HCI over SPI driver for communication with Bluetooth controllers
```

2024-08-19 09:54 UTC, HoZHel commented on drivers/bluetooth/hci/Kconfig
> +	bool "ACI message with BlueNRG-based devices"
```suggestion
	bool "ACI configuration message with BlueNRG-based devices"
```

2024-08-19 10:13 UTC, HoZHel requested changes

2024-08-19 10:13 UTC, HoZHel commented on drivers/bluetooth/hci/Kconfig
> +	  Bluetooth HCI driver for communication with the BlueNRG-1 and BlueNRG-2
```suggestion
	  Bluetooth HCI over SPI driver for communication with STMicroelectronics radio devices.
```

2024-08-19 10:13 UTC, HoZHel commented on drivers/bluetooth/hci/Kconfig
> +	  Stack. Current driver supports: ST BLUENRG-MS.
```suggestion
	  Enable vendor specific commands to switch radio to controller-only mode.
```

2024-08-19 11:17 UTC, JordanYates commented
@HoZHel the changes in this PR are not modifying the form of any of the Kconfig text, just rearranging the symbols (And duplicating in the case of `SPI_HCI_ZEPHYR`).
I think substantive changes should be their own PR, so that all the symbols can be addressed at once/wording changes discussed independently.

2024-08-19 14:03 UTC, HoZHel commented
> @HoZHel the changes in this PR are not modifying the form of any of the Kconfig text, just rearranging the symbols (And duplicating in the case of `SPI_HCI_ZEPHYR`). I think substantive changes should be their own PR, so that all the symbols can be addressed at once/wording changes discussed independently.

Well, `config BT_SPI_BLUENRG` is not an rearrangement and it has a wrong definition.

2024-08-23 07:41 UTC, JordanYates commented
Removed prompts from the new symbols as done in #77418

2024-08-23 07:56 UTC, jhedberg approved these changes, later dismissed

2024-08-23 08:04 UTC, msmttchr commented
@JordanYates, recently PR #71352 added a new HCI board which possibly needs update before merging this PR.

2024-08-23 08:09 UTC, JordanYates commented
> @JordanYates, recently PR #71352 added a new HCI board which possibly needs update before merging this PR.

Done

2024-08-23 08:17 UTC, jhedberg approved these changes, later dismissed

2024-08-23 08:46 UTC, msmttchr commented
> > @HoZHel the changes in this PR are not modifying the form of any of the Kconfig text, just rearranging the symbols (And duplicating in the case of `SPI_HCI_ZEPHYR`). I think substantive changes should be their own PR, so that all the symbols can be addressed at once/wording changes discussed independently.
> 
> Well, `config BT_SPI_BLUENRG` is not an rearrangement and it has a wrong definition.

I think this comment needs also to be addressed before merging this PR, since the information provided can be misleading.

2024-08-23 10:52 UTC, msmttchr commented
> The `BT_SPI_BLUENRG` symbol was updated mostly in line with the request
Ah, sorry I missed that.

2024-08-23 10:59 UTC, HoZHel submitted a review, later dismissed

2024-08-26 11:15 UTC, JordanYates commented
Rebasing on main in the hope the unrelated CI failures are resolved

2024-10-24 01:43 UTC, JordanYates commented
Rebase to resolve release notes conflict

2024-10-24 06:01 UTC, jhedberg approved these changes

2024-10-24 07:14 UTC, hermabe approved these changes

2024-10-24 07:54 UTC, jhedberg commented
@erwango any idea about the CI failures here? They don't seem to be related to this PR, rather something's off with mbedtls and wifi on ST platforms. Is that a know issue?

2024-10-24 08:18 UTC, erwango commented
> @erwango any idea about the CI failures here? They don't seem to be related to this PR, rather something's off with mbedtls and wifi on ST platforms. Is that a known issue?

Also failing with `nrf9160dk/nrf9160/ns`, so I guess it's rather an issue with the test itself.

2024-10-24 12:05 UTC, jhedberg commented
> Also failing with `nrf9160dk/nrf9160/ns`, so I guess it's rather an issue with the test itself.

@erwango where do you see that? I only see `stm32l562e_dk/stm32l562xx/ns` failing in the CI logs.

2024-10-24 12:09 UTC, erwango commented
> > Also failing with `nrf9160dk/nrf9160/ns`, so I guess it's rather an issue with the test itself.
> 
> @erwango where do you see that? I only see `stm32l562e_dk/stm32l562xx/ns` failing in the CI logs.

Reproduced locally. But I don't know why only `stm32l562e_dk/stm32l562xx/ns` is tested.

2024-10-24 17:22 UTC, jhedberg commented
The CI failure should get fixed by #80381

2024-10-25 06:55 UTC, merged