PCAL64XXA external reset
zephyrproject-rtos/zephyr pull request #77342
Opened 2024-08-21 13:07 UTC by benediktibk

Implement an external reset for the port expander PCAL64XXA, which allows the downstream implementation of a device state retention.

This is basically based upon the discussion in #72382.

2024-08-27 02:12 UTC, dleach02 approved these changes, later dismissed

2024-08-27 08:20 UTC, bjarki-andreasen requested changes
Public headers (`gpio/gpio_pcal64xxa.h`) should include
```
#ifdef __cplusplus
extern "C" {
#endif
```
to be compatible with C++ since C++ applications may include this file directly

2024-08-27 08:30 UTC, bjarki-andreasen approved these changes

2024-08-28 05:12 UTC, dleach02 commented
@henrikbrixandersen are you good with this PR? You had blocking comments in the previous one this is based on.

2024-09-02 16:58 UTC, henrikbrixandersen commented
> @henrikbrixandersen are you good with this PR? You had blocking comments in the previous one this is based on.

It's better than the previous proposal. I still think this should live out of tree instead, but I won't block it.

2024-09-11 06:12 UTC, dleach02 approved these changes

2024-09-11 07:35 UTC, merged