Bluetooth: audio: Fix shell available context
zephyrproject-rtos/zephyr pull request #77489
Opened 2024-08-23 15:41 UTC by fredrikdanebjer

This fixes a bug where the shell will reject setting available context to 0x0. This has now been moved to only affect supported context instead.

2024-08-26 07:29 UTC, Thalley requested changes

2024-08-26 07:29 UTC, Thalley commented on subsys/bluetooth/audio/shell/bap.c
> +		ctx_val > BT_AUDIO_CONTEXT_TYPE_ANY) {
The `ctx_val > BT_AUDIO_CONTEXT_TYPE_ANY` should still apply for both. Only the `ctx_val == BT_AUDIO_CONTEXT_TYPE_PROHIBITED` check should be for the supported contexts

2024-09-05 13:16 UTC, Thalley approved these changes

2024-09-23 07:52 UTC, larsgk approved these changes

2024-09-23 08:02 UTC, merged