bluetooth: controller: Use CONFIG_BT_LLL_VENDOR_* instead of CONFIG_SOC_COMPATIBLE_*
zephyrproject-rtos/zephyr pull request #77704
Opened 2024-08-28 13:32 UTC by Salamandar

CONFIG_SOC_COMPATIBLE_* is not configurable, but CONFIG_BT_LLL_VENDOR_* is.

This allows an alternate LLL to be built on nordic and OpenISA chips. For example, for a non-HCI chip that requires an on-board LLL.

2024-08-28 14:36 UTC, Salamandar commented on modules/hal_nordic/nrfx/nrfx_glue.h
> +#if defined(CONFIG_BT_LLL_VENDOR_NORDIC)
Inside this #if is `#include <bt_ctlr_used_resources.h>`. This header is in the `ll_sw/nordic` directory. So I'd guess this code is only relevant for LL_SW setups.

2024-08-28 14:39 UTC, hermabe commented on modules/hal_nordic/nrfx/nrfx_glue.h
> +#if defined(CONFIG_BT_LLL_VENDOR_NORDIC)
OOT controller implementations may also provide this header, for example https://github.com/nrfconnect/sdk-nrf/blob/9d6898a0a2fe1b8f666687294da224255cced1d5/subsys/bluetooth/controller/bt_ctlr_used_resources.h.

2024-08-28 14:48 UTC, Salamandar commented on modules/hal_nordic/nrfx/nrfx_glue.h
> +#if defined(CONFIG_BT_LLL_VENDOR_NORDIC)
*gasp* Well, do you have a suggestion about how to disable this code only when the nrf bluetooth IP is not used (but splitted LL_SW is used) ?

2024-08-28 15:37 UTC, Salamandar commented on modules/hal_nordic/nrfx/nrfx_glue.h
> +#if defined(CONFIG_BT_LLL_VENDOR_NORDIC)
I removed the problematic commit. Until another solution is found, the issue I encounter is fixed by providing the header in the LLL.

2024-08-29 07:28 UTC, hermabe commented on modules/hal_nordic/nrfx/nrfx_glue.h
> +#if defined(CONFIG_BT_LLL_VENDOR_NORDIC)
I was thinking the same, the alternative LLL probably needs some (D)PPI channels and should provide this header to coexist with other users of PPI.

2024-08-29 10:59 UTC, cvinayak approved these changes

2024-08-29 11:01 UTC, cvinayak requested changes
nitpick, update commit title with "Bluetooth:  Controller:... "

2024-08-29 13:21 UTC, Salamandar commented
> nitpick, update commit title with "Bluetooth: Controller:... "

Alright, but that increases the line length and it doesn't pass CI tests anymore :(

2024-08-30 07:22 UTC, cvinayak commented
Use "Bluetooth: Controller: Use BT_LLL_VENDOR_* to selectively build LLL"

2024-09-03 04:12 UTC, cvinayak approved these changes

2024-09-03 05:38 UTC, rugeGerritsen approved these changes

2024-09-03 06:24 UTC, hermabe approved these changes

2024-09-03 08:42 UTC, merged

2024-09-03 08:52 UTC, Salamandar commented
Thank you !