task_wdt: Add auto init and syswq monitoring
zephyrproject-rtos/zephyr pull request #77710
Opened 2024-08-28 14:44 UTC by alwa-nordic

This patch adds two new features to the task watchdog subsystem:
  - Automatic initialization of the task watchdog on SYS_INIT
  - Monitoring of the system work queue

The automatic initialization feature is enabled by the new Kconfig option TASK_WDT_AUTO_INIT. When enabled, the task watchdog will be initialized automatically on SYS_INIT. This is useful for applications that want to use the task watchdog but do not want to manually initialize it.

The system work queue monitoring feature is enabled by the new Kconfig option TASK_WDT_SYSWQ_STALL. When enabled, the task watchdog will monitor the system work queue. If the system work queue is stalled for longer than the specified timeout, the task watchdog will trigger a system panic.

The system work queue stall timeout is specified by the new Kconfig option TASK_WDT_SYSWQ_STALL_TIMEOUT_MS. This option specifies the maximum time in milliseconds that the system work queue is allowed to be stalled before the task watchdog triggers a system panic.

2024-08-28 15:05 UTC, ubieda commented
Sounds like a good idea!

2024-08-29 07:22 UTC, pdgendt commented on subsys/task_wdt/task_wdt_auto_init.c
I don't really see the benefit for having this in tree, this is very trivial for applications to add themselves.

Besides that, it lacks some configuration:
- No way to set a HW watchdog (could be fixed with a chosen `zephyr,wdt-wdg` or something)
- An init priority, you could even argue that `POST_KERNEL` vs `APPLICATION`

2024-08-29 07:22 UTC, pdgendt commented on subsys/task_wdt/task_wdt_auto_init.c
> +static int init(void)
Use a more specific name, this might shadow others/macros.

```suggestion
static int task_wdt_auto_init(void)
```

2024-08-29 07:22 UTC, pdgendt commented on subsys/task_wdt/task_wdt_syswq_stall.c
> +static const uint32_t feed_delay_ms = CONFIG_TASK_WDT_SYSWQ_STALL_TIMEOUT_MS / 2;
No need for these additional variables, simply use the Kconfig symbols directly.

2024-08-29 07:22 UTC, pdgendt commented on subsys/task_wdt/task_wdt_syswq_stall.c
> +static struct k_work_delayable dwork;
Use `K_WORK_DELAYABLE_DEFINE`?

2024-08-29 07:22 UTC, pdgendt commented on subsys/task_wdt/task_wdt_syswq_stall.c
> +static int init(void)
Same comment, use more specific names, also helps in debugging/breakpoints.

2024-08-29 09:30 UTC, pdgendt commented on subsys/task_wdt/task_wdt_auto_init.c
A `BUILD_ASSERT` can be used to check priorities.

2024-08-29 09:37 UTC, alwa-nordic commented on subsys/task_wdt/task_wdt_auto_init.c
> No way to set a HW watchdog (could be fixed with a chosen zephyr,wdt-wdg or something)

I will argue a HW watchdog is not necessary here. This watchdog is meant to detect deadlocks where the system work queue thread is unready/sleeping. The kernel and scheduler are assumed to work correctly and not stalled. A separate watchdog should ensure the kernel ticks.

2024-08-29 09:43 UTC, pdgendt commented on subsys/task_wdt/task_wdt_auto_init.c
This is a single instance subsystem, at our company we always have a HW watchdog fallback when using WDT tasks.

I think you are mixing the two distinct purposes introduced in this PR.

Also note that an HW fallback is useful in cases where interrupts would be temporary disabled.

2024-08-29 10:07 UTC, martinjaeger requested changes
Can you please split the two different into two dedicated commits?

Also please see my other comments below.

2024-08-29 10:45 UTC, alwa-nordic commented on subsys/task_wdt/task_wdt_auto_init.c
> A `BUILD_ASSERT` can be used to check priorities.

I'm not sure how. Do you have an example?

2024-09-03 07:18 UTC, pdgendt commented on subsys/task_wdt/task_wdt_auto_init.c
I meant if you have a configurable init priority

```c
BUILD_ASSERT(CONFIG_TASK_WDT_AUTO_INIT_PRIORITY > CONFIG_KERNEL_INIT_PRIORITY_DEFAULT);

SYS_INIT(task_wdt_auto_init, POST_KERNEL, CONFIG_TASK_WDT_AUTO_INIT_PRIORITY);
```

2024-11-18 00:36 UTC, closed without merging