drivers: eth: fix stm32_hal PHY address resolution
zephyrproject-rtos/zephyr pull request #77761
Opened 2024-08-29 17:32 UTC by scaprile

Fixes: #77705

Fix wrong macro.
Tested with all the boards mentioned in that issue, build now works.

2024-08-29 19:49 UTC, pdgendt approved these changes

2024-08-30 05:13 UTC, AlexFabre commented
This wrong macro call is my mistake, sorry for that.

2024-08-30 06:29 UTC, pdgendt commented
Please rebase as the CI issue has been fixed in `main`.

2024-08-30 07:26 UTC, erwango approved these changes

2024-08-30 07:36 UTC, mathieuchopstm approved these changes

2024-08-30 09:48 UTC, marwaiehm-st approved these changes

2024-08-30 13:50 UTC, erwango requested changes
@scaprile Please remove the merge commit.

2024-08-30 14:18 UTC, scaprile commented
> @scaprile Please remove the merge commit.

@erwango Github closed this commit when I force pushed on my fork... (?) can you reopen ? (I can't)

2024-08-30 14:21 UTC, pdgendt commented
There are no commits on your `main` branch anymore.

2024-08-30 14:24 UTC, scaprile commented
Yeah, I must have screwed something and blamed Github... added on top
Thanks.

2024-08-30 14:38 UTC, mathieuchopstm approved these changes

2024-08-30 14:39 UTC, erwango approved these changes

2024-08-30 15:14 UTC, FRASTM approved these changes

2024-09-03 08:42 UTC, merged