Add rt1180 acmp support
zephyrproject-rtos/zephyr pull request #77836
Opened 2024-08-31 06:48 UTC by lucien-nxp

samples/sensor/mcux_acmp have been supported.
`mimxrt1180_evk` board are captured in J45-13, need change the external voltage signal to check the output.

2024-09-03 07:25 UTC, lucien-nxp commented
@hakehuang , could you help test samples/sensor/mcux_acmp on RT1180? Voltage can be captured in J45-13.

2024-09-03 15:41 UTC, danieldegrasse commented on samples/sensor/mcux_acmp/README.rst
> +.. zephyr-app-commands::
This format won't work (see the rendered documentation here: https://builds.zephyrproject.io/zephyr/pr/77836/docs/samples/sensor/mcux_acmp/README.html#building-and-running-for-mimxrt1180-evk).

We need to provide two `zephyr-app-commands` entries, one per SOC target.

2024-09-03 15:43 UTC, MaureenHelm requested changes

2024-09-04 04:33 UTC, hakehuang commented
> @hakehuang , could you help test samples/sensor/mcux_acmp on RT1180? Voltage can be captured in J45-13.

basic function board test pass.

```
2024-09-04 10:05:28,996 - twister - DEBUG - DEVICE: �*** Booting Zephyr OS build v3.7.0-1989-g57af539bbbf3 ***
2024-09-04 10:05:28,999 - twister - DEBUG - DEVICE: Running TESTSUITE counter_basic
2024-09-04 10:05:29,005 - twister - DEBUG - DEVICE: ===================================================================
2024-09-04 10:05:48,396 - twister - DEBUG - DEVICE: �*** Booting Zephyr OS build v3.7.0-1941-g52cacee8f1d5 ***
2024-09-04 10:05:48,402 - twister - DEBUG - DEVICE: Adjust ACMP input voltage by turning the potentiometer
2024-09-04 10:05:48,402 - twister - DEBUG - HARNESS:Console:EXPECTED(1/2):'Adjust ACMP input voltage by turning the potentiometer'
2024-09-04 10:05:48,405 - twister - DEBUG - DEVICE: ACMP input above threshold
2024-09-04 10:05:48,405 - twister - DEBUG - HARNESS:Console:EXPECTED(2/2):'ACMP input [a-z]* threshold'
```

2024-09-04 13:13 UTC, danieldegrasse approved these changes

2024-09-04 14:19 UTC, MaureenHelm approved these changes

2024-09-04 19:27 UTC, merged