Supporting Pimoroni pico plus2
zephyrproject-rtos/zephyr pull request #77859
Opened 2024-09-01 23:28 UTC by soburi

It's working to some extent already, but it's still rough.
#77368 needs to be addressed first.

2024-09-02 08:07 UTC, nordicjm requested changes

2024-09-02 08:07 UTC, nordicjm commented on boards/pimoroni/pico_plus2/doc/index.rst
> +The rpi_pico board configuration supports the following
board name as used by west with \`\` around it and board target, not configuration

2024-09-02 08:07 UTC, nordicjm commented on boards/pimoroni/pico_plus2/pico_plus2-pinctrl.dtsi
> +	clocks_default: clocks_default {
empty can go

2025-01-25 08:30 UTC, ajf58 commented on tests/drivers/gpio/gpio_basic_api/boards/rpi_pico.overlay
> +		in-gpios = <&pico_header 15 GPIO_ACTIVE_HIGH>;
This will clash with the external pulldown resistor tests, which is why in https://github.com/ajf58/zephyr/commit/0b86b90cfd46aaed878dde538ec7c4de3abfd481 I use a different pair of pins. I think you should do the same, otherwise everyone needs to either run a subset of tests at a time, and swap wires round in between, or similar.

2025-01-31 21:58 UTC, soburi commented on tests/drivers/gpio/gpio_basic_api/boards/rpi_pico.overlay
> +		in-gpios = <&pico_header 15 GPIO_ACTIVE_HIGH>;
Thank you for your pointing out.
I have addressed this in #83427.

https://github.com/zephyrproject-rtos/zephyr/pull/83427/files#diff-6263b0be3639b44643145774c633549394a54c6234f683cb34e415a71fedc950R10-R11

2025-02-01 07:33 UTC, soburi commented on boards/pimoroni/pico_plus2/doc/index.rst
> +The rpi_pico board configuration supports the following
Completely rewritten, please check again.

2025-02-01 07:33 UTC, soburi commented on boards/pimoroni/pico_plus2/pico_plus2-pinctrl.dtsi
> +	clocks_default: clocks_default {
Same as above.

2025-02-15 06:17 UTC, soburi commented on boards/pimoroni/index.rst
Fixed.

2025-02-15 06:17 UTC, soburi commented on boards/pimoroni/pico_plus2/doc/index.rst
> +
Fixed.

2025-02-15 08:07 UTC, kartben submitted a review, later dismissed

2025-02-17 07:38 UTC, nordicjm commented on boards/pimoroni/pico_plus2/pico_plus2-pinctrl.dtsi
> +		group2 {
spacing

2025-02-17 07:38 UTC, nordicjm commented on boards/pimoroni/pico_plus2/pico_plus2.dtsi
> +		led0: led_0 {
spacing, apply throughout

2025-02-17 07:38 UTC, nordicjm commented on doc/releases/migration-guide-4.1.rst
> +* To support the RP2350B, which has many pins, the RaspberryPi-GPIO configuration has
4.1 feature freeze is past

2025-02-19 16:34 UTC, petejohanson commented
@soburi Did you intend to include the Renesas related commits in your recent push?

Looking forward to this change, since I'm planning to submit a board definition for the Adafruit Metro RP2350 which uses RP2350B. I've got it working mostly already, minus the GPIO changes, but would rather piggyback on this core work. Thanks!

2025-02-19 20:29 UTC, soburi commented
@petejohanson 

> @soburi Did you intend to include the Renesas related commits in your recent push?

Oh! It's my bad. 
I was working on both in parallel so I made a mistake. Thank you for pointing that out.
I fix it ASAP.

2025-03-08 00:11 UTC, soburi commented on boards/pimoroni/pico_plus2/pico_plus2-pinctrl.dtsi
> +		group2 {
Fixed it.

2025-03-08 00:12 UTC, soburi commented on doc/releases/migration-guide-4.1.rst
> +* To support the RP2350B, which has many pins, the RaspberryPi-GPIO configuration has
Moved into `doc/releases/migration-guide-4.1.rst`.

2025-03-08 00:12 UTC, soburi commented on boards/pimoroni/pico_plus2/pico_plus2.dtsi
> +		led0: led_0 {
Fixed it.

2025-03-10 07:47 UTC, nordicjm approved these changes

2025-03-10 07:47 UTC, nordicjm commented on boards/pimoroni/pico_plus2/pico_plus2_rp2350b_m33_defconfig
> +CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=150000000
as per other PR, should be in soc Kconfig, can be done in a later PR

2025-03-10 09:17 UTC, kartben approved these changes

2025-03-10 09:41 UTC, kartben commented
@soburi it looks like you may want to update the Raspberry Pi Pico Platforms section in MAINTAINERS.yml file

2025-03-10 10:16 UTC, soburi commented
@kartben 

> @soburi it looks like you may want to update the Raspberry Pi Pico Platforms section in MAINTAINERS.yml file

It seems that many other boards need to be addressed besides this one, so I would like to address them all together in a separate PR.

2025-03-10 10:20 UTC, merged