STM32 :  add soc for stm32u073 serie
zephyrproject-rtos/zephyr pull request #77912
Opened 2024-09-03 09:16 UTC by djiatsaf-st

select soc for stm32 nucleo_u073xx boards  and irq default configuration

2024-09-03 10:13 UTC, nordicjm submitted a review, later dismissed

2024-09-03 12:03 UTC, erwango requested changes
Please add dts files.

2024-09-03 12:36 UTC, nordicjm submitted a review, later dismissed

2024-09-03 12:58 UTC, erwango requested changes
We're getting there.
What is missing is to get u083.dtsi including u073.dtsi

2024-09-03 12:58 UTC, erwango commented on dts/arm/st/u0/stm32u073XB.dtsi
Should be `dts/arm/st/u0/stm32u073Xb.dtsi` according to existing convention.

2024-09-03 12:58 UTC, erwango commented on dts/arm/st/u0/stm32u073X8.dtsi
> +	};
Nitpick (non blocking), move the following directly  in stm32u073.dtsi:
```
	sram1: memory@20000000 {
		compatible = "zephyr,memory-region", "mmio-sram";
		zephyr,memory-region = "SRAM1";
	};

	sram2: memory@20008000 {
		compatible = "zephyr,memory-region", "mmio-sram";
		zephyr,memory-region = "SRAM2";
	};
```
and keep the following in this file:
```suggestion
	sram1: memory@20000000 {
		reg = <0x20000000 DT_SIZE_K(32)>;
	};

	sram2: memory@20008000 {
		reg = <0x20008000 DT_SIZE_K(8)>;
	};
```

2024-09-03 15:14 UTC, erwango approved these changes

2024-09-04 06:44 UTC, gautierg-st approved these changes

2024-09-04 07:39 UTC, erwango approved these changes

2024-09-04 07:43 UTC, marwaiehm-st approved these changes

2024-09-05 11:25 UTC, merged