drivers: usb_dc_rpi_pico: Fixed connected handling
zephyrproject-rtos/zephyr pull request #77976
Opened 2024-09-04 08:36 UTC by lgehreke

The sie_status register was cleared before evaluating it. Furthermore a connected state was reported as a disconnected state. This led to wrong reports of the connected state to all systems relying on it.

2024-09-04 09:15 UTC, jfischer-no requested changes

2024-09-04 09:23 UTC, lgehreke commented on drivers/usb/device/usb_dc_rpi_pico.c
> -		hw_clear_alias(usb_hw)->sie_status = USB_SIE_STATUS_CONNECTED_BITS;
You are right. Changed this

2024-09-04 09:26 UTC, jfischer-no approved these changes

2024-09-05 17:53 UTC, tmon-nordic approved these changes

2024-09-06 14:59 UTC, merged