fs: Fix fs_unmount while mountpoint is busy.
zephyrproject-rtos/zephyr pull request #78018
Opened 2024-09-04 17:20 UTC by bas-archembedded

Fixes fs_unmount when IO is potentially ongoing in a different thread. By using an use counter on the mountpoint we can prevent any thread from unmounting while busy. The fs_unmount adds -EBUSY as return value to reflect this case.

2024-09-05 07:34 UTC, de-nordic commented
Do you try to address the issue https://github.com/zephyrproject-rtos/zephyr/issues/73501 ?

2024-09-05 09:24 UTC, de-nordic commented on subsys/fs/fs.c
> +	/* Decrease use counter when we have >0 users */
LOG_ERR when called on `use_count` == 0, because we have a problem somewhere.

2024-09-05 09:29 UTC, de-nordic commented
> > Do you try to address the issue #73501 ?
> 
> Yeah, but in hindsight there are a few corner cases. Especially the file systems that have no close()/closedir() implementation. The test framework brings up this issue.
> 
> Is it worth to continue going in this direction or do you see another better way fixing this issue ?

Actually to know whether system has the call or not you have to call it.
Generally it is  just good practice to have every open paired with close, and that is it.

2024-09-05 09:45 UTC, bas-archembedded commented on subsys/fs/fs.c
> +	}
> _

Ah yes, that is why I initially had it in the loop, but that does not work. Will fix.

2024-10-08 07:44 UTC, de-nordic commented
Hi @bas-archembedded, any progress here?

2024-10-31 10:44 UTC, bas-archembedded commented
This probably needs more work and becomes tedious in the USB 'forced' removal case. Any thoughts about this ?

2024-10-31 10:56 UTC, de-nordic commented
> This probably needs more work and becomes tedious in the USB 'forced' removal case. Any thoughts about this ?

First focus on the support for internal process, so avoidance of unmounting something that is used by other process, and lets have this done.

We can not process forced removal without knowing it has happened, and forced removal will not call umount until the forced removal has already been done - so that means w have to have some proposal with subsystems with forced removal to inform VFS that it happened and policy towards them when they now have to call something forcing removal of the mount point regardless of counters or usage.

If you want to have proposal for that take a look look at how SD cards react, in Zephyr, to gather some info on how thinks are happening, so that you could fit the idea within how the system works, but not in this PR.

2025-04-01 16:03 UTC, de-nordic requested changes

2025-06-16 00:41 UTC, closed without merging