cmake: add REQUIRED option ot dt_nodelabel
zephyrproject-rtos/zephyr pull request #78406
Opened 2024-09-13 16:03 UTC by unsanded

dt_nodelabel ea currently fail quietly.
This can cause some very confusing errors later on. By adding `REQUIRED` to the function call one can easily generate a more clear message:

    required nodelabel not found: ...

I wrote this because i spent an hour debugging a strange error, which was caused because my dts didn't have a `slot0_partition` nodelabel, which mcuboot expects.

2024-09-13 19:19 UTC, tejlmand requested changes
Fine extension for cases where a nodelabel, alias, or property is indeed required.

But I would not go as far as saylng that a missing nodelabel, alias, or property is a quiet failure today.
Ref:
>  - dt_nodelabel
> - dt_alias
> - dt_prop
>
> these currently fail quietly.

There are many valid use-cases where a label can be missing which should not cause a failure, and it is documented that in those cases, the return variable will be empty so the caller of the function does have the ability to check for that:
https://github.com/zephyrproject-rtos/zephyr/blob/34727dfc4ca8027e75bb393ed01a3ef7172dd85d/cmake/modules/extensions.cmake#L3635
https://github.com/zephyrproject-rtos/zephyr/blob/34727dfc4ca8027e75bb393ed01a3ef7172dd85d/cmake/modules/extensions.cmake#L3682-L3683 

But having a `REQUIRED` option for cases where the label / property is required is a fine addition and can avoid boilerplate testing code for developers.

Just a minor observation to fix before a final +1.

2024-09-13 19:19 UTC, tejlmand commented on cmake/modules/extensions.cmake
> +
please remove extra empty line.
```suggestion
```

2024-09-13 19:20 UTC, tejlmand commented
and remember to fix compliance.

2024-09-16 10:00 UTC, pdgendt approved these changes

2024-09-16 10:03 UTC, nordicjm approved these changes

2024-09-16 10:06 UTC, unsanded commented
Thanks for the review, i fixed the compliance and the line :)
Btw, the reason (and an example usecase) for this was: [here](https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/CMakeLists.txt#L428). I didn't have this nodelabel, on my board (arduino nano ble), but the error only came way down in dt_prop, since `path` was empty.

2024-09-16 14:49 UTC, tejlmand commented
> Btw, the reason (and an example usecase) for this was: [here](https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/CMakeLists.txt#L428).

Thanks, and exactly that use seems to be flawed in MCUboot here: 
https://github.com/zephyrproject-rtos/mcuboot/blob/84b56b61118a1140e1afcb8802e2d94dd9fee44d/boot/zephyr/CMakeLists.txt#L371-L376

where `ERROR` is used instead of `FATAL_ERROR`.
If the correct `FATAL_ERROR` had been used there, my expectation is that you have found your missing node much earlier.

So it seems it is mcuboot which silently fail because it failed to properly handle missing nodes.

2024-09-16 15:05 UTC, tejlmand approved these changes

2024-09-16 15:13 UTC, tejlmand commented
sent a patch to mcuboot here: https://github.com/mcu-tools/mcuboot/pull/2065

2024-09-17 13:21 UTC, unsanded commented
I agree the flaw was in mcuboot. I was going to send them a patch, but then it seemed that having this option would be the least duplicated code way, hence this pull request.

2024-09-17 16:49 UTC, merged