usb: cdc_acm: disable logging if used for shell with logging
zephyrproject-rtos/zephyr pull request #78449
Opened 2024-09-15 16:56 UTC by xudongzheng

This prevents recursive logging loop when USB CDC ACM is used for shell with logging.

Change affects both USB stacks.

2024-09-16 06:34 UTC, tmon-nordic submitted a review, later dismissed

2024-09-18 13:06 UTC, jfischer-no requested changes

2024-09-18 13:06 UTC, jfischer-no commented on subsys/usb/device/class/cdc_acm.c
> +#define HAS_USB_SHELL   DT_NODE_HAS_COMPAT(DT_CHOSEN(zephyr_shell_uart), zephyr_cdc_acm_uart)
There is no such thing as USB console or USB shell

```suggestion
#define CHOSEN_CONSOLE DT_NODE_HAS_COMPAT(DT_CHOSEN(zephyr_console), zephyr_cdc_acm_uart)
#define CHOSEN_SHELL DT_NODE_HAS_COMPAT(DT_CHOSEN(zephyr_shell_uart), zephyr_cdc_acm_uart)
```

2024-09-19 09:18 UTC, jfischer-no approved these changes

2024-10-07 12:01 UTC, tmon-nordic approved these changes

2024-10-07 16:11 UTC, merged

2024-10-07 21:44 UTC, nashif commented
this is causing failures in CI now...


https://github.com/zephyrproject-rtos/zephyr/actions/runs/11220107511/job/31187571384

2024-10-07 21:59 UTC, jfischer-no commented
> this is causing failures in CI now...
> 
> https://github.com/zephyrproject-rtos/zephyr/actions/runs/11220107511/job/31187571384

This is good because it actually catches incorrect configuration. https://github.com/zephyrproject-rtos/zephyr/pull/79525