boards: rd_rw612_bga: Rename LED to "virtual"
zephyrproject-rtos/zephyr pull request #78500
Opened 2024-09-16 16:33 UTC by decsny

There is not a real LED on this board, it's just a pin header, rename the led node to prevent confusion from green_led to virtual_led.

2024-09-16 16:38 UTC, EmilioCBen submitted a review, later dismissed

2024-09-16 18:29 UTC, danieldegrasse submitted a review, later dismissed

2024-09-16 18:40 UTC, mmahadevan108 submitted a review, later dismissed

2024-09-16 20:27 UTC, danieldegrasse commented
Looks like this is blocked by https://github.com/zephyrproject-rtos/zephyr/pull/78415

2024-09-17 20:34 UTC, mmahadevan108 commented
@decsny , can you take a look at the CI failures.

2024-09-18 14:28 UTC, decsny commented
> @decsny , can you take a look at the CI failures.

as daniel mentioned, it's the issue being fixed in https://github.com/zephyrproject-rtos/zephyr/pull/78415 and reported in https://github.com/zephyrproject-rtos/zephyr/issues/78649

2024-09-18 14:55 UTC, dleach02 approved these changes

2024-09-19 15:36 UTC, mmahadevan108 commented
@decsny Need a rebase?

2024-09-20 07:04 UTC, henrikbrixandersen requested changes
If no LED is present on the board, why even have this node?

2024-09-20 15:51 UTC, dleach02 commented
> If no LED is present on the board, why even have this node?

So blinky can still be built and run on the board with a test fixture to the pin header.

2024-09-20 15:52 UTC, dleach02 submitted a review, later dismissed

2024-09-20 16:21 UTC, decsny commented
> > So blinky can still be built and run on the board with a test fixture to the pin header to verify operation.
> 
> Blinky is a sample, not a test. GPIOs should be tested with the `tests/drivers/gpio` test suites. Including a "virtual" LED for being able to blink a non-existing LED provides no value, but can greatly confuse end-users (is there an LED? Isn't there an LED? Is this how I configure non-LED GPIOs in the devicetree?).

yes, blinky is not useful to test GPIO rigorously from a true validation perspective of people maintaining the gpio drivers on the OS side or an upstream board. That's not the goal of this definition ...

We provided this definition of the "led" for convenience, as sometimes our customers just want a sample that toggles a GPIO, and blinky does that, LED on the board or not.

2024-10-04 18:20 UTC, decsny commented
@henrikbrixandersen at the very least, what is currently in tree makes less sense as there is definitely no green LED, so what is your actual change request

2024-10-05 19:36 UTC, henrikbrixandersen commented
> @henrikbrixandersen at the very least, what is currently in tree makes less sense as there is definitely no green LED, so what is your actual change request

I suggest removing the fake LED altogether.

2024-10-07 18:19 UTC, decsny commented
@henrikbrixandersen after lengthy and impassioned internal discussion, I confirmed we can remove the fake LED from the board definition.

2024-10-07 19:30 UTC, henrikbrixandersen approved these changes

2024-10-07 19:32 UTC, henrikbrixandersen commented
> @henrikbrixandersen after lengthy and impassioned internal discussion, I confirmed we can remove the fake LED from the board definition.

I am sorry to have caused this, but I am happy with your decision.

2024-10-08 06:53 UTC, butok approved these changes

2024-10-11 18:43 UTC, dleach02 approved these changes

2024-10-14 11:02 UTC, merged