scripts: Convert gen_offset_header to Python
zephyrproject-rtos/zephyr pull request #786
Opened 2017-07-13 22:02 UTC by lpereira

By having this as a Python script rather than a host executable, this
should simplify the build process on non-Unix platforms.  The
'pyelftools' library is required for this, and can be installed with:

	pip install pyelftools

Jira: ZEP-2062
Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

2017-07-14 02:13 UTC, tyrantlizard77 requested changes
This PR must include changes to the first-time setup doucmentation for all 3 host arches (mac/linux/windows) that pyelftools must be installed.

We also need to install it on the CI machines for this PR to pass CI

Python code looks fine.

2017-07-14 14:29 UTC, mbolivar commented
This is also 'python3-pyelftools' on Debian based distros, FYI. (Some admins may prefer using the package manager to pip).

2017-07-14 14:34 UTC, pfalcon reviewed
I'm personally all for replacing obfuscated C sources with Python ones, but I'm not sure if this change will make it better for everyone - this adds dependency on 3rd-party Python module, whereas original tool didn't have additional dependencies.

2017-07-14 14:34 UTC, pfalcon commented on scripts/gen_offset_header.py
> +  obj = ELFFile(input_file)
Indentation in this file doesn't conform to PEP8.

2017-07-14 16:08 UTC, andrewboie commented on scripts/gen_offset_header.py
> +#!/usr/bin/python
we have standardized on Python 3 for all Zephyr python code, please convert and change this line to 
#!/usr/bin/env python3

2017-07-14 16:09 UTC, andrewboie commented on scripts/gen_offset_header.py
> +  obj = ELFFile(input_file)
agreed I would prefer to see 4-space indentation

2017-07-14 16:09 UTC, andrewboie commented
CI does not like the hard tab in the commit message, BTW

2017-07-14 16:12 UTC, andrewboie commented
@pfalcon we already require several pip modules to be installed and we are converting all C-based build tools to Python to make Windows build support simpler

2017-07-14 16:31 UTC, pfalcon commented
I see, cool.

2017-07-14 17:27 UTC, andrewboie commented on scripts/gen_offset_header.py
> +  if not symtab:
I suggest throwing an exception in this and the below isinstance check if they fail

2017-07-14 18:03 UTC, andrewboie commented
I'm getting a lot of build errors, seems like there is a stray space being inserted?

                 from /projects/zephyr2/arch/arc/core/swap.S:18:
/projects/zephyr2/sanity-out/arduino_101_sss/tests/kernel/mem_slab/mslab/test/include/generated/offsets.h:8:26: warning: extra tokens at end of #ifndef directive
 #ifndef __INCLUDE_GUARD_ 5d8d48e39d92163__
                          ^~~~~~~~~~~~~~~~~

2017-07-14 18:04 UTC, andrewboie commented on scripts/gen_offset_header.py
> +    include_guard = "__INCLUDE_GUARD_%16x__" % abs(input_name.__hash__())
i think you need %016x to zero-lead the value otherwise there are gonna be spaces

2017-07-14 20:07 UTC, lpereira commented
Pull request to install pyelftools on Shippable is in the `ci-dockerfiles` repository, here: https://github.com/zephyrproject-rtos/ci-dockerfiles/pull/1

2017-07-15 02:00 UTC, dbkinder submitted a review, later dismissed
+1 for doc changes

2017-07-17 18:23 UTC, tyrantlizard77 requested changes

2017-07-17 18:23 UTC, andrewboie commented on doc/getting_started/installation_linux.rst
> +	 python-yaml dfu-util dtc python3-pyelftools
this installs version 0.22 which is too old.
Add to pip line instead.

2017-07-17 18:23 UTC, andrewboie commented on doc/getting_started/installation_linux.rst
> +	 python3-pyelftools
i don't know what version this installs.
if it's not 0.24, recommend install via pip instead.

2017-07-18 16:58 UTC, lpereira commented
@andrewboie Updated docs to suggest pyelftools installation through pip.

2017-07-19 15:28 UTC, tyrantlizard77 submitted a review, later dismissed

2017-07-19 15:28 UTC, andrewboie commented
LGTM.
I really hope we don't have to wait until next week to get pyelftools on the CI machines....

2017-07-19 16:42 UTC, galak commented
@andrewboie I'll merge the docker update, but would like it to pass CI.

2017-07-19 16:45 UTC, andrewboie commented
@galak agreed.
@nashif  said he would spend some time looking at this today.
I think the docker patch may need to be updated, unless we are using Ubuntu 16.10 or later we will need to install with pip, the library version must be 0.24 or later.

2017-07-21 10:04 UTC, andrewboie commented
If you rebase I think we can merge this

2017-07-22 18:16 UTC, nashif commented
> I'm personally all for replacing obfuscated C sources with Python ones, but I'm not sure if this change will make it better for everyone - this adds dependency on 3rd-party Python module, whereas original tool didn't have additional dependencies.

The original tool had dependency on a host compiler, and this is a major dependency compared to a python module. We do need python anyways and it is easier to get install compared with a host compiler, for example on windows...

2017-07-22 20:04 UTC, nashif requested changes

2017-07-22 20:04 UTC, nashif commented on Kbuild
> +	$(PYTHON) $(srctree)/scripts/gen_offset_header.py -i $(1) -o $@.tmp; \
this will call the script with python which by default on many systems will be python2. Call the script directly instead.

2017-07-22 20:04 UTC, nashif commented on scripts/gen_offset_header.py
> +    output_file = open(args.output, 'wb')
why are we writing binary? This fails with python3

2017-07-22 20:04 UTC, nashif commented on scripts/gen_offset_header.py
> +    symtab = obj.get_section_by_name(b'.symtab')
This is not working for me, symtab does not exist, I quickly hacked this to 

~~~~
-    symtab = obj.get_section_by_name(b'.symtab')
-    if not symtab:
-        print("Could not find .symtab section in %s" % input_name)
-        return 1
-
-    if not isinstance(symtab, SymbolTableSection):
-        print(".symtab section is not an a symbol table")
-        return 1
+    for section in obj.iter_sections():
+        if isinstance(section, SymbolTableSection):
+            symtab = section
~~~~

and now it works.

2017-07-24 16:25 UTC, andrewboie commented
hmm I seem to remember documentation changes in one version of this patch set, but they seem to not  be in this latest version?

2017-07-24 17:13 UTC, lpereira commented
Yes, that's strange; the documentation was updated in a previous version. Sending a new one in a few minutes.

2017-07-24 17:15 UTC, nashif commented
> Yes, that's strange; the documentation was updated in a previous version. Sending a new one in a few minutes.

Wait, this was modified globally in another patch already and was conflicting. I did the change.

No need to document individual python modules for every OS now, it is all listed in the requirements.txt file in one file now.

2017-07-24 17:18 UTC, lpereira commented
The documentation changes are not required any longer, since all Python dependencies are descibed in `scripts/requirements.txt`.

2017-07-24 17:32 UTC, lpereira commented
Rebased and addressed @nashif's comments.

2017-07-24 18:17 UTC, nashif approved these changes

2017-07-24 18:20 UTC, merged