drivers: eth_xlnx_gem: ICMP checksum is 0
zephyrproject-rtos/zephyr pull request #78811
Opened 2024-09-22 07:53 UTC by blofeld80

Apperently, the cadence gem within Zynq 7000 supports checksum offloading only for IP, TCP and UDP, but not ICMP. The PR provides a solution to this issue by adding a get_config with more detailed information on the checksum offloading capabilites.

2024-09-23 06:37 UTC, pdgendt commented
Some compliance issues that need fixing.

2024-09-24 14:13 UTC, ibirnbaum requested changes
This PR contains the same commit that is the item of your other PR #78808, please drop that commit from the branch you'd like to merge with this PR.

2024-09-24 14:37 UTC, ibirnbaum commented on drivers/ethernet/eth_xlnx_gem.c
> +			config->chksum_support = NET_IF_CHECKSUM_IPV4_HEADER | NET_IF_CHECKSUM_IPV4_TCP | NET_IF_CHECKSUM_IPV4_UDP | NET_IF_CHECKSUM_IPV6_HEADER | NET_IF_CHECKSUM_IPV6_TCP | NET_IF_CHECKSUM_IPV6_UDP;
config->chksum_support is of type enum ethernet_checksum_support, whose values are prefixed ETHERNET_CHECKSUM_SUPPORT_... These values should be used, even though they just redirect to NET_IF_CHECKSUM_...

2024-09-24 14:42 UTC, ibirnbaum commented on drivers/ethernet/eth_xlnx_gem.c
> +			config->chksum_support = NET_IF_CHECKSUM_IPV4_HEADER | NET_IF_CHECKSUM_IPV4_TCP | NET_IF_CHECKSUM_IPV4_UDP | NET_IF_CHECKSUM_IPV6_HEADER | NET_IF_CHECKSUM_IPV6_TCP | NET_IF_CHECKSUM_IPV6_UDP;
NET_IF_CHECKSUM_IPV4_TCP equals NET_IF_CHECKSUM_IPV4_HEADER_BIT | NET_IF_CHECKSUM_TCP_BIT
NET_IF_CHECKSUM_IPV6_TCP equals NET_IF_CHECKSUM_IPV6_HEADER_BIT | NET_IF_CHECKSUM_TCP_BIT
The TCP bit is being specified twice, which is not necessary.
ETHERNET_CHECKSUM_SUPPORT_IPV4_HEADER | ETHERNET_CHECKSUM_SUPPORT_IPV6_HEADER | ETHERNET_CHECKSUM_SUPPORT_TCP | ETHERNET_CHECKSUM_SUPPORT_UDP specifies all the capabilities without specifying anything twice.

2024-09-24 14:58 UTC, ibirnbaum commented on drivers/ethernet/eth_xlnx_gem.c
> +	int ret = -1;
Querying an unsupported / unimplemented config item should return -ENOTSUP.

2024-12-08 00:39 UTC, closed without merging