doc: mcumgr: Fix license
zephyrproject-rtos/zephyr pull request #78923
Opened 2024-09-24 09:09 UTC by jeppenodgaard

mcumgr-client is Apache-2 and not BSD licensed.
See: https://github.com/vouch-opensource/mcumgr-client/blob/main/LICENSE

2024-09-24 09:14 UTC, nordicjm submitted a review, later dismissed

2024-09-24 09:59 UTC, kartben submitted a review, later dismissed

2024-09-24 13:45 UTC, henrikbrixandersen requested changes
Shouldn't the license say Apache-2.0?

2024-09-24 13:45 UTC, henrikbrixandersen commented on doc/services/device_mgmt/mcumgr.rst
> +        | `mcumgr-client <https://github.com/vouch-opensource/mcumgr-client/>`_          | ✓       | ✓     | ✓   | ✕      | ✕        | ✓      | ✕         | ✕   | ✕  | ✓   | ✕    | ✕        | ✕  | ✕
```suggestion
        | `mcumgr-client <https://github.com/vouch-opensource/mcumgr-client/>`_          | ✓       | ✓     | ✓   | ✕      | ✕        | ✓      | ✕         | ✕   | ✕  | ✓   | ✕    | ✕        | ✕  | ✕     | ✕    | ✕      | Application   | Rust       | Apache-2.0  |
```

2024-09-24 16:31 UTC, jeppenodgaard commented
> Shouldn't the license say Apache-2.0?

I do not know. 

There's two other clients in the list that does not include the license version. I followed their example. The GPL license specifies the version, so the list is inconsistent. I guess that should be fixed.

2024-09-27 06:33 UTC, jeppenodgaard commented on doc/services/device_mgmt/mcumgr.rst
> +        | `mcumgr-client <https://github.com/vouch-opensource/mcumgr-client/>`_          | ✓       | ✓     | ✓   | ✕      | ✕        | ✓      | ✕         | ✕   | ✕  | ✓   | ✕    | ✕        | ✕  | ✕
Fixed

2024-09-27 07:37 UTC, nordicjm approved these changes

2024-09-27 08:19 UTC, henrikbrixandersen approved these changes

2024-09-27 08:22 UTC, de-nordic approved these changes

2024-09-27 09:56 UTC, merged