feat: Updated adxl345 sensor driver to utilze devicetree configuration
zephyrproject-rtos/zephyr pull request #78957
Opened 2024-09-24 18:53 UTC by whati001

Followup PR of: https://github.com/zephyrproject-rtos/zephyr/pull/66046

Updated/rewritten adxl345 sensor code to support devicetree parameters. I have tested the code with an nrf52840-dk and a adxl345 connected via I2C.

2024-10-01 09:17 UTC, ttmut commented on dts/bindings/sensor/adi,adxl345-common.yaml
> +# Copyright (c) 2023 Andreas Karner <andreaskarner@outlook.com>
The year should be 2024.

2024-10-01 09:19 UTC, ttmut commented
You may consider rewriting the commit titles to include the area of changes such as`dts: bindings: ...` and `drivers: sensor: ...`
See https://docs.zephyrproject.org/latest/contribute/guidelines.html#area-summary-of-change

2024-10-16 16:14 UTC, ubieda requested changes
Please remove non-related changes

2024-10-16 16:14 UTC, ubieda commented on drivers/sensor/adi/adxl345/adxl345.h
> +#define ADXL345_DEVICE_ID_VALUE 0b11100101
This seems like a non-related change; it already was defined in:
``` c
#define ADXL345_PART_ID            0xe5
```

Moreover, Usage of binary constants is discouraged. See: #60564.
Please discard non-related changes.

2024-10-27 10:09 UTC, whati001 commented
Part of this PR were implemented in https://github.com/zephyrproject-rtos/zephyr/pull/80004.
I may open a new PR for specifying the range via dt.

2024-10-27 10:09 UTC, closed without merging