soc: MCXW71: Enable FlexCAN
zephyrproject-rtos/zephyr pull request #78964
Opened 2024-09-24 22:45 UTC by decsny

enable the FlexCAN on MCXW71

also contains the same general fixes as #78963, doesn't matter which PR merges first though

2024-09-25 10:37 UTC, henrikbrixandersen requested changes

2024-09-25 10:37 UTC, henrikbrixandersen commented on soc/nxp/mcx/mcxw/soc.c
> +	if (CONFIG_CAN_MCUX_FLEXCAN) {
```suggestion
	if (IS_ENABLED(CONFIG_CAN_MCUX_FLEXCAN)) {
```

2024-10-09 13:50 UTC, dleach02 submitted a review, later dismissed

2024-10-10 19:38 UTC, henrikbrixandersen requested changes

2024-10-10 19:38 UTC, henrikbrixandersen commented on boards/nxp/frdm_mcxw71/frdm_mcxw71.dts
> +		max-bitrate = <420000000>;
420 Mbit/s CAN transceiver? I want one ;)

2024-10-10 19:38 UTC, henrikbrixandersen commented on dts/arm/nxp/nxp_mcxw71.dtsi
> +		sample-point = <875>;
Please remove `sample-point` property. Relying on the default is better, as it adapts to the configured bitrate.

2024-10-15 18:41 UTC, henrikbrixandersen submitted a review, later dismissed

2024-10-17 21:09 UTC, dleach02 commented
@decsny please address the merge conflicts so we can merge

2024-10-23 16:41 UTC, danieldegrasse approved these changes, later dismissed

2024-10-23 17:21 UTC, henrikbrixandersen requested changes
Did you push the wrong changeset?

2024-10-23 17:21 UTC, henrikbrixandersen commented on boards/nxp/frdm_mcxw71/frdm_mcxw71.dts
> +		max-bitrate = <420000000>;
Looks like this was re-introduced?

2024-10-23 17:21 UTC, henrikbrixandersen commented on dts/arm/nxp/nxp_mcxw71.dtsi
> +		sample-point = <875>;
Same with this one?

2024-10-23 18:07 UTC, decsny commented
@henrikbrixandersen yeah, woops, thanks for catching it

2024-10-23 18:29 UTC, danieldegrasse approved these changes

2024-10-23 19:03 UTC, henrikbrixandersen approved these changes

2024-10-24 05:13 UTC, dleach02 approved these changes

2024-10-24 07:29 UTC, merged