scripts: twister: Add test plan filtering feature (--exclude-plan)
zephyrproject-rtos/zephyr pull request #79188
Opened 2024-09-30 09:25 UTC by golowanow

New Twister `exclude-plan` feature for testplan advanced filtering and test scope gap resolution.

The new feature allows to apply Twister testplan and report JSON file(s) as extended rules to filter out tests on the following Twister executions. This way a test plan hierarchy can be orchestrated, for example with simulated and physical platforms to optimize their usage.

The testplan files can be applied for filtering in different ways: by exact match on test name, platform, runnable status, test status, and their combinations.

New Twister options (also documented in command line help):
 --exclude-plan-exact
 --exclude-plan-platform
 --exclude-plan-run
 --exclude-plan-name
 --exclude-plan-status

Twister test suites for the new feature.

2024-10-05 12:19 UTC, golowanow commented
^ dear reviewers, up to your attention

2024-10-05 18:01 UTC, nashif commented
I am not sure I understand what this PR is trying to do, please provide some more details in form of docs or in the body of this PR.

2025-01-19 14:09 UTC, hakehuang approved these changes, later dismissed

2025-01-22 13:39 UTC, nashif requested changes
value of those additional options and logic is still not clear, need to show the benefit and how those options will be used and where they will be used.

2025-09-07 00:40 UTC, closed without merging