drivers: gpio: stm32h7rs serie requires specific power rails
zephyrproject-rtos/zephyr pull request #79257
Opened 2024-10-01 10:27 UTC by FRASTM

mentionned by the [RM0477   ](https://www.st.com/resource/en/reference_manual/rm0477-stm32h7rx7sx-armbased-32bit-mcus-stmicroelectronics.pdf)10.3.16 High-speed low-voltage mode (HSLV

> The GPIOs are all programed with the same HSLV setting, except those from dedicated 
> power rail (OCTO, HEXA and USB):
> • XSPIM2 rail: PN[0:12]
> • XSPIM1 rail: PO[0:5], PP[0:15]
> • USB no software compensation setting

More power rails to enable when using GPIO bank M, N, O, P
Enables the XSPIM2 rail when using GPIO bank N
Enables the XSPIM1 rail when using GPIO bank O or P 
Enables the USBvoltage detector when using the GPIO M

2024-10-01 10:29 UTC, FRASTM commented
This PR makes the led flash when running the samples/basic/blinky  on the stm32h7s78_dk for any led0 or led1 or led2 or led3

2024-10-01 11:02 UTC, FRASTM commented
running tests/drivers/gpio/ on the stm32h7s78_dk

2024-10-07 10:22 UTC, henrikbrixandersen approved these changes, later dismissed

2024-10-07 14:19 UTC, erwango requested changes

2024-10-07 14:19 UTC, erwango commented on drivers/gpio/gpio_stm32.c
> +#endif /* CONFIG_SOC_SERIES_STM32H7RSX */
As discussed, please move these to `soc/st/stm32/stm32h7rsx/soc.c`

2024-10-11 08:26 UTC, FRASTM commented
move the change to the stm32h7rs soc

2024-10-11 08:33 UTC, erwango requested changes
Otherwise LGTM

2024-10-11 08:33 UTC, erwango commented on soc/st/stm32/stm32h7rsx/soc.c
> +#if DT_NODE_HAS_STATUS(DT_NODELABEL(gpioo), okay) ||  DT_NODE_HAS_STATUS(DT_NODELABEL(gpiop), okay)
Minor nit pick:
```suggestion
#if DT_NODE_HAS_STATUS(DT_NODELABEL(gpioo), okay) || DT_NODE_HAS_STATUS(DT_NODELABEL(gpiop), okay)
```

2024-10-11 12:26 UTC, FRASTM commented on soc/st/stm32/stm32h7rsx/soc.c
> +#if DT_NODE_HAS_STATUS(DT_NODELABEL(gpioo), okay) ||  DT_NODE_HAS_STATUS(DT_NODELABEL(gpiop), okay)
space char removed

2024-10-11 13:42 UTC, erwango approved these changes

2024-10-11 13:47 UTC, marwaiehm-st approved these changes

2024-10-11 14:02 UTC, henrikbrixandersen approved these changes

2024-10-11 17:16 UTC, merged