tests: drivers: uart: uart_pm: Fix fail on nrf54h20
zephyrproject-rtos/zephyr pull request #79268
Opened 2024-10-01 12:14 UTC by nordic-segl

Power states were recently added to the board definition of nrf54h20:
https://github.com/zephyrproject-rtos/zephyr/commit/5b607ed5c7869b6f01098bb02d5d81c357c3cb43
This has negative impact on drivers.uart.pm.int_driven test.

Delete property 'cpu-power-states' in the test overlay for nrf54h20.

2024-10-01 12:16 UTC, nordic-segl commented
FYI @nordic-krch @gmarull @nordic-piks

2024-10-01 12:24 UTC, nordic-segl commented
Fix was discussed in other PR
https://github.com/nrfconnect/sdk-nrf/pull/17380#issuecomment-2385572503

2024-10-01 12:37 UTC, gmarull requested changes
Sounds like this is papering over a real bug, the PR doesn't really fix anything. I think test should be disabled/quarantined for 54h20 until fixed.

2024-10-01 14:18 UTC, nordic-krch commented
I'm trying to investigate the root cause.

2024-10-02 06:35 UTC, nordic-segl commented
Closing in favour of https://github.com/zephyrproject-rtos/zephyr/pull/79292

2024-10-02 06:35 UTC, closed without merging