samples: drivers: gnss: more API testing
zephyrproject-rtos/zephyr pull request #79353
Opened 2024-10-03 04:14 UTC by JordanYates

Query additional information in the GNSS API sample. This exercises more of the API implemented by GNSS drivers without changing the behaviour of the sample while providing more information to the user.

Updated output looks like the following:
```
GNSS Systems:
             GNSS_SYSTEM_GPS: Supported: Yes Enabled: Yes
         GNSS_SYSTEM_GLONASS: Supported: Yes Enabled: Yes
         GNSS_SYSTEM_GALILEO: Supported: Yes Enabled:  No
          GNSS_SYSTEM_BEIDOU: Supported: Yes Enabled:  No
            GNSS_SYSTEM_QZSS: Supported: Yes Enabled: Yes
           GNSS_SYSTEM_IRNSS: Supported:  No Enabled:  No
            GNSS_SYSTEM_SBAS: Supported: Yes Enabled: Yes
            GNSS_SYSTEM_IMES: Supported:  No Enabled:  No
Fix rate = 1000 ms
```

2024-10-04 03:40 UTC, JordanYates commented
The title wording was a bit misleading, this is not meant to validate the API, just provide more useful information in the sample. I know I am more likely to stumble across new API functions in a sample than in a rigorous API test application, which don't necessarily show how to use a function in the easiest way.

2024-10-04 07:33 UTC, tomi-font submitted a review, later dismissed

2024-10-04 12:05 UTC, bjarki-andreasen approved these changes, later dismissed

2024-10-08 13:46 UTC, kartben requested changes

2024-10-08 13:46 UTC, kartben commented on samples/drivers/gnss/src/main.c
> +		printf("Failed to query supported systems (%d)\n", rc);
```suggestion
		printf("Failed to query enabled systems (%d)\n", rc);
```

2024-10-09 03:11 UTC, kartben approved these changes

2024-10-09 08:11 UTC, tomi-font approved these changes

2024-10-09 09:46 UTC, bjarki-andreasen approved these changes

2024-10-09 11:47 UTC, merged