modules: segger: remove mutex locking
zephyrproject-rtos/zephyr pull request #79404
Opened 2024-10-04 03:46 UTC by JordanYates

Remove mutex locking in favour of the standard IRQ locking mechanism. The primary problem with the mutex implementation is that mutex locking is forbidden in ISR's. This means that any logging from an interrupt context (e.g. LOG_PANIC in an exception handler), will itself trigger another assertion due its attempt to use a mutex.

Furthermore, mutexes are a relatively heavyweight locking scheme, which doesn't necessarily make sense in the context of extremely short locking periods that would be expected from RTT.

This change aligns Zephyr with the default RTT locking scheme, which uses interrupt masking to perform access control.

Resolves #79403.

2024-10-04 15:50 UTC, dcpleung submitted a review, later dismissed

2024-10-07 12:44 UTC, henrikbrixandersen requested changes

2024-10-07 12:44 UTC, henrikbrixandersen commented on modules/segger/SEGGER_RTT_zephyr.c
>  K_MUTEX_DEFINE(rtt_term_mutex);
Is this mutex instance still used?

2024-10-08 05:32 UTC, henrikbrixandersen approved these changes, later dismissed

2024-10-08 06:15 UTC, nordic-krch submitted a review, later dismissed

2024-10-08 10:50 UTC, JordanYates commented
Updated with final SHA

2024-10-08 10:54 UTC, henrikbrixandersen approved these changes

2024-10-10 08:40 UTC, nordic-krch approved these changes

2024-11-06 19:25 UTC, mmahadevan108 commented
@dcpleung , can you help review

2024-11-06 19:30 UTC, dcpleung approved these changes

2024-11-07 19:06 UTC, merged