boards: beagle: beagleplay_cc1352p7: Disable 2.4g ieee802154
zephyrproject-rtos/zephyr pull request #79405
Opened 2024-10-04 06:20 UTC by Ayush1325

- A lot of zephyr networking samples (zperf, http_server, etc) will complain if both 2.4g and subg ieee802154 are enabled simultaneously.
- This leads to a lot of new people getting confused with the network code not working without any clear errors.
- As we already set the alias `zephyr,ieee802154 = &ieee802154g`, I think it would be best to enable only subg by default.
- Following the example of: https://github.com/zephyrproject-rtos/zephyr/pull/78667

2024-10-04 08:02 UTC, vaishnavachath requested changes

2024-10-04 08:02 UTC, vaishnavachath commented on boards/beagle/beagleplay/beagleplay_cc1352p7.dts
>  };
`status = "disabled";`

2024-10-04 18:17 UTC, vaishnavachath approved these changes, later dismissed

2024-10-05 10:32 UTC, henrikbrixandersen approved these changes, later dismissed

2024-10-12 07:09 UTC, henrikbrixandersen approved these changes

2024-10-15 23:56 UTC, kartben approved these changes

2024-10-16 15:09 UTC, fgrandel approved these changes

2024-10-16 15:36 UTC, merged