boards: st: stm32h750b-dk: enable usart1
zephyrproject-rtos/zephyr pull request #79434
Opened 2024-10-04 16:49 UTC by JarmouniA

Enable LPUART1 that can be used with external periphs via Arduino pins.
Tested with `tests/drivers/uart_basic_api`.

2024-10-07 06:59 UTC, erwango approved these changes

2024-10-11 07:46 UTC, FRASTM commented on boards/st/stm32h750b_dk/stm32h750b_dk.dts
> +&lpuart1 {
could also be in the arduino_r3_connector.dtsi
`arduino_serial: &lpuart1 {};`

2024-10-11 08:13 UTC, FRASTM reviewed
I would add a comment to  mention that the stm32h750b disco is explicitly set the USART1_RX and USART1 TX  on connector CN7 pins PB7/PB6  (Arduino connector), not the LPUART1 by default.
Otherwise LGTM

2024-10-17 10:09 UTC, erwango requested changes

2024-10-17 10:09 UTC, erwango commented on boards/st/stm32h750b_dk/stm32h750b_dk.dts
> +/* Arduino Header pins: Tx:D1, Rx:D0 */
Could add `arduino_serial: &lpuart1 {};` in `arduino_r3_conector.dtsi`

2024-10-21 05:58 UTC, erwango approved these changes

2024-10-21 08:14 UTC, mathieuchopstm reviewed
Minor detail but otherwise LGTM.

2024-10-21 08:14 UTC, mathieuchopstm commented on boards/st/stm32h750b_dk/stm32h750b_dk.dts
> +/* LPUART1 can also be used with this pins */
Nit:
```suggestion
/* LPUART1 can also be used with these pins */
```

2024-10-22 14:18 UTC, FRASTM approved these changes

2024-10-22 18:41 UTC, merged