doc: boards: infineon: fix various issues with cy8ckit_062s4
zephyrproject-rtos/zephyr pull request #79496
Opened 2024-10-07 11:51 UTC by kartben

Title of the document was wrong, image info was missing, and a bunch of other formatting issues.

2024-10-07 15:50 UTC, ifyall requested changes

2024-10-08 14:17 UTC, kartben commented on boards/infineon/cy8ckit_062s4/doc/index.rst
> +INFINEON PSoC 62S4 Pioneer Kit
sure, done. FWIW, as I'm sure you're aware, there are many other places where "PSoC" is still used, including in this document ("... which is an ultra-low-power PSoC device specifically ...").

2024-10-08 16:56 UTC, ifyall approved these changes

2024-10-10 06:29 UTC, pdgendt approved these changes

2024-10-10 08:07 UTC, merged