arm-v8 a/r: linker: move data section between rodata and bss
zephyrproject-rtos/zephyr pull request #79502
Opened 2024-10-07 12:49 UTC by Dat-NguyenDuy

This PR helps to reduces size of zephyr.bin on non-XIP by moving data section between rodata and bss.
Also move to use proper macro helpers when declaring no-init section.

2024-11-08 02:54 UTC, Dat-NguyenDuy commented
Hi @nashif , @dcpleung could you help review this PR. Thanks

2024-11-18 02:55 UTC, Dat-NguyenDuy commented
Hello, @ithinuel could you help to take a look, thanks.

2024-11-18 18:57 UTC, dcpleung approved these changes, later dismissed

2024-11-25 14:41 UTC, ithinuel commented
This seems related to https://github.com/zephyrproject-rtos/zephyr/pull/74042 and more specifically https://github.com/zephyrproject-rtos/zephyr/pull/60368 which was reverted in https://github.com/zephyrproject-rtos/zephyr/pull/61595.

@gramsay0 & @tejlmand, you have a much better understanding of linker scripts than I have.
Could you have a look at this change please?

2024-11-26 20:16 UTC, gramsay0 commented
@ithinuel  https://github.com/zephyrproject-rtos/zephyr/pull/60368 was reverted because of unrelated, undefined behavior in a test, but was never reapplied after the test was fixed (see the last few comments in https://github.com/zephyrproject-rtos/zephyr/issues/61572).

AFAICT this look good

2024-11-26 20:17 UTC, gramsay0 submitted a review, later dismissed

2024-11-27 11:56 UTC, tejlmand requested changes
Changes in themselves looks reasonable, but I would like this work to be aligned with the work done in #74042, so that we can have similar structure / layout on the cortex_m and cortex_a_r, to the extent possible of course;

I made some comments here: https://github.com/zephyrproject-rtos/zephyr/pull/74042#pullrequestreview-2347636385
Please take a look, especially:
> Seems like the arm64, cortex_a_r suffers the same issue and for the above reason but also because it's nice to have the linker.ld files somewhat aligned in how they look, then it would be nice to have those aligned as well.

#74042 covers cortex_m, and this PR covers cortex_a_r, however they define the bss section differently in the two files.
For #74042 (cortex_m) the bss section is moved all the way to the end of the linker script, and this PR just moves it a little bit.

Please get the location in the ld templates aligned between the two PRs.
It's hard enough already when looking into the ld template files, and having same sections ordered differently when there is no obvious reason just make things harder to understand and update.

Perhaps going for the `at-the-end` approach used in #74042, as that also seems to cover the `last_section` counter when XIP is used, except for the ITCM case, see https://github.com/zephyrproject-rtos/zephyr/pull/74042#issuecomment-2393288500.

as for:
> and disabling Kconfig LINKER_LAST_SECTION_ID by default if non-XIP (it is seems only needed for XIP)

then I wonder from where this impression stems ?
The `_flash_used` might be used by images themselves to know their size or by bootloaders / validation code to know the size of image. Thus independent to XIP / non-XIP.
I believe moving the BSS section description to the end will have positive impact on the `_flash_used` calculation.

2024-11-29 02:26 UTC, Dat-NguyenDuy commented
Hi @tejlmand, i agree with you that we should align the work for linker script, to have a similar layout for Arm platform. I will take a look into gramsay0's PR.

However, for this `and disabling Kconfig LINKER_LAST_SECTION_ID by default if non-XIP (it is seems only needed for XIP)`.
At first, i cannot reproduce the issue you mentioned here https://github.com/zephyrproject-rtos/zephyr/pull/50711 (even XIP/non-XIP, at least on arm cortex_a_r). So i would really appreciate if you can point me how to replicate the issue to better understanding?

The purpose of `_flash_used` for non-XIP is not clear to me. From what i understand the `_flash_used` is size of LMA and it's the same with VMA on non-XIP device. And there is `last_ram_section` already https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/linker/ram-end.ld. People normally uses `image_ram_end` for this case.

Unless `_flash_used` is the size of binary to be loaded (i.e exclude noload section like .bss, .noinit, etc). But it's not true with current implementation.

2024-12-05 04:04 UTC, gramsay0 commented
> However, for this `and disabling Kconfig LINKER_LAST_SECTION_ID by default if non-XIP (it is seems only needed for XIP)`. At first, i cannot reproduce the issue you mentioned here #50711 (even XIP/non-XIP, at least on arm cortex_a_r). So i would really appreciate if you can point me how to replicate the issue to better understanding?

I also tried to recreate this. I *think* the issue was that `rom_report` was giving different results to the build footprint i.e. these both produce 8094 bytes:
```
west build -b qemu_cortex_m3 zephyr/samples/hello_world -t rom_report
...
Memory region         Used Size  Region Size  %age Used
           FLASH:        8094 B       256 KB      3.09%
...
Root   8094 100.00%  -
```

Then I added a test section in the linker script before `.last_section`:

```diff
     /* Sections generated from 'zephyr,memory-region' nodes */
     LINKER_DT_SECTIONS()
 
+SECTION_PROLOGUE(.test_section,,ALIGN(32))
+{
+  BYTE(1)
+} GROUP_LINK_IN(ROMABLE_REGION)
+
 /* Must be last in romable region */
 SECTION_PROLOGUE(.last_section,,)
 {
 ```

But the rom_report differed from the build footprint (8101 vs 8095 bytes):
```
west build -b qemu_cortex_m3 zephyr/samples/hello_world -t rom_report
...
Memory region         Used Size  Region Size  %age Used
           FLASH:        8101 B       256 KB      3.09%
...
Root   8095 100.00%  -
```

@tejlmand is this a bug, or am I misunderstanding what `.last_section` is intended for?

2024-12-12 10:52 UTC, tejlmand commented
> At first, i cannot reproduce the issue you mentioned here https://github.com/zephyrproject-rtos/zephyr/pull/50711

The issue is very hard to reproduce, and when I investigated the original cause I was not able to directly reproduce it in the Zephyr tree, only through some extra hacks which I had to use to verify that I had really solved the issue.

Besides the linked PR which briefly describes what actually happened, then triggering this issue was a combination of multiple things which seems to throw of the linker. I'm not fully sure if there could also be a linker issue involved.

The issue was originally triggered by use of `zephyr_linker_sources()`  with `RAM_SECTIONS` (and also `RWDATA` iirc) which are provided for Zephyr downstream users to inject custom linker ld snippets into final linker script.

A combination of this feature together with use of `KEEP` and `NOLOAD` it those snippets seemed to be able to throw of the `last_section` calculation, if the symbol `_flash_used` was actually used in code.
In the exact case, this symbol was used for meta data information for firmware update, like here:
https://github.com/nrfconnect/sdk-nrf/blob/c4a02e0a9f9dc7ef3d14c13f655faf6143817e68/subsys/fw_info/fw_info.c#L24
https://github.com/nrfconnect/sdk-nrf/blob/c4a02e0a9f9dc7ef3d14c13f655faf6143817e68/subsys/fw_info/fw_info.c#L38

Now I don't remember the exact construct which can trigger this, but it was not as simple as tried here: https://github.com/zephyrproject-rtos/zephyr/pull/79502#issuecomment-2519042414

But the final investigation before #50711 proved that if a symbol was written into the section, instead of `NOLOAD`, then the location counter and flash usage would sync up.

Due to the fact that this indeed is hard to reproduce, then I want to play this safe, because having to once again trace down a bug like this can be time-consuming. A second problem is that in the case where someone uses this symbol for meta data, for example as part of a firmware update process, then this is the kind of error you don't want to experience on a target.

2025-01-12 15:04 UTC, Dat-NguyenDuy commented
Happy new year @tejlmand, i have updated the PR to moving bss/noinit sections to the end of linker script, to sync with what have been done for cortex_m. Pls help to check, thanks.

2025-01-12 20:07 UTC, gramsay0 approved these changes, later dismissed

2025-01-23 09:29 UTC, Dat-NguyenDuy commented
Hi @tejlmand, could you pls revisit this PR. Thanks a lot.

2025-02-05 19:02 UTC, wearyzen commented on include/zephyr/arch/arm/cortex_a_r/scripts/linker.ld
> +        __kernel_ram_start = .;
This essentially reduces `__kernel_ram_start` from bss+data to just bss and doesn't seem to be inline with its definition [here](https://github.com/zephyrproject-rtos/zephyr/blob/be91cfedfb54f9022dc0aa02c577b57b35f887a4/include/zephyr/linker/linker-defs.h#L95).

This also changes the dynamic region configured by mpu [here](https://github.com/zephyrproject-rtos/zephyr/blob/be91cfedfb54f9022dc0aa02c577b57b35f887a4/arch/arm/core/mpu/arm_core_mpu.c#L46)

2025-02-06 09:48 UTC, tejlmand requested changes
Please take a look at the observation from @wearyzen to ensure the region defined as the kernel ram region is preserved even if the internal sections are relocated.

2025-02-06 20:47 UTC, gramsay0 commented on include/zephyr/arch/arm/cortex_a_r/scripts/linker.ld
> +        __kernel_ram_start = .;
@wearyzen thank for finding that!

It looks like there was a similar issue and fix for aarch64 here:
https://github.com/zephyrproject-rtos/zephyr/pull/80135/commits/7473aa9ef2a0a75f4a766ce231821285a31c8ffb#diff-197a7777652a0ad3f659a00cf6e1840c8e1e0c0612857064a4d1bb21f56beea6

> Seems this should also be addressed as followup from this PR: https://github.com/zephyrproject-rtos/zephyr/pull/74042
FYI @gramsay0

@tejlmand Yep, will do 👍

2025-02-07 04:06 UTC, Dat-NguyenDuy commented
Yep, sure. I will address @wearyzen's comment.

2025-02-14 01:41 UTC, Dat-NguyenDuy commented on include/zephyr/arch/arm/cortex_a_r/scripts/linker.ld
> +        __kernel_ram_start = .;
@wearyzen, @tejlmand I have addressed the comment. Pls take a look. Thanks

2025-02-17 08:54 UTC, ibirnbaum commented
Hi all,

I'm the author of #60368, as was mentioned before, this PR was first merged but then reverted due to what later turned out to be a bug in a logging-related test. At that time, I didn't get around to getting that PR started again, and things went dormant for quite some time, as my colleagues and I eventually just used the linker command file from the PR out-of-tree, as we had to get rid of the potential massive .bss/.noinit bloat in our flat .bin images one way or another. As far as I can tell, my version of the linker command file can still be merged with relatively little effort, not too much has changed in the cortex_a_r linker command file since then so we just stuck to this solution.

So thanks to @Dat-NguyenDuy for picking up the issue again and making a fix available to everyone!

I had a look at my old PR and two things I can comment on from the sideline are the following (referring to: https://github.com/ibirnbaum/zephyr/blob/d8545f42e2bfceb51dd89b990c632401374be70f/include/zephyr/arch/arm/aarch32/cortex_a_r/scripts/linker.ld):
- It seemed by the time that I submitted my PR nobody had really tried building for XIP on Cortex-A, and when building for qemu_cortex_a9 or actual Zynq-based hardware, there was a weird syntax error hidden behind the SECTION_DATA_PROLOGUE macro. That's why I defined SECTION_ALIGN in dependency of XIP mode. Does that problem still exist, or did someone change something about SECTION_DATA_PROLOGUE in the meantime?
- There was an issue revolving around the placement of z_mapped_start, which was documented in #51024. This would have been fixed if my PR had been (re-)merged. If z_mapped_start does not cover the first 4k of the image, which contains the exception vectors to be copied to 0x0 (plus the required padding up to the size of a full MMU page), the first call that maps memory at run-time via the MMU will assign the single page where the vectors used to be in the image followed by subsequent pages which are above the Zephyr image. So any first memory mapping at run-time which is > 4k will work with memory that is not physically contiguous. In the end, during my testing, it eventually turned out that the position of z_mapped_start already used for XIP was also applicable for non-XIP and solved the issue of the memory mapper thinking that this single 4k page below all the Zephyr code/data was suitable for a user mapping at run-time.

If it's helpful, you can ping me for verification testing on the Zynq once the modifications of the linker command file are considered final.

2025-03-14 18:48 UTC, wearyzen submitted a review, later dismissed

2025-04-04 09:47 UTC, wearyzen commented
@Dat-NguyenDuy could you please rebase and resolve conflicts in this PR?

2025-04-04 16:47 UTC, Dat-NguyenDuy commented
> @Dat-NguyenDuy could you please rebase and resolve conflicts in this PR?
I've fixed the conflict. I see you have changed this recently:
```
#if ROM_ADDR != RAM_ADDR
    . = RAM_ADDR;
#endif
```
so my update (used #if CONFIG_XIP) is not needed anymore.

2025-04-07 15:20 UTC, wearyzen commented
> Edit: Hi @wearyzen, looking into your recently merged PR: https://github.com/zephyrproject-rtos/zephyr/pull/87965/files. After the PR merged, the text region is overlapping with RAM in non-XIP again (that was addressed by this PR: #77291).

Hi @Dat-NguyenDuy, so in 87965, I reverted to what was initially proposed in 77291 (ref: https://github.com/zephyrproject-rtos/zephyr/pull/77291#discussion_r1943645045) so now I am bit confused and wondering if 77291 fixed any problem at all 😕 .
1 thing is for sure that, neither of the 2 solutions in the above PRs is completely right. With `#if CONFIG_XIP` the ci fails as reported [here](https://github.com/zephyrproject-rtos/zephyr/pull/77291#issuecomment-2768811915) and with 87965 you still have the ram overlapping with text.

> IMO, for non-XIP, the RAM_ADDR and ROM_ADDR should be the same (SRAM), at least for ARM. CONFIG_FLASH_<> should not be used, because the default linker script does not use Flash at all, no input sections are placed in there: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm/cortex_a_r/scripts/linker.ld#L22-L26, https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm/cortex_m/scripts/linker.ld#L22-L26. -> **default linker script should be updated instead**.
> 
> Also by default, if non-XIP, CONFIG_FLASH_SIZE=0, https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/Kconfig#L238. Some SoCs override this value for specific purposes, such as configuring the MPU for Flash, which is not necessary. I think this can be cleaned up in the future.

I don't have much experience on linker scripts as you do but I agree that it needs a cleanup since there is a lot of confusion.
I would appreciate if you or some linker expert would help on this.

2025-04-07 17:56 UTC, wearyzen approved these changes

2025-04-07 17:59 UTC, wearyzen commented
@tejlmand could you please have a look at this PR as well? there are few new follow ups raised but it would be good to get this one merged first.

2025-04-16 10:37 UTC, Dat-NguyenDuy commented
Hi @tejlmand, could you take another look, you left one blocker for this PR. Thanks

2025-05-01 13:35 UTC, tejlmand approved these changes

2025-05-01 16:15 UTC, merged