boards: nordic: ipc: added dcache alignement
zephyrproject-rtos/zephyr pull request #79596
Opened 2024-10-09 09:38 UTC by doki-nordic

The nRF54 and nRF92 chips has data cache, which means the ICMsg and ICBMsg must be configured to follow required cache alignment of the shared memory.
The `dcache-alignement` needs to be defined for that.

2024-10-09 09:53 UTC, peknis requested changes

2024-10-09 09:53 UTC, peknis commented on doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst
> +.. warning::
```suggestion
.. caution::
```
Warning is too strong.

2024-10-09 09:53 UTC, peknis commented on doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst
> +* If at least one of the cores uses data cache on shared memory, set ``dcache-alignment``.
```suggestion
* If at least one of the cores uses data cache on shared memory, set the ``dcache-alignment`` value.
```

2024-10-09 09:53 UTC, peknis commented on doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst
> +  This must be the biggest value of the invalidation or the write-back size for both sides of the communication.
```suggestion
  This must be the largest value of the invalidation or the write-back size for both sides of the communication.
```

2024-10-09 09:53 UTC, peknis commented on doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst
> +* If at least one of the cores uses data cache on shared memory, set ``dcache-alignment``.
Same fixes to the other doc.

2024-10-09 10:14 UTC, peknis approved these changes

2024-10-17 06:07 UTC, dchat-nordic approved these changes

2024-10-23 13:11 UTC, carlescufi approved these changes

2024-10-23 13:19 UTC, anangl approved these changes

2024-10-24 02:45 UTC, merged