boards: nordic: nrf7002dk: Exclude NS platforms
zephyrproject-rtos/zephyr pull request #79615
Opened 2024-10-09 13:53 UTC by krish2718

NS platforms are not supported due to lacking crypto support (only supported in NCS), so, exclude them from testing.

Note: I tried `default: False` but the platform (even without args) it still included, and `ignore_tags` doesn't seem to take wildcard, so, this is the easiest way I could find, not sure if there is a better way.

2024-10-10 07:12 UTC, PerMac requested changes
I believe it is wrong to have a platform in tree which is completely untestable. Also, this is a hacky workaround, not a proper use of tags.

2024-10-10 07:14 UTC, PerMac commented
"NS platforms are not supported due to lacking crypto support (only supported in NCS), so, exclude them from testing." If they are not supported, than they shouldn't be tree, no? If you say they need NCS, then why they are not placed in NCS?

2024-10-10 08:07 UTC, nordicjm commented
I agree, if the boards here do not work, remove them and put them downstream, they can be brought back when they are working.

2024-10-10 09:59 UTC, krish2718 commented
> Also, this is a hacky workaround, not a proper use of tags.

Yes, as mentioned in the description.

ok, I will move the board variant downstream.

2024-10-10 10:46 UTC, nordicjm submitted a review, later dismissed

2024-10-10 10:53 UTC, jukkar submitted a review, later dismissed

2024-10-10 12:21 UTC, sachinthegreen submitted a review, later dismissed

2024-10-11 06:32 UTC, krish2718 commented
@PerMac  please review, as this is gating nRF70 PRs want to get this merged ASAP.

2024-10-11 06:36 UTC, PerMac submitted a review, later dismissed

2024-10-11 07:23 UTC, anangl commented on boards/nordic/nrf7002dk/board.cmake
> -  set(TFM_PUBLIC_KEY_FORMAT "full")
Also the following is only related to non-secure targets so it's unneeded upstream: https://github.com/zephyrproject-rtos/zephyr/blob/733225e4a0322575006cca97b0d1d65f0664843c/boards/nordic/nrf7002dk/board.cmake#L9-L11

2024-10-11 07:23 UTC, anangl commented on boards/nordic/nrf7002dk/Kconfig.defconfig
> -	BOARD_NRF7002DK_NRF5340_CPUAPP_NS || \
Everything in this file is related to TF-M and does not make much sense if non-secure targets are not present. It'd be better to remove this file completely.

2024-10-11 07:29 UTC, anangl commented on boards/nordic/nrf7002dk/Kconfig.defconfig
Everything in this file is related to combined secure/non-secure builds so it does not make much sense to keep it if non-secure targets are not present.

2024-10-11 10:14 UTC, krish2718 commented on boards/nordic/nrf7002dk/Kconfig.defconfig
Yeah, I left these in intentionally to make it easier to reinstate but I can remove them as well.

2024-10-11 10:18 UTC, anangl approved these changes

2024-10-11 10:19 UTC, nordicjm approved these changes

2024-10-11 11:29 UTC, jukkar approved these changes

2024-10-11 17:32 UTC, merged