boards: add Myra SiP Baseboard
zephyrproject-rtos/zephyr pull request #79706
Opened 2024-10-11 10:13 UTC by fkokosinski

This PR:
* adds driver for the mb85rsm1t fram
* adds support for a new SoC in Zephyr - Myra SiP
* adds a new target that is based on the Myra SiP - Myra SiP Baseboard

2024-10-11 10:57 UTC, nordicjm commented on boards/antmicro/myra_sip_baseboard/doc/img/myra_sip_baseboard.jpg
Convert to webp, then put through https://tinypng.com/

2024-10-11 10:57 UTC, nordicjm commented on boards/antmicro/myra_sip_baseboard/doc/index.rst
> +The Zephyr ``myra_sip_baseboard`` board configuration supports the following hardware features:
*board target

2024-10-11 10:57 UTC, nordicjm commented on soc/antmicro/myra/Kconfig.soc
> +config SOC_MYRA
I'm really not convinced with this, it's an stm32, it should be handled as an stm32, all those extra parts should be in the board dts

2024-10-11 11:06 UTC, nordicjm requested changes
More I think about it the more it is a no, this is an stm32 with supporting components, they go in the board dts, do not create a "soc sip", use the existing stm32 one. This is no different than e.g. rm1xx_dvk where there is an spi flash inside the module

2024-10-11 13:09 UTC, kgugala commented
Hi @nordicjm, thanks for your comment.

> More I think about it the more it is a no, this is an stm32 with supporting components, they go in the board dts, do not create a "soc sip", use the existing stm32 one

This approach would mean that the shared configuration between board targets that share the same SiP would have to include duplicated code that would be otherwise provided by the SiP symbol, though.

Additionally, there already are other SIPs defined in a similar way in Zephyr, e.g.:
* `soc/nordic/nrf91/Kconfig.soc`:
  * `CONFIG_SOC_NRF9161_LACA`
* `soc/nordic/nrf92/Kconfig.soc`:
  * `CONFIG_SOC_NRF9280`
* `soc/espressif/esp32s2/Kconfig.soc`:
  * `CONFIG_SOC_ESP32S2_SOLO_N*` (4 types)
  * `CONFIG_SOC_ESP32S2_MINI*` (2 types)
  * `CONFIG_SOC_ESP32S2_WROOM`
  * `CONFIG_SOC_ESP32S2_WROVER*` (3 types)
* `soc/espressif/esp32s3/Kconfig.soc`:
  * `CONFIG_SOC_ESP32S3_MINI*` (2 types)
  * `CONFIG_SOC_ESP32S3_WROOM*` (9 types)

For now, all the SIPs in supported in Zephyr are in produced by the same vendor as the main SoC used in the SIP, however this is not always a case in the real world. Another example (similar to Myra) of such a SIP is https://octavosystems.com/octavo_products/osd32mp15x/ (this one is not yet supported in Zephyr, but we plan to add it soon)

2024-10-11 13:23 UTC, nordicjm commented
The 91* and 92* are normal SoCs in tree so I don't see what you mean. The espressif ones are different chips with different internal configurations, this one you have here is just a specific stm32 chip with peripherals around it, there is no reason to do it as you've done it here. Not that SiP's aren't important and support for that in hwmv2 is planned for the future, but there is nothing groundbreaking here that cannot be done as every other "SiP" in zephyr is done with a normal SoC definition for the actual SoC and then anything inside of a "package" being done at board level

2024-10-14 07:15 UTC, fkokosinski commented
> The 91* and 92* are normal SoCs in tree so I don't see what you mean

`SOC_NRF9161_LACA` is explicitly referred to as a SiP in a comment in Kconfig: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf91/Kconfig.soc#L31-L38, and uses the same justification that we had provided:

> The nRF9161 is technically a SiP (System-in-Package) that consists of the nRF9120 SoC and additional components like PMIC, FEM, and XTAL, so for nrfx/MDK the nRF9120 SoC is to be indicated as the build target, but since the nRF9161 is what a user can actually see on a board, using only nRF9120 in the Zephyr build infrastructure might be confusing. That's why in the top level of SoC definitions (for user-configurable options in Kconfig, for example) the nRF9161 term is used and nRF9120 underneath.

The same is true for for `CONFIG_SOC_NRF9280`: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf92/Kconfig.soc#L6-L10.

> The espressif ones are different chips with different internal configurations

Again, those SoCs that Karol had mention are listed under the "SiP" section comment in their respective Kconfig files https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/espressif/esp32s2/Kconfig.soc#L34:

> SiP with external flash / psram

2024-10-14 14:23 UTC, fkokosinski commented
> The 91* and 92* are normal SoCs in tree so I don't see what you mean

Those nRFs mentioned by @kgugala are referred to as SiPs by comments in their respective Kconfigs. As for `CONFIG_SOC_NRF9161_LACA`, the comment is here: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf91/Kconfig.soc#L31-L3

Plus, on the vendor's site nRF9161 is also explicitly called a SiP: https://www.nordicsemi.com/Products/nRF9161.

> The nRF9161 is technically a SiP (System-in-Package) that consists   of the nRF9120 SoC and additional components like PMIC, FEM, and XTAL, so for nrfx/MDK the nRF9120 SoC is to be indicated as the build target, but since the nRF9161 is what a user can actually see on a board, using only nRF9120 in the Zephyr build infrastructure might be confusing. That's why in the top level of SoC definitions (for user-configurable options in Kconfig, for example) the nRF9161 term is used and nRF9120 underneath.

And as for `CONFIG_SOC_NRF9280`, the comment is present here: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf92/Kconfig.soc#L37

> The SiP selects the actual SoC complete with engineer revision and appropriate CPU

Additionally, this file also states the following: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf92/Kconfig.soc#L12-L14

> Like it's done for the nRF91 family, let the nRF9280 SiP be represented by nRF9280 "SoC" in top-level SoC definitions and user-configurable Kconfigs, since that's what visible to users.

Which  means that those nRFs are explicitly defined as SiPs, and are definitely not "normal" SoCs.

---

> The espressif ones are different chips with different internal configurations

Again, those ESPs that Karol had mentioned are listed under the "SiP" section comment in their respective Kconfig files:
* https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/espressif/esp32s2/Kconfig.soc#L34
* https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/espressif/esp32s3/Kconfig.soc#L46

> SiP with flash and/or psram

---

>  but there is nothing groundbreaking here that cannot be done as every other "SiP" in zephyr is done with a normal SoC definition for the actual SoC and then anything inside of a "package" being done at board level

That's not exactly true, which the examples above prove. I.e. `CONFIG_SOC_NRF9161_LACA` (which is a Kconfig symbol for a SiP), selects `CONFIG_SOC_NRF9120`. I fail to see how nRF9161 is more "worthy" of being allowed this chain of Kconfig symbols as opposed to Myra, which other than having the STM32G491REI6 MCU in it, also integrates a 128kB FRAM chip, FTDI FT231XQ, crystal oscillators, LDOs etc. See more here: https://designer.antmicro.com/hardware/devices/myra-sip-interposer.

And here's the Kconfig snippet which demonstrates the Kconfig symbol chain: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nordic/nrf91/Kconfig.soc#L31-L41.

In summary: this PR doesn't really introduce any new way of defining a SiP; it just chooses the exact same convention that Zephyr had already opted to use.

2024-10-15 11:56 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/doc/img/myra_sip_baseboard.jpg
Done, filesize went down from 93k -> 34k

2024-10-15 11:56 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/doc/index.rst
> +The Zephyr ``myra_sip_baseboard`` board configuration supports the following hardware features:
Fixed

2024-10-16 07:51 UTC, henrikbrixandersen requested changes, later dismissed
> adds driver for the mb85rsm1t fram
> adds support for a new SoC in Zephyr - Myra SiP
> adds a new target that is based on the Myra SiP - Myra SiP Baseboard

This needs to be split into at least two PRs: One for adding the Myra SiP support along with the baseboard, and another for adding the EEPROM driver (unless the EEPROM driver is needed for the board to boot, but it does not look like it is?).

2024-10-16 08:14 UTC, fkokosinski commented
>  but it does not look like it is?

Correct - it's not needed for basic operation of the board. I've removed the driver from this PR.

2024-12-23 05:00 UTC, kartben requested changes

2025-01-07 11:46 UTC, fkokosinski commented on MAINTAINERS.yml
> +    - tgorochowik
Done

2025-01-07 11:46 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/board.yml
> +  name: myra_sip_baseboard
Added full name

2025-01-07 11:46 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/doc/index.rst
> +########################
the new directive is now used in the board doc

2025-01-07 11:47 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/doc/index.rst
> +
removed

2025-01-07 11:47 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/doc/index.rst
> +Applications for the ``myra_sip_baseboard`` board configuration can be built and flashed in the usual way (see :ref:`build_an_application` and :ref:`application_run` for more details).
fixed

2025-01-07 11:47 UTC, fkokosinski commented on boards/antmicro/myra_sip_baseboard/myra_sip_baseboard.yaml
> +  - xtools
removed `xtools` from the list

2025-01-08 12:44 UTC, tejlmand approved these changes, later dismissed
Approving.

There's currently no clean concepts of SiPs in Zephyr, but HWMV2 has paved the way to improve this by offering a better and more scalable model.
But for now, SiPs are generally exposed as being a SoC.

I think the current suggestion of presenting the Myra SiP with it's own SoC name in the soc / board yaml and Kconfig is acceptable as the system is for now.
I also believe it will make it less intrusive when having a true SiP support, as the names / symbols in that case will not need to change (assumption :see_no_evil: ).

Having dedicated SiP Kconfig symbol selecting the true STM SOC also allows to different cases where it's important to distinguish the SiP from the SoC.

2025-01-09 10:56 UTC, nordicjm commented on boards/antmicro/myra_sip_baseboard/myra_sip_baseboard_defconfig
> +CONFIG_MAIN_STACK_SIZE=4096
why is this needed?

2025-01-09 10:56 UTC, nordicjm commented on boards/antmicro/myra_sip_baseboard/myra_sip_baseboard_defconfig
> +CONFIG_RTC_LOG_LEVEL_WRN=y
why is RTC needed for every single build e.g. hello world?

2025-01-10 13:50 UTC, nordicjm submitted a review, later dismissed

2025-01-13 14:56 UTC, fkokosinski commented
Hey @MaureenHelm, could you take a look at this PR? Thanks!

2025-01-18 10:00 UTC, kartben requested changes
Spotted some issues with the board's doc page. Thanks!

2025-01-20 09:02 UTC, kartben approved these changes

2025-01-20 15:15 UTC, tejlmand approved these changes

2025-01-20 16:49 UTC, MaureenHelm approved these changes

2025-01-20 19:55 UTC, merged