Nxp S32 introduce support psi5
zephyrproject-rtos/zephyr pull request #79824
Opened 2024-10-15 01:43 UTC by congnguyenhuu

Introduce support Peripheral Sensor Interface (PSI5) driver on S32Z. This driver allows to communication (send, receive) with PSI5 device.

2025-01-15 13:56 UTC, JarmouniA reviewed
A test is needed as well, samples are not a replacement for tests.

2025-01-15 14:03 UTC, rruuaanng commented on samples/boards/nxp/s32/psi5/src/main.c
Because this is the smallest sample it provides that can run, I guess its prototype is developed based on nxp soc.

2025-01-16 07:03 UTC, congnguyenhuu commented on samples/boards/nxp/s32/psi5/src/main.c
I moved this sample to a generic driver sample.
And also created a test API driver .

2025-01-16 07:03 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +description: Properties for Peripheral Sensor Interface (PSI5)
I updated

2025-01-16 07:03 UTC, congnguyenhuu commented on samples/boards/nxp/s32/psi5/src/main.c
> +#define PSI5_NODE DT_INST(0, nxp_s32_psi5)
I updated

2025-01-16 07:10 UTC, rruuaanng commented on dts/bindings/psi5/psi5-controller.yaml
> +description: Properties for Peripheral Sensor Interface (PSI5)
@congnguyenhuu They are redundant and do not need to be prefixed. Putting them in `dts/bindings` already indicates that they are a binding. E.g. other bindings description.
```
Renesas RA ADC node

Static Battery Characteristics

Description of pre-defined file systems.

ADI MAX32 compatible Counter RTC

PL330 DMA Controller
```

2025-02-04 03:10 UTC, congnguyenhuu commented
.

2025-02-06 09:03 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +description: Properties for Peripheral Sensor Interface (PSI5)
I updated

2025-04-23 10:00 UTC, congnguyenhuu commented
Based on the suggestions from the Architecture WG meeting on March 4th, I have updated to the v1 changes. These updates include:
1. Changed `add_rx_callback(dev, channel, serial_cb, data_cb, user_data)` to
`register_callback(dev, channel, struct psi5_rx_callback_configs callback_configs)`
 
With the newly defined structure for RX callback configurations in `psi5.h`
```
struct psi5_rx_callback_config {
	psi5_rx_frame_callback_t callback;
	struct psi5_frame *frame;
	uint32_t max_num_frame;
	void *user_data;
};
 
struct psi5_rx_callback_configs {
	struct psi5_rx_callback_config *serial_frame;
	struct psi5_rx_callback_config *data_frame;
};
```
 
2. RX buffers are allocated by the user to improve throughput:
- Use the API `register_callback` to register the RX callback and allocate a user-defined RX buffer for each callback.
- Changed the callbcak handler:
- Count the number of RX buffer frames and trigger the RX callback when the count reaches the maximum buffer frame limit.
- Reset the count when a RX error occurs or when the count reaches the maximum buffer frame limit.
 
3. Tests and samples have been updated to demonstrate usage with the new changes

2025-05-05 07:02 UTC, congnguyenhuu commented
New update as Dat's suggestion for [PR](https://github.com/zephyrproject-rtos/zephyr/pull/80117)

New updated PSI5 frame type, separate 2 type serial format 4 bit ID and 8 bit ID
```
enum psi5_frame_type {
	PSI5_SERIAL_FRAME_4_BIT_ID,
	PSI5_SERIAL_FRAME_8_BIT_ID,
	PSI5_DATA_FRAME
};
```

New updated PSI5 status, uses the common status RX frame and RX error all type frames
```
enum psi5_status {
	PSI5_TX_DONE,
	PSI5_TX_ERR,
	PSI5_RX_FRAME,
	PSI5_RX_ERR,
};
```

2025-05-09 04:30 UTC, congnguyenhuu commented
I have updated to the v2 changes as [the suggestion for SENT](https://github.com/zephyrproject-rtos/zephyr/pull/80117#discussion_r2076726019).
I removed the `enum psi5_status`.
Tx callback still report the `status` with changed type to `int`, `status = 0` means tx done else tx error.
Rx callback just report the `num_frame`,  An error frame is received (number received frames != expected amount), only report non-error frame.

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on dts/bindings/psi5/psi5-controller.yaml
> +    num-rx-buf:
it seems to be this is vendor specific property?

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on dts/bindings/psi5/psi5-controller.yaml
> +    array-slot-duration-us:
I think it's better to use child binding for the slot, should we consider to use it instead of the array?

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on dts/bindings/psi5/psi5-controller.yaml
> +    tx-mode:
should we use `tx-frame` or the like? to avoid duplicating `frame` within the enum value

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on include/zephyr/drivers/psi5/psi5.h
> +typedef void (*psi5_tx_callback_t)(const struct device *dev, uint8_t channel, int status,
It seems like the definition for a possible value of `status` is missing.

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on drivers/psi5/psi5_nxp_s32.c
> +	if (!(config->channel_mask & BIT(channel))) {
Please move all these condition checks to `psi5_nxp_s32_send`

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on include/zephyr/drivers/psi5/psi5.h
> +__syscall int psi5_send(const struct device *dev, uint8_t channel, const uint64_t data,
Any pre-condition before this API is invoked, like channel shall be configured first in sync mode and sync pulse already generated? Pls mention in API prototype

2025-05-12 03:32 UTC, Dat-NguyenDuy commented on include/zephyr/drivers/psi5/psi5.h
> +static inline int z_impl_psi5_register_callback(const struct device *dev, uint8_t channel,
Any pre-condition before this API is invoked? Pls mention in API prototype.

2025-05-13 02:26 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +    period-sync-pulse-us:
I updated

2025-05-13 02:27 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +    num-rx-buf:
I moved this to vendor S32 binding

2025-05-13 02:28 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +    array-slot-duration-us:
I used a child binding for these config for channel rx slot

2025-05-13 02:29 UTC, congnguyenhuu commented on dts/bindings/psi5/psi5-controller.yaml
> +    array-slot-duration-us:
I updated to use child binding for these config for channel rx slot

2025-05-13 02:30 UTC, congnguyenhuu commented on include/zephyr/drivers/psi5/psi5.h
> +typedef void (*psi5_tx_callback_t)(const struct device *dev, uint8_t channel, int status,
I mentioned the possible values in description

2025-05-13 02:30 UTC, congnguyenhuu commented on drivers/psi5/psi5_nxp_s32.c
> +	if (!(config->channel_mask & BIT(channel))) {
I upadted

2025-05-13 02:30 UTC, congnguyenhuu commented on drivers/psi5/psi5_nxp_s32.c
> +	if (!(config->channel_mask & BIT(channel))) {
I updated

2025-05-13 02:31 UTC, congnguyenhuu commented on include/zephyr/drivers/psi5/psi5.h
> +__syscall int psi5_send(const struct device *dev, uint8_t channel, const uint64_t data,
I mentioned  the pre-condition

2025-05-13 02:31 UTC, congnguyenhuu commented on include/zephyr/drivers/psi5/psi5.h
> +static inline int z_impl_psi5_register_callback(const struct device *dev, uint8_t channel,
I mentioned  the pre-condition

2025-05-23 11:39 UTC, Dat-NguyenDuy approved these changes, later dismissed

2025-05-23 21:47 UTC, manuargue approved these changes, later dismissed

2025-05-26 05:45 UTC, manuargue commented
hi @carlescufi , @henrikbrixandersen . Can we remove the arch review label or is there anything else to discuss? Thanks

2025-05-28 04:27 UTC, manuargue approved these changes, later dismissed

2025-05-29 02:00 UTC, Dat-NguyenDuy approved these changes, later dismissed

2025-06-09 02:41 UTC, manuargue commented
@dleach02 @mmahadevan108 can we merge the hal_nxp pr? it seems that there's no other feedback on this pr. thanks

2025-06-23 17:37 UTC, dleach02 commented on include/zephyr/drivers/psi5/psi5.h
> + * @defgroup psi5_interface PSI5 Interface
Add the following to mark this as experimental:

```
@since 4.2
@version 0.1.0
```

as documented https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html

2025-06-24 01:56 UTC, congnguyenhuu commented on include/zephyr/drivers/psi5/psi5.h
> + * @defgroup psi5_interface PSI5 Interface
I updated this

2025-06-24 02:24 UTC, manuargue approved these changes, later dismissed

2025-06-24 04:08 UTC, Dat-NguyenDuy approved these changes, later dismissed

2025-06-24 16:29 UTC, dleach02 submitted a review, later dismissed

2025-06-24 17:34 UTC, danieldegrasse commented on include/zephyr/drivers/psi5/psi5.h
> +static inline int z_impl_psi5_send(const struct device *dev, uint8_t channel, const uint64_t data,
Would it make more sense to have a separate function to register a TX callback, rather than always passing in the user data and callback pointer? Just a suggestion, not blocking here

2025-06-25 01:47 UTC, congnguyenhuu commented on include/zephyr/drivers/psi5/psi5.h
> +static inline int z_impl_psi5_send(const struct device *dev, uint8_t channel, const uint64_t data,
This API follows the design of the CAN send API, it includes handling for case where the callback and user data pointers are NULL

2025-06-25 15:57 UTC, danieldegrasse submitted a review, later dismissed

2025-06-26 08:46 UTC, congnguyenhuu commented
Addressed review comments from Kartben in [SENT PR ](https://github.com/zephyrproject-rtos/zephyr/pull/80117)

2025-06-27 01:51 UTC, Dat-NguyenDuy submitted a review, later dismissed

2025-06-27 02:23 UTC, manuargue approved these changes, later dismissed

2025-06-27 06:07 UTC, Dat-NguyenDuy submitted a review, later dismissed

2025-06-27 06:51 UTC, manuargue approved these changes, later dismissed

2025-06-27 14:53 UTC, mmahadevan108 submitted a review, later dismissed

2025-06-27 15:21 UTC, Dat-NguyenDuy submitted a review, later dismissed

2025-06-27 15:30 UTC, manuargue submitted a review, later dismissed

2025-06-27 16:39 UTC, danieldegrasse submitted a review, later dismissed

2025-06-27 17:17 UTC, dleach02 submitted a review, later dismissed

2025-06-27 18:31 UTC, dkalowsk commented on include/zephyr/drivers/psi5/psi5.h
> +	};
@congnguyenhuu and @mmahadevan108 and @dleach02 I'm a little concerned on this struct.  The union type is 32-bit value, yet the `serial` struct is only 24-bits in size.  The union will promise a minimum of 32-bits, but when accessing the `serial` struct I believe this is going to end up with some undefined behavior and padding.  Are you sure this is what you want?

It's easily fixed with something like:
```
		struct {
			/** Serial message ID */
			uint8_t id;
			/** Serial message data */
			uint16_t data;
			uint8_t rsvd;
		} serial;
```
Otherwise, the compiler may add the padding where the cacheline is, and it's likely between the `id` and the `data` type.  Additionally because it falls within the `uint32_t` reading beyond `uint16_t data` type (because the name collides with the uint32_t version) won't trigger asan or ubsan for the memory overflow.   Again just checking that you really want to do this.

2025-06-27 20:46 UTC, dleach02 commented on include/zephyr/drivers/psi5/psi5.h
> +	};
This might vary between architectures but this is talking to an on-chip IP block so different architectures is not an issue. But I generally agree though that the sub structure should put the uint8 rsvd field where it explicitly expects it in the byte stream. It could be before the id, between the id & data, or after as you suggested. 

But having said that, as implemented, it works with the underlying hardware so the alignment likely meets the expectations of the HAL functions and the IP on chip. We would like to get this merged within the scope of the merge window because it also involved a HAL update that has been merged which complicates things. 

If we determine there is a bug here, we can patch it after the feature freeze.

2025-06-27 22:00 UTC, dkalowsk commented on include/zephyr/drivers/psi5/psi5.h
> +	};
@dleach02 I understand your concern and desire to get this merged.  And you call out the alternate case I am concerned about.
```diff
		struct {
			/** Serial message ID */
			uint8_t id;
			/** Serial message data */
			uint16_t data;
+			uint8_t rsvd;
		} serial;
```
and
```diff
		struct {
			/** Serial message ID */
			uint8_t id;
+			uint8_t rsvd;
			/** Serial message data */
			uint16_t data;
		} serial;
```
both have different meanings and support/output.  I'm not sure I follow the argument that this is an IP block only so it's correct.  The compiler will still need to provide the data structure implementation to be used.  Running this through CompilerExplorer in a simplified example shows my concern as the second is the case being generated: https://gcc.godbolt.org/z/Prb9b1bjn

2025-06-28 03:57 UTC, manuargue commented on include/zephyr/drivers/psi5/psi5.h
> +	};
`serial` and `data` represent mutually exclusive frame formats, meaning the union is used to hold either a serial frame or a data frame, and they are never meant to be read or written together. So assuming that the consumer follow the intended use, there won't be undefined behaviors due to padding, neither aliasing risks.

That said, I noticed this hasn't been properly documented so it opens possibility of misuse. Additionally, using a tagged union could improve code clarity without sacrificing compactness or requiring to model each frame type as a complete separate struct. For example:
```c
struct psi5_frame {
    enum psi5_frame_type type;
    union {
        struct {
            uint32_t payload;
        } data;  /* access this when .type is PSI5_DATA_FRAME */
        struct {
            uint8_t id;
            uint16_t payload;
        } serial;   /* access this when .type is PSI5_SERIAL_FRAME_4_BIT_ID or PSI5_SERIAL_FRAME_8_BIT_ID */
    };
    uint32_t timestamp;
    uint8_t crc;
    uint8_t slot_number;
};
```

2025-07-01 03:33 UTC, dleach02 commented on include/zephyr/drivers/psi5/psi5.h
> +	};
@dkalowsk sorry for not being clear. What I meant in my comment about it being an IP block is that this is an IP block where we are introducing a new driver framework. Our S32 platform is the only one in Zephyr that will be enabled for this IP block. It isn't generic code that will be compiled into any additional platforms so the exposure is only the NXP S32 and nothing else in Zephyr. 

But having said that, I was trying to get this PR merged before the feature freeze because we had all the approvals already. In anticipation of this, we merged our HAL PR which now causes us sequencing problems (you can chat with Daniel about this because he understands the larger challenges we have). 

I conceded to you that we did indeed need to address this but suggested that we would address this as a bug fix after the feature was merged. You seemed to not respond to this request and instead continued down the path of the problem you identified. Again, I conceded that point.

Now I'm in a situation where I'm forced to request a variance from the release team and/or TSC to have this merged.

2025-07-01 14:29 UTC, rruuaanng requested changes, later dismissed

2025-07-01 14:29 UTC, rruuaanng commented on dts/bindings/psi5/psi5-controller.yaml
> +        - short-31-1s
For string, you should not use implicit.
```suggestion
        - "short-31-1s"
```
(And other.)

2025-07-01 17:15 UTC, dleach02 commented on dts/bindings/psi5/psi5-controller.yaml
> +        - short-31-1s
I pushed an update to address this @rruuaanng

2025-07-01 17:19 UTC, dleach02 approved these changes

2025-07-01 17:27 UTC, dleach02 approved these changes

2025-07-01 18:12 UTC, mmahadevan108 approved these changes

2025-07-01 20:26 UTC, dkalowsk commented on include/zephyr/drivers/psi5/psi5.h
> +	};
Going to mark this as resolved.  Lots of offline discussion`.`

2025-07-01 20:33 UTC, dkalowsk approved these changes

2025-07-01 20:52 UTC, dkalowsk commented on dts/bindings/psi5/psi5-controller.yaml
> +        - short-31-1s
marking complete as it looks done in the PR

2025-07-01 20:53 UTC, merged