dma: nxp: edma: remove the `hal-config-index` property
zephyrproject-rtos/zephyr pull request #79906
Opened 2024-10-16 08:32 UTC by LaurentiuM1234

The HAL configuration binding can be done dynamically based on the IP's address space. The `hal-config-index` property is more tied to software rather than hardware so remove it as an attempt to clean up the binding.

2024-10-16 11:11 UTC, dbaluta approved these changes

2024-10-16 15:18 UTC, decsny approved these changes

2024-10-16 16:25 UTC, iuliana-prodan approved these changes

2024-10-16 16:33 UTC, decsny requested changes
I actually just realized, this might break bisectibility due to removing the property in a commit before the binding change, I think it will cause an EDT error, please just squash those two commits into one (and honestly the whole PR could be a single commit)

2024-10-17 12:12 UTC, LaurentiuM1234 commented
> I actually just realized, this might break bisectibility due to removing the property in a commit before the binding change, I think it will cause an EDT error, please just squash those two commits into one (and honestly the whole PR could be a single commit)

done

2024-10-17 12:41 UTC, dbaluta approved these changes

2024-10-17 15:18 UTC, decsny approved these changes

2024-11-08 20:57 UTC, nashif approved these changes

2024-11-11 14:04 UTC, teburd approved these changes

2024-11-16 20:07 UTC, merged