drivers: devmux: use int instead of ssize_t for select_get()
zephyrproject-rtos/zephyr pull request #79952
Opened 2024-10-16 22:33 UTC by cfriedt

Use int instead of ssize_t for select_get().

This eliminates the unnecessary need for POSIX types

Closes #79898

2024-10-17 00:24 UTC, kartben approved these changes, later dismissed

2024-10-17 01:19 UTC, stephanosio requested changes
Need to update `z_vrfy_devmux_select_get` as well

2024-10-17 15:57 UTC, cfriedt commented
* return `int` from `z_vrfy_devmux_select_get()`
* use `INT_MAX` instead of `INT32_MAX` to match `int` data type in new build assert

2024-10-18 00:02 UTC, stephanosio approved these changes

2024-10-21 11:06 UTC, tomi-font approved these changes

2024-10-21 23:48 UTC, merged