Display: Fix rgb565 / bgr565 interchange issue
zephyrproject-rtos/zephyr pull request #79996
Opened 2024-10-17 13:22 UTC by ngphibang

2024-10-17 13:29 UTC, ngphibang commented
@danieldegrasse : The display format is RGB565, not BGR565. I think there are two mistakes that makes it "works" in practice but make it confused, and that impacts the video capture where you forced RGB565 to BGR565.

- The display overlays should declare RGB565, not BGR565.
- The NXP eLCDIF driver should not force BGR565 to RGB565.

2024-10-17 13:30 UTC, josuah submitted a review, later dismissed

2024-10-17 13:34 UTC, josuah commented
Taking the example of RK055HDMIPI4MA01:
https://www.nxp.com/docs/en/data-sheet/RK055MHD091A0-CTG.pdf
![scrot_20241017_153215_1070x310](https://github.com/user-attachments/assets/392fab10-4fe5-4292-9dca-26f5724c5efb)

I did not test on hardware though.

2024-10-18 19:14 UTC, danieldegrasse requested changes, later dismissed
Zephyr's definition of BGR_565 is unfortunately rather odd- BGR_565 corresponds to what most definitions consider RGB565, and RGB_565 corresponds to RGB_565 byte swapped. 

The only reason I can imagine we did this was that most SPI displays that use 16 bit color would use the RGB_565 format, since the byte swap would result on the data on the SPI MOSI line being in the correct order.

This comment by @zejiang0jason does a good job explaining what is going on here: https://github.com/zephyrproject-rtos/zephyr/pull/71406#discussion_r1602564853

Another way to check this would be to run `samples/drivers/display` with this PR, you'll see that the box we expect to be gray is instead cycling through a set of incorrect colors.

2024-10-18 19:38 UTC, ngphibang commented
@danieldegrasse : I did check with both `samples/drivers/display` and `samples/drivers/video/capture` (where we used video_sw_generator to generate RGB565 color bar patttern) and see it works correctly.

2024-10-18 19:45 UTC, ngphibang commented
I will look through Jason's explaination but honestly, I can't understand where and how Zephyr define a RGB565 to become with BGR565. If it happens, it has to be at least symetrically : RGB565 -> BGR565 and vice versa.

If it's an issue with only NXP's displays, it should not be enforced widely in Zephyr.

2024-10-18 20:15 UTC, ngphibang commented
Oh, just retested. Indeed, with the display sample, the colors are wrong : R -> B, G -> R, B -> G and the grey box cycling through a set of incorrect colors as you said, sorry for that (I am not too familiar with the display sample, so I didn't check carefully).

But for the video capture sample, **the color bar pattern are all correct,** how do we explain that ?

/* Black, Blue, Red, Purple, Green, Aqua, Yellow, White */

![PXL_20241018_200555478](https://github.com/user-attachments/assets/3a2a844f-5de7-4f00-89b0-9ce794e0c6f9)

2024-10-21 08:23 UTC, ngphibang commented
@danieldegrasse The display sample didn't work correctly because it also made a mistake when doing BGR565 for RGB565. After fixing this, it works fine.

I think there exists a long-time, wrong assumption about the "byte swap" that may originally from the display sample and spread out to display drivers, shields, video sample.

Even if there is some thing like "byte swap", "big endian" etc., it is at specific hardwares and should not be taken widely and wrongly in Zephyr like that.

Could you revisit ?

2024-10-21 20:22 UTC, danieldegrasse commented
> @danieldegrasse The display sample didn't work correctly because it also made a mistake when using BGR565 and RGB565 interchangeably. After fixing this, it works fine.
> 
> I think there exists a long-time, wrong assumption about the "byte swap" in Zephyr that may originally come from the display sample and spread out to display drivers, shields, video sample.
> 
> I think even if there is really something like "byte swap", "big/little endian" issue for some specific hardwares, it should be fixed at these hardwares and should not be taken widely and wrongly in Zephyr.
> 
> Could you revisit ?

The problem is that a long time wrong assumption quickly becomes an API contract. The display sample treats `BGR565` format a certain way, and *all* in tree displays have been designed to work with this format. If we want to change the meaning of these format definitions, we need to do the following:
- change all in tree usages
- clearly document this change in the migration guide

I'm not opposed to fixing this- the way that we define display formats has always bothered me. We just need to make sure we minimize churn for downstream display drivers.

2024-10-21 21:03 UTC, ngphibang commented
> The problem is that a long time wrong assumption quickly becomes an API contract. The display sample treats BGR565 format a certain way

RGB565 and BGR56 are two different formats. The display sample just does BGR565 but names it RGB565 (function `fill_buffer_rgb565()`) and vice versa. Anyways, it is just a sample. You mentioned several times the term "API", could you point me to some display APIs (?) or macro or anything else in Zephyr that defines RGB565 as BGR565 ?

2024-10-23 11:31 UTC, josuah commented
Some extra material which could be of interest:
- https://gix.github.io/media-types/
- https://lwn.net/Articles/218798/
- https://ffmpeg.org/doxygen/trunk/pixfmt_8h.html#ac006ecccd336ce7280ef0155568ebfb6
- https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dformat

![scrot_20241023_124529_770x324](https://github.com/user-attachments/assets/d7f96c45-d79c-467b-8787-dd0e740dc8b0)

2024-10-23 11:55 UTC, loicpoulain commented
I'm fully for fixing this. If we're afraid of breaking display API, maybe fix video subsystem for now and do the explicit mitigation into the sample.

2024-10-24 14:28 UTC, ngphibang commented
> https://github.com/zephyrproject-rtos/zephyr/blob/6e653a96f7903fc932575b37f449ceaf4e94c3e7/include/zephyr/drivers/display.h#L39

@danieldegrasse Thanks for the info and your support. The document (comment) just says that byte order is big-endian. It's just the order the bytes are stored. Difference in endianess does not mean RGB565 becoming BGR565 and vice-versa. They are still two disctinct formats. I think the misunderstanding comming from this.

RGB565 in 

- big-endian machine:   RRRRRGGG  GGGBBBBB
- little-endian machine: GGGBBBBB  RRRRRGGG

BGR565 in

- big-endian machine:   BBBBBGGG GGGRRRRR
- little-endian machine: GGGRRRRR BBBBBGGG

@loicpoulain I want to do so but the problem is if we fix the video sample, we also need to fix a display driver (e.g. eLCDIF) to correctly display the video frames. But if we fix that display driver, the display sample need to be fixed too to work correctly on that display.

2024-10-25 16:34 UTC, josuah commented
> RGB565 in
> 
> * big-endian machine:   RRRRRGGG  GGGBBBBB
> * little-endian machine: GGGBBBBB  RRRRRGGG
> 
> BGR565 in
> 
> * big-endian machine:   BBBBBGGG GGGRRRRR
> * little-endian machine: GGGRRRRR BBBBBGGG

It looks like this thread has a similar comments:
- https://github.com/zephyrproject-rtos/zephyr/issues/53642

## LWN article

> for each color field, the lighter-shaded bit is the most significant

![scrot_20241025_175546_779x72](https://github.com/user-attachments/assets/a4d868d6-9851-403f-9174-e2f9c266ebf1)

This is Little Endian, and the most significant bit of each series is on the left, so this is a Verilog/VHDL-friendly representation with most significant bit at the left:

```
little-endian, MSBit first:
7  6  5  4  3  2  1  0  15 14 13 12 11 10 9  8
g  g  g  R  r  r  r  r  B  b  b  b  b  G  g  g

big-endian, MSBit first:
15 14 13 12 11 10 9  8  7  6  5  4  3  2  1  0
B  b  b  b  b  G  g  g  g  g  g  R  r  r  r  r 
```

This makes it look like R last, but if considering that `BIT(0)` is first, then red is first.

Back to an ordering starting from 0 at  the left (least significant bit first):

```
big-endian, LSBit first:
0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
r  r  r  r  R  g  g  g  g  g  G  b  b  b  b  B
```

## Intel libvpl

Looking at Intel interpretation of the Microsoft Media Foundation format definitions:
https://github.com/intel/libvpl/blob/5f6bd8a1e753c8f63a3fd8b36894d6968b808a6d/api/vpl/mfxstructures.h#L140

> 2 bytes per pixel, uint16 in little-endian format, where 0-4 bits are blue, bits 5-10 are green and bits 11-15 are red
> -- https://intel.github.io/libvpl/latest/API_ref/VPL_enums.html#_CPPv417MFX_FOURCC_RGB565

Assuming the most significant bit is at `BIT(0)`, this is the opposite!

## libavformat

Let's look at actual code:

https://github.com/libav/libav/blob/c4642788e83b0858bca449f9b6e71ddb015dfa5d/libavfilter/vsrc_testsrc.c#L403

This takes `r`, `g`, `b` 8-bit integers (stored in an `int` though), and pack them into a big-endian RGB565 integer (big endian otherwise, Green would have to be split:

```c
    case AV_PIX_FMT_RGB565: ((uint16_t*)(dst + y*dst_linesize))[x] = ((b>>3)<<11) | ((g>>2)<<5) | (r>>3); break;
```

Each color gets shifted down to drop some information of each channel R, G or B, and we are left with this:

```c
    case AV_PIX_FMT_RGB565: ((uint16_t*)(dst + y*dst_linesize))[x] = (b<<11) | (g<<5) | r; break;
```

R is not shifted => R least significant bit is at `BIT(0)`.

```
(b<<11) | (g<<5) | r
```

According to libavformat, this is correct, though shown with least significant bit first:

> RGB565 in
>
> * big-endian machine:   `rrrrRggg`  `ggGbbbbB`
> * little-endian machine:   `ggGbbbbB`  `rrrrRggg`

```
15 14 13 12 11 10 9  8  7  6  5  4  3  2  1  0
     ...(b<<11)        ...(g<<5)          ...r
B  b  b  b  b  G  g  g  g  g  g  R  r  r  r  r
```

P.S.: there is the RGB565X which Linux uses as RGB565-BE:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/videodev2.h#n564

2024-10-26 10:29 UTC, josuah commented
After looking for more reference material, it looks like both the LWN example and libav test source disagree with the majority of the implementations. In hope I did not confuse anyone for too long! @ngphibang representation is correct in its most natural MSBit first representation.

Someone searching for a description of the RGB565 format might end-up on this LWN article from 2007, and this could be the source for the confusion for Zephyr and libavformat test source pattern generator.

2024-10-26 15:02 UTC, ngphibang commented
Thank you for citing different sources of references. Yes, I believe strongly that the LWN article is WRONG. Personally, If I need a reference, I am usually based on the kernel document. The kernel document of the latest Linux release (6.11) describes the layout of the **RGB565-LE** the same as I pointed in the above comment:

https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html

2024-12-03 17:58 UTC, danieldegrasse commented
> Thank you for citing different sources of references. Yes, I believe strongly that the LWN article is WRONG. Personally, If I need a reference, I am usually based on the kernel document. The kernel document of the latest Linux release (6.11) describes the layout of the **RGB565-LE** the same as I pointed in the above comment:
> 
> https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html

So is the action here to attempt to make this correction? I think it would be worth doing, but we need to document it clearly (both in release notes and migration guide), and update all display drivers/samples.

In *theory* if we simply swap all usages, things should just work fine. That being said, I think it would be best to test this as much as possible :)

2024-12-04 11:12 UTC, ngphibang commented
Hi @danieldegrasse , thank you for reminding me of this.

I double checked in Zephyr display drivers and shields regarding this RGB565/BGR565 interchange issue. Fortunately, the problem does not span much, only the following drivers and shields are implicated:

- **elcdif** and **dcnano_lcdif** drivers with rk0xxx overlays : fixed in this PR, tested elcdif OK, dcnano_lcdif is not tested, could you help to test this one as I don't have the hardware ?
- st7735r drivers with longan_nano-common.dtsi, mini_stm32h743.dts, mini_stm32h7b0.dts : **not fixed**
- st7796s with rd_rw612_bga.overlay : **not fixed**

The two latter introduced the `config->madctl` and `config->rgb_is_inverted` with all comments about "supporting buggy modules, etc." that make me doubt whether they falls into the same rgb/bgr issue we fixed here or there are really "buggy modules" that need all of these madctl and rgb inverted configs. As you worked on these drivers, could you help to guide how to fix them, e.g. by just set rgb_is_inverted = false or removing all the logics around madctl and rgb reverted boolean ? or even better, could you make commits to fix them :-) ?

Thank you !

2024-12-04 15:43 UTC, danieldegrasse commented
Maybe I'm missing something here, but won't we effectively just need to replace all usages of `PIXEL_FORMAT_RGB_565` with `PIXEL_FORMAT_BGR_565`, and vice versa? I think that should result in no logical changes to the code, as long as we catch all usages

> The two latter introduced the config->madctl and config->rgb_is_inverted with all comments about "supporting buggy modules, etc." that make me doubt whether they falls into the same rgb/bgr issue we fixed here or there are really "buggy modules" that need all of these madctl and rgb inverted configs. As you worked on these drivers, could you help to guide how to fix them, e.g. by just setting rgb_is_inverted = false or by removing all the logics around madctl and rgb reverted boolean ? or even better, could you make commits to fix them :-) ?

For this, the best explanation I know of is by @zejiang0jason here: https://github.com/zephyrproject-rtos/zephyr/pull/71406#discussion_r1602564853

Essentially, MADCTL swaps the color channel itself, but Zephyr swaps the bytes of the color data. I think for these panels we want to send data using RGB565 (using the Linux format naming, not what Zephyr has now) when using 8 bit or 16 bit parallel mode, or RGB565x (big endian mode) when using SPI. MADCTL should not need to change based on the color format Zephyr uses.

Best I can tell, we used RGB565 the way we did in Zephyr because the first displays supported were SPI displays, which do need big endian RGB565 data.

As far as `rgb-is-inverted`, the only place I've used it is as a *very* bad workaround- on the RW612, the LCD controller can swap the RGB data bytes in flight, so we actually want to report the pixel format as RGB565 (again, linux format naming) for SPI mode displays.

2024-12-04 15:53 UTC, ngphibang commented
`Maybe I'm missing something here, but won't we effectively just need to replace all usages of PIXEL_FORMAT_RGB_565 with PIXEL_FORMAT_BGR_565, and vice versa? I think that should result in no logical changes to the code, as long as we catch all usages`.

I don't think we should swap all usages of `PIXEL_FORMAT_RGB_565` and `PIXEL_FORMAT_BGR_565`. Only the four drivers pointed out in my previous comments misused BRG/RGB. For the other drivers, when looking at the code, I see they treat RGB565 as it is and BGR565 as it is, I mean between the pixel format in the overlays and the driver codes.

2024-12-04 15:58 UTC, josuah commented
I have these three boards with me and hopefully a bit of time this week-end:

> st7735r driver with longan_nano-common.dtsi, mini_stm32h743.dts, mini_stm32h7b0.dts : not fixed

2024-12-04 17:29 UTC, ngphibang commented
> Maybe I'm missing something here, but won't we effectively just need to replace all usages of PIXEL_FORMAT_RGB_565 with PIXEL_FORMAT_BGR_565, and vice versa?

Ok, I see your point now. So, apart from the logic fixes in elcdif, dcnano_lcdif drivers as done in the current PR and **maybe** logic fixes in st7735r and st7796s drivers will be done. We also need to swap all usages of `PIXEL_FORMAT_RGB_565` / `PANEL_PIXEL_FORMAT_RGB_565` and `PIXEL_FORMAT_BGR_565` / `PANEL_PIXEL_FORMAT_RGB_565` **assumming that they are all based on the display sample** to test their functionality before getting in upstream.

For example, the following snippet:

```
	ret = nt35510_write_reg_val(dev, NT35510_CMD_COLMOD,
				    data->pixel_format == PIXEL_FORMAT_RGB_565
					    ? NT35510_COLMOD_RGB565
					    : NT35510_COLMOD_RGB888);
```

will be changed to:

```
	ret = nt35510_write_reg_val(dev, NT35510_CMD_COLMOD,
				    data->pixel_format == PIXEL_FORMAT_**BGR**_565
					    ? NT35510_COLMOD_**BGR**565
					    : NT35510_COLMOD_RGB888);
```

right ? So, it's just rather a naming change and will not affect the functionality.

2024-12-05 02:14 UTC, zejiang0jason commented
Hi @ngphibang ,

Thanks for the investigation, my understanding about pixel format is the same as https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html.

When driving display panels though [DBI interface](https://picture.iczhiku.com/resource/eetop/sHkwuKJsUOrfTXMn.pdf), the case is complicated, we need to consider the 8-bit interface, 16-bit interface. The chip MCXN947 supports both 8-bit interface and 16-bit interface, so we had a lot of discussion in #71406

The display IC can be configured for how to use the received data (st77096s MADCTL), that's another thing need to consider.

So in all, there are three parts need to take care: 1. pixel format in MCU memory. 2. pixel format sent on the bus. 3. How the display IC uses the pixel.

> > For this, the best explanation I know of is by @zejiang0jason here: [#71406 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/71406#discussion_r1602564853)
> > Essentially, MADCTL swaps the color channel itself, but Zephyr swaps the bytes of the color data. I think for these panels we want to send data using RGB565 (using the Linux format naming, not what Zephyr has now) when using 8 bit or 16 bit parallel mode, or RGB565x (big endian mode) when using SPI. MADCTL should not need to change based on the color format Zephyr uses.
> > Best I can tell, we used RGB565 the way we did in Zephyr because the first displays supported were SPI displays, which do need big endian RGB565 data.
> > As far as rgb-is-inverted, the only place I've used it is as a very bad workaround- on the RW612, the LCD controller can swap the RGB data bytes in flight, so we actually want to report the pixel format as RGB565 (again, linux format naming) for SPI mode displays.
> 
> This 's complicated for me, especially when having no hardware. But if you cannot make the commits, I will try myself :-)

2024-12-08 20:31 UTC, josuah commented
Removing the `rgb-is-inverted` works after applying this commit:
https://github.com/zephyrproject-rtos/zephyr/commit/82573fd201436f386e3ae2480e22ea78f3291071

`longan_nano`: before/after 82573fd2
![longan_nano_after_change_before_fix](https://github.com/user-attachments/assets/19081392-2e2c-4467-9cca-13723c3a1725)
![longan_nano_after_change_after_fix](https://github.com/user-attachments/assets/79c314a2-045c-4dde-b1b4-972cbf7a591e)

`mini_stm32h743`: before/after 82573fd2
![mini_stm32h743_after_change_before_fix](https://github.com/user-attachments/assets/6043a0b4-dc88-4083-bed9-a2df77ce2964)
![mini_stm32h743_after_change_after_fix](https://github.com/user-attachments/assets/dbe6f705-3b0a-4f1b-a7dd-60e713485d27)

`mini_stm32h7b0`: before/after 82573fd2
![mini_stm32h7b0_after_change_before_fix](https://github.com/user-attachments/assets/fbade0be-dfb2-49d3-9112-41d7af655c58)
![mini_stm32h7b0_after_change_after_fix](https://github.com/user-attachments/assets/18c9de9f-5331-42a6-b9f6-6da57f4f583a)

2024-12-10 00:27 UTC, danieldegrasse commented
> > Maybe I'm missing something here, but won't we effectively just need to replace all usages of PIXEL_FORMAT_RGB_565 with PIXEL_FORMAT_BGR_565, and vice versa?
> 
> Ok, I see your point now. So, apart from the logic fixes in elcdif, dcnano_lcdif drivers as done in the current PR and **maybe** logic fixes in st7735r and st7796s drivers will be done. We also need to swap all usages of `PIXEL_FORMAT_RGB_565` / `PANEL_PIXEL_FORMAT_RGB_565` and `PIXEL_FORMAT_BGR_565` / `PANEL_PIXEL_FORMAT_BGR_565` **assumming that they are all based on the display sample** to test their functionality before getting in upstream.
> 
> For example, the following snippet:
> 
> ```
> 	ret = nt35510_write_reg_val(dev, NT35510_CMD_COLMOD,
> 				    data->pixel_format == PIXEL_FORMAT_RGB_565
> 					    ? NT35510_COLMOD_RGB565
> 					    : NT35510_COLMOD_RGB888);
> ```
> 
> will be changed to:
> 
> ```
> 	ret = nt35510_write_reg_val(dev, NT35510_CMD_COLMOD,
> 				    data->pixel_format == PIXEL_FORMAT_**BGR**_565
> 					    ? NT35510_COLMOD_**BGR**565
> 					    : NT35510_COLMOD_RGB888);
> ```
> 
> right ? So, it's just rather a naming change and will not affect the functionality.
> 
> **But the problem is except the rk0xx overlays that uses `PANEL_PIXEL_FORMAT_BGR_565`, all others shields / overlay uses `PANEL_PIXEL_FORMAT_RGB_565`, so per my observation, it seems the interchange issue only happens to certains drivers / shields. Others are already correct.** This can be checked by looking at display datasheets to see whether they supports RGB_565 or BGR_565 by default.

But these shields that use `PANEL_PIXEL_FORMAT_RGB_565` need to be changed as well- in the current definition Zephyr uses, RGB_565 is byte swapped versus the standard definition Linux uses. So for consistency, those displays (which are mostly SPI based, I believe), also need to be changed to now use `PANEL_PIXEL_FORMAT_BGR_565`, since that is what we now use to define byte swapped RGB565 data (or we can define something like `PANEL_PIXEL_FORMAT_RGB_565x` if we'd prefer to follow what Linux does)

2025-02-22 16:35 UTC, josuah reviewed
LGTM! :ballot_box_with_check: 

It was tested on a few devices to check it works.
The change done on the tested devices are the same as the other devices at the source level.

May that be enough confidence that it will improve the situation of displays?

2025-02-22 16:37 UTC, kartben commented
Should this be re-opened then?

2025-02-22 16:40 UTC, josuah commented
If possible yes, that could help kick the engine.

2025-02-22 16:45 UTC, josuah submitted a review, later dismissed

2025-02-24 12:10 UTC, ngphibang commented
I will complete the change. Sorry, I am a bit tight up at this moment ...

2025-02-24 16:42 UTC, danieldegrasse commented
I think this is a worthwhile change, but I want to make sure we understand how much needs to be swapped here. Essentially if I'm following the goal of the change, all in tree usages of `PIXEL_FORMAT_RGB_565` need to be replaced with `PIXEL_FORMAT_BGR_565`, and vice versa, right? This applies to samples, devicetrees, and drivers.

We also **need** to add some form of entry to the migration guide about this- this change will affect a lot of downstream boards and drivers.

Provided we make all those changes, I'm ok with this. Just want to be clear about what is required here. Feel free to correct me if you think we can make the scope of this change more narrow and still resolve the issue though.

2025-06-03 20:51 UTC, avolmat-st commented
> I think this is a worthwhile change, but I want to make sure we understand how much needs to be swapped here. Essentially if I'm following the goal of the change, all in tree usages of `PIXEL_FORMAT_RGB_565` need to be replaced with `PIXEL_FORMAT_BGR_565`, and vice versa, right? This applies to samples, devicetrees, and drivers.
> 
> We also **need** to add some form of entry to the migration guide about this- this change will affect a lot of downstream boards and drivers.
> 
> Provided we make all those changes, I'm ok with this. Just want to be clear about what is required here. Feel free to correct me if you think we can make the scope of this change more narrow and still resolve the issue though.

Not all drivers at least since as far as the STM32 LTDC is concerned, this is already correct I think. In fact within STM32 LTDC, RGB_565 is advertised and this is indeed correctly already RGB 565, this should not be changed to BGR 565 for example.

However I agree that at least video capture test sample modification shown here should be kept.

2025-06-04 07:48 UTC, ngphibang commented
@avolmat-st Thank you for your feedback ! I also thought that we should not systematically replace `PIXEL_FORMAT_RGB_565`  by `PIXEL_FORMAT_BGR_565`, and vice versa.

BTW, when you said the STM32 LTDC is already correct, does it mean that the display sample running on it is not correct (e.g. grey box cycling through a set of incorrect colors) because the display sample swap these two pixel formats.

2025-06-09 15:52 UTC, avolmat-st commented
> BTW, when you said the STM32 LTDC is already correct, does it mean that the display sample running on it is not correct (e.g. grey box cycling through a set of incorrect colors) because the display sample swap these two pixel formats.

Having read more carefully the discussion, sorry I misunderstood. Anyway, I confirm that NOW, with this PR applied the colors are correct when running the display sample on the stm32n6. So PR looks great to me.

Maybe @ngphibang you can rebase it on top of HEAD so that it can be reviewed again and merged ?

2025-06-17 15:09 UTC, erwango commented
@ngphibang Please rebase to fix CI issue

2025-06-18 01:21 UTC, ngphibang commented
Rebased on top of HEAD.

@danieldegrasse: As pointed out by @avolmat-st , not all display drivers need to be systematically replaced RGB565 by BGR565 and vice versa. This matched with my previous understanding when looing at display drivers.

So, I propose we fix only the two samples and the NXP's elcdif driver where we know exactly that it's incorrect and merge the PR.
Then, if there are display drivers to fix, we can do it in upcomming PRs.

I think this is a safer approach than automatically fix all display driver now because with this, the displays still be functional in their current state with current downstream applications (the only risk is maybe some will not works anymore with the display sample, but it's not a big deal, we will fix when detect them).

Is it ok for you ?

2025-06-18 01:28 UTC, ngphibang commented
Added migration guide

2025-06-18 10:03 UTC, josuah approved these changes, later dismissed
The same commits were tested on these 3 boards: https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2526368054

2025-06-18 11:55 UTC, avolmat-st submitted a review, later dismissed
Tested ok on STM32MP13 for LTDC.

2025-06-19 12:00 UTC, erwango commented
@danieldegrasse PTAL

2025-06-26 12:42 UTC, danieldegrasse commented
Sorry for the delay getting back to this.

> Having read more carefully the discussion, sorry I misunderstood. Anyway, I confirm that NOW, with this PR applied the colors are correct when running the display sample on the stm32n6. So PR looks great to me.

@avolmat-st so testing the display sample with this PR versus with `main`, you see the exact same behavior? IE in both cases the grey box cycles gradually to a black one, than back to white?

I'm confused because based on my understanding of this change that shouldn't occur- either a display:
- works prior to this PR, and will have the color format swapped by this PR. This includes the displays checked in https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2526368054
- had color swap issues with the display sample prior to this PR, and now does not. I wonder if this might be what is going on with the LTDC? The color swap is somewhat less obvious with the display sample unfortunately
- works prior to this PR, is updated by this PR, and will continue working. This applies to all the NXP displays modified in this PR

> So, I propose we fix only the two samples and the NXP's elcdif driver where we know exactly that it's incorrect and merge the PR.
Then, if there are display drivers to fix, we can do it in upcomming PRs.
>
> ? I think this is a safer approach than automatically fix all display driver now because with this, the displays still be functional in their current state with current downstream applications (the only risk is maybe some will not works anymore with the display sample, but it's not a big deal, we will fix when detect them).
>
> Is it ok for you ?

I might be missing something here, but isn't the fix going to be *required* on essentially every display? If so, why not just change BGR->RGB in bulk for displays in the tree- that should keep them all working, and is what I would recommend in the migration guide. LVGL treats RGB and BGR as the same (and controls color swap with `CONFIG_LV_COLOR_16_SWAP`), so I don't think LVGL ports need a change to handle this.

To be clear here I do want this change- I just want to make sure we migrate displays correctly, rather than breaking all existing displays we can't test and waiting for users to figure out they are broken

2025-06-26 12:47 UTC, avolmat-st commented
> Sorry for the delay getting back to this.
> 
> > Having read more carefully the discussion, sorry I misunderstood. Anyway, I confirm that NOW, with this PR applied the colors are correct when running the display sample on the stm32n6. So PR looks great to me.
> 
> @avolmat-st so testing the display sample with this PR versus with `main`, you see the exact same behavior? IE in both cases the grey box cycles gradually to a black one, than back to white?

@danieldegrasse no, sorry if my message wasn't clear. With this PR applied, the color shown by the display sample are correct (grey box cycles gradually to a black one ...) while, same things done on the main branch will show bad colors.

2025-06-26 12:49 UTC, danieldegrasse commented
> @danieldegrasse no, sorry if my message wasn't clear. With this PR applied, the color shown by the display sample are correct (grey box cycles gradually to a black one ...) while, same things done on the main branch will show bad colors.

No worries, thanks for the clarification- glad I'm understanding this correctly :) So outside of this PR, the LTDC likely needs a change to the reported color format to work with the display sample

2025-06-26 14:01 UTC, ngphibang commented
> I might be missing something here, but isn't the fix going to be required on essentially every display ?

@danieldegrasse : I don't think so. Only displays that made the mistake like the elcdif need to be fixed, i.e. elcdif supports RGB565 but expose BGR565 (in DT) then twist to RGB565 inside the driver (wrong + wrong = true).

_**Most**_ of displays I see is they use and expose RGB565 as RGB565 so do not need to be fixed.

> LVGL treats RGB and BGR as the same (and controls color swap with CONFIG_LV_COLOR_16_SWAP), so I don't think LVGL ports need a change to handle this.

That's a good news. So, we don't need to worry about LVGL then

Anyways, I think the risk of "not fix now" (for displays we don't detect if it should be fixed or not) is less than "fix every display now" then realize that we "fixed" something that shouldn't be ?

2025-06-26 18:28 UTC, avolmat-st commented
> > @danieldegrasse no, sorry if my message wasn't clear. With this PR applied, the color shown by the display sample are correct (grey box cycles gradually to a black one ...) while, same things done on the main branch will show bad colors.
> 
> No worries, thanks for the clarification- glad I'm understanding this correctly :) So outside of this PR, the LTDC likely needs a change to the reported color format to work with the display sample

Hum, not sure I get the point here. The LTDC works with RGB and if data given to him are indeed RGB (and not BGR) then this is correctly displayed. Maybe I missed one part in the discussion ?
My understanding is that, (for parts impacting STM32 / LTDC):

on capture sample app: avoid requesting BGR on the display side when the video/camera side is saying RGB
(anyway, the LTDC does not expose BGR format hence locally recently I am always doing this change in order to make the capture sample app working)

on the display sample app: the LTDC is only reporting RGB format (not BGR) and until now the data being written into memory by the sample app was actually BGR formated data, hence leading to bad colors. Now that the display sample app is filling the memory with data in the RGB order, color are properly displayed.

2025-06-26 18:45 UTC, ngphibang commented
@avolmat-st : Our main point of discussion (Daniel's point) is the display sample serves as the "standard tool" to validate any in-tree displays. So, now if we say the display sample interchanged RGB565 and BGR565 and fix it, we need to replace all the RGB565 by BGR565 and vice versa in all displays (DT and driver).

So his question was that if LTDC was an exception, e.g. it didn't work with the display sample (on main branch) right at the beginning or there was some hidden change behind the scene that make it working. My understanding through your comment is the former. That's why I think not all the in-tree displays was validated with the display sample.

2025-06-26 18:58 UTC, avolmat-st commented
> @avolmat-st : Our main point of discussion (Daniel's point) is the display sample serves as the "standard tool" to validate any in-tree displays. So, now if we say the display sample interchanged RGB565 and BGR565 and fix it, we need to replace all the RGB565 by BGR565 and vice versa in all displays (DT and driver).
> 
> So his question was that "is LTDC an exception ?", i.e. it didn't work with the display sample (on main branch) right at the beginning or there was some hidden change behind the scene that make it working. My understanding through your comment is the former. That's why I think not all the in-tree displays was validated with the display sample.

Thanks @ngphibang for the clarification. Yes I confirm that it didn't work on main branch (colors were not correct). Actually as far as I am concerned, I must say that I didn't notice that it wasn't correct. That's only later on, when I saw this PR that I understood, that displayed color were not the expected one.

2025-06-26 19:07 UTC, ngphibang commented
> Actually as far as I am concerned, I must say that I didn't notice that it wasn't correct.

Me too. And I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.

So, that's why I think there are displays which are already correct and we should not "fix" them.

My point is we should fix this problem but should not fix blindly / systematically all the displays which is dangerous. We can identify them gradually and fix them in upcomming PRs if detected.

2025-06-27 18:37 UTC, danieldegrasse commented
> > Actually as far as I am concerned, I must say that I didn't notice that it wasn't correct.
> 
> Me too. And I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.
> 
> So, that's why I think there are displays which are already correct and we should not "fix" them.
> 
> My point is we should fix this problem but should not fix blindly / systematically all the displays which is dangerous. We can identify them gradually and fix them in upcomming PRs if detected.

So this is where I fundamentally disagree- what this PR is doing is swapping the meaning of two constants in Zephyr. From my POV that means we should swap all usages of those constants in tree, so if a display is broken it stays broken and if a display is working it continues to work. Why would we *knowingly* create breakage in displays (which this PR will do), versus keeping things working as they are.

2025-06-27 18:41 UTC, danieldegrasse requested changes, later dismissed
I'm sorry but my change request still stands. I do not think the right way to make this change is to "swap things and find out what breaks". We know what will break, we are swapping the meaning of two constants. Swap the usages of the constants in tree and things won't break.

I'm not a maintainer here (nor is there a display maintainer)- I would like to hear the opinion of another collaborator in displays on this change though. @VynDragon, @jfischer-no, @JarmouniA, any thoughts? If others disagree with me I'll happily remove my block- maybe there is something I'm missing here

2025-06-27 18:57 UTC, ngphibang commented
> We know what will break, we are swapping the meaning of two constants. Swap the usages of the constants in tree and things won't break.

Sorry but I disagree here too. In fact, we don't know which will break unless we test all the displays (which will be difficult).
This fix is actually not a swap of the usage of two constant. We only see that the video sample, the display sample and the NXP's elcdif driver made the mistake so we fixed it.

The assumption that all the in-tree displays are based on the display sample for validation and needs a swap is strong but I am sure that not all of them (LTDC is an example and some other boards and display drivers I see still consider RGB565 is RGB565 and BGR565 is BGR565 so no reason to swap them).

2025-06-27 20:07 UTC, josuah commented
@danieldegrasse thank you for the prompt reply. I did not intend to bypass your comment and it seems I misinterpreted your latest message as for confirmation as it was intermediate step only.

Should the milestone be moved to 4.3.0 or is this considered a bugfix that can land after the feature-freeze?

2025-06-27 20:11 UTC, danieldegrasse commented
> @danieldegrasse thank you for the prompt reply. I did not intend to bypass your comment and it seems I misinterpreted your latest message as for confirmation as it was intermediate step only.
> 
> Should the milestone be moved to 4.3.0 or is this considered a bugfix that can land after the feature-freeze?

No worries! Personally I'd rather see it go in on 4.3.0- I know the naming of the constants is confusing as is (and I'd like to see them changed) but I don't see the naming as a bug

2025-06-27 20:13 UTC, dleach02 commented
> > > Actually as far as I am concerned, I must say that I didn't notice that it wasn't correct.
> > 
> > 
> > Me too. And I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.
> > So, that's why I think there are displays which are already correct and we should not "fix" them.
> > My point is we should fix this problem but should not fix blindly / systematically all the displays which is dangerous. We can identify them gradually and fix them in upcomming PRs if detected.
> 
> So this is where I fundamentally disagree- what this PR is doing is swapping the meaning of two constants in Zephyr. From my POV that means we should swap all usages of those constants in tree, so if a display is broken it stays broken and if a display is working it continues to work. Why would we _knowingly_ create breakage in displays (which this PR will do), versus keeping things working as they are.

@danieldegrasse what is the definition of "working/not working"? 

I think the root question is whether there is agreement here on if these defines are correct or not? 

If they are incorrect then we should fix them instead of maintaining an incorrect implementation/usage. If that results in other displays behaving incorrectly they can be fixed.

2025-06-27 20:21 UTC, danieldegrasse commented
> > > > Actually as far as I am concerned, I must say that I didn't notice that it wasn't correct.
> > > 
> > > 
> > > Me too. And I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.
> > > So, that's why I think there are displays which are already correct and we should not "fix" them.
> > > My point is we should fix this problem but should not fix blindly / systematically all the displays which is dangerous. We can identify them gradually and fix them in upcomming PRs if detected.
> > 
> > 
> > So this is where I fundamentally disagree- what this PR is doing is swapping the meaning of two constants in Zephyr. From my POV that means we should swap all usages of those constants in tree, so if a display is broken it stays broken and if a display is working it continues to work. Why would we _knowingly_ create breakage in displays (which this PR will do), versus keeping things working as they are.
> 
> @danieldegrasse what is the definition of "working/not working"?
> 
> I think the root question is whether there is agreement here on if these defines are correct or not?
> 
> If they are incorrect then we should fix them instead of maintaining an incorrect implementation/usage. If that results in other displays behaving incorrectly they can be fixed.

The defines are not in alignment with what other projects use- so IMO yes, they are incorrect. However they do *work*, they just should be changed. Personally I feel this is somewhat similar to a documentation issue, IE something that isn't breaking anyone's use of Zephyr right now. My concern with making the change close to release is that it is difficult to test all displays (as @ngphibang pointed out). IMO the way to make this change is to swap all usages in tree and do it earlier in the release cycle, so that users have some time to notice any issues we might not have anticipated. Swapping all usages (IMO) is lower risk than making the change knowing it will break some displays, but it still isn't zero risk

2025-06-27 20:56 UTC, dleach02 commented
Well the PR has been posted since October of last year ;-).

But if you are okay, maybe we schedule this to be merged right after the v4.2 release. Then that would allow the next release cycle for users to identify and address any additional displays that need to be changed.

2025-06-27 21:33 UTC, ngphibang commented
>  However they do _work_, they just should be changed. Personally I feel this is somewhat similar to a documentation issue, IE something that isn't breaking anyone's use of Zephyr right now.

When we say "it works", it mean to work only in the world of the display sample. It's a burden to take care of whenver we do RGB565 or BGR565 outside of the display sample or when we go from and to the display domain, e.g. when developing a new multimedia library.

I am okay to let it be till 4.3, or more but I think I will not blindly swap RGB formats for all the in-tree displays without testing it or at least someone helps to point out that it works / breaks on a display.

2025-06-27 22:50 UTC, JarmouniA commented
> I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.

> So, that's why I think there are displays which are already correct and we should not "fix" them.

@ngphibang I agree, that was my experience when testing many STM32 boards with displays. To me, what is in this PR rn is the correct way forward, but it should be merged in the next release to leave room for potential fixes and more testing.

> So this is where I fundamentally disagree- what this PR is doing is swapping the meaning of two constants in Zephyr. From my POV that means we should swap all usages of those constants in tree, so if a display is broken it stays broken and if a display is working it continues to work. 

@danieldegrasse I disagree, in my experience when I was testing displays with the sample, I was not paying attention to colors, I noticed the weird flicking of the grey box, but ignored it (similar to what @avolmat-st described), LVGL samples were the way I would actually validate colors and other things...

2025-06-27 23:04 UTC, danieldegrasse commented
> > I think there are people who also made that mistake. When they validated their display with this sample, they see R, G, B colors, see it changes colors and thought that is fine, but not.
> 
> > So, that's why I think there are displays which are already correct and we should not "fix" them.
> 
> @ngphibang I agree, that was my experience when testing many STM32 boards with displays. To me, what is in this PR rn is the correct way forward, but it should be merged in the next release to leave room for potential fixes and more testing.
> 
> > So this is where I fundamentally disagree- what this PR is doing is swapping the meaning of two constants in Zephyr. From my POV that means we should swap all usages of those constants in tree, so if a display is broken it stays broken and if a display is working it continues to work.
> 
> @danieldegrasse I disagree, in my experience when I was testing displays with the sample, I was not paying attention to colors, I noticed the weird flicking of the grey box, but ignored it (similar to what @avolmat-st described), LVGL samples were the way I would actually validate colors and other things...

Hmm ok- thank you for the alternate perspective here. Maybe more displays than I think have this issue. Perhaps when we merge this PR we add a note to the display sample stating what an incorrect color definition looks like?

I'm going to clear my block then, but I agree- I would really rather hold this until the next release and correct displays over a release cycle

2025-06-29 15:01 UTC, VynDragon commented
i dont think it should be swapped in the sample... Higher chances displays match the current sample correctly than they dont.

2025-06-30 13:48 UTC, erwango commented
@danieldegrasse Is there a possibility that this PR is merged for v4.2.0.RC2 ?
Reason for asking is because STM32N6 capture sample is currently broken and there is no easy way to fix it other than this PR.
Also consensus is that this PR is fixing what is a real issue that should be fixed, so why not starting right now ?
(I know there might be out of tree users, but this can be documented in migration doc)

2025-07-01 14:37 UTC, danieldegrasse commented
> @danieldegrasse Is there a possibility that this PR is merged for v4.2.0.RC2 ? Reason for asking is because STM32N6 capture sample is currently broken and there is no easy way to fix it other than this PR. Also consensus is that this PR is fixing what is a real issue that should be fixed, so why not starting right now ? (I know there might be out of tree users, but this can be documented in migration doc)

Wouldn't it be possible to fix the STM32 display driver by aligning it with the (backwards) way that Zephyr currently reports display formats? IE something like the following change:

```diff
diff --git a/drivers/display/display_stm32_ltdc.c b/drivers/display/display_stm32_ltdc.c
index b34975f8c58..cdd0c63bae3 100644
--- a/drivers/display/display_stm32_ltdc.c
+++ b/drivers/display/display_stm32_ltdc.c
@@ -55,7 +55,7 @@ LOG_MODULE_REGISTER(display_stm32_ltdc, CONFIG_DISPLAY_LOG_LEVEL);
 #elif CONFIG_STM32_LTDC_RGB565
 #define STM32_LTDC_INIT_PIXEL_SIZE     2u
 #define STM32_LTDC_INIT_PIXEL_FORMAT   LTDC_PIXEL_FORMAT_RGB565
-#define DISPLAY_INIT_PIXEL_FORMAT      PIXEL_FORMAT_RGB_565
+#define DISPLAY_INIT_PIXEL_FORMAT      PIXEL_FORMAT_BGR_565
 #else
 #error "Invalid LTDC pixel format chosen"
 #endif
@@ -110,9 +110,9 @@ static int stm32_ltdc_set_pixel_format(const struct device *dev,
        struct display_stm32_ltdc_data *data = dev->data;

        switch (format) {
-       case PIXEL_FORMAT_RGB_565:
+       case PIXEL_FORMAT_BGR_565:
                err = HAL_LTDC_SetPixelFormat(&data->hltdc, LTDC_PIXEL_FORMAT_RGB565, 0);
-               data->current_pixel_format = PIXEL_FORMAT_RGB_565;
+               data->current_pixel_format = PIXEL_FORMAT_BGR_565;
                data->current_pixel_size = 2u;
                break;
        case PIXEL_FORMAT_RGB_888:
@@ -158,7 +158,7 @@ static void stm32_ltdc_get_capabilities(const struct device *dev,
                                     data->hltdc.LayerCfg[0].WindowY0;
        capabilities->supported_pixel_formats = PIXEL_FORMAT_ARGB_8888 |
                                        PIXEL_FORMAT_RGB_888 |
-                                       PIXEL_FORMAT_RGB_565;
+                                       PIXEL_FORMAT_BGR_565;
        capabilities->screen_info = 0;
```

2025-07-01 16:34 UTC, VynDragon commented
I went and did some check, current 'RGB565' order is good if we talk about data order, for example, for ssd1351, which behaves correctly with the current code (I checked today and did check with the sample README back when i wrote that driver):
![image](https://github.com/user-attachments/assets/504a0b90-1462-4b9f-a129-74c3c51e4708)
but in memory, it is the opposite: 
![image](https://github.com/user-attachments/assets/2d20a6e0-c1a6-4a40-b75c-73ebc5c52156)

What I mean is that which is the right way depends on which PoV is taken, and probably varies between devices.

In the end it can be rightfully assumed that *most* drivers match the sample as it has been, and there is no reason to swap all of them, but rather the offending drivers should be fixed to be the right way relative to what is right now, as a 'proper' way doesnt really exists.

2025-07-01 18:09 UTC, ngphibang commented
Hi @VynDragon,

Thank you for the double check of the ssd1351 display. I couldn't find an in-tree device tree that uses this display so I suppose you tested on an out-of-tree board ? Maybe there is a chance that the RGB color is already swapped, i.e. `reg-map's A[2]` property is set to 1 ? 
https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/display/solomon%2Cssd1351.yaml#L69

But I believe this is not the case. So, could you help to fill the `ssd1351` row with status "need to be fixed" in the table of the issue : https://github.com/zephyrproject-rtos/zephyr/issues/92343 ?

Up to now, we know that there is at least 1 display "need to be fixed / swapped" after the PR merged (`ssd1351`), but without this PR, at least 3 displays need to be "worked around" (LTDC, eLCDIF, eLCDIF nano).

So, as you also pointed out, there is no painless solution. The benefit of this PR is that we will have a consistent defines for RGB565 / BGR565 across Zephyr's subsystems, e.g. video, display, and which is also compliant with [most of other projects](https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2438279540), especially the [Linux kernel](https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2439613515)

https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html

PS: 

> ... and there is no reason to swap all of them

Consensus is that we do not swap all of them. We will fix / swap displays / boards that need to be, like the ssd1351.

2025-07-01 19:33 UTC, VynDragon commented
> Hi @VynDragon,
> 
> Thank you for the double check of the ssd1351 display. I couldn't find an in-tree device tree that uses this display so I suppose you tested on an out-of-tree board ? Maybe there is a chance that the RGB color is already swapped, i.e. `reg-map's A[2]` property is set to 1 ? https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/display/solomon%2Cssd1351.yaml#L69
> 
> But I believe this is not the case. So, could you help to fill the `ssd1351` row with status "need to be fixed" in the table of the issue : #92343 ?
> 
> Up to now, we know that there is at least 1 display "need to be fixed / swapped" after the PR merged (`ssd1351`), but without this PR, at least 3 displays need to be "worked around" (LTDC, eLCDIF, eLCDIF nano).
> 
> So, as you also pointed out, there is no painless solution. The benefit of this PR is that we will have a consistent defines for RGB565 / BGR565 across Zephyr's subsystems, e.g. video, display, and which is also compliant with [most of other projects](https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2438279540), especially the [Linux kernel](https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2439613515)
> 
> https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html
> 
> PS:
> 
> > ... and there is no reason to swap all of them
> 
> Consensus is that we do not swap all of them. We will fix / swap displays / boards that need to be, like the ssd1351.

At best i can tell zephyr 'RGB565' is the same as linux RGB565 
![image](https://github.com/user-attachments/assets/989d70e4-a9e5-45a0-a8ae-fc83e0b52dcd)
![image](https://github.com/user-attachments/assets/81d77e5b-0043-4f8d-b4aa-834f1c642756)
Which corresponds to the input order of SSD1351 as well, which is RGB565, first byte is rrrrrggg, second byte is ggbbbbb.

In fact it all seems to agree with the zephyr RGB565....

2025-07-01 19:42 UTC, ngphibang commented
> At best i can tell zephyr 'RGB565' is the same as linux RGB565

Well, what you call "zephyr" is actually the display sample, which is "fixed" by the PR.

In the very first comments and in the commits, it is shown that a SW generator, a camera sensor that outputs RGB565 display wrong colors on a eLCDIF display that supports RGB565.

2025-07-01 19:43 UTC, VynDragon commented
Linux at https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html mentions little-endian, are you sure it is not because that is swapped around between the camera and the display?

EG this: https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2435455251 works in the opposite way, EG, on linux:

RGB565 in

    big-endian machine: GGGBBBBB RRRRRGGG 
    little-endian machine: RRRRRGGG GGGBBBBB 

BGR565 in

    big-endian machine: GGGRRRRR BBBBBGGG 
    little-endian machine: BBBBBGGG GGGRRRRR 

Which is yet different??

2025-07-01 19:45 UTC, VynDragon commented
> Well, what you call "zephyr" is actually the display sample, which is "fixed" by the PR.

Degrass said the samples defines what it is for zephyr.

2025-07-01 19:50 UTC, ngphibang commented
> Linux at https://www.kernel.org/doc/html/v6.11/userspace-api/media/v4l/pixfmt-rgb.html mentions little-endian, are you sure it is not because that is swapped around between the camera and the display?
> 
> EG this: https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2435455251 works in the opposite way, EG, on linux:
> 
> RGB565 in
> 
> big-endian machine: GGGBBBBB RRRRRGGG 
> little-endian machine: RRRRRGGG GGGBBBBB 
> BGR565 in
> 
> big-endian machine: GGGRRRRR BBBBBGGG 
> little-endian machine: BBBBBGGG GGGRRRRR

This is opposite with what we found and comments above https://github.com/zephyrproject-rtos/zephyr/pull/79996#issuecomment-2435455251

> Degrass said the samples defines what it is for zephyr.

About "the display sample" defines what it is for Zephyr, I have no idea.

2025-07-01 19:55 UTC, VynDragon commented
NVM about this discussion, it is inverted in LVGL in practice, so I dont understand why, but you are right. Maybe one thing of note is that I need to both invert RGB565 order *AND* use CONFIG_LV_COLOR_16_SWAP to get the right output with LVGL.

2025-07-01 20:04 UTC, avolmat-st commented
> > @danieldegrasse Is there a possibility that this PR is merged for v4.2.0.RC2 ? Reason for asking is because STM32N6 capture sample is currently broken and there is no easy way to fix it other than this PR. Also consensus is that this PR is fixing what is a real issue that should be fixed, so why not starting right now ? (I know there might be out of tree users, but this can be documented in migration doc)
> 
> Wouldn't it be possible to fix the STM32 display driver by aligning it with the (backwards) way that Zephyr currently reports display formats? IE something like the following change:
> 
> ```diff
> diff --git a/drivers/display/display_stm32_ltdc.c b/drivers/display/display_stm32_ltdc.c
> index b34975f8c58..cdd0c63bae3 100644
> --- a/drivers/display/display_stm32_ltdc.c
> +++ b/drivers/display/display_stm32_ltdc.c
> @@ -55,7 +55,7 @@ LOG_MODULE_REGISTER(display_stm32_ltdc, CONFIG_DISPLAY_LOG_LEVEL);
>  #elif CONFIG_STM32_LTDC_RGB565
>  #define STM32_LTDC_INIT_PIXEL_SIZE     2u
>  #define STM32_LTDC_INIT_PIXEL_FORMAT   LTDC_PIXEL_FORMAT_RGB565
> -#define DISPLAY_INIT_PIXEL_FORMAT      PIXEL_FORMAT_RGB_565
> +#define DISPLAY_INIT_PIXEL_FORMAT      PIXEL_FORMAT_BGR_565
>  #else
>  #error "Invalid LTDC pixel format chosen"
>  #endif
> @@ -110,9 +110,9 @@ static int stm32_ltdc_set_pixel_format(const struct device *dev,
>         struct display_stm32_ltdc_data *data = dev->data;
> 
>         switch (format) {
> -       case PIXEL_FORMAT_RGB_565:
> +       case PIXEL_FORMAT_BGR_565:
>                 err = HAL_LTDC_SetPixelFormat(&data->hltdc, LTDC_PIXEL_FORMAT_RGB565, 0);
> -               data->current_pixel_format = PIXEL_FORMAT_RGB_565;
> +               data->current_pixel_format = PIXEL_FORMAT_BGR_565;
>                 data->current_pixel_size = 2u;
>                 break;
>         case PIXEL_FORMAT_RGB_888:
> @@ -158,7 +158,7 @@ static void stm32_ltdc_get_capabilities(const struct device *dev,
>                                      data->hltdc.LayerCfg[0].WindowY0;
>         capabilities->supported_pixel_formats = PIXEL_FORMAT_ARGB_8888 |
>                                         PIXEL_FORMAT_RGB_888 |
> -                                       PIXEL_FORMAT_RGB_565;
> +                                       PIXEL_FORMAT_BGR_565;
>         capabilities->screen_info = 0;
> ```
> 
> This aligns with the way the NXP LCDIF currently reports display pixel formats, and I believe that display works with the video sample (although I lack hardware to test)

Hi @danieldegrasse,

yes I confirm that with such modification done the LTDC driver, this allows to make the video sample work with the LTDC as well as  the display sample giving the right colors when displayed via the LTDC.
Waiting for the discussion about what should be RGB_565 / BGR_565 PIXEL_FORMAT in Zephyr and in order to have right display colors and video sample working on v4.2.0, is it ok to push such patch and get it merged into v4.2.0 ?
After that, if decision is taken to change formats after v4.2.0, we can change again this past v4.2.0 to align it with new definitions.
For information, on STM32 LTDC side, LVGL samples seems to be fine, with right colors (as far as I've seen with the various demo code I tried).

2025-07-01 20:08 UTC, danieldegrasse commented
> yes I confirm that with such modification done the LTDC driver, this allows to make the video sample work with the LTDC as well as the display sample giving the right colors when displayed via the LTDC.
Waiting for the discussion about what should be RGB_565 / BGR_565 PIXEL_FORMAT in Zephyr and in order to have right display colors and video sample working on v4.2.0, is it ok to push such patch and get it merged into v4.2.0 ?
After that, if decision is taken to change formats after v4.2.0, we can change again this past v4.2.0 to align it with new definitions.
For information, on STM32 LTDC side, LVGL samples seems to be fine, with right colors (as far as I've seen with the various demo code I tried).

Absolutely- this is what I'd prefer. A narrow patch like what I described to fix the LTDC driver now for 4.2, and post 4.2 we will get this PR merged.

2025-07-01 20:37 UTC, avolmat-st commented
> > yes I confirm that with such modification done the LTDC driver, this allows to make the video sample work with the LTDC as well as the display sample giving the right colors when displayed via the LTDC.
> > Waiting for the discussion about what should be RGB_565 / BGR_565 PIXEL_FORMAT in Zephyr and in order to have right display colors and video sample working on v4.2.0, is it ok to push such patch and get it merged into v4.2.0 ?
> > After that, if decision is taken to change formats after v4.2.0, we can change again this past v4.2.0 to align it with new definitions.
> > For information, on STM32 LTDC side, LVGL samples seems to be fine, with right colors (as far as I've seen with the various demo code I tried).
> 
> Absolutely- this is what I'd prefer. A narrow patch like what I described to fix the LTDC driver now for 4.2, and post 4.2 we will get this PR merged.

PR #92483 pushed

2025-07-19 07:39 UTC, aescolar requested changes, later dismissed

2025-07-19 07:39 UTC, aescolar commented on doc/releases/migration-guide-4.2.rst
> +
This would need to modify the 4.3 guide now?

2025-07-22 11:44 UTC, ngphibang commented on doc/releases/migration-guide-4.2.rst
> +
yes, done. Thank you !

2025-07-22 12:25 UTC, JarmouniA requested changes

2025-07-22 12:25 UTC, JarmouniA commented on doc/releases/migration-guide-4.3.rst
> +* The RGB565 and BGR565 interchange issue has been fixed in the display sample.
which issue? the user reading the guide will have no idea, needs more details and explanation of how the change will actually impact an app migration.

2025-07-22 13:55 UTC, josuah commented on doc/releases/migration-guide-4.3.rst
> +* The RGB565 and BGR565 interchange issue has been fixed in the display sample.
Something like this?
```
* The RGB565 and BGR565 interchange (between red and blue) in the display sample has 
  been fixed. Boards tested only with the sample as well as application reusing
  the display sample code need to verify that they do not contain this inversion.
  (:github:`79996`)
```

2025-07-28 09:36 UTC, avolmat-st commented
Would it make sense to add a comment into the display header to describe what is the expected orderring for each format ?
Something similar to what is already available on the video side.

```
/*
 * 5 red bits [15:11], 6 green bits [10:5], 5 blue bits [4:0].
 * This 16-bit integer is then packed in little endian format over two bytes:
 *
 * @code{.unparsed}
 *   7......0 15.....8
 * | gggBbbbb RrrrrGgg | ...
 * @endcode
 */
#define VIDEO_PIX_FMT_RGB565 VIDEO_FOURCC('R', 'G', 'B', 'P')
```

With this PR merged, the LTDC is now broken since we merged the PR #92483 in the v4.2.0 release cycle in order to have LTDC behaving properly in v4.2.0. So related swap done in the PR #92483 should now be reverted I believe to have it work again.
Could you also make the revert part of this PR or do you prefer I do it on top of this one ?

2025-07-28 09:46 UTC, ngphibang commented
> Would it make sense to add a comment into the display header to describe what is the expected orderring for each format ?

Yes, it's a good idea.

> Could you also make the revert part of this PR or do you prefer I do it on top of this one ?

It should better be done in the same PR I think. I will do it.

2025-07-28 11:35 UTC, JarmouniA approved these changes

2025-07-28 20:13 UTC, danieldegrasse approved these changes
Let's go ahead and get this moved forwards. @josuah I appreciate you creating #92343- I have an `st7796s` based display, which appears to need updating. I made the change here: https://github.com/danieldegrasse/zephyr/commit/0bce970b2d77e649a4ee1cd2037a880b51cad47d. @ngphibang would you prefer I make a PR with that fix, or to just pull that commit into this PR?

2025-07-28 20:45 UTC, merged

2025-07-29 07:13 UTC, avolmat-st commented
@ngphibang since this PR got merged yesterday I will prepare and push a PR in order to tackle the two points I raised in my previous comment, that is, adding format description and fixing the LTDC.

2025-07-29 07:24 UTC, ngphibang commented
@avolmat-st : Sorry for the delay. I am working on it now.
@danieldegrasse : Yes, I will pick your commit. Thanks !

2025-07-29 07:52 UTC, ngphibang commented
Here is the PR : https://github.com/zephyrproject-rtos/zephyr/pull/93805