tests:kernel: added tests for timeslice reset
zephyrproject-rtos/zephyr pull request #80
Opened 2017-05-04 02:37 UTC by sharronliu

Added test cases to verify timeslice reset among thread context switching.

Jira: ZEP-948

Signed-off-by: Sharron LIU <sharron.liu@intel.com>

2017-05-19 10:58 UTC, nashif requested changes

2017-05-19 10:58 UTC, nashif commented on tests/kernel/threads_scheduling/schedule_api/src/test_sched_timeslice_reset.c
> +			tid[i] = k_thread_spawn(tstack[i], STACK_SIZE,
please use k_thread_create instead

2017-05-19 10:58 UTC, nashif commented on tests/kernel/threads_scheduling/schedule_api/src/test_sched_timeslice_reset.c
> +	TC_PRINT("expected %lld\n", expected_slice[thread_idx]);
print things to the screen only in debug mode, the test output should  be clean without noise coming out of the test

2017-05-19 12:49 UTC, sharronliu commented on tests/kernel/threads_scheduling/schedule_api/src/test_sched_timeslice_reset.c
> +	TC_PRINT("expected %lld\n", expected_slice[thread_idx]);
done

2017-05-19 12:49 UTC, sharronliu commented on tests/kernel/threads_scheduling/schedule_api/src/test_sched_timeslice_reset.c
> +			tid[i] = k_thread_spawn(tstack[i], STACK_SIZE,
done

2017-05-20 00:06 UTC, nashif commented
@sharronliu you probably want to squash the commit about timeslice into 1 commit and force push to your branch.

2017-05-23 07:07 UTC, sharronliu commented
@Anas, I re-ordered these two commits (git rebase -i) and get the earlier one updated. Thanks.

2017-05-27 14:22 UTC, nashif approved these changes

2017-05-27 14:22 UTC, merged