net: lib: lwm2m: lwm2m_rw_senml_cbor: fix temp64 uninitialized warning
zephyrproject-rtos/zephyr pull request #80019
Opened 2024-10-17 16:39 UTC by brandon-exact

Currently GCC complains that temp64 may be used uninitialized in this
 function -Werror=maybe-uninitialized.
 
 ```bash
 /home/runner/work/etc-em3-firmware/etc-em3-firmware/zephyr/subsys/net/lib/lwm2m/lwm2m_rw_senml_cbor.c:604:18: error: ‘temp64’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  604 |         *value = (time_t)temp64;
      |                  ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

2024-10-17 17:01 UTC, brandon-exact commented
only happens when i have `CONFIG_SPEED_OPTIMIZATIONS=y`

2024-10-18 09:52 UTC, SeppoTakalo requested changes
I think the warning is correct, but the fix is wrong.
The fix just hides the error.

Can you refactor this to look like that instead:
```c
static int get_time(struct lwm2m_input_context *in, time_t *value)
{
	int64_t temp64;
	int ret;

	ret = get_s64(in, &temp64);
	if (ret == 0) {
		*value = (time_t)temp64;
	}

	return ret;
}
```

This is because `get_s64()` can really fail, so it should not just write random values from stack, or zero.

2024-10-22 07:17 UTC, SeppoTakalo approved these changes

2024-10-22 07:26 UTC, rlubos approved these changes

2024-10-22 12:12 UTC, merged