drivers: i2c: API to get max regulator voltage
zephyrproject-rtos/zephyr pull request #80029
Opened 2024-10-18 00:34 UTC by RafaelLaya

There is already a regulator_common_get_min_voltage() API, to query the maximum supported voltage on a regulator. This change adds an analogous and symmetric API to query the maximum supported voltage

2024-10-18 03:32 UTC, RafaelLaya commented
@gmarull @danieldegrasse @aasinclair Fixed title and commit message (this is on the regulator API, not i2c, but for some reason my brain made me type i2c...) Hope all the automatic tags are correct?

2024-10-18 07:41 UTC, gmarull reviewed
where is this needed/used? These are internal APIs

2024-10-18 17:02 UTC, RafaelLaya commented
> where is this needed/used? These are internal APIs

Good point. I've added two more commits, for a total of three:

1. The addition of get_max_voltage()
2. Adds unit-testing coverage for the new get_max_voltage() and for the pre-existing get_min_voltage()
3. Linter pass on the unit tests to make sure CI is happy

Now it's used in the tests

Regarding for where this is needed:

1. For symmetry since the get_min_voltage() internal API already exists
2. It is useful for code interfacing with regulators. I've some uses for it but it's not ready yet (if ever) to upstream. But in any case, this can still be a useful API for users interfacing with regulators at the low level

2024-10-21 07:34 UTC, gmarull requested changes
please, introduce any formatting changes in a separate commit.

2024-10-21 13:22 UTC, RafaelLaya commented
> please, introduce any formatting changes in a separate commit.

Good catch! I thought I had three commits. My bad, now I've actually split the changes into the three commits mentioned above

2024-10-24 08:20 UTC, gmarull approved these changes

2024-10-24 14:22 UTC, fabiobaltieri approved these changes

2024-10-24 15:51 UTC, merged