Add MAX32xxx RTC driver
zephyrproject-rtos/zephyr pull request #80040
Opened 2024-10-18 08:48 UTC by oknshn

This PR adds counter RTC driver for ADI MAX32xxx series microcontrollers. Counter tests are also enabled.

2024-10-22 09:36 UTC, oknshn commented
> Needs rebase
Done.

2024-10-23 06:55 UTC, ttmut commented on boards/adi/max32655evkit/max32655evkit_max32655_m4.dts
> + * ERTCO requires for counter RTC
```suggestion
 * ERTCO is required for counter RTC
```

2024-10-23 07:01 UTC, ttmut requested changes
Not a hard requirement but you may consider merging commits to `boards` from same author into a single one to keep commit history brief.

2024-10-23 09:05 UTC, oknshn commented
> Not a hard requirement but you may consider merging commits to `boards` from same author into a single one to keep commit history brief.

Done

2024-10-24 06:05 UTC, ttmut approved these changes

2024-10-24 06:27 UTC, ozersa approved these changes

2024-10-25 11:04 UTC, bjarki-andreasen approved these changes
looks good, like the `rtc_counter` name, its always confusing with RTC, is it real time clock, is it real time counter, or RTCC, is that real time clock calendar or real time clock counter :D

2024-10-25 11:13 UTC, oknshn commented
Hello @nordic-krch,
Could you take a look?

2024-10-25 11:18 UTC, oknshn commented
> looks good, I like the `rtc_counter` name, its always confusing with RTC, is it real time clock, is it real time counter, or RTCC, is that real time clock calendar or real time clock counter :D
Thanks, It is `real time counter`, I can create follow-up PR for it.

2024-10-25 11:21 UTC, MaureenHelm approved these changes

2024-10-30 12:42 UTC, oknshn commented
> Hello @nordic-krch, Could you take a look?
Hello @nordic-krch,
Waiting for your review.

2024-11-04 09:38 UTC, nordic-krch approved these changes

2024-11-16 20:08 UTC, merged