Introducing Zephyr Guru on Gurubase.io
zephyrproject-rtos/zephyr pull request #80099
Opened 2024-10-19 19:48 UTC by kursataktas

Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Zephyr Guru](https://gurubase.io/g/zephyr) to Gurubase. Zephyr Guru uses the data from this repo and data from the [docs](https://docs.zephyrproject.org/latest/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Zephyr Guru" badge, which highlights that Zephyr now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Zephyr Guru in Gurubase, just let me know that's totally fine.

2024-10-19 19:59 UTC, kartben commented
@kursataktas thanks for taking the time to integrate Zephyr in Gurubase (disclaimer: I'm the one who asked :))
Unfortunately at this point, and based on my testing, the answers are typically too vague or too wrong to really be helpful. One thing that may be interesting would be to ingest Discord archives too, but I don't know how easy that would be, and if that's even doable as per the terms of use...

2024-10-19 20:01 UTC, kartben requested changes
-1 as per my comment. Even if it'd work much better, promoting a 3rd party service right on our main README is likely something we would not do anyway and we'd need to find a better "home" for this link (or host the service ourselves)

2024-10-19 20:02 UTC, kursataktas commented
Hey @kartben, thanks for the review! We just released a major update yesterday. I'm curious—when exactly did you run the test? I believe the new version is more reliable and might change your opinion. 

Regarding the Discord side, I need to do some research first, and I’ll update you afterward.

2024-10-20 12:10 UTC, alexpaschoaletto commented
Hey, this is a great idea! Thank you for the contribution.

> I'm curious—when exactly did you run the test? I believe the new version is more reliable and might change your opinion.

I cannot speak for mr @kartben but I've ran a test just now to check Gurubase. As my current work with zephyr is tied with EDF, I asked it "How to set a thread deadline in Zephyr?" and the result was not correct, although the answer was actually a change I'd love to see in the API for the future. According to Gurubase, this is how you set a deadline:
```c
// API:
void k_thread_deadline_set(struct k_thread *thread, k_timeout_t deadline);

// usage:
k_thread_deadline_set(my_thread_id, K_MSEC(1000));
```

However, currently the deadline must be passed in [hardware cycles](https://docs.zephyrproject.org/latest/doxygen/html/group__thread__apis.html#gad887f16c1dd6f3247682a83beb22d1ce):

```c
// API:
void k_thread_deadline_set(struct k_thread *thread, int deadline);

// usage:
k_thread_deadline_set(my_thread_id, 10000);
```

I don't really see the point of passing hardware cycles as the deadline when the rest of the API is tailored for the `k_timeout_t` type. Not only it's an inconsistency for the API - a deadline in cycles instead of ticks also doesn't seem to cause any major benefits within the kernel aside from reducing the chances of threads being of the same exact priority. It's also less portable and might overflow much quicker.

So in short, I agree with the answer provided by Gurubase - it's what I'd like to see for the EDF API. But it's not what we have yet, so it's an inaccurate answer.

2024-10-20 21:20 UTC, henrikbrixandersen commented
> I wanted to update you that I've manually added the Zephyr Guru to Gurubase. Zephyr Guru uses the data from this repo and data from the docs to answer questions by leveraging the LLM.

The code in this repo is licensed under Apache-2.0 and copyrighted by various authors. The documentation is licensed under CC-BY-4.0 and copyrighted by the Zephyr project and it's individual authors. 

How does GuruBase honor these license terms and copyrights in it's LLM training and the answers given by it's "Zephyr Guru"?

2024-10-21 06:13 UTC, nordicjm commented
> One thing that may be interesting would be to ingest Discord archives too, but I don't know how easy that would be, and if that's even doable as per the terms of use...

Absolutely no to that

2024-10-21 11:01 UTC, kursataktas commented
> Hey, this is a great idea! Thank you for the contribution.
> 
> > I'm curious—when exactly did you run the test? I believe the new version is more reliable and might change your opinion.
> 
> I cannot speak for mr @kartben but I've ran a test just now to check Gurubase. As my current work with zephyr is tied with EDF, I asked it "How to set a thread deadline in Zephyr?" and the result was not correct, although the answer was actually a change I'd love to see in the API for the future. According to Gurubase, this is how you set a deadline:
> 
> ```c
> // API:
> void k_thread_deadline_set(struct k_thread *thread, k_timeout_t deadline);
> 
> // usage:
> k_thread_deadline_set(my_thread_id, K_MSEC(1000));
> ```
> 
> However, currently the deadline must be passed in [hardware cycles](https://docs.zephyrproject.org/latest/doxygen/html/group__thread__apis.html#gad887f16c1dd6f3247682a83beb22d1ce):
> 
> ```c
> // API:
> void k_thread_deadline_set(struct k_thread *thread, int deadline);
> 
> // usage:
> k_thread_deadline_set(my_thread_id, 10000);
> ```
> 
> I don't really see the point of passing hardware cycles as the deadline when the rest of the API is tailored for the `k_timeout_t` type. Not only it's an inconsistency for the API - a deadline in cycles instead of ticks also doesn't seem to cause any major benefits within the kernel aside from reducing the chances of threads being of the same exact priority. It's also less portable and might overflow much quicker.
> 
> So in short, I agree with the answer provided by Gurubase - it's what I'd like to see for the EDF API. But it's not what we have yet, so it's an inaccurate answer.

Sorry to hear that. We are currently dealing with this type of issue. This week, we'll release a new update that will make the asnwer generation stricter to prevent hallucination. I can update you once we release it, or I can disable the Zephyr Guru on Gurubase right now. Please let me know how you'd like me to proceed.

2024-10-21 12:28 UTC, henrikbrixandersen commented
I just did a quick test: https://gurubase.io/g/zephyr/receive-rtr-frames-can-zephyr

Not only did it dream up non-existing Zephyr API functions, the ones it actually found are used wrong - and I don't see any notice on license or copyright in the code answers given.

My vote is for disabling this integration as it only adds confusion and at best is dodgy when it comes to copyright and license.

2024-10-21 12:29 UTC, henrikbrixandersen requested changes
I don't think this is ready for us to promote as a project.

2024-10-21 13:32 UTC, kartben commented
> [...] or I can disable the Zephyr Guru on Gurubase right now. Please let me know how you'd like me to proceed.

@kursataktas for the time being, yes, please remove Zephyr RTOS from your product. Thanks!

2024-10-21 13:37 UTC, kursataktas commented
Sure, I removed it.

2024-10-21 14:50 UTC, closed without merging