drivers: sensor: Add RRH46410 driver
zephyrproject-rtos/zephyr pull request #80139
Opened 2024-10-21 11:42 UTC by TotallyOriginalUsername

Adds Renesas RRH46410 gas sensor module driver.
The reset pin gets used to make sure the sensor starts from suspend mode.

2024-11-25 07:50 UTC, TotallyOriginalUsername commented
Hello @MaureenHelm, could you please review this driver?

2025-01-18 05:33 UTC, kartben commented
@TotallyOriginalUsername could you address the compliance check failures?

2025-01-23 17:27 UTC, TotallyOriginalUsername commented
> @TotallyOriginalUsername could you address the compliance check failures? This will also need to be rebased on main

The compliance check failures have been addressed, and it has been rebased on main

2025-01-24 13:38 UTC, MaureenHelm requested changes

2025-01-24 13:38 UTC, MaureenHelm commented on drivers/sensor/renesas/rrh46410/Kconfig
> +	depends on UART_INTERRUPT_DRIVEN
Remove this and update the previous Kconfig to use `dt_compat_on_bus` for serial too.

2025-01-24 13:38 UTC, MaureenHelm commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	k_sleep(K_MSEC(600));
Are you sure you want to add 700 ms of boot delay?

2025-01-24 13:38 UTC, MaureenHelm commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	.reset_gpio = GPIO_DT_SPEC_INST_GET(0, reset_gpios), \
```suggestion
	.reset_gpio = GPIO_DT_SPEC_INST_GET(n, reset_gpios), \
```

2025-01-24 13:38 UTC, MaureenHelm commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	.reset_gpio = GPIO_DT_SPEC_INST_GET(0, reset_gpios),		\
```suggestion
	.reset_gpio = GPIO_DT_SPEC_INST_GET(n, reset_gpios),		\
```

2025-01-24 13:38 UTC, MaureenHelm commented on drivers/sensor/renesas/rrh46410/rrh46410_i2c.c
> +	if (!device_is_ready(cfg->bus_cfg.i2c.bus)) {
`i2c_is_ready_dt`

2025-02-05 19:34 UTC, MaureenHelm requested changes

2025-02-05 19:34 UTC, MaureenHelm commented on include/zephyr/drivers/sensor/rrh46410.h
> +	SENSOR_CHAN_RELIAQ,
These custom enums need to have the sensor name in them. e.g., `SENSOR_CHAN_RRH46410_IAQ`

2025-02-06 15:19 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	k_sleep(K_MSEC(600));
@MaureenHelm @teburd there are a lot of sensors like this. I'm starting to think that we should have some pattern for a 2+ phase init for sensor drivers. We can kinda fake it right now. We have https://docs.zephyrproject.org/latest/kernel/drivers/index.html#deferred-initialization so we could call `device_init()` on a `SYS_INIT` which would kick off the process, then instead of sleeping we could use a timer or a deferred work item to call `device_init()` again and continue the init process until it finishes. The device would have to maintain an internal state (maybe a place to use the fsm subsystem)?

2025-02-06 15:34 UTC, yperess requested changes

2025-02-06 15:34 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	&data->tvoc_sample, &data->etoh_sample, &data->eco2_sample, &data->reliaq_sample);
Please run clang-format on all .c and .h files

2025-02-06 15:34 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410.h
> +#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
There's no need to `#if` here, just include the i2c.h it won't hurt anything and it makes the file more readable.

2025-02-06 15:34 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410.h
> +#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
Please include `#define DT_DRV_COMPAT` in this file otherwise you're depending on include order.

2025-02-12 20:49 UTC, MaureenHelm approved these changes, later dismissed

2025-02-14 09:36 UTC, yperess submitted a review, later dismissed

2025-02-18 06:29 UTC, yperess requested changes

2025-02-18 06:29 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410_uart.c
> +}
I just noticed that the UART read_data function is empty and returns 0. Can you at least return an -EIO error or implement it?

2025-02-20 07:04 UTC, yperess requested changes

2025-02-20 07:04 UTC, yperess commented on drivers/sensor/renesas/rrh46410/rrh46410_uart.c
> +	memcpy(data->read_buffer, data->uart_buffer, sizeof(data->read_buffer));
Shouldn't the byte count be `data_size` and we should check that `data_size < sizeof(data->read_buffer)` before reading.

2025-02-26 17:46 UTC, yperess approved these changes, later dismissed

2025-02-27 19:35 UTC, MaureenHelm approved these changes, later dismissed

2025-02-27 19:54 UTC, kartben commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +		return rc;
but rrh46410_get_operation_mode returns an unsigned int

2025-02-27 19:54 UTC, kartben commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	*reliaq_sample = sys_get_be16(&data->read_buffer[9]);
reliaq_sample is a uint8_t?

```suggestion
	*reliaq_sample = data->read_buffer[9];
```

2025-03-04 16:06 UTC, teburd commented on drivers/sensor/renesas/rrh46410/rrh46410.c
> +	k_sleep(K_MSEC(600));
The large delays here are concerning, we don't have a great story on how to deal with it today as init is not based on asynchronous state machines, its based on a blocking init call done from the init loop done per level here https://github.com/zephyrproject-rtos/zephyr/blob/main/kernel/init.c#L347

Meaning this will block your application from starting for nearly a second and that would likely be surprising to people.

2025-03-14 14:02 UTC, MaureenHelm commented
Please rebase

2025-03-27 16:36 UTC, TotallyOriginalUsername commented
> Please rebase

Apologies for the delay, it has been rebased

2025-04-07 23:38 UTC, yperess approved these changes, later dismissed

2025-04-21 21:21 UTC, MaureenHelm commented
> > Please rebase
> 
> Apologies for the delay, it has been rebased

Needs another rebase.

2025-07-07 00:43 UTC, closed without merging