docs: dma: Explicitly allow reconfiguration
zephyrproject-rtos/zephyr pull request #80206
Opened 2024-10-22 08:54 UTC by rettichschnidi

This explicitly documents that a configured DMA channel can be reconfigured.

2024-10-22 13:47 UTC, teburd approved these changes, later dismissed

2024-10-22 14:02 UTC, kartben approved these changes

2024-10-22 15:01 UTC, hakehuang submitted a review, later dismissed

2024-10-22 16:18 UTC, rettichschnidi commented
Before anyone merges this, it actually looks really bad:
![image](https://github.com/user-attachments/assets/63b0ccc2-01cf-4b3c-a3a7-89a9e30aa2e6)

Ideas?

2024-10-22 16:38 UTC, kartben requested changes

2024-10-22 16:38 UTC, kartben commented on doc/hardware/peripherals/dma.rst
> +       CONFIGURED -> CONFIGURED [label=dma_config];
```suggestion
       CONFIGURED -> CONFIGURED [label=dma_stop, headport=c, tailport=e];
       CONFIGURED -> CONFIGURED [label=dma_config, headport=c, tailport=w];
```

2024-10-22 16:38 UTC, kartben commented on doc/hardware/peripherals/dma.rst
> +       CONFIGURED -> CONFIGURED [label=dma_config];
https://dreampuf.github.io/GraphvizOnline/#%20%20%20digraph%20%7B%0A%20%20%20%20%20%20%20node%20%5Bstyle%3Drounded%5D%3B%0A%20%20%20%20%20%20%20edge%20%5Bfontname%3DCourier%5D%3B%0A%20%20%20%20%20%20%20init%20%5Bshape%3Dpoint%5D%3B%0A%20%20%20%20%20%20%20CONFIGURED%20%5Blabel%3DConfigured%2Cshape%3Dbox%5D%3B%0A%20%20%20%20%20%20%20RUNNING%20%5Blabel%3DRunning%2Cshape%3Dbox%5D%3B%0A%20%20%20%20%20%20%20SUSPENDED%20%5Blabel%3DSuspended%2Cshape%3Dbox%5D%3B%0A%20%20%20%20%20%20%20init%20-%3E%20CONFIGURED%20%5Blabel%3Ddma_config%5D%3B%0A%0A%20%20%20%20%20%20%20CONFIGURED%20-%3E%20RUNNING%20%5Blabel%3Ddma_start%5D%3B%0A%20%20%20%20%20%20%20CONFIGURED%20-%3E%20CONFIGURED%20%5Blabel%3Ddma_stop%2C%20headport%3Dc%2C%20tailport%3De%5D%3B%20%20%2F%2F%20Adjusted%20to%20avoid%20overlap%0A%20%20%20%20%20%20%20CONFIGURED%20-%3E%20CONFIGURED%20%5Blabel%3Ddma_config%2C%20headport%3Dc%2C%20tailport%3Dw%5D%3B%20%20%2F%2F%20Adjusted%20to%20avoid%20overlap%0A%0A%20%20%20%20%20%20%20RUNNING%20-%3E%20CONFIGURED%20%5Blabel%3Ddma_stop%5D%3B%0A%20%20%20%20%20%20%20RUNNING%20-%3E%20RUNNING%20%5Blabel%3Ddma_start%5D%3B%0A%20%20%20%20%20%20%20RUNNING%20-%3E%20RUNNING%20%5Blabel%3Ddma_resume%2C%20headport%3Dw%5D%3B%0A%20%20%20%20%20%20%20RUNNING%20-%3E%20SUSPENDED%20%5Blabel%3Ddma_suspend%5D%3B%0A%20%20%20%20%20%20%20SUSPENDED%20-%3E%20SUSPENDED%20%5Blabel%3Ddma_suspend%5D%3B%0A%20%20%20%20%20%20%20SUSPENDED%20-%3E%20RUNNING%20%5Blabel%3Ddma_resume%5D%3B%0A%20%20%20%20%20%20%20SUSPENDED%20-%3E%20CONFIGURED%20%5Blabel%3Ddma_stop%5D%3B%0A%20%20%20%7D

![image](https://github.com/user-attachments/assets/8bcb64f7-5d0e-4aaf-a3dd-19aed347b61b)

2024-10-22 18:01 UTC, rettichschnidi commented on doc/hardware/peripherals/dma.rst
> +       CONFIGURED -> CONFIGURED [label=dma_config];
Great, thanks!

2024-10-22 18:18 UTC, kartben approved these changes, later dismissed
Looking good :)

https://builds.zephyrproject.io/zephyr/pr/80206/docs/hardware/peripherals/dma.html#channel-state-machine-expectations

2024-10-22 18:59 UTC, ubieda approved these changes, later dismissed
> A diagram showing those _**expectated**_ possible state transitions and their API calls is provided here for reference.

There's a typo a few lines above. Maybe we can take care of that in this PR?

2024-10-22 20:52 UTC, ubieda submitted a review, later dismissed
Thanks!

2024-10-22 20:56 UTC, kartben approved these changes, later dismissed

2024-10-22 21:04 UTC, teburd approved these changes, later dismissed

2024-11-18 18:56 UTC, teburd approved these changes

2024-11-18 19:13 UTC, kartben approved these changes

2024-11-19 00:31 UTC, merged