modules: hal_nordic: Require nrf-regtool 7.0.0
zephyrproject-rtos/zephyr pull request #80220
Opened 2024-10-22 11:36 UTC by carlescufi

Some upcoming changes require this version.

2024-10-22 11:38 UTC, 57300 requested changes
We need #79925 first

2024-10-26 10:08 UTC, anangl approved these changes

2024-10-26 13:36 UTC, 57300 approved these changes

2024-10-27 21:30 UTC, dkalowsk approved these changes

2024-10-27 21:30 UTC, merged