twister: terminate_process: fix NoSuchProcess error
zephyrproject-rtos/zephyr pull request #80394
Opened 2024-10-24 18:59 UTC by M1cha

NOTE: Even though previous commits indicate, that this can only happen on MacOS, that's actually not true. It happens on Linux as well.

The constructor of `psutil.Process` can throw an exception as well, so we need to wrap the whole loop in another try, unfortunately.

2024-12-04 18:48 UTC, nashif commented
@gchwier  @PerMac  can you review please?

2024-12-05 10:12 UTC, PerMac requested changes
The code will work but it is preferable to keep the code relavant. One try/except should address the os exception and the other the psutill one. Both cannot happen in the same place.

2024-12-05 10:12 UTC, PerMac commented on scripts/pylib/pytest-twister-harness/src/twister_harness/device/utils.py
> +        pass
The code will work but it's good to keep it relevant. One exception is targeting `os` and the other `psutil`. A relevant error should correspond to each of them (i.e. os won't raise psutill exception and vice versa) hence my suggestion:

```suggestion
    try:
        for child in psutil.Process(proc.pid).children(recursive=True):
            try:
                os.kill(child.pid, signal.SIGTERM)
            except (ProcessLookupError):
                pass
    except (psutil.NoSuchProcess):
        pass
```

Or in this case if we just want to pass over exception a `suppress` can be used:

```
    from contextlib import suppress
    
    with suppress(psutil.NoSuchProcess):            
        for child in psutil.Process(proc.pid).children(recursive=True):
            with suppress(ProcessLookupError):
                os.kill(child.pid, signal.SIGTERM)
```

2024-12-05 11:03 UTC, gchwier commented
Please check https://github.com/zephyrproject-rtos/zephyr/pull/82043/commits/a8d8073bc3cfc988785bb7d408c0dd694694179d
where contextlib was also introduced. Shouldn't your changes also be applied in the `handlers.py` file where process termination is used by Twister?

2025-02-19 06:42 UTC, M1cha commented on scripts/pylib/pytest-twister-harness/src/twister_harness/device/utils.py
> +        pass
that's not quite right. both `Process()` and `kill()` can raise both of these exceptions.

2025-02-19 06:51 UTC, M1cha commented
> Note, that you can always re-open a closed pull request at any time.

That's not true, GitHub does not allow me to reopen this PR.

2025-02-19 06:51 UTC, M1cha commented
I need to comment to reopen

2025-02-19 06:52 UTC, M1cha commented
I need to comment to reopen

2025-02-19 10:57 UTC, PerMac approved these changes

2025-02-19 11:34 UTC, hakehuang approved these changes

2025-02-19 20:40 UTC, nashif approved these changes

2025-02-20 05:04 UTC, merged