MAINTAINERS: add ZMS maintainer
zephyrproject-rtos/zephyr pull request #80402
Opened 2024-10-24 22:30 UTC by rghaddab

Add myself "rghaddab" as maintainer to the ZMS storage system as I am the author of this new storage solution

2024-10-25 07:43 UTC, carlescufi approved these changes, later dismissed

2024-10-25 20:37 UTC, de-nordic approved these changes, later dismissed

2024-10-25 20:43 UTC, kartben submitted a review, later dismissed

2024-10-28 12:20 UTC, tomi-font reviewed
Wondering how this is gonna play out as the files covered by this new entry are also covered by `Filesystems`? Shall we break `Filesystems` down?

By the way: https://github.com/zephyrproject-rtos/zephyr/blob/69b7ad19f0ab8bf87bebb6baddd38b7d2b800c65/MAINTAINERS.yml#L112

2024-10-28 13:38 UTC, MaureenHelm requested changes
> Contributors or Collaborators are promoted to the Maintainer role by adding the GitHub user name to one or more maintainers sections of the [MAINTAINERS File](https://docs.zephyrproject.org/latest/project/project_roles.html#maintainers-file) in the Zephyr repository. Candidates who are neither Contributors nor Collaborators must be approved by the TSC before they can assume the role of Maintainer.

https://docs.zephyrproject.org/latest/project/project_roles.html#maintainer

2024-10-30 18:31 UTC, MaureenHelm approved these changes
> > > Contributors or Collaborators are promoted to the Maintainer role by adding the GitHub user name to one or more maintainers sections of the [MAINTAINERS File](https://docs.zephyrproject.org/latest/project/project_roles.html#maintainers-file) in the Zephyr repository. Candidates who are neither Contributors nor Collaborators must be approved by the TSC before they can assume the role of Maintainer.
> > 
> > 
> > [docs.zephyrproject.org/latest/project/project_roles.html#maintainer](https://docs.zephyrproject.org/latest/project/project_roles.html#maintainer)
> 
> #80518

This was reviewed in today's TSC meeting and no concerns were raised. Thanks for stepping up as a maintainer

2024-10-30 23:17 UTC, stephanosio approved these changes

2024-10-31 01:44 UTC, merged