soc: espressif: Add hardware initialization
zephyrproject-rtos/zephyr pull request #80400
Opened 2024-10-24 22:01 UTC by LucasTambor

Bring hardware initialization to zephyr code base.

2024-10-26 01:06 UTC, uLipe requested changes

2024-10-26 01:06 UTC, uLipe commented on soc/espressif/common/include/console_init.h
> +#pragma once
I think you need to update the header file guard to the #ifdef based approach

2024-11-06 14:42 UTC, marekmatej commented on soc/espressif/common/loader.c
> +static int hardware_init(void)
Can we provide only `hardware_init` here and leave the rest of the functions in their original locations? I think it is creating unnecessary clutter in the `loader.c`.
Also I'm not sure if having separate `hardware_init` for each SoC is not better (for readability) as the procedures differ between the chips.

2024-11-22 20:01 UTC, wmrsouza approved these changes, later dismissed

2024-11-24 17:03 UTC, uLipe submitted a review, later dismissed

2024-11-25 11:29 UTC, marekmatej approved these changes, later dismissed

2024-11-25 11:41 UTC, sylvioalves commented on soc/espressif/esp32s3/hw_init.c
> +
Would you remove this empty line?

2024-11-25 13:27 UTC, marekmatej approved these changes

2024-11-25 13:38 UTC, sylvioalves approved these changes

2024-11-25 23:12 UTC, merged