doc: release: 4.0: Add MCUboot and other misc. updates
zephyrproject-rtos/zephyr pull request #80430
Opened 2024-10-25 10:06 UTC by nordicjm

Adds notes on MCUboot changes to this release and some other updates for boards/build system

2024-10-25 10:25 UTC, kartben requested changes

2024-10-25 10:25 UTC, kartben commented on doc/releases/release-notes-4.0.rst
> +* Added support for selecting MCUboot operating mode in sysbuild using ``SB_CONFIG_`MCUBOOT_MODE``.
```suggestion
* Added support for selecting MCUboot operating mode in sysbuild using ``SB_CONFIG_MCUBOOT_MODE``.
```

2024-10-28 08:03 UTC, nordicjm commented on doc/releases/release-notes-4.0.rst
> +* Added support for selecting MCUboot operating mode in sysbuild using ``SB_CONFIG_`MCUBOOT_MODE``.
Fixed

2024-10-28 16:25 UTC, kartben submitted a review, later dismissed

2024-10-28 16:52 UTC, mmahadevan108 submitted a review, later dismissed

2024-10-29 07:42 UTC, nordicjm commented on doc/releases/release-notes-4.0.rst
> +  * Added Thingy53 forwarding of network core pins to networe core for SPI peripheral (disabled
Good catch, fixed

2024-10-29 08:49 UTC, kartben submitted a review, later dismissed

2024-10-29 13:54 UTC, de-nordic submitted a review, later dismissed

2024-11-01 08:39 UTC, kartben approved these changes

2024-11-04 01:34 UTC, dkalowsk approved these changes

2024-11-04 19:42 UTC, merged