include: clock: stm32f4 high speed clock definition
zephyrproject-rtos/zephyr pull request #80509
Opened 2024-10-28 10:56 UTC by FRASTM

Add the HSI and HSE clock source for the stm32f4 serie

Fixes https://github.com/zephyrproject-rtos/zephyr/discussions/80465

2024-10-28 13:30 UTC, FRASTM commented
rebase on 9f93dede369c365c68b5618844e3d31e35327bc2
add sample for mco on some nucleo_f4 boards

2024-10-29 10:50 UTC, joerchan commented on samples/boards/st/mco/boards/nucleo_f429zi.overlay
> +#define MCO_PRE_DIV_2 1
```suggestion
#define MCO_PRE_DIV_2 4
```
According to RM0090.

2024-10-29 10:50 UTC, joerchan commented on samples/boards/st/mco/boards/nucleo_f410rb.overlay
> +#define MCO_PRE_DIV_2 1
```suggestion
#define MCO_PRE_DIV_2 4
```
According to RM0401

2024-11-04 10:37 UTC, erwango requested changes
Please remove (sqaush) 2 last commits

2024-11-04 14:14 UTC, erwango requested changes
Otherwise LGTM

2024-11-04 14:14 UTC, erwango commented on samples/boards/st/mco/boards/nucleo_f410rb.overlay
Let's remove this overlay as it doesn't have any added value and that just more file to maintain.

2024-11-04 14:26 UTC, erwango approved these changes

2024-11-04 16:05 UTC, gautierg-st approved these changes

2024-11-04 16:24 UTC, mathieuchopstm approved these changes

2024-11-05 14:04 UTC, joerchan approved these changes

2024-11-29 10:30 UTC, kartben commented
@nordic-krch PTAL - Thanks!

2024-11-29 13:46 UTC, nordic-krch approved these changes

2024-11-29 14:29 UTC, merged