samples: sensor: qdec
zephyrproject-rtos/zephyr pull request #80562
Opened 2024-10-29 10:54 UTC by nordic-pikr

Change pins that are used for qdec nrf54h20dk

2024-10-29 11:56 UTC, nordic-bami approved these changes

2024-10-29 12:01 UTC, nordic-segl approved these changes

2024-10-30 07:10 UTC, nordic-piks approved these changes

2024-10-30 09:45 UTC, kartben requested changes
please include an actual description in the commit, not just the `samples: sensor: qdec` labels

```
samples: sensor: qdec: change pins used for nrf54h20dk

<<here explain what was wrong / why it was changed>>
```

2024-10-30 11:44 UTC, kartben approved these changes

2024-10-30 15:11 UTC, MaureenHelm approved these changes

2024-10-31 14:22 UTC, merged