samples: video: capture: Fix floating point logging issue
zephyrproject-rtos/zephyr pull request #80654
Opened 2024-10-30 22:44 UTC by ngphibang

The default frame rate is printed as a floating point number. However, without enabling CONFIG_FPU, it is not printed at all.

Print it as uint32_t numbers in "denominator/numerator" frame interval form which preserves the same meaning while do not need CONFIG_FPU.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80653

2024-10-30 22:58 UTC, kartben requested changes
I believe the right fix is simply to set `CONFIG_REQUIRES_FLOAT_PRINTF=y` in the prj.conf

2024-10-31 09:55 UTC, ngphibang commented
@kartben : That's right. Thank you for showing me this config that I was not aware of.

2024-10-31 09:57 UTC, kartben approved these changes
Thanks!

2024-10-31 10:50 UTC, josuah approved these changes

2024-10-31 14:22 UTC, merged