drivers: eeprom: at2x: streamline codebase
zephyrproject-rtos/zephyr pull request #80660
Opened 2024-10-31 07:22 UTC by ndrs-pst

This PR includes several changes to the `eeprom_at2x.c` file, focusing on code simplification and optimization as follows:

- Remove '&' when assigning `init_fn` in `DEVICE_DT_INST_DEFINE` macro
- Remove orphaned `k_mutex_unlock` in `eeprom_at25_read`
- Make `spi_buf_set` constant in `eeprom_at25_wren`
- Make `spi_buf_set` constant in `eeprom_at25_rdsr`
- Simplify `cmd[]` assignment in `eeprom_at25_read` and `eeprom_at25_write`

2024-11-01 14:29 UTC, henrikbrixandersen requested changes

2024-11-01 14:29 UTC, henrikbrixandersen commented on drivers/eeprom/eeprom_at2x.c
> +	static const struct spi_buf tx_buf = {
Not sure the `static const` changes are okay. Some SPI-controller drivers may be using DMA yet unable to DMA transfer from flash. I'd prefer to leave these as-is.

2024-12-16 09:34 UTC, henrikbrixandersen commented
@ndrs-pst Any plans for picking up this PR and addressing the requested change?

2024-12-16 09:46 UTC, ndrs-pst commented
That means, even if it uses synchronous APIs and does not involve DMA transfers, it would not be justified.
Therefore, I will address the requested change. 😃

2024-12-19 22:32 UTC, henrikbrixandersen approved these changes

2024-12-20 00:27 UTC, fabiobaltieri approved these changes

2024-12-20 02:17 UTC, merged