boards: Remove PINCTRL from 3rd party NXP boards
zephyrproject-rtos/zephyr pull request #80664
Opened 2024-10-31 08:16 UTC by nordicjm

Removes lines from defconfig files having PINCTRL in them

2024-10-31 12:00 UTC, jonas-rem requested changes

2024-10-31 12:00 UTC, jonas-rem commented on boards/arduino/nicla_sense_me/arduino_nicla_sense_me_defconfig
> -CONFIG_PINCTRL=y
Same here, this is a board based on a Nordic SoC.

2024-10-31 12:49 UTC, nordicjm commented on boards/phytec/phyboard_electra/phyboard_electra_am6442_m4_defconfig
> -
Renamed

2024-10-31 12:57 UTC, jonas-rem approved these changes

2024-10-31 16:32 UTC, dnltz approved these changes
Thanks for removing them!

2024-11-04 15:07 UTC, dnltz commented
@nordicjm I don't have the permissions to merge this pull request. Where can I find out who I should assign this PR to?

2024-11-04 15:10 UTC, nordicjm commented
It will be merged post zephyr 4.0 release by someone with merge rights (currently zephyr is in feature free for 4.0)

2024-11-07 16:01 UTC, dnltz commented
> It will be merged post zephyr 4.0 release by someone with merge rights (currently zephyr is in feature free for 4.0)

@nordicjm thank you for the explaining!

2024-11-16 20:27 UTC, merged