pwm: pwm_nrf5_sw: Add prescaler support and use it in the servo_motor sample
zephyrproject-rtos/zephyr pull request #8068
Opened 2018-05-31 13:05 UTC by henrikbrixandersen

These commits fix the inaccuracies regarding PWM frequency and pulse width in the current pwm_nrf5_sw implementation, adds support for specifying a HF timer prescaler value and finally uses the prescaler to enable use of the servo_motor sample on the BBC micro:bit.

2018-05-31 18:40 UTC, dbkinder approved these changes

2018-05-31 18:42 UTC, dbkinder commented
you'll need to fix the commit message title (too long)

2018-05-31 19:12 UTC, henrikbrixandersen commented
@dbkinder Thank you for reviewing. Which commit has the too long title?

2018-06-01 16:46 UTC, henrikbrixandersen commented
This is an alternative solution to #7474 which is more in line with the proposed addition of the nrfx PWM HW driver in #7334.

2018-06-02 01:57 UTC, cvinayak requested changes
Minor change requested, else LGTM.

2018-06-02 01:57 UTC, cvinayak commented on drivers/pwm/Kconfig.nrf5_sw
> +	depends on PWM_NRF5_SW
use IF clause enclosing the DEV_NAME together, instead of using depends on (as the two can be grouped together now)

2018-06-02 05:09 UTC, henrikbrixandersen commented
@cvinayak Thank, fixed.

2018-06-02 06:53 UTC, findlayfeng commented
我的本意是修复 period_cycles  大于 0xffff 时会引发的bug，在这里，我认为应当在period_cycles大于0xffff 时返回错误
From Google Translate
My intention is to fix the bug that is caused when period_cycles is greater than 0xffff. Here, I think it should return an error when period_cycles is greater than 0xffff.

2018-06-02 18:34 UTC, henrikbrixandersen commented
@findlayfeng Good point, that should be addressed as well. Not sure I understand your math in #7474 regarding this, but perhaps it can just be rebased to address the overflow issue once this has been merged?

2018-06-04 00:56 UTC, cvinayak approved these changes

2018-06-04 01:03 UTC, cvinayak commented
@carlescufi please do the needful.

2018-06-04 01:04 UTC, cvinayak commented
@jhedberg hope you can check the mesh demo buzzer has no regression.

2018-06-04 06:41 UTC, jhedberg commented
> @jhedberg hope you can check the mesh demo buzzer has no regression.

@cvinayak I tested with `samples/boards/microbit/sound/` - seems to work fine.

2018-06-04 06:42 UTC, jhedberg approved these changes

2018-06-04 08:24 UTC, carlescufi approved these changes

2018-06-13 16:55 UTC, merged