tests: Bluetooth: Tester: Format BTP cmd/evt/rsp logs as hex
zephyrproject-rtos/zephyr pull request #80740
Opened 2024-11-01 14:04 UTC by Thalley

Since the values are defined as hex, e.g. 0x82, it is easier to compare with the log if they also log them as such.

2024-11-01 14:18 UTC, jhedberg approved these changes

2024-11-01 14:20 UTC, jhedberg requested changes

2024-11-01 14:20 UTC, jhedberg commented on tests/bluetooth/tester/src/btp.c
> +		LOG_DBG("cmd service 0x%02X opcode 0x%02X index 0x%02X", cmd->hdr.service,
The BTP spec uses lower-case hex, so seems like `0x%02x` would be more appropriate. I believe it's the common form in most of the Bluetooth code base too.

2024-11-01 14:27 UTC, jhedberg submitted a review, later dismissed

2024-11-02 19:07 UTC, sjanc commented on tests/bluetooth/tester/src/btp.c
> +		LOG_DBG("cmd service 0x%02x opcode 0x%02x index 0x%02x", cmd->hdr.service,
services are defined as decimal

2024-11-03 22:00 UTC, Thalley commented on tests/bluetooth/tester/src/btp.c
> +		LOG_DBG("cmd service 0x%02x opcode 0x%02x index 0x%02x", cmd->hdr.service,
:upside_down_face:

2024-11-03 22:07 UTC, Thalley commented
@sjanc 
In Zephyr the services are defined as decimal, opcodes and error codes are hex, indexes I'm not sure

In the autopts client everything seems to be logged as decimal, e.g. `Header(svc_id=0, op=128, ctrl_index=255, data_len=0)`, but where services are (luckily) also decimal and opcodes are hex. 

We really should align these so that it's possible to compare not only the definitions, but also the logs. 

Is there a reason why the services are decimal?

2024-11-04 09:13 UTC, sjanc submitted a review, later dismissed
no reason (other than it is defined like this in autopts docs),  we should just switch to hex everywhere

2024-11-04 11:45 UTC, kruithofa submitted a review, later dismissed

2024-11-05 15:57 UTC, Thalley commented
Since https://github.com/auto-pts/auto-pts/pull/1292 got merged in the auto-pts repo, I pulled in the commit to also change the service to be hexidecimal in this PR.

2024-11-05 16:26 UTC, sjanc approved these changes

2024-11-05 19:05 UTC, jhedberg approved these changes

2024-11-06 07:11 UTC, kruithofa approved these changes

2024-11-16 20:24 UTC, merged