drivers: flash: sam: fix flash erase last page
zephyrproject-rtos/zephyr pull request #80800
Opened 2024-11-03 19:40 UTC by bjarki-andreasen

The implementation for erasing pages in the flash_sam.c driver indicated a successful erase after exceeding the last page to be erased successfully. Since the last page has no proceeding page, the succeeded status was not set.

This fix switches around the status to be set as succeeded before erase begins, to have the succeeded status cleared if page unlock or erase fails.

2024-11-03 19:41 UTC, bjarki-andreasen commented
`DNM` until it has been tested on real hardware :)

2024-12-16 07:04 UTC, de-nordic submitted a review, later dismissed

2024-12-18 11:22 UTC, nandojve commented
Hardware tests on sam_v71_xult/samv71q21.
Assuming that tests cover the last sector.

```
*** Booting MCUboot v2.1.0-rc1-171-g5d6471bac184 ***
*** Using Zephyr OS build v4.0.0-2332-ga64d44172fe3 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: primary slot
I: Image index: 0, Swap type: none
E: Unable to find bootable image
*** Booting Zephyr OS build v4.0.0-2332-ga64d44172fe3 ***
Running TESTSUITE flash_page_layout
===================================================================
START - test_erase_single_pages_in_part
I: Erasing section of size 917504 at offset 1048576 controlled by flash-controller@400e0c00
I: Writing across page boundary at 1056768, between page index 134 and 135
I: Writing across page boundary at 1064960, between page index 135 and 136
I: Writing across page boundary at 1073152, between page index 136 and 137
I: Writing across page boundary at 1081344, between page index 137 and 138
I: Writing across page boundary at 1089536, between page index 138 and 139
I: Writing across page boundary at 1097728, between page index 139 and 140
I: Writing across page boundary at 1105920, between page index 140 and 141
I: Writing across page boundary at 1114112, between page index 141 and 142
I: Writing across page boundary at 1122304, between page index 142 and 143
I: Writing across page boundary at 1130496, between page index 143 and 144
I: Writing across page boundary at 1138688, between page index 144 and 145
I: Writing across page boundary at 1146880, between page index 145 and 146
I: Writing across page boundary at 1155072, between page index 146 and 147
I: Writing across page boundary at 1163264, between page index 147 and 148
I: Writing across page boundary at 1171456, between page index 148 and 149
I: Writing across page boundary at 1179648, between page index 149 and 150
I: Writing across page boundary at 1187840, between page index 150 and 151
I: Writing across page boundary at 1196032, between page index 151 and 152
I: Writing across page boundary at 1204224, between page index 152 and 153
I: Writing across page boundary at 1212416, between page index 153 and 154
I: Writing across page boundary at 1220608, between page index 154 and 155
I: Writing across page boundary at 1228800, between page index 155 and 156
I: Writing across page boundary at 1236992, between page index 156 and 157
I: Writing across page boundary at 1245184, between page index 157 and 158
I: Writing across page boundary at 1253376, between page index 158 and 159
I: Writing across page boundary at 1261568, between page index 159 and 160
I: Writing across page boundary at 1269760, between page index 160 and 161
I: Writing across page boundary at 1277952, between page index 161 and 162
I: Writing across page boundary at 1286144, between page index 162 and 163
I: Writing across page boundary at 1294336, between page index 163 and 164
I: Writing across page boundary at 1302528, between page index 164 and 165
I: Writing across page boundary at 1310720, between page index 165 and 166
I: Writing across page boundary at 1318912, between page index 166 and 167
I: Writing across page boundary at 1327104, between page index 167 and 168
I: Writing across page boundary at 1335296, between page index 168 and 169
I: Writing across page boundary at 1343488, between page index 169 and 170
I: Writing across page boundary at 1351680, between page index 170 and 171
I: Writing across page boundary at 1359872, between page index 171 and 172
I: Writing across page boundary at 1368064, between page index 172 and 173
I: Writing across page boundary at 1376256, between page index 173 and 174
I: Writing across page boundary at 1384448, between page index 174 and 175
I: Writing across page boundary at 1392640, between page index 175 and 176
I: Writing across page boundary at 1400832, between page index 176 and 177
I: Writing across page boundary at 1409024, between page index 177 and 178
I: Writing across page boundary at 1417216, between page index 178 and 179
I: Writing across page boundary at 1425408, between page index 179 and 180
I: Writing across page boundary at 1433600, between page index 180 and 181
I: Writing across page boundary at 1441792, between page index 181 and 182
I: Writing across page boundary at 1449984, between page index 182 and 183
I: Writing across page boundary at 1458176, between page index 183 and 184
I: Writing across page boundary at 1466368, between page index 184 and 185
I: Writing across page boundary at 1474560, between page index 185 and 186
I: Writing across page boundary at 1482752, between page index 186 and 187
I: Writing across page boundary at 1490944, between page index 187 and 188
I: Writing across page boundary at 1499136, between page index 188 and 189
I: Writing across page boundary at 1507328, between page index 189 and 190
I: Writing across page boundary at 1515520, between page index 190 and 191
I: Writing across page boundary at 1523712, between page index 191 and 192
I: Writing across page boundary at 1531904, between page index 192 and 193
I: Writing across page boundary at 1540096, between page index 193 and 194
I: Writing across page boundary at 1548288, between page index 194 and 195
I: Writing across page boundary at 1556480, between page index 195 and 196
I: Writing across page boundary at 1564672, between page index 196 and 197
I: Writing across page boundary at 1572864, between page index 197 and 198
I: Writing across page boundary at 1581056, between page index 198 and 199
I: Writing across page boundary at 1589248, between page index 199 and 200
I: Writing across page boundary at 1597440, between page index 200 and 201
I: Writing across page boundary at 1605632, between page index 201 and 202
I: Writing across page boundary at 1613824, between page index 202 and 203
I: Writing across page boundary at 1622016, between page index 203 and 204
I: Writing across page boundary at 1630208, between page index 204 and 205
I: Writing across page boundary at 1638400, between page index 205 and 206
I: Writing across page boundary at 1646592, between page index 206 and 207
I: Writing across page boundary at 1654784, between page index 207 and 208
I: Writing across page boundary at 1662976, between page index 208 and 209
I: Writing across page boundary at 1671168, between page index 209 and 210
I: Writing across page boundary at 1679360, between page index 210 and 211
I: Writing across page boundary at 1687552, between page index 211 and 212
I: Writing across page boundary at 1695744, between page index 212 and 213
I: Writing across page boundary at 1703936, between page index 213 and 214
I: Writing across page boundary at 1712128, between page index 214 and 215
I: Writing across page boundary at 1720320, between page index 215 and 216
I: Writing across page boundary at 1728512, between page index 216 and 217
I: Writing across page boundary at 1736704, between page index 217 and 218
I: Writing across page boundary at 1744896, between page index 218 and 219
I: Writing across page boundary at 1753088, between page index 219 and 220
I: Writing across page boundary at 1761280, between page index 220 and 221
I: Writing across page boundary at 1769472, between page index 221 and 222
I: Writing across page boundary at 1777664, between page index 222 and 223
I: Writing across page boundary at 1785856, between page index 223 and 224
I: Writing across page boundary at 1794048, between page index 224 and 225
I: Writing across page boundary at 1802240, between page index 225 and 226
I: Writing across page boundary at 1810432, between page index 226 and 227
I: Writing across page boundary at 1818624, between page index 227 and 228
I: Writing across page boundary at 1826816, between page index 228 and 229
I: Writing across page boundary at 1835008, between page index 229 and 230
I: Writing across page boundary at 1843200, b [...]

2024-12-18 11:24 UTC, nandojve commented
@bjarki-andreasen ,

The current tests with the samv71 partition cover the last page? If yes, I'm ready to approve.

2024-12-18 11:38 UTC, bjarki-andreasen commented
To erase the last page for that board, change this line https://github.com/zephyrproject-rtos/zephyr/blob/830c1f8134e1da0bbf3ee04e5c2acac3bc178409/tests/drivers/flash/erase_blocks/src/main.c#L24 to 
`DT_NODELABEL(scratch_partition)` and run the suite again :) we are looking for:
```
I: Erasing page at 2088960 of size 8192 with index 255
 PASS - test_erase_single_pages_in_part in 9.084 seconds
```
the board has a scratch partition at the end of the flash area :)

2024-12-18 12:12 UTC, nandojve commented
Running test using the scratch_partition

```
*** Booting MCUboot v2.1.0-rc1-171-g5d6471bac184 ***
*** Using Zephyr OS build v4.0.0-2332-ga64d44172fe3 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: primary slot
I: Image index: 0, Swap type: none
E: Unable to find bootable image
*** Booting Zephyr OS build v4.0.0-2332-ga64d44172fe3 ***
Running TESTSUITE flash_page_layout
===================================================================
START - test_erase_single_pages_in_part
I: Erasing section of size 131072 at offset 1966080 controlled by flash-controller@400e0c00
I: Writing across page boundary at 1974272, between page index 246 and 247
I: Writing across page boundary at 1982464, between page index 247 and 248
I: Writing across page boundary at 1990656, between page index 248 and 249
I: Writing across page boundary at 1998848, between page index 249 and 250
I: Writing across page boundary at 2007040, between page index 250 and 251
I: Writing across page boundary at 2015232, between page index 251 and 252
I: Writing across page boundary at 2023424, between page index 252 and 253
I: Writing across page boundary at 2031616, between page index 253 and 254
I: Writing across page boundary at 2039808, between page index 254 and 255
I: Writing across page boundary at 2048000, between page index 255 and 256
I: Writing across page boundary at 2056192, between page index 256 and 257
I: Writing across page boundary at 2064384, between page index 257 and 258
I: Writing across page boundary at 2072576, between page index 258 and 259
I: Erasing page at 1966080 of size 8192 with index 246
I: Erasing page at 1974272 of size 8192 with index 247
I: Erasing page at 1982464 of size 8192 with index 248
I: Erasing page at 1990656 of size 8192 with index 249
I: Erasing page at 1998848 of size 8192 with index 250
I: Erasing page at 2007040 of size 8192 with index 251
I: Erasing page at 2015232 of size 8192 with index 252
I: Erasing page at 2023424 of size 8192 with index 253
I: Erasing page at 2031616 of size 8192 with index 254
I: Erasing page at 2039808 of size 8192 with index 255
I: Erasing page at 2048000 of size 8192 with index 256
I: Erasing page at 2056192 of size 8192 with index 257
I: Erasing page at 2064384 of size 8192 with index 258
I: Erasing page at 2072576 of size 8192 with index 259

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/erase_blocks/src/main.c:184: test_flash_erase_page: (flash_erase(flash_contr)
Failed to erase page
 FAIL - test_erase_single_pages_in_part in 1.118 seconds
===================================================================
START - test_write_across_page_boundaries_in_part
I: Erasing section of size 131072 at offset 1966080 controlled by flash-controller@400e0c00
I: Writing across page boundary at 1974272, between page index 246 and 247
I: Writing across page boundary at 1982464, between page index 247 and 248
I: Writing across page boundary at 1990656, between page index 248 and 249
I: Writing across page boundary at 1998848, between page index 249 and 250
I: Writing across page boundary at 2007040, between page index 250 and 251
I: Writing across page boundary at 2015232, between page index 251 and 252
I: Writing across page boundary at 2023424, between page index 252 and 253
I: Writing across page boundary at 2031616, between page index 253 and 254
I: Writing across page boundary at 2039808, between page index 254 and 255
I: Writing across page boundary at 2048000, between page index 255 and 256
I: Writing across page boundary at 2056192, between page index 256 and 257
I: Writing across page boundary at 2064384, between page index 257 and 258
I: Writing across page boundary at 2072576, between page index 258 and 259
 PASS - test_write_across_page_boundaries_in_part in 0.586 seconds
===================================================================
TESTSUITE flash_page_layout failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  50.00% [flash_page_layout]: pass = 1, fail = 1, skip = 0, total = 2 duration = 1.704 seconds
 - FAIL - [flash_page_layout.test_erase_single_pages_in_part] duration = 1.118 seconds
 - PASS - [flash_page_layout.test_write_across_page_boundaries_in_part] duration = 0.586 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED

```

2024-12-18 12:45 UTC, bjarki-andreasen commented
well that sucks :)

2025-01-03 06:49 UTC, nandojve commented
Hi @bjarki-andreasen ,

I was wondering if you had time to look on it again.

2025-01-14 18:01 UTC, nandojve commented
friendly ping : )

2025-01-15 11:43 UTC, bjarki-andreasen commented
I'm getting a dev kit in the coming days, then I will fix it properly

2025-01-17 16:46 UTC, bjarki-andreasen commented
I extended the test suite to include board overlays so we can adjust the slot1 partition to extend to the very end of the flash area. With this, and running the test suite both with and without MCU boot on an sam4e_xpro, it runs without error, erasing the last page successfully:
```
I: Writing across page boundary at 1044480, between page index 258 and 259
 PASS - test_write_across_page_boundaries_in_part in 3.587 seconds
```
I did not need to change the driver, from what I can tell the bug was indeed fixed :)

2025-01-25 09:57 UTC, nandojve commented
Hi @bjarki-andreasen ,

sam4e_xpro, as you mentioned passes
```
SUITE PASS - 100.00% [flash_page_layout]: pass = 2, fail = 0, skip = 0, total = 2 duration = 9.435 seconds
 - PASS - [flash_page_layout.test_erase_single_pages_in_part] duration = 6.219 seconds
 - PASS - [flash_page_layout.test_write_across_page_boundaries_in_part] duration = 3.216 seconds
```

sam_v71_xult, as I mentioned, do not passes
```
SUITE FAIL -  50.00% [flash_page_layout]: pass = 1, fail = 1, skip = 0, total = 2 duration = 15.516 seconds
 - FAIL - [flash_page_layout.test_erase_single_pages_in_part] duration = 10.253 seconds
 - PASS - [flash_page_layout.test_write_across_page_boundaries_in_part] duration = 5.263 seconds
```

if you don't mind to include the below patch, it helps to test samv71

```diff
+tests/drivers/flash/erase_blocks/boards/sam_v71_xult_samv71q21.overlay
+/*
+ * Copyright (c) 2025 Gerson Fernando Budke <nandojve@gmail.com>
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+&flash0 {
+	partitions {
+		/delete-node/ storage_partition;
+
+		slot1_partition: partition@100000 {
+			label = "image-1";
+			reg = <0x00100000 0x100000>;
+		};
+	};
+};
```

2025-01-27 04:09 UTC, bjarki-andreasen commented
> Hi @bjarki-andreasen ,
> 
> sam4e_xpro, as you mentioned passes
> ```
> SUITE PASS - 100.00% [flash_page_layout]: pass = 2, fail = 0, skip = 0, total = 2 duration = 9.435 seconds
>  - PASS - [flash_page_layout.test_erase_single_pages_in_part] duration = 6.219 seconds
>  - PASS - [flash_page_layout.test_write_across_page_boundaries_in_part] duration = 3.216 seconds
> ```
> 
> sam_v71_xult, as I mentioned, do not passes
> ```
> SUITE FAIL -  50.00% [flash_page_layout]: pass = 1, fail = 1, skip = 0, total = 2 duration = 15.516 seconds
>  - FAIL - [flash_page_layout.test_erase_single_pages_in_part] duration = 10.253 seconds
>  - PASS - [flash_page_layout.test_write_across_page_boundaries_in_part] duration = 5.263 seconds
> ```
> 
> if you don't mind to include the below patch, it helps to test samv71
> 
> ```diff
> +tests/drivers/flash/erase_blocks/boards/sam_v71_xult_samv71q21.overlay
> +/*
> + * Copyright (c) 2025 Gerson Fernando Budke <nandojve@gmail.com>
> + *
> + * SPDX-License-Identifier: Apache-2.0
> + */
> +
> +&flash0 {
> +	partitions {
> +		/delete-node/ storage_partition;
> +
> +		slot1_partition: partition@100000 {
> +			label = "image-1";
> +			reg = <0x00100000 0x100000>;
> +		};
> +	};
> +};
> ```

I will add the overlay, i can't test it howevergiven I d8n't have that hardware, could it be a dead flash page or something on your board, or is the flash layout maybe different fro. The sam4? Don't get why its failing

2025-01-27 07:05 UTC, nandojve commented
I'm checking is there is something different on the flash controller that could fail on the test_erase_single_pages_in_part. If I can not find anything that explains we can assume it could be a page problem as you mention : )

2025-01-28 17:42 UTC, nandojve commented
Hi @bjarki-andreasen ,

I was testing and enabled debug on the driver. I noted this:

1- Given the number is DECon the tests it is harder to detected that something goes wrong.
My suggestion is that you reformat to HEX.

If I understood correctly, the below should erase all the 1MiB but it is not. I saw that this is OK for the test_write_across_page_boundaries_in_part but still not evaluate the last sector!

```
I: Erasing section of size 1048576 at offset 1048576 controlled by flash-controller@400e0c00
D: Erasing sector from 0x100000 to 0x200000
D: Erasing page at 0x100000 of size 0x2000
D: Erasing page at 0x102000 of size 0x2000
D: Erasing page at 0x104000 of size 0x2000
...
D: Erasing page at 0x1f6000 of size 0x2000
D: Erasing page at 0x1f8000 of size 0x2000
D: Erasing page at 0x1fa000 of size 0x2000
ends here
```

0x1fa000 + 0x2000 => 1fc000
It is missing 0x4000

2- Look the debug here. The device do not even call the Erasing function on the driver.
```
I: Erasing page at 2056192 of size 8192 with index 257
D: Erasing sector from 0x1f6000 to 0x1f8000
D: Erasing page at 0x1f6000 of size 0x2000
I: Erasing page at 2064384 of size 8192 with index 258
D: Erasing sector from 0x1f8000 to 0x1fa000
D: Erasing page at 0x1f8000 of size 0x2000
I: Erasing page at 2072576 of size 8192 with index 259

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/fl
```

2072576 is 1fa000. So, I assume there are something wrong in some place and that could be the issue when it tries to write, is this correct?

3- SAM4E erase 4k and SAMV71 erase 8k.
I tried to increase the SAM4E to 8k but software still using 4k

4- There are some restrictions on the erase page size.
The common value to all series and all sectors is 16 x 512 (pages x bytes_per_page)

2025-01-28 17:44 UTC, nandojve requested changes

2025-01-28 17:44 UTC, nandojve commented on tests/drivers/flash/erase_blocks/boards/sam4e_xpro_sam4e16e.overlay
> + * Copyright (c) 2025 Nordic Semiconductor ASA
BTW, is this correct?

2025-03-05 17:03 UTC, nandojve commented
Hi @bjarki-andreasen ,

As you mentioned in the pvt chat _I think I found it, erase-blocks = <&eefc 8 2048>, <&eefc 252 8192>; is incorrect, should be erase-blocks = <&eefc 8 2048>, <&eefc 254 8192>; see samx7xx21.dtsi_ .

I tested and now it passes on SAMV7 too.
Thank you so much for your effort on this.

Please, send the final update : )

2025-03-05 17:25 UTC, nandojve approved these changes

2025-03-10 10:13 UTC, pdgendt approved these changes

2025-03-10 14:02 UTC, merged