tests: kernel: mutex.error needs CONFIG_USERSPACE
zephyrproject-rtos/zephyr pull request #80851
Opened 2024-11-04 13:45 UTC by RobinKastberg

This test fails with CONFIG_USERSPACE=n
Since this test checks for error conditions
requiring userspace, we need to require it.

To reproduce
```
user@2910b946914f:/workdir/zephyr$ scripts/twister -p nrf52840dk/nrf52840 -T tests/kernel/mutex/mutex_error_case/ -x CONFIG_USERSPACE=n --hardware-map mapnrf.yml --device-testing --verbose
INFO    - 1/1 nrf52840dk/nrf52840       tests/kernel/mutex/mutex_error_case/kernel.mutex.error  FAILED Failed (device: 001050277191, 2.720s)
ERROR   - see: /workdir/zephyr/twister-out/nrf52840dk_nrf52840/tests/kernel/mutex/mutex_error_case/kernel.mutex.error/handler.log
```
[handler.log](https://github.com/user-attachments/files/17618849/handler.log)

This is all new to me, but this change matches thread_error_case which works as I expect.

2024-11-04 16:04 UTC, cfriedt approved these changes

2024-11-04 17:12 UTC, dcpleung requested changes
This is not the right fix.

This test will run on any platform that is capable of supporting userspace. The `prj.conf` explicitly enable `CONFIG_TEST_USERSPACE` which in turn enables `CONFIG_USERSPACE`. Any platform should never enable `CONFIG_USERSPACE` by itself as it is a per-application configuration. This is a legitimate failure.

2024-11-04 17:32 UTC, RobinKastberg commented
> This is not the right fix.

Sorry I don't follow. 
The test looks for error codes which only exists if `CONFIG_USERSPACE` is set. Maybe the first testcase can be salvaged ( look for `K_ERR_CPU_EXCEPTION` instead of `K_ERR_KERNEL_OOPS`, but the rest of testcases relies on CONFIG_USERSPACE mechanisms to detect error code.
How would a right fix look like? Maybe I can look at it.

My use case might be worth explaining as well. I am trying to port Zephyr to IAR toolchain, and currently `CONFIG_USERSPACE=y` is broken with `CMAKE_LINKER_GENERATOR=y`. This means I am trying to run tests with `CONFIG_USERSPACE=n`. I tried overriding `CONFIG_ARCH_HAS_USERSPACE` in toolchain config but failed.

2024-11-04 17:44 UTC, cfriedt commented
I'm a bit confused as well - I do see `filter: CONFIG_USERSPACE` in a few tests on `main`, so I assumed that was a new thing, but maybe that was the wrong assumption.

2024-11-04 17:46 UTC, cfriedt commented
@RobinKastberg - there actually needs this be some non-trivial work done on the POSIX API to make it work seamlessly with `CONFIG_USERSPACE=y` anyway (there is a thread on Discord in the `#posix` channel). So it might be best to close this for the time being.

2024-11-04 18:02 UTC, dcpleung commented
Those tests should really filter for `CONFIG_ARCH_HAS_USERSPACE` and then enable `CONFIG_TEST_USERSPACE` in `prj.conf`.

If your platform cannot support userspace, it is better to exclude it from the test, or provide a per-board config override to disable both `CONFIG_TEST_USERSPACE` and `CONFIG_USERSPACE`.

2024-11-04 18:16 UTC, RobinKastberg commented
@dcpleung the platform supports `CONFIG_USERSPACE=y` just fine, however the linker scripts I am using do not. Do you suggest the toolchain to set `CONFIG_ARCH_HAS_USERSPACE=n`

2024-11-04 20:09 UTC, dcpleung commented
I need some clarification:
1. Did you try running this via the Zephyr SDK?
2. Does the test only fail when using IAR toolchain?
3. Are you using a custom linker script that is not provided by default in Zephyr?

2024-11-05 08:46 UTC, RobinKastberg commented
@dcpleung 
1) sorry I don't understand your question, am I not using Zephyr SDK? I am using official dev container. The commandline above reproduces the issue in a default dev container with default zephyr from main.
2) The tests fails both with IAR and default toolchain since the test error codes requires `CONFIG_USERSPACE=y`
3) The tests fails both with custom linker scripts and not since the test error codes requires `CONFIG_USERSPACE=y`

Please answer my questions:
1) How would a right fix look like? If this is a legitimate failure.
2) Your suggested fix is already the way the test is "working". But this will make the test fail when running twister with `-x CONFIG_USERSPACE=n`. If a test is broken in a certain configuration, is that not why it should be filtered out?
3) You say "This test will run on any platform that is capable of supporting userspace.". How are kernel objects verified if `CONFIG_USERSPACE=n`, I don't really see a way of salvaging the tests and making it `CONFIG_USERSPACE`-agnostic

2024-11-05 10:58 UTC, cfriedt commented
@RobinKastberg - can you please create a bug report using the template? Please make sure to paste the contents of handler.log into the description rather than the link.

Thanks!

2024-11-05 13:26 UTC, RobinKastberg commented
@cfriedt https://github.com/zephyrproject-rtos/zephyr/issues/80915

2024-11-05 17:28 UTC, dcpleung commented
As I commented on #80915, the `mutex_error_case` test requires userspace, and will fail without userspace.

@anangl @masz-nordic: is nrf52840 working on your end for this test?

2024-11-08 09:28 UTC, RobinKastberg commented
@dcpleung so should it not be filtered out without userspace?

2024-11-08 17:21 UTC, dcpleung commented
A proper way is to do `platform_exclude` excluding this board for testing with a comment on why. Even better if you have filed a bug and put the issue number in the comment.

The filtering here is to make sure we test userspace for configurations that advertise userspace support. If userspace is broken for this board, it should be fixed, and not be hidden by forcing `CONFIG_USERSPACE=n`.

2024-11-08 17:39 UTC, RobinKastberg commented
@dcpleung I have submitted a bug, but userspace is not broken for this board, it works just fine. I get the feeling you have not read my explanations closely.

I am not trying to force `CONFIG_USERSPACE=n`.

I am trying to filter out the test when `CONFIG_USERSPACE=n` since the test is broken when `CONFIG_USERSPACE=n`. This has nothing to do with toolchain/platform/architecture.

The test will run just fine when `CONFIG_USERSPACE=y` both with and without my fix.

2024-11-08 18:01 UTC, dcpleung commented
I want to re-iterate the idea of filtering: the configuration advertises userspace support so the test needs to run it with userspace enabled for test coverage, especially for a userspace only test. We do not want to get into a situation where the whole configuration advertises userspace support, and yet the SoC/board forces userspace to be disabled. The decision whether to enable userspace should rest on the app, in this case, this test. From what I can tell so far, your configuration advertises userspace support and yet you are forcibly disabling userspace. That's why you are getting into this situation where you are running a userspace only test with userspace disabled.

2024-11-08 21:03 UTC, dcpleung commented
> > I want to re-iterate the idea of filtering: the configuration advertises userspace support so the test needs to run it with userspace enabled for test coverage, especially for a userspace only test.
> I agree! But wouldn't complete test coverage also mean running the same test with userspace disabled? (not for this case, but there are many such tests out there)

Yes, that's why lots of tests do not enable userspace. And plenty of testsuites have extra tests for userspace so they test both non-userspace and userspace.

> > We do not want to get into a situation where the whole configuration advertises userspace support, and yet the SoC/board forces userspace to be disabled.
> I don't understand what you mean here

This is where one tries to override userspace support in board and/or SoC configurations. We do not want to do that. This is just FYI.

> A more general question: Maybe I am just misunderstand things, but I reason something like this:
> 
> _Since applications can disable userspace, wouldn't wanting to run tests without userspace be natural, and reasonable for test coverage?_

I think you misunderstand what this test is for. This test is explicitly done to test error conditions for user threads using mutexes. And that we catch those error conditions without crashing everything, and also not causing kernel panic which halts any operations. You absolutely cannot run this test without userspace.

Also, some tests are written in ways which require certain configurations. What you are trying to do here, by disabling userspace, is outside of what the test is written for. Once you go outside that boundary, any talking of coverage is meaningless, because the test itself is no longer valid and is not serving its purpose of "testing".

2024-11-09 07:57 UTC, RobinKastberg commented
> Also, some tests are written in ways which require certain configurations. What you are trying to do here, by disabling userspace, is outside of what the test is written for. Once you go outside that boundary, any talking of coverage is meaningless, because the test itself is no longer valid and is not serving its purpose of "testing".

And is this not why it should be filtered on CONFIG_USERSPACE rather than CONFIG_ARCH_HAS_USERSPACE?

2024-11-12 15:39 UTC, RobinKastberg commented
I have multiple reasons:
* because `CONFIG_USERSPACE=y` is incompatible with `CONFIG_CMAKE_LINKER_GENERATOR=y`
* since `CONFIG_ARCH_HAS_USERSPACE=y` and `CONFIG_USERSPACE=n` is a valid application/zephyr configuration, it should be a valid test suite configuration, since the way zephyr works/builds is vastly different.
* We are implementing IAR toolchain support and "fudging the tests so they pass or are skipped so the report looks good" would be helpful. Since this test has no way of succeeding when CONFIG_USERSPACE=n I see no reason for it to fail and make the report look bad. 
* There are similar tests (thread_error_case) that works like this and it works like I would expect it too. For me it looks like the test depends on `CONFIG_USERSPACE` rather than if the architecture has it or not. This is not expected behaviour.
* I am new in Zephyr and thought this was an easy fix for a beginner like me (boy was I wrong)

But it looks like I am misunderstanding something about Kconfig/twister settings here,  it seems like this is not expected behaviour for me, but is to you. 
My expectations: I should be able to run `scripts/twister -T tests/kernel/mutex/ -x CONFIG_USERSPACE=n` and tests pass or get filtered.
Your expectations: I should not be able to run `scripts/twister -T tests/kernel/mutex/ -x CONFIG_USERSPACE=n` because this is "fudging the tests so they pass or are skipped so the report looks good."?

Please suggest a change or close this PR/issue if I am simply misunderstanding and this is the intended behavior.

2024-11-12 17:53 UTC, dcpleung commented
> * because `CONFIG_USERSPACE=y` is incompatible with `CONFIG_CMAKE_LINKER_GENERATOR=y`

I don't think there is anything fundamental which makes them incompatible. https://github.com/zephyrproject-rtos/zephyr/blob/d9ef4b7e69905a0781c9203626ab647738c9b3ef/CMakeLists.txt#L1286 is configuring linker scripts when `CONFIG_USERSPACE` is enabled. So this combined configuration is supported.

> * since `CONFIG_ARCH_HAS_USERSPACE=y` and `CONFIG_USERSPACE=n` is a valid application/zephyr configuration, it should be a valid test suite configuration, since the way zephyr works/builds is vastly different.

That is not correct. For application that can be a valid configuration, because after all it is the application configuration. And the application dictates what it needs. However, the tests are written to certain configurations. In a sense, tests can be considered applications (since they are built the same way). And if they say they need userspace enabled, userspace needs to be enabled. You forcing `CONFIG_USERSPACE=n` does not change the fact that the tests need userspace enabled for proper functionality, and for the tests to be valid tests.

> * We are implementing IAR toolchain support and "fudging the tests so they pass or are skipped so the report looks good" would be helpful. Since this test has no way of succeeding when CONFIG_USERSPACE=n I see no reason for it to fail and make the report look bad.

But here, you are forcing an invalid configuration on the tests. When it fails as expected, you then try (in a sense) changing the tests to make it look good. This should not have been an issue in the first place if you have never forced an invalid configuration to run.

> * There are similar tests (thread_error_case) that works like this and it works like I would expect it too. For me it looks like the test depends on `CONFIG_USERSPACE` rather than if the architecture has it or not. This is not expected behaviour.

`thread_error_case` is incorrect on its filtering and that needs to be fixed.

> But it looks like I am misunderstanding something about Kconfig/twister settings here, it seems like this is not expected behaviour for me, but is to you. My expectations: I should be able to run `scripts/twister -T tests/kernel/mutex/ -x CONFIG_USERSPACE=n` and tests pass or get filtered. Your expectations: I should not be able to run `scripts/twister -T tests/kernel/mutex/ -x CONFIG_USERSPACE=n` because this is "fudging the tests so they pass or are skipped so the report looks good."?

As said above, you are forcing invalid configurations on the tests. They will fail. This is not even fudging the test, as the failures are all caused by forcing the tests to run on invalid configuration, outside of the parameters of their designs.

2024-11-12 19:04 UTC, RobinKastberg commented
> > * because `CONFIG_USERSPACE=y` is incompatible with `CONFIG_CMAKE_LINKER_GENERATOR=y`
> 
> I don't think there is anything fundamental which makes them incompatible.

Since the linker features needed aren't implemented they are incompatible, why this is not expressed in Kconfig I don't know.

> In a sense, tests can be considered applications (since they are built the same way). And if they say they need userspace enabled, userspace needs to be enabled. You forcing `CONFIG_USERSPACE=n` does not change the fact that the tests need userspace enabled for proper functionality, and for the tests to be valid tests.

Yes, but the test doesn't say it needs userspace enabled, it says it needs an architecture with userspace enabled, which is clearly not the same thing. I would expect a valid app configuration to be a valid test configuration.

> But here, you are forcing an invalid configuration on the tests. When it fails as expected, you then try (in a sense) changing the tests to make it look good. This should not have been an issue in the first place if you have never forced an invalid configuration to run.

This is not for fun, but by necessity for now, if/when we fix `CONFIG_USERSPACE=y` this will be a non-issue for us, but I still think it is interesting to be able to run test suites in valid configurations without unnecessary failures.

> As said above, you are forcing invalid configurations on the tests. They will fail. This is not even fudging the test, as the failures are all caused by forcing the tests to run on invalid configuration, outside of the parameters of their designs.

If this is not a reason to filter out the test, I don't know what would be.

2024-11-12 20:20 UTC, dcpleung commented
Let me re-iterate:

1. This test is testing userspace only feature.
2. It looks for any platforms that advertise userspace support, namely `CONFIG_ARCH_HAS_USERSPACE`.
3. Enable userspace in the test (application) configuration: `prj.conf` with `CONFIG_TEST_USERSPACE=y` and thus `CONFIG_USERSPACE=y`.
4. Run the test.

Let me put it another way, `CONFIG_USERSPACE` is a feature switch. An application can turn it on or off as it needs for proper functionality. `CONFIG_ARCH_HAS_USERSPACE` is a capability advertisement. We should filter on capability to figure out if it can run a particular test.

`CONFIG_ARCH_HAS_USERSPACE=y` and `CONFIG_USERSPACE=n` could be a valid configuration in other tests, but NOT in this case. Just because it is valid in `hello_world` does not mean it is valid here. You need to look at the tests and understand what are actually being tested. A blanket statement like "it is a valid configuration" is not going to work here. And to re-iterate: that is not a correct statement for this test.

2024-12-11 09:00 UTC, RobinKastberg commented
This is not the right fix.

2024-12-11 09:00 UTC, closed without merging