boards: common: bossac: Fix bossac flash script.
zephyrproject-rtos/zephyr pull request #8100
Opened 2018-06-01 06:49 UTC by AdithyaBaglody

The flash script was broken after the cmake changes.
Updated the path needed for the flash scripts.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

2018-06-01 07:07 UTC, SebastianBoe requested changes

2018-06-01 07:07 UTC, SebastianBoe commented on boards/common/bossac.board.cmake
> +board_finalize_runner_args(bossac "--bossac=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/bossac")
The BOARD should be agnostic to the SDK/toolchain used.

So this should be:

--bossac=${BOSSAC}

and then some toolchain script should set BOSSAC appropriately. Perhaps from zephyr/cmake/toolchain/zephyr.cmake

2018-06-01 10:39 UTC, SebastianBoe approved these changes

2018-06-01 20:19 UTC, MaureenHelm commented
OpenOCD is also in the sdk, but found a different way in `cmake/host-tools.cmake`. Can we handle bossac the same way to be consistent?

2018-06-04 05:41 UTC, AdithyaBaglody commented
@MaureenHelm Made the bossac consistent with how openocd is used.

2018-06-04 15:47 UTC, nashif approved these changes

2018-06-04 17:15 UTC, MaureenHelm approved these changes

2018-06-04 17:15 UTC, merged