Add mcxc444 adc support
zephyrproject-rtos/zephyr pull request #81040
Opened 2024-11-07 03:34 UTC by NeilChen93

Add mcxc444 adc support

2024-11-08 14:37 UTC, danieldegrasse submitted a review, later dismissed

2024-11-20 19:05 UTC, danieldegrasse submitted a review, later dismissed

2024-12-17 21:18 UTC, bjarki-andreasen requested changes
a little nit and a typo, otherwise looks great :)

2024-12-17 21:18 UTC, bjarki-andreasen commented on samples/drivers/adc/adc_sequence/sample.yaml
> +      - frdm_mcxc242
actually, was probably meant to be `frdm_mcxc444` :) please update

2024-12-17 21:18 UTC, bjarki-andreasen commented on boards/nxp/frdm_mcxc444/frdm_mcxc444-pinctrl.dtsi
> +				<ADC0_SE3_PTE22>;
need one more space here to align:
```
<ADC0_SE0_PTE20>,
<ADC0_SE3_PTE22>;
```

2024-12-18 03:39 UTC, kartben commented on samples/drivers/adc/adc_sequence/sample.yaml
> +      - frdm_mcxc242
Yeah no, dropping is fine. :)
There is no point in adding this as the list could virtually grow endlessly (see https://docs.zephyrproject.org/latest/samples/sample_definition_and_criteria.html#twister-should-be-able-to-build-every-sample). It's a sample, not a test.

2024-12-18 13:08 UTC, bjarki-andreasen requested changes
tiny adjustment as suggested by @kartben and we are good to go :)

2024-12-18 13:08 UTC, bjarki-andreasen commented on samples/drivers/adc/adc_dt/sample.yaml
> +      - frdm_mcxc444
please drop it as suggested by @kartben :) my mistake

2024-12-18 13:08 UTC, bjarki-andreasen commented on samples/drivers/adc/adc_sequence/sample.yaml
> +      - frdm_mcxc444
also drop this one

2025-01-08 14:05 UTC, bjarki-andreasen approved these changes

2025-01-14 16:37 UTC, danieldegrasse approved these changes

2025-01-14 16:57 UTC, merged