Enable NETC support for i.MX95 EKV M7
zephyrproject-rtos/zephyr pull request #81113
Opened 2024-11-08 04:39 UTC by yangbolu1991

This PR is to enable NETC support for i.MX95 EKV M7.
There are dependencies of this PR.
- hal_nxp: https://github.com/zephyrproject-rtos/hal_nxp/pull/462
- scmi: https://github.com/zephyrproject-rtos/zephyr/pull/77437

Current PR already cherry-pick scmi changes and updated west.yml to address the dependency for CI.
And will drop them once they are merged.

Thanks.

2024-12-16 09:40 UTC, yangbolu1991 commented
Updated to v2. Changes,

- Rebased on latest scmi patches. And addressed west.yml conflict.

Thanks.

2025-01-15 17:53 UTC, mmahadevan108 commented on dts/arm/nxp/nxp_imx95_m7.dtsi
> +#include <zephyr/dt-bindings/power/imx95_power.h>
I don't see any `macro`  from this header used. Is this needed?

2025-01-15 19:05 UTC, mmahadevan108 commented
Please rebase and update west.yml

2025-01-15 19:06 UTC, mmahadevan108 requested changes
Needs to be sequenced behind https://github.com/zephyrproject-rtos/zephyr/pull/83827

@yangbolu1991  I merged the HAL side so please update your PR to point to the new SHA. When the gating PR merges I'll clear my CR

2025-01-15 22:21 UTC, mmahadevan108 submitted a review, later dismissed
I have rebased this PR.

2025-01-15 23:14 UTC, dleach02 approved these changes, later dismissed

2025-01-16 01:58 UTC, mmahadevan108 commented
Please help address the CI failures.

2025-01-17 04:46 UTC, yangbolu1991 commented on dts/arm/nxp/nxp_imx95_m7.dtsi
> +#include <zephyr/dt-bindings/power/imx95_power.h>
Let me remove it. It's true IP node hadn't used it now.
It's used in soc.c for power init now.

2025-01-17 04:52 UTC, yangbolu1991 commented
Sory, I have an update on the PR.

Updated to v3. Changes,

- Converted to get irq for NETC from dts node instead of IRQ MACRO defined in device header. This required irqsteer driver support. So it depends on https://github.com/zephyrproject-rtos/zephyr/pull/84017
- Updated hal_nxp for some fix-up. Depend on https://github.com/zephyrproject-rtos/hal_nxp/pull/499
- Removed imx95_power.h including in dtsi as it's not used now.

Thank you very much.

2025-01-21 10:58 UTC, yangbolu1991 commented
Updated to v4. Changes include,

- Rebased.
- Added one more patch to exclude tests not suit for multilevel interrupts.

Dependency (ported here for CI):
- https://github.com/zephyrproject-rtos/zephyr/pull/84017
- https://github.com/zephyrproject-rtos/hal_nxp/pull/499

Thank you very much.

2025-03-03 09:32 UTC, yangbolu1991 commented
Updated to v5. Changes include,
- Rebased as some changes already merged, and the dependency PR had update.

Dependency:
- https://github.com/zephyrproject-rtos/zephyr/pull/84017
- https://github.com/zephyrproject-rtos/hal_nxp/pull/499

Thank you very much.

2025-03-14 15:36 UTC, dleach02 commented
@yangbolu1991 please rebase your PR

2025-03-14 15:58 UTC, mmahadevan108 commented
@yangbolu1991, please rebase and update `west.yml`

2025-03-17 08:55 UTC, yangbolu1991 commented
Updated to v6. Changes,
- Rebased.

But It looks like there is twister issues on code base.

Thanks.

2025-03-18 03:18 UTC, yangbolu1991 commented
Rebased to try CI again.
Thanks.

2025-03-19 08:16 UTC, yangbolu1991 commented
Rebased, thanks.

2025-03-20 14:58 UTC, mmahadevan108 commented
@JiafeiPan , can you help review this PR.

2025-03-20 15:38 UTC, mmahadevan108 commented on boards/nxp/imx95_evk/board.c
> +{
Please look at the changes made as part of this PR: https://github.com/zephyrproject-rtos/zephyr/pull/85605 and update this implementation accordingly.

2025-03-21 06:42 UTC, JiafeiPan commented on boards/nxp/imx95_evk/imx95_evk_mimx9596_m7.dts
> +	status = "okay";
I suggest to disable all related nodes by default in board dts, and enable them in dts overlay, then can use "`-DEXTRA_DTC_OVERLAY_FILE=enet1.overlay`" if needed.

2025-03-24 02:40 UTC, yangbolu1991 commented on boards/nxp/imx95_evk/board.c
> +{
Actually the soc/board early init hooks are not able to be used for the SoC based on SCMI APIs.
I had commented in file.

```
/*
 * Because platform is using ARM SCMI, drivers like scmi, mbox etc. are
 * initialized during PRE_KERNEL_1. Common init hooks is not able to use.
 * SoC early init and board early init could be run during PRE_KERNEL_2 instead.
 */
```

2025-03-24 03:31 UTC, yangbolu1991 commented on boards/nxp/imx95_evk/imx95_evk_mimx9596_m7.dts
> +	status = "okay";
Thanks Jiafei. Will do that.

2025-03-24 03:33 UTC, yangbolu1991 commented
Updated to v7. Changes include,
- Created overlay file for enetc psi0 instead, and doc it.

Thanks.

2025-03-24 04:09 UTC, JiafeiPan commented on boards/nxp/imx95_evk/enetc_psi0.overlay
> +/*
We may have the other overlay for other features, I suggest to put all of them in "dts" sub-directory just like what the other platforms are using.

2025-03-24 04:09 UTC, JiafeiPan commented on boards/nxp/imx95_evk/imx95_evk_mimx9596_m7.dts
> +	pinctrl-names = "default";
I know these nodes are disabled in soc dts, but I prefer to put explict "disabled" status for these nodes to make it more readable for the user to know it is disabled currently.

2025-03-24 06:12 UTC, yangbolu1991 commented on boards/nxp/imx95_evk/imx95_evk_mimx9596_m7.dts
> +	pinctrl-names = "default";
okay, updated.
Thanks.

2025-03-24 06:13 UTC, yangbolu1991 commented
Updated to v8. Changes include,
- moved overlay file to dts/ directory.
- put explicit disabled status in dts.

Thanks.

2025-03-24 13:34 UTC, mmahadevan108 approved these changes

2025-03-24 13:42 UTC, JiafeiPan approved these changes

2025-03-24 15:08 UTC, dleach02 approved these changes

2025-03-25 04:59 UTC, merged