boards/arduino/portenta_h7: enable USART1 on M4
zephyrproject-rtos/zephyr pull request #81278
Opened 2024-11-12 13:26 UTC by fkokosinski

Right now, USART1 is enabled on the M7 target variant by default, leaving M4 without a UART to use; this is the way this port was originally contributed.

Since then, USB was enabled on M7, changing the console backend from USART1 to USB CDC ACM; the M4 target was left unchanged.

This PR enabled USART1 on the M4 variant and disabled it on the M7 variant, so that the M4 variant can use it as its console backend.

Note that, for the M4 variant, USART1 has been assigned to `zephyr,console` and `zephyr,shell-uart` since this port was contributed, even though USART1 was always disabled on M4.

Original port: https://github.com/zephyrproject-rtos/zephyr/pull/45221/files#diff-f358a7cdc75425a345797de2ad620f03e84bd5fff885583e610c96f0b7a67cc5
USART1 originally used by M7: https://github.com/zephyrproject-rtos/zephyr/pull/45221/files#diff-7677cf951c934ab01432008243aa5d8a0b73c40a606b9fd6d207d883b3ad7490
M7 switches from USART1 to CDC ACM: https://github.com/zephyrproject-rtos/zephyr/commit/d86334365f8880319744561fffa977d4c9ced402#diff-5754d71b0f03ec5deb0c225ef1c776e934ddc7909856a757b75971dfa693ca7e

2024-11-19 10:28 UTC, fkokosinski commented
Hey @erwango, could you take a look at this PR since it's a STM-based board?

2024-11-21 15:16 UTC, erwango requested changes
Otherwise LGTM

2024-11-21 15:16 UTC, erwango commented on boards/arduino/portenta_h7/arduino_portenta_h7_stm32h747xx_m4_defconfig
> +CONFIG_UART_LINE_CTRL=y
`UART_LINE_CTRL` is not implemented on STM32 uart driver.

2024-11-22 09:48 UTC, erwango approved these changes

2024-11-22 09:52 UTC, pillo79 approved these changes
Thank you!

2024-11-22 13:25 UTC, merged