tests: benchmarks: sys_kernel: Exclude arduino_due.
zephyrproject-rtos/zephyr pull request #8135
Opened 2018-06-04 06:18 UTC by AdithyaBaglody

Arduino due runs at a higher frequency hence the systick will
overflow during the benchmark resulting in incorrect values.

Fixes: GH-7906

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

2018-06-04 12:28 UTC, nashif commented
This actually fails on other ARM platforms, not only the arduino

2018-06-04 15:08 UTC, nashif requested changes
This test fails on many ARM platforms, not only the due, so there is something else going on.

2018-07-05 02:01 UTC, nashif commented
are you going to do something about this or should it be closed?

2018-07-05 02:01 UTC, closed without merging

2018-07-05 04:49 UTC, AdithyaBaglody commented
Had kept this in the back because of some other issues needed attention. Will re open when i find the actual solution.