soc: nordic: handle -include for IAR
zephyrproject-rtos/zephyr pull request #81446
Opened 2024-11-15 14:04 UTC by RobinKastberg

CMakeLists.txt uses the C compiler parameter -include, for IAR this is --preinclude.

2024-11-15 15:21 UTC, masz-nordic approved these changes, later dismissed

2024-11-26 10:35 UTC, tejlmand requested changes
Thanks for this cleanup, but please make the changes to the toolchain / compiler infrastructure instead.

2024-11-26 10:35 UTC, tejlmand commented on soc/nordic/CMakeLists.txt
> +if(CMAKE_C_COMPILER_ID STREQUAL "IAR")
we should avoid compiler / toolchain specific handling inside the code as it makes support for multiple toolchains much harder.

Instead the code itself should be cleaned up and the include flag should be defined in the compiler properties and picked up where used.

For example like this:

```
set(include_flag $<TARGET_PROPERTY:compiler,include-file>)

set_source_files_properties(
  validate_binding_headers.c
  DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  PROPERTIES COMPILE_OPTIONS "${include_flag}$<JOIN:${dt_binding_includes},;${include_flag}>"
)
```

and then in https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/gcc/compiler_flags.cmake add a line like this:
```
set_compiler_property(PROPERTY include-file "-include$<SEMICOLON>")
# Note to @RobinKastberg: check if "-include;" is sufficient in above.
```

and in the correspong IAR `compiler_flags.cmake` you can then do similar:
```
set_compiler_property(PROPERTY include-file "-preinclude$<SEMICOLON>")
```
and there will no longer be any need for doing compiler check in the CMake code itself, plus a benefit is that another toolchain can just provide its own flag and doesn't have to add an extra if-clause to this CMake code.

2024-12-05 08:45 UTC, tejlmand requested changes
looks good, a minor suggestion to keep a general safer pattern.
(devs tends to copy-paste code they find elsewhere)

2024-12-05 08:45 UTC, tejlmand commented on soc/nordic/CMakeLists.txt
> +set(include_flag ${include_flag}$<SEMICOLON>)
please switch to using a genex. genex'es are evaluated at generator time whereas `get_target_property()` is evaluated at configure time. Thus genex is a bit safer, and should be used when possible.

```suggestion
set(include_flag $<TARGET_PROPERTY:compiler,include_file>$<SEMICOLON>)
```

2024-12-05 09:45 UTC, tejlmand approved these changes

2024-12-13 10:16 UTC, kartben commented
@RobinKastberg this need rebasing to get past the unrelated CI failure

2024-12-16 19:15 UTC, nashif approved these changes

2024-12-16 19:51 UTC, merged