boards: renesas: da14695_dk_usb: added mikrobus node labels
zephyrproject-rtos/zephyr pull request #81538
Opened 2024-11-18 17:27 UTC by iandmorris

Added mikrobus_header, mikrobus_i2c, mikrobus_spi and mikrobus_serial node labels to da14695_dk_usb device tree board definition, allowing compatible shield boards to be used. Also fixed minor issues with pin assignment and header labelling.

2024-11-21 08:46 UTC, blauret submitted a review, later dismissed

2024-11-21 08:47 UTC, blauret commented
@ydamigos , @ioannis-karachalios , 

This looks ok to me. Could you kindly have a look.

2024-11-21 10:44 UTC, ydamigos requested changes

2024-11-21 16:59 UTC, ydamigos approved these changes

2024-11-25 17:36 UTC, ioannis-karachalios approved these changes

2024-11-25 20:52 UTC, merged