doc: getting_started: add anchor for installing the zephyr sdk
zephyrproject-rtos/zephyr pull request #81615
Opened 2024-11-19 17:43 UTC by cfriedt

* doc: getting_started: add anchor for installing the zephyr sdk
* doc: beyond-gsg: install notes for sdk, venv in multi-user
* doc: beyond-gsg: notes for sdk package managers

2024-11-19 18:09 UTC, cfriedt commented
I guess there is some overlap / conflict with this

https://docs.zephyrproject.org/latest/develop/toolchains/zephyr_sdk.html

Maybe the only parts that are really relevant are the shared Python virtual environment and guidelines for building files for package managers (e.g. .deb or .rpm).

2024-11-20 00:09 UTC, stephanosio commented on doc/develop/beyond-GSG.rst
> +Guidelines for Package Managers
This sounds more like it should be part of the SDK documentation -- at minimum, it should not be part of the "Getting Started Guide."

2024-11-20 00:18 UTC, cfriedt commented on doc/develop/beyond-GSG.rst
> +2. Create a shared Python virtual environment (in :ref:`this step <gs_python_deps>`)
I was trying to force it to be tied to the SDK here, but you're right - it really isn't.

In practise, I just used a date for the version, but it should be tied to a Zephyr release (and maybe a patch version).

2025-01-01 20:09 UTC, cfriedt commented on doc/develop/beyond-GSG.rst
> +Zephyr SDK Installation in Multi-User Environments
Fixed!

2025-01-01 20:09 UTC, cfriedt commented on doc/develop/beyond-GSG.rst
> +2. Create a shared Python virtual environment (in :ref:`this step <gs_python_deps>`)
Fixed!

2025-01-01 20:10 UTC, cfriedt commented on doc/develop/beyond-GSG.rst
> +Guidelines for Package Managers
Fixed!

2025-01-02 02:37 UTC, ycsin submitted a review, later dismissed

2025-01-22 15:55 UTC, cfriedt commented
@kartben @stephanosio - Please take a look again when you have some time.

2025-03-29 12:05 UTC, cfriedt commented
@ycsin, @stephanosio, @kartben - please take another look. Docs should be fine. I'm not sure what's up with CI at the moment otherwise.

2025-05-28 12:23 UTC, kartben requested changes
Apologies for having completely dropped the ball on this PR
To me these are "tips" that are not really something that belongs to the Zephyr documentation. Maybe something for a blog post?
How to manage python venvs is really out of scope IMO just like we don't have, I don't know, instructions on how to setup a ramdisk to speed up compilation or whatever.

2025-05-29 03:12 UTC, closed without merging