subsys: bluetooth: Fix uninitialized variable
zephyrproject-rtos/zephyr pull request #81633
Opened 2024-11-20 07:32 UTC by rruuaanng

Fix uninitialized sec_idx variables scanned by Coverity.

from: https://github.com/zephyrproject-rtos/zephyr/issues/74718

2024-11-20 09:03 UTC, Casales commented
> what can I say :(
> 
> ```
>  -- Build files have been written to: /__w/zephyr/zephyr/twister-out/mps3_corstone310_fvp_ns/samples/psa/its/sample.psa.its.tfm/tfm/lib/ext/ethos_u_core_driver-subbuild
> [1/9] Creating directories for 'ethos_u_core_driver-populate'
> [1/9] Performing download step (git clone) for 'ethos_u_core_driver-populate'
> Cloning into 'ethos_u_core_driver-src'...
> fatal: unable to access 'https://review.mlplatform.org/ml/ethos-u/ethos-u-core-driver/': Failed to connect to review.mlplatform.org port 443 after 129420 ms: Connection timed out
> Cloning into 'ethos_u_core_driver-src'...
> fatal: unable to access 'https://review.mlplatform.org/ml/ethos-u/ethos-u-core-driver/': Failed to connect to review.mlplatform.org port 443 after 131045 ms: Connection timed out
> Cloning into 'ethos_u_core_driver-src'...
> fatal: unable to access 'https://review.mlplatform.org/ml/ethos-u/ethos-u-core-driver/': The requested URL returned error: 502
> -- Had to git clone more than once:
>           3 times.
> CMake Error at ethos_u_core_driver-subbuild/ethos_u_core_driver-populate-prefix/tmp/ethos_u_core_driver-populate-gitclone.cmake:31 (message):
>   Failed to clone repository:
>   'https://review.mlplatform.org/ml/ethos-u/ethos-u-core-driver'
> ```

I have the same issue. Something broken in the pipeline?

2024-11-21 08:46 UTC, cvinayak requested changes

2024-11-21 18:35 UTC, cvinayak approved these changes

2024-11-23 13:15 UTC, nashif approved these changes

2024-11-23 14:29 UTC, merged