drivers: sensor: mpu6050: support for choosing sample rate divider
zephyrproject-rtos/zephyr pull request #81649
Opened 2024-11-20 10:22 UTC by nikolaptr

The mpu6050 sensor driver defaults sensor sample rate to 8KHz which leads to issues on I2C, which cannot support such high sample rates. Fix it by adding sample rate divider to Kconfig, which allows users to lower sensor sample rate.

2024-11-20 14:44 UTC, MaureenHelm requested changes

2024-11-27 20:10 UTC, MaureenHelm reviewed
Requested changes should be made by amending commits instead of adding fixup commits. Please squash the changes into one commit so the history doesn't contain the intermediate whitespace changes/fixups.

2025-01-10 03:50 UTC, kartben commented
@MaureenHelm please revisit

2025-01-10 05:55 UTC, MaureenHelm requested changes

2025-01-10 05:55 UTC, MaureenHelm commented on drivers/sensor/tdk/mpu6050/mpu6050.h
> +	int smplrt_div;
Why does adding the sample rate divider affect the GPIO interrupt?

2025-01-10 05:55 UTC, MaureenHelm commented on dts/bindings/sensor/invensense,mpu6050.yaml
> +    default: 7
Need to explain in the description why the default value was selected
https://docs.zephyrproject.org/latest/build/dts/bindings-upstream.html#dt-bindings-default-rules

2025-03-26 00:35 UTC, closed without merging