introduce the nucleo_h7s3l78 nucleo144 board from STMicroelectronics
zephyrproject-rtos/zephyr pull request #81651
Opened 2024-11-20 11:02 UTC by FRASTM

Add the nucleo_h7s3l8 board from STMicroelectronics 
This Nucleo 144 board has **stm32h7S3L8** mcu.

Refer to the https://www.st.com/en/evaluation-tools/nucleo-h7s3l8.html

$ west build -p auto -b nucleo_h7s3l8 samples/hello_world/
```
*** Booting Zephyr OS build v4.0.0-rc3-49-g7500cdb33f48 ***                     
Hello World! nucleo_h7s3l8/stm32h7s3xx         
```

2024-11-20 11:23 UTC, nordicjm requested changes

2024-11-20 11:23 UTC, nordicjm commented on boards/st/nucleo_h7s3l8/doc/img/nucleo_h7s3l8.jpg
trim space around image, (optionally) make background transparent, save as webp, put webp through https://tinypng.com/

2024-11-20 11:23 UTC, nordicjm commented on boards/st/nucleo_h7s3l8/doc/index.rst
> +The Zephyr nucleo_h7s3l8 board configuration supports the following hardware
```suggestion
The Zephyr ``nucleo_h7s3l8`` board target supports the following hardware
```

2024-11-20 11:23 UTC, nordicjm commented on boards/st/nucleo_h7s3l8/nucleo_h7s3l8_defconfig
> +CONFIG_GPIO=y
```suggestion
# Enable UART driver
CONFIG_SERIAL=y

# Enable console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable GPIO
CONFIG_GPIO=y
```

2024-11-20 14:18 UTC, FRASTM commented
add comments from @nordicjm 
Fix CI error on wdg_api and adc_api

2024-11-25 07:45 UTC, nordicjm commented on boards/st/nucleo_h7s3l8/doc/img/nucleo_h7s3l8.jpg
Seems unresolved?

2024-12-11 11:44 UTC, nordicjm requested changes

2024-12-11 13:09 UTC, FRASTM commented on tests/drivers/adc/adc_api/boards/nucleo_h7s3l8.overlay
> + * Copyright (c) 2024 STMicroelectronics4
done

2024-12-11 13:09 UTC, FRASTM commented on tests/drivers/adc/adc_api/boards/nucleo_h7s3l8.overlay
> +		/* adjust channel number according to pinmux in board.dts */
done

2024-12-11 13:09 UTC, FRASTM commented on tests/drivers/watchdog/wdt_basic_api/testcase.yaml
>      extra_args: DTC_OVERLAY_FILE="boards/stm32_wwdg_h7.overlay"
corrected

2024-12-11 13:10 UTC, FRASTM commented
reducing the image size with nucleo_h7s3l8.webp  file

2024-12-11 13:15 UTC, nordicjm submitted a review, later dismissed

2025-01-06 09:33 UTC, bjarki-andreasen approved these changes

2025-01-06 09:33 UTC, bjarki-andreasen commented on tests/drivers/watchdog/wdt_basic_api/testcase.yaml
> +      - stm32h7s78_dk
Adding `stm32h7s78_dk` to this test suite is not necessarily part of introducing the `nucleo_h7s3l78` but it is very minor so I think its fine :)

2025-01-06 15:00 UTC, erwango approved these changes

2025-01-06 15:10 UTC, merged