drivers: video: Disable the driver if real camera presents
zephyrproject-rtos/zephyr pull request #81725
Opened 2024-11-21 14:33 UTC by trunghieulenxp

Do not enable the video sw generator if a real camera is present. This helps to save some spaces and to avoid unrelated code going into the built image.

If the real camera presents, there will be a warning which cannot be avoided:
`warning: VIDEO_SW_GENERATOR (defined at drivers/video/Kconfig.sw_generator:8) was assigned the value 'y' but got the value 'n'

2024-11-21 15:12 UTC, josuah approved these changes
This makes the software generator a default source that can be enabled by default by samples, since it goes a away when some board has a camera.

Great way to always make sure there is a "last resort" video source.

2024-11-21 16:04 UTC, ngphibang requested changes
Commit titile should be changed to "drivers: video: **sw_generator**: Disable the driver if a real camera presents" as this affects only the video sw generator driver"

2024-11-21 16:19 UTC, trunghieulenxp commented
> Commit titile should be changed to "drivers: video: **sw_generator**: Disable the driver if a real camera presents" as this affects only the video sw generator driver"

Hi, I have modified it.

2024-11-22 04:15 UTC, loicpoulain approved these changes

2024-11-22 08:35 UTC, ngphibang approved these changes

2024-11-22 23:04 UTC, kartben approved these changes

2024-11-25 16:42 UTC, merged