drivers: sensor: adxl345: Support for RTIO I2C stream
zephyrproject-rtos/zephyr pull request #81721
Opened 2024-11-21 13:26 UTC by dimitrije-lilic

Updated ADXL345 driver with RTIO I2C stream functionality.

Signed-off-by: Dimitrije Lilic <dimitrije.lilic@orioninc.com>

2024-11-21 16:52 UTC, teburd requested changes
It's actually quite nice that this mostly *just works* with spi or i2c, with some small flag changes. The pool size of sqe/cqe's is way too big though. Each submission queue entry is only limited to a parts cache line size, commonly 64 bytes! this is 64*64 bytes (4kb!) of submissions which is too large really when the largest transaction here is likely only 2-4 submissions long (128-256 bytes at most).

2024-11-22 12:44 UTC, MaureenHelm commented on drivers/sensor/adi/adxl345/adxl345.c
> +#endif
This won't work if there is one instance of the sensor on an I2C bus and another instance on a SPI bus

2024-11-22 12:44 UTC, MaureenHelm commented on drivers/sensor/adi/adxl345/adxl345_stream.c
> +#endif
I think you need to check if this instance of the sensor is on an I2C bus

2024-11-22 15:19 UTC, teburd commented on drivers/sensor/adi/adxl345/adxl345.c
> +	RTIO_DEFINE(adxl345_rtio_ctx_##inst, 64, 64);
Argh, yeah thats a bit of a thing isn't it, in that case its up to you, its a trade off of having to refill the submissions with a callback or having more submissions in the pool at a cost of memory.

2024-12-18 16:14 UTC, teburd submitted a review, later dismissed

2024-12-20 13:58 UTC, dimitrije-lilic commented on drivers/sensor/adi/adxl345/adxl345_stream.c
> +#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
changed

2024-12-20 13:59 UTC, dimitrije-lilic commented on drivers/sensor/adi/adxl345/adxl345_stream.c
> +#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
changed

2024-12-20 14:19 UTC, MaureenHelm approved these changes

2024-12-20 14:50 UTC, teburd approved these changes

2024-12-20 15:23 UTC, merged