drivers: hwinfo: Support for reset reasons in nRF54H20
zephyrproject-rtos/zephyr pull request #81751
Opened 2024-11-22 09:06 UTC by kl-cruz

Adding support for reset reasons in the nRF54H20 SoC.

2024-11-26 17:47 UTC, alexanderwachter submitted a review, later dismissed
LGTM from an API point of perspective.
Anyone from nordic who can verify?

2024-11-27 08:38 UTC, anangl requested changes

2024-11-27 08:38 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (NRFX_RESET_REASON_LOCAL_DOG0_MASK) {
```suggestion
	if (reason & NRFX_RESET_REASON_LOCAL_DOG0_MASK) {
```

2024-11-27 08:38 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (NRFX_RESET_REASON_LOCAL_DOG1_MASK)
```suggestion
	if (reason & NRFX_RESET_REASON_LOCAL_DOG1_MASK)
```

2024-11-27 08:38 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
> +
```suggestion
```

2024-11-27 08:38 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
>  #endif
```suggestion
#endif /* !NRF_POWER_HAS_RESETREAS */
```

2024-11-29 12:50 UTC, nika-nordic commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (reason & NRFX_RESET_REASON_LOCKUP_MASK)
nRF54H20 has local and global lockup reset reasons, so shouldn't it be like this:
```
	if ((reason & NRFX_RESET_REASON_LOCKUP_MASK)
#if defined(NRF_RESETINFO)
	    || (reason & NRFX_RESET_REASON_LOCAL_LOCKUP_MASK)
#endif
        ) {
		flags |= RESET_CPU_LOCKUP;
        }
```
?

2024-11-29 12:50 UTC, nika-nordic commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (reason & NRFX_RESET_REASON_SREQ_MASK)
same comment as in lockup case

2024-12-03 14:25 UTC, kl-cruz commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (NRFX_RESET_REASON_LOCAL_DOG0_MASK) {
I would prefer to do it in second step

2024-12-03 14:26 UTC, kl-cruz commented on drivers/hwinfo/hwinfo_nrf.c
> +	if (reason & NRFX_RESET_REASON_SREQ_MASK)
done

2024-12-11 11:47 UTC, tejlmand approved these changes, later dismissed

2024-12-11 12:07 UTC, alexanderwachter commented
I would propose to keep the code path clean and define a mask with all the macro decisions on top


Top:
#ifdef ...
RESET_CAUSE_XXX_MASK NRF_RESET_XXX
#else

RESET_CAUSE_XXX_MASK NRF_RESET_YYX
#endif

Code:

if(reason & RESET_CAUSE_XXX_MASK) {
    flags |= CAUSE_XXX;
}

2025-01-22 13:26 UTC, nordic-segl commented
Compliance check is failing - Please add missing commit body.

2025-01-22 13:31 UTC, nordic-piks commented
@kl-cruz can you follow up with this change?

2025-01-28 07:48 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
>  #include <helpers/nrfx_reset_reason.h>
This file cannot be included for cpuppr and cpuflpr on nRF54H20 because this leads to `#error "Unsupported device"` (and excluding them just in `tests/drivers/hwinfo/api` is not sufficient).
How about handling this with something like:
```
#if defined(CONFIG_BOARD_QEMU_CORTEX_M0) || \
	(defined(CONFIG_NRF_PLATFORM_HALTIUM) && \
	 defined(CONFIG_RISCV_CORE_NORDIC_VPR))
#define RESET_CAUSE_AVAILABLE 0
#else
#include <helpers/nrfx_reset_reason.h>
#define RESET_CAUSE_AVAILABLE 1
#endif
```
and then use `#if RESET_REASON_AVAILABLE` before `z_impl_hwinfo_get_reset_cause()`?

2025-01-29 11:20 UTC, anangl commented on tests/drivers/hwinfo/api/testcase.yaml
> +      - nrf54h20dk/nrf54h20/cpuppr
Is this still needed?

2025-01-29 11:22 UTC, anangl submitted a review, later dismissed

2025-01-29 11:37 UTC, nordic-segl approved these changes

2025-01-29 11:41 UTC, nika-nordic approved these changes, later dismissed

2025-01-30 12:51 UTC, anangl requested changes

2025-01-31 08:26 UTC, anangl submitted a review, later dismissed

2025-01-31 08:38 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
> +#define REASON_WATCHDOG	NRFX_RESET_REASON_DOG1_MASK
Shouldn't this be actually `(NRFX_RESET_REASON_DOG0_MASK | NRFX_RESET_REASON_DOG1_MASK)`?

2025-01-31 09:42 UTC, nordic-krch commented on drivers/hwinfo/hwinfo_nrf.c
> +#define REASON_WATCHDOG	NRFX_RESET_REASON_DOG1_MASK
Added DOG0

2025-01-31 10:29 UTC, alexanderwachter submitted a review, later dismissed

2025-02-03 10:35 UTC, nordic-krch commented
Had to align to nrfx 3.10 where some enum names changed (e.g. NRFX_RESET_REASON_SREQ -> NRFX_RESET_REASON_SREQ_MASK)

2025-02-03 10:35 UTC, anangl commented on drivers/hwinfo/hwinfo_nrf.c
> +#define REASON_WATCHDOG	NRFX_RESET_REASON_DOG0_MASK | NRFX_RESET_REASON_DOG1_MASK
```suggestion
#define REASON_WATCHDOG	(NRFX_RESET_REASON_DOG0_MASK | NRFX_RESET_REASON_DOG1_MASK)
```

2025-02-03 10:39 UTC, nordic-krch commented on drivers/hwinfo/hwinfo_nrf.c
> +#define REASON_WATCHDOG	NRFX_RESET_REASON_DOG0_MASK | NRFX_RESET_REASON_DOG1_MASK
done

2025-02-03 10:41 UTC, anangl approved these changes

2025-02-04 10:13 UTC, nika-nordic approved these changes

2025-02-04 10:56 UTC, merged