twister: support segger real-time-transfer (rtt) for serial_pty
zephyrproject-rtos/zephyr pull request #81837
Opened 2024-11-24 18:27 UTC by cfriedt

Support RTT (Segger Real-time Transfer) for reading console messages with twister when testing with hardware.

This support should be considered experimental as transfer speed, buffering, buffer size, and buffer count are all very much tuneable parameters that can vary per-platform and debug adapter. Physical UARTs are still the primary means of capturing test output from twister.

Tested with:
```shell
twister -p nucleo_l496zg --device-testing --flash-before --west-runner openocd --west-flash --device-serial-pty rtt -T samples/hello_world
```

shell
```
cat twister-out/nucleo_l496zg_stm32l496xx/samples/hello_world/sample.basic.helloworld/handler.log
*** Booting Zephyr OS build v4.0.0-749-gc9e567da3747 ***
Hello World! nucleo_l496zg/stm32l496xx
```

This change set also includes updates to jlink and openocd west runners to add an `--rtt-quiet` option. The new option suppresses the `stdout` and `stderr` of subprocesses (e.g. `JLinkRTTLogger` or `openocd`), which is the expectation for `--device-serial-pty` scripts. By suppressing unnecessary output, we can leverage `west rtt` in an automatically generated pty script.

Currently, the only other RTT-capable west runner is `pyocd`.

Additionally, the `DeviceHandler.handle()` method of `handler.py` is a bit tricky to work with; I was unsuccessful in making separate methods for `_do_flash()` and `_do_serial()` portions of the operation, because python was throwing exceptions claiming that code was attempting to adjust objects shared between processes without synchronization. At some point, this the `handle()` method should probably be refactored, but it was considered beyond what was necessary for the first draft of this PR.

2024-11-24 18:39 UTC, cfriedt commented
@topisani - it would be great if you could try this out as well.

2024-11-24 23:18 UTC, cfriedt commented
Oh wow - the bot made a lot of review requests 😅

2024-11-26 17:26 UTC, cfriedt commented
* switched to using the already-resolved `runner` variable instead of pulling it out of `self.options.west_runner` exclusively, since the `--hardware-map` option can also be used to provide the runner

2024-11-26 17:32 UTC, cfriedt commented
* replaced `self.rtt_port = rtt_quiet` with `self.rtt_quiet = rtt_quiet` in `jlink.py`

2024-11-30 00:32 UTC, cfriedt commented on scripts/pylib/twister/twisterlib/environment.py
> +        # add the following options
Probably want to include the `rtt-console` snippet

2025-01-10 18:04 UTC, cfriedt commented
* rebased to fix merge conflict

2025-01-13 03:19 UTC, hakehuang approved these changes
can we update document for this?

2025-01-17 14:07 UTC, nashif requested changes

2025-01-17 14:07 UTC, nashif commented on scripts/pylib/twister/twisterlib/environment.py
> +            logger.error("--device-serial-pty rtt requires --west-flash")
`--device-serial-pty` accept a script name, can be anything, here you assume that the script name (is this a script?) is always going to be rtt, or asking that if someone want to use this, they have to call their script rtt?

2025-01-17 14:07 UTC, nashif commented on scripts/pylib/twister/twisterlib/environment.py
> +        options.extra_args += ['CONFIG_USE_SEGGER_RTT=y',
not a fan of injecting HW related kconfigs into twister like this, this should be done on the platform/hardware map/ or test level, not in twister. Using a snippet for example is an option.

2025-01-17 14:07 UTC, nashif commented on scripts/pylib/twister/twisterlib/handlers.py
> +    def _create_serial_pty_script(self, runner):
ok, so you are creating the pty script on the fly, if I understand this correctly, it is an abuse of the `--device-serial-pty` option, we probably need something else to cover this case.

2025-01-17 14:12 UTC, cfriedt commented on scripts/pylib/twister/twisterlib/environment.py
> +            logger.error("--device-serial-pty rtt requires --west-flash")
No, in this case rtt is a keyword, and twister simply re-uses west's rtt integration.

Normally, the argument for device-serial-pty is a script through, so that hasn't changed.

2025-01-17 14:13 UTC, cfriedt commented on scripts/pylib/twister/twisterlib/environment.py
> +        options.extra_args += ['CONFIG_USE_SEGGER_RTT=y',
I've found actually that this works better with a snippet specified in testcase.yml.

I think this can be removed.

2025-01-17 14:14 UTC, cfriedt commented on scripts/pylib/twister/twisterlib/handlers.py
> +    def _create_serial_pty_script(self, runner):
"abuse" is probably a strong term.

I prefer "reuse" - we're simply reusing west's rtt integration.

2025-01-17 14:25 UTC, nashif commented on scripts/pylib/twister/twisterlib/handlers.py
> +    def _create_serial_pty_script(self, runner):
```
    device.add_argument("--device-serial-pty",
                        help="""Script for controlling pseudoterminal.
                        Twister believes that it interacts with a terminal
                        when it actually interacts with the script.

                        E.g "twister --device-testing
                        --device-serial-pty <script>
```

Not using a script here is wrong usage. If you want to use a built-in rtt support you are adding, you need to find another way, maybe yet another option that deals with `keywords`

2025-01-17 14:29 UTC, closed without merging

2025-01-17 18:43 UTC, nashif commented
why close?