stm32 flash read out protection rdp in a common file
zephyrproject-rtos/zephyr pull request #81876
Opened 2024-11-25 14:04 UTC by FRASTM

Following the PR "Implement readout protection for STM32H7" #76640, it appears that 
" Function flash_stm32_option_bytes_lock() seems to be the obvious candidate to be moved to" a common file to stm32h7 anr other stm32 series.
This common file could be the existing drivers/flash/flash_stm32_ex_op.c 
The flash_stm32_option_bytes_lock() is moved there and the flash_stm32_write_protection is made external to that file

2024-12-09 15:44 UTC, FRASTM commented
PR #76640 is now merged, rebase on 4488ed1a20a97007d451d2ac1f093c413c56e77a

2025-03-06 16:12 UTC, FRASTM commented
rebased on 0717698277c6851bd8f680a2d7c1a3461a10ae2c

2025-03-18 10:06 UTC, FRASTM commented
rebase on 3d2059f9b66faf2b6cf4be15b2f4adc2f092f42b

2025-03-21 08:09 UTC, gautierg-st submitted a review, later dismissed

2025-03-21 08:12 UTC, erwango commented
^^@duda-patryk, @niedzwiecki-dawid

2025-04-25 06:39 UTC, FRASTM commented
> ^^@duda-patryk, @niedzwiecki-dawid

kind reminder

2025-04-25 07:52 UTC, niedzwiecki-dawid requested changes

2025-04-29 12:27 UTC, FRASTM commented on drivers/flash/flash_stm32_ex_op.c
> +	regs->OPTKEYR = FLASH_OPT_KEY2;
fixed

2025-04-29 13:12 UTC, niedzwiecki-dawid approved these changes, later dismissed

2025-04-30 08:27 UTC, gautierg-st submitted a review, later dismissed

2025-04-30 09:29 UTC, etienne-lms commented on drivers/flash/flash_stm32_ex_op.c
> +		regs->OPTKEYR = FLASH_OPT_KEY2;
Is this missing the H7RSX case?
```c
#ifdef CONFIG_SOC_SERIES_STM32H7RSX
		regs->OPTKEYR = FLASH_OPTKEY1;
		regs->OPTKEYR = FLASH_OPTKEY2;
#else

2025-04-30 13:51 UTC, FRASTM commented on drivers/flash/flash_stm32_ex_op.c
> +		regs->OPTKEYR = FLASH_OPT_KEY2;
yes, added in the flash_stm32.h file

2025-04-30 13:53 UTC, FRASTM commented
rebase on cd43e03bbe24feef4d511587f79f8f1277825ca6
add the OPTKEY1&2 for the stm32h7rs serie

2025-04-30 14:28 UTC, etienne-lms commented on drivers/flash/flash_stm32.h
> +
remove this empty line?

2025-05-06 08:51 UTC, FRASTM commented on drivers/flash/flash_stm32.h
> +
removed

2025-05-06 09:03 UTC, etienne-lms approved these changes

2025-05-06 15:41 UTC, de-nordic approved these changes

2025-05-06 16:07 UTC, erwango approved these changes

2025-05-06 16:23 UTC, merged