soc: nordic: Default enable Power Management on nRF54H20 radio core
zephyrproject-rtos/zephyr pull request #81886
Opened 2024-11-25 15:20 UTC by KyraLengfeld

Adds CONFIG_PM=y to Radio core in the nRF54H20 SoC on the nRF54H20 DK
soc defconf.

2024-11-25 15:56 UTC, gmarull requested changes
board is not the place to do this, use soc level defconfig

2024-11-26 13:07 UTC, KyraLengfeld commented
> board is not the place to do this, use soc level defconfig

Should be the right spot now, if you meant something different, please let me know where exactly.

2024-11-26 14:08 UTC, gmarull commented on soc/nordic/nrf54h/Kconfig.defconfig.nrf54h20_cpurad
> +CONFIG_PM=y
```suggestion
config PM
	default y
```

2024-11-27 08:15 UTC, gmarull approved these changes

2024-12-03 11:43 UTC, knutel-nordic approved these changes

2024-12-03 13:15 UTC, anangl approved these changes

2024-12-03 15:47 UTC, merged