drivers: flash: stm32: expose flash_stm32_write_optb
zephyrproject-rtos/zephyr pull request #82079
Opened 2024-11-26 18:00 UTC by fabiobaltieri

The STM32 specific flash API already exposes
flash_stm32_option_bytes_lock, expose flash_stm32_option_bytes_write so that an application can use the functionality to set device option bytes.

2024-11-28 09:57 UTC, erwango reviewed
Thanks @fabiobaltieri.

Looks fine, but however, I wonder if, for consistency sake, these APIs shouldn't be made available through already existing `flash_ex_op()` api, which is there to expose flash controller specific features ?

Agreed this would be slightly more complex to implement and likely consume more footprint, but I think consistency is key for users.

Alternatively, if there are good reasons not to use `flash_ex_op()`, let's make it explicit.

2024-11-28 10:50 UTC, fabiobaltieri commented
> Looks fine, but however, I wonder if, for consistency sake, these APIs shouldn't be made available through already existing `flash_ex_op()` api, which is there to expose flash controller specific features ?

Oh that makes load of sense, yeah thanks for the pointer I'll move this back to draft and rework it.

2024-12-02 19:22 UTC, fabiobaltieri commented
@erwango I've reworked it to have two ex op codes but I don't really like the resulting code if I can be totally honest. What do you think?

2024-12-16 07:01 UTC, de-nordic submitted a review, later dismissed

2024-12-16 13:35 UTC, gautierg-st requested changes
Small typo, otherwise LGTM

2024-12-16 13:35 UTC, gautierg-st commented on drivers/flash/Kconfig.stm32
> +	  STM32 option bytes.
```suggestion
	  Enables flash extended operations that can be used to write and read
	  STM32 option bytes.
```

2024-12-16 15:15 UTC, fabiobaltieri commented on drivers/flash/Kconfig.stm32
> +	  STM32 option bytes.
see, if my github account got compromised you'll be able to tell immediately as soon as you see a PR of me without at least one typo

2024-12-16 15:16 UTC, fabiobaltieri commented
ah, needs a rebase too

2024-12-16 15:37 UTC, gautierg-st approved these changes

2024-12-17 11:10 UTC, erwango approved these changes

2024-12-17 11:35 UTC, merged