drivers: video: ov5640: Fix bug out-of-bound buffer read
zephyrproject-rtos/zephyr pull request #82153
Opened 2024-11-27 17:12 UTC by trunghieulenxp

Fix #81982

2024-11-27 17:19 UTC, ngphibang requested changes
Need to fix upper bound too:

fie->index >= ARRAY_SIZE(ov5640_frame_rates)

2024-11-28 08:47 UTC, trunghieulenxp commented on drivers/video/ov5640.c
> +	    fie->index > ARRAY_SIZE(ov5640_frame_rates) ||
Fixed it. Thanks

2024-11-28 08:51 UTC, ngphibang approved these changes

2024-11-28 09:32 UTC, loicpoulain submitted a review, later dismissed

2024-11-28 09:56 UTC, ngphibang requested changes
Sorry, I just rechecked, `fie->index < 0` need to be removed as it is an unsigned value unless we will run into another coverity issue as https://github.com/zephyrproject-rtos/zephyr/issues/81936

2024-11-28 09:56 UTC, ngphibang commented on drivers/video/ov5640.c
> +	    fie->index >= ARRAY_SIZE(ov5640_frame_rates) ||
You should remove `fie->index < 0`, just do `fie->index >= ARRAY_SIZE(ov5640_frame_rates)` as `fie->index` is an unsigned value. If you compare it with 0, you will run into another coverity issue as [here](https://github.com/zephyrproject-rtos/zephyr/issues/81936)

2024-11-28 14:14 UTC, josuah approved these changes

2024-11-28 14:20 UTC, ngphibang approved these changes

2024-11-28 14:23 UTC, ngphibang commented
Commit message should be updated too "Fix the out of bound buffer read by checking the lower-bound index
in the ov5640_enum_frmival function.". Now it's not lower bound but upper-bound :-) or simply just "Add check for array out of bound". But this is minor.

2024-11-29 20:46 UTC, merged