boards: shields: add spi support to mikroe weather click shield
zephyrproject-rtos/zephyr pull request #82165
Opened 2024-11-27 19:55 UTC by iandmorris

Added support for the SPI interface which is availble on the shield if the jumper configurations are changed.

2024-12-07 00:53 UTC, kartben requested changes

2024-12-17 15:57 UTC, kartben reviewed
Sorry, just spotted this when searching for `mikroe_weather_click` across the tree to make sure there weren't stale references to the old shield: Line 44 of index.rst needs updating.
In fact, this made me realize that you also want to indicate in the migration guide that the shield was renamed (unless you maybe keep the original name as the "default" i2c  and call the new spi variant/revision `..._spi`?

2024-12-23 12:36 UTC, fabiobaltieri approved these changes

2024-12-23 12:42 UTC, kartben approved these changes

2024-12-23 16:10 UTC, merged