dts: bindings: rename nxp,kinetis-lpuart compatible
zephyrproject-rtos/zephyr pull request #82191
Opened 2024-11-28 02:07 UTC by manuargue

Rename "nxp,kinetis-lpuart" compatible to "nxp,lpuart" to remove the device family from its name because this hardware block is used in multiple NXP devices from different families.

2024-11-28 08:02 UTC, butok submitted a review, later dismissed

2024-11-28 08:08 UTC, iuliana-prodan approved these changes, later dismissed

2024-12-02 18:41 UTC, dleach02 submitted a review, later dismissed

2024-12-02 18:57 UTC, danieldegrasse commented on doc/releases/migration-guide-4.1.rst
> +UART
This section has been named `SERIAL` in past release notes- otherwise, change LGTM

2024-12-02 18:58 UTC, danieldegrasse requested changes
Going to request changes as this PR otherwise has the requisite approvals- please feel free to dismiss my block once the doc title is changed to `SERIAL` from `UART`

2024-12-03 17:42 UTC, danieldegrasse submitted a review, later dismissed

2024-12-08 05:02 UTC, manuargue commented
rebased & fixed conflicts

2024-12-09 07:43 UTC, iuliana-prodan approved these changes

2024-12-09 08:00 UTC, JiafeiPan approved these changes

2024-12-10 13:43 UTC, manuargue commented
ping @dleach02 @mmahadevan108

2024-12-10 14:25 UTC, decsny approved these changes

2024-12-11 02:01 UTC, dleach02 approved these changes

2024-12-11 07:00 UTC, merged