samples: bluetooth: Increase nRF54H20 stack for hci_ipc
zephyrproject-rtos/zephyr pull request #82255
Opened 2024-11-28 13:38 UTC by Vge0rge

Increase the stack size for hci_ipc on nRF54H20 since the IPC communication increases stack usage.

2024-11-28 14:19 UTC, jhedberg commented
Wouldn't IPC usage increase stack usage for any board, i.e. why not put this into prj.conf instead since this app is all about IPC?

2024-11-28 14:21 UTC, jhedberg requested changes
> Wouldn't IPC usage increase stack usage for any board, i.e. why not put this into prj.conf instead since this app is all about IPC?

Actually, 1024 is the default main stack size, so why do you even need this change to begin with? Does the board override the default somewhere and then you need to override the override? Doesn't sound like a very nice solution.
https://github.com/zephyrproject-rtos/zephyr/blob/2f583a8369ef5b67c4438c40d17721d31db952a0/kernel/Kconfig#L156-L160

Requesting changes until we get some clarity on the above

2024-11-28 15:31 UTC, Vge0rge commented
> > Wouldn't IPC usage increase stack usage for any board, i.e. why not put this into prj.conf instead since this app is all about IPC?
> 
> Actually, 1024 is the default main stack size, so why do you even need this change to begin with? Does the board override the default somewhere and then you need to override the override? Doesn't sound like a very nice solution.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/2f583a8369ef5b67c4438c40d17721d31db952a0/kernel/Kconfig#L156-L160
> 
> Requesting changes until we get some clarity on the above

In the prj.conf this sample sets the main stack to 512:
https://github.com/zephyrproject-rtos/zephyr/blob/ab6e59615c63479ba405794e96727b653b6a1b43/samples/bluetooth/hci_ipc/prj.conf#L6

I see no reason to affect the  nrf5340 for this since it seems to work with a reduced stack.

2024-11-28 15:44 UTC, jhedberg commented
> I see no reason to affect the nrf5340 for this since it seems to work with a reduced stack.

"Seems to work" could mean that it's very close to the limit or even slightly over it and you just get lucky that it doesn't trigger a stack overflow panic. I'd advise to at least do some profiling of exactly how much is consumed there. If there's any chance that other platforms (even non-Nordic ones) using hci_ipc might be close to the limits, I think it's safer to update `prj.conf` than to do this only for one single board.

2024-11-28 18:01 UTC, Thalley commented
> > I see no reason to affect the nrf5340 for this since it seems to work with a reduced stack.
> 
> "Seems to work" could mean that it's very close to the limit or even slightly over it and you just get lucky that it doesn't trigger a stack overflow/panic. I'd advise to at least do some profiling of exactly how much is consumed there. If there's any chance that other platforms (even non-Nordic ones) using hci_ipc might be close to the limits, I think it's safer to update `prj.conf` than to do this only for one single board.

Agreed. It's unclear why this specific board would need additional stack

2024-11-29 07:42 UTC, Vge0rge commented
> > I see no reason to affect the nrf5340 for this since it seems to work with a reduced stack.
> 
> "Seems to work" could mean that it's very close to the limit or even slightly over it and you just get lucky that it doesn't trigger a stack overflow/panic. I'd advise to at least do some profiling of exactly how much is consumed there. If there's any chance that other platforms (even non-Nordic ones) using hci_ipc might be close to the limits, I think it's safer to update `prj.conf` than to do this only for one single board.

With "seems to work" I meant that there are CI plans which run this sample and pass. I don't work closely with bluetooth, maybe the original author of this stack size can give us a comment here. @kapi-no can you give your opinion about increasing the stack size globally here?

The reason that I made this change is that I enabled in our SDK the IPC communication for this device and I realized that this image cannot run anymore because of stack overflow. So I am afraid that I don't have a very detailed description why this stack increase is needed. @Thalley could you be more specific what type of explanation do you need for increasing the stack?

2024-11-29 08:39 UTC, jhedberg commented
Is there some reason why we can't just drop all references to MAIN_STACK_SIZE in this app? Then the option would just get the default value from `kernel/Kconfig` which is 1024 for the boards that you care about.

2024-11-29 09:40 UTC, Vge0rge commented
> Is there some reason why we can't just drop all references to MAIN_STACK_SIZE in this app? Then the option would just get the default value from `kernel/Kconfig` which is 1024 for the boards that you care about.

Maybe there is but I don't know why they reduced the stack size in the first place. I mentioned in my previous message the author of the line which reduces the stack size, hopefully we can get some more information about this.

2024-11-29 11:54 UTC, Thalley commented
> could you be more specific on what type of explanation do you need for increasing the stack?

Basically, why does the nRF54H20 need more stack than e.g. the nRF5340? 
And why 1024? Why not e.g. `768`?

2024-11-29 12:11 UTC, kapi-no commented
I am okay with the stack size increase as long as the Zephyr CI and NCS CI do not expose any RAM overflow issues.

2024-11-29 12:17 UTC, Thalley commented
> I am okay with the stack size increase as long as the Zephyr CI and NCS CI do not expose any RAM overflow issues.

CI may not catch all RAM overflows: https://github.com/zephyrproject-rtos/zephyr/issues/81044

2024-11-29 12:41 UTC, Vge0rge commented
> > could you be more specific on what type of explanation do you need for increasing the stack?
> 
> Basically, why does the nRF54H20 need more stack than e.g. the nRF5340? And why 1024? Why not e.g. `768`?

Unfortunately I cannot provide these details myself. I am not aware of stack profiling reports for the IPC mechanisms and it is not my domain as well. I am a user of IPC, I am not developing/testing it.  So I chose 1024 because it the default in Zephyr and I saw in practice that it passes CI tests. 

The reason that this got noticed now is that in our sdk its the first time that IPC is enabled by default and thus some tests failed because of this.

2024-11-29 15:49 UTC, Thalley commented
> The reason that this got noticed now is that in our sdk its the first time that IPC is enabled by default and thus some tests failed because of this.

But it isn't failing on the nRF5340? 

I think it's worth figuring out why, and if there's something that requires additional stack space on the nRF54H20 that shouldn't do that, or if the nRF5340 is also at or near the limit

2024-12-05 14:18 UTC, Vge0rge commented
Closing this as it was decided to handle it in our sdk and not in upstream Zephyr.

2024-12-05 14:18 UTC, closed without merging