drivers: pwm: Place API into iterable section
zephyrproject-rtos/zephyr pull request #82253
Opened 2024-11-28 13:28 UTC by yishai1999

Add wrapper DEVICE_API macro to all pwm_driver_api instances.

2024-11-28 13:29 UTC, pdgendt commented
You still had the led commit, need to drop that.

2024-11-28 13:30 UTC, yishai1999 commented
> You still had the led commit, need to drop that.


You're too quick!

2024-11-28 13:31 UTC, pdgendt commented
You forgot `drivers/pwm/pwm_rpi_pico.c`

2024-11-28 13:35 UTC, pdgendt commented
> Missed it because it wasn't static. Fixed

Careful making it `static`, but it looks fine in this case.

2024-11-28 13:36 UTC, pdgendt submitted a review, later dismissed

2024-11-30 19:46 UTC, henrikbrixandersen requested changes

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	__ASSERT_NO_MSG(DEVICE_API_IS(pwm, dev));
As per discussions on Discord (see https://discord.com/channels/720317445772017664/1310670722401833030) the asserts needs to be removed in order not to break out-of-tree drivers.

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	__ASSERT_NO_MSG(DEVICE_API_IS(pwm, dev));
Same here.

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	__ASSERT_NO_MSG(DEVICE_API_IS(pwm, dev));
and here.

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	__ASSERT_NO_MSG(DEVICE_API_IS(pwm, dev));
and here.

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	__ASSERT_NO_MSG(DEVICE_API_IS(pwm, dev));
and finally here.

2024-11-30 19:46 UTC, henrikbrixandersen commented on include/zephyr/drivers/pwm.h
> +	return DEVICE_API_GET(pwm, dev)->configure_capture(dev, channel, flags, cb,
Instead of doing pointer dereferencing twice, why not leave the local variable? Same for the other, optional API functions.

2024-12-01 16:25 UTC, pdgendt approved these changes

2024-12-04 11:11 UTC, pdgendt commented
@anangl PTAL

2024-12-04 16:02 UTC, henrikbrixandersen approved these changes

2024-12-06 11:13 UTC, merged