boards: st: introduce new stm32f413 disco kit
zephyrproject-rtos/zephyr pull request #82275
Opened 2024-11-28 15:58 UTC by FRASTM

Add the stm32f413h_disco target to the boards/st

https://www.st.com/en/evaluation-tools/32f413hdiscovery.html

2024-11-28 17:39 UTC, kartben requested changes

2024-11-29 07:15 UTC, nordicjm requested changes

2024-11-29 07:15 UTC, nordicjm commented on boards/st/stm32f413h_disco/board.cmake
> +
```suggestion
```

2024-11-29 07:15 UTC, nordicjm commented on boards/st/stm32f413h_disco/stm32f413h_disco_defconfig
> +CONFIG_GPIO=y
```suggestion
# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable GPIO ports A, B, C, D, E, F, G, H
CONFIG_GPIO=y
```

2024-11-29 07:15 UTC, nordicjm commented on boards/st/stm32f413h_disco/doc/index.rst
> +The Zephyr stm32f413h_disco board configuration supports the following hardware features:
use correct terminology https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#board-terminology

2024-11-29 07:15 UTC, nordicjm commented on boards/st/stm32f413h_disco/doc/index.rst
> +Applications for the ``stm32f413h_disco`` board configuration can be built and
etc.

2024-11-29 08:23 UTC, FRASTM commented on boards/st/stm32f413h_disco/doc/index.rst
> +Applications for the ``stm32f413h_disco`` board configuration can be built and
changing name with `STM32F413H-DISCO`

2024-11-29 08:26 UTC, FRASTM commented on boards/st/stm32f413h_disco/doc/img/stm32f413h_disco.png
taking that image

2024-12-11 16:21 UTC, kartben commented
@FRASTM please check the CI failures

2024-12-12 08:27 UTC, FRASTM commented
rebase on 7c4abb1eb9fddadc469318f7bf4f0d4d573d3726 (CI error fixed)

2024-12-12 16:02 UTC, FRASTM commented on boards/st/stm32f413h_disco/doc/index.rst
> +with a wide range of connectivity support and configurations Here are
changed

2024-12-12 16:02 UTC, FRASTM commented on boards/st/stm32f413h_disco/doc/index.rst
> +driven internal oscillator.
changed

2024-12-12 16:02 UTC, FRASTM commented on boards/st/stm32f413h_disco/doc/index.rst
> +Other hardware features are not yet supported on Zephyr porting.
changed

2024-12-12 16:44 UTC, JarmouniA approved these changes

2024-12-18 12:40 UTC, FRASTM commented on boards/st/stm32f412g_disco/doc/index.rst
> +STM32F412G-DISCO Discovery kit provides the following hardware components:
done in commit fc5043ad104055fd0efba75411b7b25965439699

2024-12-18 12:41 UTC, FRASTM commented
with new image and new 1 commit

2024-12-18 14:15 UTC, FRASTM commented
> > with new image and new 1 commit
> 
> I'm not sure what's going on but can't you just use: https://www.mouser.fr/images/marketingid/2017/img/128173244_STMicroelectronics_32F413HDISCOVERYDiscoveryKit.png?v=070223.0256 ? The image you have in your latest commit appears to be webp, sure, but without a transparent background as if you had converted your jpg image or something?

that's the case : the webp image I put, was processed by https://tinypng.com/    but  it does not makes the background transparent. Does it really make a difference ?
I'd really prefer to have the webp format of this one : 
![stm32f413_disco](https://github.com/user-attachments/assets/bc046599-99fa-4b9a-a7b6-ad6034b211a9)

2024-12-18 14:30 UTC, kartben commented
> > > with new image and new 1 commit
> > 
> > 
> > I'm not sure what's going on but can't you just use: [mouser.fr/images/marketingid/2017/img/128173244_STMicroelectronics_32F413HDISCOVERYDiscoveryKit.png?v=070223.0256](https://www.mouser.fr/images/marketingid/2017/img/128173244_STMicroelectronics_32F413HDISCOVERYDiscoveryKit.png?v=070223.0256) ? The image you have in your latest commit appears to be webp, sure, but without a transparent background as if you had converted your jpg image or something?
> 
> that's the case : the webp image I put, was processed by [tinypng.com](https://tinypng.com/) but it seems it does not have the transparent background (I do not know exactly the command to obtain that effect) . Does it really make a difference ? I'd really prefer to have the webp format of this one : ![stm32f413_disco](https://private-user-images.githubusercontent.com/51417392/396954822-bc046599-99fa-4b9a-a7b6-ad6034b211a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MzI0MjQsIm5iZiI6MTczNDUzMjEyNCwicGF0aCI6Ii81MTQxNzM5Mi8zOTY5NTQ4MjItYmMwNDY1OTktOTlmYS00YjlhLWE3YjYtYWQ2MDM0YjIxMWE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE0Mjg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzN2U3YTU3ODc3MDczMWRiNWVlNjQ0NDYyYzM1NGE3Nzg5NjA0MGQzNWFjYjBiOWQyZmZlZjM3NDMxNjIxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bXYzOKffDljXM370dKSKbuEyGytIyaSakXxS8VtLdFU)

but why don't you want to use the one I linked to? It falls under fair-use, if that's your concern.
The image with the mbed logo is really not an option IMO, for just so many reasons, including the fact that we're Zephyr *and* that Mbed is EOL :)

2024-12-18 16:00 UTC, FRASTM commented
taking the recommended image

2024-12-18 19:50 UTC, kartben approved these changes

2024-12-19 13:32 UTC, erwango approved these changes

2024-12-19 13:41 UTC, kartben commented
> taking the recommended image

Thanks! https://builds.zephyrproject.io/zephyr/pr/82275/docs/boards/st/stm32f413h_disco/doc/index.html :)

2024-12-19 13:41 UTC, kartben approved these changes

2024-12-20 12:06 UTC, nordicjm approved these changes

2024-12-20 16:32 UTC, kartben commented
> @FRASTM sample.bluetooth.peripheral_hr.frdm_kw41z_shield build failure in CI
> 
> ```
> west build -p -b stm32f413h_disco/stm32f413xx samples/bluetooth/peripheral_hr -T sample.bluetooth.peripheral_hr.frdm_kw41z_shield
> ```

rebase on main will fix the issue

2025-01-02 08:43 UTC, FRASTM commented
> > @FRASTM sample.bluetooth.peripheral_hr.frdm_kw41z_shield build failure in CI
> > ```
> > west build -p -b stm32f413h_disco/stm32f413xx samples/bluetooth/peripheral_hr -T sample.bluetooth.peripheral_hr.frdm_kw41z_shield
> > ```
> 
> rebase on main will fix the issue

Done

2025-01-02 11:35 UTC, merged