drivers: regulator: Place API in iterable section
zephyrproject-rtos/zephyr pull request #82290
Opened 2024-11-28 20:01 UTC by pdgendt

Add wrapper DEVICE_API macro to all regulator_driver_api instances.

2024-11-29 19:28 UTC, gmarull requested changes
some tests are deleted, but they need a solution (at least a workaround in test environment)

2024-11-30 15:03 UTC, pdgendt commented
> some tests are deleted, but they need a solution (at least a workaround in test environment)

Added dummy devices and kept the tests.

2024-12-02 08:33 UTC, gmarull approved these changes

2024-12-02 19:10 UTC, danieldegrasse approved these changes

2024-12-02 22:08 UTC, merged