boards: frdm_mcxn947: add the board image
zephyrproject-rtos/zephyr pull request #82412
Opened 2024-12-02 10:56 UTC by butok

Add a missing image of the frdm-mcxn947 board.

2024-12-02 11:49 UTC, nordicjm submitted a review, later dismissed

2024-12-02 18:29 UTC, dleach02 requested changes
@butok I think you wanted to direct this change to the frdm_rw612 board.

2024-12-03 07:42 UTC, butok commented
> @butok looks like you wanted to direct this change to the frdm_rw612 board.

OMG! Fixed. Thank you 👍

2024-12-03 17:31 UTC, danieldegrasse approved these changes

2024-12-03 17:34 UTC, danieldegrasse commented
https://builds.zephyrproject.io/zephyr/pr/82412/docs/boards/nxp/frdm_rw612/doc/index.html

2024-12-04 18:46 UTC, dleach02 approved these changes

2024-12-04 19:14 UTC, merged