driver: gpio: mcp23xxx: add reset pin pulse duration config
zephyrproject-rtos/zephyr pull request #82536
Opened 2024-12-04 10:43 UTC by skullbox305

The reset pulse is currently fixed at 1 µs, the minimum required for the chip. However, a long reset pin trace increases rise time, making 1 µs insufficient for reliable detection of a reset signal. Add a KConfig option to adjust the pulse duration.

2024-12-05 11:00 UTC, skullbox305 commented
It turns out that the issue I initially thought was resolved by this PR was not fully fixed; it was only drastically reduced in frequency. The problem I faced was that my I²C bus occasionally misbehaved after a reset. I believed the issue was caused by the port expander freezing and the reset not functioning properly.

However, I discovered that the root cause was arbitration loss on the I²C bus. This occurred when a reset happened at the "wrong" moment, causing a slave device to become stuck during transmission. I resolved this issue by using `i2c_recover_bus()`.

That said, my original assumption might still hold true. It would likely be beneficial to allow adjustments to the reset pulse duration, particularly on very fast SoCs that can actually achieve a 1 µs reset pulse. What do you think?

2024-12-16 10:30 UTC, henrikbrixandersen requested changes
> That said, my original assumption might still hold true. It would likely be beneficial to allow adjustments to the reset pulse duration, particularly on very fast SoCs that can actually achieve a 1 µs reset pulse. What do you think?

I would never use the minimum value for a reset pulse length, I if was to write the driver. How about just increasing the default to 2 µs?

If you insist on making it configurable, I think the configuration should be done via devicetree.

2025-01-17 15:00 UTC, skullbox305 commented
You're right. Increasing it to 2 µs should be sufficient

2025-01-17 15:16 UTC, henrikbrixandersen approved these changes

2025-01-17 17:39 UTC, kartben approved these changes

2025-01-17 19:07 UTC, merged