subsys: net: lib: ptp: Include timestamp in follow up msg and minor fixes
zephyrproject-rtos/zephyr pull request #82605
Opened 2024-12-05 12:14 UTC by tomasixys

This PR aims to fix some small issues encountered while implementing ptp on a stm32f767. The fixes are described in the individual commit messages, but below is a brief description:

While in developement, I have asserts enabled, and experienced the asserts in transport.c always failing. It appears the condition is inverted, as PTP_SOCKET_CNT is always larger than the current socket.
The second issue is tied to the ptp_clock_synchronization in clock.c. Casting the adjustment value to a uint64/32 with a compound assignment operator (-=) causes the adjustment to be mono-directional.
The third and main issue is how the follow up message lacks the timestamp captured at the sync message egress. The timestamp is prepared by the sync message, but not inserted into the follow up.

2024-12-06 09:29 UTC, kartben approved these changes
Thanks, this looks good to me!
For second issue, I vaguely remember that I was indeed possibly not fixing this properly when taking a stab at fixing the previously broken implementation, but since the problem wasn't gonna arise in my particular use case, I probably forgot to invest more time in a proper fix 🫣

2024-12-09 09:01 UTC, awojasinski requested changes

2024-12-09 09:01 UTC, awojasinski commented on subsys/net/lib/ptp/msg.c
Timestamp in follow up is taken from a sync message. Please take a look at the `port_sync_timestamp_cb()` function in `port.c:204`. The follow up doesn't need it's own timestamp.

2024-12-09 10:02 UTC, tomasixys commented on subsys/net/lib/ptp/msg.c
This is correct, but the timestamp is not processed correctly. The port_sync_timestamp_cb() *prepares* the timestamp for the follow up message, but the time stamp is not converted to correct byteorder without being processed by msg_timestamp_pre_send().

2024-12-09 11:00 UTC, awojasinski commented on subsys/net/lib/ptp/transport.c
> +	__ASSERT(PTP_SOCKET_CNT > idx, "Invalid socket index");
`PTP_SOCKET_CNT` isn't valid socket id. Each port has at the moment 2 sockets - idx 0 for events and idx 1 for general. The `PTP_SOCKET_CNT` is used when specifying number of sockets (n_ports * `PTP_SOCKET_CNT`) so yes, we want to assert if idx is <= PTP_SOCKET_CNT

2024-12-09 11:01 UTC, awojasinski commented on subsys/net/lib/ptp/msg.c
sorry you're right I overlooked that

2024-12-09 11:22 UTC, tomasixys commented on subsys/net/lib/ptp/transport.c
> +	__ASSERT(PTP_SOCKET_CNT > idx, "Invalid socket index");
as we agree that PTP_SOCKET_CNT is *not* a valid socket id, then should we not keep the comparison to be *strictly* less than: 
    idx < PTP_SOCKET_CNT

2024-12-09 11:23 UTC, awojasinski commented on subsys/net/lib/ptp/transport.c
> +	__ASSERT(PTP_SOCKET_CNT > idx, "Invalid socket index");
yes, sorry

2024-12-09 11:23 UTC, awojasinski approved these changes

2024-12-09 14:10 UTC, merged