fix(boards): weact stm32g474 core board
zephyrproject-rtos/zephyr pull request #82628
Opened 2024-12-05 19:38 UTC by ankayca

add weact stm32g474 core board support and documentation.

2024-12-06 08:42 UTC, nordicjm requested changes
commit title needs fixing, no `fix` or brackets, add sign off

2024-12-06 08:42 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +
```suggestion
```

2024-12-06 08:42 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +&clk_lsi {
add newline gaps

2024-12-06 08:42 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core_defconfig
> +
```suggestion
```

2024-12-06 08:42 UTC, nordicjm commented on boards/weact/stm32g474_core/doc/index.rst
> +
Add a line similar to https://github.com/zephyrproject-rtos/zephyr/commit/887f210153b8a50e417232582762167d914c4033#diff-96c74ad50824463df0bd48ff926ecd261e62399a80a09226f40891629f2ea148R25

2024-12-07 11:52 UTC, ankayca commented on boards/weact/stm32g474_core/board.cmake
> +board_runner_args(stm32cubeprogrammer "--port=swd" "--reset-mode=hw")
No it doesnt. let me correct

2024-12-07 23:10 UTC, ankayca commented on boards/weact/stm32g474_core/board.cmake
> +board_runner_args(stm32cubeprogrammer "--port=swd" "--reset-mode=hw")
Let me ask a question. The board doesn't have an embedded ST-link but I am using an external ST-link as a programmer. If the proper way to declare programmer is [DFU (this board also doesn't have an embedded ST-link)](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/weact/stm32f405_core/board.cmake) , then I get this error and resetting device to boot mode not working to flashing with ST link.
`-- west flash: using runner dfu-util`
`Please reset your board to switch to DFU mode...`

So, how can I specify the programmer in my project file to keep board.cmake like the above board.cmake in DFU mode ?

2024-12-09 08:06 UTC, erwango commented
Your pull request does not conform with Zephyr contribution guidelines. For reference, I'd advise you to check:
- [Contribution guidelines on docs.zephyrproject.org](https://docs.zephyrproject.org/latest/contribute/guidelines.html)
- [Great presentation dealing with "the best way to get your patches merged"](https://youtu.be/mnVNLM7ynMQ) and the related [Slides](https://static.sched.com/hosted_files/zephyr2022/a3/HOWTO_Get_Your_Zephyr_Patches_Merged_ZDS_2022.pdf)
- Coding Guidelines bot results reported below.

Please:
- Check your commit message. It should conform to the following template:
```
<dir>: <dir>: <Title summarizing the change>

<A description useful to the reader>

Signed-off-by: foo <foo@bar.baz>
```
- Remove the merge commit(s)
- We don't merge fixup commits. Please squash all fixes in the corresponding commits
- Split commits into multiple commits when your change impacts multiple subystems
- ...

2024-12-09 12:20 UTC, closed without merging