nxp: combine MONOLITHIC_BT and MONOLITHIC_IEEE802154
zephyrproject-rtos/zephyr pull request #82638
Opened 2024-12-06 08:58 UTC by axelnxp

Combine BLE and 802.15.4 monolithic build under a single config to make it less error prone.
The choice between a BLE/802.15.4 combo firmware and a BLE only firmware is done depending on the SoC (like RW610 vs RW612).

2024-12-06 11:07 UTC, decsny approved these changes, later dismissed

2024-12-06 11:31 UTC, xavraz approved these changes

2024-12-06 14:44 UTC, jhedberg submitted a review, later dismissed

2024-12-09 22:07 UTC, dleach02 requested changes
I have merged the HAL side PR but there is a sequencing of PRs. 

- Depends on #81693 to merge

2024-12-10 03:19 UTC, dleach02 approved these changes

2024-12-10 10:01 UTC, jhedberg approved these changes

2024-12-10 10:11 UTC, merged