boards: weact: Add support for WeAct stm32g474 core board
zephyrproject-rtos/zephyr pull request #82734
Opened 2024-12-09 13:27 UTC by ankayca

STM32G4 series development board with minimum hardware.

Signed-off-by: Ahmet Adin <ankayca2121@gmail.com>

2024-12-11 10:43 UTC, nordicjm commented
Squash commits

2024-12-11 11:42 UTC, ankayca commented
> Squash commits

Does commits look squashed now?

2024-12-11 12:55 UTC, nordicjm commented
> > Squash commits
> 
> Does commits look squashed now?

Commits are, commit message is not, just have one commit message saying adding the board with one sign off

2024-12-11 14:57 UTC, ankayca commented on boards/weact/stm32g474_core/doc/img/weact_stm32g474_core_board.png
I forget to delete png one. How about now ?

2024-12-17 10:55 UTC, nordicjm commented
Merge commit needs to be removed

2024-12-17 10:56 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +
not resolved

2024-12-17 10:57 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +		};
this partitioning doesn't really make any sense, you have 4 partitions but only 2 are going to be used

2025-04-02 08:46 UTC, nordicjm commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +		slot0_partition: partition@8800 {
newline gaps between nodes

2025-04-02 09:54 UTC, kartben commented on boards/weact/stm32g474_core/weact_stm32g474_core.dts
> +		slot0_partition: partition@8800 {
done

2025-04-03 06:32 UTC, nordicjm approved these changes

2025-04-03 06:40 UTC, erwango requested changes
Otherwise LGTM

2025-04-03 06:40 UTC, erwango commented on boards/weact/stm32g474_core/board.cmake
> +include(${ZEPHYR_BASE}/boards/common/stm32cubeprogrammer.board.cmake)
First line is the default runner, and from what I understand only working solution among those is dfu.
A clean up is required in this file

2025-04-03 06:40 UTC, erwango commented on boards/weact/stm32g474_core/weact_stm32g474_core.yaml
> +  - usb device
```suggestion
  - usb_device
```

2025-04-03 06:40 UTC, erwango commented on boards/weact/stm32g474_core/weact_stm32g474_core.yaml
> +  - dma
dma not enabled

2025-04-03 06:40 UTC, erwango commented on boards/weact/stm32g474_core/support/openocd.cfg
> +reset_config srst_only
If openocd isn't actually supported, this should be removed.

2025-04-03 06:40 UTC, erwango commented on boards/weact/stm32g474_core/weact_stm32g474_core.yaml
> +  - rtc
Some ips are missing like rng,dac, ...

2025-04-07 05:46 UTC, kartben commented on boards/weact/stm32g474_core/weact_stm32g474_core.yaml
> +  - rtc
In fairness I think the inspiration was https://github.com/zephyrproject-rtos/zephyr/tree/main/boards%2Fst%2Fnucleo_g474re which has similar gaps :)

2025-04-07 07:17 UTC, erwango commented on boards/weact/stm32g474_core/weact_stm32g474_core.yaml
> +  - rtc
ok, we'll take care to fix it.

2025-06-22 00:43 UTC, closed without merging