drviers: mipi_dbi: mipi_dbi_bitbang: fix 16-bit data_gpios exceed error
zephyrproject-rtos/zephyr pull request #82782
Opened 2024-12-10 11:56 UTC by IotaHydrae

For a 16-bit data bus, "DT_INST_PROP_LEN(n, data_gpios)" returns 16 which is equals "MIPI_DBI_MAX_DATA_BUS_WIDTH(16)". As a result, the assertion will always be triggered.

Use a "<=" condition for the assertion instead.

2024-12-10 12:01 UTC, IotaHydrae commented
I just checked and found an extra space. I hope you can help me modify it.

Best regards,

2024-12-10 16:47 UTC, danieldegrasse approved these changes

2024-12-17 16:52 UTC, kartben approved these changes

2024-12-19 18:16 UTC, danieldegrasse commented
> Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

> 1: UC2 Signed-off-by: must have a full name
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

> d7e3941111387a8520724e2b3e6a3cb3f4b2cfb8: author email (iotah <writeforever@foxmail.com>) does not follow the syntax: First Last <email>.
Compliance error, check for error messages in the "Run Compliance Tests" step
You can run this step locally with the ./scripts/ci/check_compliance.py script.

@IotaHydrae could you fix the commit signoff line when you get a chance?

2024-12-25 03:17 UTC, IotaHydrae commented
> > Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details
> 
> > 1: UC2 Signed-off-by: must have a full name
> > Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details
> 
> > d7e3941111387a8520724e2b3e6a3cb3f4b2cfb8: author email (iotah [writeforever@foxmail.com](mailto:writeforever@foxmail.com)) does not follow the syntax: First Last .
> > Compliance error, check for error messages in the "Run Compliance Tests" step
> > You can run this step locally with the ./scripts/ci/check_compliance.py script.
> 
> @IotaHydrae could you fix the commit signoff line when you get a chance?

Sorry for that, I haven't looked at this PR for a while. 

I've changed the signature. Thanks for your reply.

2024-12-25 03:32 UTC, kartben commented
> > > Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details
> > 
> > > 1: UC2 Signed-off-by: must have a full name
> > > Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details
> > 
> > > d7e3941111387a8520724e2b3e6a3cb3f4b2cfb8: author email (iotah [writeforever@foxmail.com](mailto:writeforever@foxmail.com)) does not follow the syntax: First Last .
> > > Compliance error, check for error messages in the "Run Compliance Tests" step
> > > You can run this step locally with the ./scripts/ci/check_compliance.py script.
> > 
> > @IotaHydrae could you fix the commit signoff line when you get a chance?
> 
> Sorry for that, I haven't looked at this PR for a while. 
> 
> I've changed the signoff. Thanks for your reply.

Thanks! You need to please use your legal name though :)

2024-12-25 03:32 UTC, kartben requested changes
See previous comment

2024-12-25 03:59 UTC, IotaHydrae commented
> See previous comment

Sorry again, it has been modified.

2024-12-26 01:40 UTC, kartben approved these changes

2024-12-26 05:21 UTC, merged