drivers: gpio: add driver for PCA6416 IO expander
zephyrproject-rtos/zephyr pull request #83016
Opened 2024-12-16 03:27 UTC by JiafeiPan

The PCA6416A is a 16-bit general purpose I/O expander that provides remote I/O expansion for most microcontroller families via the I2C-bus interface.

2024-12-17 17:30 UTC, decsny commented on dts/bindings/gpio/nxp,pca6416.yaml
there is an existing binding in linux https://www.kernel.org/doc/Documentation/devicetree/bindings/gpio/gpio-pca95xx.yaml

2024-12-18 01:48 UTC, JiafeiPan commented on dts/bindings/gpio/nxp,pca6416.yaml
Do you mean we need to avoid to use the same binding with Linux? Why? thanks.

2024-12-19 12:44 UTC, decsny commented on dts/bindings/gpio/nxp,pca6416.yaml
No, I mean the opposite, if we can align to linux then try to is all I'm saying, that's a project goal. I didn't look at this too much just wanted to make sure you are aware linux has a binding for this

2024-12-20 01:30 UTC, dleach02 commented on dts/bindings/gpio/nxp,pca6416.yaml
While Zephyr isn't Linux, it does tend to reuse definitions that are in Linux for consistency.

2024-12-20 03:04 UTC, JiafeiPan commented
Rebased and refined some dts node property definitions.

2025-01-24 06:32 UTC, JiafeiPan commented
Rebased and added int-gpios dts binding property.

2025-01-24 18:59 UTC, dleach02 submitted a review, later dismissed

2025-01-27 22:16 UTC, mmahadevan108 commented on drivers/gpio/gpio_pca6416.c
> + *
Why do you have all these Copyrights?

2025-01-27 22:33 UTC, mmahadevan108 commented on dts/bindings/gpio/nxp,pca6416.yaml
> +  interrupt-gpios:
Why do you have 2 of these `interrupt-gpios` and `int-gpios`

2025-01-27 22:35 UTC, mmahadevan108 commented
How was this tested. I do not see any dts binding in an SoC and use of it with a board.

2025-01-27 22:36 UTC, mmahadevan108 requested changes
Need more clarification on test steps.

2025-02-05 03:26 UTC, JiafeiPan commented on drivers/gpio/gpio_pca6416.c
> + *
removed, thanks.

2025-02-05 03:26 UTC, JiafeiPan commented on dts/bindings/gpio/nxp,pca6416.yaml
> +  interrupt-gpios:
removed int-gpios, thanks.

2025-02-05 03:28 UTC, JiafeiPan commented
> How was this tested. I do not see any dts binding in an SoC and use of it with a board.

I wanted to push dts update after the driver is merged, now I put dts update in this PR, so that the driver can be verified by using tests/drivers/gpio/gpio_basic_api testcase. thanks.

2025-02-05 06:15 UTC, JiafeiPan commented
Rebased and addressed @mmahadevan108 's comments.

2025-02-05 23:17 UTC, mmahadevan108 approved these changes

2025-02-06 20:31 UTC, mmahadevan108 commented
@dbaluta can you help review

2025-02-07 20:54 UTC, dleach02 approved these changes

2025-02-07 23:31 UTC, merged