ci: update download-artifact action to v4
zephyrproject-rtos/zephyr pull request #83067
Opened 2024-12-16 21:25 UTC by nashif

v2 is deprecated and not supported anymore.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

2024-12-16 21:40 UTC, kartben requested changes
> However, this is a major update that includes breaking changes. Artifacts created with versions v3 and below are not compatible with the v4 actions. Uploads and downloads must use the same major actions versions. There are also key differences from previous versions that may require updates to your workflows.

Please also update upload-artifact versions otherwise it looks like we'll be in trouble :) (even if they do seem already out-of-sync in some places, e.g the codecov action)

2024-12-16 21:56 UTC, stephanosio submitted a review, later dismissed

2024-12-17 00:03 UTC, cfriedt submitted a review, later dismissed
Could do uploads here or in a separate pr.

2024-12-17 01:39 UTC, kartben commented
> Could do uploads here or in a separate pr.

See my comment above. I would strongly recommend doing it in the same PR has GitHub explicitly says uploads from previous versions of the upload action **DON'T** work 
https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#compatibility

2025-01-09 16:30 UTC, kartben commented
@nashif I wonder if the update can be tested on zephyr-testing first, just in case?

2025-01-09 16:44 UTC, kartben approved these changes

2025-01-09 17:18 UTC, cfriedt approved these changes

2025-01-09 17:19 UTC, cfriedt commented
Assuming all of this will work without a hitch ;-) Merge away @nashif

2025-01-09 21:12 UTC, merged