sensors: codegen for attr/chan/trig
zephyrproject-rtos/zephyr pull request #83077
Opened 2024-12-17 05:32 UTC by yperess

2024-12-23 08:33 UTC, nordicjm requested changes
cmake indent is 2 spaces, apply comments throughout whole PR

2024-12-23 08:33 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +    COMMAND python3 -m pw_sensor.sensor_desc
command is wrong, look at how python is called in other parts of cmake

2024-12-23 08:33 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +      # $ENV{PW_ROOT}/pw_sensor/py/pw_sensor/sensor_desc.py
commented lines can go?

2024-12-23 08:33 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +  add_custom_target(${NAME}.__generate_constants
why are there full stops in target names?

2024-12-23 08:33 UTC, nordicjm commented on doc/requirements.txt
> +pigweed>=0.0.20
why does every user need this?

2024-12-23 08:33 UTC, nordicjm commented on scripts/requirements-base.txt
> +pigweed>=0.0.20
as above

2024-12-23 08:33 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +                  ${z_parse_arg_REQUIRED_ARGS})
weird alignment

2024-12-23 08:33 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +  cmake_parse_arguments(
keep in-fitting with other usage in code e.g.
```
  set(options OPTIONAL EXACT)
  set(single_args FORMAT DEFAULT_REVISION HIGHEST_REVISION)
  set(multi_args  VALID_REVISIONS)
  cmake_parse_arguments(BOARD_REV "${options}" "${single_args}" "${multi_args}" ${ARGN})
```

2025-01-09 17:24 UTC, yperess commented on cmake/modules/extensions.cmake
> +    COMMAND python3 -m pw_sensor.sensor_desc
Done

2025-01-09 17:24 UTC, yperess commented on cmake/modules/extensions.cmake
> +      # $ENV{PW_ROOT}/pw_sensor/py/pw_sensor/sensor_desc.py
Yup, thanks

2025-01-09 17:25 UTC, yperess commented on doc/requirements.txt
> +pigweed>=0.0.20
The Pigweed python library is where we developed the sensor codegen library. This allowed us to start onboarding teams that don't use Zephyr to use the same sensor standard descriptor without having to add Zephyr as a dependency (yet).

2025-01-09 17:26 UTC, yperess commented on scripts/requirements-base.txt
> +pigweed>=0.0.20
Same as above, I'm going to mark this one as resolved so we can have a single thread of discussion.

2025-01-09 17:28 UTC, yperess commented on cmake/modules/extensions.cmake
> +                  ${z_parse_arg_REQUIRED_ARGS})
Fixed

2025-01-09 17:49 UTC, yperess commented on cmake/modules/extensions.cmake
> +  add_custom_target(${NAME}.__generate_constants
Why not? I've used them before in other projects. I'm happy to remove them. I use them to denote subpackage like targets. Makes it harder for things to collide when generating targets.

I'm happy to remove the `.` if you feel strongly about it.

2025-01-09 19:10 UTC, yperess commented on cmake/modules/extensions.cmake
> +  cmake_parse_arguments(
Done

2025-01-28 07:50 UTC, nordicjm commented on cmake/modules/extensions.cmake
> +  add_custom_target(${NAME}.__generate_constants
@tejlmand

2025-03-13 13:39 UTC, ubieda commented on include/zephyr/drivers/sensor.h
Do enums `sensor_channel`, `sensor_trigger_type` `sensor_attribute` need to be deleted for this to work?

I'm concerned of two things:
1. Obfuscation of supported public sensor parameters.
2. Breakage of downstream applications and drivers that have not yet adopted the YAML pattern (in-tree or downstream).

Could we get more details around this?

2025-03-13 17:34 UTC, teburd reviewed
Please fix all the SPDX license identifiers. I seriously question why we need to pull in a pigweed python module to do zephyr code generation, this feels a backwards in all the wrong ways to me and makes me hesitant to +1. I don't see why a few hundred lines of python code gen couldn't simply exist in zephyr like the DTS and Kconfig code we already have in the tree making sure its easy to fix.

If a problem in this pigweed code comes up how do you even go about getting it fixed? Will Zephyr have to wait on this? Confusing how this would work to me.

2025-03-13 19:09 UTC, yperess commented on include/zephyr/drivers/sensor_spec.h
> +#define SENSOR_SPEC_COMPAT(compat) UTIL_CAT(SENSOR_SPEC, DT_DASH(compat))
I think that we need to separate responsibilities here,

* Static information generated by the `sensor.yaml` is intended to be a superset of features.
* Per instance information should be probed at runtime using the sensor API.

So in the case of a sensor hub, I this we can do something like:

```
sensor_hub: some-hub@20 {
  compatible = "org,some-hub";
  secondary = <&some_magn>;
};

some_magn: some-magn@24 {
  compatible = "org,some-magn";
};
```

Here we should be able to query:
```c
#define HUB                DT_NODELABEL(sensor_hub)
#define SECONDARY          DT_PHANDLE(HUB, secondary)
#define SECONDARY_COMPAT   DT_PROP(MAGN, compatible)
#define SECONDARY_HAS_MAGN (SENSOR_SPEC_CHAN_INST_COUNT(SECONDARY_COMPAT, SENSOR_CHAN_MAGN_XYZ) > 0)
```

We can probably write shorthand macros for this.

2025-03-13 19:10 UTC, yperess commented on scripts/sensors/gen_defines.py
> +import pw_sensor.constants_generator as pw_sensor
Collapsing into https://github.com/zephyrproject-rtos/zephyr/pull/83077#discussion_r1993720037 so we have 1 thread about why the dependency

2025-03-13 19:20 UTC, yperess commented on scripts/requirements-base.txt
> +pigweed==0.0.21
There are a few reasons why this cannot live in Zephyr and I'm happy to meet and see if maybe you have a better idea about this.

1. Pigweed is supposed to be RTOS agnostic.

So you can use it with Zephyr or FreeRTOS etc. We're adding a `pw::sensor::Sensor` class which will also use the same spec for the sensor YAML which way it's compatible. In the case when the developer is using Pigweed + Zephyr this is seamless, the `pw::sensor::Sensor` class just wraps around a `const struct device*` and uses the generated macros from the YAML to allocate the right buffers and set the right template parameters.

This means that if we were to move the YAML generation into Zephyr then a Pigweed + FreeRTOS project would also have to download and depend on Zephyr. In previous discussions we talked about proving C++ via pigweed and that was shot down so we're not adding it as a module, but @nashif did say he's OK with just a python dependency.

2. Getting more Google teams on Zephyr

While Keith and I are working on getting more teams to buy into Zephyr, it's a big sell. Almost all firmware teams in Google already use Pigweed so by having them already switch to `pw::sensor::Sensor` and getting all the benefits of the codegen without having to add a new dependency gets them closer aligned to Zephyr. When the time comes, it'll be an easier sell to get them to switch to Zephyr.

A very reasonable response to this is "why should we care?" and I recognize that. But I do think that if we can do things that will make products adopting Zephyr less costly we should consider them. At the end of the day, more users of Zephyr is good for the project.

### Summary
There was a lot there so I want to summarize. We use the Pigweed python package to run the front end of the code generation. It validates the schemas and gets everything into a single yaml. That front end then calls into the Zephyr code generation backend which also uses Pigweed's library to make the parsing faster and it generates Zephyr code. So the dependencies are:
* Zephyr depends on Pigweed python
* Pigweed source depends on any RTOS (Zephyr is one of them)

2025-03-13 19:25 UTC, yperess commented on include/zephyr/drivers/sensor.h
So I mentioned in my comment at https://github.com/zephyrproject-rtos/zephyr/issues/71235#issuecomment-2711102815 that we have 2 options. I chose the one that I like better here as the demo.

1. Yes, you're right, public sensor enums are now moved to the `.yaml` files. So if you want to add a new one you have to go there. This is better than the alternative (in my opinion) of having to add it to 2 places (`.yaml` file and `sensor.h`).
2. Downstream applications will not be broken. The current set of `attributes.yaml`, `channels.yaml`, and `triggers.yaml` produce the exact same enums that we had before and included in the codegen template the various `_PRIV_START` and `_MAX` enums. So even in the tree, all the sensors that define their own custom attributes, channels, and triggers still work as is.

The alternative to this is to duplicate the enums in `sensor.h` and having a period of time where new values are added to both the header and the `.yaml` files.

2025-06-16 00:41 UTC, closed without merging