STM32WB0: add TRNG support
zephyrproject-rtos/zephyr pull request #83152
Opened 2024-12-18 11:04 UTC by mathieuchopstm

Add support for TRNG of STM32WB0 series to existing STM32 driver. Test overlay for Nucleo-WB05KZ and Nucleo-WB09KE is also added so that correct behavior can be verified.

Tested OK using standard `tests/drivers/entropy/api` and modified version that also verifies entropy_get_entropy_from_isr and large buffer sizes. Also tested on Nucleo-WB07CC, but board is not upstream yet.

Potentially supersedes #83109 - driver modification is split in two commits and PR is marked as draft for this reason.

2025-01-02 15:42 UTC, mathieuchopstm commented
* Mark cross-LL wrappers as `inline` to silence `-Wunused-function` (should fix CI failures)
* Improved readability by factoring in and indenting preprocessor checks better
* Corrected a typo in a comment

2025-01-09 15:08 UTC, erwango requested changes

2025-01-13 14:03 UTC, erwango reviewed
Otherwise LGTM

2025-01-13 14:40 UTC, erwango approved these changes

2025-01-15 16:15 UTC, djiatsaf-st reviewed
Otherwise LGTM

2025-01-15 16:15 UTC, djiatsaf-st commented on tests/drivers/entropy/api/boards/nucleo_wb05kz.overlay
> + * Copyright (c) 2024 STMicroelectronics
2025 

Apply everywhere

2025-01-17 15:15 UTC, djiatsaf-st approved these changes

2025-01-21 12:58 UTC, tomi-font approved these changes
Didn't check the entropy driver source changes but the rest looks good!

2025-01-21 13:22 UTC, erwango commented
@ceolin PTAL

2025-01-22 06:34 UTC, ceolin approved these changes
LGTM

2025-01-22 07:07 UTC, merged