hostap: Relocate hostapd related source code to new files
zephyrproject-rtos/zephyr pull request #83253
Opened 2024-12-20 06:28 UTC by nxf58150

Created new files and relocate hostapd support code in glue layer to new files. The new files will be compiled only if hostapd support is enabled.

2024-12-20 06:31 UTC, nxf58150 commented
This PR is related to issue https://github.com/zephyrproject-rtos/zephyr/issues/77383

2024-12-25 05:50 UTC, nxf58150 commented
Hi @krish2718 , please help review this PR. As discussed before, I moved the hostapd related source code to new files. Please also help add Jerome as reviewer. Thanks!

2025-01-14 14:38 UTC, krish2718 submitted a review, later dismissed

2025-01-14 17:04 UTC, jerome-pouiller reviewed
This definitely goes in the right direction.

(I would have appreciated smaller commits, but this is not a big deal).

2025-01-14 17:04 UTC, jerome-pouiller commented on modules/hostap/src/supp_main.c
> +#endif
Do you think it would make sense to relocate this function in `hapd_main.c` and do the same pattern than `get_default_context(void)`:
```
static struct hapd_interfaces *zephyr_get_default_hapd_context(void)
{
	static struct hapd_interfaces ctx;

	return &ctx;
}
```
Thus, `struct hapd_interfaces` won't have to be known in supplicant. It may lead to further simplifications.

2025-01-15 02:29 UTC, MaochenWang1 commented on modules/hostap/src/supp_api.h
> +enum wifi_security_type wpas_key_mgmt_to_zephyr(int key_mgmt, int proto);
```suggestion
enum wifi_security_type wpas_key_mgmt_to_zephyr(bool is_hapd, void *config, int key_mgmt, int proto, int pwe);
```

2025-01-15 02:29 UTC, MaochenWang1 commented on modules/hostap/src/supp_api.h
> +enum wifi_security_type wpas_key_mgmt_to_zephyr(int key_mgmt, int proto);
please also remove the `static inline` from definition

2025-01-15 02:33 UTC, MaochenWang1 commented on modules/hostap/src/hapd_api.c
> +	{WIFI_SECURITY_TYPE_EAP_TLS_SHA256, WIFI_EAP_TYPE_TLS, WIFI_EAP_TYPE_NONE, "TLS", NULL},
In TOT, `WIFI_SECURITY_TYPE_EAP_TLS_SHA256` has been removed

2025-01-15 02:46 UTC, MaochenWang1 requested changes
please try to build as the codebase updated

2025-02-08 07:00 UTC, nxf58150 commented on modules/hostap/src/hapd_main.c
> +	bss->ap_setup_locked = 1;
The parameter ap_setup_locked is defined in ap_config.h and wrapped by CONFIG_WPS flag in hostap. If I remove the compiler flag and change it to bss->ap_setup_locked = IS_ENABLED(CONFIG_WPS), there will be compile error once CONFIG_WPS is disabled.

2025-02-08 07:01 UTC, nxf58150 commented on modules/hostap/src/hapd_main.c
> +	conf->acs_num_scans  = 1;
Same as above. There will be compile error if CONFIG_ACS is disabled.

2025-02-08 07:50 UTC, nxf58150 commented on modules/hostap/src/hapd_main.c
> +#endif /* CONFIG_DPP */
I tried it locally but found that there will be compile errors if CONFIG_DPP is disabled. For example, the `interface->dpp` is wrapped with CONFIG_DPP flag in hostapd.h.

2025-02-11 08:42 UTC, nxf58150 commented on modules/hostap/src/supp_main.c
> +#endif
There is a global variable `ctx` defined in `supp_main.c`. Both wpa_supplicant and hostapd variables are in it. 
![image](https://github.com/user-attachments/assets/f27ae756-8ddb-4502-830b-4fdb3e30f651)
When doing hostapd init, the `ctx->hostapd` will be initialized. The API `zephyr_get_default_hapd_context()` is used to get `ctx->hostapd` and use it in `hapd_xxx.c`. 
I don't think this API could be relocate to `hapd_main.c`.

2025-02-18 07:14 UTC, nxf58150 commented on modules/hostap/src/hapd_main.c
> +void zephyr_hostapd_init(void *ctx)
Updated.

2025-02-18 07:14 UTC, nxf58150 commented on modules/hostap/src/supp_api.h
> +enum wifi_security_type wpas_key_mgmt_to_zephyr(int key_mgmt, int proto);
Updated.

2025-02-18 07:19 UTC, nxf58150 commented on modules/hostap/src/hapd_api.c
> +	{WIFI_SECURITY_TYPE_EAP_TLS_SHA256, WIFI_EAP_TYPE_TLS, WIFI_EAP_TYPE_NONE, "TLS", NULL},
Removed. Thanks!

2025-02-18 07:22 UTC, nxf58150 commented on modules/hostap/src/supp_api.c
> +#endif
I didn't get your point here. I included the header file there because some APIs used in supp_api.c is defined in hapd_api.h. If CONFIG_WIFI_NM_HOSTAPD_AP is disabled, all those APIs in hapd_api.h/hapd_api.c will not be available. Could you please provid more info? Thanks!

2025-02-19 10:36 UTC, jerome-pouiller commented on modules/hostap/src/supp_api.c
> +#endif
If the functions are not declared, you have to place all the call inside a `#ifdef` block (ditto for struct declarations). This makes the code difficult to read.

So, even if the definition of the function are not available, it make sense to have declarations.

Obviously, the definitions are not available. So, if the code wants to link with the function, you will get an error during the link. However, it should not happen if the code is correct.

Reference: https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-1-conditional-compilation

2025-02-19 11:12 UTC, jerome-pouiller commented on modules/hostap/src/supp_main.c
> +#endif
I have been tricked by the names. Many people would assume `supplicant` is a `struct supplicant_context`. Probably we should rename `struct supplicant_context` (`struct wifi_nm_context`?)

2025-02-19 11:12 UTC, jerome-pouiller commented on modules/hostap/src/supp_main.c
> +#endif
BTW, for the consistency, is supplicant field required when we compile with `CONFIG_WIFI_NM_HOSTAPD_AP`?

2025-02-20 02:39 UTC, nxf58150 commented on modules/hostap/src/supp_main.c
> +#endif
For renaming `struct supplicant_context`, I think we can discuss this with Chaitanya or Jukka because the structure is initialized by them and many vendors are using this structure.
Based on current implementation, I think `supplicant` is a must have field, no matter `CONFIG_WIFI_NM_HOSTAPD_AP` is enabled or not.

2025-02-28 06:26 UTC, nxf58150 commented on modules/hostap/src/supp_api.c
> +#endif
Removed compiler flag. Thanks!

2025-02-28 06:26 UTC, nxf58150 commented on modules/hostap/src/hapd_events.h
> +int hostapd_send_wifi_mgmt_ap_status(void *ctx,
Yes, it works. Updated.

2025-02-28 06:27 UTC, nxf58150 commented on modules/hostap/src/hapd_events.h
> +int hostapd_send_wifi_mgmt_ap_sta_event(void *ctx,
Updated.

2025-03-18 07:08 UTC, jukkar commented
The hostap PR is now merged.

2025-03-18 08:30 UTC, MaochenWang1 approved these changes, later dismissed

2025-03-20 07:47 UTC, nxf58150 commented
Hi @jerome-pouiller, could you please help review this PR again? If you don't have further questions, could you please approve this PR? Thanks!

2025-03-20 08:19 UTC, jerome-pouiller submitted a review, later dismissed
I am glad to see all these `#ifdef` to disappear.

2025-04-08 14:42 UTC, jukkar approved these changes

2025-04-08 15:46 UTC, jerome-pouiller approved these changes

2025-04-08 15:50 UTC, krish2718 approved these changes

2025-04-09 01:58 UTC, MaochenWang1 approved these changes

2025-04-09 10:35 UTC, merged

2025-04-09 11:38 UTC, kartben commented
@nxf58150 this is causing CI failures in main, please take a look
https://github.com/zephyrproject-rtos/zephyr/actions/runs/14355073679/job/40242564584#step:11:1

@jukkar @krish2718