usb: webusb: Strip CDC ACM function from the code
zephyrproject-rtos/zephyr pull request #8328
Opened 2018-06-12 07:05 UTC by finikorg

CDC ACM is not needed in webusb, communication is going through Bulk
endpoints. Endpoint numbers stay the same only Interface number
changed, so basically only this change is needed:

-        .then(() => this.device_.claimInterface(2))
+        .then(() => this.device_.claimInterface(0))

this.device_.claimInterface({2,0}) apart from removing serial port
commands.

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

2018-06-12 07:05 UTC, finikorg commented
@nagineni Please look at the changes

2018-06-13 12:51 UTC, finikorg commented
@loicpoulain could you check this commit 3babe7523c4c2836efbddd695cf3ff1e3b1b0d56

2018-06-13 13:47 UTC, loicpoulain requested changes
Hello Andrei, at first look, I don't understand this patch, we support only one transfer at a time on a same Endpoint. Requesting a transfer while an other one is ongoing is 'normally' rejected. caller can either use **usb_transfer_sync** to be sure transfer is completed after the call OR use **usb_transfer** and wait for the transfer callback before rescheduling a new one.

2018-06-14 07:37 UTC, finikorg commented
@loicpoulain btw, in this sample when we have echoed back 1 bytes transfer this situation is possible. In usb_transfer I have not found code which would reject another transfer.

2018-06-14 08:37 UTC, loicpoulain commented
@finikorg, you're right! I missed this in the last version of transfer patches. So this is something we need to fix, the simple way is to return -EBUSY if a transfer on the same endpoint is ongoing.

2018-06-18 22:34 UTC, jfischer-phytec-iot commented
@finikorg did not work for me, boards: arduino101 and frdm_k64f, webusb-serial changes:
```
--- a/index.html
+++ b/index.html
@@ -21,6 +21,7 @@ var serial = {};
     const filters = [
       { 'vendorId': 0xDEAD, 'productId': 0xBEEF },
       { 'vendorId': 0x8086, 'productId': 0xF8A1 },
+      { 'vendorId': 0x2fe3, 'productId': 0x0100 },
     ];
     return navigator.usb.requestDevice({ 'filters': filters }).then(
       device => new serial.Port(device)
@@ -47,7 +48,7 @@ var serial = {};
             return this.device_.selectConfiguration(1);
           }
         })
-        .then(() => this.device_.claimInterface(2))
+        .then(() => this.device_.claimInterface(0))
         .then(() => this.device_.controlTransferOut({
             'requestType': 'class',
             'recipient': 'interface',

```

2018-06-19 07:41 UTC, finikorg commented
@jfischer-phytec-iot Sorry, forgot to mention all patches needed. See: https://github.com/finikorg/webusb-serial/commits/master

I think missing patche is: 18b8f8af94ff2b417421c7987c38c1f4dcf8e7fd

2018-06-19 21:56 UTC, jfischer-no approved these changes
LGTM,  webusb_serial_usb_description should also be revised, can be done in other PR. This PR works, also rebased on master, but could be confusing for a user.

2018-06-20 07:09 UTC, loicpoulain approved these changes

2018-06-20 08:45 UTC, finikorg commented
@jfischer-phytec-iot I will revisit also  webusb_serial_usb_description following your changes in the next PRs.

2018-06-21 13:13 UTC, nashif commented
rebase please

2018-06-21 14:00 UTC, finikorg commented
@nashif rebased

2018-06-22 16:29 UTC, merged