drivers: usb: Fix pointer reference in the NXP drivers
zephyrproject-rtos/zephyr pull request #83284
Opened 2024-12-20 14:51 UTC by mmahadevan108

The address passed in to the function was incorrect causing failures when porting to RT1180.

2024-12-20 15:19 UTC, EmilioCBen submitted a review, later dismissed

2024-12-20 16:06 UTC, decsny submitted a review, later dismissed

2024-12-20 16:07 UTC, jfischer-no approved these changes

2024-12-20 16:09 UTC, decsny commented
@jfischer-no is this not trivial?

2024-12-20 16:13 UTC, jfischer-no requested changes

2024-12-20 16:21 UTC, decsny commented on drivers/usb/udc/udc_mcux_ehci.c
> +			(usb_phy_config_struct_t *)config->phy_config);
your comment is unclear to me here, are you commenting on the formatting of the whitespace?

2024-12-20 16:44 UTC, jfischer-no commented on drivers/usb/udc/udc_mcux_ehci.c
> +			(usb_phy_config_struct_t *)config->phy_config);
The cause of this error is an unnecessary pointer type conversion. Yes, there is nothing trivial in the USB area, although I prefer to decide what.

2024-12-20 17:03 UTC, dleach02 commented on drivers/usb/udc/udc_mcux_ehci.c
> +			(usb_phy_config_struct_t *)config->phy_config);
Okay, if the phy_config is already a pointer to usb_phy_config_struct_t then yes, I agree the casting is not needed and would have hid the original error.

2024-12-20 18:49 UTC, decsny approved these changes

2024-12-21 09:19 UTC, jfischer-no approved these changes

2024-12-21 14:09 UTC, henrikbrixandersen approved these changes

2024-12-23 01:17 UTC, MarkWangChinese approved these changes

2024-12-24 15:07 UTC, merged