drivers: flash: stm32h7 write protection and block registers functionalities
zephyrproject-rtos/zephyr pull request #83317
Opened 2024-12-23 06:45 UTC by niedzwiecki-dawid

Add support for extended operations write protection and block option/control registers.

This PR depends on:
- PR#83266
- PR#83273
- PR#83261

2024-12-23 08:19 UTC, niedzwiecki-dawid commented
Fails are caused by needed API changes #83273

2025-01-07 09:19 UTC, niedzwiecki-dawid commented
PR is ready to be reviewed

2025-01-08 12:47 UTC, erwango requested changes

2025-01-08 12:47 UTC, erwango commented on drivers/flash/Kconfig.stm32
> +	depends on SOC_SERIES_STM32F4X || SOC_SERIES_STM32H7X
If code also supports H7RS, it should also be populated here.
Otherwise let's remove H7RS related code below

2025-01-13 11:15 UTC, niedzwiecki-dawid commented on drivers/flash/Kconfig.stm32
> +	depends on SOC_SERIES_STM32F4X || SOC_SERIES_STM32H7X
Done

2025-01-17 08:04 UTC, erwango approved these changes, later dismissed

2025-01-21 12:37 UTC, duda-patryk requested changes

2025-01-21 12:37 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +	uint32_t sectors_per_bank = 32 - __builtin_clz(bank_mask);
`__builtin_clz()` counts leading 0-bits starting from most significant bit, but `bank_mask` is 64 bit variable. Is this a problem?

EDIT:
This probably works because `__builtin_clz()` takes `unsigned int` which is probably 32 bit. I think you should probably use `__builtin_clzll()`. It would be even better if you'd use `__builtin_popcountll()` which counts 1-bits.

2025-01-21 12:37 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +		(volatile uint32_t *)((uint32_t)regs + offsetof(FLASH_TypeDef, WRPSR));
We should use `uintptr_t` (or `intptr_t`) if you want to keep pointer as a variable.

2025-01-21 12:37 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +#endif /* DUAL_BANK */
I see this is repeated below. Can we introduce some define for that e.g. `NUMBER_OF_BANKS`?

2025-01-21 12:37 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +	uint32_t sectors_per_bank = 32 - __builtin_clz(bank_mask);
Do we have a guarantee that each bank has the same number of sectors?

2025-01-22 07:04 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	uint32_t sectors_per_bank = 32 - __builtin_clz(bank_mask);
Yes, from I saw in the HAL, there is always one mask defined for both banks.

2025-01-22 09:33 UTC, niedzwiecki-dawid commented
Rebased and changes after review.

2025-01-22 09:33 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +#endif /* DUAL_BANK */
Done.

2025-01-22 09:33 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +		(volatile uint32_t *)((uint32_t)regs + offsetof(FLASH_TypeDef, WRPSR));
This definitely makes sense :-)

2025-01-22 09:38 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	uint32_t sectors_per_bank = 32 - __builtin_clz(bank_mask);
Agree, I think `__builtin_popcount()` + cast to `uint32_t` makes most sense, because `__builtin_popcount` is most standard and there is no risk of lack of implementation.

2025-01-22 10:23 UTC, duda-patryk requested changes

2025-01-22 10:23 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +	rc = flash_stm32_wait_flash_idle(dev);
From RM0433 Rev 8 p. 175
```
To modify user option bytes, follow the sequence below:

1. Unlock FLASH_OPTCR register as described in Section 4.5.1: FLASH configuration
protection, unless the register is already unlocked.
2. Write the desired new option byte values in the corresponding option registers
(FLASH_XXX_PRG1/2).
3. Set the option byte start change OPTSTART bit to 1 in the FLASH_OPTCR register.
4. Wait until OPT_BUSY bit is cleared.
```

I think we are not waiting for `OPT_BUSY` bit to clear

2025-01-23 12:10 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	rc = flash_stm32_wait_flash_idle(dev);
You are so right. I sent #84430 that also fixes that problem for RDP and this PR can reuse added functions. So I'll wait till #84430 is merged

2025-01-29 08:26 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	uint32_t sectors_per_bank = __builtin_popcount((uint32_t)bank_mask);
Changed.

2025-01-29 08:26 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	rc = flash_stm32_wait_flash_idle(dev);
Done.

2025-01-29 13:04 UTC, duda-patryk requested changes

2025-01-29 13:04 UTC, duda-patryk commented on drivers/flash/flash_stm32h7x.c
> +		}
I think, error handling here is not that simple as you might expect. What would happen if the `write_optwp()` function fails for the second bank? What would happen if we fail to update the first bank, but the second would succeed? Even if we commit option bytes outside of the loop as I suggest in the other comment, returning error here will basically skip commit.

2025-01-31 14:34 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +	uint64_t bank_mask = WP_MSK >> WP_POS;
Done.

2025-01-31 14:41 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +		}
Am I understanding correctly that you think it would be good to commit changes, even if call `write_optwp(dev, changed_sectors_reg, protected_sectors_reg, i, false);` fails for one of the banks? (not current version)

2025-02-03 09:47 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +		}
You are right.

2025-02-03 09:47 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +		if (changed_sectors == 0) {
Done.

2025-02-03 12:06 UTC, duda-patryk requested changes

2025-02-03 13:11 UTC, niedzwiecki-dawid commented on drivers/flash/flash_stm32h7x.c
> +		}
Done.

2025-02-03 13:21 UTC, duda-patryk submitted a review, later dismissed

2025-02-04 12:39 UTC, erwango commented on tests/drivers/flash/stm32/testcase.yaml
> +            dt_label_with_parent_compat_enabled("storage_partition", "fixed-partitions")
This filter will also match for h7rs based platforms. Is that expected ?

2025-02-04 12:43 UTC, niedzwiecki-dawid commented on tests/drivers/flash/stm32/testcase.yaml
> +            dt_label_with_parent_compat_enabled("storage_partition", "fixed-partitions")
No, since it is not supported for h7rs. Isn't platform allow enough?

2025-02-04 13:49 UTC, erwango commented on tests/drivers/flash/stm32/testcase.yaml
> +            dt_label_with_parent_compat_enabled("storage_partition", "fixed-partitions")
Right, but then maybe filter on `CONFIG_SOC_SERIES_STM32H7XX` instead of this compatible which cover both series to be consistent.

2025-02-04 14:28 UTC, niedzwiecki-dawid commented on tests/drivers/flash/stm32/testcase.yaml
> +            dt_label_with_parent_compat_enabled("storage_partition", "fixed-partitions")
Done.

2025-02-04 14:32 UTC, duda-patryk approved these changes

2025-02-04 14:38 UTC, erwango approved these changes

2025-02-06 13:45 UTC, merged