drivers: udc: add support for USB device on Renesas RA USBFS HWIP
zephyrproject-rtos/zephyr pull request #83358
Opened 2024-12-24 11:26 UTC by thenguyenyf

This PR to add support for USB device on USBFS port of Renesas RA family
- Add missing uclk clock node on RA2A1
- Remove old binding of renesas,ra-usb → renesas,ra-usbhs and renesas,ra-usbfs
- Remove unused interrupts of USBHS device in Renesas RA dts
- Add driver support for Renesas RA USBFS module
- Add support for USB device on Renesas RA USBFS port

2025-01-09 13:13 UTC, tmon-nordic submitted a review, later dismissed

2025-01-21 08:43 UTC, thaoluonguw approved these changes, later dismissed

2025-01-21 08:44 UTC, thaoluonguw commented
@thenguyenyf : Please rebase to solve conflict.

2025-01-23 01:24 UTC, thenguyenyf commented
Last push to update the hal_renesas rev, because it was merged, and solve the conflict

2025-01-23 10:57 UTC, jfischer-no requested changes

2025-01-23 10:57 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +	static int udc_renesas_ra_driver_preinit_##id(const struct device *dev)                    \
This can be normal function as you have dev parameter, no need to put it inside macro.

2025-01-23 10:57 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +			uint32_t uclk_src = RA_CGC_CLK_SRC(DT_CLOCKS_CTLR(DT_NODELABEL(uclk)));    \
Variable definition should be at the top of a block.

2025-01-23 10:57 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +	static int renesas_ra_usb_irq_config##id(const struct device *dev)                         \
Can be normal function, no need to place it inside macro.

2025-01-23 10:57 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +	static void udc_renesas_ra_make_thread_##id(const struct device *dev)                      \
Stray change, no need to introduce id.

2025-01-23 10:57 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +		.irq_config_func = renesas_ra_usb_irq_config##id};                                 \
```c
		.irq_config_func = renesas_ra_usb_irq_config##id
	};
```
Style issue, please fix it everywhere.

2025-02-03 08:15 UTC, thenguyenyf commented
Last push to rebase main branch and solve conflict

2025-02-03 09:03 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +	static int udc_renesas_ra_driver_preinit_##id(const struct device *dev)                    \
I fixed it

2025-02-03 09:03 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +			uint32_t uclk_src = RA_CGC_CLK_SRC(DT_CLOCKS_CTLR(DT_NODELABEL(uclk)));    \
I fixed it

2025-02-03 09:03 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +	static int renesas_ra_usb_irq_config##id(const struct device *dev)                         \
I fixed it

2025-02-03 09:03 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +	static void udc_renesas_ra_make_thread_##id(const struct device *dev)                      \
I fixed it

2025-02-03 09:03 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +		.irq_config_func = renesas_ra_usb_irq_config##id};                                 \
I fixed it

2025-02-03 09:40 UTC, tmon-nordic submitted a review, later dismissed

2025-02-04 01:09 UTC, thenguyenyf commented
Last push to update the board document and add support for voice_ra4e1

2025-02-06 07:46 UTC, tmon-nordic submitted a review, later dismissed

2025-02-07 01:53 UTC, duynguyenxa submitted a review, later dismissed

2025-02-12 10:29 UTC, thenguyenyf commented
Last push to rebase main and solve conflict

2025-02-13 03:52 UTC, thaoluonguw approved these changes, later dismissed

2025-02-13 13:27 UTC, tmon-nordic submitted a review, later dismissed

2025-02-13 13:36 UTC, jfischer-no commented on drivers/usb/udc/udc_renesas_ra.c
> +				.module_number = USB_RENESAS_RA_MODULE_NUMBER(DT_INST_PARENT(n)),  \
```c

		.udc_cfg = {                                                                       \
			.module_number = USB_RENESAS_RA_MODULE_NUMBER(DT_INST_PARENT(n)),  \
```

2025-02-14 04:21 UTC, thenguyenyf commented on drivers/usb/udc/udc_renesas_ra.c
> +				.module_number = USB_RENESAS_RA_MODULE_NUMBER(DT_INST_PARENT(n)),  \
I fixed it

2025-02-14 07:22 UTC, jfischer-no approved these changes

2025-02-14 07:24 UTC, thaoluonguw approved these changes

2025-02-14 07:27 UTC, KhiemNguyenT approved these changes

2025-02-14 07:44 UTC, merged