Feature/optimize a2dp avdtp
zephyrproject-rtos/zephyr pull request #83375
Opened 2024-12-25 03:38 UTC by MarkWangChinese

- When the cmd packet is invalid (buf->len is not enough), reply with reject.
- Split the packet handler to cmd_handler and rsp_handler, and optimize the handler array to be function pointer array.
- If receiving the unsupported cmd (signal identifier), send reject or discard it.
- Optimize `bt_a2dp_ep_info`'s field `struct bt_avdtp_sep_info sep_info` as `struct bt_avdtp_sep_info *sep_info`, see the explain in the commit.

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	}
This could use a bit more vertical whitespace to improve readability. E.g. add empty lines after `}` and before `if (...`

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	avdtp_sep_unlock(sep);
Ok, I see that this "monolithic blocks" style is quite pervasive, so you might want to do a separate cleanup commit to fix it.

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	if (!err && !ret) {
`else if (!err) {` perhaps? You should also fix the variable naming & usage here, since it's super confusing to have both `err` and `ret`. Is it possible to remove one of them? If not, you need to use names which are more descriptive.

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	if (msg_type == BT_AVDTP_ACCEPT && req->status == BT_AVDTP_SUCCESS) {
Same thing here with the lack of vertical white space. Simple way to improve the readability is to have an empty line at least after every `}` and before `if (...) {`

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	if (req->status == BT_AVDTP_SUCCESS) {
Here you're doing it right - I just don't understand why you're not consistent about it.

2025-01-07 07:23 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	if (!err && !ret) {
Same thing here. There's a general convention in Zephyr to use either `err` or `ret` for `int` style generic error variable. The convention in Bluetooth code has been to use `err`. However, it gets really confusing when you have both - please don't do that. Note: I can see that this problem exists even before this PR, so fixing it doesn't necessarily have to be done in this commit/PR as long as it get fixed ASAP.

2025-01-08 07:21 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +	if (!err && !ret) {
Hi @jhedberg  I add one commit to address all the blank line issue, please help to review. One exception that I do is: if the code `if (xx) {`'s condition use the previous simple code line's result, I put the previous simple codes lines near with the `if (xx) {`. like: https://github.com/zephyrproject-rtos/zephyr/pull/83375/files#diff-aebc3083e23e5c1f24f55bc6bf88e71ffa3ddc8dbae92db402bd4fa8402aa461L585-L587
This is my understand. please help to check whether it is right.

For `err` and `ret`, I plan to change `err` as `cmd_err` because it is result of processing the cmd, change `ret` as `l2cap_ret` because it is the l2cap send api return value in next pr after this pr is merged.

2025-01-15 11:27 UTC, lylezhu2012 requested changes

2025-01-16 08:35 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/a2dp.c
>  			a2dp->get_capabilities_param.buf = NULL;
updated

2025-01-16 08:35 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +		if (msg_type == BT_AVDTP_ACCEPT && req->status == BT_AVDTP_SUCCESS) {
updated

2025-01-16 08:35 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +		if (msg_type == BT_AVDTP_ACCEPT && req->status == BT_AVDTP_SUCCESS) {
updated

2025-01-16 08:35 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/a2dp.c
>  	a2dp->discover_param.buf = NULL;
updated

2025-02-19 08:52 UTC, jhedberg requested changes

2025-02-19 08:52 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	avdtp_set_status(req, buf, msg_type);
This looks buggy to me from a net_buf reference counting perspective. In the first branch (AVDTP_ACCEPT) you seem to moving the reference to `DISCOVER_REQ(req)->buf` whereas in the `else` branch the reference stays as-is. Yet, there's no difference in later treatment of the `buf` pointer. If you really intend to move the reference, it'd be best to set the original pointer (`buf`) immediately to NULL, so that it can't be used anymore. If you don't intend to move the reference, you should be using `net_buf_ref()` as part of the assignment to `DISCOVER_REQ(req)->buf`.

2025-02-19 11:52 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +	avdtp_set_status(req, buf, msg_type);
`DISCOVER_REQ(req)->buf` is set to be used by the upper (a2dp) layer, no `buf` needs to be passed to a2dp and `DISCOVER_REQ(req)->buf` is `NULL` if fail. `avdtp_set_status` set the result to be used by the upper (a2dp) layer too. So, the buf is always valid when calling `avdtp_set_status`.
Anyway your comment is right from reading only this part of codes. I will change it as the follow codes.
I have one query, is the `net_buf_ref` needed from your viewpoint? The `DISCOVER_REQ(req)->buf` should be only used in the `req->fun(req)` callback, `unref` is needed after callback. Without `ref` and `unref`, we can reduce codes. 

Note: If the upper layer (a2dp) want to keep the buf, a2dp need to ref the `DISCOVER_REQ(req)->buf` and keep it from my understand.
```
	avdtp_set_status(req, buf, msg_type);

	if (msg_type == BT_AVDTP_ACCEPT) {
		DISCOVER_REQ(req)->buf = buf;//net_buf_ref(buf);
	} else {
		DISCOVER_REQ(req)->buf = NULL;
		//buf = NULL;
	}

	bt_avdtp_clear_req(session);

	if (req->func != NULL) {
		req->func(req);
	}

	//if (buf) {
		//net_buf_unref(buf);
	//}
```

2025-02-19 12:37 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +	avdtp_set_status(req, buf, msg_type);
> I have one query, is the `net_buf_ref` needed from your viewpoint?

It depends what you want to do. If you want to retain the original ref, then you need to use ref() as part of copying the pointer. However, if you *don't* need the original ref, then you can just move it to the req, however then the right thing to do would be to set the original pointer to NULL right after the move. In some ways it'd be nice if we had this helper function in the net_buf API, but until then you just need to do it yourself:

```c
struct net_buf *net_buf_move(struct net_buf **buf)
{
	struct net_buf *moved;

	moved = *buf;
	*buf = NULL;

	return moved;
}
```

and then your code would be doing:

```c
DISCOVER_REQ(req)->buf = net_buf_move(&buf);
```

> Without ref and unref, we can reduce codes.

Reference counted objects, and doing reference counting correctly, is a really common source of programming errors. Having a clear concept of who owns which reference, when references are moved, and following consistent patterns in code to reflect these things, is the best way to avoid such bugs.

2025-02-19 15:15 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +	avdtp_set_status(req, buf, msg_type);
Thank very mchu for the explanation. I updated it to use the `move`.

2025-02-19 15:37 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +		GET_CAP_REQ(req)->buf = NULL;
Aren't you missing a `net_buf_unref(buf);` in this branch? Seems like you are, and then you can move the `buf = NULL;` to be a single common step after both branches.

2025-02-19 15:37 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
>  	}
Same here.

2025-02-20 03:52 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +		GET_CAP_REQ(req)->buf = NULL;
The `buf` comes from the l2cap through the L2CAP `recv` callback `bt_avdtp_l2cap_recv`. avdtp doesn't ref the `buf`, so I think avdtp doesn't need to unref it too.
I change the `req->func(req)` callback function to pass the `buf` as one parameter not give the `buf` to another variable, so I think the `ref/unref` is not needed. please see the last commit in the pr.

2025-02-20 13:20 UTC, jhedberg commented on subsys/bluetooth/host/classic/avdtp.c
> +		GET_CAP_REQ(req)->buf = NULL;
Then this function doesn't own the ref, and if you don't own the ref then you can't move it either. In that case the only thing the function needs to do is a `ref()` as part of assigning to the `req`.

2025-02-20 13:25 UTC, MarkWangChinese commented on subsys/bluetooth/host/classic/avdtp.c
> +		GET_CAP_REQ(req)->buf = NULL;
I have changed the codes, there is no assigning `buf` to the `req` now. I pass the `buf` as parameter that has similar behavior like the L2CAP callback.

2025-02-20 18:57 UTC, jhedberg approved these changes

2025-02-21 01:20 UTC, lylezhu2012 approved these changes

2025-03-07 18:45 UTC, merged