boards: st: fix partition size
zephyrproject-rtos/zephyr pull request #83385
Opened 2024-12-25 18:22 UTC by arifbalik

Fixed wrong partitions size as described in #83329

2024-12-25 18:43 UTC, kartben requested changes
Please update commit message to not reference an issue but instead have a description that's "self-contained"
https://docs.zephyrproject.org/latest/contribute/guidelines.html#adding-links

2024-12-26 05:24 UTC, kartben approved these changes

2024-12-26 08:52 UTC, marwaiehm-st approved these changes

2024-12-27 11:39 UTC, FRASTM approved these changes
thanks for fixing

2025-01-06 16:37 UTC, erwango approved these changes

2025-01-06 17:13 UTC, merged

2025-01-06 21:35 UTC, besteinm commented
Many thanks for fixing!