Bluetooth: Controller: Add NRF_CCM support in nRF54L15 SoC
zephyrproject-rtos/zephyr pull request #83394
Opened 2024-12-26 10:01 UTC by cvinayak

Add NRF_CCM h/w based encryption support in nRF54L15 SoCs.

2025-01-06 11:13 UTC, aescolar reviewed
Thanks @cvinayak, (a relatively quick review given the PR size)
one relevant comment (the one about removing the sim hal files) and otherwise just some suggestions

2025-01-06 11:13 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c
> -uint32_t radio_is_tx_done(void)
It would be nice if this revert commit elaborated on why it is doing the revert, specially as the next commit reverts the revert :)

2025-01-06 11:13 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c
> +	radio_tmr_hcto_configure_abs(hcto);
Silly comment: quite a few very similar 1 line commits :)

2025-01-06 15:58 UTC, aescolar requested changes

2025-01-06 15:58 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h
I see.
But this change is making me very uneasy.
* we are testing in CI only each target against itself, so it can be easy to mask an error. (AFAIR Demant was testing its target against the nrf52 also, so their internal CI would be likely to detect an issue here @wopu-ot @thoh-ot could you guys spin this PR thru your tests?)
* In this PR we are changing quite a lot of timings, so it is not trivial to see if something went a bit/a lot bad due to the hal file merge. It would be much nicer to decouple a change like this into another PR (also in case we need to revert)
* The majority of timing differences are sub µs. But some of them are >5µs. That includes the S2 coded with differences of 10µs in the rampup time and 5µs in the Rx chain delay. But I tend to recall we are not testing S2 in CI(?)
I would sleep much better if we did not do this merge in this PR.

2025-01-07 08:06 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h
> simulation specific incorrect timings with respect to actual target values is removed.

The timing constants in the hal files for the simulation targets are based on the actual timings of the HW models which are in turn mostly based on what the spec said at the time. These hal timings are not incorrect as they reflect the timing of the models.
While, I understand, the timings for the real target hal files were based on measurements of those targets.
Meaning, those hal files timing differences actually reflect different targets' timings. Now we could argue the models should match those measurements from real target instead of the whatever the spec said, but that is another discussion that would require changing the models timings and not just these hal files.

> The removed incorrect values in simulation specific file are contained in a single commit: https://github.com/zephyrproject-rtos/zephyr/commit/063b50a75ec8c194a818eb8de31ae03d8a68afa8

Yes, but the very next commit (89f32146083cf508b898287e94b3fb063220a40c) changes what is expected from the hal files, so it is not like that commit can be just reverted without doing quite a few other changes.

Could you please not do this change in this PR?

2025-01-07 11:09 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h
All this is skeptical that bsim testing is green (https://github.com/zephyrproject-rtos/zephyr/actions/runs/12604177426/job/35130591570?pr=83394) with the real target hal files, makes me wonder if the results are all false positive, or the timings constant just the similar values but in redundant simulation hal files... hmmm!

Ok, i can revert back and add the files back for your satisfaction, but I will need a new nrf54L15 simulation hal files so that at least the file structure/includes are consistent (today, there is no simulation hal for nRF54L upstream).

2025-01-17 14:55 UTC, aescolar approved these changes
+1

2025-01-17 14:55 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf54l.h
This would not be required in this PR as this was already the case, but this timings are off for simulation as the simulated radio has the exact same timings for all SOCs so far,
If you want you can pick this commit already into this PR to correct the values
https://github.com/aescolar/zephyr/commit/ed78e93055dd603d3398ef6ff09441b8aa5ff627
Otherwise I can send a follow up PR with it.

2025-01-17 15:00 UTC, cvinayak commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf54l.h
Follow up PR is good. Should your  RNG PR go in first or this one? I am ok with either.

2025-01-17 15:05 UTC, aescolar commented on subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf54l.h
Im fine either way. You are welcome to +1 the RNG PR if you think it is good :)

2025-01-18 08:24 UTC, jhedberg approved these changes

2025-01-18 09:03 UTC, merged