tests: posix: fs: correct arguments to readdir_r()
zephyrproject-rtos/zephyr pull request #83395
Opened 2024-12-26 10:33 UTC by cfriedt

* correct arguments to `readdir_r()` in `tests/posix/fs/src/test_fs_dir.c`
* move `struct posix_fs_desc` to `fs_priv.h`
* move `POSIX_FILE_SYSTEM_R` code to `file_system_r.c` and separate Kconfig

2024-12-31 01:43 UTC, m0sf3tz commented on lib/posix/options/file_system_r.c
> +	strncpy(entry->d_name, de.name, MIN(sizeof(entry->d_name), sizeof(de.name)));
Should this be `MIN(sizeof(entry->d_name), sizeof(de.name) **- 1**)` or something? we want to leave space to always place a NULL termination no?

2024-12-31 15:42 UTC, ycsin approved these changes
LGTM

2025-01-01 15:53 UTC, nandojve requested changes
Just a small fix to match the commit message.

2025-01-01 15:53 UTC, nandojve commented on tests/posix/fs/prj.conf
> +CONFIG_ZTEST_STACK_SIZE=2048
You say 1-4k but you are in fact increasing to 2k

2025-01-01 16:54 UTC, cfriedt commented on tests/posix/fs/prj.conf
> +CONFIG_ZTEST_STACK_SIZE=2048
Fixed (the commit message)

2025-01-01 16:56 UTC, ycsin approved these changes

2025-01-01 16:57 UTC, nandojve approved these changes

2025-01-02 05:54 UTC, kartben approved these changes

2025-01-02 08:18 UTC, kartben commented on lib/posix/options/Kconfig.file_system_r
> +	  For more informnation, please see
```suggestion
	  For more information, please see
```

On my phone but I'm guessing there might be other occurrences elsewhere, so fixing as a follow-up is fine

2025-01-02 08:18 UTC, merged