net: http_server: serve resources only for the specific services they are registered to
zephyrproject-rtos/zephyr pull request #83473
Opened 2024-12-31 15:04 UTC by mrodgers-witekio

Currently the mechanism of defining resources for each specific HTTP service using `HTTP_RESOURCE_DEFINE` doesn't seem to work as intended, since `get_resource_detail` iterates over all services and resources. This means that a resource defined for one service will actually be served for any service.

Perhaps the easiest way to demonstrate this is to comment out the following line in the HTTP server sample so that the resource is defined only for the HTTPS service and not the HTTP one:

```
// HTTP_RESOURCE_DEFINE(uptime_resource, test_http_service, "/uptime", &uptime_resource_detail);
```

The result is that a curl request to either http://192.0.2.1/uptime or https://192.0.2.1/uptime returns the uptime, while it should give a 404 response over http.

This PR ensures that resources are only served to a client connected on a service that the resource was registered against, based on the server fd used to accept the client connection. This could be useful for e.g. serving certain resources only over HTTPS, not over unencrypted HTTP.

2025-01-02 12:00 UTC, rlubos approved these changes
Looks good, nice finding!

2025-01-02 13:27 UTC, jukkar requested changes
I am currently on vacation and would like to review properly by the end of next week. So marking it so in order to avoid accidental merge.

2025-01-09 08:50 UTC, jukkar commented on include/zephyr/net/http/service.h
> +	int *fd;
Instead of a pointer, could we use here the fd directly, so why not `int fd`?

2025-01-09 08:50 UTC, jukkar commented on include/zephyr/net/http/service.h
> +		.fd = &_name##_fd,                                                                 \
We could set initial value here if using int
```
.fd = -1,
```

2025-01-09 12:22 UTC, jukkar approved these changes

2025-01-09 13:13 UTC, merged