drivers: flash: w25qxxdv: Add configuration options for delay and device ID
zephyrproject-rtos/zephyr pull request #8477
Opened 2018-06-19 14:42 UTC by lairdjm

Adds support for configuring the CS toggling delay and using a
different device ID so that compatible flash chips can also be
used by this driver.

Signed-off-by: Jamie McCrae <jamie.mccrae@lairdtech.com>

2018-06-19 14:43 UTC, lairdjm commented
Have tested with a Nordic nRF52832 MCU connected to a non-winbond SPI memory chip and was able to communicate successfully.

2018-06-19 16:26 UTC, tbursztyka requested changes
your commit title is too long also

2018-06-22 08:18 UTC, lairdjm commented
@tbursztyka Have updated the push request to resolve these issus

2018-06-22 08:42 UTC, tbursztyka approved these changes

2018-06-22 16:27 UTC, merged