USB DMA
zephyrproject-rtos/zephyr pull request #852
Opened 2017-07-19 21:47 UTC by andyross

Time to stop fiddling with this and cut bait.  It works as well as the existing FIFO workaround now, with hardware bugs under the same conditions (one-byte packets).  I can't see anything that breaks in existing usage.  The interrupt ordering mess is documented in code to the extent I can and "works" for all the cases I can find to test (even though it can't in the general case).  Pointers for future work to address shortcomings are documented in the commit message and that giant comment.

2017-07-19 22:40 UTC, jfischer-phytec-iot commented on drivers/usb/device/Kconfig
> +	which the transferred data must be copied.  The USB framework
The same with Kinetis USBFSOTG #542 , I've made the buffers configurable, but I'm not that happy. Maybe we can find better solution later.

2017-07-19 22:45 UTC, jfischer-phytec-iot commented
Please change the heading to something like: 
drivers: usb: add DMA for DesignWare usb device driver

2017-08-24 10:30 UTC, nashif commented
@andyross I am not getting an ACM device when building samples/subsys/usb/cdc_acm with this patch set, how did you test this?

2017-09-20 13:15 UTC, finikorg reviewed
We should not enable DMA mode by default

2017-09-20 13:15 UTC, finikorg commented on drivers/usb/device/Kconfig
> +	help
This patch breaks my USB application (yet to be submitted), IMO this should not be enabled by default

2017-09-21 13:01 UTC, nashif requested changes
breaks usb on arduino 101, needs to be rebased probably.

2018-05-28 20:55 UTC, nashif commented
outdated, closing. Reopen with updates/rebase if needed.

2018-05-28 20:55 UTC, closed without merging