spim_nrf52: Fixes
zephyrproject-rtos/zephyr pull request #858
Opened 2017-07-20 08:40 UTC by vaussard

Here are two fixes for the SPIM driver of the NRF52.

- The first patch fixes a bug that prevents using a speed of 8 MHz due to a missing "break"
- The second patch fixes a glitch issue when configuring the CS line

2017-07-26 19:12 UTC, tyrantlizard77 reviewed
switch statement case is very clear.
maybe a bit more detail in the commit message about why moving the _csn call fixes the other problem for you.

2017-07-27 03:50 UTC, cvinayak requested changes

2017-07-27 03:50 UTC, cvinayak commented on drivers/spi/spim_nrf52.c
> +			spim_nrf52_csn(data->gpio_port, config->psel.ss[i],
Please revert to setting GPIO config prior to SPIM selection, but use a correct pullup/pulldown setting.

Refer to how it is for UART... https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/serial/uart_nrf5.c#L205

The reason is, all peripherals in nRF5 when configured will internally grab the GPIO and place the GPIO line in required state by that protocol. This is the reason why moving gpio_pin_configure after spim csn call solves your problem, as gpio configure has no effect after spim has grabbed the line. When the peripheral is powered down or SoC enters system off, GPIO configuration is reverted back to (requiring correct pullup/pulldown to be set).

2017-07-28 08:04 UTC, vaussard commented on drivers/spi/spim_nrf52.c
> +			spim_nrf52_csn(data->gpio_port, config->psel.ss[i],
The CS line is never claimed by the SPIM, it is used as a regular GPIO only. See spim_nrf52_csn().
Anyway I updated to use a pull-up as this also fixes the glitch seen on the oscilloscope. But beware that this solution will use slightly more power when toggling CS low as it must drive the additional pull-up.

2017-07-31 09:43 UTC, carlescufi requested changes
There seem to be a lot of unrelated commits in this PR. Is this because we are merging into the arm branch? @galak can you confirm?

2017-07-31 10:38 UTC, vaussard commented
Oh sorry, I should have rebased on zephyr/arm. I will do it ASAP.

2017-07-31 10:39 UTC, vaussard commented
Looks better.

2017-07-31 10:55 UTC, carlescufi approved these changes

2017-07-31 11:00 UTC, cvinayak approved these changes

2017-07-31 14:43 UTC, galak approved these changes

2017-07-31 14:43 UTC, merged