Fix parsing of IPv6 HBHO message
zephyrproject-rtos/zephyr pull request #8582
Opened 2018-06-27 11:20 UTC by rveerama1

2018-06-27 11:52 UTC, jukkar requested changes

2018-06-27 11:52 UTC, jukkar commented on include/net/net_pkt.h
>  	};
Typo in commit message of "net: ipv6: Fix HBHO parsing options function"

s/parsing is failed/parsing fails/
s/declared as/is declared as/

The "PAD1 contains only one byte which is 0." looks confusing, could we say here "PAD1 contains only one byte which has value 0."

2018-06-27 11:52 UTC, jukkar commented on subsys/net/ip/ipv6.c
> +			net_pkt_set_ipv6_ext_len(pkt, length);
As there can be multiple extension headers, we need to accumulate the total length here.

2018-06-27 11:52 UTC, jukkar commented on samples/net/echo_server/src/common.h
Typos in commit message of "samples: net: echo_server: Fix handling of large IPv6 header"

s/single buffer net_buf_pull/single buffer then net_buf_pull/
s/and pull of the header/and pull the header/

The last sentence needs clarification, perhaps something like "After this, the packet payload can be copied correctly when replying messages."

2018-06-27 11:52 UTC, jukkar commented on samples/net/echo_server/src/echo-server.c
> +
Remove extra empty line

2018-06-27 11:52 UTC, jukkar commented on samples/net/echo_server/src/echo-server.c
> +		NET_DBG("pull of header %d", header_len);
This will print too much information as debugging is enabled by default. Thus this print can be removed.

2018-06-27 11:52 UTC, jukkar commented on samples/net/echo_server/src/echo-server.c
> +		pull_of_header(pkt, header_len);
The "of" looks redundant information, what about just calling this "pull_header()" instead.

2018-06-27 12:33 UTC, rveerama1 commented
I have noticed other issues also. I am working on it.

2018-07-20 14:03 UTC, jukkar approved these changes
LGTM

2018-07-23 12:01 UTC, merged