IP APIs sanity
zephyrproject-rtos/zephyr pull request #8635
Opened 2018-06-29 09:14 UTC by tbursztyka

2018-06-29 09:16 UTC, tbursztyka commented
@ozhuraki These patches are doing what you attempted in #8561 
As you did, _raw should disappear but also the context based functions should go in net_context.c

(Well I have to fix the mld test, will do that)

2018-06-29 09:30 UTC, tbursztyka commented on subsys/net/ip/tcp.c
> +		return net_ipv6_finalize(pkt,
Hum, I mixed up ipv6 changes in ipv4 patch...

2018-06-29 11:02 UTC, jukkar requested changes

2018-06-29 11:02 UTC, jukkar commented on subsys/net/ip/net_context.c
> +		src = &ipv4->unicast[0].address.in_addr;
We should change this to use the net_if_ipv4_select_src_addr() that was introduced recently.

2018-06-29 14:43 UTC, pfalcon approved these changes
This is definitely a step in the right direction.

2018-07-02 09:33 UTC, jukkar approved these changes

2018-07-02 09:34 UTC, merged