STM32F723 support
zephyrproject-rtos/zephyr pull request #8649
Opened 2018-06-29 15:37 UTC by aurel32

This patch series adds support for the STM32F723 SoC, including basic support for the STM32F723E-DISCO board.

2018-06-30 12:34 UTC, ydamigos requested changes
LGTM. Some comments need to be fixed.

2018-06-30 12:34 UTC, ydamigos commented on boards/arm/stm32f723e_disco/Kconfig.board
> +# Kconfig - STM32F746G Discovery board configuration
STM32F723E?

2018-06-30 12:34 UTC, ydamigos commented on boards/arm/stm32f723e_disco/pinmux.c
> +/* pin assignments for STM32F746G-DISCO board */
STM32F723E Discovery?

2018-06-30 12:34 UTC, ydamigos commented on boards/arm/stm32f723e_disco/pinmux.c
> +#endif	/* CONFIG_UART_STM32_PORT_1 */
CONFIG_UART_STM32_PORT_2?

2018-07-01 16:13 UTC, aurel32 commented
@ydamigos, thanks for the review and for finding some leftover in the comments. I have just pushed a new version.

2018-07-02 08:30 UTC, erwango approved these changes

2018-07-02 10:10 UTC, ydamigos approved these changes

2018-07-03 18:14 UTC, dbkinder approved these changes
docs LGTM, thanks.

2018-07-03 18:53 UTC, merged