dts: stm32f7-pinctrl Add definitions for F7 USART/UARTs
zephyrproject-rtos/zephyr pull request #8665
Opened 2018-07-01 13:49 UTC by therealprof

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

2018-07-02 08:37 UTC, erwango requested changes
One comment otherwise sounds good.
Then please add a one liner comment in the commit message.

2018-07-02 08:37 UTC, erwango commented on dts/arm/st/stm32f7-pinctrl.dtsi
> +					rx = <STM32_PIN_PE6 (STM32_PINMUX_ALT_FUNC_8 | STM32_PUPDR_NO_PULL)>;
STM32_PIN_PF6

2018-07-02 10:37 UTC, therealprof commented
@erwango Done, thanks for the review.

2018-07-04 06:48 UTC, therealprof commented
@erwango Would you mind re-checking whether everything is to your satisfaction, please?

2018-07-04 07:04 UTC, erwango approved these changes

2018-07-04 07:12 UTC, ydamigos approved these changes

2018-07-05 16:24 UTC, merged