drivers: entropy: stm32: add support for STM32F7
zephyrproject-rtos/zephyr pull request #8666
Opened 2018-07-01 16:20 UTC by aurel32

All the STM32F7 SoCs have a TRNG. Adding support for it is just a matter
of tweaking the #ifdef and including the right file from HAL.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

2018-07-02 08:44 UTC, erwango requested changes
One minor update
Then, I have 2 comments:
- Have you been able to test with `tests/drivers/entropy`?
- Can you update help section for  `ENTROPY_STM32_RNG` flag and mention It is available for F4 (except STM32F401), L4 and F7 series.

Thanks!

2018-07-02 08:44 UTC, erwango commented on drivers/entropy/entropy_stm32.c
>  #error RNG only available on STM32F4 and STM32L4 series
Could you update  the error message?

2018-07-02 20:02 UTC, aurel32 commented
Thanks @erwango for the review, I have done the changes you requested. I am confident it works fine, I am using it in a project for a few weeks. I have launched `tests/drivers/entropy` anyway on an STM32F723E-DISCO board, and the test passes:

```
***** Booting Zephyr OS v1.12.0-438-gd20b8bd30 *****
Running test suite entropy_api
===================================================================
starting test - test_entropy_get_entropy
random device is 0x2000127c, name is ENTROPY_0
  0xeb
  0x12
  0xf5
  0x91
  0x9c
  0xc3
  0x4b
  0xcd
  0x2b
PASS - test_entropy_get_entropy
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

2018-07-03 07:10 UTC, erwango approved these changes

2018-07-03 07:20 UTC, ydamigos approved these changes
Looks good. Please consider updating the help section for ENTROPY_STM32_RNG flag with the exception of STM32F411 for the F4 series.

2018-07-03 07:20 UTC, ydamigos commented on drivers/entropy/Kconfig.stm32
> +	  F4 (except STM32F401), L4 and F7 series.
It is also not available on STM32F411 SoCs according to the driver.

2018-07-03 17:27 UTC, galak approved these changes

2018-07-04 02:48 UTC, merged