net: icmpv4: Simplify the flow at net_icmpv4_get_hdr()
zephyrproject-rtos/zephyr pull request #8676
Opened 2018-07-02 11:25 UTC by ozhuraki

Minor simplification here, no need to trigger 3 reads here,
net_frag_read() will do the same inside itself.

Signed-off-by: Oleg Zhurakivskyy <oleg.zhurakivskyy@intel.com>

2018-07-02 11:35 UTC, jukkar requested changes
The refactoring is missing the fast path here. Typically in 99% of the cases the net_icmp_header_fits() returns true in which case we do not need to do the reading. Thus I do not see much point in this refactoring.

2018-07-02 12:42 UTC, tbursztyka commented
Actually this patch makes totally sense.

net_pkt_icmp_data() isn't faster if the header fits into the frag already, here is the call trace:

```
net_pkt_icmp_data -> net_pkt_get_pos -> net_frag_skip -> net_frag_read
```

(with tests on frag validity, length..)

Where here, it would just do give:

```
net_frag_read directly.
```

And if it does not fit, it will anyway go to net_frag_read.

2018-07-02 12:42 UTC, tbursztyka approved these changes

2018-07-02 12:42 UTC, tbursztyka requested changes

2018-07-02 12:42 UTC, tbursztyka commented on subsys/net/ip/icmpv4.c
> +	u16_t pos = 0;
you need to start at pos net_pkt_ip_hdr_len(pkt)

2018-07-02 13:29 UTC, tbursztyka commented
@ozhuraki you could do the same for net_icmpv4_set_hdr() btw

2018-07-03 12:24 UTC, tbursztyka approved these changes

2018-07-03 12:37 UTC, jukkar approved these changes
LGTM

2018-07-03 12:38 UTC, merged

2018-07-03 13:09 UTC, pfalcon commented
@jukkar : So, what happened with you claim about fast path handling in this PR?

2018-07-03 19:00 UTC, pfalcon commented
> My claim was for earlier version of the PR where it called more heavier net_pkt_frag*() function always. Calling net_pkt_linearize() is quite elegant now.

And yet the fast path you were talking about is now gone, as net_pkt_linearize() uses memcpy().

The issue here is that we have the same pattern (if a header fits within frag, return ptr, otherwise make copy) in many other places. So, this PR sets an important precedent of getting rid of it. I think it's especially important to draw attention to that in the light of what @tbursztyka was talking today at the forum meeting (code cleanup). Myself, I'm split in feelings re: this "fast path" pattern. On one hand, I love optimizations. On the other hand, this adds branches to bunch of functions, and I'm sure that non-fastpath case isn't covered by the tests we have.