net: l2: update wifi mgmt to adapt non-offload wifi chip.
zephyrproject-rtos/zephyr pull request #8703
Opened 2018-07-03 08:45 UTC by easonxiang

The wifi mgmt does only support TCP/IP offload wifi chip,
while non-offload wifi chip can not scan/connect to AP.

Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>

2018-07-03 09:22 UTC, tbursztyka requested changes
NACK on that. This does not make any sense from design point of view.

Non offloaded WiFi chip will not implement wifi mgmt interface at all. That thould be into wifi_mgmt.c part, as it will be generic.

But, so far, I haven't heard anything about a native WiFi stack going into Zephyr.

2018-07-03 10:20 UTC, easonxiang commented
@tbursztyka Yes, you are right, Wi-Fi stack is always implemented by Wi-Fi firmware, including our chip.

However, I think it possible that Wi-Fi stack(scan/connect/security, etc.) is offload, but TCP/IP stack(listen/bind/connect, etc) is non offload. That's why I commit this patch.

In this patch, We need to confirm if it is necessary to check iface->if_dev->offload when scan/connect. Because iface->if_dev->offload is point to  TCP/IP offload API.

2018-07-03 11:29 UTC, tbursztyka commented
> However, I think it possible that Wi-Fi stack(scan/connect/security, etc.) is offload, but TCP/IP stack(listen/bind/connect, etc) is non offload. That's why I commit this patch.

Still, no rename is needed: net_wifi_mgmt_offload means you are offloading the net_wifi_mgmt only. It's already fully separated from struct net_offload.

2018-07-03 11:49 UTC, easonxiang commented
That's right, update the patch without rename modification.

Just remove the unneeded checkpoint.

2018-07-06 03:01 UTC, easonxiang commented
This is a real problem I am facing now. I did not set net_offload in struct net_if_dev, as we don't need offload TCP/IP stack. If iface->if_dev->offload is NULL, we can't call off_api->scan at all.

I don't know if I have misunderstanding for the network and wifi management on Zephyr system.

Do you have some suggestion for fix this problem?

Thank you!

2018-10-10 07:32 UTC, tbursztyka approved these changes

2018-10-10 08:30 UTC, pfalcon approved these changes
+1 from me too. I was too shy to approve without @tbursztyka's review, as I'm not familiar enough with that area, but I assume that e.g. WiFi chips offering an "Ethernet emulation" + additional WiFi specific control operations should be a common thing.

2018-10-10 08:35 UTC, jukkar approved these changes

2018-10-10 08:37 UTC, jukkar commented
Thanks @easonxiang and sorry that this review took so long time. You can always ping the persons doing the review if the patches do not seem to move forward, sometimes these PRs just get lost in the queue.

2018-10-10 08:38 UTC, merged