dts: stm32: uart clocks
zephyrproject-rtos/zephyr pull request #873
Opened 2017-07-21 14:51 UTC by erwango

Provide rcc node to stm32 based socs.
Use rcc node to provide clock information on STM32 u(s)art nodes

2017-07-21 14:54 UTC, galak requested changes
Some cleanup on enum / defines, but otherwise looks fine.

2017-07-21 14:54 UTC, galak commented on dts/arm/st/clocks.h
> +#ifdef CONFIG_SOC_SERIES_STM32L4X
remove the #ifdef here.

2017-07-21 14:54 UTC, galak commented on include/drivers/clock_control/stm32_clock_control.h
remove this enum, and just the defines from dts/arm/st/clocks.h.

2017-07-21 14:54 UTC, galak commented on dts/arm/st/stm32f103Xb.dtsi
> +			label = "STM32_CLOCK";
is the label here for code generation purposes?  If so how about STM32_CLK_RCC

2017-07-21 15:00 UTC, galak commented on dts/arm/yaml/st,stm32-rcc.yaml
> +  - bus
is this correct, should we have:

- phandle
- bus
- bits

?

2017-07-21 16:56 UTC, ydamigos commented on dts/common/yaml/uart.yaml
> +      type: array
Do you mean "interrupt-names"?
The interrupt-names property consists of a list of strings so the "stringlist" should be used here.

2017-07-21 19:18 UTC, erwango commented on dts/arm/st/stm32f103Xb.dtsi
> +			label = "STM32_CLOCK";
arbitrary choice, STM32_CLK_RCC is ok

2017-07-21 19:20 UTC, erwango commented on dts/arm/yaml/st,stm32-rcc.yaml
> +  - bus
I can have a try but I don't know if script will handle it.
It's a bit picky with clocks node (I'll fw you a mail about that)

2017-07-21 19:22 UTC, erwango commented on dts/common/yaml/uart.yaml
> +      type: array
Indeed, thanks!

2017-07-21 19:37 UTC, erwango commented on include/drivers/clock_control/stm32_clock_control.h
I'm able to #include <cloks.h>
I think it'd be better to #include <dts/arm/st/clocks.h>, but I can't get it work
Any idea how I could do that?

2017-07-21 19:42 UTC, erwango commented on dts/arm/yaml/st,stm32-rcc.yaml
> +  - bus
seems to work, let's go

2017-07-21 19:52 UTC, erwango commented on include/drivers/clock_control/stm32_clock_control.h
So best I could do is #include <arm/st/clocks.h>
I'll change the plan and #include <dt_stm32_clocks.h>

2017-07-24 12:38 UTC, ydamigos commented
According to linux device tree bindings for "st,stm32-rcc" (http://elixir.free-electrons.com/linux/v4.13-rc2/source/Documentation/devicetree/bindings/clock/st,stm32-rcc.txt):

> - #clock-cells: 2, device nodes should specify the clock in their "clocks"
>   property, containing a phandle to the clock device node, an index selecting
>   between gated clocks and other clocks and an index specifying the clock to
> use.

@erwango Do we plan to follow linux DT bindings for clocks or use something different for Zephyr?

2017-07-24 13:19 UTC, erwango commented
@ydamigos : Thanks for raising this question.
Long term plan is indeed to converge with Linux DT (not "converge to" Linux DT), but we don't want this to block zephyr short term objectives/progress, and hence I'd like to  be able to derogate when needed.

There are several reasons to that:
1-Using Linux bindings may require to either rework zephyr driver either to have binding not reflecting
zephyr implementation of being over complicated vs zephyr driver need. 
For instance on rcc node, Linux biding is the output of a complex driver (clock gating, ability to have clock per IP, ..) which is not in line with the current rcc driver on Zephyr. Having same bindings on Zephyr would be nice but would not reflect current Zephyr RCC driver.

2-"Linux time" is different from "Zephyr time", they have their own objectives and plan. Linux STM32 device tree is not frozen and evolutions are on-going. Given Linux upstream process, it can take time and may require several reworks (hence months), before we know on what we should align on.

3-Zephyr will have more stm32 dts files than Linux. If we want to have a dts collection of files coherent from {zephyr, Linux, ..} global point of view, Linux dts will have to accept choices that might not be
coherent from single Linux point of view.

This being said, if there are options to get things closer to Linux, or more coherent from global point of view, while keeping things simple in zephyr and not preventing us to progress at our expected pace, we should use them.

2017-07-24 16:40 UTC, galak requested changes
Some minor nits and how we access the includes

2017-07-24 16:40 UTC, galak commented on dts/arm/Makefile
> +ZEPHYRINCLUDE += -I$(srctree)/dts/arm/st
Can we not just include via:

#include <dts/arm/st/dt_stm32_clocks.h>

2017-07-24 16:40 UTC, galak commented on dts/arm/st/dt_stm32_clocks.h
> +/*
any reason not to just name this stm32_clocks.h (related to how we include it)

2017-07-24 16:40 UTC, galak commented on dts/arm/st/dt_stm32_clocks.h
> +#define	STM32_CLOCK_BUS_APB1_2  4
some odd whitespace issue, guessing a tab after define

2017-07-24 16:40 UTC, galak commented on include/drivers/clock_control/stm32_clock_control.h
> +#include <dt_stm32_clocks.h>
lets include this via #include <dts/arm/st/dt_stm32_clocks.h>

2017-07-24 16:45 UTC, erwango commented on dts/arm/Makefile
> +ZEPHYRINCLUDE += -I$(srctree)/dts/arm/st
I had a try but didn't work. Maybe I was not lucid anymore but is there any subtlety to achieve this?
I guess #include "dts/arm/st/dt_stm32_clocks.h" would be more likely to work

2017-07-24 16:45 UTC, erwango commented on dts/arm/st/dt_stm32_clocks.h
> +/*
Indeed I added dt_ to compensate the missing path

2017-07-25 12:53 UTC, erwango commented
@galak: Are you good with new version?

2017-07-25 14:08 UTC, galak approved these changes

2017-07-25 14:30 UTC, merged