boards: Add stm32f407g-disc1 Discovery devboard support
zephyrproject-rtos/zephyr pull request #8853
Opened 2018-07-11 13:08 UTC by finikorg

Add support for stm32f407g-disc1 board, this is mofified version of
stm32f4_disco board.

Fixes: #8810

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

2018-07-11 17:34 UTC, ydamigos requested changes
Looks good. Some minor comments regarding copyright and board name in comments.

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/Kconfig.board
> +# Kconfig - STM32F4DISCOVERY board configuration
STM32F407G-DISC1?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/Kconfig.board
> +# Copyright (c) 2016 Linaro Limited.
Shouldn't this be 2018, Intel Corporation?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/Kconfig.defconfig
> +# Kconfig - STM32F4DISCOVERY board configuration
STM32F407G-DISC1?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/Kconfig.defconfig
> +# Copyright (c) 2016 Linaro Limited.
2018, Intel Corporation?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/board.h
> + * Copyright (c) 2016 Linaro Limited.
2018, Intel Corporation?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/pinmux.c
> + * Copyright (c) 2016 Linaro Limited.
2018, Intel Corporation?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/stm32f407g_disc1.dts
> + * Copyright (c) 2017 Linaro Limited
2018, Intel Corporation?

2018-07-11 17:34 UTC, ydamigos commented on boards/arm/stm32f407g_disc1/stm32f407g_disc1.yaml
> +  - pwm
You could add gpio, pwm and usb_device.

2018-07-11 20:28 UTC, dbkinder requested changes
looks good, just a couple of formatting fixes

2018-07-11 20:28 UTC, dbkinder commented on boards/arm/stm32f407g_disc1/doc/stm32f407g_disc1.rst
> +       - `STM32F407VG on www.st.com`_
add a blank line before this bullet list, and don't indent the items:

    More information about STM32F407VG can be found here:

    - `STM32F407VG on www.st.com`_
    - `STM32F407 reference manual`_

2018-07-11 20:28 UTC, dbkinder commented on boards/arm/stm32f407g_disc1/doc/stm32f407g_disc1.rst
> +
delete the blank line and the leading spaces before  the filename

    The default configuration can be found in the defconfig file:
    ``boards/arm/stm32f407g_disc1/stm32f407g_disc1_defconfig``

2018-07-12 08:03 UTC, finikorg commented
@ydamigos @dbkinder Updated PR.

2018-07-12 08:36 UTC, ydamigos approved these changes
Looks good.

2018-07-17 08:03 UTC, finikorg commented
@dbkinder Could you recheck?

2018-07-31 13:57 UTC, erwango commented
Thanks for this work, but I wonder if we should introduce different board revisions as new boards.
Ideal would be to support various board revisions for a board.
I raised an issue once (https://github.com/zephyrproject-rtos/zephyr/issues/4315), it might be good to do this instead

2018-11-12 10:49 UTC, erwango requested changes
@finikorg , let's merge this PR has I have no other option to propose for now, and technically both boards revisions have their own reference

One comment though:
Remove board.h

2018-11-12 10:49 UTC, erwango commented on boards/arm/stm32f407g_disc1/stm32f407g_disc1_defconfig
> +CONFIG_PWM=y
Remove this line

2018-11-12 13:14 UTC, erwango commented
@dbkinder , can you review again?

2018-11-12 13:14 UTC, erwango approved these changes

2018-11-12 20:45 UTC, dbkinder approved these changes
doc changes LGTM, thanks.

2018-11-23 14:17 UTC, nashif requested changes

2018-11-23 14:17 UTC, nashif commented on boards/arm/stm32f407g_disc1/stm32f407g_disc1_defconfig
> +CONFIG_STM32_ARM_MPU_ENABLE=y
you need to remove this, it is not defined anywhere

2018-11-26 09:16 UTC, closed without merging