samples: zephyr_sizeofs: Print sizes of various structures used by Zephyr
zephyrproject-rtos/zephyr pull request #8962
Opened 2018-07-17 09:48 UTC by pfalcon

This sample app prints sizeof() of various structures and types used
by Zephyr kernel and libs, and thus offers a convinient way to assess
Zephyr's memory efficiency and usage.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

2018-07-17 09:50 UTC, pfalcon commented
Questions "what's the size of structure X" pop up randomly (e.g. https://github.com/zephyrproject-rtos/zephyr/pull/8905#discussion_r202932829) and it's a bit boring to go and patch some app to do printk(sizeof()) at the start. So, some time ago I hacked up a sample which does just that, and now even submit it as a PR.

2018-07-18 20:12 UTC, andrewboie commented
> it's a bit boring to go and patch some app to do printk(sizeof()) at the start.

You can just open any kernel .elf in GDB and print the sizeof there since the size of all data structures is in the debug info.

For example:
```
(gdb) p sizeof(struct k_thread)
$1 = 140
```

2018-07-19 16:12 UTC, pfalcon commented
> You can just open any kernel .elf in GDB and print the sizeof 

Thanks, that's a nice lifehack, but probably not as convenient to print a bunch of sizeofs at once.

2018-07-20 17:52 UTC, tyrantlizard77 requested changes
> Thanks, that's a nice lifehack, but probably not as convenient to print a bunch of sizeofs at once.

Actually, I think it's the only correct way to do it.
The size of various kernel objects is directly tied to the kernel configuration. you might notice that the structures you are printing out have members conditional on ifdefs's, arrays sized by kconfig, etc.

So any numbers printed here are only accurate for the platform and kernel configuration used to build this sample, another application with a different config the sizes can be very different.

2018-07-20 20:16 UTC, pfalcon commented
> The size of various kernel objects is directly tied to the kernel configuration.

Yes, so interested party can adjust prj.conf, and see how that affects structure sizes, en masse - even if that party doesn't know intricacies of gdb usage.

So, please be more direct - if you don't think that such a sample should be in the mainline, please say so.

2018-07-25 02:35 UTC, nashif commented
> Thanks, that's a nice lifehack, but probably not as convenient to print a bunch of sizeofs at once.

write a gdb macro.

2018-07-25 02:48 UTC, nashif commented
or use pahole:

```
i9:hello_world(master): pahole outdir/qemu_x86/zephyr/zephyr.elf -C k_queue
struct k_queue {
	sys_sflist_t               data_q;               /*     0     8 */
	union {
		_wait_q_t          wait_q;               /*          16 */
	};                                               /*     8    16 */

	/* size: 24, cachelines: 1, members: 2 */
	/* last cacheline: 24 bytes */
};
```

2018-08-07 21:49 UTC, closed without merging