Add a generic SPI NOR flash driver instead of the specific w25qxxdv driver
zephyrproject-rtos/zephyr pull request #9078
Opened 2018-07-23 18:04 UTC by sbourdelin

Implement a new generic SPI NOR flash driver using the CFI (Common Flash Interface) and the JEDEC ID to address all SPI NOR flash.
This driver is heavily based on the previous w25qxxdv, with few enhancements and a flash id table which contains the geometry for few SPI NOR flash.

2018-08-15 05:26 UTC, sbourdelin commented
@nashif ping?

2018-08-15 10:53 UTC, vanwinkeljan commented
Looks to me that there is already more generic SPI NOR driver pull request #7561 (which is based on pr #5456). PR #7561 relies on the SFDP information present in the flash device instead of adding the data hard coded into a struct for every device.

Is till see a use case for this driver if the parameters where passed from dts or kconfig as this would reduce the code size compared to auto detection at run time.

2018-11-05 14:32 UTC, tbursztyka requested changes
As noticed in #10988, having a patch that enables dts would be nice and avoid the Kconfig option about SPI settings.

2018-11-05 14:32 UTC, tbursztyka commented on drivers/flash/spi_nor.c
> +	{ "W25Q80",     JEDEC_ID(0xef4014), SZ_256, SZ_4K, SZ_256, SZ_64K, BLOCK_ERASE_32K | BLOCK_ERASE_64K },
80 chars limit (why checkpatch has not noticed it?)

2018-11-05 14:32 UTC, tbursztyka commented on drivers/flash/spi_nor.c
> + * @brief Write data to the flash
You don't need to repeat the documentation which is the same as flash API. So remove it for write, read, etc...

2018-11-05 14:32 UTC, tbursztyka commented on drivers/flash/spi_nor.c
> +
move all the above to the spi_nor.h header file

2018-11-05 14:32 UTC, tbursztyka commented on drivers/flash/spi_nor.c
> +#define spi_nor_cmd_read(dev, opcode, dest, length) \
add an empty line here. I'd rather use inlines, but that's fine

2018-11-05 14:32 UTC, tbursztyka commented on drivers/flash/spi_nor.c
> +static inline int spi_nor_wait_until_ready(struct device *dev)
no need to make it inline I think

2018-11-13 23:49 UTC, nashif commented
merged in another PR #10988,

2018-11-13 23:49 UTC, closed without merging

2018-11-14 02:49 UTC, sbourdelin commented
Sorry for the delay.
Thanks for the review and the merge in the PR #10988

Regards,
Sébastien.