ext: tinycrypt: Update revision
zephyrproject-rtos/zephyr pull request #9127
Opened 2018-07-25 23:33 UTC by ceolin

Update tinycrypt to latest revision, two commits after 0.2.8 release.

These commits are only bug fixes and one of them is fixing incorrect
buffer size in decryption with CBC mode.

This algorithm is being used by tinycrypt shim and is tested in samples/drivers/crypto/.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

2018-07-26 17:13 UTC, lpereira approved these changes
If these came from upstream, LGTM.  However, I would try asking them to release a new version before merging this patch as it's easier to reference it in the README file and release notes.  (If no new tinycrypt version can be released prior to Zephyr 1.13 being released, this patch is fine as it is.)

2018-07-27 21:51 UTC, ceolin commented
I've added fixes for the tests too.   tests/crypto/cbc_mode/src/cbc_mode.c was wrong even before tinycrypt fix.

2018-07-30 16:33 UTC, ceolin commented
@lpereira  I've asked in the mailing list about a new release, lets see what they say. If it takes time, I think it's better merge it and then update with the release tag later.

2018-08-01 18:44 UTC, pswarnak commented
recheck

2018-08-01 18:52 UTC, tyrantlizard77 approved these changes

2018-08-01 18:55 UTC, pswarnak requested changes
Please update the commit message line to not exceed max length as per guideline.

2018-08-01 18:56 UTC, pswarnak requested changes
Looks like your 'Signed-Off-by' line got wrongly updated. Please change it from "Signed-by:" to "Signed-off-by:" in commit 085a5cc7c34625bf43461810737cffe1dd9e7f19.

2018-08-01 18:57 UTC, pswarnak commented
Overall code changes look good to me. Thanks.

2018-08-02 00:12 UTC, ceolin commented
@pswarnak  fixed. Thank you

2018-08-02 07:00 UTC, pswarnak approved these changes

2018-08-02 07:00 UTC, pswarnak approved these changes

2018-08-02 07:01 UTC, pswarnak approved these changes

2018-08-02 17:18 UTC, carlescufi approved these changes

2018-08-02 17:18 UTC, merged