Bluetooth: Fix storing name in plain text
zephyrproject-rtos/zephyr pull request #9208
Opened 2018-08-01 10:12 UTC by Vudentz

Settings consider the character space the end of the value, so instead
encode the name using settings_str_from_bytes and restore it with
settings_bytes_from_str.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

2018-08-01 10:14 UTC, jhedberg requested changes

2018-08-01 10:14 UTC, jhedberg commented on subsys/bluetooth/host/settings.c
>  		bt_dev.name[sizeof(bt_dev.name) - 1] = '\0';
Shouldn't this be `bt_dev.name[len] = '\0';`?

2018-08-01 10:22 UTC, jhedberg approved these changes

2018-08-01 21:02 UTC, cvinayak approved these changes

2018-08-02 17:16 UTC, carlescufi approved these changes

2018-08-02 17:16 UTC, merged