arch: arc: reserve the place for errno in thread stack
zephyrproject-rtos/zephyr pull request #9264
Opened 2018-08-03 08:06 UTC by vonhust

modify the setting to stack check to reserve the place for
errno in thread stack, avoid the stack check exception caused
by the access to errno which is in the unallocated area of stack

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

Fixes #9067

The bug is introduced in kernel: fix errno access for user mode (commit 7f4d006).

For ARC' stack check, Non-%SP based memory references may not reference the unallocated stack region, so the access to errno will raise stack check exception.

2018-08-03 11:12 UTC, ruuddw requested changes
Adjusting the stack bounds checking is a good solution, it protects overwriting errno by stack overflow as well.
Please double check if errno_location requires updating for the dynamic user/kernel stack optimization (merge privilege stack into stack if started in kernel mode).

2018-08-03 11:12 UTC, ruuddw commented on arch/arc/core/thread.c
> +		thread->arch.k_stack_top = (u32_t)pStackMem + 4;
Should errno_location be updated here since it's in the guard space (if MPU stack guards would be used)?

2018-08-03 11:12 UTC, ruuddw commented on arch/arc/core/thread.c
> +	_current->errno_location = (int *)_current->stack_info.start;
Required? Isn't errno_location already initialized in the generic kernel/thread.c ?

2018-08-03 11:18 UTC, ruuddw commented
@andrewboie : adjusting HW stack bounds checking to exclude the 'thread local' errno location seems a solution for the "downside of this approach is potential stack corruption" in commit 7f4d006. Something to do for other arches as well?

2018-08-13 14:58 UTC, andrewboie commented
This appears to work but I think it's a better solution to move the storage area to the other end of the stack.

2018-08-14 08:57 UTC, ruuddw commented
> This appears to work but I think it's a better solution to move the storage area to the other end of the stack.

I'm fine with that solution as well, we can drop this PR when that's done - stack allocation/sizing/protection is complex enough already without this.

2018-08-23 08:53 UTC, ruuddw commented
Fixed in a different way by #9458.

2018-08-23 08:53 UTC, closed without merging