drivers: watchdog: nrfx: Migrate to new logging subsys
zephyrproject-rtos/zephyr pull request #9367
Opened 2018-08-09 13:46 UTC by Olivier-ProGlove

Migrate from `SYS_LOG` to `LOG` logging mechanism.

Signed-off-by: Olivier Martin <olivier.martin@proglove.de>

2018-08-14 06:52 UTC, ioannisg approved these changes
LGTM. 
I would rename commit title prefix to
drivers: watchdog: nrf: 
(nrf: is used for Nordic SOC-related patches, AFAICS)

2018-08-14 07:00 UTC, ydamigos commented on drivers/watchdog/wdt_nrfx.c
>  #define SYS_LOG_LEVEL CONFIG_SYS_LOG_WDT_LEVEL
I opened similar PRs for stm32 I2C (#9385) and usb (#9384) drivers. I had to change this line to make it work with the new LOG subsys. Did it work without changing this line?

2018-08-14 07:04 UTC, anangl commented
@ioannisg The commit title is okay as it is. This is a shim using the nrfx driver underneath, so it is perfectly fine to use the "nrfx:" prefix. Such prefix would be inappropriate for a commit changing something related to Nordic SoCs but not using the nrfx driver package.

2018-08-14 10:49 UTC, ydamigos commented
@Olivier-ProGlove CONFIG_SYS_LOG_WDT_LEVEL depends on `SYS_LOG`. In order to work with the new `LOG` subsys you need to edit Kconfig file and change it to:
`depends on SYS_LOG || LOG`

2018-08-14 12:17 UTC, Olivier-ProGlove commented
@ydamigos I have updated the pull-request to migrate all watchdog drivers to `LOG`

2018-08-17 16:10 UTC, Olivier-ProGlove commented
I have rebased the pull-request to fix the conflict after this pull-request has been merged https://github.com/zephyrproject-rtos/zephyr/commit/8cf8db3a73aa0658d728006e93d9ef5e0361a1b2

2018-09-12 14:24 UTC, galak requested changes
Can you fix this for the change in LOG_MODULE_REGISTER to take the name as a param, and remove LOG_MODULE_NAME

2018-09-17 21:19 UTC, nashif commented
cherrypicked in #10029

2018-09-18 08:58 UTC, Olivier-ProGlove commented
@nashif That's a better cherry-pick compared to https://github.com/zephyrproject-rtos/zephyr/pull/9429#issuecomment-422175587 :+1:

2018-10-08 21:50 UTC, nashif commented
addressed in #10029

2018-10-08 21:50 UTC, closed without merging