boards: riscv: Convert HiFive1 to DTS
zephyrproject-rtos/zephyr pull request #9375
Opened 2018-08-10 03:26 UTC by palmer-dabbelt

Adds DTS bindings for sifive,pwm0, sifive,uart0, sifive,spi0, and
riscv,plic0.

Signed-off-by: Nathaniel Graff <nathaniel.graff@sifive.com>
Signed-off-by: Palmer Dabbelt <palmer@sifive.com>

2018-08-10 03:26 UTC, palmer-dabbelt commented
https://github.com/zephyrproject-rtos/zephyr/pull/9195

2018-08-13 19:28 UTC, galak commented on boards/riscv32/hifive1/hifive1.dts
> +	current-speed = <115200>;
status = "ok";

2018-08-13 19:30 UTC, galak commented on dts/riscv32/riscv32-fe310.dtsi
> +/ {
Need status properties on the peripheral nodes.  The typical pattern is that peripherals are status = "disabled" by default, and the board.dts explicitly enables. them with a status = "ok".

2018-08-13 19:31 UTC, galak requested changes
Some minor dts updates related to use of status property.

2018-08-13 23:33 UTC, galak commented on dts/riscv32/riscv32-fe310.dtsi
> +/ {
No interrupt controllers are typically always enabled, so we don't bother with status on them.  Its more things that have external pin/signals that would be board/application specific.  While interrupts can obviously fall in that group, its almost always the case that at least one internal interrupt ends being needed.

2018-08-13 23:35 UTC, galak approved these changes

2018-08-13 23:35 UTC, merged