drivers: grove: Modify light sensor
zephyrproject-rtos/zephyr pull request #9434
Opened 2018-08-15 04:12 UTC by punitvara

Replace old ADC apis with new ones.

Signed-off-by: Punit Vara <punit.vara@intel.com>

2018-08-20 06:05 UTC, punitvara commented on drivers/grove/light_sensor.c
> +#if CONFIG(ARG)
Sorry for Typo. I meant to add parameters needed to pass for ARC architecture to make this sensor work.

2018-08-21 12:34 UTC, nashif requested changes

2018-08-21 12:34 UTC, nashif commented on drivers/grove/light_sensor.c
> +#if defined(CONFIG_ARC)
I do not see much difference here, just 1 entry?
Make the ifdef apply on to that different entry and avoid duplicating all other elements.

checking for architecture here (CONFIG_ARC) is wrong, you should be checking for the specific driver being used, an ARC system can have different drivers other than designware.

2018-08-21 12:42 UTC, nashif commented
also, building this fails, how did you build and test this change?

```
/home/nashif/Work/github/zephyr/drivers/grove/light_sensor.c: In function ‘gls_init’:
/home/nashif/Work/github/zephyr/drivers/grove/light_sensor.c:77:47: error: assignment of member ‘extra_samplings’ in read-only object
  drv_data->adc_table.options->extra_samplings = 0;
                                               ^
/home/nashif/Work/github/zephyr/drivers/grove/light_sensor.c:78:43: error: assignment of member ‘interval_us’ in read-only object
  drv_data->adc_table.options->interval_us = 12;
                                           ^
/home/nashif/Work/github/zephyr/drivers/grove/light_sensor.c:79:35: error: ‘ADC_RESOLUTION’ undeclared (first use in this function)
  drv_data->adc_table.resolution = ADC_RESOLUTION;
                                   ^~~~~~~~~~~~~~
/home/nashif/Work/github/zephyr/drivers/grove/light_sensor.c:79:35: note: each undeclared identifier is reported only once for each function it appears in
```

(note: this is built on top of your other PR changing the DW driver)

2018-08-23 05:22 UTC, closed without merging