dt-bindings: pinctrl: fix stm32 pin configuration comments
zephyrproject-rtos/zephyr pull request #949
Opened 2017-07-28 14:03 UTC by erwango

STM32 pin configuration comments where offset by 4 bits.
Fix this issue and make pin configuration settings
easier to read.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

2017-07-28 14:37 UTC, mbolivar requested changes
Just a couple of nitpicks.

2017-07-28 14:37 UTC, mbolivar commented on include/dt-bindings/pinctrl/stm32-pinctrl.h
> +/* Usefull definitions */
Typo, "useful"

2017-07-28 14:37 UTC, mbolivar commented on include/dt-bindings/pinctrl/stm32-pinctrl.h
> -/* Alternate functions numbers*/
Does deleting STM32_FUNC_ALT_x belong in a separate patch?

2017-07-28 19:20 UTC, erwango commented on include/dt-bindings/pinctrl/stm32-pinctrl.h
> -/* Alternate functions numbers*/
Actually, I just moved them up into /* Alternate functions numbers */ section for coherency

2017-07-28 19:26 UTC, erwango commented on include/dt-bindings/pinctrl/stm32-pinctrl.h
> +/* Usefull definitions */
Thanks, corrected

2017-07-28 20:04 UTC, mbolivar commented on include/dt-bindings/pinctrl/stm32-pinctrl.h
> -/* Alternate functions numbers*/
Ah, right you are. Thanks.

2017-07-28 20:04 UTC, mbolivar approved these changes
LGTM

2017-07-31 14:20 UTC, galak approved these changes

2017-07-31 14:20 UTC, merged