cmake: Set new CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_MACROS
zephyrproject-rtos/zephyr pull request #9528
Opened 2018-08-20 10:24 UTC by ibisz

Set a new CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_MACROS to
add pre-processor definitions from autoconf.h. This feature allows for eclipse
graying out sections.

The CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake is
pached in _DETERMINE_GCC_SYSTEM_INCLUDE_DIRS. The C compiler command is called
additionally, with "-imacros ${CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_MACROS}"
argument to extend the standard C compiler macro definitions with
definitions from autoconf.h file.

The following patch is applied to the CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake
from CMake installation directory:
```
@@ -23,14 +23,36 @@ macro(_DETERMINE_GCC_SYSTEM_INCLUDE_DIRS _lang _resultIncludeDirs _resultDefines
     if (CMAKE_CXX_FLAGS MATCHES "(-std=[^ ]+)")
       set(_stdver "${CMAKE_MATCH_1}")
     endif ()
+    if (CMAKE_EXTRA_GENERATOR_CXX_SYSTEM_INCLUDE_MACROS)
+      message(STATUS "*CXX -imacros*")
+      execute_process(COMMAND ${_compilerExecutable} -imacros ${CMAKE_EXTRA_GENERATOR_CXX_SYSTEM_INCLUDE_MACROS} ${_arg1} ${_stdver} ${_stdlib} -v -E -x ${_lang} -dD dummy
+                      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles
+                      ERROR_VARIABLE _gccOutput
+                      OUTPUT_VARIABLE _gccStdout )
+    else ()
+      message(STATUS "*CXX*")
+      execute_process(COMMAND ${_compilerExecutable} ${_arg1} ${_stdver} ${_stdlib} -v -E -x ${_lang} -dD dummy
+                      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles
+                      ERROR_VARIABLE _gccOutput
+                      OUTPUT_VARIABLE _gccStdout )
+    endif ()
   else ()
     set(_compilerExecutable "${CMAKE_C_COMPILER}")
     set(_arg1 "${CMAKE_C_COMPILER_ARG1}")
+    if (CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_MACROS)
+      message(STATUS "*C -imacros*")
+      execute_process(COMMAND ${_compilerExecutable} -imacros ${CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_MACROS} ${_arg1} ${_stdver} ${_stdlib} -v -E -x ${_lang} -dD dummy
+                      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles
+                      ERROR_VARIABLE _gccOutput
+                      OUTPUT_VARIABLE _gccStdout )
+    else ()
+      message(STATUS "*C*")
+      execute_process(COMMAND ${_compilerExecutable} ${_arg1} ${_stdver} ${_stdlib} -v -E -x ${_lang} -dD dummy
+                      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles
+                      ERROR_VARIABLE _gccOutput
+                      OUTPUT_VARIABLE _gccStdout )
+    endif ()
   endif ()
-  execute_process(COMMAND ${_compilerExecutable} ${_arg1} ${_stdver} ${_stdlib} -v -E -x ${_lang} -dD dummy
-                  WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/CMakeFiles
-                  ERROR_VARIABLE _gccOutput
-                  OUTPUT_VARIABLE _gccStdout )
   file(REMOVE "${CMAKE_BINARY_DIR}/CMakeFiles/dummy")
 
   # First find the system include dirs:
```
The second patch is a fix applied to the CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake
from CMake installation directory too. The defines with value 0 erronously are replaced with value ' '. 
```
@@ -66,10 +88,10 @@ macro(_DETERMINE_GCC_SYSTEM_INCLUDE_DIRS _lang _resultIncludeDirs _resultDefines
     #message(STATUS "m1: -${CMAKE_MATCH_1}- m2: -${CMAKE_MATCH_2}- m3: -${CMAKE_MATCH_3}-")
 
     list(APPEND ${_resultDefines} "${_name}")
-    if(_value)
-      list(APPEND ${_resultDefines} "${_value}")
-    else()
+    if ("${_value}" STREQUAL "")
       list(APPEND ${_resultDefines} " ")
+    else()
+      list(APPEND ${_resultDefines} "${_value}")
     endif()
   endforeach()
```
Signed-off-by: Istvan Bisz istvan.bisz@t-online.hu

2018-08-20 10:40 UTC, SebastianBoe requested changes
Do you intend to upstream the patches to 'CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake' ?

2018-08-20 11:55 UTC, ibisz commented
@SebastianBoe 
No, the first intention is to share my findings regarding the eclipse integration.
Maybe someone with a better connections/skill can do it, if it is considered useful.
In any case these changes make my life easier in this environment.

2018-08-20 12:04 UTC, SebastianBoe commented
It is a goal to support IDE's better out-of-the-box and having IDE's understand "-include" statements is a part of this.

It is also interesting that patching 'CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake' can help the IDE's that use dedicated generators.

But we can't ask users to patch their CMake installation. So this approach must be blocked until we find a cleaner solution.

Alternatives that we might consider:

- Drop the '-include' flag as proposed in #7216.
- Fork and distribute CMake.
- Upstream the patch to CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake.

2018-08-20 12:04 UTC, closed without merging

2018-08-20 12:34 UTC, ibisz commented
OK, it's clear.
I considered it useful for the community.
Maybe the fix can be up streamed.
In any case, until a useful solution, I will use it in my environments.

2018-08-28 08:43 UTC, ibisz commented
Upstreamed the fix patch to CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs.cmake
```
Extra Generator: Fix extraction of macros with value 0
 
Fix logic in CMakeExtraGeneratorDetermineCompilerMacrosAndIncludeDirs to handle macros with value 0.

In .cproject with "Eclipse CDT4 - Ninja" generator the macros with 0 value are converted erroneusly with value=" " For ex.:
<pathentry kind="mac" name="__ATOMIC_RELAXED" path="" value=" "/>
correct is:
<pathentry kind="mac" name="__ATOMIC_RELAXED" path="" value="0"/>
Topic-rename: extra-gen-fix-0
```
and the merged answer: 
```
Re: CMake | Extra Generator: Fix extraction of macros with value 0 (!2308)

Merge Request !2308 was merged 
```
Regarding the first patch a reworked PR is under elaboration.