cmsis_rtos_v1: add semaphore negative tests, replace an else case
zephyrproject-rtos/zephyr pull request #9548
Opened 2018-08-21 09:16 UTC by nniranjhana

Added couple of negative tests for osSemaphoreWait
and osSemaphoreRelease to increase code coverage.

Replaced an else if case in osSemaphoreWait with else
to account for both EBUSY and EAGAIN return values
from k_sem_take. The return value would be 0 for
osSemaphoreWait in both cases.

2018-08-21 09:53 UTC, rgundi requested changes

2018-08-21 09:53 UTC, rgundi commented on lib/cmsis_rtos_v1/cmsis_semaphore.c
remove the below return statement as that'll not be executed now.

2018-08-21 09:53 UTC, rgundi commented on tests/cmsis_rtos_v1/src/semaphore.c
> +
Please modify the statement above to make it similar to the below statements. Also, change the comment to indicate this is a testcase with 0 timeout.

2018-08-23 06:04 UTC, nniranjhana commented
Hi @rgundi addressed your review comments, thanks

2018-08-23 08:50 UTC, rgundi approved these changes
LGTM

2018-08-26 15:56 UTC, nashif approved these changes

2018-08-26 15:56 UTC, merged