Arm: Handle time slicing before context swicth on exception.
zephyrproject-rtos/zephyr pull request #976
Opened 2017-08-02 06:08 UTC by youvedeep

Currently Thread time slice is getting reset at end of timer
interrupt. Due to which equal priority threads behind current thread
in ready_q are not getting chance to run and leading to starvation.

This patch handles time slice in _ExcExit section context switch is
required.

Jira: ZEP-2444

Signed-off-by: Youvedeep Singh <youvedeep.singh@intel.com>
Signed-off-by: Ramesh Thomas <ramesh.thomas@intel.com>

2017-08-03 02:26 UTC, ramesh-thomas approved these changes

2017-08-03 10:46 UTC, nashif submitted a review, later dismissed

2017-08-03 15:47 UTC, tyrantlizard77 submitted a review, later dismissed

2017-08-03 16:07 UTC, galak requested changes
If we are making this change than _IntExit and _ExcExit are the same, so we should remove one.  Also, seems wrong that this code is now only enabled if CONFIG_PREEMPT_ENABLED is y.

2017-08-03 16:15 UTC, galak commented
Also in the commit message, would like an explanation of what the implication to cortex_m_systick.c that calls _ExcExit() in a few places and why its ok that it now calls _IntExit

2017-08-03 18:02 UTC, nashif commented
> Also, seems wrong that this code is now only enabled if CONFIG_PREEMPT_ENABLED is y.

Time slicing is only available in preemptive mode

2017-08-04 06:17 UTC, youvedeep commented
Hi @galak 

Few Clarifications 
1. At the end of systick :  ExecExit is called. (it does not call IntExit).
2. At the end of "nrf RTC timer" (on nrf51/52) :   IntExit() is called. (as it is registered as interrupt in nrf platform).
Earlier update "_time_slice_before_swap()" was called unconditionally at the exit of each Interrupt (as per of IntExit()), this was leading to thread time slice reset. Due to which current executing thread was not giving chance to other threads with same priority level to run.


With this fix,  "update_time_slice_before_swap()" is getting called only when context switch is needed (when _Current and _ready_q.cache are not same). 

Also as @nashif  mentioned time-slice is applicable only in case preemption is enabled.

2017-08-04 13:17 UTC, galak commented
With this change _IntExit and _ExecExit have effectively the same entry point, so call one is just like calling the other.  Thus my comment about removing one of them (I would think _ExecExit).

2017-08-07 04:50 UTC, youvedeep commented
Hi @galak 

I got your point, As both ExcExit and IntExit are doing exactly same tasks.
So basically your suggestion is to replace_ExcExit with _IntExit, something Like 
diff --git a/arch/arm/core/cortex_m/nmi.c b/arch/arm/core/cortex_m/nmi.c
index 37dd169..ef7be0a 100644
--- a/arch/arm/core/cortex_m/nmi.c
+++ b/arch/arm/core/cortex_m/nmi.c
@@ -91,5 +91,6 @@ void _NmiHandlerSet(void (*pHandler)(void))
 void __nmi(void)
 {
        handler();
-       _ExcExit();
+       _IntExit();
 }



But i was avoiding this for 2 reasons
1. These separate Handler Exit points (ExcExit and IntExit) was added from starting itself before Tickless kernel patches were merged. Even in Zephyr v1.7 when both ExcExit and IntExit were doing exactly same task still these were 2 separate entries.
2. Keeping both Exit separate (ExcExit and IntExit) makes code logically clean, if required we can put some code which may be different for both.

2017-08-07 17:40 UTC, pfalcon commented
Typo in commit message:

> context swicth on exception. 

(should be "switch")

2017-08-08 13:33 UTC, nashif approved these changes

2017-08-08 13:33 UTC, merged