arch: stm32: gpio: give ability to set open-drain on pins
zephyrproject-rtos/zephyr pull request #9834
Opened 2018-09-06 17:16 UTC by psidhu

If user wants to configure different pin drive strengths for STM32
soc's, configure the pin to be open-drain.

2018-09-12 11:45 UTC, erwango commented
@psidhu , please get CI passed so we can start the review.

2018-10-03 18:15 UTC, psidhu commented
@erwango done.

2018-10-08 09:58 UTC, erwango requested changes
One question (see comments) and one querry:
Since you're familiar with this piece of code now, can you factorize it into `drivers/gpio/gpio_stm32.c` (at least this function for now). I don't think there is a good reason to have this code duplicated across various stm32 series. Would be great. Thanks

2018-10-08 09:58 UTC, erwango commented on soc/arm/st_stm32/stm32f0/soc_gpio.c
> +		if (ds_low == GPIO_DS_ALT_LOW ||
I missing something here.
Can you explain why DS_ALT_LOW is equivalent to DS_DISCONNECT_HIGH and not DISCONNECT_LOW here?

2018-10-08 15:56 UTC, psidhu commented
@erwango I need to rework this patch anyways. Should we wait for the outcome of https://github.com/zephyrproject-rtos/zephyr/issues/10339 first?

2018-10-08 16:03 UTC, erwango commented
> @erwango I need to rework this patch anyways. Should we wait for the outcome of #10339 first?

Might be wiser indeed.

2019-04-26 22:00 UTC, psidhu commented
Closing this in lieu of https://github.com/zephyrproject-rtos/zephyr/pull/13190.

2019-04-26 22:00 UTC, closed without merging