MS5837 pressure sensor
zephyrproject-rtos/zephyr pull request #9887
Opened 2018-09-10 21:52 UTC by vanwinkeljan

Added sensor driver for MS5837 pressure sensor

2018-09-11 17:22 UTC, dbkinder requested changes
Small change to the intro, otherwise looks good. Thanks!

2018-09-11 17:22 UTC, dbkinder commented on samples/sensor/ms5837/README.rst
> +Sample application that every 10 seconds retrieves the pressure and temperature
This should be a complete sentence, so how about:

    This sample application retrieves the pressure and temperature
    from a MS5837 sensor every 10 seconds, and prints this
    information to the UART console.

2018-09-14 16:25 UTC, dbkinder approved these changes
+1 for docs, thanks.

2018-09-18 19:15 UTC, vanwinkeljan commented
DTS bindings are missing, I will add them

2018-09-19 20:01 UTC, MaureenHelm requested changes

2018-09-19 20:01 UTC, MaureenHelm commented on samples/sensor/ms5837/src/main.c
> +	struct device *dev = device_get_binding("MS5837");
Don't hardcode the string, get the label from device tree instead.

2018-09-20 18:43 UTC, vanwinkeljan commented on drivers/sensor/ms5837/ms5837.c
> +	err = i2c_write(i2c_master, &cmd, 1, MS5837_ADDR);
To trigger a conversion on the MS5837 only a single byte command should be issued and as such i2c_reg_write_byte can not be used as it transfers 2 bytes (reg address + value).

2018-09-20 19:18 UTC, vanwinkeljan commented on drivers/sensor/ms5837/ms5837.c
> +	err = i2c_write(data->i2c_master, &cmd, 1, MS5837_ADDR);
Reset is a single byte command i2c_reg_write_byte is a 2 byte transfer (reg + value)

2018-09-21 14:06 UTC, MaureenHelm commented on drivers/sensor/ms5837/ms5837.c
> +	err = i2c_write(data->i2c_master, &cmd, 1, MS5837_ADDR);
Ok

2018-10-08 17:48 UTC, vanwinkeljan commented on drivers/sensor/ms5837/ms5837.c
> +	data->temperature_conv_delay = 1;
Added set attribute function to the driver as these are configurable parameters

2018-10-09 13:06 UTC, MaureenHelm requested changes

2018-10-09 13:06 UTC, MaureenHelm commented on drivers/sensor/ms5837/ms5837.c
> +const struct ms5837_config ms5837_config = {
This should be static too

2018-10-09 13:06 UTC, MaureenHelm commented on drivers/sensor/ms5837/ms5837.c
> +int ms5837_init(struct device *dev)
Make this static

2018-10-09 13:06 UTC, MaureenHelm commented on dts/bindings/sensor/te,ms5837.yaml
> +      constraint: "te,ms5837"
Let's make this `meas,ms5837` to be consistent with the linux kernel

2018-10-09 13:06 UTC, MaureenHelm commented on samples/sensor/ms5837/dts_fixup.h
> +#if defined(CONFIG_HAS_DTS_I2C)
Add a license/copyright header

2018-10-09 13:06 UTC, MaureenHelm commented on samples/sensor/ms5837/nrf52840_pca10056.overlay
> +&i2c1 {
Add a license/copyright header

2018-10-09 20:47 UTC, vanwinkeljan commented on drivers/sensor/ms5837/ms5837.c
> +	 * (https://tinyurl.com/y9eu4c9t) section PRESSURE AND TEMPERATURE
add url to landing page for ms5837 as url is of reasonable length

2018-10-12 19:28 UTC, MaureenHelm approved these changes

2018-10-12 19:28 UTC, merged